- config/orca.m4
- configure
- depends/conanfile_orca.txt
- gpAux/releng/releng.mk
The corresponding ORCA PR is https://github.com/greenplum-db/gporca/pull/607
> Bump ORCA version to 3.113

- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- src/backend/commands/tablecmds.c
- src/test/regress/expected/expand_table.out
> [6X backport] Allow gpexpand to expand materialized view

- src/backend/utils/adt/genfile.c
- src/backend/utils/error/elog.c
- src/backend/utils/misc/guc.c
> Remove several pg12 merge fixmes 

- src/backend/commands/indexcmds.c
Appendoptimized tables need block directory relation for index access. Creating
and maintaining a block directory is expensive. We delay the block directory
creation until it is really needed - the first index creation. Once created,
all indexes share the same block directory. We need a stronger lock
(ShareRowExclusiveLock) if the block directory needs to be created. If the
block directory already exists, we can use the same lock as heap tables.
> Level down the lock of creating indexes on AO tables if blkdir exists

- src/backend/gporca/README.format.md
We included some rough steps in 57b744c19a394c46. This patch updates
those with a higher level of details so that it's hopefully easier to
follow in a step-by-step fashion.
> Update Instructions for formatting in-flight PR's

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
add optimizer_cost_model to the guc reference.
will be backported to 6x and 5x.
> docs - document the optimizer_cost_model guc

- src/backend/commands/analyze.c
- src/backend/commands/analyzeutils.c
- src/test/regress/expected/incremental_analyze.out
- src/test/regress/expected/incremental_analyze_optimizer.out
- src/test/regress/sql/incremental_analyze.sql
The analyze routine for partitioned table is based on merging statistics from its child tables. And building routines for MCV and histogram bounds collections explicitly use the default_statistics_target value as the number of slots for these structures ignoring the similar higher priority column-wise setting assigned via ALTER TABLE ... ALTER COLUMN ... SET STATISTICS ... statement.
Besides of main fix of upper function calls (`aggregate_leaf_partition_MCVs` and `aggregate_leaf_partition_histograms`) there was fixed the definition of upper bound of minimal frequency (expressed in terms of estimated count of rows having target value of attribute) for MCV values gotten from partitions. Also I have made light refactoring into that routine.
```sql
-- create partitioned table with 2 …
```
> Enable for partitioned tables to use column-wise statistics setting

- src/backend/utils/adt/dbsize.c
Error out if this kind of functions runs on entry DB, so
user will not confuse with the generated wrong results.
(cherry picked from commit ca90fb093c0e4c9f968427a4512f8e33882df5ec)
> [5X Backport]Some functions do dispatch so they should not execute on entry db.

- gpdb-doc/dita/admin_guide/load/load.ditamap
- gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
- gpdb-doc/dita/analytics/overview.xml
- gpdb-doc/dita/install_guide/platform-requirements.xml
- gpdb-doc/dita/install_guide/upgrading.xml
- gpdb-doc/dita/utility_guide/utility-programs.xml
- gpdb-doc/dita/utility_guide/utility_guide.ditamap
> docs - update some cross references

- gpMgmt/bin/gpload_test/gpload2/TEST.py
gpload test case 60 leads to test fail, deleting it for now
> fix master pipeline gpload fail

- gpdb-doc/dita/ref_guide/modules/adv_passwd_check.xml
- gpdb-doc/dita/ref_guide/modules/intro.xml
- gpdb-doc/dita/ref_guide/modules/modules.ditamap
add some docs about the advanced password check module.
doc review site link:  http://docs-lisa-gp-advpwdchk.cfapps.io/7-0/ref_guide/modules/adv_passwd_check.html
> docs - add info about the advanced password check module

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
add info about this config param to the guc reference.
doc review site link:  http://docs-lisa-gp-oeios.cfapps.io/6-13/ref_guide/config_params/guc-list.html#optimizer_enable_dml
> docs - add content for the optimizer_enable_indexonlyscan guc

- gpdb-doc/dita/admin_guide/load/load.ditamap
- gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
misc edits to load page and subnav
> docs - add a new load option

- src/backend/cdb/cdbgroup.c
- src/backend/cdb/cdbpath.c
- src/backend/optimizer/README
- src/backend/optimizer/path/equivclass.c
- src/backend/optimizer/path/joinpath.c
- src/backend/optimizer/path/pathkeys.c
- src/backend/optimizer/plan/initsplan.c
- src/backend/optimizer/prep/prepunion.c
- src/include/optimizer/paths.h
- src/test/regress/expected/bfv_aggregate.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
- src/test/regress/expected/with.out
- src/test/regress/sql/bfv_aggregate.sql
- src/test/regress/sql/with.sql
> [5X Backport] Fix "could not find pathkey item to sort" for subquery join

- src/backend/storage/file/buffile.c
Function 'ZSTD_initCStream' may fail due to out of memory, ignore the return
value could lead to an error later 'Context should be init first'.
> [6X backport] Check the return value of 'ZSTD_initCStream'

- src/backend/optimizer/path/joinpath.c
> Fix GPDB_12_MERGE_FIXME in try_partial_mergejoin_path()

- src/backend/optimizer/plan/createplan.c
In GPDB, it's possible that the Unique plan node created in
create_unique_plan() is the topmost plan node, and the topmost plan node's
targetlist is required to be consistent with the original targetlist, to avoid
the assertion failure in apply_tlist_labeling(). So we need to change its
targetlist back if it has been changed.
In PostgreSQL, we don't have this same problem, because there would always be a
join node above the Unique plan node created here, which is projection capable.
> Remove GPDB_12_MERGE_FIXME in create_unique_plan()

- gpMgmt/doc/gpinitstandby_help
Add --hba-hostnames to gpinitstandby help
> Add --hba-hostnames to gpinitstandby help

- src/backend/cdb/cdbdtxrecovery.c
- src/backend/postmaster/pgstat.c
- src/include/pgstat.h
> Add a new WaitEventIPC for the dtx recovery progress.

- concourse/pipelines/gpdb_6X_STABLE-generated.yml
- concourse/pipelines/templates/gpdb-tpl.yml
- gpAux/platform/gpnetbench/gpnetbenchClient.c
- gpAux/platform/gpnetbench/gpnetbenchServer.c
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Add ipv6 support for gpcheckperf
> [6X backport]: Add ipv6 support for gpcheckperf

- concourse/pipelines/templates/gpdb-tpl.yml
- gpAux/platform/gpnetbench/gpnetbenchClient.c
- gpAux/platform/gpnetbench/gpnetbenchServer.c
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
> [5x backport]: add support for ipv6

- src/backend/gporca/libgpopt/include/gpopt/base/CConstraint.h
- src/backend/gporca/libgpopt/src/base/CConstraint.cpp
- src/backend/gporca/libgpopt/src/base/CConstraintConjunction.cpp
- src/backend/gporca/libgpopt/src/base/CConstraintDisjunction.cpp
- src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
- src/backend/gporca/libgpopt/src/base/CConstraintNegation.cpp
- src/backend/gporca/libgpopt/src/base/CDrvdPropRelational.cpp
- src/backend/gporca/libgpopt/src/engine/CEngine.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionUtils.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/search/CJobGroupExpressionOptimization.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformLeftSemiApplyWithExternalCorrs2InnerJoin.cpp
- src/backend/gporca/libgpos/include/gpos/memory/CCacheEntry.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/IStatistics.h
- src/backend/gporca/server/src/unittest/CTestUtils.cpp
These are little patches I've kept while working on converting our usages of reference counting, but they can stand on their own and be merged without depending on the (much larger) effort. See each commit message for details.
> [ORCA] Assorted little clean ups

- src/backend/gporca/data/dxl/minidump/DPE-with-unsupported-pred.mdp
- src/backend/gporca/data/dxl/minidump/ExtractPredicateFromDisj.mdp
- src/backend/gporca/data/dxl/minidump/IndexApply-ForPartialIndex.mdp
- src/backend/gporca/data/dxl/minidump/Join-Varchar-Equality.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-AvoidRangePred-DPE.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-DPE-PartitionSelectorRewindability.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverIntersect.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoin.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalPartitionSelector.cpp
- src/backend/gporca/server/CMakeLists.txt
This is a forward port of PR: https://github.com/greenplum-db/gporca/pull/612
Co-authored-by: David Kimura <dkimura@pivotal.io>
Co-authored-by: Shreedhar Hardikar <hardikar@cs.wisc.edu>
Co-authored-by: Chris Hajas <chajas@pivotal.io>
> 6X: Ban plans that demand a rescan of a dynamic PartitionSelector

- src/backend/gporca/data/dxl/minidump/InferPredicatesForProcessedColumn.mdp
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/server/CMakeLists.txt
Signed-off-by: terry <fengyuatad@126.com>
> Set column processed after infer new predicate on it

- src/backend/access/external/url_curl.c
Reading from gpfdist external table can generate lots of HTTP traffic
in very short time window. This may cause intermittent network issues
resulting in "No route to host" error. Backdown and retry in such
scenario.
Reuse the backdown and retry logic for writable external table as
gp_perform_backoff_and_check_response. Pass read/write specific
part as function pointer(multi_perform_work/easy_perform_work).
It's difficult to reproduce such scenario in an automatic way so we
only manually tested this by setting IP_TTL option of socket to 1.
This will immediately result in TTL exceeded packet that cause the
"No route to host" error.
> [5X] Backdown and retry for "No route to host" in gpfdist ext table

- src/backend/optimizer/util/var.c
The function flatten_join_alias_vars_mutator will walk the expression
tree to do some mutation work. It will frequently access the root
parse tree's rtable using list_nth. When the rtable is huge, performance
is poor. This commit caches the rtable list into array to achieve random
access to speed up a lot when rtable is huge.
See Github issue https://github.com/greenplum-db/gpdb/issues/11379
for details. This commit fixes it.
-------
This PR is only for 6X, the master branch does not have such issues.
No test cases added, this is just to improve performance, current test suites should be enough.
-------
In my env:
```
ORCA generates the plan with 32 subpartitions in 8sec (this patch does not impact ORCA).
With this patch, planner generate the plan in 3 sec;
without this patch, planner …
```
> (6X only) Speed up flatten_join_alias_vars() when the rtable is huge.

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
doc changes for https://github.com/greenplum-db/gpdb/pull/11251 and https://github.com/greenplum-db/gpdb/pull/11320 (6x)
> docs - shuffle optimizer_cost_model values/impls

- src/backend/utils/gdd/gddbackend.c
> Remove unused variables and macro in gddbackend.c.

- src/bin/gpfdist/regress/data/catfile.yml
Fix gpfdist test case on ubuntu due to path env
> Fix gpfdist test case on ubuntu

- gpMgmt/bin/gpload_test/gpload2/TEST_local_config.py
- gpMgmt/bin/gpload_test/gpload2/data/transform/input_transform.py
- gpMgmt/bin/gpload_test/gpload2/data/transform/input_transform.xslt
- gpMgmt/bin/gpload_test/gpload2/data/transform/prices.xml
- gpMgmt/bin/gpload_test/gpload2/data/transform/transform_config.yaml
- gpMgmt/bin/gpload_test/gpload2/query100.ans
- gpMgmt/bin/gpload_test/gpload2/setup.ans
- gpMgmt/bin/gpload_test/gpload2/setup.sql
gpload supports transforming data, and loading data by the external
table. Add extra test case to verify the gpload transform feature.
Authored-by: Tingfang Bao <baotingfang@gmail.com>
> Add gpload transform test case

- src/backend/catalog/toasting.c
Starting GPDB7 avoid creating TOAST table for CO tables. Prior
versions created but never populated any data to these tables.
Hence, even if binary upgrade provides TOAST table oid ignore and
avoid creating toast table. Regular code TOAST table creation for CO
table is avoided by consulting table AM API
table_relation_needs_toast_table().
> Avoid creating toast table for CO table during binary upgrade

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- src/backend/utils/misc/gpexpand.c
> Fix typo in gpexpand's error message.

- README.ubuntu.bash
Greenplum is using Python 3 now, update the script.
If you are using other platforms, please help updating the corresponding script and python dependencies files.
> Update README.ubuntu.bash for Python 3

- src/backend/access/transam/xact.c
Currently when replaying distributed commit WAL records, there is no
logic for cache invalidation and clog updates. These are necessary for
a standby coordinator segment or any replica of the coordinator
segment trying to run in hot standby mode. It also seems like the
distributed commit redo function hasn't been updated after so many
Postgres merges. Luckily, distributed commit WAL records are very
similar to regular commit WAL records so we can simply just call
xact_redo_commit(). This should help with maintainability with future
Postgres merges as well.
With this commit, simple stuff like table/view creation on the
coordinator segment will properly reflect on the coordinator
standby/replica side when querying in hot standby mode.
> Properly handle distributed commit WAL replay

- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/expected/qp_union_intersect.out
- src/test/regress/expected/qp_union_intersect_optimizer.out
- src/test/regress/sql/gporca.sql
- src/test/regress/sql/qp_union_intersect.sql
> Fix couple of test to pass for Server compiled without orca

- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
> DOCS: Move memory_spill_ratio to correct location in left navbar.

- src/backend/cdb/cdbmutate.c
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
We do that for normal subplans, but it's not needed for initplans which
only executed once.
> 6X: Don't append duplicated initplans even if referred at multi places

- src/backend/commands/explain_gp.c
- src/test/regress/greenplum_schedule
- src/test/regress/input/direct_dispatch_explain_analyze.source
- src/test/regress/output/direct_dispatch_explain_analyze.source
> Fix that Explain analyze coredump while direct dispatch is enabled

- gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
> DOCS: Remove sentence referring to non-existent functionality

- gpdb-doc/dita/admin_guide/load/load.ditamap
- gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
- gpdb-doc/dita/install_guide/platform-requirements.xml
- gpdb-doc/dita/utility_guide/utility-programs.xml
update the names of some components.
> docs - rename some entries

- gpMgmt/bin/gpload_test/gpload2/TEST_local_preload.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_sql.py
- gpMgmt/bin/gpload_test/gpload2/query608.ans
- gpMgmt/bin/gpload_test/gpload2/query651.ans
- gpMgmt/bin/gpload_test/gpload2/query652.ans
- gpMgmt/bin/gpload_test/gpload2/query653.ans
- gpMgmt/bin/gpload_test/gpload2/query661.ans
- gpMgmt/bin/gpload_test/gpload2/query662.ans
- gpMgmt/bin/gpload_test/gpload2/query663.ans
- gpMgmt/bin/gpload_test/gpload2/query664.ans
- gpMgmt/bin/gpload_test/gpload2/query665.ans
- gpMgmt/bin/gpload_test/gpload2/query666.ans
- gpMgmt/bin/gpload_test/gpload2/query667.ans
SQL: BEFORE, AFTER
PRELOAD: STAGING_TABLE
> Add test for gpload SQL and PRELOAD

- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
- src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql
> [5X backport]recommit the resource wait queue corruption fix

- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
- src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql
> [6X backport]recommit resource group wait queue corruption fix

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
Staging here:
https://schaffergpestats.sc2-04-pcf1-apps.oc.vmware.com
(You must be on VPN.)
> DOCS: Documenting optimizer_dpe_stats GUC.

- gpdb-doc/dita/ref_guide/sql_commands/CREATE_FUNCTION.xml
new attributes are: 
NO SQL | CONTAINS SQL | READS SQL DATA | MODIFIES SQL 
Doc is staging here (you must be on VPN to view): 
https://jschaffer-gpdb.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/sql_commands/CREATE_FUNCTION.html
> DOCS: Documenting previously undocumented CREATE FUNCTION attributes.

- gpdb-doc/dita/ref_guide/feature_summary.xml
- gpdb-doc/dita/ref_guide/sql_commands/FETCH.xml
> Removing features that are no longer unsupported

- gpdb-doc/dita/utility_guide/ref/analyzedb.xml
Document analyzedb `--skip_orca_root_stats` option. Also removes `--skip_root_stats`.
> Document --skip_orca_root_stats

- src/backend/catalog/system_views.sql
- src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
- src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
This is a view that will show the output of the system view
pg_stat_archiver across all segments and the coordinator.
For testing, exercise the view in the gpdb_pitr test suite.
> Introduce the gp_stat_archiver system view

- contrib/test_decoding/expected/oldest_xmin.out
- contrib/test_decoding/expected/rewrite.out
- doc/src/sgml/ref/alter_role.sgml
- doc/src/sgml/ref/alter_table.sgml
- doc/src/sgml/ref/alter_type.sgml
- doc/src/sgml/ref/alter_user_mapping.sgml
- doc/src/sgml/ref/comment.sgml
- doc/src/sgml/ref/copy.sgml
- doc/src/sgml/ref/create_aggregate.sgml
- doc/src/sgml/ref/create_foreign_data_wrapper.sgml
- doc/src/sgml/ref/create_foreign_table.sgml
- doc/src/sgml/ref/create_function.sgml
- doc/src/sgml/ref/create_index.sgml
- doc/src/sgml/ref/create_role.sgml
- doc/src/sgml/ref/create_server.sgml
- doc/src/sgml/ref/create_table.sgml
- doc/src/sgml/ref/create_trigger.sgml
- doc/src/sgml/ref/create_user.sgml
- doc/src/sgml/ref/create_view.sgml
- doc/src/sgml/ref/grant.sgml
- doc/src/sgml/ref/initdb.sgml
- doc/src/sgml/ref/pg_basebackup.sgml
- doc/src/sgml/ref/pg_dump.sgml
- doc/src/sgml/ref/select.sgml
- src/test/isolation/expected/eval-plan-qual.out
- src/test/isolation/specs/eval-plan-qual.spec
Most of the conflicts are from documentation. Resolved to the best of my knowledge.
> Resolve leftover PostgreSQL 12 merge conflicts

- gpcontrib/gpcloud/include/makefile.inc
using `-pthread` to replacement `-lpthread` when compiling with higher version GCC.
> Adapt the advanced version of GCC

- gpdb-doc/dita/admin_guide/managing/maintain.xml
- gpdb-doc/dita/ref_guide/sql_commands/REINDEX.xml
- gpdb-doc/dita/utility_guide/ref/reindexdb.xml
Changed pages are staging here (you must be on VPN): 
https://jenny-reindex.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/managing/maintain.html
https://jenny-reindex.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/reindexdb.html#topic1
https://jenny-reindex.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/sql_commands/REINDEX.html
> DOCS: Revise wording of REINDEX note, plus add same note to REINDEX and reindexdb pages

- .travis.yml
- README.CentOS.bash
- README.Docker.md
- README.Windows.md
- concourse/pipelines/README.md
- gpMgmt/bin/gppkg
We already upgraded to Python 3, but there are still some Python2 things remaining in Travis and READMEs, update them.
> Python3 updates for Travis and READMEs

- gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
Edited some of the steps when upgrading PXF as part of a GPDB upgrade.
Unfortunately I am unable to provide preview link.
> Docs: Modified Upgrade PXF when GPDB

- gpdb-doc/dita/admin_guide/roles_privs.xml
Changes are staging here (VPN required): https://jennyprivileges.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/roles_privs.html
> DOCS: Adding missing objects and updating privileges lists for some objects

- src/backend/commands/indexcmds.c
It's not being used since Greenplum 6, remove and align to the upstream.
> Remove ChooseRelationNameWithCache() and a merge fixme

- src/backend/partitioning/partdesc.c
Bring back the temporary memory context which gets removed in
upstream commit d3f48dfae42f9655425d1f58f396e495c7fb7812.
The reason is when using the GPDB's CREATE PARTITION TABLE syntax,
it'll create lots of subpartitions under the same portal and the memory
leak below will blow up the CurrentMemoryContext, upstream's syntax does
not have this issue since one portal can only create one partition table.
Although we can set -DRECOVER_RELATION_BUILD_MEMORY=1 at compile time to
use upstream logic to free the leak for each RelationBuildDesc() call.
But seems like there is performance concern.
See https://www.postgresql.org/message-id/30380.1552657187%40sss.pgh.pa.us
So we decide to revert part of the commit, this only affects partition
related relations, so the performance should not have much …
> Reduce memory usage for GPDB's CREATE PARTITION TABLE syntax

- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/aosegfiles.c
It looks similar now, I checked the codes before and after the merge.
Remove the FIXME.
> Remove a fixme in ClearAOCSFileSegInfo()

- gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
I have modified the section for gprecoverseg -p as suggested by @kalensk. 
Let me know if anything needs to be amended. Thanks!
Preview (needs VPN access):
https://mireia-gprecoverseg-p.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gprecoverseg.html
> Docs: modified gprecoverseg -p utility guide

- gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
mirror_mode changed to mirror-mode
> DOCS: Change underscore to hyphen

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Addressed typo reported in https://github.com/greenplum-db/gpdb/issues/11775
> Docs: Corrected typo

- src/backend/libpq/be-secure-gssapi.c
- src/interfaces/libpq/fe-connect.c
- src/interfaces/libpq/fe-secure-gssapi.c
- src/interfaces/libpq/libpq-int.h
- src/test/kerberos/t/001_auth.pl
I have seen several issues about this already, let's have this fixed before the 12_STABLE merge.
> Backport GSSAPI changes to fix #11772

- src/backend/utils/misc/guc_gp.c
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/expected/gp_explain_optimizer.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/expected/join_optimizer.out
- src/test/regress/expected/pg_lsn_optimizer.out
- src/test/regress/expected/qp_correlated_query_optimizer.out
- src/test/regress/expected/update_gp_optimizer.out
Reverts d3f4ed9149f, as there were some plan regressions for some user queries that need more investigation.
> Revert "Make exhaustive2 the default"

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
docs for https://github.com/greenplum-db/gpdb/pull/11836/files
> docs - optimizer_join_order default value is exhaustive

- concourse/scripts/compile_gpdb.bash
> libuv is included when compiling photon

- src/backend/commands/copy.c
Since commit be82a3d6761b99e2fbe8aa169728812af2f81bd9, we alloc
part_distData in the per tuple memory context. But we still try
to modify it's values after reset the memory context.
This will lead to memory corruption.
> [5X only]Should not modify pointer's memory after free it in CopyFromDispatch

- gpdb-doc/dita/admin_guide/managing/backup-plugin-api.xml
> DOCS: Storage plugin no longer in Beta

- gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml
- gpdb-doc/dita/admin_guide/managing/replication-ddb.xml
> DOCS: Fix typos in two parameters

- gpdb-doc/dita/install_guide/install_gpdb.xml
- gpdb-doc/dita/install_guide/migrate.xml
- gpdb-doc/dita/install_guide/platform-requirements.xml
- gpdb-doc/dita/install_guide/preinstall_concepts.xml
- gpdb-doc/dita/install_guide/prep_os.xml
- gpdb-doc/dita/install_guide/upgrading.xml
> DOCS: Various changes from docs feedback project: install/upgrade content

- src/backend/access/appendonly/appendonlyam.c
- src/test/isolation2/input/uao/bitmapindex_rescan.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/bitmapindex_rescan.source
> Don't reuse AO block if the corresponding segment file was closed

- concourse/scripts/behave_gpdb.bash
- concourse/tasks/run_behave_on_ccp_cluster.yml
> Install python dependencies for behave explicitly.

- gpdb-doc/dita/security-guide/topics/Authenticate.xml
Added an example for using sslmode
> Docs: Added ssl example

- .travis.yml
- concourse/tasks/check_format.yml
- src/backend/gporca/.clang-format
There were no code changes associated with this version bump.
> 6X: Bump clang-format version to 11

- concourse/tasks/run_behave.yml
> Install python dependencies for behave ccp tests.

- gpMgmt/bin/gpload.py
> Fix gpload unit test error in check_centos.

- contrib/dblink/dblink.c
> Fix duplicated include

- .travis.yml
> Reinstate macOS build in Travis

- gpdb-doc/dita/admin_guide/perf_intro.xml
- gpdb-doc/dita/install_guide/platform-requirements.xml
Added a note about anti-virus installation not being recommended in the following sections:
https://mireia-antivirus.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/platform-requirements.html
https://mireia-antivirus.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/perf_intro.html
> Docs: Added reference against installing anti-virus

- gpAux/platform/gpnetbench/gpnetbenchServer.c
This fix issue: https://github.com/greenplum-db/gpdb/issues/12048
> [6X only]Fix memory leak in gpnetbenchServer

- src/backend/executor/nodeMotion.c
When configuring with 'CPPFLAGS=-DCDB_MOTION_DEBUG', the codes for it
are broken. So fix related codes.
This fix issue: https://github.com/greenplum-db/gpdb/issues/11242
> [6x only]Fix CDB_MOTION_DEBUG preprocessor flag

- src/backend/gporca/data/dxl/minidump/DML-Volatile-Function.mdp
- src/backend/gporca/data/dxl/minidump/SqlFuncDmlScalar.mdp
- src/backend/gporca/data/dxl/minidump/SqlFuncDmlTvf.mdp
- src/backend/gporca/data/dxl/minidump/SqlFuncNullReject.mdp
- src/backend/gporca/data/dxl/minidump/SqlFuncPredFactorize.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CFunctionProp.h
- src/backend/gporca/libgpopt/include/gpopt/base/COptCtxt.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalApply.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalJoin.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalRowTrigger.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalTVF.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnary.h
- src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CScalar.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CScalarFunc.h
- src/backend/gporca/libgpopt/src/base/CFunctionProp.cpp
- src/backend/gporca/libgpopt/src/base/COptCtxt.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionFactorizer.cpp
- src/backend/gporca/libgpopt/src/operators/CLogical.cpp
- src/backend/gporca/libgpopt/src/operators/CLogicalRowTrigger.cpp
- src/backend/gporca/libgpopt/src/operators/CLogicalTVF.cpp
- src/backend/gporca/libgpopt/src/operators/COperator.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
- src/backend/gporca/libgpopt/src/operators/CScalarWindowFunc.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
This is a backpatch of #11887 
@vraghavan78
> [6X_STABLE] Stop checking function data access indication

- src/bin/pg_basebackup/streamutil.c
CreateReplicationSlot() and DropReplicationSlot() were not cleaning up
the query buffer in some cases (mostly error conditions) which meant a
small leak.  Not generally an issue as the error case would result in an
immediate exit, but not difficult to fix either and reduces the number
of false positives from code analyzers.
In passing, also add appropriate PQclear() calls to RunIdentifySystem().
Pointed out by Coverity.
(cherry picked from commit 273b29dbe96b1584dd66615cf8dc83e7e6ae7386)
This fis issue: https://github.com/greenplum-db/gpdb/issues/12050
> [6X]Clean up Create/DropReplicationSlot query buffer

- gpdb-doc/dita/install_guide/platform-requirements.xml
Added reference to R2B XLog under Data Connectors
> Docs: Xlog

- gpdb-doc/dita/analytics/overview.xml
> DOCS: Missed a couple of GPText instances

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/Makefile
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/bin/gppylib/test/unit/gp_unittest.py
6X backport of https://github.com/greenplum-db/gpdb/pull/12097
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-6X_gprecoverseg_common_config_code)
> 6X backport: gprecoverseg: refactor creation of recovery triples

- src/bin/pg_dump/pg_dumpall.c
- src/bin/pg_upgrade/dump.c
This is a forward-port of PR: #12143
> Upgrade resource queues and groups

- contrib/pg_upgrade/greenplum/check_gp.c
This commit introduces a pg_upgrade check to look for views referencing
deprecated columns in a 5X cluster.
This is accompanied by 5X PR: #12168, which introduces a
pg_upgrade_support UDF to detect such views.
> pg_upgrade: Detect views referencing deprecated columns

- src/backend/commands/copy.c
Which was introduced in a refactor commit while merging upstream.
> copy: remove duplicated check

- gpdb-doc/dita/utility_guide/ref/pg_dumpall.xml
See issue https://github.com/greenplum-db/sre-test/issues/120
> Docs: modified setence regarding vacuumdb

- gpdb-doc/dita/best_practices/schema.xml
- gpdb-doc/dita/best_practices/summary.xml
- gpdb-doc/dita/utility_guide/ref/gpstart.xml
Fixed a few typos on the docs.
> Docs: fixed typos

- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
`PgPortIsActive` would rely on `netstat` to find active tcp port. In many
modern Centos systems it has been replaced by `ss`. So now in absence of
`netstat` we use `ss`.
Co-authored-by: Sumit Basu Mallick sumitbm@rediffmail.com
Co-authored-by: Hari Krishna pobbati.hari@gmail.com
> Use 'ss' command in absence of 'netstat' to find active tcp port

- config/orca.m4
- configure
- gpAux/releng/releng.mk
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
These tests are backported from https://github.com/greenplum-db/gpdb/pull/12201
GPORCA PR: https://github.com/greenplum-db/gporca/pull/623
> Add tests for partitioned table with dropped column mismatch between root & leaf

- src/backend/storage/smgr/md.c
What does the expression `+nextsegno` mean?
> Fix a typo in md.c

- gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml
- gpdb-doc/dita/utility_guide/ref/gpmovemirrors.xml
- gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
gpaddmirrors
gpmovemirrors
gprecoverseg
> DOCS: First pass at updating -B and adding -b for these 3 utilities

- concourse/tasks/tar_git_repo.yml
> 7X: Remove extra layer in RC source code

- concourse/tasks/tar_git_repo.yml
> 6X: Remove extra layer in RC source code

- gpdb-doc/dita/ref_guide/sql_commands/ALTER_USER.xml
Added reference to Create User and Drop User under See also.
> Docs: added references to alter user

- gpdb-doc/dita/ref_guide/sql_commands/ALTER_PROTOCOL.xml
Added reference to DROP PROTOCOL in the ALTER PROTOCOL page
> Added reference to drop protocol

- gpdb-doc/dita/ref_guide/sql_commands/CREATE_AGGREGATE.xml
Line indicating optimizer type was missing, added example for ORCA.
> Added mention of optimizer

- gpdb-doc/dita/ref_guide/sql_commands/CLUSTER.xml
added missing option [ USING index_name ]
> Added using index option to cluster

- gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
- gpdb-doc/dita/utility_guide/ref/gpstart.xml
- gpdb-doc/dita/utility_guide/ref/pg_dump.xml
- gpdb-doc/dita/utility_guide/ref/pgbouncer-ref.xml
- gpdb-doc/dita/utility_guide/ref/psql.xml
> Fixed misspellings

- gpdb-doc/markdown/common/gpdb-features.html.md.erb
Updates to account for "Greenplum Database by VMware".
> Docs - update VMware licensing info on landing page

- src/pl/plpython/plpython.c
This commit is backported from upstream's d54de3962a1. Following is
original commit message (refined):
```
PLy_elog() could attempt to access strings that Python had already freed,
because the strings that PLy_get_spi_error_data() returns are simply
pointers into storage associated with the error "val" PyObject.  That's
fine at the instant PLy_get_spi_error_data() returns them, but just after
that PLy_traceback() intentionally releases the only refcount on that
object, allowing it to be freed --- so that the strings we pass to
ereport() are dangling pointers.
In principle this could result in garbage output or a coredump.  In
practice, I think the risk is pretty low, because there are no Python
operations between where we decrement that refcount and where we use the
strings (and copy them …
```
> (5x only)Fix access-to-already-freed-memory issue in plpython's error handling.

- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/gpfdist_ssl.source
- src/bin/gpfdist/regress/output/gpfdist_ssl.source
> Disable unsafe tls(tls1.0 and tls1.1) protocol for gpfdist.

- src/backend/commands/analyze.c
- src/backend/commands/analyzeutils.c
- src/test/regress/expected/incremental_analyze.out
- src/test/regress/sql/incremental_analyze.sql
> [6X backport] Enable for partitioned tables to use column-wise statistics setting

- gpdb-doc/dita/utility_guide/ref/pg_restore.xml
Updated database version as it was out of date
> Updated database version

- gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
- gpdb-doc/dita/ref_guide/sql_commands/ALTER_TEXT_SEARCH_DICTIONARY.xml
- gpdb-doc/dita/ref_guide/sql_commands/CREATE_TEXT_SEARCH_TEMPLATE.xml
Small changes batch:
- Changed reference from CREATE TEXT SEARCH TEMPLATE to ALTER TEXT SEARCH TEMPLATE
- Right formatting on examples
- Wrong order of steps/examples
> Small changes

- gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml
> DOCS: Modify -R description and add -s description for gpcheckcat

- gpdb-doc/dita/ref_guide/modules/diskquota.xml
- gpdb-doc/dita/ref_guide/sql_commands/ANALYZE.xml
- Corrected a syntax error on diskquota page
- Minor modifications on ANALYZE.html page
- Added reference to analyzedb page from ANALYZE page
> Quick fixes

- src/backend/gporca/concourse/test_explain_pipeline.yml
> GPORCA CI: add workload4 to explain pipeline

- src/bin/pg_dump/common.c
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/pg_dump.h
- src/bin/pg_dump/pg_dump_sort.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
> pg_dump dumps foreign/external partitions

- concourse/tasks/run_explain_suite.yml
> GPORCA CI: use 7X stats for workloads in explain_master pipeline

- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
- src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
> Fix clang-tidy errors

- gpcontrib/gpcloud/src/s3restful_service.cpp
- gpcontrib/gpmapreduce/src/yaml_parse.y
- gpcontrib/orafce/file.c
- gpcontrib/orafce/shmmc.c
- gpdb-doc/dita/admin_guide/managing/backup-s3-plugin.xml
- src/backend/access/appendonly/appendonly_visimap_store.c
- src/backend/access/bitmap/bitmapinsert.c
- src/backend/access/transam/xlog.c
- src/backend/cdb/dispatcher/cdbgang_async.c
- src/backend/replication/syncrep.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/resgroup-ops-linux.c
- src/backend/utils/workfile_manager/workfile_mgr.c
- src/bin/pg_upgrade/Makefile
- src/include/catalog/pg_control.h
- src/include/gppc/gppc.h
- src/include/replication/walsender_private.h
- src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out
- src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql
Authored-by: Bradford D. Boyle <bradfordb@vmware.com>
> Fix multiple typos

- concourse/scripts/compile_gpdb.bash
The bytecode is compiled and installed during package installation.
Vendor pkgconfig files for libzstd, libuv, quicklz.
> Vendor pkgconfig files, do not include compiled python bytecode in exported tarball.

- gpMgmt/bin/gpcheckcat
> Adding missing --help option and small formatting correction for gpcheckcat

- gpMgmt/bin/gpcheckcat
> Adding missing --help option and small formatting correction

- gpdb-doc/dita/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.xml
> docs - reference correct package

- gpMgmt/bin/generate-greenplum-path.sh
Issue #12420
INFO : backporting changes from master
> Fix environment variables generation when using symlinks

- gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
Patching the below gaps in unit tests of gpstart utility
1. gpstart should success with auto accept
2. gpstart should success without auto accept
3. gpstart should exit when user abort
4. gpstart with master only option should exit when user abort
Co-authored-by: M Hari krishna hmaddileti@vmware.com
> Inclusion of unit tests for more test coverage of gpstart

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Based on greenplum-db/sre-test#229 and greenplum-db/sre-test#213
> Docs: correct parameter set classifications; correct parameter default value

- gpdb-doc/dita/install_guide/platform-requirements.xml
correct the version of bundled pxf, add a note about how to obtain a newer version of pxf, conditionalize some text.
> docs - misc pxf-related updates to platform reqs page

- gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> DOCS: First draft of small updates to gprecoverseg ref page

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Based on greenplum-db/sre-test#222
> Rename 'replication_timeout' and remove 'regex_flavor'

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Based on greenplum-db/sre-test#213
> Docs: Correct parameter classification

- gpdb-doc/dita/admin_guide/textsearch/dictionaries.xml
Link for Ispell has changed, I have updated the reference.
> Docs: Fixed broken link

- src/backend/storage/lmgr/lwlock.c
I see no point for us to have diff here with upstream. The changes
made to this file like LWLockTryLockWaiting() function are way back in
history and reveal no context for the change. Plus I think being under
LOCK_DEBUG I highly doubt is used much. Some other minor differences
existed compared to upstream so taking them out as well. With this
change lwlock.c fully aligns with upstream.
Other benefit of this change also fixes github issue #12484 ("compile
error while enable LOCK_DEBUG")
> Align lwlock.c with upstream

- concourse/tasks/run_explain_suite.yml
- src/backend/gporca/concourse/test_explain_pipeline.yml
Updating workload pipeline to add a new suite. 
The commit also includes a check to decompress a zipped stats file if
exists.
Same content as that of https://github.com/greenplum-db/gpdb/pull/12519 except the temp changes.
https://github.com/greenplum-db/gpdb/pull/12519 has the approval, but can't push the changes as I don't have permissions, so will close that and use this.
> Update orca workload pipeline to add a new suite

- src/backend/utils/resscheduler/resqueue.c
- src/include/utils/resscheduler.h
- src/test/regress/expected/resource_queue.out
- src/test/regress/sql/resource_queue.sql
This PR introduces various fixes to the ERROR code path for ResLockAcquire().
Please review the commits individually.
> Miscellaneous fixes to the ERROR path for ResLockAcquire

- concourse/tasks/rename_rc_artifacts.yml
This change was missed in #12518
> [6X] Replace centos8 artifact with rhel8 artifact

- README.CentOS.bash
- README.Ubuntu.bash
Add to READMEs for newbies.
Fix #12530
> Add sysctl and limits configurations to README.*.bash

- gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml
> DOCS: Bigger updates to gpercoverseg ref page

- README.Linux.md
- README.macOS.md
> docs - make installation easier to understand for macOS and Ubuntu

- gpdb-doc/dita/utility_guide/ref/gpstart.xml
> docs - correct a psql command typo

- gpdb-doc/dita/admin_guide/kerberos.xml
- gpdb-doc/dita/install_guide/prep_os.xml
will need to backport these changes to 6X_STABLE
> docs - correct a few more typos

- src/backend/commands/sequence.c
New sequence hash key, introduced in d874700, wasn't taken into account by `SeqTable` struct, which should contain the whole key to avoid key data corruption. `SeqTable` now using whole `SeqTableKey` struct to avoid future bugs related to key extension.
Issue #12583.
> Fix incomplete hash key in sequence table data.

- src/backend/executor/execUtils.c
- src/backend/executor/nodeDynamicBitmapHeapscan.c
- src/backend/executor/nodeDynamicBitmapIndexscan.c
- src/backend/executor/nodeDynamicSeqscan.c
- src/include/executor/execUtils.h
- src/include/nodes/execnodes.h
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
Commit db5163474d did a big refactor of DynamicXXXScan, unfortunately,
it introduces memory leak during Executor running stage for
ExecDynamicBitmapHeapScan and ExecDynamicSeqScan (ExecDynamicIndex does
not leak memory). Use ExecDynamicSeqScan to demonstrate the issue, it
will init a new seqscan state for each new partition (some memroy will
be allocated during this operation), this is not a good pattern as I
can see. Postgres only invoke ExecInitXXX during InitPlan(), never in
ExectorRun()'s lifetime. The point is ExecDynamicSeqScan might appear
as the inner plan of Nestloop join which means it might be rescaned
many many times. So we cannot init a new seqscan state each time for
a new partition or we have to clean it up totally after a single partition
is finished one time.
We have …
> (6x only) Fix memory leak for DynamicBitmapHeapScan and DynamicSeqScan.

- src/backend/commands/sequence.c
New sequence hash key, introduced in d874700, wasn't taken into account by
`SeqTable` struct, which should contain the whole key to avoid key data
corruption. `SeqTable` now using whole `SeqTableKey` struct to avoid future
bugs related to key extension.
Issue #12583.
(cherry picked from commit eff458fdaa986673781ee6ad6c90fe08674a8907)
> Fix incomplete hash key in sequence table data. (#12589)

- src/backend/executor/nodeMotion.c
- src/test/regress/expected/shared_scan.out
- src/test/regress/expected/shared_scan_optimizer.out
- src/test/regress/sql/shared_scan.sql
Backport of https://github.com/greenplum-db/gpdb/pull/12550
> [Backport] Fix crash on QD when squelching CTE producer with a Motion child

- gpMgmt/bin/mem_watcher
This is currently available on Knowledge Base and used by support and some
customers. We want to add it to gpdb to save it in source control and to make
it easier for customers to get it.
Authored-by: Karen Huddleston <khuddleston@vmware.com>
> Add mem_watcher utility to gpdb source

- gpMgmt/bin/mem_watcher
This is currently available on Knowledge Base and used by support and some
customers. We want to add it to gpdb to save it in source control and to make
it easier for customers to get it.
Authored-by: Karen Huddleston <khuddleston@vmware.com>
> [6x] Add mem_watcher utility to gpdb source

- gpdb-doc/README.md
> Fix broken markdown format.

- gpdb-doc/book/master_middleman/source/subnavs/cloud-subnav.erb
- gpdb-doc/book/master_middleman/source/subnavs/gpdb-landing-subnav.erb
- gpdb-doc/book/master_middleman/source/subnavs/pxf-subnav.erb
- gpdb-doc/dita/admin_guide/admin_guide.ditamap
- gpdb-doc/dita/best_practices/best-practices.ditamap
- gpdb-doc/dita/ref_guide/ref_guide.ditamap
- gpdb-doc/dita/security-guide/security-guide.ditamap
- gpdb-doc/dita/utility_guide/utility_guide.ditamap
> docs - ditamap updates for 5.29 release

- src/backend/commands/copy.c
- src/test/regress/expected/copy_eol.out
- src/test/regress/greenplum_schedule
- src/test/regress/input/gpcopy.source
- src/test/regress/output/gpcopy.source
- src/test/regress/sql/copy_eol.sql
This is the gp6 version of #12455 with additional fix of test
data produce issue.
> [6x backport and additional fixes] Fix copy command EOL 

- gpdb-doc/dita/install_guide/migrate.xml
would open the release notes for the most recent release of greenplum.
> docs - replace an incorrect xref

- gpdb-doc/dita/utility_guide/ref/gpstate.xml
Changes staging here (VPN required): https://jenny-gpstate.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gpstate.html#topic1
> DOCS: Update information about gpstate -e and gpstate -s content to reflect new WAL mirror sync functionality.

- concourse/pipelines/gen_pipeline.py
- concourse/scripts/compile_gpdb.bash
> Cache xerces-c in build container

- gpMgmt/bin/Makefile
- gpMgmt/bin/gpmemreport
- gpMgmt/bin/gpmemwatcher
Adding memwatcher and memreport support utilitites to gpdb source control
control and to make it easier for customers to get it.
Co-authored-by:Sambitesh Dash <sdash@pivotal.io>
Co-authored-by:Piyush Chandwadkar <pchandwadkar@vmware.com>
Sample output:
[gpadmin@instance-mhk-gpdb-master mem_tools]$ ./memreport instance-mhk-gpdb-master.ps.out.gz
>>>21:10:21:06:16:01<<<
>>>21:10:21:06:17:01<<<
>>>21:10:21:06:18:01<<<
>>>21:10:21:06:19:01<<<
>>>21:10:21:06:20:02<<<
[gpadmin@instance-mhk-gpdb-master mem_tools]$ cat 20211021-061601
Polling Timestamp:  2021-10-21T06:16:01
NODE SUMMARY
============
Total Number of Processes:                        164
Total Memory used (MB)                            1499.0898
SEGMENT SUMMARY
===============
Segment             Total (MB)   Session (MB) …
> Adding memwatcher and memreport support utilitites to gpdb source control

- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalJoin.h
- src/backend/gporca/libgpopt/src/operators/CPhysicalInnerNLJoin.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
- src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
Currently, NL LOJ inner child always get's a replicated distribution
request, due to which we always broadcast the inner child even though if
it's already distributed on the join columns.
Consider the example:
```
create table t1 (a int, b int);
create table t2 (a int, b int);
set optimizer_enable_hashjoin=off;
explain select * from t1 left outer join t2 on t1.a = t2.a;
Gather Motion 3:1  (slice2; segments: 3)  (cost=0.00..1324032.82 rows=2 width=16)
->  Nested Loop Left Join  (cost=0.00..1324032.82 rows=1 width=16)
Join Filter: (t1.a = t2.a)
->  Seq Scan on t1  (cost=0.00..431.00 rows=1 width=8)
->  Materialize  (cost=0.00..431.00 rows=1 width=8)
->  Broadcast Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=8)
->  Seq Scan on t2  (cost=0.00..431.00 rows=1 width=8) …
```
> Allow requesting hashed distribution for NL LOJ inner childs

- concourse/scripts/compile_gpdb.bash
- concourse/tasks/rename_rc_artifacts.yml
> Vendor libzstd for clients in GPDB7.

- gpdb-doc/dita/ref_guide/system_catalogs/pg_partitions.xml
Added missing column based on engineering feedback and 6.18.1 environment.
> Docs: added missing columns in doc for pg_partitions table

- gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_replication.xml
Added missing column based on engineering input and 6.18.1 environment.
> Docs: added missing columns in doc for pg_stat_replication

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Configuration parameters that do not need restart to be modified have been changed to reload.
> Docs: changed list of GUCs that need reload instead of restart

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> Docs: specified range of values for guc extra_float_digits

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
> Docs: dynamic_library_path needs reload not restart

- gpdb-doc/dita/utility_guide/ref/createdb.xml
> Docs: moved maintenance-db option under connection options

- gpdb-doc/dita/best_practices/analyze.xml
- gpdb-doc/dita/best_practices/bloat.xml
- gpdb-doc/dita/best_practices/data_loading.xml
- gpdb-doc/dita/best_practices/security.xml
- gpdb-doc/dita/best_practices/summary.xml
- gpdb-doc/dita/best_practices/sysconfig.xml
Some typos, incorrect statements, etc.
> Docs: miscelaneous edits to Best Practices section

- gpdb-doc/dita/best_practices/security.xml
- gpdb-doc/dita/security-guide/topics/BestPractices.xml
For Best Practices section and Security section.
> Docs: indicate that commands need to be run as root/sudo

- gpMgmt/bin/gpexpand
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
This reverts commit de93d318ad672da41e1eb78aac64517162f2ba83.
Pipeline job gpexpand become red since this commit, revert it
and investigate this later.
> Revert "Copy postgresql.auto.conf from segment while gpexpand."

- src/backend/cdb/motion/README.ic-proxy.md
Hi there, I am learning the implementation of ic-proxy and I find something confused in README.
I believe it is a mistake, so I amend this part according to my understanding, or it will be a contradiction with subsequent parts of README. Please check it, thx. 🦆
> Docs: fixing error in ic-proxy README

- gpMgmt/bin/gpload.py
- gpMgmt/doc/gpload_help
Reverts greenplum-db/gpdb#12868
Gpload in 5X will not add new features.
Reverting this pr.
> Revert "add gpload input newline config"

- config/orca.m4
- configure
- gpAux/releng/releng.mk
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
gporca 3.121 fixes an issue with casting for EXCEPT & INTERSECT that
was crashing executor
> Add regression test for SetOps casting and bump orca ver to 3.121

- gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-notes.xml
- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
update the guc reference guide and a gporca topic.
not sure if i am characterizing the behaviour correctly...
> docs - new gporca guc optimizer_force_comprehensive_join_implementation

- src/tools/vagrant/README.md
> fix: markdown syntax error

- contrib/hstore/hstore_io.c
- contrib/pageinspect/heapfuncs.c
- src/backend/utils/adt/encode.c
- src/backend/utils/adt/jsonpath_gram.y
- src/backend/utils/adt/regexp.c
- src/backend/utils/adt/varbit.c
- src/backend/utils/adt/varlena.c
- src/backend/utils/error/elog.c
- src/test/regress/expected/misc_jiras.out
- src/test/regress/sql/misc_jiras.sql
This PR includes two commits:
* Backport upstream commit 16e3ad5d143 from v14 which fixed issue #12381, and added a test case too.
* Remove extraneous verify_and_replace_mbstr() to align with upstream.
> Fix #12381

- src/backend/libpq/auth.c
In `cdbconn_doConnectStart()`, Greenplum cleans the host info to force
using domain socket for entry db connections. Checking the connection's
authentication here is not necessary, even annoying, if the user is not
allowed to connect via domain socket.
This commit authenticates it directly, just as Greenplum authenticates
TCP internal connections coming from the same host.
Fix https://github.com/greenplum-db/gpdb/issues/12851
> Authenticate internal connections via domain sockets

- README.linux.md
Updating RHEL8 installation steps on README.Linux.md, as few additional RHEL8 specific steps needs to be updated.
Co-authored-by: Piyush Chandwadkar pchandwadkar@vmware.com
> RHEL8: README.Linux.md update on 6X_STABLE

- src/bin/gpfdist/gpfdist.c
When the segments write data to gpfdist through http protocol, the
socket may be reset because of the network failure. When gpfdist
detects this error, it tries to send an internal error code to the
clients side through the reset socket. But it will fail to inform
the clients because the socket is already unusable. The client side
usually gets an error when calling curl_easy_perform. So it will
retry the curl_easy_perform, and libcurl will try to connect to the
gpfdist will a new socket, and the new socket connection is regarded
as a new request by gpfdist. And at the time gpfdist accept this
socket, the fstream has already been closed by last error. So when
the new request tries session_attach, it will get an empty response
with no error. And so are all the following post requests sent …
> Fix gpfdist writable external table false success.

- src/backend/gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.cpp
Similar to dede33b352f when statistics may not be derived yet, we should
take care to handle the scenario gracefully.
Following demonstrated error using non-assert build:
```sql
CREATE TABLE a_table(col text);
SELECT a.col FROM (
SELECT col FROM a_table e
WHERE exists
(
SELECT col FROM a_table
)
) a
WHERE exists (
SELECT c.col FROM a_table c
INNER JOIN a_table b
ON c.col = a.col
WHERE exists (
SELECT distinct _a.col FROM (
SELECT distinct col FROM a_table _a
) _a
WHERE _a.col = c.col
)
);
```
NOTE: I opted not to add the above as a regress test as it felt very fragile, but I'm open to suggestions otherwise.
> Fix SIGSEGV due to non-derived statistics

- src/backend/cdb/cdbtm.c
- src/test/isolation2/expected/concurrent_update.out
- src/test/isolation2/expected/gdd/concurrent_update.out
- src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
- src/test/isolation2/sql/gdd/concurrent_update.sql
> Fix flaky concurrent update on 6x

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Incorporating review comments from #12964  to master 
Ran the concourse flow and gpcheckcat tests are passing.
> [Master] Gpcheckcat: Incorporating minor review comments

- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Modified some of the GUCs parameter settings, in particular the Set Classifications column. Might need engineering approval.
> Docs: modified parameter settings for certain GUCs

- gpdb-doc/markdown/install_guide/prep_os.html.md
the install guide has been converted from dita to markdown.  this is an equivalent PR to https://github.com/greenplum-db/gpdb/pull/12919.
> docs - adjust the /etc/sysctl.conf kernel.sem setting

- gpMgmt/test/behave/mgmt_utils/gpconfig.feature
> Added Behave testcase for  guc with same prefix

- src/backend/gporca/README.md
> Docs - fix the broken link to a non-existing doc

- src/backend/gporca/concourse/test_explain_pipeline.yml
> GPORCA CI: add workload6 to explain pipeline

- gpMgmt/bin/gpload.py
- gpMgmt/bin/gpload_test/gpload2/query33.ans
set the schema of staging table to gpload:external:shcema in gpload yaml file.
> set staging table schema to external-schema in yaml file

- gpMgmt/bin/gpload_test/gpload2/query33.ans
modify ans file for gpload test case 33
> fix gpload causing pipeline fail

- gpcontrib/Makefile
- gpcontrib/gp_array_agg/.gitignore
- gpcontrib/gp_array_agg/Makefile
- gpcontrib/gp_array_agg/README.md
- gpcontrib/gp_array_agg/expected/gp_array_agg.out
- gpcontrib/gp_array_agg/expected/gp_array_agg_optimizer.out
- gpcontrib/gp_array_agg/gp_array_agg--1.0.0.sql
- gpcontrib/gp_array_agg/gp_array_agg.c
- gpcontrib/gp_array_agg/gp_array_agg.control
- gpcontrib/gp_array_agg/sql/gp_array_agg.sql
This reverts commit 2dd05f4683ac0e0e4e6565b9633de225cb37d255.
> Revert "Revert "Introducing parallel array_agg (#13051)""

- src/Makefile
- src/test/unit/cmockery/Makefile
- src/test/unit/mock/Makefile
make clean ```${CMOCKERY_DIR}``` and ```${MOCK_DIR}```
> make clean ${CMOCKERY_DIR} and ${MOCK_DIR}

- src/backend/executor/nodeModifyTable.c
Previous bug has already been fixed by 043b809a1e. Now we do support
such kind of SQL:
WITH updated AS
(update tbl set rank = 6 where id = 5 returning rank)
select * from tbl where rank in (select rank from updated);
This commit just removes the comments and change the error message
because this piece of code is not reachable.
-----------------
There is no need to have tests in this PR because the piece of code now is not reachable, and previous commit
introduce a case for the fix.
> Resolve a MERGE 12 FIXME in nodeModifyTable.c.

- src/backend/storage/smgr/md.c
`segno` in `mdsync()` is reset to 0 if `is_seg0` is true. That is not correct because `is_seg0` really just means something's wrong when opening the base relfilenode in `_mdfd_getseg()`, which could happen for any `segno`. So, `segno` shouldn't be changed, especially considering `bms_next_member()` relies on it to give a correct next `segno`.
Also, limit the scope of `is_seg0` so its value won't affect things unintentionally in the following loops.
The corrupted `segno` value could result in stuck loop in `mdsync()`. We've seen cases where relfilenodes of some table get unlinked while we are still trying to access `segno=1` in `mdsync()`. After getting ENOENT (file not existing) for the file, we will reset `segno` to 0. Then because the `canceled` flag was set we'll break the retry loop …
> Fix segno being incorrectly reset in mdsync()

- src/backend/cdb/cdbpathlocus.c
Direct looking for ```AppendRelInfos``` by relid in the ```append_rel_array```
instead of trawl through the ```append_rel_list```.
Finding ```AppendRelInfos``` by relid had quite a large overhead when the
number of items in the ```append_rel_list``` was high, as it had to trawl
through the ```append_rel_list``` looking for ```AppendRelInfos``` belonging to
the given childrelids.
Upstream introduced ```append_rel_array``` to fix this performance issue
by storing an array in PlannerInfo which indexes ```AppendRelInfos``` by
child relid. Reduced time complexity from O(N) to O(1).
Discussion: https://postgr.es/m/94dd7a4b-5e50-0712-911d-2278e055c622@dalibo.com
commit: https://github.com/greenplum-db/gpdb/commit/7d872c91a3f9d49b56117557cdbb0c3d4c620687
> Direct looking for AppendRelInfos by relid in the append_rel_array instead of trawl through the append_rel_list.

- gpdb-doc/dita/analytics/text.xml
- gpdb-doc/markdown/install_guide/prep_os.html.md
> Correct some spelling mistakes about word "Greenplum".

- gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-limitations.xml
> docs - add missing tags (doh)

- gpdb-doc/dita/admin_guide/managing/backup-s3-plugin.xml
- gpdb-doc/markdown/install_guide/install_pxf.html.md
- gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb
- gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
> docs - a few misc xref corrections

- gpdb-doc/markdown/admin_guide/wlmgmt.html.md
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/install_guide/platform-requirements.html.md
> Add RHEL8 to list of supported platforms

- src/test/regress/pg_regress.c
> Fix typo in pg_regress help

- gpdb-doc/dita/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.xml
- gpdb-doc/dita/ref_guide/sql_commands/INSERT.xml
- gpdb-doc/dita/ref_guide/system_catalogs/catalog_ref-views.xml
> Docs - adding missing attributes for newly-converted html links

- src/backend/cdb/endpoint/cdbendpoint.c
- src/backend/cdb/endpoint/cdbendpointretrieve.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/sync_guc_name.h
> Add GUC gp_log_endpoints to print endpoints information to server log

- src/test/regress/expected/gangsize.out
- src/test/regress/expected/gangsize_optimizer.out
- src/test/regress/sql/gangsize.sql
Now with orca enabled the case runs correctly, so just remove the
sql that disbale orca and the comments.
> Remove Merge FIXME in test gangsize.

- src/backend/optimizer/prep/prepjointree.c
PostgreSQL only processes EXISTS_SUBLINK in not clause, does not process ANY_SUBLINK | ALL_SUBLINK, and notclause in not-clause.
the second param of canonicalize_qual in pull_up_sublinks_qual_recurse is false, here expr must not be a check constraint.
before commit 220e45bf32 in gpdb5
we optimize ANY_SUBLINK or ALL_SUBLINK in not clause in that case:
NOT val op ANY (subq) => val op' ALL (subq)
NOT val op ALL (subq) => val op' ANY (subq)
after commit 220e45bf32 (11 years ago): Improve the planner's simplification of NOT constructs.
we optimize ANY_SUBLINK or ALL_SUBLINK in not clause in that case:
NOT val op ANY (subq) =>NOT val op ALL (subq)
NOT val op ALL (subq) =>NOT val op ANY (subq)
then in preprocess_expression-->eval_const_expressions-->eval_const_expressions_mutator
we …
> resolve pull_up_sublinks fixme

- gpcontrib/gp_exttable_fdw/extaccess.c
- gpcontrib/gpcloud/regress/input/3_01_create_wet.source
- gpcontrib/gpcloud/regress/output/3_01_create_wet.source
- src/backend/cdb/cdbcat.c
This PR is ported from 6X_STABLE PR #13307
> Support writable s3 external table on master

- src/backend/cdb/dispatcher/cdbgang_async.c
Commit 9116c93d054c632eb40d81da4740a63762c5bdad fixed an issue that global transaction still continues even after FTS changed cluster configuration during the transaction.
The fix worked perfectly but the comments could use some clarification where we found confusing.
> Update the comments for commit 9116c93

- configure
- configure.in
Authored-by: Bradford D. Boyle <bradfordb@vmware.com>
> Fix typo of gss_store_cred_into in configure.in

- doc/src/sgml/config.sgml
- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- src/backend/cdb/motion/ic_udpifc.c
- src/backend/libpq/pqcomm.c
- src/backend/tcop/postgres.c
- src/backend/utils/init/globals.c
- src/backend/utils/init/postinit.c
- src/backend/utils/misc/guc.c
- src/backend/utils/misc/timeout.c
- src/include/libpq/libpq.h
- src/include/miscadmin.h
- src/include/tcop/tcopprot.h
- src/include/utils/sync_guc_name.h
- src/include/utils/timeout.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/expected/pg_terminate_backend.out
- src/test/isolation2/sql/pg_terminate_backend.sql
- src/test/isolation2/sql_isolation_testcase.py
Backport https://github.com/greenplum-db/gpdb/pull/12223 to 6X_STABLE
> [6X] Detect client disconnection while running query and interrupt execution

- src/backend/cdb/cdbsubselect.c
- src/test/regress/expected/notin.out
- src/test/regress/expected/notin_optimizer.out
- src/test/regress/sql/notin.sql
This PR contains two commits, please review it one by one.
Commit message contains the whole information.
> Enhance the test of nonnullable for NOT-IN sublink.

- gpdb-doc/dita/analytics/intro.xml
- gpdb-doc/dita/analytics/madlib.xml
- gpdb-doc/dita/analytics/pl_container.xml
- gpdb-doc/dita/analytics/pl_container_using.xml
- gpdb-doc/dita/analytics/pl_java.xml
- gpdb-doc/dita/analytics/pl_perl.xml
- gpdb-doc/dita/analytics/pl_python.xml
- gpdb-doc/dita/analytics/pl_r.xml
- gpdb-doc/dita/analytics/pl_sql.xml
- gpdb-doc/dita/security-guide/topics/Authenticate.xml
- gpdb-doc/dita/security-guide/topics/BestPractices.xml
> Fix varnames in Authenticate.xml

- gpdb-doc/markdown/install_guide/install_pxf.html.md
> docs - use external link for pxf xref

- gpdb-doc/markdown/ref_guide/SQL2008_support.html.md
> Docs - fix broken markdown table causing build failure

- gpdb-doc/markdown/ref_guide/SQL2008_support.html.md
- gpdb-doc/markdown/ref_guide/feature_summary.html.md
Replacing complex table with html table source in md.
> Docs correct md table

- src/backend/cdb/cdbutil.c
The global variable host_segments is only used on QEs under resource
group mode and the value is dispatched to QEs from QD. Previously in
the function getCdbComponentInfo(), QD make a hashtable, and count host_segments
group by the key of ip address. This is not correct. A typical
Greenplum deployment environment may have different ip addresses point
to the same machine. Use ip address as hash key will lead to wrong
number of host_segments and lead to more memory limit of a segment
than user's intent.
This commit use hostname as a machine's unique identifier to fix the issue.
-------
Almost the same as https://github.com/greenplum-db/gpdb/pull/13478/, but do not rename vars and functions for 6X.
> (6x) Use hostname instead of ip to compute the host_segments.

- gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
Fix unit test case missed in pr 13413
> fix failed pipeline caused in pr[13413].   

- gpdb-doc/markdown/admin_guide/roles_privs.html.md
- gpdb-doc/markdown/best_practices/bloat.html.md
- gpdb-doc/markdown/best_practices/ha.html.md
- gpdb-doc/markdown/best_practices/maintenance.html.md
- gpdb-doc/markdown/best_practices/resgroups.html.md
- gpdb-doc/markdown/best_practices/summary.html.md
- gpdb-doc/markdown/best_practices/sysconfig.html.md
- gpdb-doc/markdown/best_practices/workloads.html.md
> Docs - removing escaped characters appearing in rendered html

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Missing closure of connection was causing many idles connections in GPDB leading to tests getting stuck.
> test case correction to add connection close

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
In a test step, as DB connection was not getting closed, some tests are getting hung because locks were not released.
> test case correction to add connection close in test step (#13555)

- src/backend/catalog/namespace.c
- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/tcop/postgres.c
- src/include/catalog/namespace.h
- src/test/regress/expected/bfv_temp.out
- src/test/regress/sql/bfv_temp.sql
cherry pick from 6X
same as #13213
> [6.20.x] dispatch temporary namespace id to all Gangs.

- gpdb-doc/markdown/utility_guide/ref/gpmt-gp_log_collector.html.md
- gpdb-doc/markdown/utility_guide/ref/gpmt-gp_storage_rca_collector.html.md
- gpdb-doc/markdown/utility_guide/ref/gpmt.html.md
Staging here: 
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/6.21-gpmt-updates/greenplum-database/GUID-utility_guide-ref-gpmt.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/6.21-gpmt-updates/greenplum-database/GUID-utility_guide-ref-gpmt-gp_storage_rca_collector.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/6.21-gpmt-updates/greenplum-database/GUID-utility_guide-ref-gpmt-gp_log_collector.html
> DOCS: 6.21 changes to GPMT

- gpdb-doc/markdown/admin_guide/monitoring/monitoring.html.md
- gpdb-doc/markdown/install_guide/platform-requirements.html.md
> Docs - fix html table formatting in markdown

- src/test/regress/expected/gp_explain.out
- src/test/regress/expected/gp_explain_optimizer.out
- src/test/regress/sql/gp_explain.sql
> Fix GPDB_12_MERGE_FIXME in `gp_explain.sql`: Non default collation

- src/test/regress/regress_gp.c
When the chunk unit is larger than 1MB, the allocated memory size in **reGroupPalloc** is incorrect.
Notice the following code snippet:
```c
ResGroupGetMemInfo(&memLimit, &slotQuota, &sharedQuota);
size = ceilf(memLimit * ratio);
...
size %= 512;
MemoryContextAlloc(TopMemoryContext, size * 1024 * 1024);
```
The unit of `memLimit` is chunk, and the chunk size may be larger than 1MB.
On the other hand, the result of `size %= 512` may be 0, but the param of `MemoryContextAlloc` **should not** pass the value 0.
> Fixed bug in resGroupPalloc about the allocated memory size.

- src/backend/access/aocs/aocs_compaction.c
- src/backend/access/appendonly/aomd.c
- src/backend/access/appendonly/appendonly_compaction.c
- src/include/access/aomd.h
Please see individual commits for details.
> OpenAOSegmentFile: minor cleanups

- src/backend/cdb/cdbpath.c
GPDB_12_MERGE_FIXME:
PostgreSQL fires the DELETE+INSERT trigger if we UPDATE a partitioning key column. 
We could probably do the same with Update on the distribution key column.
Firstly, Trigger is not supported officially by GPDB.
Secondly, the update trigger is processed in ExecUpdate, however, updating the
distribution key will generate a split plan, and split update to delete + insert. so the
top plan below will execute ExecSplitUpdate_Insert or ExecDelete instead of ExecUpdate.
And the update trigger will not be triggered in a split plan.
PostgreSQL fires the row-level DELETE, INSERT, and BEFORE UPDATE triggers,
but not row-level AFTER UPDATE triggers, if you UPDATE a partitioning key column.
Doing a similar thing doesn't help Greenplum likely, the behavior would be uncertain
since …
> resolve fixme in cdbpath.c about update distribution key

- src/include/access/appendonlytid.h
> [typo] fix a typo to make the comment more precise

- concourse/scripts/build_gpdb.py
- concourse/scripts/builds/GpBuild.py
Also set `source_env_cmd` accordingly.
> [GPORCA CI] Don't setup gpadmin user if database already exists

- src/backend/access/aocs/aocs_compaction.c
- src/backend/access/appendonly/aomd.c
- src/backend/access/appendonly/appendonly_compaction.c
- src/include/access/aomd.h
> 6X: OpenAOSegmentFile: minor cleanups

- src/backend/utils/misc/guc_gp.c
> Fix small typos in parameters description in guc_gp.

- src/backend/cdb/dispatcher/cdbdisp_async.c
- src/backend/tcop/postgres.c
- src/bin/gpfdist/gpfdist.c
- src/include/miscadmin.h
> [6X_STABLE] resolve compiler warnings

- gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_tables.xml
some columns in pg_stat_all_tables are not populated in 5X.
> docs - clarify that the pg_stat_all_tables last_xxx cols not populated

- src/backend/utils/misc/fstream/gfile.c
Long log:
When we write compressed data into a full disk, gpfdist will return 500 error.
After 5 mins, the session will be removed. 
Then, if we write data into the full disk again, gpfdist will fail, like:
`gz_file_write_one_chunk: Assertion `ret1 != (-2)' failed.`
This ia a phenomenon that users do not expect. In fact, gpfdist can still work for other request.
We think we shouldn't carry on assert(ret1 != Z_STREAM_ERROR);  
If the error happens, we need to judge and return directly, avoiding gpfdist fails.
The log is shown as below:
```
2022-06-27 18:10:55 6837 INFO active segids in session: 0 1 2
2022-06-27 18:10:55 6837 WARN [1:6:1:11] handle_post_request, write error: cannot write into file
2022-06-27 18:10:55 6837 WARN [1:6:1:11] HTTP ERROR: 127.0.0.1 - 500 cannot write into file …
```
> master: fix gpfdist crash

- src/backend/utils/misc/fstream/gfile.c
Long log:
When we write compressed data into a full disk, gpfdist will return 500 error.
After 5 mins, the session will be removed.
Then, if we write data into the full disk again, gpfdist will fail, like:
```
gz_file_write_one_chunk: Assertion `ret1 != (-2)' failed.
```
This is a phenomenon that users do not expect.
In fact, gpfdist can still work for other request.
We think we shouldn't carry on assert(ret1 != Z_STREAM_ERROR);
If the error happens, we need to judge and return directly, avoiding gpfdist fails.
The log is shown as below:
```
2022-06-27 18:10:55 6837 INFO active segids in session: 0 1 2
2022-06-27 18:10:55 6837 WARN [1:6:1:11] handle_post_request, write error: cannot write into file
2022-06-27 18:10:55 6837 WARN [1:6:1:11] HTTP ERROR: 127.0.0.1 - 500 cannot write into file …
```
> 6X: fix gpfdist crash (#13750)

- concourse/pipelines/pr_pipeline.yml
> Migrate all secrets from gpdb_pr master pipeline to prod Vault

- concourse/pipelines/pr_pipeline.yml
> Migrate all secrets from gpdb_6X_STABLE_pr pipeline to prod Vault

- concourse/pipelines/pr_pipeline.yml
> Migrate all secrets from gpdb_pr_5x_stable pipeline to prod Vault

- src/backend/utils/resscheduler/resqueue.c
When i investigated another one assertion failure in ResLockAcquire, i 
found this possible issue.
If palloc() failed in ResWaitOnLock due to OOM, it will trigger
a PANIC "Waiting on lock already held" because partitionLock is
not released correctly.
The first attempt is to add a try/catch surrounding for this
palloc() call, and release the partitionLock before rethrowing
error. But it is not good as ResIncrementRemove is not called.
So use local char new_status[160], length 160 is enough.
----
Add a fault at the palloc() position:
```
#ifdef FAULT_INJECTOR
SIMPLE_FAULT_INJECTOR("reslock_acquire_before_wait");
#endif
```
```sql
-- superuser:
-- test user session 1:
> SELECT pg_sleep(120);
-- test user session 2:
> SELECT version();
PANIC:  Waiting on lock already held! …
```
> Remove palloc() call in ResWaitOnLock

- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/test/regress/expected/qp_with_clause_optimizer.out
- src/test/regress/sql/qp_with_clause.sql
- Fix off-by-one error in fe8cb1fbdb
- Add optimizer_trace_fallback to catch issue in non-assert build
> Fix qp_with_clause testcase without asserts

- src/bin/pg_dump/pg_dump.h
Please see individual commits for details.
> pg_dump: Minor cleanup for TypeInfo

- src/backend/optimizer/prep/prepunion.c
Very straightforward, no test cases needed.
> Fix compiler warning introduced by 62b58c763.

- src/backend/access/transam/xact.c
> remove duplicate ereport to make the code neat

- src/backend/gporca/concourse/test_explain_pipeline.yml
- src/backend/gporca/concourse/test_orca_pipeline.yml
Updated and deployed pipelines:
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/explain_master
> [7X] Convert ORCA pipelines to use Vault variables

- src/backend/libpq/auth.c
When an LDAP user attempts to login to the GPDB database with bad credentials, the below message is "leaked" to the log.  This includes the LDAP server address, bind user (distinguished name), and bind password. 
Something like this:
> 2021-11-23 19:43:46.528056 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"LOG","00000","LDAP login failed for user ""uid=ajones2,ou=people,dc=dc1,dc=nebula,dc=local"" on server ""192.168.1.82"": Invalid credentials",,,,,,,0,,"auth.c",2384,
> 
> 2021-11-23 19:43:46.528139 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"FATAL","28000","LDAP authentication failed for user ""ajones2""","Connection matched pg_hba.conf line 92: ""host …
> LDAP bind credentials are leaked to log on failed login attempt

- src/backend/libpq/auth.c
When an LDAP user attempts to login to the GPDB database with bad credentials, the below message is "leaked" to the log. This includes the LDAP server address, bind user (distinguished name), and bind password.
Something like this:
> 2021-11-23 19:43:46.528056 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"LOG","00000","LDAP login failed for user ""uid=ajones2,ou=people,dc=dc1,dc=nebula,dc=local"" on server ""192.168.1.82"": Invalid credentials",,,,,,,0,,"auth.c",2384,
> 
> 2021-11-23 19:43:46.528139 UTC,"ajones2","ajones2",p12654,th-1991804800,"127.0.0.1","53756",2021-11-23 19:43:42 UTC,0,con17,,seg-1,,,,sx1,"FATAL","28000","LDAP authentication failed for user ""ajones2""","Connection matched pg_hba.conf line 92: ""host all …
>  LDAP bind credentials are leaked to log on failed login attempt 6X 

- src/test/regress/pg_regress.c
This is a backport of 7X commit: 937187e9789
Conflicts from missing commits addressed by ignoring changes from the
same:
* 1437824564f: pg_regress: Increase space available for test names.
* 55ca9a18342: Isolation2: run setup test internally as prerequisite for
running test
It is often observed in CI that a test that leaves the cluster in an
inconsistent state (e.g. primary-mirror pair is not in sync, or
primary has not finished crash recovery) cause several following tests
in the schedule to fail.  What's worse, the culprit test itself may be
reported as passed because its validation criteria did not include the
state of the cluster.  This has found to mislead debugging efforts,
ultimately waste of time.
To make debugging CI failures more efficient, this …
> [6X] Validate cluster state during regression tests

- src/backend/access/aocs/aocsam.c
- src/backend/catalog/pg_compression.c
- src/backend/cdb/cdbappendonlystoragewrite.c
- src/backend/utils/datumstream/datumstream.c
- src/backend/utils/datumstream/datumstreamblock.c
Please review commits piecemeal.
> DatumStream teardown: NULL out after pfree

- src/backend/access/aocs/aocs_compaction.c
Since we have removed toast for aocs tables and have already checked the visibility during scan tuples in aocs compaction, the visibility check code  in aocs compaction is unnecessary and can be removed.
> Remove visibility check code in aocs compaction

- gpdb-doc/markdown/ref_guide/modules/gp_pitr.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/gp_stat_archiver.html.md
Staging here:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/pitr_support/greenplum-database/GUID-ref_guide-modules-gp_pitr.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/pitr_support/greenplum-database/GUID-ref_guide-system_catalogs-gp_stat_archiver.html
> DOCS: Document new extension and view to support PITR

- gpdb-doc/markdown/install_guide/prep_os.html.md
install topic - add some guidance about setting ip fragmentation parameters.
need to confirm that these are the desired settings...
> docs - specify ipfragmentation sysctl.conf settings in install topic

- src/backend/executor/nodeModifyTable.c
Considering that the original command is UPDATE for a SplitUpdate, fire
INSERT and DELETE triggers may lead to the wrong action to be enforced.
And the triggers in GPDB may require cross segments data changes, disallow
the INSERT and DELETE triggers on a SplitUpdate.
> Disallow Insert and Delete triggers on SplitUpdate

- gpdb-doc/markdown/admin_guide/workload_mgmt.html.md
> [doc] add missing space and remove extra backquote

- gpAux/Makefile
Add support for LDAP in pgbouncer. More informations are written in
commit: 
https://github.com/greenplum-db/pgbouncer/commit/d83d349fba7f3de9edb5dca5f3e703796a32fe04
https://github.com/greenplum-db/pgbouncer/commit/97d0b46995820e51f4bddf61208b0fb3fccdf35d
> Update version of submodule pgbouncer for 6X.

- gpdb-doc/markdown/analytics/pl_python.html.md
- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
Python 3 Data Science Module instructions to be included shortly.
> Docs: Add plpython3u instructions to python topic

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/postgresql-hll.html.md
- gpdb-doc/markdown/ref_guide/toc.md
add some module docs for postgresql-hll.
> docs - content for new postgresql-hll module

- gpdb-doc/markdown/ref_guide/modules/gp_percentile_agg.html.md
docs for https://github.com/greenplum-db/gpdb/pull/13743 - upgrade is required if previously using the module.
(will add an xref to this topic in the release notes.)
> docs - add upgrade instructions for gp_percentile_agg

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
> docs - remove duplicate sentence in max_connections guc descript

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/include/gpopt/gpdbwrappers.h
- src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
This PR addresses 2 FIXMEs in the file (1 commit for each) and removes the collation related FIXME which would be addressed later when the collation work for ORCA is picked.
> Address FIXMEs in gpdbwrappers.cpp file

- gpMgmt/bin/gppylib/db/dbconn.py
> [doc] %s/itirate/iterate/g

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/libgpopt/src/base/CDefaultComparator.cpp
- src/test/regress/expected/generated_optimizer.out
- src/test/regress/sql/generated.sql
These commits are some more low-hanging FIXMEs that seemed straightforward.
> [ORCA] Address some merge FIXMEs

- gpMgmt/bin/generate-greenplum-path.sh
- gpMgmt/bin/pythonSrc/PyGreSQL-4.0/setup.py
- python-dependencies.txt
- src/backend/gporca/libgpos/include/gpos/utils.h
Make sure you have installed python 2.7:
```
brew install pyenv
pyenv install 2.7.18
```
Don't use the python 2.7 shipped with macOS.
> Make 6X_STABLE work with Apple M1

- src/backend/cdb/motion/ic_proxy.h
- src/backend/cdb/motion/ic_proxy_addr.c
- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_client.c
- src/backend/cdb/motion/ic_proxy_iobuf.c
- src/backend/cdb/motion/ic_proxy_main.c
- src/backend/cdb/motion/ic_proxy_peer.c
- src/backend/cdb/motion/ic_proxy_pkt_cache.c
- src/backend/cdb/motion/ic_proxy_router.c
- src/backend/cdb/motion/ic_tcp.c
This is mainly a backport of #14209. #14167 is also backported for convenience.
Dev-pipeline w/ all IC types: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_fix_proxy_logging
> [6X] Revamp ic-proxy logging

- src/backend/cdb/dispatcher/cdbconn.c
The QE notice message might be truncated because MPPnoticeReceiver()
limited message lenght about 800 bytes sent to the client. The client
should not see an incomplete notice message.
This commit changes its behaviour, it allows QE messages of any length
(include QE identifier) to send to the client.
> Forward complete QE notice messages

- src/bin/pg_dump/pg_dump.c
- src/bin/pg_upgrade/info.c
- src/bin/pg_upgrade/pg_upgrade.c
- src/bin/pg_upgrade/test_gpdb_pre.sql
Resolves several GPDB_12_MERGE_FIXMEs in pg_dump and pg_upgrade codebase.
> Resolve pg_dump/pg_upgrade FIXMEs

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
the data is always encrypted with gpfdists.
> docs - clarify the description of the verify_gpfdists_cert guc

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/test/aocsam_test.c
- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/backend/access/brin/brin.c
- src/backend/access/common/reloptions.c
- src/backend/access/common/reloptions_gp.c
- src/backend/access/gin/ginutil.c
- src/backend/access/gist/gistutil.c
- src/backend/commands/cluster.c
- src/include/access/reloptions.h
> Fix several memory leaks

- gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
- gpdb-doc/markdown/admin_guide/expand/expand-planning.html.md
- gpdb-doc/markdown/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.html.md
- gpdb-doc/markdown/admin_guide/highavail/topics/g-overview-of-master-mirroring.html.md
- gpdb-doc/markdown/admin_guide/highavail/topics/g-overview-of-segment-mirroring.html.md
- gpdb-doc/markdown/admin_guide/intro/about_ha.html.md
- gpdb-doc/markdown/admin_guide/intro/about_loading.html.md
- gpdb-doc/markdown/admin_guide/intro/about_utilities.html.md
- gpdb-doc/markdown/admin_guide/intro/arch_overview.html.md
- gpdb-doc/markdown/admin_guide/load/topics/transforming-xml-data.html.md
- gpdb-doc/markdown/admin_guide/managing/backup-main.html.md
- gpdb-doc/markdown/admin_guide/query/topics/gp-mapreduce.html.md
- gpdb-doc/markdown/admin_guide/query/topics/parallel-proc.html.md
- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-overview.html.md
- gpdb-doc/markdown/admin_guide/wlmgmt_intro.html.md
- gpdb-doc/markdown/admin_guide/workload_mgmt.html.md
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/analytics/graph.html.md
- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/analytics/overview.html.md
- gpdb-doc/markdown/analytics/pl_container.html.md
- gpdb-doc/markdown/best_practices/ha.html.md
- gpdb-doc/markdown/install_guide/preinstall_concepts.html.md
Used existing graphics title text where available.
> Doc - Add missing alt text to graphics

- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/sql/partition_pruning.sql
Commit 76379b08d6 finishes the feature to allow SPE plans to
show "Partitions selected: 1 (out of 5)". Just forget to update
the test case partition_pruning. This commit removes
get_selected_parts and related FIXME.
> Remove get_selected_parts FIXME.

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/install_guide/platform-requirements.html.md
Creates a note based on the research done on HT. 
JIRA [GPDOCS-41](https://jira.eng.vmware.com/browse/GPDOCS-41)
> Docs- hyperthread note - JIRA gpdocs-41

- gpdb-doc/markdown/analytics/pl_container.html.md
- gpdb-doc/markdown/analytics/pl_container_using.html.md
Add requirements and instructions for CUDA functions in PL/Container Python.
HTML of this PR available at https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/cuda/greenplum-database/GUID-analytics-pl_container_using.html#developing-cuda-api-functions-with-plcontainer-9
> Docs - CUDA suport for PL/Container

- src/backend/postmaster/postmaster.c
Greenplum starts several background workers, including `sweeper process`. Such worker doesn't use `BGWORKER_BACKEND_DATABASE_CONNECTION` flag, which means `do_start_bgworker()` only calls `AssignPostmasterChildSlot()` instead of fully-fledged `assign_backendlist_entry()`. This, in turn, means new worker not added to `BackendList`, so `CountChildren()` not counts it.
The problem is `canAcceptConnections()` allows connection of new backend even `PMChildFlags` array is overflowed, which cause postmaster hang.
To reproduce a problem I wrote a small program
https://github.com/RekGRpth/pg_ddos
I run it on demo cluster with the following settings
```
gpconfig -c gp_debug_linger -v 10s -m 10s
```
using the following command
```
DDOS_COUNT=100 ./pg_ddos
```
Postmaster crashed after 10 seconds.
The …
> ADBDEV-3108: Postmaster process may exhaust all signal slots under intensive connections pressure (6X)

- SECURITY.md
> Fix the formatting issue for SECURITY.md

- concourse/pipelines/pr_pipeline.yml
> Update PR base pipeline

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/README.md
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/test/regress/greenplum_schedule
- src/test/regress/input/uao_dml/uao_dml_unique_index_delete.source
- src/test/regress/input/uao_dml/uao_dml_unique_index_update.source
- src/test/regress/output/uao_dml/uao_dml_unique_index_delete.source
- src/test/regress/output/uao_dml/uao_dml_unique_index_update.source
> DELETE/UPDATE on AO/CO tables with unique indexes

- concourse/pipelines/pr_pipeline.yml
> Update the GP7  PR pipeline for image resource

- concourse/scripts/common.bash
- concourse/tasks/setup_for_gpexpand_to_make_new_gpdb.yml
- gpAux/Makefile
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
> [Releng] Support rocky8 platform on gpdb7

- src/backend/commands/cluster.c
The toast tables need to keep existing `relfrozenxid` value unchanged, when it's working with append-optimized tables.
See the relative comment:
```
/* Recursively swap the contents of the toast tables */
/*
* CLUSTER operation on append-optimized tables does not
* compute freeze limit (frozenXid) because AO tables do not
* have relfrozenxid.  The toast tables need to keep existing
* relfrozenxid value unchanged in this case.
* 
*/
```
> Resolve GPDB_12_MERGE_FIXMEs: assertion in swap_relation_files in cluster.c

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
> DOCS: Document ALTER TABLE column encodings feature

- src/backend/cdb/motion/ic_proxy_addr.c
When we use ic-proxy and execute the following sql,
An error may be thrown. But this is flaky.
ERROR:  interconnect error: connection closed prematurely
select gp_segment_id, pg_reload_conf() from gp_dist_random('gp_id');
QE execute pg_reload_conf will send a signal to other processes to reload
the config file, then ic-proxy will receive a signal and call
ic_proxy_server_on_signal to process.
If the value of gp_interconnect_proxy_addresses is not ordered by dbid,
ic_proxy_unknown_addrs loaded from config file and sorted by dbid is
different from ic_proxy_prev_addrs, some addr will be added in 
ic_proxy_removed_addrs, these addrs will be disconnected after reloading
config file, Actually gp_interconnect_proxy_addresses is not modified.
This may lead to some cases failing when reading data …
> fix ic-proxy mis-disconnect addrs after reloading config file

- src/backend/catalog/oid_dispatch.c
- src/backend/commands/matview.c
- src/backend/optimizer/util/clauses.c
- src/include/catalog/oid_dispatch.h
- src/test/regress/expected/oid_consistency.out
- src/test/regress/sql/oid_consistency.sql
Backport PR https://github.com/greenplum-db/gpdb/pull/14472 to 6X_STABLE
Co-authored-by: Zhenghua Lyu <kainwen@gmail.com>
> [6X] Refactor SaveOidAssignments and RestoreOidAssignments logic

- src/test/isolation2/expected/resgroup/resgroup_views.out
- src/test/isolation2/sql/resgroup/resgroup_views.sql
Fix the failed pipeline due to #13880
> fix resgroup views cases

- concourse/scripts/compile_gpdb.bash
> Only update PATH when PYTHONHOME39 not null

- src/test/isolation2/input/parallel_retrieve_cursor/concurrency.source
- src/test/isolation2/output/parallel_retrieve_cursor/concurrency.source
Ref: https://www.postgresql.org/docs/current/sql-altersystem.html
> RESET newly added GUC to pass binary swap tests

- src/backend/cdb/dispatcher/cdbdisp_async.c
- src/test/regress/input/dispatch.source
- src/test/regress/output/dispatch.source
Port https://github.com/greenplum-db/gpdb/pull/14504 to main branch.
> Skip invalid socks in checkDispatchResult()

- src/bin/pg_dump/common.c
- src/bin/pg_dump/dumputils.c
- src/bin/pg_dump/pg_backup.h
- src/bin/pg_dump/pg_backup_db.c
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/pg_dump.h
- src/bin/pg_dump/pg_dump_sort.c
- src/bin/pg_dump/pg_dumpall.c
This PR is backporting a subset of the PG upstream performance improvements to pg_dump from https://github.com/greenplum-db/gpdb/pull/13791
Relevant changes from upstream are detailed in the individual commit messages.
> 6X pg_dump: Backport performance improvements

- src/backend/executor/nodeDynamicBitmapHeapscan.c
- src/backend/executor/nodeDynamicSeqscan.c
- src/include/nodes/execnodes.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/expected/qp_dropped_cols.out
- src/test/regress/expected/qp_dropped_cols_optimizer.out
- src/test/regress/sql/gporca.sql
- src/test/regress/sql/qp_dropped_cols.sql
> Fix failure when DynamicSeqScan has a subPlan 

- concourse/tasks/run_explain_suite.yml
- src/backend/gporca/concourse/test_explain_pipeline.yml
We also needed to move the image declaration to the pipeline file since the image now has a password.
> Update Orca explain pipeline for rhel8 changes

- src/backend/optimizer/util/predtest.c
- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/sql/partition_pruning.sql
Add test case and fix compile warning for commit:f25190de2b3b3e063af2274629673a9c48ebff50
> Add test case for fix wrong results caused by over-eager constraint exclusion

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/gpfdist.c
Eliminate compiler warnings caused by PR [https://github.com/greenplum-db/gpdb/pull/14144](https://github.com/greenplum-db/gpdb/pull/PR). The PR is about the compression transmission of the gpfdist external table.
> fix compiler warning caused by gpfdist compression external table

- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/input/resgroup/resgroup_cpuset.source
- src/test/isolation2/output/resgroup/resgroup_cpuset.source
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Fix dev pipline failure of previous PR https://github.com/greenplum-db/gpdb/pull/14332.
> Fix resource group cpuset test case

- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
kiwi and kiwisolver are two differnt projects.
https://pypi.org/project/kiwi/
https://pypi.org/project/kiwisolver/
> docs - Fix doc for python data science bundle

- src/backend/optimizer/plan/planner.c
This is a PR2 depending on another one, please first review PR1 https://github.com/greenplum-db/gpdb/pull/14354
commits for current PR2:
- 6dc0d83f0b inited JIT support for plan generated by ORCA
commits of  PR1:
- fc0f289e46 JIT jobs updated: add _jit to jobs with JIT set to on.
- a3cd9793bf tuned jit to false in guc.c.
- 6ca44eff15 fixed broken tests due to variable JIT gucs in Explain Settings field
- fa1cfe0619 fixed broken auto_explain test due to JIT compilation
- de76b350d8 fixed the broken tests caused by DEBUG messages from JIT
- b13bc21c15 JIT compiled in pipeline and job icw_jit_rhel8 inited for JIT tests 
- a2d4e48201 add guc gp_enable_mute_jit_explain to benifit installcheck & pipeline
- a9c6c71eb7 Prepare for forthcoming LLVM 13 API change.
- aa4735feb1 jit: configure: …
> ORCA with JIT enabled

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RULE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RULE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_RULE.html.md
no new features, mostly minor edits.
> docs - ALTER/CREATE/DROP RULE sql ref page updates

- concourse/scripts/setup_gpadmin_user.bash
- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Incorporating review comments from 6x PR 
https://github.com/greenplum-db/gpdb/pull/14506
Ran the sanity pipeline and gpinitsystem tests are green.
> gpinitsystem tests updates for parity with 6x

- src/backend/commands/resgroupcmds.c
- src/include/utils/resgroup.h
This PR is for refactor and simplify some code of previous PR https://github.com/greenplum-db/gpdb/pull/14332
> simplify RG cpuset seperated by coordinator/segment

- gpdb-doc/markdown/ref_guide/modules/gp_parallel_retrieve_cursor.html.md
> docs - fix bad xref to guc

- gpdb-doc/markdown/ref_guide/system_catalogs/pg_proc.html.md
> docs - correct a misspelling in pg_proc reference

- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
this link was causing a build failure.
> docs - fix a bad link

- gpdb-doc/markdown/ref_guide/modules/uuid-ossp.html.md
> docs - need quotes when create uuid-ossp extension

- gpdb-doc/markdown/install_guide/data_sci_pkgs.html.md
fix the file name and ref to the current version.
> docs - correct an xref to pxf topic

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14642, add reference info for new GPORCA guc.
> docs - ref info for new optimizer_discard_redistribute_hashjoin guc

- concourse/scripts/common.bash
- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/cdb/cdbappendonlystorageread.c
- src/backend/storage/buffer/bufmgr.c
- src/include/access/aocssegfiles.h
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/include/storage/bufmgr.h
- src/test/isolation2/expected/ao_index_build_progress.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/ao_index_build_progress.sql
Please see individual commits for details.
> ao/co: Report scan progress for CREATE INDEX

- src/backend/executor/execMain.c
Issue #12690, the code path in `standard_ExecutorStart` didn't handle
the exception of `Policy*AssignOperatorMemoryKB`, which may cause the OOM
exception not handled in `standard_ExecutorStart` but thrown to upper
`PortalStart` methods, in that case, the hook needed by GPCC will not
be called. This commit fixed the issue.
> Handling exception to call the hook in standard_ExecutorStart

- configure
- configure.in
- src/backend/regex/regexec.c
- src/include/port/atomics/arch-x86.h
- src/include/storage/s_lock.h
Backports https://github.com/postgres/postgres/commit/03bf971d2dc701d473705fd00891028d140dd5ae and resolves FIXME in `configure.in`
Discussion:
https://www.postgresql.org/message-id/20220308185902.ibdqmasoaunzjrfc@alap3.anarazel.de
> Remove uses of register

- contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
- contrib/postgres_fdw/postgres_setup.bash
- contrib/postgres_fdw/sql/gp2pg_postgres_fdw.sql
Orca now supports foreign scans, so we can enable this test suite
> Enable postgres_fdw test for Orca

- src/backend/commands/extension.c
Fix some comments format for PR #14534.
> Fix comments for PR #14534.

- src/test/regress/expected/aoco_projection.out
- src/test/regress/sql/aoco_projection.sql
Fix syntax error in regress test
> Fix aoco_projection test

- src/backend/commands/extension.c
- src/test/modules/test_extensions/Makefile
- src/test/modules/test_extensions/expected/test_extensions.out
- src/test/modules/test_extensions/sql/test_extensions.sql
- src/test/modules/test_extensions/test_ext_cau--1.0--1.1.sql
- src/test/modules/test_extensions/test_ext_cau--1.0.sql
- src/test/modules/test_extensions/test_ext_cau--1.1.sql
- src/test/modules/test_extensions/test_ext_cau--unpackaged--1.0.sql
- src/test/modules/test_extensions/test_ext_cau.control
- src/test/regress/expected/create_extension_fail.out
- src/test/regress/sql/create_extension_fail.sql
Back-port of https://github.com/greenplum-db/gpdb/pull/14534.
> [6X_STABLE] [backport] CREATE EXTENSION in explicit transaction fails on assertion on executors

- gpdb-doc/markdown/ref_guide/feature_summary.html.md
greenplum 7 doesn't support logical replication, so doesn't support the ALTER/CREATE/DROP PUBLICATION and SUBSCRIPTION commands.
> docs - PUBLICATION, SUBSCRIPTION not supported

- gpdb-doc/markdown/ref_guide/sql_commands/REINDEX.html.md
remove statement per review comment in https://github.com/greenplum-db/gpdb/pull/14430
> docs - remove outdated statement from REINDEX ref page (6x)

- src/bin/gpfdist/gpfdist.c
> fix compiler warning

- src/backend/cdb/cdbsubselect.c
- src/test/regress/expected/notin.out
- src/test/regress/expected/notin_optimizer.out
- src/test/regress/sql/notin.sql
Backport PR https://github.com/greenplum-db/gpdb/pull/14859 to 6X.
> (6x backport) Shortcut when joinaliasvars' element is not Var during NOT-IN pullup.

- gpdb-doc/markdown/ref_guide/sql_commands/DROP_OWNED.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/REASSIGN_OWNED.html.md
> docs - sql ref page updates for DROP/REASSIGN OWNED

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-210-fix-platform-requirements/greenplum-database/GUID-install_guide-platform-requirements-overview.html
> DOCS: Update Platform Requirements topic  for 7x

- src/backend/storage/ipc/procarray.c
Upstream introduced group XID clearing in 9.6, and gxiong used in Greenplum.
But currently, Greenplum resets the proc entry without the lock after the
regular or group XID clearing. This commit gets the lock back.
commit 0e141c0fbb211bdd23783afa731e3eef95c9ad7a
Author: Robert Haas <rhaas@postgresql.org>
Date:   Thu Aug 6 11:52:51 2015 -0400
Reduce ProcArrayLock contention by removing backends in batches.
When a write transaction commits, it must clear its XID advertised via
the ProcArray, which requires that we hold ProcArrayLock in exclusive
mode in order to prevent concurrent processes running GetSnapshotData
from seeing inconsistent results.  When many processes try to commit
at once, ProcArrayLock must change hands repeatedly, with each
concurrent process trying to commit waking up to …
> Reset proc entry with the lock in ProcArrayEndTransaction()

- src/backend/gpopt/relcache/CMDProviderRelcache.cpp
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
- src/include/gpopt/relcache/CMDProviderRelcache.h
Fixes some compiler warnings in Orca code. 
Fixes https://github.com/greenplum-db/gpdb/issues/14936
> Fix unused variable compiler warnings

- gpdb-doc/markdown/admin_guide/wlmgmt.html.md
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/analytics/pl_container.html.md
- gpdb-doc/markdown/analytics/pl_container_using.html.md
- gpdb-doc/markdown/analytics/pl_java.html.md
- gpdb-doc/markdown/analytics/pl_r.html.md
- gpdb-doc/markdown/analytics/postGIS.html.md
- gpdb-doc/markdown/analytics/postgis-upgrade.html.md
- gpdb-doc/markdown/install_guide/ansible-example.html.md
- gpdb-doc/markdown/install_guide/init_gpdb.html.md
- gpdb-doc/markdown/install_guide/install_gpdb.html.md
- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
- gpdb-doc/markdown/install_guide/prep_os.html.md
- gpdb-doc/markdown/install_guide/upgrading.html.md
- gpdb-doc/markdown/install_guide/verify_sw.html.md
- gpdb-doc/markdown/utility_guide/ref/plcontainer-configuration.html.md
Also update some gpdb 6 references to 7.
> Remove centos/ubuntu and older RHEL information

- concourse/scripts/compile_gpdb_remote_windows.bash
The job is flaky, so need to show the script to show more info
> [Releng][7X]Show debug info for compile_gpdb_remote_windows

- concourse/scripts/compile_gpdb_remote_windows.bash
The job is flaky, so need to show the script to show more info
> [Releng][6X]Show debug info for compile_gpdb_remote_windows

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/scripts/common.bash
- gpAux/Makefile
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Co-authored-by: Anusha Shakarad <shakarada@vmware.com>
Co-authored-by: Ning Wu <ningw@vmware.com>
> Adding Oracle8 platform for GPDB6

- concourse/vars/common_prod.yml
> Add the reduced-frequency-trigger time for oel8

- gpMgmt/bin/gpload.py
rename master to main 
**Signed-off-by:** Yongtao Huang <yongtaoh@vmware.com>
> Inclusive Terminology for Greenplum 7 in gpload

- src/bin/gpfdist/doc/init
- src/bin/gpfdist/doc/start
rename master to coordinator in gpfdist
**Signed-off-by:** Yongtao Huang [yongtaoh@vmware.com](mailto:yongtaoh@vmware.com)
> inclusive terminology for Greenplum 7 in gpfdist

- concourse/pipelines/gen_pipeline.py
> Changing the dist variable from oel to oel8

- src/test/recovery/t/019_replslot_limit.pl
Fixup commit d28d587847f0baf267fb1211be8a8028d49b2919
This will address the CI failures
> Modify 019_replslot_limit.pl test for Greenplum, take 2

- src/backend/commands/tablecmds.c
GPDB has specific ALTER TABLE commands for partition tables, which
are handled differently than the other AT commands: instead of being
executed on QD first and then dispatched to QEs after all the other
commands are done, they are dispatched immediately in ATExecCmd()
and executed on QEs at the same time as QD. This results in the
possibility that AT commands could be executed in different order
in QEs than in QD.
The FIXME comment suggests to make those AT partition commands
same as other AT commands, but that could be very invasive, e.g.:
1. The AT partition commands generate a lot of subcommands that
are not AT subcommands like CREATE TABLE (see ATExecGPPartCmds()).
We cannot put them in the AT workqueue as AT subcommands.
At minimal we would need separate code to split them off the …
> Resolve a FIXME in prepare_AlterTableStmt_for_dispatch()

- src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
- src/test/regress/expected/qp_union_intersect.out
- src/test/regress/expected/qp_union_intersect_optimizer.out
- src/test/regress/sql/qp_union_intersect.sql
Various Orca FIXMEs. See individual commits for details
> Address a few Orca FIXMEs

- src/backend/access/aocs/aocsam.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/parser/parse_partition_gp.c
> Suppress compiler warnings in release build.

- gpdb-doc/markdown/install_guide/migrate-oss-to-vmware.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-182-migrate-OSS-commercial/greenplum-database/GUID-install_guide-migrate-oss-to-vmware.html
> DOCS: Add topic on migrating from OSS GPDB to commercial GPDB

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/scripts/common.bash
- concourse/vars/common_prod.yml
- gpAux/Makefile
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Remove the non exist output of os_id, for oel7 and oel8, the os_id will return centos
[GPR-1090]
> [Releng][6X]Adding support for oel7 for gpdb6

- gpMgmt/bin/gppylib/operations/package.py
> [6X] fix: unsafe tar extract for gppkg

- src/backend/commands/explain.c
- src/backend/commands/explain_gp.c
- src/include/nodes/execnodes.h
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/expected/select_parallel.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/explain_format.sql
- src/test/regress/sql/select_parallel.sql
- src/test/regress/sql/subselect.sql
> Resolve GPDB_12_MERGE_FIXMEs in explain.c / explain_gp.c

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-182-migrate-OSS-commercial/greenplum-database/GUID-ref_guide-config_params-guc-list.html#gp_resource_group_cpu_priority
> DOCS: Document gp_resource_group_cpu_priority GUC

- doc/src/sgml/ref/vacuum.sgml
Add help text for the AO_AUX_ONLY option to the sgml docs.
> Update vacuum sgml docs for ao_aux_only

- gpdb-doc/markdown/analytics/madlib.html.md
new version available.  i am assuming that we distribute a rhel7 version.
> docs - madlib 1.21.0 (6x)

- src/bin/pg_dump/pg_dump.c
greenplum-db/gpdb@8259899 removed columnstore from pg_appendonly, but neglected to consider pg_dump compatibility
with pre GPDB7 servers, where the field still exists and is used to determine ao_column/ao_row AM.
This commit now populates a table's amname field from pg_appendonly.columnstore when the server version is older than GPDB7.
> Fix pg_dump AO tables from GPDB5/6 server.

- concourse/scripts/test_upgrade.bash
For the pg_upgrade CI job, we need to run ANALYZE on the catalog after loading in the dump file so that the planner can generate good query plans. Without the ANALYZE, the query plans will be generated with bad statistics which can cause severe slowness in some of the pg_dump catalog queries.
Context:
The pg_upgrade CI job used to take about 23 minutes to run but jumped to about 1.5 hours recently due to a pg_dump catalog query having a bad plan.  This PR brings the testing time back to about 23 minutes.
> Run analyzedb after loading dump file in the pg_upgrade CI job

- concourse/vars/common_dev.yml
> Support running windows compilation job on dev pipeline

- src/backend/utils/mmgr/redzone_handler.c
In previous version, we disable red-zone check for resource group, the resgroup use cgroup to clean the process which consumes memory exceeds the rg's configuration.
For the new version for resgroup, we use redZoneChunks to determine whether the current process is in red-zone or not, so remove the resGroupId check.
> remove resGroupId check in runaway detector

- src/backend/commands/explain.c
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
> Fix flaky case and compiler warnings introduced from explain fixme PR.

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
cherry pick of https://github.com/greenplum-db/gpdb/pull/14717 commit for 6x docs.
> docs - ref info for new optimizer_discard_redistribute_hashjoin guc (6x)

- src/backend/access/heap/heapam_handler.c
Backends load or build relcache when starting (process title conveys "startup"). If relcache init file is present then can just load relcache from it. In absence of the file (file is deleted on sinval message), need to perform sequential scan on pg_class, pg_attribute for locating tuples related to these critical system tables and indexes to build the relcache, refer RelationCacheInitializePhase3().
General expectation is tuples corresponding to these critical catalog tables (created during bootstrap and with xmin=1) will be present in starting blocks and hence seqscan and tuple visibility will not be costly to perform during backend startup. Though occasionally in production setups these bootstrap tuples were found in very high block numbers for pg_attribute. As a effect from this, …
> Avoid syncscan for vacuum full and cluster for catalog tables

- src/backend/executor/functions.c
- src/test/regress/expected/qp_functions.out
- src/test/regress/sql/qp_functions.sql
Port of https://github.com/greenplum-db/gpdb/pull/15096 to main
> Protect function execution in entrydb QE

- gpdb-doc/markdown/ref_guide/modules/isn.html.md
- gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
Staging here:
https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-326-extensions-updates/greenplum-database/GUID-ref_guide-modules-isn.html
https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-326-extensions-updates/greenplum-database/GUID-ref_guide-modules-timestamp9.html
> DOCS: Add datatypes info for timestamp9 extension and add topic for isn extension

- concourse/pipelines/templates/gpdb-tpl.yml
> Support test_gpdb_clients_windows job run in dev concourse

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Dev pipeline with gpcheckat box: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/checkcat_attrib
> gpcheckcat: Improvements to aoseg vpinfo check

- src/backend/executor/execUtils.c
Fixes https://github.com/greenplum-db/gpdb/issues/14348
> Fix leaking hash tables when inserting into AO tables

- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
The PR is related to regress test external_table and about handling different error messages on different platform.
> Minor fix for regress external_table

- src/backend/access/common/reloptions.c
- src/backend/access/common/reloptions_gp.c
- src/backend/catalog/pg_appendonly.c
- src/backend/commands/tablecmds.c
- src/backend/utils/misc/guc_gp.c
- src/include/access/reloptions.h
Some logic for AO reloptions handling is super confusing which makes modification very painful (a hindsight from https://github.com/greenplum-db/gpdb/pull/14713). Trying to simplify a few things here. Please review each commit individually.
There should be no behavior change.
> Refactor AO reloptions related code

- src/backend/cdb/cdbbufferedappend.c
- src/backend/cdb/cdbbufferedread.c
- src/test/isolation2/input/uao/collected_stats_views.source
- src/test/isolation2/output/uao/collected_stats_views.source
> Collect I/O timing stats for AO/AOCO tables

- src/backend/cdb/dispatcher/cdbconn.c
> fix: typo of allocated

- src/backend/cdb/motion/ic_udpifc.c
6X backport of PRs  [#15107](https://github.com/greenplum-db/gpdb/pull/15107) and [#15129](https://github.com/greenplum-db/gpdb/pull/15129)
> [6X] Enhance logging for dispatch conn liveness checks

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a partial backport of #15211 (don't need the second commit, see Ashwin's explanation below). There were minor conflicts, please refer to the commit message for more information.
6X dev pipeline with gpcheckcat box: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_checkcat_attrib
> [6X] gpcheckcat: Improvements to aoseg vpinfo check

- src/test/isolation2/input/uao/collected_stats_views.source
- src/test/isolation2/output/uao/collected_stats_views.source
This eliminates diff caused by different number of spaces
> Fix space diff with matchsubs

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/tablefunc.html.md
- gpdb-doc/markdown/ref_guide/toc.md
add an overview topic for the tablefunc module.
> docs - add content for tablefunc module (6x)

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-161-bypass-catalog-query/greenplum-database/GUID-ref_guide-config_params-guc-list.html#gpresourcegroupbypasscatalogquery-127
> DOCS: New resource_group_bypass_catalog_query GUC

- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
Modified partials path to add vpshere directory, which is updated on the gpvirtual repository.
> modified partials path

- src/bin/pg_basebackup/t/010_pg_basebackup.pl
A previous commit https://github.com/greenplum-db/gpdb/commit/4a33bb59dfc33566f04e18ab5e1f90b8e7461052 had changed the code so that WAL pages skipped by a forced WAL switch are zero-filled. This commit adds a test for this code change. Similar change was made to 6X_STABLE in this PR https://github.com/greenplum-db/gpdb/pull/14545
Test description:
-----------------
Ensure that when pg_basebackup is run, the last WAL segment file containing the BACKUP_END and wal SWITCH records match on both the primary and mirror segment. We want to ensure that all pages after the wal SWITCH record are all zeroed out. Previously, the primary segment's WAL segment file would have interleaved page headers instead of all zeros. Although the WAL segment files from the primary and mirror segments were …
> Add tests for ensuring WAL file is zeroed out

- src/backend/commands/explain_gp.c
For example:
```
postgres=# explain analyze verbose select * from test limit 10;
QUERY PLAN                                                            
---------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=35.50..35.67 rows=10 width=4) (actual time=16.941..16.944 rows=0 loops=1)
Output: c1
->  Gather Motion 3:1  (slice1; segments: 3)  (cost=35.50..36.01 rows=30 width=4) (actual time=15.436..15.438 rows=0 loops=1)
Output: c1
->  Limit  (cost=35.50..35.61 rows=10 width=4) (actual time=0.000..1.317 rows=0 loops=1)
Output: c1
->  Seq Scan on public.test  (cost=0.00..355.00 rows=32100 width=4) (actual time=0.000..0.029 rows=0 loops=1)
Output: c1
Settings: jit = 'on', …
```
> Print all JIT instrumentation in EXPLAIN ANALYZE VERBOSE mode

- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckresgroupimpl.py
As the title said, just fix the broken pipeline.
> Fix broken pipeline

- src/test/regress/expected/partition.out
- src/test/regress/expected/partition1.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
- src/test/regress/sql/partition1.sql
Both 'partition' and 'partition1' tests have test cases for MPP-13806 both of which create/drop a table named 'mpp13806'. Running them in parallel caused flakiness with an error:
```
alter table mpp13806 add partition test end (date '2008-01-01') exclusive;
+ERROR:  relation "mpp13806" does not exist
```
The log clearly shows that it's just that the two tests stepped each other's toes:
```
2023-04-19 20:53:01.875375 UTC,"gpadmin","regression",p45824,th-117626752,"[local]",,2023-04-19 20:52:25 UTC,0,con467,cmd1524,seg-1,,,,sx1,"LOG","00000","statement: CREATE TABLE mpp13806 (id int, date date, amt decimal(10,2)) 2023-04-19 20:53:01.905142 UTC,"gpadmin","regression",p46488,th-117626752,"[local]",,
2023-04-19 20:52:44 UTC,0,con474,cmd865,seg-1,,,,sx1,"LOG","00000","statement: drop table if …
```
> Merge redundant test cases in regress tests partition|partition1

- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_DATABASE.html.md
> docs - fix bad xref

- src/backend/access/transam/xlog.c
- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/expected/segwalrep/select_throttle.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/segwalrep/select_throttle.sql
- src/test/isolation2/sql/setup.sql
- src/tools/gdb/.gdbinit
This is a backport of https://github.com/greenplum-db/gpdb/pull/15436
> Fix syncrep off 6.23.x

- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
diskquota v2.2.1 will be releaseed soon.  refactor the upgrade docs so that they are not specific to 2.0 and 2.1.
> docs - refactor diskquota upgrade docs for new version

- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
Adding behave test cases for testing the changes in https://github.com/greenplum-db/gpdb/pull/15269.
> Behave test cases to test the value of TRUSTED_SHELL in gpcreateseg

- src/test/regress/expected/partition_join.out
fix pipeline for commit:75a35c7b289998919abedfd23e2c924888bd5396
> modify partition_join.out to fix pipeline

- gpAux/Makefile
Authored-by: Lucas Bonner <blucas@vmware.com>
> Adding ubuntu18 back to gpAux so that it can compile

- src/backend/commands/createas.c
- src/backend/commands/explain.c
- src/backend/commands/tablecmds.c
- src/backend/tcop/pquery.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/resgroup.h
Some refactor work to make code a little better.
No test cases added because we already have
cases covery the feature and this PR is just
doing refactor work.
> Refactor unassign and bypass logic for resgroup.

- src/backend/cdb/cdbgroupingpaths.c
> Fix code indent.

- src/backend/commands/explain.c
See issue https://github.com/greenplum-db/gpdb/issues/15551.
> Fix several compile warnings.

- contrib/pg_upgrade/greenplum/check_gp.c
There is a bug in the 5X parser (gram.y) where the first N-1 columns is
considered a separate column list that has no checking. Only the last
entry in the distribution column list will be checked for duplication.
Because of this, it is possible to distribute tables on duplicated
columns like the examples below.
CREATE TABLE foo (a int, b int) DISTRIBUTED BY (a, a, a, a, b);
CREATE TABLE bar (a int, b int, c int) DISTRIBUTED BY (a, b, a, b, c);
This is fixed in GPDB6.
reference fix commit:
https://github.com/greenplum-db/gpdb/commit/242783ae9f573bb03da3d89dc689c6743dfce510
> Add pg_upgrade check for duplicated distribution columns

- gpMgmt/bin/gpload.py
Authored-by: Bradford D. Boyle <bradfordb@vmware.com>
> Remove unused Progress class from gpload

- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
We need to analyze the table, otherwise auto-analyze may kick in and change the plan.
> Fix flaky test

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-578-system-views-phase2/greenplum-database/GUID-ref_guide-system_catalogs-catalog_ref-views.html
> DOCS: Add meat of  MPP-ized system views and note which summary views the relevant views are summarized in

- concourse/pipelines/templates/gpdb-tpl.yml
> Fixup:  Create and test Rocky9/Rhel9/Oel9 environments for Greenplum7

- src/backend/cdb/cdbvars.c
- src/backend/commands/user.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/test/isolation2/expected/resgroup/resgroup_bypass.out
- src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_bypass.sql
- src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
There are 3 simple commits inside this PR. Please review one by one.
> Rg misc refinement.

- src/backend/executor/nodeDynamicIndexscan.c
It's a back-port of https://github.com/greenplum-db/gpdb/pull/15619
> Fix dangling pointer in ExecDynamicIndexScan()

- gpdb-doc/markdown/analytics/pl_python.html.md
> doc: drop python2.7 for plpython doc

- concourse/pipelines/templates/gpdb-tpl.yml
> Remove rocky9 server_src_rc and keep only server_src_rc for rocky8 and refactor the code

- src/backend/cdb/cdbtargeteddispatch.c
In a recent pgbench test, we found perf regression.
After tested, its dues to the commit: https://github.com/greenplum-db/gpdb/commit/e8deb29ae0, and the bottleneck is the indexscan on systable.
Here is the flame graph of one QD in pgbench:
So, let's simply hardcode the opfamily of `GpSegmentId` here since it's a stable type in GP. And confirmed it solves the perf regression.
(Will port to 6x later)
> Hardcode the opfamily of GpSegmentId in GetContentIdsFromPlanForSingleRelation()

- concourse/tasks/run_explain_suite.yml
We store compressed stats for this workload since the raw data is over 100M. Have to decompress before running pipeline.
> Unzip 7X stats for explain pipeline

- src/backend/cdb/cdbpullup.c
- src/include/cdb/cdbpullup.h
- src/test/regress/expected/bfv_subquery.out
- src/test/regress/expected/bfv_subquery_optimizer.out
- src/test/regress/sql/bfv_subquery.sql
There are two commits in this PR, each contains its own commit messages.
Please review one by one. Thanks.
------
Fix issue https://github.com/greenplum-db/gpdb/issues/15079
> Refactor cdbpullup missing var walker

- gpdb-doc/markdown/analytics/pl_python.html.md
The GUC SET doesn't need LOAD before.
Also fixed a typo.
> Fix plpython3.python_path doc

- src/backend/nodes/nodeFuncs.c
- src/backend/utils/resgroup/resgroup.c
- src/backend/utils/resource_manager/resource_manager.c
> fix misc rg issue

- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v1.out
fix the icw pipeline for resgroup
> fix indent and udf's ending whitespace for resgroup/resgroup_auxiliary_tools_v1

- contrib/pageinspect/brinfuncs.c
- contrib/pageinspect/expected/brin.out
- contrib/pageinspect/pageinspect--1.8--1.9.sql
- src/backend/access/brin/brin.c
- src/backend/access/brin/brin_inclusion.c
- src/backend/access/brin/brin_minmax.c
- src/backend/access/brin/brin_tuple.c
- src/include/access/brin_tuple.h
- src/test/isolation2/expected/ao_partial_scan.out
- src/test/isolation2/expected/brin_heap.out
- src/test/isolation2/output/uao/brin.source
- src/test/modules/brin/expected/summarization-and-inprogress-insertion.out
- src/test/modules/brin/specs/summarization-and-inprogress-insertion.spec
Please review the cherry-picks individually.
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/brin_backports
> brin: Backport critical fixes to NULL handling

- src/backend/cdb/cdbpullup.c
- src/test/regress/expected/bfv_subquery.out
- src/test/regress/expected/bfv_subquery_optimizer.out
- src/test/regress/sql/bfv_subquery.sql
There are two commits in this PR:
1. revert a previous commit
2. add regression cases introduced by the above commit.
> Revert aff2a34333

- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a post commit of [62bcf77](https://github.com/greenplum-db/gpdb/commit/62bcf771aef01841903abe96bfd9b2c3b6a5d91d)
> Post fix: replace 'egrep' with 'grep -E' in gpMgmt

- contrib/Makefile
Add make clean command for postgres_fdw.
This commit is supplement for the last commit e7ea88e6ada4dc3fa281bb37b8eee4094d5e7386.
> Add make clean command for postgres_fdw.

- src/test/recovery/t/002_archiving.pl
Commit 700cad0 add 'has_streaming => 1' when make a standby node. This will start a walreceiver process to receive the wal log from primary node, rather than just store its contents on the archives of the primary. In this way, the inserted 2000 rows can all have been present on standby node.
Revert the enable streaming change when create standby, append conn info to the postgresql.conf after pass the first check and restart standby node.
> Fix flacky case 002_archiving.pl

- gpdb-doc/markdown/analytics/postgis-upgrade.html.md
- gpdb-doc/markdown/install_guide/prep_os.html.md
- gpdb-doc/markdown/ref_guide/removed-objects.html.md
Fix typos for 6X_STABLE branch documentation
> Docs: fixed Greenplum typos for 6X branch

- contrib/pg_upgrade/pg_upgrade.c
- src/bin/pg_dump/pg_dump.c
When running pg_dump with --binary-upgrade, the relfrozenxids are preserved for each user table. However, there were many issues with the logic:
1. For partition tables, there was no preservation SQL commands outputted for subroot and child partitions. Only the root partition had a SQL command be outputted to preserve its relfrozenxid.
2. For AO/CO tables, the relfrozenxid does not need to be preserved since AO/CO tuples do not contain xid info.
3. After pg_upgrade runs pg_restore to recreate objects and update relfrozenxids as per the dump file, pg_upgrade later bulk updates pg_class to set the relfrozenxids to the source segment's datfrozenxid for applicable pg_class tuples... which seemingly makes the relfrozenxid preservation SQL commands in the dump file redundant.
Because of the …
> [6X] Do not preserve relfrozenxid of user tables for pg_dump --binary-upgrade

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/vars/common_prod.yml
- gpAux/Makefile
- gpcontrib/orafce/pipe.c
> Support RHEL9 platform for GP6 clients

- concourse/vars/common_prod.yml
> Update madlib ci tag filter to rel/v1*

- concourse/vars/common_prod.yml
> [Releng]Add missing vars for 6X_STABLE_oel9 pipeline

- src/backend/catalog/aclchk.c
- src/include/utils/acl.h
Add this hook to capture grant event for pgaudit extension on gpdb_6X
> Add grant_hook to capture grant event.

- src/backend/storage/lmgr/lock.c
- src/backend/utils/resscheduler/resqueue.c
- src/include/storage/lock.h
- src/test/isolation2/expected/resource_queue.out
- src/test/isolation2/sql/resource_queue.sql
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/resq_holdable
> Fix statement leak for holdable cursors

- concourse/scripts/ic_gpdb_resgroup.bash
- concourse/scripts/ic_gpdb_resgroup_v2.bash
- gpMgmt/requirements-dev.txt
- python-dependencies.txt
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v1.out
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v1.sql
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Use subprocess instead of paramiko in isolation2 test, and remove all
dependencies.
> remove paramiko dependencies

- concourse/pipelines/templates/gpdb-tpl.yml
> Refactor code of gpdb-tpl.yml for 6X directed release

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/vars/common_prod.yml
- gpAux/Makefile
[GPR-1342]
Authored-by: Lucas Bonner <blucas@vmware.com>
> Adding rocky9 to gpdb6

- gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
Documenting new features for advanced_password_check module for 6.25.0.
Review site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-advanced_password_check/greenplum-database/ref_guide-modules-adv_passwd_check.html
@radarwave Let me know if we should cherry-pick all these changes to 7.x as well.
> Docs advanced password check

- concourse/pipelines/templates/gpdb-tpl.yml
> Fixing option build-test-rc of gpdb main

- gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
Step 'An entry to {action} {env} env var is added on all hosts of cluster' is failing on centos6 platform. This step was added as part of https://github.com/greenplum-db/gpdb/pull/15504
Reason:
systemctl command is being used to restart sshd service which is not present on centos6 so it is failing to restart sshd.
Fix:
Updated the step to check for the os platform and version. If it is a centos os wth version 6 then use 'sudo service sshd restart' command to restart sshd service.
> Fixed test failing on centos6

- gpdb-doc/markdown/ref_guide/modules/pgaudit.html.md
- gpdb-doc/markdown/security-guide/topics/Auditing.html.md
Adding a reference page for pgaudit module which points to the open source documentation.
> Docs: added documentation page for pgaudit module

- gpdb-doc/markdown/admin_guide/highavail/topics/g-recovering-from-segment-failures.html.md
> Docs: removed -F from differential syntax

- src/test/isolation2/expected/concurrent_partition_table_operations_should_not_deadlock.out
- src/test/isolation2/expected/concurrent_partition_table_operations_should_not_deadlock_optimizer.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/concurrent_partition_table_operations_should_not_deadlock.sql
I verified that undoing commit 0417465a744 will cause this new testcase to
hang.
> Backfill isolation2 test for commit 0417465a744

- gpMgmt/requirements-dev.txt
> Fix CVE-2020-26137 for urllib3

- src/backend/utils/resgroup/Makefile
- src/backend/utils/resgroup/cgroup_io_limit.c
- src/backend/utils/resgroup/io_limit_gram.y
fix compile warning in io_limit_gram.y
related issure: https://github.com/greenplum-db/gpdb/issues/16038
> fix compile warning in io_limit_gram.y

- src/test/regress/expected/create_index.out
- src/test/regress/expected/create_index_optimizer.out
- src/test/regress/sql/create_index.sql
> Fix flaky create_index test

- gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
doc updates for https://github.com/greenplum-db/gpdb/pull/15820
> docs - open parallel retrieve cursor on behalf of current user

- gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
This PR is a follow up from https://github.com/greenplum-db/gpdb/pull/15833. 
Note that there is also an existing PR for main https://github.com/greenplum-db/gpdb/pull/15936 with the same changes.
> Docs: rearranged list of gucs for advanced_password_check and added upgrade section

- gpdb-doc/markdown/ref_guide/modules/adv_passwd_check.html.md
This PR ports the changes made in PR https://github.com/greenplum-db/gpdb/pull/15833 for 6X_STABLE branch to the main branch.
> Docs: added new features to advanced_passsword_check module

- gpdb-doc/markdown/install_guide/install_r_dslib.html.md
And adjust the table rendering to align.
> docs - remove rjags and R2jags from DSB-R

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR documents the guc wal_compression
@Chibin can you please confirm the set classifications field?
> Docs: added wal_compression to list of gucs

- gpMgmt/bin/gppylib/operations/package.py
> Fix python import and syntax warning

- concourse/pipelines/pr_pipeline.yml
[GPR-1501]
Authored-by: Lucas Bonner <blucas@vmware.com>
> Disables PR pipeline running from PRs from forks

- concourse/pipelines/pr_pipeline.yml
> Disables PR pipeline running from PRs from forks 

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/15974.
could use some more info about the benefits.
> docs - add optimizer_enable_dynamicindexonlyscan to guc ref

- gpdb-doc/markdown/ref_guide/modules/pgaudit.html.md
- gpdb-doc/markdown/security-guide/topics/Auditing.html.md
Porting pgaudit documentation from 6.25 to main.
> Docs: port pgaudit documentation to main

- CONTRIBUTING.md
[GPR-1495]
Authored-by: Lucas Bonner <blucas@vmware.com>
> Updating CLA in CONTRIBUTING.md

- gpdb-doc/markdown/admin_guide/external/map_ext_to_foreign.html.md
there was a formatting error in the external table PR that just just merge.  this fixes it.
> docs - fix table formatting in new exttble topic

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/operations/rebalanceSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
**Issue**: If there is a big gap between flush_lsn and replay_lsn on mirror then trigerring rebalance will cause a panic.
**Fix:** Added a check to WAL Replay Location of mirror. gprecoverseg rebalance should throw an exception if replay lag (flush_lsn - replay_lsn) on mirror is more than the default allowed limit (10 GB). 
The default value for ALLOWED_REPLAY_LAG has been decided based on the experiments performed with different amount of replay lags on mirror. Below are the findings:
**Purpose of experiments:** Get the rough estimate of time mirror takes to replay different amount of wals
```
Replay_lag in bytes(flush_lsn - replay_lsn) | time taken by mirror to make replay_lag 0
--------------------------------------------|-------------------------------------------
132350280 (0.123 GB) …
```
> [7X] Abort rebalance if replay lag is big on mirror

- src/test/recovery/t/002_archiving.pl
Commit a247b9d add 'has_streaming => 1' when make a standby node. This will start a walreceiver process to receive the wal log from primary node, rather than just store its contents on the archives of the primary. In this way, the inserted 2000 rows can all have been present on standby node.
Revert the enable streaming change when create standby, append conn info to the postgresql.conf after pass the first check and restart standby node.
This is backport https://github.com/greenplum-db/gpdb/pull/15812
> [6X] Fix flacky case 002_archiving.pl

- gpdb-doc/markdown/admin_guide/perf_intro.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
- gpdb-doc/markdown/install_guide/prep_os.html.md
Will also cherry-pick into 6X_STABLE.
> Update anti-virus note with non-support notice

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
This PR documents https://github.com/greenplum-db/gpdb/pull/16132 which introduces the `ALTER TABLE REPACK BY COLUMNS` option.
> Docs: Document ALTER TABLE REPACK BY COLUMNS

- src/test/regress/expected/gp_recursive_cte.out
Fix test gp_recursive_cte introduced in 4f2ab91501 which had plan cherry-picked, causing failure in CI
> 6X CI fix test gp_recursive_cte

- src/backend/cdb/motion/ic_udpifc.c
`SendDummyPacket` eventually calls `getaddrinfo` (which is a reentrant), however, `getaddrinfo` is not an async-signal-safe function. `getaddrinfo` internally calls `malloc`, which is strongly advised to not do within a signal handler as it may cause deadlocks. Cache the accepted socket information for the listener, so that it can be reused in `SendDummyPacket()`.
The purpose of `SendDummyPacket` seems to be to exit more quickly; it circumvents the polling that happens, which eventually times out after 250ms.
Without `SendDummyPacket()`, there will be multiple test failures since some tests expects the backend connection to terminate almost immediately.
To view all the async-signal-safe functions, please view the signal-safety(7) — Linux manual page.
This PR addresses …
> Remove `getaddrinfo` in `SendDummyPacket()` to address malloc deadlock

- gpdb-doc/markdown/ref_guide/config_params/guc_config.html.md
add a note to the server configuration parameters topic.
> docs - add non-supported note about ALTER SYSTEM

- gpdb-doc/markdown/ref_guide/modules/gp_parallel_retrieve_cursor.html.md
docs for https://github.com/greenplum-db/gpdb/pull/15854
6x backport of https://github.com/greenplum-db/gpdb/pull/16027
> docs - open parallel retrieve cursor for current user (6x)

- gpdb-doc/markdown/utility_guide/ref/gpcheckperf.html.md
This PR adds the --buffer-size -buffer_size option for gpcheckperf.
This PR has to be cherrypicked to the main as well.
> Added documentation for gpcheckperf option

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_sequence.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-986-pg_sequence/greenplum-database/GUID-ref_guide-system_catalogs-pg_sequence.html
> DOCS: Document pg_sequence catalog table

- src/backend/cdb/motion/ic_udpifc.c
> Due to IC failures, rever this fix

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR documents the server configuration parameter `work_mem`.
> Docs: add configuration parameter work_mem

- gpdb-doc/markdown/analytics/pl_container_using.html.md
Removing RG support for initial 7.0 release.
> Remove resource groups support for pl/container

- gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
This PR ports https://github.com/greenplum-db/gpdb/pull/15790 to main branch.
> Docs: added -k option for gpfdist

- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
This PR updates the Software Dependencies for Greenplum 6.
> Docs: updated the Software Dependencies page for 6

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
This PR updates the Software Dependencies for Greenplum 7.
> Docs: updated Software Dependencies for GP 7

- gpdb-doc/markdown/install_guide/upgrading_6_to_7.html.md
STAGING HERE: https://docs-staging.vmware.com/en/Greenplum-Database-7/rejigger-6-to-7-upgrade-steps/greenplum-database/GUID-install_guide-upgrading_6_to_7.html
> DOCS: Rework task steps in upgrading 6 => 7 procedural topic

- gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
- gpdb-doc/markdown/admin_guide/textsearch/controlling.html.md
- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
- gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
- gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
found some "the the" in the docs, only need one
> docs - remove some extra the s

- gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
> Update docs to reference the correct extension name for PostgresML

- gpMgmt/bin/gpsd
- gpMgmt/bin/minirepro
Removing the copyright statement from the output of minirepro/gpsd and
updating the copyright in the comments.
> Change copyright of minirepro and gpsd

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
a new filepath column was added to gp_check_orphaned_files in https://github.com/greenplum-db/gpdb/pull/16428
> docs - add filepath column to gp_check_orphaned_files

- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
minor edits to supported platforms and madlib install topic.
> docs - gp7 supports madlib 2.1.0

- gpdb-doc/markdown/ref_guide/system_catalogs/pg_resgroupcapability.html.md
This PR updates the possible values for the column reslimittype on table pg_resgroupcapability
> Docs: update the values for pg_resgroupcapability catalog table

- src/backend/cdb/cdbvars.c
- src/backend/cdb/motion/ic_udpifc.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
- src/include/utils/sync_guc_name.h
This PR backported https://github.com/greenplum-db/gpdb/pull/16458 to 6x.
All details please check at https://github.com/greenplum-db/gpdb/pull/16458.
> (6X) Improve prune behavior for the read-only transaction

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
libcgroup/libcgroup-utils packages are official removed since RHEL9. A new service is provided in the document to support gpdb6 with cgroup v1 on RHEL 9.x
edit: I have added a staging link: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-rg-6/greenplum-database/admin_guide-workload_mgmt_resgroups.html#configuring-and-using-resource-groups
> docs - updated workload_mgmt_resgroups to support cgroup v1 on rhel9 (6X)

- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
Fix test case plan changes after PR https://github.com/greenplum-db/gpdb/pull/16080, mainly adapt plans about gp2gp aggregate pushdown and gporca.
> fix testcase for broken CI

- src/backend/utils/adt/ruleutils.c
- src/test/regress/expected/AOCO_Compression.out
- src/test/regress/expected/gp_partition_template.out
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
> Remove the redundant comma in subpartition template.

- src/backend/cdb/dispatcher/test/Makefile
- src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
- src/backend/cdb/dispatcher/test/gpsegconfig_dump
- src/interfaces/libpq/fe-connect.c
- src/interfaces/libpq/fe-misc.c
This PR ported https://github.com/greenplum-db/gpdb/pull/16141 to 6x.
Note: random pipeline failure happened when I merged https://github.com/greenplum-db/gpdb/pull/16299.
After investigation, it was caused by SIGUSR, fix it in this PR (in the second commit).
> [6X] Fix segmentation fault during dispatch interrupt

- gpMgmt/doc/gpfdist_help
Add some help information for the gpfdist flag 'ssl_verify_peer'.
> Add help information for gpfdist

- src/backend/utils/adt/ruleutils.c
- src/test/regress/expected/AOCO_Compression.out
- src/test/regress/expected/gp_partition_template.out
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
> Fix subtemplate relstorage dump result.

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gporca/libgpos/src/common/clibwrapper.cpp
Remove 'hack' from comments from commit 6e2c664e
> Remove 'hack' from comments from commit 6e2c664e

- src/backend/postmaster/syslogger.c
- src/test/regress/expected/qp_indexscan.out
- src/test/regress/expected/qp_indexscan_optimizer.out
- src/test/regress/sql/qp_indexscan.sql
As the title said, fix some typos in GPDB 7X.
> Fix some typos

- gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
- gpdb-doc/markdown/utility_guide/ref/gpload.html.md
Porting https://github.com/greenplum-db/gpdb/pull/16711to 6X_STABLE
> Docs: edit MAX_LINE_LENGHT description for 6X

- concourse/scripts/build_gpdb.py
- concourse/scripts/builds/GpBuild.py
- concourse/tasks/run_explain_suite.yml
- src/backend/gporca/concourse/test_explain_pipeline.yml
This PR includes YAML modifications to facilitate a 3TB explain pipeline and configures segments based on workloads
> Add workload7 to explain pipeline

- gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
- src/test/regress/input/appendonly.source
- src/test/regress/output/appendonly.source
> Fix typos clause.

- src/bin/psql/print.c
This PR ported https://github.com/greenplum-db/gpdb/pull/16388 to 6x.
(6x's directory structure is different from main branch, so the unit test have to be rewritten. I just removed them)
> (6X) Fix ERROR: "Cannot add cell to table content: total cell count of XXX exceeded"

- gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
This PR cherry-picks the contents of https://github.com/greenplum-db/gpdb/pull/16735 for the main branch.
> Docs:  pgbouncer supports encrypted ldap password

- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
This PR documents https://github.com/greenplum-db/gpdb/pull/16628
I just made a few modifications to @ShirishaRao 's contribution to adjust to documentation style.
> Docs: edited the gprecoverseg reference page for max-rate

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table.out
- src/test/regress/sql/alter_table.sql
Fix https://github.com/greenplum-db/gpdb/issues/16805
> fix Alter Table tlbname Alter Column Type with multi indexes reuse index error #16805

- src/backend/utils/mmgr/aset.c
This pr fix a memory accouning bug when move memory context to another accouting node.
Take this as an example:
```
root - A - B
\
C
```
Only root and B are accounting nodes, A and C are accounted to root. If move C under B, then for now it will not change accoutint parent of C which is not expected.
> Fix memory accounting bug when move memory context

- src/backend/cdb/cdbtm.c
> Fix comment on 'performDtxProtocolPrepare'

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
This PR adds the gp_move_orphaned_files() UDF to gp_toolkit reference page.
The PR for the same function documentation for 6X is https://github.com/greenplum-db/gpdb/pull/16692
This PR also incorporates a section on how to update the gp_toolkit extension in order to avail of new functions included in newer versions of GPDB.
> Docs: add gp_move_orphaned_files gp_toolkit

- gpdb-doc/markdown/utility_guide/ref/gpstate.html.md
This PR ports https://github.com/greenplum-db/gpdb/pull/16739/files to 7 branch.
> Docs: Add note for rsync version gpstate

- gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
Commit b2ad54e87c9485e5b8a99a2437e0d378f817dfe6 changed the expected output files for gp_toolkit, but resource groups have a separate output file. Update that as well.
> Fix ICW output file for resgroup gp_toolkit

- gpMgmt/bin/gpexpand
> fix a logging bug

- contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
- src/backend/optimizer/plan/orca.c
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
**Issue:**
When executing a query with a false filter that results in zero rows 
from a table, ORCA returns incorrect column type information in the plan.
The type modifier details for columns in the table metadata are absent.
Setup query:
`CREATE TABLE foo(col decimal(7,4));`
Play query:
`EXPLAIN (VERBOSE) SELECT * FROM foo WHERE 1=0;`
```
QUERY PLAN
------------------------------------------
Result  (cost=0.00..0.00 rows=0 width=8)
Output: NULL::numeric
One-Time Filter: false
Optimizer: GPORCA
(4 rows)
```
The type info `NULL::numeric` represents the column `col` of table `foo`
which is missing the modifier info of precision 7 and scale 4.
**RCA:**
In 7X, redundant Result node in a planned_stmt is being removed
by function `remove_redundant_results` in _orca.c_.
Within …
> Fix ORCA returning wrong column type modifier info

- gpdb-doc/markdown/analytics/pl_java.html.md
> Add Java 17 in pljava doc

- src/backend/utils/misc/guc_gp.c
Intent is to enhance the user experience by adding more context to
easily know how and when to use the GUC
> Add long description of optimizer_enable_right_outer_join

- src/backend/access/transam/xlog.c
The redo routines for XLOG_CHECKPOINT_{ONLINE,SHUTDOWN} must acquire ControlFileLock before modifying ControlFile->checkPointCopy, or the checkpointer could write out a control file with a bad checksum.
Likewise, XLogReportParameters() must acquire ControlFileLock before modifying ControlFile and calling UpdateControlFile().
Back-patch to all supported releases.
Author: Nathan Bossart <bossartn@amazon.com>
Author: Fujii Masao <masao.fujii@oss.nttdata.com>
Reviewed-by: Fujii Masao <masao.fujii@oss.nttdata.com>
Reviewed-by: Michael Paquier <michael@paquier.xyz>
Reviewed-by: Thomas Munro <thomas.munro@gmail.com>
Discussion: https://postgr.es/m/70BF24D6-DC51-443F-B55A-95735803842A%40amazon.com
(cherry picked from Postgres commit 57cb8063089a7d6c54e27adfd5d028cc01f21536)
GPDB Merge Conflicts: …
> [6X backport] Fix locking bugs that could corrupt pg_control.

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/tsm_system_rows.html.md
- gpdb-doc/markdown/ref_guide/modules/tsm_system_time.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/SELECT.html.md
Staging here:
https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-1055-tablesampling-aoco/greenplum-database/GUID-ref_guide-sql_commands-SELECT.html
https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-1055-tablesampling-aoco/greenplum-database/GUID-ref_guide-modules-tsm_system_rows.html
https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-1055-tablesampling-aoco/greenplum-database/GUID-ref_guide-modules-tsm_system_time.html
> Document new TABLESAMPLE features

- gpdb-doc/markdown/utility_guide/ref/gpv-config.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv-greenplum.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv.html.md
- gpdb-doc/markdown/utility_guide/utility-programs.html.md
> Greenplum 7.1 Update GPV utility docs

- gpdb-doc/markdown/analytics/pl_container_using.html.md
This PR adds a section to the documentation page "Using PL/Container" in order to configure remote hosts to run PL/Container functions.
Review site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-plcontainer/greenplum-database/analytics-pl_container_using.html#remote_container
@radarwave can I please confirm the minimum PL/Container and Docker versions for the Prerequisites section. Feel free to add any additional reviewers.
> Docs plcontainer remote containers

- src/backend/optimizer/util/pathnode.c
It's from a FIXME at /src/backend/optimizer/util/pathnode.c:5408:
```
/*   
* Set the distribution of the ModifyTable node itself. If there is only
* one subplan, or all the subplans have a compatible distribution, then
* we could mark the ModifyTable with the same distribution key. However,
* currently, because a ModifyTable node can only be at the top of the
* plan, it won't make any difference to the overall plan.
*
* GPDB_96_MERGE_FIXME: it might with e.g. a INSERT RETURNING in a CTE
* I tried here, the locus setting is quite simple, but failed if it's not
* in a CTE and the locus is General. Haven't figured out how to create
* flow in that case.
* Example:
* CREATE TABLE cte_returning_locus(c1 int) DISTRIBUTED BY (c1);
* COPY cte_returning_locus FROM PROGRAM 'seq 1 100';
* EXPLAIN …
```
> FIXME: remove the fixme about locus for ModifyTable

- gpdb-doc/markdown/ref_guide/modules/pgcrypto.html.md
> DOCS: Fix bad syntax in pgcrypto reference page

- gpdb-doc/markdown/ref_guide/sql_commands/INSERT.html.md
> DOCS: Add restriction for UPSERT on AO/CO tables

- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/pg_buffercache.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-1218-pg_buffercache-extension/greenplum-database/GUID-ref_guide-modules-pg_buffercache.html
> DOCS: Document pg_buffercache extension

- src/bin/pg_upgrade/greenplum/check_gp.c
Partitioned tabled with a LIST partition key containing multiple columns is not supported in GP7. Add a check to find and output the offending tables.
```
Checking for multi-column LIST partition keys               fatal
| Your installation contains partitioned tables
| with a LIST partition key containing multiple
| columns, which is not supported anymore. Consider
| modifying the partition key to use a single column
| or dropping the tables. A list of the problem tables
| is in the file:
/home/bdoil/workspace/gpdb7/gpAux/gpdemo/datadirs/qddir/demoDataDir-1/pg_upgrade_output.d/multi_column_list_partitions.txt
```
```
In database: regression
bfv_partition.t26002_t1
bfv_partition.t26002_t1
dpe_malp.malp
partition_pruning.pt_complex
partition_pruning.pt_complex
public.dml_ao_pt_p …
```
> Check for multi-column LIST partition keys

- src/bin/pg_upgrade/greenplum/check_gp.c
The check should only run on 6X
> Fix check_multi_column_list_partition_keys

- gpcontrib/pg_hint_plan/Makefile
- gpcontrib/pg_hint_plan/SPECS/pg_hint_plan12.spec
- gpcontrib/pg_hint_plan/pg_hint_plan.c
Fix a couple build errors on different platforms/configurations.
> Fix pg_hint_plan build errors

- src/backend/gporca/libnaucrates/src/parser/CParseHandlerDynamicForeignScan.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerDynamicTableScan.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerGatherMotion.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerHashJoin.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerMaterialize.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerMergeJoin.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerNLJoin.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerPhysicalAbstractBitmapScan.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerRandomMotion.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerRedistributeMotion.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerResult.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerRoutedMotion.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerSort.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerTableScan.cpp
While.. 
A misspell search by mistake find these
typos, fix them by the way.
> Fix typo of statistics under gporca.

- src/backend/storage/smgr/md.c
> Remove unused buf[MAXPGPATH] variable in mdcreate_ao()

- src/backend/gporca/scripts/convert_minirepro_6_to_5.py
GPDB5 to GPDB6 minirepro conversion adds line 2,9,13,17,21 to pg stats
This script essentially removes those added lines at line 2, 10, 15, 20, 25
> Add GPDB6 to GPDB5 minirepro conversion script

- gpdb-doc/markdown/analytics/pl_container.html.md
- gpdb-doc/markdown/analytics/pl_container_using.html.md
> DOCS: Update plcontainer prerequisites and add section called Configuring a Remote PL/Container

- gpdb-doc/markdown/analytics/pl_container_using.html.md
> DOCS: Fill in PL/Container and Docker required versions

- README.Rhel-Rocky.bash
- README.macOS.arm.bash
- concourse/scripts/common.bash
- concourse/scripts/ic_gpdb_resgroup.bash
- concourse/scripts/ic_gpdb_resgroup_v2.bash
- concourse/scripts/ic_resgroup.bash
- gpAux/Makefile
- gpdb-doc/markdown/analytics/pl_python.html.md
- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
- gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This reverts commit 2765123a5c04590ea5e093c78959cd6e5abbf043.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/revert_py11?group=all
> Revert "Update to python3.11 for plpython (#17135)"

- contrib/pg_upgrade_support/pg_upgrade_support.c
Views that use deprecated operators will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using types that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a deprecated operator causes pg_upgrade to fail. In order to detect views with deprecated operators. A query_tree_walker is used to walk the nodes of all views. Each node is then checked to see if is an operator. If it is, we then check if the oid of the operator matches one that is not present in GPDB7.
Due to the limitations of the query walker being a function that only returns a bool, we can only tell if a deprecated operator exists in a view. We do not have an easy way to tell users how many or …
> pg_upgrade: add support func to check views using removed operators

- src/bin/pg_upgrade/greenplum/check_gp.c
Views that use removed functions will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using functions that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a removed operator causes pg_upgrade to fail. This check calls a support function on the source cluster to check if views using removed functions exist.
https://github.com/greenplum-db/gpupgrade/pull/902
6x: https://github.com/greenplum-db/gpdb/pull/17152
7x: https://github.com/greenplum-db/gpdb/pull/17153
> pg_upgrade: check for views using removed functions

- src/backend/utils/cache/plancache.c
Move oneoffPlan check to function `BuildCachedPlan`, travel through plan list once to get all oneoffPlan, transientPlan and dependsOnRole value.
Remove GPDB_96_MERGE_FIXME in plancache.c.
> remove function plan_list_is_oneoff

- README.Rhel-Rocky.bash
- README.macOS.arm.bash
- concourse/scripts/common.bash
- concourse/scripts/ic_gpdb_resgroup.bash
- concourse/scripts/ic_gpdb_resgroup_v2.bash
- concourse/scripts/ic_resgroup.bash
- gpAux/Makefile
- gpdb-doc/markdown/analytics/pl_python.html.md
- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
- gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This reverts commit 721a7601f2520705da81aa288bbd7530872f54f6.
> Re-apply "Update to python3.11 for plpython" 

- contrib/pg_upgrade_support/pg_upgrade_support.c
Views that use removed types will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using types that do not exist anymore. This is not ideal as we could be many hours into upgrade before a failure occurs. In order to detect views with removed types. A query_tree_walker is used to walk the nodes of all views. Each node is then checked to see if it is a type. If it is, we then check if the oid of the type matches one that is not present in GPDB7.
Currently we only notify end users of views that contain a removed type. We do not log what specific part of the view triggered the check for a removed type.
https://github.com/greenplum-db/gpupgrade/pull/903
https://github.com/greenplum-db/gpdb/pull/17187 …
> [6X] pg_upgrade: add support func to check if view contains removed types

- gpcontrib/gp_toolkit/gp_toolkit--1.4--1.5.sql
GDD and other services like GPCC may always keep the connections to coordinator or segments. As discussed in PR#16903, we should skip checking the idle session for orphaned files detection to avoid that we can't get a detection result due to the ERROR `There is a client session running on one or more segment.Aborting...`.
> Check orphaned files functions exclude idle sessions when doing safety check

- src/bin/pg_upgrade/greenplum/check_gp.c
For 9.5 and beyond, doing `CREATE OPERATOR =>` has been removed and disallowed. The => operator is now reserved for named parameters. As a result, any user defined operations that are => cannot be upgraded.
With this commit, a check has been added to ensure that the source cluster is compatable with the target cluster.
The upstream change happened in commit 865f14a2d31af23a05bbf2df04c274629c5d5c4d.
corresponding gpupgrade test:
https://github.com/greenplum-db/gpupgrade/pull/905
> pg_upgrade: Add check for disallowed OPERATOR

- src/test/regress/expected/plpgsql.out
- src/test/regress/expected/plpgsql_optimizer.out
- src/test/regress/sql/plpgsql.sql
It acts as expected, remove the comment fixme.
> Remove a fixme of plpgsql tests

- gpdb-doc/markdown/ref_guide/modules/ip4r.html.md
Update ip4r version for Greenplum 6.27 to 2.4.2.
> Updated ip4r version

- gpcontrib/gp_exttable_fdw/input/gp_exttable_fdw.source
- gpcontrib/gp_exttable_fdw/output/gp_exttable_fdw.source
Fix pipeline diff caused by different length of `-----`
> Fix pipeline diff caused by different length of `-----`

- gpMgmt/bin/gpcheckcat
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/data/gpcheckcat/create_legacy_hash_ops_tables.sql
- gpMgmt/test/behave/mgmt_utils/steps/data/gpcheckcat/create_non_legacy_hashops_tables.sql
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Gpcheckcat is enhanced to report if there are tables created using legacy and non legacy hashops in distribution policy. This check is essential as ORCA fails back to planner if there is mix distribution policy found.
Option Added 
`gpcheckcat -R mix_distribution_policy
`
High level design of "gpcheckcat -R mix_distribution_policy" Check if there are tables created with both legacy and non legacy hashops in distribution policy.
1.      If there is Mix Distribution Policy
-       Report error that there is mix distribution policy.
-       Create an sql file containing the sql query using which the user can
obtain the table names created with legacy and non legacy hashops
2.     In case there is no Mixed Policy
-      Check if gp_use_legacy_hashops is on and there are no tables created with …
> gpcheckcat enhancement to report if there are tables created using mix distribution policy 

- gpdb-doc/markdown/utility_guide/ref/gpcheckcat.html.md
Going into 7.2.0 docs.
Will be cherry-picked to 6.27.0 docs.
> DOCS: Add mix_distribution_policy test to gpcheckat utility docs

- gpdb-doc/markdown/utility_guide/ref/gpsupport-gp_log_collector.html.md
Updated docs for new gpdr option added in gpsupport.
> DOCS: New gpsupport option

- gpdb-doc/markdown/utility_guide/ref/gpmt-gp_log_collector.html.md
Updated docs for new gpdr option added in gpmt.
> DOCS: New gpmt option

- gpdb-doc/markdown/utility_guide/ref/gpsupport-gp_log_collector.html.md
This pr is follow up correction pr of pr #17295
> DOCS: updated gpdr option descriptions

- src/backend/cdb/motion/ic_udpifc.c
- src/include/cdb/cdbicudpfaultinjection.h
- src/test/regress/expected/icudp/icudp_full.out
- src/test/regress/sql/icudp/icudp_full.sql
> Add hint message for MTU settings when IC reports ERROR "Failed to send packet"

- src/test/regress/expected/planhints_optimizer.out
- src/test/regress/expected/rowhints_optimizer.out
This commit fixes plans in Row and Scan hints tests after aliases
change made as part of commit:
https://github.com/greenplum-db/gpdb/commit/84168e355fe9faca763a9b4e48f07b184aa8eff1
> Fix planhints test failures after alias change commit

- src/backend/cdb/cdbvars.c
> Update cdbvars.c: remove unused variables

- gpMgmt/bin/go-tools/configs/saltstates/pillar/cgroups.sls
- gpMgmt/bin/go-tools/configs/saltstates/pillar/top.sls
- gpMgmt/bin/go-tools/configs/saltstates/salt/common/cgroups.sls
- gpMgmt/bin/go-tools/configs/saltstates/salt/templates/cgconfig.conf.tpl
- this state file will configure cgroups by creating the cgconfig.conf in the etc directory
- added the cgconfig.conf.tpl in the templates directory which will act as the source file
- added the pillar state file for the cgroups
> Added the cgroups.sls state file
