configure
configure.in

We converge our configure script a little more to upstream, and we'll see massive speed up on Travis CI GCC compilation due to much improved cache hit rate.
This patchset is a combination of two commits (the second one depends on the first):
1. "Typo in configure left from #11112"
2. "Converge compiler debug flags with upstream"

One Surprising Trick to Massively Increase Cache Hit Rate (a.k.a Converge compiler debug flags with upstream)

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/dpe.out
src/test/regress/expected/dpe_optimizer.out
src/test/regress/sql/dpe.sql

This adds an ICW test for the ORCA commit: 54769b3025 (https://github.com/greenplum-db/gporca/pull/612)
Bump ORCA version to 3.115

Add test after ORCA banned rescans on DPE PartitionSelectors

---

src/bin/pg_upgrade/check.c
src/bin/pg_upgrade/dump.c
src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
src/bin/pg_upgrade/pg_upgrade.c
src/bin/pg_upgrade/server.c

For pg_upgrade and pg_dump use correct GUC when connecting in utility mode. For GPDB6 use gp_role and for GPDB7 use gp_session_role. This is needed when performing GPDB6 to GPDB7 upgrades.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/pg_upgrade_connection_guc)

pg_upgrade: use correct utility mode guc

---

.travis.yml

clang-tidy job takes ~11 mins to run. Hence, instead of running it
serially better to run in parallel with other tests to cut down
feedback time.
This should help to cut down full travis CI feedback time for PRs from
~41 mins to ~30 mins.

Run clang-tidy job in travis CI in parallel

---

src/backend/access/transam/distributedlog.c
src/backend/storage/lmgr/lwlock.c
src/include/access/distributedlog.h

Distributed log buffers were hard-coded to 8. Mostly in HTAP
work-load, it is possible to have many distributed log page requests
in flight at one time which could lead to disk access for distributed
log page if the required page is not found in memory. Testing revealed
that we can get the best performance by having 128 distributed log
buffers, more than that it doesn't improve performance.
Hence, seeking inspiration from CLOG buffers, number of distributed
log buffers are also selected based on shared_buffers.
Discussion:
https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/l_iNnfwTF7s/m/Fk-6UVlbAwAJ
(cherry picked from commit 41a645bb0acc0f515d4d269b205fc78a764fcd5a)

[Backport 6X] Pick number of distributed log buffers based on shared_buffers

---

src/backend/partitioning/partdesc.c

Seems the FIXME is not an issue right now.

Remove useless FIXME in partdesc.c

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c
src/test/isolation2/expected/bitmap_index_ao_sparse.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_index_ao_sparse.sql

If there are multiple LOV items matched for the scan, and the index is on an
AO table, the `tbm_iterate_page` will generate empty bitmap for a block's
PagetableEntry.
Then in BitmapHeapNext, table_scan_bitmap_next_block returns false(which means
the block should be skipped) for the empty PagetableEntry, but we still try
to fetch tuple through table_scan_bitmap_next_tuple, and the code didn't find
out the PagetableEntry is empty cause `aoscan->rs_cindex != tbmres->ntuples`.
Actually I think we should set `tbmres = NULL` if `table_scan_bitmap_next_block`
return false. But seems we are using upsream's logic, so just fix
with current logic.

Fix Bitmap Heap Scan on AO's sparse bitmap index.

---

src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Method `CXformUtils::FIndexApplicable()` allowed a btree index to be
used for an IndexGet on an AO table, which is not supported.
Fixing the method to return false for this situation.
Now, the `CXformJoin2IndexGetApply` xform should no longer generate
an alternative for a btree index on an AO table.

Disallow btree index scan on AO table

---

src/backend/gporca/server/CMakeLists.txt
src/backend/gporca/server/src/startup/main.cpp

Currently we happily return a 0 (success) status even if we print a
warning that the argument to "-u" or "-x" isn't valid. This has led to
an incomplete removal when we try to delete and disable tests recently
(greenplum-db/gpdb#11336).
~~## Why is this marked as WIP, is this ready for review?~~
~~Yes it's actually reviewable. The reason it's marked as a "draft" is because we cannot merge this without failing 172 tests in CI right now (because of #11336). So this needs to wait and rebase on the follow-up of #11336 before merging.~~
Now that #11427 is merged, I can change this to "ready for review". The two commits are intended to be squashed, but I've separated them for ease of review.
I had to disable two dead-on-arrival tests to get the suite passing, and left two FIXME's, so that's sad …

Fail gporca_test if the unit test name is invalid

---

src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Method CXformUtils::FIndexApplicable() allowed a btree index to be
used for an IndexGet on an AO table, which is not supported.
Fixing the method to return false for this situation.
Now, the CXformJoin2IndexGetApply xform should no longer generate
an alternative for a btree index on an AO table.
This is a backport of master PR https://github.com/greenplum-db/gpdb/pull/11399.

6X: Disallow btree index scan on AO table

---

src/backend/catalog/system_views.sql
src/backend/commands/matview.c
src/backend/postmaster/pgstat.c
src/test/regress/input/pgstat_qd_tabstat.source
src/test/regress/output/pgstat_qd_tabstat.source

The REFRESH MATERIALIZED used to count pgstat on QD. But it always
result to 0 since the es_processed are not colleted from segments.
In GPDB, we should count the pgstat on segments and union them on
QD, so both the segments and coordinator will have pgstat for this
relation.
This fix issue: https://github.com/greenplum-db/gpdb/issues/11375

Correct pgstat for materialized view after REFRESH MATERIALIZED

---

src/backend/optimizer/plan/planner.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/gp_aggregates_costs.out
src/test/regress/expected/gp_aggregates_costs_optimizer.out
src/test/regress/sql/gp_aggregates_costs.sql

Greenplum planner tries its best to build an accurate cost model
for agg paths. It will generate one-stage or multi-stage agg paths
when adding paths to grouped rel, and it chooses the best path based
on costs. The accuracy of this progress depends on the accuracy of
the previous cost model, like cardinality estimation of all previous
paths which is hard to be accurate. Thus even if the cost model of
agg paths is good, in practical scenario, planner may not choose
the best path for agg. For MPP database to handle big data, two
stage agg may reduce much data in the first stage.
This commit adds a GUC to allow user to force choosing two stage
agg. Set gp_eager_two_phase_agg to true, when we can do two stage
agg, it will add a disable_cost to all the first stage agg paths
thus let two stage …

Add GUC gp_eager_two_phase_agg to allow user control agg pattern.

---

gpcontrib/gp_exttable_fdw/extaccess.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

```
SubPlan 1
->  External Scan
```
or
```
SubPlan 1
->  Limit
->  External Scan
```
A plan snippet like one of these two would trigger SEGV on 6X before. 7X
has no such issue after it switched to the FDW framework, however one
more case doesn't hurt.

Add a case which was panicing on 6X, for external table

---

.gitignore
src/backend/access/external/fileam.c
src/backend/executor/nodeExternalscan.c
src/include/nodes/execnodes.h
src/test/regress/expected/.gitignore
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source
src/test/regress/sql/.gitignore

```
SubPlan 1
->  External Scan
```
A plan snippet like this would trigger SEGV because the state needed by
rescan was freeed when the external table outputted its last row.
It was introduced by the refactor below, only `ExternalNext()` has this
issue.
commit 6195b96780312d836473b04fd08cc0345999eb9a
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Mon Jan 7 12:24:23 2019 +0200
Refactor executor Squelch and EagerFree functions.
Merge the two concepts, squelching and eager-freeing. There is now only
one function, ExecSquelchNode(), that you can call. It recurses to
children, as before, but it now also performs eager-freeing of resources.
Previously that was done as a separate call, but that was an unnecessary
distinction, because all callers of ExecSquelchNode() also called …

6X: Delay the eager-free of external scan if it's not safe

---

src/backend/postmaster/pgstat.c

Remove useless assert.
If `dispatchResult->okindex` is -1 which means we don't receive any
pgresult from a QE, cdbdisp_getPGresult() will return NULL, so no
need to assert dispatchResult->okindex >= 0.

Remove assert in pgstat_combine_from_qe.

---

src/backend/commands/vacuum.c
src/test/regress/expected/incremental_analyze.out
src/test/regress/expected/incremental_analyze_optimizer.out
src/test/regress/sql/incremental_analyze.sql

When using `analyze (rootpartition off) <tbl>` or `analyze (hllscan off) <tbl>`,
we didn't properly parse the option value. `rootpartition off` would
have the same effect as `rootpartition on`.
Thanks @d  for finding this

Fix analyze rootpartition and hllscan when used in option list

---

src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalRightOuterJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
src/backend/gporca/libgpopt/src/operators/CLogicalRightOuterJoin.cpp
src/backend/gporca/libgpopt/src/xforms/CXformLeftJoin2RightJoin.cpp
src/backend/gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.cpp

Commit be71386dd0c4a902 was the result of "rebase and merge" of
greenplum-db/gpdb#11462. This means that while it passed the check it
introduced, the result of the rebase would fail the test (due to
greenplum-db/gpdb#11461), as evidenced by a red Travis CI.
This commit fixes the remaining occurrences of "NULL".

Fix the remaining occurrences of NULL

---

gpdb-doc/dita/admin_guide/managing/configure.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

the gp_fts_probe_threadcount guc was removed in 6, clean up the docs.

docs - remove refs to gp_fts_probe_threadcount guc

---

contrib/bloom/bloom.h
contrib/bloom/blscan.c
gpcontrib/gp_internal_tools/gp_instrument_shmem.c
src/backend/access/bitmap/bitmap.c
src/backend/access/brin/brin.c
src/backend/access/gin/ginget.c
src/backend/access/gist/gistget.c
src/backend/access/hash/hash.c
src/backend/access/index/indexam.c
src/backend/access/nbtree/nbtree.c
src/backend/access/spgist/spgscan.c
src/backend/executor/nodeBitmapIndexscan.c
src/include/access/amapi.h
src/include/access/bitmap_private.h
src/include/access/brin_internal.h
src/include/access/genam.h
src/include/access/gin_private.h
src/include/access/gist_private.h
src/include/access/hash.h
src/include/access/nbtree.h
src/include/access/spgist.h
src/test/regress/expected/partition_prune.out
src/test/regress/expected/partition_prune_optimizer.out

GPDB has a different definition of amgetbitmap with upstream.
Since GPDB also supports StreamBitmap in bitmap index. So normally
we need to create a specific bitmap node in the amgetbitmap AM.
We used to return the created node, this leads to losing the tuples
matched in the bitmap.
So I refactor the amgetbitmap function definition to set bitmap
through pointer and then return the tuples matched in the bitmap.
For GPDB specific bitmap index, it's hard to get matched tuples
in amgetbitmap AM, so ignore it for now.
Also correct the `gp_instrument_shmem_detail` UDF which used to
return wrong results.

Resolve FIXME in indexam.c

---

src/backend/gporca/data/dxl/minidump/PartPredsWithRandom.mdp
src/backend/gporca/libgpopt/src/operators/CScalarIdent.cpp
src/backend/gporca/server/CMakeLists.txt

When testing whether a function (e.g random() or timeofday()) can be
used as a monotonically increasing function in stats for partition
columns, we tried to access the function argument without checking for
its arity which can lead to an illegal access. This commit fixes this
issue by adding the check. Other functions with arity 0 are evaluated
at planning time and don't run into this problem. Examples: pi(),
current_timestamp, current_schema().

Fix SIGSEGV/assert violation with certain functions with no arguments

---

src/backend/utils/adt/ruleutils.c
src/test/isolation2/expected/query_gp_partitions_view.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/query_gp_partitions_view.sql

This interface is designed to parse a generic rule expression and rule
expressions contain references to relations. Acquiring AccessShareLock
on a relation encountered while deparsing a rule expression seems
logical.
For partition tables, the RANGE and LIST expressions are much simpler -
they cannot contain any references to relations.
So we decide to optimize out the lock when the expression contains
no Var nodes.

Optimize pg_get_expr to avoid unnecessary lock on relation. 

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
gpdb-doc/dita/utility_guide/ref/gpfdist.xml
src/backend/access/external/url.c
src/backend/access/external/url_curl.c
src/backend/utils/misc/guc_gp.c
src/bin/gpfdist/regress/input/exttab1.source
src/bin/gpfdist/regress/output/exttab1.source
src/include/access/url.h
src/include/utils/unsync_guc_name.h

The GUC controls the time that gpdb waits before returning when it
connects or writes to gpfdist. It handles retry times if getting an error from socket/network.
So write_to_gpfdist_timeout is not an exact name and need to be renamed.

Rename write_to_gpfdist_timeout as gpfdist_retry_timeout

---

src/backend/cdb/motion/ic_proxy_pkt_cache.c
src/backend/cdb/motion/ic_proxy_pkt_cache.h

icproxy's flow control is based on the PAUSE/RESUME, which needs to
route to a remote client. This asynchronous flow control may result
in the size of packet cache increase rapidly but packet returned to
free list slowly.
Packet cache should have a maximum size to limit the total memory
used by icproxy background worker. When limit is reached, the packet
should be freed instead putting to free list.
Note that this patch could not fix the flow control issue, but only
helps to avoid the bloating of packet cache.
Manually tested on a Azure big cluster, this cannot be reproduced in
small cluster.

ic-proxy: limit max size of packet cache.

---

src/backend/cdb/cdbfts.c
src/backend/fts/ftsprobe.c
src/backend/fts/test/ftsprobe_test.c
src/include/cdb/cdbfts.h

Remove FtsControlBlock->ControlLock (the LWLock for guarding ftsProbeInfo->status)
and related ftsLock()/ftsUnlock() functions.
FtsControlBlock->ControlLock is intended to guard concurrent access to
ftsProbeInfo->status array. In the original code implementation, only the writer
(FTS probe process) acquires this lock before updating ftsProbeInfo->status, but
readers (query dispatcher processes) reads ftsProbeInfo->status without locking
(see function FtsIsSegmentDown()).
ftsProbeInfo->status is a volatile uint8 array. Because accessing unaligned byte
in memory is not atomic and a reader does not acquire the LWLock before reading,
the original implementation poses race condition to readers. That is, a QD may
not see the correct ftsProbeInfo->status values when calling FtsIsSegmentDown(). …

Remove FtsControlBlock->ControlLock.

---

src/backend/fts/README
src/backend/fts/fts.c
src/backend/fts/ftsmessagehandler.c
src/backend/fts/ftsprobe.c
src/include/cdb/cdbfts.h

Remove unused variables and macro, and fix typos in FTS code.
Reword notes in src/backend/fts/README.

FTS code cleanup

---

src/backend/storage/lmgr/lock.c

1) Fix typos and grammar errors in comments;
2) Avoid computing distribXid repetitively in GetLockStatusData().

Minor code refactoring in lock.c.

---

src/backend/access/appendonly/appendonly_visimap.c

off_t should be a signed integer type according to the
POSIX standard, and is typedef-ed as long long on MacOS.
For portability, the print format for a value of type off_t
is specifed as INT64_FORMAT, and the value is also cast to int64.
The related issue is here: https://github.com/greenplum-db/gpdb/issues/11436

Suppress compiler warnings on MacOS for appendonly_visimap.c.

---

src/backend/gporca/libgpopt/src/minidump/CMinidumperUtils.cpp

Properly end minidump filename with a NULL byte

---

src/backend/replication/syncrep.c

In GPDB, the coordinator segment does not follow the usual rules for
synchronous replication. It just assumes that all WAL streaming
connections are synchronous no matter if the synchronous_standby_names
GUC is set or not (to allow the coordinator to skip blocking if the
standby coordinator crashes). To allow asynchronous connections to the
coordinator segment, we should check for the is_for_gp_walreceiver
flag that we label our High Availability mirror connections with. If
it's not set to true, we should not consider the WAL stream to be
synchronous.
I am fully aware that this SyncRepWaitForLSN coordinator segment hack may be removed with the implementation of a coordinator/standby autofailover... but there hasn't been much talk on how that would look (e.g. do we need to keep the hack …

Do not wait for synchronous replication if QD WAL sender is not for HA

---

gpMgmt/bin/gppylib/gparray.py
gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Don't bail out early if some segments can not be rebalanced. Rather rebalance all possible segments, and skip those that are down. Down segments can occur for hosts that are unreachable.
Rebalance segment pairs that are swapped, status is up, host is reachable, and synchronized.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/7X_rebalance)

gprecoverseg: rebalance all possible segments

---

concourse/pipelines/templates/gpdb-tpl.yml
concourse/scripts/common.bash
gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
src/bin/pg_upgrade/test_gpdb.sh

There is already logic in initdb to determine the system locale and
initialize the database with the correct locale values, so this commit
removes the existing default locale logic in gpinitsystem in favor of
letting initdb set the locale on the coordinator and then retrieving the
resulting values to use when initializing the segments.
This commit only changes gpinitsystem's behavior with respect to the
default locale, and then only on systems whose locale did not already
match the default.  Specifying one or more locales with the appropriate
flags still has the same behavior.
The pipeline for this commit is [here](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpinitsystem_locale).

gpinitsystem: Use initdb to determine locale

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/doc/gprecoverseg_help
gpMgmt/doc/gpstate_help

Now that gprecoverseg blocks and shows progress update logging. Also, gpstate does not show recovery progress so remove references to that.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gprecoverseg_logging)

CLI: update logging and help text

---

src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CQueryMutators.cpp
src/backend/optimizer/util/walkers.c
src/include/gpopt/gpdbwrappers.h
src/include/gpopt/translate/CQueryMutators.h
src/include/optimizer/walkers.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

GPDB does not support nested window functions like
select sum(rank(a) over(order by a)) over(order by a)
In 5X_STABLE, this check is done in the planner code path and
then again in the executor. The executor check will cause gpdb
to abort with an internal error.
Since ORCA does not go through the planner syntax check (function
window_tlist_mutator), queries with nested window functions will
abort.
This commit adds a check similar to the one in window_tlist_mutator
to the ORCA code path. To be more precise, to the algebrizer that
is part of the DXL generation.
I tried nested window functions on Postgres, MySQL and Oracle and
those engines don't support them, either.

Fall back for queries with nested window functions

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/doc/gprecoverseg_help
gpMgmt/doc/gpstate_help

Backport of https://github.com/greenplum-db/gpdb/pull/11501
Now that gprecoverseg blocks and shows progress update logging. Also, gpstate does not show recovery progress so remove references to that.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gprecoverseg_logging_6X)

[6X backport] CLI: update logging and help text

---

src/include/catalog/catversion.h
src/include/catalog/pg_namespace.dat
src/include/catalog/pg_publication.h
src/test/regress/expected/namespace_gp.out
src/test/regress/sql/namespace_gp.sql

pg_upgrade via pg_dump and pg_restore binary upgrade mode in functions
to preassign oids (like
pg_catalog.binary_upgrade_set_next_array_pg_type_oid()) use schema
OIDs from old cluster for built-in schemas. Namespace oid is part of
key for preassgined oid search. If the OID is different between source
and destination cluster for pg_aoseg (built-in schema), then can't
find preassigned oid. That results in attempt to allocate new oid for
objects in pg_aoseg schema and fails. This restriction doesn't
exist for user schemas as during restore user schema is created with
the OID from old cluster.
For fun played with pg_toast schema to have OID different between
source and destination cluster. On restore it skips creating toast
table for this case, as decision to create toast table or not during …

Use OID of pg_aoseg same as used for gpdb6 and gpdb5

---

gpMgmt/bin/gpconfig
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstop.py
gpMgmt/bin/gpstart
gpMgmt/bin/gpstop
gpMgmt/doc/gpconfig_help
gpMgmt/doc/gpstart_help
gpMgmt/doc/gpstop_help

Add coordinator flag to gpstop gpstart and gpconfig.
Specifically:
- gpstart and gpstop
- add `-c` and `--coordinator_only`
- any combination of `[-m,-c,--master_only,--coordinator_only]` means what `-m` by itself means
- gpconfig
- add `--coordinatoronly`
-  any combination of `[-m,--masteronly,--coordinatoronly]` means what `-m` by itself means
- add `--coordinatorvalue`
- `[-m,--mastervalue]` is as before; only one should be specified; if both are, which is used is unspecified.
- now , `--coordinatorvalue` has precedence; if specified, its value is used in favor of the existing `-m,--mastervalue`
We are not printing deprecation warnings; these are done at the documentation level.
We are not changing internal uses; this will be done later when we obsolete the existing flags. …

Add coordinator flag to gpstop gpstart and gpconfig

---

concourse/pipelines/gen_pipeline.py

The master of gpdb should be using python3 everywhere, including here.
I am not sure how to test this as it is not called anywhere in the repo, but it does work locally on my machine.

CI: gen_pipeline.py should use python3

---

.clang-tidy
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDBLegacy.h
src/backend/gporca/libgpdbcost/src/CCostModelGPDBLegacy.cpp
src/backend/gporca/libgpopt/include/gpopt/engine/CEnumeratorConfig.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
src/backend/gporca/libgpopt/src/engine/CEnumeratorConfig.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalUnionAll.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperatorFactory.h
src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
src/backend/gporca/server/include/unittest/gpopt/CTestUtils.h
src/backend/gporca/server/include/unittest/gpopt/search/CTreeMapTest.h
src/backend/gporca/server/src/unittest/CTestUtils.cpp
src/backend/gporca/server/src/unittest/gpopt/search/CTreeMapTest.cpp
src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
src/include/gpopt/translate/CTranslatorUtils.h

This patch adds the "readability-non-const-parameter" check to clang-tidy and it also fixes all the warnings that it produces (in both the translator and gporca proper).
[1] https://clang.llvm.org/extra/clang-tidy/checks/readability-non-const-parameter.html

readability: const-qualify pointer parameters

---

src/backend/optimizer/plan/planner.c
src/include/nodes/pathnodes.h
src/include/optimizer/tlist.h

1, make can_mpp_hash a bitmask bit.
2, remove the hasNonCombine check because Greenplum now spills tuples
instead, not the transdata.
3, remove several duplicated declaration.

Resolve several FIXMEs of hash aggregations

---

gpMgmt/bin/Makefile
gpMgmt/bin/gpcheckcat
gpMgmt/bin/gppylib/gpcatalog.py
src/backend/commands/vacuum.c
src/backend/postmaster/autovacuum.c
src/test/regress/expected/.gitignore
src/test/regress/expected/rpt_joins.out
src/test/regress/greenplum_schedule
src/test/regress/input/autovacuum-segment.source
src/test/regress/input/autovacuum-template0-segment.source
src/test/regress/input/autovacuum.source
src/test/regress/output/autovacuum-segment.source
src/test/regress/output/autovacuum-template0-segment.source
src/test/regress/output/autovacuum.source
src/test/regress/regress_gp.c
src/test/regress/sql/.gitignore
src/test/regress/sql/rpt_joins.sql

Allows emergency autovacuum on catalog tables across all databases.
Tables in information_schema are included as system tables in order to
maintain autovacuum behavior parity on template0 from commit 4e65571.
GUC "autovacuum" can still be set if desired, but remains disabled by
default.
I think it's probably debatable whether this is the right approach.  Given
that autovacuum operates on oldest database and in GPDB we do not
autovacuum all tables, it is possible that non-vacuumed user tables
keeps a database old enough that we do not autovacuum template0 as
frequently.
On my list of things to do:
1) Check old incidents relating to performance bottlenecks due to
autovacuum.
2) Investigate further into the GPDB_91_MERGE_FIXME regarding
vacuuming of temp tables from other backends

Enable autovacuum on catalog tables

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/unix.py

print usage is changed from python 2 to python3.
I noticed one of these issues when running gprecoverseg,
"Unable to determine if /data/gpdb7/gpAux/gpdemo/datadirs/dbfast_mirror1/demoDataDir0 is symlink.  Assuming it is not symlink"

Fix print in python utility code.

---

src/backend/tcop/postgres.c

Commit 59da71 fixed elog infrastrucutre to correctly handle
errhidestmt(). As side effect of that, case 1 query "duration" log
messages no more contain query stmt. In GPDB, it becomes very
difficult and it's highly desirable to have query stmt associated with
message to understand the context for message. One can always look at
previous message for session to find the query stmt but that
unnecessarity complicates the debugging.
Hence, marking `errhidestmt(false)` for such duration log messages.

Emit query stmt for duration log messages

---

.travis.yml
gpMgmt/bin/gpinitsystem
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature

Followup to https://github.com/greenplum-db/gpdb/pull/11483
1. Reverts the gpinitsystem Travis CI workaround
2. Set LC_* enviornment variables in Travis CI. Some of the docker containers set LC_ALL and LC_CTYPE to values that are not specified on the system's locale as found via "locale -a". This causes gpinitsystem and possibly initdb to fail. Set these environment variables to the system's locale.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/travisCIDebug)

Travis CI: set LC_* enviornment variables

---

gpMgmt/bin/gpinitsystem

gpinitsystem: use -X with psql to avoid parsing output from .psqlrc
This commit fixes a bug introduced in 267d52c6bdf: psql by default reads
the users .psqlrc file.  If a script parses the output of psql and .psqlrc
causes output, the script may fail.  So add the -X option to psql.  We
also use our standard idiom of using "$PSQL -X -A -t" instead of "psql".
Co-authored-by: Kalen Krempely <kkrempely@vmware.com>
This PR is related to https://github.com/greenplum-db/gpdb/pull/11528 and hence is based on that.
This fixes an issue introduced in https://github.com/greenplum-db/gpdb/pull/11483.
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-gpinitsystem_psql_ignore_psqlrc)

Gpinitsystem psql ignore psqlrc

---

src/backend/parser/parse_coerce.c
src/test/regress/expected/bfv_statistic.out
src/test/regress/expected/bfv_statistic_optimizer.out
src/test/regress/expected/gp_create_view.out
src/test/regress/sql/bfv_statistic.sql
src/test/regress/sql/gp_create_view.sql

The anyarray coercion hack was added circa 2008 to accommodate INSERT
statements into catalog tables such as pg_statistic, which sport the
anyarray type - a pseudo-type that does not handle insertions.
However, coerce_type() is a very low level function that has a variety
of callsites. The logic added has an adverse effect on views, for e.g.
that have an OpExpr with array types:
```
CREATE VIEW fooview AS SELECT '{1}'::int[] = '{2}'::int[];
\d+ fooview
View "public.fooview"
Column  |  Type   | Modifiers | Storage | Description
----------+---------+-----------+---------+-------------
?column? | boolean |           | plain   |
View definition:
SELECT '{1}'::anyarray = '{2}'::anyarray;
```
We can see that the view definition includes incorrect downcasts to the
pseudo-type anyarray. (It …

Limit anyarray coercion to INSERT statements

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h
src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
src/backend/gporca/libgpopt/include/gpopt/operators/CNormalizer.h
src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorDXLToExpr.h
src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformSimplifySubquery.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
src/backend/gporca/libgpopt/src/xforms/CXformSimplifySubquery.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLOperatorFactory.h
src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerDXL.h
src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
src/backend/gporca/libnaucrates/src/parser/CParseHandlerDXL.cpp
src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
src/include/gpopt/translate/CTranslatorDXLToScalar.h
src/include/gpopt/translate/CTranslatorQueryToDXL.h
src/include/gpopt/translate/CTranslatorScalarToDXL.h

This patch is inspired by a change in #11285 but we've wholesale applied it to all of ORCA codebase. See each commit for more topical details.
* The patch is organized into topical commits for convenience of review, but we plan to land the change as one squashed commit
* Most of the changes are fairly mundane, each "mundane" change roughly consists of 3 parts:
1. Replace the look-up logic from a for-loop-over-array-of-function pointers to a straightforward switch case
2. At every site of such a for-loop, there's always an array and a struct defined (with the lookup key and a function pointer). Remove the array, the "init" function, and the struct.
3. This leaves behind a `typedef` that defines a shorthand of the function pointer. Remove the `typedef`.
* "Interesting" changes that require …

Use switch cases instead of for-loops over array-of-function pointers

---

src/backend/gporca/libgpopt/include/gpopt/base/CCTEInfo.h
src/backend/gporca/libgpopt/include/gpopt/base/CColRefSet.h
src/backend/gporca/libgpopt/include/gpopt/base/CConstraint.h
src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h

Replacing an unstable hash function in maps that used CColRef as the key
I got SIGSEGV in production. 
After investigating the bug, I found that the internal structures of the map contain a lost key (CColRef), but cannot find the value for this key.
I think that the reason for this behavior lies in the fact that the hash function used CColRef as a value, which means that any change in CColRef led to a change in the hash value and broke the map.
When I tried to apply the merge to the master, I found that a similar fix was already there. 
https://github.com/greenplum-db/gpdb/commit/65276acb0fd8f6f860d017c1fe5bf6aca7220731
But this fix is not in 6X
Main problem HashMap was ColRefToConstraintArrayMap in CConstraint.h
GP 6.12.1 SIGSEGV Stack (if need i can give core dump):
```
#0 …
```

[Backport] Use CColRef Id for hash/equal comparisons in Orca

---

src/backend/gpopt/relcache/CMDProviderRelcache.cpp
src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdCast.h
src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdColStats.h
src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdGPDB.h
src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdRelStats.h
src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdScCmp.h
src/backend/gporca/libnaucrates/include/naucrates/md/CMDProviderMemory.h
src/backend/gporca/libnaucrates/include/naucrates/md/IMDId.h
src/backend/gporca/libnaucrates/include/naucrates/md/IMDProvider.h
src/backend/gporca/libnaucrates/src/md/CMDProviderMemory.cpp
src/include/gpopt/relcache/CMDProviderRelcache.h

For every object that is requested from GPDB, ORCA currently constructs
and MD object, serializes it completely to a string, and then
de-serializes it back to an MD object before inserting it into the MD
Cache.
Although this needs to be done only once per session for every unique
object, it is very wasteful of resources, and can be skipped entirely
for faster total optimization time.
For instance, this commit brings down the total optimization time for
the following query down from 5.3s to 2.5s (over 2X speed up) by speeding
up metadata retrieval.
```
set statement_mem = "4096MB";
select * from foo_4k;
```
* foo_4k is a partitioned table with 4000 partitions.
* the memory limits are increased to accommodate the larger query plan &
metadata requirements

Speed up ORCA's Relcache translation

---

gpMgmt/bin/analyzedb
gpMgmt/test/behave/mgmt_utils/analyzedb.feature

Added a new option --skip_orca_root_stats to suppress the final
ANALYZE ROOTPARTITION command.
Recommendation: Use this option only if
a) The analyze rootpartition commands take up a lot of time, and
b) You are not using ORCA
Also made the analyzedb log output more readable by suppressing
the SET commands.
NOTE 1: If you use this option, a subsequent analyzedb without the option
will NOT update the root-level stats, unless there have been additional
changes in the table. Example:
analyzedb -d sampledb -s public --skip_orca_root_stats
This analyzes tables but does not create root-level stats for partitioned tables.
analyzedb -d sampledb -s public
This will NOT create the root-level stats of partitioned AO tables, unless
the tables were updated between the two analyzedb runs.
NOTE 2: We …

Add analyzedb option to skip analyze rootstats

---

src/backend/commands/copy.c
src/test/isolation2/input/external_table.source
src/test/isolation2/output/external_table.source
src/test/regress/data/exttab_escape_off.data

escape char will be set as delimiter char if escape is 'OFF' for text
format external table. That should not be expected behavior.
So fix it by checking escape_off flag in CopyReadAttributesText().

Fix external table escape off bug

---

gpMgmt/bin/analyzedb
src/backend/commands/vacuum.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/unsync_guc_name.h

Remove these useless FIXMEs, the most of the question logic is still in
use. So add more comments on it.
For the `ANALYZE ROOTPARTITION`, I don't see why we need to discard it.
And `analyzedb` still rely on it.
Add comment to clarify the FIXME why no need to convert back some params
values before dispatch the vacuum to QEs.
Also, do some small refactor to clean code.

Remove some GPDB_12_MERGE_FIXMEs and add comments in vacuum.c

---

gpAux/gpdemo/demo_cluster.sh
gpMgmt/bin/lib/gp_bash_functions.sh

On linux gpinitsystem was defaulting to the hard coded value of "en_US.utf8". Photon3 uses the value en_US.UTF-8. Later checks in gpinitsystem would fail due to this discrepancy. Thus, query the system for the correct utf-8 variation to use as the default.
Note, we use `$HEAD -1` protects from the unlikely scenario of there being two utf8 variants on the system and grabbing only one, rather than passing both values to initdb causing a failure.
If no utf8 variant is found on the system default to "en_US.utf8" to prevent future checks and code within gpinitsystem from failing, and a friendly error message returned.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6X_gpinitsystem_default_locale)
For reference:
- previous 6X PR https://github.com/greenplum-db/gpdb/pull/11500
- 7X …

[6X] gpinitsystem: update default locale on linux

---

gpMgmt/bin/gpload.py

In merge mode, when inserting the data from the staging
table into the base table, gpload uses a left join sql
to pick up the data which doesn't exist in the base
table. This leads to poor performance when the base
table is big (more than 1 billion): greenplum will hash
the base table and that generates a lot of spill files.
To improve the performance, we decided not to use the
left join sql. Instead, we delete the rows in staging
table which have already existed in the base table so
we can directly insert new rows left in staging table
and avoid left outer join.
Co-authored-by: XiaoxiaoHe <hxiaoxiao@vmware.com>

[6X Backport] Imporve gpload merge performance

---

src/backend/utils/resgroup/resgroup.c
src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql

This commit fixes a situation, when a process waiting for resource group slot receives `SIGTERM`. Some callbacks - `RemoveTempRelationsCallback` for example - try to open new transactions on proc exit. It caused an attempt to add the process to the waiting queue for the second time (and queue corruption). Now we don't add process to the queue if it is already waiting for the slot.
This PR fixes https://github.com/greenplum-db/gpdb/issues/11369 and should be back ported to 6X and 5X.

Fix resource group waiting queue corruption

---

gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py

As of Python 3.3, mock is part of python's standard distribution.
Using it instead of getting it from PyPi.
This also works around a bug.  With Python 3.6.8 and mock==1.0.1, the `addCommand` was being called 5 times but mock thought it was only being called once.  The python standard distribution mock works.
The PyPi mock is still used in other unit tests; those will be removed in a separate effort.
Co-authored-by: Divyesh Vanjare <vanjared@vmware.com>

gpMgmt testing: use unittest.mock instead of PyPi's mock

---

src/backend/parser/parse_partition_gp.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

If the partitioned table doesn't contain subpartition, we should error
out when specifying subpartition in ALTER ADD PARTITION statement.
Create the partition and ignore the subpartitions is not correct.

Error out if ADD PARTITION specify subpartition to an invalid table

---

src/backend/storage/lmgr/lmgr.c

Currently, DescribeLockTag() handles `LOCKTAG_RESOURCE_QUEUE` as default case, so it is printed as `unrecognized locktag 9`, like the example below.
````
DETAIL:  Process 51807 waits for ExclusiveLock on unrecognized locktag type 9; blocked by process 25040.
````

Print description of LOCKTAG_RESOURCE_QUEUE in DescribeLockTag().

---

contrib/pg_upgrade/greenplum/check_gp.c
contrib/pg_upgrade_support/pg_upgrade_support.c

This PR is a follow-up to https://github.com/greenplum-db/gpdb/pull/11506
This commit introduces a new Greenplum check to see if there are any
views with corrupted view definitions (having anyarray casts), which
could arise from the special GPDB specific ANYARRAY coercion logic added
in parse_coerce.c: coerce_type() circa 2008.
The check makes use of a new support UDF that invokes a walker to figure
out if there are any anyarray casts in the view's query tree.
Since, the pg_node_tree type (column type of pg_rewrite.ev_action), does
not allow input, it is hard to bust the catalog in order to perform an
automated test. So we performed a manual test by creating the following busted
views created with server binaries not having the fix.
```sql
View "public.v_anyarray_in_cte"
Column | Type | …
```

Follow-up: pg_upgrade check to detect views with anyarray casts

---

contrib/pg_upgrade_support/pg_upgrade_support.c
src/backend/parser/parse_coerce.c
src/backend/rewrite/rewriteHandler.c
src/include/rewrite/rewriteHandler.h
src/test/regress/expected/bfv_statistic.out
src/test/regress/expected/bfv_statistic_optimizer.out
src/test/regress/expected/gp_create_view.out
src/test/regress/sql/bfv_statistic.sql
src/test/regress/sql/gp_create_view.sql

This is a consolidated backport of #11506 and #11542.
Notes:
1. The first commit has the fix and is slightly different in implementation
from the 6X version, due to the `ParseState` struct's field differences.
2. The second commit is a partial backport of #11542: it includes only
the support UDF and helper walker. To get access to the view's query
tree, backporting the function `get_view_query` from upstream commit
a99c42f291 was necessary. Manually tested the UDF by loading in
the pg_upgrade_support library and ran it on the busted views referenced
in the commit message.

5X backport: Limit anyarray coercion to INSERT statements

---

src/backend/access/transam/xlogarchive.c
src/backend/postmaster/pgarch.c
src/test/gpdb_pitr/test_gpdb_pitr.sh

This commit introduces the contentId (%c) parameter to archive_command
and restore_command. It will be substituted with the contentId of the
segment involved in the archival/recovery process.
Thus, an archive_command = 'cp %p /tmp/archive/seg%c/%f' might be
substituted by (for a 3 segment cluster):
cp pg_wal/00000001000000A900000065 /tmp/archive/seg-1/00000001000000A900000065
cp pg_wal/00000001000000A900000065 /tmp/archive/seg0/00000001000000A900000065
cp pg_wal/00000001000000A900000065 /tmp/archive/seg1/00000001000000A900000065
cp pg_wal/00000001000000A900000065 /tmp/archive/seg2/00000001000000A900000065
The param will serve as a piece of identifying information for a WAL
stream from a given segment.
test_gpdb_pitr.sh updated to exercise the (%c) substitution.
Co-authored-by: Soumyadeep …

Introduce contentId parameter for WAL archiving

---

src/backend/cdb/motion/ic_proxy_addr.c
src/backend/nodes/list.c
src/backend/optimizer/util/pathnode.c
src/backend/parser/parse_partition_gp.c
src/include/nodes/pg_list.h

This interface is exposed to extensions.  And the Greenplum specific modifications were used only by Greenplum specific partitioning code.
The `pg_auto_failover` extension uses `list_qsort` and fails to build with Greenplum without this patch.
@gfphoenix78 it is inspired from your commit https://github.com/gfphoenix78/gpdb/commit/a589329dfe3b1e1ebaea955fd612d9019a710f6c

Restore list_qsort interface to how it is in PostgreSQL

---

src/backend/access/external/url.c
src/backend/access/external/url_curl.c
src/backend/utils/misc/guc_gp.c
src/bin/gpfdist/regress/input/exttab1.source
src/bin/gpfdist/regress/output/exttab1.source
src/include/access/url.h
src/include/utils/unsync_guc_name.h

Reading from gpfdist external table can generate lots of HTTP traffic
in very short time window. This may cause intermittent network issues
resulting in "No route to host" error. Backdown and retry in such scenario.
Reuse the backdown and retry logic for writable external table as
gp_perform_backoff_and_check_response. Pass read/write specific
part as function pointer(multi_perform_work/easy_perform_work).   
(cherry picked from commit 7f1589a786e7fd9cac950ee104a729e370ec3606)
This patch depends on gpfdist_retry_timeout GUC. So backport the commit of adding gpfdist_retry_timeout GUC too.
(cherry picked from commit ab73713211e93a95e696429f4821e893ee3397de)

[6X] Backdown and retry for "No route to host" in gpfdist ext table

---

gpMgmt/bin/gppylib/operations/package.py
gpMgmt/bin/gppylib/operations/test/regress/test_package/__init__.py
gpMgmt/bin/gppylib/operations/test/regress/test_package/test_regress_simple_negative.py
gpMgmt/bin/gppylib/operations/test/test_package.py
gpMgmt/bin/gppylib/programs/gppkg.py
gpMgmt/bin/gppylib/test/unit/test_unit_mainUtils.py
gpMgmt/bin/gppylib/test/unit/test_unit_package.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpactivatestandby.feature
gpMgmt/test/behave/mgmt_utils/gpconfig.feature
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/gppkg.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Python does not guarantee backwards source compatibility.  We need to make a few changes to allow our unittests to run in Python3 later minor versions:
- implement platform.linux_distribution() directly
As of Python 3.8, the standard library module 'platform' does not have
linux_distribution().  However, we only use this function on our supported
production platforms.  These evidently all use systemd, which requires a file
/etc/os-release containing all the information we need.
- gppkg: remove import of platform for general cleanup
We only use x86_64 architectures for Greenplum, so remove packaging support
for 32-bit.  The motivation is to remove the import of platform.  This is general cleanup and isn't
strictly required but removes an import.
- gpMgmt unit tests: remove obsolete field …

gpMgmt unittests: allow unittests to run on new Python3 distributions

---

src/backend/libpq/Makefile
src/backend/libpq/auth.c
src/backend/libpq/be-gssapi-common.c
src/backend/libpq/be-secure-gssapi.c
src/include/libpq/be-gssapi-common.h

In GPDB backend, we also link with some objects of the frontend for
inter-communicating. Rename the duplicated `pg_GSS_error()` with a "_be"
suffix to avoid linker error.

Renanme the duplicated symbol of backend libpq

---

src/backend/utils/resgroup/resgroup.c
src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql

Commit 4d5a653 fix the resource group wait queue corruption issue. On top of
that, this commit bypass resource group when the proc is exiting so that the
proc can terminate immediately.

Bypass resource group when the proc is exiting in progress

---

gpMgmt/bin/gppylib/gparray.py
gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

cherry-pick of https://github.com/greenplum-db/gpdb/pull/11484
Don't bail out early if some segments can not be rebalanced. Rather rebalance all possible segments, and skip those that are down. Down segments can occur for hosts that are unreachable.
Rebalance segment pairs that are swapped, status is up, host is reachable, and synchronized.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/rebalance_6X)

[6X backport] gprecoverseg: rebalance all possible segments

---

contrib/pg_upgrade/greenplum/check_gp.c

Setting search_path to `''` in 5X, during a 5X->6X upgrade leads to:
```
SET search_path to '';
ERROR:  schema "" does not exist.
```
So, set search_path to `'pg_catalog'` instead, which has the same effect.
PG Documentation excerpt: The system catalog schema, pg_catalog, is
always searched, whether it is mentioned in the path or not. If it is
mentioned in the path then it will be searched in the specified order.
If pg_catalog is not in the path then it will be searched before
searching any of the path items.
Co-authored-by: David Krieger <dkrieger@vmware.com>
Co-authored-by: Kevin Yeap <kyeap@vmware.com>

check_gp.c: Use pg_catalog to empty out search path

---

src/backend/catalog/system_views.sql
src/include/catalog/catversion.h
src/test/gpdb_pitr/.gitignore
src/test/gpdb_pitr/Makefile
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql

When calling pg_switch_wal, it will only execute on the coordinator
segment. To run pg_switch_wal on the primary segments, we would need
to use gp_dist_random or use utility-mode connections. To make things
easier for end-users and help with external WAL archiving projects,
this commit introduces a new catalog function that switches WAL
segment files on all seegments by using the GPDB-specific EXECUTE ON
[COORDINATOR | ALL SEGMENTS] feature of CREATE FUNCTION (a less hacky
way compared to using gp_dist_random for function calls).
Co-authored-by: Jimmy Yih <jyih@pivotal.io>

Add a gp_switch_wal() catalog function to system_views.sql

---

src/backend/optimizer/plan/plangroupext.c
src/test/regress/expected/aggregate_with_groupingsets.out
src/test/regress/expected/olap_group.out

When creating Agg/Group nodes for rollups, previously we would skip the
final Agg for Plan nodes with Flow of FLOW_SINGLETON. This works fine in
most cases but not for GroupingFunc. As a result, queries such as the
one below would have wrong results for GroupingFunc.
create table t1(a int, b int) distributed replicated;
insert into t1 values(1,1);
select grouping(a, b), a, b from t1 group by grouping sets((a, b),(a));
grouping | a | b
----------+---+---
0 | 1 | 1
0 | 1 |
(2 rows)
As a workaround, this PR just removes that logic and creates final Agg
if needed even for Plan nodes with Flow of FLOW_SINGLETON.

Fix GroupingFunc for Plan nodes with SINGLETON flow

---

concourse/scripts/builds/GpBuild.py
concourse/scripts/common.bash
concourse/scripts/ic_gpdb.bash

And sort the flags in alphabetical order.
We do the `configure` in the test task just for `src/test`, and some
tests are decided to run or not based on that `configure` but not the
one which built the binary.
For instance, this snippet is in the `src/test/Makefile`:
```
ifeq ($(with_gssapi),yes)
ifneq (,$(filter kerberos,$(PG_TEST_EXTRA)))
SUBDIRS += kerberos
SUBDIRS += gpkerberos
endif
```

Enable tests for GSSAPI and SSL on CI

---

src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/nodes/readfuncs.c
src/backend/tcop/utility.c
src/test/isolation2/expected/segwalrep/mirror_promotion.out
src/test/isolation2/expected/terminate_in_gang_creation.out
src/test/isolation2/sql/segwalrep/mirror_promotion.sql
src/test/isolation2/sql/terminate_in_gang_creation.sql
src/test/regress/expected/disable_autovacuum.out
src/test/regress/expected/enable_autovacuum.out
src/test/regress/sql/disable_autovacuum.sql
src/test/regress/sql/enable_autovacuum.sql

`ALTER SYSTEM` only modified the GUC on coordinator. Changing it to dispatch the command to segments as well. Would be ideal in long run for `ALTER SYSTEM` similar to `gpconfig` to have `coordinator_only` option. But for now it seems more natural to set GUC on all nodes instead of only coordinator. Given this command directly works directly on filesystem and not transactional, if fails on a segment, the modification will still remain on other segments. I believe this is no different from `gpconfig` failing half way.
Also, in this PR then changing disable/enable autovacuum test to take effect on segments along with coordinator. That hopefully should help to fix the flakiness we are seeing in CI post the autovacuum feature was enabled for catalog on segments.

Dispatch ALTER SYSTEM command

---

gpMgmt/bin/gpload_test/Makefile

Gpload doesn't need to support ubuntu, and some test cases in ubuntu will fail. We disable gpload test in ubuntu for further convenience.
Modify Makefile in gpload_test folder, skip gpload test if TEST_OS contains ubuntu.
This change only skips gpload test if the OS is ubuntu and would not impact other tests.

disable gpload test in ubuntu

---

src/backend/utils/resgroup/resgroup.c
src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql

[5X backport] backport 2 commits to fix resource group wait queue corruption

---

src/backend/utils/resgroup/resgroup.c
src/test/isolation2/expected/resgroup/resgroup_cancel_terminate_concurrency.out
src/test/isolation2/sql/resgroup/resgroup_cancel_terminate_concurrency.sql

[6X backport] backport 2 commits to fix resource group wait queue corruption

---

src/backend/parser/parse_func.c
src/interfaces/gppc/test/expected/tabfunc_gppc_demo.out
src/test/regress/expected/qp_dml_joins.out
src/test/regress/expected/qp_dml_joins_optimizer.out
src/test/regress/expected/qp_functions.out
src/test/regress/sql/qp_functions.sql

A set returning function when used on the left of ANY/ALL clause in a WHERE clause leads to wrong results.  Such queries are prohibited in PostgreSQL version 12 / Greenplum 7.  This patch prohibits the queries in 6X by partially cherry-picking commit a4c35ea1 from REL_12_STABLE.
The executor is not equipped to handle more than one row when evaluating a scalar operator expresssion (ANY/ALL), see
`ExecEvalFPScalarArrayStr` as an example.
I have refrained from pulling in follow up commits such as d43a619c60405ecda275ca9e3ac9ead242e20ecb because that would be too much behavior churn on a stable branch.

6X-only Prohibit set returning functions in WHERE clause

---

src/backend/commands/tablecmds_gp.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

When finding partition by name, After PG12 merge, users may use pg
syntax to do the partition maintenance, like `ALTER TABLE ...
DETACH/ATTACH PARTITION`.
This may cause the partition table's name different from GPDB's
partition table name pattern <parentname>_<level>_prt_<partition_name>.
When this happens, it's not possible to find the target partition table
based on the name specified by the user.
Users could always use PARTITION FOR or pg syntax instead.

GpFindTargetPartition() based on name should consider name mismatch

---

src/backend/catalog/index.c

We have already considered IsBinaryUpgrade in GetNewOrPreassignedOid,
so there is no need to deal with this variable in index_create.

Remove fixme in function 'index_create'

---

src/backend/utils/adt/dbsize.c

We still need use fdw functions to caculate the size of forign table.
So keep the codes and remove the fix me on the fdw code. But we can
remove the codes checking oid is zero.

Remove the fixmes on pg_relation_size

---

src/backend/access/transam/xlog.c
src/test/gpdb_pitr/test_gpdb_pitr.sh
src/test/gpdb_pitr/test_gpdb_pitr_cleanup.sh

This PR comprises of two commits.
The first one removes some unnecessary diffs (some of which are
historical) in xlog.c by performing a re-merge against the 12 merge
iteration PG parent: 9e1c9f95942.
The second one updates the gpdb_pitr test suite to the post 12 merge
world. There is an [upstream bug](https://www.postgresql.org/message-id/flat/CAE-ML%2B_EjH_fzfq1F3RJ1%3DXaaNG%3D-Jz-i3JqkNhXiLAsM3z-Ew%40mail.gmail.com) that hinders it from fully passing. The
plan is to backport that fix, when it is accepted upstream and then add
this test suite to CI.
More details in the commit messages.
Co-authored-by: Kevin Yeap <kyeap@vmware.com>

Miscellaneous improvements to WAL archiving/PITR

---

src/backend/commands/explain_gp.c

Earlier, we used strchr() to seek out the newline in
cdbexplain_formatExtraText(). What we didn't consider that the newline
could be located beyond notelen.
This led to issues such as the following incorrect extra text report in
EXPLAIN ANALYZE output:
```
Extra Text: (seg1)   Hash chain length 2.1 avg, 5 max, using 21 of 32
buckets; total 0 expansions.123 groups total in 32 batches; 1 overflows;
123 spill groups.
```
when the output should have been:
```
Extra Text: (seg1)   Hash chain length 2.1 avg, 5 max, using 21 of 32
buckets; total 0 expansions.
```
Co-authored-by: Jesse Zhang<jzhang@pivotal.io>

Use memchr instead of strchr inside cdbexplain_formatExtraText()

---

src/backend/cdb/motion/ic_proxy_pkt_cache.c
src/backend/cdb/motion/ic_proxy_pkt_cache.h

icproxy's flow control is based on the PAUSE/RESUME, which needs to
route to a remote client. This asynchronous flow control may result
in the size of packet cache increase rapidly but packet returned to
free list slowly.
Packet cache should have a maximum size to limit the total memory
used by icproxy background worker. When limit is reached, the packet
should be freed instead putting to free list.
Note that this patch could not fix the flow control issue, but only
helps to avoid the bloating of packet cache.

[Backport] ic-proxy: limit max size of packet cache. (#11489)

---

gpdb-doc/dita/admin_guide/highavail/topics/g-recovering-from-segment-failures.xml

Now that gprecoverseg reports progress of incremental recovery we no longer need to tell user to run gpstate -m. 
View revised content online here (you must be on VPN): 
https://schaffer-segment.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/highavail/topics/g-recovering-from-segment-failures.html

DOCS: Removing references to gpstate -m 

---

gpdb-doc/dita/utility_guide/ref/gpstate.xml

Now that customers can use gprecoverseg to report on both incremental and full recovery they don't need to use gpstate -m to get a progress report.

DOCS: Remove reference to relationship between the -m flag and synch

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

Modified some settings for guc gpfdist_retry_timeout to the master branch (it is listed alphabetically now)
Corresponding PR: https://github.com/greenplum-db/gpdb/pull/11434
Can be viewed here: https://mireia-guc-master.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html#gpfdist_retry_timeout

Docs - gpfdist guc for master

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

Adding guc gpfdist_retry_timeout to the 6X_STABLE branch.
Corresponding PR: https://github.com/greenplum-db/gpdb/pull/11406
Can be viewed here: https://mireia-guc-6x.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html#gpfdist_retry_timeout

Docs - Adding GUC gpfdist_retry_timeout to 6X_STABLE

---

gpdb-doc/dita/ref_guide/modules/dblink.xml

Documented the following PR: https://github.com/greenplum-db/gpdb/pull/11566
Added a Warning section to highlight this is a high risk functionality and also mentioned that pg_hba.conf needs to be correctly configured for dblink_connect_u to work.
You can preview the page by using the following link (needs VPN access):
https://mireia-dblink-branded.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/modules/dblink.html

Docs - adding dblink new function dblink_connect_no_auth

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
src/backend/postmaster/postmaster.c
src/bin/initdb/initdb.c

71043c5b1859a2f6340d46e0d7f808cdf35955e8 removed pg_utilitymodedtmredo related
code in kernel, but today I found still there are some related code in
utilities. Let's clean up them.

Remove rest pg_utilitymodedtmredo related code.

---

src/backend/fts/ftsmessagehandler.c

O_EXCL should be usually with O_CREAT.  No need of PG_O_DIRECT or fsync since
usually if there is io error, read/write/open have already detected, also
O_DIRECT is broken at this moment in some releases (e.g. Photon OS) - this
leads all primaries to be marked as down by fts.

Fix io checking in fts probe

---

gpdb-doc/dita/analytics/madlib.xml
gpdb-doc/dita/install_guide/install_python_dsmod.xml

Here are the links of the staging app for review:
https://mireia-deeplearning.sc2-04-pcf1-apps.oc.vmware.com/7-0/analytics/madlib.html
https://mireia-deeplearning.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/install_python_dsmod.html
Note I have used the GPDB branded book since Python Data Science Module Package is only available on the branded GPDB docs.

Added reference to RHEL 6 not supported on both sections

---

gpMgmt/bin/gppylib/commands/gp.py

Make sure gpstate should not log Error message if no expansion is in progress
resolves https://github.com/greenplum-db/gpdb/issues/11554
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-fix_gpstate_issueno_11554)

gpstate: Do not log ERROR during gpstate if gpexpand.status table does not exists

---

src/bin/pg_rewind/filemap.c

"log" is part of excluded directory list. The semantics of exclude
file/directory list is to avoid copy from source to target. But also
as side effect if those files are present in target, they are removed
as well.
This semantic is good for most of things but for "log" directory don't
wish to get them removed. Hence, adding logic to add this exception.
(I am continuing to look into why we even scan and record internal structure files in directories as part of exclude list. Seems avoiding that should help performance as "log" and other directories in that exclude list can have many files. But that's separate problem.)

pg_rewind: avoid removing "log" files

---

src/backend/cdb/cdbgroupingpaths.c
src/test/regress/expected/gp_dqa.out
src/test/regress/expected/gp_dqa_optimizer.out
src/test/regress/sql/gp_dqa.sql

For the following query:
create table t(a int, b int, c int) distributed by (a);
select count(distinct a), sum(b), sum(c) from t;
Planner will gather first gather all tuples into QD and
then do a single agg. However, ORCA and 6X's planner will
choose two-stage agg. If the data is huge and first stage
can remove much data, two-stage agg plan is much faster.
It seems such regression is because we forget the Single-DQA-With-Group
case in the function add_first_stage_group_agg_path. This commit
adds back two stage agg plan for this kind of query.

Support two stage agg for Single-DQA-With-Group.

---

src/backend/executor/nodeNestloop.c
src/backend/gporca/data/dxl/minidump/AllSubqueryWithSubqueryInScalar.mdp
src/backend/gporca/data/dxl/minidump/AntiSemiJoin2Select-1.mdp
src/backend/gporca/data/dxl/minidump/AntiSemiJoin2Select-2.mdp
src/backend/gporca/data/dxl/minidump/NotInToLASJ.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-LASJ.mdp
src/backend/gporca/data/dxl/minidump/Subq2NotInWhereLOJ.mdp
src/backend/gporca/data/dxl/minidump/SubqAll-Limit1.mdp
src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
src/test/regress/expected/notin_optimizer.out

`NOT IN` is equivalent to `<> ALL` SQL expression and should be replaced with LAS-Apply in `CSubqueryHandler::FRemoveAllSubquery()`. Before current commit ORCA transformed `<> ALL` subquery in filter
incorrectly. A query
```sql
select * from R where R.a <> ALL (select S.b from S)
```
was translated to
```sql
select * from R LAS-APPLY-Not-In (select S.b from S where S.b = R.a) on true;
```
This plan returns wrong results when `S.b` is `NULL`. To handle it (`S.b = R.a`) should be checked with `IS_NOT_FALSE` expression.
For example in https://github.com/greenplum-db/gpdb/issues/10967
```sql
create table t1(a int) distributed by (a);
insert into t1 values (1), (2), (3);
select * from t1 where a not in (
select b.a from t1 a left join t1 b on false
);
```
returned incorrect `(1), (2), (3)` …

Fix preprocessing of NOT IN to LAS-Apply in filter

---

src/backend/commands/tablecmds_gp.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

If two drop partition cmds are specified in same alter table stmt,
the blow check still works to make sure the partitioned table at least
have one partition table.
When the first drop gets executed, the catalog will have an update which make
current Relation get invalid and call RelationClearRelation to refresh
the Relation. After that the next drop cmd will have parties->nparts = 1,
and raise error to abort.
So remove the fixme and add more tests to cover it.

Remove FIXME for multi drop partition table in same alter statement.

---

.travis.yml

This commit removes the ubuntu-toolchain-r-test repo from our Travis CI
environment, and reverts the choice of GCC-8 to whatever Ubuntu provides
from its main repository. In general, the ubuntu-toolchain-r-test repo
is unstable, but it only recently manifests itself as a package conflict
in the xenial+clang job in the matrix.  The folklore of having to add
ubuntu-toolchain-r-test was a relic from the olden days of Ubuntu 12.04
and 14.04, when running mildly modern version of Clang (3.3?) needed a
backport of glibc from ubuntu-toolchain-r-test. Starting from Ubuntu
16.04 (Xenial) this is no longer true.
Note I also had to bump up the OS to Ubuntu Bionic for the Clang 7 build
because libstdc++ from GCC 5 (the version shipped in Ubuntu Xenial) has
a bug (https://wg21.link/N4387) that's only …

Use default GCC/Clang toolchain from Travis CI.

---

gpMgmt/bin/gppylib/commands/gp.py

Make sure gpstate should not log Error message if no expansion is in progress
resolves #11554
backport of https://github.com/greenplum-db/gpdb/pull/11615
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-fix_gpstate_6X?group=all)

6X backport: gpstate: Avoid logging ERROR if no expansion is in progress 

---

gpMgmt/bin/gpdeletesystem
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/db/test/unit/test_cluster_dbconn.py
gpMgmt/bin/gppylib/gparray.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

In 6X, the "with" statement context manager closes the connection.
In 7X, with py3 and PyGreSQL 5.2.2 and our dbconn wrapper, we need to explicitly close these connections correctly, since the exit function for "with" context doesn't close it anymore.
Fixing these cases by using contextlib.closing to keep 7X code semantically similar to 6X
Fixing additional cases in gpMgmt where connections aren't closed correctly
Concourse pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/fix_dbconn

Fix dbconn connections to be closed correctly

---

gpdb-doc/dita/install_guide/upgrading.xml
gpdb-doc/dita/utility_guide/ref/gppkg.xml

This PR also updates the "Upgrading from an Earlier Greenplum 6 Release" topic so that gppkg is not used to reinstall extensions until after GPDB is restarted.

Docs: discourage use of gppkg --migrate option

---

gpdb-doc/dita/ref_guide/sql_commands/DELETE.xml

Confirmed this operation doesn't take place so removing from our Docs
Opening against master but might need to be backported

Docs: removing reference of DELETE adding implicit TRUNCATE

---

gpdb-doc/dita/utility_guide/ref/gpstate.xml

Removing content that is no longer part of gpstate output.
Staging here (you must be on VPN):  https://jenny-obsolete.sc2-04-pcf1-apps.oc.vmware.com

DOCS: Removing obsolete output.

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

DOCS: Document limit on number of concurrent inserts into append-optimized table.

---

src/backend/gporca/server/src/startup/main.cpp

Running `gporca_test -d test.mdp -p` will print out the DXL plan to stdout, similar to what `EXPLAIN DXL` does in GPDB.
There is another option `-T 103001` which will dump out the entire minidump (in a minidumps directory) but I did find this option more convenient for faster iteration.

Print serialized DXL Plan in gporca_test with -p argument

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-limitations.xml

It was pointed out that "Feature not supported: Multiple Distinct Qualified Aggregates are disabled in the optimizer" had not been documented under ORCA limitations. Adding it to the list followed by the example used in that user case.

Docs: added Multiple Distinct Qualified Aggregates to ORCA limitations

---

gpdb-doc/dita/ref_guide/modules/dblink.xml

Added short reference to dblink_connect_u signatures based on Postgresql docs:
https://github.com/mperezfuster/gpdb/pull/new/docs-dblink-signatures

added dblink_connect_u signatures description

---

gpdb-doc/dita/ref_guide/modules/dblink.xml

Added short reference to dblink_connect_u signatures based on Postgresql docs:
https://github.com/mperezfuster/gpdb/pull/new/docs-dblink-signatures
Also for new function dblink_connect_no_auth (only for 6X_STABLE)

added dblink_connect_u and dblink_connect_no_auth signatures description

---

gpdb-doc/markdown/pxf/gphdfs-pxf-migrate.html.md.erb

updates to the gphdfs migration document for the upcoming pxf v6.0.0 release:
- config file locations have changed, add a v6 variant
- pxf 5.15.1 is embedded in greenplum 6, add an optional step to install pxf 6.
- changes to config/start procedure depending on which version of pxf migrating to.
since pxf 5.15.1 is embedded in pxf, that is the version of the pxf docs that are linked to from this page.  if the user has installed a pxf rpm, it is likely a different version (5.16+ or soon-to-be 6.0), they will manually need to switch the version on the pxf doc site.  i don't think there aren't major changes to these topics between the versions, so seems ok?  
doc review site link:  http://docs-lisa-gphdfs-pxf6.cfapps.io/7-0/pxf/gphdfs-pxf-migrate.html

docs - gphdfs to pxf migration doc updates for pxf v6

---

concourse/scripts/configurations/pg_upgrade_gpinitsystem_config
gpAux/gpdemo/demo_cluster.sh
gpMgmt/bin/gpinitsystem
gpMgmt/doc/gpconfigs/gpinitsystem_config
gpMgmt/doc/gpconfigs/gpinitsystem_singlenode
gpMgmt/doc/gpconfigs/gpinitsystem_test
gpMgmt/doc/gpinitsystem_help
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave_utils/configs/gpinitconfig_mirror_template
gpMgmt/test/behave_utils/configs/gpinitconfig_template
gpdb-doc/dita/install_guide/init_gpdb.xml
gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
src/tools/docker/ubuntu16_ppa-persistent/container_init.sh

The ARRAY_NAME variable hasn't been used for anything since 4.2 at the latest.
It still shows up in sample config files and is marked as a required argument in the docs.
Removing the variable from GP7
If ARRAY_NAME is passed in GP7 then gpinitsystem should start the cluster successfully.

remove ARRAY_NAME variable

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmapinsert.c
src/backend/access/bitmap/bitmapsearch.c
src/backend/access/bitmap/bitmaputil.c
src/backend/optimizer/path/indxpath.c
src/include/access/bitmap.h
src/include/access/bitmap_private.h
src/test/isolation2/expected/bitmap_index_concurrent.out
src/test/isolation2/sql/bitmap_index_concurrent.sql

Concurrent scan on bitmap index when there's insert running in the backend
may cause the bitmap scan read wrong tid.
If a LOV has multiple bitmap pages, and the index insert tries to insert a tid
into a compressed word on a full bitmap page(Let's call the page `PAGE_FULL`).
Then it'll try to find free space on next bitmap page(Let's call the page `PAGE_NEXT`)
and rearrange the words and copy extra words into the next bitmap page.
So when the above insertion happens, imagine below case:
1. Query on bitmap: A query starts and reads all bitmap pages to `PAGE_FULL`, increase
next tid to fetch, release the lock after reading each page.
2. Concurrent insert: insert a tid into `PAGE_FULL` cause expand compressed words to
new words, and rearrange words into `PAGE_NEXT`.
3. Query on bitmap: fetch …

Fix bitmap index scan when concurrent insert update full bitmap page

---

src/backend/commands/extension.c
src/backend/commands/functioncmds.c
src/test/regress/expected/create_extension_gp_debug_segments.out
src/test/regress/greenplum_schedule
src/test/regress/sql/create_extension_gp_debug_segments.sql

This is to fix bug [#11304](https://github.com/greenplum-db/gpdb/issues/11304) the context is
1:in cdbdisp_dispatchCommandInternal, if QE return err, the
cdbdisp_destroyDispatcherState which must be called is missing.
2:QE was set to the wrong state due to the execution error.
If we call cdbdisp_destroyDispatcherState directly
during error handling in cdbdisp_dispatchCommandInternal,
the original code called CdbDispatchUtilityStatement to
Reset QE CurrentExtensionObject, and QE is likely in abort
state, so the error return to client will be the QE error.
so we call DisconnectAndDestroyAllGangs to reset QE's state.
and PostgresMain will eventually call to cdbdisp_destroyDispatcherState
by calling AbortCurrentTransaction in the top of try catch stack.

Reset QE CurrentExtensionObject on qe

---

src/backend/optimizer/util/clauses.c
src/test/regress/expected/bfv_partition_plans.out
src/test/regress/expected/bfv_partition_plans_optimizer.out
src/test/regress/expected/direct_dispatch.out
src/test/regress/expected/direct_dispatch_optimizer.out
src/test/regress/expected/partition_prune.out
src/test/regress/expected/partition_prune_optimizer.out
src/test/regress/expected/plancache.out
src/test/regress/expected/plancache_optimizer.out
src/test/regress/expected/rowsecurity.out
src/test/regress/expected/select_views.out
src/test/regress/expected/select_views_optimizer.out
src/test/regress/expected/update.out
src/test/regress/expected/update_optimizer.out
src/test/regress/sql/bfv_partition_plans.sql
src/test/regress/sql/direct_dispatch.sql
src/test/regress/sql/partition_prune.sql
src/test/regress/sql/plancache.sql

The issue is that we do not pre-evaluate SQLValueFunction for a single
row insertion query and add a redistribution motion to it where performance
degrades significantly. However, for a stable build-in function like
now(), we can pre-evaluate it and directly dispatch it to a single segment.
An example:
+ insert into t values(now());
+ insert into t values(current_timestamp);
Actually, the two functions do the same thing and exhibit the same
behavior. But for the first query, we can use the direct dispatch
feature but for the second one we cannot. This commit aims to solve
this problem.

Fix direct dispatch issue.

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmapinsert.c
src/backend/access/bitmap/bitmapsearch.c
src/backend/access/bitmap/bitmaputil.c
src/backend/optimizer/path/indxpath.c
src/include/access/bitmap.h
src/test/isolation2/expected/bitmap_index_concurrent.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_index_concurrent.sql

Concurrent scan on bitmap index when there's insert running in the
backend may cause the bitmap scan read wrong tid.
If a LOV has multiple bitmap pages, and the index insert tries to insert
a tid into a compressed word on a full bitmap page(Let's call the page
`PAGE_FULL`).
Then it'll try to find free space on next bitmap page(Let's call the
page `PAGE_NEXT`) and rearrange the words and copy extra words into
the next bitmap page.
So when the above insertion happens, imagine below case:
1. Query on bitmap: A query starts and reads all bitmap pages to
`PAGE_FULL`, increase
next tid to fetch, release lock after reading each page.
2. Concurrent insert: insert a tid into `PAGE_FULL` cause expand
compressed words to
new words, and rearrange words into `PAGE_NEXT`.
3. Query on bitmap: fetch …

[6X Backport]Fix bitmap index scan when concurrent insert update full bitmap page

---

gpMgmt/bin/analyzedb
gpMgmt/test/behave/mgmt_utils/analyzedb.feature
gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py

This is a backport of 6X PR https://github.com/greenplum-db/gpdb/pull/11654.
The analyzedb utility leaves a state directory each time it is run (in
a way that it actually performs ANALYZE commands). These state
directories are stored in a subdirectory db_analyze below the master
data directory.
With this fix we preserve only state directories that less than 8 days
old, with one exception: We also preserve the 3 most recent state
directories regardless of age, plus the current state directory.
All others are removed automatically.
Users should not need to deal with state directories, except when
using the `--clean_last` option that restores the state of the previous
analyzedb run. Leaving at least 3 historic state directories allows to
use this option at least 3 times in a row (more often …

Clean stale state directories in analyzedb

---

gpAux/Makefile

package gppylib to `path-to-loaders/bin/ext` in loaders for gp5
Loaders for gpdb5 do not include gppylib, and that will cause gpload cannot find the gpversion of server and run in gpdb5 compatibility mode.

include gppylib when compile loaders

---

src/backend/executor/nodeBitmapAnd.c
src/backend/executor/nodeBitmapHeapscan.c
src/backend/executor/nodeBitmapIndexscan.c
src/backend/executor/nodeBitmapOr.c
src/backend/nodes/tidbitmap.c

For upstream, `BitmapIndexScanState.biss_result` only used to store
`tbm_create` result in `MultiExecBitmapOr` and BitmapIndexScanState does
not have the responsibility to free it, and normally BitmapIndexScanState
always has a new biss_result each time.
But for GPDB, AM `amgetbitmap` may return different types of node like
`TIDBitmap` and `StreamBitmap`. And we used to store the node as
`BitmapIndexScanState.biss_result` and make BitmapIndexScanState take
care of it. This leads GPDB to have different code logic compare with
upstream. Actually, this is not needed, we can just do as upstream does.
Free the bitmap as soon as possible.
So refactor it to make code consistent with upstream.
Also remove a GPDB_84_MERGE_FIXME in nodeBitmapAnd.c which should
not have any issues now.

Resolve FIXME in nodeBitmapOr

---

src/backend/fts/ftsmessagehandler.c

O_EXCL should be with O_CREAT only since per open(2) man page the behavior of
O_EXCL without O_CREAT is undefined. O_DIRECT is not supported on some file
systems (e.g. tmpfs). open() with O_DIRECT on those file systems returns with
errno EINVAL so let's tolerate this kind of error in fts io checking code
to avoid that the node is marked s down by FTS.
Reviewed by: Ashwin Agrawal <aashwin@vmware.com>
Reviewed-by: Asim R P <pasim@vmware.com>
(cherry picked from commit 4bb42cbcbe9795802f2f0d20c870533af7ae46e3)

[6X Backport] Fix io checking in fts probe (#11586)

---

src/test/regress/expected/plancache.out
src/test/regress/expected/plancache_optimizer.out
src/test/regress/sql/plancache.sql

In #11607, we optimized single row insertion statements by pre-evaluate SQLValueFunction and added some test to ensure correctness of prepare/execute statements. However, we met a test case failure during the execution. The result is as follows.
```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3
/tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/plancache.out
/tmp/build/e18b2f02/gpdb_src/src/test/regress/results/plancache.out
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/plancache.out
2021-03-25 08:12:17.579226940 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/plancache.out
2021-03-25 08:12:17.607228586 +0000
@@ -418,15 +418,15 @@
insert into test_prepare_sql_value_function values (1,
current_timestamp);
-- should return one row
execute …
```

Fix a test case bug caused by #11607

---

src/backend/gporca/server/src/unittest/CTestUtils.cpp
src/backend/gporca/server/src/unittest/dxl/statistics/CFilterCardinalityTest.cpp
src/backend/gporca/server/src/unittest/dxl/statistics/CMCVTest.cpp

Current PR resolves the issue https://github.com/greenplum-db/gpdb/issues/11281.
The [CTestUtils::EresCompare()](https://github.com/greenplum-db/gpdb/blob/7d7615cebe8bc763d95b8b75971f8e3ccb7054ce/src/backend/gporca/server/src/unittest/CTestUtils.cpp#L2861-L2893) function compares incoming strings that represents actual and expected objects participating in tests. As a side effect, this function logs to output stream (that is defined as incoming function argument) the result of such comparison including dumps of xmls in case of inequality.
Before the current patch any callers of `CTestUtils::EresCompare()` just ignored the output stream with comparison logs. As result, in the presence of failed object comparison inside `CTestUtils::EresCompare()` it's impossible to define the fact that …

Show log entries from CTestUtils::EresCompare routine

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
src/test/isolation2/expected/dispatcher_fts_error.out
src/test/isolation2/expected/fts_dns_error.out
src/test/isolation2/expected/segwalrep/max_slot_wal_keep_size.out

gprecoverseg completes resync before finishing.
Updating the output message to not ask the user anymore for checking resync status.
Updating tests expected output.
Tracker story: https://www.pivotaltracker.com/story/show/177353609
7X PR: https://github.com/greenplum-db/gpdb/pull/11713

6X gprecoverseg -r: change finishing output

---

gpdb-doc/dita/utility_guide/ref/gpload.xml

Removed the reference to "(or inserted in the case of a MERGE)." for gpload option UPDATE_CONDITION since this was never accurate.

Docs: Removed gpload reference to inserted in the case of a MERGE

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbconn.c

The SegmentDatabaseDescriptor is allocated under CdbComponentsContext.
The CdbComponentsContext will be freed when calling
cdbcomponent_destroyCdbComponents.
If my understanding is correct, cdbcomponent_destroyCdbComponents
will only be called under some special circumstances. For Example,
when a node is down, or a new segment joins the cluster, or 2PC
commit is abnormal. In normal scenarios, SegmentDatabaseDescriptor
will never be released, which will cause memory leaks

Fix memory leak in cdb components memory context

---

src/backend/gpopt/translate/CQueryMutators.cpp
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/backend/gporca/libgpopt/include/gpopt/operators/CScalarIsDistinctFrom.h
src/backend/gporca/libgpopt/include/gpopt/search/CGroup.h
src/backend/gporca/libgpopt/include/gpopt/search/CTreeMap.h
src/backend/gporca/libgpopt/src/base/CCTEInfo.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalGet.cpp
src/backend/gporca/libgpopt/src/operators/CScalarIsDistinctFrom.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExprUtils.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDType.h
src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
src/backend/gporca/libnaucrates/src/md/CMDPartConstraintGPDB.cpp
src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDType.cpp
src/backend/gporca/libnaucrates/src/statistics/CLeftOuterJoinStatsProcessor.cpp
src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
src/backend/gporca/server/include/unittest/dxl/statistics/CCardinalityTestUtils.h
src/backend/gporca/server/src/unittest/dxl/statistics/CCardinalityTestUtils.cpp
src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp

Stumbled upon these while working on my reference count refactoring, see commit messages for detail:
1. Remove covariant return types
2. Remove faux "forward" declarations
3. Replace one conditional `Release()` with `SafeRelease`
4. Remove redundant `const_cast`s

Assorted cleanups in ORCA

---

src/bin/gpfdist/gpfdist.c
src/bin/gpfdist/regress/Makefile
src/bin/gpfdist/regress/test_ipv4v6_port.sh

If /proc/sys/net/ipv6/bindv6only is set to 0:
In one case that if process A is already listening on ipv4 8080 port,
the gpfdist cannot start successfully. But if process A is listening on
ipv6 8080 port, the gpfdist can start successfully and will listen on
ipv4 8080 port. But in this situation if one client tries to connect to
gpfdist using ipv6 8080 port, it will connect to proccess A. Then the outcome
is not what we want.
If /proc/sys/net/ipv6/bindv6only is set to 1:
In one case that if either process A or process B is already listening on
either ipv4 8080 port or ipv6 8080 port, the gpfdist can still start
successfully. In this situation if one client tries to connect to
gpfdist using the port which process A or B is listening on, the outcome
is not what we want.
So in an environment …

Fix cases in gpfdist for dual stack solution.

---

config/python.m4
configure

It's already commented, let's remove it.
And remove the `python_enable_shared` test, because we already have these
two commits in:
d664a10f9623fd2198b257e513bce849d439a773
46ddbbb1177a7e6ce5a4fe0ef8fa8ac49f36d0bb

Remove `python_libdir` merge fixme

---

src/backend/executor/spi.c

This PR fixs a bug in GPDB5 that for SPI queries, sometime gpcc log the inner query text instead of the actual query text.
Because in GPDB5, the flag for inner query was set inside _SPI_prepare_plan instead of _SPI_execute_plan, but sometime the prepare step will be skipped and cause the flag unset.
The code only effects gpcc functionality, and the bug doesn't exist in GPDB6.

fix inner query emit problem of GPDB5

---

src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

This fixes https://github.com/greenplum-db/gpdb/issues/11655.
This mdid was potentially a default value of 0.0.0.0. Add a check
so we don't try to look up the invalid mdid and cause an exception
that leads to a fallback.
This happens when we come across a BCC (Binary Coercible Cast),
which has a dummy cast function of 0.0.0.0.

Add a missing IsValid() check before mdid lookup

---

src/bin/gpfdist/gpfdist.c
src/bin/gpfdist/regress/Makefile
src/bin/gpfdist/regress/test_ipv4v6_port.sh

If /proc/sys/net/ipv6/bindv6only is set to 0:
In one case that if process A is already listening on ipv4 8080 port,
the gpfdist cannot start successfully. But if process A is listening on
ipv6 8080 port, the gpfdist can start successfully and will listen on
ipv4 8080 port. But in this situation if one client tries to connect to
gpfdist using ipv6 8080 port, it will connect to proccess A. Then the outcome
is not what we want.
If /proc/sys/net/ipv6/bindv6only is set to 1:
In one case that if either process A or process B is already listening on
either ipv4 8080 port or ipv6 8080 port, the gpfdist can still start
successfully. In this situation if one client tries to connect to
gpfdist using the port which process A or B is listening on, the outcome
is not what we want.
So in an environment …

Fix cases in gpfdist for dual stack solution. (#11728)

---

gpMgmt/bin/gpcheck
gpMgmt/bin/gppylib/operations/test/unit/test_unit_gpcheck.py

Currently, gpcheck assumes that all XFS filesystems on a user cluster
will use the same mount options, but this is not necessarily the case.
This commit adds the ability for the user to specify different sets of
options in the gpcheck config file by adding the mount point to the end
of xfs_mount_options, separated by a dot.  For example:
[linux]
xfs_mount_options./data = rw
xfs_mount_options./nfs = rw,noatime
xfs_mount_options = defaults
The standard option is still respected, and will be used as the default
for any mount points that don't have their own options specified.  Not
specifying the default xfs_mount_options allows the user not to check
unspecified mount points if for whatever reason they want to that.
Co-authored-by: Divyesh Vanjare <vanjared@vmware.com>
Co-authored-by: Jamie …

gpcheck: allow per-mount xfs_mount_options

---

src/bin/gpfdist/gpfdist.c
src/bin/gpfdist/regress/Makefile
src/bin/gpfdist/regress/test_ipv4v6_port.sh

If /proc/sys/net/ipv6/bindv6only is set to 0:
In one case that if process A is already listening on ipv4 8080 port,
the gpfdist cannot start successfully. But if process A is listening on
ipv6 8080 port, the gpfdist can start successfully and will listen on
ipv4 8080 port. But in this situation if one client tries to connect to
gpfdist using ipv6 8080 port, it will connect to proccess A. Then the outcome
is not what we want.
If /proc/sys/net/ipv6/bindv6only is set to 1:
In one case that if either process A or process B is already listening on
either ipv4 8080 port or ipv6 8080 port, the gpfdist can still start
successfully. In this situation if one client tries to connect to
gpfdist using the port which process A or B is listening on, the outcome
is not what we want.
So in an environment …

Fix cases in gpfdist for dual stack solution. (#11728) (#11752)

---

src/backend/gporca/data/dxl/minidump/SubqInIndexPred.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformDynamicIndexGet2DynamicIndexScan.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementBitmapTableGet.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementCorrelatedApply.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementDynamicBitmapTableGet.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementFullOuterMergeJoin.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementIndexApply.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementLimit.h
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalInnerNLJoin.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalLimit.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformDynamicIndexGet2DynamicIndexScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementBitmapTableGet.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementDynamicBitmapTableGet.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementFullOuterMergeJoin.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementLimit.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementSplit.cpp
src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/server/CMakeLists.txt

This is a forward-port of Disallow subquery in predicate of implementation xforms. There
were some formatting merge conflicts, and I added a check for Index-Only scans. 
This generates an invalid plan for most cases. While we had this logic
in some xforms, we missed a few cases.
This manifested as a crash in some cases as we assumed subqueries had
been handled by time we get to optimization stage.
Additionally, add error handling to PexprScalarExactChild()
This function is only called in places where the exact child must exist,
and returns null otherwise.
However, there have been some cases where we assume the child must
exist, but due to another bug the child does not and we don't handle the
null. This is a defensive change; if we get into this situation we'll
throw an exception and fall …

Disallow subquery in predicate of implementation xforms

---

src/backend/gporca/data/dxl/minidump/SubqInIndexPred.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformDynamicIndexGet2DynamicIndexScan.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementBitmapTableGet.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementCorrelatedApply.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementDynamicBitmapTableGet.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementFullOuterMergeJoin.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementIndexApply.h
src/backend/gporca/libgpopt/include/gpopt/xforms/CXformImplementLimit.h
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalFilter.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalFullMergeJoin.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalInnerNLJoin.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalLimit.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformDynamicIndexGet2DynamicIndexScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementBitmapTableGet.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementDynamicBitmapTableGet.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementFullOuterMergeJoin.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementLimit.cpp
src/backend/gporca/libgpopt/src/xforms/CXformImplementSplit.cpp
src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexScan.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/server/CMakeLists.txt

This is a forward-port of Disallow subquery in predicate of implementation xforms. There
were some formatting merge conflicts, and I added a check for Index-Only scans.
This generates an invalid plan for most cases. While we had this logic
in some xforms, we missed a few cases.
This manifested as a crash in some cases as we assumed subqueries had
been handled by time we get to optimization stage.
Additionally, add error handling to PexprScalarExactChild()
This function is only called in places where the exact child must exist,
and returns null otherwise.
However, there have been some cases where we assume the child must
exist, but due to another bug the child does not and we don't handle the
null. This is a defensive change; if we get into this situation we'll
throw an exception and fall …

[6X] Disallow subquery in predicate of implementation xforms #11760

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Corresponding ORCA commit: Disallow subquery in predicate of implementation xforms (https://github.com/greenplum-db/gporca/pull/617)
This generates an invalid plan for most cases. While we had this logic
in some xforms, we missed a few cases.
This manifested as a crash in some cases as we assumed subqueries had
been handled by time we get to optimization stage.
Additionally, add error handling to PexprScalarExactChild()
This function is only called in places where the exact child must exist,
and returns null otherwise.
However, there have been some cases where we assume the child must
exist, but due to another bug the child does not and we don't handle the
null. This is a defensive change; if we get into this situation we'll
throw an exception and fall back to planner instead of crashing.

[5X] Bump ORCA version to 3.116 (Disallow subquery in predicate of implementation xforms)

---

gpdb-doc/dita/analytics/pl_r.xml

Modifying table creation on Example 3 from: https://gpdb.docs.pivotal.io/6-15/analytics/pl_r.html#topic9 since it was incorrect.

Docs: Changing plr example as it was incorrect

---

src/backend/access/transam/xlog.c
src/backend/utils/misc/guc_gp.c
src/include/access/transam.h
src/include/access/xlog.h
src/include/catalog/catversion.h
src/include/catalog/pg_proc.dat
src/include/utils/unsync_guc_name.h
src/test/recovery/t/101_restore_point_and_startup_pause.pl

Enable continuous controlled restore point recovery
This commit adds the capability to perform continuous (live) controlled
restore point based recovery for GP standbys, especially in an archive
recovery setting. This enables an application to gate recovery at
restore points created with `gp_create_restore_point()`. By gating
recovery at these restore point, eventual cluster consistency can be
achieved. A state of cluster consistency is reached when all of the
standbys in the cluster have replayed to the same restore point.
This commit introduces the `gp_pause_on_restore_point_replay` GUC, which
when set, pauses WAL recovery when a restore point WAL record is
replayed on a standby.
Example (very similar to the TAP test in the commit):
Cluster Setup:
3 primaries replicating to 3 standbys …

Enable continuous controlled restore point recovery

---

src/backend/utils/misc/guc_gp.c
src/backend/utils/resgroup/resgroup-ops-linux.c
src/include/utils/resgroup.h
src/include/utils/unsync_guc_name.h
src/test/isolation2/input/resgroup/resgroup_cpu_rate_limit.source
src/test/isolation2/output/resgroup/resgroup_cpu_rate_limit.source

CPU enforcement in resource group is based on Cgroup. Cgroup supports
two kinds of CPU enforcement: relative shares V.S. ceiling enforcement.
Resource group currently supports relative shares, which enable CPU
bursting to use 100% of CPU when the system is idle.
To avoid the CPU burst, we introduce the ceiling enforment in resource
group as well. User is able to choose the relative shares or
ceiling enforcement based on their requirement.

resource group: support CPU ceiling enforcement

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbconn.c

The SegmentDatabaseDescriptor is allocated under CdbComponentsContext.
The CdbComponentsContext will be freed when calling
cdbcomponent_destroyCdbComponents.
If my understanding is correct, cdbcomponent_destroyCdbComponents
will only be called under some special circumstances. For Example,
when a node is down, or a new segment joins the cluster, or 2PC
commit is abnormal. In normal scenarios, SegmentDatabaseDescriptor
will never be released, which will cause memory leaks

[6X Backport]Fix memory leak in cdb components memory context

---

src/backend/cdb/cdbpartition.c
src/backend/cdb/partitionselection.c
src/include/cdb/cdbpartition.h
src/test/regress/expected/bfv_partition.out
src/test/regress/sql/bfv_partition.sql

This fix regards only projection-based implementation of partition selector that works only under postgres planner. The plan has to have the following fragment:
```sql
Join
Join Cond: partitioned_table.id = othertable.id
-> Append
-> Result
One-Time Filter: PartSelected
-> Seq Scan partition1
-> Result
One-Time Filter: PartSelected
-> Seq Scan partition2
...
-> Some materialization point
-> PartitionSelector for partitioned_table
Filter: othertable.id
-> SeqScan othertable
Filter: <other conditions>
```
Executor under postgres planner performs projection of input tuple to further determine partitions appropriate for dynamic scan node. At the same time, such partition selection mechanics assumes that the type of search tuple after projection has to match to the schema of partitioning table …

Fix dynamic partition selection for postgres planner under join when type of partitioning key different from type of search values

---

src/backend/utils/misc/guc_gp.c
src/backend/utils/resgroup/resgroup-ops-linux.c
src/include/utils/resgroup.h
src/include/utils/unsync_guc_name.h
src/test/isolation2/input/resgroup/resgroup_cpu_rate_limit.source
src/test/isolation2/output/resgroup/resgroup_cpu_rate_limit.source

CPU enforcement in resource group is based on Cgroup. Cgroup supports
two kinds of CPU enforcement: relative shares V.S. ceiling enforcement.
Resource group currently supports relative shares, which enable CPU
bursting to use 100% of CPU when the system is idle.
To avoid the CPU burst, we introduce the ceiling enforment in resource
group as well. User is able to choose the relative shares or
ceiling enforcement based on their requirement.
Reviewed-by: Gang Xiong <gxiong@pivotal.io>
cherry-pick from commit: 2fc4ec7

[6X Backport] resource group: support CPU ceiling enforcement

---

gpMgmt/bin/gpsd
gpMgmt/bin/minirepro

* Fix minirepro bug with column types that are not built-in
In the generated SQL, `minirepro` used an unqualified name for the
type, which didn't work for types like `citext` that usually come
from a schema other than `pg_catalog` and other than the schema of
the table to be dumped.
The fix is to use a qualified name. For example, `citext` becomes
something like `"public"."citext"`.
* Fix minirepro bug with embedded double quotes and backslashes
When values in `pg_statistic.stavalues<n>` had embedded double quotes or
backslashes, minirepro generated a single set of escape characters
(backslash) but the correct syntax for an embedded double quote in an
array constant is `\\"`, because it goes through two layers of escape
processing. For embedded backslashes we need to use `\\\\`.

Minirepro fixes

---

gpMgmt/bin/gppylib/utils.py
gpMgmt/bin/gpsd
gpMgmt/bin/minirepro
src/test/regress/expected/gpsd.out
src/test/regress/sql/gpsd.sql

This is a port from 6X PR https://github.com/greenplum-db/gpdb/pull/11748, but it is not a simple cherry-pick. Two things changed in master:
- The code to format the insert list is now shared between gpsd and minirepro
- In Python3, arrays get returned by PygreSQL as lists, so the code is a bit different
**Fix gpsd and minirepro bug with column types that are not built-in**
In the generated SQL, gpsd and minirepro used an unqualified name for the type, which didn't work for types like `citext` that usually come from a schema other than `pg_catalog` and other than the schema of the table to be dumped.
The fix is to use a qualified name. For example, `citext` becomes something like `"public"."citext"`.
**Fix gpsd and minirepro bug with embedded double quotes and backslashes**
When values in …

gpsd and minirepro fixes from 6X

---

src/backend/access/appendonly/aomd.c

Unlinking the other segfiles doesn't make many differences, just remove
the FIXME.
Ref: https://github.com/greenplum-db/gpdb/pull/11131

Remove a merge fixme in ao_truncate_one_rel()

---

src/backend/commands/copy.c
src/backend/parser/gram.y
src/include/commands/copy.h
src/test/regress/input/gpcopy.source
src/test/regress/output/gpcopy.source

Add a case that proves it works.
Rename the internal variable name to skip_foreign_partitions, which is
more accurate.
Update SQL syntax, IGNORE EXTERNAL PARTITIONS and IGNORE FOREIGN
PARTITIONS are the same thing.

Remove the merge fixme about skip_ext_partition

---

src/backend/access/transam/xlogarchive.c
src/test/gpdb_pitr/test_gpdb_pitr.sh

This commit introduces the contentId (%c) parameter to
archive_cleanup_command. It will be substituted with the
contentId of the segment involved in the archival/recovery process.
Thus, an archive_cleanup_command = 'pg_archivecleanup /path/to/archive/seg%c %r'
might be substituted by (for a 3 segment cluster):
pg_archivecleanup /path/to/archive/seg-1/00000001000000A900000065
pg_archivecleanup /path/to/archive/seg0/00000001000000A900000065
pg_archivecleanup /path/to/archive/seg1/00000001000000A900000065
pg_archivecleanup /path/to/archive/seg2/00000001000000A900000065
The param will serve as a piece of identifying information for a WAL
stream from a given segment.

Add %c to `archive_cleanup_command`

---

src/backend/access/heap/tuptoaster.c

Original logic and improvements:
1. heap table
> it ignores the toast_tuple_target setting of reloptions, just using TOAST_TUPLE_TARGET
Improve it to use reloptions, so the user's setting value can take effect (e.g. `alter table T set (toast_tuple_target=5000)` ).
2. ao table
> set it to toast_tuple_target param and all callers pass TOAST_TUPLE_TARGET
Considering reloptions for AO table is not permitted, using TOAST_TUPLE_TARGET to make code clearly (with correct length: target_length - header_len, same as heap table ).

[GPDB_12_MERGE_FIXME] support toast_tuple_target

---

src/backend/commands/analyzeutils.c

We already changed that lock to NoLock while Postgres 12 merge.
commit 3afdf90f8cbce5b36c3bb6a757d3b9d08a2837b8
Author: Heikki Linnakangas <hlinnakangas@pivotal.io>
Date:   Thu Jul 23 17:18:21 2020 +0300
Silence test failure caused by SKIP_LOCKED blocking.
It is in fact OK, given the weasel words in the docs. Relax the locking
slightly in leaf_parts_analyzed() to make it happen less often, though.

Remove an outdated merge fixme in analyzeutils

---

gpMgmt/bin/minirepro

Issues:
Minirepro would hang because SQL is too big and syntax is wrong.
[gpadmin@smdw tmp]$ minirepro gpadmin -q query2.sql -f test.out
Connecting to database: host=smdw, port=8450, user=gpadmin, db=gpadmin ...
Extracting metadata from query file query2.sql ...
psql gpadmin --pset footer --no-psqlrc -Atq -h smdw -p 8450 -U gpadmin -f /tmp/20191101054341/toolkit.sql
The reason for that is because p.wait() has a deadlock issue with P.open; if the input SQL has a syntax error, it would error out to the pipe buffer and if the error is too large, it would make the mini-repro hang.
Python's explanation is as below:
https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait
I removed the p.wait() code and just use the p.communicate() for error handling

p.wait() would have deadlock with P.open

---

concourse/pipelines/templates/gpdb-tpl.yml
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Add behave test for gprecoverseg -p option to recover new host such as when customer wants to replace or update hardware. Note that gprecoverseg requires the hostname be the same as the node being replaced.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/recover_new_host_7X)

behave: test to recovering new host with -p

---

src/backend/replication/syncrep.c

Currently, the GPDB cluster will crash if pg_auto_failover is enable.
To enable synchronous replication, there're lots of work to do.
This patch only works around the assert failure.

Remove an assert to prepare synchronous replication

---

src/backend/access/transam/xlog.c
src/backend/storage/lmgr/proc.c
src/bin/pg_ctl/pg_ctl.c

~~To run pg_auto_failover for GPDB, we need some adapter code
for some reasons:~~
~~1. Enable hot-standby feature but only in utility mode.
Calling cdb_setup() in hot-standby should be OK.
2. Fix `cdbcomponent_getComponentInfo()` issue.
Currently, cdbcomponent_getComponentInfo() can't work well
in hot-standby, it gets the coordinator's entry on the standby.
3. Fix ready status for hot-standby.
4. Set proper `dbid` and `content` for monitor instance.
Monitor has dummy dbid and content. -1 is OK~~
Enable hot-standby in utility mode
1. When the standby turns on hot_standby, the ready status changed.
pg_ctl can't properly wait for the ready status for the standby.
2. To connect to the GPDB cluster with multi-host/port in connection info,
connecting to the hot-standby in dispatch(the default) …

Enable hot-standby in utility mode

---

gpMgmt/bin/gpconfig
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
gpMgmt/test/behave/mgmt_utils/gpconfig.feature
gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

When a host is down, and a user runs gpconfig to update any config: we should warn them and ask for confirmation to continue with the config update. Since they might get out of sync config values.
The warning and ask for confirmation were part of gpconfig until 6X, which got removed during py2/3 migration change.
This change adds that warning/ask for confirmation back in. 
Tracker story: https://www.pivotaltracker.com/story/show/177336745
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/7x_fix_gpconfig_down_host

gpconfig: add confirmation to continue for user when a host is down

---

gpMgmt/bin/gpinitstandby
gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
gpMgmt/bin/gppylib/operations/initstandby.py
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

When one or more segment hosts are unreachable, gpinitstandby can create the standby without difficulty, but related modifications of pg_hba.conf files on the segments cannot happen on that host, leaving the cluster in an inconsistent state.
Either preventing the user from initializing the standby or letting the user go ahead with it so long as they know to modify those files manually can make sense in this case, so this commit adds support for both along with a prompt to allow the user to choose which they would prefer.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpinitstandby_host_down)

gpinitstandby: Handle cases when a segment host is unreachable

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbgang_async.c
src/test/isolation2/expected/fts_errors.out
src/test/isolation2/expected/fts_errors_1.out
src/test/isolation2/expected/fts_session_reset.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/fts_session_reset.sql

If FTS changed cluster configuration in between two commands within a
transaction, the session is reset and the global transaction should be aborted.
fts_session_reset.sql is the test case for the this fix.
An new expected file fts_errors_1.out is added for fts_errors.sql. That is because,
with gp_interconnect_type "tcp" or "udpifc", the outputs of "END" statement in session#3 are different.
For interconnect type "tcp", when "END" statement is executed, function CommitTransaction
is called, then function mppExecutorFinishup throws QE error. The error is catched and the function
AbortTransaction is called to abort the transaction, a new gang is created to dispach command:
DTX_PROTOCOL_COMMAND_ABORT_NO_PREPARED, at this point, the transaction is not in progress,
so the check for FTS is down …

Fix the bug that the global transacation is not aborted when the session is reset.

---

contrib/pg_upgrade/greenplum/check_gp.c
contrib/pg_upgrade_support/pg_upgrade_support.c
src/backend/parser/parse_coerce.c
src/test/regress/expected/gp_create_view.out
src/test/regress/sql/gp_create_view.sql

```
CREATE VIEW unknown_v1 AS SELECT '2020-12-13'::unknown AS
field_unknown;
CREATE VIEW unknown_v2 AS SELECT field_unknown::date FROM unknown_v1;
```
The definition was this before this commit:
```
SELECT unknown_v1.field_unknown::cstring::date AS field_unknown
FROM unknown_v1;
```
Which would error out with `ERROR: cannot cast type cstring to date`.
This commit coerces unknown-type literals to type text instead of
cstring while converting stored expressions/querytrees back to source
text.
Upstream also chose text, Greenplum 7 too (PR #9655, #9686), but they
broke behaviors, we could not do that refactor on 6X_STABLE branch.
commit 1e7c4bb0049732ece651d993d03bb6772e5d281a
Date:   Wed Jan 25 09:17:18 2017 -0500
Change unknown-type literals to type text …

6X: Coerce unknown-type literals to type text instead of cstring

---

src/backend/executor/execMain.c
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

CTAS will first define relation in QD, and generate the OIDs,
and then dispatch with these OIDs to QEs.
QEs store these OIDs in a static variable and delete the one
used to create table.
If CTAS's query contains initplan, when we invoke
preprocess_initplan to dispatch initplans, if with
queryDesc->ddesc->oidAssignments be set, these OIDs are
also dispatched to QEs.
For details please see github issue https://github.com/greenplum-db/gpdb/issues/10760

Aviod dispatching OIDs for InitPlan.

---

contrib/pg_upgrade_support/pg_upgrade_support.c
src/backend/parser/parse_coerce.c
src/test/regress/expected/gp_create_view.out
src/test/regress/sql/gp_create_view.sql

```
CREATE VIEW unknown_v1 AS SELECT '2020-12-13'::unknown AS
field_unknown;
CREATE VIEW unknown_v2 AS SELECT field_unknown::date FROM unknown_v1;
```
It would show the definition as this before this commit:
```
SELECT unknown_v1.field_unknown::cstring::date AS field_unknown
FROM unknown_v1;
```
Which would error out with `ERROR: cannot cast type cstring to date`.
This commit coerces unknown-type literals to type text instead of
cstring while converting stored expressions/querytrees back to source
text.
Upstream also chose text, Greenplum 7 too (PR #9655, #9686), but they
broke behaviors, we could not do that refactor on 6X_STABLE branch.
commit 1e7c4bb0049732ece651d993d03bb6772e5d281a
Date:   Wed Jan 25 09:17:18 2017 -0500
Change unknown-type literals …

5X: Coerce unknown-type literals to type text instead of cstring

---

gpMgmt/bin/gppylib/utils.py
gpMgmt/bin/gpsd
src/test/regress/expected/gpsd.out
src/test/regress/sql/gpsd.sql

In python 2, unicode strings were represented as a unicode type.  However, in
python 3, this is handled by the default str type. When parsing a unicode
character, we used the escape sequence instead of the literal unicode character
in python 2. To maintain this behavior in python 3, we need additional
encoding/decoding.
The pgdb.escape_string() function expects a string without unicode characters.
Now, we now encode, perform escaping, then decode as utf8 to ensure we're
removing all non-ascii characters. This means the MCV values for that we
populate in pg_statistic using minirepro/gpsd will be the escape sequence for
unicode characters, which is also the 6X behavior.

Fix handling of non-ASCII characters in gpsd

---

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

Documenting PR: https://github.com/greenplum-db/gpdb/pull/11678 
Added reference under Assigning CPU Resources by Percentage and new GUC in the utility reference.
Preview link (needs VPN):
https://mireia-cpu-resources.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/workload_mgmt_resgroups.html
https://mireia-cpu-resources.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html#gp_resource_group_cpu_ceiling_enforcement

Docs: resource group cpu ceiling enforcement

---

src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
src/backend/gporca/libnaucrates/src/init.cpp

When ORCA runs out of memory while setting up its memory pool manager, in
CMemoryPoolManager::SetupGlobalMemoryPoolManager<>, it used to ignore
exceptions other than those of minor type ExmiOOM. When we use the
default GPDB memory allocators (optimizer_use_gpdb_allocators = true),
then an OOM condition will generate a different type of exception
(minor type of ExmiGPDBError). Ignoring that exception leads to a
crash with a segment violation.
The fix is to re-throw either of these OOM exceptions, so that they
are caught in the try/catch block in global method InitGPOPT(). Since
this is called before we set up a longjump buffer, that still causes a
FATAL error and an abort, but that's an improvement over the crash.
The reason for changing the behavior for exception of type ExmiOOM is
that …

Fix exception handling in the very initial stages of ORCA optimization

---

gpdb-doc/markdown/pxf/migrate_5to6.html.md.erb

update the "migrating pxf when upgrading from greenplum 5->6" docs that reside in the greenplum doc set.  in this PR:
- account for the different pxf distributions for greenplum 5.x and 6.x.
- provide instructions for migrating to pxf 5.x (installed via rpm or embedded in greenplum 6 distribution).
doc review site link behind vpn :^(
- https://docs-lisa-gp5-migrate-pxf.sc2-04-pcf1-apps.oc.vmware.com/7-0/pxf/migrate_5to6.html

docs - update gp 5->6 pxf migration docs

---

gpdb-doc/dita/ref_guide/modules/gp_sparse_vector.xml

add some info about upgrading gp_sparse_vector module from 1.0.0. to 1.0.1.  added new "about" and "upgrade" topics.
doc review site link:  https://docs-lisa-gpsv-upgrade.sc2-04-pcf1-apps.oc.vmware.com/6-16/ref_guide/modules/gp_sparse_vector.html#topic_reg

docs - add gp_sparse_vector 1.0.1 upgrade

---

getversion

If source is not a git repository and VERSION file exists, use version string from file.
This commit resolve the issue outlined here:
https://groups.google.com/a/greenplum.org/g/gpdb-users/c/74CMXJkZZK4
Currently, compiling Greenplum from the [source tarball provided on the Github release page](https://github.com/greenplum-db/gpdb/releases/tag/6.15.0) will result in the version being reported as **postgres (Greenplum Database) 6.0.0-beta.1 build dev**
Future Github releases will bundle the VERSION file with the source tarball, allowing the build system to inject the proper version when compiling.

getversion: check for VERSION file

---

src/backend/optimizer/path/pathkeys.c
src/backend/optimizer/plan/createplan.c
src/backend/optimizer/plan/plangroupext.c
src/include/optimizer/paths.h
src/test/regress/expected/aggregate_with_groupingsets.out
src/test/regress/sql/aggregate_with_groupingsets.sql

For query like 'select 1, a from t group by grouping sets(1,2)', we assume that
there is a one-to-one mapping between the pathkeys in root->group_pathkeys and
the group columns, so we add a workaround to construnct a one-to-one pathkey
list even it contains a constant pathkey. In this case, function
'prepare_sort_from_pathkeys' will consider the pathkey list has no sort column.
To fix this, we remove the constant pathkey and then pass it to
'prepare_sort_from_pathkeys'. We should resolve the GPDB_91_MERGE_FIXME in
'plan_grouping_extension' to come up with a thorough fix.
This issue only exist on 6X.

[6X only] Fix incorrect group pathkey

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gporca/data/dxl/minidump/Insert-AO-Partitioned-SortDisabled.mdp
src/backend/gporca/data/dxl/minidump/Insert-AO-Partitioned.mdp
src/backend/gporca/data/dxl/minidump/Insert-Parquet-Partitioned-SortDisabled.mdp
src/backend/gporca/data/dxl/minidump/Insert-Parquet-Partitioned.mdp
src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution-2.mdp
src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution.mdp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/test/regress/expected/bfv_dd_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/incremental_analyze_optimizer.out
src/test/regress/expected/orca_static_pruning.out
src/test/regress/expected/orca_static_pruning_optimizer.out
src/test/regress/expected/qp_orca_fallback_optimizer.out
src/test/regress/expected/qp_targeted_dispatch_optimizer.out
src/test/regress/sql/orca_static_pruning.sql

INSERT INTO a partitioned table now goes through the same code path as a regular relation during transforms. Hence it no longer needs the partition selector node.

Re-enable INSERT for partitioned tables in GPORCA

---

src/backend/storage/ipc/procarray.c
src/backend/utils/gdd/gddbackend.c
src/backend/utils/gdd/gdddetector.c
src/backend/utils/gdd/gdddetector.h
src/backend/utils/gdd/gdddetectorpriv.h
src/backend/utils/gdd/gddfuncs.c
src/backend/utils/gdd/test/gdddetector_test.c
src/include/catalog/catversion.h
src/include/catalog/pg_proc.dat

Note that commit 24e274093461727b305fda4bae8ea41e2de6507b introduce
64 bits gxid for distribtued transaction. But GDD didn't modified
accordingly, and there is a slim chance that vertex ID in GDD's wait-for
graph can overflow and result in deadlock can't be resolved properly.

Use 64 bits vertex ID for GDD

---

src/backend/optimizer/plan/plangroupext.c
src/test/regress/expected/olap_group.out
src/test/regress/sql/olap_group.sql

In commit 5eaaa5800e9f492683c3ce313e54d3db5afbce79, it didn't
consider the grouping columns that need to be replaced with NULL
may appear in expression with RelabelType wrap. We should consider
this case too. For example:
CREATE TABLE w_time_d (
row_wid bigint,
per_name_qtr character varying(150)
) DISTRIBUTED BY (row_wid);
CREATE TABLE iqm_unified_assets_contract_qtr_base_asset_test (
apid character varying,
qtrs character varying[],
start_qtr character varying(150),
end_qtr character varying(150),
nxt_qtr_exp_join character varying,
quota_block character varying,
cust_cntrct_nbr numeric(18,0),
svc_rtl_rev numeric
) DISTRIBUTED BY (cust_cntrct_nbr);
explain SELECT
(per_name_qtr=nxt_qtr_exp_join),
COUNT(DISTINCT cust_cntrct_nbr) AS warranties_count
FROM w_time_d a
INNER JOIN …

[5X Only]Replace unused target entry with NULL in RelabelType

---

gpdb-doc/dita/admin_guide/expand/expand-initialize.xml

Reference to tablespace mapping file being generated by gpexpand utility if the cluster is configured with tablespaces.

Docs: added reference to tablespace mapping file for gpexpand utility

---

concourse/scripts/compile_gpdb.bash

Fix postgre --gp-version
Previous commit:
https://github.com/greenplum-db/gpdb/commit/444bcb99caf7cc3b337a02cfd7e5324739a6fbe8#diff-75a3e145e34ecdcbddb795d0c26cadfdd0c29de469d4519b84ca249bc5acefccR49
accidentally changed postgres --gp-version output, which add an extra
space in `commit: XXXX`, which should be `commit:XXXX`

Fix  Release_Candidate job

---

concourse/scripts/compile_gpdb.bash

Fix postgres --gp-version
Previous commit: ee4961fc349aad16ae64e4fa10154d7996ce0401 accidentally
changed postgres --gp-version output, which add an extra
space in `commit: XXXX`, which should be `commit:XXXX`
Co-authored-by: Ning Wu <ningw@vmware.com>
Co-authored-by: Shaoqi Bai <bshaoqi@vmware.com>

Fix Release_Candidate job

---

src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
src/backend/gporca/libnaucrates/src/init.cpp

This is a backport of #11806.
* Fix exception handling in the very initial stages of ORCA optimization
When ORCA runs out of memory while setting up its memory pool manager, in
CMemoryPoolManager::SetupGlobalMemoryPoolManager<>, it used to ignore
exceptions other than those of minor type ExmiOOM. When we use the
default GPDB memory allocators (optimizer_use_gpdb_allocators = true),
then an OOM condition will generate a different type of exception
(minor type of ExmiGPDBError). Ignoring that exception leads to a
crash with a segment violation.
The fix is to re-throw either of these OOM exceptions, so that they
are caught in the try/catch block in global method InitGPOPT(). Since
this is called before we set up a longjump buffer, that still causes a
FATAL error and an abort, but that's an …

Fix exception handling in initial stages of ORCA optimization (#11806)

---

src/backend/access/appendonly/appendonlyam.c
src/include/cdb/cdbappendonlyam.h

Currently, whether to compress data in AO table is stored in
`AppendOnlyStorageWrite`'s `storageAttributes`.
`aoInsertDesc->shouldCompress` is never set to ture, so just remove
the related logic.

Remove compress dead code for AO table

---

src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalFullMergeJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalHashJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalInnerHashJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftAntiSemiHashJoinNotIn.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterHashJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftSemiHashJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalRightOuterHashJoin.h
src/backend/gporca/libgpopt/src/base/CDistributionSpecStrictSingleton.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp

Stumbled upon these while working on my reference count refactoring, see eacg commit for details
1. Fix an incorrect cast (In case you wonder why it didn't trigger a warning: It was a C-style cast, so "no questions asked")
2. Remove an incorrectly placed call to `Release()`
3. This is the most interesting one: remove a default argument to various physical hash join constructors, it's never used.

Upstreaming fixes from refcount 3

---

contrib/citext/citext--1.5--1.6.sql
contrib/citext/expected/citext.out
contrib/citext/expected/citext_1.out
contrib/citext/sql/citext.sql
contrib/cube/cube--1.3--1.4.sql
contrib/cube/expected/cube.out
contrib/cube/sql/cube.sql
contrib/ltree/expected/ltree.out
contrib/ltree/ltree--1.0--1.1.sql
contrib/ltree/ltree--1.1.sql
contrib/ltree/sql/ltree.sql
contrib/seg/expected/seg.out
contrib/seg/seg--1.2--1.3.sql
contrib/seg/sql/seg.sql
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

For some extensions that have types, there are associated btree operator
classes that allow GPDB to use index scans. However, since bitmap
indexes are a GPDB-only feature, the bitmap operator class was not
included. We found this issue when neither orca nor planner would
generate an index scan on a bitmap index for a citext type, but would if
there was a btree index.
Bitmap and btree operator classes define the same strategies. Therefore,
given a btree opclass, we can safely create a bitmap opclass.
We don't currently install/ship the cube, ltree, and seg extensions, but
I added the corresponding opclasses so we don't hit this issue if we
choose to ship them in the future.
These opclasses are added to the latest extension version file. Since
these versions don't conflict with existing …

Create corresponding bitmap operator class for extensions

---

gpMgmt/bin/gpexpand

When running gpexpand utility to expand the segments, If the process receives a signal.SIGTERM or signal.SIGHUP, the sig_handler function will have an error，as shown below：
TypeError: sig_handler() takes exactly 1 argument (2 given)
As a result, we can  not clean up correctly for gpexpand.
This change can fix the above error to clean up correctly. 
6X and 5X also have this issue.

Fix TypeError for sig_handler function in gpexpand

---

concourse/scripts/compile_gpdb.bash

[6X]: vendor libquicklz.so during Photon compile

---

concourse/scripts/compile_gpdb.bash

[7X]: vendor libquicklz.so during Photon compile

---

src/backend/executor/execUtils.c
src/backend/executor/nodeHashjoin.c
src/backend/executor/nodeMergejoin.c
src/backend/executor/nodeNestloop.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/plan/createplan.c
src/include/executor/executor.h
src/include/nodes/execnodes.h
src/include/nodes/plannodes.h
src/test/regress/expected/deadlock2.out
src/test/regress/expected/deadlock2_optimizer.out

In commit fa762b, we introduce prefetch joinqual logic to avoid motion
hazard. For non join qual in a join node, if it contains a motion and
the outer relation also contains a motion, then motion deadlock could
happen as well. Prefetch NonJoinQual if required.
Motion Hazard details please refer to commit fa762b

Prefetch NonJoinQual to avoid motion hazard.

---

src/backend/utils/mmgr/portalmem.c
src/test/regress/expected/resource_queue.out
src/test/regress/sql/resource_queue.sql

When creating a portal, we should assign the portal->queueId with
GetResQueueId() not only for master, but also for segments. Or,
resqueue's CPU priority will have no effect.

Fix resqueue's CPU priority invalid in segments

---

src/backend/catalog/gp_toolkit.sql
src/test/regress/expected/gp_toolkit.out
src/test/regress/sql/gp_toolkit.sql

The gp_toolkit.gp_bloat_diag view uses average width of a row as
computed from a sample of a relation's blocks (by analyze) and
multiplies it with reltuples to compute expected size of the relation.
The width itself is approximate and using it as a multiplying factor
further increases the error.  Consequently, we have seen confusion in
production deployments where the gp_bloat_diag reported "moderate
bloat" for a relation right after it was vacuumed using "vacuum full".
To fix this confusion, a factor is added to the approximate width
computed from pg_statistic.  The added amount is proportional to the
number of variable length attributes in the relation.  The thresholds
used to report moderate and severe bloat are changed too, so that the
bloat compulation now errors on the side of "not …

Make gp_toolkit bloat computation more lenient

---

src/backend/storage/ipc/procarray.c
src/backend/utils/time/sharedsnapshot.c
src/test/regress/expected/gp_combocid.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_combocid.sql

After a call to repalloc the address of the newly allocated memory must
be saved back in the pointer, otherwise the pointer is left to point to
the old (now free’d) memory.
In GetSnapshotData(), GPDB repalloc()'s comboCids and then memcpy()'s
into it contents larger than than its previously allocated size.
This overflows to other allocations in the block and corrupts the chunk
header of other allocations.
In the attached test, this corrupt the chunk header of ActiveSnapshot
and subsequently crashes the backend later during PopSnapshot().
The affected allocation happens to be that of the ActiveSnapshot, but
that is coincidental. This could affect any allocation in the same block
of the TopTransactionContext.
To reproduce this, we first need to execute the query within a
transaction which …

Fix use after free in GetSnapshotData()

---

gpMgmt/bin/gpconfig
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
gpMgmt/test/behave/mgmt_utils/gpconfig.feature
gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

When a host is down, and a user runs gpconfig to update any config: we warn them and ask for confirmation to continue with the config update. If the user chooses to abort the update, we currently do not exit out properly due to (non daemon) threads staying open when exiting.
This change fixes the abort/exit to close threads
We also remove use of GpHostCache as part of this change and instead use functions from GpArray
Tracker story: https://www.pivotaltracker.com/story/show/177336745
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6x_fix_gpconfig_down_host

gpconfig: aborting a config update with down host should exit properly

---

src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
src/test/regress/expected/join_optimizer.out

The CombineBuckets() function combines buckets to get a target
desired_num_buckets. However, this logic isn't working correctly.  While
it limits the number of buckets for non-singleton buckets, singleton
buckets are not merged, and thus we can get in a case where the number
of result buckets is larger than the desired number of buckets.
If singleton buckets are merged, we can lose accuracy within the
histogram, so it's not clear what the ideal behavior here should be. For
now, we'll keep the same logic and relax the assert.
Fixes the gpdb_master_without_asserts pipeline.

Relax Orca assert when merging histogram buckets

---

gpMgmt/bin/gpcheck

Removing the warning message as some customers prefer less verbose output when a default xfs_mount_options configuration option is excluded from the config file.

gpcheck: remove xfs_mount_options warning message

---

src/include/utils/sync_guc_name.h
src/include/utils/unsync_guc_name.h

The guc bytea_output sets the output format for the binary type bytea to
be either escape (octal notation) or hex. This guc should be synced
across all segments so that the output from different segments is using
a consistent format.
See https://github.com/greenplum-db/gpdb/issues/11870 for more details.
Co-authored-by: Ashuka Xue <axue@vmware.com>
Co-authored-by: Bradford Boyle <bradfordb@vmware.com>

Move bytea_output guc to be a sync'd guc

---

gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Fix broken behave tests that check files on master data directory. 
Behave sub-step wasn't named correctly, and hence wasn't found.
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/fix_behave_tests_6x

fix behave tests 'escaped' keyword

---

src/backend/executor/execUtils.c
src/backend/executor/nodeHashjoin.c
src/backend/executor/nodeMergejoin.c
src/backend/executor/nodeNestloop.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/optimizer/plan/createplan.c
src/include/executor/executor.h
src/include/nodes/execnodes.h
src/include/nodes/plannodes.h
src/test/regress/expected/deadlock2.out
src/test/regress/expected/deadlock2_optimizer.out
src/test/regress/init_file

In commit fa762b, we introduce prefetch joinqual logic to avoid motion
hazard. For non join qual in a join node, if it contains a motion and
the outer relation also contains a motion, then motion deadlock could
happen as well. Prefetch NonJoinQual if required.
Motion Hazard details please refer to commit fa762b

[BackPort 6X] Prefetch NonJoinQual to avoid motion hazard.

---

src/include/utils/sync_guc_name.h
src/include/utils/unsync_guc_name.h

The guc bytea_output sets the output format for the binary type bytea to
be either escape (octal notation) or hex. This guc should be synced
across all segments so that the output from different segments is using
a consistent format.
See https://github.com/greenplum-db/gpdb/issues/11870 for more details.
This commit is a backport of master commit 227b05f78a401b4a46977bb20c829ab4fdede7c2
Co-authored-by: Ashuka Xue <axue@vmware.com>
Co-authored-by: Bradford Boyle <bradfordb@vmware.com>

[6X backport] Move bytea_output guc to be a sync'd guc

---

gpMgmt/bin/gpmovemirrors

Need to print lineno instead of line

gpmovemirrors: fix typo lineno instead of line

---

gpMgmt/bin/gpmovemirrors

The expectation appeared to be to print lineno instead of line.

Fix Typo - lineno must be printed instead of line

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/test/regress/expected/alter_table_gp.out
src/test/regress/sql/alter_table_gp.sql

ORCA falls with segfault when trying to select from view:
- With JOIN clause
- With table which column was dropped after view creation
`RangeTblEntry::joinaliasvars` alias list can contain pointers to NULL node if correspond column was dropped ([rewriteHandler.c#L296](https://github.com/greenplum-db/gpdb/blob/23814da5b0eb50a4c3957f1d95ab54a9f72e25b5/src/backend/rewrite/rewriteHandler.c#L296)).
Postgres planner itself can handle such values ([var.c#L878](https://github.com/greenplum-db/gpdb/blob/23814da5b0eb50a4c3957f1d95ab54a9f72e25b5/src/backend/optimizer/util/var.c#L878)) and the logic of NULL pointers is legit.
ORCA doesn't respect NULL pointers when loop over them ([CTranslatorQueryToDXL.cpp#L3854](https://github.com/greenplum-db/gpdb/blob/23814da5b0eb50a4c3957f1d95ab54a9f72e25b5/src/b …

Segfault when trying to select from view with JOIN and table with dropped column

---

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Commit b48098eeddc added support for partitioned tables with mixed
storage types by checking the child partitions. However, if a
partitioned table has no child partitions, it did not get a valid
storage type and crashed. We now assign it a heap partition type (though
it really doesn't matter as it will error out during execution since
there isn't a valid partition).

Fix handling of partitioned tables with no partitions in Orca

---

gpdb-doc/dita/install_guide/install_guide.ditamap
gpdb-doc/markdown/pxf/pxf_upgrade_migration.html.md.erb

Added a "PXF Upgrade and Migration" landing page for Greenplum upgrade documentation. 
When upgrading to Greenplum 6 (https://mireia-pxf-upgrade-landing.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/upgrade_intro.html), all PXF options are grouped into one into the landing page: 
https://mireia-pxf-upgrade-landing.sc2-04-pcf1-apps.oc.vmware.com/7-0/pxf/pxf_upgrade_migration.html
This provides a breakdown of different scenarios and directs user to the specific steps to follow in every case.

docs: pxf upgrade landing page

---

gpdb-doc/dita/admin_guide/managing/startstop.xml

I have added a description of the behavior of gpstop: waits for 2 minutes then prompts with 3 different options.
Since immediate mode is dangerous and not recommended to use, I have also added a warning section about it.
Preview: https://mireia-capgemini-gpstop.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/managing/startstop.html

Docs: modified gpstop options description

---

gpdb-doc/dita/admin_guide/textsearch/features.xml

Insert statement from example was failing because one of the columns input was missing.

Docs: Added missing entry '1' to insert statement

---

gpdb-doc/dita/admin_guide/monitoring/monitoring.dita

On 4.x we recommended a database restart to rebalance segments running out of they preferred roles, but with recent versions it is advisable to run gprecoverseg -r instead.

Docs: changed restart for gprecoverseg -r to rebalance

---

gpMgmt/bin/gpcheckcat
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

gpcheckcat check partitions with different distributing policies from
the parent table. Readable external partitions are fine, this commit
skips them.

gpcheckcat permits readable external partitions

---

src/backend/catalog/oid_dispatch.c
src/backend/commands/user.c
src/backend/utils/adt/pg_upgrade_support.c
src/bin/pg_upgrade/README.gpdb

Greenplum requires a pre-assigned auth id to keep QD and QEs synchronized in
binary upgrade mode, error out if there is no pre-assigned id as the merge
fixme says.

Remove a merge fixme about GetNewOidForAuthId()

---

.travis.yml

Canonical yanked a (higher) version of libc6 from Ubuntu Focal recently after the Travis CI image was built, leaving us with a fairly mysterious package installation conflict.
Until Travis publishes a new image, work around this by downgrading libc to the published and available version to unblock CI.

Workaround yanked libc version in Travis

---

src/backend/utils/error/elog.c

Long queries are truncated when logged. This wasn't done correctly because it doesn't consider the encoding. This results in some utf characters being truncated in the middle.

Fix query string truncation while writing it to server logs

---

src/backend/access/appendonly/appendonlyam.c
src/test/isolation2/input/uao/bitmapindex_rescan.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/bitmapindex_rescan.source

ERROR:  append-only table version -1 is invalid
Requires plan containing a Bitmap Index NL join with bir (containing more than
1 tuple) on the outer side and yolo (with 2 aoseg files, the latter of which is
empty) on the inner side:
```
->  Nested Loop Left Join
Join Filter: true
->  Seq Scan on bir
->  Bitmap Heap Scan on yolo
Recheck Cond: (a = bir.a)
->  Bitmap Index Scan on yolo_idx
Index Cond: (a = bir.a)
```

Don't reuse AO block if the corresponding segment file was closed

---

src/backend/commands/schemacmds.c
src/test/regress/expected/privileges.out
src/test/regress/sql/privileges.sql

Assume user1 has the privilege to database db1 and user2 has not, when
user1 try to create a schema in db1 and authorize it to user2, a
permission denied error is reported in QE. The RCA is QD set current
user to user2 before dispatching the query to QEs, so QE will also
set current user to user2, however, user2 has no provilege to create
schema in database db1.
To fix this, we delay setting the current user to user2 until the query
is dispatched to QEs.

[5X Backport] Fix a permission denied issue

---

src/backend/executor/execMain.c
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

CTAS will first define relation in QD, and generate the OIDs,
and then dispatch with these OIDs to QEs.
QEs store these OIDs in a static variable and delete the one
used to create table.
If CTAS's query contains initplan, when we invoke
preprocess_initplan to dispatch initplans, if with
queryDesc->ddesc->oidAssignments be set, these OIDs are
also dispatched to QEs.
This commit avoid dispatching OIDs for InitPlan to fixes
github issue https://github.com/greenplum-db/gpdb/issues/10760
--------
Backport https://github.com/greenplum-db/gpdb/commit/6c424a9fb20febfb69d1a6891157975b84efa8ef
to 6X.

(6x backport from master) Avoid dispatching OIDs for InitPlan.

---

getversion

Allow `./getversion` and `./getversion --short` commands to function as expected when source does not contain a `.git` directory and a non-empty VERSION file exists in the source top directory.
```
./getversion
TAG build commit:SHA
./getversion --short
TAG
```

7X: getversion: If not a git repository and VERSION file exists, derive version from file.

---

getversion

Allow `./getversion` and `./getversion --short` commands to function as expected when source directory is not a git repo and a VERSION file exists.
```
./getversion
TAG build commit:SHA
./getversion --short
TAG
```

6X: Improve getversion logic when .git directory does not exist.

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-features.xml

Existing syntax on how to create a partitioned table was incorrect, modified example with a correct one.

Docs: incorrect partitioned table example

---

gpdb-doc/dita/analytics/postGIS.xml

"If exists" clause was specified in the incorrect order. This is not fixed.

Docs: incorrect syntax for drop extension

---

src/backend/cdb/cdbcopy.c
src/test/regress/expected/gp_copy_dtx.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_copy_dtx.sql

When executing COPY FROM statement, QD will wait in cdbCopyEndInternal
to get the execution results from QE, but before this fix, flag
TopXactexecutorDidWriteXLog is not set as processResults does, which
results in the incorrect use of dtx protocol command. So we need to
check if segments have written XLOG, and set the flag properly.
COPY FROM will have 2PC after this commit.
Signed-off-by: Adam Lee <adlee@vmware.com>
(cherry picked from commit 2a224dbc1e718e9fd45d75bf091bdfa1c828fe14)

6X: Fix treat COPY FROM dtx as a read-only dtx

---

src/backend/catalog/oid_dispatch.c
src/backend/commands/matview.c
src/include/catalog/oid_dispatch.h
src/test/regress/expected/matview.out
src/test/regress/expected/matview_optimizer.out
src/test/regress/sql/matview.sql

Refresh materialized view will first create a temp table on QD, this will
save the table's oid in static variable of QD, dispatch will use it. Then
QD try to execute the query, first generate a plan, it might pre-evaluted
some function during planning, if the function invokes SQL, it will lead
to dispatch and consume the oids. So later dispatch ref mat view will
dispatch no OIDs.
This comit fixes this by first saving the OIDs before planning the matview's
body query and then restoring it when dispatching the ref query.
Fix Github Issue: https://github.com/greenplum-db/gpdb/issues/11956

Avoid dispatch OIDs during planning when refresh matview.

---

src/backend/utils/adt/ruleutils.c
src/backend/utils/misc/guc.c
src/backend/utils/misc/postgresql.conf.sample
src/include/utils/builtins.h
src/test/regress/expected/partition.out
src/test/regress/sql/partition.sql

This backports ONLY the quote_all_identifiers GUC from upstream commit:
ce68df4 (leaves the --quote-all-identifiers options alone).
This is done in response to customer issues with upgrades involving
reserved/unreserved keywords in partition names. This commit, in
combination with future version PRs such as for 6X: PR #11939, enables
future major versions of pg_dump(all) binaries to dump these names in a
safe manner when executed against a 5X server (which is typical during
an upgrade).  Please refer to #11939 for more detailed commentary.
A test is also added to partition.sql to exercise the GUC with
partitioned tables carrying keywords.
Original commit message follows from Robert Haas:---------------------
Add options to force quoting of all identifiers.
I've added a …

5X: Backport quote_all_identifiers GUC

---

src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dumpall.c

`pg_dump/pg_dumpall --quote-all-identifiers` and the `quote_all_identifiers`
GUC ensures that all identifiers generated by the dump are quoted. This
facility was introduced in upsteam commit: ce68df468a in response to bug
report 5488, which dealt with a 8.3 table using "window" as a column
name, which lead to a failure to upgrade to 8.4 (window became a
reserved keyword in 8.4). Thus quoting all identifiers in the dump
output prevents problems due to newly introduced reserved keywords when
restoring to a higher version.
Also, since upstream commit 1c36700e9e3, `pg_upgrade` passes
`--quote-all-identifiers` to `pg_dumpall`.
However, `quote_all_identifiers`  was not backported below 9.1 (the
community considered it as unjustified cost to do so. See: …

6X: pg_dump(all): Allow quote_all_identifiers for 8.3

---

src/test/regress/expected/partition_optimizer.out

I missed updating the _optimizer.out file in 3aab3d7def
Pipeline (passed all icw_gporca* tests): https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/5X_quote_all_id_followup

5X: Update partition_optimizer.out for quote_all_identifiers test

---

src/backend/gporca/data/dxl/minidump/ExceptAllCompatibleDataType.mdp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

During DXL->Expr translation of UNION & UNION ALL operators, ORCA adds
scalar casts for any input columns whose types don't match the output
types of the SetOp.
ORCA did not do this for EXCEPT/EXCEPT ALL or INTERSECT/INTERSECT ALL,
which was okay in most cases because an appropriate cast gets added when
implementing the SetOp using AntiJoin or SemiJoin. However, when there are
eligible scalar predicates that are pushed under the SetOp, ORCA also
doesn't add an appropriate scalar cast, which will produce wrong results
depending on the predicate (see tests in this PR for examples).
This commit avoids all this by extending the logic in DXL->Expr
translation to the other SetOps.

Correctly cast types for all SetOps during DXL->Expr translation

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py

This is tech-debt from DCA specific code. Also, it was determing interface incorrectly. Specifically,
`segAddress[segAddress.rfind('-'):]` returns the last character from the
hostname and appending that to the address.
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-gprecoverseg_remove_isStandardArray)
See #11968 as a related PR.

gprecoverseg: remove isStandardArray

---

src/include/access/xlog_internal.h

gpdb uses 64MB segment size while upstream uses 16MB by default, thus
DEFAULT_MAX_WAL_SEGS should be modified accordingly on gpdb.  This variable
affects guc max_wal_size_mb and max_wal_size_mb affects the variable
CheckPointSegments.  CheckPointSegments is a guc on gpdb6 with default value 8,
but on master & upstream it is calculated using max_wal_size_mb and guc
checkpoint_completion_target. With previous DEFAULT_MAX_WAL_SEGS value of 64,
CheckPointSegments is 42. This is not acceptable since this variable is used to
control checkpoint frequency.
With DEFAULT_MAX_WAL_SEGS as 16, CheckPointSegments becomes to 10 and this
should be ok for gpdb. In latest upstream code, checkpoint_completion_target is
changed from 0.5 to 0.9. CheckPointSegments would become to 8 when we merge to
that …

Change DEFAULT_MAX_WAL_SEGS from 64 to 16

---

src/backend/access/transam/test/xlog_test.c
src/backend/access/transam/xlog.c
src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
src/test/isolation2/sql_isolation_testcase.py

This is the master version of https://github.com/greenplum-db/gpdb/pull/11891
Previously we thought the fix for master and that for gp6 are different so created a gp6 version at first. Now we found the master version is similar, so port the gp6 version. The code change is a bit different but the theory is the same.

Fix incremental recovery failure because the checkpoint redo wal file before divergence LSN is gone.

---

src/backend/utils/misc/fstream/gfile.c

Fix compiling error for macro ZSTD_CLEVEL_DEFAULT for 1.3.3 zstd or before.

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/test/regress/expected/alter_table_gp.out
src/test/regress/sql/alter_table_gp.sql

- With JOIN clause
- With table which column was dropped after view creation
RangeTblEntry::joinaliasvars alias list can contain pointers to NULL
node if corresponding column was dropped
ORCA doesn't respect NULL pointers when loop over them
which cause segfault

ORCA falls with segfault when trying to select from view:

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py

See 7X commit f61d35cd for context.
[pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-6X_gprecoverseg_remove_gphostcache)
see #11971 as well.
NOTE: This PR Is rebased off of the branch in https://github.com/greenplum-db/gpdb/pull/11992; that will be merged in first and then this one will be.  So, only look at the last two commits on this one.

6x gprecoverseg remove gphostcache

---

src/backend/catalog/oid_dispatch.c
src/backend/commands/matview.c
src/include/catalog/oid_dispatch.h
src/test/regress/expected/matview.out
src/test/regress/expected/matview_optimizer.out
src/test/regress/sql/matview.sql

Refresh materialized view will first create a temp table on QD, this will
save the table's oid in static variable of QD, dispatch will use it. Then
QD try to execute the query, first generate a plan, it might pre-evaluted
some function during planning, if the function invokes SQL, it will lead
to dispatch and consume the oids. So later dispatch ref mat view will
dispatch no OIDs.
This comit fixes this by first saving the OIDs before planning the matview's
body query and then restoring it when dispatching the ref query.
Fix Github Issue: https://github.com/greenplum-db/gpdb/issues/11956

(6x backport)Avoid dispatch OIDs during planning when refresh matview.

---

src/backend/utils/workfile_manager/workfile_mgr.c

The workfile_set(or work_set referenced in the code) is used to
track the usage of the temporary files. For example, in hash join,
if the hash table is too large to put them all in the memory,
the hash table is split and saved in temporary files. When the
transaction is finished(no matter commit or abort), the workfile_set
referenced by the executor node will be freed(reference count).
There are also other workfile_set with different lifecycle(e.g. session).
The backend records the usage of the workfile_set in its local memory,
and it will free all the `workfile_set`s in the callback(AtProcExit_WorkFile)
when the backend is going to exit.
The problem is that the function `AtProcExit_WorkFile` is called before
the cleanup of the current transaction. So, the executor node may free
the …

[6X backport] Fix the double-free issue of work_set

---

src/backend/executor/nodeSort.c
src/backend/utils/misc/faultinjector.c
src/include/utils/faultinjector.h
src/test/regress/expected/query_finish_pending.out
src/test/regress/expected/query_finish_pending_optimizer.out
src/test/regress/sql/query_finish_pending.sql

To trigger this bug, we need plan with a Sort node in a subplan that is
executed at least twice (viz. if there are multiple tuples on the outer
side).  Moreover, the QD must do a PQrequestFinish(), which sets
QueryFinishPending on all the QE processes, after the ExecRescanSort()
is executed, but before the next ExecSort(). This leaves the sort state
in an inconsistent state where node->tuplesortstate->sortstore != NULL,
but has already been freed. So another attempt to free it (in
ExecEndSort for example) will cause a crash.
This commit fixes this logic by setting the sortstore to NULL during
ExecRescanSort.
Co-authored-by: Alexandra Wang <lewang@pivotal.io>

Fix double free of TupleSort memory context (5X)

---

src/backend/executor/nodeSort.c

This is a forward port of commit 0043ae4f from 5X, with the test
removed, since it did not reproduce in 6X. In fact, it is unlikely for
this bug to occur in 6X because QueryFinishPending does not get checked
in between ExecReScanSort() and ExecSort() in many cases. This behavior
is different from 5X. However, a crash can still theoretically occur in
6X, and its better to patch this, even without a repro/test since the
fix is fairly simple.
Notes from 5X commit:
To trigger this bug, we need plan with a Sort node in a subplan that is
executed at least twice (viz. if there are multiple tuples on the outer
side).  Moreover, the QD must do a PQrequestFinish(), which sets
QueryFinishPending on all the QE processes, after the ExecRescanSort()
is executed, but before the next ExecSort(). This …

Fix double free of TupleSort memory context (6X)

---

src/bin/psql/describe.c
src/test/regress/expected/psql_gp_commands.out
src/test/regress/sql/psql_gp_commands.sql

When running \df+ on a function that has exec location INITPLAN, the
"Execute on" column did not properly display INITPLAN. This is because
psql was not updated to recognize the new exec location. To fix, simply
add exec location INITPLAN to the \df+ query.
commit reference:
https://github.com/greenplum-db/gpdb/commit/a21ff23b615e5f9a7dd3b02d82fad86175b188ec
This will need to be backported to 6X_STABLE as well.

Fix exec location INITPLAN not showing up in \df+

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py

Previously if incremental gprecoverseg fails we have to rerun with -v
to get the pg_rewind log for debugging. This is not convenient and also
sometimes the log output is not complete in the gprecoverseg log somehow.
Let's keep the pg_rewind log if incremental gprecoverseg fails.

Keep pg_rewind log if incremental gprecoverseg fails.

---

src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/test/regress/expected/domain.out
src/test/regress/expected/domain_optimizer.out
src/test/regress/sql/domain.sql

This field will be saved in catalog, if we do not dispatch it then the
catalog is not consistent among the cluster.
Fix github issue: https://github.com/greenplum-db/gpdb/issues/12015

Dispatch collClause field for CreateDomainStmt.

---

src/backend/commands/createas.c
src/backend/executor/execMain.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/tcop/utility.c
src/include/nodes/parsenodes.h
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

Previously even the statement of CTAS (or matview) is specified
with the no data flag, we will execute the plan for matview.
Besides, in the function `create_ctas_internal`, it builds
a CreateStmt and then dispatch to QEs. The framework is from
upstream and works well for upstream because there is only
one instance and one catalog in single Postgres. For Greenplum,
the MPP architecture force that we have to make catalog consistent.
This commit fixes the issue by dispatching the related fields to
QEs in CreateStmt.
Fix github issue https://github.com/greenplum-db/gpdb/issues/11999

Correct behavior of CTAS with no data

---

gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/commands/base.py
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
gpMgmt/bin/lib/gpconfigurenewsegment
gpMgmt/sbin/gpsegstart.py
gpMgmt/sbin/gpsegstop.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

gpmovemirrors and gprecoverseg spawn more parallel processes than the options passed in.
This change fixes that, correctly limiting the number of parallel processes we can spawn on coordinator.
And also introduces an option to limit it on each individual host.
6X PR: https://github.com/greenplum-db/gpdb/pull/12000
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpmovemirrors_fix_parallel)

movemirrors/recoverseg: -B option fix parallel processes 

---

src/backend/cdb/motion/ic_proxy_addr.c
src/backend/cdb/motion/ic_proxy_main.c
src/backend/cdb/motion/ic_proxy_peer.c
src/backend/cdb/motion/ic_proxy_server.h

When reloading the addresses we first sort them then classify them as
existing, added, or removed.  We use list_qsort() for the sorting, which
requires a compare function.  The compare function passes 2 pointers to
the list cells, the pointer type should be "ListCell **", but we used to
treat them as "ICProxyAddr *", so the adresses cannot be correctly
sorted and classified, this should cause problems when adding or
removing addresses.
Fixed the compare function.

ic-proxy: fix the sorting of addresses

---

gpdb-doc/dita/install_guide/install_r_dslib.xml

Library ellipsis was being included and not listed, library RcppRoll was listed and not being included.

Docs: added missing library, removed extra library

---

src/backend/cdb/cdbpartition.c
src/backend/cdb/partitionselection.c
src/include/cdb/cdbpartition.h
src/test/regress/expected/bfv_partition.out
src/test/regress/sql/bfv_partition.sql

This is a fixed version of reverted commit from https://github.com/greenplum-db/gpdb/pull/11709 .
Previously, I forgot to release temporary template tuple descriptor [allocated](https://github.com/greenplum-db/gpdb/pull/11709/files#diff-33f435105c31233e11adf06f798e6ed8fb1f42a62a27ecca338ed39fb0772b93R114) in `partition_selection()` function inside long living `ExecutorState` context. As a consequence, this caused memory leak when partition selection routine based on execution of level expressions (ORCA case) was often performed, e.g., under execution of following bulk insert:
```sql
CREATE TABLE rank (id int, rank int, year int, count int)
DISTRIBUTED BY (id)
PARTITION BY RANGE (year)
( START (2006) END (2016) EVERY (1), 
DEFAULT PARTITION extra ); 
insert into rank select i, 1, 2010, 12 …
```

Fix partition selector under join by keys with different types, take 2

---

src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/test/regress/expected/domain.out
src/test/regress/expected/domain_optimizer.out
src/test/regress/sql/domain.sql

This field will be saved in catalog, if we do not
dispatch it then the catalog is not consistent among
the cluster.
Fix github issue: https://github.com/greenplum-db/gpdb/issues/12015
-------
This is in master branch, now backport.

(6x backport) Dispatch collClause field for CreateDomainStmt.

---

src/backend/utils/workfile_manager/workfile_mgr.c

The workfile_set(or work_set referenced in the code) is used to
track the usage of the temporary files. For example, in hash join,
if the hash table is too large to put them all in the memory,
the hash table is split and saved in temporary files. When the
transaction is finished(no matter commit or abort), the workfile_set
referenced by the executor node will be freed(reference count).
There are also other workfile_set with different lifecycle(e.g. session).
The backend records the usage of the workfile_set in its local memory,
and it will free all the `workfile_set`s in the callback(AtProcExit_WorkFile)
when the backend is going to exit.
The problem is that the function `AtProcExit_WorkFile` is called before
the cleanup of the current transaction. So, the executor node may free
the …

Fix the double-free issue of work_set

---

src/backend/gporca/data/dxl/minidump/DML-Volatile-Function.mdp
src/backend/gporca/data/dxl/minidump/SqlFuncDmlScalar.mdp
src/backend/gporca/data/dxl/minidump/SqlFuncDmlTvf.mdp
src/backend/gporca/data/dxl/minidump/SqlFuncNullReject.mdp
src/backend/gporca/data/dxl/minidump/SqlFuncPredFactorize.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CFunctionProp.h
src/backend/gporca/libgpopt/include/gpopt/base/COptCtxt.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalApply.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalJoin.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalRowTrigger.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalTVF.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnary.h
src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h
src/backend/gporca/libgpopt/include/gpopt/operators/CScalar.h
src/backend/gporca/libgpopt/include/gpopt/operators/CScalarFunc.h
src/backend/gporca/libgpopt/src/base/CFunctionProp.cpp
src/backend/gporca/libgpopt/src/base/COptCtxt.cpp
src/backend/gporca/libgpopt/src/operators/CExpressionFactorizer.cpp
src/backend/gporca/libgpopt/src/operators/CLogical.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalRowTrigger.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalTVF.cpp
src/backend/gporca/libgpopt/src/operators/COperator.cpp
src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
src/backend/gporca/libgpopt/src/operators/CScalarWindowFunc.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/server/CMakeLists.txt
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp

The SQL 2003 standard specified 4 different levels of "SQL data access
indication":
1. NO SQL
2. CONTAINS SQL
3. READS SQL DATA
4. MODIFIES SQL DATA
Upstream PostgreSQL doesn't support any of the above. Greenplum has had
syntactic support for this as part of `CREATE FUNCTION` command, but so
far we only store that in the catalog (and possibly dump back out),
without taking it into consideration in our planning or execution
process. Except ORCA does, for a seemingly unnecessary purpose: ORCA
opts out of various optimizations when it sees a function that is not
"NO SQL" (that's a mouthful). The intent, it seems, is we really want to
execute such functions on the QD. But that seems questionable for two
fundamental reasons:
1. Forgoing the various optimizations (as evidenced by the test cases …

[ORCA] Stop checking data access indication

---

src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExcept.mdp
src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExceptAll.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifference.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifferenceAll.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersect.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersectAll.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSetOp.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnion.h
src/backend/gporca/libgpopt/src/operators/CLogicalSetOp.cpp
src/backend/gporca/server/CMakeLists.txt
src/test/regress/expected/qp_dml_joins.out
src/test/regress/expected/qp_dml_joins_optimizer.out
src/test/regress/sql/qp_dml_joins.sql

Issue manifested itself in the following query:
```
EXPLAIN INSERT INTO mytable
SELECT a.col FROM mytable a
INNER JOIN (
SELECT _a.col
FROM mytable _a,
mytable _b
WHERE  (_a.col = _b.col)
EXCEPT (SELECT col FROM mytable)
) b
ON (a.col = b.col);
```
Which produced the algebrized query:
```
+--CLogicalNAryJoin
|--CLogicalGet "mytable" ("mytable"), Columns: ["col" (0), ...]
|--CLogicalDifference Output: ("col" (8)), Input: [("col" (8)), ("col" (24))]
|  |--CLogicalNAryJoin
|  |  |--CLogicalGet "mytable" ("mytable"), Columns: ["col" (8), ...]
|  |  |--CLogicalGet "mytable" ("mytable"), Columns: ["col" (16), ...]
|  |  +--CScalarCmp (=)
|  |     |--CScalarIdent "col" (8)
|  |     +--CScalarIdent "col" (16)
|  +--CLogicalGet "mytable" ("mytable"), Columns: ["col" (24), ...]
+--CScalarCmp (=) …
```

Fix logical difference derived constraint property

---

src/backend/cdb/cdbsetop.c
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

An omission of CdbLocusType_SegmentGeneral led to an error error:
```
psql: ERROR:  unexpected argument locus to set operation (cdbsetop.c:187)
```
when running the following SQL statements:
```sql
CREATE TABLE reptable(a int) DISTRIBUTED REPLICATED;
CREATE SEQUENCE a_sequence;
SELECT a FROM reptable UNION ALL SELECT * FROM nextval('a_sequence');
```

Explicity call out all locus types in adjust_setop_arguments()

---

gpdb-doc/dita/admin_guide/expand/expand-initialize.xml

The removed file expand-rm-schema was still being referenced by one of the pages. It is pointing to the right page now.

Docs: changed reference to wrong file

---

gpdb-doc/dita/admin_guide/ddl/ddl-storage.xml

Since the provided example couldn't be run without defining the functions int33_in and int33_out, added a previous step where the functions are defined.

Docs: added function definition to create type example

---

src/backend/commands/user.c
src/test/isolation2/expected/resgroup/resgroup_syntax.out
src/test/isolation2/sql/resgroup/resgroup_syntax.sql

When altering a role set superuser or nosuperuser, should change the default
resource group to admin_group or default_group accordingly.

Change the default resource group when ALTER ROLE

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query44.ans
gpMgmt/bin/gpload_test/gpload2/query45.ans
gpMgmt/bin/gpload_test/gpload2/query46.ans

fix 6x gpload to support column name without quotes in yaml file
judge if an into_column name is quoted, if not, add double quotations to it. So we can compare it correctly with the column name from database for capital letters and special characters.
Pyyaml cannot check if a string is quoted or not, so we add double quotations to not quoted column names. This will support writing into columns like 'Col_name', "Col_name" and Col_name.  '"Col_name"' is also supported.

fix 6x gpload to support column without quotes

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_input_column.py
gpMgmt/bin/gpload_test/gpload2/query73.ans
gpMgmt/bin/gpload_test/gpload2/query76.ans
gpMgmt/bin/gpload_test/gpload2/query77.ans

fix 6x gpload to support column name without quotes in yaml file
judge if an into_column name is quoted, if not, add double quotations to it. So we can compare it correctly with the column name from database for capital letters and special characters.
Pyyaml cannot check if a string is quoted or not, so we add double quotations to not quoted column names. This will support writing into columns like 'Col_name', "Col_name" and Col_name. '"Col_name"' is also supported.

fix gpload to support column without quotes

---

src/backend/executor/nodeFunctionscan.c
src/backend/executor/nodeSort.c
src/test/regress/expected/subselect_gp2.out
src/test/regress/sql/subselect_gp2.sql

Executor try to squelch nodes in it‘s subtree after a node returning a
NULL tuple. But sometimes squelching is not safe. If the node is not
safe to squelch, the parameter ’delayEagerFree‘ will be set to true. We
should check the parameter when we squelch the node both on 'Execxxx'
function and 'ExecSquelchxxxx' function.
So add code checking 'delayEagerFree' in ExecSquelchSort and
ExecSquelchFunction.
Co-authored-by: Wen Lin <linw@vmware.com>

Check delay eager free in squelch functions

---

src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dumpall.c

This commit enables the proper dump of keywords used as identifiers
during an upgrade in the context of partition tables and otherwise (the
upgrade being from versions 5 -> 7+)
This is a forward port of PR: #11939. Please refer to it for detailed
commentary.
(cherry picked from commit 86efbf09efffea8cc340ac8905f318719d5ee82e)

pg_dump(all): Allow quote_all_identifiers for 8.3

---

concourse/pipelines/templates/gpdb-tpl.yml

Change pipeline to use the private gpdb5-centos6-build-mingw image.
Also, remove unused python-behave resource.
[GP-588]
Dev pipleine - https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-batturu

The gpdb5-centos6-build-mingw image has been changed to private.

---

gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature

gprecoverseg -r didn't pick up the -B/-b options for spawning correct number of parallel processes.
This change fixes that behaviour.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/recoverseg_rebalance_fix_parallel)

gprecoverseg rebalance: fix parallel processes -B/-b option

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/programs/clsAddMirrors.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

gpaddmirrors does not spawn correct number of parallel processes as intended by -B option.
This change fixes that behavior
We would be using two options for finer control.
'-B' option limits the number of hosts working in parallel for recovery
'-b' option limits the number of segments working in parallel on a host
https://github.com/greenplum-db/gpdb/pull/11933 added a similar feature to gpmovemirrors.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpaddmirrors_fix_parallel)

gpaddmirrors: fix parallel processes -B/-b option

---

src/backend/executor/nodeFunctionscan.c
src/backend/executor/nodeSort.c
src/test/regress/expected/subselect_gp2.out
src/test/regress/sql/subselect_gp2.sql

Executor try to squelch nodes in it‘s subtree after a node returning a NULL tuple.
But sometimes squelching is not safe. If the node is not safe to squelch, the
parameter ’delayEagerFree‘ will be set to true. We should check the parameter
when we squelch the node both on 'Execxxx' function and 'ExecSquelchxxxx' function.
So add code checking 'delayEagerFree' in ExecSquelchSort and
ExecSquelchFunction.
This is a backport of commit 361f211 from master.
Co-authored-by: Jinbao Chen <cjinbao@vmware.com>

[Backport 6X] Check delay eager free in squelch functions.

---

src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExcept.mdp
src/backend/gporca/data/dxl/minidump/InnerJoinOverJoinExceptAll.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifference.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDifferenceAll.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersect.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalIntersectAll.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSetOp.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnion.h
src/backend/gporca/libgpopt/src/operators/CLogicalSetOp.cpp
src/backend/gporca/server/CMakeLists.txt
src/test/regress/expected/qp_dml_joins.out
src/test/regress/expected/qp_dml_joins_optimizer.out
src/test/regress/sql/qp_dml_joins.sql

Issue manifested itself in the following query:
```
EXPLAIN INSERT INTO mytable
SELECT a.col FROM mytable a
INNER JOIN (
SELECT _a.col
FROM mytable _a,
mytable _b
WHERE  (_a.col = _b.col)
EXCEPT (SELECT col FROM mytable)
) b
ON (a.col = b.col);
```
Which produced the algebrized query:
```
+--CLogicalNAryJoin
|--CLogicalGet "mytable" ("mytable"), Columns: ["col" (0), ...]
|--CLogicalDifference Output: ("col" (8)), Input: [("col" (8)), ("col" (24))]
|  |--CLogicalNAryJoin
|  |  |--CLogicalGet "mytable" ("mytable"), Columns: ["col" (8), ...]
|  |  |--CLogicalGet "mytable" ("mytable"), Columns: ["col" (16), ...]
|  |  +--CScalarCmp (=)
|  |     |--CScalarIdent "col" (8)
|  |     +--CScalarIdent "col" (16)
|  +--CLogicalGet "mytable" ("mytable"), Columns: ["col" (24), ...]
+--CScalarCmp (=) …
```

[6X backport] Fix logical difference derived constraint property (#12009)

---

src/backend/commands/createas.c
src/backend/executor/execMain.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/tcop/utility.c
src/include/nodes/parsenodes.h
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

Previously even the statement of CTAS (or matview) is specified
with the no data flag, we will execute the plan for matview.
Besides, in the function `create_ctas_internal`, it builds
a CreateStmt and then dispatch to QEs. The framework is from
upstream and works well for upstream because there is only
one instance and one catalog in single Postgres. For Greenplum,
the MPP architecture force that we have to make catalog consistent.
This commit fixes the issue by dispatching the related fields to
QEs in CreateStmt.
Fix github issue #11999
-----------------------------------
PR for master branch is merged, backporting to 6X.

(backport to 6x) Correct behavior of CTAS with no data.

---

gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_conf.py
gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py

Currently, when recovering segments gprecoverseg updates the pg_hba.conf
entries on every acting primary regardless of whether those primaries
have mirrors to be recovered.  This commit restricts the update to only
those primaries that need to be updated.

gprecoverseg: Skip pg_hba update on non-failed hosts

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/aggregates.out
src/test/regress/expected/aggregates_optimizer.out
src/test/regress/sql/aggregates.sql

In Github issue #12061, there is an assert failure that the numsegments is
wrongly set to segnum for general locus in function create_minmaxagg_path.
General Locus means the tuples could be fetched from any segments or
coordinator, so the numsegments of general locus should always be -1.
This PR simpely set numsegments of general locus to -1 in create_minmaxagg_path.
Co-authored-by: pingfu li <peefau@163.com>
Co-authored-by: Peng Han <parker.han@outlook.com>
Co-authored-by: xianglli <mail@plizong.com>
Co-authored-by: miaopo <992470565@qq.com>
Co-authored-by: ranger0925 <youxinhua0925@126.com>
Co-authored-by: mabingbing <290800656@qq.com>
Co-authored-by: jianfei wen <wenjianfei@163.com>
- [x ] Pass `make installcheck`

Fix numsegments is not set correctly for general locus 

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/data/external_file_15.txt
gpMgmt/bin/gpload_test/gpload2/data/external_file_16.txt
gpMgmt/bin/gpload_test/gpload2/query40.ans
gpMgmt/bin/gpload_test/gpload2/query41.ans
gpMgmt/bin/gpload_test/gpload2/query42.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

back port fix from 6x to support gpload column name having capital letters without quotes.
fix 5x gpload to support column name without quotes in yaml file
judge if an into_column name is quoted, if not, add double quotations to it. So we can compare it correctly with the column name from database for capital letters and special characters.
Pyyaml cannot check if a string is quoted or not, so we add double quotations to not quoted column names. This will support writing into columns like 'Col_name', "Col_name" and Col_name. '"Col_name"' is also supported.

fix gpload 5x support column name with capital letters

---

src/test/isolation2/expected/ao_same_trans_truncate_crash.out
src/test/isolation2/expected/fsync_ao.out
src/test/isolation2/sql/ao_same_trans_truncate_crash.sql
src/test/isolation2/sql/fsync_ao.sql

Some tests enable fsync temporarily, but disable fsync incorrectly finally
since they use "gpconfig -r". "gpconfig -r" comments out the guc setting so
finally the system uses the default guc value but for guc fsync the default
value is off. Fixing this by explicitly set fsync off with gpconfig in those
tests.
This change should be able to speed up testing some since all subsequent tests
after those tests could be accelerated now.

Turn fsync off correctly in some tests

---

src/backend/libpq/hba.c
src/backend/utils/init/postinit.c

Free the contexts holding this data after we're done using it, by the
expedient of attaching them to the PostmasterContext which we were
already taking care to delete (and where, indeed, this data used to live
before commits e5e2fc842c418432 and 7c45e3a3c682f855).  This saves a
probably-usually-negligible amount of space per running backend.  It also
avoids leaving potentially-security-sensitive data lying around in memory
in processes that don't need it.  You'd have to be unusually paranoid to
think that that amounts to a live security bug, so I've not gone so far as
to forcibly zero the memory; but there surely isn't a good reason to keep
this data around.
Arguably this is a memory management bug in the aforementioned commits,
but it doesn't seem important enough to back-patch.
(cherry …

Don't leave pg_hba and pg_ident data lying around in running backends.

---

src/test/isolation2/expected/ao_same_trans_truncate_crash.out
src/test/isolation2/expected/fsync_ao.out
src/test/isolation2/sql/ao_same_trans_truncate_crash.sql
src/test/isolation2/sql/fsync_ao.sql

Some tests enable fsync temporarily, but disable fsync incorrectly finally
since they use "gpconfig -r". "gpconfig -r" comments out the guc setting so
finally the system uses the default guc value but for guc fsync the default
value is on. Fixing this by explicitly set fsync off with gpconfig in those
tests.
This change should be able to speed up testing a lot since all subsequent tests
could be accelerated.
Reviewed by: Ashwin Agrawal <aashwin@vmware.com>
(cherry picked from commit b43ffa0966575fd3f10ce7242c750b2b1042fd25)

[6X Backport] Turn fsync off correctly in some tests (#12088)

---

src/backend/gporca/data/dxl/minidump/AllSubqueryWithSubqueryInScalar.mdp
src/backend/gporca/data/dxl/minidump/MultiLevel-NOT-IN-Subquery.mdp
src/backend/gporca/data/dxl/minidump/NotInToLASJ.mdp
src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
src/backend/gporca/server/CMakeLists.txt
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/qp_misc_jiras_optimizer.out
src/test/regress/sql/gporca.sql

NOT IN is equivalent to "<> ALL" SQL expression and should be replaced
with LAS-Apply-NotIn in CSubqueryHandler::FRemoveAllSubquery().
Earlier, ORCA transformed "<> ALL" subquery to a LAS-Apply-NotIn with the apply
predicate as a filter over it's inner child (See CXformSelect2Apply). This is
problematic when the subquery contains NULLs, as the generated filter is NULL
rejecting. Thus, although LAS-Apply-NotIn correctly handles the NULL-semantics
of a NOT IN subquery, an incorrect NULL rejecting filter on inner side will
prevent the Apply from seeing any NULLs, resulting in wrong results.
For example: A LOJ inside the NOT IN subquery (see issue #10967)
```
create table t1(a int) distributed by (a);
insert into t1 values (1), (2), (3);
set optimizer_join_order='query';
select * from t1 …
```

Fix wrong results from nested LOJ in ALL subqueries

---

src/backend/tcop/postgres.c

At the moment, an error will always generate a debug_query_string
exception message in the logs even when log_min_messages is set to
PANIC. This can be a security concern if the query string is not meant
to be logged (e.g. a failed pgcrypto decrypt query is logged which can
be equivalent to logging a plaintext password).
Fix the issue by changing the call function from write_stderr to elog.
With elog, the log message will be controlled by log_min_messages and
may enhance the original debugging intent (the debug_query_string log
will always show the user-executed query along with the actual query
that failed).
GPDB references:
https://github.com/greenplum-db/gpdb/pull/1456
https://github.com/greenplum-db/gpdb/commit/bd7f682392b30b859588d0d60f2625095f1cd63f
This will need to be backported …

Allow debug_query_string exception log messages to be suppressed

---

contrib/pg_upgrade/greenplum/check_gp.c

This commit introduces a pg_upgrade check to look for views referencing
deprecated tables in a 5X cluster.
This is accompanied by 5X PR: #12072, which introduces a
pg_upgrade_support UDF to detect such views.

[6X] pg_upgrade check: views with deprecated tables

---

src/test/fsync/expected/bgwriter_checkpoint.out
src/test/fsync/sql/bgwriter_checkpoint.sql

Saw this on CI. Here is the diff. The reason might be autovacuum relevant.
Let's disable autovacuum during testing to see if the failure is gone.
@@ -121,7 +121,8 @@
as (tablespace oid, database oid, relfilenode oid, block int);
tablespace | database | relfilenode | block
------------+----------+-------------+-------
-(0 rows)
+       1663 |    16384 |       17756 |   101
+(1 row)
-- Make buffers dirty.  At least two relfiles must be sync'ed during
-- next checkpoint.

Try to fix flaky test fsync/sql/bgwriter_checkpoint

---

contrib/pg_upgrade/greenplum/check_gp.c

This fixes the upgrade path for 6X->6X upgrades which was broken by
67df5542a8 with the following error during a 6X->6X upgrade:
```
Checking for views referencing deprecated tables            SQL command failed
CREATE OR REPLACE FUNCTION view_references_deprecated_tables(OID) RETURNS BOOL AS '$libdir/pg_upgrade_support' LANGUAGE C STRICT;
ERROR:  could not find function "view_references_deprecated_tables" in file "/usr/local/greenplum-db-devel/lib/postgresql/pg_upgrade_support.so"
```
For upgrades from 6X->6X, we should not have to run this check as
deprecated object detection only applies to major version upgrades.

pg_upgrade_support: Fix 6X->6X upgrade path

---

src/backend/access/transam/xlog.c
src/backend/storage/file/fd.c
src/bin/pg_rewind/pg_rewind.c
src/include/storage/fd.h
src/test/isolation2/expected/ao_same_trans_truncate_crash.out
src/test/isolation2/sql/ao_same_trans_truncate_crash.sql

This is an alternative method for the issue discussed in https://github.com/greenplum-db/gpdb/pull/11896. The PR includes two commits.
```
commit 90219f3935e7bb8a9adb63823dca1926803b955e (HEAD -> sync_opt, origin/sync_opt)
Author: Paul Guo <guopa@vmware.com>
Date:   Wed Jan 20 16:05:34 2021 +0800
Just fsync those affected files during pg_rewind.
In gpdb we've ensured that the database is in sync state before rewinding, so
we could just fsync those affected files after rewinding.
commit 8d3100bb7400d909a6c6093baafc6f0c5922700b
Author: Paul Guo <pguo@pivotal.io>
Date:   Thu May 27 14:18:41 2021 +0800
Optimize the pgdata directory fsync during startup.
Previously startup would fsync all files under the whole pgdata directory if
the database is not cleanly shutdown. This step could be rather …
```

fsync related optimization for gpdb recovery

---

gpdb-doc/dita/best_practices/encryption.xml

Section "Encrypting Data in Tables using PGP" does not work if we don't create the pgcrypto extension before inserting data into the tables.
Also corrected the INSERT syntax since there was a ")" missing.

Docs: Pgcrypto - Added extra step to create extension

---

gpdb-doc/dita/security-guide/topics/Auditing.xml

Corrected example on how to use gplogfilter so it segment directory matches the path we specify under the installation guide ( /data*/*/gp*/pg_log/gpdb*.csv)

Docs: edited provided gplogfilter example

---

gpdb-doc/dita/admin_guide/highavail/topics/g-restoring-master-mirroring-after-a-recovery.xml

The first 4 steps instruct user on how to restore master mirroring, and the following steps are optional if user wants to swap roles again between master/standby.
@VMWareJennyBeth can you confirm if it looks clear? I have added a paragraph on the second process to make sure user follows the first 4 steps before moving on to the optional one:
https://mireia-standby.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/highavail/topics/g-restoring-master-mirroring-after-a-recovery.html
thanks!

Docs: Split Restoring Master Mirroring steps into two processes

---

gpdb-doc/dita/security-guide/topics/gpcc.xml

This PR is against 6X_STABLE since the file gpcc.xml is not present under dita/security-guide/topics/

Docs: Added reload command

---

gpdb-doc/dita/admin_guide/managing/monitor.xml

The command `gplogfilter -n 3` reads the last 3 lines of each of the log files located under the master directory, not only the last 3 lines of the master logs. Corrected the docs so it reflects this more clearly.

Docs: corrected statement about gplogfilter

---

gpdb-doc/dita/best_practices/data_loading.xml

One of the references to guc gp_external_max_segs was incorrect, stating gp_external_max_segments instead. This has now been corrected.

Docs: incorrect guc gp_external_max_segments

---

src/backend/cdb/dispatcher/cdbdisp_async.c

This PR will fix #10955
In short: 
most in the case, this log is printed on connection broken, the previous message is misleading to user.
so improve the message and adjust log level from INFO to DEBUG.

Fix misleading log: libpq says we are still busy

---

src/bin/pg_rewind/pg_rewind.c

commit f695018614ea6e17849bb36442db7e9bf23b7e68 does fsync affected files after
pg_rewind. It forgets to fsync the pgdata directory itself since we write a new
file backup_label under the directory.

fsync the pgdata directory itself after pg_rewind.

---

concourse/pipelines/README.md
gpAux/Makefile
gpAux/Makefile.global
gpAux/Makefile.thirdparty
gpAux/client/scripts/greenplum_clients_path.sh
gpAux/releng/set_bld_arch.sh
gpMgmt/bin/Makefile
gpMgmt/bin/gpload
gpMgmt/bin/gpload_test/gpload2/README
gpdb-doc/dita/install_guide/platform-requirements.xml
src/bin/gpfdist/Makefile
src/template/aix

AIX has never been supported for GP6. Remove code supporting AIX in the
enterprise build system.

6X: Remove AIX build support from gpAux.

---

src/bin/pg_rewind/pg_rewind.c

Not remember why I forgot to do that (I did do that in the PG patch).

pg_rewind: should do fsync after writing the recovery conf information.

---

src/backend/tcop/postgres.c

PostmasterContext is not necessary for a normal postgres backend
process, drop it to save memory.
In a corner case, the flat files it loaded into memory, like hba, ident
and role files, could be big, which would be a serious issue if the
postmaster forks them with thousands of copies without vmem tracking.
FYI, CoW memory is counted by system OOM killer if the Linux
configuration vm.overcommit_memory is 2.

Drop PostmasterContext after InitPostgres()

---

src/backend/commands/sequence.c
src/test/regress/expected/sequence_gp.out
src/test/regress/sql/sequence_gp.sql

Issue is that since `nextval_internal()` handles requests from both QD
and QE, it was possible to reference a `SeqTable` object containing
cached numbers that belonged to a different requestor. This led to a
chance to generate duplicate sequence values.
This issue may be benign as typical `nextval()` request flows from QE to
QD, except when user calls `SELECT nextval()` directly on QD itself.
However, seems better to be consistent and not produce any duplicate
sequence values.

Fix stale sequence reference causing duplicate nextval()

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gporca/libgpos/include/gpos/common/CLink.h
src/include/gpopt/translate/CPartPruneStepsBuilder.h

This is a one-off fix for all the errors / warnings we encounter when running clang-tidy against `src/backend/gpopt`. There's a forthcoming patch that should make it more accessible to continuously run these checks both locally and in CI. See either commit for details

Fix clang tidy warnings in translator

---

gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/commands/base.py
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/programs/clsAddMirrors.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py
gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
gpMgmt/bin/lib/gpconfigurenewsegment
gpMgmt/sbin/gpsegstart.py
gpMgmt/sbin/gpsegstop.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

This is a 6X backport for https://github.com/greenplum-db/gpdb/pull/11933, https://github.com/greenplum-db/gpdb/pull/12058, https://github.com/greenplum-db/gpdb/pull/12039
gpmovemirrors and gprecoverseg spawn more parallel processes than the options passed in.
This change fixes that, correctly limiting the number of parallel processes we can spawn on master.
And also introduces an option -b to limit number of segments recovered on each individual host in parallel.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6x_gpmovemirrors_fix_parallel)

6x backport: movemirrors/recoverseg: -B option fix parallel processes

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature

If one (or more) of the hosts are unreachable, gprecoverseg -p
showed an error (ssh: unreachable host) even though the operation
continued and finalized successfully. This commit adds checks to
eliminate these redundant ssh calls.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6xgprecoverseg_fix_error)

[6X_STABLE] gprecoverseg: Clean error log for successful run

---

gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py

Having different defaults/max  -B option values between utils created a bug. 
When one util calls another with -B value above the called util's limit, the operation would cause failure.
This change fixes that.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/uniform_utils_defaults)

uniform default/max -B options values across utils

---

src/backend/tcop/postgres.c

At the moment, an error will always generate a debug_query_string
exception message in the logs even when log_min_messages is set to
PANIC. This can be a security concern if the query string is not meant
to be logged (e.g. a failed pgcrypto decrypt query is logged which can
be equivalent to logging a plaintext password).
Fix the issue by changing the call function from write_stderr to elog.
With elog, the log message will be controlled by log_min_messages and
may enhance the original debugging intent (the debug_query_string log
will always show the user-executed query along with the actual query
that failed).
GPDB references:
https://github.com/greenplum-db/gpdb/pull/1456
https://github.com/greenplum-db/gpdb/commit/bd7f682392b30b859588d0d60f2625095f1cd63f
Backport of …

[5X backport] Allow debug_query_string exception log messages to be suppressed

---

src/backend/tcop/postgres.c

At the moment, an error will always generate a debug_query_string
exception message in the logs even when log_min_messages is set to
PANIC. This can be a security concern if the query string is not meant
to be logged (e.g. a failed pgcrypto decrypt query is logged which can
be equivalent to logging a plaintext password).
Fix the issue by changing the call function from write_stderr to elog.
With elog, the log message will be controlled by log_min_messages and
may enhance the original debugging intent (the debug_query_string log
will always show the user-executed query along with the actual query
that failed).
GPDB references:
https://github.com/greenplum-db/gpdb/pull/1456
https://github.com/greenplum-db/gpdb/commit/bd7f682392b30b859588d0d60f2625095f1cd63f
Backport of …

[6X backport] Allow debug_query_string exception log messages to be suppressed

---

gpdb-doc/dita/security-guide/topics/Authenticate.xml

We do not ship a version of openssl with Greenplum 6 so there is no openssl.conf file under $GPHOME/etc.
It is now listed as a requirement https://greenplum.docs.pivotal.io/6-16/install_guide/platform-requirements.html
I removed the whole OpenSSL Configuration section since it only consisted of an explanation of that file. I can add it again with references to how to configure OpenSSL or references to OpenSSL documentation if that makes more sense?

docs: removed reference of openssl.conf

---

gpdb-doc/dita/best_practices/bloat.xml

As discussed, removing the REINDEX steps from the section "Steps for intensive system catalog maintenance".
Section "Removing bloat from system catalogs" stays the same.

Docs: Removed REINDEX step from intensive system catalog maintenance

---

concourse/tasks/build_with_orca.yml
concourse/tasks/diff_explain_results_with_baseline.yml
concourse/tasks/test_icg.yml
concourse/tasks/untar_build_with_orca.yml

Pushed image to gcr.io/data-orca/qp-gpdbdev:latest.
$ gcloud container images list --repository gcr.io/data-orca
NAME
gcr.io/data-orca/qp-gpdbdev
This commit updates the corresponding pipeline references.

Migrate qp-gpdbdev image to GCR

---

gpMgmt/bin/gppylib/gpMgmttest/__init__.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/programs/Makefile
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature

gprecoverseg: refactor code to enable unit testing of recovery triples
gprecoverseg has two main parts: determining the segment information
necessary for recovery and then performing that recovery.  This commit
simplifies the determination of the segment information necessary for
recovery.
This commit provides a minor refactor of the code with extensive unit
testing.
The main information needed is the list of Segment triples:
[ (failed, live, failover),... ]
The failed Segment is recovered to the failover segment using the live
segment information.
Refactoring the current implementation to return only the recovery
triples information allows unit testing.  We have added tests for:
- "-i config_file.txt" that provides inconsistent information.  For
instance, specifying two different …

gprecoverseg: refactor creation of recovery triples

---

src/backend/parser/gram.y
src/test/regress/input/appendonly.source
src/test/regress/output/appendonly.source

Commit b3b2797e adds an alias `appendoptimized ` for AO table, but forget to
modify the PartSpec related syntax. The commit b3b2797e exists in Greenplum 6,
we should fix this for PartSpec also.

(6x only) Fix appendoptimized alias issue for appendonly.

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/bfv_planner.out
src/test/regress/expected/bfv_planner_optimizer.out
src/test/regress/sql/bfv_planner.sql

The function set_append_path_locus will deduce the append path's
locus in two steps:
* first, loop all subpaths to deduce the final locus type
* second, depends on the final locus type, choose next step,
if final locus type is Strewn, then it will loop each subpaths
to see if finaly is Strewn or can be Hashed. If any of the
two subpaths' locus are different, we will set to Strewn with
numsegments to be the max numsegments of all subpaths.
Previous code break out the loop and just set the numsegments to be
the max of the last two not all. This commit fixes this by recording
max numsegments in the first loop.
Fix Github Issue: https://github.com/greenplum-db/gpdb/issues/12146

set_append_path_locus should use max numsegments when break loop.

---

gpMgmt/bin/gpstart

Correction of gpstart -m warning message to more appropriate one
As discussed, creating the PR in master (old PR on 6X_STABLE https://github.com/greenplum-db/gpdb/pull/12142)

gpstart -m warning messages change

---

src/backend/gporca/data/dxl/minidump/LOJ-PushDown.mdp
src/backend/gporca/libgpopt/src/xforms/CXformPushDownLeftOuterJoin.cpp
src/backend/gporca/server/CMakeLists.txt

The CXformPushDownLeftOuterJoin pushes a left outer joins whose outer
child is an NAry join to be a child of the NAry-join. However, this
transform is not possible when the LOJ predicate doesn't use any columns
from the NAry-Join.
This commit fixes a bug in the xform implementation that assumed it
would always find at least one child of the NAry-join to become the
outer child of the LOJ and thus performed an out-of-bounds access.
Repro (No data needed):
```
create table push_t1 (a int, b int);
create table push_t2 (a int, b int);
create table push_t3 (a int, b int);
explain select 1 from push_t3 where exists (
select * from (select x.* from push_t1 x join push_t1 y using (a)) t left join push_t2 on (push_t2.a = push_t3.a));
```
This issue also exists on master branch (with `set …

Fix out-of-bounds error in CXformPushDownLeftOuterJoin

---

gpMgmt/bin/gpcheckcat
gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature

gpcheckcat currently allows running only one test at a time or running
all tests. This change allows the user to select a subset of tests to
run or skip.
This introduces a -s option for skipping tests.
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/checkcat_add_skiptest)

gpcheckcat: allow running/skipping multiple tests

---

gpMgmt/bin/gpdeletesystem
gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/operations/Makefile
gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpdeletesystem.py
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

The issue was raised on the internal portal for utility gpmovemirrors that failed to remove old user-defined tablespace directories for a mirror when it's moved to a new host. 
This commit includes the following changes:
* common function `get_tablespace_locations` to get user-defined tablespace locations from all hosts or specific mirror data directory
* unit and behave test for function 
* Function is implemented in utilities gpmovemirrors and gpdeletesystem to fix the issue
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpmovemirror_rm_old_tblspc_dir)
Co-authored-by: Jamie McAtamney jmcatamney@vmware.com, Orhan Kislal okislal@vmware.com

gpmovemirrors: remove tablespace directories from old host

---

gpMgmt/bin/gpdeletesystem
gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/operations/Makefile
gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpdeletesystem.py
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

6X backport for [11831](https://github.com/greenplum-db/gpdb/pull/11831)
gpmovemirrors did not remove the mirror tablespace directories on old host after move to a new host. This commit will help in the cleanup of unused tablespace directories from old host
[Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6X_gpmovemirror_rm_old_tblspc_dir)

6X backport: gpmovemirrors to remove tablespace directories on old host

---

contrib/pg_upgrade/dump.c
src/bin/pg_dump/pg_dumpall.c

This PR consists of two commits. Please review these separately.
1) Fix dump of built-in resource groups.
2) Pass `--resource-groups` and `--resource-queues` to `pg_dumpall` during a `pg_upgrade`.
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/dumpResgrp_6X
Upgradeable regress-style tests (which tests the schema upgrade): https://github.com/greenplum-db/gpupgrade/pull/561
Additional testing: This PR was tested in a CI environment supporting resource groups by
upgrading a resource group from `resgroup_memory_limit.source` and checking that
the memory limits prescribed by that group were respected when queries on the target
cluster exceeded the limits.
Co-authored-by: Kalen Krempely <kkrempely@vmware.com>

6X: Upgrade resource queues and groups

---

gpMgmt/doc/gpaddmirrors_help
gpMgmt/doc/gprecoverseg_help

gprecoverseg and gpaddmirrors have changed behavior for -B/-b options.
This commit is to edit the help files to show that change.
gpmovemirrors/gprecoverseg changes: 695a73aa19, 25e463d7ae, 26e8a0bf6c, cb55a7e567
gpaddmirrors changes: 3a4067395d

recoverseg/addmirrors: change -B/-b help description

---

src/backend/commands/user.c
src/test/isolation2/expected/resgroup/resgroup_syntax.out
src/test/isolation2/sql/resgroup/resgroup_syntax.sql

When altering a role set superuser or nosuperuser, should change the default
resource group to admin_group or default_group accordingly.

[6X backport] Change the default resource group when ALTER ROLE

---

gpMgmt/doc/gpstart_help

Adding --skip-heap-checksum-validation to gpstart help section
Co-authored-by: Sambitesh Dash sdash@pivotal.io

Missing option in gpstart --help

---

src/backend/commands/sequence.c
src/test/regress/expected/sequence_gp.out
src/test/regress/sql/sequence_gp.sql

In the current sequence design, all sequence allocations originating
from dispatcher or executor ultimately flow through the dispatcher.
This led to a situation where it was possible to reference a `SeqTable`
object containing cached sequence numbers that belonged to a different
requestor.  This meant that it was possible to generate duplicate
sequence values.
Fix is to maintain separate sequence caches on dispatcher that
distinguishes between sequences allocated to dispatcher and those
allocated to executors. When the dispatcher sequence is mantained
separately, it is able to freely consume its own sequence numbers from
its cache without fear of duplicating values allocated to an executor.
(cherry picked from commit d8747002b9a0e7d73c377cb56539c08bc0b7c47f)
Notes:
In 6X this bug was …

[6X Backport] Fix stale sequence reference causing duplicate nextval() (#12029)

---

src/backend/gpopt/translate/CTranslatorUtils.cpp
src/include/gpopt/translate/CTranslatorUtils.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

in function CTranslatorUtils::ResolvePolymorphicTypes(), the size
of array arg_types is num_args, and it is smaller than total_args,
this causes a memory corruption and a backend crash. Fixed by
correcting the array size "total_args"(num_args + num_return_args).
Fixes GitHub issue #11880

Fix array overflow for function argument types in orca

---

gpMgmt/doc/gpaddmirrors_help
gpMgmt/doc/gprecoverseg_help

gprecoverseg and gpaddmirrors have changed behavior for -B/-b options.
This commit is to edit the help files to show that change.
gprecoverseg changes: 736bd3fdff, d7c854f8ae, 54261fb073, 0f30f1dd3c
gpaddmirrors changes: 489b89c4ad

addmirrors/recoverseg : change -B/-b help desc

---

gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_conf.py

Due to disordered execution of unit test case, tests that depend on GPHOME environment variable failed after execution of package test_unit_update_pg_hba_conf. This test reset GPHOME to new location
causing "No such file or directory" Error.  
Fix has been applied to fetch GPHOME from current environment

fixed check centos unit test flakiness

---

contrib/pg_upgrade_support/deprecated_objects.c
contrib/pg_upgrade_support/pg_upgrade_support.c

This commit ensures that `check_node_deprecated_tables_walker` recurses into
all possible expressions that can contain range tables. Earlier, we only
dealt with CTEs, but not sublinks for instance. So the following view
would not have been detected:
```sql
CREATE VIEW dep_rel_sublink AS SELECT dbid FROM gp_segment_configuration
WHERE 0 < ALL (SELECT fsedbid FROM pg_filespace_entry);
```
This commit also makes the walker implementation more canonical and
removes the pre-existing recursion logic for CTEs(which we now get for
free with `expression_tree_walker`). Some additional minor improvements
along the way.
Please refer to #12168, which introduces a similar walker to check for
deprecated columns.

[5X] Fix walker that detects deprecated tables

---

src/backend/fts/ftsprobe.c

FTS's workflow prints the error message first and processes the error
later. It confuses some customers, especially the customer who monitors
the log in real-time.
Add an "ERROR" keyword for customer convenience, as we discussed.

Update message of FTS double fault detected

---

src/backend/fts/ftsprobe.c

FTS's workflow prints the error message first and processes the error
later. It confuses some customers, especially the customer who monitors
the log in real-time.
Add an "ERROR" keyword for customer convenience, as we discussed.

6X: Update message of FTS double fault detected

---

src/backend/replication/gp_replication.c
src/backend/replication/test/gp_replication_test.c
src/test/isolation2/expected/segwalrep/max_slot_wal_keep_size.out
src/test/isolation2/sql/segwalrep/max_slot_wal_keep_size.sql

Previously, FTS used to treat a mirror as up as soon as the walsender enters `catchup` state.  This patch restricts that criterion.  A mirror is now considered up only if it at least one chunk of WAL has been transferred to it.
An active replication slot is obsoleted when replication lag grows beyond `max_slot_wal_keep_size` limit.  This is a point of no return, the mirror must be destroyed and recreated using `pg_basebackup` (`gprecoverseg -F`).  The walsender process exits when this happens.  However, the walreceiver on mirror is oblivious to this and keeps on attempting new replication connections.
Walsender enters `catchup` state immediately upon receiving a connection request.  The request fails soon after, when an attempt to locate the requested start LSN in locally available WAL …

Mirror is up only if it has received WAL

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/bfv_planner.out
src/test/regress/sql/bfv_planner.sql

The function set_append_path_locus will deduce the append path's
locus in two steps:
* first, loop all subpaths to deduce the final locus type
* second, depends on the final locus type, choose next step,
if final locus type is Strewn, then it will loop each subpaths
to see if finaly is Strewn or can be Hashed. If any of the
two subpaths' locus are different, we will set to Strewn with
numsegments to be the max numsegments of all subpaths.
Previous code break out the loop and just set the numsegments to be
the max of the last two not all. This commit fixes this by recording
max numsegments in the first loop.
Fix Github Issue: https://github.com/greenplum-db/gpdb/issues/12146

(6x) set_append_path_locus should use max numsegments when break loop.

---

src/backend/tcop/postgres.c
src/backend/utils/misc/guc_gp.c
src/test/isolation2/expected/crash_recovery.out
src/test/isolation2/expected/crash_recovery_dtm.out
src/test/isolation2/expected/crash_recovery_redundant_dtx.out
src/test/isolation2/expected/segwalrep/dtx_recovery_wait_lsn.out
src/test/isolation2/sql/crash_recovery.sql
src/test/isolation2/sql/crash_recovery_dtm.sql
src/test/isolation2/sql/crash_recovery_redundant_dtx.sql
src/test/isolation2/sql/segwalrep/dtx_recovery_wait_lsn.sql

This is a back patch of PR #12153 from 7.  Cherry-pick was clean, this PR is only for visibility.
The before_read_command fault location is executed by not only regular backends but also special backends such as FTS probe backends, fault injection backends, walsender, etc.  Several tests made use of this fault to cause PANIC in QD, after executing a command.  This strategy caused intermittent failures in CI because the fault would trigger unexpectedly from other backends listed above.  This patch defines a new fault in `exec_simple_query()` that is guaranteed to be triggered only by query executing backends.  This should resolve some of the intermittent failures in CI.

[6X back patch]  Avoid before_read_command fault usage where possible 

---

concourse/scripts/compile_gpdb.bash

include_dependencies searches build environment for vendored libs and includes the provided list of vendored shared libraries and headers in server installdir
Set library_search_path precedence ld.so.conf.d > system paths
For each path, search for the library and copy the first match to ${GREENPLUM_INSTALL_DIR}/lib
If the file already exists in ${GREENPLUM_INSTALL_DIR}/lib the library will be skipped
Search /usr/local/include and /usr/include for each vendored header.
If found, copy header to destination directory ${GREENPLUM_INSTALL_DIR}/include
If the file already exists in ${GREENPLUM_INSTALL_DIR}/include the header will be skipped
Vendor pkgconfig files libzstd.pc libuv.pc quicklz.pc

7X: include_dependencies searches build environment for vendored libs

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature

Mirrors with **standby.signal** file display empty status after pg_rewind
call during incremental recovery. pg_rewind is not required in this
scenario as per the existing design and replication needs to be handle by
WAL.  As empty status creates confusion at the user end, this commit will
introduce valid status "skipping pg_rewind on mirror as standby.signal is present".
It also changes existing recoverseg message from **Running pg_rewind on required mirrors**
to  **Running pg_rewind on failed segments**

gprecoverseg: show valid status for mirror with no pg_rewind

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/data/external_file_47.txt
gpMgmt/bin/gpload_test/gpload2/query47.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

If gpload loads one file with 'REUSE_TABLES' and 'HEADER' for the first time. Then loads another file with 'REUSE_TABLES' and without 'HEADER', the second loading will reuse the first external table which make the second loading miss the first line.
The reuse table procedure tries to get the existing external table and
compare the format option strings with sql 'like "%fmtopts%'. If the result
returns at least one table, it will reuse the existing external table. The
problem here is that format options are constructed in this order:
delimiter-> null -> escape -> quote(csv) -> [header] -> [fill_missing_field]
->[force_not_null] ->[force-quote] -> [newline]. The options in the square
brackets are optional, so the compare sql will not end with '%'.
This pr fix the incorrect reuse table by …

Fix gpload with header and reuse_tables bug.

---

contrib/pg_upgrade/greenplum/check_gp.c
contrib/pg_upgrade_support/pg_upgrade_support.c
src/backend/parser/parse_coerce.c
src/test/regress/expected/gp_create_view.out
src/test/regress/expected/gp_types.out
src/test/regress/expected/gp_types_optimizer.out
src/test/regress/expected/matview.out
src/test/regress/expected/matview_optimizer.out
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/expected/with.out
src/test/regress/sql/gp_create_view.sql
src/test/regress/sql/gp_types.sql
src/test/regress/sql/matview.sql
src/test/regress/sql/subselect.sql
src/test/regress/sql/with.sql

Commit 951f817e9b4 "Coerce unknown-type literals to type text instead of
cstring" has an issue that it processed outfunc and infunc directly,
which made Greenplum have no chance to do an unknown-to-text-to-cstring
cast. It errors out, even panics, in some cases since the data type
don't match.
The better solution is still coercing unknown-type literals to type
cstring, but hiding it. Check out the test case to see what it fixes.

6X: Coerce unknown-type literals to type cstring, but hide it

---

gpdb-doc/dita/admin_guide/ddl/ddl-tablespace.xml
gpdb-doc/dita/install_guide/migrate.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLESPACE.xml
src/bin/pg_rewind/pg_rewind.c

Tablespaces in different locations are not supported for a primary-mirror pair. This is different from filespaces so it has caused some confusion among customers.
I have edited the following 2 sections to add a warning about it:
https://mireia-tablespace.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/ddl/ddl-tablespace.html
https://mireia-tablespace.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/sql_commands/CREATE_TABLESPACE.html
https://mireia-tablespace.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/migrate.html
For the second link I didn't include it in a note element since there is a Notes section on that page. Let me know if this makes sense.
There is another pending PR to update the Release Notes for GPDB 6.0.
This PR should be merged to master and cherrypicked to 6.x.

Docs: Tablespaces note for primary-mirror pair

---

src/backend/executor/execQual.c
src/test/isolation2/expected/eval_record.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/eval_record.sql

When we eval a RECORD for the projection, we'll use the slot's type ID info.
It's likely that the slot's type is also RECORD; if so, make sure it's been
"blessed" (assign_record_type_typmod), so that the Datum can be interpreted
later. Because some plan trees may return different slots at different times,
we should make sure we do for all of them. See assign_record_type_typmod in
ExecEvalWholeRowFast for more details.
6X and master don't have this issue since they already do the same fix
in ExecEvalWholeRowVar and ExecEvalWholeRowFast.

[5X Only]Don't forget to assign typmod for RECORD type during eval

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Materialize is not a projection node, and thus must use the target list
of its child. Previously, when generating a materialize node for a shared
scan producer, it used the requested columns from the parent, which
worked in most cases. However, in other cases, the requested columns did
not match the columns projected by the materialize's child, causing Orca to generate a
materialize node that projects. This caused a failure during execution
with 'Material operator does not support projection' due to a check at https://github.com/greenplum-db/gpdb/blob/6X_STABLE/src/backend/executor/nodeMaterial.c#L360
Now, we ensure the materialize uses the child's target list, and let the shared scan project different columns if needed.

Ensure materialize does not project in Orca

---

src/backend/cdb/motion/ic_tcp.c

Previously, the result of `select()` system call and `errno` set by it was checked after performing several function calls, including checking for interrupts and `checkForCancelFromQD`.  That made it very likely for `errno` to change, losing the original value that was set by the `select()`.
This patch fixes it so that the `errno` is checked immediately after the system call.  This should address intermittent failures in CI with error message like this:
```
"ERROR","58M01","interconnect error: select: Success"
```
This patch would have made the following CI failure easier to diagnose: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE_without_asserts/jobs/icw_planner_ictcp_centos6/builds/991

[6X backport] Check errno as early as possible

---

src/backend/commands/vacuum.c
src/test/regress/expected/incremental_analyze.out
src/test/regress/sql/incremental_analyze.sql

If for a column attstattarget is set to 0, it should not be considered
while evaluating if the stats could be merged for the root. The user has
specifically disabled stats collection on that column, so leaf stats
merge should proceed based on the other columns.

Exclude columns which has attstattarget=0 for analyzing stats merge

---

src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c

_outSortBy and _readSortBy are mismatch obviously, adjust them to be
consistent.

Fix SortBy serialize/deserialize problem

---

src/backend/cdb/cdbmutate.c
src/backend/cdb/cdbsetop.c
src/backend/optimizer/path/allpaths.c
src/backend/optimizer/plan/createplan.c
src/backend/optimizer/plan/planagg.c
src/backend/optimizer/plan/planner.c
src/backend/optimizer/prep/prepunion.c
src/include/cdb/cdbmutate.h
src/include/cdb/cdbsetop.h
src/test/regress/expected/rpt.out
src/test/regress/sql/rpt.sql

Set correctlocus type for gather motion since if we operate(join, set
operation, etc.) replicated table with catalog table, we may scan the
replicated table on entry DB, but entry DB does not contain data for
replicated table.
The fix logic is to set the correct locus type for the motion node,
so when we try to optimize out motion node in apply_motion_mutator,
it shouldn't remove it.
This fixed the issue: https://github.com/greenplum-db/gpdb/issues/11945

[6X] Correct locus type for replicated table's upper gather motion node 

---

src/backend/executor/execMain.c

Inside targetid_get_partition(), the parentInfo->ri_partition_hash named
"Partition Result Relation Hash" was created under the TopMemoryContext;
CloseResultRelInfo() only freezes it without calling hash_destroy().
Long running backend processes (e.g. pgpool connections) might leak a
large amount of memory into the partition result hash context, blowing
up vmem memory usage.
Fix this by creating the context under the estate->es_query_cxt.

Create Partition ResultRel Hash table under the per query context

---

src/backend/cdb/cdbmutate.c
src/test/regress/expected/bfv_planner.out
src/test/regress/sql/bfv_planner.sql

For CTAS plans, general and segmentGeneral locus implies that if the corresponding
slice is executed in many different segments should provide the same result
data set. If the segmentGeneral and general locus path contain volatile
functions they lose the property and cannot be treated as *general.
So adjust the plan in apply_motion when the query is used in CTAS.
This is the continued fix base on https://github.com/greenplum-db/gpdb/pull/10418.

[6X]Correct CTAS plan for general & segmentGeneral path with volatiole functions

---

contrib/pg_upgrade_support/deprecated_objects.c

This PR consists of 3 separate fixes to deprecated object detection for pg_upgrade --check.
It is one PR for review atomicity. Please review individually.
Tests for the deprecated column check can be found in: https://github.com/greenplum-db/gpupgrade/pull/563

pg_upgrade_support: Multiple fixes to deprecated object detection

---

src/backend/utils/misc/guc.c

These GUCs are inherited from PostgreSQL, but are not relevant for
GPDB. Hence, mark these GUCs as GUC_NO_SHOW_ALL to avoid confusion
when seen in GUCs show all list. (I didn't go over all the GUCs yet, these are few
which received complaints from field about hence marking them in first iteration.
We will have to go over all the GUCs and stamp them properly.)
For master branch, we need to separately before the release go over all the
GUCs and mark them accordingly.

Mark GUCs not relevant to GPDB as GUC_NO_SHOW_ALL

---

src/backend/utils/mmgr/portalmem.c
src/test/regress/expected/resource_queue.out
src/test/regress/sql/resource_queue.sql

When creating a portal, we should assign the portal->queueId with
GetResQueueId() not only for master, but also for segments. Or,
resqueue's CPU priority won't take effects.
Co-authored-by: wuchengwen <wcw190496@alibaba-inc.com>
(cherry picked from commit 5490a34bac5133c05ad01ca1bf5815b0a94ecbb2)

[Backport6] Fix resqueue's CPU priority didn't take effects in segments (#11234)

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature

**cherry-pick** [12198](https://github.com/greenplum-db/gpdb/pull/12198)
Mirrors with **recovery.conf** file display empty status after pg_rewind
call during incremental recovery. pg_rewind is not required in this
scenario as per the existing design and replication needs to be handle by
WAL. As empty status creates confusion at the user end, this commit will
introduce valid status **skipping pg_rewind on mirror as recovery.conf is present**
It also changes existing recoverseg message from **Running pg_rewind on required
mirrors** to **Running pg_rewind on failed segments**

[6X backport] gprecoverseg: show valid status for mirror with no pg_rewind

---

src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/libnaucrates/include/naucrates/md/IMDCast.h
src/backend/gporca/libnaucrates/src/md/CMDCastGPDB.cpp
src/include/gpopt/translate/CTranslatorDXLToScalar.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

ORCA already supported CoerceViaIO casts when they're explicit in the
query. This commit expands their usage for implicit casts and adds
handling for them in subplan test exprs during DXL to PlStmt
translation.
Also, refactor code in TranslateDXLSubplanTestExprToScalar(). This 
commit makes the code easier to extend for other cast types; and
sets inputcolid and opcollid in op_expr, which were previously left
unset causing an ERROR on execution.
Please review the two commits separately - that'll be easier.

Support implicit CoerceViaIO casts in Subplan test expressions in ORCA (6x)

---

src/backend/postmaster/autostats.c
src/backend/storage/lmgr/lmgr.c
src/backend/utils/misc/faultinjector.c
src/backend/utils/resscheduler/resqueue.c
src/include/utils/faultinjector.h
src/test/isolation2/expected/resource_queue_deadlock.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue_deadlock.sql

When process tries to release the resource queue lock after deadlock
error, the process was not properly holding the partitionLock and
ResQueueLock. This could lead to shared memory corruption (when
another process goes to release its resource queue locks) and later
cause segmentation faults. Fix the issue by making sure we hold both
locks before touching the shared memory queue. We also introduce a
validation check to PANIC when corruption of the lock table is
encountered.
This commit contains code inspired from Github user dh-cloud's PR:
https://github.com/greenplum-db/gpdb/pull/12185
This commit also contains test code inspired from Github user
dreamedcheng's PR:
https://github.com/greenplum-db/gpdb/pull/9652
Co-authored-by: dh-cloud <60729713+dh-cloud@users.noreply.github.com> …

Acquire proper locks when releasing resource queue locks from lock table

---

src/backend/storage/file/fd.c
src/include/storage/fd.h
src/test/isolation2/input/workfile_mgr_test.source
src/test/isolation2/output/workfile_mgr_test.source
src/test/isolation2/workfile_mgr_test.c

Please see individual commit messages for details.  This patch removes `OpenNamedTemporaryFile()` interface that was used only by workfile_mgr test.  The workfile_mgr_test.c still contains several merge fixmes and disabled code, but this PR is one step forward.

Cleanup workfile_mgr isolation2 test

---

src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/libnaucrates/src/md/CMDRelationGPDB.cpp
src/test/regress/expected/qp_dropped_cols.out
src/test/regress/expected/qp_dropped_cols_optimizer.out
src/test/regress/sql/qp_dropped_cols.sql

ORCA for GPDB6 and older versions assumes that the root and leaf
partitions have the same underlying column structure. This assumption
can be broken when an exchange partition with or without same dropped
columns as root is inserted into the partition table. Further
complicating the matter is that ORCA always uses the root partition to
construct index metadata. If ORCA detects a mismatch in the index and
relation metadata, then it will not consider an index plan.
This PR mainly addresses the scenarios which can lead to a crash 
for exchange partition having mismatched dropped column layout with root.
There is another scenario dealing with exchange partition and mismatched dropped columns 
where ORCA generates a plan that errors out during execution that is not addressed 
in this PR (when …

Fix crash in ORCA if root and leaf dropped column layouts mismatch

---

src/backend/gporca/libnaucrates/src/statistics/CUpperBoundNDVs.cpp

This patch adds space between title text and UpperBoundNDVs value in logging message so these entries don't stick together in output.

Typo fix in logging message of UpperBoundNDVs module

---

src/backend/commands/vacuum.c
src/backend/executor/execMain.c
src/backend/parser/parse_clause.c
src/backend/storage/lmgr/README-partition
src/backend/utils/cache/plancache.c
src/test/isolation2/expected/concurrent_vacuum_with_delete.out
src/test/isolation2/expected/gdd/dml_locks_only_targeted_table_in_query.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/concurrent_vacuum_with_delete.sql
src/test/isolation2/sql/gdd/dml_locks_only_targeted_table_in_query.sql
src/test/regress/expected/partition_locking.out

The problem is ERROR "tuple concurrently updated" occurs when running
delete qeury during ETL as below error. When we concurrently execute an
UPDATE/DELETE statement and a VACUUM statement on a partition ao table.
UPDATE/DELETE statement is likely to get an out-of-date snapshot after

[6X FIX]Fix a bug of concurrently executing UPDATE/DELETE with VACUUM on a partition ao table

---

src/backend/parser/parse_clause.c
src/backend/utils/cache/plancache.c
src/test/isolation2/expected/cached_plan.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/cached_plan.sql

Previous commit 99fbc8ea9496 does not init ListCell correctly,
it may lead to coredump. Actually prod 6X pipeline find it.
Besides, function `find_all_inheritors` will also return the
parent Oid, so we should skip it in the foreach loop.
This commit fixes the above issue.
I find this in https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/icw_planner_icproxy_centos6/builds/392 and https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE_without_asserts/jobs/icw_gporca_centos7/builds/1005
The bug (mistake) is so obvious that we do not find it when reviewing and most of the pipeline is OK. This really surprises me.
The coredump's backtrace is:
```
#0  0x00007fc9768a26ab in raise () from /lib64/libpthread.so.0
#1  0x0000000000c9eeb0 in …
```

(6x only) Fix unlock leaf partitions.

---

src/backend/access/aocs/aocs_compaction.c
src/backend/access/aocs/aocsam.c
src/backend/access/appendonly/appendonly_compaction.c
src/backend/access/appendonly/appendonlyam.c
src/backend/access/appendonly/appendonlywriter.c
src/test/isolation2/input/uao/snapshot_eof.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/snapshot_eof.source

In 5X a snapshot satisfies "now" was used when transaction extracted AO/AOCO segment file eof. In other words "now" allowed us to see all committed transactions. When this code was ported to 6X a catalog snapshot was chosen for this purpose. As a result we don't see committed transactions that started after the snapshot has been taken. As a result a transaction can change segment file eof between the moment a snapshot was taken and an exclusive file segment lock was hold. So AO/AOCO in 6X suffers from data corruption in concurrent DML queries.
This PR consists of two commits. The first one demonstrates the problem (all added tests should fail). The second one fixes the problem using snapshot self instead of catalog snapshot - it allows us to see all committed data as "now" in 5X did.
5X …

Wrong snapshot for EOF corrupts data in AO/AOCO

---

src/backend/cdb/cdbpath.c
src/test/regress/expected/rpt_joins.out
src/test/regress/sql/rpt_joins.sql

`cdbpath_create_motion_path` function doesn't check subpath's params Relids. When Path contains index scan with quals it leads to segfault.
Fix adds a few additional checks of can motion node be generated atop of subpath. Additional regression test included.
Related to issue #[12228](https://github.com/greenplum-db/gpdb/issues/12228). Partial backport of 9cc1da6 (#[10012](https://github.com/greenplum-db/gpdb/issues/10012)).

Check if subpath can do motion.

---

gpMgmt/bin/gpexpand

This issue also exsits in 6X_STABLE, not only in master branch, as described below.
When running gpexpand utility to expand the segments, If the process receives a signal.SIGTERM or signal.SIGHUP, the sig_handler function will have an error---TypeError: sig_handler() takes exactly 1 argument (2 given).
As a result, we can not clean up correctly for gpexpand.

[6X] Fix TypeError for sig_handler function in gpexpand  #11766

---

gpMgmt/bin/analyzedb

pg_magic_oid.h:
> #define FirstNormalObjectId	16384
16384 is the first normal oid, analyzedb should not skip it.
When running pivotalguru/TPC-H on a fresh Greenplum cluster
inside containers, we met:
```
$ psql
postgres=# select oid,* from pg_namespace;
oid  |      nspname    | nspowner |  nspacl
-------+-----------------+----------+-----------
16384 | tpch            |       10 |
$ analyzedb -d postgres -s tpch --full -a -v
[WARNING]:-There are no tables or partitions to be analyzed. Exiting...
```
Fix: replace `relnamespace > 16384` with `relnamespace >= 16384`

[6X backport] analyzedb - include FirstNormalObjectId

---

gpdb-doc/dita/ref_guide/sql_commands/COMMENT.xml

The following options were missing:
TEXT SEARCH CONFIGURATION object_name |
TEXT SEARCH DICTIONARY object_name |
TEXT SEARCH PARSER object_name |
TEXT SEARCH TEMPLATE object_name |

Added mission options to COMMENT

---

src/backend/access/external/url_curl.c

In order to make the gpdb5 client able to connect to gpdb6 gpfdist
server using ssl, we have to delete the old cipher
TLS_RSA_WITH_AES_128_CBC_SHA. In this way, gpdb5 client can choose
a compatible protocol with latest version of gpfdist and also be
able to connect with version 5 gpfdist(using tls1.0 protocol).

Delete TLS_RSA_WITH_AES_128_CBC_SHA for gpdb5 clients.

---

src/bin/gpfdist/gpfdist.c
src/bin/gpfdist/regress/input/gpfdist_ssl.source
src/bin/gpfdist/regress/output/gpfdist_ssl.source

Disable tls1.0 and tls1.1 protocol for gpfdist for security reasons.

---

gpMgmt/bin/gppylib/commands/unix.py

It can not get a list of postgres processes in the kill_9_segment_processes function when the gpdb system is running. Thanks for your review.
Please see the log below : 
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*port\s*5434" | awk '{print $2}'
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*5434" | awk '{print $2}'
8873
8876
8877
8878
8879
8881
8894
8896
8897
8941
[gpadmin@mdw ~]$ ps ux | grep "[p]ostgres:\s*5434" 
gpadmin  8873  0.0  0.0 239984  5264 ?        Ss   Jan16   0:02 postgres:  5434, master logger process   
gpadmin  8876  0.0  0.0 477124  8500 ?        Ss   Jan16   0:00 postgres:  5434, checkpointer process   
gpadmin  8877  0.0  0.0 477012  4960 ?        Ss   Jan16   0:00 postgres:  5434, writer process   
gpadmin  8878  0.0  0.0 477012  8648 ?        Ss   Jan16   0:00 …

Fix that kill_9_segment_processes can not get a list of processes to kill.

---

src/backend/cdb/cdbllize.c
src/backend/cdb/cdbpath.c
src/test/regress/expected/bfv_planner.out
src/test/regress/expected/bfv_planner_optimizer.out
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/bfv_planner.sql
src/test/regress/sql/rpt.sql

follow up #10418.
CTAS has an additional code path that will add a replicated locus on the top of the current node.
but the code path lacks some volatile function check, which will produce an incorrect plan. The incorrect
plan will execute the volatile function more times than expected.
```
-- the old plan
> explain (costs off) create table rpt_ctas as select random() from generate_series(1, 10) distributed replicated;
+-------------------------------------+
| QUERY PLAN                          |
|-------------------------------------|
| Function Scan on generate_series    |
| Optimizer: Postgres query optimizer |
+-------------------------------------+
> explain (costs off) create table rpt_ctas as select a from generate_series(1, 10) a group by a having sum(a) > random() distributed …
```

correct plan for CTAS with volatile functions.

---

gpdb-doc/dita/utility_guide/ref/gpconfig.xml

As of 6.x, users cannot pass in to gpconfig -c values enclosed in single quotes for GUCs of vartype string.

DOCS: No single quotes around string GUCs for gpconfig -c

---

gpdb-doc/dita/ref_guide/modules/diskquota.xml

When editing the configuration parameter diskquota.naptime, database restart is required. Added a reference to indicate this.

Added reference to restart database

---

src/backend/cdb/cdbcopy.c
src/backend/cdb/cdbsreh.c
src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/commands/copy.c
src/include/cdb/cdbdispatchresult.h
src/interfaces/libpq/fe-protocol3.c
src/interfaces/libpq/libpq-int.h
src/test/regress/expected/gpcopy_dispatch.out
src/test/regress/sql/gpcopy_dispatch.sql

`Copy rowcount` might have a wrong number when COPY FROM. This happens
if SREH or BEFORE-TIGGER has rejected rows on QEs.
PR #9932 has already added a test, but its regression result
did not contain the completion tag:
```sql
DROP TABLE IF EXISTS partdisttest;
CREATE TABLE partdisttest(id INT, t TIMESTAMP, d VARCHAR(4))
DISTRIBUTED BY (id)
PARTITION BY RANGE (t)
(
PARTITION p2020 START ('2020-01-01'::TIMESTAMP) END ('2021-01-01'::TIMESTAMP),
DEFAULT PARTITION extra
);
COPY partdisttest FROM STDIN LOG ERRORS SEGMENT REJECT LIMIT 2;
1	'2020-09-24'	abcde
1	'2020-09-24'	abc
\.
COPY 2
```
The correct completion tag should be `COPY 1`, e.g. COPY on **QD**:
```
COPY partdisttest(id, d, t) FROM STDIN LOG ERRORS SEGMENT REJECT LIMIT 2;
1	abcde	'2020-09-24'
1	abc	'2020-09-24'
\.
COPY 1
``` …

Fix possible wrong completionTag in Copy From

---

gpMgmt/bin/gpload_test/Makefile

this pr fix pipeline fail in #12301
modify gpload test Makefile, recognize the system os, skip gpload test if in centos6 and ubuntu

skip gpload test in centos6

---

gpMgmt/bin/gpload_test/Makefile
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_legacy.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_options.py
gpMgmt/bin/gpload_test/gpload2/query302.ans
gpMgmt/bin/gpload_test/gpload2/query39.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

1. skip gpload test in Red Hat for gpdb6-oracle7-test task
judge the os in gpload test Makefile, if os is red hat, than skip gpload test
2. add test case 39
case 39 is added by Zhaorui in pr #12166 (case number is 47 in his pr), and missed when refactor gpload test
3. delete 'ignore drop' command when compare ans and out files
drop information is ignored when comparing ans and out files in local test. While in remote test it is not ignored. So we delete the ignore command in local test to make the ans files same in local and remote tests.

Fix 6x pipeline fail

---

src/backend/optimizer/plan/createplan.c
src/test/regress/expected/union_gp.out
src/test/regress/sql/union_gp.sql

Most of the calls of `add_to_flat_tlist_junk` seem not necessary,
since if there are no sub plans in the hashExpr, it means all the
elements must come from the target list, then there's no need to
check the target list again and add it back from hashExpr to the
target list.
Normally add extra junk target entry is ok, but for issue:
https://github.com/greenplum-db/gpdb/issues/12031.
When the node which add junk target entry is under Append node and
with Motion on top of it, the targetlist of these nodes are not same,
this will cause the Motion node recognizes tuple with wrong target
entries, and lead to wrong results.
The plan looks like:
Motion
--> Append
-----> Subplan1
-----> Subplan2
Co-authored-by: bbbearxyz <mzj1996@mail.ustc.edu.cn>

[6X]Remove unnecessary calls for add_to_flat_tlist_junk function

---

README.macOS.bash

Without setting the correct LC_CTYPE, demo cluster creation fails in Master

Fix Readme for Mac OS

---

src/backend/storage/lmgr/lock.c
src/backend/utils/gdd/gddfuncs.c

The fix is from github issue 11923, which is about some incorrect behavior due to that holdTillEndXact is not initialized:
https://github.com/greenplum-db/gpdb/issues/11923
Basically the change includes:
1. Setting holdTillEndXact to false in the initialization block.
2. Adding an assert to check if holdTillEndXact is false when a lock with type LOCKTAG_RELATION_EXTEND is released.
No extra test case was added, because the change is related to all actions requiring a lock, which have been covered by existing tests.

init holdTillEndXact and add asserts

---

src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp
src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
src/backend/gporca/server/CMakeLists.txt

Fix Cardinality estimation for not well defined histograms
Consider the below example:
```
create table bar (a int, b int);
insert into bar select i, i from generate_series(1,1000)i;
analyze bar;
EXPLAIN WITH  CTE AS  (SELECT a::int8, b  FROM bar) SELECT 1 FROM CTE WHERE (a <> 1 OR a = 1 AND b <> 101) AND (a<>1 or a = 1);
QUERY PLAN                                                                
------------------------------------------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.01 rows=2 width=4)
->  Result  (cost=0.00..431.01 rows=1 width=4)
->  Result  (cost=0.00..431.01 rows=1 width=1)
Filter: (((((a)::bigint) <> 1) OR ((((a)::bigint) = 1) AND (b <> 101))) AND …
```

Fix Cardinality estimation for not well defined histograms

---

src/backend/commands/vacuum.c
src/test/regress/expected/vacuum_gp.out
src/test/regress/sql/vacuum_gp.sql

For GPDB on coordinator, vac_update_relstats() gets called
twice. First in regular flow of vacuum via lazy_vacuum_rel() and next
time after receiving values for reltuples and relpages from segments
via vac_update_relstats_from_list() → vac_update_relstats(). Without
CommandCounterIncrement() added as part of this commit, second call to
vac_update_relstats() reads stale value of row from pg_class and hence
overwrites the effect (mostly update to relfrozenxid) performed by
first calls update.
Added test to showcase and validate the behavior.

Vacuum should read fresh version of pg_class for update

---

src/backend/access/transam/xlog.c
src/backend/cdb/cdbtm.c
src/test/isolation2/expected/checkpoint_dtx_info.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/checkpoint_dtx_info.sql

WAL insert and in-memory state change for XLOG_XACT_DISTRIBUTED_COMMIT
is protected by delayChkpt. This makes the operation atomic from
checkpoint perspective. Hence, getDtxCheckPointInfo() is expected to
be called only after GetVirtualXIDsDelayingChkpt() to ensure no middle
state is seen.
Before this fix, getDtxCheckPointInfo() was called before
GetVirtualXIDsDelayingChkpt(), resulted in situation where WAL insert
for XLOG_XACT_DISTRIBUTED_COMMIT was performed but in-memory state was
not changed. If CHECKPOINT happened during this time window,
checkpoint record missed to transaction in
DTX_STATE_INSERTED_COMMITTED state. When recovering from this
checkpoint record, the coordinator will think that these distributed
transactions are orphaned and will execute `rollback prepared`.
So we move …

[Backport to 6X] Fix transaction may be committed on coordinator, aborted on segments

---

src/backend/gporca/data/dxl/minidump/DeleteRandomDistr.mdp
src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTable.mdp
src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTableJoin.mdp
src/backend/gporca/data/dxl/minidump/SelfUpdate.mdp
src/backend/gporca/data/dxl/minidump/UpdateRandomDistr.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
src/backend/gporca/libgpopt/src/operators/CPhysical.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalDML.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
src/test/regress/expected/bfv_dml.out
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/expected/qp_subquery_optimizer.out
src/test/regress/sql/bfv_dml.sql

Previously, we always added a redistribute motion on a DELETE on a randomly
distributed table. Now, we allow randomly distributed specs to match iff
gp_segment_id ColRef match.
Updated CDistributionSpecRandom::Matches to check whether two random distributions
have the same gp_segment_id and return true in that case. This commit re-derives
gp_segment_id through ptabdesc.
Added test cases to src/test/regress/sql/bfv_dml.sql and updates expected with
the new test cases.
```
create table foo (a int, b int) distributed randomly;
create table bar(a int, b int);
explain delete from foo where foo.a=1;
QUERY PLAN
Delete on foo  (cost=0.00..431.03 rows=1 width=1)
->  Seq Scan on foo foo_1  (cost=0.00..431.00 rows=1 width=18)
Filter: …
```

Improve performance of DELETEs on randomly distributed tables in ORCA.

---

src/backend/gporca/data/dxl/minidump/DeleteRandomDistr.mdp
src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTable.mdp
src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTableJoin.mdp
src/backend/gporca/data/dxl/minidump/SelfUpdate.mdp
src/backend/gporca/data/dxl/minidump/UpdateRandomDistr.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
src/backend/gporca/libgpopt/src/operators/CPhysical.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalDML.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
src/test/regress/expected/bfv_dml.out
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/expected/qp_subquery_optimizer.out
src/test/regress/expected/update_gp_optimizer.out
src/test/regress/sql/bfv_dml.sql

Previously, we always added a redistribute motion on a DELETE on a randomly
distributed table. Now, we allow randomly distributed specs to match iff
gp_segment_id ColRef match.
Updated CDistributionSpecRandom::Matches to check whether two random distributions
have the same gp_segment_id and return true in that case. This commit re-derives
gp_segment_id through ptabdesc.
Added test cases to src/test/regress/sql/bfv_dml.sql and updates expected with
the new test cases.
```
create table foo (a int, b int) distributed randomly;
create table bar(a int, b int);
explain delete from foo where foo.a=1;
QUERY PLAN
Delete on foo  (cost=0.00..431.03 rows=1 width=1)
->  Seq Scan on foo foo_1  (cost=0.00..431.00 rows=1 width=18)
Filter: …
```

Improve performance of DELETEs on randomly distributed tables in ORCA (6X)

---

src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterIndexNLJoin.h
src/backend/gporca/libgpopt/src/engine/CEngine.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterIndexNLJoin.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Previously, CPhysicalLeftOuterIndexNLJoin requested any distribution on the
inner child, and threw an exception (and fell back to planner) if the inner
table was randomly distributed to prevent incorrect results.  This commit adds
CPhysicalLeftOuterIndexNLJoin::EpetDistribution to prohibit certain plans so we
do not reach an invalid state (i.e. reject random distributions on the inner
child without creating a new distribution spec entirely).
This commit adds a specific case where `EpetDistribution` is called if we are
using `CPhysicalLeftOuterIndexNLJoin` (normally, an operation with
`CDistributionSpecAny` will not have `EpetDistribution` called, so we made an
exception specifc to this operation) and adds test cases to `gporca` to verify the
behavior is correct. This commit also adds …

Update distribution spec for inner child of left outer index NL join to handle random distributions

---

src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalLeftOuterIndexNLJoin.h
src/backend/gporca/libgpopt/src/engine/CEngine.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalLeftOuterIndexNLJoin.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Previously, CPhysicalLeftOuterIndexNLJoin requested any distribution on the
inner child, and threw an exception (and fell back to planner) if the inner
table was randomly distributed to prevent incorrect results.  This commit adds
CPhysicalLeftOuterIndexNLJoin::EpetDistribution to prohibit certain plans so we
do not reach an invalid state (i.e. reject random distributions on the inner
child without creating a new distribution spec entirely).
This commit adds a specific case where `EpetDistribution` is called if we are
using `CPhysicalLeftOuterIndexNLJoin` (normally, an operation with
`CDistributionSpecAny` will not have `EpetDistribution` called, so we made an
exception specifc to this operation) and adds test cases to `gporca` to verify the
behavior is correct. This commit also adds …

Update distribution spec for inner child of left outer index NL join to handle random distributions (6X)

---

gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature

Tests performing gprecoverseg rebalance should wait to have the
segments in synchronized state. This makes sure following tests starts
with expected state.
CI many times encountered flaky behavior as next test call "stop all
primaries". If the segments were not in sync and primaries are stopped
creates double fault situation.
Ideally, stop all primaries or mirrors test function should have check
for segments are in-sync before stopping. Though that's patch for some
other day.

Fix flaky gprecoverseg behave test

---

src/test/isolation2/sql_isolation_testcase.py

When running isolation2 tests on MacOS using Python 3.8+, all tests
fail with the following error:
```
FAILED: cannot pickle '_io.TextIOWrapper' object
```
This is due to a change introduced in Python 3.8 where the
multiprocessing start method default was changed from 'fork' to
'spawn' for MacOS. To avoid a lengthy refactor, simply just set the
method to 'fork' (the Unix default) when running isolation2 tests on
MacOS with Python 3.8+.
Python3 Documentation:
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

Fix isolation2 test framework for MacOS using Python 3.8+

---

gpMgmt/bin/Makefile

Mentioned mistake makes impossible to proceed install
with custom DESTDIR
There are recommendations about PyGreSQL and Postgres components from system repositories:
1. https://github.com/greenplum-db/gpdb/blob/c3846b85afab67496717a348b69283367f38066e/python-dependencies.txt#L2
2. https://github.com/greenplum-db/gpdb/blob/c3846b85afab67496717a348b69283367f38066e/README.CentOS.bash#L28-L31
But gpdb builds PyGreSQL from its submodule with python modules now. Do we really need these dependencies?

fix missing DESTDIR in pygresql Makefile target

---

gpdb-doc/dita/install_guide/migrate.xml
gpdb-doc/dita/ref_guide/deprecated-objects.xml
gpdb-doc/dita/ref_guide/ref_guide.ditamap

new PR. cleaner history, same info as https://github.com/greenplum-db/gpdb/pull/12302/files but branched from 6X_STABLE
Created new page as requested by Nirali and gpupgrade team.
Plan is to decommission https://gpdb.docs.pivotal.io/upgrade/1-0/guc-changes-5to6.html when all info is migrated in the gpdb docs upgrade/migrate sections.
Tracker: https://www.pivotaltracker.com/story/show/178371453

Docs - new deprecated objects page and small fixes for migrate page

---

gpMgmt/bin/gppylib/operations/rebalanceSegments.py

It should format `failed_count` integer, but forgot.

Display the number of failed segments in gprecoverseg -r

---

src/backend/access/transam/xlog.c
src/backend/storage/file/fd.c
src/bin/pg_basebackup/pg_basebackup.c
src/bin/pg_rewind/pg_rewind.c
src/include/storage/fd.h
src/test/isolation2/expected/ao_same_trans_truncate_crash.out
src/test/isolation2/sql/ao_same_trans_truncate_crash.sql

This is the gp6 version of https://github.com/greenplum-db/gpdb/pull/12065
The PR includes 5 patches. Three of them are backported patches. Other two patches are:
(one for pg_basebackup and another is for pg_rewind).
```
commit 764abaa2703e60d8c51511c6eadf648708728893
Author: Paul Guo <paulguo@gmail.com>
Date:   Thu May 27 11:38:49 2021 +0800
Do target pgdata directory sync at the end of pg_basebackup.
Previously we did not do that. Upstream added this later, for us this should be
fine previously since we do fsync during startup finally, but now that we skip
fsync for this scenario during startup, let's do fsync in pg_basebackup.
```
And
```
commit f6b7c50ee8d4391c2d23088c38bb685559cb09fc
Author: Paul Guo <paulguo@gmail.com>
Date:   Thu May 27 10:16:46 2021 +0800
Backport fsync_fname() …
```

[6x backport and additional fixes] fsync related optimization for gpdb recovery

---

src/test/regress/input/autovacuum-segment.source
src/test/regress/input/autovacuum-template0-segment.source
src/test/regress/input/autovacuum.source
src/test/regress/output/autovacuum-segment.source
src/test/regress/output/autovacuum-template0-segment.source
src/test/regress/output/autovacuum.source

Based on investigation from Hubert and Asim in referenced discussion,
if multiple workers are launched for autovacuum, then the test can
exhibit flaky behavior, as we can only reliable wait for pre-known
number of fault hits not a dynamic number.
Hence, to make the test reliable adding retry to check if autovacuum
performed the job or not for 5 minutes else fail. Picked 5 minutes as
timeout as on CI we have seen cases where it took close to 2 mins time
to complete the autovacuum for regression database.
Discussion:
https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/8QNIiwtjh2U/m/TSGeLp8hBAAJ

Add retry loop in autovacuum tests to avoid flakiness

---

src/test/regress/expected/bfv_dml.out
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/sql/bfv_dml.sql

The case is flaky because of the table is defined as randomly
distributed and then load data into it which will lead to
random cost and different plans.
This commit fixes the flakiness by firstly define the table
to hash distributed and then load data into it. This will ensure
us a stable data distribution. Then we use alter table to change
the policy of this table to randomly without moving the data.
I find some jobs fail in 6x pipeline:
* https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/icw_planner_oracle7/builds/436
* https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE_without_asserts/jobs/icw_planner_ictcp_centos6/builds/1030
* https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE_without_asserts/jobs/icw_gporca_icproxy_centos …

(6x only) Fix flaky test case in bfv_dml.

---

src/backend/utils/gdd/gddfuncs.c

Commit 036a31bdd24 refactor the function lockIsHoldTillEndXact
but forgot to remove the unused variable. Just remove it to
slient compiler.

Fix compiler warning for unused variable.

---

src/backend/cdb/cdbtm.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/executor/execScan.c
src/backend/tcop/postgres.c
src/include/cdb/cdbgang.h
src/test/isolation2/expected/orphan_temp_table.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/orphan_temp_table.sql

When the backend process panics on the segment, temp tables should be dropped
on the coordinator. Before this, QD only resets the gang upon detecting the QE crash
but not dropping temp tables because it's still in a transaction block at that point.

Fix orphan temp table on the coordinator

---

src/test/regress/expected/bfv_dml.out
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/sql/bfv_dml.sql

The case is flaky because of the table is defined as randomly
distributed and then load data into it which will lead to
random cost and different plans.
This commit fixes the flakiness by firstly define the table
to hash distributed and then load data into it. This will ensure
us a stable data distribution. Then we use alter table to change
the policy of this table to randomly without moving the data.
----------------
It seems that on master branch's pipeline we do not encounter such flakiness.
Also in last pr for 6x, I miss later SQL, we should add them later.

Fix flaky test case in bfv_dml.

---

src/test/regress/expected/bfv_dml.out
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/sql/bfv_dml.sql

The case is flaky because of the table is defined as randomly
distributed and then load data into it which will lead to
random cost and different plans.
This commit fixes the flakiness by firstly define the table
to hash distributed and then load data into it. This will ensure
us a stable data distribution. Then we use alter table to change
the policy of this table to randomly without moving the data.
-----------------------------------
This PR first revert my previous commit https://github.com/greenplum-db/gpdb/commit/0cc730a51d4adc30136483cb44a9d9eaf4885610
and then a simply cherry-pick of the PR of master https://github.com/greenplum-db/gpdb/pull/12338

(6x backport) Fix flaky test case in bfv_dml.

---

src/backend/storage/lmgr/lock.c
src/backend/utils/gdd/gddfuncs.c

The fix is from github issue 11923, which is about some incorrect behavior due to that holdTillEndXact is not initialized:
Basically the change includes:
1. Setting holdTillEndXact to false in the initialization block.
2. Adding an assert to check if holdTillEndXact is false when a lock with type LOCKTAG_RELATION_EXTEND is released.
No extra test case was added, because the change is related to all actions requiring a lock, which have been covered by existing tests.
----------------
Cherry-pick https://github.com/greenplum-db/gpdb/commit/036a31bdd24226d7977ef780796e281750764b67 and https://github.com/greenplum-db/gpdb/commit/2145129d631ee1fee409f805296b16962818af14 from master to 6X.
I also squash the two commits into one.

(backport to 6x) Init holdTillEndXact and add asserts.

---

src/backend/optimizer/plan/planagg.c
src/test/regress/expected/gp_aggregates.out
src/test/regress/sql/gp_aggregates.sql

This is a regression caused by commit: 6ae9179dca7.
The refactor forget to consider agg on entryDB.
So fix the issue and add a test case to cover it.

[6X Only]Agg on entryDB shouldn't raise error

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/.gitignore
gpMgmt/bin/gpload_test/gpload2/query37.ans
gpMgmt/bin/gpload_test/gpload2/query44.ans
gpMgmt/bin/gpload_test/gpload2/query76.ans
gpMgmt/bin/gpload_test/gpload2/query77.ans

complete gpload error message when cannot create external table
Some  creation fail may be caused by standard_conforming_strings set to off,
We check the standard_conforming_strings in gpdb and if it is 'off' than advice clients to try again with standard_conforming_strings on.

complete gpload error message when cannot create external table

---

src/backend/cdb/cdbgroup.c
src/test/regress/expected/gp_aggregates.out
src/test/regress/sql/gp_aggregates.sql

grps_tlist for MppGroupContext may contains extra vars with the
group expression in some cases, for example subplan in group expression.
But for normal case it only contains group expression in grps_tlist.
We used to sure that there could only be one target entry in grps_tlist
for a group.
When we build the 3 stage agg and try to split the Aggref and find or
add target list into different Aggref stages with function `split_aggref`,
it'll match to wrong Vars in `AGGSTAGE_INTERMEDIATE` and `AGGSTAGE_FINAL`
stage.

[6X]Correct var mapping for 3 stage agg with group by expression

---

src/test/regress/expected/gp_aggregates.out
src/test/regress/sql/gp_aggregates.sql

Previous commit d87d5e6bf8eb9605d2349e938c813f0622cfccd7 use GUC
optimizer_enable_groupagg to force orca generate same plan with
planner for a test, but seems it can not guarantee this right now.

Stabilize the test resutls for gp_aggregates

---

src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp
src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
src/backend/gporca/server/CMakeLists.txt

Consider the below example:
```
EXPLAIN WITH  CTE AS
(SELECT c::int8, b  FROM badestimate1)
SELECT 1 FROM CTE WHERE c <> 1 OR c = 1 AND b <> 101;
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.13 rows=2 width=4)
->  Result  (cost=0.00..431.13 rows=1 width=4)
->  Result  (cost=0.00..431.13 rows=1 width=1)
Filter: ((c::bigint) <> 1 OR ((c::bigint) = 1 AND b <> 101)) AND ((c::bigint) <> 1 OR (c::bigint) = 1)
->  Result  (cost=0.00..431.13 rows=1 width=12)
->  Table Scan on badestimate1  (cost=0.00..431.08 rows=3334 width=8)
Optimizer status: PQO version 3.116.0
```
This histogram for c::int8 is not well defined, so while merging the
histograms due to …

[6X backport] Fix Cardinality estimation for not well defined histograms

---

src/backend/storage/ipc/procsignal.c

PROCSIG_WALSND_INIT_STOPPING is checked twice under
procsignal_sigusr1_handler, so remove the extra one and
also rearrange the check order to align with upstream.

Remove extra signal check in procsignal_sigusr1_handler

---

config/orca.m4
configure
gpAux/releng/releng.mk

Corresponding ORCA commits: (https://github.com/greenplum-db/gporca/pull/625)
Fix Cardinality estimation for union not well defined histograms

Bump ORCA version to 3.118.0

---

src/bin/pg_dump/pg_dump.c

This PR contains separate fixes to pg_dump's logic for dumping functions.
We discovered these issues while trying to upgrade a GPDB cluster with PXF.
Please review each commit separately.
Co-authored-by: Kalen Krempely <kkrempely@vmware.com>

6X: Ensure that pg_dump considers 5X when dumping functions

---

src/bin/pg_dump/pg_dump.c

This is a forward port of 6X_STABLE commit: bdad273 in order to
support upgrading extensions that install dependent functions under
pg_catalog in a 5X->7X+ upgrade path.
------------------------------------------------------------------------
This ensures that when pg_dump is invoked in binary_upgrade mode against
a 5X cluster during pg_upgrade, it collects and dumps the functions
under pg_catalog belonging to an extension.
We found this bug when we tried to upgrade PXF and PXF's functions
did not get dumped in binary upgrade mode. (PXF's functions are created
under pg_catalog)
This change in 6X should have accompanied the backport of the
extension machinery into 5X.
------------------------------------------------------------------------
Co-authored-by: …

Dump extension functions under pg_catalog for 5X

---

gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml

Docs are currently stating that SET STATISTICS option for ALTER TABLE can be set in the range 100 to 10000 (https://gpdb.docs.pivotal.io/6-16/ref_guide/sql_commands/ALTER_TABLE.html).
However PostgreSQL documentation states the range is 0 to 10000 and it can be proven by repro as well
https://www.postgresql.org/docs/9.4/sql-altertable.html

Set statistics parameter for alter table was incorrect

---

gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpcreateseg.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

gpinitsystem currently creates backout script on coordinator and on each segment, and then appends all the segment backout scripts to the coordinator backout script and we ask the user to run only that script.
If some of the gpcreateseg fail, the segment backout scripts aren't appended correctly in some cases, and the user has to manually cleanup those directories.
This change creates a single backout script early in gpinitsystem run, so even if anything fails later, we would always be able to cleanup all segment directories.

gpinitsystem: fix backout script creation

---

src/backend/gporca/data/dxl/minidump/CTE-Join-Redistribute-Producer.mdp
src/backend/gporca/data/dxl/minidump/CTE-NoPushProperties.mdp
src/backend/gporca/data/dxl/minidump/CTE-PushProperties.mdp
src/backend/gporca/data/dxl/minidump/CTE-volatile.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
src/backend/gporca/libgpopt/include/gpopt/base/CReqdPropPlan.h
src/backend/gporca/libgpopt/src/base/CCTEReq.cpp
src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
src/backend/gporca/libgpopt/src/base/COptimizationContext.cpp
src/backend/gporca/libgpopt/src/base/CReqdPropPlan.cpp
src/backend/gporca/server/CMakeLists.txt

After optimizing with the "natural" distribution spec of a CTE
producer, we try to translate the query's distribution spec to
the column of the producer and do another round of optimization.
This could lead to incorrect results when the query had a distribution
spec (including equivalent distribution specs) that came from multiple
CTE consumers, with some of these columns being equivalent because
of "=" predicates between them.
For example:
```
with cte as (select a,b from foo where b<10)
select * from cte x1 join cte x2 on x1.a=x2.b
```
On the query side, columns x1.a and x2.b are equivalent. We do NOT
want to get into a situation where we treat columns a and b of the
producer as equivalent.
For an explanation of how this works, see [this VLDB …

Fix distribution spec used for CTE producer requirement

---

config/orca.m4
configure
gpAux/releng/releng.mk

Corresponding commits in gporca: greenplum-db/gporca#626
Fix distribution spec used for CTE producer requirement

Bump ORCA version to 3.119.0

---

concourse/pipelines/gen_pipeline.py

This section was commented out in 69dc29b0754, but the commit message
doesn't reveal why this section was commented out.
The ability to fly a dev pipeline with a specific set of OSes help
reduce the turnaround time for dev pipelines (especially for components
such as gpupgrade that support a subset of the default OSes)

[5X] ci: Enable OS selection for dev pipelines

---

src/backend/postmaster/autovacuum.c

Issue is that get_namespace_name() can return NULL values when nspid no
longer exists in the cat cache and the tuple has been deleted from the
relation on disk. This can happen during the normal lifecycle of a tuple
in pg_namespace. And so without a NULL check, the strcmp call is at risk
of crashing autovacuum process.
Fix is to remove the offending calls altogether. Previously we treated
information_schema special in order to vacuum all tables in template0.
That allowed commit 379512a3fbf to keep parity with previous behavior
that vacuumed all tables in non-connectable databases. However, initdb
already freezes all tuples in information_schema tables on database
creation. And even in the worst case where we're at risk of wraparound,
auto-vacuum will force a vacuum regardless of the …

Fix autovacuum crash

---

src/backend/cdb/cdbmutate.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

We do that for normal subplans, but it's not needed for initplans which
only executed once.
See Github Issue: https://github.com/greenplum-db/gpdb/issues/12353
Backport 70e397ede

(backport to 5x) Don't append duplicated initplans even if referred at multi places.

---

src/backend/optimizer/path/indxpath.c

index_pathkeys might be NULL when target index does not provide
a desired sort order in query or when useful for sorting index
corresponding to inherited or child relation does not participate
in join.
Due to that the following fragment fails:
```
CREATE TABLE clstr_tst (a int, b INT) DISTRIBUTED BY (a);
CREATE INDEX clstr_tst_b_c ON clstr_tst (b);
CREATE TABLE clstr_tst_inh () INHERITS (clstr_tst);
SELECT a FROM clstr_tst ORDER BY 1
```
The solution is to check if index_pathkeys list is empty before using it.
There are already number of tests in regression that fails if enable
asserts (with passing --enable-cassert flag to ./configure).
For example, cluster test was failing:
> INSERT INTO clstr_tst (b, c, d) VALUES (6, 'seis', repeat('xyzzy', 100000));
> CLUSTER clstr_tst_c ON clstr_tst; …

Check if index pathkeys list is empty in find_usable_indexes() function

---

gpMgmt/bin/gpcheckperf
gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature

-t and -f flags are deprecated and gpcheckperf kept printing
NOTICE: -t is deprecated, and has no effect
NOTICE: -f is deprecated, and has no effect
Co-authored-by: M Hari Krishna hmaddileti@vmware.com

Do not pass deprecated flags to gpnetbenchClient

---

src/backend/tcop/postgres.c
src/backend/utils/error/elog.c
src/include/utils/elog.h
src/test/regress/expected/log_guc.out
src/test/regress/greenplum_schedule
src/test/regress/sql/log_guc.sql

When writing server log, GPDB always write out the statement string and
ignore the GUC log_min_error_statement. So fix it.

[6X]Make the GUC log_min_error_statement working for GPDB

---

src/backend/tcop/postgres.c
src/backend/utils/error/elog.c
src/include/utils/elog.h
src/test/regress/expected/log_guc.out
src/test/regress/greenplum_schedule
src/test/regress/sql/log_guc.sql

When writing server log, GPDB always write out the statement string and
ignore the GUC log_min_error_statement. So fix it.

[5X]Make the GUC log_min_error_statement available for GPDB

---

gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpcreateseg.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

gpinitsystem currently creates backout script on coordinator and on
each segment, and then appends all the segment backout scripts to the
coordinator backout script and we ask the user to run only that script.
If some of the gpcreateseg fail, the segment backout scripts aren't
appended correctly in some cases, and the user has to manually
cleanup those directories.
This change creates a single backout script early in gpinitsystem run,
so even if anything fails later, we would always be able to
cleanup all segment directories. To simplify, we are using 'echo' to
add lines into backout script instead of using BACKOUT_COMMAND
Co-authored-by: Divyesh Vanjare <vanjared@vmware.com>
(cherry picked from commit b0493ceb97c24eb48cae9017ce62949ff2f583e5)

6X gpinitsystem: fix backout script creation

---

concourse/scripts/compile_gpdb.bash

The bytecode is compiled and installed during package installation.

7X: Do not include compiled python bytecode in exported tarball

---

gpMgmt/bin/README.md
gpMgmt/bin/gplogfilter
gpMgmt/bin/gppylib/logfilter.py

gplogfilter is a log filter tool like awk, but easy to use.
[our document](https://gpdb.docs.pivotal.io/6-17/utility_guide/ref/gplogfilter.html) still says this tool is available. so upgrade this tool to fit python3.

Make gplogfilter support python3

---

src/backend/tcop/postgres.c
src/backend/utils/error/elog.c
src/include/utils/elog.h
src/test/regress/expected/log_guc.out
src/test/regress/greenplum_schedule
src/test/regress/sql/log_guc.sql

When writing server log, GPDB always write out the statement string and
ignore the GUC log_min_error_statement. So fix it.

Make the GUC log_min_error_statement working for GPDB

---

gpMgmt/bin/gppylib/operations/initstandby.py
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature

fix #12397 follow up #10853
`data_dirs_list` is `[Str]` (a list of string). after use `str()` the type will become a `Str`.
the subprocess will not deserialize correctly.
before: `-d '"["foo", "bar"]"'`
after: `-d '["foo", "bar"]'`

Delete 'pg_hba.conf.bak' after standby is fully setup

---

gpMgmt/bin/gpcheckperf

man pkill:
> The process name used for matching is limited to the 15 characters
> present in the output of /proc/pid/stat. Use the -f option to match
> against the complete command line.
When executing command, e.g. `gpcheckperf -f hostfiles -r N -d /tmp`,
the following subcommand will be executed:
```
/path/to/greenplum/bin/gpssh -f hostfiles 'F=gpnetbenchServer &&
(pkill $F || pkill -f $F || killall -9 $F) > /dev/null 2>&1 || true'
```
The length of `gpnetbenchServer` is 16, so `pkill gpnetbenchServer` will fail.
`pkill -f gpnetbenchServer` can succeed but it can also kill gpssh(its command
line contains gpnetbenchServer) if hostfiles contains this host. It can cause
some ssh connections from gpssh disconnected:
```
$ ps -ef | grep ssh
gpadmin   672077       1  0 17:30 ?        00:00:00 …
```

Fix: gpcheckperf did not close the SSH connections completely

---

gpMgmt/bin/gpconfig
gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
gpMgmt/test/behave/mgmt_utils/gpconfig.feature

We should check unique hostnames instead of checking for hostname associated
with each dbid. Each hostname has multiple dbids associated with it. In larger
clusters it led to 100s of liveness checks and failed with filedescriptor out
of range in select() error. In future we should move from `select` to `poll`.

Fix gpconfig filedescriptor out of range issue

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_input_column.py
gpMgmt/bin/gpload_test/gpload2/query44.ans
gpMgmt/bin/gpload_test/gpload2/query71.ans
gpMgmt/bin/gpload_test/gpload2/query73.ans
gpMgmt/bin/gpload_test/gpload2/query75.ans
gpMgmt/bin/gpload_test/gpload2/query76.ans
gpMgmt/bin/gpload_test/gpload2/query77.ans
gpMgmt/bin/gpload_test/gpload2/query78.ans

fix gpload cannot deal with column name in upper case
we treat column names like `COL, "COL"`as lower case letters unless it is quoted like `'"COL"' or "\"col\""`

fix gpload cannot deal with column name in upper case

---

src/backend/optimizer/path/allpaths.c
src/backend/optimizer/path/indxpath.c
src/backend/optimizer/plan/planmain.c
src/backend/optimizer/plan/planner.c
src/backend/optimizer/plan/subselect.c
src/include/nodes/plannerconfig.h
src/include/nodes/relation.h
src/test/regress/expected/join_gp.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/expected/subselect_gp_indexes.out
src/test/regress/expected/subselect_gp_indexes_optimizer.out
src/test/regress/greenplum_schedule
src/test/regress/sql/subselect_gp_indexes.sql

The problem is that `indexscan` cannot be used together with `Motion` node.  So we have to import a commit from 6x to fix it.
https://github.com/greenplum-db/gpdb/commit/cd055f999f87c8bd381cc3fd7a64ee94dfa46073
1. Create table
```sql
CREATE SCHEMA test_schema;
CREATE TABLE test_schema.users_unmasked (
user_id bigint NOT NULL,
params text
) DISTRIBUTED BY (user_id);
ALTER TABLE ONLY test_schema.users_unmasked
ADD CONSTRAINT users_20171219_pkey PRIMARY KEY (user_id);
INSERT INTO test_schema.users_unmasked
SELECT
gen,
case when random() > 0.5 then 'A' else 'B' end
FROM generate_series(1,20000) gen;
```
2. Run two queries. The second one returns incorrect data, because of incorrect plan with indexscan node without Motion.
```sql
SELECT cte."userId" FROM ( SELECT 7 as "userId" ) cte WHERE ( …
```

Don't choose indexscan when you need a motion for a subplan [Backport]

---

src/backend/commands/event_trigger.c
src/backend/commands/foreigncmds.c
src/backend/commands/proclang.c
src/backend/commands/trigger.c
src/backend/parser/parse_func.c
src/pl/tcl/pltcl.c

GCC 11 failed to build the project with following error:
```
foreigncmds.c:500:22: error: ‘funcargtypes’ may be used uninitialized [-Werror=maybe-uninitialized]
500 |         handlerOid = LookupFuncName((List *) handler->arg, 0, funcargtypes, false);
|                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from foreigncmds.c:38:
../../../src/include/parser/parse_func.h:65:17: note: by argument 3 of type ‘const Oid *’ {aka ‘const unsigned int *’} to ‘LookupFuncName’ declared here
65 | extern Oid      LookupFuncName(List *funcname, int nargs, const Oid *argtypes,
|                 ^~~~~~~~~~~~~~
foreigncmds.c:494:33: note: ‘funcargtypes’ declared here
494 |         Oid                     funcargtypes[1];        /* dummy */
| …
```

Fix build error with gcc 11

---

src/backend/optimizer/plan/createplan.c
src/backend/optimizer/plan/planner.c
src/backend/optimizer/plan/subselect.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

When creating plan with subquery and CTE,
it sets the useless flow for the plan.
But we only need flow for the topmost plan
and child of the motion. See commit
http://github.com/greenplum-db/gpdb/commit/93abe741cd67f04958e2951edff02b45ab6e280f
for more detail. The extra flow will cause
subplan set wrong motionType and cause an
ERROR unexpected gang size: XX.
This fixed issue https://github.com/greenplum-db/gpdb/issues/12371
Co-authored-by: Junfeng Yang <yjerome@vmware.com>

Remove useless flow from plan.

---

src/backend/cdb/dispatcher/cdbdispatchresult.c
src/test/isolation2/expected/gpdispatch.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/gpdispatch.sql

fix issue #12399 
The bug exists also in 6X_STABLE and 5X_STABLE, need to backport
cdbdisp_makeResult() may return NULL due to OOM.
Check the pointer when Gang cleanup.
Co-authored-by: Zhenghua Lyu <kainwen@gmail.com>

Fix: Gang cleanup null pointer reference (#12399)

---

src/backend/cdb/dispatcher/cdbdispatchresult.c
src/test/isolation2/expected/gpdispatch.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/gpdispatch.sql

dispatchResult->resultbuf returned by cdbdisp_makeResult() may return NULL due to OOM.
We should check the pointer when Gang cleanup in cdbdisp_resetResult().
Set a FAULT_INJECTOR(make_dispatch_result_error) to simulate this scenario.
Github issue https://github.com/greenplum-db/gpdb/issues/12399
Co-authored-by: Zhenghua Lyu <kainwen@gmail.com>
---------------------------
Backport pr https://github.com/greenplum-db/gpdb/pull/12430 to 6x.

(backport to 6x) Fix Gang cleanup null pointer reference

---

src/backend/catalog/heap.c
src/backend/parser/parse_utilcmd.c

We don't have `is_part_child` in CreateStmt now and the partition
implementation is using upstream's now see `generatePartitions`.
So remove the dead code and useless comment.

Remove useless FIXMEs for partition related

---

src/backend/access/appendonly/appendonlyam.c
src/backend/catalog/pg_appendonly.c
src/include/catalog/pg_appendonly.h

Retrieve append only table entry atts in one function call
in appendonly_fetch_init.
Also refactor GetAppendOnlyEntryAttributes and GetAppendOnlyEntryAuxOids.
There is no need to check NULL for pg_appendonly catalog entries since
InsertAppendOnlyEntry never insert NULL values.

FIXME: retrieve append only table entry atts in one call

---

gpdb-doc/dita/install_guide/init_gpdb.xml

Small change to the backout_gpinitsystem output in order to keep the example consistent with CLI output.

Docs: minor change for backout script

---

gpdb-doc/dita/analytics/pl_java.xml

Reflecting the change for 6.17.2. When creating javapl extension, now the option pljavat` is available which only contains trusted language `pljava` and does not contain untrusted language `pljavau`.
Preview:
https://mireia-pljavat.sc2-04-pcf1-apps.oc.vmware.com/7-0/analytics/pl_java.html#topic28

Docs: added reference to extension pljavat

---

src/backend/optimizer/util/pathnode.c
src/include/nodes/relation.h
src/test/regress/expected/bfv_planner.out
src/test/regress/expected/join_gp.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/greenplum_schedule
src/test/regress/sql/bfv_planner.sql

Greenplum has a specical method to implement semjoin: it
might create unique rowid path to first do inner join and
then de-duplicated based on ctid. The method was added to
Greenplum long before but after merging so many commits
from upstream, some new logic might fail when applying this
method. IndexOnlyScan is a case that the de-dup logic did
not consider. IndexOnlyScan's var is pointing to the Index
Rel, not the Heap Rel, to totally fix the logic seems risky
on a stable branch like 6X. So this commit just disallows
the unique rowid method when seeing indexonly scan to avoid
error-out. Index paths are set during base rel, and planner
then generates join rels so that the disallow-loigc works.

(6x only) Disallow unique rowid path when seeing indexonly scan.

---

src/backend/optimizer/plan/planner.c
src/test/regress/expected/bfv_planner.out
src/test/regress/sql/bfv_planner.sql

Greenplum has a special path to handle semjoin,
planner might add unique_row_id path to first inner join
and then de-duplicate. The logic is added into
Greenplum long before, but when merging more code from
upstream, the old logic does not consider new paths,
there are two relevant issues:
https://github.com/greenplum-db/gpdb/issues/3719
https://github.com/greenplum-db/gpdb/issues/12402
issue-12402 is that while creating a plan for the second append rel,
it will add pseudo column in rtable of subroot, however, do not
add it to final_rtable (subroot->rtable of the first append rel),
so failed to find the corresponding pseudo column in cdbpath_dedup_fixup.
issue-3719 is that the pseudocols of root->rtable is not null,
while creating a plan for first append rel, in build_simple_rel …

(6x only) Disallow unique rowid path for inheritance plan

---

src/bin/psql/startup.c

The purpose of this PR is to make the behavior about logging of the tool psql consistent with PostgreSQL 12.
Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-users/c/Eu0YIj7328M
Refer to these three commits from PostgreSQL repo:
https://github.com/postgres/postgres/commit/d8ec5ebaea4455a5b19fa1bc8ec6eb299e93e835
https://github.com/postgres/postgres/commit/363382521eb26106587c7dab7f439636c3a6876a
https://github.com/postgres/postgres/commit/16eadc4695ef120e5a6f6adf026a034e291806cc

Merge bin/psql/startup.c from PostgreSQL 12

---

src/backend/utils/error/elog.c

This commit fixes a server Segmentation Fault that can happen while trying to write error messages to the logs.
Also:  fixes logic for detecting errors while calling addr2line or atos (previously, addr2line_ok was always set to true, even after a failure)
This commit has already been reviewed in [PR 11840](https://github.com/greenplum-db/gpdb/pull/11884), and it looks like the consensus was that it should be merged to master.  I lost track of it for a few months, but just noticed it--re-opening it here as a separate PR for the same commit against master instead of 6X_STABLE.

Fix Segmentation Fault in append_stacktrace

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c

This commit ensures that the following lock table corruption scenario is
avoided:
Consider two sessions S1 and S2.
1. S1 is currently stuck in ResProcSleep(), waiting for a resource queue
lock (one possible reason being S1 has hit the active_statements limit
on the resource queue)
2. We cancel S1 with pg_cancel_backend() or kill SIGINT.
3. S1 exits ResLockAcquire() with an ERROR due to the cancel (from
withing the ProcessInterrupts() call within PGSemaphoreLock() within
ResProcSleep()).
4. S1 catches the ERROR in the PG_CATCH in ResLockPortal() and calls
ResLockWaitCancel(), which removes the proclock and lock shmem hash
table entries (with call to ResRemoveFromWaitQueue()). However, we don't
remove the locallock entry from the locallock hash table.
Note: When a hash table entry is …

Mitigate a proclock/lock table corruption case

---

src/backend/commands/resgroupcmds.c
src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql

In some cases, the AccessExclusiveLock for table pg_resgroupcapability may cause database setup/recovery pending.
For example in the test resgroup_seg_down_2pc, user ran "alter resource group" firstly, and before the QD broadcasts
the commit prepared command to QEs(that is the second phase of 2PC), if there is one primary segment down, then the "alter resource group" can't get executed successfully. Even run gprecoverseg to recover the segment, the segment is still pending on function InitResGroups.
The reason is that, when run "alter resource group", the AccessExclusiveLock is acquired for table pg_resgroupcapability on each segment, and if primary is switched or restart due to some error, function InitResGroups will acquire AccessShareLock for table pg_resgroupcapability in order to do …

Use ExclusiveLock for accessing the table pg_resgroupcapability when CREATE/ALTER resouce group.

---

src/backend/access/aocs/aocssegfiles.c
src/test/isolation2/expected/uao_crash_compaction_column.out
src/test/regress/expected/alter_table_aocs.out
src/test/regress/sql/alter_table_aocs.sql

Before current commit we initailized `pg_aocsseg` entries with frozen tuples to make these entries implicitly visible even after rollback. It is a working approach for AO tables, but AOC tables store additional `vpinfo` structure with serialized information about every column EOF. This can cause inconsistency between `vpinfo` structure in `pg_aocsseg` entries and the actual number of columns in a table when we modify the amount of columns under explicit transaction and rollback it later. As a result we fail on asserts in `GetAllAOCSFileSegInfo_pg_aocsseg_rel()` or (in a case of a build without asserts) in some unpredictable places in the code when retrieve metadata from `pg_aocsseg`.
As a fix this commit inserts simple tuples to `pg_aocsseg` but still insert frozen tuples to …

Fix aocsseg inconsistency when rollback add column

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/commands/pg.py
gpMgmt/bin/gppylib/commands/unix.py
gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Management utils are fails when user configures banner through bashrc.
gprecoverseg and gpinitstandby utils are addressed as part of this PR. Most of
the changes are related to parsing failures which are addressed below.
Note: Hitting issue only when banner set through bashrc.

gpinitstandby/gprecoverseg utils fail when there is banner on .bashrc  present

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

- Modified default value of GUC unix_socket_permissions to 0777
- Added GUC log_file_mode
- Did not add data_directory_mode since I cannot see it available on a Greenplum test environment.
Can you please confirm that the values under Set Classifications column for log_file_mode are correct?
Test site:  https://mireia-gucs.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html
Needs to be added to 6.17 as well

Unix socket permissions

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c

This is a backport of PR: #12465

5X: Mitigate a proclock/lock table corruption case.

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c

This is a backport of PR: #12465

6X: Mitigate a proclock/lock table corruption case

---

src/backend/cdb/dispatcher/cdbconn.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/cdb/dispatcher/cdbgang_async.c
src/backend/postmaster/postmaster.c
src/backend/utils/init/postinit.c
src/backend/utils/misc/guc.c
src/include/cdb/cdbconn.h
src/include/cdb/cdbgang.h
src/include/libpq/libpq-be.h
src/interfaces/libpq/fe-connect.c
src/interfaces/libpq/fe-protocol3.c
src/interfaces/libpq/libpq-int.h
src/test/isolation2/expected/sync_guc.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/sync_guc.sql

When we change some GUC values and reset them later in
a session. The GUC values may be inconsistent among QD and/or QEs.
The key steps of current GUC settings are:
1. The QD dispatches its current `sync`ed GUC values(as startup
options) to create QEs.
2. The QE sets the GUCs' `reset_val` to the options passsed
from the QD during its process initialization.
2.5 When the QD dispatches `SET XXX=YYY` for an existing QE,
the QE will set the GUC's current value to YYY, `reset_val`
is unchanged. Because its guc-source is PGC_S_SESSION.
3. When the QE receives `RESET XXX`, it resets the GUC's value to
its `reset_val`.
The problem happens in the step 1, which causes the `reset_val`s
between QD and QEs inconsistent if the QD changed the GUC before
creating the QE(s).
The fix is to send the GUC's …

Fix reset GUC issue that causes inconsistent GUC values

---

src/backend/cdb/cdbllize.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

When creating a plan with subplan in ParallelizeSubplan, it uses
the wrong flow to decide motion type for subplan. And the wrong
flow will cause subplan set wrong motion type and cause assertion
failure Assert(recvSlice->gangSize == 1) in nodeMotion.c.
When ParallelizeSubplan(), if the subplan is uncorrelated, multi-row
subquery, then it either focuses or broadcasts the subplan based on the
flow which describes the containing plan node's slice execution position.
Actually, the flow should be the top-level flow for the corresponding slice
instead of the containing the plan node's flow. To select the correct flow during
the plan tree iteration, we only set currentPlanFlow when jumping into a new slice.
This fixed issue: #12371

[5X]Use the correct flow in ParallelizeSubplan for subplan

---

src/backend/cdb/cdbllize.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

When creating a plan with subplan in ParallelizeSubplan,it use
the wrong flow to decide motion type for subplan. And the wrong
flow will cause subplan set wrong motionType and cause assertion
failure Assert(recvSlice->gangSize == 1) in nodeMotion.c.
When ParallelizeSubplan(), if the subplan is uncorrelated, multi-row
subquery,then it either focuses or broadcasts the subplan based on the
flow which describe the containing plan node's slice execution position.
Actually the flow should be the top-level flow for the corresponding slice
instead of the containing plan node's flow. To select the correct flow during
the plan tree iteration, we only set currentPlanFlow when jump into a new slice.
This fixed issue: #12371

[6X]Use the correct flow in ParallelizeSubplan for subplan

---

src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Previously, `IS DISTINCT FROM FALSE` was simplified to checking if it is true.
However, due to the three valued logic of SQL, these are not equivalent
statements. This change changes the direct equality check to an OR between the
equality check and `IS NULL`.
```
CREATE TABLE tt1 (a int, b int);
CREATE TABLE tt2 (c int, d int);
INSERT INTO tt1 VALUES (1, NULL), (2, 2), (3, 4), (NULL, 5);
INSERT INTO tt2 VALUES (1, 1), (2, NULL), (4, 4), (NULL, 2);
EXPLAIN SELECT b FROM tt1 WHERE NOT EXISTS (SELECT * FROM tt2 WHERE (tt2.d = tt1.b) IS DISTINCT FROM false);
```
Expected/Patched:
```
QUERY PLAN
--------------------------------------------------------------------------------------------------
Result  (cost=0.00..1324032.17 rows=1 width=4)
Filter: (SubPlan 1)
->  Gather Motion 3:1  (slice1; …
```

Fixed missing NULL check in LeftAntiSemiHashJoin2HashJoin (6X)

---

src/backend/parser/parse_clause.c
src/test/regress/expected/olap_group.out
src/test/regress/sql/olap_group.sql

Retrieve the correct pstate for GroupingFunc according to varlevelsup
Fixes #12343

Fix assertion failure for GroupingFunc with subqueries

---

src/backend/commands/resgroupcmds.c
src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql

In some scenarios, the AccessExclusiveLock for table pg_resgroupcapability may cause database setup/recovery pending. Below is why we need change the AccessExclusiveLock to ExclusiveLock.
This lock on table pg_resgroupcapability is used to concurrent update this table when run "Create/Alter resource group" statement. There is a CPU limit, after modify one resource group, it has to check if the whole CPU usage of all resource groups doesn't exceed 100%.
Before this fix, AccessExclusiveLock is used. Suppose one user is running "Alter resource group" statement, QD will dispatch this statement to all QEs, so it is a two phase commit(2PC) transaction. When QD dispatched "Alter resource group" statement and QE acquire the AccessExclusiveLock for table pg_resgroupcapability. Until the 2PC …

[Backport 6X] Use ExclusiveLock for accessing the table pg_resgroupcapability when CREATE/ALTER resouce group.

---

src/backend/commands/resgroupcmds.c
src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql

In some scenarios, the AccessExclusiveLock for table pg_resgroupcapability may cause database setup/recovery pending. Below is why we need change the AccessExclusiveLock to ExclusiveLock.
This lock on table pg_resgroupcapability is used to concurrent update this table when run "Create/Alter resource group" statement. There is a CPU limit, after modify one resource group, it has to check if the whole CPU usage of all resource groups doesn't exceed 100%.
Before this fix, AccessExclusiveLock is used. Suppose one user is running "Alter resource group" statement, QD will dispatch this statement to all QEs, so it is a two phase commit(2PC) transaction. When QD dispatched "Alter resource group" statement and QE acquire the AccessExclusiveLock for table pg_resgroupcapability. Until the 2PC …

[Backport 5X]Use ExclusiveLock for accessing the table pg_resgroupcapability when CREATE/ALTER resouce group.

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/commands/pg.py
gpMgmt/bin/gppylib/commands/unix.py
gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_utils.py
gpMgmt/bin/gppylib/operations/utils.py
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Management utils are fails when user configured banner through bashrc
gprecoverseg and gpinitstandby gpstart and gpstop  are addressed as part of this PR. Most of
the changes are related to parsing failures which are addresed below.
Info : Backporting changes from master to 6X with minor changes

Gpinitstandby gprecoverseg gpstart gpstop  fails when there is a banner  on bashrc  --6x

---

gpMgmt/bin/gpinitstandby
src/bin/pg_ctl/pg_ctl.c
src/bin/pg_ctl/t/001_start_stop.pl

pg_ctl supports two internal cmdline arguments, --wrapper and
--wrapper-args, they are gpdb specific arguments for debugging purpose,
however we lost them since gpdb 5 during the postgres merging. The
arguments are still accepted, just not being used.
Now we bring the function back.
Co-Authored-By: Ning Yu <nyu@pivotal.io>
Co-Authored-By: Adam Lee <adlee@vmware.com>

6X: pt_ctl: rework the wrapper function

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query40.ans
gpMgmt/bin/gpload_test/gpload2/query41.ans
gpMgmt/bin/gpload_test/gpload2/query42.ans

backport fix gpload6 column uppercase  #12416 to gpload5
if column name has upper case letters, column should write like `'"Col"'` or `"\"Col\""` in the yaml file. 
`"Col"` will be treated as lower case.

fix gpload upper case column

---

src/backend/access/bitmap/bitmapsearch.c

Seems left over debug message by commit 22c1ec81c1ce. It floods the
log files unnecessarily, when using bitmap index scans.

Delete verbose logging of message "fetch bitmap page"

---

src/backend/gporca/libgpopt/include/gpopt/engine/CPartialPlan.h
src/backend/gporca/libgpopt/include/gpopt/exception.h
src/backend/gporca/libgpopt/src/base/CCostContext.cpp
src/backend/gporca/libgpopt/src/engine/CPartialPlan.cpp
src/backend/gporca/libgpopt/src/exception.cpp
src/backend/gporca/libgpos/src/_api.cpp
src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp

This is a forward port of https://github.com/greenplum-db/gpdb/pull/12491.
In some edge cases in Orca, groups may not have had statistics derived
during the exploration stage. This is ok in many cases, as these groups
may not be used during implementation or their stats may not be accessed
during implementation. However, there are some cases where we do need
these stats, and trying to access them resulted in a crash.
This commit adds a defensive check to fall back to planner if we
encounter such a scenario, similar to checks added in
a6f92be1b8327aadc7l.

Add check to ensure stats are not null in implementation stage of Orca

---

gpdb-doc/markdown/pxf/migrate_5to6.html.md.erb

PXF is not compatible with GPDB 6 if running on RHEL/CentOS 6.x due to cURL version incompatibilities. This was listed on the Known Issues and Limitations section of the GPDB Release Notes but might not be enough.
Added it as well to the PXF upgrade guidelines when upgrading GPDB from 5.x. 
Let me know if it would make sense to add it to any other section.
Preview:
https://mireia-pxf-rhel.sc2-04-pcf1-apps.oc.vmware.com/7-0/pxf/migrate_5to6.html

Added note to PXF migration from GPDB 5

---

src/backend/utils/misc/guc.c
src/test/regress/expected/guc.out
src/test/regress/sql/guc.sql

log_lock_waits was never officially supported and it was missing from
our official documentation. This commit disallows the GUC from being
set. Setting the GUC to on will be a no-op with a WARNING emitted.
The reason why we can't support this GUC boils down to inconsistencies
between ResProcSleep() and its upstream equivalent ProcSleep().
ResProcSleep() clearly did not get the memo about log_lock_waits.
(introduced in e52c4a6e26f, much after resource queues were incepted)
The way the GUC works is simple: When anything other than a hard
deadlock is detected in CheckDeadlock(), the waiting process wakes up
inside ProcSleep(), logs the lock wait, and then goes back to sleep.
Unlike ProcSleep(), if a process is waiting on a resource queue in
ResProcSleep(), after waking up, we don't log the …

6X: Disable the log_lock_waits feature

---

src/backend/utils/error/elog.c

I had noticed over the past few years that gpdb occasionally crashes with a SIGSEGV while trying to write an error message to the log.  But usually the error I cared about investigating became clear after opening the core file, and went away after fixing it, so I never took the time to go back and reproduce this crash.
It happened a couple days ago, and I took a look at it this time.  It's a null pointer dereference in `append_stacktrace()` that can happen while parsing the output of `addr2line/atos` when they output lines longer than 512 bytes (SYMBOL_SIZE).  This may not happen often in C, but the symbols are often longer than that in C++ so the output lines gets truncated.  If there are open parenthesis in the string and the truncation happens before the first close paren, then it …

Fix segfault in elog.c

---

gpdb-doc/dita/admin_guide/wlmgmt_intro.xml
gpdb-doc/dita/best_practices/summary.xml
gpdb-doc/dita/best_practices/sysconfig.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

The calculation of gp_vmem on the tool https://greenplum.org/calc/ has been reviewed and modified to avoid waste of RAM.
When the total system memory is equal to or higher than 256 GB, a new formula applies:
```
gp_vmem = ((SWAP + RAM) – (7.5GB + 0.05 * RAM)) / 1.17
```
Docs have been updated to reflect the change. I have created the PR against master, can you confirm what versions of 6.x should include the change?
Also let me know if 5.x versions need to be edited as well.
Preview sites:
https://mireia-gp-vmem.sc2-04-pcf1-apps.oc.vmware.com/7-0/best_practices/summary.html
https://mireia-gp-vmem.sc2-04-pcf1-apps.oc.vmware.com/7-0/best_practices/sysconfig.html
https://mireia-gp-vmem.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/wlmgmt_intro.html …

Docs: updated gp_vmem calculation

---

gpdb-doc/dita/admin_guide/wlmgmt_intro.xml
gpdb-doc/dita/best_practices/summary.xml
gpdb-doc/dita/best_practices/sysconfig.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

PR for 5X_STABLE equivalent to https://github.com/greenplum-db/gpdb/pull/12477
The calculation of gp_vmem on the tool https://greenplum.org/calc/ has been reviewed and modified to avoid waste of RAM.
When the total system memory is equal to or higher than 256 GB, a new formula applies:
gp_vmem = ((SWAP + RAM) – (7.5GB + 0.05 * RAM)) / 1.17

Gp vmem mods

---

src/backend/executor/nodeMotion.c

We should check interrupts in ExecMotion(). Or we cannot process interrupts in time.
Hi, we found that GPDB cannot process interrupts in time in `execMotion()`.
The easiest way to reproduce:
```sql
create table t(a int, b int);
insert into t select i, i%3 from generate_series(1,60000000) i;
select * from t;
/* Hit CTRL-C */
/* We have to wait a very long time until it cancels the query. */
```

Add CHECK_FOR_INTERRUPTS() to ExecMotion().

---

src/backend/utils/misc/guc.c
src/test/regress/expected/guc.out
src/test/regress/sql/guc.sql

This is a backport of 6X commit 3763cc7379b with minor changes.
log_lock_waits was never officially supported and it was missing from
our official documentation. This commit disallows the GUC from being
set. Setting the GUC to on will be a no-op with a WARNING emitted.
The reason why we can't support this GUC boils down to inconsistencies
between ResProcSleep() and its upstream equivalent ProcSleep().
ResProcSleep() clearly did not get the memo about log_lock_waits.
(introduced in e52c4a6e26f, much after resource queues were incepted)
The way the GUC works is simple: When anything other than a hard
deadlock is detected in CheckDeadlock(), the waiting process wakes up
inside ProcSleep(), logs the lock wait, and then goes back to sleep.
Unlike ProcSleep(), if a process is waiting on a …

5X: Disable the log_lock_waits feature

---

gpMgmt/bin/gpexpand

The address for WAL-replication should be the primary's `address`
in gp_segment_configuration. When running pg_basebackup,
the destination address for pg_basebackup is resolved to
the address in WAL replication by its mirror.

Use the segment address for WAL-replication in gpexpand

---

gpMgmt/bin/gpexpand

The address for WAL-replication should be the primary's `address`
in gp_segment_configuration.
This PR is a sub-fix of another PR(https://github.com/greenplum-db/gpdb/pull/12208).
The major intent is to make this change minimal for review and merge
it soon.

Use the address for WAL-replication in gpexpand

---

gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py

Patching the below gaps in unit tests of gpstart utility
1. gpstart should success with auto accept
2. gpstart should success without auto accept
3. gpstart should exit when user abort
4. gpstart with master only option should exit when user abort
Note: Backporting from master to 6x_stable
Co-authored-by: M Hari krishna hmaddileti@vmware.com

[Backport 6x] Inclusion of unit tests for more test coverage of gpstart

---

src/backend/cdb/motion/ic_proxy.h
src/backend/cdb/motion/ic_proxy_addr.c
src/backend/cdb/motion/ic_proxy_main.c

Fix ic-proxy logging not work due to outdated api.
In the logging enabled code block, `ic_proxy_extract_addr` is deprecated instead of `ic_proxy_extract_sockaddr`, with minor changes in parameters also.
- [x ] Pass `make installcheck`

[Minor] Fix ic-proxy logging not work due to outdated api.

---

gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

The behave tests added for gpinitsystem backout scripts are timing
dependent, since they involve asynchronous killing of processes.
This was causing failures on pipeline if the kill is executed too
early/late.
This commit aims at reducing this flaky behavior by
- making the kill condition more accurate for gpcreateseg- by monitoring
process instead of logs. We monitor the process using ps/grep and want
to kill it after it has setup the trap for ERROR_EXIT. Added test step
for the same.
- for scenario of killing gpinitsystem, gpcreateseg processes can still
run in the background after gpinitsystem has been killed. We want to
wait for these processes to complete to successfully run backout
script. Added test step for the same.
- changing the 'waiting to complete' step to monitor processes, …

gpinitsystem behave tests fix flakes

---

gpMgmt/bin/gpcheckperf

man pkill:
> The process name used for matching is limited to the 15 characters
> present in the output of /proc/pid/stat. Use the -f option to match
> against the complete command line.
When executing command, e.g. `gpcheckperf -f hostfiles -r N -d /tmp`,
the following subcommand will be executed:
```
/path/to/greenplum/bin/gpssh -f hostfiles 'F=gpnetbenchServer &&
(pkill $F || pkill -f $F || killall -9 $F) > /dev/null 2>&1 || true'
```
The length of `gpnetbenchServer` is 16, so `pkill gpnetbenchServer` will fail.
`pkill -f gpnetbenchServer` can succeed but it can also kill gpssh(its command
line contains gpnetbenchServer) if hostfiles contains this host. It can cause
some ssh connections from gpssh disconnected:
```
$ ps -ef | grep ssh
gpadmin   672077       1  0 17:30 ?        00:00:00 …
```

Fix: gpcheckperf did not close the SSH connections completely (#11141)

---

src/backend/executor/nodeMaterial.c
src/backend/executor/nodeShareInputScan.c
src/backend/executor/nodeSort.c
src/include/nodes/execnodes.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

ShareInputScan node uses temporary files as shared buffers and FIFOs as
a syncing mechanism for cross-slice communication (i.e IPC). The names
of these files is based on gp_session_id, gp_command_count & share_id.
Since these are computed (multiple times) during ExecProcNode, if the
gp_command_count (or another variable) changes between when the files
are created, written to and read from, the executor could ERROR failing
to find the required file, or even see wrong entries.
For the attached test case, ORCA produces a plan that executes an SPI
(pl/pgSQL) function on a master slice, which increments the gp_command
count, between the creation of the shared buffer file and it's
subsequent reading.
This commit fixes this issue by computing the names of all the files
required for cross-slice …

Compute SharedScan xslice buffer file names during ExecInitNode

---

src/backend/utils/adt/dbsize.c

AO auxiliary tables using different relkind poses problem as requires
explicit effort to add those values to switch
blocks. pg_relation_filenode() is missing RELKIND_AOSEGMENTS,
RELKIND_AOBLOCKDIR and RELKIND_AOVISIMAP. Hence, used to report NULL
when run against those. With this change, works fine for AO auxiliary
tables as well.
Fixes https://github.com/greenplum-db/gpdb/issues/12409.

Make pg_relation_filenode() working for AO auxiliary tables

---

src/backend/executor/nodeAgg.c
src/backend/executor/nodeShareInputScan.c
src/backend/storage/file/fd.c
src/backend/utils/sort/logtape.c
src/backend/utils/sort/tuplestore.c
src/include/storage/fd.h
src/include/utils/logtape.h
src/include/utils/tuplestore.h
src/test/regress/GNUmakefile
src/test/regress/input/temp_tablespaces.source
src/test/regress/output/temp_tablespaces.source

NB: The current code has already correctly used temp_tablespaces for
hash aggregate and sisc(share input scan) across slices. This commit
only adds test cases for them to constraint future code break.
The `temp_tablespaces` defines the temp tablespaces that are used
when spill file happens. Using wrong tablespaces usually doesn't
have errors or even warnings, but we want to ensure that the GUC
`temp_tablespaces` is honored if it was set.
When `temp_tablespaces` is set, usually any tablespace can be chosen
for temp files, but we need to take care of one case that uses
temp file(s) across slices. The producer backend must use the same
tablespace as the consumer backend(s), or they refer to different
path for the expected temp file(s).

Add test case for hashagg and sisc across slices to honor temp_tablespaces

---

src/backend/executor/execMain.c
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

If a query is a CTAS with initplan, it may reset 'Oid dispatch context'
when an exception occurs in preprocess_initplans, which will further
cause invlid list reference during the serialization of oidAssignments
when dispatching plan.
In this fix, we copy an extra list for oidAssignments for querys
that contain CTAS and initplan.

Fix the invalid oidAssignments list for CTAS query with initplan

---

src/backend/executor/nodeShareInputScan.c

Hi there~Recently I built from GreenPlum master branch to run TPC-DS query with 1GB data. For Q47 and Q57, when I turned off GUC `execute_pruned_plan` (on by default), some of worker processes will be hang and the query never returns.
Take Q57 as an example. My cluster configuration is 1 QD + 2 QE. The query looks like:
```sql
with v1 as(
select
i_category,i_brand,
cc_name,d_year,d_moy,
sum(cs_sales_price) sum_sales,
avg(sum(cs_sales_price)) over (partition by
i_category,i_brand,cc_name,d_year)
avg_monthly_sales,
rank() over (partition by
i_category,i_brand,cc_name
order by
d_year,d_moy
) rn
from
item,catalog_sales,date_dim,call_center
where
cs_item_sk = i_item_sk and
cs_sold_date_sk = d_date_sk and
cc_call_center_sk= cs_call_center_sk and(
d_year = 1999 or
( d_year = 1999-1 and d_moy …
```

Fix squelch deadlock in nodeShareInputScan of CTE

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

This PR is a combination of changes for enhancing gpstate output on showing mirror sync progress. (More technical details in commit message)
[1] gpstate -e: Add `WAL sync remaining bytes` field for unsyncronized segment
pairs catching up to get to sync. 
- This is only required when walsender starts for the first time (after mirror
recovery) and is in catchup state.
- Sample output:
```
----------------------------------------------------
Unsynchronized Segment Pairs
Current Primary           Port    WAL sync remaining bytes   Mirror                    Port
vanjared-a01.vmware.com   15434   2802320                    vanjared-a01.vmware.com   15437
```
[2] gpstate -s: Add WAL fields for commit queue/delay for tracking delays on
commit queue. This change aims at giving the user additional …

gpstate: show Mirror sync progress

---

src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h

When initially creating the memory pools in Orca, there is a Malloc call
that is not properly handled if Malloc returns a null pointer. Since
Orca is also initialized on the segments, it is possible that this could
cause a segment OOM to be improperly handled if OOM occurs at this time.
Now, we raise an exception if we fail to allocate here.

Add NULL pointer check when creating memory pool manager in Orca

---

src/backend/commands/vacuum.c
src/test/isolation/expected/vacuum-full-permissions.out
src/test/isolation/isolation_schedule
src/test/isolation/specs/vacuum-full-permissions.spec

If non superuser runs VACUUM FULL, it could block on a table that the user
doesn't have permissions to if someone else is running a transaction on the same
table at the same time. In fact, in this case, the table would have been skipped,
but the permissions check currently happens after AccessExclusiveLock is
acquired. Until the AccessExclusiveLock is acquired and VACUUM FULL skips the
table, all other transactions touching the table would be blocked on the
AccessExclusiveLock request.  This is especially troublesome when the table is a
system catalog table such as pg_class or pg_database.
This commit adds the permission check to get_rel_oids() to filter out the tables
that the user doesn't have permission to during relation list creation. In this
case, if such a table is locked VACUUM …

[6X]: VACUUM FULL should do permissions check during relation list creation

---

src/test/regress/expected/guc_gp.out
src/test/regress/sql/guc_gp.sql

6X_stable has a bug with single quote `'` in the string GUC value, which
will cause a incorrect quoted string gets dispatched to QEs. e.g.:
> SET search_path = "'";
ERROR:  unterminated quoted string at or near "'"
"SET search_path = '" will be dispatched instead of the correct one
"SET search_path = ''''"
Luckily the bug has been fixed on master by 320af40b31f5.
This commit adds test cases to prepare to be backported to 6X with
the original fix together.

Add test cases for SET with quoted string

---

gpcontrib/Makefile
gpcontrib/gp_legacy_string_agg/Makefile
gpcontrib/gp_legacy_string_agg/expected/gp_legacy_string_agg_tests.out
gpcontrib/gp_legacy_string_agg/gp_legacy_string_agg--1.0.0.sql
gpcontrib/gp_legacy_string_agg/gp_legacy_string_agg.c
gpcontrib/gp_legacy_string_agg/gp_legacy_string_agg.control
gpcontrib/gp_legacy_string_agg/sql/gp_legacy_string_agg_tests.sql

In GPDB6 the one-argument version of string_agg() was removed (Postgres
removed it in 9.1 commit b0c451e). This commit brings back the
one-argument version string agg in a user-defined aggregate extension.
A simpler approach is to use a SQL user-defined function like so:
```SQL
CREATE FUNCTION aggs_trans(text,text) RETURNS text
AS 'SELECT concat($1,$2)' LANGUAGE SQL STRICT IMMUTABLE;
CREATE AGGREGATE string_agg(text) (
sfunc = aggs_trans, stype = text,
initcond = ''
);
```
Issue with that implementation is that it is significantly slower:
```SQL
\timing
-- UDF version of one-argument string_agg()
SELECT string_agg('a') FROM generate_series(1, 5000);
Time: 77.713 ms
-- built-in two-argument version of string_agg()
SELECT string_agg('a', '') FROM generate_series(1, 5000);
Time: 11.101 ms …
```

Revive legacy one-argument string_agg() aggregate

---

src/backend/commands/vacuum.c
src/test/isolation/expected/vacuum-full-permissions.out
src/test/isolation/isolation_schedule
src/test/isolation/specs/vacuum-full-permissions.spec

If non superuser runs VACUUM FULL, it could block on a table that the user
doesn't have permissions to if someone else is running a transaction on the same
table at the same time. In fact, in this case the table would have been skipped,
but the permissions check currently happens after AccessExclusiveLock is
acquired. Until the AccessExclusiveLock is acquired and VACUUM FULL skips the
table, all other transactions touching the table would be blocked on the
AccessExclusiveLock request.  This is especially troublesome when the table is a
system catalog table such as pg_class or pg_database.
This commit adds the permission check to get_rel_oids() to filter out the tables
that the user doesn't have permissions to during relation list creation. In this
case, if such a table is locked VACUUM …

[5X] VACUUM FULL should do permissions check during relation list creation

---

src/backend/utils/mmgr/memaccounting.c
src/backend/utils/mmgr/test/memaccounting_test.c

Previously, we used the max vmem and called this "Vmem". Now, we report
both the reserved and max vmem, which hopefully will be a bit clearer for debugging.
This memory accounting framework does not exist on the master branch, so this change only applies to 6X.

Improve memory accounting logging for VMEM

---

src/backend/commands/copy.c
src/test/regress/expected/copy_eol.out
src/test/regress/greenplum_schedule
src/test/regress/input/gpcopy.source
src/test/regress/output/gpcopy.source
src/test/regress/sql/copy_eol.sql

Fix copy command can't read file with special character at the end of line(#12454 )
The copy command read data from a file and process data once a character.
In non-CSV mode, anything after a backslash is skipped over, so that EOL
character after a backslash can not be recognized.
An example file with content:
>
1, message1
2, message2\
3, message3
The copy from command will fail because line2 and line3 will be regarded as one line.

Fix copy command can't read file with special character at the end of line

---

gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

This is a backport of https://github.com/greenplum-db/gpdb/pull/12514
The behave tests added for gpinitsystem backout scripts are timing
dependent, since they involve asynchronous killing of processes.
This was causing failures on pipeline if the kill is executed too
early/late.
This commit aims at reducing this flaky behavior by
- making the kill condition more accurate for gpcreateseg- by monitoring
process instead of logs. We monitor the process using ps/grep and want
to kill it after it has setup the trap for ERROR_EXIT. Added test step
for the same.
- for scenario of killing gpinitsystem, gpcreateseg processes can still
run in the background after gpinitsystem has been killed. We want to
wait for these processes to complete to successfully run backout
script. Added test step for the …

6X backport: gpinitsystem behave tests fix flakes

---

src/backend/access/appendonly/appendonly_visimap_entry.c

In gpdb4，visiMapEntry->bitmap is not set to NULL after freeing in AppendOnlyVisiMapEnty_ReadData, before it is assigned new values, we get cancel signal and throw an error, When we catch the error and process AbortCurrentTransaction to rollback, we call PortalCleanup->ExecutorEnd to release the resource, In AppendOnlyVisimapEntry_Finish visiMapEntry->bitmap is not null, It is freed the second time.
I did not reproduce this issue in master, because the logic of AbortCurrentTransaction is different from gpdb4,
However, we should set visiMapEntry->bitmap to null after we free it to avoid other similar issues.
This issue occurs, when segment free bitmap in AppendOnlyVisiMapEnty_ReadData, Then when we palloc memory we receive a cancel signal and throw an error, this occurs randomly, So the …

Set bitmap to NULL after freeing it to avoid freeing twice

---

src/backend/utils/misc/faultinjector.c
src/backend/utils/resscheduler/resqueue.c
src/include/utils/faultinjector.h
src/include/utils/resscheduler.h
src/test/regress/expected/resource_queue.out
src/test/regress/sql/resource_queue.sql

This is a backport of #12528.
1. The first commit is a partial backport for test coverage (the associated fix was already present in 5X from commit: a7f8e8c275). Some minor changes to the test and test infrastructure was necessary due to differences in the fault injector framework between 5X and 7X.
2. The second commit is a straight-forward backport without any conflict resolution necessary.

[5X] Miscellaneous fixes to the ERROR path for ResLockAcquire

---

src/backend/utils/resscheduler/resqueue.c
src/include/utils/resscheduler.h
src/test/regress/expected/resource_queue.out
src/test/regress/sql/resource_queue.sql

This is a backport of #12528.
1. The first commit is a partial backport for test coverage (the associated fix was already present in 6X from commit: e1793e77ea9)
2. The second commit is a straight-forward backport without any conflict resolution necessary.

[6X] Miscellaneous fixes to the ERROR path for ResLockAcquire

---

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

This PR is a combination of changes for enhancing gpstate output on showing mirror sync progress. (More technical details in commit message)
[1] gpstate -e: Add `WAL sync remaining bytes` field for unsyncronized segment
pairs catching up to get to sync. 
- This is only required when walsender starts for the first time (after mirror
recovery) and is in catchup state.
- Sample output:
```
----------------------------------------------------
Unsynchronized Segment Pairs
Current Primary           Port    WAL sync remaining bytes   Mirror                    Port
vanjared-a01.vmware.com   15434   2802320                    vanjared-a01.vmware.com   15437
```
[2] gpstate -s: Add WAL fields for commit queue/delay for tracking delays on
commit queue. This change aims at giving the user additional …

[6X backport] gpstate: mirror sync progress

---

gpMgmt/bin/gpsd
gpMgmt/bin/minirepro
src/test/regress/expected/minirepro.out
src/test/regress/sql/minirepro.sql

If the field type is array, then the type of statistical information
will be array[array]. But now we use One-dimensional array like
array[float].
Since we have output in a good format, if it is considered to be of text
type, it will be automatically converted to array[array]

Use text type in output of array type

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

Based on greenplum-db/sre-test#230

Documentation for writable_external_table_bufsize: correct units

---

gpdb-doc/dita/utility_guide/ref/analyzedb.xml

the analyzedb ref page synopsis and examples for -i and -x option/values specify spaces between column names.  this is incorrect, there must be no spaces.

docs - no spaces between column names in analyzedb -i, -x option values

---

src/backend/utils/resscheduler/resqueue.c

This is inspired from PR #12185
This change was already backported to 5X (https://github.com/greenplum-db/gpdb/pull/12233) and 6X (https://github.com/greenplum-db/gpdb/pull/12267). It wasn't committed to master, since the associated test wasn't passing due to problems with the deadlock check code not getting invoked from resource queue code (See https://github.com/greenplum-db/gpdb/issues/9651). 
Adding this change for code consistency between 5x, 6x and 7x and overall stability until we remove resource queues from 7X.

Protect ResCleanupLock callsite with partitionLock

---

README.CentOS.bash
README.Ubuntu.bash

This patch helps add kernel.sem to sysctl.conf, since gpstart/gpinitsystem
may fail with "could not create semaphores: No space left on device".

Add kernel.sem to sysctl.conf.

---

src/backend/storage/smgr/md.c

If the AO table exceeds 1G, it will cause an assertion failure when called _mdfd_openseg().
Fix issue https://github.com/greenplum-db/gpdb/issues/12408.
As PostgreSQL upstream also has the assertion, comment this line for now.
Comment this line, for now, to avoid future pg merge adds back the code.

Fix assertion failure for AO table.

---

gpdb-doc/dita/admin_guide/highavail/topics/g-recovering-a-failed-segment.xml
gpdb-doc/dita/admin_guide/intro/arch_overview.xml
gpdb-doc/dita/admin_guide/managing/monitor.xml
gpdb-doc/dita/install_guide/install_modules.xml
gpdb-doc/dita/utility_guide/ref/analyzedb.xml
gpdb-doc/dita/utility_guide/ref/clusterdb.xml
gpdb-doc/dita/utility_guide/ref/createdb.xml
gpdb-doc/dita/utility_guide/ref/createuser.xml
gpdb-doc/dita/utility_guide/ref/dropdb.xml
gpdb-doc/dita/utility_guide/ref/dropuser.xml
gpdb-doc/dita/utility_guide/ref/reindexdb.xml
gpdb-doc/dita/utility_guide/ref/vacuumdb.xml
gpdb-doc/dita/utility_guide/utility-programs.xml

Some paragraphs/tables had the property otherprops="op-help" set. This was causing issues when viewing the PDF version of the documentation, some text was being hidden.
Removed all references to this property for all xml files. I didn't change some ditamap/ditaval files.

Docs: Removed otherprops value op-help from xml files

---

src/backend/cdb/cdbvars.c
src/backend/commands/analyze.c
src/backend/commands/vacuum.c
src/backend/postmaster/autostats.c
src/backend/postmaster/autovacuum.c
src/backend/tcop/utility.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/commands/vacuum.h
src/include/utils/guc_tables.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/autostats.out
src/test/regress/greenplum_schedule
src/test/regress/sql/autostats.sql

This PR adds the ability to allow autostats to be triggered whenever a table is modified by any user, rather than only when it's modified by the table's owner.
Note that autostats can only be triggered *after* a user has successfully modified the table, ie they must have some kind of write access to the table (INSERT, DELETE, or UPDATE)... so this change will not affect any abilities of users who have no access to the table or only read-only access.  Nevertheless, `gp_autostats_allow_nonowner` GUC is introduced as a way of disabling this behavior in case there is any existing SQL code whose performance depends on table statistics not being up to date after modification by a non-owner.
Only the superuser may modify this GUC.
Existing behavior is maintained when an ANALYZE command is issued …

Autostats skip ownership check

---

src/backend/cdb/cdbvars.c
src/test/regress/expected/autostats.out
src/test/regress/sql/autostats.sql

Also update initial value of gp_autostats_allow_nonowner in cbdvars.c;
This shouldn't matter, but keeping it consistent for readability.
Co-authored-by: Alexandra Wang <walexandra@vmware.com>

Fix autostats test

---

src/backend/executor/nodeMotion.c
src/backend/storage/file/fd.c
src/test/regress/expected/shared_scan.out
src/test/regress/expected/shared_scan_optimizer.out
src/test/regress/sql/shared_scan.sql

Previously in commit 9fbd2da5635eecac6975e7349209373fc9177ef8, we added
special treatment for squelching share input scan by continueing
executing nodes below the CTE producer, so that a CTE consumer on a
differernt slice will not hang while waiting for the producer to finish
writing. However, this previous fix could cause QD crash if there is a
Motion node below the CTE producer, because by the time QD executes
ExecSquelchNode() in mppExecutorFinishup(), the interconnect should have
been teared down already. In this case, there is no way we could
complete executing the CTE producer subtree.
This patch added early return in execMotionUnsortedReceiver() for the
above case and removed an unnecessary assertion that would introduce
crash.

Fix crash on QD when squelching CTE producer with a Motion child

---

src/backend/cdb/cdbmutate.c
src/backend/executor/execMain.c
src/test/regress/expected/initplan.out
src/test/regress/expected/initplan_optimizer.out
src/test/regress/sql/initplan.sql

The slice table is incorrect when the following conditions are met:
1. An init plan is re-used some two or more sub-plans
2. The re-used init-plan contains motion
The root cause is that the number of motion slices and init-plans
are wrongly calculated in apply_motion/apply_motion_mutator.
Assume that there are 2 sub-plans(P1 and P2) that refer to the same
init-plan(I1), i.e. P1.plan_id == P2.plan_id, the number of motion
slice is calculated by walking the plan tree from top to bottom.
When it sees the sub-plan P1 or P2, it walks the referred init-plan,
so the motion under the init plan is re-counted. The number of
init-plans is counted by the number of sub-plans that refer to an
init plan. Both of the P1 and P2 refer to the same init-plan, the
number of init-plan is wrongly counted.
The …

Fix an assert failure that slice table is incorrect

---

src/backend/gpopt/utils/COptTasks.cpp
src/backend/gporca/data/dxl/minidump/NestedSubqLimitBindings.mdp
src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
src/backend/gporca/server/CMakeLists.txt
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

This reopens https://github.com/greenplum-db/gpdb/pull/11866. The intention is to backport to this 
to 6X (and possibly 5X).
In some cases with deeply nested subqueries, an expression can end up being binded
many times. The expression is decorrelated, and the new expression
generated continuously is decorrelated over and over. While this does
work and will properly decorrelate complex trees, it also results in high
optimization times/OOM in severe cases.
Looking at the memo, we are generating new and unique plans. However,
the vast majority of the groups generated are duplicates. I'm not sure
if there's a relatively simple way to prune these away in the current
way we do decorrelation.
This commit adds a guc, optimizer_xform_bind_threshold, to limit the
number of bindings for each group …

Limit number of bindings per group expression in Orca

---

doc/src/sgml/ref/create_table.sgml
doc/src/sgml/ref/psql-ref.sgml

Keep the Greenplum extra command `\dP` because it still exists.
```
gpadmin=# \dP
List of partitioned relations
Schema | Name | Owner | Type | Table
--------+------+-------+------+-------
(0 rows)
```

Resolve leftover PostgreSQL 12 merge conflicts in doc

---

config/orca.m4
configure
gpAux/releng/releng.mk
src/backend/gpopt/utils/COptTasks.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Backport of https://github.com/greenplum-db/gpdb/pull/12574
Corresponding Orca commit "Limit number of bindings per group expression
in Orca"
This commit adds a guc, optimizer_xform_bind_threshold, to limit the
number of bindings for each group expression to a certain value. By
default, this is set to 0 (unlimited). A reasonable value for this would
be 1000 or 10000, but it is query dependent.
Example query affected by this change:
```
create table t (a int) distributed by (a);
explain select a in (
select a from t as t1 where a in (
select a from t as t2 where a in (
select a from t as t3 where a in (
select a from t as t4 join t as t5 using(a) group by t4.a
union
select a from t as t4 join t as t5 using(a) group by t4.a
union
select a from t as t4 join t as t5 using(a) group by t4.a
)
) …
```

Bump Orca version to 3.120.0 and add GUC to limit bindings

---

src/backend/cdb/cdbvars.c
src/backend/commands/analyze.c
src/backend/postmaster/autostats.c
src/backend/postmaster/autovacuum.c
src/backend/tcop/utility.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/nodes/parsenodes.h
src/include/utils/guc_tables.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/autostats.out
src/test/regress/greenplum_schedule
src/test/regress/sql/autostats.sql

Backport of https://github.com/greenplum-db/gpdb/pull/12591
6X_STABLE VACUUM code has been refactored in 7X, so it was not a simple cherry-pick, but the gist of this fix remains the same and so does the tests.

[Backport] Add GUC for allowing autostats to be triggered by non-owners

---

src/backend/cdb/cdbthreadlog.c
src/include/pgtime.h
src/timezone/localtime.c

Currently, `write_log()` is not thread safe, though it should be. The calling trace is:
```
write_log() -> get_timestamp() -> pg_localtime()
```
pg_locatime() is modifying the global variable `struct pg_tm *tm` and when multiple threads calling `pg_localtime()` there's a possibility that makes gpdb crash (See: #11300 ). This PR is trying to make `write_log()` thread safe by introducing a new thread safe function `pg_localtime_thread_safe()` without modifying the interface or function body of the original `pg_locatime()`.
I haven't crafted a test since I have no idea how to test this change. It would be great if somebody can help me :-)

Trying to make write_log() thread safe.

---

src/backend/executor/execCurrent.c
src/test/regress/expected/portals_updatable.out
src/test/regress/expected/portals_updatable_optimizer.out
src/test/regress/sql/portals_updatable.sql

Based on 6X_STABLE behavior, the desirable error message is
'cursor "c" is not a simply updatable scan of table "tidscan"'.
The reason of reporting "Unexpected internal error" on master
branch is because the commit "updatable evaluation for partition
table" 20ae004 limited the simply updatable check to partitioned
table and temporary table, the ordinary table skipped the check
and proceeded then failed at the empty tuple slot check.
Also, PG12 removed tuple slot allocation from LIMIT plan node,
intended to save some cost and separate the determination of the
result type from the slot creation(refer to postgres/postgres@1ef6bd2).
This causes the empty tuple slot check failed in above scenario.
To be consistent with the design, a straightforward fix should
be applying "simply-updatable" …

Fix cursor CURRENT OF operation reported wrong error message

---

src/backend/access/bitmap/bitmaputil.c
src/test/isolation2/expected/bitmap_update_words_backup_block.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_update_words_backup_block.sql

Bitmap indexes bitmap pages don't use standard buffer page
structure. These store the hwords and cwords as part of page content,
which forms the full page content of the
page. `XLOG_BITMAP_UPDATEWORD` and `XLOG_BITMAP_UPDATEWORDS` WAL
records incorrectly set `buffer_std to true` when writing WAL. This
caused backup block created to be empty for these pages as it conveys
hole start as 24 and length as 32728 (which essentially maps to entire
page to skipped from backed up). We should be copying full 32K page as
backup block for bitmap pages.

Fix backup block logic for Bitmap index bitmap pages

---

concourse/pipelines/templates/gpdb-tpl.yml
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/sbin/gpgetstatususingtransition.py
gpMgmt/test/behave/mgmt_utils/gpstate.feature

when the environment does not has a $HOSTNAME database present,
gpstate command throwing FATAL error on master logs
solution: Try to utilize the default DB defined in PGDATABASE from
gpstate

gpstate throws cosmetic errors when gpadmin database is not present

---

src/test/isolation2/expected/bitmap_index_crash.out
src/test/isolation2/sql/bitmap_index_crash.sql

Test validates meta-page is read from disk during bitmap LOV item
insert replay. There used to be bug such that if the metapage is not
present in shared buffers, it will not be fetched from disk. Instead,
a zeroed out page will be returned from memory. A subsequent flush of
the metapage will lead to an inadvertent permanent overwrite.
Luckily, the bug if fixed on this branch via usage of API
`XLogReadBufferForRedo()` which already supplies `RBM_NORMAL`. Having
test to cover the code path is always better.

Bitmap index replay test focused on meta-page not in shared_buffers

---

src/backend/commands/copy.c
src/test/regress/expected/copy_eol.out
src/test/regress/greenplum_schedule
src/test/regress/input/gpcopy.source
src/test/regress/output/gpcopy.source
src/test/regress/sql/copy_eol.sql

The copy command read data from a file and process data once a character.
In non-CSV mode, anything after a backslash is skipped over, so that the EOL
character after a backslash can not be recognized.
An example file with content:
1, message1
2, message2`\`
3, message3
The copy from the command will fail because line2 and line3 will be regarded as one line.
This pr also fixes other EOL: '\r', '\r\n', keep the same behaviour with 5x.
This commit cherry-pick from commit e07d84948f587ef9c250f6ce358b2c14b012e9a6 which has
been reverted because of different behaviour of echo on ubuntu18. Use printf with an absolute
path instead.
Co-authored-by: zhaorui <zhaoru@vmware.com>

Fix copy command EOL

---

src/backend/cdb/cdbcopy.c
src/backend/postmaster/pgstat.c
src/include/pgstat.h

For the bitmapset, it requires a signed integer as its value, but
for Oid, it is an unsigned integer. Therefore, if we meet an oid value
big enough, the overflow issue is triggered. Using a list instead of bitmapset
to record distinct oid value in function `pgstat_combine_one_qe_result`.
Fix issue: #12270

Oid bitmapset retire in pg_stat

---

src/include/catalog/catversion.h

Forget to do this in the parallel retrieve cursor code.

Bump catalog version for the parallel retrieve cursor feature.

---

concourse/pipelines/templates/gpdb-tpl.yml
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/sbin/gpgetstatususingtransition.py
gpMgmt/test/behave/mgmt_utils/gpstate.feature

when the environment does not has a $HOSTNAME database present,
gpstate command throwing FATAL error on master logs
solution: Try to utilize the default DB defined in PGDATABASE from
gpstate

[backport 6X]gpstate throws cosmetic errors when gpadmin database is not present

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query37.ans
gpMgmt/bin/gpload_test/gpload2/query40.ans
gpMgmt/bin/gpload_test/gpload2/query44.ans

add max_retries feature
add more information of standard_conforming_strings when creating staging table sql failed
the logic of recognizing gpdb version still remains unchanged, which is different from 6X but right.

make gpload code same with 6x, add feature max_retries

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

docs for https://github.com/greenplum-db/gpdb/pull/12574, https://github.com/greenplum-db/gpdb/pull/12619,  https://github.com/greenplum-db/gpdb/pull/12620
add the server configuration parameter to the reference guide.
this will be backported to 6X_STABLE, 5X_STABLE.

docs - for new GPORCA guc optimizer_xform_bind_threshold

---

gpMgmt/bin/gpload_test/gpload2/TEST.py

fix gpload 5x max_retries test fail
gpload test case for max_retries is not stable in docker.
We can only do retry when error message contains `time out`. However, sometimes it returns `network error` and that will lead to test case failure. 
I annotate the case for max_retires to avoid failure. We will see if there is any better solution.

fix gpload 5x max_retries test fail

---

contrib/postgres_fdw/postgres_setup.bash

The script fails on the pipeline when downloading postgres source from
the URL for testing postgres_fdw tests. This is because there are new
updated certificates.
This commit adds a temporary workaround to skip the certificate check
for now.

Updating postgres_setup.bash to skip certificate check

---

gpdb-doc/dita/install_guide/install_modules.xml
gpdb-doc/dita/install_guide/migrate.xml
gpdb-doc/dita/ref_guide/modules/gp_legacy_string_agg.xml
gpdb-doc/dita/ref_guide/modules/intro.xml
gpdb-doc/dita/ref_guide/modules/modules.ditamap

document the new gpcontrib single-argument string_agg() function.  note that this function was not previously documented in greenplum 5.  in this PR:
- include gp_legacy_string_agg in the list of additional supplied modules.
- update the migrate topic mention to reference the new module.
- add a separate topic for the module which identifies how to install/register/use it.
doc review site link for new topic:  https://docs-lisa-legacy-stringagg.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/modules/gp_legacy_string_agg.html (behind vpn)

docs - add content for new gp_legacy_string_agg gpcontrib module

---

gpdb-doc/dita/admin_guide/workload_mgmt.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

clarify use of virtual CPU cores and primary segments in the calculation of this server configuration parameter.

docs - clarify the desc of gp_resqueue_priority_cpucores_per_segment

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

Adding documentation for GUC quote_all_identifiers. 
Needs to be merged to master and 6x.
Re: parameter categories, I have not added it under any of the existing categories. Would any of them fit?
I thought about [Past Version Compatibility Parameters](https://gpdb.docs.pivotal.io/6-17/ref_guide/config_params/guc_category-list.html#topic48) since it is used when upgrading from 5.x to 6.x but not sure if it fits.
Preview site: https://mireia-quote-all-identifiers.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html#quote_all_identifiers

Docs: Added GUC quote_all_identifiers

---

concourse/tasks/ic_gpdb.yml

It shouldn't be required for the interconnect test which uses the same
task.yml file
Authored-by: Karen Huddleston <khuddleston@vmware.com>

Make postgres_for_fdw input optional

---

src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Previously, if we had a query such as
`select count(*)  from (select trim(regexp_split_to_table((a)::text, ','::text)) from bar)a;`
Orca would consider the `trim()` function as a non-set returning function (SRF) and optimize away
the function call, leading to incorrect results. Because
`regexp_split_to_table` is a SRF, we must also consider `trim` to be a
SRF and evaluate the nested function.
Orca will now check the nested functions too. If any of these DXL
children are a SRF, the outer function is also marked as set-returning.

Fix wrong results with nested SRF in Orca

---

src/backend/cdb/dispatcher/cdbdisp_async.c

After the sequence refactor in eae1ee3fbead8baad3803c64de8cbee07d076d9e,
an INSERT query on a table with a sequence column is not cancellable in
some cases. Specifically, if the QE makes a nextval request, the QD
should process any interrupts, or the QD could continuously receive
requests and never check for interrupts while it's in
checkDispatchResult(). There was no measurable overhead difference with
adding this check.

Add CHECK_FOR_INTERRUPTS call when processing sequence nextval().

---

gpdb-doc/dita/admin_guide/intro/about_statistics.xml
gpdb-doc/dita/best_practices/analyze.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

docs for https://github.com/greenplum-db/gpdb/pull/12591, https://github.com/greenplum-db/gpdb/pull/12624.
add guc reference for new gp_autostats_allow_nonowner guc.  misc updates to existing topics about automatic stats collection.
question:  what is greenplum's behaviour when this guc is set to true and gp_autostats_mode=on_no_stats?
this will be backported to 6X_STABLE.

docs - for new guc gp_autostats_allow_nonowner

---

gpdb-doc/dita/best_practices/sysconfig.xml
gpdb-doc/dita/install_guide/prep_os.xml

Ref https://github.com/greenplum-db/gpdb/issues/12329
Core dump instructions should be part of the Install Guide rather than Best Practices.
Preview page:
https://mireia-core.sc2-04-pcf1-apps.oc.vmware.com/7-0/install_guide/prep_os.html#topic3__core_dump

Docs: moved core dump instructions to install guide

---

src/backend/libpq/ip.c
src/backend/libpq/test/Makefile
src/backend/libpq/test/ip_test.c
src/backend/postmaster/postmaster.c
src/port/getaddrinfo.c

This PR backports two upstream Postgres commits:
https://github.com/postgres/postgres/commit/c424d0d1052cb4053c8712ac44123f9b9a9aa3f2
https://github.com/postgres/postgres/commit/1997f34db4687e671690ed054c8f30bb501b1168
The above two patches were missed in a previous backport commit:
https://github.com/greenplum-db/gpdb/commit/a9768e32a0a310bd7e7a45c089898542670bf2c2
Due to the incomplete backport, we see invalid WARNING logs whenever connecting to the coordinator segment using a UNIX socket (e.g. `psql postgres vs. psql -h cdw postgres`) when the `log_hostname` GUC was enabled on the coordinator segment.  Example warning message in the logs: `"WARNING","01000","pg_getnameinfo_all() failed: Non-recoverable failure in name resolution",,,,,,,0,,"postmaster.c",6569`.  The WARNING is harmless …

Remove NI_NUMERICHOST and NI_NUMERICSERV checks in getnameinfo()

---

src/backend/cdb/cdbsubselect.c
src/backend/optimizer/plan/subselect.c
src/include/cdb/cdbsubselect.h
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect_gp.sql

For fix the issue #12656 we need to keep DISTINCT ON clause and ORDER BY clause in SubQuery when pulling up sublinks of ANY type, to ensure that the planner can de-duplicate according to the correct logic.
Not only for DISTINCT ON, the ORDER BY clause should be reserved too, the following example illustrates why we need to keep the ORDER BY clause:
```
postgres=# select version();
version                                                
------------------------------------------------------------------------------------------------------
PostgreSQL 12.8 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit
(1 row)
postgres=# create table test_table(i int, tz timestamptz);
postgres=# insert into test_table values (1, '2021-01-01'), (1, '2021-02-01'); …
```

Do not drop DISTINCT ON clause and ORDER BY clause in `pull_up_sublinks`

---

src/backend/gporca/concourse/test_orca_pipeline.yml

Download postgres from gcs rather than public internet.  This fixes a certificate verification issue with postgres_fdw.
See:
https://github.com/greenplum-db/gpdb/commit/d81557c4884281a3b502228da24fdbda361e06c3

[6X] concourse/test_orca_pipeline.yml: Download pg from gcp to avoid cert error

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmaputil.c
src/backend/utils/adt/selfuncs.c
src/test/isolation2/expected/bitmap_union.out
src/test/isolation2/expected/bitmap_union_optimizer.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_union.sql

In previous refactor which try to resolve issue:
https://github.com/greenplum-db/gpdb/issues/11308.
We change the way to calculate the firstTid holding in the
current position batch words, since concurrent insert will cause
the wrong tid matching in words_get_match().
To fix that issue in PR https://github.com/greenplum-db/gpdb/pull/11377,
we always get the correct firstTid from the bitmap index page.
But _bitmap_union is not touched. It was responsible to union bitmap
batch words for multivalues index scan like `where x in (x1, x2)` or `x > v`.
And also the logic for the catch up loop is not correct in
_bitmap_catchup_to_next_tid, it should check remain words number.
Co-authored-by: Junfeng Yang <yjerome@vmware.com>

Correct the real firstTid in _bitmap_union

---

src/backend/optimizer/plan/subselect.c
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/shared_scan.out
src/test/regress/expected/shared_scan_optimizer.out
src/test/regress/sql/gporca.sql
src/test/regress/sql/shared_scan.sql

This PR fix #12701 .
Current code logic is trying to enable CTE sharing in subplan automatically (but ignores the gp_cte_sharing GUC, maybe it's also a bug).
https://github.com/greenplum-db/gpdb/blob/baa0c336b43f7d907ee6d3ca3758898e8495eea9/src/backend/optimizer/plan/subselect.c#L604-L611
It is fixup_subplans() that copy subplan and leads to mismatch of the length of subplans and subroot. And apply_shareinput_xslice() cannot make it correct when shared plan is in subplan, then an assert of panic happened (please see the repro of issue).
Trying to keep the length consistent (todo something in copy subplan and root) is a bit complicated. Considering the gp_cte_sharing GUC is off in default, so I think disable all CTE sharings in subquery is an acceptable workaround.

[6X] disable cte sharing in subplan

---

src/interfaces/libpq/fe-connect.c

libpq connection options as returned by PQconndefaults() have a
"dispchar" field that determines (among other things) whether an option
is a "debug" option, which shouldn't be shown by default to clients.
postgres_fdw makes use of that to control which connection options to
accept from a foreign server configuration.
Curiously, the "options" option, which allows passing configuration
settings to the backend server, was listed as a debug option, which
prevented it from being used by postgres_fdw.  Maybe it was once meant
for debugging, but it's clearly in general use nowadays.
So change the dispchar for it to be the normal non-debug case.  Also
remove the "debug" reference from its label field.
Reported-by: Shinoda, Noriyoshi <noriyoshi.shinoda@hpe.com>
(cherry picked from commit …

[6X]libpq: Change "options" dispchar to normal

---

src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
src/backend/gporca/server/include/unittest/dxl/statistics/CBucketTest.h
src/backend/gporca/server/src/unittest/dxl/statistics/CBucketTest.cpp

When intersecting two empty histogram buckets, we expect the result
histogram bucket to be empty too.
This patch avoids the edge case of CDouble(0) / CDouble(0) = 1 when
calculating the m_frequency of the result bucket.
Fixes #12750.

ORCA: Avoid divide-by-zero when intersecting histogram buckets

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/join_gp.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/sql/join_gp.sql

I introduced this bug in commit dc92cc92 by forgetting the
else-clause to let to code fall through. This might lead to
a wrong plan that choose inner join instead of semi join.
The following case is an example:
```
create table t1(a int, b int);
create table t2(a int, b int);
insert into t1 select i,i from generate_series(1, 100)i;
insert into t2 select i,i from generate_series(1, 4)i;
insert into t2 select i,i from generate_series(1, 4)i;
create unique index idx on t1(a);
analyze;
explain
select * from
(
select a from t1 where a < 3 -- index only scan
) x (a)
where x.a + 1 in (select distinct b from t2);
select * from
(
select a from t1 where a < 3 -- index only scan
) x (a)
where x.a + 1 in (select distinct b from t2);
```
Let's take a deep look at the above case:
- first, the distinct …

(6x only) Fix wrong plan of dedup semi join.

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
src/backend/commands/tablecmds.c
src/backend/parser/gram.y
src/include/nodes/parsenodes.h
src/test/regress/expected/alter_distribution_policy.out
src/test/regress/expected/gpdist.out
src/test/regress/expected/gpdist_optimizer.out
src/test/regress/expected/partition_expand.out
src/test/regress/sql/partition_expand.sql

The policy of leaves can be different from the policy of root, But it must follow below rules:
1、If a partitioned table is Hash distributed, then all its leaf partitions must also be Hash partitioned on the
same distribution key, with the same 'numsegments', or randomly distributed with the same 'numsegments'.
2、If a partitioned table is Randomly distributed, then all the leaves must be randomly distributed as well.
we expand leaf partitions separately in parallel rather than expand root partition in one shot through two steps:
Step1:
BEGIN;
Lock all root/interior/leaf partitions
Change all numsegments of root/interior/leaf partitions to size of cluster;
Change all leaf partition to random distributed;
COMMIT;
Step2:
Change all leaf partition's policy back to parent's policy with set …

Expand partition table in parallel

---

src/backend/utils/misc/guc_gp.c

This is the warning:
guc_gp.c:4063:4: warning: initialization of 'int' from 'void *'
makes integer from pointer without a cast [-Wint-conversion]
4063 |    NULL,
|    ^~~~
That happens because there was an extra field in the struct that
described gp_dispatch_keepalives_count GUC (introduced in
https://github.com/greenplum-db/gpdb/commit/d673b309ce571932fbf887ae25182d28dac913b7).

Fix compilation warning for gp_dispatch_keepalives GUC

---

src/backend/cdb/cdbresynchronizechangetracking.c

The assertion was added back in 2017 to make sure that change tracking
was disabled when change tracking logs get partially written or
corrupted (mostly due to disk full or other disk issues). However, it
was not noticed that gpaddmirrors goes through the same code path with
mode PMModeMirrorlessSegment (mostly because our gpaddmirrors
automated tests used to run on non-assert builds). The assertion would
always fail when running gpaddmirrors because getFileRepRoleAndState()
only returns valid values for PMModePrimarySegment and
PMModeMirrorSegment. Modify the assertion to make an exception for
gpaddmirrors.
GPDB commit reference:
https://github.com/greenplum-db/gpdb/commit/a0cc23d497a001c82b6cff07d5143be6f2e322b1
This PR fixes the gpaddmirrors job in the 5X_STABLE_with_asserts pipeline …

Modify change tracking disabled assertion to work with gpaddmirrors

---

src/backend/postmaster/autostats.c
src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c
src/test/isolation2/expected/resource_queue.out
src/test/isolation2/expected/resource_queue_deadlock.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue.sql
src/test/isolation2/sql/resource_queue_deadlock.sql

Fix waiting on resqueue regular lock doesn't trigger deadlock detection
Since PG9.6, deadlock timeout mechanism was changed greatly compared
to the version before. Because resqueue lock is based on regular lock,
we need modify the correspoding deadlock detection mechanism on resqueue
lock accordingly.
fix issue #9651

fix ResProcSleep doesn't trigger deadlock check

---

src/backend/gporca/data/dxl/minidump/ExpandJoinOrder.mdp
src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-CompsiteKey-NoMotion.mdp
src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-DistKey-Multiple-Predicates.mdp
src/backend/gporca/data/dxl/minidump/LOJ-IndexApply-MultiDistKeys-IndexKeys.mdp
src/backend/gporca/data/dxl/minidump/LeftJoinDPv2JoinOrder.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
src/backend/gporca/server/CMakeLists.txt

The optimization cost model in Orca biases against NLJs. In the DPv2
(exhaustive2) join order transform, we penalized cross joins; however,
we did not penalize other joins that would generate a NLJ. This resulted
in generating join orders that were costed very low in the xform
generation, but very high in the optimization cost model later on,
causing poor plans to be chosen.
Now, we more generally check whether there is a hashable predicate for
the join in the DPv2 xform. If there isn't, we penalize the join similarly to
the real cost model.
Looking at the plan changes in our performance pipelines, most were very minor (<1% cost change,
either better or worse). However, there were significant cost decreases
in some cases. This is primarily due to NLJs getting pushed lower down
the plan …

Improve exhaustive2 algorithm to penalize predicates that create NLJs

---

src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h

Explicitly defefault copy assignment operator for SGroupAndExpression.
Without this, we would get below compile error with Clang++-13 and above
with -std=c++14.
```
In file included from CJoinOrderDPv2.cpp:12:
../../../../../../src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h:187:3: error: definition of implicit copy assignment operator for 'SGroupAndExpression' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
SGroupAndExpression(const SGroupAndExpression &other) = default;
^
CJoinOrderDPv2.cpp:1083:24: note: in implicit copy assignment operator for 'gpopt::CJoinOrderDPv2::SGroupAndExpression' first required here
left_child_expr_info = GetBestExprForProperties(
^
1 error generated.
```

Fix clang++-13 compile error

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmapinsert.c
src/backend/access/bitmap/bitmapsearch.c
src/backend/access/bitmap/bitmaputil.c
src/backend/optimizer/path/indxpath.c
src/backend/utils/adt/selfuncs.c
src/include/access/bitmap.h
src/test/isolation2/expected/bitmap_index_concurrent.out
src/test/isolation2/expected/bitmap_union.out
src/test/isolation2/expected/bitmap_union_optimizer.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_index_concurrent.sql
src/test/isolation2/sql/bitmap_union.sql

As commit f37efbc6f268e59d0a5478fe5b83e75f8780b671 was reverted due to regression with incorrect results.
In this PR, bring commit 3420e7701acdf176126c8ef7ece19070862336ce back and also include the commit 0005bb8aeed7373aec58ecefa662955e000a2423 which fixes the regression.
Before these two commits, concurrent scan on bitmap index when there's insert running in the
backend may cause the bitmap scan read wrong tid.
The second commit fixes the issue that the firstTid is not updated in _bitmap_union() and the logic for _bitmap_catchup_to_next_tid is not correct.

Backport bitmap index scan when concurrent insert update full bitmap page on 6X_STABLE

---

gpdb-doc/dita/utility_guide/ref/gpmt.xml

Modified GPMT home page:
- Under synopsis, Separate the help, verbose and version option.
- Give only global options - same as in online help
- Divide tools into GPDB and MISC as in online help
- Add examples same as from online help
Preview site:
https://mireia-gpmt.sc2-04-pcf1-apps.oc.vmware.com/7-0/utility_guide/ref/gpmt.html

Docs: improved gpmt home page

---

src/backend/executor/nodeWindowAgg.c
src/backend/utils/mmgr/aset.c
src/backend/utils/mmgr/mcxt.c
src/backend/utils/mmgr/test/Makefile
src/backend/utils/mmgr/test/mcxt_test.c
src/include/utils/memutils.h

The existing version of MemoryContextContainsGeneric(context, pointer) reads the 24 bytes of memory preceding the pointer passed to it, casts it to a StandardChunkHeader, and returns true or false based on whether the address stored at header->sharedHeader matches any of the addresses in the context->sharedHeaderList.
This was an improvement  over MemoryContextContains(context, pointer), which dereferences header->sharedHeader causing an immediate crash if header->sharedHeader is not a valid pointer (which is the case, whenever it points to a memory structure not aligned with the beginning of a chunk allocated with palloc()).  But several problems with it remained.
As with MemoryContextContains(), the present version of MemoryContextContainsGenericAllocation works fine for pointers which …

Replace MemoryContextContainsGenericAllocation() with a more robust version

---

src/test/isolation2/expected/segwalrep/recoverseg_from_file.out
src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql

PR9974 introduced case 'segwalrep/recoverseg_from_file' to guard
the fix to issue #9837, but the case is not able to do that. Because the
content of configure in it is not suitable, which will not
trigger function __callSegmentAddMirror when executing 'gprecoverseg -i xxx'.

fix incorrect isolation2 case segwalrep/recoverseg_from_file

---

src/backend/executor/nodeModifyTable.c

GPDB-specific junk attributes elog info is not correct.
For now elog info of segid_attno attribute is "action is NULL".
and elog info of action_attno attribute is "gp_segment_id is NULL".

to #12808 Fix elog info of ExecModifyTable function is not suitable. 

---

src/backend/cdb/cdbpullup.c
src/test/regress/input/gpcopy.source
src/test/regress/output/gpcopy.source

The function cdbpullup_findEclassInTargetList, if passed a valid HashOpFamily,
it will not only check the EquivalenceClass in the targetlist, but also check
the EquivalenceClass is hashable under the given HashOpFamily. Previous code
using get_opfamily_member to verify if it is hashable, this is too strict,
for example, both OpClass hash/varchar_ops and hash/text_ops belong to OpFamily
text_ops, but in OpFamily hash/text_ops, there is only one operator and it only
handles text type (this statement only holds for current version, I check later
version Postgres, small changes, including name type). That's why if the simply
invoking get_opfamily_member is not enough here since it does not consider type
compatible, like varchar is binary compatible with text.
Consider a detailed case:
``` …
```

(6x) Fix bug: cdbpullup_findEclassInTargetList not consider compatible types.

---

gpMgmt/bin/gpload.py

1. It is not necessary to create dataflow extension when gpload connect
to gpdb5.
2. If there's no GUC or not text format is used, do not create
dataflow extension even gpload connect to gpdb6 or above

Do not create dataflow extension for gpdb5

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_data_format.py
gpMgmt/bin/gpload_test/gpload2/data/external_file_253.txt
gpMgmt/bin/gpload_test/gpload2/data/external_file_254.csv
gpMgmt/bin/gpload_test/gpload2/data/external_file_255.txt
gpMgmt/bin/gpload_test/gpload2/data/external_file_256.csv
gpMgmt/bin/gpload_test/gpload2/data/external_file_257.txt
gpMgmt/bin/gpload_test/gpload2/data/external_file_258.csv
gpMgmt/bin/gpload_test/gpload2/data/external_file_259.txt
gpMgmt/bin/gpload_test/gpload2/data/external_file_260.csv
gpMgmt/bin/gpload_test/gpload2/query253.ans
gpMgmt/bin/gpload_test/gpload2/query254.ans
gpMgmt/bin/gpload_test/gpload2/query255.ans
gpMgmt/bin/gpload_test/gpload2/query256.ans
gpMgmt/bin/gpload_test/gpload2/query257.ans
gpMgmt/bin/gpload_test/gpload2/query258.ans
gpMgmt/bin/gpload_test/gpload2/query259.ans
gpMgmt/bin/gpload_test/gpload2/query260.ans
gpMgmt/doc/gpload_help

Introduce an optional NEWLINE gpload INPUT configuration. This
configuration will in turn be passed to the create external table
FORMAT configuration.
An example of this usage is for the handling of DOS formatted
files (CRLF terminated lines). If used, instead of erroring out, we
can now load data with embedded CR or LF characters in text fields. To
allow this, an optional line termination NEWLINE field ('CR', 'LF',
'CRLF') has been introduced into the gpload INPUT configuration.
The gplaod REUSE_TABLES option is also supported.
The change validates with CSV and TXT file formats.
The change validates an error is received when using an unsupported
NEWLINE value.
The change adds the ability to specify "None" for the 'delimiter' test
configuration. This allows a CSV testing to generate a …

gpload: Add INPUT configuration NEWLINE support.

---

src/backend/executor/nodeAgg.c
src/backend/executor/nodeWindowAgg.c
src/backend/utils/mmgr/aset.c
src/backend/utils/mmgr/mcxt.c
src/backend/utils/mmgr/test/Makefile
src/backend/utils/mmgr/test/mcxt_test.c
src/include/utils/memutils.h

The existing version of MemoryContextContains(context, pointer) reads the 8 bytes in memory preceding the pointer passed to it, and returns true or false based on whether it matches the address of context.
This method works well for pointers which point to the beginning of a memory chunk allocated by palloc(), but is not safe to call when the pointer points to an offset into a chunk of memory.  In that case, it will likely return false, but has the potential to return true (a "false positive" result) if the bytes in memory immediately preceding pointer happen to match this address.
In postgres, the pointers passed to it point to the beginning of a chunk.  But in gpdb, that's often not the case... so this function can cause cause a crash if these unlikely circumstances occur.  It's a bit …

Replace MemoryContextContains() with a more robust version

---

concourse/scripts/compile_gpdb.bash

We plan to use OS provided libzstd for clients.

Revert vendor libzstd for clients in GPDB7.

---

src/backend/cdb/dispatcher/cdbdisp_async.c

Demote and clarify a dispatcher log message:
this log is printed on a broken connection, the previous message is misleading to user.
Fixes Github issue #10955
Reviewed by: paul-guo-
(cherry picked from commit a76a939819adb3998e610add22bd751b5221bf15)

[6X Backport] Fix misleading log: libpq says we are still busy (#12101)

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_constraint.xml

Added missing columns based on https://www.postgresql.org/docs/9.1/catalog-pg-constraint.html and 6.18.1 environment.

Docs: added missing columns in doc for pg_constraint table

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_enum.xml

Added missing column based on https://www.postgresql.org/docs/9.4/catalog-pg-enum.html and 6.18.1 environment.

Docs: added missing columns in doc for pg_enum table

---

src/backend/executor/nodeShareInputScan.c
src/backend/storage/file/buffile.c
src/test/regress/input/temp_tablespaces.source
src/test/regress/output/temp_tablespaces.source

Backport the commit 93f03dad824f14f40519597e5e4a8fe7b6df858e
from upstream, to ensure that PrepareTempTablespaces() is always
called if needed.
```
Make BufFileCreateTemp() ensure that temp tablespaces are set up.
If PrepareTempTablespaces() has never been called in the current
transaction, OpenTemporaryFile() will fall back to using the default
tablespace, which is a bug if the user wanted temp files placed elsewhere.
gistInitBuildBuffers() appears to have this disease already, and it
seems like an easy trap for future coders to fall into.
We discussed other ways to close this gap, but none of them are prettier
or more reliable than just having BufFileCreateTemp do it.  In particular,
having fd.c do this creates layering issues that we could do without.
Per suggestion from Melanie …
```

Ensure PrepareTempTablespaces() is called when using temp tablespaces

---

gpdb-doc/dita/ref_guide/gp_toolkit.xml

Added missing column based on engineering input and version 6.18.1

Docs: added missing column in doc for gp_log_master_concise

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

Opening PR against 6X_STABLE as some GUCs were not available on master branch.

Docs: changed set classification values for some gucs

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_trigger.xml

Table missing columns, updated as per https://www.postgresql.org/docs/9.1/catalog-pg-trigger.html and referenced with version 6.18.1.

Docs: added missing columns to table pg_trigger

---

gpdb-doc/dita/utility_guide/ref/psql.xml

The output of command "\d my_table" was displaying incorrect information.

Docs: corrected output from psql reference

---

gpdb-doc/dita/utility_guide/ref/gpcheckperf.xml

netperf has now migrated to github. Updated references to http://www.netperf.org/ with new link https://github.com/HewlettPackard/netperf

Docs: changed path to download netperf

---

contrib/pg_upgrade/check.c
contrib/pg_upgrade/pg_upgrade.h
contrib/pg_upgrade/version.c

This check is not necessary for a 5X->6X upgrade, as we don't support
the line datatype in 5X. Recently, the 9_4_STABLE merge commit
af96694494c, brought in upstream fixes 235a52ca0f2 and 56c06999d3c,
which added a recursive CTE to search for the line datatype in
composite types, domains, arrays and ranges. A recursive CTE, when
executed on a 5X cluster results in:
ERROR:  RECURSIVE option in WITH clause is not supported
So, in this commit we compile these functions out.

6X: Disable pg_upgrade check for line datatypes

---

src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
src/backend/gporca/server/include/unittest/gpopt/xforms/CSubqueryHandlerTest.h
src/backend/gporca/server/src/unittest/gpopt/xforms/CSubqueryHandlerTest.cpp
src/test/regress/expected/subselect_optimizer.out

Commit bc4a66ebba9 in repo gp-qp-orca removed code in the preprocessor
that converted an ANY/ALL subquery with child CLogicalConstTableGet
into a disjunction (conjunction) of equalities.  After that code was
removed assertions in FRemoveAnySubquery and FRemoveAllSubquery became
invalid.
Commit eb9d1f0504a contained in Postgres 9.4.26 merge (commit
af96694494c) exposed this invalid assertion.

Remove stale assertion in ORCA

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

The config file postgresql.auto.conf might not the same across
QD or QEs. While execute gpexpand, copy this file from master
is not correct. We should copy them from segment for newly added
segments.
In master branch it is not easy to add a normal case by alter system,
because we dispatch AlterSystem statement to QEs. We add the
case based on the advice in
https://github.com/greenplum-db/gpdb/pull/12212#issuecomment-880255593
Authored-by: Miao Chen <miaochen@mail.ustc.edu.cn>
--------
This is a pre-port version of https://github.com/greenplum-db/gpdb/pull/12212
We hit the issue in some practical env.

Copy postgresql.auto.conf from segment while gpexpand.

---

src/backend/cdb/cdbsubselect.c
src/backend/optimizer/plan/subselect.c
src/include/cdb/cdbsubselect.h
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect_gp.sql

For fix the issue #12656 we need to keep DISTINCT ON clause and ORDER BY clause in SubQuery, to ensure that the planner can de-duplicate according to the correct logic.
Not only for DISTINCT ON, the ORDER BY clause should be reserved too, the following example illustrates why we need to keep the ORDER BY clause:
```
postgres=# create table test_table(i int, tz timestamptz);
postgres=# insert into test_table values (1, '2021-01-01'), (1, '2021-02-01');
postgres=# select * from test_table where (i, tz) in
(select distinct on (i) i, tz from test_table order by i, tz desc);
i |           tz
---+------------------------
1 | 2021-02-01 00:00:00+00
(1 row)
postgres=# select * from test_table where (i, tz) in
(select distinct on (i) i, tz from test_table order by i, tz asc);
i |           tz …
```

[6X] Do not drop DISTINCT ON clause and ORDER BY clause in pull_up_sublinks

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

For command ALTER SYSTEM, will modify the config file postgresql.auto.conf, while execute gpexpand, copy this file from master is not correct.

The postgresql.auto.conf should copy from segment

---

gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
gpMgmt/bin/gpstart
gpMgmt/test/behave/mgmt_utils/gpstart.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Restricted mode mentioned in log when using -R option along with gpstart -m.
Updated respective unit tests.
Co-authored-by: Deena Venkatesan <vdeenathayal@vmware.com>

Updating logs for restricted mode along with gpstart -m

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

This reverts commit e3e95865e77828ee97711e99bebcaafe59d926c9.
gpexpand job becomes red since previous commit, revert first and
wait for later fixing.

Revert "Copy postgresql.auto.conf from segment while gpexpand. (#12212)"

---

concourse/scripts/regression_tests_gpcloud.bash
gpcontrib/gpcloud/bin/dummyHTTPServer.py
gpcontrib/gpcloud/include/s3utils.h
gpcontrib/gpcloud/lib/ini.cpp
gpcontrib/gpcloud/lib/ini.h
gpcontrib/gpcloud/regress/Makefile
gpcontrib/gpcloud/regress/input/1_16_multiple_files_with_header_line.source
gpcontrib/gpcloud/regress/input/5_01_normal_http_param.source
gpcontrib/gpcloud/regress/input/5_02_normal_https_param.source
gpcontrib/gpcloud/regress/output/1_16_multiple_files_with_header_line.source
gpcontrib/gpcloud/regress/output/5_01_normal_http_param.source
gpcontrib/gpcloud/regress/output/5_02_normal_https_param.source
gpcontrib/gpcloud/regress/regress_schedule
gpcontrib/gpcloud/src/s3conf.cpp
gpcontrib/gpcloud/src/s3utils.cpp
gpcontrib/gpcloud/test/Makefile
gpcontrib/gpcloud/test/data/s3httptest.conf
gpcontrib/gpcloud/test/s3conf_test.cpp

Now the s3 external table get params from local files in the location file path after "config=" which relies on the file exists on each segment locally. But for cloud users, the users cannot settle each config file on each segment. 
So this pr provides a way for each s3 external table QE get params from http/https server whose address is configured after the "server=" string. So if you are using the "server=" string in the location, you need to start the http/https server by yourself. In this way, the s3 accessid and secret key will not have to be written into configfile on the segment locally which is safer than before.
If you set both "config=filepath" and "server=httpaddress" at the same time, it will only try to get params from http server. If it fails, the s3 segments will fail to …

Add S3 external table getting parameters from http/https server function for 6X.

---

gpMgmt/bin/gpload.py
gpMgmt/doc/gpload_help

backport pr #12739 in master to 5X
Introduce an optional NEWLINE gpload INPUT configuration. This
configuration will in turn be passed to the create external table
FORMAT configuration.
An example of this usage is for the handling of DOS formatted
files (CRLF terminated lines). If used, instead of erroring out, we
can now load data with embedded CR or LF characters in text fields. To
allow this, an optional line termination NEWLINE field ('CR', 'LF',
'CRLF') has been introduced into the gpload INPUT configuration.
The gplaod REUSE_TABLES option is also supported.
The change validates with CSV and TXT file formats.
The change validates an error is received when using an unsupported
NEWLINE value.
The change adds the ability to specify "None" for the 'delimiter' test
configuration. This …

add gpload input newline config

---

concourse/scripts/regression_tests_gpcloud.bash
gpcontrib/gpcloud/bin/dummyHTTPServer.py
gpcontrib/gpcloud/include/s3utils.h
gpcontrib/gpcloud/lib/ini.cpp
gpcontrib/gpcloud/lib/ini.h
gpcontrib/gpcloud/regress/Makefile
gpcontrib/gpcloud/regress/input/1_09_partition.source
gpcontrib/gpcloud/regress/input/1_16_multiple_files_with_header_line.source
gpcontrib/gpcloud/regress/input/3_05_insert_to_wet_from_ret.source
gpcontrib/gpcloud/regress/input/3_06_special_characters.source
gpcontrib/gpcloud/regress/input/5_01_normal_http_param.source
gpcontrib/gpcloud/regress/input/5_02_normal_https_param.source
gpcontrib/gpcloud/regress/output/1_09_partition.source
gpcontrib/gpcloud/regress/output/1_10_all_regions.source
gpcontrib/gpcloud/regress/output/1_16_multiple_files_with_header_line.source
gpcontrib/gpcloud/regress/output/1_18_all_regions_version2.source
gpcontrib/gpcloud/regress/output/3_05_insert_to_wet_from_ret.source
gpcontrib/gpcloud/regress/output/3_06_special_characters.source
gpcontrib/gpcloud/regress/output/4_01_create_invalid_wet.source
gpcontrib/gpcloud/regress/output/5_01_normal_http_param.source
gpcontrib/gpcloud/regress/output/5_02_normal_https_param.source
gpcontrib/gpcloud/regress/regress_schedule
gpcontrib/gpcloud/src/s3conf.cpp
gpcontrib/gpcloud/src/s3utils.cpp
gpcontrib/gpcloud/test/Makefile
gpcontrib/gpcloud/test/data/s3httptest.conf
gpcontrib/gpcloud/test/s3conf_test.cpp

Enable S3 external table get S3 parameters from http/https server.
Now the s3 external table get params from local files in the location file
path after "config=" which relies on the file exists on each segment
locally. But for cloud users, the users cannot settle each config file on
each segment.
So this pr provides a way for each s3 external table QE get params from
http/https server whose address is configured after the "server=" string.
So if you are using the "server=" string in the location, you need to
start the http/https server by yourself. In this way, the s3 accessid
and secret key will not have to be written into configfile on the segment
locally which is safer than before.
If you set both "config=filepath" and "server=httpaddress" at the same
time, it will only try to get …

Add S3 external table getting parameters from http/https server function for master.

---

gpdb-doc/dita/ref_guide/system_catalogs/gp_pgdatabase.xml

The column 'valid' was missing from gp_pgdatabase.
Updated according to the following explanation:
6X:
If the segment is down, valid is always false.
If the segment is up,
If the sync mode of the segment (see gp_segment_configuration.mode) is either 's' (synchronized) or 'n' (Not in Sync) then valid = true
Otherwise, valid = false

Docs: added missing column for gp_pgdatabase

---

gpdb-doc/dita/best_practices/ha.xml

The current documentation is incorrectly indicating that the first column of the input file passed to gpmovemirrors is contentID. This is not a valid field. Removing it and making it consistent with the utility help.

Docs: corrected format for gpmovemirrors input file

---

gpdb-doc/dita/best_practices/data_loading.xml

Section https://greenplum.docs.pivotal.io/6-18/best_practices/data_loading.html was recommending users to update `pg_class` to set rough estimates for external table statistics. Updating catalog tables is not best practices so we are removing the section.

Docs: removed reference to update pg_class

---

src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

For the following query, Orca generated plan that caused wrong results:
```
CREATE TABLE dist_tab_a (a varchar(15)) DISTRIBUTED BY(a);
INSERT INTO dist_tab_a VALUES('1 '), ('2  '), ('3    ');
CREATE TABLE dist_tab_b (a char(15), b bigint) DISTRIBUTED BY(a);
INSERT INTO dist_tab_b VALUES('1 ', 1), ('2  ', 2), ('3    ', 3);
CREATE TABLE result_tab_a AS
(SELECT a.a, b.b FROM dist_tab_a a LEFT JOIN dist_tab_b b ON a.a=b.a) DISTRIBUTED BY(a);
EXPLAIN CREATE TABLE result_tab_a AS
(SELECT a.a, b.b FROM dist_tab_a a LEFT JOIN dist_tab_b b ON a.a=b.a) DISTRIBUTED BY(a);
Hash Left Join  (cost=0.00..862.00 rows=2 width=16)
Hash Cond: ((dist_tab_a.a)::bpchar = dist_tab_b.a)
->  Redistribute Motion 3:3  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=8)
Hash Key: dist_tab_a.a
->  Seq Scan on …
```

Fix bug that Orca generates wrong plan for CTAS

---

src/backend/cdb/cdbpath.c
src/backend/optimizer/path/allpaths.c
src/backend/optimizer/util/pathnode.c

Removing unnecessary check for replicated locus type. Adding missed blank lines. Mentioning broken regression test.
PR #12238 [contains](https://github.com/arenadata/gpdb/blob/dc74b6bc0ce6fa459300763e5b1ed90046be2a3b/src/backend/cdb/cdbpath.c#L320) unnecessary `if` condition which was included by mistake. This statement can return NULL, which in rare cases can filter the optimal plan.

Fixing PR #12238.

---

gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
gpMgmt/bin/gpstart

Restricted mode mentioned in log when using -R option along with gpstart -m.
Updated respective unit tests.

[6x] Updating logs for restricted mode along with gpstart -m

---

concourse/pipelines/templates/gpdb-tpl.yml

ssh and scl commands failing during cli_cross_subnet execution with
error. "Unable to negotiate with 10.0.43.106 port 22: no matching host key type found.
Their offer: ssh-rsa,ssh-dss lost connection"
This could be an issue with OpenSSH (7.0 and greater).OpenSSH implements all of the
cryptographic algorithms needed for compatibility with standards-compliant SSH implementations,
but since some of the older algorithms have been found to be weak, not all of them are
enabled by default.  We can avoid this failures by using below flags while running ssh/scp commands.
HostKeyAlgorithms=+ssh-dss and PubkeyAcceptedKeyTypes=+ssh-rsa

cli_cross_subnet failing on 6X_STABLE pipeline

---

src/backend/utils/adt/datetime.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/qp_misc_jiras.out
src/test/regress/expected/qp_misc_jiras_optimizer.out
src/test/regress/expected/timestamp.out
src/test/regress/sql/qp_misc_jiras.sql
src/test/regress/sql/timestamp.sql

Commit 71ec37a9136 removed the implicit format in favor of better
aligning with Postgres. However, it broke existing customers upgrades
from 5X to 6X. This patch brings back the old behavior behind a GUC
'enable_implicit_timeformat_YYYYMMDDHH24MISS' that is disabled by
default.

Add GUC to re-enable YYYYMMDDHH24MISS timestamp support

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

Documented three new GUCs: gp_dispatch_keepalives_idle, gp_dispatch_keepalives_interval, gp_dispatch_keepalives_count to tune TCP keepalives for QD/QE libpq connections.
I have based the Set Classification values on the same ones as tcp_keepalives_idle, tcp_keepalives_interval, tcp_keepalives_count.
Preview site:
https://mireia-gucs.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/config_params/guc-list.html#gp_dispatch_keepalives_count

Docs gp dispatch gucs

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_data_format.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_schema_and_mode.py
gpMgmt/bin/gpload_test/gpload2/query205.ans
gpMgmt/bin/gpload_test/gpload2/query233.ans
gpMgmt/bin/gpload_test/gpload2/query253.ans
gpMgmt/bin/gpload_test/gpload2/query259.ans
gpMgmt/bin/gpload_test/gpload2/query260.ans
gpMgmt/bin/gpload_test/gpload2/query37.ans
gpMgmt/bin/gpload_test/gpload2/query402.ans
gpMgmt/bin/gpload_test/gpload2/query76.ans
gpMgmt/bin/gpload_test/gpload2/query77.ans

When gpload finds reuse external tables, it will check the format option(as a string) of the external table. The order of the format options matters.
Modify the order of adding newline option when creating the sql to create external table and find it.
Also, change the type of an error message to make it print normally.

Fix gpload cannot find reuse table

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c
src/test/isolation2/expected/resource_queue.out
src/test/isolation2/expected/resource_queue_cancel.out
src/test/isolation2/expected/resource_queue_deadlock.out
src/test/isolation2/expected/resource_queue_multi_portal.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue.sql
src/test/isolation2/sql/resource_queue_cancel.sql
src/test/isolation2/sql/resource_queue_deadlock.sql
src/test/isolation2/sql/resource_queue_multi_portal.sql

Since commit 2fa7c06d6a5, we have introduced an opportunity where the
active statement count is leaked (the active statements is not
decremented with `ResLockUpdateLimit(.., .., false, ..)`. This can happen
during a deadlock report or a statement cancellation of a statement
if the session has at least one other active named portal. During
`CheckDeadlock()/ResLockWaitCancel()`, we would clean up the locallock,
which would cause a subsequent call to `ResLockRelease()`, for the other
active portal to early return here:
```c
/*
* If the lock request did not get very far, cleanup is easy.
*/
if (!locallock ||
!locallock->lock ||
!locallock->proclock)
{
elog(LOG, "Resource queue %d: no lock to release", locktag->locktag_field1);
if (locallock)
{
RemoveLocalLock(locallock);
}
return false;
}
``` …

Fix a resource queue active stmt leak case

---

src/backend/optimizer/plan/setrefs.c
src/test/regress/expected/bfv_index.out
src/test/regress/expected/bfv_index_optimizer.out
src/test/regress/sql/bfv_index.sql

The node doesn't support for evaluating set-returning-functions in targetlists, they
should be moved onto a new Result node which will be inserted above the given node.
fix issue #11307

[6x] fix error for Index Only Scan plan when targetlists contain set-returning-functions

---

src/backend/storage/file/buffile.c
src/backend/storage/file/fd.c
src/backend/utils/time/sharedsnapshot.c
src/include/storage/buffile.h
src/test/regress/GNUmakefile
src/test/regress/input/temp_tablespaces.source
src/test/regress/output/temp_tablespaces.source

The buf-file of snapshot passed to reader cursor is not large so we
do not need to put it in temp tablespaces even the GUC is set. This
can fix a complicated infinite recursive function call problem 
mentioned in Github Issue 12871. (So long, not suitable to elaborate
here).
This commit also invalidate CatalogSnapshot at the end of the function
readSharedLocalSnapshot_forCursor(), so that next it will create a
new CatalogSnapshot that contains the correct command id from the
shared snapshot loaded.
Fix Issue: https://github.com/greenplum-db/gpdb/issues/12871, refer to
the issue page for details.

(6x) Not use temp tablespaces for snapshot buf-file passed to reader cursor.

---

src/test/isolation2/expected/resource_queue_cancel.out
src/test/isolation2/expected/resource_queue_multi_portal.out
src/test/isolation2/sql/resource_queue_cancel.sql
src/test/isolation2/sql/resource_queue_multi_portal.sql
src/test/isolation2/sql_isolation_testcase.py

isolation2 quit syntax is not blocking. Thus relying on session quits,
like in e4c6c36, in order to assert resource queue emptiness, can
lead to flakes.
Use END instead to ensure deterministic behavior. Using END is more
accurate too, as resource queue cleanup occurs at transaction end,
rather than during backend exit.
Also update this fact in the isolation2 in-code documentation.
This needs to be backported into https://github.com/greenplum-db/gpdb/pull/12909 and https://github.com/greenplum-db/gpdb/pull/12908

Don't rely on quits for resqueue cleanup tests

---

gpdb-doc/dita/admin_guide/intro/about_statistics.xml

greenplum 6 computes correlation statistics for heap tables.
this PR is against 6X_STABLE.
question about support on master - does greenplum also compute the stats for AO and AOCO tables?  (will submit a separate PR.)

docs - update correlation statistic support

---

src/backend/executor/execMain.c
src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
src/test/isolation2/sql/gdd/concurrent_update.sql

With GDD enabled, QE might be blocked by other transaction's UPDATE
operation, and later wakes up, EvalPlanQual logic is triggered. To
re-evaluate the plan, it will try to init all subplans (even if the
subplan is not needed in the plan to re-eval), we should also consider
nmotions when init such subplans. Throw error to avoid PANIC when
such subplans contain motion.
NOTE: this is not a behavior change and this just makes thing correct.
See Greenplum's document: https://docs.greenplum.org/6-16/admin_guide/dml.html#topic_gdd
for details. Error out here to make the database consistent is the same idea
as the Postgres's repeatable read isolation level, see the Postgres doc for
details: https://www.postgresql.org/docs/9.4/transaction-iso.html.
-------
Master branch does not need this, since …

(6x) Throw error when try to Init SubPlan with Motion during EvalPlanQual.

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c
src/test/isolation2/expected/resource_queue.out
src/test/isolation2/expected/resource_queue_cancel.out
src/test/isolation2/expected/resource_queue_deadlock.out
src/test/isolation2/expected/resource_queue_multi_portal.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue.sql
src/test/isolation2/sql/resource_queue_cancel.sql
src/test/isolation2/sql/resource_queue_deadlock.sql
src/test/isolation2/sql/resource_queue_multi_portal.sql

Cherry-picked from e4c6c368cda9f2928dbd530967fb56acf214a326 and follow
up 780005f8026600b91e9c88e32c35b41614014d50 with minor
conflicts resolved. Original commit message follows along with a manual repro
for 5X that involves named portals in extended protocol:
-------------------------------------------------------------------------
Since commit 2fa7c06d6a5, we have introduced an opportunity where the
active statement count is leaked (the active statements is not
decremented with ResLockUpdateLimit(.., .., false, ..). This can happen
during a deadlock report or a statement cancellation of a statement
if the session has at least one other active named portal. During
CheckDeadlock()/ResLockWaitCancel(), we would clean up the locallock,
which would cause a subsequent call to …

5X: Fix a resource queue active stmt leak case

---

src/test/isolation2/sql_isolation_testcase.py

Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/A2JUpJ0NrEA/m/3S6rmd2zBAAJ
(cherry picked from commit b1dc547ccd231f3ce7d66719eafda652a8326748)

5X: Document that explicit quit syntax is non-blocking

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c
src/test/isolation2/expected/resource_queue.out
src/test/isolation2/expected/resource_queue_cancel.out
src/test/isolation2/expected/resource_queue_deadlock.out
src/test/isolation2/expected/resource_queue_multi_portal.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue.sql
src/test/isolation2/sql/resource_queue_cancel.sql
src/test/isolation2/sql/resource_queue_deadlock.sql
src/test/isolation2/sql/resource_queue_multi_portal.sql

Cherry-picked from e4c6c368cda9f2928dbd530967fb56acf214a326 and
follow-up 780005f8026600b91e9c88e32c35b41614014d50 with minor conflicts
resolved. Original commit message follows along with a manual repro for
6X that involves named portals in extended protocol:
-------------------------------------------------------------------------
Since commit 2fa7c06d6a5, we have introduced an opportunity where the
active statement count is leaked (the active statements is not
decremented with ResLockUpdateLimit(.., .., false, ..). This can happen
during a deadlock report or a statement cancellation of a statement
if the session has at least one other active named portal. During
CheckDeadlock()/ResLockWaitCancel(), we would clean up the locallock,
which would cause a subsequent call to …

6X: Fix a resource queue active stmt leak case

---

src/test/isolation2/sql_isolation_testcase.py

Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/A2JUpJ0NrEA/m/3S6rmd2zBAAJ
(cherry picked from commit b1dc547ccd231f3ce7d66719eafda652a8326748)

6X: Document that explicit quit syntax is non-blocking

---

gpdb-doc/dita/install_guide/migrate.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

doc the new guc enable_implicit_timeformat_YYYYMMDDHH24MISS.  in this PR:
- add the new guc to the guc reference
- update to the migration topic, which mentions that greenplum no longer automatically converte from the deprecated YYYYMMDDHH24MISS timestamp format.  (the existing examples don't look that useful to me, but i assume that they are there for a reason, so kept them.)

docs - new 6x guc enable_implicit_timeformat_YYYYMMDDHH24MISS

---

gpdb-doc/dita/admin_guide/external/g-s3-protocol.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.xml

the user can now specify the `config_server=url` option in the `CREATE EXTERNAL TABLE` `LOCATION` clause for the s3 protocol to have greenplum pull the config file from an http/https server.  in this PR:
- some usability improvements, including reorg/renaming topics, removing duplicate info
- a small reorg and renaming of some of the topics
- split configuring and using into two different sections
- grouped relevant read and write info together and added separate sections
- S3 refers to aws objects, s3 refers to the external table, `s3` refers to the greenplum protocol
- add discussion of new config_server option
- update synpsis on s3 page and `CREATE EXTERNAL TABLE` page to include config_server
NOTE:  to focus on the changes that are specific to this new feature, review the topic …

docs - s3 protocol supports specifying config via http(s)

---

gpdb-doc/dita/utility_guide/ref/gpload.xml

update the gpload reference page to include the NEWLINE property.  docs for https://github.com/greenplum-db/gpdb/pull/12739 and https://github.com/greenplum-db/gpdb/pull/12867.

docs - gpload supports NEWLINE property in load cfg file

---

README.Ubuntu.bash

Since everytime I build gpdb in a new environment of ubuntu 20.04, I will got this error:
```bash
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.
```
So I think add pkg-config to bash script will be more convenient.

add pkg-config to README.Ubuntu.bash

---

src/test/isolation2/input/uao/snapshot_eof.source
src/test/isolation2/output/uao/snapshot_eof.source

Add case to test VACUUM snapshot correctness against AO table.
Add one more case for PR https://github.com/greenplum-db/gpdb/pull/12197
to test AO block header CRC verification, to assert taking a proper snapshot
under VACUUM and concurrent insert requests.
The patch was originally written by Junfeng Yang (junfeng91).

[6X_STABLE] Add case to test VACUUM snapshot correctness against AO table.

---

gpdb-doc/dita/admin_guide/intro/about_statistics.xml

correlation stats are computed/used differently in master and 6x.  6x text was mistakenly forward ported to master with https://github.com/greenplum-db/gpdb/pull/12761/files.  update the master text.

docs - clarify correlation stats on master

---

gpdb-doc/dita/admin_guide/access_db/topics/pgbouncer.xml

add a note to the pgbouncer docs that the psql client shipped with greenplum 6.x is too old to use the scram authentication method.

docs - psql client too old for pgbouncer scram

---

gpMgmt/sbin/packcore

Packcore tests on RHEL8 were failing because of GDB failing to start. And this was happening because GDB needs some environment variables set before invoking command.

Packcore tests were failing on 6x. Current change makes sure that we are in parity with gpdb6.

---

src/backend/cdb/cdbcopy.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/cdb/dispatcher/cdbgang_async.c
src/include/cdb/cdbgang.h
src/test/isolation2/expected/fts_errors.out
src/test/isolation2/expected/fts_errors_1.out
src/test/isolation2/expected/fts_session_reset.out
src/test/isolation2/expected/gpdispatch.out
src/test/isolation2/expected/gpdispatch_1.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/sql/gpdispatch.sql

DisconnectAndDestroyAllGangs will destroy the memory context CdbComponentsContext.
But if we have named portal exists (cursors), later when we clean up
those portals during transaction-abort, it will PANIC due to null pointer
reference to the destroyed CdbComponentsContext.
So it is safe to call this function:
1. call it after all portals are cleaned up
2. call it when there cannot be any named portals
In this commit, I remove the invocation of DisconnectAndDestroyAllGangs in:
* cdbgang_createGang_async
* cdbCopyEndInternal
When the above two places hit error we can just leave the cleanup progress
when aborting transaction.
For details, please refer to Github Issue 12703. This commit fixes it.

Removing some invocation of DisconnectAndDestroyAllGangs that might PANIC.

---

src/backend/storage/lmgr/proc.c
src/test/isolation2/expected/resource_queue_query_cancel_deadlock_timeout.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/resource_queue_query_cancel_deadlock_timeout.sql

fix panic when a query in res waiting queue is about to cancel itself

---

src/backend/commands/foreigncmds.c
src/backend/foreign/foreign.c
src/backend/optimizer/util/pathnode.c
src/backend/optimizer/util/plancat.c
src/include/foreign/foreign.h
src/include/nodes/pathnodes.h
src/test/regress/expected/gp_foreign_data.out
src/test/regress/sql/gp_foreign_data.sql

Support specifying the num_segments option for foreign servers and
tables, Greenplum will create that amount of QEs if the `mpp_execute`
option's value is 'all segments'.
```
CREATE FOREIGN TABLE ft1 (
c1 int
) SERVER s1 OPTIONS (mpp_execute 'all segments', num_segments '42');
```

Support num_segments option for foreign servers and tables

---

gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Testcase was failing sometimes pg_ctl was failing with default timeout resulting into testcase failure. To make sure that the instance is stopped, added timeout of 120 seconds.

Adding timeout in the testcase when stopping the pg instance.

---

src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

The commit 8f4c96e, introduced adding a project node on top of group by
for outer references. The changes work fine for `CScalarSubqueryAny` as
in a later preprocessing step, the CScalarSubqueryAny with colref gets
processed to CScalarSubqueryExists (no colref). Whereas for
CScalarSubqueryAll, this colref would not be adjusted and still point to
the original colref, causing ORCA to generate a plan that would either
cause incorrect results or segment crash when executing the query.
Consider the following query,
select b from foo where b not in (select distinct b where c>1 );
The above query will get preprocessed as shown below:
```
Algebrized query:
+--CLogicalSelect
|--CLogicalGet "foo" ("foo"), Columns: ["a" (0), "b" (1), "c" (2), "ctid" (3), "xmin" (4), "cmin" (5), "xmax" (6), "cmax" …
```

Fix colref in preprocessing for SubqueryALL with outer refs

---

config/orca.m4
configure
gpAux/releng/releng.mk
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

This version of ORCA fixes colref in preprocessing for SubqueryALL with
outer refs. Adding regression tests for the same.
Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/633

Bump ORCA version to 3.122.0

---

src/backend/access/aocs/aocsam.c
src/backend/access/aocs/test/aocsam_test.c
src/backend/access/appendonly/aomd.c
src/backend/access/appendonly/appendonlyam.c
src/test/isolation2/expected/prevent_ao_wal.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/prevent_ao_wal.sql

For mirrorless clusters, WAL records are only used for crash recovery
purposes. In the case of AO/AOCO tables, their WAL records are only
generated for replication purposes (they are not used for crash
recovery because AO/AOCO table operations are crash-safe). To decrease
disk space usage and to improve the performance of AO/AOCO operations, we
suppress the generation of XLOG_APPENDONLY_INSERT and
XLOG_APPENDONLY_TRUNCATE WAL records when wal_level=minimal is
specified.

Prevent AO/AOCO WALs for wal_level=minimal

---

GNUmakefile.in
contrib/pg_trgm/expected/pg_trgm.out
contrib/pg_trgm/expected/pg_trgm_optimizer.out
contrib/pg_trgm/sql/pg_trgm.sql

pg_trgm is a build-in extension of PostgreSQL. this patch enables it in Greenplum.
pg_trgm does not contain new file formats or executor changes, which has good compatibility with
Greenplum.
Signed-off-by: Sasasu <i@sasa.su>

7X: enable pg_trgm by default

---

src/test/isolation2/expected/prevent_ao_wal.out
src/test/isolation2/sql/prevent_ao_wal.sql

- The test introduced in the commit
https://github.com/greenplum-db/gpdb/commit/e1720dd12ad87ebb61439d10a75044ddc97fd07a
was failing in ic_gpdb job due to 'pushd: not found'.
To fix it this commit removes pushd command from the test.

Fix ic_gpdb job

---

src/backend/commands/tablecmds.c

The PANIC issue is bringed in by commit: [Expand partition table leaves in parallel.](https://github.com/greenplum-db/gpdb/commit/a45be43489294386c23c5fa068ce071ec068d0d8), here's the setp to reproduce it:
1. Build gpdb without cassert, such as
```
./configure --with-perl --with-python --with-libxml --with-gssapi --enable-debug --disable-cassert --prefix=/usr/local/gpdb
````
2. Run commands:
```
postgres=# create extension if not exists gp_debug_numsegments;
NOTICE:  extension "gp_debug_numsegments" already exists, skipping
CREATE EXTENSION
postgres=# select gp_debug_set_create_table_default_numsegments(1);
gp_debug_set_create_table_default_numsegments 
-----------------------------------------------
1
(1 row)
postgres=# begin;
BEGIN
postgres=# ALTER TABLE partition_test EXPAND PARTITION …
```

Fix PANIC error in ALTER TABLE xxx EXPAND PARTITION PREPARE

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

Greenplum pulls up NOT-IN sublink to achieve better OLAP performance.
Generally, NOT-IN sublink is not semantically equivalent to NOT-EXIST
sublink because of NULL values. Besides, Greenplum cannot choose Hash
Join and cannot take advantage of partition-distribution  due to the
limitation of Executor currently (refer f77bf0879a28 and the comments
https://github.com/greenplum-db/gpdb/pull/11579#issuecomment-793385278).
Life will be much easier if both sides of NOT-IN sublink testexpr are
sure non-nullable.
We might seek for a great improvement of the executor to better support
NOT_IN. This commit just refactors the code and make the non-nullable
deduction clearer and can cover more cases. It does the following things:
* Rename the function find_nonnullable_vars_walker.
I find that …

Refactor convert_IN_to_antijoin.

---

gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/sbin/gpconfig_helper.py

Fix #12957, modify regex in **gp_bash_functions.sh** and **gpconfig_helper.py** from prefix match to full match after removing spaces.
6X_STABLE and other branches will also benefit from this commit.

Fix gpinitsystem/gpconfig comment other GUCs with same prefix.

---

src/backend/libpq/auth.c

In `cdbconn_doConnectStart()`, Greenplum cleans the host info to force
using domain socket for entry db connections. Checking the connection's
authentication here is not necessary, even annoying, if the user is not
allowed to connect via domain socket.
This commit authenticates it directly, just as Greenplum authenticates
TCP internal connections coming from the same host.
Fix https://github.com/greenplum-db/gpdb/issues/12851
This is the 6X version of https://github.com/greenplum-db/gpdb/pull/12872

6X: Authenticate internal connections via domain sockets

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

Greenplum pulls up NOT-IN sublink to achieve better OLAP performance.
Generally, NOT-IN sublink is not semantically equivalent to NOT-EXIST
sublink because of NULL values. Besides, Greenplum cannot choose Hash
Join and cannot take advantage of partition-distribution  due to the
limitation of Executor currently (refer f77bf0879a28 and the comments
https://github.com/greenplum-db/gpdb/pull/11579#issuecomment-793385278).
Life will be much easier if both sides of NOT-IN sublink testexpr are
sure non-nullable.
We might seek for a great improvement of the executor to better support
NOT_IN. This commit just refactors the code and make the non-nullable
deduction clearer and can cover more cases. It does the following things:
* Rename the function find_nonnullable_vars_walker.
I find that …

(6x backport) Refactor convert_IN_to_antijoin.

---

src/backend/tcop/postgres.c
src/backend/utils/misc/guc_gp.c

When a string guc such as search_path is set to '', Then some command such as create an extension with schema xxx, will add the changed guc to restore_list, before the next command begins to execute, call restore_guc_to_QE to restore changed guc. the restoring string is "set search_path to ;",  then the string will be dispatched to QEs, QE elog an error, QD gets the error, and call ReThrowError to re-throw the error, errordata_stack_depth++, however, when we catch the error did not call FlushErrorState() to reset errordata_stack_depth.
when we execute other commands, after all, the errordata_stack_depth is not -1, The return value of elog_geterrcode shows there is an error. 
related commits:https://github.com/greenplum-db/gpdb/commit/320af40b31f571dbb9fa7323f33f4963ff02f4ec
related issue: …

quote when resetting a GUC and resolve empty values

---

src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct.mdp
src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
src/backend/gporca/server/CMakeLists.txt

Previously, in CreateStatsPredDisj, if one of the filter's child expression is
an CScalarArrayCmp of type EarrcmpAll, we directly append the CStatsPred of
each ArrayCmp element into the result pred stats array for the parent filter.
While this works if the parent filter is a conjunctive filter, as it flattens
the result conjunctive pred stats array, this generates incorrect result pred
stats for a disjunctive filter.
For example, for the following predicate expression:
a is NULL OR a <> ALL  ('{0, 1, 2}'::int[])
with the previous logic, we would create a disjunctive pred stats for:
a is NULL OR a <> 0 OR a <> 1 OR a <> 2
This patch fixes the problem by creating a new conjunctive pred stats array
only for the ArrayCmpAll expression, and append it to the final disjunctive
pred stats array. …

ORCA: Fix CreateStatsPredDisj with an ArrayCmpALL disjunct

---

src/backend/commands/explain_gp.c
src/backend/executor/execMain.c
src/backend/executor/nodeSubplan.c
src/backend/executor/test/nodeSubplan_test.c
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

Currently, if one segment (like seg1) panics due to some reason, other
segments (like seg0) will report "InstrEndLoop called on running node".
This is because QE on seg1 reports ERROR to QD when execution fails,
and the QD dispatches cancel command to all the QEs, but another QE on
seg0 is not finished yet, its `instr` structure is not cleaned up.
This commit is to remove the logic of sending stats when execution
failed, which is not needed.
Fixes https://github.com/greenplum-db/gpdb/issues/9904

6X: Don't collect execution stats if the query failed

---

contrib/pageinspect/Makefile
contrib/pageinspect/bmfuncs.c
contrib/pageinspect/pageinspect--1.7--1.8.sql
contrib/pageinspect/pageinspect.control
src/test/isolation2/expected/bitmap_index_inspect.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_index_inspect.sql

Including two commits (squashed into one now):
1. (Authored by @soumyadeep2007 ) The main pageinspect bitmap implementation (`bmfuncs.o`), including `bm_metap()` for Bitmap metapage, `bm_lov_page_items()` for Bitmap LOV page, `bm_header_items()` and `bm_page_items()` for Bitmap pages.
2. Added tests and some enhancements, including better presentation of the bitmap words in the result sets, an additional `bm_page_items()` with page input, and fixed a bug where the lovlastblknum parameter in bm_metap() needs to be bigint instead of int to cover the whole range of block number which is defined as unsigned int in code.
TODO:
1. Testing RPM packaging.
2. Writing up some doc for this.

Pageinspect for bitmap

---

gpMgmt/bin/gpinitsystem

Because we can change the `root` name, so use name to check if user is `root user` may not be enough for here.

fix: root name may not necessary for root user

---

src/backend/tcop/postgres.c

when QE process nextval  it sends NOTIFY to QD and asks QD to send nextval back to
QE, after getting nextval on QD is failed, QD send '?' message back to QE and cancel all
unfinished QEs, if the QE receives cancel before '?' message, QE will throw an error and 
finish current command, the message  '?' will stay in the socket, next time when we ReadCommand
we get '?' and ignore it. If we receive '?' before receiving the cancel signal, the next command will be OK,
it is flaky.

ignore message '?' after nextval on QD is failed

---

src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct-2.mdp
src/backend/gporca/data/dxl/minidump/ArrayCmpAll-Disjunct.mdp
src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp
src/backend/gporca/server/CMakeLists.txt

This is a back port of https://github.com/greenplum-db/gpdb/pull/12793.
The test added in the 7X commit does not serve its purpose well for 6X, because the preprocess optimization `PexprConvert2In()` is disabled in 7X. Hence added a new test for 6X. I will squash all three commits together when merge, but keep them separate in this PR for clarity.

[6X_STABLE] Fix CreateStatsPredDisj with an ArrayCmpALL disjunct

---

src/backend/postmaster/backoff.c
src/backend/utils/misc/guc_gp.c
src/include/utils/sync_guc_name.h

This commit allows logging of the duration spent by a statement in sleep
due to resource queues backoff mechanism
If the GUC is enabled a message will be logged like below:
```
2021-12-23 16:03:46.112877 PST,"bchaudhary","bchaudhary",p32725,th357490112,"127.0.0.1","59752",2021-12-23 16:03:43 PST,843,con12,cmd3,seg0,,dx7,x843,sx1,"LOG","00000","Total sleep time in resource queue: 690.479 ms",,,,,,"insert into r1 select i, i from generate_series(1,1000000)i;",0,,"backoff.c",1026,
```
This allow for post-analysis to see the impact of concurrency on the statement.

Add GUC to display sleep time for a stmt in RQ

---

src/backend/tcop/postgres.c

when QE process nextval it sends NOTIFY to QD and asks QD to send nextval back to
QE, after getting nextval on QD is failed, QD send '?' message back to QE and cancel all
unfinished QEs, if the QE receives cancel before '?' message, QE will throw an error and
finish current command, the message '?' will stay in the socket, next time when we ReadCommand
we get '?' and ignore it. If we receive '?' before receiving the cancel signal, the next command will be OK,
it is flaky.

(6x) ignore message '?' after nextval on QD is failed

---

gpMgmt/bin/gpcheckcat
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Requirement was to remove all and owner test from default running those, and run them when user specified it with -R option.
* removing acl and owner test from default run
* Adding behave test case for confirming the skip test in log message

[6x]Gpcheckcat: Removing 'acl' and 'owner' tests from default run all option

---

src/backend/access/aocs/aocsam.c
src/backend/access/aocs/test/aocsam_test.c
src/backend/access/appendonly/aomd.c
src/backend/access/appendonly/appendonlyam.c
src/backend/utils/misc/guc.c
src/test/isolation2/expected/prevent_ao_wal.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/prevent_ao_wal.sql

Prevent AO/AOCO WALs for wal_level=minimal [6X]
- For mirrorless clusters, WAL records are only used for crash recovery
purposes. In the case of AO/AOCO tables, their WAL records are only
generated for replication purposes (they are not used for crash
recovery because AO/AOCO table operations are crash-safe). To decrease
disk space usage and to improve performance of AO/AOCO operations, we
suppress generation of XLOG_APPENDONLY_INSERT and
XLOG_APPENDONLY_TRUNCATE WAL records when wal_level=minimal is
specified.
Cherry-picked from:
https://github.com/greenplum-db/gpdb/commit/e1720dd12ad87ebb61439d10a75044ddc97fd07a
with modifications.
Changes compare to master:
- seperate commit to set max_wal_senders minimal value to 0 and allows wal_level=minimal
- using WAL_LEVEL_ARCHIVE instead of …

[6X] Prevent AO/AOCO WALs for wal_level=minimal

---

src/backend/gporca/libgpopt/src/xforms/CXformRightOuterJoin2HashJoin.cpp
src/backend/gporca/server/CMakeLists.txt
src/backend/gporca/server/include/unittest/gpopt/CTestUtils.h
src/backend/gporca/server/include/unittest/gpopt/xforms/CXformRightOuterJoin2HashJoinTest.h
src/backend/gporca/server/src/startup/main.cpp
src/backend/gporca/server/src/unittest/CTestUtils.cpp
src/backend/gporca/server/src/unittest/gpopt/xforms/CXformRightOuterJoin2HashJoinTest.cpp

Similar to dede33b352f when statistics may not be derived yet, we should
take care to handle the scenario gracefully.
Following demonstrated error using non-assert build:
```sql
CREATE TABLE a_table(col text);
SELECT a.col FROM (
SELECT col FROM a_table e
WHERE exists
(
SELECT col FROM a_table
)
) a
WHERE exists (
SELECT c.col FROM a_table c
INNER JOIN a_table b
ON c.col = a.col
WHERE exists (
SELECT distinct _a.col FROM (
SELECT distinct col FROM a_table _a
) _a
WHERE _a.col = c.col
)
);
```

Fix SIGSEGV due to non-derived statistics (#12970)

---

src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/test/regress/expected/domain_optimizer.out
src/test/regress/expected/qp_misc.out
src/test/regress/sql/qp_misc.sql

Earlier it was set to collation id of resulttype. But consider an expression
like  below :
string_to_array(unnest(anyarray)) <> '{nullout}'
annyarray has a collation oid of 0 but string_to_array returns a TEXTARRAY
which has a collation oid of 100.  So for resultcollid we should rely on
collation type of the expression.
Co-authored-by: Bhuvnesh Chaudhary bhuvnesh2703@gmail.com

Set correct resultcollid for RelabelType

---

src/backend/access/bitmap/bitmap.c
src/backend/access/gin/ginget.c
src/backend/access/gist/gistget.c
src/backend/access/hash/hash.c
src/backend/access/index/indexam.c
src/backend/access/nbtree/nbtree.c
src/backend/access/spgist/spgscan.c
src/backend/executor/nodeBitmapIndexscan.c
src/include/access/genam.h
src/test/regress/expected/gp_explain.out
src/test/regress/expected/gp_explain_optimizer.out
src/test/regress/sql/gp_explain.sql

GPDB has a different definition of amgetbitmap with upstream.
Since GPDB also supports StreamBitmap in bitmap index. So normally
we need to create a specific bitmap node in the amgetbitmap AM.
We used to return the created node, this leads to losing the tuples
matched in the bitmap.
So I refactor the amgetbitmap function definition to set bitmap
through pointer and then return the tuples matched in the bitmap.
(backported from 3245d17, PR #11415)

Backport synchronization of amgetbitmap definition with upstream

---

concourse/pipelines/templates/gpdb-tpl.yml
gpMgmt/bin/gpexpand
gpMgmt/bin/gpinitstandby
gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py
gpMgmt/bin/gppylib/operations/initstandby.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_initstandby.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_on_segments.py
gpMgmt/bin/gppylib/operations/update_pg_hba_on_segments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Removed update_pg_hba_conf_on_segments() which is the old one. 
Updated update_pg_hba_on_segments() to handle unreachable hosts 
Added new test cases and updated existing test cases accordingly.
Updated gpexpand utility to have new logic to update pg_hba.

Reconcile duplicate pg_hba update logic

---

src/backend/executor/nodeSubplan.c

Currently, if one segment (like seg1) panics due to some reason, other
segments (like seg0) will report "InstrEndLoop called on running node".
This is because QE on seg1 reports ERROR to QD when execution fails,
and the QD dispatches cancel command to all the QEs, but another QE on
seg0 is not finished yet, its `instr` structure is not cleaned up.
This commit is to remove the logic of sending stats when execution
failed, which is not needed.
Fixes greenplum-db#9904

Don't collect execution stats if the query failed

---

gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.c
src/backend/utils/misc/faultinjector.c
src/include/utils/faultinjector.h
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

The fault 'send_qe_details_init_backend' injected in dispatch.source was
triggered by other backend processes by accident, which makes the
dispatch case flaky.
This commit provides another version of gp_inject_funtion() with an extra
parameter, so that the fault could be triggered by a specific session, to
avoid the fault triggered by other backend processes unexpectedly.

Add another version of gp_inject_funtion() to fix flaky case

---

src/backend/commands/createas.c
src/backend/tcop/postgres.c
src/test/regress/expected/guc_gp.out
src/test/regress/sql/guc_gp.sql

add testcase for pr: #12903 
when the original string guc is empty, we change the guc to new value during executing a command.
this guc will be added to gp_guc_restore_list, and they will be restored to original value to QE
when the next command is executed.
however, the dispatch command is "set xxx to ;" that is wrong.
we  inject fault to change the value of search_path during creating materialized view
inject fault when dispatch guc restore command occur errors, we throw an error.

add testcase for restore guc of empty string

---

src/backend/commands/createas.c
src/backend/tcop/postgres.c
src/backend/utils/misc/guc.c
src/backend/utils/misc/guc_gp.c
src/test/regress/expected/guc_gp.out
src/test/regress/sql/guc_gp.sql

When a string guc such as search_path is set to '', Then some command such as create an extension with schema xxx, will add the changed guc to restore_list, before the next command begins to execute, call restore_guc_to_QE to restore changed guc. the restoring string is "set search_path to ;", then the string will be dispatched to QEs, QE elog an error, QD gets the error, and call ReThrowError to re-throw the error, errordata_stack_depth++, however, when we catch the error did not call FlushErrorState() to reset errordata_stack_depth.
when we execute other commands, after all, the errordata_stack_depth is not -1, The return value of elog_geterrcode shows there is an error.
related commits:320af40  and c4f03b8
related issue: #12900
tests: current extensions set search_path to public, so we …

(6x) backport quote when resetting a GUC and resolve empty values to 6x

---

src/test/isolation2/input/uao/vacuum_cleanup.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/vacuum_cleanup.source

Autovacuum jobs that are running in the background could cause flaky test cases such as in uao/vacuum_cleanup_row where checking the age of some tables on the segments becomes larger than expected because autovacuum running on the segments.
Since all the uao tests do not need autovacuum, disable it for them (there's already a bunch of tests with autovacuum being disabled, we just include the uao tests there too). 
And in particular, we can now check the exact age instead of an age range in the vacuum_cleanup tests since those results should be deterministic now. Therefore, we don't need to guess around should another failure happens.

Disable autovacuum for isolation2/uao tests to fix flaky test cases

---

src/backend/gporca/data/dxl/minidump/BitmapIndexProbeMergeFilters.mdp
src/backend/gporca/data/dxl/minidump/DynamicIndexScan-Heterogenous-PartSelectRange.mdp
src/backend/gporca/data/dxl/minidump/JoinOrderDPE.mdp
src/backend/gporca/data/dxl/minidump/NLJ-Broadcast-DPE-Outer-Child.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverGbAgg-2.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost1.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost2.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost3.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost4.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-List-Cost5.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost1.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost2.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost3.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost4.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-SPE-DynamicTableScan-Range-Cost5.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h
src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h
src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
src/backend/gporca/libgpopt/src/operators/CLogical.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGet.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGetBase.cpp
src/backend/gporca/server/CMakeLists.txt

ORCA: Improve cardinality estimation for Dynamic Table Scan under SPE
Previously, Orca always generates cardinality estimation for the
CLogicalDynamicGetBase operator by applying the query predicate stats
on top of the root table stats.  This makes sense for Dynamic Bitmap
Heap Scan and Dynamic Index Scan because the input rows for those
dynamic scans are filtered exactly by the query predicate.  However,
Dynamic Table Scan (CLogicalDynamicGet) is slightly different.
Although the query predicate helps partition pruning, we scan every
tuple of the selected partitions regardless the selectivity of the
query predicate within a leaf partition.  Therefore, for static
partition elimination, we should use the combined statistics of the
selected leaf partitions to estimate cardinality of …

ORCA: Improve cardinality estimation for Dynamic Table Scan under SPE

---

src/backend/gporca/data/dxl/minidump/BitmapIndexScan.mdp
src/backend/gporca/data/dxl/minidump/BitmapTableScan-Basic.mdp
src/backend/gporca/data/dxl/minidump/GinIndex.mdp
src/backend/gporca/data/dxl/minidump/GinIndexPathOpfamily.mdp
src/backend/gporca/data/dxl/minidump/GinIndexSearchModeAll.mdp
src/backend/gporca/data/dxl/minidump/Gist-AOCOTable-NonLossy-BitmapIndexPlan.mdp
src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/output/qp_gist_indexes2_optimizer.source
src/test/regress/sql/gporca.sql

Prior to this PR, ORCA would project recheck/scalar filter columns
in addition to the output columns for BitmapTableScan/DynamicBitmapTableScan. 
This would work fine for most of the cases, but would produce wrong results in case of SharedScan with
BitmapTableScan on AO tables. This commit fixes the issue by removing
the unnecessary projection of recheck/scalar filter columns, similar to how planner projects
for BitmapHeapScan.
This fixes the issue: #12796
This PR also updates regress tests and mdp files with the updated plans and comments.  
Note: This is only an issue with 6X_STABLE and not on master as the materialize for shared scan was removed from master as part of this PR commit https://github.com/greenplum-db/gpdb/pull/10032/commits/5bdf2c8be30fea55fa7badadd1c7a2fd2acc69b9.

[6X_STABLE] Remove unnecessary projection of recheck/scalar filter columns from Bitmap Scan 

---

src/backend/access/bitmap/bitmap.c
src/backend/access/gin/ginget.c
src/backend/access/gist/gistget.c
src/backend/access/hash/hash.c
src/backend/access/nbtree/nbtree.c
src/backend/access/spgist/spgscan.c
src/backend/utils/mmgr/mcxt.c
src/include/utils/memutils.h

This commit: https://github.com/greenplum-db/gpdb/commit/699998c79460babd05d4a710e29fe74eeceae89e imported some compile warnings.
Fix them in this PR.

[6X] Fix compile warnings which imported in "synchronization of amgetbitmap definition with upstream"

---

gpcontrib/Makefile
gpcontrib/gp_sparse_vector/Makefile
gpcontrib/gp_sparse_vector/expected/gp_svec.out
gpcontrib/gp_sparse_vector/expected/gp_svec_features.out
gpcontrib/gp_sparse_vector/gp_sparse_vector--1.0.0--1.0.1.sql
gpcontrib/gp_sparse_vector/gp_sparse_vector--1.0.1.sql
gpcontrib/gp_sparse_vector/gp_sparse_vector.control
gpcontrib/gp_sparse_vector/sql/gp_svec.sql
gpcontrib/gp_sparse_vector/sql/gp_svec_features.sql

As #12986 mentioned, some binary operators function definition in GP extension `gp_sparse_vector` is not `strict`, which cannot properly handle NULL rows, may cause SIGSEV memory crush as follow:
```
#0  0x00007fdf3f7d74fb in raise () from /data/logs/298723/packcore-postgres.626108.181669.core/lib64/libpthread.so.0
#1  0x0000000000bf8260 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5579
#2  <signal handler called>
#3  pg_detoast_datum (datum=0x0) at fmgr.c:2209
#4  0x00007fdf183bec11 in svec_l2_eq () from /data/logs/298723/packcore-postgres.626108.181669.core/ms/dist/gpdb/PROJ/ds/6.17.7/.exec/@sys/lib/postgresql/gp_svec.so
#5  0x00000000008c590b in ExecMakeFunctionResultNoSets (fcache=0x33d19d8, econtext=0x33ddf38, …
```

Make svec_l2_eq strict function to handle NULL properly.

---

GNUmakefile.in
contrib/btree_gin/Makefile
contrib/btree_gin/btree_gin.c
contrib/btree_gin/expected/money.out
contrib/btree_gin/sql/money.sql
contrib/pg_trgm/Makefile
contrib/pg_trgm/expected/pg_trgm_optimizer.out

from 7X branch #12927 #12928
those extensions do not contain new file formats or executor changes. so they have good compatibility with Greenplum.
this PR includes 2 commits in order to avoid merge conflicts.

6X: enable pg_trgm and btree_gin 

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

document the new guc that logs statement sleep time in resource queues.  misc edits to arrange some gucs in alphabetic order.

docs - add new guc gp_log_resqueue_priority_sleep_time to ref guide
