greenplum-db/gpdb

gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

gpinitsystem Testcases:
Scenario: gpinitsystem succeeds if there is banner on host
Scenario: gpinitsystem succeeds if there is multi-line banner on host
gpinitstandby Testcase:
Scenario: gpinitstandby should not throw error when banner exists on the host
gprecoverseg testcase:
Scenario: gprecoverseg should not return error when banner configured on host
Added scenario tag 'backup_restore_bashrc' which will backup and restore bashrc file to undo the banner changes on host.
Changes in backup_bashrc and restore_bashrc functions to pickup the home directory from environment and other minor changes.

Undo the banner changes on behave tests once the test has completed.

---

gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py

In order to test the `-p` functionality in gprecoverseg, we create a cluster
with spare hosts and then make one or more of the cluster hosts as unreachable
and use -p to make the segments on thost hosts failover to the spare hosts.
For this to work, we had to bring the cluster back to it's original state for
each example of the test scenario. This was done to make sure examples were not
dependent on each other and that they could start with a clean cluster. To
achieve this, we would delete the cluster using gpdeletesystem and reinitialize
it using gpinitsystem.
The problem with this approach was that any changes made to the cluster like
setting a guc would get removed because of running gpdeletesystem and
gpinitsystem. A better way is to reconnect the down hosts and then make the
segments …

gprecoverseg behave: Do not delete the cluster for newhost scenario

---

src/backend/replication/basebackup.c
src/bin/pg_basebackup/t/010_pg_basebackup.pl
src/bin/pg_rewind/filemap.c
src/bin/pg_rewind/t/003_extrafiles.pl

First commit:
```
Exclude default gpbackup directory from pg_rewind
When running pg_rewind, things that exist on the target segment but
not on the source segment will be removed. In the case of HA when
recovering the preferred primary segment (mirror is active primary),
pg_rewind would try to delete the gpbackup default directory
"backups". Although this directory default is not recommended, it's a
valid path that needs to be excluded to protect backup data.
Note: This "backups" directory follows the same special GPDB exclusion
logic but with a unique difference. We must prevent the top-level
directory "backups" from being processed in the target files AND
exclude it in the source files exclusion check. This is because the
"backups" directory could exist only on the primary segment, only …
```

Exclude gpbackup default directory from pg_basebackup and pg_rewind

---

src/bin/gpfdist/gpfdist.c

###Background
When writing an external table of gpfdist protocol, segments will send 
tuples of data to gpfdist through http protocol. For each segment, it
sends a start post request with "X-GP-SEQ" set to 1 as a start request
with no data. Then it will send several post requests with sequence number
of "X-GP-SEQ".
```azure
[segment] ---->> start post request with header "X-GP-SEQ:1"
Then
[segment] ---->> data post request with header "X-GP-SEQ:2"
[segment] ---->> data post request with header "X-GP-SEQ:3"
...
[segment] ---->> data post request with header "X-GP-SEQ:n"
```
But in production environment, the socket between the segment and gpfdist 
in one post request will fail because of the network environment. The 
return value of the syscalls of "send" or "recv" through the failing …

Fix gpfdist writable external table false success for 5X.

---

src/bin/gpfdist/gpfdist.c

###Background
When writing an external table of gpfdist protocol, segments will send 
tuples of data to gpfdist through http protocol. For each segment, it
sends a start post request with "X-GP-SEQ" set to 1 as a start request
with no data. Then it will send several post requests with sequence number
of "X-GP-SEQ".
```azure
[segment] ---->> start post request with header "X-GP-SEQ:1"
Then
[segment] ---->> data post request with header "X-GP-SEQ:2"
[segment] ---->> data post request with header "X-GP-SEQ:3"
...
[segment] ---->> data post request with header "X-GP-SEQ:n"
```
But in production environment, the socket between the segment and gpfdist 
in one post request will fail because of the network environment. The 
return value of the syscalls of "send" or "recv" through the failing …

Fix gpfdist writable external table false success for 6X.

---

src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql

The case is tesing the bug when gp crash recovery, it calls
two checkpoints, if some checkpoint triggered removed/recylced
wal file, the gp_rewind might failed.
The flaky is due to sometimes when stoping the primary and
promoting the mirror, the end of recovery hasn't fully completed
after mirror is promoted, then insert some data will see errors
"seg is in recovery mode".
The fix is waiting for the end of recovery CHECKPOINT completed
after the mirror was promoted.

Fix flaky failed cases pg_rewind_fail_missing_xlog.

---

src/backend/utils/mmgr/memprot.c
src/test/isolation2/expected/oom_startup_memory.out
src/test/isolation2/sql/oom_startup_memory.sql

By default, Greenplum tracks virtual memory internally for resource group using a memory auditor referred to as vmtracker, those methods defined in `vmem_tracker.h`.If we enabled resource group, memory allocation will go through an additional step——allocate memory from vmtracker first.
To implement this, Greenplum defines `MemoryAllocationStatus` to represent the state of memory allocation:
```cpp
typedef enum MemoryAllocationStatus
{
MemoryAllocation_Success,
MemoryFailure_VmemExhausted,
MemoryFailure_SystemMemoryExhausted,
MemoryFailure_QueryMemoryExhausted,
MemoryFailure_ResourceGroupMemoryExhausted
} MemoryAllocationStatus;
```
When OOM happens, Greenplum should output different logs according to the state of memory allocation. But for now, the error message is confusing and …

update the error message when OOM happens

---

gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Sometimes pg_ctl was failing with default timeout resulting into testcase failure. To make sure that the instance is stopped, added timeout of 120 seconds.
(cherry-picked from commit 57b676af4f25c1443dccc19233b1bb685b7dab68)

[Backport 6X]Adding timeout to stop the segment in the testcase.

---

gpMgmt/bin/gpcheckcat_modules/orphaned_toast_tables_check.py
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature

gpcheckcat failed to handle when there is a temp toast table exists
In current gpcheckcat orphaned_toast_tables querey only includes toast table with format
<pg_toast.pg_toast_>, updating querey to handle tost table with format
<pg_toast<_temp_*>.pg_toast_> as well.

gpcheckcat orphaned_toast_tables fails when there is temp toast table exists

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-root-partition.xml
gpdb-doc/dita/ref_guide/sql_commands/ANALYZE.xml

the ANALYZE sql command ref page was using the term `root_partition` to refer to the name of the root partition table.  this terminology is close enough to the ROOTPARTITION keyword to be confusing.  replace root_partition with root_partition_table (the first line of the command syntax uses table) and leaf_partition with leaf_partition_table to remove any ambiguity.  also made a similar change to gporca topic.

docs - rename some ANALYZE ref page varnames to clarify

---

contrib/pageinspect/Makefile
contrib/pageinspect/bmfuncs.c
contrib/pageinspect/pageinspect--1.2--1.8.sql
contrib/pageinspect/pageinspect--1.8.sql
contrib/pageinspect/pageinspect.control
src/test/isolation2/expected/bitmap_index_inspect.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/bitmap_index_inspect.sql

Original 7X PR: https://github.com/greenplum-db/gpdb/pull/12944
Add pageinspect functions and tests for bitmap meta page, LOV page
items and bitmap pages.
Features that can be added later: bm_page_stats(), similar to
bt_page_stats().
Cherrypicking was mostly clean except for:
* Adding upgrading script 1.2->1.8 instead of 1.7->1.8 like that in 7X, since 6X only has 1.2, and we have to skip versions between 1.2 and 1.8 to make sure we can upgrade from 6X to 7X in future (see @soumyadeep2007 's comment below).
* Removing `PARALLEL` keywords from the function definitions in the scripts since that's not supported in 6X.

[6X] [backport] pageinspect bitmap support

---

src/backend/replication/basebackup.c
src/bin/pg_basebackup/t/010_pg_basebackup.pl
src/bin/pg_rewind/expected/extrafiles.out
src/bin/pg_rewind/filemap.c
src/bin/pg_rewind/sql/extrafiles.sql
src/bin/pg_rewind/t/003_extrafiles.pl

First commit:
```
Exclude default gpbackup directory from pg_rewind
When running pg_rewind, things that exist on the target segment but
not on the source segment will be removed. In the case of HA when
recovering the preferred primary segment (mirror is active primary),
pg_rewind would try to delete the gpbackup default directory
"backups". Although this directory default is not recommended, it's a
valid path that needs to be excluded to protect backup data.
Note: This "backups" directory follows the same special GPDB exclusion
logic but with a unique difference. We must prevent the top-level
directory "backups" from being processed in the target files AND
exclude it in the source files exclusion check. This is because the
"backups" directory could exist only on the primary segment, only …
```

[6X] Exclude gpbackup default directory from pg_basebackup and pg_rewind

---

src/backend/utils/resgroup/resgroup.c

len was used instead of cpuset_len. In most of cases this resulted in
garbage being copied. But rare out-of-page reads could cause a crash.
Forward-patching for main branch from #13044

Fix typo in DeserializeResGroupInfo()

---

gpcontrib/Makefile
gpcontrib/gp_sparse_vector/expected/gp_svec.out
gpcontrib/gp_sparse_vector/gp_sparse_vector--1.0.1.sql
gpcontrib/gp_sparse_vector/sql/gp_svec.sql

As #12986 mentioned, some binary operators function definition in GP extension `gp_sparse_vector` is not `strict`, which cannot properly handle NULL rows, may cause SIGSEV memory crush as follow:
```
#0  0x00007fdf3f7d74fb in raise () from /data/logs/298723/packcore-postgres.626108.181669.core/lib64/libpthread.so.0
#1  0x0000000000bf8260 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5579
#2  <signal handler called>
#3  pg_detoast_datum (datum=0x0) at fmgr.c:2209
#4  0x00007fdf183bec11 in svec_l2_eq () from /data/logs/298723/packcore-postgres.626108.181669.core/ms/dist/gpdb/PROJ/ds/6.17.7/.exec/@sys/lib/postgresql/gp_svec.so
#5  0x00000000008c590b in ExecMakeFunctionResultNoSets (fcache=0x33d19d8, econtext=0x33ddf38, …
```

(Backport to 6X) Make svec_l2_eq strict function to handle NULL properly.

---

src/backend/cdb/cdbhash.c
src/backend/cdb/cdbpullup.c
src/include/cdb/cdbhash.h
src/test/regress/expected/bfv_planner.out
src/test/regress/sql/bfv_planner.sql

Previous commit 87b9c8f9d introduces a bug in the following code
in the function cdbpullup_findEclassInTargetList:
Oid hash_proc;
PG_TRY();
{
hash_proc = cdb_hashproc_in_opfamily(hashOpFamily, em->em_datatype);
}
PG_CATCH();
{
hash_proc = InvalidOid;
}
PG_END_TRY();
However, cdb_hashproc_in_opfamily might throw error and the
PG_CATCH does not clean up thus might lead to ERRORDATA_STACK_SIZE
exceeded.
This commit fixes the issue by introducing a version of cdb_hashproc_in_opfamily
that returns InvalidOid instead of throwing error when not found. This
new API let the caller to decide what to do and seems useful.

(6x only) Fix ERRORDATA_STACK_SIZE exceeded issue.

---

gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpcreateseg.sh

Fixing bug to treat command output as string instead of array which was causing gpinitsystem failure when cluster created with mirrors and hosts have multiple interfaces configured. The regression was introduced as part of commit: 248c1c740b2f5f351ef6ee6cc4c1317397c857f9

Changes to avoid gpinitsystem failure when multiple address interfaces

---

gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpcreateseg.sh

This regression was introduced while fixing bash banner issue 248c1c740b2f5f351ef6ee6cc4c1317397c857f9
Due to this output of ifaddrs command is interpreted as text instead of array which in turn
resulted in some ip missing in pg_hba.conf. That led to failure of gpinitsystem when multiple
interfaces are present and cluster created with mirrors.
Created pipeline for 6x, will update here once green. 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb6x-dev-piyush?group=all
Update: Pipeline is green now.

[6x]Changes to avoid gpinitsystem failure when multiple address interfaces and mirrors

---

src/backend/utils/mmgr/memprot.c
src/test/isolation2/expected/oom_startup_memory.out
src/test/isolation2/sql/oom_startup_memory.sql

By default, Greenplum tracks virtual memory internally for resource group using a 
memory auditor referred to as vmtracker, those methods defined in vmem_tracker.h.
If we enabled resource group, memory allocation will go through an additional step:
allocate memory from vmtracker first.
To implement this, Greenplum defines MemoryAllocationStatus to represent the state 
of memory allocation:
- MemoryAllocation_Success
- MemoryFailure_VmemExhausted
- MemoryFailure_SystemMemoryExhausted
- MemoryFailure_QueryMemoryExhausted
- MemoryFailure_ResourceGroupMemoryExhausted
When OOM happens, Greenplum should output different logs according to the state of 
memory allocation. But for now, the error message is confusing and misleading.
So this pr is try to make it clear what things really going on to …

[6X] update the error message when OOM happens (#12971)

---

src/backend/access/transam/varsup.c
src/backend/utils/resgroup/resgroup_helper.c
src/test/isolation2/expected/resgroup/resgroup_large_group_id.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_large_group_id.sql

In the function getResUsage it will set the group Id (type Oid)'s
value from a string. Previous code use pg_atoi to do the value parse,
this is not correct because type Oid is uint, we should use
atooid. Another place is building the SQL involving group id it uses
"%d", this commits fix this by using "%u".

Fix getResUsage integer overflow.

---

src/include/utils/guc.h

removed redefined PG_AUTOCONF_FILENAME in guc.h

---

src/backend/access/transam/varsup.c
src/backend/replication/basebackup.c
src/test/isolation2/input/pg_basebackup_large_database_oid.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/pg_basebackup_large_database_oid.source

In the function SendBaseBackup it will set the group Id (type Oid)'s
value from a string. Previous code use pg_atoi to do the value parse,
this is not correct because type Oid is uint, we should use
atooid.

Fix pg_basebackup integer overflow.

---

src/backend/access/transam/varsup.c
src/backend/utils/resgroup/resgroup_helper.c
src/test/isolation2/expected/resgroup/resgroup_large_group_id.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_large_group_id.sql

In the function getResUsage it will set the group Id (type Oid)'s
value from a string. Previous code use pg_atoi to do the value parse,
this is not correct because type Oid is uint, we should use
atooid. Another place is building the SQL involving group id it uses
"%d", this commits fix this by using "%u".
(cherry picked from commit 29a9f92fcbb3fd21ddbd7fe0bb61c9abb0d28457)

(6x backport) Fix getResUsage integer overflow.

---

concourse/scripts/windows_remote_test.ps1

VC_redist.x64.exe is downloaded and saved into Windows terraform image
snapshot. Use the local copy to avoid downloading it every time which
may fail sometimes because of network issue.

Do not download VC_redist.x64.exe in windows client test

---

src/test/regress/expected/aggregates.out
src/test/regress/expected/aggregates_optimizer.out
src/test/regress/expected/gp_dqa.out
src/test/regress/expected/gp_dqa_optimizer.out
src/test/regress/sql/aggregates.sql
src/test/regress/sql/gp_dqa.sql

In the aggregates test, sometimes the prepared statements would be replanned and log ORCA
fallbacks, which are expected and ok. However, to make this more
deterministic, reset the plan cache in the test.
Additionally, enable `optimizer_trace_fallback` in the gp_dqa ICW test.
We saw a flake here, but haven't been able to repro. It's a fallback to
planner, but we're not exactly sure why. Hopefully this will give us a
hint if it happens again, and it's anyway helpful to enable this so we can more
easily tell when and why Orca falls back.

Harden flaky Orca ICW test

---

contrib/pg_upgrade/greenplum/check_gp.c
contrib/pg_upgrade/greenplum/check_gp.h
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dump.h
src/test/regress/expected/pg_dump_binary_upgrade.out
src/test/regress/greenplum_schedule
src/test/regress/sql/pg_dump_binary_upgrade.sql

First commit:
```
Ignore partition table dropped columns for pg_dump --binary-upgrade
When running pg_dump --binary-upgrade, dropped columns are always
preserved to make sure the catalog matches with the physical data
files. For GPDB partition tables, this gets very complicated because
the root partition delegates whether or not the entire partition table
will have dropped columns or not. If the root partition has dropped
columns but a child partition does not, we hit a heterogeneous
partition table scenario which requires manual user intervention. The
current user workaround for this scenario is to do a plain CTAS on the
entire partition table... but doing that could be extremely costly.
To provide a less costly workaround, we simply need to ignore the
dropped column from the partition …
```

[6X] Refactor how we handle dropped column references in partition tables during major version upgrades

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_distribution_policy.out
src/test/regress/sql/alter_distribution_policy.sql

We used to allow `ALTER TABLE ... DISTRIBUTE BY` statement to have additional storage options, and when they are present, we will re-distribute data over the segments.
However, now we have [disallowed that syntax](https://docs.greenplum.org/6-16/ref_guide/sql_commands/ALTER_TABLE.html) and only allowed one option to be passed in `ALTER TABLE ... DISTRIBUTE BY` which is the `REORGANIZE` option. 
Therefore, it makes no more sense to keep checking "new options" for making decision for re-distribution. The only place to use the "new options" (i.e. variable `newOptions` in `ATExecSetDistributedBy()`, which btw has been reduced to just getting the existing `pg_class.reloptions` of the table) is for building CTAS statement.

"New options" shouldn't affect redistribution in ALTER TABLE ... DISTRIBUTE BY

---

src/backend/cdb/cdbpartindex.c
src/backend/cdb/partitionselection.c

This PR is for 6X only. This code no longer exists in gpdb master,
and this issue isn't present there.
This PR optimizes the remapping of leaf partitions to root
partitions for use in Orca. In recordIndexesOnLeafPart, we don't need to
recompute the attamp for each index, we just need to do it once. For one
query with many indexes and columns on a partitioned table, this brought
the planning time from 7.5s to .85s using Orca.
In varattnos_map, we would check each attribute of the old and new tuple
descriptor in an n^2 fashion. This is necessary to handle dropped/moved
columns. However, instead we'll do a first iteration through all the
columns, if they're equal and nothing has been dropped/moved, we don't
need to do this additional n^2 logic. This brings the planning time for
this query …

Optimize retrieving indexes on partitions within Orca

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/query33.ans

set gpload staging table schema to gpload:external:schema in yaml file
backport pr for 6X: https://github.com/greenplum-db/gpdb/pull/13109

set gpload staging table schema to gpload:external:schema in yaml file

---

gpdb-doc/dita/admin_guide/external/g-devel-fdw.xml
gpdb-doc/dita/admin_guide/external/g-foreign.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_DATA_WRAPPER.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_TABLE.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_SERVER.xml

docs for old PRs https://github.com/greenplum-db/gpdb/pull/9943 and https://github.com/greenplum-db/gpdb/pull/9987, greenplum supports parallel writes to foreign tables.  in this PR:
- add the fdw write callbacks to the "writing an fdw" page
- reorg the "accessing foreign tables" page (new "Using FDWs with Greenplum Database" topic) and include info about mpp_execute option
- update server/fdw/foreigntable sql ref pages
notes:  
- this PR does not include docs for new num_segments option, will submit those changes in a separate PR
- will backport to 6X_STABLE
- accessing foreign tables page: https://docs-lisa-fdw-pwrite.sc2-04-pcf1-apps.oc.vmware.com/6-19/admin_guide/external/g-foreign.html
- writing an fdw page: …

docs - greenplum can support fdw parallel writes

---

src/backend/optimizer/plan/subselect.c
src/include/optimizer/subselect.h
src/test/regress/expected/qp_correlated_query.out
src/test/regress/expected/qp_correlated_query_optimizer.out
src/test/regress/sql/qp_correlated_query.sql

Execution of multilevel correlated queries with high level of nesting
can cause segfault(when using array_agg, json_agg) or can provide wrong
results (when using classic aggs like sum()). Due to some GP
limitations, correlated subqueries with skip-level correlations are not
supported. Additional check condition is provided to prevent such
queries from planning. QueryHasDistributedRelation function, used by
this check, doesn't recurse over subplans and may return wrong results
for distributed RTE_RELATION entries hidden by RTE_SUBQUERY entries.
Commit fixes such behavior by adding optional recursion to
QueryHasDistributedRelation function. Additional regression test is
included. Additional information can be found at issue #12054.

Fix segfault on execution of multilevel correlated queries.

---

src/backend/optimizer/plan/subselect.c
src/include/optimizer/subselect.h
src/test/regress/expected/qp_correlated_query.out
src/test/regress/expected/qp_correlated_query_optimizer.out
src/test/regress/sql/qp_correlated_query.sql

Execution of multilevel correlated queries with a high level of nesting
can cause segfault(when using array_agg, json_agg) or can provide wrong
results (when using classic aggs like sum()). Due to some GP
limitations, correlated subqueries with skip-level correlations are not
supported. Additional check condition is provided to prevent such
queries from planning. QueryHasDistributedRelation function, used by
this check, doesn't recurse over subplans and may return wrong results
for distributed RTE_RELATION entries hidden by RTE_SUBQUERY entries.
Commit fixes such behavior by adding optional recursion to
QueryHasDistributedRelation function. Additional regression test is
included. Additional information can be found at issue https://github.com/greenplum-db/gpdb/issues/12054.

6X: Fix segfault on execution of multilevel correlated queries.

---

src/backend/utils/hyperloglog/gp_hyperloglog.c

set data with bzero in order to fix #13102 comiling error cause by GCC 11.2  [-Werror=maybe-uninitialized].

set memory allocated by malloc to 0 to fix 'error: ‘data’ may be used uninitialized'

---

src/backend/commands/tablecmds.c

This commit is to confirm and remove the FIXME message that we can safely stop closing relations in `ATExecSetDistributedBy()` (already done so in 8518ed4). Detailed reason as below.
In the earliest historical commit that supported `ALTER TABLE SET DISTRIBUTE`, we needed to close relations in `ATExecSetDistributedBy()`, just before swapping the original table and temp table (`swap_relation_files()`) because `swap_relation_files()` back then needed to forget the relcache entries in order to work around some dangling smgr entry issue: https://github.com/greenplum-db/gpdb/blob/5X_STABLE/src/backend/commands/cluster.c#L1249-L1263
Therefore `ATExecSetDistributedBy()` had to close the relation: https://github.com/greenplum-db/gpdb/blob/5X_STABLE/src/backend/commands/tablecmds.c#L12209-L12216 …

Resolve a merge FIXME for ATExecSetDistributedBy()

---

src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql

The case is tesing the bug when gp crash recovery, it calls
two checkpoints, if some checkpoint triggered removed/recylced
wal file, the gp_rewind might failed.
The flaky is due to sometimes when stoping the primary and
promoting the mirror, the end of recovery hasn't fully completed
after mirror is promoted, then insert some data will see errors
"seg is in recovery mode".
The fix is waiting for the end of recovery CHECKPOINT completed
after the mirror was promoted.

[6X]Fix flaky failed cases pg_rewind_fail_missing_xlog.

---

src/backend/access/aocs/aocsam.c
src/backend/commands/createas.c
src/backend/tcop/utility.c
src/test/regress/expected/gpctas.out
src/test/regress/sql/gpctas.sql

When the table is created using "CREATE TABLE ... AS ... WITH NO DATA" pg_attribute_encoding may be omitted in some cases. This can result in a crash when reading the table with AOCS storage.
This commit fixes installment of pg_attribute_encoding for CTAS WITH NO DATA and adds a test for the case.
Fix for #12936

Install pg_attribute_encoding for AOCS during CTAS

---

src/backend/access/aocs/aocsam.c
src/backend/access/appendonly/appendonlyam.c
src/test/isolation2/input/uao/snapshot_index_corruption.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/snapshot_index_corruption.source

Using of regular MVCC snapshot to access AO-tables metadata may cause index building (performed globally) inconsistency, because tuples inserted (the same globally) at another opened transactions are not visible.
Commit fixes such behavior using SnapshotSelf for metadata access. Additional isolation test shows how to reproduce the bug before the fix.
Via #12797
___________________
Second test is not actual, because we already use SnapshotAny for data access, but I decided to keep it.

Fix index corruption when invalid snapshot used with AO tables.

---

src/backend/catalog/index.c
src/backend/commands/indexcmds.c
src/test/isolation2/input/uao/snapshot_index_corruption.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/snapshot_index_corruption.source

Using of regular MVCC snapshot to access AO-tables metadata may cause index building (performed globally) inconsistency, because tuples inserted (the same globally) at another opened transactions are not visible. Using the same MVCC snapshot to access AO-tables data ignore RECENTLY_DEAD tuples, used, for example, by "repeatable read" transactions, which again leads to inconsistent results caused by index access.
Commit fixes such behavior using SnapshotSelf for metadata access and SnapshotAny for data access. Additional isolation tests shows how to reproduce the bug before the fix.
_______________
When building an index, the MVCC snapshot [taken](https://github.com/arenadata/gpdb/blob/18d86c55845cecb9325a338c2f8cc389b877544e/src/backend/tcop/pquery.c#L1371) before …

[6X] Fix index corruption when invalid snapshot used with AO tables.

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_distribution_policy.out
src/test/regress/sql/alter_distribution_policy.sql

Backporting #13092
No major merge conflict. Code change exactly the same.
-------------
This fixes an issue where existing reloptions would cause a reorganize in
situations that it should not. We used to allow ALTER TABLE SET DISTRIBUTE WITH
clause to have additional storage options, and when they are present, we
will re-distribute data over the segments.
However since 50f2e3bbb88, we don't allow new reloptions to be supplied in the
ALTER TABLE SET DISTRIBUTED WITH clause. So this commit is really a follow-up,
removing redistribution decision making logic based on reloptions.
Also renamed new_rel_opts() to get_rel_opts() accordingly.

[6X] Existing reloption shouldn't affect redistribution in SET DISTRIBUTE BY

---

src/backend/cdb/cdbappendonlystoragewrite.c

Previously we only flushed but didn't close AO segment in
AppendOnlyStorageWrite_FlushAndCloseFile() function. It caused
file descriptors stuck in backends' cache, that could delay kernel
to free disk space after such files would be unlinked.
Back-ported from: https://github.com/greenplum-db/gpdb/commit/d3a4fa897aef820386b3cb6f2f14650aa0dcbe6c

[6X] Close AO segment file

---

src/backend/storage/smgr/md.c

When committing a transaction that dropped a relation, we previously
truncated only the first segment file to free up disk space (the one
that won't be unlinked until the next checkpoint).
Truncate higher numbered segments too, even though we unlink them on
commit.  This frees the disk space immediately, even if other backends
have open file descriptors and might take a long time to get around to
handling shared invalidation events and closing them.  Also extend the
same behavior to the first segment, in recovery.
Back-patch to all supported releases.
Bug: #16663
Reported-by: Denis Patron <denis.patron@previnet.it>
Reviewed-by: Pavel Borisov <pashkin.elfe@gmail.com>
Reviewed-by: Neil Chen <carpenter.nail.cz@gmail.com>
Reviewed-by: David Zhang <david.zhang@highgo.ca>
Discussion: …

[6X] Free disk space for dropped relations on commit.

---

src/backend/access/heap/vacuumlazy.c

the fault 'vacuum_update_dat_frozen_xid' injected in autovacuum-segment
was not triggred until Time-out, which makes the autovacuum-segment case
failed.
the reason why the injected fault 'vacuum_update_dat_frozen_xid' was not
triggred was some shared tables such as pg_shseclabel(it's randomly, but
must be some of critical shared tables) didn't change its frozenxid in
regression.pg_class tuple, so the database 'regression' couldn't update
its frozenxid either.
This reverts commit 2aa6e33, that added a fast path to skip
anti-wraparound and non-aggressive autovacuum jobs (these have no sense
as anti-wraparound implies aggressive).  With a cluster using a high
amount of relations with a portion of them being heavily updated, this
could cause autovacuum to lock down, with autovacuum workers …

Revert "Skip redundant anti-wraparound vacuums" to fix flacky case

---

gpdb-doc/dita/admin_guide/external/g-devel-fdw.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_DATA_WRAPPER.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_TABLE.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_SERVER.xml
gpdb-doc/dita/ref_guide/sql_commands/GRANT.xml

update the CREATE SERVER sql ref page for https://github.com/greenplum-db/gpdb/pull/12920, https://github.com/greenplum-db/gpdb/pull/12789 (6X_STABLE, not yet merged).  PR also includes some misc edits for consistency.
will be backport to 6X_STABLE.
note:  this PR is against master.  the 6X_STABLE feature PR removes the num_segments option from foreign table.  i am assuming that this change will be forward-ported to 7/master.  let me know if that is not the case.

docs - new foreign server num_segments option

---

src/backend/executor/nodeWindowAgg.c
src/test/regress/expected/misc_jiras.out
src/test/regress/expected/statement_mem_for_windowagg.out
src/test/regress/greenplum_schedule
src/test/regress/sql/misc_jiras.sql
src/test/regress/sql/statement_mem_for_windowagg.sql

This patch helps fix incorrect amount of memory allocated for WindowAgg.
Greenplum uses statement_mem rather than work_mem to control the memory
allocated to queries. Besides, test cases are attached for this patch.

Fix incorrect amount of memory allocated for WindowAgg.

---

.travis.yml
src/backend/commands/foreigncmds.c
src/backend/foreign/foreign.c
src/backend/optimizer/util/pathnode.c
src/backend/optimizer/util/plancat.c
src/include/foreign/foreign.h
src/include/nodes/pathnodes.h
src/test/regress/expected/.gitignore
src/test/regress/expected/gp_foreign_data.out
src/test/regress/sql/.gitignore
src/test/regress/sql/gp_foreign_data.sql

https://github.com/greenplum-db/gpdb/commit/aa7c74cfa4734ae6d2969740a0b341d26ea4ad2e - Support num_segments option for foreign servers and tables
Commit above introduces the support of num_segments option, however in
practice the option for foreign tables confuses the user.
This commit removes it from the foreign table layer, only the foreign
servers support.

Remove num_segments option from the foreign table layer

---

gpMgmt/bin/gpstop
gpMgmt/test/behave/mgmt_utils/gpstop.feature
gpMgmt/test/behave/mgmt_utils/steps/gpstart.py

Added check for standby reachability before stopping the standby to avoid gpstop failures when standby is unreachable.
Added behave test case for gpstop when standby is not reachable.

Changes to avoid gpstop errors when standby is not reachable.

---

src/backend/catalog/index.c
src/backend/commands/indexcmds.c
src/test/isolation2/input/uao/snapshot_index_corruption.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/snapshot_index_corruption.source

This is a resubmission of 44dc41a212b98b7b60c470f8f85ffc72894526fe (#12797) which introduced a compile error because uninitialized `OldestXmin` in some code path. The fix is simple but since the error is blocking release 6.19.3 currently and it takes time to verify the fix on pipeline, we've just reverted the original commit and re-submitted this PR which has the `OldestXmin` been fixed.
For some reason, this PR didn't trigger any pipeline job. Manually started a dev pipeline to verify: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/index-fix-compile-error
(_update: all tests passed_)

Fix index corruption when invalid snapshot used with AO tables. (#12797)

---

src/test/regress/expected/misc_jiras.out
src/test/regress/expected/statement_mem_for_windowagg.out
src/test/regress/sql/misc_jiras.sql
src/test/regress/sql/statement_mem_for_windowagg.sql

We observed greenplum built without cassert couldn't pass tests. Because
when the gpdb is configured with --enable-cassert, the minimum
statement_mem it accepts is 50kB while if it's configured without
--enable-cassert, the minimum statement_mem it accepts is 1000kB (See:
backend/utils/misc/guc_gp.c).
Some failed pipelines:
gpdb_master_without_asserts/icw_planner_rhel8: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master_without_asserts/jobs/icw_planner_rhel8/builds/145
gpdb_master_without_asserts/icw_gporca_icproxy_rhel8: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master_without_asserts/jobs/icw_gporca_icproxy_rhel8/builds/145
This patch is trying to make them happy.

Set statement_mem to a larger value in tests to make pipelines happy.

---

src/test/isolation2/input/parallel_retrieve_cursor/fault_inject.source
src/test/isolation2/output/parallel_retrieve_cursor/fault_inject.source

This patch is trying to make isolation2/parallel_retrieve_cursor/fault_inject
stable by replacing 'sleep' fault with 'suspend' fault.
I can reproduce the failure with my machine by running installcheck multiple
times and I cannot reproduce it with this patch being applied. 
Below is the regression.diffs file fetched from the PR pipeline.
```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /tmp/build/d62a0504/gpdb_src/src/test/isolation2/expected/parallel_retrieve_cursor/fault_inject.out /tmp/build/d62a0504/gpdb_src/src/test/isolation2/results/parallel_retrieve_cursor/fault_inject.out
--- /tmp/build/d62a0504/gpdb_src/src/test/isolation2/expected/parallel_retrieve_cursor/fault_inject.out	2022-02-24 16:18:00.128491568 +0000
+++ /tmp/build/d62a0504/gpdb_src/src/test/isolation2/results/parallel …
```

Trying to make parallel_retrieve_cursor/fault_inject stable.

---

src/test/regress/expected/misc_jiras.out
src/test/regress/sql/misc_jiras.sql

This is a follow-up patch for ad8b266 and a039910 to make pipelines
happy.
Previous commits are causing CI failure.
See: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master_without_asserts/jobs/icw_planner_icproxy_ubuntu18.04/builds/603

Insert more data to make tuplestore spill in regress/misc_jiras.sql.

---

src/backend/cdb/motion/cdbmotion.c
src/backend/commands/foreigncmds.c
src/backend/executor/execMain.c
src/backend/foreign/foreign.c
src/backend/optimizer/util/pathnode.c
src/backend/optimizer/util/plancat.c
src/include/foreign/foreign.h
src/test/regress/expected/gp_foreign_data.out
src/test/regress/sql/gp_foreign_data.sql

This PR contains two features needed by Greenplum FDW.
1, Support creating a Gang with QEs more than the segment count 
Scenarios like FDW could have more QEs than the segment count to query
the foreign clusters.
2, Support num_segments option for foreign servers
Support specifying the num_segments option for foreign servers,
Greenplum will create that amount of QEs if the `mpp_execute`
option's value is 'all segments'.
```
CREATE SERVER s1 FOREIGN DATA WRAPPER dummy OPTIONS (num_segments '42');
```

6X: Backport FDW features to support Greenplum FDW

---

src/backend/executor/nodeShareInputScan.c
src/test/regress/expected/shared_scan.out
src/test/regress/expected/shared_scan_optimizer.out
src/test/regress/greenplum_schedule
src/test/regress/sql/shared_scan.sql

Current 6X ShareInputScan using FIFO as the notification mechanism between processes and using `select()` to detect whether the specific fd can read.
But `select()` has the "**max fd number**" limit, we can see the check logic (65535) in `MPP_FD_SET()`:
```
#define MPP_FD_SET(fd, set) do{ \
if (fd > 65535) \
elog(FATAL,"Internal error:  Using fd > 65535 in MPP_FD_SET"); \
((set)->__fds_bits[MPP_FD_WORD(fd)] = ((set)->__fds_bits[MPP_FD_WORD(fd)]) | MPP_FD_BIT(fd)); \
} while(0)
```
One error scene example is 
```
Sequence  (cost=0.00..9854193.27 rows=149 width=205) (actual time=19477.963..20583.114 rows=456618 loops=1)
->  Shared Scan (share slice:id 0:0)  (cost=0.00..431.00 rows=1 width=1) (actual time=15.110..15.114 rows=1 loops=1)
->  Materialize  (cost=0.00..431.00 rows=1 width=1) …
```

Using poll instead of select in nodeShareInputScan

---

gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.c
src/backend/utils/misc/faultinjector.c
src/include/utils/faultinjector.h
src/test/regress/expected/psql_gp_commands.out
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

The fault 'send_qe_details_init_backend' injected in dispatch.source was
triggered by other backend processes by accident, which makes the
dispatch case flaky.
This commit provide another version of gp_inject_funtion() with an extra
parameter, so that the fault could be fixed by specific session, to
avoid the fault triggered by other backend process unexpectly.

[6x] Add another version of gp_inject_funtion() to fix flaky case

---

src/test/regress/expected/brin.out
src/test/regress/expected/brin_ao.out
src/test/regress/expected/brin_ao_optimizer.out
src/test/regress/expected/brin_aocs.out
src/test/regress/expected/brin_aocs_optimizer.out
src/test/regress/expected/brin_optimizer.out
src/test/regress/sql/brin.sql
src/test/regress/sql/brin_ao.sql
src/test/regress/sql/brin_aocs.sql

Using ORCA, CI has caught instances of brin_ao regress test failing with
following diff:
```
-WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,<=,inet,255.255.255.255,100)
WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,>,cidr,0.0.0.0,125)
-WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,>,inet,0.0.0.0,125)
WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,>=,cidr,0.0.0.0,125)
+WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,<=,inet,255.255.255.255,100)
+WARNING:  ORCA did not produce a bitmap indexscan plan for (inetcol,>,inet,0.0.0.0,125)
```
Issue appears to be due to dependency of volatile ordering. Testcase orders by
"colname" and "typ", but seems like we should add "op" as well.

Fix flaky brin testcase

---

GNUmakefile.in
contrib/btree_gin/Makefile
contrib/btree_gin/btree_gin.c
contrib/btree_gin/expected/money.out
contrib/btree_gin/sql/money.sql
contrib/pg_trgm/Makefile
contrib/pg_trgm/expected/pg_trgm_optimizer.out

from 7X branch https://github.com/greenplum-db/gpdb/pull/12927 https://github.com/greenplum-db/gpdb/pull/12928
in 812f297e9a0c55ae311454c2705974fe3e44ba94 299606b807ab77ae1121c34a59b4325cd2e01131 this patch was reverted because it is a new feature. should merge in GPDB 6.20 not 6.19.3.
now, the 6.20 merge window is ready, I am bringing this back.

6X: enable pg_trgm and btree_gin

---

src/backend/cdb/dispatcher/cdbgang.c
src/backend/storage/lmgr/proc.c
src/backend/utils/time/sharedsnapshot.c
src/test/isolation2/input/idle_gang_cleaner.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/idle_gang_cleaner.source

* Fix shared snapshot collision (cherry picked from commit https://github.com/greenplum-db/gpdb/commit/cc58ac6afec2587ae7afb489f59fc7c1d1949325)
> FATAL "writer segworker group shared snapshot collision" happens when
gp_vmem_idle_time reached, the QD will clean the idle writer and
reader gang and close the connection to the QE, QE will quit in an
async way. QD processes remain. If QE cannot quit before QD starts a
new command, it will find the same session id in the shared snapshot
and collision will happen. QE session quit may take time due to
ProcArrayLock contention.
> Hence, this commit only cleans up reader gangs and not writer gang
during idle cleanup session timeout. This way no need to remove and
readd shared snapshot slot on QEs and hence avoids the collision
possibility.
* add …

Fix shared snapshot collision 

---

src/backend/catalog/dependency.c
src/backend/parser/gram.y
src/test/regress/input/appendonly.source
src/test/regress/output/appendonly.source

1. In `greenplumLegacyAOoptions()` : the comment reminds us about adding sanity check for the AO options in the WITH clause. However, it seems that all the necessary sanity check should be already in place, either in greenplumLegacyAOoptions() itself or elsewhere. So here we just need to add some missing test cases and can resolve the comment.
2. In `checkDependencies()` : the flags passed to `findDependentObjects()` are for deletion only (`PERFORM_DELETION_xxx`). So it's ok here.

Remove two FIXME comments in greenplumLegacyAOoptions() and checkDependencies()

---

gpMgmt/bin/gpload_test/.gitignore
gpMgmt/bin/gpload_test/gpload2/TEST_local_legacy.py
gpMgmt/bin/pythonSrc/PyGreSQL-4.0/pgmodule.c

1. Recover gpload test case 22. It was a flaky case about gpload count formatting errors.
2. Ask for a GIL (global interpreter lock) during function notice_processor()
In CPython, GIL is a mutex that prevents multiple native threads from executing Python bytecodes at once. Threads created by low-level C codes also need GIL to do something to python objects.
Pygresql will fork a thread to process notices and call notice_processor() after finishing the query. So we need to ask for GIL to process notices and store them in python objects.

fix gpload occasional error to count formatting error

---

src/backend/cdb/cdbpartindex.c
src/backend/executor/nodeDynamicBitmapIndexscan.c
src/backend/executor/nodeDynamicIndexscan.c
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/libnaucrates/src/md/CMDRelationGPDB.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/qp_dropped_cols.out
src/test/regress/expected/qp_dropped_cols_optimizer.out
src/test/regress/output/partindex_test.source
src/test/regress/sql/gporca.sql
src/test/regress/sql/qp_dropped_cols.sql

In Orca, we currently only support index/bitmap scans if the entire partitioned table has the 
same index storage type in most cases.
For Orca, indexes on partitioned tables are marked as partial or non-partial. It is partial if
there is not a homogenous index on all partitions. This can occur if
there are not indexes on some partitions, or if there are different
index types on some partitions. When we create a btree index on an AO
partition, we mark this internally as a bitmap index, as the executor cannot run an index
scan on an AO table. This is a bit of a hack, as the underlying storage
is still a btree index, and we build the bitmap index during the scan.
This way, GPDB is still able to perform a bitmap scan on a btree index.
The goal of this PR is to support bitmap scans on …

[6X] Support bitmap scans on mixed heap/AO partitioned tables

---

src/backend/access/common/reloptions_gp.c
src/backend/catalog/pg_attribute_encoding.c
src/backend/catalog/pg_compression.c
src/backend/catalog/pg_type.c
src/backend/commands/indexcmds.c
src/backend/commands/tablecmds.c
src/backend/commands/tablecmds_gp.c
src/backend/commands/typecmds.c
src/backend/parser/parse_utilcmd.c
src/include/access/reloptions.h
src/include/catalog/pg_attribute_encoding.h
src/include/catalog/pg_compression.h
src/include/catalog/pg_type.h
src/include/commands/tablecmds.h
src/include/parser/analyze.h
src/test/regress/expected/column_compression.out

This PR attempts to refactor the code around processing the encoding clauses mainly in CREATE TABLE, ALTER TABLE, CREATE TYPE and ALTER TYPE. A total of 15 related FIXMEs are removed here.
Also removed another FIXME in `makeObjectName()` that's not related to encoding but it's fairly straightforward: we added an elog(ERROR) to workaround an assert failure in the regress test. But I ran the regress test and didn't see the failure, so restored the code and removed the FIXME. If there's ever an assert failure again, we should fix the same instead of adding another FIXME.
The changes mainly include:
* Refactor encoding code for CREATE TABLE and ALTER TABLE 
* Remove `transformAttributeEncoding()` and create `transformColumnEncoding()` to be used in both `DefineRelation()` and …

Refactoring encoding related code and resolve related FIXMEs

---

src/backend/postmaster/bgwriter.c

I'm trying to investigate some flaky test failure of
regress/fsync/bgwriter_checkpoint.sql and haven't made any progress so
far. However, I found that the fault injection point
'fault_in_background_writer_main' wasn't enabled in builds without
assertion. So, this patch helps fix it.
P.S. 6X_STABLE branch has the same issue.
https://github.com/greenplum-db/gpdb/blob/5a435d78e0d0f4d1779bf61d93d68d9e95c5d699/src/backend/postmaster/bgwriter.c#L263-L265

Enable faultinject point 'fault_in_background_writer_main' in builds without assertion.

---

src/backend/commands/tablecmds.c
src/test/regress/expected/partition_expand.out

gpexpand in partition table has two-stage:
1. if the root table is hash distributed, change the leaf tables to randomly distributed, 
that's what `ALTER TABLE EXPAND PARTITION PREPARE` does. And extract the table 
info into `gpexpand.status_detail`. 
2. perform actual expansion, moving data to correct segment.
For the current implementation, we can not re-enter `ALTER TABLE EXPAND PARTITION PREPARE` 
because it's not reentrant. So if we failed at stage-1 for some reason, like share memory 
exhausted, we cannot re-execute the expand script, it's a problem.
So this PR make `ALTER TABLE EXPAND PARTITION PREPARE` reentrant by changing the 
`ERROR` to `NOTICE`, just leave a NOTICE message instead of aborting the transaction.

make ALTER TABLE EXPAND PARTITION PREPARE reentrant

---

src/backend/commands/tablecmds.c
src/test/regress/expected/partition_expand.out

gpexpand in partition table has two-stage:
1. if the root table is hash distributed, change the leaf tables to randomly distributed, 
that's what `ALTER TABLE EXPAND PARTITION PREPARE` does. And extract the table 
info into `gpexpand.status_detail`. 
2. perform actual expansion, moving data to correct segment.
For the current implementation, we can not re-enter `ALTER TABLE EXPAND PARTITION PREPARE` 
because it's not reentrant. So if we failed at stage-1 for some reason, like share memory 
exhausted, we cannot re-execute the expand script, it's a problem.
So this PR make `ALTER TABLE EXPAND PARTITION PREPARE` reentrant by changing the 
`ERROR` to `NOTICE`, just leave a NOTICE message instead of aborting the transaction.

[6X] make ALTER TABLE EXPAND PARTITION PREPARE reentrant

---

gpdb-doc/dita/ref_guide/modules/btree_gin.xml
gpdb-doc/dita/ref_guide/modules/intro.xml
gpdb-doc/dita/ref_guide/modules/modules.ditamap
gpdb-doc/dita/ref_guide/modules/pg_trgm.xml
gpdb-doc/markdown/install_guide/install_modules.html.md

docs for: https://github.com/greenplum-db/gpdb/pull/12928, https://github.com/greenplum-db/gpdb/pull/12927, https://github.com/greenplum-db/gpdb/pull/12929 (6X_STABLE)
GPORCA support of these new modules is not clear to me...

docs - add topics for btree_gin and pg_trgm modules

---

configure
configure.in
src/Makefile.global.in
src/backend/libpq/Makefile
src/backend/libpq/auth.c
src/backend/libpq/be-gssapi-common.c
src/include/libpq/be-gssapi-common.h
src/include/pg_config.h.in
src/interfaces/libpq/fe-auth.c

1. Create the with_gssapi output variable for autoconf 
2. Stores kerberos proxy credentials in memory of backend,  and check the cache and reuse it in fe-auth.
```
+--------+      +-----------+          +---------------+
| client |------| Greenplum |----------| remote server |
+--------+      +-----------+   (FDW)  +---------------+
Kerberos delegation
```
3. Add `HAVE_GSSAPI_PROXY` macro in configure to indicate wether the krb5-lib supports kerberos proxy API.
This PR is split from PR #12789. 
It depends on krb5-lib 1.15+.

[6X] support kerberos delegation in libpq

---

concourse/pipelines/pr_pipeline.yml

For PR Pipeline, use dedicated (tagged) ICW workers (icw-centos7).

PR pipeline: Use dedicated worker (icw-centos7).

---

src/backend/access/appendonly/appendonlyam.c

Resolve GPDB_12_MERGE_FIXMEs: TOAST for AO_ROW Table
This is intended to keep TOAST enabled for AO_ROW table.
Although large contents of attributes can be fully stored
in AO_ROW table, it is still necessary to keep TOAST capability
for AO_ROW to deal with out-of-line data storage case.
Queries (like select pg_relation_size()) will get better
performance for skipping fetching the out-of-line data unless
it is required. It is a good way of keeping tables being stored
locally and compactly.
However, for AOCS tables, we removed TOAST long time ago, because
there is meaningless to store a column data outside the column
storage itself. Long length content for a single column is not
a problem and no row-like overflow situation in column oriented
storage. Queries on AOCS tables always return all …

Resolve GPDB_12_MERGE_FIXMEs: TOAST for AO_ROW Table

---

src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql

The fts_unblock_primary isolation2 test would sometimes fail stating
that the GUC value was not updated after running `gpstop -u` to reload
from the updated postgresql.conf file. The cause of the flakiness was
due to the assumption that the SHOW command would immediately be
usable after `gpstop -u` returned. The `gpstop -u` command merely
sends SIGHUP signals to all the segments (e.g. pg_ctl reload on all
the segments) and does not do any validations. In this test, the SHOW
command was being run before the SIGHUP signal was handled which
resulted in the incorrect value being displayed. To fix this test
flake, we simply need to close our SQL connection after sending the
SIGHUP signals and open a new connection to run the SHOW command. This
solution works because the new connection will …

Fix flaky fts_unblock_primary isolation2 test

---

src/backend/tcop/postgres.c
src/test/recovery/t/009_twophase.pl
src/test/recovery/t/012_subtransactions.pl
src/test/regress/expected/gp_prepared_xacts.out
src/test/regress/expected/temp.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_prepared_xacts.sql
src/test/regress/sql/temp.sql

In GPDB, we do not allow users to use PREPARE TRANSACTION in regular
and utility-mode connections to prevent any conflicts/issues with
GPDB's distributed transaction manager that heavily utilizes two-phase
commit. As part of the Postgres 10 merge into GPDB, a regression was
introduced that allowed PREPARE TRANSACTION to be run in utility-mode
connections. The error check was being bypassed because the
TransactionStmt was not being properly obtained. The cause of this was
due to an upstream Postgres refactor that introduced RawStmt which
would wrap the TransactionStmt so the TransactionStmt typecast was
being done on the wrong parse node (needs to be done on the
RawStmt->stmt). Added simple regression test to make sure this
regression doesn't occur again from future Postgres merges. Also …

Fix regression about PREPARE TRANSACTION in utility-mode connections

---

src/backend/executor/nodeWindowAgg.c
src/backend/utils/sort/tuplesort.c
src/backend/utils/sort/tuplesort_mk.c
src/include/utils/tuplesort.h
src/include/utils/tuplesort_gp.h
src/include/utils/tuplesort_mk.h
src/test/regress/expected/misc_jiras.out
src/test/regress/expected/statement_mem_for_windowagg.out
src/test/regress/greenplum_schedule
src/test/regress/sql/misc_jiras.sql
src/test/regress/sql/statement_mem_for_windowagg.sql

This patch helps fix incorrect amount of memory allocated for WindowAgg.
Greenplum uses statement_mem rather than work_mem to control the memory
allocated to queries. Besides, test cases are attached for this patch.
This is a backport of ad8b266 from the master branch.
The differences between 6X_STABLE and master are as follows
1. Tuplesort in 6X_STABLE supports multi-key sorting so I've added some
additional tests for it.
2. tuplesort_get_stats() in 6X_STABLE is a static function, I've made it
visible from other translation units.

[6X] (Backport) Fix incorrect amount of memory allocated for WindowAgg.

---

src/backend/cdb/dispatcher/cdbgang.c
src/backend/storage/lmgr/proc.c
src/backend/utils/time/sharedsnapshot.c
src/test/isolation2/input/idle_gang_cleaner.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/idle_gang_cleaner.source

* Fix shared snapshot collision (cherry picked from commit https://github.com/greenplum-db/gpdb/commit/cc58ac6afec2587ae7afb489f59fc7c1d1949325)
> FATAL "writer segworker group shared snapshot collision" happens when
gp_vmem_idle_time reached, the QD will clean the idle writer and
reader gang and close the connection to the QE, QE will quit in an
async way. QD processes remain. If QE cannot quit before QD starts a
new command, it will find the same session id in the shared snapshot
and collision will happen. QE session quit may take time due to
ProcArrayLock contention.
> Hence, this commit only cleans up reader gangs and not writer gang
during idle cleanup session timeout. This way no need to remove and
readd shared snapshot slot on QEs and hence avoids the collision
possibility.
* add …

[6x]Fix shared snapshot collision

---

gpMgmt/bin/gpexpand

For the current stage-1 implementation in gpexpand, we run ALTER TABLE EXPAND PARTITION 
PREPARE in a single transaction with the database as the dimension, then when there are many 
partition tables in a database, the ALTER TABLE statement will hold a large number of locks, 
which is likely to cause shared memory exhaustion.
Therefore, we split it into multiple transactions to execute separately, this does not break existing 
processes. In a local performance test, 500 partitioned tables with 700 subtables took about 21 
minutes to complete all preparation. I think it's acceptable.
Here are some performance tests result between run `ALTER TABLE EXPAND PARTITION PREPARE` in a 
single transaction and in a multi transaction:
single transaction spent: 13.754475116729736s
multi transaction …

run ALTER TABLE EXPAND PARTITION PREPARE in separate transactions

---

gpMgmt/bin/gpexpand

For the current stage-1 implementation in gpexapnd, we run ALTER TABLE EXPAND PARTITION 
PREPARE in a single transaction with the database as the dimension, then when there are many 
partition tables in a database, the ALTER TABLE statement will hold a large number of locks, 
which is likely to cause shared memory exhaustion.
Therefore, we split it into multiple transactions to execute separately, this does not break existing 
processes. In a local performance test, 500 partitioned tables with 700 subtables took about 21 
minutes to complete all preparation. I think it's acceptable.

[6X] run ALTER TABLE EXPAND PARTITION PREPARE in separate transactions

---

src/include/libpq/be-gssapi-common.h

c2e56adb5b46e0c95aa7a1970d92cacca4cf0548 introduced kerberos delegation
in libpq. It missed the ENABLE_GSS guard rail in be-gssapi-common.h.
Without this patch, even if we are building without the --with-gssapi
flag, we would run into the following error (reported on Ubuntu 20.04.4
LTS) if we don't have dependencies installed:
../../../src/include/libpq/be-gssapi-common.h:20:10: fatal error: gssapi/gssapi.h: No such file or directory
20 | #include <gssapi/gssapi.h>
|          ^~~~~~~~~~~~~~~~~
compilation terminated.

[6X] be-gssapi-common.h: Introduce configure guard

---

src/test/isolation/expected/insert-conflict-toast_1.out

The insert-conflict-toast isolation test would sometimes fail with a
weird diff that showed one INSERT in the permutation happening before
another INSERT. From first glance, it clearly looks like a race
condition which I was able to confirm by reproducing the issue on my
local machine. Upstream Postgres has already seen this issue before
with this isolation test and has a couple fixes on top but for the
current GPDB snapshot of PG12, the solution is to have a secondary
expected output file. Weirdly enough, the secondary expected output
file already existed but was not up-to-date. Updated it and confirmed
the output race condition is now properly handled.

Fix flaky insert-conflict-toast isolation test

---

src/backend/access/aocs/aocsam.c
src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c

This PR contains two following FIXMEs:
- Not scan visimap for AO/AOCS costing
For Heap table, visibility map may help to estimate
the number of page fetches can be avoided during an
index-only scan. That is not the case for AO/AOCS table
since index-only scan hasn't been used with AO/AOCS.
So leave the comment here for future reference once
we have a clear requirement to do that.
- Rename aocs_initscan to initscan_with_colinfo

Resolve GPDB_12_MERGE_FIXMEs

---

src/backend/commands/collationcmds.c

Postgres 10 added the ```pg_import_system_collations()``` UDF that will import collations from all system locales installed on the system. This function is used in initdb to import the collations on the system, or can be called by a system administrator to import newly added collations any time thereafter.
Some adaptations were made to MPP during the GreenPlum back port this UDF in https://github.com/greenplum-db/gpdb/pull/5016.
In order for collations to work correctly, we need to be sure that every collation that is created on the QD is also installed on the QEs, and that the OID matches in every database.  In upstream, collations are created during initdb, but this won't work for GPDB. Because while initdb is running there is no way to be sure that every segment has the same locales …

remove gpdb_12_merge_fixme in pg_import_system_collations

---

src/bin/psql/command.c

In 6X_STABLE, `\dP` means "list parent-only tables", no children, but in PG_12_STABLE, `\dP[tin+]` means "list [only table/index] partitioned relations", they conflict.
This needs to be consistent with PG's behavior.

Resolve GPDB_12_MERGE_FIXME in psql/command.c

---

src/backend/catalog/cdb_schema.sql
src/backend/catalog/system_views.sql
src/test/regress/expected/db_size_functions.out
src/test/regress/sql/db_size_functions.sql

There are some gp functions (e.g. `gp_tablespace_location`) in src/backend/catalog/system_views.sql. They are designed to run on master and dispatch internal logic to segment.
But in some situations, they are executed on the entrydb QE, it will cause error result.
For example:
the definition of `gp_tablespace_location`
```
-- pg_tablespace_location wrapper functions to see Greenplum cluster-wide tablespace locations
CREATE FUNCTION gp_tablespace_segment_location (IN tblspc_oid oid, OUT gp_segment_id int, OUT tblspc_loc text)
AS 'SELECT pg_catalog.gp_execution_segment() as gp_segment_id, * FROM pg_catalog.pg_tablespace_location($1)'
LANGUAGE SQL EXECUTE ON ALL SEGMENTS;
CREATE FUNCTION gp_tablespace_location (IN tblspc_oid oid, OUT gp_segment_id int, OUT tblspc_loc text)
RETURNS SETOF …
```

Some gp wrapper function should not execute on entrydb QE

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-limitations.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

docs for https://github.com/greenplum-db/gpdb/pull/12992 - gporca supports ordered aggregates and multi-argument distinct aggregates.  in this PR:
- docs for new server configuration parameter optimizer_enable_orderedagg
- updates to the "gporca does not support" topic
(there will be a separate docs PR for master.)

docs - new optimizer_enable_orderedagg guc

---

gpdb-doc/dita/ref_guide/modules/gp_array_agg.xml
gpdb-doc/dita/ref_guide/modules/intro.xml
gpdb-doc/dita/ref_guide/modules/modules.ditamap
gpdb-doc/markdown/install_guide/install_modules.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13168, which introduces a new gp_array_agg aggregate function in a module of the same name.  in this PR:
- doc the new gp_array_agg module that includes the new aggregate function.
- some misc nav updates.
(there will be a separate PR for master, as the new aggregate function is built-in there, not provided in a module.)
doc review site link (behind vpn):  https://docs-lisa-gp_array_agg.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/modules/gp_array_agg.html

docs - add content for new 6x gp_array_agg module

---

gpdb-doc/dita/ref_guide/modules/pageinspect.xml

docs for https://github.com/greenplum-db/gpdb/pull/12944 and https://github.com/greenplum-db/gpdb/pull/12994.  in this PR:
- update the pageinpect module docs to include new bitmap functions
- rearranged the content a bit to consolidate the (now more) greenplum-specific info
- this will be backported to 6X_STABLE.
doc review site link (behind vpn):  https://docs-lisa-pageinspect.sc2-04-pcf1-apps.oc.vmware.com/7-0/ref_guide/modules/pageinspect.html

docs - update pageinspect module docs for new bitmap support

---

gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py

While testing the recover_mirrors/add_mirrors function, we assert that
we make the right call to the gpsegrecovery wrapper. This unit test
failed on the 6X pipeline because for some reason gplog's verbose
setting got enabled. Because of this, the call to gpsegreovery.py
included a '-v' flag. This commit explicitly mocks the function
`logging_is_verbose` and sets the return value to False.

Fix flaky unit test in buildMirrorSegments

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

Added new section under gpstate -e, which displays progress of segments in recovery
-Edited buildMirrorSegments to create new file (recovery_progress.file) and updates
the current recovery progress, deletes the file after recoveries are completed.
-Added new section under gpstate -e to display progress of segments in recovery
-Added _parse_recovery_progress_data(), which will look for the recovery_progress.file
and populate the required fields
-Added behave and unit tests for above scenario
```
Sample output:
-----------------------------------------------------
Segments in recovery
Segment                     Port   Recovery type   Completed bytes (kB)   Total bytes (kB)   Percentage completed
hmaddileti-a01.vmware.com   7002   full            1164848                1371715 …
```

gpstate -e : Display ongoing recovery progress

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
gpMgmt/test/behave_utils/utils.py

Added new section under gpstate -e, which displays progress of mirrorss
in recovery
-Edited buildMirrorSegments to create new file (recovery_progress.file)
and updates the current recovery progress, deletes the file after
recoveries are completed.
-Added new section under gpstate -e to display progress of mirrors in
recovery
-Added _parse_recovery_progress_data(), which will look for the
recovery_progress.file and populate the required fields -Added behave
and unit tests for above scenario
Sample output:
-----------------------------------------------------
Segments in recovery
Segment                     Port   Recovery type   Completed bytes (kB)   Total bytes (kB)   Percentage completed
hmaddileti-a01.vmware.com   7002   full            1164848                1371715            84% …

[6X] gpstate -e : Display ongoing recovery progress

---

src/bin/pg_upgrade/check.c

A materialized view of append only mode must have invalid relfrozenxid (0).
However, some views might have valid relfrozenxid due to a known code issue.
We need to check the problematical view before upgrading.
The problem can be fixed by issuing "REFRESH MATERIALIZED VIEW <viewname>"
with latest code.
See the PR for details:
https://github.com/greenplum-db/gpdb/pull/11662/
About to test:
I didn't add unit test because it's difficult to do. The scenario is hit only when we apply pg_upgrade of GPDB7 to a GPDB6 instance, i.e. we cannot simply test with GPDB6 or GPDB7, and the scenario is not covered by existing test framework. Instead, I did some tests manually:
Create table/view in a GPDB6 instance:
```
create table foo(a int);
CREATE MATERIALIZED VIEW m_view WITH ("appendonly"='true', …
```

Add check for appendonly materialized view to pg_upgrade

---

src/backend/commands/createas.c
src/backend/tcop/postgres.c
src/test/regress/expected/guc_gp.out
src/test/regress/sql/guc_gp.sql

GUC values of PGC_STRING type should be quoted or parsing
at GUC value rollback will fail otherwise.
As failed SET command leads to transaction abort that leads to
backend exit that triggers RemoveTempRelationsCallback to remove
temp relations, the new tests verify that after GUC PGC_STRING value
rollback no temp relation is removed.
Test for empty search_path GUC value from 620bdbda7ac40016f9bbd49941f70c4247ca2637
replaced with new one that required no Fault Injector and keeps the
source code clean.

Add tests for GUC of PGC_STRING type value rollback

---

src/backend/gporca/libgpopt/src/base/CDrvdPropScalar.cpp
src/backend/gporca/libgpopt/src/operators/CExpression.cpp

During cafe3a6ce refactoring we introduced on demand property
derivation, but accidentaly broke the printing of expression properties.
This commit does the following
1) Print Expression Properties (DrvdPropScalar / DrvdPropRelational)
only when they have been derived completely.
2) Print the actual values of instead of addresses.
```sql
set client_min_messages = log;
set optimizer_print_expression_properties=on;
set optimizer_print_plan=on;
explain select 1;
```
Before this commit:
```
LOG:  statement: explain select 1;
LOG:  2022-03-12 18:29:33:987979 PST,THD000,ERROR,"CDrvdPropScalar.cpp:151: Failed assertion: IsComplete()
Stack trace:
1    0x000000010c0ee480 gpos::CException::Raise + 432
2    0x000000010c38782d gpopt::CDrvdPropScalar::GetDefinedColumns + 125
3    0x000000010c387dc9 …
```

Fix Printing Expression Properties

---

src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql

The fts_unblock_primary isolation2 test would sometimes fail stating
that the GUC value was not updated after running `gpstop -u` to reload
from the updated postgresql.conf file. The cause of the flakiness was
due to the assumption that the SHOW command would immediately be
usable after `gpstop -u` returned. The `gpstop -u` command merely
sends SIGHUP signals to all the segments (e.g. pg_ctl reload on all
the segments) and does not do any validations. In this test, the SHOW
command was being run before the SIGHUP signal was handled which
resulted in the incorrect value being displayed. To fix this test
flake, we simply need to close our SQL connection after sending the
SIGHUP signals and open a new connection to run the SHOW command. This
solution works because the new connection will …

[6X backport] Fix flaky fts_unblock_primary isolation2 test

---

src/backend/cdb/cdbdtxrecovery.c

Need to call cdbdisp_clearCdbPgResults() to free up cdb_pgresults
returned by CdbDispatchCommand(), but PR #10393 forgot.
Speed up reproduction:
```
psql# create extension if not exists gp_inject_fault;
psql# select gp_inject_fault_infinite('finish_prepared_start_of_function', 'suspend', dbid)
from gp_segment_configuration where content != -1 and role = 'p';
shell# gpconfig -c gp_dtx_recovery_interval -v 5
shell# for ((i=0;i<50;i++)); do psql -c "create table test_$(date +%H%M%S)(id int)" & sleep 2; done
```

Fix memory leak in dtx recovery process

---

src/backend/access/transam/twophase.c
src/test/recovery/t/023_pitr_prepared_xact.pl

As per the main commit message:
```
Fix timeline assignment in checkpoints with 2PC transactions
Any transactions found as still prepared by a checkpoint have their
state data read from the WAL records generated by PREPARE TRANSACTION
before being moved into their new location within pg_twophase/.  While
reading such records, the WAL reader uses the callback
read_local_xlog_page() to read a page, that is shared across various
parts of the system.  This callback, since 1148e22a, has introduced an
update of ThisTimeLineID when reading a record while in recovery, which
is potentially helpful in the context of cascading WAL senders.
This update of ThisTimeLineID interacts badly with the checkpointer if a
promotion happens while some 2PC data is read from its record, as, by
changing …
```

[PG12_STABLE Backport] Fix timeline assignment in checkpoints with 2PC transactions

---

gpdb-doc/markdown/admin_guide/external/g-devel-fdw.html.md
gpdb-doc/markdown/admin_guide/external/g-foreign.html.md

2 PRs in master were made to admin_guide XML content in the window after the adminguide was converted to markdown. This PR brings those changes into the markdown source.

Docs update admin md

---

src/test/isolation2/expected/fts_errors.out
src/test/isolation2/expected/fts_errors_1.out
src/test/isolation2/sql/fts_errors.sql

This test is flaky in terms of where error will be thrown during a `FETCH` cursor transaction when some original primary segments are down. The test expects no error during `FETCH` itself but an error in the `END` statement, since the table is small (in fact, 0 row) and during `FETCH` QD should have enough data already buffered at sockets for it to read and doesn't need to reach out to QEs. However, sometimes when the interconnect is proxy, this is not true and when QD fails to read data from socket it reaches out to QEs and throw an error.
For example test diff we saw:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/expected/fts_errors_1.out	2022-03-09 10:00:32.786358101 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/results/fts_errors.out	2022-03-09 …
```

Fix flaky test fts_errors with nondeterminsitc error in FETCH

---

gpdb-doc/dita/ref_guide/modules/greenplum_fdw.xml
gpdb-doc/dita/ref_guide/modules/intro.xml
gpdb-doc/dita/ref_guide/modules/modules.ditamap
gpdb-doc/markdown/install_guide/install_modules.html.md

add some basic module docs for greenplum_fdw.  this is based on postgres_fdw.  the org of this page differs from the org of postgres_fdw docs.  in some cases i xref'd to the postgres docs.
doc review site link (behind vpn):  https://docs-lisa-gpfdw.sc2-04-pcf1-apps.oc.vmware.com/6-19/ref_guide/modules/greenplum_fdw.html

doc - add content for new greenplum_fdw module

---

src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h
src/backend/gporca/libgpopt/src/xforms/CXform.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/bfv_joins.out
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/sql/bfv_joins.sql

Use optimizer_enable_nljoin to disable all xforms that produce nestloop
join alternatives.

Add ORCA GUC optimizer_enable_nljoin to disable NLJ

---

gpdb-doc/dita/ref_guide/modules/gp_sparse_vector.xml

https://github.com/greenplum-db/gpdb/pull/13156 is a gp_sparse_vector bug fix.  to get the fix, the user must upgrade the gp_sparse_vector module in any databases where they are currently using it.  there is an existing upgrade topic because a previous fix moved the functions/objects to a new schema.
question:  please verify the upgrade commmand.  the version of the extension did not change with this fix, will the ALTER EXTENSION ... UPDATE actually update the same version of an extension?  or does this need a drop/create extension (but doesn't that remove dependent objects)?

docs - rework gp_sparse_vector upgrade topic a bit

---

src/backend/gporca/libgpopt/src/operators/CScalarSortGroupClause.cpp
src/test/regress/expected/qp_misc.out
src/test/regress/expected/qp_misc_optimizer.out
src/test/regress/sql/qp_misc.sql

ICW caught cases where qp_misc SIGSEGV'd.  Issue is that
CScalarSortGroupClause::Matches() incorrectly assumed that it is only
used to check for matches against other CScalarSortGroupClause objects.
When that was not the case, dynamic_cast returns nullptr and leads to
SIGSEGV.

Fix flaky qp_misc test case

---

src/backend/gporca/libgpopt/src/operators/CScalarSortGroupClause.cpp
src/test/regress/expected/qp_misc_optimizer.out
src/test/regress/sql/qp_misc.sql

ICW caught cases where qp_misc SIGSEGV'd.  Issue is that
CScalarSortGroupClause::Matches() incorrectly assumed that it is only
used to check for matches against other CScalarSortGroupClause objects.
When that was not the case, dynamic_cast returns nullptr and leads to
SIGSEGV.
Also set optimizer trace fallback in qp_misc test so that we can catch
unexpected fallbacks when assert are enabled.
(cherry picked from commit cd84fb806f24cecc584040a6420545600b67ef9d)
cherry picked from PR https://github.com/greenplum-db/gpdb/pull/13261

Fix flaky qp_misc test case (#13261)

---

src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql

Pipeline shows the case resgroup_seg_down_2pc flaky with the
following diffs:
-- reset the injected fault on primary segment
2:select gp_inject_fault('fts_conn_startup_packet', 'reset', dbid) from gp_segment_configuration where content=0;
- gp_inject_fault
------------------
- Success:
- Success:
-(2 rows)
+ERROR:  connection to dbid 4 sdw1:21000 failed (gp_inject_fault.c:107)
1<:  <... completed>
ALTER
-- make sure "alter resource group" has taken effect.
Actually we do not need to reset the fault inject
fts_conn_startup_packet for this case because the segment we set it
will be marked down and then recoverseg with a new clean shared
memory. Remove the statement that reset it to make this test case stable.
------
Master pipeline flaky: …

Make test resgroup_seg_down_2pc stable.

---

src/backend/executor/nodeNestloop.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

Greenplum will pull up not-in sublink to a specific join LASJ,
this kind of join's joinqual might contain a NULL const here,
for such case we do not need to split it. A case that can
reach here is:
create table t1(a int not null, b int not null);
create table t2(a int not null, b int not null);
explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
The above SQL in Greenplum will be turned in a join whose qual contains
a bool expr (NULL = t2.a) and (t1.b = t2.b), this piece of expr will be
evaluated to (t1.b = t2.b) and NULL by the following code path:
subquery_planner
-> preprocess_qual_conditions(root, (Node *) parse->jointree)
-> preprocess_expression
-> eval_const_expressions
-> eval_const_expressions_mutator
So in splitJoinQualExpr, we should expect a null const in …

Fix planner bug: correctly handling NULL when pulling-up NOT-IN.

---

src/test/isolation2/expected/resgroup/resgroup_seg_down_2pc.out
src/test/isolation2/sql/resgroup/resgroup_seg_down_2pc.sql

Pipeline shows the case resgroup_seg_down_2pc flaky with the
following diffs:
-- reset the injected fault on primary segment
2:select gp_inject_fault('fts_conn_startup_packet', 'reset', dbid) from gp_segment_configuration where content=0;
- gp_inject_fault
------------------
- Success:
- Success:
-(2 rows)
+ERROR:  connection to dbid 4 sdw1:21000 failed (gp_inject_fault.c:107)
1<:  <... completed>
ALTER
-- make sure "alter resource group" has taken effect.
Actually we do not need to reset the fault inject
fts_conn_startup_packet for this case because the segment we set it
will be marked down and then recoverseg with a new clean shared
memory. Remove the statement that reset it to make this test case stable.
(cherry picked from commit 1d2697f765505281f106f827ea2f1d95011db3a6)

(6x backport) Make test resgroup_seg_down_2pc stable.

---

src/backend/access/common/reloptions_gp.c
src/backend/commands/tablecmds.c
src/include/access/reloptions.h
src/test/regress/expected/expand_table_ao.out
src/test/regress/sql/expand_table_ao.sql

When a table is an AO table and has an index, `ALTER TABLE EXPAND TABLE` will not be done directly 
using CTAS, but create table + insert data. However, when creating a table, the original storage option 
of the AO table is ignored, and the default parameters of the current environment are used, which will 
lead to inconsistency between the table before and after expansion.
The pr fixes issue #13245, reconstructs the storage option of the original table, and passes it down.

add original storage options to AO table with index when expanding

---

src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql

One of the flakiness in the test pg_rewind_fail_missing_xlog we saw is:
```
--- expected/pg_rewind_fail_missing_xlog.out
+++ results/pg_rewind_fail_missing_xlog.out
@@ -73,16 +105,32 @@
1: SELECT role, preferred_role from gp_segment_configuration where content = 0;
role | preferred_role
------+----------------
- m    | p
- p    | m
+ m    | m
+ p    | p
(2 rows)
-- Run two more checkpoints. Previously this causes the checkpoint.redo wal
-- file before the oldest replication slot LSN is recycled/removed.
0M: CHECKPOINT;
-CHECKPOINT
```
This is because FTS couldn't promote the mirror after an attempted failover. The root cause of this is that the mirror was
not-in-sync before the primary is scheduled to be down. In that case the FTS will repeatedly see the primary as down (case …

Fix a flakiness in pg_rewind_fail_missing_xlog where FTS could not promote not-in-sync mirror

---

gpdb-doc/dita/ref_guide/modules/gp_parallel_retrieve_cursor.xml
gpdb-doc/dita/ref_guide/modules/greenplum_fdw.xml

in this PR:
- fix an xref title in greenplum_fdw
- psql command in p_parallel_retrieve_cursor docs should use -U to specify user

docs - a few misc edits to recently-added module docs

---

src/backend/executor/nodeShareInputScan.c
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/optimizer/plan/planshare.c
src/include/nodes/plannodes.h

When dealing with queries which have CTE and result set being used
more than once, ORCA produces a plan with Sequence Node and
ShareInputScan Node. Here is an example:
explain (costs off) with tmp_t as (select id from test) select a.id from tmp_t a join tmp_t b on a.id = b.id;
```
QUERY PLAN
------------------------------------------------------------
->  Sequence
->  Shared Scan (share slice:id 1:0)
->  Seq Scan on test
->  Hash Join
Hash Cond: (share0_ref3.id = share0_ref2.id)
->  Shared Scan (share slice:id 1:0)
->  Hash
->  Shared Scan (share slice:id 1:0)
Optimizer: Pivotal Optimizer (GPORCA)
(10 rows)
```
This plan has three ShareInputScan nodes: one producer and two
consumers, all of them read from the tuplestore and return tuples to
upper …

[6X backport] ORCA: avoid returning output of a CTE producer

---

src/backend/executor/spi.c
src/test/regress/expected/plpgsql_cache.out
src/test/regress/sql/plpgsql_cache.sql

The problem was detected when we found out that partition elimination didn't work inside plpgsql functions. The root of the problem was in `SPI exec_run_select()` call (used by plpgsql to evaluate SQL queries). It reevaluated the plan for prepared queries (that is how plpqsql works with parameters) but didn't take parameters into account - only cached plan. GPDB `6X_STABLE` uses both cached plan and parameter to reevaluated the plan. This commit synchronizes behavior with `6X_STABLE`.

Revalidate plan in SPI taking params into account

---

src/backend/optimizer/plan/setrefs.c
src/test/regress/expected/update_gp.out
src/test/regress/expected/update_gp_optimizer.out
src/test/regress/sql/update_gp.sql

Greenplum planner will pull up NOT-IN sublink to a join type called
left-anti-semi-join (LASJ_NOTIN), the executor logic of it is similar
to anti-join or semi-join. So during set_join_references's
fix_join_expr, for LASJ_NOTIN,  we should use the same logic as
anti-join. This commit fixes Issue:
https://github.com/greenplum-db/gpdb/issues/13265.
A case that leads to wrong behavior without this commit is shown
below:
create table t1(a int, b int, c int, d int);
create table t2(a int, b int, c int, d int);
insert into t1 values (1, null, 1, 1);
insert into t2 values (2, null, 2, 2);
explain (verbose, costs off)
update t1 set b = 2 where
(c, d) not in (select c, d from t2 where a = 2);
Update on public.t1
->  Explicit Redistribute Motion 3:3  (slice2; segments: 3)
Output: t1.a, (2), t1.c, …

(6x)Do not match non vars in inner plan's target for LASJ_NOTIN.

---

src/backend/commands/portalcmds.c
src/test/isolation2/.gitignore
src/test/isolation2/expected/parallel_retrieve_cursor/set.out
src/test/isolation2/sql/parallel_retrieve_cursor/set.sql

The PARALLEL RETRIEVE CURSOR feature depends on the extension
gp_parallel_retrieve_cursor on Greenplum 6.X, error out in the DECLARE
statement to save resources and tell the users if the extension is not
installed.
DECLARE is the beginning of everything, it's good enough to do this on
it only.

Error out in DECLARE if gp_parallel_retrieve_cursor is not installed

---

src/backend/cdb/cdbdtxrecovery.c

This patch backports change in PR #13252.
Since commit eea513bb913dcc638bfa7076dba806ce88ea85b2, 
the Dtx Recovery Process needs to gather prepared transactions
from all segments by dispatching a query. However, we forgot to free the memory
used by the results of dispatch, which can cause memory leak.
1. Create a large number of transactions and leave them prepared on segments but
not commit them so that pg_prepared_xacts on the segments is not empty.
2. Check the memory usage of the Dtx Recovery Process. It will keep increasing
since the results of querying pg_prepared_xacts is never freed.
(cherry picked from commit d7ffe63029c4135d977a37d4561904817ce6c4a3)
Co-authored-by: @dh-cloud <60729713+dh-cloud@users.noreply.github.com>

[6X] Fix memory leak in dtx recovery process

---

gpMgmt/sbin/gpgetstatususingtransition.py
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

pg_isready was generating fatal message on primary segments to use utiltily mode for direct connections to primary segments. Included PGOPTIONS="-c gp_role=utility" with pg_isready command to avoid the fatal message.
Added behave test case for above scenario.

[6X] gpstate -e: Changes to avoid fatal message on primary segments

---

src/bin/pg_upgrade/README.gpdb
src/bin/pg_upgrade/check.c
src/bin/pg_upgrade/exec.c
src/bin/pg_upgrade/function.c
src/bin/pg_upgrade/greenplum/check_gp.c
src/bin/pg_upgrade/greenplum/option_gp.c
src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
src/bin/pg_upgrade/option.c
src/bin/pg_upgrade/pg_upgrade.c
src/bin/pg_upgrade/pg_upgrade.h
src/bin/pg_upgrade/tablespace.c
src/bin/pg_upgrade/util.c

Adds `--skip-target-check` and `--continue-check-on-fatal` features for check mode:
The  flag lets us traverse through the pg_upgrade --check list without
exiting the first error encountered. It allows the user to get a report of 
the entire list of non-upgradable objects in their cluster at one go.
Note: We canot ignore certain checks despite the flag being supplied -
they may be critical to the check process . One such example is
heck_proper_datallowconn(), which ensures that we can connect to user
databases to perform the checks themselves.  Specific checks are
multi-step, like the check to ensure that only the install user is the
sole user in the target database. If we get fatal: "could not determine
the number of users", we can't proceed with the check. Thus, in these
cases, the flag …

pg_upgrade check feature

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
src/test/regress/expected/qp_orca_fallback.out
src/test/regress/expected/qp_orca_fallback_optimizer.out
src/test/regress/sql/qp_orca_fallback.sql

Orca doesn't support composite types (also called "whole-row
variables"). While we have a fallback when we project
composite type, we missed the case for functions returning
composite types, which led to wrong results.
This fallback was already added to the master branch during the
PG12 merge. We are also looking at adding support for composite 
types to Orca, but let's fix the wrong results here first.

Fallback to planner for functions returning composite types

---

gpAux/platform/gpnetbench/gpnetbenchServer.c
src/backend/cdb/cdblegacyhash.c
src/backend/cdb/motion/ic_tcp.c
src/bin/initdb/initdb.c
src/bin/psql/describe.c

These issues are reported by Coverity: [detail link](https://pivotal.polaris.synopsys.com/projects/34158812-801e-47d3-8aad-492774ea4d91/branches/12d9ee7f-fb2e-4153-be92-bc147e3a5603/issues?filter=issue%5Bstatus%5D%5B%24eq%5D%3Dopened%26issue%5Btaxonomy%5D%5Bid%5D%5B4bae258d-865d-4a06-9ff8-a7e141cabb2d%5D%5Btaxon%5D%5B%24eq%5D%3Dhigh%26issue%5Btriage-status%5D%5B%24eq%5D%3Dto-be-fixed)
Actually, more issues are found, but some of them are the same as upstream code 
and not a very big deal (e.g. in utility, like pg_dump), so ignore them.
Just fix issues which gpdb introduced in this PR.

6X: Fix memory leak issues which reported by Coverity

---

src/backend/catalog/namespace.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/tcop/postgres.c
src/include/catalog/namespace.h
src/test/regress/expected/bfv_temp.out
src/test/regress/expected/guc.out
src/test/regress/sql/bfv_temp.sql
src/test/regress/sql/guc.sql

Dispatch temporary tablespace id to all Gangs.
If a query has multiple Gangs, the secondary Gang cannot get correct temporary tablespace ID.
Consider this SQL:
```
create table tn_a(id int) distributed by (id); insert into tn_a values (1), (2);
create temp table tn_a_tmp(a int) distributed replicated; insert into tn_a_tmp values(1);
create or replace function fun(sql text, a oid) returns bigint AS '
return plpy.execute(sql).nrows() + a
' language plpython3u stable;
create table tn_a_new as with c as (
select fun('select * from tn_a_tmp', s.id) from tn_a s
) select 1 from c;
```
The key to reproducing this bug is forcing the secondary Gang to scan on temp
table which normally won't happen. to reach that, the test case uses SPI to
scan on replicated table.
In this scenario. the first …

Dispatch temporary tablespace id to all Gangs.

---

src/backend/parser/parse_coerce.c
src/test/regress/expected/gp_dump_query_oids.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gp_dump_query_oids.sql

This PR is trying to fix issue #13195.
The RCA is that PostgreSQL does not support type conversion between `unknown` and `text`, 
but Greenplum hacks this behavior so that the below SQL can be executed on 6X:
```
CREATE TABLE t (pid varchar(1), dummy varchar(1)) DISTRIBUTED BY (pid);
CREATE VIEW s AS SELECT 'D' as dummy;
select * from t join s on t.dummy = s.dummy;	// not allowed in PostgreSQL 9
```
In the process of hack, the principle is multi-level function nesting, first convert `unknown` into 
`cstring` through `unknownout` function, and then use `textin` function to convert `cstring` into 
`text`. Then in the nested process, the constructed function parameters are:
```
args = list_make3(fe,
makeConst(OIDOID, -1, InvalidOid, sizeof(Oid),
ObjectIdGetDatum(intypioparam),
false, true), …
```

[6X Only] fix cache look up failed for relation 25 in pg_catalog.gp_dump_query_oids()

---

src/backend/parser/parse_cte.c
src/test/regress/expected/with.out
src/test/regress/expected/with_clause.out
src/test/regress/expected/with_clause_optimizer.out
src/test/regress/sql/with_clause.sql

Greenplum does not support window agg in the target list of recursive
part of recursive CTE. Current implementation of recursive queries is
based on Postgres' Worktable Scan and RecursiveUnion, this forces
the two nodes must be in the same slice, means no motion node is
allowed between them. The locus of worktable scan is determined by the
non-recurisve part of path thus it is hard to avoid motion over
worktable scan when there are window aggs. This should be the reason
why Greenplum does not support this feature.
However, previous code only checks the direct raw expression in parse
tree's targetlist, this is not enough, since it might be a compound
expression that involving window aggs, like a type cast expression. We
should use raw_expression_tree_walker to search window functions.
This …

Fix banning window agg in recursive queries.

---

src/test/isolation2/sql_isolation_testcase.py

Probably because of the heavy CI load, we observed several timeouts,
increase the timeout value to work around it.

Increase the timeout of isolation2 GlobalShellExecutor

---

src/backend/parser/parse_cte.c
src/test/regress/expected/with.out
src/test/regress/expected/with_clause.out
src/test/regress/expected/with_clause_optimizer.out
src/test/regress/sql/with_clause.sql

Greenplum does not support window agg in the target list of recursive
part of recursive CTE. Current implementation of recursive queries is
based on Postgres' Worktable Scan and RecursiveUnion, this forces
the two nodes must be in the same slice, means no motion node is
allowed between them. The locus of worktable scan is determined by the
non-recurisve part of path thus it is hard to avoid motion over
worktable scan when there are window aggs. This should be the reason
why Greenplum does not support this feature.
However, previous code only checks the direct raw expression in parse
tree's targetlist, this is not enough, since it might be a compound
expression that involving window aggs, like a type cast expression. We
should use raw_expression_tree_walker to search window functions.
This …

(6x backport) Fix banning window agg in recursive queries.

---

src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/include/gpopt/translate/CTranslatorDXLToScalar.h
src/test/regress/expected/correlated_subquery.out
src/test/regress/sql/correlated_subquery.sql

Commit 6f175df1 added support for subplan test expression containing
scalar ident on left side. But in order to properly support that
scenario we needed to account for cast and coerceio as well.

Fix testexpr translation of outer expr

---

src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
src/test/regress/expected/qp_misc.out
src/test/regress/expected/qp_misc_optimizer.out
src/test/regress/sql/qp_misc.sql

When there is a param, `ExprCollation` relies on paramcolid to figure out the
resultcolid. We weren't setting it while creating a param.
This commit fixes it,

Fix paramcolid for param in ORCA translator

---

src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/include/gpopt/translate/CTranslatorDXLToScalar.h
src/test/regress/expected/correlated_subquery.out
src/test/regress/sql/correlated_subquery.sql

Commit 6f175df1 added support for subplan test expression containing
scalar ident on left side. But in order to properly support that
scenario we needed to account for cast and coerceio as well.
(cherry picked from commit fd9e35bbeab3c7e0691be8336abda5d89b8f9671)

Fix testexpr translation of outer expr (#13296)

---

src/backend/commands/tablecmds.c
src/test/isolation/expected/partition-drop-index-locking.out
src/test/isolation/isolation_schedule
src/test/isolation/specs/partition-drop-index-locking.spec

DROP INDEX needs to lock the index's table before the index itself,
else it will deadlock against ordinary queries that acquire the
relation locks in that order.  This is correctly mechanized for
plain indexes by RangeVarCallbackForDropRelation; but in the case of
a partitioned index, we neglected to lock the child tables in advance
of locking the child indexes.  We can fix that by traversing the
inheritance tree and acquiring the needed locks in RemoveRelations,
after we have acquired our locks on the parent partitioned table and
index.
While at it, do some refactoring to eliminate confusion between
the actual and expected relkind in RangeVarCallbackForDropRelation.
We can save a couple of syscache lookups too, by having that function
pass back info that RemoveRelations will need. …

Fix risk of deadlock failure while dropping a partitioned index.

---

contrib/pg_upgrade/README.gpdb
contrib/pg_upgrade/check.c
contrib/pg_upgrade/exec.c
contrib/pg_upgrade/function.c
contrib/pg_upgrade/greenplum/check_gp.c
contrib/pg_upgrade/greenplum/option_gp.c
contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h
contrib/pg_upgrade/greenplum/version_gp.c
contrib/pg_upgrade/option.c
contrib/pg_upgrade/pg_upgrade.c
contrib/pg_upgrade/pg_upgrade.h
contrib/pg_upgrade/tablespace.c
contrib/pg_upgrade/util.c
contrib/pg_upgrade/version_old_8_3.c

Adds `--skip-target-check` and `--continue-check-on-fatal` features for check mode:
The  flag lets us traverse through the pg_upgrade --check list without
exiting the first error encountered. It allows the user to get a report of 
the entire list of non-upgradable objects in their cluster at one go.
Note: We canot ignore certain checks despite the flag being supplied -
they may be critical to the check process . One such example is
heck_proper_datallowconn(), which ensures that we can connect to user
databases to perform the checks themselves.  Specific checks are
multi-step, like the check to ensure that only the install user is the
sole user in the target database. If we get fatal: "could not determine
the number of users", we can't proceed with the check. Thus, in these
cases, the flag …

[6X] pg_upgrade check features

---

src/backend/gpopt/translate/CMappingColIdVarPlStmt.cpp
src/test/regress/expected/qp_misc.out
src/test/regress/expected/qp_misc_optimizer.out
src/test/regress/sql/qp_misc.sql

When there is a param, `ExprCollation` relies on paramcollid to figure out the
resultcollid. We weren't setting it while creating a param.
This commit fixes it.
Co-authored-by: Sambitesh Dash <sdash@pivotal.io>
Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@vmware.com>
(cherry picked from commit d03632b6c0a389944ca50ddc788b1d5fbc2a4308)

Fix paramcollid for param in ORCA translator (#13302)

---

src/backend/optimizer/plan/setrefs.c
src/test/regress/expected/update_gp.out
src/test/regress/expected/update_gp_optimizer.out
src/test/regress/sql/update_gp.sql

This commit is cherry-picked from 6X to fix issue
https://github.com/greenplum-db/gpdb/issues/13265.
Master branch's code also has the same issue, but
due to other parts of code refactor (like removing
disuse_physical_tlist), it is hard to find a bad
case for master branch. But I still keep the test
in this commit since more tests do no harm.
(cherry picked from commit f9597375fef8f37d07b283e99b6a0b8f3a6b2796)

(pre-port) Do not match non vars in inner plan's target for LASJ_NOTIN.

---

src/backend/access/common/reloptions_gp.c
src/backend/commands/tablecmds.c
src/include/access/reloptions.h
src/test/regress/expected/expand_table_ao.out
src/test/regress/sql/expand_table_ao.sql

When a table is an AO table and has an index, ALTER TABLE EXPAND TABLE will not be done directly
using CTAS, but create table + insert data. However, when creating a table, the original storage option
of the AO table is ignored, and the default parameters of the current environment are used, which will
lead to inconsistency between the table before and after expansion.
The pr fixes issue https://github.com/greenplum-db/gpdb/issues/13245, reconstructs the storage option of the original table, and passes it down.
This is the backport of #13246.

[6X] add original storage options to AO table with index when expanding

---

gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpconfigurenewsegment
gpMgmt/bin/lib/gpcreateseg.sh
gpMgmt/sbin/gpsegrecovery.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature

Updated gpcreateseg.sh to update the port after the copying data dir tomirror. pg_basebackup copies primary data to mirror.
Updated gpconfigurenewsegment to update the port on newly added mirrorsegment.
Updated gprecoverseg to update the port number after full recovery.
Added test case to validate mirror port in initstandby workflow.
Added test case to validate mirror port in gpexpand/gpaddmirror workflow.
Updated gprecoverseg unit test for port number update.

conf on mirror seg doesn't get updated with mirror port number

---

src/test/regress/expected/plpgsql.out
src/test/regress/expected/plpgsql_optimizer.out
src/test/regress/sql/plpgsql.sql

Commit 2ddd30e336 exposed an ORCA issue with following diff in test
output:
select trap_matching_test(1);
- NOTICE:  caught numeric_value_out_of_range or cardinality_violation
-  trap_matching_test
- --------------------
-                  -2
- (1 row)
-
+ ERROR:  One or more assertions failed
+ DETAIL:  Expected no more than one row to be returned by expression
+ CONTEXT:  SQL statement "select unique1 from tenk1 where unique2 = (select unique2 from tenk1 b where ten =  $1 )"
+ PL/pgSQL function "trap_matching_test" line 8 at SQL statement
Previously ORCA would fall back because it doesn't support SIRV
functions. It used to be that before commit 2ddd30e336 we would reuse
the cached plan. Now, we may build a new plan because of existence of
boundParams. This gives ORCA a chance to plan …

Fix plpgsql testcase for ORCA

---

src/test/regress/expected/olap_plans.out
src/test/regress/expected/olap_plans_optimizer.out
src/test/regress/sql/olap_plans.sql

Now we do generate a two stage hash agg plan due to commit 9a790f8a4a.
Just remove the FIXME and update the test case.

Remove FIXME in test olap_plan.

---

src/backend/executor/nodeNestloop.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

Greenplum will pull up not-in sublink to a specific join LASJ,
this kind of join's joinqual might contain a NULL const here,
for such case we do not need to split it. A case that can
reach here is:
create table t1(a int not null, b int not null);
create table t2(a int not null, b int not null);
explain  select 1 from t1 where (NULL, b) not in (select a, b from t2);
The above SQL in Greenplum will be turned in a join whose qual contains
a bool expr (NULL = t2.a) and (t1.b = t2.b), this piece of expr will be
evaluated to (t1.b = t2.b) and NULL by the following code path:
subquery_planner
-> preprocess_qual_conditions(root, (Node *) parse->jointree)
-> preprocess_expression
-> eval_const_expressions
-> eval_const_expressions_mutator
So in splitJoinQualExpr, we should expect a null const in …

(6x) Fix planner bug: correctly handling NULL when pulling-up NOT-IN.

---

gpcontrib/gpcloud/regress/input/3_01_create_wet.source
gpcontrib/gpcloud/regress/output/3_01_create_wet.source
src/backend/access/external/fileam.c
src/backend/cdb/cdbcat.c

The writable s3 external table on master is supported in the [document](https://gpdb.docs.pivotal.io/6-20/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html)
But it will be dispatched to QE:
```
gpadmin=# explain insert into all_ext_tab01_wr values(1,1);
QUERY PLAN
----------------------------------------------------------------------------------------
Insert on all_ext_tab01_wr  (cost=0.00..0.01 rows=1 width=0)
->  Redistribute Motion 1:3  (slice1; segments: 1)  (cost=0.00..0.01 rows=1 width=0)
->  Result  (cost=0.00..0.01 rows=1 width=0)
(4 rows)
```
So, the insert will fail if s3 config file in only on master.
This PR fix the bug by:
1. set distribute policy as POLICYTYPE_ENTRY for writable external
talbe too.
2. do insert if the external table with …

[6X] Support writable s3 external table on master

---

src/backend/cdb/motion/ic_udpifc.c

As #12961 mentioned, `sendControlMessage()` is sent without retry, that is because in the normal cases, UDPIFC's retransmit mechanism will handle the normal data packet loss issue, and will retransmit UDP packets with another ACK sent, so there is no need to retry in `sendControlMessage()`, as [the comments](https://github.com/greenplum-db/gpdb/blob/f4ffe428f06616cf50904f5eb5f129f19ce6ba98/src/backend/cdb/motion/ic_udpifc.c#L1774) pointed out. But for some special cases, if the ACK is lost, it will not retransmit with UDP packets, e.g. in the EOS ACK message case.
In this PR, I move `sendto()` call with retry logic to a new method, so any relative call can reuse it enabling retries when interrupted.
This is a backport of PR #12983.
For black-box testing, the scenario is hard to reproduce …

(6x backport)  Make sendControlMessage to retry when interrupted

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_schema_and_mode.py
gpMgmt/bin/gpload_test/gpload2/data/external_file_546.txt
gpMgmt/bin/gpload_test/gpload2/query493.ans
gpMgmt/bin/gpload_test/gpload2/query497.ans
gpMgmt/bin/gpload_test/gpload2/query506.ans
gpMgmt/bin/gpload_test/gpload2/query545.ans
gpMgmt/bin/gpload_test/gpload2/query546.ans
gpMgmt/bin/gpload_test/gpload2/query76.ans

When gpload do update and merge, it will first insert data from the external table to a staging table. And then compare the data between the staging table and the target table to do merge or update.
We add a feature to better the staging table by using the distribution key of the target table as the distribution key for the staging table.
If target table is distributed randomly, we will use the match columns as the staging table's DK.

gpload add distribution key for staging table

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query25.ans
gpMgmt/bin/gpload_test/gpload2/query26.ans
gpMgmt/bin/gpload_test/gpload2/query27.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

gpload yaml should like:
'''
GPLOAD:
PRELOAD:
- STAGING_TABLE: '"Staging_table"'
'''
gpload should recognize capital letters table name in '" and "'

fix gpload yaml staging_table when it has capital letters

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_preload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_schema_and_mode.py
gpMgmt/bin/gpload_test/gpload2/__init__.py
gpMgmt/bin/gpload_test/gpload2/query27.ans
gpMgmt/bin/gpload_test/gpload2/query401.ans
gpMgmt/bin/gpload_test/gpload2/query405.ans
gpMgmt/bin/gpload_test/gpload2/query406.ans
gpMgmt/bin/gpload_test/gpload2/query433.ans
gpMgmt/bin/gpload_test/gpload2/query603.ans
gpMgmt/bin/gpload_test/gpload2/query604.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

1.  gpload should recognize capital letters table name in '" and "', gpload YAML file like:
```
GPLOAD:
PRELOAD:
- STAGING_TABLE: '"Staging_table"'
```
2. better gpload test frame. Make pytest print the diff file if the case fail

fix gpload staging_table when it has capital letters

---

src/backend/access/aocs/aocsam_handler.c
src/test/regress/input/aocs.source
src/test/regress/output/aocs.source

On first index creation (block directory is created) and only that time all columns are scanned. Later any index creation just scans needed columns.

Speed up AOCS index build by only scan needed columns.

---

src/backend/executor/nodeSubplan.c

Just remove duplicate code in `ExecSetParamPlan()`, it repeated with line 1158.

remove duplicate codes in ExecSetParamPlan

---

src/backend/cdb/cdbsubselect.c
src/backend/optimizer/prep/prepjointree.c

Commit fe44b1f7a use negate_clause instead of make_notclause,
this might lead to (NOT =) become <>, semantically they should
be the same. But in later convert_IN_to_antijoin, it does not
consider sublink expr is OpExpr thus fails a test case notin.
This commit fixes the failure case by considering OpExpr in
convert_IN_to_antijoin.
------
No test cases needed. This just fixes a test case faliure.

Fix test case notin.

---

src/backend/parser/analyze.c
src/backend/parser/parse_clause.c
src/backend/parser/parse_relation.c
src/backend/utils/cache/plancache.c
src/test/isolation2/expected/lockmodes.out
src/test/isolation2/expected/lockmodes_optimizer.out
src/test/isolation2/output/uao/parallel_delete.source
src/test/isolation2/output/uao/parallel_update.source
src/test/isolation2/sql/lockmodes.sql
src/test/regress/expected/ao_locks.out
src/test/regress/expected/partition_locking.out
src/test/regress/expected/partition_locking_optimizer.out

Since GPDB_12_MERGE, the appropriate lockmode of the relations in a
query has been decided and recorded into RTE.rellockmode field when
transforming parsetree to querytree. the cached plan can just reuse
those info.
No testcase is added, as this commit only clean commented-out code
and isolation2/lockmodes.sql has already covered the lockmode test

Clean the deprecated lockmode logic of AcquireExecutorLocks in plancache

---

src/backend/gpopt/gpopt.mk

Commit ac6ce1a5c4 accidentally introduced nullptr usage during backport
to 6X branch. In 6X compiler is C++98 and nullptr is C++11. Fix that and
add explicit -std=c++98 in gpopt.mk to catch better next time.

Revert C++11 nullptr usage

---

gpcontrib/gpcloud/regress/input/3_01_create_wet.source
gpcontrib/gpcloud/regress/output/3_01_create_wet.source

drop the s3 external table in test cases to make sure the final `DROP PROTOCOL IF EXISTS s3` operation success

drop s3 external table in test cases

---

src/backend/cdb/motion/ic_udpifc.c

As #12961 mentioned, `sendControlMessage()` is sent without retry, that is because in the normal cases, UDPIFC's retransmit mechanism will handle the normal data packet loss issue, and will retransmit UDP packets with another ACK sent, so there is no need to retry in `sendControlMessage()`, as [the comments](https://github.com/greenplum-db/gpdb/blob/f4ffe428f06616cf50904f5eb5f129f19ce6ba98/src/backend/cdb/motion/ic_udpifc.c#L1774) pointed out. But for some special cases, if the ACK is lost, it will not retransmit with UDP packets, e.g. in the EOS ACK message case.
In this PR, I move `sendto()` call with retry logic to a new method, so any relative call can reuse it enabling retries when interrupted.
For black-box testing, the scenario is hard to reproduce on local dev, and it occurs when …

Make sendControlMessage to retry when interrupted

---

gpcontrib/gp_exttable_fdw/extaccess.c

`on master` clause has been replaced by `on coordinator` on gpdb master.
so we have to check COORDINATOR_ONLY instead of MASTER_ONLY in external table options.
This PR is used to fix the failed cases due to #13307

use COORDINATOR_ONLY instead of MASTER_ONLY for gpdb master

---

src/backend/optimizer/prep/preptlist.c

In the older version we can create table with (oids=true);
therefore, each row has an OID, when we update distributed columns of a table,
a row may move from one segment to another one.
so we must ensure that the target list contains the old OID so that the Split Update can copy it to the new tuple.
but the newest version of GPDB, does not support create table with (oids=true).
when merging postgres12, the logic of codes is deleted, the comments remain.
Now we delete related comments also.
we just modify comments, so there is no testcase.

resolve fixme update table about oids

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/cdb/motion/ic_tcp.c
src/backend/cdb/motion/ic_udpifc.c
src/test/regress/expected/motion_socket.out
src/test/regress/greenplum_schedule
src/test/regress/sql/motion_socket.sql

- Assert that interconnect_address is always set, in order to get rid of
conditional code
- Remove AI_PASSIVE flag from socket setup functions (it was being
ignored anyway as we always pass a unicast address to getaddrinfo)
- Comment cleanup
- Added regress test for checking motion socket 
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-refactor_ic_addr
This is a follow-up for https://github.com/greenplum-db/gpdb/pull/9696. Once we merge this, we are considering backporting the changes in #9696 along with the changes in this PR.

Refactor IC motion socket setup

---

src/backend/utils/adt/genfile.c
src/backend/utils/adt/pivot.c
src/include/catalog/pg_aggregate.dat
src/include/catalog/pg_cast.dat
src/include/catalog/pg_operator.dat
src/include/catalog/pg_proc.dat
src/test/regress/expected/opr_sanity.out

1.remove GPDB_12_MERGE_FIXME in pg_operator.dat:change the description 
to 'minus' for the unary operator.
2.remove GPDB_12_MERGE_FIXME(brought adminpack functions to core in GPDB)
in pg_proc.dat: in 6X_STABLE branch,adminpack functions has added to
GPDB and the extension adminpack is not compiled, the extension
adminpack shouldn't be used anymore.  upgrade the adminpack functions to 
new version which using the GRANT system to control access instead of 
having hard-coded superuser checks.
3.resolve GPDB_12_MERGE_FIXME in pg_proc.dat: rename 'numeric2point' to
'numeric2complex',although point and complex have same struct,but i
don't find any other functions has the format '*2point'.
4.resolve GPDB_12_MERGE_FIXME in pg_aggregate.dat: alter the transition
type to _int8 and alter return …

Resolve GPDB_12_MERGE_FIXME in catalog/*.dat

---

src/backend/utils/misc/guc.c

The checkpoint_timeout, archive_command, and data_directory GUC
settings were hidden back in the early GPDB 4.0.X days to prevent
users from messing with them. It should be fine to realign the
visibility of these GUCs with how they are in Postgres
(checkpoint_timeout and archive_command visible to all users and
data_directory visible to superusers or users with
pg_read_all_settings permission). They won't be documented in
Greenplum GUC documentation so they'll still be somewhat hidden to
individual users but not for us developers and the tools we build that
may require checking their GUC values. This is mainly needed now to
allow external tools such as pgbackrest to work properly.
Edit: Updated opening comment to reflect the new commit message.

Restore visibility of some GUCs to be viewable from pg_settings

---

src/test/regress/expected/motion_socket.out
src/test/regress/sql/motion_socket.sql

Since we have slightly different logic in constructing the source
address of motion sockets for singleton readers on the QD, create a
singleton reader on the QD as well.

motion_socket.sql: additional test coverage

---

src/test/regress/expected/motion_socket.out
src/test/regress/sql/motion_socket.sql

Use match_subs instead of match_ignore to ensure that we assert the
count of lines starting w/ "Checking postgres backend postgres"

motion_socket.sql: Correct regex match and ignore

---

src/backend/gporca/data/dxl/minidump/UpdateWindowGatherMerge.mdp
src/backend/gporca/libgpopt/src/base/CDistributionSpecSingleton.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Previously, we missed the opportunity to have GatherMerge for non-EstMaster singleton distribution. This lead to suboptimal plan with Sort node above Gather Motion executed on one segment. This, in turn, can lead to slow query execution and can consume all spills for heavy datasets.
This patch removes EstMaster distribution check, so EstSegment distribution can use GatherMerge alternative too.
New ORCA test shows the real example of fixed plan.
For example, the optimized memo Group 1 of new test looked like this:
```
Group 1 (#GExprs: 4):
0: CLogicalGet "window_agg_test" ("window_agg_test"), Columns: ["i" (9), "j" (10), "ctid" (11), "xmin" (12), "cmin" (13), "xmax" (14), "cmax" (15), "tableoid" (16), "gp_segment_id" (17)] Key sets: {[2,8]} [ ]
1: CPhysicalTableScan "window_agg_test" …
```

[7X] Enable GatherMerge plan alternative for non-EstMaster singleton distribution (GPORCA).

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/cdb/motion/ic_common.c
src/backend/cdb/motion/ic_tcp.c
src/backend/cdb/motion/ic_udpifc.c
src/backend/postmaster/postmaster.c
src/include/cdb/ml_ipc.h
src/include/postmaster/postmaster.h
src/test/regress/expected/motion_socket.out
src/test/regress/greenplum_schedule
src/test/regress/sql/motion_socket.sql

This backports #9696 and follow-up refactor #13326, and follow-up test fixes #13351 and #13352 in order to reduce the number of ports consumed by interconnect sockets. We also had to backport commit 349bf7cc1a.
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6x_ic_use_address

6X: Use a unicast IP address for motion sockets

---

src/backend/access/transam/xlog.c
src/test/gpdb_pitr/test_gpdb_pitr.sh
src/test/gpdb_pitr/test_gpdb_pitr_cleanup.sh

The recovery_end_command GUC was able to be set the but the execution
of it was disabled because GPDB did not support archive recovery at
the time. Now that archive recovery is being actively worked on, this
feature should be enabled back.

[6X] Enable execution of recovery_end_command GUC

---

gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_reconfigurer.py

Currently gprecoverseg -r waits for a maximum of 30 seconds for preferred primaries to be promoted. This may not be enough and results in an exception
gprecoverseg rebalance workflow
1. All the segments are up and running but the roles are switched
1. User runs gprecoverseg -r
1. gprecoverseg shuts down all the acting primaries(preferred mirrors)
1. gprecoverseg triggers fts probe
1. gprecoverseg sends a test query (CREATE TEMP TABLE) to start a distributed transaction to test if all the preferred primaries were promoted
1. gprecoverseg waits for a max of 30 secs and checks if the CREATE TABLE query succeeded, else raises timeout exception
1. gprecoverseg starts the stopped preferred mirrors
The problem is that in some cases, the preferred primary may not be promoted in 30 seconds which …

gprecoverseg rebalance is failed with timeout while promoting mirrors

---

gpMgmt/bin/gppylib/operations/rebalanceSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_reconfigurer.py

Currently gprecoverseg -r waits for a maximum of 30 seconds for preferred primaries to be promoted. This may not be enough and results in an exception
gprecoverseg rebalance workflow
All the segments are up and running but the roles are switched
User runs gprecoverseg -r
gprecoverseg shuts down all the acting primaries(preferred mirrors)
gprecoverseg triggers fts probe
gprecoverseg sends a test query (CREATE TEMP TABLE) to start a distributed transaction to test if all the preferred primaries were promoted
gprecoverseg waits for a max of 30 secs and checks if the CREATE TABLE query succeeded, else raises timeout exception
gprecoverseg starts the stopped preferred mirrors
The problem is that in some cases, the preferred primary may not be promoted in 30 seconds which results in an …

[6X] gprecoverseg rebalance is failed with timeout while promoting mirrors

---

src/backend/executor/spi.c

Commit 2ddd30e exposed divergent behavior between ORCA and PLANNER
through gp_toolkit functions that used to be hidden behind fallback
plans. It is questionable which is "correct".
Consider following query (based on gp_toolkit regress test):
```
EXPLAIN SELECT * FROM gp_toolkit.__gp_localid, gp_toolkit.__gp_param_local_setting('gp_role');
QUERY PLAN
-------------------------------------------------------------
Nested Loop
Join Filter: true
->  Function Scan on __gp_param_local_setting
->  Materialize
->  Gather Motion 3:1
->  External Scan on __gp_localid
Optimizer status: PQO version 3.122.0
```
ORCA runs the Function Scan on corrdinator while PLANNER runs it on
segments. But without execlocation defined in pg_proc catalog (like in
GPDB 6X) I think it's actually impossible to 100% …

Allow ORCA to reuse cached PL/pgSQL fallback plans

---

src/backend/postmaster/pgstat.c

The duplicate calling of AllocateFile() in pgstat_read_statsfile() is obviously wrong.
That will cause file allocation leak and easily hit the limit to result error out with
"too many private files demanded".

Remove duplicate code of file allocation in pgstat_read_statsfile().

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_preload.py
gpMgmt/bin/gpload_test/gpload2/TEST_local_schema_and_mode.py
gpMgmt/bin/gpload_test/gpload2/query27.ans
gpMgmt/bin/gpload_test/gpload2/query401.ans
gpMgmt/bin/gpload_test/gpload2/query405.ans
gpMgmt/bin/gpload_test/gpload2/query406.ans
gpMgmt/bin/gpload_test/gpload2/query433.ans
gpMgmt/bin/gpload_test/gpload2/query603.ans
gpMgmt/bin/gpload_test/gpload2/query604.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

backport pr #13192 to master branch
1. gpload should recognize capital letters table name in '" and "', gpload YAML file like:
```
GPLOAD:
PRELOAD:
- STAGING_TABLE: '"Staging_table"'
```
2. better gpload test frame. Make pytest print the diff file if the case fail

fix gpload cannot recoginze capital letters in staging_table

---

src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/executor/execMain.c
src/backend/executor/nodeSort.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/utils/misc/guc_gp.c
src/backend/utils/resource_manager/memquota.c
src/include/cdb/cdbvars.h
src/include/nodes/plannodes.h
src/include/utils/unsync_guc_name.h
src/test/isolation2/expected/resgroup/resgroup_query_mem.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_query_mem.sql

In the current resource group implementation, `query_mem` in the plan tree is calculated using 
QD's system memory and the number of primary segments, not QE's own system memory and 
the number of primary segments. This can result in the wrong memory being allocated at the 
execution stage eventually, which can lead to various problems such as OOM, underutilization of 
QE resources, etc.
The `query_mem` is linearly to system memory and number of primary segments if we enable 
resource group, the approximate calculation formula is as follows:
```bash
query_mem = (total_memory * gp_resource_group_memory_limit * memory_limit / nsegments) * memory_spill_ratio / concurrency
```
Only `total_memory` and `nsegments` differ between QD and QE, so we can dispatch these two 
parameters to QE, and …

recalculate QE's query_mem proportionally

---

src/backend/cdb/cdbcopy.c
src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/cdb/motion/ic_tcp.c
src/backend/tcop/postgres.c
src/include/miscadmin.h

Backport of https://github.com/greenplum-db/gpdb/pull/13148 to 6X_STABLE branch.

[6X] Replace usages of InterruptPending to the flag of query cancellation

---

src/backend/cdb/motion/ic_udpifc.c

Pipeline job interconnect becomes flaky since 55ce8ba. Revert it to
make pipeline stable and later we will do a complete fix.
This reverts commit 55ce8ba70f21d7864171a0ebf7dca137c533ceb6.

Revert "Make sendControlMessage to retry when interrupted (#12983)"

---

gpdb-doc/book/master_middleman/source/subnavs/admin-guide.erb
gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md

parallel retrieve cursor content in 6x is implemented in the gp_parallel_retrieve_cursor module. in 7/master, this functionality is built in.  in this PR:
- add an entry to the (now markdown-format) admin guide nav for parallel retrieve cursor.  
- add a markdown version of the parallel retrieve cursor docs. (i took the 6x dita content and converted it to markdown.  i also removed references to the module.)
doc review site link (behind vpn):  https://docs-lisa-prc-master.sc2-04-pcf1-apps.oc.vmware.com/7-0/admin_guide/parallel_retrieve_cursor.html

docs - add parallel retrieve cursor content to master

---

gpdb-doc/dita/ref_guide/gp_toolkit.xml

resolves https://github.com/greenplum-db/gpdb/issues/10777.

docs - clarify gp_toolkit.gp_stats_missing smirecs description

---

src/backend/executor/nodeHash.c
src/backend/executor/nodeHashjoin.c
src/include/executor/hashjoin.h
src/test/regress/expected/dpe.out
src/test/regress/expected/dpe_optimizer.out
src/test/regress/expected/partition_prune.out
src/test/regress/expected/partition_prune_optimizer.out
src/test/regress/sql/dpe.sql
src/test/regress/sql/partition_prune.sql

1.remove GPDB_12_MERGE_FIXME in nodeHash.c: In GPDB, we don't skip batch 0
is because batch 0 can still be used to support rescan of hashjoin.
2.remove GPDB_12_MERGE_FIXME in nodeHash.c:function BufFileGetSize has been
removed,use BufFileSize to get the size of buffile.support the collection of
hash chain statistics.
3.remove GPDB_12_MERGE_FIXME in nodeHashjoin.c: don't need to consider
parallel hashjoins which use shared tuplestores instead of raw files.
parallel hashjoins will never call the function SpillCurrentBatch,so we can
only check unshared here.

Resolve GPDB_12_MERGE_FIXME in nodeHash.c and nodeHashjoin.c

---

src/backend/utils/adt/dbsize.c
src/test/regress/expected/db_size_functions.out
src/test/regress/init_file
src/test/regress/sql/db_size_functions.sql

The returned relation 'auxRel' of 'try_relation_open()' is not checked.
Though it's safe to pass nullptr to 'calculate_total_relation_size()',
'relation_close()' needs a valid pointer.
Simple SQL to reproduce:
```sql
CREATE TABLE ao_with_malformed_visimaprelid (a int) WITH (appendonly=true);
-- Set visimaprelid record in the pg_appendonly table to a malformed value.
SET allow_system_table_mods=true;
UPDATE pg_appendonly
SET visimaprelid=16383
WHERE relid=(SELECT oid FROM pg_class WHERE relname='ao_with_malformed_visimaprelid');
SELECT pg_table_size('ao_with_malformed_visimaprelid');
```
This change is intuitive, do we need a test?

Fix potential nullptr dereference issue.

---

src/backend/executor/execMain.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/include/nodes/plannodes.h

This PR is a patch to #13160, which fixed inaccurate int type `total_memory_coordinator` of `PlannedStmt`.
The return type of the function `ResGroupOps_GetTotalMemory` is `int`, we need to be consistent with it, 
and fix the incorrect type writing and reading in functions such as `_outPlannedStmt` and `_readPlannedStmt`.
No more tests need, since #13160 already has.

fix inaccurate int type total_memory_coordinator of PlannedStmt

---

src/backend/executor/execMain.c
src/include/nodes/execnodes.h

Since PostgreSQL 10 has it's own partition table and partition pruning implementation, 
we'll never need `DynamicTableScanInfo` to record inner leaf tables' OID during HashJoin.
We can improve that from the below case:
```
create table foo (a int, b int, c int) partition by range(a) (start(0) end (10) every(1));
create table bar (d int, e int, f int) partition by range(d)  (start(5) end (15) every(1));
explain select * from foo, bar where foo.a = bar.d and bar.d > 5;
```
In 6X, we can use Dynamic Seq Scan to prune some leaf tables:
```
postgres=# explain select * from foo, bar where foo.a = bar.d and bar.d > 5;
QUERY PLAN                                                   
---------------------------------------------------------------------------------------------------------------
Gather …
```

remove DynamicTableScanInfo struct and correlative codes

---

src/test/recovery/t/201_close_connection.pl

Commit 733cbbd adjusted and backported an upstream fix that when client is disconnected the backend could be left as a zombie.
Both the upstream and our backport commits are without a test. The initial upstream patch, however, had a TAP test. It was removed later because it could suffer issues on slow machines in the buildfarm (details see https://www.postgresql.org/message-id/flat/77def86b27e41f0efcba411460e929ae%40postgrespro.ru)
The same fix in GPDB 6X (0bb081e) has an isolation2 test. But it was seen to be flaky in pipeline due to a race condition. Failure diff:
```
--- \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/expected\/pg_terminate_backend\.out	2022-04-06 14:16:31.922530584 +0000
+++ \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/results\/pg_terminate_backend …
```

Cherrypick TAP test for "Detect client disconnection while running query and interrupt execution"

---

gpdb-doc/dita/utility_guide/ref/gpload.xml

docs for https://github.com/greenplum-db/gpdb/pull/13163 and https://github.com/greenplum-db/gpdb/pull/13159.

docs - gpload selection of staging table distribution key

---

src/test/isolation2/expected/pg_terminate_backend.out
src/test/isolation2/sql/pg_terminate_backend.sql
src/test/modules/Makefile
src/test/modules/connection/Makefile
src/test/modules/connection/t/001_close_connection.pl

Commit 0bb081e adjusted and backported an upstream fix that when client is disconnected
the backend could be left as a zombie.
The upstream commit does not have a test. Our backport commit has an isolation2 test.
But it was seen to be flaky in pipeline due to a race condition:
```
--- \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/expected\/pg_terminate_backend\.out	2022-04-06 14:16:31.922530584 +0000
+++ \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/results\/pg_terminate_backend\.out	2022-04-06 14:16:31.922530584 +0000
@@ -50,7 +50,7 @@
!& psql -c "set client_connection_check_interval to 5000; commit; select pg_sleep(1359);" postgres; 2: select count(*) from pg_stat_activity where query='set client_connection_check_interval to 5000; commit; select pg_sleep(1359);'; …
```

[6X] Cherrypick TAP test for "Detect client disconnection while running query and interrupt execution"

---

src/backend/executor/execMain.c

ParamListInfo structures are used to pass parameters into the executor
for parameterized plans.  We support two basic approaches to supplying
parameter values, the "static" way and the "dynamic" way.
In the dynamic approach, all access to parameter values is done through
hook functions found in the ParamListInfo struct. The params will be
lazily evaluated in Executor. And more specifically, dynamic approach is
designed for plpgsql, there has a complete mechanism internally to call 
the `plpgsql_param_fetch` method to obtain dynamic parameters from 
the entrance of `plpgsql_call_handler()`.
In conclusion, we don't need to explicitly call the `paramFetch` method 
to get dynamic parameters before `preprocess_initplans`, but get them 
during the actual execution.
No more tests need, already …

remove redundant codes of invoking paramFetch before preprocess_initplans

---

src/backend/storage/file/buffile.c
src/test/regress/expected/workfile_limits.out
src/test/regress/sql/workfile_limits.sql

PostgreSQL breaks temporary files into 1 GB segments. Greenplum didn't do that until
v12 merge https://github.com/greenplum-db/gpdb/commit/19cd1cf4b68faff2e29bc2fa884c480e4644cdb4 breaks BufFiles into segments and counts each segment file as one work file.
The GUC `gp_workfile_limit_files_per_query` is used to control the maximum number of spill files for a given query, to prevent runaway queries from destroying the entire system. Counting each segment file is reasonable for this scenario and 100,000 seems reasonable default.
We for sure need to count all physical files and not logical files, this parameter/GUC is just for defensive mechanism and ideally not required to be tuned/configured by users most of the time (practically can just be #define in code, though fine as we have exposed …

Remove gpdb_12_merge_fixme in buffile.c.

---

src/backend/gporca/data/dxl/minidump/AllSubqueryWithSubqueryInScalar.mdp
src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
src/test/regress/expected/qp_correlated_query.out
src/test/regress/expected/qp_correlated_query_optimizer.out
src/test/regress/sql/qp_correlated_query.sql

If SubqueryAll operator has a Subquery scalar child then we should treat
the subquery context as EsqctxtValue, even if the SubqueryAll comes from
the predicate. Let's use the following example:
```
SELECT * FROM foo WHERE (SELECT a FROM foo limit 1) = ALL(SELECT b FROM bar);
+--CScalarSubqueryAll(=)["b" (8)]
|--CLogicalGet "bar" ("bar"),
+--CScalarSubquery["a" (16)]
+--CLogicalLimit <empty> global
|--CLogicalGet "foo" ("foo"),
|--CScalarConst (0)
+--CScalarCast
+--CScalarConst (1)
```
Setting subquery context EsqctxtValue signals to transform the scalar
subquery into a left outer apply as opposed to an inner apply in
function FGenerateCorrelatedApplyForScalarSubquery(). A left outer apply
is necessary to preserve non-matching rows in the output (inner apply
would have filtered them out) …

Fix subquery all subquery context

---

SECURITY.md

Created with guidance from VMware Security Response Center and VMware Open Source Project office, in the best interest of the Greenplum Database community.

Add security policy for Greenplum Database

---

src/test/ssl/gen_gpdb_certs.sh

The duplicated certificate config will override the final config in certificate. Then the CA flag and key Identifier will miss, and verify CA failed.
Ubuntu uses a newer ssl library, so it will suffer this error.

Remove duplicated certificate config in gen_gpdb_certs.sh

---

src/backend/cdb/motion/ic_udpifc.c

This patch aims to fix the memory leak issue #10314 .
Previously, the IC history table got pruned only after begining a
new distributed transaction (dtx). As a result, 
- when a transaction contains many commands, or 
- when a session never begins any distributed transaction, 
the history will never get pruned. This can cause memory leak.
This patch fixes this issue by reverting this part of code to the
last version before dependency on distributed transaction was
introduced. After that, we will only maintain a constant-length IC 
history. This ensures that
- The history table takes only constant amount of memory, and
- The history is long enough to handle mismatched packets.

Disregard dtx when pruning IC history

---

src/backend/commands/functioncmds.c

In GPDB, we don’t support ‘describe’ grammar in create function and
alter function, there is no ‘describe’ in upstream codes either,
so delete it here.

Remove gpdb_12_merge_fixme in functioncmds.c

---

src/backend/tcop/postgres.c
src/test/isolation2/input/idle_gang_cleaner.source
src/test/isolation2/output/idle_gang_cleaner.source

After commit cdc0104566d34374701bd2a889f15093655e43e5, `IDLE_GANG_TIMEOUT` won't enable in transaction or transaction block. It will cause `IDLE_GANG_TIMEOUT` to behave inconsistently as before. This commit fixed this issue and add a testcase for idle gang cleanup in transaction or transaction block.

Release idle reader gangs in transaction or transaction block

---

src/backend/executor/execMain.c
src/backend/executor/execUtils.c
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/test/isolation2/output/uao/parallel_delete_optimizer.source
src/test/isolation2/output/uao/parallel_update_optimizer.source
src/test/regress/expected/ao_locks_optimizer.out

By default, Greenplum Database acquires the more restrictive `EXCLUSIVE` lock 
(rather than `ROW EXCLUSIVE` in PostgreSQL) for `UPDATE`, `DELETE`, and 
`SELECT...FOR UPDATE` operations on heap tables. When the Global Deadlock 
Detector is enabled the lock mode for `UPDATE` and `DELETE` operations on 
heap tables is `ROW EXCLUSIVE`.
During the parse stage, the appropriate lock will be granted and store the lock
mode in `RangeTableEntry.rellockmode`. And there has lock upgrade in gpdb,
which has been perfected by #13274.
But the ORCA did not process the `rellockmode` in `RangeTableEntry` correctly
during translating DXL to PlannedStmt, this PR makes it correct.
After that, `rte->rellockmode` will be exactly equal to what lock we granted in the
parse stage, so we don't need to check stronger …

fix incorrect RTE's rellockmode in the process of translating DXL to PlannedStmt

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonly_compaction.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/commands/tablecmds.c
src/backend/commands/vacuum.c
src/backend/commands/vacuum_ao.c
src/include/access/appendonly_compaction.h
src/include/commands/vacuum.h

This is intended to provide a simple implementation for relation_vacuum
access method for Append-Optimized tables to address FIXMEs in
appendonly_vacuum_rel() and aoco_vacuum_rel().
It should be noted that although we implement both AMs, they still will not
be invoked in current code. Instead, we will keep doing AO/CO different
phases vacuuming by calling a wrapper function ao_vacuum_rel()(enclosing
ao_vacuum_rel_*()) in vacuum_rel() directly.

Resolve GPDB_12_MERGE_FIXME: Implement relation_vacuum AM for AO/CO tables.

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

this is a 6X backport of [1737f5f](https://github.com/greenplum-db/gpdb/commit/1737f5fded1d0805419721d49d6363035668795d) to enhance NOT-IN pullup.
The original PR to gpdb master:
https://github.com/greenplum-db/gpdb/pull/12998

Gpdb not in extend 6X backport

---

gpMgmt/bin/lib/gp_bash_functions.sh

To my surprise, gp_bash_functions.sh finds available commands by
iterating over hardcoded paths. This patch helps teach the script
find commands by using the `which` command.
I encountered this problem on my macOS laptop, the `ip` command
is installed by Homebrew and the path of it isn’t hardcoded in the script.

Try to lookup commands by $PATH before iterating over hardcoded paths.

---

gpdb-doc/markdown/admin_guide/managing/proxy-ic.html.md

xref to the guc section rather than the top of the (long) guc page.

docs - use more directed ic proxy guc xrefs

---

SECURITY.md

The Greenplum Project Team is the maintainer and responsible party specifically for what is mentioned in this security policy.

Clarify maintaining team in security policy

---

src/test/Makefile
src/test/README
src/test/authentication/Makefile
src/test/authentication/README
src/test/authentication/t/001_password.pl
src/test/regress/expected/password.out
src/test/regress/parallel_schedule
src/test/regress/serial_schedule
src/test/regress/sql/password.sql
src/test/ssl/Makefile
src/test/ssl/ServerSetup.pm
src/test/ssl/t/001_ssltests.pl

in 6X_STABLE we have not yet had test cases about authentication.
we add test cases for authentication to 6X_STABLE by extracting test cases from https://github.com/greenplum-db/gpdb/pull/13286/
the pr 13286 is Backporting scram-sha-256 to 6X_STSBLE
this pr contains some test cases about scram-sha-256, md5, and password for authentication.
here we extract the test cases about none scram-sha256 so when we do ABI test, we can run these
cases in the old version of psql.

add test cases for authentication

---

src/backend/access/table/table.c
src/backend/gpopt/gpdbwrappers.cpp
src/backend/storage/lmgr/lmgr.c
src/include/storage/lmgr.h

Currently `CondUpgradeRelLock()` always needs to open and close table to check if it's an AO table. Try to avoid that when we can pass an opened table in. 
And, modify `UpgradeRelLockIfNecessary()` too so the caller can pass opened table in, in which case if there's a need to upgrade, we will re-open the table.

Resolve a FIXME about not opening table in CondUpgradeRelLock() when possible

---

src/backend/gpopt/translate/CTranslatorUtils.cpp
src/backend/gpopt/utils/COptTasks.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
src/backend/gporca/libgpos/include/gpos/error/CException.h
src/backend/gporca/libgpos/src/error/CException.cpp
src/include/gpopt/utils/COptTasks.h

Issue is that with the overload we cannot properly raise while passing a
variadic integer argument. Instead it will interpret the arguemnt as
severity_level. This leads to bogus error messages that don't make sense.
Following SQL demonstrates the issue:
```sql
CREATE TABLE foo(a INT);
CREATE TABLE bar(b INT);
SET client_min_messages='log';
EXPLAIN SELECT * FROM foo WHERE (SELECT a FROM foo limit 1) = ALL(SELECT b FROM bar);
```
Error log with bogus attribute number:
```
LOG:  statement: EXPLAIN SELECT * FROM foo WHERE (SELECT a FROM foo limit 1) = ALL(SELECT b FROM bar);
LOG:  2022-04-08 19:12:08:288416 UTC,THD000,ERROR,"DXL-to-PlStmt Translation: Attribute number -1903101480 not found in project list",
```

Remove overload raise function with severity_level

---

src/backend/optimizer/util/inherit.c

Since #13274 and #13392 have already processed the LOCKMODE correctly in
`addRangeTableEntryForRelation()`, and no  matter we use ORCA or Optimizer,
we will get correct LOCKMODE in execution stage, so we don't need another
LOCKMODE upgrade in `expand_inherited_rtentry`, just remove it.

remove useless lockmode upgrade in inherit.c

---

src/backend/commands/explain_gp.c

In the implementation of EXPLAIN ANALYZE of Greenplum Database, it will aggregate all
execution results from all QEs, these results will be stored in the struct `CdbExplain_StatInst`,
used by function `cdbexplain_depositStatsToNode`. 
`nfiltered1` and `nfiltered2` are not a crucial results to indicate the bottleneck from the output
of EXPLAIN ANALYZE, so we can just use winner QE's `nfiltered1` and `nfiltered2` directly, which
has the largest number of rows returned.
Otherwise, we only print the non-zero filter value, which is `Rows Removed by Filter`:
```
postgres=# create table foo(
id int,
t int
) distributed by (id)
partition by range(t)
(
partition p1 start (0) end (1000),
partition p2 start (1000) end (2000)
);
postgres=# explain (analyze, costs off, summary off, timing off) select …
```

Use winner QE's nfiltered1 and nfiltered2 in the output of EXPLAIN ANALYZE

---

src/test/isolation2/expected/checkpoint_dtx_info.out
src/test/isolation2/sql/checkpoint_dtx_info.sql

The test is flaky w/ this failure diff:
```
--- \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/expected\/checkpoint_dtx_info\.out	2022-04-27 20:34:00.072018951 +0000
+++ \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/results\/checkpoint_dtx_info\.out	2022-04-27 20:34:00.076018949 +0000
@@ -43,6 +43,7 @@
Success:
(1 row)
33&: checkpoint;  <waiting ...>
+FAILED:  Forked command is not blocking; got output: CHECKPOINT
2: select gp_inject_fault_infinite('keep_log_seg', 'panic', 1);
gp_inject_fault_infinite
@@ -74,9 +75,7 @@
before or while processing the request.
33<:  <... completed>
-server closed the connection unexpectedly
-	This probably means the server terminated abnormally
-	before or …
```

Fix flaky test checkpoint_dtx_info

---

src/test/isolation2/expected/checkpoint_dtx_info.out
src/test/isolation2/sql/checkpoint_dtx_info.sql

Backporting 0d94a486e0cbe47a24fe23cf7a3d9ec3a424741f (PR #13441).
It is a straightforward merge, no conflict.
Original description
---------------
The test is flaky w/ this failure diff:
```
--- \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/expected\/checkpoint_dtx_info\.out	2022-04-27 20:34:00.072018951 +0000
+++ \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/results\/checkpoint_dtx_info\.out	2022-04-27 20:34:00.076018949 +0000
@@ -43,6 +43,7 @@
Success:
(1 row)
33&: checkpoint;  <waiting ...>
+FAILED:  Forked command is not blocking; got output: CHECKPOINT
2: select gp_inject_fault_infinite('keep_log_seg', 'panic', 1);
gp_inject_fault_infinite
@@ -74,9 +75,7 @@
before or while processing …
```

[6x] Fix flaky test checkpoint_dtx_info

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbgang.c
src/include/catalog/catversion.h
src/include/catalog/pg_proc.dat
src/include/cdb/cdbgang.h
src/include/cdb/cdbutil.h
src/test/regress/expected/gp_backend_info.out
src/test/regress/expected/motion_socket.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_backend_info.sql
src/test/regress/sql/motion_socket.sql

To debug into the master backend for a given Postgres session, you can `SELECT pg_backend_pid()` and attach a debugger to the resulting process ID. We currently have no corresponding function for the segment backends, however -- developers have to read the output of `ps` and try
to correlate their connected session to the correct backends. This is error-prone, especially if there are many sessions in flight.
`gp_backend_info()` is an attempt to fill this gap. Running
```sql
SELECT * FROM gp_backend_info();
```
will return a table of the following format:
```
id | type | content |   host    | port  |  pid
----+------+---------+-----------+-------+-------
-1 | Q    |      -1 | pchampion | 25431 | 50430
0 | w    |       0 | pchampion | 25432 | 50431
1 | w    |       1 | pchampion | 25433 | …
```

Add gp_backend_info() for runtime introspection/debugging

---

src/test/regress/expected/gang_reuse.out
src/test/regress/expected/gang_reuse_optimizer.out
src/test/regress/sql/gang_reuse.sql

Build a local dev pipeline without cassert, it not failed at `gang_reuse`, so maybe we can
consider remove this FIXME and make things the way they should be.

remove fixme in gang_reuse.sql

---

src/backend/access/table/table.c
src/backend/gpopt/gpdbwrappers.cpp
src/backend/storage/lmgr/lmgr.c
src/include/storage/lmgr.h

This commit removes the function UpgradeRelLockAndReuseRelIfNecessary
and clean up the implementation of CdbTryOpenTable. Now the logic is:
1. open the relation using some lockmode
2. if need correct lockmode (AO|AOCO with GDD enabled), then close and
reopen it using upgraded lockmode
3. if need lockUpgraded information, deduce this using actually mode
with request mode.
Also we remove the post-check for AO table not upgrade, because under
the new implementation that's impossible to happen and NOTE Greenplum
does not support change table's storage kind yet (Even support some
day, there will not be any problem).
The other place that uses UpgradeRelLockAndReuseRelIfNecessary is
gpdbwrappers.cpp:GPDBLockRelationOid. Before this commit, it passes
nullptr to …

Clean up logic in CdbTryOpenTable.

---

src/backend/commands/tablecmds.c
src/test/regress/expected/expand_table_ao.out
src/test/regress/sql/expand_table_ao.sql

This change is an extension of the PR #13246.
The commit c121bcd83c9 fixes the bug for
ALTER TABLE EXPAND TABLE and ALTER TABLE SET DISTRIBUTED BY
operations on AO tables with indexes.
These operations on AO tables with indexes are executed with CT + IIS
whereas on AO tables without indexes which are executed with CTAS
The bug about not preserving storage options is also present
for ALTER TABLE on AO tables without indexes case.
This change fixes that bug by adding the storage options preservation
logic to AT calls for AO tables which go through an internal CTAS.

Preserve AO storage options during internal CTAS

---

src/backend/access/external/fileam.c

In `external_set_env_vars_ext()`, it sets many env variables for external table, one of them is database name:
```c
// get pg_database tuple by SearchSysCache(DATABASEOID,...)
extvar->GP_DATABASE = get_database_name(MyDatabaseId);
extvar->GP_SEG_PG_CONF = ConfigFileName;
...
```
Though `MyDatabaseId` is always a valid value, but `get_database_name()` may return NULL in some rare cases.
Brief background:
In 5x stable (postgres version < 9.4), it uses SnapshotNow to scan catalog table, but: 
> "A concurrent SnapshotNow scan could see both old and new versions of an updated row as valid, or neither of them, if the commit happens between scanning the two versions."
Details pls see:
https://github.com/postgres/postgres/commit/568d4138c646cd7cd8a837ac244ef2caf27c6bb8 …

Check the return value of get_database_name() in external_set_env_vars_ext()

---

src/backend/cdb/dispatcher/cdbdisp.c
src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/cdb/motion/ic_tcp.c
src/backend/cdb/motion/ic_udpifc.c
src/backend/tcop/postgres.c
src/include/cdb/cdbdisp.h
src/test/regress/expected/ic_1.out
src/test/regress/sql/ic.sql

In `receiveChunksUDPIFC()`, a loop is waiting for: ( latch / one QE fd / timeout ) happens.
But waiting only one QE fd has a drawback, the fixme message said it clearly:
```
* GPDB_12_MERGE_FIXME:
* XXX: We currently only get a single FD to wait on. That catches
* the common case that *all* the QEs report the same error more or
* less at the same time. WaitLatchOrSocket doesn't allow waiting for
* more than one socket at a time. PostgreSQL 9.6 introduces a more
* flexible "wait event" API for the latches, so once we merge with
* that, we could improve this.
```
This PR enhances it: now, can sense the QE events more quickly. 
Because PR changed `DispatcherInternalFuncs` interface, so also need to modify ic_tcp.c to follow this change.

Resolve GPDB_12_MERGE_FIXME in motion/ic_udpifc.c

---

src/backend/commands/tablecmds.c
src/test/regress/expected/expand_table_ao.out
src/test/regress/sql/expand_table_ao.sql

This change is an extension of the PR #13248.
The commit 0fb3faf896 fixes the bug for
ALTER TABLE EXPAND TABLE and ALTER TABLE SET DISTRIBUTED BY
operations on AO tables with indexes.
These operations on AO tables with indexes are executed with CT + IIS
whereas on AO tables without indexes which are executed with CTAS
The bug about not preserving storage options is also present
for ALTER TABLE on AO tables without indexes case.
This change fixes that bug by adding the storage options preservation
logic to AT calls for AO tables which go through an internal CTAS.
(cherry picked from commit 10130c5d1d1d054e1fb4b258e638b02b073ab9c3, minor changes to the tests)

6X: Preserve AO storage options during internal CTAS

---

src/backend/commands/lockcmds.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/parser/gram.y
src/include/nodes/parsenodes.h
src/test/regress/expected/gp_lock.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_lock.sql

Currently, LOCK TABLE will always dispatch the lock statement to the
segments. However, the dispatch is unnecessary in many common cases
(e.g. when you just want to prevent DDL changes from ALTER TABLE or
DROP TABLE). Having the ability to not dispatch would give a small
performance boost in large Greenplum clusters when explicitly locking
a large amount of tables in a transaction.
To skip the dispatch, we introduce a new option to LOCK TABLE called
MASTER ONLY.  When added to the LOCK TABLE query, the lock will only
be taken on the master.
----------------------------
This idea came from observing a large Greenplum cluster taking a couple hours to lock 10000+ tables on a presumably saturated network.  The locks were being taken just to prevent DDL changes.
Need to add doc changes but …

Add MASTER ONLY option for LOCK TABLE

---

src/backend/executor/nodeShareInputScan.c
src/bin/pg_upgrade/pg_upgrade.h
src/include/utils/builtins.h

Commit b554f888881949de1952537978e727f88f458e3d upgrade the adminpack functions to new version,
the old version function won’t be used. And postgres keep the old version functions in backend,
so add the declaration of these functions in builtins.h file to fix the compiler warning.

fix compiler warning for genfile.c

---

contrib/pg_upgrade/pg_upgrade.h
src/backend/executor/nodeShareInputScan.c

1.util.c: function ‘gp_fatal_log’ might be a candidate for ‘gnu_printf’ format attribute
[-Wsuggest-attribute=format], add the attribute gnu_printf to function gp_fatal_log.
2.nodeShareInputScan.c: the format issue, change the indents.

[6X] fix compiler warning for util.c and nodeShareInputScan.c

---

src/backend/utils/adt/selfuncs.c
src/test/regress/expected/select_distinct.out
src/test/regress/expected/select_distinct_optimizer.out
src/test/regress/sql/select_distinct.sql

related GitHub issue: #13467
fixed ERROR: cache lookup failed for attribute 0 of relation xxx (lsyscache.c:943). when SELECT DISTINCT <father_table> FROM <father_table>

Fixed 'select distinct <tbl_name> from <tbl_name>' for inheritance/partition table in GP7 

---

src/backend/executor/nodeHash.c
src/backend/executor/nodeHashjoin.c
src/backend/storage/file/buffile.c
src/include/storage/buffile.h
src/test/isolation2/input/workfile_mgr_test.source
src/test/isolation2/output/workfile_mgr_test.source
src/test/isolation2/workfile_mgr_test.c

This commit is to remove GPDB_12_MERGE_FIXMEs in `workfile_mgr_test.c`, which
are noted about the breakage of BufFile API changes.
BufFileSize() now has a different behavior compared to 6X, it was like:
```
BufFileGetSize(BufFile *buffile)
{
returns buffile->maxoffset; // buffile->maxoffset = buffile->offset + buffile->pos;
}
```
After the merge, BufFileSize() only returns the size on disk, not including the
buffer.
Upstream is safe because it's used only once, and it's after BufFileOpenFileSet().
```
file = BufFileOpenFileSet(&lts->fileset->fs, filename, O_RDONLY, false);
filesize = BufFileSize(file);
```
But Greenplum uses it in `ExecHashTableExplainBatchEnd()` to collect inner and
outer batch size.
Therefore, add the function `BufFileGetSize()` back to get the real BufFile size.

Remove the gpdb_12_merge_fixmes in workfile_mgr_test.c

---

src/backend/cdb/cdbdistributedsnapshot.c
src/backend/cdb/cdbtm.c
src/backend/storage/ipc/sinval.c
src/backend/utils/time/snapmgr.c
src/include/cdb/cdbdistributedsnapshot.h
src/include/cdb/cdbtm.h
src/test/isolation2/expected/export_distributed_snapshot.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/export_distributed_snapshot.sql

Add distributed snapshot support to pg_export_snapshot
This PR adds distributed snapshot metadata when exporting and
importing snapshots.
Calling `select pg_export_snapshot()` from the QD will write the
following fields to the snapshot file in `pg_snapshots` in the
coordinator data directory.
```
dsxminall
dsid
dsxmin
dsxmax
dscnt
dsxip
```
When a snapshot is imported via SET TRANSACTION SNAPSHOT from the QD, subsequent
queries will have the distributed snapshot metadata dispatched to the QEs.
This enables cluster-wide data visibility consistency.
Reference: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/C6cY8yIbcps

Add distributed snapshot support to pg_export_snapshot

---

src/test/isolation2/expected/export_distributed_snapshot.out
src/test/isolation2/sql/export_distributed_snapshot.sql

Commit 8eaa3b682efb050ccdd7b22c0f0b7087b8ea6efd updated the
behavior of ON [COORDINATOR | ALL SEGMENTS] to only allow
set returning functions.
This commit updates the export snapshot isolation tests
to reflect that change.
Add tests for UPDATE and DELETE table

Fix export snapshot test

---

src/backend/access/external/url_curl.c
src/bin/gpfdist/regress/input/gpfdist2.source
src/bin/gpfdist/regress/output/gpfdist2.source

Psql may report "unknown meta type 108" sometimes when error happens
at the gpfdist side. But from the perspective of error handling, this
error message should never be reported. If the message is reported,
it hints that a bug exists in the gpfdist external table subsystem.
After debugging the bug, I have found two essential conditions that
could trigger this error message to be reported.
1. Error happened at gpfdist side and an error was reported to the
segment with GP-PROTO:1 protocol.
2. "LOG ERRORS SEGMENT REJECT LIMIT" should be set in the readable
external table.
This bug may be introduced by this commit 522c7c09e59df8993f33c8ce56e07734d5a24a4d. Because
when sreh is enabled, when gpfdist reports an error by GP-PROTO:1
protocol, it is handled by single row error handling. And after …

Fix gpfdist report "unknown meta type 108" error master.

---

src/backend/access/aocs/aocsam.c
src/backend/access/aocs/aocsam_handler.c
src/backend/access/aocs/aocssegfiles.c
src/backend/access/appendonly/aosegfiles.c
src/backend/access/appendonly/appendonly_visimap_udf.c
src/backend/access/appendonly/appendonlyam.c
src/backend/access/brin/brin.c
src/backend/access/heap/heapam_handler.c
src/backend/commands/tablecmds.c
src/backend/commands/vacuum_ao.c
src/include/access/aocssegfiles.h
src/include/access/aosegfiles.h
src/include/access/tableam.h
src/include/cdb/cdbaocsam.h
src/include/cdb/cdbappendonlyam.h
src/test/isolation2/input/uao/limit_indexscan_inits.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/limit_indexscan_inits.source

Previously, initialization of segment file lastSequence during
Append-Optimized table index scan is by calling ReadLastSequence()
for all 128 segments, which introduced many unnecessary gp_fastsequence
scans in most cases, slowing down the query speed.
This change narrows down to initialize lastSequence only for AO
target scanning segments, excluding non-existing ones to reduce
unnecessary gp_fastsequence scans.

Initialize lastSequence only for the target scanning segments before index scan.

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/qp_functions_in_contexts_setup.out
src/test/regress/expected/qp_functions_in_subquery.out
src/test/regress/sql/qp_functions_in_contexts_setup.sql
src/test/regress/sql/qp_functions_in_subquery.sql

These are limitations for functions defined with the `EXECUTE ON MASTER` or
`EXECUTE ON ALL SEGMENTS` attribute in Greenplum doc, one of them is: The
function must be a set-returning function. We can't pull up a subquery
has set-returning functions in target list as `RTE_RESULT` relation. Therefore,
we don't need check execute location for functions in RTE_RESULT
relation's target list.

Resolve GPDB_12_MERGE_FIXME in pathnode.c

---

src/bin/pg_upgrade/check.c

Two commits:
1) pg_upgrade --continue-check-on-fatal exit status 1 on fatal
gpupgrade relies on a non-zero exit status code when there are errors in pg_upgrade in order to correctly bubble up errors. Thus, when there is at least one fatal error during check return a non-zero exit status.
2) pg_upgrade: print check output file location
The primary user of pg_upgrade is gpupgrade where users need to know the full path location to the pg_upgrade check output files.
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/pgUpgradeCheckFixups_7X
Backport: https://github.com/greenplum-db/gpdb/pull/13475

[7X] pg_upgrade --check fixups

---

src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/cdb/dispatcher/cdbgang.c
src/backend/cdb/dispatcher/cdbgang_async.c
src/backend/executor/execMain.c
src/backend/utils/resgroup/resgroup-ops-linux.c
src/backend/utils/resgroup/resgroup.c
src/include/cdb/cdbgang.h
src/include/cdb/cdbutil.h
src/include/utils/resgroup.h

The global variable host_segments is **only** used on QEs under resource
group mode and the value is dispatched to QEs from QD. Previously in
the function getCdbComponentInfo(), QD make a hashtable, and count host_segments
group by the key of ip address. This is not correct. A typical
Greenplum deployment environment may have different ip addresses point
to the same machine. Use ip address as hash key will lead to wrong
number of host_segments and lead to more memory limit of a segment
than user's intent.
This commit use hostname as a machine's unique identifier to fix the issue.
-------
It is not easy to add a test case for this. I have manually test under my local env (demo cluster in a single VM), host_segments should be 4:
I directly update `gp_segment_configuration` to modify some …

Use hostname instead of ip to compute the host_segments.

---

src/backend/cdb/dispatcher/cdbgang_async.c

My previous commit: https://github.com/greenplum-db/gpdb/commit/e30909fccfef42a99070f080b7c06439d6d79b29 caused the ubuntu18.04 related jobs of master pipeline failed.
After investigation, the reason is a little tricky:
When checking the ready events in `cdbgang_createGang_async()`
https://github.com/greenplum-db/gpdb/blob/61323b178e46b8a9595f06e14cff9c91bd2f144a/src/backend/cdb/dispatcher/cdbgang_async.c#L307-L309
It is called `PQconnectPoll(conn)` to iterate to the next state.
But a notable point is:
The `conn->sock` may be closed and set a new one in `PQconnectPoll()` (details pls grep `need_new_connection` variable usage in it). So after `PQconnectPoll(conn)`, the conn->sock maybe a new sock fd and the previous fd has been deleted (OS did it) from the epoll set.
When this happened, in …

Fix ubuntu18.04 failed pipeline jobs: destroy and create a new waiteventset in each loop of cdbgang_createGang_async()

---

src/backend/cdb/endpoint/cdbendpoint.c
src/backend/cdb/endpoint/cdbendpointretrieve.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h

6X: Add GUC gp_log_endpoints to print endpoints information to server log

---

src/backend/cdb/motion/ic_udpifc.c

This patch backports PR #13355 to 6X_STABLE
This patch aims to fix the memory leak issue #10314 .
Previously, the IC history table got pruned only after begining a
new distributed transaction (dtx). As a result,
- when a transaction contains many commands, or
- when a session never begins any distributed transaction,
the history will never get pruned. This can cause memory leak.
This patch fixes this issue by reverting this part of code to the
last version before dependency on distributed transaction was
introduced. After that, we will only maintain a constant-length IC
history. This ensures that
- The history table takes only constant amount of memory, and
- The history is long enough to handle mismatched packets.
(cherry picked from commit 7ece53ec846977ec670830d62ab683d8efd1923f)

[6X] Disregard dtx when pruning IC history

---

src/backend/utils/adt/selfuncs.c
src/test/regress/expected/select_distinct.out
src/test/regress/sql/select_distinct.sql

When the GUC gp_statistics_pullup_from_child_partition is on,
we run 'SELECT DISTINCT <father_table> FROM <father_table>'
for an inheritance/partition table will meet the error:
'cache lookup failed for attribute 0 of relation xxx (lsyscache.c:xxx)'.
See Github Issue 13467 for details.
This commit fixes the issue by taking 0 varnoatto into consideration when
get_attname and get_attnum.
Co-authored-by: juyi.lmz <juyi.lmz@alibaba-inc.com>
backport PR #13468 to 6X_STABLE.

[6X] Fix 'cache lookup failed for attribute 0 of relation xxx'

---

src/backend/catalog/namespace.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/tcop/postgres.c
src/include/catalog/namespace.h
src/test/regress/expected/bfv_temp.out
src/test/regress/sql/bfv_temp.sql

If a query has multiple Gangs, the secondary Gang cannot get the correct temporary namespace ID.
Consider this SQL:
```
create table tn_a(id int) distributed by (id); insert into tn_a values (1), (2);
create temp table tn_a_tmp(a int) distributed replicated; insert into tn_a_tmp values(1);
create or replace function fun(sql text, a oid) returns bigint AS '
return plpy.execute(sql).nrows() + a
' language plpython3u stable;
create table tn_a_new as with c as (
select fun('select * from tn_a_tmp', s.id) from tn_a s
) select 1 from c;
```
The key is to the reader gang to access temp table via text-sql execute, this can only happen when
UDF executing text SQL and the temp table is replicated.
In this scenario happened. the first `create temp table` will create a
temporary schema then dispatch …

6X: dispatch temporary namespace ID to all Gangs.

---

src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

This addresses https://github.com/greenplum-db/gpdb/issues/13058 (this fixes the issue described but this PR is not the backport to `6X_STABLE`)
Previously, CPhysicalJoin derived the outer distribution when it was tainted
replicated. It checked only for strict replicated and universal replicated and
returned the inner distribution in these cases (in this case, it satisfies
random). Tainted replicated wasn't considered and was causing an undercount (the
JOIN derived tainted replicated instead of random, which was causing the number
of columns to be undercounted, because it wrongly assumed that one segment
contained all output columns).

Updated CPhysicalJoin to derive the inner distribution in the case of tainted replicated

---

contrib/pg_upgrade/check.c

Two commits:
1) pg_upgrade --continue-check-on-fatal exit status 1 on fatal
gpupgrade relies on a non-zero exit status code when there are errors in pg_upgrade in order to correctly bubble up errors. Thus, when there is at least one fatal error during check return a non-zero exit status.
2) pg_upgrade: print check output file location
The primary user of pg_upgrade is gpupgrade where users need to know the full path location to the pg_upgrade check output files.
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/pgUpgradeCheckFixups
Original PR: https://github.com/greenplum-db/gpdb/pull/13474

[6X] pg_upgrade --check fixups

---

src/include/nodes/tidbitmap.h

In PostgreSQL 12, it will use the size of a pointer to define the size of a bitmap word, just 
like:
```
/*
* Data representation
*
* Larger bitmap word sizes generally give better performance, so long as
* they're not wider than the processor can handle efficiently.  We use
* 64-bit words if pointers are that large, else 32-bit words.
*/
#if SIZEOF_VOID_P >= 8
#define BITS_PER_BITMAPWORD 64
typedef uint64 bitmapword;		/* must be an unsigned type */
typedef int64 signedbitmapword; /* must be the matching signed type */
#else
#define BITS_PER_BITMAPWORD 32
typedef uint32 bitmapword;		/* must be an unsigned type */
typedef int32 signedbitmapword; /* must be the matching signed type */
#endif
```
So, `bitmapword` will be 32 bits on some 32-bit-platform.
For the functions and methods in the …

remove GPDB_12_MERGE_FIXME in tidbitmap.h: make sure TBM_BITS_PER_BITMAPWORD is 64-bit

---

src/backend/executor/nodeSort.c

In ancient time (GPDB3) gp_sort_max_distinct was added as a patch for mechanism to 
choose heap sort or insertion sort when sorting tuple.
In GPDB6 (and older versions) there is mechanism to choose heap sort or insertion sort 
when sorting tuple: heap sort is used for sort without limit or duplicate elimination, or 
discard_ratio < 50, otherwise insertion sort is used. However, insertion sort is less 
efficient for large numbers of distinct values. In GPDB3 Cohen Jeffrey patched the sort 
to forcedly fallback to heap sort if the number of distinct values exceeds 20K. 
Tuplesortstate->gpmaxdistinct (and GUC gp_sort_max_distinct) with default value 20000 
indicates maximum distinct values.
The patch is meaningless for now because the entire mechanism is disappeared in GPDB7. 
The reason …

Remove FIXME about maxdistinct/sort_flags

---

src/backend/utils/misc/guc.c

The checkpoint_timeout, archive_command, and data_directory GUC
settings were hidden back in the early GPDB 4.0.X days to prevent
users from messing with them. It should be fine to realign the
visibility of these GUCs with how they are in Postgres
(checkpoint_timeout and archive_command visible to all users and
data_directory visible to superusers or users with
pg_read_all_settings permission). They won't be documented in
Greenplum GUC documentation so they'll still be somewhat hidden to
individual users but not for us developers and the tools we build that
may require checking their GUC values. This is mainly needed now to
allow external tools such as pgbackrest to work properly.
Backported from GPDB master:
https://github.com/greenplum-db/gpdb/commit/598557c697c25343ee830ac3c6630680a3d01 …

[6X] Restore visibility of some GUCs to be viewable from pg_settings

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/backend/gporca/libgpopt/src/operators/CLogicalTVF.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalTVF.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
src/backend/gporca/libnaucrates/include/naucrates/md/IMDRelation.h
src/backend/gporca/libnaucrates/src/md/IMDRelation.cpp
src/backend/gporca/libnaucrates/src/operators/CDXLLogicalTVF.cpp
src/backend/gporca/libnaucrates/src/operators/CDXLPhysicalTVF.cpp
src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
src/include/gpopt/translate/CTranslatorUtils.h
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Objective: Support Const TVF returning composite type in ORCA.
Background: Const TVF returning multi-column composite type returns incorrect result in 6X. TVF returning composite type falls back on planner in 7X.
Implementation:
1. Use invalid funcid to indicate TVF evaluates to const. Remove all valid funcid assertions.
2. Refactored code. Query -> DXL translation cases divided into three categories (i) non TVF && non const composite (eg. Var, Const returning simple type), (ii) const TVF returning composite type, (3) TVF.
3. Add relation storage type and token for composite type, similar to "virtual" storage type in 6X.
4. Remove tests for const TVF fall back. Add tests for const TVF

Support Const TVF returning composite type in ORCA

---

gpMgmt/bin/gppylib/operations/unix.py

follow up #10853 and #11530
I get this error when testing gpexpand (checking if TDE works with gpexpand):
```
20210809:17:39:37:140129 gpexpand:fluorite:sa-[DEBUG]:-Running Command:  python -c "import os, pickle; print(pickle.dumps(os.path.isdir('~/share/packages/archive')))"
20210809:17:39:37:140129 gpexpand:fluorite:sa-[DEBUG]:-Ending CheckRemoteDir
20210809:17:39:37:140129 gpexpand:fluorite:sa-[DEBUG]:-Ending SyncPackages
20210809:17:39:37:140129 gpexpand:fluorite:sa-[ERROR]:-unpickling stack underflow
File "~/lib/python3/gppylib/commands/base.py", line 277, in run
self.cmd.run()
File "~/lib/python/gppylib/operations/__init__.py", line 53, in run
self.ret = self.execute()
File "~/lib/python/gppylib/operations/package.py", line 1000, in execute
if not …
```

pylib: Fix the error while doing remote file operation

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
gpMgmt/bin/gppylib/recoveryinfo.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/lib/gpcreateseg.sh
gpMgmt/sbin/gpsegrecovery.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature

Problem Statement: port on mirror segment's postgresql.conf is not in
sync with the port listed in gp_segment_configuration table. this
creates problem while starting mirror segment without providing the port
number in pgctl command(required for gpv).
Fix: to fix this problem we have identified the blocks where we need to
make changes to keep the port in sync between mirror conf and
gp_segment_configuration. This commit consist of following changes:
1. Updated SED_PG_CONF for the search regex which was causing issue in
find and replace while changing the port.
2. Updated CREATE_QES_MIRROR() to update the port number in conf file
after mirror gets created.
3. Added port update call in FullRecovery and IncrementalRecovery class
as this is the place which is common for …

Update mirror port in postgresql.conf 

---

src/backend/postmaster/postmaster.c
src/test/recovery/t/103_promotion_wait_status_ready.pl

Earlier https://github.com/greenplum-db/gpdb-postgres-merge/commit/67a589c6ec2467256a33075d0be9fad1b46a1514
introduced checking for promote_trigger_file before
putting PM_STATUS_STANDBY into postmaster.pid as if we intend
to promote - PM_STATUS_READY will be written when promotion
completes. However, promote_trigger_file is not the only option
to request promotion. In the case of recovery, the recovery_target_action
configuration parameter to 'promote' will also result
in promotion after recovery is completed.

Check recoveryTargetAction before put PM_STATUS_STANDBY

---

src/backend/access/external/url_curl.c
src/bin/gpfdist/regress/input/gpfdist2.source
src/bin/gpfdist/regress/output/gpfdist2.source

Psql may report "unknown meta type 108" sometimes when error happens
at the gpfdist side. But from the perspective of error handling, this
error message should never be reported. If the message is reported,
it hints that a bug exists in the gpfdist external table subsystem.
After debugging the bug, I have found two essential conditions that
could trigger this error message to be reported.
1. Error happened at gpfdist side and an error was reported to the
segment with GP-PROTO:1 protocol.
2. "LOG ERRORS SEGMENT REJECT LIMIT" should be set in the readable
external table.
This bug may be introduced by this commit 522c7c09e5. Because
when sreh is enabled, when gpfdist reports an error by GP-PROTO:1
protocol, it is handled by single row error handling. And after it
is handled, `NextCopyFrom` …

Fix gpfdist report "unknown meta type 108" error 6X.

---

src/backend/access/external/url_curl.c
src/bin/gpfdist/regress/input/gpfdist2.source
src/bin/gpfdist/regress/output/gpfdist2.source

Psql may report "unknown meta type 108" sometimes when error happens
at the gpfdist side. But from the perspective of error handling, this
error message should never be reported. If the message is reported,
it hints that a bug exists in the gpfdist external table subsystem.
After debugging the bug, I have found two essential conditions that
could trigger this error message to be reported.
1. Error happened at gpfdist side and an error was reported to the
segment with GP-PROTO:1 protocol.
2. "LOG ERRORS SEGMENT REJECT LIMIT" should be set in the readable
external table.
This bug may be introduced by this commit 522c7c09e5. Because
when sreh is enabled, when gpfdist reports an error by GP-PROTO:1
protocol, it is handled by single row error handling. And after it
is handled, `NextCopyFrom` …

Fix gpfdist report "unknown meta type 108" error 5X.

---

src/backend/catalog/namespace.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/tcop/postgres.c
src/test/regress/expected/bfv_temp.out
src/test/regress/sql/bfv_temp.sql

follow up #13213 and #13221.
dispatch temp namespace oid in every query. on writer gang skips set
temp namespace oid, the writer gang will do InitTempTableNamespace().
on reader gang always use the oid from query message, allow temp NS
oid change dynamically.
temp namespace oid will stale after creating temp NS rollback. it
should be fine, new oid will be dispatched in the next sql.

Don't dispatch temp namespace oid to writer gang

---

src/backend/cdb/cdbpath.c
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

In planner, If a SegmentGeneral pat contains volatile expressions, it
cannot be taken as General, and we will try to make it SingleQE by
adding a motion (if this motion is not needed, it will be removed
later). But a corner case is that if the path refs outer Params then
it cannot be motion-ed. This commit fixes the issue by not trying to
bring to singleQE for segmentgeneral path that refs outer Params.
See Github Issue 13532 for details.

Do not turn to singleQE for SegmentGeneral path refs outer Params.

---

gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md

parallel retrieve cursor functionality is no longer beta.  (master)

docs - remove beta designation from parallel retrieve cursor

---

gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13254 and https://github.com/greenplum-db/gpdb/pull/13253.
there is a new guc, gp_log_endpints, that controls the logging of parallel retrieve cursor endpoints to the server log.
will be backported to 6X_STABLE
question:  do we want to mention this guc in the parallel retrieve cursor docs?  (i chose not to because it is superuser only.)

docs - add reference doc for new gp_log_endpoints guc

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmaputil.c
src/include/access/bitmap_private.h
src/test/regress/expected/bitmap_index.out
src/test/regress/expected/bitmap_index_optimizer.out
src/test/regress/sql/bitmap_index.sql

Since this PR #11377 has fixed bitmap index scan when concurrent insert update full 
bitmap page, which resolved concurrent read on bitmap index when there's insert running 
in the backend may cause the bitmap scan read wrong tid:
1. Query on bitmap: A query starts and reads all bitmap pages to `PAGE_FULL`, increases
the next tid to fetch, and releases the lock after reading each page.
2. Concurrent insert: insert a tid into `PAGE_FULL` cause expand compressed words to
new words, and rearrange words into `PAGE_NEXT`.
3. Query on bitmap: fetch `PAGE_NEXT` and expect the first tid in it should equal the
saved next tid. But actually `PAGE_NEXT` now contains words used to belong in PAGE_FULL.
This causes the real next tid less than the expected next tid. But our scan keeps increasing
the …

fix incorrect scan position during bitmap index words scan

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/test/regress/expected/union.out
src/test/regress/expected/union_optimizer.out
src/test/regress/sql/union.sql

cherry-picked
https://github.com/greenplum-db/gpdb-postgres-merge/commit/98154a8f6c47fc6007638ffe84e7ae8999b19f2a

ORCA: Explicitly fallback to planner if target list is empty

---

src/backend/cdb/cdbdistributedsnapshot.c
src/backend/cdb/cdbtm.c
src/backend/storage/ipc/sinval.c
src/backend/utils/time/snapmgr.c
src/include/cdb/cdbdistributedsnapshot.h
src/include/cdb/cdbtm.h
src/test/isolation2/expected/export_distributed_snapshot.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/export_distributed_snapshot.sql

Backport from https://github.com/greenplum-db/gpdb/pull/13201
Add distributed snapshot support to pg_export_snapshot
pg_export_snapshot now exports distributed snapshot metadata, enabling cluster-wide data visibility consistency via `SET TRANSACTION SNAPSHOT`
Calling `select pg_export_snapshot()` from the QD will write the
following fields to the snapshot file in `pg_snapshots` in the
coordinator data directory.
```
dsxminall
dsid
dsxmin
dsxmax
dscnt
dsxip
```
When a snapshot is imported via SET TRANSACTION SNAPSHOT from the QD, subsequent
queries will have the distributed snapshot metadata dispatched to the QEs.
Reference: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/C6cY8yIbcps

[6X] Add distributed snapshot support to pg_export_snapshot

---

src/backend/access/bitmap/bitmap.c
src/backend/access/bitmap/bitmaputil.c
src/test/regress/expected/bitmap_index.out
src/test/regress/expected/bitmap_index_optimizer.out
src/test/regress/sql/bitmap_index.sql

This is the backport of #13479.
Since this PR https://github.com/greenplum-db/gpdb/pull/11377 has fixed bitmap index scan when concurrent insert update full
bitmap page, which resolved concurrent read on bitmap index when there's insert running
in the backend may cause the bitmap scan read wrong tid:
1. Query on bitmap: A query starts and reads all bitmap pages to `PAGE_FULL`, increases
the next tid to fetch, and releases the lock after reading each page.
2. Concurrent insert: insert a tid into `PAGE_FULL` cause expand compressed words to
new words, and rearrange words into `PAGE_NEXT`.
3. Query on bitmap: fetch `PAGE_NEXT` and expect the first tid in it should equal the
saved next tid. But actually `PAGE_NEXT` now contains words used to belong in `PAGE_FULL`.
This causes the real next …

[6X] fix incorrect scan position during bitmap index words scan

---

src/backend/cdb/cdbpath.c
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

In planner, If a SegmentGeneral pat contains volatile expressions, it
cannot be taken as General, and we will try to make it SingleQE by
adding a motion (if this motion is not needed, it will be removed
later). But a corner case is that if the path refs outer Params then
it cannot be motion-ed. This commit fixes the issue by not trying to
bring to singleQE for segmentgeneral path that refs outer Params.
See Github Issue 13532 for details.
(cherry picked from commit https://github.com/kainwen/gpdb/commit/adde572bf29888d233598a503dac559dfa1223e8)

(6x backport) Do not turn to singleQE for SegmentGeneral path refs outer Params. 

---

src/backend/gporca/data/dxl/minidump/DqaAddRef.mdp
src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
src/backend/gporca/server/CMakeLists.txt

In gporca debug mode, a failed assertion “m_refs != 0xCdCdCdCdCdCdCdCd”
was observed on using the “.mdp” file generated from the sample query
like:
CREATE TABLE bar (a int, b int);
SET optimizer_minidump=always;
EXPLAIN SELECT COUNT(DISTINCT(a)) FROM bar;
The cause of the error was found in file: CXformSplitDQA.cpp, function :
CXformSplitDQA::PexprSplitHelper.  In this function, it was found that
while using “pexprDirectArg”pointer to the class CExpression, AddRef()
was not invoked. This resulted in a double free causing the exception.

Fix double free in debug build

---

src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGetBase.cpp
src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApply.cpp

If the partition constraints are too complicated, then the benefit of using
partition constraints during the plan outweigh the costs of calculating them.
The following disables partition constraint calculations for a set of queries.
This also adds an assertion which verifies that partition constraints (when
added after the partial index flag has been set) are valid. A similar assertion
exists inside of SetPartial, but running SetPartial before SetPartCnstr would
only check against the old partition constraints and not the new partition
constraints. This reverse-pattern exists in the codebase currently.
This commit is only on applicable for 6X. On 7X, due to the partitioned tables changes, we do not calculate it.

Speed up planning times by marking some partition constraints as dummy constraints (6X)

---

src/backend/utils/adt/datetime.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h
src/test/regress/expected/date.out
src/test/regress/sql/date.sql

reject ambigous 5-digits date in non-standard YYYMMDD format
The 5-digits date string was invalid and would be rejected on GPDB5. But then
the upstream pg modified the date parsing logic, which would make it parsed
as YYYMMMDD. As it's not a standard timeformat and the change causes gp6+ to
behave differently from previous version. this commit lets gp reject it by
default. And if the pg-like date parsing required, we can set the value of
GUC gp_allow_date_field_width_5digits to true.
This is a backport of commit 52b3646a from gpdb master (v7)
The original PR for master is here ( https://github.com/greenplum-db/gpdb/pull/13500 )

optional reject parsing ambigous 5-digits date in non-standard YYYMMDD format

---

src/backend/optimizer/plan/createplan.c
src/test/regress/expected/select_distinct.out
src/test/regress/expected/select_distinct_optimizer.out
src/test/regress/sql/select_distinct.sql

1. due to function push_partition_selector_candidate_for_join: for hashjoin,
or for nestloop or mergejoin with a Material or Sort node on the inner side,
they will process all the inner rows before scanning the outer side. Only in
these cases, a Partition Selector could be placed at this join. Even if the
prefetch_inner flag maybe reset to false, it doesn't affect the resullt.
2. the postgres planner doesn't support hash join on IS NOT DISTINCT FROM
for now, get rid of the hashqualclauses parameter from the make_hashjoin().

resolve GPDB_12_MERGE_FIXME in createplan.c

---

src/backend/executor/execMain.c

According to a reported error in PolicyEagerFreeAssignOperatorMemoryKB makes query end without calling mppExecutorCleanup #12690 , the code path in `standard_ExecutorStart` didn't handle exception in `PolicyAutoAssignOperatorMemoryKB` and `PolicyEagerFreeAssignOperatorMemoryKB` calling, which may cause the OOM exception not handled in `standard_ExecutorStart` but throw to upper `PortalStart` methods, while there is also exception handling machanism in `PortalStart` but `mppExecutorCleanup` will not call because of `portal->queryDesc` will be `NULL` in certain transation states. This PR fixed this issue.

Handling exception to call mppExecutorCleanup in standard_ExecutorStart

---

src/test/isolation2/expected/fts_segment_reset.out
src/test/isolation2/sql/fts_segment_reset.sql

Backport from https://github.com/greenplum-db/gpdb/pull/13543 . No cherrypick conflict.
--------
Have seen some flakiness in test fts_segment_reset because sometimes
FTS would still promote mirror if the primary takes a bit longer to
restart after getting out of RESET stage. An example like below:
- Primary 0 gets out of RESET and was going to be restarted:
2022-05-23 15:32:53.924540 UTC,,,p105578,th1560833280,,,,0,,,seg0,,,,,"LOG","00000","all server processes terminated; reinitializing",,,,,,,0,,"postmaster.c",4284,
- And it takes primary 0 about 2-3 seconds to do so:
2022-05-23 15:32:56.184117 UTC,,,p105578,th1560833280,,,,0,,,seg0,,,,,"LOG","00000","database system is ready to accept connections”
- Unfortunately before primary 0 could restart, FTS makes one last probe
and finds that …

[6X] Reduce flakiness in test fts_segment_reset

---

src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/include/nodes/plannodes.h

Commit cb120281a introduces two fields of struct PlannedStmt and not
put them at the end of the struct. In Greenplum 6X, some extensions,
like metrics_collector will use fields of PlannedStmt, and the
extension is created in a previous version of Greenplum 6, when users
upgrade to later version of Greenplum 6, the extension's .so file is
not recompiled, however offset of fields changed.
This commit fixes the ABI broken by putting the new-added fields at
the end of the struct.
---------------------
WIP.
TODOS:
1. ~manually verify the fix~ (DONE, we manually test).
2. try to see if we can add a test case.

(6x only) Fix API broken introduced by cb120281a.

---

src/backend/optimizer/plan/planner.c
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect.sql

1.   create table foo (a int, b int, c int);
explain select * from (select b, c from foo order by 1,2) as x limit 3;
above case in 6X_STABLE generate 2 phase limit path, the results are not sorted. 
in master, the case generates 1 phase limit path, but the results are sorted.
if a subpath is sorted, but the subqueryscan is not. the order of subqueryscan is 
implementation-dependent which is specified by SQL standard.
revert the modification to be consistent with gpdb6 to enhance performance.
2.   define a ParseState as the param of make_op instead of NULL to avoid hitting null pointer exception.
when calculating limitoffset we should use "+" of schema pg_catalog to avoid misuse user-defined operator "+".

resolve GPDB_12_MERGE_FIXME in planner to revert 1 phase limit path to 2 phase limit path

---

src/backend/commands/tablecmds.c
src/backend/commands/tablecmds_gp.c
src/include/commands/tablecmds.h
src/test/regress/expected/pg_stat_last_operation.out
src/test/regress/sql/pg_stat_last_operation.sql

> GPDB_12_MERGE_FIXME: We reported new partitions with "ALTER INHERIT"
> in previous versions, but I think it was mostly an implementation
> artifact when PostgreSQL didn't have native partitioning support and
> GPDB partitioning was a special case of table inheritance. Take a
> holistic look on how all the partition commands are reported in
> pg_stat_last_operation. Including new upstream commands
> CREATE TABLE PARTITITION OF, ATTACH PARTITION etc.
This commit tracked GPDB specific alter partition commands in pg_stat_last_operation.
New upstream commands:
```
postgres=# alter table sales detach partition sales_1_prt_sep16;
postgres=# select * from pg_stat_last_operation;
classid | objid | staactionname | stasysid | stausename | stasubtype |            statime …
```

metadata tracking for GPDB specific ALTER PARTITION commands

---

src/backend/cdb/dispatcher/cdbdisp_async.c

A history commit ee255b55398818c6e6401668b540d2f45ff4c719 introduced a `PG_TRY()` / `PG_CATCH()` surrounding to `CHECK_FOR_INTERRUPTS`, which seems not necessary and may cause some trouble, according the discussions here:
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883190234
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883240823
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883244949
So it's better to revert this change to avoid nested `TRY-CATCH` now.
What do you think? @maksm90 @soumyadeep2007 @interma 
,## Here are some reminders before you submit the pull request

Revert PG_TRY() / PG_CATCH() surrounding of CFI.

---

src/backend/commands/lockcmds.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/parser/gram.y
src/include/nodes/parsenodes.h
src/test/regress/expected/gp_lock.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_lock.sql

Backporting from #8703
`COORDINATOR ONLY` in 7x is the same thing. We'll just support and document `MASTER ONLY` in 6x for keyword coherency.
-----------
Currently, LOCK TABLE will always dispatch the lock statement to the
segments. However, the dispatch is unnecessary in many common cases
(e.g. when you just want to prevent DDL changes from ALTER TABLE or
DROP TABLE). Having the ability to not dispatch would give a small
performance boost in large Greenplum clusters when explicitly locking
a large amount of tables in a transaction.
To skip the dispatch, we introduce a new option to LOCK TABLE called
MASTER ONLY.  When added to the LOCK TABLE query, the lock will only
be taken on the master. And to limit the possible misuses, currently
we support MASTER ONLY only for AccessShareLock.

 [6X] Add MASTER ONLY option for LOCK TABLE

---

src/backend/gporca/data/dxl/minidump/UpdateDistKeyWithNestedJoin.mdp
src/backend/gporca/libgpopt/src/operators/CPhysicalSplit.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp

When deriving distribution spec for `CPhysicalSplit`, ORCA checks if its
disjoint with the hashed colrefs aswell as the equivalent hashed colrefs
(PdshashedEquiv()). For certain nested queries with a JOIN on the same
column, it is possible that the equivalent hashed colrefs also have
other equivalent hashed colrefs. ORCA did not consider such cases and
would skip recursively checking for hashed-equivalent colrefs and
include it to check if its disjoint with the colrefs being modified.
Thus generating a plan without a Redistribute on top of a Split node
when updating the distribution column. This would lead to wrong results.
This PR fixes the issue: https://github.com/greenplum-db/gpdb/issues/13242

Fix missing Redistribute on top of Split Update

---

src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/cdb/dispatcher/cdbgang_async.c
src/backend/cdb/motion/ic_udpifc.c
src/test/isolation2/init_file_isolation2
src/test/regress/init_file

Introduced the waiteventset instead of poll() in my previous commits:
https://github.com/greenplum-db/gpdb/commit/e30909fccfef42a99070f080b7c06439d6d79b29
https://github.com/greenplum-db/gpdb/commit/683d5a4c724f4eee1dc98fded1e0b1e7b37371ef
But in some scenarios (most of them are exception related), the epoll fd leaks, this PR fix it.

Fix epoll() fd leak in waiteventset

---

src/backend/gporca/data/dxl/minidump/UpdateDistKeyWithNestedJoin.mdp
src/backend/gporca/libgpopt/src/operators/CPhysicalSplit.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp

When deriving distribution spec for `CPhysicalSplit`, ORCA checks if its
disjoint with the hashed colrefs aswell as the equivalent hashed colrefs
(PdshashedEquiv()). For certain nested queries with a JOIN on the same
column, it is possible that the equivalent hashed colrefs also have
other equivalent hashed colrefs. ORCA did not consider such cases and
would skip recursively checking for hashed-equivalent colrefs and
include it to check if its disjoint with the colrefs being modified.
Thus generating a plan without a Redistribute on top of a Split node
when updating the distribution column. This would lead to wrong results.
This commit fixes the issue.
Co-authored-by: gpopt <103469259+gpopt@users.noreply.github.com>
(cherry picked from commit f47b262779de1d940e47e109be0aa483f4494957)

Fix missing Redistribute on top of Split Update with Orca

---

gpcontrib/Makefile
gpcontrib/ip4r/LICENSE
gpcontrib/ip4r/expected/ip4r-explain.out
gpcontrib/ip4r/expected/ip4r-explain_optimizer.out
gpcontrib/ip4r/sql/ip4r-explain.sql

This is a hotfix for the accident merge & push to master commit
17f17297c9. (#13418)
The following is the original commit message:
Add ip4r repository as a git subtree. Refer to gpcontrib/README on usage
of git subtree.
This extension add IPv4/v6 and IPv4/v6 range index type. Refer to
gpcontrib/ip4r/README.ip4r for more details.
Add testcase ip4r-explain.sql for index on these new types.
Co-authored-by: Chen Mulong <chenmulong@gmail.com>
Co-authored-by: Xuebin Su <sxuebin@vmware.com>
Co-authored-by: Sasasu <i@sasa.su>

Add extension ip4r as contrib extension

---

src/test/regress/expected/aggregates.out
src/test/regress/expected/aggregates_optimizer.out
src/test/regress/sql/aggregates.sql

Sometimes these prepared statements would be replanned and log ORCA
fallbacks, which are expected and ok. However, to make this more
deterministic, reset the plan cache in the test.
This uses the same approach as dee8ee04909f03e0aaa1e3def7c6fea4ab11778a.

Fix another flaky aggregates test

---

src/backend/commands/createas.c
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpec.h
src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

This addresses https://github.com/greenplum-db/gpdb/issues/13058
Previously, CPhysicalJoin derived the outer distribution when it was tainted
replicated. It checked only for strict replicated and universal replicated and
returned the inner distribution in these cases (in this case, it satisfies
random). Tainted replicated wasn't considered and was causing an undercount (the
JOIN derived tainted replicated instead of random, which was causing the number
of columns to be undercounted, because it wrongly assumed that one segment
contained all output columns).

Updated CPhysicalJoin to derive the inner distribution in the case of tainted replicated (6X)

---

src/backend/access/appendonly/appendonlywriter.c
src/test/isolation2/input/uao/max_concurrency2.source
src/test/isolation2/output/uao/max_concurrency2.source

When finding an available AO segment file to start writes, the
AppendOnlyHash entry's txns_using_rel is always incremented
immediately at the beginning. There were two ERROR locations during
this selection process where the transaction could exit but the
entry's txns_using_rel would not decrement back down. To fix the
issue, simply increment the AppendOnlyHash entry's txns_using_rel
after the two ERROR locations when the AO segment file has actually
been chosen instead of before.

Fix txns_using_rel leak in AppendOnlyHash entry

---

src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGetBase.cpp
src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApply.cpp

Prior to this commit, ORCA would calculate partition constraints
everytime (for DynamicGet) and use it only for partial scans later. As
the number of partitions grow, calculating these constraints would slow
down the query plan time. This commit speeds it up by computing
constraints only for partial scans and passing dummy constraints
otherwise.
This also adds an assertion which verifies that partition constraints (when
added after the partial index flag has been set) are valid. A similar assertion
exists inside of SetPartial, but running SetPartial before SetPartCnstr would
only check against the old partition constraints and not the new partition
constraints. This reverse-pattern exists in the codebase currently.
(cherry picked from commit 1849a2c8b2806a317e588bdf42aafe68763985ce)

Speed up planning times by marking some partition constraints as dummy constraints

---

src/backend/cdb/cdbutil.c
src/backend/cdb/cdbvars.c
src/backend/cdb/motion/ic_tcp.c
src/backend/cdb/motion/ic_udpifc.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/utils/sync_guc_name.h

790c7bac695 changed our address binding strategy to use a unicast
address (segment's gp_segment_configuration.address) instead of the
wildcard address, to reduce port usage on segment hosts and to ensure
that we don't inadvertently use a slower network interface for
interconnect traffic.
In some cases, inter-segment communication using the unicast address
mentioned above, may not be possible. One such example is if the source
segment's address field and the destination segment's address field are
on different subnets and/or existing routing rules don't allow for such
communication. In these cases, using a wildcard address for address
binding is the only available fallback, enabling the use of any
network interface compliant with routing rules.
Thus, this commit introduces the …

Support both unicast and wildcard address binding

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c

The PR resolves the following items:
- Resolve GPDB_12_MERGE_FIXME: Should we close the underlying AO fetch desc here ?
Unlike Heap, we don't release the fetch descriptor at index rescan
because the featch descriptor for AO/CO is more like a global data
structure shared across scans, rather than an iterator to yield a
granularity of data.
- Resolve GPDB_12_MERGE_FIXME: Is it possible for the 'snapshot' to change.
There should be identical snapshot between index fetching tuple
calls after fetch_init is called. Otherwise tuple's visibility
could be inconsistent in the same index scan.
- Fix a memory leak in index fetch tuple sub-routines on AO/CO.
index_fetch_begin() allocates IndexFetchTableData scan at the beginning
of the index fetching process, it should be freed in index_fetch_end().

Resolve GPDB_12_MERGE_FIXME on index fetch tuple routines for Append-Optimized table.

---

src/backend/storage/ipc/procarray.c
src/include/storage/procarray.h

As commit 7383c2b said, lazy vacuum for bitmap indexed tables performs
reindex causing updates to pg_class for index entries, ignoring lazy
vacuum will cause incorrect result. GPDB doesn't set PROC_IN_VACUUM flag
in lazy vacuum, exclude PROC_IN_VACUUM flag in procarray.c too.

Resolve GPDB_12_MERGE_FIXME: exclude PROC_IN_VACUUM flag in procarray.c

---

src/backend/cdb/dispatcher/cdbdisp_async.c

This is a back-port PR of #13567 from master branch.
A history commit ee255b55398818c6e6401668b540d2f45ff4c719 introduced a `PG_TRY()` / `PG_CATCH()` surrounding to `CHECK_FOR_INTERRUPTS`, which seems not necessary and may cause some trouble, according the discussions here:
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883190234
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883240823
- https://github.com/greenplum-db/gpdb/pull/13513#discussion_r883244949
So it's better to revert this change to avoid nested `TRY-CATCH` now.
What do you think? @maksm90 @soumyadeep2007 @interma

[6x backport] Revert PG_TRY() / PG_CATCH() surrounding of CFI.

---

src/backend/nodes/nodeFuncs.c
src/backend/optimizer/plan/subselect.c

1.remove fixme in subselect.c: the paramid in PartitionSelector and the
params in part_prune_info is used to do partition pruning on the other
side of the join, they won't affect the output of this plan node. And
the params in part_prune_info are also in join qual or join filter,
so they won't affect the join plan's extParam/allParam either.
2.add the support to walk prune infos.

Resolve GPDB_12_MERGE_FIXME in PartitionSelector to support walking prune info

---

src/backend/access/aocs/aocs_compaction.c
src/backend/access/appendonly/appendonly_compaction.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/access/heap/tuptoaster.c
src/include/access/appendonly_compaction.h
src/include/access/tuptoaster.h
src/include/executor/tuptable.h
src/test/regress/expected/toast.out
src/test/regress/sql/toast.sql

This PR contains the following changes:  
1. Resolves GPDB_12_MERGE_FIXME in  appendonly_compaction.c:
> GPDB_12_MERGE_FIXME: loop through all attributes, call `toast_delete_datum()`
> on any toasted datums, like `toast_delete` does for heap tuples.
2. Refactor `ExecFetchSlotMemTuple()`：
- Rename `ExecFetchSlotMemTuple()` to `appendonly_form_memtuple()` like `heap_from_tuple()`.
- Remove `shouldFree` parameter since it's always set as true.
- Add function `appendonly_free_memtuple()` to replace `free(memtuple)`.

fixme: delete toast values of invisible AppendOptimized tuple during vacuum.

---

src/backend/executor/execExpr.c

As Heikki said, we will constructing multi-DQA plans using the TupleSplit node for it. So in the 
function `ExecInitExprRec` we can ignore the HashJoin to combine multiple aggregations in
target list. Just delete the MERGE_FIXME in `execExpr.c`.
No more tests need, since `gp_dqa.sql` has corresponding tests. Like:
```
set enable_hashagg=on;
set enable_groupagg=off;
create table dqa_f1(a int, b int, c int) distributed by (a);
create table dqa_f2(x int, y int, z int) distributed by (x);
insert into dqa_f1 select i%17, i%5 , i%3 from generate_series(1,1000) i;
insert into dqa_f2 select i % 13, i % 5 , i % 11 from generate_series(1,1000) i;
postgres=# explain select sum(distinct a) filter (where a > 0), sum(distinct b) filter (where a > 0) from dqa_f1 group by c;
QUERY PLAN …
```

remove FIXME in execExpr.c:ExecInitExprRec

---

src/backend/executor/nodeAgg.c

It was noted while resolving PG 12 conflicts, then we re-enabled
serial/deserial functions and multi-phase aggregates on the merge
branch.
This MERGE_FIXME is unnecessary, remove it.
Co-authored-by: Wenlin Zhang <zwenlin@vmware.com>

Remove a unnecessary MERGE_FIXME of multi aggregate

---

src/backend/cdb/endpoint/cdbendpoint.c
src/backend/cdb/motion/ic_udpifc.c

We should print the error message associated with the errno populated by
the recv() call inside checkQDConnectionAlive() and dispatcherAYT().

Print errno for QE->QD dispatch checks

---

gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
gpdb-doc/markdown/admin_guide/roles_privs.html.md
gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ROLE.html.md
gpdb-doc/markdown/ref_guide/system_catalogs/pg_authid.html.md
gpdb-doc/markdown/security-guide/topics/Authenticate.html.md
gpdb-doc/markdown/security-guide/topics/Authorization.html.md

doc changes for https://github.com/greenplum-db/gpdb/pull/13286.  6X_STABLE.
in this PR (review site is behind the vpn):
- remove pgbouncer note about greenplum client not supporting scram-sha-256
- update the "managing roles and privileges" topic in the admin guide - rearrange topic, add scram-sha-256 info; doc review site link:  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-review/greenplum-database/GUID-admin_guide-roles_privs.html#protecting-passwords-in-greenplum-database
- add SCRAM-SHA-256 password_hash_algorithm guc value; doc review site link:  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-review/greenplum-database/GUID-ref_guide-config_params-guc-list.html#password_hash_algorithm
- update the CREATE ROLE topic; doc review site link: …

docs - updates for greenplum SCRAM-SHA-256 support

---

gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13369 (6X_STABLE).
the PR above introduces a new guc: gp_resource_group_enable_recalculate_query_mem.  in this PR:
- add reference info about this guc (default value: false)
- add new topic "About How Greenplum Database Allocates Transaction Memory" to the "using resource groups" doc page
(the default value of this new guc is true on the master branch; i'll submit a separate PR for those doc changes.)
- guc reference: https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-rgg/greenplum-database/GUID-ref_guide-config_params-guc-list.html#gp_resource_group_enable_recalculate_query_mem
- using resource group topic: https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-rgg/greenplum-database …

docs - new guc gp_resource_group_enable_recalculate_query_mem (6x)

---

gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13160 (master).
new guc gp_resource_group_enable_recalculate_query_mem.  in this PR:
- add reference info about this guc (default value: true)
- update the "using resource groups" topic

docs - new guc gp_resource_group_enable_recalculate_query_mem (master)

---

src/backend/cdb/endpoint/cdbendpoint.c
src/backend/cdb/motion/ic_udpifc.c

We should print the error message associated with the errno populated by
the recv() call inside checkQDConnectionAlive() and dispatcherAYT().
(cherry picked from commit 13902f8b335ca5085327da456532cc2dbeb57498)

6X: Print errno for QE->QD dispatch checks

---

src/backend/cdb/dispatcher/cdbgang.c
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

related GitHub issue: https://github.com/greenplum-db/gpdb/issues/13393
cdbdisp_destroyDispatcherState should not throw errors by design.
but there may be some errors in RecycleGang, details please refer to the GitHub issue,
some gangs are destroyed in cdbdisp_destroyDispatcherState, before the end of
cdbdisp_destroyDispatcherState some error is thrown, we call AbortTransaction to rollback this
transaction, and enter cdbdisp_destroyDispatcherState the second time, some segdbDesc of
the destroyed gang will be freed twice, or we may use some freed struct somewhere else.
all the two above situations may be due to panic.
we use HOLD_INTERRUPTS in RecycleGang to prevent an interrupt, so cdbdisp_destroyDispatcherState
can execute without interruption.

Fix master crash when there is an error during cdbdisp_destroyDispatcherState

---

src/backend/cdb/motion/ic_udpifc.c
src/include/cdb/cdbicudpfaultinjection.h

This modernizes and refactors the UDP IC socket setup code somewhat,
drawing inspiration from pgstat_init(), where similar UDP socket setup
is performed.
Significant changes:
* Prefer pg_getaddrinfo_all() to getaddrinfo().
* Consistently use guarded logging for address retries.
* Simplify interface for sizing UDP IC socket send/receive buffers.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/ic_modernize_v1

UDP interconnect: Modernize IC socket setup

---

gpdb-doc/markdown/install_guide/install_modules.html.md
gpdb-doc/markdown/ref_guide/modules/gp_percentile_agg.html.md
gpdb-doc/markdown/ref_guide/modules/intro.html.md
gpdb-doc/markdown/ref_guide/toc.md

docs for https://github.com/greenplum-db/gpdb/pull/13596 (6x).
in this PR:
- add docs for new gp_percentile_agg module/extension 
- misc updates to related content
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-review/greenplum-database/GUID-ref_guide-modules-gp_percentile_agg.html

docs - new gp_percentile_agg extension

---

src/test/unit/mock/mocker.py

The mocker.py uses all of `os.path.abspath`, `os.path.realpath` and
`os.path.relpath`. When we configure greenplum source using a soft
path, unit test will error out because file relative path returned
by mocker.py is wrong.
Maybe we can replace `os.path.abspath` with `os.path.realpath`
. However there are some special paths:
fe-auth.c -> ../../../src/interfaces/libpq/fe-auth.c
fe-exec.c -> ../../../src/interfaces/libpq/fe-exec.c
...
Use os.path.realpath(os.path.dirname(path) can gain the
correct path.

Fix possible wrong mocking path in mocker.py

---

src/backend/cdb/dispatcher/cdbgang.c
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

related GitHub issue: https://github.com/greenplum-db/gpdb/issues/13393
cdbdisp_destroyDispatcherState should not throw errors by design.
but it may be interrupted by a signal while RecycleGang, details please refer to the GitHub issue,
some gangs are destroyed in cdbdisp_destroyDispatcherState, before the end of
cdbdisp_destroyDispatcherState some error is thrown, we call AbortTransaction to rollback this
transaction, and enter cdbdisp_destroyDispatcherState the second time, some segdbDesc of
the destroyed gang will be freed twice, or we may use some freed struct somewhere else.
all the two above situations may be due to panic.
we use HOLD_INTERRUPTS in RecycleGang to prevent an interrupt, so cdbdisp_destroyDispatcherState
can execute without interruption.
cherry-picked from …

(6x backport) Fix master crash when there is an error during cdbdisp_destroyDispatherState

---

src/test/isolation2/expected/prevent_ao_wal.out
src/test/isolation2/expected/prevent_ao_wal_1.out
src/test/isolation2/sql/prevent_ao_wal.sql

The case prevent_ao_wal will check XLOG entries and before the
check it invokes VACUUM without table names so this vacuum will
operates on tables in the whole database. If previous cases leave
some Append Only Tables, then there might be more XLOG entries
to make the case failure.
This commit fixes the issue by adding table names in the case.

Make case prevent_ao_wal stable.

---

src/test/regress/expected/partition_prune.out
src/test/regress/expected/partition_prune_optimizer.out
src/test/regress/sql/partition_prune.sql

This file had a very weird mix of tests that did "set plan_cache_mode =
force_generic_plan" to get a generic plan, and tests that relied on
using five dummy executions of a prepared statement.  Converting them
all to rely on plan_cache_mode is more consistent and shaves off a
noticeable fraction of the test script's runtime.
Discussion: https://postgr.es/m/11952.1569536725@sss.pgh.pa.us
(cherry picked from commit d52eaa094847d395f942827a6f413904e516994c)
-----
This PR is to remove merge_fixme by cherry-pick upstream commit. Previously ORCA
will fallback to planner and can not use generic plan, so it do direct dispatch. However,
planner will choose generic plan so that can not do direct dispatch.

Rely on plan_cache_mode to force generic plans in partition_prune test.

---

src/backend/utils/mmgr/vmem_tracker.c

`ResGroupActivated = true` is set at the ending of InitPostgres()
by InitResManager(). If inside InitPostgres() some code before
InitResManager() call palloc() failed, then call trace:
gp_failed_to_alloc()
-> VmemTracker_GetAvailableVmemMB()
-> VmemTracker_GetNonNegativeAvailableVmemChunks
-> VmemTracker_GetVmemLimitChunks
It will trigger:
VmemTracker_GetVmemLimitChunks()
{
AssertImply(vmemTrackerInited && IsResGroupEnabled(),
IsResGroupActivated());
}
Like commit c1cdb99d does，remove the AssertImply and add TODO comment.

Fix assertion failure in InitPostgres when resgroup is on

---

src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect.sql

The select for update statement with locking clause is not easy to fully
supported in greenplum. The case, for update inside a CTE not toplevel
SQL, even with GDD enabled greenplum will still lock the table in Exclusive
Lock and not generate LockRows plan node. For detail, please refer to
checkCanOptSelectLockingClause.

Remove one merge_fixme in regress/subselect.

---

src/backend/cdb/cdbgroupingpaths.c

It is a long hard issue how to estimate hash table during creating path stage, and also the GUC `work_mem` is confirmed deprecated in GPDB. So we just remove this FIXME.

Remove one fixme in cdbgroupingpaths.c

---

src/test/isolation2/expected/prevent_ao_wal.out
src/test/isolation2/expected/prevent_ao_wal_1.out
src/test/isolation2/sql/prevent_ao_wal.sql

The case prevent_ao_wal will check XLOG entries and before the
check it invokes VACUUM without table names so this vacuum will
operates on tables in the whole database. If previous cases leave
some Append Only Tables, then there might be more XLOG entries
to make the case failure.
This commit fixes the issue by adding table names in the case.
(cherry-pick from bea1bfefe840b5c2e8c54544beefe07ca7ece320)

(6x backport) Make case prevent_ao_wal stable.

---

src/backend/executor/execParallel.c
src/backend/executor/nodeBitmapHeapscan.c
src/backend/optimizer/plan/createplan.c

Thanks for working with @haolinw, Greenplum will not support parallel scan recently, so we can change
all the FIXME about parallel StreamBitmap scan to TODO tag, since it bases on the parallel scan.
No more tests need, this PR just change comments.

remove parallel StreamBitmap scan FIXME

---

configure
gpAux/gpdemo/README

The configure default prefix is `/usr/local/gpdb`, and the top
README also use `/usr/local/gpdb` as the prefix, so there is
large chance that developer will use `/usr/local/gpdb` instead
of `/usr/local/greenplum_db`.
This change will eliminate the newcomers' confusion.
The patch also remove the duplicate init of `ac_default_prefix`

[README][typo] fix gpdemo path typo

---

src/test/isolation2/expected/checkpoint_memleak.out
src/test/isolation2/sql/checkpoint_memleak.sql

The test fails sometimes because it takes too long for the mirror to be promoted. E.g.:
```
2022-06-03 22:00:54.035647 ,"statement: SELECT pg_ctl(datadir, 'stop', 'immediate') FROM gp_segment_configuration WHERE role = 'p' AND content = 1;",,,,,,"SELECT pg_ctl(datadir, 'stop', 'immediate') FROM gp_segment_configuration WHERE role = 'p' AND content = 1;"
...
2022-06-03 22:00:59.077389 ,"segment is in reset/recovery mode (seg1 10.254.0.10:6006)",,,,,,"select count(*) from gp_toolkit.__gp_log_segment_ext where logsegment = 'seg1' and logtime > (select * from t_ckpt_memleak_test_timestamp) and logmessage like '[CheckpointMemoryLeakTest] Possible memory leak %';"
...
2022-06-03 22:01:12.016995 ,"failed to acquire resources on one or more segments","Segments are in reset/recovery …
```

[6X] Fix a flaky test checkpoint_memleak

---

src/test/regress/expected/workfile/hashagg_spill.out
src/test/regress/sql/workfile/hashagg_spill.sql

After merging PG12, we removed the hybrid hash table and don't have hhashtable and num_overflows.
Remove the useless functions and sql in hashagg_spill test.

Remove fixme in hashagg_spill test.

---

src/backend/executor/execMain.c
src/backend/parser/parse_clause.c
src/test/isolation2/expected/gdd/insert_root_partition_truncate_deadlock.out
src/test/isolation2/expected/insert_root_partition_truncate_deadlock_without_gdd.out
src/test/isolation2/expected/lockmodes.out
src/test/isolation2/expected/lockmodes_optimizer.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/gdd/insert_root_partition_truncate_deadlock.sql
src/test/isolation2/sql/insert_root_partition_truncate_deadlock_without_gdd.sql
src/test/isolation2/sql/lockmodes.sql
src/test/regress/expected/partition_locking.out
src/test/regress/expected/partition_locking_optimizer.out

Greenplum will lock relation on QD during parse-analyze stage and then
dispatch the plan to QEs to execute. Note the dispatch is async. For
insert statement on root, we cannot predict which leaf partitions will
be inserted. Thus, if we never lock leaf partitions on QD, this leads
to async dispatch to QEs, means, some of the session's QEs will
execute insert and hold locks, some of the session's QEs might be
blocked by other sessions. The problematical lock pattern in MPP
database  is: without locks on QD and first time hold lock is on QEs.
An global deadlock case is:
First, create a partition table
```sql
create table rank (id int, year int)
distributed randomly
partition by range (year)
(start (2006) end (2009) every (1));
```
Second, in a new session (named `sess1`)
```sql
set …
```

Lock leaf partitions for Insert Statement when GDD disabled.

---

src/test/perl/PostgresNode.pm

The test fails on some pipelines because there's a checkpoint WAL
being written after we write a new segment. So when the standby
is created from the same backup directory, it will complain about
not finding the checkpoint WAL, since we deleted it in the test.
It's flaky in some pipeline but not others because if the checkpoint
creation is slower than we killed the primary, we'll avoid the failure.
The reason which it writes the checkpoint WAL is because TAP test
set max_wal_size to 128 when creating the node. So the calculation
for how many segments to create checkpoint becomes:
(see CalculateCheckpointSegments)
```
floor(128 / 64 / 1.5) = 1
```
So basically it'll force a checkpoint for every new segment, which
is not good.
Also part of the reason is that GPDB has segment size = 64MB. In …

Fix a flakiness in recovery test overwrite_contrecord

---

src/backend/gpopt/translate/CTranslatorUtils.cpp

Found while rebasing Jesse's WIP refcount branch that is attempting to
remove manual refcounting.
NOTE: I didn't think of a good way to test this.  And since this is in gpopt I don't think a MDP testcase will work. Looking for thoughts/suggestions.

[ORCA] Fix memory leak in translator

---

src/backend/gpopt/translate/CTranslatorUtils.cpp

Found while rebasing Jesse's WIP refcount branch that is attempting to
remove manual refcounting.  Example demonstrating leak:
```
$ gpconfig -c optimizer_use_gpdb_allocators -v off --skipvalidation
$ gpstop -air
test=# CREATE TYPE myType as (a int, b int);
test=# CREATE OR REPLACE FUNCTION myFunc() RETURNS myType IMMUTABLE as $$ SELECT 1, 2 $$ LANGUAGE SQL;
test=# EXPLAIN SELECT * FROM myFunc();
```
(cherry picked from commit 6bbef9ec1228e4212e226a13804a2c5503a93403)

[ORCA] Fix memory leaks in translator (#13656)

---

gpAux/gpdemo/demo_cluster.sh

Here is the case:
If one gpdemo cluster with `PORT_BASE=7008` is running on the
machine, then a second gpdemo cluster with `PORT_BASE=7000`
runs `make check` will fail due to extra segment ports check.
It make no sense to check `4 * $NUM_PRIMARY_MIRROR_PAIRS` ports
since the needed segment ports are already list in
${DEMO_SEG_PORTS_LIST}, check only what we need.

[gpdemo] polish checkDemoConfig

---

src/backend/executor/nodeAgg.c
src/include/executor/nodeAgg.h
src/test/regress/expected/eagerfree.out
src/test/regress/expected/eagerfree_optimizer.out
src/test/regress/sql/eagerfree.sql

As the comment mentioned, for the test query from 'eagerfree' test, it will break before.
```
with my_group_sum(d, total) as (select d, sum(i) from smallt group by d)
select smallt2.* from smallt2
where 0 < all (select total from my_group_sum, smallt2 as tmp where my_group_sum.d = smallt2.d);
```
The query plan looks like
```
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1.50 rows=25 width=15)
->  Seq Scan on smallt2  (cost=0.00..1.17 rows=8 width=15)
Filter: (SubPlan 1)
SubPlan 1
->  Nested Loop  (cost=10000000003.67..10000000019.17 rows=1050 width=8)
->  Result  (cost=3.67..4.09 rows=21 width=12)
Filter: (smallt.d = smallt2.d)
->  HashAggregate …
```

Remove fixme in nodeAgg.c:ExecSquelchAgg.

---

gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh

Since LOG_MSG has a DISPLAY_TXT option, we should use it to
reduce introduction of new variable and remove duplicate
echo messages.

remove a superfluous variable

---

src/test/regress/expected/select_parallel.out
src/test/regress/expected/select_parallel_optimizer.out
src/test/regress/sql/select_parallel.sql

The issue mentioned in the fixme description has been resolved by [PR#10456](https://github.com/greenplum-db/gpdb/pull/10456).
Related information: [ISSUE#12916](https://github.com/greenplum-db/gpdb/issues/12916).

Remove a MERGE_FIXME from the test select_parallel

---

contrib/auto_explain/.gitignore
contrib/auto_explain/expected/auto_explain.out
contrib/auto_explain/expected/auto_explain_optimizer.out
src/backend/commands/explain.c
src/backend/utils/misc/guc.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/test/regress/expected/explain_format.out
src/test/regress/expected/explain_format_optimizer.out
src/test/regress/expected/fast_default.out
src/test/regress/expected/gp_explain.out
src/test/regress/expected/gp_explain_optimizer.out
src/test/regress/expected/insert_conflict.out
src/test/regress/expected/partition_prune_optimizer.out
src/test/regress/sql/explain_format.sql
src/test/regress/sql/fast_default.sql

Greenplum lists the planner GUCs and work_mem on the verbose mode,
Postgres lists the non-default GUCs if SETTINGS on.
This commit combines them into one section, and keeps the behaviors.
Co-authored-by: Jian Guo <gjian@vmware.com>

Combine Greenplum and Postgres's EXPLAIN SETTINGS

---

gpMgmt/bin/gpinitsystem
gpMgmt/doc/gpinitsystem_help

In gpinitsystem USAGE, the recommended `gpinitsystem_INSTRUCTIONS`
file cannot be found in the codebase and the internet, so I guess
this should be the gpinitsystem_help, which was referenced by
$HELP_DOC_NAME variable.

[doc] fix some gpinitsystem usage and doc mismatch

---

src/backend/utils/mmgr/vmem_tracker.c

This is the backport of #13643
`ResGroupActivated = true` is set at the ending of InitPostgres()
by InitResManager(). If inside InitPostgres() some code before
InitResManager() call palloc() failed, then call trace:
gp_failed_to_alloc()
-> VmemTracker_GetAvailableVmemMB()
-> VmemTracker_GetNonNegativeAvailableVmemChunks
-> VmemTracker_GetVmemLimitChunks
It will trigger:
``` 
VmemTracker_GetVmemLimitChunks()
{
AssertImply(vmemTrackerInited && IsResGroupEnabled(),
IsResGroupActivated());
}  
```
Like commit c1cdb99d does, remove the AssertImply and add 
TODO comment.

[6X] Fix assertion failure in InitPostgres when resgroup is on (#13643)

---

src/backend/tcop/postgres.c
src/include/miscadmin.h

```
postgres.c:6080:1: warning: no previous prototype for 'CancelRequested' [-Wmissing-prototypes]
CancelRequested() {
^
```

resolve compiler warning

---

src/backend/cdb/cdbgroupingpaths.c
src/backend/optimizer/plan/planner.c
src/backend/optimizer/util/pathnode.c
src/include/optimizer/pathnode.h

1. the last param of create_groupingsets_path is not used, so remove it.
2. remove useless codes, the last param is removed in create_groupingsets_path, 
so there is no need to calculate dNumGroups before create_groupingsets_path.
3. the last param of consider_groupingsets_paths should be dNumGroupsTotal. 
in consider_groupingsets_paths it will calculate dNumGroups in one segment.

fix fixme in planner about calculating dNumGroups for grouping sets

---

gpMgmt/bin/gppylib/operations/package.py

old (and current) gppkg create the package like this format:
```
PostInstall:
- Master:  "sh ./master.sh"
- Segment: "sh ./segment.sh';"
- All:     "echo 'install successful'"
```
sed -i s/master/coordinator/g will break this behavior.
#11365

Fix gppkg's coordinator hook not execute.

---

src/backend/utils/adt/lockfuncs.c
src/test/regress/expected/gp_lock.out
src/test/regress/sql/gp_lock.sql

A bug exists in pg_lock_status() which resulted in wrong view in pg_locks. E.g.:
```
postgres=# CREATE TABLE gp_lock_test (a int);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# begin;
BEGIN
postgres=# LOCK TABLE gp_lock_test IN ACCESS SHARE MODE;
LOCK TABLE
postgres=# SELECT l.gp_segment_id, c.relname, l.mode, l.granted
FROM pg_locks l, pg_class c WHERE l.relation = c.oid and c.relname = 'gp_lock_test';
gp_segment_id |   relname    |      mode       | granted
---------------+--------------+-----------------+--------- …
```

[6X] Backporting "Fix the logic in pg_lock_status() to keep track of which row to return."

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature

Issue: when one or more cluster is down or not in their preferred role, the assignment of port on expanded nodes are going wrong. the reason behind that the calculation of port using function get_max_primary_port() and get_max_mirror_port(). 
one of the suggested fix is to check if clusters are in good state as soon as we run gpexpand. this will also avoid any further issues which can be cause due to nodes are not in their preferred role. 
Added feature test for bot the scenario when either of node is down or they are not in preferred role.

added cluster health check for gpexpand

---

src/backend/cdb/cdbdistributedsnapshot.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
src/test/isolation2/sql/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.sql

We have had recent reports of: "ERROR: maximum length exceeded" in
EndPrepare().
This was encountered at the segment level when running VACUUM FULL on a
thoroughly bloated system catalog table. This arose due to the sheer
number of tuples being moved in move_plain_tuple(). Around ~26M tuples
were being moved in each segment, and since each move generates 2*32 =
64bytes of cache inval messages, the 2PC record data grew to be 1.6G,
well over MaxAllocSize(1G).
As a workaround to users, we want to provide a way to vacuum the tables
in utility mode to avoid 2PC altogether. Currently all tuples are
considered live for the purposes of utility mode vacuum. We end up
hitting:
```c
/*
* If don't have distributed snapshot to check, return it can be seen and
* hence not to be cleaned-up.
*/
return …
```

[5X] GUC: Bypass dtx visibility checks for tuples

---

gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.control
src/backend/commands/extension.c
src/test/regress/expected/create_extension_fail.out
src/test/regress/sql/create_extension_fail.sql

This commit fixes https://github.com/greenplum-db/gpdb/issues/6716.
In postgres, CREATE EXTENSION WITH SCHEMA will set up the `search_path`
to contain the target schema and required schemas before execute extension
script. Because the commands of the extension script will be dispatched to
QE, GPDB needs to set up the `search_path` on both QD and QE.
NOTE: `search_path` will be reset during transaction commit.

Set the search_path correctly when CREATE EXTENSION WITH SCHEMA

---

doc/src/sgml/ref/alter_table.sgml
src/backend/catalog/pg_appendonly.c
src/backend/commands/cluster.c
src/backend/commands/matview.c
src/backend/commands/tablecmds.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/parser/gram.y
src/bin/psql/tab-complete.c
src/include/catalog/pg_appendonly.h
src/include/commands/cluster.h
src/include/commands/event_trigger.h
src/include/nodes/altertablenodes.h
src/include/nodes/parsenodes.h
src/test/regress/expected/alter_distribution_policy.out
src/test/regress/expected/alter_table_set_am.out
src/test/regress/expected/create_am.out
src/test/regress/expected/create_am_optimizer.out
src/test/regress/greenplum_schedule
src/test/regress/sql/alter_distribution_policy.sql
src/test/regress/sql/alter_table_set_am.sql
src/test/regress/sql/create_am.sql

This PR is a combination of following changes:
Add support for SET ACCESS METHOD in ALTER TABLE - This is a backport of a PG15 commit, motivating the feature to swap in between heap, AO and AOCS tables.
Add support for changing access method from heap to AO.
This change includes creating the catalog entries for AO tables, and AO auxiliary tables, and supporting the `AT SET ACCESS METHOD ao_row;` for heap tables.
Add support for AT SET WITH() syntax to change access method

Add support for changing ACCESS METHOD from heap to AO

---

gpdb-doc/markdown/install_guide/prep_os.html.md

a subtopic in the "configuring your system" section of the install guide that discusses the networking MTU setting.
question:  is this enough info, or do we need to specify the actual commands to set the MTU?  will need someone to provide the commands if required.

docs - add some networking MTU config recommendations to install guide

---

gpdb-doc/markdown/analytics/postGIS.html.md

geos library updated to version 3.10.2.  also noticed in https://github.com/greenplum-db/geospatial/blob/master/postgis/Makefile.version that the expat dependency was also updated.

docs - update postgis dependency versions; remove limitation

---

src/backend/utils/resgroup/resgroup_helper.c

There is a meaningless line in resgroup_helper.c

removed meaningless code line in resgroup_helper.c

---

src/backend/optimizer/path/allpaths.c
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect.sql

1. use replicated table to generate a plan like this:
Limit -> Subquery -> Sort. And insert more values into sq_limit to
make the sort use a top-N sort method.
2. prevent inlining happens if exists volatile function in CTE.

Resolve GPDB_12_MERGE_FIXME in subselect.sql

---

src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
src/test/isolation2/sql/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.sql

This is a follow-up to commit b1da07beba0.
With ORCA, since updates are converted to deletes and inserts in a
manner where the heap AM's update implementation is not used, we end up
with a diff in the number of tuples that could be HOT pruned (pruned
during the newly added delete after the 2 update statements):
```
*** ./expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out	2022-06-23 20:43:50.048535147 +0000
--- ./results/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out	2022-06-23 20:43:50.052535542 +0000
***************
*** 52,58 ****
2U: select count(*) from test_recently_dead_utility;
count
-----
! 1000
(1 row)
2U: set gp_select_invisible=0;
SET
--- 52,58 ----
2U: select count(*) from test_recently_dead_utility;
count
-----
! 1280
(1 row)
2U: set …
```

[5X]: Fix vacuum full utility mode test

---

gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.control
src/backend/commands/extension.c
src/test/regress/expected/create_extension_fail.out
src/test/regress/sql/create_extension_fail.sql

This commit fixes https://github.com/greenplum-db/gpdb/issues/6716.
In postgres, CREATE EXTENSION WITH SCHEMA will set up the `search_path`
to contain the target schema and required schemas before execute extension
script. Because the commands of the extension script will be dispatched to
QE, GPDB needs to set up the `search_path` on both QD and QE.
NOTE: `search_path` will be reset during transaction commit.

[6X_STABLE] Set the search_path correctly when CREATE EXTENSION WITH SCHEMA.

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature

Reverts greenplum-db/gpdb#13695
While backporting to 6x found some issue when we rerun gpexpand in rollback and other scenario. 
reverting to make a fresh fixed pr.

Revert "added cluster health check for gpexpand"

---

README.macOS.md

`README.macOS.bash` doesn't write to ` ~/.bash_profile` but ` ~/.bashrc`, 
so this instruction results `No such file or directory` error on a new mac environment.
Step 2 write to ` ~/.bash_profile` and sourced the `~/.bashrc`. so just remove it here.
v2
After discussed with @SmartKeyerror, we decided to change
`source ~/.bash_profile` to `source ~/.bashrc`, which guarantees
not missing source configuration files.

[doc] remove useless instruction

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature

Issue: when one or more cluster is down or not in their preferred role, the assignment of port on expanded nodes are going wrong. the reason behind that the calculation of port using function get_max_primary_port() and get_max_mirror_port().
one of the suggested fix is to check if clusters are in good state as soon as we run gpexpand. this will also avoid any further issues which can be cause due to nodes are not in their preferred role.
Added feature test for bot the scenario when either of node is down or they are not in preferred role.

added cluster health check for gpexpand updated

---

src/backend/access/heap/tuptoaster.c
src/test/regress/expected/toast.out
src/test/regress/sql/toast.sql

This is a fix for issue https://github.com/greenplum-db/gpdb/issues/13659
------------------------
In commit a0684da5f14f we made a change to use the fixed TOAST_TUPLE_TARGET
instead of the AO table's toast_tuple_target that's calculated based on its
custom blocksize, when toasting AO table tuples.
This caused an issue that some tuples that are well beyond the
toast_tuple_target are not being toasted (because they're smaller than
TOAST_TUPLE_TARGET). This is ok when the tuples can still fit into the
AO table's blocksize. But if not, an error would occur. E.g.:
```
postgres=# create table t (a int, b int[]) WITH (appendonly=true, blocksize=8192);
CREATE TABLE
postgres=# insert into t select 1, array_agg(x) from generate_series(1, 2030) x;
ERROR:  item too long (check #1): length 8160, …
```

Toasting for AO tables should still use custom toast_tuple_target

---

src/backend/access/rmgrdesc/xlogdesc.c
src/backend/access/transam/xlog.c
src/backend/access/transam/xlogreader.c
src/backend/replication/logical/decode.c
src/include/access/xlog_internal.h
src/include/access/xlogreader.h
src/include/catalog/pg_control.h
src/test/perl/PostgresNode.pm
src/test/recovery/t/026_overwrite_contrecord.pl
src/tools/pgindent/typedefs.list

Backport from upstream commit 148c6ee3be39be61968d580eaafc93795aed1f0c
The corresponding 7X PR for GPDB is https://github.com/greenplum-db/gpdb/pull/13648
GPDB related message
====================
We saw similar issue in GPDB where an incomplete cross-segment WAL
record can cause the mirror to try to stream from the next segment,
whereas the primary has a flush point somewhere at the end of the
previous segment. So the primary saw:
requested starting point D81/54000000 is ahead of the WAL flush position of this server D81/53FF7FE8
In fact, the test scenario in this commit (026_overwrite_contrecord.pl)
would produce the above error w/o the fix, instead of the one mentioned
in the upstream commit message, at least for GPDB.
But the main difference is just whether the primary has written & …

[6X] Fix issue caused by primary restart after streamed an incomplete cross-segment WAL

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

This adds a GUC `optimizer_enable_replicated_table`, which defaults any DML
operation on a replicated table to fall back to Postgres planner.
`optimizer_enable_replicated_table` is on by default.

Add an Orca GUC to control fallback for replicated table

---

gpMgmt/bin/gpactivatestandby

Since commit e7010c "pg_ctl: Add wait option to promote action" have
option -t to wait for required number of secs for promotion. Hence,
deleting the retry loop with dbconn.execSQL() logic to check for
promotion completion via connection acceptance.
Using -t option with 10 mins as timeout to align the value with
MIRROR_PROMOTION_TIMEOUT used in other part of codebase. Having
consistent timeout value for same operation is helpful.

Use pg_ctl -t secs option for promote in gpactivatestandby

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/access/heap/heapam_handler.c
src/backend/access/rmgrdesc/smgrdesc.c
src/backend/catalog/storage.c
src/backend/commands/tablecmds.c
src/backend/storage/smgr/smgr.c
src/include/catalog/storage_xlog.h

>  GPDB_12_MERGE_FIXME: SMGR WAL record does not have a way to
>  identify a specific SMGR implementation.  If the SMGR
>  implementation that the caller expects does not match the
>  implementation we already have in the hash table, it is most likely
>  due to calling smgropen when replaying a SMGR WAL record.  Fix the
>  expectation as a workaround for now.  A proper fix should include
>  the implementation identifier (smgr_which) in the SMGR WAL record.
This commit appended the implementation identifier into the SMGR WAL record.
pg_waldump:
```
rmgr: Storage     len (rec/tot):     46/    46, tx:          0, lsn: 0/04FDF640, prev 0/04FDF620, desc: CREATE base/13379/16384; smgr: ao
rmgr: Storage     len (rec/tot):     46/    46, tx:          0, lsn: 0/050426C8, prev 0/05042690, desc: …
```

Include the implementation identifier in the SMGR WAL record

---

src/backend/parser/parse_partition_gp.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

When we create a temporary table, we can use `ON COMMIT` to control the behavior 
of temporary tables at the end of a transaction block, such as `DELETE ROWS`, means
delete all rows in this temporary table after this transaction is committed.
But when used on a partitioned table, this is not cascaded to its partitions, so we can just
use `ONCOMMIT_NOOP` (default behavior) when we create child partition tables.
And If we use the parent on commit action, it will lead to inconsistent behavior between 
Greenplum and PostgreSQL, which we need to avoid.

Just use default on commit behavior to child tables when we create partition table

---

src/backend/tcop/postgres.c
src/backend/utils/time/sharedsnapshot.c
src/test/isolation2/expected/write_gang_idle_in_transaction_session_timeout.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/write_gang_idle_in_transaction_session_timeout.sql

When a query spawn a write gang and multiple read gangs on segment
and idle_in_transaction_session_timeout was set to a non-zero
value, in this case, if a read gang is still in progress, but the
write gang has done its execution, some unexpected errors may be
caused due to the early termination of the write gang.
In this fix, idle_in_transaction_session_timeout is disabled on QE.

Fix idle_in_transaction_session_timeout works on QE

---

src/backend/catalog/pg_appendonly.c
src/backend/commands/cluster.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

Reference:
* Heap to AO: https://github.com/greenplum-db/gpdb/pull/13571
* Comments about the general WF of ATAM from/to AO/AOCO tables: https://github.com/greenplum-db/gpdb/pull/13744
-------------
Main considerations of changes:
* Dropping pg_appendonly entries and AO aux tables:
* We rely on the existing AT framework to drop those since it needs to cleanup the intermediate temporary table in the end. The only thing we need to do is to transfer the AO entry for the original AO table to the temporary heap table and also link the AO aux table dependencies to it too. 
* So, we can reuse the existing `ATAOEntriesHeapToAO()` function but rename it accordingly.
* Added more comment for `ATAOEntries` too.
* Reloptions from the old AO are not applicable to new heap table, discard them
* The new …

Support for changing ACCESS METHOD from AO to heap

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

greenplum-db/gpdb-postgres-merge@98154a8f6c47fc6007638ffe84e7ae8999b19f2a and
a8bb542fb8de88682bbfb18de0dbab0200674307 started a small refactoring, which
pointed that we have a lot of `NULL != target_list` asserts to be appropriately
replaced. There is a new case which cause SIGSEGV on builds without asserts -
empty target list in CTE producer. From now, we fallback to Postgres optimizer
in such case.
Cherry-picked from 0707124380bd4bd87851702cd53dc32509b728da.

[6X] Fallback to Postgres optimizer on empty target list in CTE producer

---

src/backend/executor/execMain.c

According to a reported error in PolicyEagerFreeAssignOperatorMemoryKB makes query end without calling mppExecutorCleanup https://github.com/greenplum-db/gpdb/issues/12690 , the code path in standard_ExecutorStart didn't handle exception in PolicyAutoAssignOperatorMemoryKB and PolicyEagerFreeAssignOperatorMemoryKB calling, which may cause the OOM exception not handled in standard_ExecutorStart but throw to upper PortalStart methods, while there is also exception handling machanism in PortalStart but mppExecutorCleanup will not call because of portal->queryDesc will be NULL in certain transation states. This PR fixed this issue.
This is a backport of PR #12694 to 6x branch.

[6x backport] Handling exception to call mppExecutorCleanup in standard_ExecutorStart

---

src/backend/optimizer/prep/prepunion.c
src/test/regress/expected/partition_subquery.out
src/test/regress/expected/partition_subquery_optimizer.out
src/test/regress/sql/partition_subquery.sql

This problem occurs with Postgres Query Optimizer only, ORCA is not affected.
If we have a partitioned table and a nested correlated subquery, we can face an error 
that would say something like that:
```
FATAL:  Unexpected internal error (list.c:395)
DETAIL:  FailedAssertion("!(n < list->length)", File: "list.c", Line: 395)
```
In a case when a query has a partitioned table and InitPlan can't be created, 
GPDB will make copies of first level subplans by number of partitions, and
all more nested subplans will be added later. But all more nested subplans copies 
will be added in a wrong order and that they will go in a flat plan list after thier 
parent nodes, what will lead to a crash. 
```
create table t1 (a int) partition by range (a) (start (1) end (3) every (1));
create table t2 (b …
```

(6x only) Wrong subplans order in correlated subquery

---

src/backend/commands/copy.c
src/backend/executor/execMain.c
src/test/isolation2/expected/copy_insert_utility_mode_hierarchies.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/copy_insert_utility_mode_hierarchies.sql

Ban utility mode COPY/INSERT on partition/inh roots
For advanced parallel data loading use cases w/ COPY (such as one recent
use case in gprestore on different sized clusters), one may be tempted to
load the data parallely with COPY FROM over utility mode connections.
(Even though COPY FROM .. ON SEGMENT exists, one may not have a segment
specific data file etc)
Allowing the above leads to a bug where the data gets loaded directly
into the partition root (and does not flow into the respective partiton
leaves), causing wrong results and mayhem.
Unfortunately, since only the master carries partitioning related
catalogs (pg_partition, pg_partition_rule), it is impossible to obtain
partiioning info in utility mode on the segments. Note that this
info is usually dispatched from the master. …

6X: Ban utility mode COPY/INSERT on partition/inh roots

---

src/backend/catalog/toasting.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_upgrade/info.c

Since columnar tables in GPDB7 do not have toast tables, trying to set
the toast OID confuses pg_upgrade. Have pg_dump omit those values to
avoid the problem.
This fix is on same lines as upstream commit 203749a "pg_upgrade: Ignore TOAST for partitioned tables". Reverting my previous commit made in server to fix this problem as no more needed.

pg_upgrade: Ignore TOAST for columnar tables

---

src/backend/commands/explain.c
src/backend/commands/explain_gp.c
src/test/regress/data/.gitignore
src/test/regress/expected/explain_format.out
src/test/regress/expected/explain_format_optimizer.out
src/test/regress/sql/explain_format.sql

NodeSummary's sort statistics were incorrectly updated, some exact same
processes were called twice due to the merge mistake.
FYI, the reason for making mistakes is Greenplum 6 does the statistics
for memory sort and disk sort separately, but now we don't.
Co-authored-by: Hongxu Ma <interma@outlook.com>
Fixes #13767

Fix sort node statistics in EXPLAIN (ANALYZE, VERBOSE)

---

src/include/executor/instrument.h
src/include/storage/sync.h

This pr contains the following changes:
- Remove GPDB_12_MERGE_FIXME in instrument.h
`ntuples` was changed in https://github.com/greenplum-db/gpdb/pull/4317/commits/c3a9ed28aad53951d9eca162c0eae14414c7f036 for performance reason. It's not necessary to do the same for `ntuples2`, so just remove GPDB_12_MERGE_FIXME flag and align with upstream.
- Resolve GPDB_12_MERGE_FXIME in sync.h
We no longer need "is the AO table" flag in struct `FileTag` since upstream introduced a new function table `SyncOps syncsw[]` for sync handlers in https://github.com/postgres/postgres/commit/3eb77eba5a51780d5cf52cd66a9844cd4d26feb0. The difference of handling sync and unlink requests of ao and heap is hidden by the SyncOps api.

Resolve GPDB_12_MERGE_FIXME in sync.h and instrument.h

---

gpAux/gpdemo/demo_cluster.sh

`clusterConfigPostgresAddonsFile` should be removed when destruting
the cluster.

[gpdemo] delete clusterConfigPostgresAddonsFile when clean demo

---

src/backend/cdb/dispatcher/cdbgang_async.c
src/backend/executor/nodeHashjoin.c
src/backend/executor/nodeShareInputScan.c

Use PG_USED_FOR_ASSERTS_ONLY to supress unused variable warnings for
assert only variables. Plus guard isNotDistinctJoin under
USE_ASSERT_CHECKING.

Fix compiler warnings for non-assert builds

---

contrib/hstore_plperl/Makefile
contrib/hstore_plperl/expected/create_transform.out
contrib/hstore_plperl/init_file
contrib/hstore_plperl/sql/create_transform.sql
src/backend/commands/functioncmds.c

Fix issue #13611 , see it for more details.
The issue also exists in 6x and 5x.
Exec `CREATE OR REPLACE TRANSFORM` twice will fail in gpdb.
catalog `pg_stat_last_operation` with unique index
`pg_statlastop_classid_objid_staactionname_index` will collect metadata
tracking information about operations on database objects.
When exec `CREATE OR REPLACE TRANSFORM` the previous objid's record is
only added but not updated. And the unique index reports a
duplicate key error.
Another similar issue is that a transform is dropped, the record in
`pg_stat_last_operation` still exists. It should be dropped too.
Update the transform's `pg_stat_last_operation` record if exists.
Drop the transform's `pg_stat_last_operation` record when dropping a
transform. This pr fix it too.
The test cases are already …

Fix the issue CREATE OR REPLACE TRANSFORM failed

---

configure
configure.in

Since `blocksize` & `wal_blocksize` are default to 32 in greenplum,
the configure **--help message** should refect that.

[doc] fix configure help display mismatch

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/nodes/readfuncs.c

Fixes a couple compiler warnings introduced in https://github.com/greenplum-db/gpdb/pull/13551

Fix compiler warnings from Dynamic Scan commit

---

src/common/hashfn.c

The commit https://github.com/greenplum-db/gpdb/commit/ab12230fa11574bf2e7470242489864fe8a63c1b
added some WIN32 ifdefs to fix fe-connect compilation errors.
The commit https://github.com/greenplum-db/gpdb/commit/5d3dc2e81f272396281eddc082bd998ab96fd0da
allows hashfn.c to be compiled into both frontend and backend code but
broke the win32 clients compilation with
```
src\include\utils\elog.h(86): fatal error C1083: Cannot open include
file: 'pthread-win32.h': No such file or directory (compiling source file src/common/hashfn.c)
```
We carry a dependency on pthread_win32.h in elog.h, which causes
compilation errors when building Windows clients (as elog.h is included by
postgres.h). So use postgres-fe.h instead for this case.
Also add windows client tests to pipeline.

Fix windows clients compilation of libpgcommon

---

src/bin/initdb/initdb.c
src/bin/pg_basebackup/pg_basebackup.c

This seems like a omission when mergeing upstream postgresql 12,
some `fprintf` are changed to `pg_log_error`, every change removed
the ending `\n` except here.
This patch fixed issue #13700

[initdb] remove ending \n from pg_log_error

---

src/backend/utils/mmgr/aset.c

As AllocSetTransferAccounting() was called during MemoryContextSetParent().
Before update the memory accouting info, it asserts MemoryContextIsValid(),
which includes AllocSetContext, SlabContext and GenerationContext.
Currently, there is no mixed context situation and other context doesn't have
the accounting info, so I think it's ok to remove the comment.

Remove fixme comment in aset.c:AllocSetTransferAccounting.

---

contrib/auto_explain/expected/auto_explain_optimizer.out
contrib/btree_gin/expected/name_optimizer.out
src/backend/optimizer/util/walkers.c
src/test/regress/expected/aggregates_optimizer.out
src/test/regress/expected/autostats.out
src/test/regress/expected/bfv_index_optimizer.out
src/test/regress/expected/brin_ao_optimizer.out
src/test/regress/expected/brin_aocs_optimizer.out
src/test/regress/expected/brin_optimizer.out
src/test/regress/expected/gp_array_agg_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/join_optimizer.out
src/test/regress/expected/portals_optimizer.out
src/test/regress/expected/select.out
src/test/regress/expected/select_optimizer.out
src/test/regress/expected/select_parallel_optimizer.out
src/test/regress/sql/autostats.sql
src/test/regress/sql/select.sql

For type NAMEOID, the default collation is C. Make sure various nodetypes are
aware of it.  Earlier only VAR node type took care of it. Extend it CONST and
OPEXPR.
A note about test case change in `select` ICG test. The test cases are supposed
to test for index scan on partial indexes. Earlier ORCA would fall back to
planner. After this fix, ORCA started to give sequential scan which was flaky
with explain analyze. So just like planner, we have turned off tablescan for
these tests. They are falling back to Planner for now.

Fix non-default collation fallbacks

---

src/backend/cdb/cdbhash.c
src/backend/libpq/hba.c

1. remove fixme in cdbhash.c: this is only used in internal to compute
the hash key value, they all use the same collation with default collation,
so it will get same result with the same value, it's ok here.
2. remove fixme in hba.c: ldapserver is used to set Names or IP addresses
of LDAP servers to connect to, the 'ldaps://' is set by ldapurl value now.

Resove GPDB_12_MERGE_FIXME in some misc files

---

src/include/utils/sync_guc_name.h

The GUC replacement_sort_tuples was introduced in GP 9.6 to indicate the threshold to use replacement selection rather than quicksort. See the doc:
https://www.postgresql.org/docs/9.6/runtime-config-resource.html#GUC-REPLACEMENT-SORT-TUPLES
In PG12, the GUC was removed with all code related to replacement selection sort, and doesn't appear in GPDB7. However, in GPDB7 there is still one line about replacement_sort_tuples in sync_guc_name.h (without any other related code). It should be treated as a mistake.
The fix is to simply move the line and doesn't impact any existing behavior.

Remove one line about replacement_sort_tuples

---

src/backend/cdb/cdbappendonlystorageread.c

Currently with debug_appendonly_print_read_block set, we can run into
ths assertion failure as AppendOnlyStorageRead->segmentFileName isn't
populated until AppendOnlyStorageRead_FinishOpenFile() is called.
Unexpected internal error (assert.c:44)",
"FailedAssertion(""!(strvalue != ((void *)0))"
1    0x558983f311ea postgres errstart + 0x3cb
2    0x558983f2fe48 postgres ExceptionalCondition + 0x91
3    0x55898404fde1 postgres <symbol not found> + 0x8404fde1
4    0x55898404f5f6 postgres pg_vsnprintf + 0x8f
5    0x55898405b412 postgres pvsnprintf + 0x34
6    0x55898405cf47 postgres appendStringInfoVA + 0x8a
7    0x558983f32112 postgres errmsg_internal + 0x192
8    0x55898400f72a postgres <symbol not found> + 0x8400f72a
9    0x55898400fa5e postgres AppendOnlyStorageRead_TryOpenFile + 0xa7
... …

AO read: Avoid use-before-assignment in debug print

---

src/backend/utils/misc/guc_gp.c
src/backend/utils/mmgr/redzone_handler.c
src/backend/utils/mmgr/test/redzone_handler_test.c

When we set `runaway_detector_activation_percent` to 100 means to disable runaway detection,
this should apply to Vmem Tracker and Resource Group. 
However, in current implementation, we will still invoke `IsGroupInRedZone()` if we enabled resource
group if we set `runaway_detector_activation_percent` to 0 or 100. And in function `IsGroupInRedZone()`
has some automatic operation to read variables. At the same time `RedZoneHandler_IsVmemRedZone` 
is a very frequently called function, so this will waste a lot of CPU resources.
When we init Red-Zone Handler, will set `redZoneChunks` to `INT32_MAX` if we disable runaway
detection, so we can use it to judge whether we are in Red-Zone or not quickly.
No more tests need, since current unit tests already have cases covering this situation. …

skip red-zone check in some situations

---

contrib/pg_upgrade/check.c
contrib/pg_upgrade/controldata.c
contrib/pg_upgrade/greenplum/controldata_gp.c
contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h
contrib/pg_upgrade/pg_upgrade.c
contrib/pg_upgrade/pg_upgrade.h
src/bin/pg_resetxlog/pg_resetxlog.c

We recently ran into a pg_clog truncation issue when gpupgrade was trying to upgrade segments.
```
-- In source cluster:
createdb test
psql test
CREATE TABLE foo(i int);
-- Insert some tuples in a segment that will refer to the current clog file
INSERT INTO foo SELECT 1 FROM generate_series(1, 5);
gpconfig -c debug_burn_xids -v on --skipvalidation
gpstop -au
echo "INSERT INTO foo VALUES(1);" > /tmp/clog_preservation.sql
pgbench -n -f /tmp/clog_preservation.sql -c 8 -t 512 test
gpupgrade initialize --source-gphome /usr/local/gpdb5 --target-gphome /usr/local/gpdb6 --source-master-port 15432 --disk-free-ratio 0 --verbose --skip-version-check
gpupgrade execute
-- Connect to the target cluster
SELECT count(*) FROM foo;
ERROR:  could not access status of transaction 693  (seg0 slice1 …
```

[6X] Fix inadvertent CLOG truncation during segment upgrade

---

src/backend/cdb/cdbappendonlystorageread.c

This is a backport of master commit:
f598bbae79f0b60c6d4512c737976084b690703e
Currently with debug_appendonly_print_read_block set, we can run into
ths assertion failure as AppendOnlyStorageRead->segmentFileName isn't
populated until AppendOnlyStorageRead_FinishOpenFile() is called.
Unexpected internal error (assert.c:44)",
"FailedAssertion(""!(strvalue != ((void *)0))"
1    0x558983f311ea postgres errstart + 0x3cb
2    0x558983f2fe48 postgres ExceptionalCondition + 0x91
3    0x55898404fde1 postgres <symbol not found> + 0x8404fde1
4    0x55898404f5f6 postgres pg_vsnprintf + 0x8f
5    0x55898405b412 postgres pvsnprintf + 0x34
6    0x55898405cf47 postgres appendStringInfoVA + 0x8a
7    0x558983f32112 postgres errmsg_internal + 0x192
8    0x55898400f72a postgres <symbol not found> + …

[6X]  AO read: Avoid use-before-assignment in debug print

---

doc/src/sgml/ref/pg_resetwal.sgml
src/bin/pg_resetwal/pg_resetwal.c
src/bin/pg_upgrade/controldata.c
src/bin/pg_upgrade/pg_upgrade.c
src/bin/pg_upgrade/pg_upgrade.h

This cherry-picks recent REL12_STABLE commit:
7626e9f2be7d0fc9b20936910831b900b555728b
Technically, we could have absorbed this later, but since we are going
to be making the change for 6X and we uncovered valuable context about
5X->7X upgrades wrt old_cluster.controldata.chkpnt_oldstxid, we have
done the backport.
Add pg_resetxlog -u option to set the oldest xid in pg_control.
Previously -x set this value be -2 billion less than the -x value.
However, this causes the server to immediately scan all relation's
relfrozenxid so it can advance pg_control's oldest xid to be inside the
autovacuum_freeze_max_age range, which is inefficient and might disrupt
diagnostic recovery.  pg_upgrade will use this option to better create
the new cluster to match the old …

pg_resetxlog:  add option to set oldest xid & use by pg_upgrade

---

contrib/pg_upgrade/greenplum/check_gp.c
src/test/regress/expected/table_statistics.out
src/test/regress/sql/table_statistics.sql

Check for AO and AOCO root partitions that contain entries in pg_aocsseg without a corresponding relfile. When upgrading the primaries pg_upgrade performs a vacuum freeze of the database before restoring the AO segment tables. Since the segment catalog is copied from the master pg_aocsseg may contain entries without a corresponding relfile causing pg_upgrade to fail with:
```
"ERROR","58P01","could not open Append-Only segment file
""base/16410/20863.1665"": No such file or directory",,,,,,"VACUUM
(FREEZE);",0,,"aomd.c"
```
Tests PR: https://github.com/greenplum-db/gpupgrade/pull/686
Pipelines: 
https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/upgradeCheckAocsRootParts_6X and https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/upgradeCheckAocsRootParts_6X_full

[6X] pg_upgrade: check for parent partitions with seg entries

---

src/backend/commands/tablecmds.c

While performing an AT for access method changes
such as Heap table (Oid:a) to AO table Workflow:
- Create transient AO table (Oid:b) and its AO aux tables in
make_new_heap
- Copy table data into the transient table
- Swap Oids in the pg_appendonly entry so that newly generated aux
tables are mapped to Oid a in ATAOEntries
- Swap attributes in pg_class entry between the two tables (such as
relfilenode, relam, ...)
- Reindex the relation
- Now that pg_class has Oid a pointing to transient table, drop the heap
table

Add comment explaining AT SET ACCESS METHOD flow

---

src/backend/access/appendonly/appendonly_compaction.c

This only one was missed while upstream merging, just set it to
`PROCARRAY_FLAGS_VACUUM` to align the codes, and avoid future risk.
The behavior is actually not changed, `GetLocalOldestXmin()` doesn't check
`PROCARRAY_VACUUM_FLAG` in Greenplum, which was removed from
`PROCARRAY_PROC_FLAGS_MASK`, `true` (0x01) is not checked either.
Reference:
commit af4b1a0869bd3bb52e5f662e4491554b7f611489
Author: Simon Riggs <simon@2ndQuadrant.com>
Date:   Wed Mar 22 16:51:01 2017 +0000
Refactor GetOldestXmin() to use flags
Replace ignoreVacuum parameter with more flexible flags.
Author: Eiji Seki
Review: Haribabu Kommi
Fixes #13830

GetOldestXmin() should use flags as its second parameter

---

gpdb-doc/markdown/install_guide/prep_os.html.md

clarify the disk schedule docs.  in this PR:
- add a storagetype/os/scheduler table
- remove some specifics about setting the scheduler and replace with links to rhel and ubuntu documentation
QUESTION:  i pulled the ubuntu settings from the referenced link.  can someone please confirm/verify these settings?
attached is a screen cap of the html.

docs - add disk i/o sched policy recommends for diff storage types

---

gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md

update the resource group cgroup setup docs so that it is also applicable to rhel8.

docs - update resgroup cgroup setup docs to include rhel8

---

gpdb-doc/markdown/best_practices/heap_tables.html.md

add some info about perf issues with heap tables after bulk load.
couldn't find an ideal location for this info, added a new topic to the best practices guide.
doc review site link (not sure where title went.  focus only on this topic, site is not fully functional):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-review/greenplum-database/GUID-best_practices-heap_tables.html

docs - add best practices for heap table bulk load/update

---

gpdb-doc/markdown/install_guide/migrate.html.md
gpdb-doc/markdown/ref_guide/deprecated-objects.html.md

address the changes to the lead()/lag() function signatures between greenplum 5 and greenplum 6.
- remove lead() and lag() from the deprecated objects topic.
- refine the mention in the migration topic and add a new topic that specifies how to migrate these functions.
question:  i obtained the SQL to identify the views from https://github.com/greenplum-db/gpdb/pull/10849.  can someone confirm that this is correct?
doc review site link for new migration topic (behind VPN):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-pgb/greenplum-database/GUID-install_guide-migrate.html#laglead.

docs - lead() and lag() migration, remove from deprecated objects

---

src/backend/access/common/reloptions_gp.c
src/backend/catalog/pg_appendonly.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

During changing access method from AO to heap, we need to transfer the
pg_appendonly entry of the AO table to be associated with the newly
created temp heap table (TransferAppendonlyEntries). But we (I) mistakenly
insert a new tuple instead of updating the existing tuple. So even the
one associated with the temp table is removed, we still end up having
the old pg_appendonly entry, which has the same oid as the resulting
heap table.
Fixing that. And add test cases for it too.
Ref: AO->heap PR: https://github.com/greenplum-db/gpdb/pull/13738
Also in ddd80abb1aba5b812fb085ad516dcee6c9e130f3 the fillfactor option was moved from intRelOpts_gp to boolRelOpts_gp during the review phase by mistake. Moving it back now.

Fix an issue where the pg_appendonly entry is not removed during AO->heap

---

src/backend/storage/smgr/smgr.c
src/include/storage/smgr.h

This patch introduces extensible storage manager API and hooks, making possible to define custom storage manager in extension. 
To do so, it changes smgropen call a little, removing smgr_which parameter, which is now part of RelFileNode structure. Because of that, smgr_which is now automatically wal-logged, making possible to choose correct set of function for managing storage-related operations, which is: REL_MD(old SMGR_MD) & REL_AO(old SMGR_AO). Renaming SMGR_MD -> REL_MD was made because of circular dependency (we cannot define RelFileNode field of type SmgrImpl because smgr.h uses relfilenode.h). 
Wal changes are needed, because md functions for ao-optimised and "classic" heap relations are now just two implementations of SMGR API, so we choose which to use in smgr_standard function. …

Extensible storage manager API and hooks

---

gpcontrib/gpcloud/include/s3conf.h
gpcontrib/gpcloud/regress/Makefile
gpcontrib/gpcloud/regress/generate_aws_profiles.sh
gpcontrib/gpcloud/regress/generate_config_file.sh
gpcontrib/gpcloud/regress/input/1_21_no_accessid_secret.source
gpcontrib/gpcloud/regress/output/1_21_no_accessid_secret.source
gpcontrib/gpcloud/regress/regress_schedule
gpcontrib/gpcloud/src/s3conf.cpp

This is a new feature for supporting authentication using aws default profiles into S3 pluginSupport.
When both accessid and secret are empty in s3 config file, we will try to get accessid and secret from aws default profiles(~/.aws/credentials).
The section (like “default”) we used in config file is same.
```
[default]
accessid = ""
secret = ""
```
```
[default]
aws_access_key_id=AKIAIOSFONN7EXALE
aws_secret_access_key=wJalrXUtnFEM7MDENG/bPCYEXAMPLEKEY
```
And if only either accessid or secret is empty in s3 config file, we will still report errors and exit.

Support authentication using aws default profiles into S3 pluginSupport

---

concourse/pipelines/gen_pipeline.py

I believe this is a python3 support change. Was getting the error `TypeError: a
bytes-like object is required, not 'str'` This was backported from 3a7bd87028
on 6X_STABLE
Authored-by: Karen Huddleston <khuddleston@vmware.com>

Fix gen_pipeline type for git remote and branch

---

src/backend/commands/cluster.c
src/backend/commands/tablecmds.c
src/backend/parser/gram.y
src/include/commands/tablecmds.h
src/test/regress/expected/alter_distribution_policy.out
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

This allow users to specify reloptions when they are switching the
storage model of the table:
```
ALTER TABLE <> SET ACCESS METHOD <> WITH ([reloptions]);
```
We also support the legacy `appendonly`/`appendoptimized` options
in the SET WITH clause:
```
ALTER TABLE <> SET WITH (appendonly|appendoptimized=true|false, [reloptions]);
```
Examples:
```
CREATE TABLE tab (a int);
ALTER TABLE tab SET ACCESS METHOD ao_row WITH (blocksize=65536);
```
or:
```
ALTER TABLE tab SET WITH (appendonly=true, blocksize=65536);
```
Note that if a user specifies different access methods in a single
statement, an error will be thrown. E.g.:
```
ALTER TABLE ataoset SET ACCESS METHOD ao_row WITH(appendonly=true, orientation=column);
ERROR:  ACCESS METHOD is specified as "ao_row" but the WITH option indicates it …
```

Support specification of reloptions when switching storage model

---

src/bin/pg_dump/t/002_pg_dump.pl

Perl 5.26 packaged with Ubuntu 18 didn't like some newly introduced regex, this fixes the failing test for that platform.
Failed test was `should dump CREATE EXTERNAL WEB TABLE dump_test.dummy_ext_tab`

pg_dump: Fix failing test on Ubuntu 18

---

src/backend/gporca/data/dxl/minidump/TaintedReplicatedTablesCTE.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecNonSingleton.h
src/backend/gporca/libgpopt/src/base/CDistributionSpecNonSingleton.cpp
src/backend/gporca/libgpopt/src/base/CEnfdDistribution.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalSequence.cpp
src/backend/gporca/libgpopt/src/operators/CPhysicalSerialUnionAll.cpp
src/backend/gporca/server/CMakeLists.txt
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

NOTE: Porting changes from master[#13833] to 6X_STABLE
During the optimisation of CTE’s for distributed replicated tables, Sequence operator optimize the first child with any distribution
Requirement and compute the distribution request on the other children based on derived distribution of the first child.
If distribution of first child is a Singleton, requests singleton on all children
If distribution of first child is a Non-Singleton, requests Non-Singleton on all children,
Here when the first child is a Replicated/TaintedReplicated, still we requests Non-Singleton, Hence optimiser adding redistribution motion on
Top of second child, which is creating a wrong plan hence query is getting hung.
So we are trying to request Non-singleton without enforcers when the first child is …

Queries on Distributed Replicated tables hangs when using optimizer

---

src/backend/utils/misc/guc_gp.c
src/backend/utils/mmgr/redzone_handler.c
src/backend/utils/mmgr/test/redzone_handler_test.c

This is the backport of #13668.
When we set runaway_detector_activation_percent to 0 or 100 means to disable runaway detection,
this should apply to Vmem Tracker and Resource Group.
However, in the current implementation, we will still invoke IsGroupInRedZone() if we enabled resource
group if we set runaway_detector_activation_percent to 0 or 100. And in function IsGroupInRedZone()
has some automatic operation to read variables. At the same time RedZoneHandler_IsVmemRedZone
is a very frequently called function, so this will waste a lot of CPU resources.
When we init Red-Zone Handler, will set redZoneChunks to INT32_MAX if we disable runaway
detection, so we can use it to judge whether we are in Red-Zone or not quickly.
No more tests need, since already have case covering this situation.

[6X] skip red-zone check in some situations

---

src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
src/test/regress/expected/qp_with_clause_optimizer.out
src/test/regress/sql/qp_with_clause.sql

- Fix off-by-one error in 71dd8b0239
- Add optimizer_trace_fallback to catch issue in non-assert build
NOTE to reviewers:
- This is already merged in 6X_STABLE https://github.com/greenplum-db/gpdb/commit/1ece764c280ee8544617e013af9cbe6629be3c40
- qp_with_clause_optimizer answer file contains fallback "Out of stack space".  It is a separate issue which will be addressed.  It is related to https://github.com/greenplum-db/gpdb/commit/2d49b616fe7c89ce24c287beb3e36755aca4c38b mishandling cyclic loop in memo group.

Fix qp_with_clause testcase without asserts (#13862)

---

gpcontrib/gpcloud/src/gpreader.cpp
gpcontrib/gpcloud/src/gpwriter.cpp

(1) Remove unnecessary null pointer checks
In C++, there is no need to check whether a pointer is null or not.
This pr removes these unnecessary null pointer checks.
This issue is reported in #8194.
(2) Fix bug using delete to destroy objects allocated by new[]
Using `delete` on a pointer returned by `new []` results in undefined behavior.
This pr fix this bug reported by issue #13811.

Remove unnecessary null pointer checks in gpcloud code

---

src/backend/gporca/libgpopt/src/search/CGroup.cpp
src/test/regress/expected/qp_with_clause.out
src/test/regress/expected/qp_with_clause_optimizer.out
src/test/regress/sql/qp_with_clause.sql

Commit 2d49b616fe updated memo group reset to include reset of a group's
duplicate. Previously, group reset would recursively traverse only the
children. However, by also traversing duplicates it became possible to
form cyclic reset paths in the memo (e.g. a group's child is a duplicate
of parent group). This can lead to a infinite reset loop.
Admittedly, this patch should only be a temporary solution. Intent of
the function FResetStats() is to only reset if logical operators were
added to any group reachable from reset group. In order to do that we
must first search the children before resetting ourselves. Ultimately,
we need a way to properly detect cycles.
Co-authored-by: Jingyu Wang <wjingyu@vmware.com>

ORCA Update reset stat to handle cyclic memo path

---

src/backend/utils/gdd/gddfuncs.c
src/test/regress/expected/deadlock.out
src/test/regress/sql/deadlock.sql

gp_dist_wait_status used to destroy a gang after
execution, which led to a transaction failing.
This fix deletes related code lines, so that the
transaction won't fail.
(cherry picked from commit 1735b5ca3dd37d83e58d3fd4d5da3d31d4d948dc)

Gang loss with gp_dist_wait_status during running transaction.

---

src/backend/executor/execMain.c

**This PR reverts the commit feb285612914edb9a5078178b3adfe9e0459cabe , as the `queryDesc->estate` may be `NULL` in the catch block, which may cause a PANIC.**

Revert mppExecutorCleanup() call in standard_ExecutorStart's catch block

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table_aocs.out
src/test/regress/sql/alter_table_aocs.sql

ADBDEV-2872: ALTER TABLE erase pg_appendonly values
Ensure reorganize keep default compresstype, compresslevel and blocksize table options.
This is need for use for append-optimized column-oriented tables
with compresstype, compresslevel and blocksize options
when new column without compresstype, compresslevel and blocksize options
is added after table reorganize to inherit these options from table
This fixes https://github.com/greenplum-db/gpdb/issues/8207

ADBDEV-2872: ALTER TABLE erase pg_appendonly values

---

src/backend/access/transam/xloginsert.c
src/backend/utils/misc/guc_gp.c
src/test/isolation2/expected/segwalrep/select_throttle.out
src/test/isolation2/expected/setup.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/segwalrep/select_throttle.sql
src/test/isolation2/sql/setup.sql

SELECT or other read-only operations can result in setting hint bits on
pages, which in turn results in generating Full Page Images (FPI) WAL
records. These operations are not throttled currently and hence can
generate huge WAL traffic on primary without waiting for the mirror. This
causes concurrent transactions to suffer from replication lag.
One scenario this was seen in production was during SELECT post
restore of a large heap table from backup. Ideally, these situations
should be avoided by performing vacuum on such tables or via some
other mechanisms. Though there is still a possibility the best practice
guidance is not followed and hence to still avoid the situation better
to have throttling in writing the FPI code as well.

Avoid large replication lag due to FPI WAL records from hintbits

---

src/backend/access/aocs/aocssegfiles.c

according to the comment, when `GetAllAOCSFileSegInfo_pg_aocsseg_rel`
was called from `gp_aoseg_history` after an upgrade, the `state` and
`modcount` might not be set, but no `formatversion`, the if conditon
should always be true, so just remove it to make the code more clean.

[AOCO] remove the useless if condition

---

src/backend/commands/vacuum.c
src/backend/postmaster/autovacuum.c

There is a GPDB_12_MERGE_FIXME in `vacuum_params_to_options_list()` mentioned that some params are not converted for now, but need to be converted when we do vacuum as how we do analyze. We call the scenario "distributed auto vacuum", i.e. to trigger auto vacuum on QD, and QD manages to dispatch the vacuum request to QEs as distributed transaction.
GPDB team had a detailed discussion about distributed auto vacuum. We have no plan for GPDB7, and will determine the approach in future based on feedback from customer. So I changed the FIXME to NOTE with some comments.

Change FIXME to NOTE with comments in vacuum_params_to_options_list()

---

src/backend/gporca/concourse/test_explain_pipeline.yml
src/backend/gporca/concourse/test_orca_pipeline.yml

Updated and deployed pipelines:
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-6X
- https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/explain_6X

[6X] Convert ORCA pipelines to use Vault variables

---

src/bin/pg_dump/common.c
src/bin/pg_dump/pg_backup.h
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dump.h

This PR refactors the functions used to gather metadata required for binary upgrade schema dumps to avoid repetitive queries in performance-critical paths. 
Upgrades require us to preassign the OIDs of tables, indexes, and types so that they match in the old and new clusters. Previously, multiple queries were executed for each object to gather the necessary info to record in the dump file. Now we gather all of the info required up front and use hash table lookups to set and dump the correct OIDs.
Currently, a database with 100k AO tables can result in well over 1 million queries just to gather the required metadata from the old cluster. This PR eliminates those queries.
The names of pg_toast, pg_aoseg, and pg_bitmapindex tables for the given table/index are set to match what they will be …

pg_dump: Rework binary upgrade metadata queries.

---

README.md

Without fetching the submodules, compilation and installation is successful,
but an error occurs when starting the demo cluster.

Mention submodules in the build instructions

---

src/backend/catalog/oid_dispatch.c

I think the `extern` keyword tells the compiler that the function
is defined somewhere else, since here for `RestoreOidAssignments`
it is a definition, `extern` is useless, so remove it.

remove useless extern

---

src/backend/catalog/gp_fastsequence.c
src/backend/commands/tablecmds.c
src/test/regress/input/aocs.source
src/test/regress/input/appendonly.source
src/test/regress/output/aocs.source
src/test/regress/output/appendonly.source

This is to fix #13699.
As we know, AO/AOCO table relies on the `last_sequence` to generate a new first row number
to a new var block, this value will store in the heap table `gp_fastsequence`. 
Whenever we generate a new variable-length storage block, we need to obtain a continuous row 
number from the `gp_fastsequence` table as the first row number of the var block, and also as the 
unique identifier of the tuple when creating an index.
**So, the row number should not be same and not reuse deleted tuple's row number**. Therefore, 
Greenplum must ensure that row numbers are not repeated and always increment.
But sub-transaction will break it:
```sql
begin;
create table t (a int, b int) with (appendonly = true);
insert into t values (1, 1);
savepoint sub;
truncate table t;
insert into t …
```

remove gp_fastsequence entries when executing TRUNCATE AO TABLE

---

src/bin/pg_dump/pg_dump.c

On some compilers, we were getting a sometimes initialized error:
pg_dump.c:6979:2: error: variable 'bitmap_index_namespace' is used uninitialized whenever '?:' condition is false [-Werror,-Wsometimes-uninitialized]
fout->remoteVersion >= 90400 ? bitmap_index_namespace = PG_BITMAPINDEX_NAMESPACE : 3012;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
pg_dump.c:6996:7: note: uninitialized use occurs here
bitmap_index_namespace, bitmap_index_namespace);
^~~~~~~~~~~~~~~~~~~~~~
pg_dump.c:6979:2: note: remove the '?:' if its condition is always true
fout->remoteVersion >= 90400 ? bitmap_index_namespace = PG_BITMAPINDEX_NAMESPACE : 3012;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                 ~~~~~~~
pg_dump.c:6976:28: note: initialize the variable 'bitmap_index_namespace' to silence this …

pg_dump: fix compiler error in getBMIndxInfo

---

gpcontrib/gp_internal_tools/gp_ao_co_diagnostics.c
src/backend/access/appendonly/Makefile
src/backend/access/appendonly/appendonly_blkdir_udf.c
src/backend/access/appendonly/appendonlyblockdirectory.c
src/backend/catalog/gp_toolkit.sql
src/include/cdb/cdbappendonlyblockdirectory.h
src/test/regress/expected/alter_table_set_am.out
src/test/regress/expected/gp_toolkit_ao_funcs.out
src/test/regress/sql/alter_table_set_am.sql
src/test/regress/sql/gp_toolkit_ao_funcs.sql

This commit introduces the `gp_toolkit.__gp_aoblkdir` UDF to print all of
the block directory entries for an AO/AOCO relation. It essentially
flattens the minipage binary column in `pg_aoblkdir_*` relations, printing
a minipage entry in every output row.
This function is in the same spirit as `__gp_aovisimap()` and can be run
in utility mode or with `gp_dist_random()` to obtain meaningful results.
Example:
```sql
postgres=# create table baz(i int, j int) with (appendonly=true);
postgres=# create index on baz(i);
postgres=# insert into baz select i, i FROM generate_series(1, 10) i;
postgres=# insert into baz select i, i FROM generate_series(1, 10) i;
postgres=# SELECT gp_segment_id, (gp_toolkit.__gp_aoblkdir('baz')).* FROM gp_dist_random('gp_id')
order by 1, 2, 3, 4, 5, 6, 7, 8; …
```

gp_aoblkdir: Block directory inspection function

---

src/backend/postmaster/backoff.c
src/include/postmaster/backoff.h

GPCC's metrics collector needs to call BackoffPriorityIntToValue and ResourceQueueGetPriorityWeight.

Declare BackoffPriorityIntToValue and ResourceQueueGetPriorityWeight as extern functions

---

contrib/pgcrypto/Makefile
contrib/pgcrypto/expected/fips_1.out
contrib/pgcrypto/expected/fips_2.out
contrib/pgcrypto/expected/setup_fips.out
contrib/pgcrypto/internal.c
contrib/pgcrypto/openssl.c
contrib/pgcrypto/pgcrypto.c
contrib/pgcrypto/pgp.c
contrib/pgcrypto/pgp.h
contrib/pgcrypto/px.h
contrib/pgcrypto/sql/fips.sql
contrib/pgcrypto/sql/setup_fips.sql
src/test/regress/init_file

this feature from 5X https://github.com/greenplum-db/gpdb/commit/5c751a06d52e43b2e99c81bad8714b69d8047de5 and https://github.com/greenplum-db/gpdb/commit/923ecc088d04f851c9f3a52fc26dfa00ac3ef314
there is no logic change, all behaviors are the same as GPDB 5X.
this PR was tested manually on centos 7 with FIPS enabled OpenSSL and Archlinux with FIPS not enabled.
finished, no push -f anymore.

6X: pgcrypto: add fips support

---

src/backend/commands/exttablecmds.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

This PR fixes https://github.com/greenplum-db/gpdb/issues/9727 
We make the default encoding of the external table the same as the database encoding. 
If user doesn't set the encoding option in create external table [statement](https://gpdb.docs.pivotal.io/6-16/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html), it applies the current client_encoding as the default value:
```
/* If encoding is defaulted, use database encoding */ 
if (encoding < 0) 
encoding = pg_get_client_encoding(); 
```
This will cause a problem that when client_encoding is different from server encoding, the encoding column of pg_exttable will be different in QD and QEs. 
In the previous fix https://github.com/greenplum-db/gpdb/pull/13597, the default encoding is set to client_encoding and dispatched to QEs. However, …

Use the server encoding as default when creating external talbe

---

src/backend/commands/exttablecmds.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

this pr backport https://github.com/greenplum-db/gpdb/pull/13885 in master branch, fixes issue https://github.com/greenplum-db/gpdb/issues/9727
We make the default encoding of the external table the same as the database encoding.
Before this fix, if user doesn't set the encoding option in create external table [statement](https://gpdb.docs.pivotal.io/6-16/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html), it applies the current client_encoding as the default value:
```
/* If encoding is defaulted, use database encoding */ 
if (encoding < 0) 
encoding = pg_get_client_encoding(); 
```
This will cause a problem that when client_encoding is different from server encoding, the encoding column of pg_exttable will be different in QD and QEs.
However, the actual encoding behavior is decided by …

use gpdb server encoding as default external table encoding

---

src/backend/catalog/gp_fastsequence.c
src/backend/commands/tablecmds.c
src/test/regress/input/aocs.source
src/test/regress/input/appendonly.source
src/test/regress/output/aocs.source
src/test/regress/output/appendonly.source

This is the backport of #13762, all details and discussion can be found there.
And @ashwinstar  made a refactor on 7X-Alpha, more details can look at #13780, 
this refactor will avoid the truncate issue, which will keep the `last_sequence` in 
the table `gp_fastsequence` increasing, even we run `TRUNCATE TABLE` on it.
But this fix will reset `last_sequence` in `gp_fastsequence` when we truncate it.
There are some differences, we should notice that.

Fix gp fastsequence truncate 6x

---

src/backend/postmaster/postmaster.c
src/backend/tcop/postgres.c

There are 3 Fixmes in this PR:
* ~~postmaster.c check EnableHotStandby guc~~
just a code refactor (if I understand the fixme message correctly).
* postgres.c T_Query sourceTag
not change it, reason: the sourceTag isn't dispatched to QE and current code works well.
* postgres.c statement_timeout
disable statement_timeout on QE (like gp5 and 6 did).
I think it's meaningless to enable it on QE, and user may encounter this scenario if enable it
```
// most of the time
ERROR:  canceling statement due to statement timeout
// but QE timeout first sometimes
ERROR:  canceling statement due to statement timeout  (seg0 slice1 127.0.1.1:6000 pid=99920)
```

Resolve fixmes in postgres.c and postmaster.c: refactor code and disable statement_timeout on QE

---

gpcontrib/Makefile
gpcontrib/gp_subtransaction_overflow/Makefile
gpcontrib/gp_subtransaction_overflow/expected/subtransaction_overflow_test.out
gpcontrib/gp_subtransaction_overflow/gp_subtransaction_overflow--1.0.0.sql
gpcontrib/gp_subtransaction_overflow/gp_subtransaction_overflow.c
gpcontrib/gp_subtransaction_overflow/gp_subtransaction_overflow.control
gpcontrib/gp_subtransaction_overflow/sql/subtransaction_overflow_test.sql

Subtransaction overflow is a chronic problem for Postgres and Greenplum,
which arises when a backend creates more than PGPROC_MAX_CACHED_SUBXIDS
(64) subtransactions. This is often caused by the use of plpgsql
EXCEPTION blocks, SAVEPOINT etc.
Overflow implies that pg_subtrans needs to be consulted and the
in-memory XidCache is no longer sufficient.
The lookup cost is particularly felt when there are long running
transactions in the system, in addition to backends with suboverflow.
Long running transactions increase the xmin boundary, leading to more
lookups, especially older pages in pg_subtrans. Looking up older pages
while we are constantly generating new pg_subtrans pages (with the
suboverflowed backend(s)) leads to pg_subtrans LRU misses, exacerbating
the slowdown in overall system …

[6X] Feat: Identify backends with suboverflowed transactions

---

src/backend/commands/indexcmds.c
src/backend/commands/tablecmds.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

When a partitioned tables contains external tables as partitions, it is
not possible to implement unique or primary key indexes -- but when
regular indexes are created, there is no reason to do anything other
than ignoring such partitions.  We were raising errors upon encountering
the foreign partitions, which is unfriendly and doesn't protect against
any actual problems.
Relax this restriction so that index creation is allowed on partitioned
tables containing external partitions, becoming a no-op on them. This
applies to CREATE INDEX, as well as ALTER TABLE / EXCHANGE PARTITION.
This commit is back-porting from https://github.com/postgres/postgres/commit/55ed3defc966cf718fe1e8c0efe964580bb23351.

Fix partitioned index creation with external partitions backport

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/gparray.py
gpMgmt/bin/gppylib/test/unit/test_unit_gparray.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature

**Why** : In previous PR [13757](https://github.com/greenplum-db/gpdb/pull/13757) where the plan was to check the health of the cluster before starting the expansion in gpexpand.  while backporting in 6x we realised that hard exit after the health check will create problem for the customer when due to some reason they will not able to make the cluster up in balance state. this will block customer to expand. 
**Issue** : we found the root cause as when the cluster is not in balance state then the max/min port is returning wrong port values and as result system is expanding at the wrong port which is giving multi port error.  
**Fix:** updated the function to work in imbalance cluster state scenario.  we are collecting all the port for primary and mirror based on preferred role of the …

gpexpand : Fix multi port issue when clusters are not in balanced state 

---

gpcontrib/gp_pitr/Makefile
gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
gpcontrib/gp_pitr/gp_pitr--1.0.sql
gpcontrib/gp_pitr/gp_pitr--1.1.sql
gpcontrib/gp_pitr/gp_pitr.control
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql

- This commit creates a new version of the gp_pitr extension (version 1.1.)
- The new version of the extension contains:
gp_stat_arcrhiver view
(copied to gp_pitr extension from the original GPDB7 commit:
https://github.com/greenplum-db/gpdb/commit/9792ebdedf7ae5830af4c69e8cf75c8084396cac)
GPDB7 commit description: introduce the gp_stat_archiver system view
This is a view that will show the output of the system view
pg_stat_archiver across all segments and the coordinator.
For testing, we exercise the view in the gpdb_pitr test suite.
gp_switch_wal() function
(copied to gp_pitr extension from the original GPDB7 commit:
https://github.com/greenplum-db/gpdb/commit/7a850e94dedfbbb69f5a84b780d3d0710d8c98e4)
GPDB7 commit description: When calling pg_switch_wal, it will only
execute on the …

Backport gp_switch_wal() and gp_stat_archiver to 6X (gp_pitr extension)

---

src/test/isolation2/expected/gdd/insert_root_partition_truncate_deadlock.out
src/test/isolation2/expected/insert_root_partition_truncate_deadlock_without_gdd.out
src/test/isolation2/sql/gdd/insert_root_partition_truncate_deadlock.sql
src/test/isolation2/sql/insert_root_partition_truncate_deadlock_without_gdd.sql

The injected fault 'func_init_plan_end' is set only triggered once, and it's
possible that the fault can be triggered by dtx recovery process before than
insert statement. So in this case, the insert statement is not blocked which
causes the pipeline failed.
Inject the fault 'func_init_plan_end' in the same session as the insert, and
specify the current sessionid, so that the fault can't be triggered by other
sessions.
The test insert_root_partition_truncate_deadlock with gdd have the same problem.

Fix flaky test in insert_root_partition_truncate_deadlock_without_gdd

---

src/backend/catalog/pg_appendonly.c
src/backend/commands/tablecmds.c
src/backend/nodes/makefuncs.c
src/backend/parser/gram.y
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

**READY to review**
Description
=============
Currently adding support for the following cases:
```
CREATE TABLE foo(a int) WITH (appendonly=true);
ALTER TABLE foo SET ACCESS METHOD ao_column;
-- or:
ALTER TABLE foo SET WITH (appendonly=true, orientation=column);
```
Similar to other variations of ATSETAM commands, user can also
specify reloptions in a WITH clause, such as:
```
ALTER TABLE foo SET ACCESS METHOD ao_column WITH (blocksize=65536);
```
If no reloptions are given, the new AOCO table will use the existing
table-level options for its column encoding options. If any reloption
is given in the WITH clause, it will be recorded in the catalog and
then used for the column encoding option too.
Note that there was once a thought to support specifying column-level
encoding in the ATSETAM …

ALTER TABLE SET ACCESS METHOD: AO->AOCO support

---

src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
src/backend/gporca/server/include/unittest/dxl/statistics/CStatisticsTest.h
src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp

In Orca, we copy group statistics to avoid costly stats re-deriving.
However, we unintentionally didn't copy the relpages, relallvisible, and
rebinds fields.  These fields are used in costing, and in some cases the
wrong rebind value caused us to improperly cost a NLJ much lower and
Orca selected a non-optimal plan.

Fix improper copying of group statistics in Orca

---

src/backend/executor/nodeAssertOp.c
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/include/executor/nodeAssertOp.h
src/pl/plpgsql/src/expected/plpgsql_trap.out
src/pl/plpgsql/src/sql/plpgsql_trap.sql
src/test/regress/expected/bfv_statistic_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/groupingsets_optimizer.out
src/test/regress/expected/partition_prune_optimizer.out
src/test/regress/expected/qp_correlated_query_optimizer.out
src/test/regress/expected/qp_dml_joins.out
src/test/regress/expected/qp_dml_joins_optimizer.out
src/test/regress/expected/qp_misc_optimizer.out
src/test/regress/expected/qp_subquery_optimizer.out
src/test/regress/expected/qp_union_intersect.out
src/test/regress/expected/qp_union_intersect_optimizer.out
src/test/regress/expected/update_gp.out
src/test/regress/expected/update_gp_optimizer.out
src/test/regress/output/table_functions_optimizer.source
src/test/regress/sql/qp_dml_joins.sql
src/test/regress/sql/qp_union_intersect.sql
src/test/regress/sql/update_gp.sql

AssertOp is used by ORCA for run-time assertion checking. For example,
it guarantees that the following query will not violate implicit
cardinality contraints (i.e. foo cannot contain more than 1 row):
```sql
CREATE TABLE foo(a int);
CREATE TABLE bar(b int);
SELECT * FROM foo WHERE (SELECT a FROM foo) IN (SELECT b FROM bar);
```
PLANNER handles that check in the executor subplan node where it can
determine if the subquery is used in an expression sublink where it
should only return 1 row. However, this is not sufficient for ORCA which
may generate de-correlated plan that contains a join node instead of a
subplan node.
Postgres 12 merge commit 2e653c6e54b disabled this feature in ORCA so
that implementation may be fixed at a later date. This commit does that.

Fix assert op executor node

---

src/backend/gporca/libgpopt/src/mdcache/CMDAccessor.cpp
src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
src/backend/gporca/server/include/unittest/dxl/statistics/CStatisticsTest.h
src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp

In Orca, we copy group statistics to avoid costly stats re-deriving.
However, we unintentionally didn't copy the relpages, relallvisible, and
rebinds fields.  These fields are used in costing, and in some cases the
wrong rebind value caused us to improperly cost a NLJ much lower and
Orca selected a non-optimal plan.
Cherry-picked from c18ebb17bd0de8758caa05259f6c55c56feaefc5

Fix improper copying of group statistics in Orca (#13926)

---

src/backend/parser/parse_expr.c
src/backend/parser/parse_node.c

A RowExpr with more than MaxTupleAttributeNumber columns would fail at
execution anyway, since we cannot form a tuple datum with more than that
many columns.  While heap_form_tuple() has a check for too many columns,
it emerges that there are some intermediate bits of code that don't
check and can be driven to failure with sufficiently many columns.
Checking this at parse time seems like the most appropriate place to
install a defense, since we already check SELECT list length there.
While at it, make the SELECT-list-length error use the same errcode
(TOO_MANY_COLUMNS) as heap_form_tuple does, rather than the generic
PROGRAM_LIMIT_EXCEEDED.
Per bug #17561 from Egor Chindyaskin.  The given test case crashes
in all supported branches (and probably a lot further back),
so patch all. …

In transformRowExpr(), check for too many columns in the row.

---

src/backend/optimizer/plan/planner.c
src/test/regress/expected/partition_aggregate.out

When considering finalizing a partially aggregated path in sorted way, if we
have to insert a sort node, we prefer to do so only for the cheapest path. This
keeps the same logic with PostgreSQL's.

Minor fix for partially grouped rel

---

gpcontrib/gpcloud/include/s3conf.h
gpcontrib/gpcloud/regress/Makefile
gpcontrib/gpcloud/regress/generate_aws_profiles.sh
gpcontrib/gpcloud/regress/generate_config_file.sh
gpcontrib/gpcloud/regress/input/1_21_no_accessid_secret.source
gpcontrib/gpcloud/regress/output/1_21_no_accessid_secret.source
gpcontrib/gpcloud/regress/regress_schedule
gpcontrib/gpcloud/src/s3conf.cpp

This is a new feature for supporting authentication using aws default profiles into S3 pluginSupport.
When both accessid and secret are empty in s3 config file, we will try to get accessid and secret from aws default profiles(~/.aws/credentials).
The section (like “default”) we used in config file is same. 
```
[default]
accessid = ""
secret = ""
```
```
[default]
aws_access_key_id=xxxxx
aws_secret_access_key=xxxxxxxxxxxxxxx
```
And if only either accessid or secret is empty in s3 config file, we will still report errors and exit.

Support authentication using aws default profiles in S3 plugin

---

README.md

'make cluster' with enviroment variables was added after 'make cluster' in
fd2e045, but was not changed to 'make create-demo-cluster' in either c3d74c6
or bb022db. Add environment variables to the demo cluster creation command.

Replace wrong target name with valid one

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

Increases the maximum number of superuser connections from 3 to 10.

docs - set superuser_reserved_connections GUC default  to 10

---

src/test/isolation2/expected/checkpoint_memleak.out
src/test/isolation2/sql/checkpoint_memleak.sql

We weren't waiting for promotion of the mirror before recovery, causing
the test to flake sometimes with a gprecoverseg failure:
```
--- \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/expected\/checkpoint_memleak\.out  2022-08-16 07:02:45.284609608 +0000
+++ \/tmp\/build\/e18b2f02\/gpdb_src\/src\/test\/isolation2\/results\/checkpoint_memleak\.out   2022-08-16 07:02:45.288609897 +0000
@@ -66,11 +83,21 @@
-- Bring back primary and wait until primary and mirror are up & running
!\retcode gprecoverseg -a;
-(exited with code 0)
..
+GP_IGNORE:20220816:06:56:16:066655 gprecoverseg:a71037bd-f5df-43e4-4f12-e72540b6da75:gpadmin-[INFO]:-Starting gprecoverseg with args: -a
...
+GP_IGNORE:20220816:06:56:16:066655 gprecoverseg:a71037bd-f5df-43e4-4f12-e72540b6da75:gpadmin-[INFO]:-Obtaining …
```

[6X] checkpoint_memleak: Ensure promotion before recovery

---

gpcontrib/orafce/pipe.c
gpcontrib/orafce/sqlscan.c

This Patch is back-ported from https://github.com/orafce/orafce/commit/1f162a6da427ae31ab0fcff8c3f0abdb3c5eddb2
Co-Authored-by: Bradford Boyle <bradfordb@vmware.com>

[orafce] Rename pipe type to orafce_pipe to resolve its conflict with pipe function from unistd.h.

---

gpcontrib/gp_replica_check/gp_replica_check.py
src/test/regress/input/dispatch.source
src/test/regress/output/dispatch.source

Since the PostgreSQL 9.4.20 merge, commit 928bca1a30, pg_upgrade can
handle database names that contain quotes correctly. Re-enable test for
it.
Fixes https://github.com/greenplum-db/gpdb/issues/3857
Cherry picked from PR https://github.com/greenplum-db/gpdb/pull/6713
Authored-by: Heikki Linnakangas

Re-enable test with database name containing quotes.

---

gpcontrib/gpcloud/src/gpreader.cpp
gpcontrib/gpcloud/src/gpwriter.cpp

1. Remove unnecessary null pointer checks
In C++, there is no need to check whether a pointer is null or not.
This pr removes these unnecessary null pointer checks.
This issue is reported in #8194.
2. Fix bug using delete to destroy objects allocated by new[]
Using delete on a pointer returned by new [] results in undefined behavior.
This pr fix this bug reported by issue #13811.

Remove unnecessary null pointer checks in gpcloud code (#13877)

---

src/backend/catalog/pg_appendonly.c
src/backend/commands/cluster.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

Should be ready to review. But might need to make minor rebasing adjustment after https://github.com/greenplum-db/gpdb/pull/13835 is merged.
One note: in the above AO->AOCO PR we add column encoding in `ATExecCmd`, whereas in this AOCO->Heap PR we remove the same in `ATAOEntries` due to the following reasons:
* Table rewriting of AOCO table needs those encodings, so adding column encoding needs to happen **before** that, and removing them needs to happen **after** that.
* We can take WITH options (or even more from future syntax support) into consideration when adding the column encoding.
----------------
As part of the ATSETAM support, this commit adds support for
changing AM of a table from AOCO to heap. E.g.:
```
CREATE TABLE foo (appendonly=true, orientation=column);
ALTER TABLE foo …
```

ALTER TABLE SET ACCESS METHOD: AOCO->Heap support

---

src/backend/catalog/pg_appendonly.c
src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

This PR includes two commits:
1. Remove existing reloptions *as long as* AM is changed 
Previously, we only remove the existing reloptions when the AM is
changing between Heap and AO/AOCO, since the reloptions are mutually
exclusive between them.
Now we do the same when changing AM between AO and AOCO too, for
the following reasons:
1. Keep behaviors consistent.
2. Even between AO and AOCO there's certain reloption that's not
applicable to one of them: e.g. 'compresslevel=rle_type' only
applies to AOCO but not AO.
3. If customer specifies reloptions themselves within the ATSETAM
statement, we then need to pick and remove those conflicting
with the new reloptions. Too much complicities will be introduced.
With this change, we also refactored ATExecSetRelOptions a little bit
since now we …

ALTER TABLE SET ACCESS METHOD: AOCO->AO support

---

src/bin/pg_dump/pg_backup.h
src/bin/pg_dump/pg_dump.c

Partitioning has existed in GPDB for a long time (4.2 and before). So, no reason to check for existence of these features since we do not support dumps from servers <= GPDB5. Removing the check because we expect these to exist.

Remove unnecessary partitioning checks in pg_dump

---

src/backend/catalog/pg_appendonly.c
src/backend/commands/cluster.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

Currently adding support for the following cases:
```
CREATE TABLE foo;
ALTER TABLE foo SET ACCESS METHOD ao_column;
-- Or:
ALTER TABLE foo SET WITH (appendonly=true, orientation=column);
```
Similar to other variations of ATSETAM commands, user can also
specify reloptions in a WITH clause, such as:
```
ALTER TABLE foo SET ACCESS METHOD ao_column WITH (blocksize=65536);
```
If no reloptions are given, the new AOCO table will use the default
reloptions for its column encoding options. If any reloption
is given in the WITH clause, it will be recorded in the catalog and
then used for the column encoding option too.

ALTER TABLE SET ACCESS METHOD: Heap->AOCO support

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table_set_am.out
src/test/regress/sql/alter_table_set_am.sql

It is found that when changing from AO to AOCO we cannot specify `compresstype=rle_type` which would complain that it is not applicable to AO table, despite that it should be a valid usage.
This is because during setting new reloptions, we miss the information about the new AM being AOCO, and the code behavior is to validate the reloptions as AO tables.
Fixing it by passing the new AM into ATExecSetRelOptions() based on which we can validate the reloptions. If there is no AM change, an InvalidOid will be passed in and we will use the current table AM to validate the reloptions.
Also modifying the regress test to include this usage.

Fix an issue with rle_type when changing table from AO to AOCO

---

src/test/regress/expected/dsp.out
src/test/regress/sql/dsp.sql

The first FIXME is introduced by the commit from
merge branch 002f61d8. Remove it and run the full
pipelines it passes the tests.
The second FIXME is asking if it is necassary to
test GUC gp_default_storage_options should keep
consistent among master and segments. Although
gpconfig's unittest might cover this, it does no
harm to also test here for this important GUC.

Resolve a GPDB_12_MERGE_FIXME in regress/dsp.

---

gpMgmt/bin/gppylib/db/dbconn.py
src/test/regress/input/dispatch.source
src/test/regress/input/gpcopy.source
src/test/regress/output/dispatch.source
src/test/regress/output/gpcopy.source
src/test/regress/test_dbconn.py

This is really a bug of the Python Package PyGreSQL,
see issue: https://github.com/PyGreSQL/PyGreSQL/issues/77
As a workaround, let's modify GPDB's code to manually
escape before passing args to pgdb.

Escape database name for dbconn.

---

src/bin/pg_basebackup/pg_basebackup.c

Change sprintf function to snprintf, to check resulting buffer size overflow.
This is the same pr as #13963 applied to master branch.

Fix compile-time warn in pg_basebackup code

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table_aocs2.out
src/test/regress/expected/partition.out
src/test/regress/sql/alter_table_aocs2.sql
src/test/regress/sql/partition.sql

Remove fixmes about ATTACH partition
We don't need these fixmes as the ATExecAttachPartition takes care of
the checks.
Attaching an expanded table on an unexpanded table will correctly
error out due to different distribution policies.
Resolving AOCO add column optimization fixme
We won't need to execute it on QE.
QD/utility would still benefit from the no-rewrite optimization.

Resolve tablecmds fixmes

---

src/test/regress/greenplum_schedule

This is intended to fix flaky cases introduced by VACUUM index
enhancement on AO PR https://github.com/greenplum-db/gpdb/pull/13255.
As the new VACUUM strategy cleaning up index dead tuples isn't based on
visibility map checking any more, there might be more index->reltuples
to be counted in the case of concurrent AUTOVACUUM/AUTOANALYZE(for sampling
the stats of user tables) being reading the same table result in dead tuples
deletion skipped. So move impact tests under disable_autovacuum for validity
of stats on index->reltuples.
As we didn't enable AUTOVACUUM on 6X, so it is supposed to be no issue on 6X.

Move stats related tests under disable_autovacuum for validity of index's reltuples.

---

src/backend/parser/parse_expr.c
src/backend/parser/parse_node.c

A RowExpr with more than MaxTupleAttributeNumber columns would fail at
execution anyway, since we cannot form a tuple datum with more than that
many columns.  While heap_form_tuple() has a check for too many columns,
it emerges that there are some intermediate bits of code that don't
check and can be driven to failure with sufficiently many columns.
Checking this at parse time seems like the most appropriate place to
install a defense, since we already check SELECT list length there.
While at it, make the SELECT-list-length error use the same errcode
(TOO_MANY_COLUMNS) as heap_form_tuple does, rather than the generic
PROGRAM_LIMIT_EXCEEDED.
Per bug #17561 from Egor Chindyaskin.  The given test case crashes
in all supported branches (and probably a lot further back),
so patch all. …

(6x) In transformRowExpr(), check for too many columns in the row.

---

src/backend/commands/tablecmds.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

We have these checks as part of ATPrepCmd for individual AT commands,
These checks allow AT on external partitions iff ATT_FOREIGN_TABLE
is permitted
For AT_SetDistributedBy, we only allow ATT_TABLE, so external partitions
should always error out
Added test for this behavior

Resolve tablecmd fixme for AT_SetDistributedBy external partition check

---

src/test/regress/expected/alter_table_aocs2.out
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/alter_table_aocs2.sql
src/test/regress/sql/partition.sql

Commit 60758eecea4 introduced a test which didn't work with gpcheckcat
for having different distribution policies on same table. 
This change fixes the test by dropping the tables in the end as cleanup.
Add output for partition_optimizer test
Change temp table name in alter_table_aocs2 to avoid collision with
other tests using same table name

Fixes for tests introduced in fixme PR for ATTACH partition

---

gpcontrib/gp_percentile_agg/expected/gp_percentile_agg.out
src/backend/optimizer/plan/plangroupext.c
src/test/regress/expected/aggregate_with_groupingsets.out
src/test/regress/sql/aggregate_with_groupingsets.sql

compare_pathkeys() assumes the pathkeys are canonical, and checks them
for equality by simple pointer comparison. So we should not use the copy
of pathkeys when generating subplans for rollups. Otherwise we would
have unnecessary sort nodes in the final plan.

Remove unnecessary sort nodes for grouping sets with DQA

---

src/test/isolation2/output/resgroup/resgroup_bypass.source

There is small mistake in 178a555a33146aef20b25fb1ca801a7e7a67582b
This commit has changed input for `memory limit in bypass mode, on qd`,
but corrupt output for `memory limit in bypass mode, on one slice` test
To reproduce the problem run resgroup tests with command:
`make PGOPTIONS="-c optimizer=off" installcheck-resgroups`
Mentioned mistake was fixed in master by https://github.com/greenplum-db/gpdb/commit/19cd1cf4b68faff2e29bc2fa884c480e4644cdb4

[6X] Fix mistake in resgroup bypass isolation test

---

src/test/regress/expected/alter_table_aocs2.out
src/test/regress/sql/alter_table_aocs2.sql

Change table name in alter_table_aocs2 to avoid collision with
other test alter_table_aocs which runs in parallel using same table name

Fix for ICW test alter_table_aocs2

---

src/backend/optimizer/path/allpaths.c
src/backend/optimizer/plan/createplan.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

When we bring a path to OuterQuery locus, we need to keep its param info,
because this path may further join with other paths. For instance,
select * from a where a.i in
(select count(b.j) from b, c,
lateral (select * from d where d.j = c.j limit 10) s
where s.i = a.i
);
The path for subquery 's' requires parameter from 'c'. When we bring this path
to OuterQuery locus, its param info needs to be preserved, so that when joining
's' with 'b' we can have correct param info.

Preserve param info when bringing a path to OuterQuery locus

---

src/backend/optimizer/path/indxpath.c
src/test/regress/expected/combocid_gp.out
src/test/regress/expected/combocid_gp_optimizer.out
src/test/regress/expected/rpt.out

When picking up index paths for bitmap scans, do not consider whether seqscan
is disabled.
This change removes the GPDB_92_MERGE_FIXME, and also makes the codes
consistent with PostgreSQL.

Remove the check of enable_seqscan when creating bitmap index path

---

src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/executor/execMain.c

https://github.com/greenplum-db/gpdb/pull/2588 eliminates alien nodes before execution but entry db nodes was missed.
This PR adds alien nodes elimination for entry db.
There is a small fix in `formIdleSegmentIdList` function to  propagate GUC change to **entry db** (e.g. `execute_pruned_plan` that was used in test).
The is a PR https://github.com/arenadata/gpdb/pull/352 in GPDB fork in **6x** that also adds test for entry db nodes elimination.
As there is no memory accounting for **X_Alien** nodes in **master** alien nodes elimination can be tested manually (i.e. test from https://github.com/greenplum-db/gpdb/pull/2663 is not applicable).

Eliminate alien nodes before execution for entry db

---

README.md

Thanks OpenLab for providing ARM regression tests service for a very
long time.
This PR is also to raise some attention from developers. As #13903 mentions,
even if OpenLab is EOL, they can generously donate us some ARM VM resources
for testing Greenplum.

Remove OpenLab CI from README as it's EOL.

---

src/test/regress/expected/workfile_limits.out
src/test/regress/sql/workfile_limits.sql

The below commit added a case to test the GUC gp_workfile_limit_files_per_query,
but there is already one and the newly added one takes way too much time.
This commit removes the newly added case.
commit 209694154bdc5797ea66b2116dcd82fc9454e593
Author: zwenlin <zwenlin@vmware.com>
Date:   Fri Mar 25 19:14:13 2022 +0800
Remove gpdb_12_merge_fixme in buffile.c.
PostgreSQL breaks temporary files into 1 GB segments. Greenplum didn't
do that until v12 merge greenplum-db/gpdb@19cd1cf breaks BufFiles into
segments and counts each segment file as one work file.
The GUC gp_workfile_limit_files_per_query is used to control the maximum
number of spill files for a given query, to prevent runaway queries from
destroying the entire system. Counting each segment file is reasonable
for this scenario. …

Remove an redundant case from workfile_limits

---

src/test/regress/expected/bitmap_index.out
src/test/regress/expected/bitmap_index_optimizer.out
src/test/regress/sql/bitmap_index.sql

In commit dfb8c7c7c19, I thought it just moves a test case location
and I verify the case locally so that pushing it in a
hurry. Unfortunately, there is a previous test case bitmapops which
create the same name index without dropping. Naming conflict leads to
pipeline failure.
This commit change the index name in the case of dfb8c7c7c19 to make
ci green.

Fix pipeline failure introduced by dfb8c7c7c194f

---

src/backend/parser/gram.y

gram.y compilation warning:
```
gram.y:3326:49: warning: size argument in 'strncmp' call is a comparison [-Wmemsize-comparison]
strncmp(n->name, witham, strlen(n->name) != 0))
~~~~~~~~~~~~~~~~^~~~
gram.y:3326:8: note: did you mean to compare the result of 'strncmp' instead?
strncmp(n->name, witham, strlen(n->name) != 0))
^                                            ~
)
gram.y:3326:33: note: explicitly cast the argument to size_t to silence this warning
strncmp(n->name, witham, strlen(n->name) != 0))
^
(size_t)(           )
1 warning generated.
```
As suggested by the compiler, we simply needed to move the ending
parenthesis to compare the strncmp result as most likely intended. The
main reason why this didn't cause any issues is because the strlen
comparisons were good enough since the …

Fix compilation warning in gram.y

---

gpMgmt/bin/gppylib/test/unit/test_unit_foreign_key_check.py

In commit afde39b3f973c429aa4175e5d70575566bb905bd we changed a query filter in the foreign_key_check test in gpcheckcat. That breaks the gppylib's unit test 'test_unit_foreign_key_check' where it checks if the gpcheckcat tests have desired calls. Adjusted it now.
Side note: we might be able to import the gpcheckcat filters into the gppylib unit test so we don't have to adjust it every time we modified them. But since these changes should be very rare (only one change since [the test was introduced 6 years ago](https://github.com/greenplum-db/gpdb/commit/92cc01872c81)), we can consider that in a later day.

Fix a test failure in test_unit_foreign_key_check

---

concourse/scripts/compile_gpdb.bash

https://github.com/greenplum-db/gpdb/commit/80907fb1c3fbe7257befb4fa60a8757cec6d12eb has add introduced the
zstd for gpdb6 client's gpfdist.so So need to ship libzstd.so to customer

vendor libzstd.so to clients

---

src/backend/access/transam/xlog.c
src/backend/utils/misc/guc_gp.c
src/test/isolation2/expected/segwalrep/select_throttle.out
src/test/isolation2/expected/setup.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/segwalrep/select_throttle.sql
src/test/isolation2/sql/setup.sql

This is a 6X backport of 611b788d18d.
Conflicts resolved:
(1) xloginsert.c doesn't exist on 6X. Side note: we also don't have
XLOG_FPI_FOR_HINT as we don't have 0bd624d63b0, but that doesn't matter
much as we still add the throttle logic for XLogSaveBufferForHint().
(2) SRFs aren't supported in the WHERE clause, so had to change
is_query_waiting_for_syncrep() a bit.
(3) wait_event is not present in pg_stat_activity, used waiting_reason
instead.
(4) Had to include server_helpers.sql to get
wait_until_all_segments_synchronized().
SELECT or other read only operations can result in setting hintbits on
pages, which in turn results in generating Full Page Images (FPI) WAL
records. These operations are not throttled currently and hence can
generate huge wal …

[6X] Avoid large replication lag due to FPI WAL records from hintbits

---

src/backend/commands/tablecmds.c

In ATExecAddColumn() where we find child tables to apply a flag,
we used to open the tables w/o lock. That is because we have already
held a lock on the parent and we implicitly believed that no one
else could alter the child tables now. That is still correct, but
the upstream had introduced an expectation for relation_open()
in 4b21acf522d751ba5b6679df391d5121b6c4a35f that all callers of
relation_open() should have acquired a lock except in bootstrap
mode. I do not think it's important to still use NoLock and try
to workaround that assert in relation_open() in some way.
Therefore, resolving the FIXME as it is.

Resolve a fixme comment in ATExecAddColumn() about why no lock child table

---

gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature

gpinitsystem is not working with debug option -D and throwing errors as below:
20220715:11:44:09:048391 gpinitsystem:-[INFO]:-End Function PING_HOST
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: 2>/dev/null: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: REMOTE_EXECUTE_AND_GET_OUTPUT: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1055: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1060: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1066: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1079: [: too many arguments
20220715:11:44:09:048391 gpinitsystem:-[INFO]:-End Function GET_PG_PID_ACTIVE
When we run gpinitsystem with …

gpinitsystem is not working with debug option

---

src/backend/cdb/motion/tupleremap.c
src/test/regress/expected/gpparams.out
src/test/regress/sql/gpparams.sql

This is a 5X backport of bugfix https://github.com/greenplum-db/gpdb/pull/10773.
The master node dispatches external and internal (gathered from plan
tree) parameters along with query plan. Internal parameters might
include not initialized zero values, e.g., used for storing results of
not yet evaluated initPlans. Those parameters are trasmitted as zero
values that cases segfault on segments under deserialization of complex
type value.
The current fix intercepts on QE side handling of zero value parameter
before further deserialization process.

Explicitly handle on QE side zero value parameter incoming from QD

---

src/backend/cdb/cdbllize.c
src/test/regress/expected/rpt.out
src/test/regress/expected/rpt_optimizer.out
src/test/regress/sql/rpt.sql

The last query from the series
```
set optimizer=off;
create table t_replicate_dst(id serial, i integer) distributed replicated;
create table t_replicate_src(i integer) distributed replicated;
insert into t_replicate_src select i from generate_series(1, 5) i;
insert into t_replicate_dst (i) select i from t_replicate_src;
select distinct id from gp_dist_random(t_replicate_dst);
```
returned 15 lines (not 5) on cluster with 3 segments.
The plan of the second insert was:
```
Insert on t_replicate_dst
->  Seq Scan on t_replicate_src
```
The error is not reproduced on master, because when volatile functions are
detected in the query at the stage of adding the Insert node,
the Broadcast Motion node will be added. The plan on master is:
```
Insert on t_replicate_dst
->  Broadcast Motion 1:3 …
```

Fix INSERT INTO replicated table SELECT FROM another replicated with sequence generation

---

src/backend/access/transam/xlogfuncs_gp.c
src/backend/catalog/cdb_schema.sql
src/include/catalog/catversion.h
src/include/catalog/pg_proc.dat
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/expected/test_gp_switch_wal.out
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
src/test/gpdb_pitr/test_gpdb_pitr.sh

The LSN output from pg_switch_wal() is commonly used with
pg_walfile_name(). However, the LSN set outputted from gp_switch_wal()
cannot be used by pg_walfile_name() because of the very likely
timeline differences of the coordinator segment and all the
segments. To make sure users/developers that want the WAL segment
filename and 100% guarantee that it is correct, we should bake it into
gp_switch_wal(). Having a separate catalog function would create a
window where HA failover would make the timeline ids incorrect and we
would have the same problem all over again.
We also convert the function into a C function to guarantee that all
the function calls in gp_switch_wal() are called on the correct
segments. Using the EXECUTE ON SEGMENT/COORDINATOR combo with a UNION
was observed to have known …

Update gp_switch_wal() to include pg_walfile_name() output

---

gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13763 and https://github.com/greenplum-db/gpdb/pull/13764.  will be backported to 6X_STABLE.

docs - new optimizer_enable_replicated_table guc

---

src/test/regress/expected/db_size_functions.out
src/test/regress/sql/db_size_functions.sql

The test started failing after a change to `gp_switch_wal()` was
made. The db_size_functions regress test was not updated
accordingly. Fix the test by simply updating the expected output
(matchsub in the test added as well).
GPDB commit reference:
https://github.com/greenplum-db/gpdb/commit/d3163467b018082b1b36d70f94fe95e59898b6e0
This PR fixes the ICW test job failures on the GPDB Concourse pipeline.

Fix db_size_functions regress test

---

src/backend/access/aocs/aocsam.c
src/backend/catalog/pg_compression.c
src/backend/cdb/cdbappendonlystoragewrite.c
src/backend/utils/datumstream/datumstream.c
src/backend/utils/datumstream/datumstreamblock.c

Backport of #13988. Please see individual commits for details.

[6X] DatumStream teardown: NULL out after pfree

---

gpMgmt/bin/gpexpand
src/test/regress/expected/db_size_functions.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/db_size_functions.sql
src/test/regress/sql/subselect_gp.sql

During gpexpand, it will record all the tables that need to do data
redistribution and in order to show the progress the table size is
also saved in the status_details table.
Previously, we directly invoke pg_relation_size to compute that value
in the target list of a SQL involving only catalog tables. This will
lead to very bad performance because for each table it will do a dispatch
to compute its size and the whole progress is done in serial.
This commit rewrite the SQL generating the status_details information.
The skills used to MPP compute table size is:
1. we use gp_dist_random('pg_class') to get a force random RangeTable
2. since pg_relations_size is volatile, wrap the computation in a
subquery before group-by to prevent optimizer to pull up subquery
and force the pg_relation_size …

Improve the performance of source_bytes computation during gpexpand.

---

gpMgmt/bin/gpexpand
src/test/regress/expected/db_size_functions.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/db_size_functions.sql
src/test/regress/sql/subselect_gp.sql

During gpexpand, it will record all the tables that need to do data
redistribution and in order to show the progress the table size is
also saved in the status_details table.
Previously, we directly invoke pg_relation_size to compute that value
in the target list of a SQL involving only catalog tables. This will
lead to very bad performance because for each table it will do a dispatch
to compute its size and the whole progress is done in serial.
This commit rewrite the SQL generating the status_details information.
The skills used to MPP compute table size is:
1. we use gp_dist_random('pg_class') to get a force random RangeTable
2. since pg_relations_size is volatile, wrap the computation in a
subquery before group-by to prevent optimizer to pull up subquery
and force the pg_relation_size …

(6x) Improve the performance of source_bytes computation during gpexpand.

---

gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature

Issue:
gpinitsystem is not working with debug option -D and throwing errors as below:
20220715:11:44:09:048391 gpinitsystem:-[INFO]:-End Function PING_HOST
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: 2>/dev/null: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1051: [: REMOTE_EXECUTE_AND_GET_OUTPUT: integer expression expected
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1055: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1060: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1066: [: too many arguments
/usr/local/gpdb6/bin/lib/gp_bash_functions.sh: line 1079: [: too many arguments
20220715:11:44:09:048391 gpinitsystem:-[INFO]:-End Function GET_PG_PID_ACTIVE
Cause:
When we run …

[6X] gpinitsystem is not working with debug option (#13942)

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/gparray.py
gpMgmt/bin/gppylib/test/unit/test_unit_gparray.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature

**Issue:** when one or more cluster is down or not in their preferred role, the assignment of port on expanded nodes are going wrong. the reason behind that the calculation of port using function get_max_primary_port() and get_max_mirror_port(). The idea to exit from gpexpand when the cluster is not in balanced state was blocking customer to expand if they found difficulty to make the system in balance state.  
**Fix:** updated the function to work in imbalance cluster state scenario. we are collecting all the port for primary and mirror based on preferred role of the segment, and if the role is switched we are considering segmentPairs.mirrorDB for primary port and segmentPairs.primaryDB for mirror port. in this we are collecting the port which is based on the preferred role.
Added …

[backport] added cluster health check for gpexpand

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
src/backend/utils/misc/guc_gp.c

It is expensive to derive constraints and stats if we expand the large array
into CNF/DNF form. 100 is still a large default value, so lower it down to 20
to get better performance for most queries.
Ref: GPQP-31

Change optimizer_array_expansion_threshold default value to 20

---

contrib/auto_explain/expected/auto_explain.out
contrib/auto_explain/expected/auto_explain_optimizer.out
src/backend/commands/explain.c
src/backend/utils/misc/guc.c
src/include/utils/guc_tables.h
src/test/regress/expected/explain_format.out
src/test/regress/expected/explain_format_optimizer.out
src/test/regress/expected/fast_default.out
src/test/regress/sql/explain_format.sql
src/test/regress/sql/fast_default.sql

EXPLAIN prints non-default GUCs on verbose mode, before this commit it actually
checked the source of the setting but not the value.
This commit borrows the upstream implementation and tests on the YAML and
unaligned mode. (gpdiff masks the settings out on normal mode)

Check GUC variables if match the built-in default accurately

---

src/backend/access/transam/varsup.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h
src/test/regress/expected/subtrx_overflow.out
src/test/regress/sql/subtrx_overflow.sql

We might want to also consider adding a log message to print the query string
that caused the overflow. This is important as only 1 statement out of thousands
executed in a backend may trigger the overflow, or the backend can come out of
the overflow state before it is inspected with our view/UDF. Logging the
statement will ensure that customers can pinpoint the offending statements.

[7X] Add a GUC to control the output of suboverflow transaction sql statement

---

gpcontrib/gp_subtransaction_overflow/expected/subtransaction_overflow_test.out
gpcontrib/gp_subtransaction_overflow/sql/subtransaction_overflow_test.sql
src/backend/access/transam/varsup.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/sync_guc_name.h
src/include/utils/unsync_guc_name.h

We might want to also consider adding a log message to print the query string
that caused the overflow. This is important as only 1 statement out of thousands
executed in a backend may trigger the overflow, or the backend can come out of
the overflow state before it is inspected with our view/UDF. Logging the
statement will ensure that customers can pinpoint the offending statements.

[6X] Add a GUC to control the output of suboverflow transaction sql statement

---

src/backend/access/bitmap/bitmap.c
src/backend/access/index/indexam.c
src/backend/executor/nodeBitmapIndexscan.c
src/include/access/bitmap_private.h
src/include/access/genam.h
src/test/regress/expected/bitmap_index.out
src/test/regress/expected/bitmap_index_optimizer.out
src/test/regress/sql/bitmap_index.sql

when we create bitmap-index on column and using bitmap index scan with NULL array condition on this column, then failed. Like this:
> create temp table foo (a int); 
> create index foo_i on foo using bitmap(a); 
> select * from foo where a = any(null::int[]); 
> Conversant: ERROR "unrecognized result from subplan (nodeBitmapHeapscan.c:293)"
The reason is when we using bitmap-index scan on NULL Array key condition, MultiExecbitmapscan treate it as runtime key then it will return NULL to parent node. But for parent node like BitmapHeapNext cannot handle NULL return, then error happened. So we should return an empty bitmap instead of nothing to upper node(BitmapHeapNext), and force BitmapHeapNext scan this empty bitmap.

Fix Bitmap index null-array condition failed

---

src/backend/commands/tablecmds.c

We used to always dispatch in DefineIndex(). Now we don't if it is part of the ALTER TABLE command execution: https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/indexcmds.c#L613-L618 . So we no longer need to skip DefineIndex for QEs. Resolving this FIXME then.

Cleanup a FIXME in ATExecAddIndex

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gporca/data/dxl/minidump/DeleteWithTriggers.mdp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
src/test/isolation2/output/uao/parallel_delete_optimizer.source
src/test/regress/expected/ao_locks_optimizer.out
src/test/regress/expected/direct_dispatch_optimizer.out

It was observed that, in response to a DELETE based DML query wherein we
know that the data resides on a particular segment, the commands should
be issued by Orca to that segment only. However, it was found that the
commands were issued to all the segment.  This behaviour was
cross-checked with the Legacy Planner, it was found that Legacy Planner
was sending the query to single segment only.
To correct this behaviour changes were done in the following files:
1. FILE NAME : CTranslatorExprToDXL.cpp
In function CtranslatorExprToDXL::PdxlnDML , object for
CDXLDirectDispatchInfo is created by calling GetDXLDirectDispatchInfo
function.
Before the update, in the GetDXLDirectDispatchInfo function, null
pointer was returned for any DML command other than INSERT.
Now, this condition has been …

Enable direct dispatch for DML statements with ORCA

---

src/backend/access/common/reloptions.c
src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table_set.out
src/test/regress/expected/alter_table_set_am.out
src/test/regress/expected/partition_locking.out
src/test/regress/expected/partition_locking_optimizer.out
src/test/regress/sql/alter_table_set.sql

Code ready to review. ~But the test cases that involved changing AM won't pass until https://github.com/greenplum-db/gpdb/pull/13897 is merged.~ (merged now)
-----------------------
Users can now use ALTER TABLE ... SET to set reloptions for root partition tables. E.g.:
```
ALTER TABLE part SET (fillfactor=70);
```
Similar to SET ACCESS METHOD, the reloptions being set for the root partition will be inherited by their existing child partitions and recursed into their children as well.
Also similarly, if user uses the "ONLY" keyword, e.g.:
```
ALTER TABLE ONLY part SET (fillfactor=70);
```
Then the reloptions will only apply to the root and its future child tables.

Support setting reloptions for partition tables

---

src/backend/access/transam/xlogfuncs_gp.c
src/include/catalog/catversion.h
src/include/catalog/pg_proc.dat
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
src/test/gpdb_pitr/expected/test_gp_switch_wal.out
src/test/gpdb_pitr/init_file_gpdb_pitr
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
src/test/gpdb_pitr/test_gpdb_pitr.sh

The gp_create_restore_point() catalog function was not properly marked
as EXECUTE ON COORDINATOR and required a column definition list to get
nice looking output from a `SELECT *`. Fix the issues by marking the
proexeclocation as 'c' (previously using default 'a') and explicitly
setting the proarg details. A dedicated test has been added to the
gpdb_pitr test suite to add some needed test coverage.
This will be backported to the 6X-exclusive gp_pitr extension as well.

Update gp_create_restore_point() catalog function

---

gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
gpcontrib/gp_pitr/gp_pitr--1.1.sql
gpcontrib/gp_pitr/gp_pitr.c
src/backend/access/transam/xlogfuncs_gp.c
src/include/access/xlog_fn.h
src/test/gpdb_pitr/.gitignore
src/test/gpdb_pitr/Makefile
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/expected/test_gp_switch_wal.out
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
src/test/gpdb_pitr/test_gpdb_pitr.sh

The LSN output from pg_switch_wal() is commonly used with
pg_walfile_name(). However, the LSN set outputted from gp_switch_wal()
cannot be used by pg_walfile_name() because of the very likely
timeline differences of the coordinator segment and all the
segments. To make sure users/developers that want the WAL segment
filename and 100% guarantee that it is correct, we should bake it into
gp_switch_wal(). Having a separate catalog function would create a
window where HA failover would make the timeline ids incorrect and we
would have the same problem all over again.
We also convert the function into a C function to guarantee that all
the function calls in gp_switch_wal() are called on the correct
segments. Using the EXECUTE ON SEGMENT/COORDINATOR combo with a UNION
was observed to have known …

[6X backport] Update gp_switch_wal() to include pg_walfile_name() output

---

contrib/bloom/blutils.c
src/backend/access/common/reloptions.c
src/backend/access/common/reloptions_gp.c
src/include/access/reloptions.h

This patch is derived from the postgres upstream [0],
the main idea is for each add_<type>_reloption and
allocate_reloption, add a LOCKMODE as a parameter,
so that we can initialize the option's lock mode
when allocating the struct.
we can get ride of *set_reloption_lockmode* then.
[0]: https://github.com/postgres/postgres/commit/69f94108079d70093b59096a3ae0ad82c842b4c0

Allow definition of lock mode for custom reloptions

---

gpMgmt/bin/gppylib/commands/pg.py

--no-verify-checksum option shouldn't be needed but it was added to avoid basebackup failures with appendoptimized tables. To fix this improvement issue is created https://github.com/greenplum-db/gpdb/issues/12536
So change the GPDB_12_MERGE_FIXME to GPDB_12_MERGE_FEATURE_NOT_SUPPORTED.

change verify checksum FIXME to FEATURE NOT SUPPORTED

---

src/bin/psql/describe.c

add_partition_by_footer is still needed by legacy partitioning to print
old version server's 'partition by' clause.

Resolve GPDB_12_MERGE_FIXME in describe.c about legacy partitioning.

---

src/backend/optimizer/util/pathnode.c

It happens in the below query:
explain (verbose, costs off)
select foo.f1, loct1.f1 from foo join loct1 on (foo.f1 = loct1.f1) order by foo.f2 offset 10 limit 10;
select foo.f1, loct1.f1 from foo join loct1 on (foo.f1 = loct1.f1) order by foo.f2 offset 10 limit 10;
The reason is that set_append_path_locus()->cdbpath_create_motion_path()
returns NULL (i.e. can not create a motion to reach the target locus
requirement) but set_append_path_locus() does not handle this bad case and
panic due to this (i.e. when accessing subpath->sameslice_relids while subpath
is NULL). This happens because in the above query, foo has a child with foreign
table (and a local heap table child additionally) and the append node tries to
create a parameterized path (one is an index scan path and another is the …

Fix a panic case in the greenplum_fdw test.

---

src/backend/access/transam/xlog.c
src/test/regress/expected/checkpoint_xlog.out
src/test/regress/greenplum_schedule
src/test/regress/sql/checkpoint_xlog.sql

When we turned on the GUC `gp_before_filespace_setup` and restarted GPDB, we hit an assertion in `UnpackCheckPointRecord()`:
```
8393         Assert(remainderLen > ckptExtended->masterMirroringCheckpointLen);
```
Relevant stack:
```
#0  0x00007f47d42406b3 in __select_nocancel () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000c03b8d in pg_usleep (microsec=30000000) at pgsleep.c:43
#2  0x0000000000a727dd in elog_debug_linger (edata=0x11f4940 <errordata>) at elog.c:4342
#3  0x0000000000a69d31 in errfinish (dummy=0) at elog.c:616
#4  0x0000000000a6847c in ExceptionalCondition (conditionName=0xc1f0d0 "!(remainderLen > ckptExtended->masterMirroringCheckpointLen)", errorType=0xc1a9ea "FailedAssertion", fileName=0xc1aa32 "xlog.c", lineNumber=8393) at assert.c:49
#5  0x000000000051a6ce …
```

Fix checkpoint record corrupt with gp_before_filespace_setup

---

src/bin/psql/describe.c

Fixes issue: #13997 for master branch.
This patch adds support for describing auxiliary tables. e.g.,
```
postgres=# create table foo(i int) with (appendonly=true);
postgres=# create index on foo(i);
CREATE INDEX
postgres=# select blkdirrelid::regclass from pg_appendonly where relid = 'foo'::regclass;
blkdirrelid
----------------------------
pg_aoseg.pg_aoblkdir_16411
(1 row)
postgres=# \d+ pg_aoseg.pg_aoblkdir_16411
Appendonly block directory table: "pg_aoseg.pg_aoblkdir_16411"
Column     |  Type   | Storage
----------------+---------+---------
segno          | integer | plain
columngroup_no | integer | plain
first_row_no   | bigint  | plain
minipage       | bytea   | plain
Indexes:
"pg_aoblkdir_16411_index" PRIMARY KEY, btree (segno, columngroup_no, first_row_no)
postgres=# \d+ …
```

[psql] Add support for describing auxiliary tables for ao table.

---

src/backend/libpq/auth.c
src/backend/libpq/hba.c
src/include/libpq/hba.h

Version 6X_STABLE don't support ldapsearchfilter option for LDAP authentication.
We use the value of ldapsearchattribute option as ldap search filters. 
For example, when the entry in pg_hba.conf is `host all user1 0.0.0.0/0 ldap ldapserver=xxx ldapbasedn="xxx" ldapbinddn="xxx" ldapbindpasswd="xxx" ldapsearchattribute="sAMAccountName"`, we use "(sAMAccountName=$username)" as ldap search filters.
We can't specify more complex ldap search filters by ourselves.
To allow for more flexible search filters, we backport ldapsearchfilter option from master branch.
With this pr, we can specify ldap search filters in pg_hba.conf by ldapsearchfilter option, like `host all user1 0.0.0.0/0 ldap ldapserver=xxx ldapbasedn="xxx" ldapbinddn="xxx" ldapbindpasswd="xxx" …

[6X] support ldapsearchfilter option for LDAP authentication 

---

src/backend/fts/ftsmessagehandler.c
src/backend/fts/ftsprobe.c
src/backend/fts/test/ftsmessagehandler_test.c
src/backend/replication/gp_replication.c
src/backend/replication/test/gp_replication_test.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/replication/gp_replication.h
src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out
src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql

Commits start blocking only if STREAMING or CATCHUP within range.
In real scenarios it often happens that the mirror node is down (probably not
really down) and out-of-sync for some time and that could lead to large wal lag
on the mirror node, and when the mirror is added back by fts, fts currently
soon sets syncrep on. While at the time the mirror is catching up and thus it
stalls the new write query for a long time until wal catchup finishes.
There was a guc repl_catchup_within_range that "Sets the maximum number of xlog
segments allowed to lag when the backends can start blocking despite the WAL
sender being in catchup phase." It was for the coordinator only. Now we could
use it on segments also, to allow commits start blocking only if walsender is
in STREAMING state or in CATCHUP …

Enable catchup within range on segment.

---

src/backend/fts/ftsmessagehandler.c
src/backend/fts/ftsprobe.c
src/backend/fts/test/ftsmessagehandler_test.c
src/backend/replication/gp_replication.c
src/backend/replication/test/gp_replication_test.c
src/backend/utils/misc/guc_gp.c
src/include/cdb/cdbvars.h
src/include/replication/gp_replication.h
src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out
src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql

This is backport of https://github.com/greenplum-db/gpdb/pull/13891.
Commits start blocking only if STREAMING or CATCHUP within range.
In real scenarios it often happens that the mirror node is down (probably not
really down) and out-of-sync for some time and that could lead to large wal lag
on the mirror node, and when the mirror is added back by fts, fts currently
soon sets syncrep on. While at the time the mirror is catching up and thus it
stalls the new write query for a long time until wal catchup finishes.
There was a guc repl_catchup_within_range that "Sets the maximum number of xlog
segments allowed to lag when the backends can start blocking despite the WAL
sender being in catchup phase." It was for the coordinator only. Now we could
use it on segments also, to allow commits …

Enable catchup within range on segment backport.

---

gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature

The gpinitsystem utility fails when incoming locale value doesn't
correspond character-by-character to the some line of locale -a output
[[1](https://github.com/greenplum-db/gpdb/blob/5cfd4791b3e327f733ba4a2832f627ef70f4aa91/gpMgmt/bin/gpinitsystem#L644-L653), [2](https://github.com/greenplum-db/gpdb/blob/5cfd4791b3e327f733ba4a2832f627ef70f4aa91/gpMgmt/bin/gpinitsystem#L656-L665), [3](https://github.com/greenplum-db/gpdb/blob/5cfd4791b3e327f733ba4a2832f627ef70f4aa91/gpMgmt/bin/lib/gp_bash_functions.sh#L179-L186)]
Because locale -a among other things [represents](https://github.com/bminor/glibc/blob/2d5ec6692f5746ccb11db60976a6481ef8e9d74f/locale/programs/locale.c#L440-L442) locales from the archive [with](https://github.com/bminor/glibc/blob/2d5ec6692f5746ccb11db60976a6481ef8e9d74f/locale/ …

Fix gpinitsystem fails with custom locale

---

contrib/pgcrypto/Makefile
contrib/pgcrypto/expected/fips_1.out
contrib/pgcrypto/expected/fips_2.out
contrib/pgcrypto/expected/setup_fips.out
contrib/pgcrypto/internal.c
contrib/pgcrypto/openssl.c
contrib/pgcrypto/pgcrypto.c
contrib/pgcrypto/pgp.c
contrib/pgcrypto/pgp.h
contrib/pgcrypto/px.h
contrib/pgcrypto/sql/fips.sql
contrib/pgcrypto/sql/setup_fips.sql
src/test/regress/init_file

this feature from 5X 5c751a06d52e43b2e99c81bad8714b69d8047de5 and 923ecc088d04f851c9f3a52fc26dfa00ac3ef314 (6X #13799)
there is no logic change, all behaviors are the same as GPDB 5X.
this PR was tested manually on Archlinux with FIPS not enabled and passed the main pipeline.

7X: pgcrypto: add fips support

---

gpdb-doc/markdown/ref_guide/modules/pgcrypto.html.md

pgcrypto.fips instructions forward-ported from 5X_STABLE.  
HTML review at https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/pgcrypto/greenplum-database/GUID-ref_guide-modules-pgcrypto.html

Docs - Add pgcypto.fips instructions

---

gpdb-doc/markdown/install_guide/install_modules.html.md
gpdb-doc/markdown/ref_guide/modules/intro.html.md
gpdb-doc/markdown/ref_guide/modules/ip4r.html.md
gpdb-doc/markdown/ref_guide/toc.md

docs for https://github.com/greenplum-db/gpdb/pull/13588 (master) and https://github.com/greenplum-db/gpdb/pull/13600 (6X_STABLE)
in this PR:  add topic for new ip4r module.
question:  did i appropriately state the attribution?
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-ip4r/greenplum-database/GUID-ref_guide-modules-ip4r.html

docs - for ip4r contrib module

---

gpcontrib/gp_percentile_agg/expected/gp_percentile_agg_optimizer.out
gpcontrib/gp_percentile_agg/gp_percentile_agg--1.0.0.sql
gpcontrib/gp_percentile_agg/gp_percentile_agg.c
src/backend/gporca/data/dxl/minidump/CTAS_OrderedAgg_multiple_cols.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_diffcol.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol_difforderespec.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_single.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_skewed_data.mdp
src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonOrderedAgg.mdp
src/backend/gporca/libgpopt/include/gpopt/operators/COrderedAggPreprocessor.h
src/backend/gporca/libgpopt/src/operators/COrderedAggPreprocessor.cpp
src/backend/gporca/libnaucrates/include/naucrates/dxl/gpdb_types.h
src/backend/gporca/server/CMakeLists.txt

This is a backport of https://github.com/greenplum-db/gpdb/pull/13740 to 6X
This is an extension to the original PR https://github.com/greenplum-db/gpdb/pull/13596
As part of the original PR, the plan ORCA generated for ordered-set aggs were of the following shape:
```
GbAgg (New aggregate: gp_percentile_cont(a, 0.5, total_cnt)) 
+----- Gather (output: a, 0.5, total_cnt)
(merge key = a)
+----- Sort (Gather Merge on coordinator)  --- parallelized on segments
+----- NLJ (output: a, 0.5, total_cnt)
+----- GbAgg (count(a) as total_cnt)  --- parallelized on segments
+----- Scan t
```
This would be MPP-efficient for non-skewed data scenarios, where there is no duplicate data and would read the entire table. But for skewed data (with duplicates), reading the entire data would lead to slower …

[6X] Enhance ORCA to generate performant plans for ordered-set aggs with skewed data

---

gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
gpcontrib/gp_pitr/gp_pitr--1.1.sql
src/backend/access/transam/xlogfuncs_gp.c
src/test/gpdb_pitr/expected/gpdb_pitr_setup.out
src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
src/test/gpdb_pitr/expected/test_gp_switch_wal.out
src/test/gpdb_pitr/init_file_gpdb_pitr
src/test/gpdb_pitr/sql/gpdb_pitr_setup.sql
src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
src/test/gpdb_pitr/sql/test_gp_switch_wal.sql
src/test/gpdb_pitr/test_gpdb_pitr.sh

The gp_create_restore_point() gp_pitr extension function was not
properly marked as EXECUTE ON MASTER and required a column definition
list to get nice looking output from a `SELECT *`. Fix the issues by
marking the proexeclocation as 'c' (previously using default 'a') and
explicitly setting the proarg details. A dedicated test has been added
to the gpdb_pitr test suite to add some needed test coverage.
Backported from GPDB master commit:
https://github.com/greenplum-db/gpdb/commit/8aaa0474610ee608eae2aa13d7096bff261819a0
6X backport merge conflicts:
* The gp_create_restore_point() catalog function is an extension
function in 6X_STABLE so relative changes had to be made to the
extension accordingly instead.
* On 6X, it's EXECUTE ON MASTER instead of EXECUTE ON COORDINATOR.
* Also needed …

[6X backport] Update gp_create_restore_point() gp_pitr extension function

---

gpcontrib/gp_pitr/gp_pitr--1.0--1.1.sql
gpcontrib/gp_pitr/gp_pitr--1.1.sql

The newly introduced gp_stat_archiver view was added into the
extension script as CREATE OR REPLACE VIEW. While this is technically
okay, it doesn't look right and at the time of merging the commit into
GPDB 6X had a potential security issue (see reference commit). Update
it to simply use CREATE VIEW to prevent any possible future issues.
GPDB 6X commit reference:
https://github.com/greenplum-db/gpdb/commit/ecc2f0b2b7a11ab137078db3383d7245771df21a

Update gp_stat_archiver view definition in gp_pitr extension

---

contrib/auto_explain/Makefile
contrib/auto_explain/auto_explain.c
contrib/auto_explain/expected/bfv_preload_auto_explain.out
contrib/auto_explain/expected/bfv_preload_auto_explain_optimizer.out
contrib/auto_explain/init_file
contrib/auto_explain/sql/bfv_preload_auto_explain.sql

The reason of failure is that auto_explain hooks are fully executed on QEs.
The global variable Gp_role is initialized after auto_explain is loaded as shared preload library.
The QE has valid planstate objects just for nodes in query plan corresponded to the slice of current QE.
As result, for "intermediate" slices we have NULL pointer to subtree state for "child" (within slice borders)
Motion nodes (subtree itself is valid and points to real node but state for this subtree is not).
ExplainNode() routine called within ExplainPrintPlan() function fails trying to dereference that pointer.
To fix the failure I've changed the guard check Gp_role != GP_ROLE_DISPATCH in _PG_init() of auto_explain
to macro IS_QUERY_DISPATCHER() that relies on GpIdentity.segindex value to define the kind of node …

auto_explain: fix failure when executor hooks are run in QEs

---

contrib/auto_explain/Makefile
contrib/auto_explain/auto_explain.c
contrib/auto_explain/expected/bfv_preload_auto_explain.out
contrib/auto_explain/expected/bfv_preload_auto_explain_optimizer.out
contrib/auto_explain/init_file
contrib/auto_explain/sql/bfv_preload_auto_explain.sql

The reason of failure is that auto_explain hooks are fully executed on QEs. The global variable Gp_role is initialized after auto_explain is loaded as shared preload library. In Greenplum 6X, each postmaster (not matter master, or segment) will have Gp_role == GP_ROLE_DISPATCH, and when create gang, new QEs will set Gp_role when the receive dispatch from QD. Since gpdb7, this is passed as cmd args to the binary postgres.
The QE has valid planstate objects just for nodes in query plan corresponded to the slice of current QE. As result, for "intermediate" slices we have NULL pointer to subtree state for "child" (within slice borders) Motion nodes (subtree itself is valid and points to real node but state for this subtree is not). ExplainNode() routine called within ExplainPrintPlan() …

(6x backport) auto_explain: fix failure when executor hooks are run in QEs

---

src/test/regress/init_file

some blank character mistake.
```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /tmp/build/e18b2f02/gpdb_src/contrib/pgcrypto/expected/fips_2.out /tmp/build/e18b2f02/gpdb_src/contrib/pgcrypto/results/fips.out
--- /tmp/build/e18b2f02/gpdb_src/contrib/pgcrypto/expected/fips_2.out	2022-09-07 06:59:53.878157887 +0000
+++ /tmp/build/e18b2f02/gpdb_src/contrib/pgcrypto/results/fips.out	2022-09-07 06:59:53.882158271 +0000
@@ -16,7 +16,7 @@
(1 row)
SELECT digest('santa claus', 'md5');
-ERROR:  Cannot use "md5": 
+ERROR:  Cannot use "md5": Some PX error (not specified)
SELECT 'Test digest sha256: EXPECTED PASS' as comment;
comment              
-----------------------------------
@@ -36,7 +36,7 @@
(1 row)
SELECT hmac('santa claus', 'aaa', 'md5');
-ERROR:  Cannot use "md5": 
+ERROR:  Cannot use …
```

ci: fix ci failure #13905

---

src/backend/executor/nodeRecursiveunion.c
src/backend/executor/nodeWorktablescan.c
src/backend/optimizer/path/allpaths.c
src/backend/optimizer/plan/subselect.c
src/include/nodes/execnodes.h
src/include/optimizer/subselect.h
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect.sql

If a WITH RECURSIVE query has multiply-referenced CTEs with outer
recursive refs, it will generate multiple WorkTable scans which
scan the same working table with the same readptr, so that it will
lose some datas. Create a readptr for each WorkTable scan to generate
rigrt results.
Remove GPDB_12_MERGE_FIXME in subselect.sql which describes the issue.
-----
Fix https://github.com/greenplum-db/gpdb/issues/10014

Fix wrong results with a WITH RECURSIVE query

---

gpdb-doc/markdown/admin_guide/external/g-s3-protocol.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13789 and https://github.com/greenplum-db/gpdb/pull/13849.  will be backported to 6X_STABLE.
the s3 protocol can now examine the default AWS credential file for S3 creds when the s3 protocol config file does not specify the accessid and secret.  i updated the s3 protocol topic:
- added a new section named "About Providing the S3 Authentication Credentials"
- related changes now that there is an alternate way to specify the creds and accessid/secret are no longer required  
doc review site link (behind VPN):  https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/lisa-pgb/greenplum-database/GUID-admin_guide-external-g-s3-protocol.html#s3_auth

docs - s3 protocol supports using the default aws profile auth creds

---

gpdb-doc/markdown/admin_guide/external/g-file-protocol.html.md
gpdb-doc/markdown/admin_guide/external/g-gpfdist-protocol.html.md
gpdb-doc/markdown/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.html.md
gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13933, adds zstd compression on read/write to gpfdist.  by extension, also adds zstd compression on read for the file protocol; docs didn't reference any compression support for file protocol, so add that info.

docs - gpfdist and file protocols support zstd compression

---

src/backend/commands/createas.c
src/backend/commands/exttablecmds.c
src/backend/commands/sequence.c
src/backend/commands/tablecmds.c
src/backend/commands/typecmds.c
src/backend/commands/view.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/parser/gram.y
src/backend/parser/parse_partition_gp.c
src/include/nodes/parsenodes.h

In MergeAttributes() when we merge attributes of the parents, we avoided checking their refcount because in GPDB, ALTER TABLE ... ADD|SPLIT PARTITION couldn't meet the upstream expectation that at this point the partition root shouldn't be in use.
But that seems to be an overkill. That check would be useful for majority of the cases. We should restore it for all the other cases. Therefore, now passing the query string to MergeAttributes() so that we only avoid doing so for ALTER TABLE ... ADD|SPLIT PARTITION.

Resolve a FIXME in MergeAttributes()

---

src/backend/gporca/data/dxl/minidump/Date-TimeStamp-HashJoin.mdp
src/backend/gporca/data/dxl/minidump/NotWellDefinedDisjunctConjunctPredicates.mdp
src/backend/gporca/data/dxl/minidump/TimeStamp-Date-HashJoin.mdp
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CCastTest.cpp

ORCA commit https://github.com/greenplum-db/gpdb/commit/f8990fbd5dfbaf94d715a7d0db68987333e88512 enables more datatypes in constraint
evaulation. However, it also exposed an issue in preprocessor step
PexprInferPredicates() which can cause ORCA to produce a plan with
duplicate casted predicates.
This commit fixes the issue by deduplicating cast equality predicates.
Example: Date-TimeStamp-HashJoin.mdp

[ORCA] Fix duplicate cast predicates 

---

src/backend/catalog/system_views.sql
src/include/catalog/catversion.h
src/test/gpdb_pitr/expected/test_gp_create_restore_point.out
src/test/gpdb_pitr/expected/test_gp_switch_wal.out
src/test/gpdb_pitr/sql/test_gp_create_restore_point.sql
src/test/gpdb_pitr/sql/test_gp_switch_wal.sql

The gp_create_restore_point (GPDB wrapper of pg_create_restore_point) and gp_switch_wal (GPDB wrapper of pg_switch_wal) catalog functions can be called by any user but would eventually error out if the user didn't have permissions on the wrapped catalog functions after the function dispatch (e.g. permission denied for function pg_switch_wal on segment 3). Instead of relying on the permissions error on the wrapped catalog functions when they're dispatched, revoke the EXEC permissions from the GPDB wrapper catalog functions to explicitly and immediately error out before the functions are even executed.

Change default permissions on gp_create_restore_point and gp_switch_wal

---

src/bin/pg_upgrade/greenplum/reporting.c
src/bin/pg_upgrade/test_gpdb.sh

The report_progress function called when using the pg_upgrade `--progress` flag may take a NULL argument for `cluster`, but was not checking for NULL before trying to print `cluster->major_version_str`, resulting in a core dump.
Add a check before fprintf call, which also resolves a FIXME.
Also use --progress flag in pg_upgrade regression test.

pg_upgrade: Fix core dump in report_progress()

---

gpMgmt/bin/gppylib/gpcatalog.py
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature

gpcheckcat currently flags default privilege objects as having missing
dependencies. This is because it searches for dependencies of
pg_default_acl oids in pg_depend instead of in pg_shdepend. The fix is
to recognize pg_default_acl as a table outside the purview of pg_depend.
Minimal repro:
```
postgres=# CREATE ROLE foo;
postgres=# ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
postgres=# SELECT oid, * FROM pg_default_acl;
oid  | defaclrole | defaclnamespace | defaclobjtype |  defaclacl
-------+------------+-----------------+---------------+-------------
17304 |      17303 |               0 | f             | {foo=X/foo}
(1 row)
postgres=# SELECT * FROM pg_shdepend WHERE objid = 17304;
dbid  | classid | objid | objsubid | refclassid | refobjid | deptype …
```

Fix gpcheckcat false alarms for pg_default_acl

---

src/backend/cdb/cdbgroupingpaths.c
src/backend/optimizer/plan/planner.c
src/test/regress/expected/groupingsets.out
src/test/regress/expected/groupingsets_optimizer.out
src/test/regress/sql/groupingsets.sql

We already support multistage hash aggregation for grouping set by this commit 9a790f8a4ab443ffb2efb6fac8cb96c5ab36f5b7.
There is no need to bail out if there are any unsortable refs.

Support multistage hash aggregation for grouping set with unsortable refs

---

src/test/isolation2/sql_isolation_testcase.py
src/test/regress/pg_regress.c

GlobalShellExecutor checks `o.endswith(GlobalShellExecutor.BASH_PS1)`
before, there is a possibility that the current `o` only has several
ending characters of the `GlobalShellExecutor.BASH_PS1`, in that case it
never terminates but times out.
This commit checks the whole output instead.

GlobalShellExecutor checks the whole output as the termination condition

---

gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Currently, the gpinitsystem Behave tests fail because of environment variables being set in the tests not being unset/reset. Subsequent tests after an environment variable is set are affected and could fail if related (e.g. the locale tests). It didn't help that our Behave steps relating to environment variables were not working cohesively as well. The step to set the environment variable was not storing the original into the context for the other two steps to use. The step to unset the environment variable was not being used properly in our Behave tests because the step format did not have double quotes whereas all step references were double-quoting the environment variable. The previously unused step to restore the environment variable did not properly check for None values and would …

Fix gpinitsystem Behave tests that use environment variables

---

src/backend/gporca/libgpopt/include/gpopt/base/CPartitionPropagationSpec.h
src/backend/gporca/libgpopt/src/base/CPartitionPropagationSpec.cpp

Prior to this commit, partition propogation spec stored a partition info
list in an array that needed to stay sorted. It needed to stay sorted in
order to compare for equality against another partition propogation spec
where order of the stored partition info list is relevant.
By using an array implementation we pay a cost of O(N log N X N) to
insert data that is sorted on each insert and at best O(log N)) to find
using binary search. By contrast a hash map implementation costs O(N) to
build and O(1) to find.
This commit store partition info list in a hash map.

[ORCA] Resolve merge FIXMEs in CPartitionPropagationSpec 

---

gpMgmt/bin/gppylib/gpcatalog.py

The setting of partition template only happens on QD and is not dispatched to QEs https://github.com/greenplum-db/gpdb/blob/master/src/backend/commands/tablecmds_gp.c#L1375 This is intentional since only QD needs to read the partition template when creating new subpartitions, and it then dispatches custom CreateStmts to the QEs. So QE doesn’t need the catalog.

Fixme: gp_partition_template for segments

---

gpMgmt/bin/gpcheckcat

Removed as there is no functional difference after removing the older query. No reg is found from 6x to 7x.

Fixme: removed fixme tag as the changes have no impact

---

src/backend/optimizer/plan/subselect.c
src/test/regress/expected/sublink_optimizer.out
src/test/regress/sql/sublink.sql

This is another way to fix #11849, more details can be found at #13823.
And is this fix, there has no regression on uncorrelated EXISTS sublinks 
that have DISTINCT/DISTINCT ON/ORDER BY clause, but the logic of the 
function `simplify_EXISTS_query()` is more complicated.
This PR and #13823 both can fix issue #11849, and #13823 makes 
`simplify_EXISTS_query()`  easier to understand, but has regression in some 
cases. This PR makes `simplify_EXISTS_query()` a little more complicated, 
but has no regression.

Don't simplify uncorrelated EXISTS sublink in some cases

---

src/test/regress/expected/tidscan_optimizer.out

The commit 4aaf666ff removed system column stats from Orca, but forgot to update the expected output plan.

Update tidscan optimizer expected output

---

src/backend/commands/explain.c
src/backend/executor/nodeSort.c
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfuncs.c
src/backend/optimizer/path/allpaths.c
src/backend/optimizer/plan/createplan.c
src/backend/utils/misc/guc_gp.c
src/backend/utils/misc/postgresql.conf.sample
src/include/cdb/cdbvars.h
src/include/nodes/execnodes.h
src/include/nodes/plannodes.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/join_gp.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/tpch500GB.out

On GPDB6, the GUC `gp_enable_sort_distinct` is used to optimize sort by indicating "noduplicate" to remove duplicated rows and reduce data handling. It effects on replacement selection sort only. However, on GPDB7, replacement selection sort has been removed completely. So we need to remove `gp_enable_sort_distinct` and other codes related to "noduplicate" sort.
In GPDB6, `Tuplesortstate` has a member `noduplicates`:
```
326     bool        noduplicates;   /* discard duplicate rows if true *//* CDB */
```
The usages of `noduplicates` is to indicate `tuplesort_sorted_insert()` to discard duplicated tuples:
```
3990     if (state->noduplicates && (0 == comparestat))
3991     {
3992         freetup = tuple;
3993         goto L_freetup;
3994     }
```
And they are ONLY usages of noduplicates, …

FIXME remove gp_enable_sort_distinct and noduplicates optimizing

---

src/backend/access/transam/xact.c
src/backend/commands/indexcmds.c
src/backend/tcop/utility.c
src/include/access/xact.h
src/include/commands/defrem.h
src/test/regress/expected/partition_indexing.out
src/test/regress/sql/partition_indexing.sql

This is intended to adjust https://github.com/greenplum-db/gpdb/pull/11994 to prevent executing reindex partitioned table in function only, keep allowing reindex partitioned table in transaction block in STABLE release.

[6X] Prevent REINDEX TABLE partitioned table statement in function

---

src/backend/access/transam/xact.c
src/backend/commands/indexcmds.c
src/backend/tcop/utility.c
src/include/access/xact.h
src/include/commands/defrem.h
src/test/regress/expected/partition_indexing.out
src/test/regress/sql/partition_indexing.sql

This is a backport of https://github.com/greenplum-db/gpdb/pull/14081.
As different from upstream, we support REINDEX TABLE on partitioned table which will expand the partitioned table and start new transaction to do the reindex for each table. This has side effects that cannot be rolled back if it gets called in PL language and may crash, so we need to make sure it must not run inside a function.
This fix is related to issue greenplum-db#11948.
This is applied to STABLE release only for less impact of current transaction behavior. It will be changed in the next major release to fully address preventing multi-transaction statement running in a transaction block.
Co-authored-by: Haolin Wang <whaolin@vmware.com>

[5X Backport] Prevent REINDEX TABLE partitioned table statement in function.

---

gpMgmt/bin/gppylib/gpcatalog.py
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature

This is a backport of #13834 from 7X to 6X.
gpcheckcat currently flags default privilege objects as having missing dependencies. This is because it searches for dependencies of pg_default_acl oids in pg_depend instead of in pg_shdepend. The fix is to recognize pg_default_acl as a table outside the purview of pg_depend.
Minimal repro:
```
postgres=# CREATE ROLE foo;
postgres=# ALTER DEFAULT PRIVILEGES FOR ROLE foo REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC; 
postgres=# SELECT oid, * FROM pg_default_acl;
oid  | defaclrole | defaclnamespace | defaclobjtype |  defaclacl
-------+------------+-----------------+---------------+-------------
17304 |      17303 |               0 | f             | {foo=X/foo}
(1 row)
postgres=# SELECT * FROM pg_shdepend WHERE objid = 17304;
dbid  | classid | objid | …
```

[6X_Backport] Fix gpcheckcat false alarms for pg_default_acl

---

gpMgmt/bin/gpactivatestandby

Increased the loop count to 600 in promote_standby(), to align the standby promotion timeout with MIRROR_PROMOTION_TIMEOUT. Fixes https://github.com/greenplum-db/gpdb/issues/11105
Backport of 7X PR https://github.com/greenplum-db/gpdb/pull/13504/

Increased the standby promotion wait time in gpactivatestandby

---

src/bin/pg_dump/pg_backup_db.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dump.h
src/bin/pg_dump/pg_dumpall.c

This PR updates child partition metadata handling when dumping from GPDB{5,6}
To gather binary upgrade information for GPDB{5,6} partition children, they need to exist in the tblinfo array for findTableByOid.
This requires the getTable query to also collect all GPDB partition children, then filter them out of the dump so we only dump the partition root DDL. Previously, partition children were being excluded from the getTables query and gathered separately in
dumpTableSchema. This allows dumpTableSchema to perform lookups of the partition children to dump their OIDs for binary upgrade. [1]
Move pg_get_partition_def and pg_get_partition_template_def queries from dumpTableSchema to getTables. The functions
are only run for parent tables. This change reduces the number repetitive queries and …

Fixes for dumping from GPDB5/6 using GPDB7 pg_dump

---

src/backend/cdb/cdbmutate.c
src/backend/executor/execMain.c
src/backend/executor/nodeMaterial.c
src/backend/optimizer/plan/orca.c
src/backend/optimizer/plan/planner.c
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/shared_scan.out
src/test/regress/expected/shared_scan_optimizer.out
src/test/regress/sql/shared_scan.sql

GPDB has Shared Scan node to share the output of a subplan. Each Shared Scan node can act like producer or consumer. Each one may be a part of different slice. One of essential parts of Shared Scan processing is cross-slice interaction detection. It helps to find the difference in producer's and consumer's slices and mark underlying Material or Sort nodes as cross-slice. Cross-slice producer reads all the tuples from child plan before the consumer Shared Scan can read it.
Before this patch, cross-slice interaction detection of underlying subplan nodes was broken. We [walked](https://github.com/greenplum-db/gpdb/blob/6.20.5/src/backend/cdb/cdbmutate.c#L2642) through subplans separately from main plan. This, in case subplan has no motion, …

[6X] Fix cross-slice interaction detection for subplans

---

src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/executor/execMain.c
src/backend/executor/execProcnode.c
src/test/regress/expected/memconsumption.out
src/test/regress/sql/memconsumption.sql

This is a https://github.com/greenplum-db/gpdb/pull/13857 backport from **master** branch that solves the following.
https://github.com/greenplum-db/gpdb/pull/2588  (commit 9b8f5c0) that eliminates alien nodes, but it lacks elimination
of alien nodes for entry db. This commit resolves this issue. Tests for alien nodes
elimination (added with https://github.com/greenplum-db/gpdb/pull/2663 commit b831ed6) are extended to support entry db too.
Also, this patch fixes dispatching of set command to already existing entry db gang in `formIdleSegmentIdList` function to propagate GUC change to **entry db** (e.g. `execute_pruned_plan` that was used in test).
The simple test to check alien nodes elimination:
```
create table t1 (a int, b int, c int) distributed by (a);
\pset pager off
set …
```

(6x backport) Eliminate alien nodes before execution for entry db

---

gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
gpdb-doc/markdown/best_practices/resgroups.html.md
gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md

6X_STABLE docs:  clarify description the of gp_resource_group_enable_recalculate_query_mem guc.  add the guc to resource group best practices topic.

docs - clarify use of gp_resource_group_enable_recalculate_query_mem guc

---

gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

docs for https://github.com/greenplum-db/gpdb/pull/11443.  add ref docs for the gp_eager_two_phase_agg guc.
the guc is in 6X_STABLE with the same default value, so will backport to that branch.

docs - add guc ref for gp_eager_two_phase_agg

---

src/backend/cdb/cdbgroupingpaths.c
src/test/regress/expected/gp_dqa.out
src/test/regress/expected/gp_dqa_optimizer.out
src/test/regress/sql/gp_dqa.sql

This patch is to fix #14096.
How does multi-DQA work:
When creating path for multi-DQA (multiple distinct qualified aggregate), the planner generates the plan as follows:
```
Finalize Aggregate
-> Gather Motion
-> Partial Aggregate
-> HashAggregate, to remove duplicates
-> Redistribute Motion
-> TupleSplit (according to DISTINCT expr)
-> input
```
The plan is generated via the following steps:
1. The planner compares the expr in DQA with the input tuples, if the DQA expr is not in PathTarget, the TupleSplit node will append the corresponding column the the PathTarget together with a special column 'AggExprId' to the output tuple. E.g., if the input of TupleSplit is '(a: 1, b: 2, c: 3)' and the DQA expressions are 'DQA(a)', 'DQA(b)', the output of TupleSplit are '(a: 1, b: null, c: 3, …

Fix incorrect hash-key of Redistribute-Motion when creating path for multi-DQA expr.

---

concourse/scripts/compile_gpdb.bash
gpAux/Makefile
gpMgmt/bin/generate-greenplum-path.sh

Python3.9 is the dependency of the plpython3 extension, which is not integrated into gpdb6. This commit integrates python3.9 into GPDB6 and does not set PYTHONPATH and PYTHONHOME for python3.9 to guarantee it does not influence python2.
Co-authored-by: Ning Wu <ningw@vmware.com>

Integrate python3.9 to GPDB6

---

src/backend/cdb/motion/ic_tcp.c
src/test/isolation2/expected/tcp_ic_teardown.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/tcp_ic_teardown.sql

Introduce timeout to tcp ic teardown select loop
Background:
1c1f16448ba introduced the waitOnOutbound() call for non-error cases as
well during TCP IC teardown, after "Interconnect error: connection
closed prematurely." ERRORs were seen in Azure environments. This is
essential because performing a close() does not necessitate that the
peer has received any unflushed data in the kernel send buffers. Neither
does it flag cases where the peer may have crashed after the sender
performed the close(). Thus it is essential we have an app-defined
protocol to ensure delivery - this is where the EOS message comes in.
Motion senders send an EOS to the motion receiver. Then the receiver
closes the socket (and sent an optional 'stop' message), which is
detected by the sender in waitOnOutbound() by …

Introduce timeout to tcp ic teardown select loop

---

src/backend/access/common/memtuple.c

MemtupleBinding is column aligned by 4 or 8 bytes.
It can be set to 8 if we find an attribute's attalign is 'd' (8 bytes on
most machines), there is no need to check other attributes.
Add some comments about how to compute null bitmap entries space.

Break early when creating Memtuple binding from TupleDesc

---

src/bin/psql/describe.c
src/test/regress/expected/psql_gp_commands.out
src/test/regress/sql/psql_gp_commands.sql

IN GPDB7, we fill the storage type according to the access method
oid of the pg_am system catalog. Except the heap table and append
only table, we can't create correspond access method in pg_am for
other storage types. Just remove the fixme.

Resolve one GPDB_12_MERGE_FIXME in describe.c

---

src/bin/psql/describe.c

Fixes #13997 for 6X_STABLE branch.
Commit for master branch: e0f7833d10776610cffc5bae524161840924afb3
This patch adds support for describing auxiliary tables. e.g.,
```
postgres=# create table foo(i int) with (appendonly=true);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'i' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# create index on foo(i);
CREATE INDEX
postgres=# select blkdirrelid::regclass from pg_appendonly where relid = 'foo'::regclass;
blkdirrelid
----------------------------
pg_aoseg.pg_aoblkdir_16384
(1 row)
postgres=# \d+ pg_aoseg.pg_aoblkdir_16384 …
```

[6X][psql] Add support for describing auxiliary tables for ao table.

---

src/backend/utils/hyperloglog/gp_hyperloglog.c
src/include/utils/hyperloglog/gp_hyperloglog.h
src/test/regress/expected/gp_hyperloglog.out
src/test/regress/greenplum_schedule
src/test/regress/sql/gp_hyperloglog.sql

This patch helps remove redundant base64 encoding and decoding functions
in gp_hyperloglog.c and add test cases for gp_hyperloglog.
1. Postgres upstream provides the implementation of base64 encoding and
decoding utilities. The difference between Postgres's base64 and the
original base64 is that the original encoding function obeys the
76-character per-line rule (it inserts a `\n` to the encoded string
every 76-character). I think it doesn't matter whether to start a new
line every 76-characters and it's good to remove redundant codes.
2. Test cases for gp_hyperloglog are added in this patch (I don't know
why there isn't any test for it).

Improve gp_hyperloglog codes and add tests for it.

---

src/test/regress/expected/psql_gp_commands.out
src/test/regress/sql/psql_gp_commands.sql

pipeline failed with the log 'Table pg_am has a dependency issue on oid 152563 at content ...'.
The newly created access method in psql_gp_commands regress test is not cleaned up at the end. Then the gpcheckcat checked that the newly created object in pg_am catalog doesn't have a reference in pg_depend under objid or refobjid column, it will show a dependency issue.

Fix pipeline failure caused by psql_gp_commands test

---

src/test/isolation2/input/workfile_mgr_test.source
src/test/isolation2/output/workfile_mgr_test.source
src/test/isolation2/workfile_mgr_test.c

This is a backport of two commits from PR #12213 from 7X.
```
Wait until backend process exits in workfile_mgr isolation2 test
The test was sufferring from "q:" problem described in
https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/A2JUpJ0NrEA/m/3S6rmd2zBAAJ
This patch implements Ashwin's suggestion on that thread by
introducing retry logic.
```
and
```
Remove pointless sleep from legacy workfile_mgr_test
It reduces the test runtime by 1 minute.  It must have been a remnant
of an old refactor.  I couldn't find a justification for it in last
few years worth of commit history.
```

[6X backport] Workfile mgr test cleanup

---

gpMgmt/bin/gppylib/gparray.py
src/pl/plpython/expected/plpython_returns.out
src/pl/plpython/sql/plpython_returns.sql

%s/compatable/compatible/g in file gparray.py
Since initFromString is already compatible with repr() formatting, remove the TODO mark.
Search `compatable` globally and change them all to `compatible`.

[typo] compatable => compatible

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SEQUENCE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SEQUENCE.html.md

docs for https://github.com/greenplum-db/gpdb/pull/10612.
update the default value and add a note about consecutive values.

docs - default sequence cache size is 20

---

gpMgmt/bin/generate-greenplum-path.sh

Python3.9 is the dependency of the plpython3 extension, it is better to set the python3 ENV in the plpython3 script.
[GPR-1035]

Remove python3 ENV from `PATH` and `LD_LIBRARY_PATH`

---

gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

With latest commit #8e99ec3 it takes little longer to update sync status even when bytes to replicate are zero and leading to gpstate test failure. Current changes add To wait till segment replication status is in sync before calling gpstate. 
issue was seen after this changes: 
https://github.com/greenplum-db/gpdb/pull/13891
Testing: 
Ran the test localy and also created concourse pipeline.

gpstate behave test failure fix

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
src/backend/gporca/libgpopt/src/base/CKeyCollection.cpp
src/backend/gporca/libgpopt/src/base/CUtils.cpp
src/backend/gporca/libgpopt/src/xforms/CXformDifference2LeftAntiSemiJoin.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/test/regress/expected/union.out
src/test/regress/expected/union_optimizer.out
src/test/regress/sql/union.sql

There were a lot of asserts on NULL != target_list in the translator,
but most of them were unnecessary. Fix ORCA to handle empty target list.
Following SQL works:
```sql
EXPLAIN (COSTS OFF) SELECT UNION SELECT;
```

[ORCA] Allow empty target list

---

src/backend/cdb/motion/ic_tcp.c
src/test/isolation2/expected/tcp_ic_teardown.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/tcp_ic_teardown.sql

Cherry-picked from master commit: 06c05e5e48e
Minor Conflicts:
* Use older ereport syntax
* Use plpythonu instead of plpython3u
------------------------------------------------------------------------
Background:
1c1f16448ba introduced the waitOnOutbound() call for non-error cases as well during TCP IC teardown, after "Interconnect error: connection closed prematurely." ERRORs were seen in Azure environments. This is essential because performing a close() does not necessitate that the peer has received any unflushed data in the kernel send buffers. Neither does it flag cases where the peer may have crashed after the sender performed the close(). Thus it is essential we have an app-defined protocol to ensure delivery - this is where the EOS message comes …

[6X] Introduce timeout to tcp ic teardown select loop

---

src/backend/commands/explain.c
src/test/regress/expected/dpe_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/inherit_optimizer.out
src/test/regress/expected/orca_static_pruning_optimizer.out
src/test/regress/expected/partition_prune_optimizer.out

""GPDB_12_MERGE_FIXME: we used to show something along the lines of "Partitions selected: 1 (out of 5)" under the partition selector. By eleminating the (static) partition selector during translation, we only get the survivor count, and lose the size of the universe temporarily. However, if we manage to shift the static pruning information sufficiently adjacent to (or better, into) a DXL Dynamic Table Scan, we should be able to get that information back.""
Through this PR I am trying to pass the total partition information through ORCA and into the plan node used in explain.

Explain plan shows the number of leaf partitions for dynamic scans

---

gpcontrib/gp_exttable_fdw/gp_exttable_fdw--1.0.sql
gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

pg_exttable on gpdb7 is not consistent with gpdb6
This is the result of `\d pg_exttable` in gpdb6:
```
[gpadmin@localhost ~]$ psql
psql (9.4.26)
gpadmin=# \d pg_exttable
Table "pg_catalog.pg_exttable"
Column      |  Type   | Modifiers
-----------------+---------+-----------
reloid          | oid     | not null
urilocation     | text[]  |
execlocation    | text[]  |
fmttype         | "char"  |
fmtopts         | text    |
options         | text[]  |
command         | text    |
rejectlimit     | integer |
rejectlimittype | "char"  |
logerrors       | boolean |
encoding        | integer |
writable        | boolean |
Indexes:
"pg_exttable_reloid_index" UNIQUE, btree (reloid)
```
This is the result of `\d pg_exttable` in gpdb7:
```
[gpadmin@localhost ~]$ psql
psql …
```

change type of logerrors in pg_exttable from char to boolean

---

gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md

https://github.com/greenplum-db/gpdb/pull/14105 removed the gp_enable_sort_distinct guc from the code.  remove doc refs to this guc.

docs - remove refs to gp_enable_sort_distinct guc

---

src/backend/executor/execUtils.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

Executing a query that doesn't fetch all tuples from external scan that execute
program on coordinator leads to the next error:
ERROR:  external table table_master command ended with SHELL TERMINATED by
signal SIGPIPE (13)
DETAIL:  Command: execute:(echo foo; sleep 1; echo bar)
There are several cases when gpdb ends unfinished plan: extended protocol,
cursors. Greenplum communicate with shell command by pipe, it closes pipe while
shell command steel sends results. And SIGPIPE happens here. In such cases
if external web table is executed on segments, then it uses squelching
mechanics, that provides a separate way to handle unfinished yet plan nodes and
simply ignore SIGPIPE for externalScan. But the squelching doesn't execute
for master-only plans on coordinator. So the solution is …

ADBDEV-2982: SIGPIPE during ending not exhausted external table scan

---

gpMgmt/bin/gpcheckcat
src/test/regress/expected/psql_gp_commands.out
src/test/regress/sql/psql_gp_commands.sql

Creating AMs with internal handlers will not have entries in `pg_depend`, which is reasonable since internal handlers could not be dropped, but `gpcheckcat` is not happy with it.
This commit excludes that and fixes the `getName()` deprecated issue.

Exclude AMs with internal handlers in gpcheckcat dependency checks

---

src/test/regress/expected/qp_union_intersect.out
src/test/regress/expected/qp_union_intersect_optimizer.out
src/test/regress/sql/qp_union_intersect.sql

This test case has been flaky for a while, and while it's being worked on and discussed, it currently makes developers either ignore red tests or blocks other work from being merged. For now, add a FIXME and disable the test case for Orca.
Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/u3-D7isdvmM

Disable flaky qp_union_intersect test

---

src/backend/executor/nodeBitmapIndexscan.c

If a DynamicBitmapScan was under a NLJ, memory would increase very quickly and the system would soon terminate due to OOM. Additionally, performance was slower than an equivalent planner plan using regular Bitmap Scans. This only affected Orca as only Orca uses Dynamic Scans.
This change had been done for regular index scans, but was not done for bitmap scans.

Fix memory leak in Dynamic Bitmap Scans

---

src/backend/cdb/motion/ic_proxy.h
src/backend/cdb/motion/ic_proxy_addr.c
src/backend/cdb/motion/ic_proxy_backend.c
src/backend/cdb/motion/ic_proxy_client.c
src/backend/cdb/motion/ic_proxy_iobuf.c
src/backend/cdb/motion/ic_proxy_main.c
src/backend/cdb/motion/ic_proxy_peer.c
src/backend/cdb/motion/ic_proxy_pkt_cache.c
src/backend/cdb/motion/ic_proxy_router.c

This is a follow-up to 24140214f21, which was reverted for being too verbose by default, causing CI failures. This reintroduces the gp_log_interconnect GUC to ic-proxy logging and follows the specifications outlined in cdbvars.c. The ic_proxy_log macro is replaced with elog and elogif for WARNINGs/ERRORs and other events respectively.
The scheme used:
TERSE[LOG]:     Server main loop events, signals
VERBOSE[LOG]:   Startup, (un)register, close/shutdown, EOF receipt etc.
DEBUG[DEBUG1]:  Special packet (BYE/HELLO) transfer, pause/resume events
DEBUG[DEBUG3]:  Less interesting packet transfers, caching
DEBUG[DEBUG5]:  Very low-level tracing info
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/fix_proxy_logging

Revamp ic-proxy logging

---

src/backend/commands/tablecmds.c
src/test/regress/input/external_table.source
src/test/regress/output/external_table.source

The external tables have distribution policy but it does not dictate actual data distribution. It is only used when unloading data, to compare with source table's distribution policy:https://docs.vmware.com/en/VMware-Tanzu-Greenplum/6/greenplum-database/GUID-ref_guide-sql_commands-CREATE_EXTERNAL_TABLE.html#parameters . 
Therefore, when supporting ALTER TABLE SET DISTRIBUTED BY for external tables, we don't really need to re-organize the table but just need to make sure the catalog change happens.

Support ALTER TABLE SET DISTRIBUTED BY for external tables

---

src/bin/pg_dump/pg_backup.h
src/bin/pg_dump/pg_backup_db.c
src/bin/pg_dump/pg_dump.c
src/bin/pg_dump/pg_dumpall.c

Two conditionals in getTableSchema were testing remote version <= 90400
for GPDB5/6 specific code, which is a bug because it omits GPDB6 (90426)
altogether. This commit fixes the issue by defining and using a macro for
the exact GPDB6 Postgres version. Also cleans up some now unused functions.

pg_dump: Define macros for GPDB Postgres versions

---

src/backend/executor/nodeBitmapIndexscan.c

If a DynamicBitmapScan was under a NLJ, memory would increase very quickly and the system would soon terminate due to OOM. Additionally, performance was slower than an equivalent plan using regular Bitmap Scans. This only affected Orca as only Orca uses Dynamic Scans.
This change had been done for regular index scans, but was not done for bitmap scans.
(cherry picked from commit fe5f92b165bd135ebf5614630990df5cc4333f45)

[6X] Fix memory leak in DynamicBitmapScans

---

src/backend/access/transam/xlog.c
src/backend/access/transam/xlogarchive.c
src/test/gpdb_pitr/expected/test_mirror_wal_recycling.out
src/test/gpdb_pitr/sql/test_mirror_wal_recycling.sql
src/test/gpdb_pitr/test_gpdb_pitr.sh

When a mirror is running with archive_mode=on, it may incorrectly mark WAL segments as ready to be archived (".ready" file in the $datadir/pg_xlog/archive_status directory) when checking to see if any WAL segments can be recycled. This causes the marked WAL segment to never be recycled. It can also cause issues when the mirror is promoted and tries to start archiving WAL since the old stale WAL segment may already exist in the archive location.
To fix the issue, ignore the XLOG archive check when creating a restart point on a mirror segment. We really shouldn't be doing anything relating to WAL archiving on the mirror segment while it's in standby mode anyways since continuous WAL archiving for mirrors/standbys is not supported until its introduction in Postgres 9.5.
This patch was …

[6X_STABLE] Ignore XLOG archive check when creating restart point on mirror segment

---

src/backend/commands/typecmds.c

Whenever a new OID is needed for an object in PostgreSQL, the GetNewOidWithIndex() is used. In GPDB, all the upstream calls to GetNewOidWithIndex() function have been replaced with calls to the GetNewOidFor* functions.  
All the GetNewOidFor*() functions are actually just wrappers for the GetNewOrPreassignedOid() function, and only differ in the key arguments for each object type. GetNewOrPreassignedOid() does the heavy lifting. 
In GPDB Binary Upgrade, pg_upgrade records the OIDs from the old cluster and inserts them into a preassigned_oids list to restore them, which is then used to assign specific OIDs.
The AssignTypeArrayOid call is a wrapper for GetNewOidForType, which handles the OID preassignment, so no special code is needed.
See the comment at the top of …

Resolve FIXME in typecmds.c

---

src/bin/pg_upgrade/controldata.c
src/bin/pg_upgrade/greenplum/option_gp.c
src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
src/bin/pg_upgrade/option.c
src/bin/pg_upgrade/test_gpdb.sh

These flags are unused by gpupgrade and are safe to remove.

pg_upgrade: Remove flags to add/remove data checksums

---

README.CentOS.bash
README.Ubuntu.bash
README.macOS.bash

The conan package has been removed in commit
274c5411b8044147b3970338cf1b708a40e2ada9.
This patch helps remove that from README.[platform].bash scripts.

Remove references to conan from dependency installation scripts.

---

gpMgmt/bin/gpsd
gpMgmt/bin/minirepro
src/test/regress/expected/minirepro.out

This commit includes a couple improvements when dumping minirepros:
1. Dump the number of segments. This is needed to replicate the plan, and often we have to ask users/customers this separately. Instead just retrieve it during the minirepro
2. Output a `set optimizer=off` for when the minirepro is being restored. The short insert statements into pg_statistic/pg_class are much faster (~10X) using planner than Orca, especially if done in a debug buiild. Output this by default so I don't have to modify this manually.

Dump number of segments during minirepro

---

src/backend/access/aocs/aocs_compaction.c
src/backend/access/aocs/aocsam.c
src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonly_compaction.c
src/backend/access/appendonly/appendonlyam.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/catalog/gp_fastsequence.c
src/include/cdb/cdbaocsam.h
src/include/cdb/cdbappendonlyam.h
src/test/regress/greenplum_schedule
src/test/regress/input/uao_dml/gp_fastsequence.source
src/test/regress/output/appendonly.source
src/test/regress/output/uao_dml/gp_fastsequence.source

For multi-insert, our insert workflow already supports batched WAL and
there is no page locking by virtue of buffer cache bypass for AO/CO
relations. So there is not much to gain over the existing
call-single-insert-in-a-loop approach that we have. There is except for
optimizing gp_fastsequence in-place updates. This is described below:
For COPY, we know the number of tuples to be inserted for every
invocation of table_multi_insert(). Due to the sizing of the copy
buffer, we can call table_multi_insert() with #rows = 1000 in the best
case => which implies we can cut down on the number of in-place updates
by a factor of 10 in the best case(as we don't have to do 10 piecemeal
allocations of NUM_FAST_SEQUENCES each). This can give us a performance
boost, specially when we have concurrent …

COPY/CLUSTER: Use ntuples for gp_fastsequence allocation 

---

src/backend/commands/tablecmds.c
src/backend/commands/trigger.c
src/test/regress/expected/triggers.out
src/test/regress/sql/triggers.sql

Backport upstream commit 0e6b6f8c719. No merge conflict. This doesn't need tobe backported to 6X where ENABLE/DISABLE TRIGGER cannot be recursed at all.
Original commit message
-----------
More precisely, correctly handle the ONLY flag indicating not to recurse.  This was implemented in 86f575948c77 by recursing in trigger.c, but that's the wrong place; use ATSimpleRecursion instead, which behaves properly.  However, because legacy inheritance has never recursed in that situation, make sure to do that only for new-style partitioning.
I noticed this problem while testing a fix for another bug in the vicinity.
This has been wrong all along, so backpatch to 11.
Discussion: https://postgr.es/m/20201016235925.GA29829@alvherre.pgsql

Fix ALTER TABLE .. ENABLE/DISABLE TRIGGER recursion

---

src/backend/executor/nodeModifyTable.c
src/backend/rewrite/rewriteHandler.c
src/test/regress/expected/uao_catalog_tables.out
src/test/regress/expected/uaocs_catalog_tables.out
src/test/regress/sql/uao_catalog_tables.sql
src/test/regress/sql/uaocs_catalog_tables.sql

When the AO/CO auxiliary tables have data and a DELETE is called on them after setting allow_system_table_mods to on, the DELETE would fail due to assertion failure. The issue was that the rewrite handler and the executor did not know about AO/CO auxiliary tables so the junk filters were not being set up correctly like they would be if the AO/CO auxiliary tables were regular heap tables. To fix the issue, simply add logic to check for the AO/CO auxiliary table relkinds.
Issue was reported from gpupgrade team where this DELETE operation is done in the data migration scripts.

Fix errors when trying to DELETE FROM AO/CO auxiliary tables

---

src/backend/access/aocs/aocsam.c
src/backend/access/aocs/test/aocsam_test.c
src/backend/access/appendonly/appendonlyblockdirectory.c
src/backend/access/common/reloptions.c
src/backend/access/common/reloptions_gp.c
src/backend/access/gin/ginutil.c
src/backend/access/gist/gistutil.c
src/backend/executor/nodeBitmapHeapscan.c
src/include/access/reloptions.h

- Cherry-pick https://github.com/greenplum-db/gpdb/commit/d09c39cfcd45934ef796bf75566eb726d63b9874 from master branch. 
> Prevent memory leaks in parseRelOptions().
parseRelOptions() tended to leak memory in the caller's context.  Most
of the time this doesn't really matter since the caller's context is
at most query-lifespan, and the function won't be invoked very many times.
However, when testing with CLOBBER_CACHE_RECURSIVELY, the same relcache
entry can get rebuilt a *lot* of times in one query, leading to significant
intraquery memory bloat if it has any reloptions.  Noted while
investigating a related report from Tomas Vondra.
> In passing, get rid of some Asserts that are redundant with the one
done by deconstruct_array().
> As with other patches to avoid leaks in CLOBBER_CACHE …

[6X_STABLE]Fix several memory leaks

---

src/backend/libpq/be-secure.c

Some users reported a problem about libpq ssl in gpdb 5X_STABLE.
Users want to apply high level ssl algorithm such as 'ECDHE-RSA-AES256-GCM-SHA384', but they can not set it and take effect.
The original result is reproduced as followed:
```
[gpadmin@localhost gpseg-1]$ gpconfig -c ssl_ciphers -v 'ECDHE-RSA-AES256-GCM-SHA384'
20220923:18:07:55:015540 gpconfig:localhost:gpadmin-[INFO]:-completed successfully with parameters '-c ssl_ciphers -v ECDHE-RSA-AES256-GCM-SHA384'
[gpadmin@localhost gpseg-1]$  gpstop -ar
... ... ...
20220923:18:07:56:023550 gpstop:localhost:gpadmin-[INFO]:-Restarting System...
[gpadmin@localhost gpseg-1]$ psql -h 127.0.0.1
psql (8.3.23)
SSL connection (cipher: DHE-RSA-AES256-GCM-SHA384, bits: 256) 
gpadmin=#
```
Although we have set it as …

Support high security SSL encryption algorithms in libpq of 5X_STABLE

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

In GPDB, expression subquery is promoted to join, e.g. select * from T where a > (select 10*avg(x) from R where T.b=R.y); in postgres, the plan is:
```
QUERY PLAN
-----------------------------------------------------------------
Seq Scan on t  (cost=0.00..80364.30 rows=753 width=8)
Filter: ((a)::numeric > (SubPlan 1))
SubPlan 1
->  Aggregate  (cost=35.53..35.54 rows=1 width=32)
->  Seq Scan on r  (cost=0.00..35.50 rows=10 width=4)
Filter: (t.b = y)
```
while in GPDB, the subquery is promoted to join:
```
QUERY PLAN
---------------------------------------------------------------------------------------------
->  Hash Join  (cost=477.00..969.11 rows=9567 width=8)
Hash Cond: (t.b = "Expr_SUBQUERY".csq_c0)
Join Filter: ((t.a)::numeric > …
```

Fixed bug in legacy optimizer convert_EXPR_to_join (#14107) :

---

src/backend/access/aocs/aocs_compaction.c

The same value is assigned to the variable at the moment of declaration (some lines before)

Removed unnecessary variable assignment

---

src/backend/access/appendonly/aosegfiles.c
src/test/regress/expected/AORO_Compression.out
src/test/regress/sql/AORO_Compression.sql

Crash happened on Master when we call GET_AO_COMPRESSION_RATIO functions on partition table. 
```
postgres=# \d+;
List of relations
Schema |            Name             |       Type        |  Owner  | Storage |  Size   | Description 
--------+-----------------------------+-------------------+---------+---------+---------+-------------
public | test_table                  | partitioned table | gpadmin | heap    | 0 bytes | 
public | test_table_1_prt_123        | table             | gpadmin | heap    | 0 bytes | 
public | test_table_1_prt_cmp_202202 | table             | gpadmin | ao_row  | 128 kB  | 
(3 rows)
postgres=# select get_ao_compression_ratio(t.relid) from (select relid from pg_partition_tree('test_table') where isleaf != false) as t;
This …
```

FIX crash of GET_AO_COMPRESSION_RATIO on heap table 

---

gpdb-doc/markdown/admin_guide/expand/expand-planning.html.md

the docs currently state that greenplum supports both rebuild and move table redistribution methods, when in fact greenplum supports only the rebuild method.  
this PR updates the "Table Redistribution Method" topic to address only the rebuild method, and moves the topic both up a section level and a section.
note:  the git diff is kind weird, i did not update the "Managing Redistribution in Large-Scale Greenplum Systems" topic except to move the "Table Redistribution Method" subtopic out of it and up a level.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpxredist/greenplum-database/GUID-admin_guide-expand-expand-planning.html#tabred

docs - gpexpand uses a rebuild redistribution method

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_partition.xml
gpdb-doc/markdown/ref_guide/system_catalogs/pg_partition.html.md

The type of pg_partition.paratts should be int2 vector. This patch helps correct the documentation.
See:
```
postgres=# \d+ pg_partition;
Table "pg_catalog.pg_partition"
Column     |    Type    | Modifiers | Storage | Stats target | Description
---------------+------------+-----------+---------+--------------+-------------
parrelid      | oid        | not null  | plain   |              |
parkind       | "char"     | not null  | plain   |              |
parlevel      | smallint   | not null  | plain   |              |
paristemplate | boolean    | not null  | plain   |              |
parnatts      | smallint   | not null  | plain   |              |
paratts       | int2vector | not null  | plain   |              |  <---------- Here
parclass      | oidvector  | not null  | plain   | …
```

[6X][Doc] pg_partition.paratts's type should be int2vector.

---

src/backend/access/aocs/test/aocsam_test.c

We see unittest failure in pipeline:
FATAL:  (XX000) Unexpected internal error
DETAIL:  FailedAssertion("!(pointer != ((void *)0))", File: "mcxt.c", Line: 1291)
Unittest code forget to mock Relation->rd_rel->relnatts which is needed by core code (like aocs_addcol_init). Mock them to fix the unittest.
Co-author-by: Qing Ma <maqi@vmware.com>
-------
pipeline failure: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/6X_STABLE/jobs/compile_gpdb_sles12/builds/715
master branch does not have the code yet. 
-----
**Interesting that this only constantly fail on SLES, I have run a GCP of SLES 12 and run the unitest with the fix commit many times, all passed.**

(6x) Fix unittest aocsam_test.

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/executor/nodeModifyTable.c

This addresses a FIXME and performs the check in ExecInitModifyTable(), saving us an unnecessary dispatch round trip.

ao/co: Perform serializable isolation check early

---

src/backend/commands/tablecmds.c
src/test/regress/expected/alter_table.out
src/test/regress/expected/vacuum.out
src/test/regress/sql/alter_table.sql
src/test/regress/sql/vacuum.sql

In GPDB6 ALTER TABLE ... OWNER on partition root recurses into child tables. However, the upstream does not do the same and during merging, GPDB7 lost that behavior and became inconsistent with GPDB6.
We have decided to restore that behavior for GPDB7. We will support the 'ONLY' keyword for ALTER TABLE ... OWNER so that the user has the option to just alter the root, which will be done & verified with the 'ONLY' support for other commands altogether.
Have to adjust the vacuum test case after this change.
Discussion thread: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/ImJrvQEECwA

Make ALTER TABLE ... OWNER recurse by default

---

src/backend/gporca/libgpos/src/string/CWStringDynamic.cpp
src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp

We may hit this assertion error in some cases, see GPQP-74. Also removed assertion in CWStringDynamic::AppendBuffer, the assertion is useless, and extremely time-consuming, remove it to get faster optimizer in debug mode.

Comment out assertion in CBucket::SplitAndMergeBuckets

---

gpdb-doc/markdown/admin_guide/managing/maintain.html.md
gpdb-doc/markdown/ref_guide/gp_toolkit.html.md

docs for https://github.com/greenplum-db/gpdb/pull/13887.
describe the new gp_toolkit __gp_aoblkdir() function.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gptk/greenplum-database/GUID-ref_guide-gp_toolkit.html#gp_aoblkdirregclass

docs - new __gp_aoblkdir(regclass) gp_toolkit function

---

src/backend/commands/tablecmds.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

The issue is reported as https://github.com/greenplum-db/gpdb/issues/14186 .
This PR is a more proper way to fix this issue compared to https://github.com/greenplum-db/gpdb/pull/14187.
We should error out with wrong syntax into cause in AlterPartitionCmd, then the behavior could align with 7X branch.
```
postgres=# ALTER TABLE ao_test_spilt SPLIT PARTITION FOR ('2021-03-01') AT ('2021-03-02') INTO (PARTITION prt_20210301, default partition);
ERROR:  INTO can only have second partition by name
LINE 1: ...IT PARTITION FOR ('2021-03-01') AT ('2021-03-02') INTO (PART...
^
```
The current test cases have already covered this scenario, so I only updated the test answer files.

[6X only] Error out with wrong syntax into cause in AlterPartitionCmd.

---

src/backend/access/aocs/aocsam.c
src/backend/access/appendonly/appendonlyam.c
src/backend/access/heap/heapam.c
src/backend/executor/nodeDynamicSeqscan.c
src/include/access/heapam.h
src/include/cdb/cdbaocsam.h
src/include/cdb/cdbappendonlyam.h
src/test/regress/expected/bfv_partition_plans.out
src/test/regress/expected/bfv_partition_plans_optimizer.out
src/test/regress/sql/bfv_partition_plans.sql

The tables with high count of partitions can drain high amount of executor
memory for processing. This can be especially critical for column-oriented
tables, because we allocating a buffer (which is triple of block size) for each
column. Following the standard flow we free such buffers at executor end. But it
seems, we can safely free some structures, including this buffers, after
processing of each partition. To do this in the uniform way, new *_afterscan()
access methods introduced by this patch.
Related to #13725

Free underlying Dynamic Seq Scan structures after processing of each partition

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

This PR backports commit 6473bbf87786c697347293c08499378311eec8c5 from 7X.
In GPDB, expression subquery is promoted to join, e.g. select * from T where a > (select 10*avg(x) from R where T.b=R.y); in postgres, the plan is:
```
QUERY PLAN
-----------------------------------------------------------------
Seq Scan on t  (cost=0.00..80364.30 rows=753 width=8)
Filter: ((a)::numeric > (SubPlan 1))
SubPlan 1
->  Aggregate  (cost=35.53..35.54 rows=1 width=32)
->  Seq Scan on r  (cost=0.00..35.50 rows=10 width=4)
Filter: (t.b = y)
```
while in GPDB, the subquery is promoted to join:
```
QUERY PLAN
---------------------------------------------------------------------------------------------
->  Hash Join  (cost=477.00..969.11 …
```

[6X] Fix incorrect sortOp and eqOp generated by IsCorrelatedEqualityOpExpr.

---

src/backend/access/appendonly/aosegfiles.c
src/test/regress/expected/AORO_Compression.out
src/test/regress/sql/AORO_Compression.sql

Crash happened on Master when we call GET_AO_COMPRESSION_RATIO functions on partition table. 
```
postgres=# \d+;
List of relations
Schema |            Name             |       Type        |  Owner  | Storage |  Size   | Description 
--------+-----------------------------+-------------------+---------+---------+---------+-------------
public | test_table                  | partitioned table | gpadmin | heap    | 0 bytes | 
public | test_table_1_prt_123        | table             | gpadmin | heap    | 0 bytes | 
public | test_table_1_prt_cmp_202202 | table             | gpadmin | ao_row  | 128 kB  | 
(3 rows)
postgres=# select get_ao_compression_ratio(partitionschemaname||'.'||partitiontablename) from pg_partitions WHERE tablename IN('test_table'); …
```

Fix crash of GET_AO_COMPRESSION_RATIO on heap table

---

src/backend/utils/time/snapmgr.c
src/test/isolation2/expected/export_distributed_snapshot.out
src/test/isolation2/sql/export_distributed_snapshot.sql

This PR is trying to fix the issue #14177. Because 6X-STABLE is still using the 
`DistributedTransactionTimeStamp` to check the visibility, which 7.0-Alpha has 
removed this filed from `DistributedSnapshot` in PR #10910. 
In 6X-STABLE, we will not write the distributed snapshot's timestamp into snapshot 
files, it just like:
```
smart@stable: qddir/demoDataDir-1/pg_snapshots$ cat 000002DF-1
xid:735
dbid:12812
iso:2
ro:1
xmin:735
xmax:735
xcnt:0
sof:0
sxcnt:0
rec:0
dsxminall:5
dsid:12
dsxmin:5
dsxmax:5
dsxcnt:0
``` 
So in the function `ImportSnapshot()` we could not get the value of timestamp in QD, 
then there is no way to serialize this value and pass it to QE, so this value will be 0 in 
QE, and will lead to the wrong judgment of visibility.
This PR adds the value of …

[6X-Only] fix up the lack of timestamp when we import snapshot

---

src/backend/cdb/cdbsubselect.c
src/backend/optimizer/plan/subselect.c
src/include/cdb/cdbsubselect.h
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

In GP7's convert_ANY_sublink_to_join(), there is no simplification of origin subquery, as a result sometimes the sublink cannot be pulled up, which produced a bad query plan. In GP5, there is a subquery simplify step which helped sublink pull-up:
```
/* Delete ORDER BY and DISTINCT. */
cdbsubselect_drop_orderby(subselect);
cdbsubselect_drop_distinct(subselect);
```
As only simple sub-query is allowed to be pulled up:
```
/*
* Under certain conditions, we cannot pull up the subquery as a join.
*/
if (!is_simple_subquery(root, subselect, NULL, NULL))
return NULL;
```
Take a look at the following query case:
```
EXPLAIN SELECT rmv_1.cover_no,
rmv_1.period_no,
rmv_1.risk_no,
rmv_1.risk_period_no,
rmv_1.location_ext_no,
rmv_1.source_system
FROM ctx.gis_risk_mv rmv_1
WHERE ((rmv_1.cover_no, …
```

Simplify IN subquery for sublink pullup. 

---

src/backend/access/appendonly/appendonlyblockdirectory.c

remove unused variable `groupNo` In function `AppendOnlyBlockDirectory_End_forSearch`.
```
appendonlyblockdirectory.c: In function 'AppendOnlyBlockDirectory_End_forSearch':
appendonlyblockdirectory.c:1448:8: warning: unused variable 'groupNo' [-Wunused-variable]
int   groupNo;
^
```

fix compiler warning in appendonlyblockdirectory.c

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp

Issue:
Regression in GPDB compatibility with PostGIS. Exception hit by NULL Datum pointer.
Root cause:
While implementing support for composite type returning TVF, we didn't factor in unsupported PostGIS functions.
Solution:
Patch 394c0586db. While translating query to DXL, check if the const value of TVF is NULL. If so, fall back on planner.
Implementation:
[CTranslatorQueryToDXL] -- Raise exception if the const value of TVF cannot be populated

Patch handling of composite type returning TVF that evaluates to const

---

src/backend/commands/resgroupcmds.c
src/backend/utils/resgroup/resgroup.c
src/include/utils/resgroup.h
src/test/isolation2/expected/resgroup/resgroup_syntax.out
src/test/isolation2/input/resgroup/resgroup_cpuset.source
src/test/isolation2/output/resgroup/resgroup_cpuset.source
src/test/isolation2/sql/resgroup/resgroup_syntax.sql

New SYNTAX of resource group cpuset for different master and segment
Using syntax like cpuset="1;3-4" could different cpuset of master and segment by semicolon.  For example,
if we define cpuset="1;3-4", then master will use the first  cpu core, segments will use third  and fourth core.
CREATE and ALTER resource group support this new syntax.
```
postgres=# CREATE RESOURCE GROUP rg1 WITH (cpuset='1;2-3');
CREATE RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset 
-----------+--------
rg1       | 1;2-3
(1 row)
postgres=# ALTER resource group rg1 SET cpuset '4;5-6';
ALTER RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset …
```

NEW SYNTAX of resource group cpuset

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
gpMgmt/test/behave/mgmt_utils/environment.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py

gprecoverseg, gpmovemirrors should show warning and gpexpand should raise an exception if there is already a running instance of pg_basebackup for the segment that needs to be recovered/moved.
How this issue was produced:
- gprecoverseg -F was called to bring up down segments
- This gprecoverseg call was interrupted because of a disconnected putty session
- Because of this, the main gprecoverseg process was killed but the background pg_basebackup process was still running
- After this, gprecoverseg -F was run multiple times, all of which failed because of multiple parallel basebackup processes running per segment.
- One of the gprecoverseg ran till completion before running any other gprecoverseg operation. Once this basebackup process was finished, the background code also automatically …

Error out if any segment has a running basebackup

---

src/backend/catalog/aclchk.c
src/backend/parser/gram.y
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/input/tablespace.source
src/test/regress/output/tablespace.source
src/test/regress/sql/partition.sql

Historically in GPDB6, when executing GRANT/REVOKE on a partition root, we will recurse into its child tables. We have decided to keep this behavior for 7X, but to also support the ONLY keyword so that users can choose to grant/revoke just the partition root, without recursion. The syntax is e.g.:
```
GRANT SELECT ON ONLY foo_par TO role;
```
Similarly, for other commands like ALTER TABLE SET TABLESPACE we will do the same. However, since the ONLY keyword has been implicitly supported for ALTER TABLE, we just need to add test coverage.
Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/ImJrvQEECwA

Support ONLY keyword for GRANT/REVOKE and add test coverage for ALTER TABLE SET TABLESPACE

---

src/test/regress/expected/join_hash.out
src/test/regress/expected/join_hash_optimizer.out
src/test/regress/sql/join_hash.sql

The case is to test some code path during parallel hash join
but Greenplum does not support Postgres' parallel plan.
Changes the FIXME to a NOTE.

Change FIXME to note in join_hash case.

---

src/test/regress/expected/arrays.out
src/test/regress/expected/bfv_index.out
src/test/regress/expected/bfv_index_optimizer.out
src/test/regress/sql/arrays.sql
src/test/regress/sql/bfv_index.sql

Commit 5f168fa5f already fix non-default collation fallbacks of
ORCA then we can remove some related FIXMEs.
NOTE: the one in select_parallel still fallback to planner due to
non default collate, we should take a look at it later.

Remove already fixed non-default collate orca fallback in test.

---

src/backend/storage/ipc/procarray.c
src/backend/utils/time/snapmgr.c
src/include/storage/procarray.h

The name of UpdateSerializableCommandId is a bit wrong, now that SERIALIZABLE and REPEATABLE READ are not the same. From comparison, the if-check above was changed from checking IsXactIsoLevelSerializable to IsolationUsesXactSnapshot().
This commit renames it and resolves that GPDB_91_MERGE_FIXME.
commit 5eb15c9942a9bd6aaf712f2ab6175005e035168a
Author: Joe Conway <mail@joeconway.com>
Date:   Sat Sep 11 18:38:58 2010 +0000
SERIALIZABLE transactions are actually implemented beneath the covers with
transaction snapshots, i.e. a snapshot registered at the beginning of
a transaction. Change variable naming and comments to reflect this reality
in preparation for a future, truly serializable mode, e.g.
Serializable Snapshot Isolation (SSI).
For the moment transaction snapshots are still used to …

Rename UpdateSerializableCommandId() to UpdateCommandIdInSnapshot()

---

gpMgmt/bin/gpload_test/gpload2/TEST_local_config.py

If OS user that installed gpdb cluster is not gpadmin, gpload regression case#50 would be fail since it specified a hard code user gpadmin. To fix it, we need to use PGUSER instead.

Fix gpload regress case failure when OS user is not gpadmin

---

src/backend/executor/nodeModifyTable.c
src/backend/rewrite/rewriteHandler.c
src/test/regress/expected/uao_catalog_tables.out
src/test/regress/expected/uaocs_catalog_tables.out
src/test/regress/sql/uao_catalog_tables.sql
src/test/regress/sql/uaocs_catalog_tables.sql

When the AO/CO auxiliary tables have data and a DELETE is called on them after setting allow_system_table_mods to on, the DELETE would fail due to assertion failure. The issue was that the rewrite handler and the executor did not know about AO/CO auxiliary tables so the junk filters were not being set up correctly like they would be if the AO/CO auxiliary tables were regular heap tables. To fix the issue, simply add logic to check for the AO/CO auxiliary table relkinds.
Issue was reported from gpupgrade team where this DELETE operation is done in the data migration scripts.
Merge conflicts:
* USING ao_row/ao_column doesn't exist in 6X so replaced with the old WITH (appendonly=true) and WITH (appendonly=true, orientation=column).
* gp_toolkit.__gp_aoblkdir() does not exist so replaced with …

[6X backport] Fix errors when trying to DELETE FROM AO/CO auxiliary tables

---

src/backend/access/transam/xact.c
src/test/regress/expected/catcache.out
src/test/regress/expected/catcache_optimizer.out
src/test/regress/expected/qp_union_intersect.out
src/test/regress/expected/qp_union_intersect_optimizer.out
src/test/regress/greenplum_schedule
src/test/regress/sql/catcache.sql
src/test/regress/sql/qp_union_intersect.sql

In AbortTransaction, Postgres does not need to tell other backend to
invalidate catcache because the change is invisible. However,
Greenplum's MPP architecture has writer gang, reader gangs and gangs
can be reused in the same session. Only writer gang can modify
catalogs, thus in Greenplum we have to tell other backends (reader
gangs) when abort transaction.
Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/u3-D7isdvmM
Authored-by: David Kimura <dkimura@vmware.com>

Invalidate CatCache in AbortTransaction to clear reader gang's cache.

---

src/backend/cdb/cdbsubselect.c
src/backend/optimizer/plan/subselect.c
src/include/cdb/cdbsubselect.h
src/test/regress/expected/join_gp.out
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/expected/rpt.out
src/test/regress/expected/subselect.out
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/expected/subselect_optimizer.out
src/test/regress/sql/subselect_gp.sql

This is a backport of master PR #14258 & #14322.
In GP6's convert_ANY_sublink_to_join(), there is no simplification of origin subquery, as a result sometimes the sublink cannot be pulled up, which produced a bad query plan. In GP5, there is a subquery simplify step which helped sublink pull-up:
```
/* Delete ORDER BY and DISTINCT. */
cdbsubselect_drop_orderby(subselect);
cdbsubselect_drop_distinct(subselect);
```
As only simple sub-query is allowed to be pulled up:
```
/*
* Under certain conditions, we cannot pull up the subquery as a join.
*/
if (!is_simple_subquery(root, subselect, NULL, NULL))
return NULL;
```
Take a look at the following query case:
```
EXPLAIN SELECT rmv_1.cover_no,
rmv_1.period_no,
rmv_1.risk_no,
rmv_1.risk_period_no,
rmv_1.location_ext_no,
rmv_1.source_system
FROM …
```

[6X backport] Simplify IN subquery for sublink pullup.

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/notin.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/sql/notin.sql

The crash happened in not-in pullup sublink optimization, Param has been ignored when check non-nullable of not-in exprs. Like example below:
```
update
t1p
set
a = age.aging
from
(
select
c,
(
select
diff
from
generate_series(1, 10) diff
where
(diff, **t1p.b**) not in (select a, b from t2p)
) as aging
from
t1p
) age
where a = age.c;
```
aging is target-sublink in age subquery which is from UPDATE from clause, and _t1p.b_ is from table t1p in age subquery, so we could call _t1p.b_ as  correlated column. Steps optimization of this sql as below
- age subquery will be pull up, and table t1p in age subquery will be pulled up in UPDATE level.
- handle sublink aging, optimize not-in
As optimizing not-in sublink in step two, we still handle t1p.b in aging level. But it's param from upper level …

Fix crash of not-in pullup sublink with Params

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_DEFAULT_PRIVILEGES.html.md
gpdb-doc/markdown/ref_guide/sql_commands/GRANT.html.md
gpdb-doc/markdown/ref_guide/sql_commands/REVOKE.html.md

this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. i don't believe there was any greenplum-specific content in the original (v6) pages.
doc review site link for ALTER DEFAULT PRIVILEGES (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-privs/greenplum-database/GUID-ref_guide-sql_commands-ALTER_DEFAULT_PRIVILEGES.html

docs - update sql ref pages for ALTER DEFAULT PRIVS, GRANT, REVOKE

---

gpcontrib/gp_replica_check/Makefile
gpcontrib/gp_replica_check/gp_replica_check.c
gpcontrib/gp_replica_check/gp_replica_check.py

```
gp_replica_check: resolve FIXMEs
FIXMEs were related to adding support for checking dynamic access
methods. Given we are far away from supporting all built-in access
methods, dynamic support is not on the radar at all. Plus, having a new
access method is not a common act at all. So, we can cross the bridge of
converting RelationTypeData to a dynamic array instead of the static
array when we get there. Hence, for now, resolving the FIXME by
manually updating the static array to reflect all the current access
methods.
Note: with this change now "ao" gets split into ao_row and
ao_column. This is nice as can run more granular checking if desired.
Also, converted GPDB_94_MERGE_FIXME to GPDB_FEATURE_NOT_SUPPORTED in
Makefile. As we are yet to test/validate/enable this tool for various
index …
```

Resolving few FIXMEs from gp_replica_check

---

src/backend/libpq/be-secure.c

Current OpenSSL code includes a BIO_clear_retry_flags() step in the sock_write() function.  Either we failed to copy the code correctly, or they added this since we copied it.  In any case, lack of the clear step appears to be the cause of the server lockup after connection loss reported in bug 8647 from Valentine Gogichashvili.  Assume that this is correct coding for all OpenSSL versions, and hence back-patch to all supported branches.
Diagnosis and patch by Alexander Kukushkin.

[5X] Clear retry flags properly in replacement OpenSSL sock_write function.

---

gpcontrib/gp_exttable_fdw/Makefile

PXF external-table is dependent on `fileam.h`. In GP7, this file is renamed to `extaccess.h` and when we install the gpdb, the header file is not copied to `$GPHOME/include/postgresql/server/extension/gp_exttable_fdw`. 
By adding this `HEADERS` flag in the Makefile, the header file will get copied to the `gp_exttable_fdw` extension and can be referenced in the PXF code.

Make headerfile  extaccess.h accessible to pxf extension

---

src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
src/backend/gporca/libgpos/src/string/CWStringDynamic.cpp
src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp

For the following case:
```go
T join PT1 on func(T.a) = PT1.a join PT2 on func(T.a) = PT2.a
HashJoin1
+-- Dynamic Scan on PT1
+-- Hash
+-- HashJoin2
+-- Seq Scan on T
+-- Hash
+-- Dynamic Scan on PT2
```
When HashJoin2 computes the required partition propagation spec for inner child dynamic scan on PT2, it may not be able to find the partition keys for dynamic scan id 1 (pdrgppartkeys is NULL), the server crashes with null pointer error. This patch fixes that issue by adding a NULL check.
Comment out assertion in CBucket::SplitAndMergeBuckets, because we may hit this assertion error in some cases. Also removed assertion in CWStringDynamic::AppendBuffer, the assertion is useless, and extremely time-consuming, remove it to get faster optimizer in debug mode.
Ref: GPQP-80
I can't reproduce …

Fix bug that Orca may crash on null pointer in case of DPE with dynamic partial scan

---

src/backend/rewrite/rewriteHandler.c
src/backend/tcop/postgres.c
src/backend/utils/adt/gp_dump_oids.c
src/include/nodes/parsenodes.h
src/include/tcop/tcopprot.h
src/test/regress/expected/gp_dump_query_oids.out
src/test/regress/sql/gp_dump_query_oids.sql

Previously, when using minirepro on a query that accessed materialized views, the object that the materialized view used/accessed were not dumped with the minirepro. This is because queries themselves treat materialized views as tables, not views. However, when enumerating the dependent objects for dumping the relevant DDL, we need to treat materialized views as regular views.
This commit sets a flag when dumping from gp_dump_query_oids so that materialized views are treated as regular views when parsing the query.
(cherry-picked from eedd5ff94edc137abe75ebe16b094bd977345435)

[6X] Fix dependency bug with minirepro and materialized views (#14223)

---

src/backend/gporca/data/dxl/minidump/DirectDispatch-GpSegmentId-MultiCol-Conjunction.mdp
src/backend/gporca/data/dxl/minidump/DirectDispatch-GpSegmentId-SingleCol-Conjunction.mdp
src/backend/gporca/libgpopt/include/gpopt/base/CConstraint.h
src/backend/gporca/libgpopt/include/gpopt/base/CConstraintConjunction.h
src/backend/gporca/libgpopt/include/gpopt/base/CConstraintInterval.h
src/backend/gporca/libgpopt/src/base/CConstraintConjunction.cpp
src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
src/test/regress/expected/direct_dispatch.out
src/test/regress/expected/direct_dispatch_optimizer.out
src/test/regress/sql/direct_dispatch.sql

Probelm:
ORCA failed to do direct dispatch when filtering gp_segment_id on conjunction constraints
setup :
#create table foo (a int);
#explain select * from foo where gp_segment_id=0 and a between 1 and 10;
Sol:
-- This PR filterts the gp_segment_id on constraints with conjunction
-- Tries to do direct dispatch if finds gp_segment_id in constraint.
NOTE: code changes back-ported from master fefb41757491b0ef96cefc790baa3d1e1b56882c

[6X] Allow direct dispatch when filtering on gp_segment_id

---

src/bin/pg_dump/pg_dump.c

cef5b96ea89f532929ee92b994d283d7ef3817d1 introduced a bug where external partition tables were not being properly dumped, causing failures on subsequent restores.
Correctly set the relname and dump flag for partition children that are also external tables.
Reported by @xiaoxiaoHe-E

pg_dump: Fix regression with dumping external leaf partition tables

---

src/backend/executor/instrument.c
src/backend/executor/test/Makefile
src/backend/executor/test/instrument_test.c

gp_gettmid() is using PgStartTime as the startup timestamp which is wrong. 
Use timestamptz_to_time_t to get the correct timestamp.

Fix gp_gettmid() to return the correct gpdb startup timestamp

---

src/backend/gpopt/translate/CTranslatorUtils.cpp
src/include/gpopt/translate/CTranslatorUtils.h
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/groupingsets_optimizer.out
src/test/regress/expected/orca_groupingsets_fallbacks_optimizer.out
src/test/regress/expected/tsrf.out
src/test/regress/expected/tsrf_optimizer.out
src/test/regress/sql/tsrf.sql

This builds on the work of commit https://github.com/greenplum-db/gpdb/commit/df3ce784285f7d9ceccfa761fd790ece65b65cde to implement CUBE.
Following now works in ORCA:
```sql
EXPLAIN (COSTS OFF) SELECT i FROM generate_series(1, 3) i GROUP BY CUBE(i, i);
```
Note: Current optimization time for CUBE is slow. Seems ORCA is
generating many alternatives. Look into if this can be reduced.

[ORCA] Enable CUBE result grouping set 

---

src/backend/commands/vacuum.c
src/test/regress/expected/uao_compaction/index_stats.out
src/test/regress/expected/uaocs_compaction/index_stats.out
src/test/regress/sql/uao_compaction/index_stats.sql
src/test/regress/sql/uaocs_compaction/index_stats.sql

This is backporting (https://github.com/greenplum-db/gpdb/pull/14260).
* IndexVacuumInfo.analyze_only was not initialized, leading to possible no-ops in index_vacuum_cleanup(), if the garbage value for it was non-zero.
* IndexVacuumInfo.num_heap_tuples should be set to the AO table's old reltuples value (value prior to kicking off vacuum). Please see IndexVacuumInfo and lazy_vacuum_index() for details. As explained in the code comments, num_heap_tuples will always be an estimate during ambulkdelete(). Since dedd407, we have been using the index rel's reltuples instead. This is wrong (eg in scenarios where the index has been created post data manipulation). So, correctly use the table's reltuples value to provide the estimate.

[6X] vacuum_appendonly_index: Fix IndexVacuumInfo initialization

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_GROUP.html.md
gpdb-doc/markdown/ref_guide/sql_commands/ALTER_ROLE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/ALTER_USER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_GROUP.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_ROLE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_USER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_GROUP.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_USER.html.md

this PR updates the listed sql command reference pages to align with the postgres v12 ref page content.  existing greenplum-specific content on the CREATE/ALTER role pages includes RESOURCE QUEUE and RESOURCE GROUP clauses and examples
questions:  
1.  do  the `ALTER ROLE <role_name> RESOURCE QUEUE {<queue_name> | NONE}`, and `ALTER ROLE <role_name> RESOURCE GROUP {<group_name> | NONE}` commands allow `<role_name>` to be `CURRENT_USER` or  `SESSION_USER`?  (i'll try to bring up a greenplum 7 cluster and test this out.)
2. postgres 12 ref pages did not include `DENY`-related clauses.  are these greenplum additions that i should add back in?
doc review site link for ALTER GROUP (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/s …

docs - update sql ref pages for GROUP/ROLE/USER commands

---

gpMgmt/bin/generate-greenplum-path.sh

Load an external environment variable from '$GPHOME/etc/environment.d/'. The name of the configuration must be '\d\d-\w*\.conf'. Adding two numeric prefixes in front of the file name simplifies the ordering.
For example:
```
etc/environment.d/
- 00-overload-openssl.conf
- 10-add-python-path-gpdb.conf
- 90-add-rlib.conf
- 90-load-pfx-path.conf
- some_bad_file
```
The order of loading will be an ascending numerical order, in this case it will be 00, 10 and then 90, the order between two 90's is undefined. files without .conf suffix will not be loaded.
The format and file path are from systemd, which is already widely used in most Linux systems.
https://www.freedesktop.org/software/systemd/man/environment.d.html
Use case:
Some extensions need an additional environment variable to boot up, …

Loading environment variable from etc/environment.d

---

src/backend/optimizer/prep/prepunion.c
src/test/regress/expected/with_clause.out

The effort was duplicated with set_append_path_locus(), which is called
from create_append_path(). Let's just let set_append_path_locus() deal
with it.

Remove unnecessary code that dealt with locus of UNION plans.

---

src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out
src/test/regress/sql/partition.sql

Adding test coverage for the inheritance behavior of various table properties in a partition hierarchy. Note that some cases might have been covered already by existing tests. But for better organization and easier to reviewing, we add a new test section to the partition regress test and include all cases besides tablespace.
For tablespace, it requires setting up custom tablespace which needs the test file to be in input/output dirctory for the tablespace name transformation. Since it is already covered by the regress/tablespace test, we don't include in this new partition test section.
One FIXME is left for triggers that behaves differently between partitions created from table creation syntax and the subpartition template.
Discussion: …

Add test coverage for the partition inheritance behavior

---

src/bin/pg_dump/pg_dump.c
src/test/regress/expected/pg_dump_binary_upgrade.out
src/test/regress/greenplum_schedule
src/test/regress/sql/pg_dump_binary_upgrade.sql

External tables with dropped columns failed to upgrade with:
```
pg_restore: creating EXTERNAL TABLE ext_upgrade_failure_test
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 237; 1259 18142 EXTERNAL TABLE ext_upgrade_failure_test gpadmin
pg_restore: [archiver (db)] could not execute query: ERROR:  syntax error at or near ","
LINE 14:     "........pg.dropped.1........" ,
^
```
Fix pg_dump to output the ALTER TABLE DROP COLUMN DDL for external tables with dropped columns.
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/pgDumpExternalTables_7X_dev

pg_dump: fix upgrading external tables with dropped cols

---

src/bin/pg_dump/pg_dump.c
src/test/regress/expected/pg_dump_binary_upgrade.out
src/test/regress/sql/pg_dump_binary_upgrade.sql

External tables with dropped columns failed to upgrade with:
```
pg_restore: creating EXTERNAL TABLE ext_upgrade_failure_test
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 237; 1259 18142 EXTERNAL TABLE ext_upgrade_failure_test gpadmin
pg_restore: [archiver (db)] could not execute query: ERROR:  syntax error at or near ","
LINE 14:     "........pg.dropped.1........" ,
^
```
Fix pg_dump to output the ALTER TABLE DROP COLUMN DDL for external tables with dropped columns.
7X PR: https://github.com/greenplum-db/gpdb/pull/14355
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/pgDumpExternalTables_6X_dev

[6X backport] pg_dump: fix upgrading external tables with dropped cols

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SERVER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SERVER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_SERVER.html.md

this PR updates the listed sql command reference pages to align with the postgres v12 ref page content.  the CREATE page includes content describing the greenplum-specific mpp_execute and num_segments options, i've retained this info.
(no review site, changes are pretty self-explanatory.)

docs - update sql ref pages for ALTER/CREATE/DROP SERVER

---

src/backend/commands/tablecmds.c
src/test/regress/expected/partition_locking.out
src/test/regress/expected/partition_locking_optimizer.out

In commit 0ae9dce7b54f313b88c8306d0640cb45fbebb34c we open table in DefineRelation with AccessShareLock to read its reloptions. But we close it with AccessExclusiveLock which would inadvertently release the AccessExclusiveLock we already held. Fix it now.

Fix a wrong unlock mode in DefineRelation

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/access/heap/heapam_handler.c
src/backend/commands/copy.c
src/backend/commands/createas.c
src/backend/commands/matview.c
src/backend/commands/tablecmds.c
src/backend/executor/execPartition.c
src/backend/executor/nodeModifyTable.c
src/include/access/tableam.h
src/include/cdb/cdbaocsam.h
src/include/cdb/cdbappendonlyam.h

This PR does minor refactors to the DML state machinery, and lifts core FIXMEs surrounding this area, in addition to formally adding tableAM support for DML state initialization/teardown.

aoco: Refactor DML state machinery

---

src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
src/backend/gporca/libgpos/server/src/unittest/gpos/common/CBitSetTest.cpp
src/backend/gporca/libgpos/src/common/CBitSet.cpp

There was a corner case where intersecting a bitset A with bitset B, where A had elements in a vector that did not exist in B, would cause bitset A to have a size of 0, but still have a bitvector. This was an undefined and unexpected state. We assume that bitvectors in a bitset are non-empty, and breaking this assumption causes operations such as Equals() and Contains() to produce wrong results. In this case, it led to Orca failing to produce a plan since required columns did not satisfy the Contains() method.
This is a VERY hot codepath, bitset operations are heavily used in Orca and isEmpty requires iterating through the bitvector. I ran this through some performance tests and didn't see any decrease in performance.

Fix CBitSet Intersection logic in Orca

---

gpdb-doc/markdown/admin_guide/query/topics/json-data.html.md
gpdb-doc/markdown/ref_guide/function-summary.html.md

doc new support for SQL/JSON, jsonpath.  in this PR:
- ported the postgres 12 json function/operators content located on https://www.postgresql.org/docs/12/functions-json.html; also reviewed the existing content int the JSON section and updated where necessary.
- ported the postgres 12 json types content located on https://www.postgresql.org/docs/12/datatype-json.html; also reviewed existing content on that page and updated where necessary.
- the json function/operators tables were duplicated on the json types page, likely from a conref before we migrated to markdown.  i removed this duplicate content.
- for some of the new tables, i copied the html from postgres.
questions:
1.  the docs reference the jsonb_plperl and jsonb_plpython contrib modules - do we have plans to build/deliver them …

docs - add content for jsonpath, SQL/JSON path language

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_CONFIGURATION.html.md
gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_DICTIONARY.html.md
gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TEXT_SEARCH_TEMPLATE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_CONFIGURATION.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_DICTIONARY.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_PARSER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TEXT_SEARCH_TEMPLATE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_CONFIGURATION.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_DICTIONARY.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_PARSER.html.md
gpdb-doc/markdown/ref_guide/sql_commands/DROP_TEXT_SEARCH_TEMPLATE.html.md

this PR updates the following sql command reference pages to align with the postgres v12 ref page content:
- ALTER/CREATE/DROP TEXT SEARCH CONFIGURATION
- ALTER/CREATE/DROP TEXT SEARCH DICTIONARY
- ALTER/CREATE/DROP TEXT SEARCH PARSER
- ALTER/CREATE/DROP TEXT SEARCH TEMPLATE
i didn't notice any greenplum-specific content on the pages.  most of the changes are minor edits or formatting fixes.

docs - update sql ref pages for TEXT SEARCH-related commands

---

src/test/regress/greenplum_schedule

Grouping them with the other uao_dml tests led to flakes. Move them to a new group.
Heed the words of wisdom:
"These tests use gp_select_invisible and VACUUM, and will get confused if there are concurrent transactions holding back the global xmin."

ao/co: Move unique index DML tests to new group

---

src/backend/access/nbtree/nbtree.c
src/backend/cdb/dispatcher/cdbdispatchresult.c
src/backend/commands/vacuum.c
src/backend/commands/vacuum_ao.c
src/include/cdb/cdbdispatchresult.h
src/include/commands/vacuum.h
src/test/regress/expected/btree_index.out
src/test/regress/expected/uao_compaction/index_stats.out
src/test/regress/expected/uaocs_compaction/index_stats.out
src/test/regress/sql/btree_index.sql
src/test/regress/sql/uao_compaction/index_stats.sql
src/test/regress/sql/uaocs_compaction/index_stats.sql

Commit 1: fix unpredictable behavior during AO index vacuum
This is a backport of 6X https://github.com/greenplum-db/gpdb/pull/14260
Commit 2: Fix incorrect index->reltuples after VACUUM
Given the scenario of updating stats during VACUUM:
1) coordinator vacuums and updates stats of its own;
2) then coordinator dispatches vacuum to segments;
3) coordinator combines stats received from segments
to overwrite the stats of its own.
Because upstream introduced a feature which could skip
full index scan uring cleanup of B-tree indexes when
possible (refer to: https://github.com/postgres/postgres/commit/857f9c36cda520030381bd8c2af20adf0ce0e1d4),
there was a case in QD-QEs distributed deployment that
some QEs could skip full index scan and stop updating
statistics, resulting in QD being unable to …

Fix incorrect index->reltuples after VACUUM

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c

Unique index checks use SNAPSHOT_DIRTY, which is stack allocated and a
new snapshot object is passed always to table_index_fetch_tuple_check().
While this is fine for heap, for AO/CO tables, we persist this stack
allocated object in the unique check descriptor's block directory and
visimap data structures, which are palloced. This leads to nasty memory
trespassing, resulting in segfaults.
Remedy this by deferring the metadata snapshot assignment to
index_fetch_tuple_exists(), just before the block directory and visimap
are scanned.
This should help fix the prod CI.
Dev pipeline for added coverage: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/aoco_uniq_snap_fix

ao/co: Fix snapshot setup for unique index checks

---

src/backend/gporca/libgpopt/src/operators/CLogicalDynamicGet.cpp
src/test/regress/expected/bfv_partition.out
src/test/regress/sql/bfv_partition.sql

ORCA was not remapping the colids of the disjunctive constraint when copying CLogicalDynamicGet with remapped columns. This led to a case where ORCA crashed while trying to derive stats on an unexpected colid.
Following is an example that demonstrated the issue:
```sql
CREATE TABLE pt(c1 int) PARTITION BY LIST(c1) (
PARTITION a_part values(2,3),
DEFAULT partition other);
INSERT INTO pt SELECT 2;
ANALYZE pt;
WITH cte AS (SELECT * FROM pt WHERE c1 < 2) SELECT * FROM cte WHERE c1 = 1;
```
Fixes #14395

Fix disjunctive constraint colid remapping

---

gpMgmt/doc/gpsync_help

Replaced scp with rsync and all gpscp references with gpsync in gpscp_help doc file and renamed it to gpsync_help as the next step of PR https://github.com/greenplum-db/gpdb/pull/14145

Renamed gpscp_help to gpsync_help

---

src/backend/commands/tablecmds.c
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/unsync_guc_name.h
src/test/regress/expected/alter_table_gp.out
src/test/regress/sql/alter_table_gp.sql

This GUC was introduced in de4e95a6a914 in order to workaround a specific case where we couldn't rename a relation if its metadata is corrupted. When this GUC is ON, we don't really open the relation which would throw error with the aforementioned metadata corruption.
Now removing this GUC at least for 7X because its benefit is questionable: 
(1) It seems to be a one-time workaround trick, and has been obsolete for a long time. There's no Slack/JIRA/Github history that could show it has been actively used by support;
(2) There is better alternative to workaround the issue, which is to simply fix the metadata. Leaving a hole like this in the product does not feel safe. It creates needless divergence from the upstream too.

Remove gp_allow_rename_relation_without_lock

---

src/backend/gporca/data/dxl/minidump/NestedInSubqWithPrjListOuterRefNoInnerRef.mdp
src/backend/gporca/libgpos/server/src/unittest/gpos/common/CBitSetTest.cpp
src/backend/gporca/libgpos/src/common/CBitSet.cpp

There was a corner case where intersecting a bitset A with bitset B, where A had elements in a vector that did not exist in B, would cause bitset A to have a size of 0, but still have a bitvector. This was an undefined and unexpected state. We assume that bitvectors in a bitset are non-empty, and breaking this assumption causes operations such as Equals() and Contains() to produce wrong results. In this case, it led to Orca failing to produce a plan since required columns did not satisfy the Contains() method.
This is a VERY hot codepath, bitset operations are heavily used in Orca and isEmpty requires iterating through the bitvector. I ran this through some performance tests and didn't see any decrease in performance.
(cherry picked from commit 232309c21a461e78fd1ad25ee8a39ca31c047c97

[6X] Fix CBitSet Intersection logic in Orca

---

src/test/regress/expected/bfv_partition.out
src/test/regress/sql/bfv_partition.sql

Test case "dispatch started failing on PLANNER CI after commit a7ca9e27.
Using github Issue #14428 for tracking. It seems somehow triggered to
the test added in bfv_partition in aforementioned commit.

Workaround flaky test "dispatch"

---

src/backend/access/common/reloptions.c
src/backend/access/common/reloptions_gp.c
src/backend/commands/analyze.c
src/bin/psql/tab-complete.c
src/include/access/reloptions.h
src/include/utils/guc.h
src/include/utils/rel.h
src/test/regress/expected/incremental_analyze.out
src/test/regress/expected/incremental_analyze_optimizer.out
src/test/regress/sql/incremental_analyze.sql

Currently, tables do not collect HLL statistics by default unless the table is part of a partitioned table. This however means that a regular table that is exchanged or added to a partition table will also not have HLL statistics unless it is re-analyzed, and the root table will also therefore not have statistics for the exchanged/added partition.
This commit adds a reloption, "analyze_hll", that will force collection of HLL stats even if the table isn't part of a partitioned table. HLL stats will still always be collected if the table is created as part of a partitioned table.
AO tables go through a different path for parsing reloptions, so additional logic/tests were added for this. Also, pg_dump/gpbackup will automatically dump this without any changes since this is stored as a string …

Add reloption to force table to collect HLL stats

---

src/backend/cdb/motion/ic_proxy_backend.c
src/backend/cdb/motion/ic_proxy_client.c
src/backend/postmaster/postmaster.c
src/test/isolation2/Makefile
src/test/isolation2/expected/ic_proxy_peer_shutdown.out
src/test/isolation2/expected/tcp_ic_teardown.out
src/test/isolation2/isolation2_ic_proxy_schedule
src/test/isolation2/isolation2_ic_tcp_schedule
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/ic_proxy_peer_shutdown.sql
src/test/isolation2/sql/tcp_ic_teardown.sql

Upon remote peer shutdown, we need to drop all logical connections
involving the remote peer. A part of that is dropping packets that were
cached by placeholder clients.
Unfortunately, we were indiscriminately dropping these for clients
belonging to ALL logical connections (regardless of the dbid of the
remote peer) in ic_proxy_client_table_shutdown_by_dbid().
This can lead to DATA and BYE packets being dropped from the client-local
cache for unrelated connections, leading to messages like:
WARNING: ic-proxy: client.placeholder[...]: unhandled cached BYE [..], dropping it
Consequently, later when the placeholder clients are replaced by actual
clients, these packets aren't transferred and ultimately are never
processed, leading to messages like:
DEBUG3: ic-proxy: [...]: replace my …

ic-proxy: Fix cache eviction on remote peer shutdown

---

src/backend/executor/nodeModifyTable.c
src/test/regress/expected/delete.out
src/test/regress/sql/delete.sql

As #14417 reported, there will be assertion failures in some cases when executing ModifyTable.
This is because we opened all the range table relations in `NoLock` mode, but sometimes with no lock holding by us.
This also resolved a GPDB_91_MERGE FIXME left around range table locking code: https://github.com/greenplum-db/gpdb/blob/05b333dfdc03d0477fafe132b10c0cfa2a19d5ae/src/backend/executor/nodeModifyTable.c#L2991~L2993

Fix Range Tables related relations opening's locking issue inside ExecInitModifyTable().

---

src/backend/commands/analyze.c
src/test/isolation2/expected/lockmodes.out
src/test/isolation2/expected/lockmodes_optimizer.out
src/test/isolation2/sql/lockmodes.sql

A FIXME was left noting whether to use AccessShareLock or NoLock when opening child tables to merge their stats. Since we are not updating or even opening the child tables, NoLock should be enough.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/fixme-analyze-lock

Resolve a FIXME in merge_leaf_stats()

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/include/gpopt/translate/CTranslatorQueryToDXL.h
src/include/gpopt/translate/CTranslatorUtils.h
src/test/regress/expected/groupingsets_optimizer.out
src/test/regress/expected/orca_groupingsets_fallbacks.out
src/test/regress/expected/orca_groupingsets_fallbacks_optimizer.out
src/test/regress/sql/orca_groupingsets_fallbacks.sql

After commit 17c7da54f5a028dc1a7c9276e632a1ba59b257b0, following produces valid plan in ORCA:
```sql
CREATE TABLE t AS SELECT i as a, i as b FROM generate_series(1,3)i;
EXPLAIN SELECT a, b FROM t GROUP BY a, ROLLUP(b);
```
In ORCA, multiple grouping set specs is implemented as the pairwise
concatenation of the individual elements from the different grouping
sets. In the above example, there are 2 sets:
```
"a" that produces (1), (2), (3)
"ROLLUP(b)" that produces (), (1), (2), (3).
```
Pairwise concatenation of the two sets produces groups:
```
(1,),(2,),(3,),(1,1),(2,1),(3,1),(1,2),(2,2),(3,2),(1,3),(2,3),(3,3)
```
Based on the table contents and the groups, the query result produces:
```
(1,),(2,),(3,),(1,1),(2,2),(3,3)
```
---
Fallback for multiple grouping set specs using duplicate …

Orca enable multiple grouping set specs

---

src/backend/cdb/motion/ic_proxy_backend.c
src/backend/cdb/motion/ic_proxy_client.c
src/backend/postmaster/postmaster.c
src/test/isolation2/Makefile
src/test/isolation2/expected/ic_proxy_peer_shutdown.out
src/test/isolation2/expected/tcp_ic_teardown.out
src/test/isolation2/isolation2_ic_proxy_schedule
src/test/isolation2/isolation2_ic_tcp_schedule
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/ic_proxy_peer_shutdown.sql
src/test/isolation2/sql/tcp_ic_teardown.sql

This is a backport of https://github.com/greenplum-db/gpdb/pull/14412
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_proxy_shutdown_bug

[6X] ic-proxy: Fix cache eviction on remote peer shutdown

---

concourse/pipelines/gen_pipeline.py
concourse/vars/common_cm.yml
concourse/vars/common_dev2.yml
concourse/vars/common_dp.yml
concourse/vars/common_ud.yml

Based on the pipeline target specified to gen_pipeline.py script:
* Enhance pipeline generation script to use CCP vault entries.
* Use GCP project-dependent CI vars file.
* The fly command output from gen_pipeline.py will be able to run unchanged. The exception is the need to specify the developer-specific GitHub repo and possibly the branch.

Support running GPDB dev pipelines in GP alternate CI environments.

---

concourse/pipelines/gen_pipeline.py
concourse/vars/common_cm.yml
concourse/vars/common_dev2.yml
concourse/vars/common_dp.yml
concourse/vars/common_ud.yml

Based on the pipeline target specified to gen_pipeline.py script:
* Enhance pipeline generation script to use CCP vault entries.
* Use GCP project-dependent CI vars file.
* The fly command output from gen_pipeline.py will be able to run unchanged. The exception is the need to specify the developer-specific GitHub repo and possibly the branch.
* Update Pipeline target help information.

6X backport: Support running GPDB dev pipelines in GP alternate CI environments.

---

concourse/scripts/compile_gpdb.bash

Remove support for centos7 and ubuntu18.04, we vendor zstd, libuv header and shared library to customer, but in rhel8, we do not need to vendor, since they can be installed from the os official repo.

Remove support for centos7 and ubuntu18.04

---

gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md

"cherry-picking" merge from #14455 in main to 6X_STABLE

Fix wrong representation of percentage (#14455)

---

src/bin/pg_dump/pg_dump.c

As in gp6 there is no 'objtype' abbreviation E in 'acldefault' fuction.

Fix external protocol dump from gp6 using gp7 pg_dump.

---

contrib/postgres_fdw/Makefile
contrib/postgres_fdw/postgres_fdw.h

This reverts commit 667f0c37bc6d7bce7be8b758652ef95ddb823e19.
It would also work without it, in the opposite way, it has two issues:
1, it failed to build on macOS, with an error "ld: unknown option: --exclude-libs=libpq.a"
2, after the 12 merge, it triggers a PostgreSQL's error: "libpq is incorrectly linked to backend functions"
Fixes https://github.com/greenplum-db/gpdb/issues/11400 and https://github.com/greenplum-db/gpdb/issues/11523
BTW, checkout https://github.com/greenplum-db/gpdb/pull/9462 if you have frontend/backend concern.

Revert "Fix postgres_fdw's libpq issue (#10617)"

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonlyam_handler.c
src/test/isolation2/input/uao/index_build_reltuples.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/uao/index_build_reltuples.source
src/test/regress/greenplum_schedule
src/test/regress/input/uao_dml/ao_unique_index_build.source
src/test/regress/output/uao_dml/ao_unique_index_build.source

This is a follow-up to the discussion:
https://github.com/greenplum-db/gpdb/pull/13526#discussion_r1002037396
It consists of 2 commits:
1. Pre-factor commit to only use SnapshotAny (alternatives are dead code really)
2. Address the visibility check FIXME for AO/CO index build scans, which fixes buggy CREATE UNIQUE INDEX behavior.

ao/co: Correct tuple visibility reporting for index builds

---

gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md

Staging here:
NOTE: No release note, as this is being introduced in 6X (v likely 6.24), not in 7X. 
https://docs-staging.vmware.com/en/Greenplum-Database-7/collect-HLL-stats/greenplum-database/GUID-ref_guide-sql_commands-CREATE_TABLE.html
https://docs-staging.vmware.com/en/Greenplum-Database-7/collect-HLL-stats/greenplum-database/GUID-ref_guide-sql_commands-ALTER_TABLE.html

DOCS: Document new parameter to force collection of HLL stats for tables that are part of a partitioned table

---

src/backend/access/aocs/aocsam_handler.c
src/backend/access/appendonly/appendonly_visimap.c
src/backend/access/appendonly/appendonlyam_handler.c
src/backend/access/appendonly/appendonlyblockdirectory.c
src/include/access/appendonly_visimap.h
src/include/cdb/cdbappendonlyblockdirectory.h

This commit refactors block directory and visimap initialization, lookup
and teardown code to make the special non-MVCC snapshot manipulation
more apparent. Assumptions are also asserted copiously.

ao/co: Refactor blkdir/visimap access for unique checks

---

gpMgmt/bin/gpcheckcat
gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
gpMgmt/test/behave/mgmt_utils/steps/data/gpcheckcat/create_multilevel_partition.sql

Earlier gpcheckcat used to error out when root partition has different distribution policy than child partition. But commit a45be43489294386c23c5fa068ce071ec068d0d8 introduces a new statement `ALTER TABLE EXPAND PARTITION PREPARE` which modifies the distribution policy of the leaf partitions to be randomly distributed. Based on this a policy is good if the following conditions are satisfied:
- numsegments value is equal for all root, middle and leaf level partitions
- if a root is randomly distributed, then all middle, leaf level partitions must also be randomly distributed
- if a root is hash distributed, then middle level should be same as root and leaf level partition can be hash on same key or randomly distributed
This commit modifies the existing SQL query such that whenever a parent …

Fix gpcheckcat partition distribution policy check

---

gpMgmt/doc/Makefile

As part of scp to rsync replacement task gpscp_help file was renamed to gpsync_help https://github.com/greenplum-db/gpdb/pull/14392, so did the code clean up and replaced all the references of gpscp_help with gpsync_help.

Replaced gpscp_help with gpsync_help
