src/backend/cdb/cdbfilerep.c
This was causing a segfault when compiling with -O3 on Centos 7
(gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)). I'm not 100% if that was
actually a compiler bug, but unaligned access would definitely be wrong
on architectures that are strict on alignment anyway.
=> Fix alignment in FileRep_CalculateParity.

src/test/regress/input/appendonly.source, src/test/regress/output/appendonly.source
Extensive tests for UAO exist in TINC.  Our goal is to migrate those tests to ICG or elsewhere along with main codebase.  This change tests bare-minimum UAO functionality.
=> UAO installcheck test should verify visibility by executing SELECT.

src/backend/access/common/reloptions.c
For "checksum=on/off", and "appendonly=on/off", we used the "on" or "off"
value to allocate space (i.e. 2 or 3 bytes), but then constructed a string
that said "true" or "false" (4 or 5 bytes). That lead to overflowing the
allocation by a few bytes, which produced warnings on assertion-enabled
builds.
To fix, don't try to count the space needed by hand. Use a StringInfo
instead.
In the passing, clean up accumAOStorageOpt function in some other ways:
remove the namelen argument to make it a bit more readable (this is hardly
performance-critical code), and don't split error message across lines
(makes it easier to grep for them if you need to find where an error
is coming from).
This fixes github issue #221.
=> Fix buffer overflow in parsing boolean-type storage options.

src/backend/access/nbtree/nbtxlog.c
This isn't otherwise better than the existing code, but this matches the
upstream more closely, which will make merging slightly easier.
=> Refactor btree_desc() code to match upstream more closely.

gpMgmt/bin/gppylib/test/behave/mgmt_utils/gptransfer.feature, gpMgmt/bin/gptransfer, gpMgmt/doc/gptransfer_help
also updated the help doc with examples and more details.
=> gptransfer to do some extra pre-checks of users' input for partition table transfer

src/backend/optimizer/util/plancat.c, src/test/regress/expected/subselect_gp.out
See discussion at https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/nPi5Y8PWd8Q/LxL52_qBEQAJ
=> If a relation contains self-contradictory quals, don't plan it.

doc/src/sgml/ref/create_function.sgml
It is left-behind work of "5b2af3cf6892061ca43e5e310861870fada13fcf"
=> Update sgml description for default values of function arguments

src/backend/access/external/url.c
@yydzero @vraghavan78 @addisonhuddy @hsyuan
=> Add hint for rescan of external table [#115361337]

gpAux/extensions/gps3ext/src/S3Common.cpp, gpAux/extensions/gps3ext/src/S3Common.h, gpAux/extensions/gps3ext/src/S3Common_test.cpp, gpAux/extensions/gps3ext/src/S3Downloader.cpp, gpAux/extensions/gps3ext/src/S3Downloader.h, gpAux/extensions/gps3ext/src/S3Downloader_test.cpp
some code reformations and header order changes come from clang-format, not the point.
=> s3ext: support more than 1000 files in a single folder

concourse/scripts/build_with_orca.py, concourse/scripts/gporca/GporcaCommon.py, concourse/scripts/gporca/__init__.py, concourse/scripts/test_with_orca.py
Refactor test_with_orca.py and build_with_orca.py
Extract the common piece out as GporcaCommon package.
Disable gpfdist tests with --disable-gpfdist option for configure,
because GPORCA doesn't impact the management utilities like gpfdist.
=> Fix gpdb_icg job [#118185321]

gpMgmt/bin/gppylib/test/behave/mgmt_utils/backup.feature, gpMgmt/bin/gppylib/test/behave/mgmt_utils/steps/backup_mgmt_utils.py, src/bin/pg_dump/cdb/cdb_dump_agent.c
* Add Behave test that uncovers the bug hinted at by the compiler warning.
=> Fixes commit b9abd61dbe that introduced a compiler warning. 

gpMgmt/bin/gpcrondump, gpMgmt/bin/gppylib/test/unit/test_cluster_gpcrondump.py, gpMgmt/doc/gpcrondump_help
information.
Authors: Christopher Hajas, Pengcheng Tang
=> Add a flag into gpcrondump to show the DDBoost configuration

gpAux/extensions/gps3ext/Makefile, gpAux/extensions/gps3ext/Makefile.chkcfg, gpAux/extensions/gps3ext/Makefile.others, gpAux/extensions/gps3ext/include/gps3ext.h, gpAux/extensions/gps3ext/include/s3common.h, gpAux/extensions/gps3ext/include/s3downloader.h, gpAux/extensions/gps3ext/include/s3http_headers.h, gpAux/extensions/gps3ext/include/s3log.h, gpAux/extensions/gps3ext/include/s3macros.h, gpAux/extensions/gps3ext/include/s3thread.h, gpAux/extensions/gps3ext/include/s3uploader.h, gpAux/extensions/gps3ext/include/s3url_parser.h, gpAux/extensions/gps3ext/include/s3utils.h, gpAux/extensions/gps3ext/src/s3common.cpp, gpAux/extensions/gps3ext/src/s3conf.cpp, gpAux/extensions/gps3ext/src/s3downloader.cpp, gpAux/extensions/gps3ext/src/s3http_headers.cpp, gpAux/extensions/gps3ext/src/s3log.cpp, gpAux/extensions/gps3ext/src/s3thread.cpp, gpAux/extensions/gps3ext/src/s3uploader.cpp, gpAux/extensions/gps3ext/src/s3url_parser.cpp, gpAux/extensions/gps3ext/src/s3utils.cpp, gpAux/extensions/gps3ext/src/s3wrapper.cpp, gpAux/extensions/gps3ext/test/s3common_test.cpp, gpAux/extensions/gps3ext/test/s3conf_test.cpp, gpAux/extensions/gps3ext/test/s3http_headers_test.cpp, gpAux/extensions/gps3ext/test/s3log_test.cpp, gpAux/extensions/gps3ext/test/s3thread_test.cpp, gpAux/extensions/gps3ext/test/s3url_parser_test.cpp
Refactor s3common code and add unit tests.
Author: Adam & Yandong
=> s3ext: refactor s3common codes

src/test/regress/output/partindex_test.source
This fixes the test failure introduced in commit effc38f6965c9b30fc2dce5c7a0b8d7f08217298
fixes #809
[delivers #120723853]
=> Fix `partindex_test`

concourse/scripts/build_with_orca.py
@gcaragea @xinzweb @d Please have a look.
=> Add unittests in the build step of GPDB in concourse.

gpAux/releng/make/dependencies/ivy.xml
@vraghavan78 I picked the latest releases for each on Github
=> Bump optimizer and gpos versions to latest

vagrant/debian/Vagrantfile, vagrant/debian/vagrant-build.sh, vagrant/debian/vagrant-setup.sh
Add more required packages
Fix upgraded Python packages
Add missing options to configure line
Fix ssh known hosts
=> Fix Debian Vagrant file

docker/base/Dockerfile
1) Reduce RUN count to reduce images
2) Fix 'Unexpected EOF error' when 'ADD get-pip.py' occasionally.
=> enhance Dockerfile to generate less images

src/backend/codegen/include/codegen/utils/codegen_utils.h, src/backend/codegen/tests/codegen_utils_unittest.cc
A simple wrapper around llvm::InlineFunction, with some unit tests.
@karthijrk @armenatzoglou @gcaragea @foyzur Please take a look.
=> Implement InlineFunction to force inline at call site

gpAux/extensions/gps3ext/include/s3url_parser.h, gpAux/extensions/gps3ext/include/s3utils.h, gpAux/extensions/gps3ext/src/s3log.cpp, gpAux/extensions/gps3ext/src/s3url_parser.cpp, gpAux/extensions/gps3ext/src/s3utils.cpp, gpAux/extensions/gps3ext/test/s3http_headers_test.cpp, gpAux/extensions/gps3ext/test/s3url_parser_test.cpp, gpAux/extensions/gps3ext/test/s3utils_test.cpp
Signed-off-by: Kuien Liu <kliu@pivotal.io>
=> s3ext: Remove some dead code and improve unit test code coverage

gpAux/extensions/gps3ext/Makefile, gpAux/extensions/gps3ext/src/s3common.cpp, gpAux/extensions/gps3ext/test/s3common_test.cpp
=> s3ext: remove duplicate functions

gpAux/extensions/gps3ext/include/s3bucket_reader.h, gpAux/extensions/gps3ext/include/s3interface.h, gpAux/extensions/gps3ext/src/s3bucket_reader.cpp, gpAux/extensions/gps3ext/src/s3interface.cpp, gpAux/extensions/gps3ext/test/s3bucket_reader_test.cpp, gpAux/extensions/gps3ext/test/s3interface_test.cpp
=> s3ext: enhance the failure retrying mechanism in S3Service

src/backend/codegen/include/codegen/pg_arith_func_generator.h, src/backend/codegen/include/codegen/pg_date_func_generator.h, src/backend/codegen/include/codegen/pg_func_generator.h, src/backend/codegen/include/codegen/pg_func_generator_interface.h, src/backend/codegen/op_expr_tree_generator.cc, src/backend/codegen/pg_date_func_generator.cc
I am using PGFuncGeneratorInfo struct to pass around information needed for pg_func code generation. 
@foyzur @hardikar please have a look when you get chance.
=> Use PGFuncGeneratorInfo to codegen pg functions

gpMgmt/bin/gppylib/test/behave/mgmt_utils/backup.feature, gpMgmt/bin/gppylib/test/behave/mgmt_utils/steps/valgrind_suppression.txt, src/bin/pg_dump/cdb/cdb_backup_state.c, src/bin/pg_dump/cdb/cdb_dump.c, src/bin/pg_dump/cdb/cdb_dump_util.c
There were some memory/resource leaks that were detected by Valgrind on SuSE.
This commit addresses some of those issues.
=> Address memory leaks

src/backend/utils/misc/guc_gp.c
New GUC : assign_codegen_optimization_level
=> Fix gpinitsystem when built without codegen because of new GUC

src/backend/optimizer/path/joinpath.c, src/test/regress/expected/bfv_subquery.out, src/test/regress/expected/bfv_subquery_optimizer.out, src/test/regress/sql/bfv_subquery.sql
I am wrapping up an earlier PR https://github.com/greenplum-db/gpdb/pull/813 by adding a test.
@hlinnaka @oarap @d @hsyuan @bhuvnesh2703 please take a look.
=> Enable NOT IN subquery when merge join on condition is not supported [#120384087]

concourse/scripts/build_gpdb.py, concourse/scripts/builds/GpBuild.py, concourse/scripts/builds/__init__.py, concourse/scripts/test_gpdb.py, concourse/test_with_planner.yml
As of the now the icg tests scripts only handles running the test with optimizer on. Include the flag to run tests with legacy planner.
=> Updated scripts to include icg to run on planner and orca [#130117989]

gpAux/Makefile, gpAux/extensions/gphdfs/Makefile, gpAux/extensions/gphdfs/build.xml, gpAux/extensions/gphdfs/ivysettings.xml, gpAux/releng/make/dependencies/build.xml, gpAux/releng/make/dependencies/ivy.xml, gpAux/releng/make/dependencies/ivysettings.xml, gpAux/releng/releng.mk, src/backend/gpopt/gpopt.mk, src/bin/Makefile, src/bin/pg_dump/cdb/Makefile, src/bin/pg_dump/cdb/test/Makefile
This PR removes dependencies on hardcoded paths in Makefiles and fixes paths / parts of build process.
=> Prepare build process for CI integration

concourse/pr_pipeline.yml
PR pipeline is at: https://gporca.ci.pivotalci.info/pipelines/gpdb_pr
- Add new pullrequest_resource through docker image at `pivotaldata/pr-resource:latest`
- Add github pull request pipeline `pr_pipeline.yml`
Signed-off-by: Karthikeyan Jambu Rajaraman <krajaraman@pivotal.io>
=> [#129419545] Create new PR pipeline for GPDB

concourse/perf_pipeline.yml
https://gporca.ci.pivotalci.info/pipelines/gpdb_perf
Signed-off-by: Jesse Zhang <jzhang@pivotal.io>
=> [#130552639] Add performance pipeline

src/backend/catalog/gp_toolkit.sql
[#130666969]
Internally this is the shared memory variable used_segspace in
the view gp_toolkit.gp_workfile_mgr_used_diskspace.
Signed-off-by: Xin Zhang <xzhang@pivotal.io>
@karthijrk @armenatzoglou
=> Expose UDF in a view to retrieve workfiles used diskspace

concourse/ic_gpdb.yml, concourse/pipelines/pipeline.yml, concourse/scripts/common.bash, concourse/scripts/ic_gpdb.bash, concourse/scripts/setup_gpadmin_user.bash, gpAux/gpdemo/probe_config.sh
Adds the ICG test to the main pipeline.
=> Add the ICG test to pipeline.

src/test/regress/expected/gp_numeric_agg.out, src/test/regress/expected/qp_misc_jiras.out, src/test/regress/expected/qp_misc_jiras_optimizer.out, src/test/regress/greenplum_schedule, src/test/regress/sql/gp_numeric_agg.sql, src/test/regress/sql/qp_misc_jiras.sql
[#127140493] This checkin will make ICG green.
Let's keep the green pipeline.
=> Remove the unstable legacy tests.

concourse/perf_pipeline.yml, concourse/provision.yml, concourse/scripts/perf_common.sh, concourse/scripts/perf_provision.sh, concourse/scripts/perf_unprovision.sh, concourse/unprovision.yml
[#130552319]
* Automate VM provisioning with given VM size
* Output the VM information, e.g. hostname, IP etc.
* Be able to SSH to that VM from Pipeline.
* Destroy VM.
Signed-off-by: Nikos Armenatzoglou <nikos.armenatzoglou@gmail.com>
=> Performance pipeline: provision and destroy VM in AWS

src/bin/gpfdist/gpfdist.c, src/bin/gpfdist/gpfdist_helper.c
Customers request this for their Informtica workflow connections.
=> Increase gpfdist max values of -t and -w options to 2 hours

concourse/perf_pipeline.yml, concourse/provision.yml, concourse/scripts/perf/common.sh, concourse/scripts/perf/prepare_kernel.sh, concourse/scripts/perf/prepare_network.sh, concourse/scripts/perf/prepare_security.sh, concourse/scripts/perf/provision.sh, concourse/scripts/perf/unprovision.sh, concourse/unprovision.yml
Configuring the following for the spawned instance:
* Setting up RSA key pair
* Enhancement to kernel parameters by changing sysctl.conf
* Changing ulimit values for opened files and number of processes
* Additional debug log in concourse for detecting parameter changes
-- Jesse And Foyzur
=> Configuring spawned instance for perf pipeline.

README.md
Fixes issues #506, #507, #508, and #510.
=> Update ./configure examples with options that pass regression tests.

src/backend/parser/parse_relation.c
relation close was missed for cases returning false,
used to throw warning of relcache reference leak.
fixes #1060
=> Close relation in isSimplyUpdatableRelation

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
There is no functional changes in this commit. Fixes pylint warnings and whitespace.
Authors: Chris Hajas and Chumki Roy
=> Fix pylint warnings in gprecoverseg

gpMgmt/bin/gppylib/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/bin/gppylib/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/bin/gppylib/test/behave_utils/utils.py
This is a followup test for PR #1005
=> add test for gprecoverseg -r when the segments are waiting to be synchronized

src/test/regress/bugbuster/expected/spi.out
=> Correct the expected file to pass the test

gpAux/extensions/Makefile
TBD (trigger gpdb_pr pipeline)
Signed-off-by: Gang Xiong <gxiong@pivotal.io>
=> Install orafce before run installcheck

gpAux/extensions/gphdfs/gphdfsprotocol.c
Four characters "'", "\", "<", ">" could cause shell injection in
gphdfs. This quick fix filters out them to avoid the security issue.
PS, it's a quick fix, will get the best solution then apply to GPDB 4 and 5.
Signed-off-by: Haozhou Wang <hawang@pivotal.io>
Signed-off-by: Peifeng Qiu <pqiu@pivotal.io>
=> Validate GPHDFS URL before calling execl() with it

src/bin/psql/help.c
=> Update copyright statement

gpMgmt/bin/gpcheckcat_modules/foreign_key_check.py
A minor refactor of comments and code to explain the way foreign keys are validated.
=> refactor gpcheckcat foreign key validation

.gitmodules, gpAux/Makefile, gpAux/releng/NON_PRODUCTION_FILES.txt, gpAux/releng/QAUTILS_FILES.txt, src/backend/Makefile
Also update related makefiles.
Signed-off-by: Gang Xiong <gxiong@pivotal.io>
=> Delink private submodules addon and gp_filedump

concourse/pipelines/pipeline.yml
Signed-off-by: Gang Xiong gxiong@pivotal.io
=> Be able to store bin_gpdb and sync_tools_gpdb to specified S3 locations

src/backend/access/transam/xact.c
This avoids a lot of overhead for short read-only queries. We still don't
do lazy assignment for most transactions, like PostgreSQL 8.3 does, but
this is a step in the right direction.
=> Avoid assigning an XID to DTX_CONTEXT_QE_AUTO_COMMIT_IMPLICIT queries.

gpMgmt/bin/gppylib/test/behave/mgmt_utils/gptransfer.feature, gpMgmt/bin/gppylib/test/unit/gp_unittest.py, gpMgmt/bin/gppylib/test/unit/test_unit_gptransfer.py, gpMgmt/bin/gptransfer
Add additional case when source and destination attributes are different.
Authors: Larry Hamel, Marbin Tan, Chris Hajas
=> Tighten the criteria for partition validation

src/backend/catalog/heap.c, src/backend/catalog/oid_dispatch.c, src/backend/catalog/pg_enum.c, src/backend/commands/tablecmds.c, src/backend/commands/typecmds.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/outfast.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/nodes/readfuncs.c, src/include/catalog/heap.h, src/include/catalog/pg_enum.h, src/include/executor/execdesc.h, src/include/nodes/parsenodes.h
Use the new generic OID dispatch mechanism also for pg_enum and pg_attrdef.
=> Oid dispatch cleanup

src/backend/codegen/include/codegen/pg_arith_func_generator.h, src/backend/codegen/include/codegen/utils/codegen_utils.h, src/backend/codegen/tests/codegen_utils_unittest.cc, src/backend/codegen/utils/codegen_utils.cc
In this PR, we add support for overflow for double type. We leveraged GPDB function that checks overflow for double. As a quick implementation, we made an external function call to GPDB function that checks  for overflow. There is a separate story to avoid this external function call for performance reason.
Also, this PR introduce new API to create tuple similar to `make_tuple` in c++. This is needed to make sure the return type of `ArithOpOverflow<double>` is same as `ArithOpOverflow<int>`. `ArithOpOverflow<int>` return tuples using intrinsic instruction.
This is the last change we need to make ICG green for planner + codegen.
@foyzur @hardikar Please take a look.
Signed-off-by: Nikos Armenatzoglou <nikos.armenatzoglou@gmail.com>
=> Support overflow checks for doubles.

src/backend/commands/explain.c
=> Fix segfault on EXPLAIN ANALYZE of a Sort node with 0 rows.

concourse/README.md
This file explains the contract that we are drawing out for the use and maintenance of the concourse directory. It describes the organization of the directory, and how to make changes safely. It also describes individual team's responsibility to make sure they are alerted if changes are made to a pipeline they are using.
=> Add README to concourse directory

concourse/gpdb_src_tinc_packaging.yml, concourse/pipelines/pipeline.yml, concourse/scripts/gpdb_src_tinc_packaging.bash
Adding a new step in concourse that generates a tarball for
the tinc.
=> Create TINC source tarball in concourse.

src/backend/access/transam/xact.c, src/backend/utils/time/sharedsnapshot.c
- Added initial description about QE writers, readers and shared snapshot. Lot more to gain knowledge on and updating the documents in the process.
- QE readers are not required to participate in any transaction activity like commit or abort. There counter part QE writer is responsible for performing the same. This commit is just fixing the over-sight caused by commit a453004, as anyways for QE reader case we will return much earlier in function and never ever reach here.
=> Initial info on QE writers, readers and shared snapshot and fix for 1275

src/backend/gpopt/utils/COptTasks.cpp, src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h
This guc allow us to change the cost of sort and tuning the query plan
generated by Orca for better performance.
=> Adding guc to tune the Orca's cost model for sort.

concourse/README.md, concourse/pipelines/pipeline_gpcloud.yml, concourse/scripts/gpcheckcloud_tests_gpcloud.bash, concourse/scripts/regression_tests_gpcloud.bash, concourse/scripts/unit_tests_gpcloud.bash, concourse/tasks/gpcheckcloud_tests_gpcloud.yml, concourse/tasks/regression_tests_gpcloud.yml, concourse/tasks/unit_tests_gpcloud.yml
Signed-off-by: Haozhou Wang <hawang@pivotal.io>
Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>
=> Add concourse pipeline files for gpcloud

src/test/tinc/tincrepo/mpp/gpdb/tests/utilities/gpexpand/scenarios/run_gpexpand.py, src/test/tinc/tincrepo/mpp/gpdb/tests/utilities/gpexpand/test_gpexpand.py
-- set MASTER_DATA_DIRECTORY env var during each test
-- port of 7cfb44a from tinc repo
=> tinc: fix tests that now require MASTER_DATA_DIRECTORY

src/backend/utils/sort/tuplesort.c
The old GPDB code had a "fall through" in switch-case block, that was not
present in PostgreSQL 8.2. PostgreSQL 8.3 added a new case-block to the
statement, so that the GPDB-specific "fall through" fell through to the
wrong case-block. This lead to a crash, if a sort was small enough to be
performed in memory, was shared by multiple slices. Fix by moving the
GPDB-specific check outside the switch-case statement.
=> Fix bug with small sorts and shared scans, introduced by 8.3 merge.

src/backend/utils/adt/ruleutils.c, src/backend/utils/error/elog.c
=> Misc small Coverity fixes

concourse/pipelines/pipeline.yml, concourse/scripts/gpMgmt_check_gpdb.bash, concourse/tasks/gpMgmt_check_gpdb.yml, gpMgmt/bin/Makefile
-- change PYTHONPATH priority for src/ext, putting it behind
installed/ext
=> add task to master pipeline to run MU unit tests (make check)

src/backend/parser/parse_utilcmd.c, src/backend/tcop/utility.c, src/include/parser/parse_utilcmd.h
Signed-off-by: Peifeng Qiu <pqiu@pivotal.io>
=> Fix serial type not supported by external table issue

src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/appendonly_eof/expected_concurrency/aoco_conc_load1.ans
Update the .ans file to conform to the test.
=> Fix diffs in access_methods/appendonly_eof tests.

concourse/tasks/build_with_orca.yml, concourse/tasks/test_with_orca.yml, concourse/tasks/test_with_planner.yml, gpAux/releng/releng.mk, src/backend/gpopt/utils/funcs.cpp
GPOS is not a stand alone library anymore. All the source code of gpos is merged into gporca. So some changes are required in gpdb.
=> Merge gpos into gporca

src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
=> Add a case creating external table with a serial type column

gpMgmt/bin/gppylib/test/behave/mgmt_utils/gprecoverseg.feature
-- no functional change in production code.
=> add initial test to highlight this behave suite's requirement for multiple hosts

gpMgmt/bin/analyzedb
* Timeout was removed from the WorkerPool on commit
c7dfcc4538b9677f92ea863a26ee156401ac98b3
=> Remove timeout logic from analyzedb

src/backend/postmaster/postmaster.c
Currently, the walsender process is not properly stopped during
gpstop. The SignalSomeChildren function was changed in the Postgres
8.3 merge in commit 20ac0be199f07f75025311538cf15cd96ffe2108. It was
previously at a Postgres 9.2 state to support sending signals to
walsender as a part of our master and standby master replication.
Without this revert, there is a 2 minute delay before the postmaster sends a SIGQUIT to the walsender:
```
20170111:14:43:49:099551 gpstop:Jimmy:jyih-[INFO]:-Commencing Master instance shutdown with mode=fast
20170111:14:43:49:099551 gpstop:Jimmy:jyih-[INFO]:-Master segment instance directory=/dir
20170111:14:45:50:099551 gpstop:Jimmy:jyih-[INFO]:-Failed to shutdown master with pg_ctl.
20170111:14:45:50:099551 gpstop:Jimmy:jyih-[INFO]:-Sending SIGQUIT signal... …
```
=> Revert SignalSomeChildren function back to Postgres 9.2 functionality

src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/checksum_negative.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/database_appendonly.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/database_checksum.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/database_orientation.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/parameters.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/plpgsql_database.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/plpgsql_role.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/plpgsql_session.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/plpgsql_table.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/role_appendonly.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/role_checksum.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/role_orientation.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/session_appendonly.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/session_checksum.ans, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/access_methods/storage_parameters/expected/session_orientation.ans
Update the .ans file to conform to the test output for 5.0.
=> Fix diffs in the storage/access_methods/storage_parameter tests.

concourse/pipelines/pipeline.yml
* pipelines were missing the new input from pulse trigger
gpdb_src_behave_tarball. This is an update to fix that issue.
* Restructured/refactored the pipeline for better visibility for each
job
=> Pipeline update to add missing pulse input

src/backend/access/transam/xlog.c
Addressing GPDB_83_MERGE_FIXME comment in xlog.c:8881
Originally, `CheckpointStartLock` prevent any MMXLOG insert between
collecting persistent table objects information
(mmxlog_append_checkpoint_data) through XLogInsert of checkpoint record.
Since `CheckpointStartLock` is removed from upstream, to prevent error
in MMXLOG replay on standby, we have to add protection back.
For the same reason, we used PersistentObjLock in SHARED mode to
prevent any update between mmxlog_append_checkpoint_data and XLogInsert
for checkpoint record.
Here is a broken scenario before this patch:
- Create standby like `gpinitstandby -s localhost -P 12345 -F pg_system:/tmp/standby/ps,fs1:/tmp/standby/fs1`
- Create two connections c1 and c2
- c2:
- `create tablespace ts1 filespace fs1;`: double check the new …
=> Protect checkpoint from MMXLOG record insertion.

src/backend/access/transam/xlog.c
Removed the overlapping information logged under log_checkpoints guc
and Debug_persistent_recovery_print guc.
Moved all the information log under Debug_persistent_recovery_print
to use log_checkpoints.
Signed-off-by: Xin Zhang <xzhang@pivotal.io>
=> Cleanup logging in CreateCheckPoint()

src/test/tinc/tincrepo/partitioning/staticselection/sql/setup/setup.sql, src/test/tinc/tincrepo/query/cte/answer/cte_functest_52.ans, src/test/tinc/tincrepo/query/cte/answer/cte_functest_53.ans, src/test/tinc/tincrepo/query/cte/answer/cte_functest_54.ans, src/test/tinc/tincrepo/query/cte/answer/cte_functest_67.ans, src/test/tinc/tincrepo/query/cte/answer/cte_functest_68.ans, src/test/tinc/tincrepo/query/cte/answer/cte_functest_9.ans, src/test/tinc/tincrepo/query/cte/sql/cte_functest_9.sql, src/test/tinc/tincrepo/query/joins/lasj/sql/setup.sql, src/test/tinc/tincrepo/query/statistics/expected/analyze_rootpartition_correctness.ans, src/test/tinc/tincrepo/query/statistics/sql/analyze_rootpartition_correctness.sql
Fixed Optimizer functional test Part 1
Issues faced:
1 - Error Message Change
2 - Different results due to upstream analyze
3 - Parsing of explain plan had issues due to extra space in the pattern
4 - Cast Issues
There is one case which still needs to be fixed but is blocked on explain bug. Will be done in a followup story.
=> 136084309 opt func part1

src/backend/utils/misc/guc_gp.c
By request from @vraghavan78. @karthijrk @foyzur Please take a look.
=> Set codegen off by default.

gpMgmt/test/behave/mgmt_utils/backup.feature, gpMgmt/test/behave/mgmt_utils/steps/data/gpcrondump/guc_role_create_table.sql, gpMgmt/test/behave/mgmt_utils/steps/data/gpcrondump/guc_session_only.sql, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave_utils/PgHba.py
*  Move backup/restore privileges tinc tests to behave
*  Move openbar tinc test into behave
-- add behave test for gp_default_storage_options
-- add PgHba class to represent pg_hba.conf for textual manipulation
This eliminates a full 4 hour test suite.
=> Migrate tinc tests to behave

src/backend/postmaster/syslogger.c
There are two issues with current logfile_getname()
- First, it doesn't honor the `gp_log_format` GUC. Originally,
when the format is CSV, then `.csv` is used, and when format is TEXT,
the `.log` if used. However, currently the `.csv` is always used regardless
of the `gp_log_format` settings, hence make the content of the file
and suffix inconsistent.
- Second, it mistakenly generate logs with wrong suffix `.csv.csv`
during logfile_rotate(), due to the wrong assumption of the filename
always containing `.log` when suffix is NULL. Also, due to the calling
sequence of the logfile_rotate, an extra empty file is generated, e.g.
in this case, the file with `.csv.csv` is always empty.
Fix in this patch bring back original GPDB behavior. After the fix,
we generated correct extension, however, …
=> Fix logfile_getname()

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
@armenatzoglou @hsyuan -- please take a look.
=> Fix warning for unused variable due to removal of sort limit.

src/backend/commands/sequence.c
Postgres merge introduced init_sequence() which can optionally lock sequence
relation.
In GPDB, single sequence server instance is used to generate sequence values
for all requests coming from segments, hence it doesn't require a lock on
sequence relation.
There are three concurrent scenarios when using sequence:
Scenario A: concurrent requests from segments:
create table t1 (c int, d serial) distributed by (c);
insert into t1 select i from generate_series(1, 100) i;
Scenario B: concurrent requests from master:
tx1: select nextval('t1_c_seq'::regclass);
tx2: select nextval('t1_c_seq'::regclass);
Scenario C: concurrent requests from both master and segments
tx1: select nextval('t1_c_seq'::regclass);
tx2: insert into t1 values (200, default);
Scenario A is protected by the single instance …
=> Locking on sequence relation is not required for sequence server

src/backend/tcop/postgres.c
This fixes a deadlock scenario in filerep postmaster reset. We
encountered a situation in our testing where injecting PANIC on
primary to force a postmaster reset would cause the mirror to hang
while waiting for a child backend process to exit. The child backend
process sends a message to the postmaster to start terminating its
child processes and then runs proc_exit. The postmaster will then
start sending exit signals to its child processes. In rare cases, the
child backend process described here can encounter a deadlock where
authdie from SIGQUIT is called before its natural proc_exit finishes.
Example backtrace of the deadlock:
```
#0  0x0000003c1e8f82ce in __lll_lock_wait_private () from /lib64/libc.so.6
#1  0x0000003c1e87d0a0 in _L_lock_5189 () from /lib64/libc.so.6
#2 …
```
=> Make authdie use proc_exit and check if one is already in progress.

ci/pulse/api/lib/pulse_build_result.rb, ci/pulse/api/monitor_pulse.yml, ci/pulse/api/trigger_pulse.yml
=> Pulse api: Add retries; small image; more output

gpdb-doc/README.md
Download links also provided.
@xinzweb - this update should prevent the problem you ran into in building the docs.
=> updating README to require the full-easy-install DITA-OT

src/backend/postmaster/backoff.c
The PR doesn't change any logic of backoff mechanism. It just changed counter intuitive variable name from `nobackoff` to `backoff`, and rename function from `isInvalid` tp `isValid` to help us understand the code easily. In addition, explanation of backoff mechanism and proper comments for the codes are added.
=> Add comments for backoff mechanism

src/test/regress/expected/DML_over_joins.out, src/test/regress/expected/DML_over_joins_optimizer.out, src/test/regress/sql/DML_over_joins.sql
Make the test deterministics. Similar to https://github.com/greenplum-db/gpdb/pull/1655
@hardikar @danielgustafsson @d @oarap @bhuvnesh2703 etc. please take a look.
=> Make DML_over_joins tests less flaky

gpAux/extensions/gpcloud/include/s3utils.h, gpAux/extensions/gpcloud/src/compress_writer.cpp, gpAux/extensions/gpcloud/src/decompress_reader.cpp, gpAux/extensions/gpcloud/src/s3interface.cpp, gpAux/extensions/gpcloud/src/s3url.cpp, gpAux/extensions/gpcloud/src/s3utils.cpp, gpAux/extensions/gpcloud/test/s3interface_test.cpp
Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>
=> gpcloud: hash and sign the payload

src/backend/optimizer/path/joinrels.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_1.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
When we create Left Anti Semi Join relations in case the left
side is a dummy relation, it implies that the join relation
is also a dummy relation.
Signed-off-by: Omer Arap <oarap@pivotal.io>
=> Handle dummy rel for Left Anti Semi Join [#134705163]

src/bin/pg_dump/cdb/cdb_dump_agent.c, src/bin/pg_dump/pg_dump.c, src/bin/psql/describe.c
Due to catalog change of ON MASTER patch, psql, pg_dump, cdb_dump_agent is not working properly against old gpdb version if there's external table.
This PR will fix this.
Signed-off-by: Peifeng Qiu <pqiu@pivotal.io>
=> Fix MU tests after ON MASTER patch

gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
Added test to cover option value issues.
=> Add gpconfig unit test for change value and master flags

src/test/tinc/tincrepo/functions/builtin/__init__.py, src/test/tinc/tincrepo/functions/builtin/sql/select_notable_pg_lock_status.sql
We updated the test to adapt to the new output format of `pg_lock_status()`
=> Unskip select_notable_pg_lock_status test

gpdb-doc/dita/ref_guide/sql_commands/ALTER_FUNCTION.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_FUNCTION.xml, gpdb-doc/dita/ref_guide/sql_commands/SET.xml
- updated the SET, CREATE and ALTER FUNCTION SQL command reference pages
- included new examples in the CREATE and ALTER FUNCTION pages
wasn't sure if i needed to update release notes or any feature pages?
=> doc updates for per-function guc setting support

concourse/pipelines/pipeline.yml, gpMgmt/bin/gppylib/operations/persistent_rebuild.py, gpMgmt/test/behave/mgmt_utils/gppersistent_rebuild.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, src/test/tinc/Makefile, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/persistent_tables/test_PT_RebuildPT.py
Add behave tests to pt_rebuild, include a pipeline task for a couple of tinc tests, and ignore a tinc test judged to be irrelevant by Storage team
=> persistent table (pt) rebuild: add more behave tests, add tinc task

src/backend/catalog/system_views.sql, src/backend/commands/user.c, src/backend/parser/gram.y, src/backend/utils/resgroup/resgroup.c, src/include/utils/resgroup.h, src/test/regress/expected/resource_group.out, src/test/regress/greenplum_schedule, src/test/regress/sql/resource_group.sql
In this patchset we implemented the CREATE/ALTER ROLE RESOURCE GROUP syntax, testcases were also provided.
=> CREATE/ALTER ROLE RESOURCE GROUP

src/backend/cdb/cdbexplain.c
While addressing the PR #1753, I changed the enum to string. But in some place, I missed changing the '==' operator to 'strcmp'. This cause some assert failure and the issue #1880 has been created.
I took the PR #1952, refactored and opened this PR.
=> Sort issue

src/include/port/atomics/arch-arm.h, src/include/storage/s_lock.h
This is essentially a backport of https://github.com/postgres/postgres/commit/4893ccd02459fdb444f4f4b34c441eb899592879
=> Enabling build on ARM64

README.md
See here for how it actually looks like https://github.com/rvs/gpdb#contributing
This is very much available for peer review and comments (especially the peer review and comments section ;-))
=> Updating a "how to contribute" section

gpdb-doc/dita/admin_guide/load/topics/g-mapreduce-sample-code.xml, gpdb-doc/dita/client_tool_guides/client/unix/unix_client_install.xml, gpdb-doc/dita/client_tool_guides/client/unix/unix_client_tool_ref.xml, gpdb-doc/dita/ref_guide/yaml_spec.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpmapreduce.xml
Notices for deprecation of gpmapreduce and associated YAML file.
=> Deprecate gpmapreduce

gpdb-doc/dita/ref_guide/feature_summary.xml
=> Updatable cursor support in pg-gpdb feature differences chart.

src/bin/gpfdist/regress/.gitignore, src/bin/gpfdist/regress/input/exttab1.source, src/bin/gpfdist/regress/output/exttab1.source, src/test/regress/.gitignore, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
The old cdbfast test suite had these, move to ICW.
Signed-off-by: Yuan Zhao <yuzhao@pivotal.io>
=> Add more test cases for writable external table

gpMgmt/bin/gpconfig, gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
--only show error for lacking MASTER_DATA_DIRECTORY for --file, not
other options
=> gpconfig: change option validation for --file

concourse/scripts/compile_gpdb.bash, concourse/scripts/setup_gpadmin_user.bash, gpAux/Makefile, gpAux/releng/make/dependencies/ivy.xml, gpAux/releng/releng.mk
We made the following changes to compile gpdb5 on a new sles11 image we built.
=> Compile gpdb5 on sles11

gpMgmt/bin/gppylib/test/unit/test_unit_gpstop.py
* Initial stab into creating unit tests for gpstop
=> Add unit test for gpstop for better code coverage.

gpMgmt/bin/gppylib/test/unit/gp_unittest.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py
* Initial stab into creating unit tests for gpstart
=> Add unit test for gpstart for better code coverage.

gpdb-doc/dita/best_practices/encryption.xml
=> docs: add a ref to Zettaset [#141726793]

gpdb-doc/dita/admin_guide/load/topics/g-setting-compression-options-for-hadoop-writable-external-tables.xml, gpdb-doc/dita/gpdb-webhelp.ditaval, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/ref_guide/sql_commands/sql_ref.xml
fixing/cleaning up dita control files, some minor edits.
[ci skip]
=> GPDB DOCS - cleaning up ditamap ditaval files, some minor edits/fixes

src/backend/access/transam/xlog.c
Initialize TransactionXmin to avoid situations where scanning pg_authid or other
tables mostly in BuildFlatFiles() via SnapshotNow may try to chase down
pg_subtrans for older "sub-committed" transaction. File corresponding to which
may not and is not supposed to exist. Setting TransactionXmin will avoid calling
SubTransGetParent() in TransactionIdDidCommit() for older XIDs.
Repro for record of one such case:
```
CREATE ROLE foo;
BEGIN;
SAVEPOINT sp;
DROP ROLE foo;
RELEASE SAVEPOINT sp; -- this is key which marks in clog as sub-committed.
kill or gpstop -air
< N transactions to atleast cross pg_subtrans single file limit roughly
CLOG_XACTS_PER_BYTE * BLCKSZ* SLRU_PAGES_PER_SEGMENT >
restart -- errors recovery with missing pg_subtrans
```
Note:
Merge with 9.0 will get rid of …
=> Avoid could not open file pg_subtrans/xxx situation during recovery.

README.md
See how it renders here: https://github.com/rvs/gpdb#travis-
=> Adding link to Concourse CI

gpMgmt/bin/gppylib/test/unit/test_unit_gprestore_filter.py, gpMgmt/bin/gprestore_filter.py
Move most of the logic into functions, clean up dead code, rename variables/functions,
and cover the process_schema function with unit tests.
Signed-off-by: Chris Hajas <chajas@pivotal.io>
=> Refactor schema filtering in gprestore_filter.

src/backend/executor/nodeNestloop.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/optimizer/plan/createplan.c, src/include/nodes/execnodes.h, src/include/nodes/plannodes.h
Remove the dead code for a nested loop.
@hardikar @foyzur @hsyuan  Please take a look.
=> Nl deadcode

gpAux/Makefile, gpAux/extensions/Makefile
=> revert-2220-fixorfce

concourse/pipelines/pipeline.yml, gpAux/gpperfmon/README.md, gpAux/gpperfmon/src/gpmon/gpmondb.c, gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
-- add README for macOS build and configuration notes
=> gpperfmon: add behave test for running, add pipeline job

src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/expected/bfv_catalog.out, src/test/regress/expected/bfv_catalog_optimizer.out, src/test/regress/expected/bfv_olap.out, src/test/regress/expected/bfv_olap_optimizer.out, src/test/regress/expected/bfv_subquery.out, src/test/regress/expected/bfv_subquery_optimizer.out, src/test/regress/expected/qp_dpe.out, src/test/regress/expected/qp_dpe_optimizer.out, src/test/regress/expected/qp_query_execution.out, src/test/regress/expected/union_gp.out, src/test/regress/sql/bfv_aggregate.sql, src/test/regress/sql/bfv_catalog.sql, src/test/regress/sql/bfv_olap.sql, src/test/regress/sql/bfv_subquery.sql, src/test/regress/sql/qp_dpe.sql, src/test/regress/sql/qp_olap_window.sql, src/test/regress/sql/qp_query_execution.sql, src/test/regress/sql/union_gp.sql
This is similar to  https://github.com/greenplum-db/gpdb/commit/6858104f82ff73ef4c3778af639dbfc588459ab3
@d @hsyuan @bhuvnesh2703 @oarap please take a look.
=> Fix tests to avoid explain_format by atmsort

gpdb-doc/dita/admin_guide/intro/about_mvcc.xml, gpdb-doc/dita/admin_guide/intro/mvcc_example.xml, gpdb-doc/dita/admin_guide/managing/maintain.xml
update for GPDB 5.0 docs.
[ci skip]
=> GPDB DOCS - add short note about lazy XID (XID only for DDL or DML)

gpAux/releng/releng.mk
Corresponding GPORCA PR: https://github.com/greenplum-db/gporca/pull/167
=> Bump ORCA to 2.24

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h, src/test/regress/expected/bfv_partition.out, src/test/regress/expected/bfv_partition_optimizer.out, src/test/regress/sql/bfv_partition.sql
=> Remove GUC optimizer_static_partition_selection

gpMgmt/bin/gpdbrestore, gpMgmt/bin/gppylib/operations/backup_utils.py, gpMgmt/bin/gppylib/operations/restore.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_backup_utils.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpdbrestore.py
- This also fixes a bug where we looked for the report file in the
wrong directory
Signed-off-by: Karen Huddleston <khuddleston@pivotal.io>
=> Split _search_for_latest and add unit tests

gpdb-doc/dita/admin_guide/managing/monitor.xml, gpdb-doc/dita/admin_guide/perf_troubleshoot.xml
update existing references to session_level_memory_consumption view with new idle_start column.
=> add idle time to session_level_memory_consumption view

src/backend/utils/misc/guc_gp.c
This GUC should be a power of 2 for the proper functioning of HashAgg. It is not discoverable, but can be changed by customers - so this check is important.
shardikar=# set gp_hashagg_default_nbatches = 32;
SET
shardikar=# set gp_hashagg_default_nbatches = 33;
ERROR:  invalid value for parameter "gp_hashagg_default_nbatches": 33
@foyzur @hsyuan @karthijrk Please take a look.
=> Ensure gp_hashagg_default_nbatches is a power of two.

gpAux/releng/releng.mk, src/backend/gpopt/utils/COptTasks.cpp
These are the changes required to accommodate ORCA changes from PR:
https://github.com/greenplum-db/gporca/pull/159
=> Change calls to ORCA functions to match changes in ORCA.

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave_utils/utils.py
-- refactor previous tests to DRY out repeated setup
=> gpperfmon: Add behave test for system_history

concourse/pipelines/pipeline.yml, gpAux/releng/make/dependencies/ivy.xml, gpMgmt/test/behave/mgmt_utils/netbackup.feature, src/bin/pg_dump/cdb/Makefile
Pulls netbackup 7.7 libraries from artifactory and adds new job to concourse pipeline
Authors: Karen Huddleston and Chris Hajas
=> Enable GPDB to backup/restore with Netbackup client 7.7

gpdb-doc/dita/admin_guide/topics/g-greenplum-extension-parameters.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/sql_commands/COPY.xml
Add XML GUCs xmlbinary, xmloption.
Also added note to COPY about copying XML data.
The GUC reference information was reviewed previously.
[ci skip]
=> GPDB DOCS - XML gucs xmlbinary, xmloption

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
Signed-off-by: Melanie Plageman <mplageman@pivotal.io>
=> gpperfmon: Add behave test for segment_history

src/test/regress/expected/gp_optimizer.out, src/test/regress/sql/gp_optimizer.sql
Minor clean up. @hsyuan @d @oarap @bhuvnesh2703
=> Clean up gp_optimizer tests. Remove extra dashes

gpMgmt/bin/README, gpMgmt/bin/gpmovemirrors, gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gppylib/db/catalog.py, gpMgmt/bin/gppylib/db/test/regress/test_regress_catalog.py, gpMgmt/bin/gppylib/db/test/test_catalog.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gptransfer, gpMgmt/bin/lib/gpconfigurenewsegment, gpMgmt/sbin/gpgetstatususingtransition.py, gpMgmt/sbin/gprepairmirrorseg.py, gpMgmt/sbin/gpsegstop.py, gpMgmt/sbin/gpsegtoprimaryormirror.py
While looking at other things, spotted that there were quite a few functions in catalog.py that were unused. Remove these, and also remove imports of gppylib.db.catalog when unused.
I'm far from a Python hacker so I might be off in the weeds completely here, clues are warmly welcomed.
=> Remove dead code from catalog.py

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This PR is based on https://github.com/greenplum-db/gpdb/pull/2309. The first 2 commits will be pushed on the other PR.
=> gpperfmon: Add behave test for log_alert_history

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave_utils/utils.py
-- remove commented-out test (moved to tracker)
-- refactor behave "summary" step for qamode, ensuring configuration is in place
=> gpperfmon: add behave test for diskspace history

concourse/pipelines/pipeline.yml, concourse/pipelines/pr_pipeline.yml
@ashwinstar @hardikar @tom-meyer Please take a look.
=> Removing codegen icg from pipeline.

gpAux/releng/make/dependencies/ivy.xml
This is a follow on from https://github.com/greenplum-db/gpdb/pull/2294
Signed-off-by: Tushar Dadlani <tdadlani@pivotal.io>
=> Removed EMCConnect from ext and update the change to third-party/ext 3.1

gpAux/gpperfmon/src/gpmon/Makefile, gpAux/gpperfmon/src/gpmon/gpmondb.c
=> gpperfmon: makefile fix

gpMgmt/bin/gpconfig, gpMgmt/bin/gpexpand, gpMgmt/bin/gppylib/gphostcache.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
- Fix whitespace and indentation
- Remove unused variables
- Fix syntax errors
=> Address pylint warnings and errors (gpconfig | gpexpand)

gpAux/gpperfmon/src/gpmon/gpmmon.c, gpAux/gpperfmon/src/gpmon/gpmondb.c, gpAux/gpperfmon/src/gpmon/gpmondb.h, gpAux/gpperfmon/src/gpmon/gpmonlib.h, gpAux/gpperfmon/src/gpmon/gpperfmon41.sql, gpAux/gpperfmon/src/gpmon/gpsmon.c
pipeline to demonstrate that this removal doesn't affect other parts: https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/dev:MU_gpperfmon_remove_health
=> gpperfmon: remove health history and other DCA appliance code

src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/post_sql/expected/ao_ctas_post.ans.orca, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/post_sql/expected/co_ctas_post.ans.orca, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/post_sql/expected/heap_ctas_post.ans.orca, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/trigger_sql/sql/ao_ctas_trigger.sql, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/trigger_sql/sql/co_ctas_trigger.sql, src/test/tinc/tincrepo/mpp/gpdb/tests/storage/pg_twophase/commit_create_tests/trigger_sql/sql/heap_ctas_trigger.sql
Include distribution policy to have consistent behavior with planner and orca
=> Storage test - Fix Distribution Policy

concourse/pipelines/pipeline.yml
Signed-off-by: Tom Meyer <tmeyer@pivotal.io>
=> Drop build-# from gpdb5 artifacts

gpdb-doc/dita/ref_guide/sql_commands/ALTER_SEQUENCE.xml
Heikki says RENAMED TO is now supported.
=> Add RENAME TO option

src/backend/optimizer/util/clauses.c
=> Remove duplicate case statements in clauses.c

doc/src/sgml/ref/copy.sgml, src/test/regress/expected/gpcopy.out, src/test/regress/sql/gpcopy.sql
To test if `ON SEGMENT` is compatible with all the other options.
=> Add more cases to test COPY ON SEGMENT

src/backend/executor/execJunk.c, src/backend/executor/execMain.c, src/backend/executor/execQual.c, src/backend/executor/functions.c, src/backend/executor/nodeDML.c, src/backend/executor/nodeTableFunction.c, src/include/executor/executor.h
Signed-off-by: Gang Xiong <gxiong@pivotal.io>
=> Keep ExecInitJunkFilter() the same as upstream.

gpdb-doc/dita/ref_guide/sql_commands/SELECT.xml, gpdb-doc/dita/ref_guide/sql_commands/SELECT_INTO.xml
Add WITH clause to the SQL commands
SELECT
SELECT INTO
information from postgres docs and  https://github.com/greenplum-db/gpdb/pull/2394
=> GPDB DOCS - SELECT( INTO) - add WITH clause (common table expression)

gpdb-doc/dita/ref_guide/data_types.xml
Add overview information about pseudo-types and link to Postgres.
=> GPDB DOCS - Add information about pseudo-types.

src/test/regress/expected/segspace.out, src/test/regress/sql/segspace.sql
=> Change workset_cleanup test to not rely on absolute number of workset in

gpdb-doc/dita/ref_guide/extensions/postGIS.xml
=> DOCS: fix typos in PostGIS

gpdb-doc/dita/client_tool_guides/load/windows/win_load_install.xml
Updated Python Windows loader version from 2.5 to 2.5.4.
=> Update Python winloader to 2.5.4

gpdb-doc/dita/ref_guide/extensions/pl_python.xml, gpdb-doc/dita/ref_guide/sql_commands/DO.xml
added info about pl/python multi-dimensional array support and composite types to pl/python page. not sure if this is too detailed.
=> add info about pl/python multidim array support

gpMgmt/Makefile
- We only want to copy the file if it exists
=> Removes unittest2 from shipped gpdb

gpdb-doc/dita/utility_guide/admin_utilities/gpperfmon_install.xml
Follow up for commit c52c768edf022217947ed3439a927d8fa971ee23
=> gpperfmon: update gpperfmon install user doc IPv6

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
Please note: this test does not pass on macOS because
of an apparent failure of libsigar
Signed-off-by: Melanie Plageman <mplageman@pivotal.io>
=> gpperfmon: add test for skew_cpu and cpu_elapsed

gpdb-doc/dita/admin_guide/query/query.ditamap, gpdb-doc/dita/admin_guide/query/topics/xml-data.xml
New page includes xml datatype and xml function material.
=> Page for xml datatype

gpdb-doc/dita/admin_guide/roles_privs.xml, gpdb-doc/dita/ref_guide/extensions/pl_python.xml, gpdb-doc/dita/utility_guide/admin_utilities/gppkg.xml
Reducing number of packages installed with gppkg; correcting install methods
=> Gppkg doc updates

GNUmakefile.in, gpAux/gpdemo/Makefile
Based on feedback from new gpdb developers, we are improving
top level make targets.
https://github.com/greenplum-db/gpdb/issues/2422
=> Adds make create-demo-cluster

concourse/README.md
- Provide a high-level overview welcome section
- Remove exceptions for gpcloud -- now in this repo
- Newline/return more frequently in the markdown
=> concourse: Revise README

src/backend/optimizer/plan/createplan.c, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
ON MASTER feature is not fully supported by built-in protocols other
than s3 yet, disable it with those protocols for now.
=> Restrict 'ON MASTER' feature to custom protocols only

gpdb-doc/dita/admin_guide/ddl/ddl-partition.xml, gpdb-doc/dita/admin_guide/ddl/ddl-storage.xml, gpdb-doc/dita/admin_guide/load/topics/g-configuration-file-format.xml, gpdb-doc/dita/admin_guide/load/topics/g-importing-and-exporting-fixed-width-data.xml, gpdb-doc/dita/admin_guide/load/topics/g-write-a-transform.xml, gpdb-doc/dita/admin_guide/query/parallel-proc.xml, gpdb-doc/dita/admin_guide/query/topics/parallel-proc.xml, gpdb-doc/dita/admin_guide/test.xml, gpdb-doc/dita/client_tool_guides/client/unix/psql.xml, gpdb-doc/dita/client_tool_guides/client/windows/psqlexe.xml, gpdb-doc/dita/client_tool_guides/drivers/windows/win_connect.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/gp_toolkit.xml, gpdb-doc/dita/ref_guide/yaml_spec.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpfilespace.xml, gpdb-doc/dita/utility_guide/admin_utilities/pgbouncer-ref.xml, gpdb-doc/dita/utility_guide/client_utilities/psql.xml
Some minor documentation fixes
=> Add spaces in documentation where needed

gpMgmt/Makefile.behave, gpMgmt/test/run_behave.sh
Signed-off-by: Nadeem Ghani <nghani@pivotal.io>
=> Clarify `make behave` behavior and remove unused call

README.md, src/tools/vagrant/README.md
"make installcheck-good" -> "make installcheck-world"
=> Update documentation to reflect new test target

gpdb-doc/dita/admin_guide/components.xml, gpdb-doc/dita/admin_guide/intro/about_gp.xml
libpq is probably the most common API for PostgreSQL.
=> add "libpq" to list of common APIs

README.md
=> Remove mapreduce recommendation from readme

src/test/regress/expected/rangefuncs_cdb.out, src/test/regress/sql/rangefuncs_cdb.sql
Few minor updates in error messages and comments.
=> Update error messages/comments in rangefuncs_cdb [#146175795]

gpdb-doc/dita/admin_guide/perf_troubleshoot.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpcheck.xml
Also removes notice gpcheck is deprecated and use gpsupport instead.
=> Deprecate gpsupport

gpdb-doc/dita/ref_guide/extensions/pl_java.xml, gpdb-doc/dita/ref_guide/extensions/pl_r.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_LANGUAGE.xml, gpdb-doc/dita/utility_guide/admin_utilities/gppkg.xml, gpdb-doc/dita/utility_guide/client_utilities/createlang.xml
Updating per latest gppkg distributions available with alpha 5.  Also conditionalizing so that the gppkg instructions aren't built with OSS docs.
=> Updating/Conditionalizing PL/Java PL/R topics

gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
Clause has been removed from CREATE EXTERNAL TABLE.
=> Remove LOG ERRORS INTO note

gpdb-doc/dita/best_practices/ha.xml
Includes changes from enterprise guide.
=> Docs: Add backup best practices from field.

concourse/pipelines/pipeline.yml, concourse/scripts/behave_gpdb.bash, concourse/scripts/common.bash, concourse/tasks/behave_gpdb.yml, gpMgmt/Makefile, gpMgmt/bin/.gitignore, gpMgmt/bin/gpcheck, gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py, gpMgmt/bin/gppylib/gpcheckutil.py, gpMgmt/bin/gppylib/operations/gpcheck.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_gpcheck.py, gpMgmt/doc/gpcheck_help, gpMgmt/doc/gpconfigs/gpcheck.cnf, gpMgmt/sbin/gpcheck_hostdump, gpMgmt/test/behave/mgmt_utils/gpcheck.feature
Added the file and bit of refactor to make `gpcheck -?` work. @skahler-pivotal not sure how far you wanted us to go -- we bring in the gpcheck.cnf file but haven't yet seen it in action.
=> Resurrect gpcheck

gpdb-doc/dita/admin_guide/intro/about_ha.xml
Mirrors must reside on different storage systems too.
Master failover must be triggered externally.
10-Gb Ethernet is optional.
=> Update HA documentation

README.md
Partiall addresses https://github.com/greenplum-db/gpdb/issues/2422
=> Restructures readme to put build directions front and center

src/backend/executor/nodeSeqscan.c, src/include/executor/nodeSeqscan.h
- Only difference is `#if 0` / `#endif` around the whole file so that
it's clear to developer utilities that these aren't compiled in
Will reduce future merge conflicts significantly. Alternative to #2573
=> Reset file (unused by GPDB) to Postgres 8.3.23

gpMgmt/doc/gpperfmon_install_help, gpdb-doc/dita/utility_guide/admin_utilities/gpperfmon_install.xml
In the dita file, I conditionalized the FIPS authentication method so it won't appear in 5.x user docs. Please verify that this is correct.
from story #146663167
=> Docs gpperfmon install

concourse/pipelines/pipeline.yml, gpMgmt/test/behave/mgmt_utils/gppkg.feature
Also, we removed redundant configuration from the concourse pipeline
=> gppkg: add behave test and concourse job

gpMgmt/bin/gpcrondump, gpMgmt/bin/gppylib/test/unit/test_cluster_gpcrondump.py
Signed-off-by: Chris Hajas <chajas@pivotal.io>
=> Add statistics file to list of pipes in gpcrondump --list-backup-files

src/backend/optimizer/path/joinpath.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
Fixes github issue #2195, reported by @Toknowledge.
=> Don't generate invalid plans with LASJ merge joins.

src/backend/optimizer/path/joinpath.c, src/test/regress/expected/bfv_planner.out, src/test/regress/sql/bfv_planner.sql
=> Remove incorrect optimizations on IS NOT FALSE.

gpdb-doc/dita/admin_guide/highavail/topics/g-overview-of-high-availability-in-greenplum-database.xml, gpdb-doc/dita/admin_guide/highavail/topics/g-overview-of-master-mirroring.xml, gpdb-doc/dita/admin_guide/intro/arch_overview.xml
Additional info added based on questions from a user.
=> Adding extra concepts

gpdb-doc/dita/admin_guide/ddl/ddl-partition.xml, gpdb-doc/dita/admin_guide/expand/expand-redistribute.xml, gpdb-doc/dita/admin_guide/query/topics/parallel-proc.xml
Replacement for https://github.com/greenplum-db/gpdb/pull/2595 which pulled in extra files.
=> Update timestamps, correct example

src/bin/pg_dump/cdb/cdb_dump_agent.c
This functionality was included with pg_dump, but was missing from
gpcrondump.
=> Fix gpcrondump to correctly backup ordered aggregates

gpAux/gpdemo/README
Remove Solaris documentation
Update port numbers
Add environment variables
=> Update gpdemo documentation

gpMgmt/bin/gppylib/operations/restore.py
Previously, if the statistics for a table were dumped and then a table column was dropped before statistics were restored, the attribute numbers from the dump would not match the attribute numbers for the table and JOIN queries run after the restore could error out.
This commit adds a processing step for the attribute numbers in the dump file to ensure that they match the attribute numbers in pg_statistic in the target database.
Authors: Chris Hajas, Jamie McAtamney
=> Correctly restore statistics for tables with dropped columns

gpMgmt/bin/gpload.py
gpload.cleanupSql() in the `finally` block may throw a `SystemExit`
exception, which will not be caught by `except Exception:` and exit
before cleaning up others like gpfdist processes.
This commit catches `SystemExit`, and do the stop_gpfdists() before
cleanupSql() to avoid this situation.
Signed-off-by: Xiaoran Wang <xiwang@pivotal.io>
=> Fix gpload exiting before cleaning up

gpAux/gpperfmon/src/gpmon/gpmon_agg.c, gpAux/gpperfmon/src/gpmon/gpsmon.c, gpMgmt/test/behave/mgmt_utils/gpperfmon.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
sigar_proc_cpu_get is the function which takes a pid
and goes to the cpu and gets the cpu_elapsed value for that pid at a
given moment.
get_pid_metrics saves the information into a hash table within the
gpsmon process. That pid only gets wiped out of the hashtable when
gpmmon requests a dump command to gpsmon.
gpsmon process sends tcp packets with information about cpu_elapsed
(amount of cpu cycles spent on a given
slice/process). Doing a 'dump' clears out the gpsmon hashtables.
This could lead to scenarios where a query has ended,
the process has died, and the sigar_proc_cpu_get function can't find the pid
so it puts 0 into the struct which is updating the hashtable so the
hashtable has a 0 for cpu_elapsed and then this is what is in
queries_tail and so queries_history ends up having a 0 …
=> gpperfmon: Fix incorrect data saved into queries_history table

config/orca.m4, configure, gpAux/releng/releng.mk, src/test/regress/expected/bfv_dd_types.out, src/test/regress/expected/bfv_dd_types_optimizer.out, src/test/regress/sql/bfv_dd_types.sql
This PR is corresponding to the GPORCA PR: https://github.com/greenplum-db/gporca/pull/195 and covers the following
- Bump ORCA version
- Fix tests
=> Reorder scalar cmp child

config/orca.m4, configure
Fix ORCA version error message.
=> Fix ORCA version error message

gpMgmt/doc/gpconfig_help, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_configuration_history.xml
Updates references to Pivotal GSS or Greenplum customer support. 
[skip ci]
=> Docs gss rename

gpMgmt/bin/gpload.py
1. Log raw string if it can't be decoded as unicode.
2. If similar exception issues in log(), continue processing left log with a warning.
3. If other exception issues in CatThread, log thread exit without blocking worker process,
and report warning "gpfdist log halt because Log Thread got an exception:".
Manually tested on some special env, it is hard to add CI test for this case.
=> Fixed gpload freezed when logging some non-unicode data

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
Seems like a good thing to test.
=> Add test case for writable external table with more URIs than segments.

README.md
Signed-off-by: John Gaskin <johntgaskin@gmail.com>
Signed-off-by: Todd Sedano <tsedano@pivotal.io>
=> Fixes readme confusion over steps for mac vs linux

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
If gpdb and orca is build with debugging enabled, there is an assert in
orca to check if the upper and lower bound are both closed.
`GPOS_ASSERT_IMP(FSingleton(), fLowerClosed && fUpperClosed);`
The histogram that is stored in pg_statistics might lead to have a
singleton buckets as follows: `10, 20, 20, 30, 40` which will lead to have
buckets in this format: `[0,10), [10, 20), [20,20), [20,30), [30,40]`
This will cause assert to fail since [20,20) is a singleton bucket but
its upper bound is open.
With this fix, the generated buckets will look like below:
`[0,10], [10,20), [20,20], (20,30), [30,40]`
Signed-off-by: Shreedhar Hardikar <shardikar@pivotal.io>
=> Fix having singleton bucket in histogram for debug build

gpMgmt/bin/gppylib/programs/gppkg.py, gpMgmt/bin/gppylib/test/unit/test_unit_gppkg.py
When a user has multiple gppkgs installed, and they try to run gppkg
--remove, we were actually giving back all of the packages instead of
the specific one that the user wants to remove.
Tighten up our regex to match only the name that the user specified in
the argument.
Make it so that gppkg --remove will now do an equality check <package
name>.gppkg before trying out the previous behavior. Message the user if
there is more than one match.
Signed-off-by: Marbin Tan <mtan@pivotal.io>
=> gppkg: Fix gppkg --remove name matching regex

config/orca.m4, configure, gpAux/releng/releng.mk, src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/include/gpopt/translate/CTranslatorDXLToPlStmt.h, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/expected/gp_explain_optimizer.out
Translating the newly added `CDXLPhysicalValuesScan` and `CDXLScalarValuesList` to VALUESCAN node with values_lists in GPDB.
=> DXL to PLNSTMT Translation for Valuescan [#147774757]

gpMgmt/test/behave/mgmt_utils/backup_and_restore_backups.feature, gpMgmt/test/behave/mgmt_utils/backup_and_restore_restores.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is an internal utility called by gpdbrestore and should not be called directly by a user.
=> Remove tests for gp_restore

gpMgmt/bin/gppylib/test/unit/test_unit_gprestore_filter.py, gpMgmt/bin/gprestore_filter.py
Signed-off-by: Tom Meyer <tmeyer@pivotal.io>
=> Don't skip schema privileges during filtered restore

src/backend/utils/resgroup/resgroup-ops-linux.c
In the past we use hard coded path "/sys/fs/cgroup" as cgroup mount
point, this can be wrong when 1) running on old kernels or 2) the
customer has special cgroup mount points.
Now we detect the mount point at runtime by checking /proc/self/mounts.
Signed-off-by: Ning Yu <nyu@pivotal.io>
=> Detect cgroup mount point at runtime.

gpdb-doc/dita/ref_guide/gpperfmon/db-database.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-diskspace.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-filerep.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-interface-stats.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-log-alert.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-queries.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-segment.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-socket-stats.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-system.xml, gpdb-doc/dita/ref_guide/gpperfmon/dbref.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpperfmon_install.xml
Clarifies how alert logs are captured and rotated, adds gpmmon/gpsmon process overview.
=> gpperfmon overview improvements

gpMgmt/bin/gpload.py
It's useful and important for debugging.
=> Log gpload threads' terminating

concourse/pipelines/pipeline.yml, concourse/scripts/run_behave_test.sh, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Add test to verify preservation of checksum GUC configuration after gprecoverseg.
Also, use terraform for the testing infrastructure.
=> gprecoverseg respects GUC for checksums, using terraform 

gpMgmt/bin/gppylib/test/unit/test_unit_gprestore_filter.py, gpMgmt/bin/gprestore_filter.py
Signed-off-by: Karen Huddleston <khuddleston@pivotal.io>
=> Fix gpdbrestore filter script to handle BEGIN..END block in functions

gpdb-doc/dita/utility_guide/admin_utilities/gpinitsystem.xml
Adding info for previously-undocumented options.
=> DOCS: gpinitsystem additions

concourse/pipelines/pipeline.yml, concourse/scripts/gppkg_behave.sh, concourse/tasks/gppkg_behave.yml, gpMgmt/bin/gppylib/commands/base.py, gpMgmt/bin/gppylib/commands/test/unit/test_unit_base.py, gpMgmt/bin/gppylib/test/unit/test_unit_command.py, gpMgmt/test/behave/mgmt_utils/gppkg.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Add multi-node testing with terraform for gppkg.
Add test for gppkg --migrate
* gppkgs installed on the original master should be installed on the new master and all segments
=> Add gppkg behave terraform setup and gppkg behave test

concourse/pipelines/pipeline.yml
Added a single get job that triggers for any commit which passes _all_ the tests (including the nightly timer).  This is used to help identify possible commits to tag for release.
Because of the changes to the pipeline shape I've also introduced groups to keep the pipeline readable
=> added job to identify release candidates

src/backend/access/transam/test/xact_test.c
Originally, we didn't verify the correct error level in our helper method.
=> Fix up the xact_test for elog verification.

concourse/pipelines/pipeline.yml
Signed-off-by: Jim Doty <jdoty@pivotal.io>
=> Group remaining Pulse jobs and CCP adopted jobs

concourse/scripts/ic_gpdb_resgroup.bash
ccp cluster need bzlib.h to pass configure
=> Install bzip2-devel on ccp cluster

src/include/catalog/pg_appendonly.h
Seems harmless, in this direction, but let's be tidy.
=> Set Natts_pg_appendonly correctly.

gpdb-doc/dita/ref_guide/sql_commands/CREATE_OPERATOR.xml
Update MERGES and HASHES, removed SRT1, SORT2, LTCMP, GTCMP.
=> Revise reference doc for CREATE OPERATOR

gpdb-doc/dita/ref_guide/extensions/postGIS.xml
PostGIS topic has been updated to reflect the following
--PostGIS extension includes a new install/uninstall script.
--PostGIS SQL scripts to install/uninstall PostGIS and PostGIS raster have been moved.
=> DOCS: PostGIS docs - add new install script information

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/utility_guide/admin_utilities/gpinitsystem.xml
Adds HEAP_CHECKSUM to the gpinitsystem config file section and the heap_checksums GUC to the GUC reference.
=> Add heap checksums to gpinitsystem ref and GUC reference

concourse/pipelines/pipeline.yml, concourse/pipelines/pr_pipeline.yml, concourse/scripts/validate_pipeline_release_jobs.py, concourse/tasks/validate_pipeline.yml
Pipeline demonstrating the change https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/dev:cjameson_concourse_pipeline_alert_new_release_jobs
@doty-pivotal to take a look at the first re-ordering commit
Can all be squashed if makes sense.
=> Concourse pipeline: alert job writers about the new release checker job

src/backend/access/hash/hashfunc.c
These calls got lost during the 8.3 merge. There was a different mechanism
in GPDB earlier, to free these, and we replaced it with the upstream
mechanism in the merge, but missed these lines.
=> Fix memory leak in hashtext.

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/init_file_resgroup, src/test/isolation2/input/uao/max_concurrency.source, src/test/isolation2/input/uao/max_concurrency2.source, src/test/isolation2/output/resgroup/enable_resgroup.source, src/test/isolation2/output/uao/max_concurrency.source, src/test/isolation2/output/uao/max_concurrency2.source, src/test/regress/expected/gp_toolkit_resgroup.out, src/test/regress/expected/resource_queue_resgroup.out, src/test/regress/expected/wrkloadadmin_resgroup.out, src/test/regress/init_file, src/test/regress/output/resource_queue_function_resgroup.source, src/test/regress/pg_regress.c, src/test/regress/pg_regress.h, src/test/regress/pg_regress_main.c, src/test/regress/regress.c
ICW is performed with resqueue by default, and there will be some failures when performed with resgroup, this PR is to fix them.
=> Fix ICW failures when resgroup enabled

src/backend/commands/resgroupcmds.c, src/backend/tcop/utility.c, src/test/isolation2/expected/resgroup/resgroup_concurrency.out, src/test/isolation2/expected/resgroup/resgroup_transaction.out, src/test/isolation2/sql/resgroup/resgroup_concurrency.sql, src/test/isolation2/sql/resgroup/resgroup_transaction.sql
Signed-off-by: Zhenghua Lyu <zlv@pivotal.io>
=> Make resource group DDL cannot run inside transaction block.

concourse/pipelines/pipeline_coverity.yml
Signed-off-by: Jingyi Mei <jmei@pivotal.io>
=> Update coverity job to run daily

gpAux/extensions/pxf/Makefile, gpAux/extensions/pxf/expected/pxfinvalid.out, gpAux/extensions/pxf/expected/setup.out, gpAux/extensions/pxf/sql/pxfinvalid.sql, gpAux/extensions/pxf/sql/setup.sql, gpAux/extensions/pxf/src/pxfprotocol.c, gpAux/extensions/pxf/src/pxfuriparser.c, gpAux/extensions/pxf/src/pxfuriparser.h, gpAux/extensions/pxf/src/pxfutils.c, gpAux/extensions/pxf/src/pxfutils.h, gpAux/extensions/pxf/test/mock/pxfuriparser_mock.c, gpAux/extensions/pxf/test/mock/pxfutils_mock.c, gpAux/extensions/pxf/test/pxfprotocol_test.c, gpAux/extensions/pxf/test/pxfuriparser_test.c, gpAux/extensions/pxf/test/pxfutils_test.c
Add pxfprotocol_validate_urls for validating URLs and the corresponding unit tests
Signed-off-by: Alexandra Wang <lewang@pivotal.io>
=> Add PXF protocol URI validation logic

src/test/regress/input/gpcopy.source, src/test/regress/output/gpcopy.source
1, remove unnecessary web tables
2, add various distribution with `ON SEGMENT` tests
3, add a zero column with `ON SEGMENT` test
=> Update gpcopy test cases

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
Addresses additional comments on closed PR: https://github.com/greenplum-db/gpdb/pull/2933#discussion_r132796314
=> Expand description of data_checksums GUC with checksum behavior and scope

gpdb-doc/dita/ref_guide/system_catalogs/pg_roles.xml
Adds missing entries to pg_roles reference page
=> Update doc entries for rolcreaterexthdfs, rolcreatewexthdfs

src/backend/optimizer/plan/createplan.c
Remove premature optimization in create_indexscan_plan, where we stripped
RestrictInfo decorations while we iterated through the list. That was
premature, because while it works, order_qual_clauses() can make use of the
information in the RestrictInfo, if it's still present. This reverts that
piece of code to the way it is in the upstream. I'm not sure if this makes
any observable difference, but let's be tidy in any case.
Also, reorder the extract_actual_clauses and order_qual_clauses calls
in create_ctescan_plan, so that order_qual_clauses is called first. For
the same reason.
=> Fix extract_actual_clauses() calls.

src/backend/commands/explain.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/optimizer/plan/subselect.c, src/backend/utils/adt/ruleutils.c, src/include/nodes/primnodes.h, src/test/regress/expected/arrays.out, src/test/regress/expected/notin.out, src/test/regress/expected/qp_correlated_query.out, src/test/regress/expected/subselect_gp.out, src/test/regress/expected/subselect_gp_optimizer.out, src/test/regress/output/table_functions.source, src/test/regress/output/table_functions_optimizer.source
Most of this was already in GPDB or done in a different way. We resolved the conflicts using clion that also corrected the indentation a little for us.
=> Cherry pick upstream commit fbcce08

src/backend/storage/buffer/bufmgr.c
Because Greenplum uses persistent tables (PT), if `gp_disable_tuple_hints` is
false, then reading PT tables during startup will cause hint bit
change, and attempt to mark page dirty, which will try to create a
Full Page Image in XLOG.
Because we are in init processing, write to XLOG is disallowed. We must
protect against the XLOG write.
=> Prevent XLOG write during init processing

concourse/pipelines/pipeline.yml, gpMgmt/test/behave/mgmt_utils/environment.py, gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Add a behave test to show that gpinitstandby uses the same data_checksum as master.
-- add pipeline task for gpinitstandby
-- introduce template to DRY some pipeline tasks for behave
=> gpinitstandby respects checksums

src/backend/storage/lmgr/proc.c
Currently, auxiliary and backend processes are defaulted to
GP_ROLE_DISPATCH.  This was kind of harmless until we started enabling
segment WAL replication.  The WAL sender would be initialized as a
backend process that would have a gp_session_id set and mppIsWriter be
True.  This would intermittently cause issues with cursors.  The writer
would open a temporary file with its session id and process id but the
reader would construct the temporary filename incorrectly with the
right session id but the WAL sender's process id.  The reader would
then fail to open the correct temporary file.
To fix this, we set Gp_role to GP_ROLE_UTILITY for all auxiliary
processes and make exceptions for certain backend processes
(Autovacuum and WAL sender).
=> Auxiliary and some backend processes should be set to GP_ROLE_UTILITY

contrib/formatter_fixedwidth/fixedwidth.c
The "if (buf->len != field_size)" block in make_val_with_blanks() function
is unreachable. The code that precedes it has just checked that buf->len
isn't larger than field_size, and if it was smaller, it was padded. Remove
it, and refactor a bit for clarity.
=> Remove unreachable code in fixedwidth formatter.

gpdb-doc/dita/utility_guide/client_utilities/psql.xml
update psql page for dx (now displays extensions) and dE (display external tables)
=> psql doc updates for dx, dE

src/backend/access/common/tupdesc.c, src/backend/catalog/pg_aggregate.c, src/backend/catalog/pg_proc.c, src/backend/utils/cache/relcache.c, src/include/fmgr.h, src/include/optimizer/planmain.h, src/include/utils/builtins.h
Hopefully avoids a couple of merge conflicts in the future.
=> Misc refactoring and comments fixes, to match upstream formatting.

src/backend/access/transam/xlog.c
During gp_expand, the guc gp_before_filespace_setup is used to skip
mmxlog and ptas information from the checkpoint record. However, the
UnpackCheckPointRecord() was expecting additional information.
The fix is to make that part optional based on the remaining length of
checkpoint record.
Signed-off-by: Xin Zhang <xzhang@pivotal.io>
=> Fix UnpackCheckPointRecord Assert failure

gpdb-doc/dita/admin_guide/load/topics/g-one-time-hdfs-protocol-installation.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/extensions/pl_java.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpconfig.xml
Updated description and examples to use new syntax.
port of reviewed 4.3.x content.
=> DOCS: update gpconfig. Updated, simplified quoting syntax for GUC values

gpdb-doc/dita/utility_guide/admin_utilities/gpstart.xml
Added
--new option --skip-heap-checksum-validation
--updated -m option. no checksum validation.
--New information about checking heap checksum validation
=> DOCS: add heap checksum information to gpstart.

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
This PR responds to comments on merged PR
=> revise to more accurately describe failed checksum verify behavior

gpMgmt/bin/gppylib/gparray.py, gpMgmt/bin/gppylib/heapchecksum.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py, gpMgmt/bin/gpstart
Signed-off-by: Nadeem Ghani <nghani@pivotal.io>
=> gpstart: verify heap_checksum matches on master and standby

src/backend/commands/resgroupcmds.c, src/test/isolation2/Makefile, src/test/isolation2/expected/resgroup/resgroup_concurrency.out, src/test/isolation2/expected/resgroup/resgroup_parallel_queries.out, src/test/isolation2/expected/resgroup/restore_default_resgroup.out, src/test/isolation2/isolation2_resgroup_schedule, src/test/isolation2/sql/resgroup/resgroup_concurrency.sql, src/test/isolation2/sql/resgroup/resgroup_parallel_queries.sql, src/test/isolation2/sql/resgroup/restore_default_resgroup.sql
This PR adds all kinds of tests for the resource group, please refer the commit message of each commit for details.
=> Add kinds of tests for resource group

GNUmakefile.in, contrib/Makefile, contrib/hstore/Makefile, contrib/hstore/expected/hstore.out, contrib/hstore/hstore_gist.c, contrib/hstore/sql/hstore.sql, src/backend/access/common/heaptuple.c
This fixes a couple of bugs that were causing crashes with hstore, and adjusts regression test output to match what you get on Greenplum. The hstore regression tests now pass.
=> Fix hstore

gpMgmt/bin/gppylib/programs/clsAddMirrors.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py
Edit:
This change adds a check to gpaddmirrors: First check if heap_checksum
setting is consistent across cluster. If not, fail immediately, else
continue with the normal workflow.
=> Gpaddmirrors heap checksum 150067435

README.md, depends/conanfile.txt
This PR achieves the following:
1. Add documentation to use conan dependency manager
2. Updates the location where the libraries and header files are installed
=> Conan depends lib header location

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_ROLE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_ROLE.xml, gpdb-doc/dita/ref_guide/sql_commands/DROP_RESOURCE_GROUP.xml
add warning to resource group GUCs and reference pages
=> qualify resgroup gucs, ref pages with expermental warning

src/backend/executor/nodeWindow.c
=> Replace custom expandable buffer implementation with StringInfo.

src/backend/access/transam/xact.c
Only a top-level transaction can have a distributed transaction ID, so
this seems more logical.
=> Move current distributed transaction ID out of the per-subxact struct.

src/backend/cdb/cdbgroup.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/makefuncs.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfuncs.c, src/backend/optimizer/plan/planwindow.c, src/backend/parser/parse_agg.c
Theses are just pro forma, as the location field isn't used for anything
after parse analysis, but let's be tidy.
=> Fix a few missing initializations of 'location' fields.

src/backend/parser/analyze.c
I guess once upon a time this was needed to get better error messages,
with error positions, but we rely on the 'location' fields in the parse
nodes nowadays. Removing this doesn't affect any of the error messages
memorized in the regression tests, so it's not needed anymore.
=> Remove unnecessary parse-analysis error position callback.

src/backend/storage/file/bfz.c
That seems like a very random place to do it (sorry for the pun). The
random seed is initialized at backend startup anyway, that ought to be
good enough, so just remove the spurious initialization from bfz.c.
In the passing, improve the debug-message to mention which compression
algorithm was used.
=> Don't initialize random seed when creating a temporary file.

README.macOS.bash
Solves https://github.com/pivotal/workstation-setup/issues/144
=> Adds python to PATH for macOS directions

README.macOS.bash
Solves https://github.com/greenplum-db/gpdb/issues/3176
=> Adds conan for macOS directions

README.linux.md, README.macOS.bash, README.md
This makes the linux directions look more like the macOS directions for the top level readme.
=> Extracts linux readme directions

src/backend/cdb/cdbvars.c, src/test/isolation2/expected/resgroup/resgroup_verify_guc.out, src/test/isolation2/isolation2_resgroup_schedule, src/test/isolation2/sql/resgroup/resgroup_verify_guc.sql
This is to fix github issue #3072
=> Verify the newval for GUC 'statement_mem' and 'max_resource_groups' only if they are actually being set.

src/backend/executor/nodeWindow.c
Refactor the EDGE_IS_* macros so that they take the current
WindowStatePerLevel as argument, rather than a WindowFrameEdge. This will
make the transition to the upstream window function implementation a bit
easier, because the upstream implementation doesn't have a WindowFrameEdge
struct.
Encapsulate access to level_state->is_rows in a macro. This is also in
preparation for the upstream implementation, which will contain that
information as a flag in the frameOptions bitmask.
Many functions used an 'is_lead' argument, and one used 'is_trail', to
keep track whether we're dealing with the leading or trailing edge.
Introduce a little enum with EDGE_TRAIL and EDGE_LEAD values, to avoid
having to remember what 'true' or 'false' means in which context.
=> Refactor EDGE_* macros in nodeWindow.c.

gpdb-doc/dita/admin_guide/workload_mgmt.xml, gpdb-doc/dita/ref_guide/extensions/pl_python.xml, gpdb-doc/dita/ref_guide/extensions/pl_r.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_LANGUAGE.xml
-Added reference to R and python Data Science package
-Updated PL/R package example
-Removed plpython (trusted) from CREATE LANGUAGE
Also minor dita fix to file admin_guide/workload_mgmt.xml
For master and 5.x
=> DOCS: updates and fixes for PL/python and PL/R

src/include/pg_config.h.in
pg_config.h.in is generated by autoheader, but it had fallen out of date.
Has everyone just been adding stuff manually to it, or how did this happen?
In any case, let's run it now.
=> Run autoheader.

README.macOS.bash
Solves https://github.com/greenplum-db/gpdb/issues/3211
=> Adds xerces-c for gporca

src/backend/storage/lmgr/proc.c, src/backend/utils/resgroup/resgroup.c, src/include/storage/proc.h
We are in the progress of refactoring resource group source code, to get a better review we'll submit the changes in separate PRs, this is the first part.
Changes in this part can all be covered with existing tests, so no new test cases were included.
Basically we split the changes into small commits, please refer to the commit messages to get their purposes.
=> Resgroup refactor (part 01)

gpMgmt/bin/gppylib/test/unit/test_unit_pysync.py, gpMgmt/bin/lib/pysync.py, gpMgmt/bin/lib/pysync_remote.py
This is backport of PR https://github.com/greenplum-db/gpdb/pull/3199 to 5X_STABLE.
The original commit messages are:
pysync: replace md5 by sha256
This utility used to confirm data transfered by doing a md5 digest. This
commit changes behavior to use sha256 instead.
Whitespace commit.
=> Backport pysync fips 150678922

concourse/pipelines/pipeline.yml, concourse/scripts/ic_gpdb_resgroup.bash
Signed-off-by: Zhenghua Lyu <zlv@pivotal.io>
=> Add pipeline job for resource group on centos7

src/backend/utils/resource_manager/memquota.c
Historically this function was used to special case a few operators that
were not considered to be MemoryIntensive. However, now it always
returns true. This commit removes the function and also moves the case
for T_FunctionScan in IsMemoryIntensiveOperator into the group that
always returns true, as this is its current behavior
=> Remove isMemoryIntensiveFunction

src/backend/optimizer/util/pathnode.c, src/test/regress/expected/qp_correlated_query.out, src/test/regress/expected/qp_correlated_query_optimizer.out, src/test/regress/expected/subselect.out, src/test/regress/expected/subselect_gp.out, src/test/regress/expected/subselect_gp_optimizer.out, src/test/regress/expected/subselect_optimizer.out, src/test/regress/expected/update_gp.out, src/test/regress/expected/update_gp_optimizer.out, src/test/regress/sql/subselect.sql
This commit contains the upstream cherry-pick 2e7469d along with the plan diff changes after merging subselect_merge branch with master.
=> Cherrypick of Upstream commits 2e7469d 

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.xml
in this PR:
- add memory_spill_ratio GUC and description
- add memory_spill_ratio GUC to resource group GUC category
- update ALTER RESOURCE GROUP to include setting MEMORY_SPILL_RATIO
- update "using resource groups" discussion to reference new memory_spill_ratio guc
=> docs - memory_spill_ratio guc and related content

src/backend/utils/resgroup/resgroup.c
This is the second part for resgroup refactor, previous part was tracked in https://github.com/greenplum-db/gpdb/pull/3246.
In this part we abstract many frequently used or complex operation sequence into helper functions to increase the code readability.
There will be more abstraction in preceding parts.
=> Resgroup refactor (part02)

gpAux/platform/Makefile
Signed-off-by: Taylor Vesely <tvesely@pivotal.io>
=> Fix distclean target for platform directory

gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
add conditionalized link to greenplum-spark connector documentation.
=> docs load/unload page - add link

gpdb-doc/dita/admin_guide/admin_guide.ditamap, gpdb-doc/dita/admin_guide/external/external-tables.ditamap, gpdb-doc/dita/admin_guide/external/g-external-tables.xml, gpdb-doc/dita/admin_guide/external/g-working-with-file-based-ext-tables.xml
promote the following topics:
- defining database objects
- inserting, updating, and deleting data
- working with external data
- loading and unloading data
- querying data
removed "working with databases" topic and rearranged a bit.
link to review staging site (you may need to refresh):
- http://docs-gpdb-review-staging.cfapps.io/500/admin_guide/intro/partI.html
=> docs - restructure admin guide top level topics

src/backend/cdb/cdbpgdatabase.c
As part of commit efed2fccaad4c5c8e3ad99b6e7479cc944bca621 new walrep state was
added 'n' (not-in-sync). The toolkit function gp_pgdatabase__() needs to be
modified as well to check for that state.
Original code not using #defines but direct characters like 's', 'c' makes it
very tricky find stuff in code. Hopefully, future chnages would be easy to spot
and make.
=> Fix gp_pgdatabase__ function by including walrep state 'n'.

src/backend/cdb/cdbgroup.c, src/backend/cdb/cdbsetop.c, src/backend/utils/mmgr/ext_alloc.c, src/include/utils/ext_alloc.h, src/include/utils/memaccounting.h
Fix compiler warnings for ext_alloc.c and callers of make_motion_gather_to_*().
=> Fixing more newly introduced compiler warnings

concourse/scripts/build_orca.py, concourse/tasks/build_gpdb_with_orca_gen_by_conan.yml, concourse/tasks/build_orca_using_conan.yml, concourse/tasks/test_with_orca_conan.yml
Add steps to build orca using conan and run icg
=> Add steps to build orca using conan and run icg

src/backend/access/aocs/aocs_compaction.c, src/backend/access/aocs/aocsam.c, src/backend/access/aocs/aocssegfiles.c, src/backend/access/aocs/test/aocsam_test.c, src/include/access/aocs_compaction.h, src/include/access/aocssegfiles.h, src/include/access/aomd.h, src/include/access/aosegfiles.h, src/include/access/appendonly_compaction.h, src/include/access/appendonly_visimap.h, src/include/access/appendonly_visimap_entry.h, src/include/access/appendonly_visimap_store.h, src/include/access/appendonlytid.h, src/include/access/appendonlywriter.h, src/include/access/distributedlog.h, src/include/access/persistentendxactrec.h, src/include/access/persistentfilesysobjname.h
I will continue to open PRs for pgindent changes, mainly to get feedback from PR pipeline run and general awareness.
Not expecting reviews for the same line-by-line (I am doing it myself and hence doing in shorter chunks / slow with it). But still useful if folks can take a look and spot issues, which then maybe added as enhancements to the pgindent tool.
=> Take-2 of pgindent (aocs and only greenplum files in include/access directory.)

src/backend/cdb/cdbexplain.c
We will be adding an extra line detailing total memory used across slices to explain analyze. This will help us in profiling memory usage from TPC-DS benchmark.
```
(slice0)    Executor memory: 322K bytes.  Peak memory: 11783K bytes.  Vmem reserved: 12288K bytes.
(slice1)    Executor memory: 8375K bytes avg x 3 workers, 8375K bytes max (seg0).
Peak memory: 9488K bytes avg x 3 workers, 9488K bytes max (seg0).  Vmem reserved: 9216K bytes avg x 3 workers, 9216K bytes max (seg0).
Total memory used across slices: 40247K  bytes
Statement statistics:
Memory used: 128000K bytes
```
Signed-off-by: Sambitesh Dash <sdash@pivotal.io>
=> Explain analyze will detail memory used across slices.

gpdb-doc/dita/utility_guide/admin_utilities/gptransfer.xml
see https://github.com/greenplum-db/gpdb/pull/3324
Will backport to 5X_STABLE
=> docs: gptransfer - add sha-256 option for --validate option

concourse/scripts/compile_gpdb.bash
This PR changes PXF build process so build result will be tailored for GPDB-specific environment properties(user, logs, pid locations).
Since HAWQ-1531 is already implemented, PXF now supports customized for GPDB/HAWQ build.
=> Updated PXF to be built for GPDB.

concourse/pipelines/pipeline.yml
Some of the new features that came with this version of CCP are
- Multiple cluster support
- n-nodes per cluster support where n can be 1, 2, 3...
- SLES 11 Platform support
This commit also contains the pipeline changes needed for breaking changes that CCP 1.0.0
=> Upgrade CCP to 1.0.0

concourse/pipelines/nbu_ddboost_pipeline.yml, concourse/pipelines/pipeline.yml, concourse/scripts/backup_utils.sh, concourse/tasks/run_behave.yml, concourse/tasks/setup_new_gpdb_for_backup_restore.yml, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This modifies the gpdb_master_nbu_ddboost pipeline.
Signed-off-by: Karen Huddleston <khuddleston@pivotal.io>
=> Migrate DDBoost backup/restore tests to terraform

depends/conanfile.txt, gpAux/releng/releng.mk
=> Bump ORCA to 2.46.5

gpAux/extensions/pxf/src/libchurl.c, gpAux/extensions/pxf/src/libchurl.h
=> Change URL to IPAddress:Port to maintain compatibility

src/test/regress/atmsort.pm, src/test/regress/expected/olap_window_seq.out, src/test/regress/expected/olap_window_seq_optimizer.out, src/test/regress/sql/olap_window_seq.sql
Fixes to correctly format the output for explain for few tests. Based on mailing list discussion https://groups.google.com/a/greenplum.org/d/msg/gpdb-dev/iPSs0a8S4X8/vM_tu_5KCAAJ.
=> Couple of fixes to make atmsort.pm happy

src/backend/utils/resgroup/resgroup.c
Previously every resource group has its own slot pool, each with size of 'MaxConnection'.
In order to reduce memory usage, implement a slot pool shared by all resource groups.
In addition, free slots in the slot pool are organized as a free list to optimize alloc/free
operations.
=> Implement slot pool shared by all resource groups.

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/expected/resgroup/resgroup_concurrency.out, src/test/isolation2/expected/resgroup/resgroup_set_memory_spill_ratio.out, src/test/isolation2/sql/resgroup/resgroup_concurrency.sql, src/test/isolation2/sql/resgroup/resgroup_set_memory_spill_ratio.sql
This PR is meant to bypass set/show command for the resource group. To achieve this, I also did some refactoring. Please refer to each commit messages for details.
=> Bypass set command for resource group

gpdb-doc/dita/ref_guide/GPReferenceSQLSummaryLOP.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.xml
see issue https://github.com/greenplum-db/gpdb/issues/3338
@hlinnaka could you review this. 
HTML formatted output
http://docs-gpdb-review-staging.cfapps.io/510/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.html
=> docs: fixes to ALTER EXTERNAL TABLE

concourse/pipelines/pipeline.yml, concourse/scripts/common.bash, concourse/scripts/compile_gpdb_open_source_ubuntu.bash, concourse/scripts/ic_gpdb_ubuntu.bash, concourse/scripts/setup_gpadmin_user.bash, concourse/tasks/ic_gpdb_ubuntu.yml, contrib/pg_upgrade/Makefile, src/test/kerberos/Makefile, src/test/kerberos/installcheck.sh, src/test/regress/input/gpcopy.source, src/test/regress/output/gpcopy.source
Various discoveries and open questions -- going to tag people on individual commits.
Pipeline exposing this change: https://gpdb.ci.pivotalci.info/teams/gpdb/pipelines/dev:gpbosh_ubuntu-icw
=> ICW on Ubuntu

gpdb-doc/dita/admin_guide/wlmgmt.xml, gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
=> doc: Warning about add cgroup kernel issue to resource group docs.

concourse/pipelines/pipeline.yml, concourse/scripts/build_gpdb.py, concourse/scripts/build_orca.py, concourse/scripts/builds/GpBuild.py, concourse/scripts/compile_gpdb_and_orca_with_conan_ubuntu16.bash, concourse/scripts/setup_gpadmin_user.bash, concourse/scripts/test_gpdb.py, concourse/tasks/compile_gpdb_and_orca_with_conan.yml, concourse/tasks/icw_gpdb_with_orca_conan_ubuntu16.yml, concourse/tasks/test_with_orca_conan.yml
- Compile ORCA & GPDB on Ubuntu
- ICW GPDB with ORCA enabled
- Using python scripts to run compilation and ICW
=> Ubuntu enable orca

concourse/pipelines/pr_pipeline.yml
- Adding Ubuntu platform check for PR pipeline
=> PR pipeline: Ubuntu compile and ICW w/ ORCA

concourse/pipelines/pipeline.yml, concourse/scripts/validate_pipeline_release_jobs.py
Add madlib and postgis tests on 5X_STABLE piepline, and also make those jobs as a requirements for release candidates.
=> Merge advanced analytics tests to 5 stable pipeline

gpdb-doc/dita/admin_guide/wlmgmt.xml, gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
This change also destined for 5X_STABLE.
=> adding rhel 6 kernel support

concourse/pipelines/pipeline.yml, concourse/scripts/backup_utils.sh, concourse/tasks/setup_netbackup.yml
Signed-off-by: Chris Hajas <chajas@pivotal.io>
=> Migrate netbackup tests to terraform

concourse/pipelines/nbu_ddboost_pipeline.yml, concourse/scripts/backup_utils.sh, concourse/tasks/setup_netbackup.yml
Updating the separate netbackup and ddboost pipeline now that all jobs are running in ccp.
=> Add ccp netbackup jobs and remove unecessary resources and jobs

src/backend/utils/resgroup/resgroup.c, src/backend/utils/resgroup/resgroup_helper.c, src/include/utils/resgroup.h, src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out, src/test/isolation2/input/resgroup/resgroup_dumpinfo.source, src/test/isolation2/isolation2_resgroup_schedule
Dump runtime info of resgroup to help debug.
=> Dump resgroup runtime info to LOG via UDF.

src/backend/commands/resgroupcmds.c, src/backend/storage/lmgr/proc.c, src/backend/utils/resgroup/resgroup.c, src/include/storage/proc.h, src/include/utils/resgroup.h, src/test/isolation2/expected/resgroup/resgroup_concurrency.out
This was originally tracked in https://github.com/greenplum-db/gpdb/pull/3413, per offline discussion with the original owner, @xiong-gang, I'll take this PR now while he is on vacation this week.
This v2 is based on the original one, but rebased with master. Also I split it into small commits for easy review.
Some further changes will be made according to comments on the original PR.
=> Resgroup refactor slot (v2)

src/backend/cdb/cdbpartition.c, src/backend/commands/tablecmds.c, src/test/regress/input/partindex_test.source, src/test/regress/output/partindex_test.source
Signed-off-by: Xiaoran Wang <xiwang@pivotal.io>
=> Support exchange sub partition with external table

gpMgmt/bin/gppylib/test/unit/test_unit_gprestore_filter.py, gpMgmt/bin/gprestore_filter.py
Will backport to 5X_STABLE.
Signed-off-by: Chris Hajas <chajas@pivotal.io>
=> Properly filter data containing SET search_path statements in gpdbrestore

src/test/regress/expected/gp_recursive_cte.out, src/test/regress/sql/gp_recursive_cte.sql
- Non-recursive CTE nested in non-recursive CTE
- Non-recursive CTE nested in recursive CTE
- Recursive CTE nested in non-recursive CTE
- Recursive CTE nested in recursive CTE
=> Add nested CTE tests

gpdb-doc/dita/best_practices/sysconfig.xml
=> docs - remove gp_ from gp_statement_mem references

gpdb-doc/dita/best_practices/sysconfig.xml
=> docs - remove gp_ from gp_statement_mem references (5x branch)

gpdb-doc/dita/admin_guide/wlmgmt.xml, gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
small change to add RESET command to resource group limit bypass
=> docs - add RESET cmd to resgroup limit bypass

src/backend/utils/adt/gp_dump_oids.c, src/test/regress/expected/gp_dump_query_oids.out, src/test/regress/sql/gp_dump_query_oids.sql
This follow up work for PR#2072, all previous discussion please see below
https://github.com/greenplum-db/gpdb/pull/2072
=> minirepro: dump all the children relid of partition table

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out, src/test/isolation2/input/resgroup/resgroup_dumpinfo.source
* Add some fields in ResGroupControl.
* Add key validation in tests.
* Improve code style.
=> Add more dumps for resgroup.

src/backend/cdb/dispatcher/cdbdisp.c, src/backend/cdb/dispatcher/cdbdisp_async.c, src/backend/cdb/dispatcher/cdbdisp_thread.c, src/backend/cdb/motion/ic_udpifc.c, src/include/cdb/cdbdisp.h
See commit messages. I'm hoping that this will speed up the regression tests a little bit.
=> Wake up faster if a segment reports an error

gpAux/gpperfmon/src/gpmon/gpsmon.c
Before this commit, gpmmon expected to see QLOG packets before QUERYSEG packets. Out of order packets were quietly dropped. This behavior was causing intermittent test failure with the message: No segments for CPU skew calculation.
This commit change the order of packet sends on gpsmon to fix these failures. Fixes #3585.
=> Change the order in which gpsmon sends packets to gpmmon

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
see "Other Memory Considerations" subsection:  http://docs-gpdb-review-staging.cfapps.io/510/admin_guide/workload_mgmt_resgroups.html
=> docs - resgroup - add palloc/malloc discussion

src/backend/access/appendonly/appendonly_compaction.c, src/backend/access/appendonly/appendonlyam.c, src/backend/access/external/fileam.c, src/backend/commands/copy.c, src/backend/commands/tablecmds.c, src/backend/executor/execMain.c, src/backend/executor/execTuples.c, src/include/cdb/cdbappendonlyam.h, src/include/executor/tuptable.h, src/test/regress/expected/bfv_dml.out, src/test/regress/expected/bfv_dml_optimizer.out, src/test/regress/expected/qp_dml_oids.out, src/test/regress/expected/qp_dml_oids_optimizer.out, src/test/regress/greenplum_schedule, src/test/regress/input/trigger_sets_oid.source, src/test/regress/output/trigger_sets_oid.source, src/test/regress/regress_gp.c, src/test/regress/sql/bfv_dml.sql, src/test/regress/sql/qp_dml_oids.sql
=> ExecInsert changes

config/programs.m4, configure, src/bin/pg_dump/cdb/cdb_ddboost_util.c, src/bin/pg_dump/pg_backup_files.c, src/bin/pg_dump/pg_backup_tar.c, src/interfaces/libpq/fe-auth.c, src/interfaces/libpq/fe-connect.c, src/interfaces/libpq/fe-exec.c, src/interfaces/libpq/fe-protocol2.c, src/interfaces/libpq/fe-protocol3.c, src/interfaces/libpq/fe-secure.c, src/interfaces/libpq/pqexpbuffer.c
=> Fix a bunch of compiling warnings

gpMgmt/test/behave/mgmt_utils/gpperfmon.feature
The gpperfmon test is enhanced to include rows_out metric from the
queries_history table.
Signed-off-by: Marbin Tan <mtan@pivotal.io>
Edit:
This will be back-ported to 5X_STABLE
=> Enhance gppperfmon test to include row metrics.

concourse/scripts/ic_gpdb_resgroup.bash
Passing complex commands via bash here documents instead of ssh string
arguments to simplify the handing of quotes and multiple lines.
=> resgroup: concourse: use here doc instead of ssh args.

concourse/scripts/test_gpdb.py
Signed-off-by: Xiaoran Wang <xiwang@pivotal.io>
=> Output regression.diffs in icw_gporca_conan_ubuntu16 task

contrib/Makefile, contrib/README, contrib/passwordcheck/Makefile, contrib/passwordcheck/expected/passwordcheck.out, contrib/passwordcheck/passwordcheck.c, contrib/passwordcheck/sql/passwordcheck.sql, src/backend/commands/user.c, src/include/commands/user.h
* merge passwordcheck plugin from pg(c742b795ddce852975c513a04c29966420937553)
```
original commit message :
Add a hook to CREATE/ALTER ROLE to allow an external module to check the
strength of database passwords, and create a sample implementation of
such a hook as a new contrib module "passwordcheck".
Laurenz Albe, reviewed by Takahiro Itagaki
```
* merge reason: some customer waiting
=> merge passwordcheck plugin from pg (#3689)

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
now easier to access subtopics on that page
=> docs - add quick links to using resource groups subtopics

concourse/README.md
Currently, we do not tell the user how to get fly.
=> Adds step on how to install fly

gpdb-doc/markdown/pxf/troubleshooting_pxf.html.md.erb
add a section to pxf troubleshooting document discussing how to address memory issues with PXF.
doc review site link:
-http://docs-gpdb-review-staging.cfapps.io/510/pxf/troubleshooting_pxf.html#pxf-memcfg
=> docs - add PXF memory and thread config content

gpdb-doc/dita/admin_guide/managing/monitor.xml, gpdb-doc/dita/admin_guide/perf_troubleshoot.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-database.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-dynamic-memory-info.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-memory-info.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-queries.xml, gpdb-doc/dita/ref_guide/gpperfmon/db-segment.xml, gpdb-doc/dita/ref_guide/gpperfmon/dbref.xml
qualify gpperfmon and related content
=> docs - RG/RQ-qualify gpperfmon, other content where appropriate

gpdb-doc/dita/admin_guide/roles_privs.xml, gpdb-doc/dita/best_practices/encryption.xml, gpdb-doc/dita/security-guide/topics/Encryption.xml
=> docs - pgcrypto installed with greenplum

gpMgmt/bin/gpcheckcat, src/backend/commands/dbcommands.c, src/test/regress/input/dispatch.source, src/test/regress/output/dispatch.source
=> Fix quoting issues in dispatching ALTER and DROP DATABASE.

gpdb-doc/book/master_middleman/source/subnavs/pxf-subnav.erb, gpdb-doc/dita/admin_guide/external/g-pxf-protocol.xml, gpdb-doc/dita/admin_guide/external/pxf-overview.xml, gpdb-doc/markdown/pxf/hbase_pxf.html.md.erb, gpdb-doc/markdown/pxf/overview_pxf.html.md.erb
wrapping up a few loose ends from the pxf PRs.
=> docs - minor pxf content edits

gpdb-doc/dita/ref_guide/extensions/pl_container.xml
@dyozie @wuj21 
Added compatibility information.
=> docs: pl/container - add compatible w/ 5.2, not tested w 5.1, 5.0

gpdb-doc/dita/admin_guide/external/g-s3-protocol.xml
=> docs: S3 gpcheckcloud - add config parameter gpcheckcloud_newline

concourse/scripts/build_orca.py, concourse/tasks/build_orca_using_conan.yml, depends/conanfile_orca.txt, gpAux/releng/releng.mk
Update orca scripts to use conan as per the changes done previously via commit #264ade0
=> Update orca scripts to use conan

gpdb-doc/dita/ref_guide/extensions/pl_container.xml
and some minor edits.
Information is in the Note section
@wuj21 Please review.
=> docs: pl/container - add note about docker hang.

gpdb-doc/dita/admin_guide/query/query.ditamap, gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-enable.xml, gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-root-partition.xml
This PR consolidates the GPORCA ANALYZE ROOTPARTITION info into a dedicated topic, and adds more best practices info.  
An HTML version of this PR is available at http://docs-gpdb-review-staging.cfapps.io/510/admin_guide/query/topics/query-piv-opt-root-partition.html
(commits destined for master & 5X_STABLE)
=> Docs: ANALYZE ROOTPARTITION best practices

src/backend/commands/explain.c
Compared to upstream, there was a bunch of changes to the error handling
in EXPLAIN, to try to catch errors and produce EXPLAIN output even when an
error happens. I don't understand how it was supposed to work, but I don't
remember it ever doing anything too useful. And it has the strange effect
that if an ERROR happens during EXPLAIN ANALYZE, it is reported to the
client as merely a NOTICE. So, revert this to the way it is in the
upstream.
Also reorder the end-of-EXPLAIN steps so that the "Total runtime" is
printed at the very end, like in the upstream. I don't see any reason to
differ from upstream on that, and this makes the "Total runtime" numbers
more comparable with PostgreSQL's, for what it's worth.
I dug up the commit that made these changes in the old git repository, from
before …
=> Remove attempt to make EXPLAIN print something even on error.

src/backend/fts/fts.c, src/backend/fts/ftsfilerep.c, src/backend/fts/ftsprobefilerep.c, src/backend/fts/test/Makefile, src/backend/fts/test/fts_test.c, src/include/postmaster/fts.h
Testing probeWalRepPublishUpdate from fts.c
=> Unit test probeWalRepPublishUpdate

gpMgmt/.gitignore
Signed-off-by: C.J. Jameson <cjameson@pivotal.io>
=> behave: gitignore artifacts from analyzedb and gpcheckcat tests

gpdb-doc/dita/admin_guide/external/pxf-overview.xml
=> docs - note that pxf does not yet support filter pushdown

concourse/scripts/test_gpdb.py
- Handle missing case for codegen mode
=> Refactor test_gpdb.py for different modes

doc/src/sgml/ref/alter_resource_group.sgml, doc/src/sgml/ref/alter_role.sgml, doc/src/sgml/ref/create_resource_group.sgml, doc/src/sgml/ref/create_role.sgml, doc/src/sgml/ref/drop_resource_group.sgml
port to 5x.
built 5X_STABLE with these updates and tried it out.  all worked.
=> resgroup - add sgml docs - 5X_STABLE

gpAux/gpdemo/gpsegwalrep.py
It also output the segment configuration at the end.
Author: Xin Zhang <xzhang@pivotal.io>
Author: Ashwin Agrawal <aagrawal@pivotal.io>
=> Verify correct mode for segwalrep script.

src/test/regress/atmsort.pm
This silences false regression failures caused by row order differences in
some queries that use those constructs. While we don't have such false
failures in the regression suite right now, the upcoming rewrite of the
window functions implementation will change the plans for some queries, and
would cause some.
=> Make atmsort recognize an ORDER BY in an OVER or WITHIN GROUP construct.

concourse/README.md, concourse/scripts/build_gpdb.py
report failure from any conditional branch
-- reformat whitespace using IDE
=> fix status reporting on build tool

src/backend/tcop/postgres.c
A mismerge. Surprisingly it worked despite the duplication. Although I
think there may have been a memory leak, because of the duplicated
MemoryContextSwitchTo call.
=> Remove duplicated code.

src/backend/utils/adt/ruleutils.c
We have lately seen a lot of failures in test cases related to
partitioning, with errors like this:
select tablename, partitionlevel, partitiontablename, partitionname, partitionrank, partitionboundary from pg_partitions where tablename = 'mpp3079a';
ERROR:  cache lookup failed for relation 148532 (ruleutils.c:7172)
The culprit is that that the view passes a relation OID to the
pg_get_partition_rule_def() function, and the function tries to perform a
syscache lookup on the relation (in flatten_reloptions()), but the lookup
fails because the relation was dropped concurrently by another transaction.
This race is possible, because the query runs with an MVCC snapshot, but
the syscache lookups use SnapshotNow.
This commit doesn't eliminate the race completely, but at least it makes it …
=> Narrow race condition between pg_partitions view and altering partitions.

src/bin/pg_dump/cdb/cdb_dump_agent.c
The window functions rewrite made some changes to pg_dump, to cope with the
catalog changes. cdb_dump_agent is a heavily-modified copy of pg_dump, so
it needs to be changed accordingly.
=> Port recent pg_dump changes to cdb_dump_agent.

src/backend/access/appendonly/README.md
Signed-off-by: Xin Zhang <xzhang@pivotal.io>
@asimrp @ashwinstar Please let us know whether this is a good move to introduce MD to README. There is no content change yet, but just to set the format. Thanks.
=> Change Appendonly README to README.md

src/bin/pg_dump/pg_dumpall.c
A bad 8.4 merge resolution on my part. We may not support older server_versions in GPDB's pg_dump, but that doesn't mean we should use uninitialized memory if we come across one.
Found as part of #3871.
=> pg_dumpall: fix uninitialized variable warning

configure, configure.in
- Append "-oss" to greenplum as default extra-version
- Remove appending version to Postgres Version String
=> Append extra version to Greenplum

depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
=> Bump Orca Version

src/test/regress/expected/gporca.out
This was missed in commit 407b2880fe293380ee8698a635d11335b6e289db
=> Update Planner answer file for gpora

gpdb-doc/dita/ref_guide/extensions/postGIS.xml
How to enable GDAL raster drivers for postGIS
HTML - on GPDB doc review site
http://docs-gpdb-review-staging.cfapps.io/530/ref_guide/extensions/postGIS.html#topic_ydr_q5l_ybb
=> docs: postGIS - add GDAL raster driver information

gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
All changes will also go into master branch.
HTML pages for these changes are available at:
http://docs-gpdb-review-staging.cfapps.io/530/admin_guide/managing/backup-gpbackup.html
http://docs-gpdb-review-staging.cfapps.io/530/utility_guide/admin_utilities/gpbackup.html
http://docs-gpdb-review-staging.cfapps.io/530/utility_guide/admin_utilities/gprestore.html
=> New gpbackup options

src/test/tinc/tincrepo/mpp/gpdb/tests/utilities/gpexpand/scenarios/run_gpexpand.py
We only need check for parallelism until the number of tables redistributed
reached the specified number of tables to be redistributed simultaneously.
Author: Marbin Tan <mtan@pivotal.io>
Author: Shoaib Lari <slari@pivotal.io>
=> gpexpand: Simplify test for parallelism.

gpAux/gpdemo/gpsegwalrep.py, src/backend/access/transam/xlog.c, src/backend/catalog/system_views.sql, src/backend/replication/Makefile, src/backend/replication/gp_replication.c, src/backend/replication/walreceiver.c, src/backend/replication/walsender.c, src/include/catalog/pg_proc_gp.h, src/include/replication/gp_replication.h, src/include/replication/walsender_private.h, src/test/isolation2/sql_isolation_testcase.py, src/test/walrep/Makefile, src/test/walrep/expected/missing_xlog.out, src/test/walrep/sql/missing_xlog.sql
- It can perform incremental recovery
- It can report failed segments if the incremental recovery failed
- `gp_stat_replication` view is extended to display the reason of sync_error
Also some minor refactoring of 'fsync=off` by default etc.
=> Add `recover` operation to `gpsegwalrep.py`

src/backend/access/bitmap/bitmap.c, src/backend/executor/nodeBitmapAnd.c, src/backend/executor/nodeBitmapAppendOnlyscan.c, src/backend/executor/nodeBitmapHeapscan.c, src/backend/nodes/tidbitmap.c
I extracted these from PR #4081, these seem independent and sensible changes on their own.
=> Two little cleanups to tidbitmap stuff

gpdb-doc/dita/utility_guide/citext.xml
This changes allows the citext example in the doc to run.
=> Fix citext example

src/backend/catalog/storage.c
Greenplum uses three-pass crash recovery guided by persistent tables to
determine whether a relfile needs to be created during crash recovery.  This
happens on master and primary segments, and in case of filerep, also on mirror
segments.  In case of WALrep, the standby master and mirrors replay MMXLOG
records to create relfiles.
Replay of SMGR create records is already disabled by
08f4e145c6351d17e395d1827a0ef07796ddc7ac.  Thanks to Ashwin (@ashwinstar) for
pointing out that emitting of SMGR create needs to be disabled too.
In future, persistent tables as well as MMXLOG records for relfiles are slated
to be removed from Greenplum, allowing SMGR xlog records to be used, like
upstream.
Author: Jimmy Yih <jyih@pivotal.io>
Author: Asim R P <apraveen@pivotal.io>
=> SMGR create XLOG records are not used in Greenplum, disable them.

src/backend/commands/copy.c
commit:
commit 95c238d941216feca4116359f2b4632fb9a9081d
Author: Andrew Dunstan <andrew@dunslane.net>
Date:   Sat Mar 8 01:16:26 2008 +0000
Improve efficiency of attribute scanning in CopyReadAttributesCSV.
The loop is split into two parts, inside quotes, and outside quotes, saving some instructions in both parts.
Author: Max Yang <myang@pivotal.io>
=> Refactor the CopyReadAttributeCsv code to follow upstream according

src/bin/gpfdist/regress/input/custom_format.source, src/bin/gpfdist/regress/input/exttab1.source, src/bin/gpfdist/regress/input/gpfdist2.source, src/bin/gpfdist/regress/input/gpfdist_ssl.source, src/bin/gpfdist/regress/output/custom_format.source, src/bin/gpfdist/regress/output/exttab1.source, src/bin/gpfdist/regress/output/gpfdist2.source, src/bin/gpfdist/regress/output/gpfdist_ssl.source
Update grep keywords to filter the unrelated programs in different platforms.
=> Fix issue 4071

src/backend/executor/nodeHash.c
This was left out during the merge, because when we started merging this,
we used to track the amount of memory used by the hash table differently.
It was changed back the way it is in the upstream in commit f4d6067355,
before this code was merged in, but I forgot to restore these calls.
Also re-enable increasing # of batches in hash join, when adding to skew
bucket.
=> Fix accounting for memory usage of the new skew bucket in hash join.

depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/backend/utils/misc/guc_gp.c
Signed-off-by: Haisheng Yuan <hyuan@pivotal.io>
=> Set the max size of exhaustive search join order threshold to 12

src/backend/access/bitmap/bitmap.c
Author: Xiaoran Wang <xiwang@pivotal.io>
=> Resolve some GPDB_84_MERGE_FIXMEs in bitmap as well as a minor possible memory leak

concourse/pipelines/pipeline.yml
This will protect against regression in segwalrep due to changes on the master branch.
=> Add segwalrep jobs to master pipeline

src/backend/access/transam/xact.c
Resolving the GPDB_84_MERGE_FIXME now, that we match close to upstream. Without
thsi fix the relation files were not dropped during recovery or replay on
mirrors.
=> Properly delete relation files on commit record replay.

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
changed max value to 12
see PR https://github.com/greenplum-db/gpdb/pull/4046
=> docs: optimizer_join_order_threshold GUC update max value

gpdb-doc/dita/utility_guide/admin_utilities/gpaddmirrors.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpexpand.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpinitsystem.xml
add note the increasing MaxStartups may be necessary to gpexpand, gpinitsystem, and gpaddmirrors.
=> docs - add note about MaxStartups to relevant utility cmds

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/backend/gpopt/utils/COptTasks.cpp
Corresponding to PR https://github.com/greenplum-db/gporca/pull/263
Have a similar change but with different OIDs for GPDB4 and GPDB5 (7000 and 7001 instead of 3100 and 3101)
=> Pass Row Number & Rank Oid to Optimizer Config

gpdb-doc/dita/admin_guide/ddl/ddl-storage.xml, gpdb-doc/dita/best_practices/schema.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE_AS.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_appendonly.xml
reviewed the recent doc additions to support zstandard compression algorithm.  this PR includes a few miscellaneous edits, some formatting updates, and added some what i think was missing info.
=> docs - review zstd doc additions, misc related edits

gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gppylib/db/catalog.py, gpMgmt/bin/gppylib/operations/buildMirrorSegments.py, gpMgmt/bin/gppylib/operations/startSegments.py, gpMgmt/bin/gppylib/system/environment.py, gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py, gpMgmt/bin/gpstart, gpMgmt/sbin/gpsegstart.py, gpMgmt/sbin/gpsegtoprimaryormirror.py
The locale information is not used for anything, so no need to collect and
pass it around.
=> Remove code to pass locale data to gpsegstart.py.

gpAux/gpdemo/gpsegwalrep.py
Mostly re-used init-mirrors for this functionality.
Author: Ashwin Agrawal <aagrawal@pivotal.io>
Author: Taylor Vesely <tvesely@pivotal.io>
=> Enhance gpsegwalrep.py to support full recovery.

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query24.ans, gpMgmt/bin/gpload_test/gpload2/setup.ans, gpMgmt/bin/gpload_test/gpload2/setup.sql
- Fix gpload.py, add schema prefix to every external table name when EXTERNAL.SCHEMA is set
- Add new test cases
=> Fix gpload count error bug with EXTERNAL.SCHEMA

concourse/scripts/compile_gpdb.bash, concourse/scripts/compile_gpdb_open_source_centos.bash, concourse/scripts/compile_gpdb_open_source_ubuntu.bash, concourse/scripts/compile_gpdb_remote.bash, concourse/scripts/deb_create_package.bash, gpAux/Makefile, gpAux/extensions/gphdfs/build.xml, gpAux/releng/make/dependencies/build.xml, gpAux/releng/make/dependencies/ivy_util.sh, gpAux/releng/releng.mk, src/test/unit/cmockery/cmockery.c
This PR turns down the volume of build output across multiple compilation jobs to help relieve the weight on the Concourse UI. There is no functional difference in the build process.
=> Build output trimming.

depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/test/regress/expected/co_nestloop_idxscan_optimizer.out
=> Bump Orca version to 2.53.4

gpdb-doc/dita/utility_guide/admin_utilities/gpstop.xml
See related PR https://github.com/greenplum-db/gpdb/pull/3910
=> docs: gpstop new option --host

src/backend/postmaster/backoff.c
There is a long-standing race condition in BackoffSweeper() which
triggers an error and then triggers another assertion failure for
not reset sweeperInProgress to false.
This commit doesn't resolve the race condition fundamentally with
lock or other implementation, because the whole backoff mechanism
did not ask for accurate control, so skipping some sweeps should
be fine so far. We also downgrade the log level to DEBUG because
a restart of sweeper backend is unnecessary.
this PR can resolve the intermittent failure in pipeline job icw_planner_sles12.
=> Minimize the race condition in BackoffSweeper()

gpdb-doc/dita/admin_guide/external/g-one-time-hdfs-protocol-installation.xml, gpdb-doc/dita/admin_guide/external/g-reading-and-writing-custom-formatted-hdfs-data.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml
doc updates for developer PR https://github.com/greenplum-db/gpdb/pull/4068
- gp_hadoop_target_version values changed, as did the default
- gnet jar file name changes
=> docs - gphdfs file name and gp_hadoop_target_version updates

src/test/isolation2/sql_isolation_testcase.py
The temporary file hack to deal with pygresql output oddities didn't ensure that those files were always removed. Instead of a named file we don't need, just use a `TemporaryFile` that will go away as soon as we release it.
Added a `FIXME` to revisit this once we upgrade pygresql.
=> isolation2: stop littering <stdout>.pid files on failure

gpdb-doc/dita/ref_guide/config_params/guc_config.xml
add GUC parameter type enum to supported types, and add description text.
doc review site link:
- http://docs-gpdb-review-staging.cfapps.io/540/ref_guide/config_params/guc_config.html#topic_vsn_22l_z4
=> docs - identify enum type support for GUCs

gpdb-doc/dita/admin_guide/external/g-hdfs-parquet-format.xml
fix incorrect parquet data type
=> docs - correct the reference to parquet data type fixed_len_byte_array

src/tools/pgindent/typedefs.list
Author: C.J. Jameson <cjameson@pivotal.io>
=> Stop pgindenting pg_filespace Form and FormData

src/backend/port/sysv_sema.c, src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h
One was completely unused, and the other one seemed useless.
=> Remove two debugging gucs

src/backend/utils/sort/tuplesort_mk.c
tuple store which just advances current position by N instead of getting
tuple N times.
Author: Max Yang <myang@pivotal.io>
=> Minor optimization in tuplesort_skiptuples_mk for in memory non unique

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/extensions/pl_container.xml
updates
-attribute names have changed for logging, and network
-the GUC log_min_messages controls the log level
-add note information about controlling container lifetime
-add information in log_min_messages definition.
HTML of updated pl/container doc on doc review site.
http://docs-gpdb-review-staging.cfapps.io/540/ref_guide/extensions/pl_container.html
=> docs: plcontainer logging and attribute updates.

gpdb-doc/dita/ref_guide/extensions/madlib.xml
=> doc: MADlib fix when upgrading to 1.13

src/backend/access/aocs/aocs_compaction.c, src/backend/access/appendonly/appendonly_compaction.c
In the first cut of the walreplication work, I left out the part that
drops a segfile during AO compaction, because there was no
straightforward native PostgreSQL function to drop just a single segfile.
However, that leads to a massive disk space leak, as the space freed by
VACUUM on an AO table is not reclaimed, until the same segment number is
used again for further insertions, so we clearly must do something about
that.
Instead of dropping the segfile altogether, like we used to, truncate the
file to 0 bytes. Mostly because that's more expedient to do, as we have
the functions to do that and to WAL-log that, whereas code to fully remove
just a single segfile doesn't exist. But if you squint a bit, you could
even call that an optimization: it saves the overhead of recreating the
file …
=> Reclaim space when an AO segment is dropped at AO compaction.

gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml
-Add new options
-Update AdminGuide
Link to HTML docs on GPDB Review site.
http://docs-gpdb-review-staging.cfapps.io/540/utility_guide/admin_utilities/gpbackup.html
http://docs-gpdb-review-staging.cfapps.io/540/admin_guide/managing/backup-gpbackup.html#topic_et4_b5d_tbb
=> docs: gpbackup new options -include-table -exclude-table

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpexpand.xml
-gpexpand - Add link to AdminGuide, Expanding a Greenplum System
-pljava_vmoptions - change set classification to reload from restart
=> docs: minor updates.

gpdb-doc/dita/best_practices/sysconfig.xml
-updated XFS mount options
-updated GPDB/ipv4_local_port_range information
-added example for setting blockdev.
=> docs: best practices - update some system config information.

src/backend/cdb/cdbvars.c, src/backend/executor/execHHashagg.c, src/backend/executor/nodeHash.c, src/backend/executor/nodeHashjoin.c, src/backend/storage/file/bfz.c, src/backend/utils/misc/guc_gp.c, src/backend/utils/workfile_manager/workfile_mgr.c, src/include/cdb/cdbvars.h, src/include/executor/execHHashagg.h, src/include/utils/workfile_mgr.h
see individual commit messages.
=> Little cleanups to "workfile" code. 

src/bin/pg_dump/pg_dump.c
* Don't query for external partitions in non-partitioned tables. The
query for possible external partitions is fairly expensive, and it's
pointless if the table is not partitioned at all.
* Cache the results of server version checks.
With these improvements, dumping the regression database takes about 25
seconds on my laptop, vs. 70 seconds before.
=> Speed improvements to pg_dump.

doc/src/sgml/ref/comment.sgml, src/bin/psql/tab-complete.c
Now that filespaces are gone..
=> Fix tab-completion CREATE TABLESPACE, and remove \h for COMMENT ON FILESPACE.

configure, src/include/pg_config.h.in
Follow-up to commit 8922315e; remove stale code in the generated files.
=> configure: run autoreconf to pull in recent changes

src/bin/pg_dump/cdb/cdb_dump_agent.c
Previously, we would include the DEFAULT argument modifier when
performing the ACL dump, which caused an error during restore. This is
dumping correctly in pg_dump, so we now use the same logic in gpcrondump.
Author: Chris Hajas <chajas@pivotal.io>
=> Fix invalid ALTER FUNCTION syntax in gpcrondump (GPDB5)

src/test/tinc/Makefile
Author: Xin Zhang <xzhang@pivotal.io>
Author: Asim R P <apraveen@pivotal.io>
=> Fix TESTER env variables

concourse/pipelines/gen_pipeline.py, concourse/pipelines/gpdb_master-generated.yml, concourse/pipelines/templates/gpdb-tpl.yml
- Also suggest dev pipeline command has a git-branch
Author: Jim Doty <jdoty@pivotal.io>
Author: C.J. Jameson <cjameson@pivotal.io>
=> concourse: remove stagger-start from generated dev pipelines

src/backend/access/appendonly/appendonly_visimap.c, src/backend/executor/execWorkfile.c, src/backend/executor/nodeShareInputScan.c, src/backend/storage/file/bfz.c, src/backend/storage/file/buffile.c, src/backend/storage/file/fd.c, src/backend/utils/sort/logtape.c, src/backend/utils/sort/tuplesort.c, src/backend/utils/sort/tuplesort_mk.c, src/backend/utils/sort/tuplestorenew.c, src/backend/utils/time/combocid.c, src/backend/utils/time/sharedsnapshot.c, src/backend/utils/workfile_manager/workfile_mgr.c, src/include/storage/buffile.h, src/include/storage/fd.h, src/test/regress/workfile_mgr_test.c
see individual commit messages.
=> Cleanup temp files stuff

src/backend/utils/adt/selfuncs.c
The test forcibly modifies pg_statistics.stavalues, with a array that
doesn't match the column's datatype. In general, if you muck around the
catalogs like that, all bets are off, but since we have a test like that
in the test suite, let's at least make it work.
The problem only arises with enable_mergejoin=on, because apparently the
cost estimation of other join types follow a different codepath that
happens to work.
=> Fix crash in 'bfv_statistics' test with enable_mergejoin=on.

gpdb-doc/dita/utility_guide/admin_utilities/gpload.xml
Ported from 4.3.x documentation.
see PR https://github.com/greenplum-db/gpdb/pull/4356
=> docs: gpload - new yaml file parameter STAGING_TABLE

contrib/gp_replica_check/gp_replica_check.c
This makes it a lot easier to diagnose problems after a failure.
=> Print table name, if gp_replica_check fails.

gpMgmt/bin/gpcheckperf, gpMgmt/bin/lib/multidd
- Also whitespace formatting in gpcheckperf
=> Print Stderr to STDOUT in gpcheckperf

hooks/pre-push
Author: C.J. Jameson <cjameson@pivotal.io>
=> concourse git-hook: check for pipeline generation

gpdb-doc/markdown/pxf/hdfs_read_pxf.html.md.erb, gpdb-doc/markdown/pxf/using_pxf.html.md.erb
There's also an HTML review for this available at http://docs-gpdb-review-staging.cfapps.io/550/pxf/hdfs_read_pxf.html
=> Docs - adding info, example for pxf parquet profile

gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml, gpdb-doc/dita/admin_guide/managing/backup.ditamap, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
Summary of updates for GA.
-Remove experimental notes (GA release)
-Update email configuration information
-Add return code information
-Fix syntax error in gpbackup
Link to HTML in GPDB Review doc site.
Admin. Guide
https://docs-gpdb-review-staging.cfapps.io/550/admin_guide/managing/backup-gpbackup.html
Utility Guide
http://docs-gpdb-review-staging.cfapps.io/550/utility_guide/admin_utilities/gpbackup.html
http://docs-gpdb-review-staging.cfapps.io/550/utility_guide/admin_utilities/gprestore.html
PR for 5X_STABLE 
=> docs: gpbackup/gprestore updates

src/backend/optimizer/path/allpaths.c
=> Remove 8.4 merge fixme in allpaths.c

src/backend/nodes/nodeFuncs.c, src/test/regress/expected/portals.out, src/test/regress/sql/portals.sql
Did a quick sanity check. Looks alright.
=> Remove residual FIXMEs

src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp, src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
These underlying issues were resolved in the following PRs that were
merged. The fixmes where not removed.
https://github.com/greenplum-db/gpdb/pull/4174
https://github.com/greenplum-db/gporca/pull/263
=> Clean up FIXME added after WINDOW merge

gpdb-doc/book/master_middleman/source/subnavs/gpdb-landing-subnav.erb, gpdb-doc/dita/admin_guide/external/pxf-overview.xml, gpdb-doc/markdown/pxf/overview_pxf.html.md.erb
these changes made it to master, didn't make it to 5X stable branch...
=> docs - pxf to main subnav, use consistent titles (5X_STABLE)

depends/conanfile_orca.txt, gpAux/releng/releng.mk
This PR is just to trigger the PR pipeline. No review needed.
=> Bump ORCA version to 2.55.3

depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/sql/bfv_aggregate.sql
Corresponding to ORCA PR: https://github.com/greenplum-db/gporca/pull/335
=> Adding negative test for aggregate on set returning function

src/backend/cdb/cdboidsync.c
Add more checks to make sure it returns a valid OID. Turn an assertion
into an elog(), so that you get a graceful error rather than crash if
assertions are not enabled. Schema-qualify the call, so that we don't
get fooled by a UDF called pg_highest_oid().
These errors are "can't happen" scenarios, but we've nevertheless seen the
assertion fail occasionally in the pipeline. I believe the failure has been
caused by bugs elsewhere, and these changes won't fix it, but it doesn't
hurt to check for errors more thoroughly here.
=> Make dispatching of pg_highest_oid() more robust.

gpdb-doc/dita/admin_guide/topics/g-past-postgresql-version-compatibility-parameters.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
see PR https://github.com/greenplum-db/gpdb/pull/4605
=> docs: add GUC gp_ignore_error_table

src/backend/utils/misc/faultinjector.c
Infinite waiting may not be good idea and hence adding to ERROR out
after 10 mins if fault doesn't get trigered. So, tests using such
fault type doesn't hang CI if for some reason the fault doesn't
hit. Would atleast fail that test and move forward to run other tests.
=> Add timeout for wait_until_triggered fault.

gpdb-doc/dita/admin_guide/managing/backup-boostfs.xml, gpdb-doc/dita/admin_guide/managing/backup.ditamap
Link to HTML output on GPDB Review site.
http://docs-gpdb-review-staging.cfapps.io/550/admin_guide/managing/backup-boostfs.html
=> docs: gpbackup/gprestore support for BoostFS

gpdb-doc/dita/ref_guide/extensions/pl_python.xml, gpdb-doc/dita/ref_guide/extensions/pl_r.xml
-remove compiling Python numpy package, add using pip to install numpy.
-mention gpssh -s option to source greenplum_path.sh
Link to HTML output on GPDB 
http://docs-gpdb-review-staging.cfapps.io/550/ref_guide/extensions/pl_python.html
http://docs-gpdb-review-staging.cfapps.io/550/ref_guide/extensions/pl_r.html
=> docs: PL/Python, PL/R updates for installing modules and using gpssh.

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
update set classification for writable_external_table_bufsize server configuration parameter.
=> docs - can set writable_external_table_bufize at session level

src/backend/access/transam/test/Makefile, src/backend/access/transam/test/varsup_test.c
Co-authored-by: Ashwin Agrawal <aagrawal@pivotal.io>
Co-authored-by: Xin Zhang <xzhang@pivotal.io>
=> Adding unit test to verify the xid_stop_limit and xid_warn_limit

gpAux/gpdemo/Makefile, gpAux/gpdemo/demo_cluster.sh, gpMgmt/bin/gppylib/gparray.py, src/test/fsync/expected/bgwriter_checkpoint.out, src/test/walrep/Makefile
Author: Max Yang <myang@pivotal.io>
Author: Xiaoran Wang <xiwang@pivotal.io>
(cherry picked from commit 0c7f12814bbff95885c7c5b2c93621138c35bafc)
Excluded changes to gpsegwalrep.py since they don't apply.
=> Start standby master in create-demo-cluster when WITH_MIRRORS = true.

src/include/catalog/pg_am.h, src/test/regress/expected/information_schema.out, src/test/regress/expected/information_schema_optimizer.out
It's been unused for as long as I can see.
=> Remove unused pg_am.amcanshrink column.

gpMgmt/bin/gpinitsystem, gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/lib/gpcreateseg.sh, gpMgmt/sbin/gpgetstatususingtransition.py, gpMgmt/sbin/gpsegstart.py, gpMgmt/sbin/gpsegtoprimaryormirror.py, src/backend/postmaster/postmaster.c, src/backend/utils/misc/guc.c
Revert commit 6d2a1f6, that commit doesn't work if 'listen_address'
is commented out in postgresql.conf
=> Fix gp_primarymirror default hostname

gpMgmt/bin/gpinitsystem, gpMgmt/bin/gppylib/commands/gp.py, src/backend/cdb/motion/ic_udpifc.c, src/backend/postmaster/postmaster.c, src/include/postmaster/postmaster.h
This reverts commit c1e148a489f16846798533744b3b34405a9d9c2d.
=> Revert "Enable listen_addresses"

README.macOS.md
Update README based on feedback from a new developer to the GPDB codebase
Co-authored-by: Jim Doty <jdoty@pivotal.io>
Co-authored-by: Kevin Yeap <kyeap@pivotal.io>
=> Update macOS README

src/backend/access/transam/distributedlog.c
To help debug the issue, PANIC incase encounter this shouldn't happen case. The issue was seen in CI few times now.
=> PANIC in debug for "local snapshot's xmin is older".

gpdb-doc/dita/ref_guide/extensions/pl_r.xml
=> docs - fix incorrect R version reference

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
add memory control group to gpdb.conf cgroups configuration file.
=> docs - add memory control group to resgroup cgroup config

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/test/regress/expected/qp_orca_fallback.out, src/test/regress/expected/qp_orca_fallback_optimizer.out, src/test/regress/sql/qp_orca_fallback.sql
Signed-off-by: Sambitesh Dash <sdash@pivotal.io>
=> ORCA falls back on ONLY keyword in FROM clause

src/backend/gpopt/config/CConfigParamMapping.cpp, src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h, src/test/regress/expected/qp_correlated_query_optimizer.out, src/test/regress/expected/update_gp_optimizer.out
Introduce a GUC to enable / disable associativity in ORCA. Currently, its controlled by a xform, which is not a user friendly way.
Also, set the value of the GUC to disable associativity by default.
=> Introducing Associativity GUC

src/backend/parser/parse_relation.c
This seems like a more clear and robust way to do this, and matches the
upstream code more closely, too.
=> Refactor parserOpenTable, to match upstream better.

gpdb-doc/dita/ref_guide/extensions/pl_container.xml
plcontainer command to display images is image-list, not image-show.
=> docs - use plcontainer image-list to display images

src/backend/utils/misc/faultinjector.c
Currently, in CI autovacuum worker is randmly hitting faults intended
for other backends by test and causing failures. Since there exists no
test now to test auto-vacuum processes with fault injector framework,
lets skip them. Other alternative would be to vacuum all existing
databases at end of auto-vacuum test to drop age for every database
and avoid triggering auto-vacuum after that test but that seems too
heavy and unnecessary.
=> Skip autovacuum processes from fault injector framework.

gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
Also cleaned up some dita tagging.
=> docs: gpbackup/gprestore add --help option.

src/backend/parser/parse_clause.c
This commit replaces the usage of CdbOpenRelationRv() with parserOpenTable()
for updates and deletes in setTargetList(). We cannot use the same function for
inserts since it upgrades the lock to Exclusive mode so leave the heap_openrv()
call intact there.
=> Remove GPDB_84_MERGE_FIXME in parse_clause.c

gpdb-doc/dita/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.xml
Just some minor tweaks. 
I tested the examples, and they work.
=> docs: minor edits to ALTER EXTERNAL TABLE.

src/backend/utils/mmgr/aset.c
Might be missing from the 9.0 merge
=> Add missing #ifdef block in aset.c

contrib/gp_replica_check/gp_replica_check.c
Use relmapping file in gp_replica_check.
commit b9b8831 introduced "relation mapping" infrastructure, which stores relfilenode as "0" in pg_class for shared and nailed catalog tables. The actual relfilenode is stored in separate file which
provides mapping from OID to relfilenode. gp_replica_check builds hashtable for relfilnodes to perform lookup for actual files on-disk. So, while populating this hashtable, consult relmap file to get relfilenode for tables with relfilenode = 0.
This should help avoid seeing WARNINGs like "relfilenode XXXX not present in primary's pg_class" or "found extra unknown file on mirror:" for gp_replica_check.
Also, gp_replica_check should fail if any WARNING is generated.
=> Use relmapping file in gp_replica_check

gpdb-doc/dita/admin_guide/external/g-gpfdists-protocol.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/utility_guide/admin_utilities/gpfdist.xml
-added guc definition to list of gucs
-added link to guc from appropriate topics.
See PR https://github.com/greenplum-db/gpdb/pull/4835
=> docs: Add guc verify_gpfdists_cert

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
See PR https://github.com/greenplum-db/gpdb/pull/4804
=> docs: add guc gp_max_slices

gpMgmt/bin/minirepro
This commit includes the stainherit column in minirepro output which has been recently
added.
=> Add the new column stainherit in minirepro dumps

concourse/scripts/deb_create_package.bash
only echo output of build upon failure
Co-authored-by: Larry Hamel <lhamel@pivotal.io>
Co-authored-by: Xin Zhang <xzhang@pivotal.io>
=> quiet build for debian package

src/backend/replication/gp_replication.c, src/backend/replication/test/gp_replication_test.c
When pid is not 0 and state is WALSNDSTATE_STARTUP mirror gets reported as down
without consulting the grace period. Hence refactor the logic to check for
grace period any time before replying to FTS that mirror is down. This was one
of the cases reported in CI possibly causing walrep_1 job to be flaky.
Co-authored-by: Ashwin Agrawal <aagrawal@pivotal.io>
=> Always check grace period when reporting mirror down

src/bin/pg_dump/pg_dumpall.c
Dump the new capability resgroup memory_auditor in pg_dumpall.
=> resgroup: dump memory_auditor in pg_dumpall for 5X branch.

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
=> docs - missed this on rebase; clarify cfg steps

src/tools/docker/centos6/Dockerfile, src/tools/docker/centos7/Dockerfile
Also getting rid of www.city-fan.org repo for building curl
=> Make dockerfiles for centos6 and centos7 consistent

concourse/scripts/deb_create_package.bash
use function to report error after failure
=> Concourse: refactor reporting after debuild error

src/bin/pg_ctl/pg_ctl.c
Currently, pg_ctl has 1 sec default sleep for -w option for start and stop and
always for restart. This is pretty long delay as most of times without -w start
and stop complete in msecs. So, instaed cut down waiting time to 0.2 msecs and
more frequently check. The patch doesn't change how long wait happens, just
modifiers sleep time in-between checking.
On laptop this nicely helps improve gpinitsystem (27 to 20 secs), gpstop (3
secs) and gpstart (12 secs to 7 secs).
=> Speedup pg_ctl stop,start,restart by reducing 1 sec sleep.

python-dependencies.txt
Fixed typo
[ci skip]
Authored-by: Todd Sedano <tsedano@pivotal.io>
=> Syncing python-dependencies with pythonsrc-ext

gpdb-doc/dita/admin_guide/query/topics/defining-queries.xml
-Move cast examples to install guide
-Pointer from install guide to admin guide for cast description.
Link to updated pages on gpdb review site
http://docs-gpdb-review-staging.cfapps.io/review/install_guide/43x_to_5x.html
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/query/topics/defining-queries.html#topic14
=> docs: integrate cast information with install guide.

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/atmsort.pm
This PR ports commit c38c72ff979bf4a7e618b5a19700df8cc6d67159.
No review needed. This is to trigger the PR pipeline
=> Do not translate printable filters of PartitionSelector

gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml, gpdb-doc/dita/admin_guide/managing/backup-plugin-api.xml, gpdb-doc/dita/admin_guide/managing/backup-plugins.xml, gpdb-doc/dita/admin_guide/managing/backup-s3-plugin.xml, gpdb-doc/dita/admin_guide/managing/backup.ditamap, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
--also minor update to S3 plugin- change yaml file parameter "backupdir" to "folder".
Link to HTML format of doc on GPDB review site.
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-plugins.html
S3 plugin
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-s3-plugin.html
DD Boost plugin
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-ddboost-plugin.html
=> docs - gpbackup/gprestore plugin for DD Boost

gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
also, fix title link to gpbackup plugins.
Link to HTML format docs on GPDB doc review site.
http://docs-gpdb-review-staging.cfapps.io/review/utility_guide/admin_utilities/gprestore.html
=> docs - add gprestore options --data-only, --metadata-only.

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
enhance global shared memory discussion.
also moved note to the section.
doc review site link:
- http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/workload_mgmt_resgroups.html#topic833glob
=> docs - add resgroup global shmem recommendation

src/pl/plpython/plpython.c, src/test/regress/expected/python_processed64bit.out, src/test/regress/greenplum_schedule, src/test/regress/sql/python_processed64bit.sql
=> First shot at merging SPI 64 bit changes for pl/Python

gpdb-doc/dita/ref_guide/extensions/pl_container.xml
Add the new attribute information to doc for
--plcontainer utility
--PL/Container confguration XML file
HTML format on the GPDB doc review site.
plcontainer Utility
http://docs-gpdb-review-staging.cfapps.io/review/ref_guide/extensions/pl_container.html#topic_rw3_52s_dw
XML attribute definition.
http://docs-gpdb-review-staging.cfapps.io/review/ref_guide/extensions/pl_container.html#topic_ojn_r2s_dw__plc_settings
=> docs - pl/container new setting attribute roles

src/backend/commands/resgroupcmds.c, src/backend/utils/resgroup/resgroup-ops-linux.c, src/backend/utils/resgroup/resgroup.c
- Change strncpy to StrNCpy, make sure dest string be terminated
- Initilize some variables before use it.
=> Fix potential bugs reported by CoverityScan of the PR 5023(Implement CPUSET)

gpdb-doc/dita/utility_guide/admin_utilities/gpcopy.xml, gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml, gpdb-doc/dita/utility_guide/utility_guide.ditamap
Link to HTML format on GPDB review site.
http://docs-gpdb-review-staging.cfapps.io/review/utility_guide/admin_utilities/gpcopy.html#topic1
=> docs - add gpcopy utility

src/backend/cdb/motion/ic_tcp.c
Previously, for an interconnect connection, if no data are available at
sender peer, the sender sends a customized EOS packet to the receiver
and disables further send operations using shutdown(SHUT_WR), then
somehow, the sender closes the connection totally with close()
immediately and it counts on the kernel and TCP stack to guarantee the
data been transformed to the receiver. The problem is, on some platform,
if the connection is closed on one side, the TCP behave is undetermined,
the packets may be lost and receiver may report an unexpected error.
The correct way is sender blocks on the connection until receiver
getting the EOS packet and close its peer, then the sender can close
the connection safely.
=> Fix teardown issue of TCP interconnect

gpdb-doc/dita/ref_guide/extensions/gppc.xml
=> docs - correct one of the gppc examples

gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml
will be backported to 5X_STABLE
Link to HTML doc on GPDB doc review site.
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-ddboost-plugin.html
=> docs - gpbackup ddboost plugin - add replication feature

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
-change set classification from system to session
-clarify INTO ERROR TABLE clause is not used.
will be backported to 5X_STABLE
=> docs - update GUC gp_ignore_error_table

README.md
new pipelines, new badge and link
=> updating README for pipeline changes

src/backend/commands/variable.c, src/backend/postmaster/postmaster.c, src/backend/replication/syncrep.c, src/backend/tcop/utility.c, src/backend/utils/time/tqual.c, src/test/isolation2/expected/.gitignore, src/test/isolation2/sql/.gitignore
Individual commit messages have details of the resolution for the same.
=> Resolve bunch of GPDB_91_MERGE_FIXME's

concourse/pipelines/README.md, concourse/pipelines/gen_pipeline.py
(cherry picked from commit 12888bf0f4df2d2a7286a8913e7c7e7ae24790eb)
=> Update README and remove depricated options

gpdb-doc/dita/ref_guide/GPReferenceSQLSummaryLOP.xml, gpdb-doc/dita/ref_guide/ref_guide.ditamap, gpdb-doc/dita/ref_guide/sql_commands/ALTER_FOREIGN_DATA_WRAPPER.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_FOREIGN_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_SERVER.xml, gpdb-doc/dita/ref_guide/sql_commands/ALTER_USER_MAPPING.xml, gpdb-doc/dita/ref_guide/sql_commands/COMMENT.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_DATA_WRAPPER.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_FOREIGN_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_SEQUENCE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_SERVER.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_USER_MAPPING.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_VIEW.xml, gpdb-doc/dita/ref_guide/sql_commands/DROP_FOREIGN_DATA_WRAPPER.xml, gpdb-doc/dita/ref_guide/sql_commands/DROP_FOREIGN_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/DROP_SERVER.xml, gpdb-doc/dita/ref_guide/sql_commands/DROP_USER_MAPPING.xml, gpdb-doc/dita/ref_guide/sql_commands/GRANT.xml, gpdb-doc/dita/ref_guide/sql_commands/REVOKE.xml, gpdb-doc/dita/ref_guide/sql_commands/sql_ref.xml, gpdb-doc/dita/utility_guide/client_utilities/pg_dump.xml
foreign data wrapper SQL reference pages:
- on par with postgresql version 9.1 content (even though the feature is not yet completely baked)
- new reference pages for alter/create/drop  server/usermapping/foreigntable/foreigndatawrapper
- updated comment/grant/revoke reference pages with new clauses
- minor additions to a few other reference pages
notes/questions:
- i did not update ref_guide/SQL2008_support.xml.  there will be many updates for the merge work, and this feature development is not complete.
- there is a reference in the postgresql docs to a built-in foreign-data wrapper named "default"?  is this a thing?  i couldn't find it anywhere.
doc staging site links for some of the ref pages:
- http://docs-gpdb-review-staging.cfapps.io/review/ref_guide/sql_commands/ALTER_FOREIGN_DATA_ …
=> docs - add foreign data wrapper-related sql ref pages

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
Will be ported to 5X_STABLE
Link to HTML on GPDB review doc site.
http://docs-gpdb-review-staging.cfapps.io/review/ref_guide/config_params/guc-list.html#gp_resource_group_bypass
GUC list by category
http://docs-gpdb-review-staging.cfapps.io/review/ref_guide/config_params/guc_category-list.html#topic444
Dev PR https://github.com/greenplum-db/gpdb/pull/5205
=> docs - add GUC gp_resource_group_bypass

src/test/isolation2/input/resgroup/resgroup_bypass.source, src/test/isolation2/output/resgroup/resgroup_bypass.source, src/test/isolation2/output/resgroup/resgroup_bypass_optimizer.source
- Remove async session before CREATE FUNCTION
- Change comment format from -- to /* */
=> Fix resource group bypass test case

gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gpstart, gpMgmt/bin/gpstop
Follow-up to #4923 (and #4934)
I will back-port this to 5X_STABLE once merged.
=> gppylib: Remove gp.get_user() and replace uses with unix.getUserName()

gpMgmt/bin/gppylib/test/unit/test_unit_gpstop.py, gpMgmt/bin/gpstop
Backport of https://github.com/greenplum-db/gpdb/pull/5274
=> `gpstop -u` runs HUP commands locally when possible

gpdb-doc/dita/admin_guide/load/load.ditamap, gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml, gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml, gpdb-doc/dita/utility_guide/utility_guide.ditamap
=> docs - add kafka connector xrefs

contrib/pg_upgrade/version.c
GPDB5 changed relation indexes on disk, and so they are all invalidated when upgrading from 4. Rather than expecting the user to know what to do after that mass-invalidation, write a script to perform a `REINDEX SYSTEM`/`DATABASE` for every `db_name` we have, and point the user to it.
=> pg_upgrade: dump REINDEX instructions after upgrade from GPDB4

contrib/xlogdump/xlogdump_rmgr.c
Adds a facility to dump XLOG_HINT records with xlogdump. We have backported
XLOG_HINT xlog records from upstream and this record type never existed at the
time that xlogdump was originally created.
=> Dump XLOG_HINT records with xlogdump

src/backend/cdb/cdbtm.c, src/backend/cdb/dispatcher/cdbdispatchresult.c, src/backend/utils/misc/guc_gp.c, src/test/regress/expected/dtm_retry.out, src/test/regress/greenplum_schedule, src/test/regress/sql/dtm_retry.sql
Please see individual commit messages for details.
=> Fix error handling in DTM retry logic and a bug in dispatcher's error handling

gpdb-doc/dita/best_practices/logfiles.xml
best practices guide had some incorrect locations for admin utility log files, my attempt at correcting these.
current doc content:
- https://gpdb.docs.pivotal.io/590/best_practices/logfiles.html
updated doc review site link:
- http://docs-gpdb-review-staging.cfapps.io/review/best_practices/logfiles.html
=> docs - correct log file locations in best practices

gpdb-doc/dita/admin_guide/external/g-external-tables.xml, gpdb-doc/dita/admin_guide/external/g-pxf-protocol.xml, gpdb-doc/dita/admin_guide/external/pxf-overview.xml, gpdb-doc/markdown/pxf/hive_pxf.html.md.erb, gpdb-doc/markdown/pxf/using_pxf.html.md.erb
this PR:
- enhances hive docs with partition filtering information
- clarifies connector support
- fixes some formatting errors
- misc edits
doc review site links:
- http://docs-pxfpush-lisa.cfapps.io/600/pxf/using_pxf.html#filter-pushdown
- http://docs-pxfpush-lisa.cfapps.io/600/pxf/hive_pxf.html#partitionfiltering
=> docs - enhance pxf filter pushdown info

gpdb-doc/dita/admin_guide/managing/access_db.xml, gpdb-doc/dita/admin_guide/managing/monitor.xml, gpdb-doc/dita/ref_guide/extensions/postGIS.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_LANGUAGE.xml
=> docs - fix some pivnet links

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-notes.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
Will be ported to 5X_STABLE.
See dev PR https://github.com/greenplum-db/gpdb/pull/5322
=> docs - update guc gp_enable_relsize_collection - ORCA support

gpMgmt/bin/lib/gp_bash_functions.sh
We believe this commit solves a long-standing intermittent bug where the `listen_addresses` GUC would be commented out in the resulting postgresql.conf; e.g.
```ini
#listen_addresses='*' #listen_addresses = '*'                   # what IP address(es) to listen on;
```
The culprit is that the following shell pipeline:
```sh
$CAT $SED_TMP_FILE | $TRUSTED_SHELL ${SED_HOST} $DD of=$SED_TMP_FILE > /dev/null 2>&1
```
when run with a `TRUSTED_SHELL` that executed the command on the local host, suffered from a race where `cat` was reading from the file as `dd` was attempting to truncate it. In situations where `dd` won that race, the resulting sed command file would be empty, and no change would be made.
Simplify the logic by removing all temporary files and forwarding the sed command file …
=> SED_PG_CONF: fix race condition that corrupted configurations

src/backend/cdb/cdbllize.c
This commit removes the FIXME along with the code that was disabled as
part of the FIXME, since it is no more relevant.
Prior to the merge, this code was introduced to handle the following
cases:
1. In case of UPDATE, DELETE and INSERT, we would set all plans to
`DISPATCH_PARALLEL` if the relation is either POLICYTYPE_REPLICATED or
POLICYTYPE_PARTITIONED
2. If UPDATE, DELETE and INSERT have returning as part of the sql and
the relation is either `POLICYTYPE_REPLICATED` or `POLICYTYPE_PARTITIONED`,
it should error out as `RETURNING` was not supported.
Post merge,
1. The dispatch for UPDATE, DELETE and INSERT plan is set to
`DISPATCH_PARALLEL` in the function `prescan()`, called later in the
code, based on `FLOW`
Earlier, the checks were explicitly required before the `prescan()`
as this …
=> Remove GPDB_90_MERGE_FIXME in cdblize.c

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
describe workloads and link to command center docs.  conditionalized.
=> docs - add conditionalized info about command center

src/test/regress/regress_gp.c
Changed only the files regress_gp
Please refer: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/BH1IXU6vnEw
=> Convert Insist into Assert on test/regress folder

src/backend/tcop/postgres.c
Remove the usages of Insist and replace them with Assert instead
Please refer: https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/BH1IXU6vnEw
=> Convert Insist into Assert on backend/tcop

src/backend/cdb/cdbcopy.c, src/backend/cdb/dispatcher/cdbdisp.c, src/backend/cdb/dispatcher/cdbdisp_dtx.c, src/backend/cdb/dispatcher/cdbdisp_query.c, src/backend/commands/copy.c, src/backend/commands/explain.c, src/backend/executor/execUtils.c, src/backend/executor/nodeSubplan.c, src/include/cdb/cdbcopy.h, src/include/cdb/cdbdisp.h, src/include/cdb/cdbdisp_query.h, src/test/regress/output/sreh.source
Please refer to commit message for details
=> misc cleanup of dispatcher code

src/backend/cdb/dispatcher/cdbdispatchresult.c
cdbdisp_get_PQerror create a new error data object and initialize it
with filename, function values from QE, errdata need a const filename,
function, it does not copy it in ErrorContext. The problem is filename
and function was point to a unstable memory, so when edata is used later,
it may report a SIGSEGV. To resolve this, copy them in the transaction
context because this error data can only be used inside current transaction.
=> Fix memory bug within cdbdisp_get_PQerror

src/backend/optimizer/path/allpaths.c
Co-authored-by: Alexandra Wang<lewang@pivotal.io>
Co-authored-by: Gang Xiong<gxiong@pivotal.io>
=> Remove a GPDB_92_MERGE_FIXME

src/backend/cdb/cdbvars.c
The line "if (source != PGC_S_DEFAULT)" was added a long time
ago, and there's no trace why it's added except the commit message:
"Don't set up interconnect too soon"
The 'do_connect' is true only when it's a backend process, and
there's no obvious problem setting 'gp_role' of the backend process.
Co-authored-by: Alexandra Wang <lewang@pivotal.io>
Co-authored-by: Gang Xiong <gxiong@pivotal.io>
=> Remove FIXME in assign_gp_role

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-limitations.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_INDEX.xml
=> docs - Add GPORCA support for GiST index.

gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml, gpdb-doc/dita/admin_guide/managing/backup-plugin-api.xml, gpdb-doc/dita/admin_guide/managing/backup-plugins.xml, gpdb-doc/dita/admin_guide/managing/backup-s3-plugin.xml, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml
-Removed Warning - plugin is experimental feature.
-Removed limitation to use --single-data-file or --metadata-only with --plugin
=> docs - gpbackup - plugin GA, plugin support multi-file backup.

src/backend/cdb/cdbhash.c, src/include/cdb/cdbhash.h
It should be modulo, not module.
=> Fix typo in cdbhash.

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/backend/gpopt/translate/CTranslatorUtils.cpp, src/include/gpopt/translate/CTranslatorUtils.h
=> Silence a couple of compiler warnings

src/backend/commands/explain.c, src/test/regress/expected/gp_explain.out, src/test/regress/expected/gp_explain_optimizer.out, src/test/regress/sql/gp_explain.sql
Fixes https://github.com/greenplum-db/gpdb/issues/5551
=> Fix EXPLAIN of a window function's PARTITION BY clause.

gpdb-doc/dita/admin_guide/managing/backup-gpbackup-incremental.xml, gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml, gpdb-doc/dita/admin_guide/managing/backup.ditamap, gpdb-doc/dita/utility_guide/admin_utilities/gpbackup.xml, gpdb-doc/dita/utility_guide/admin_utilities/gprestore.xml
--New Admin. Guide topic describing incremental backups
--Updates to gpbackup/gprestore Admin Topic for history file.
--Updates to gpbackup/gprestore reference for new functionality
Links to HTML documents on the GPDB review site
new incremental backup topic
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-gpbackup-incremental.html
updated admin topic - gpbackup history file.
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-gpbackup.html
Updated gpbackup/gprestore reference topics
http://docs-gpdb-review-staging.cfapps.io/review/utility_guide/admin_utilities/gpbackup.html
http://docs-gpdb-review-staging.cfapps.io/review/utility_guide/admin_utilities/gprestore.html
=> docs - gpbackup -incremental backups

src/backend/libpq/auth.c, src/backend/libpq/hba.c, src/backend/libpq/pg_hba.conf.sample, src/backend/postmaster/postmaster.c, src/include/getaddrinfo.h, src/include/libpq/hba.h, src/include/libpq/libpq-be.h, src/port/getaddrinfo.c
These are the two commits we ported:
https://github.com/greenplum-db/gpdb/commit/6ab42ae36713b1e6f961c37e22f99d3e6267523b
and 
https://github.com/greenplum-db/gpdb/commit/fc752505a99a4e2c781a070d3d42a25289c22e3c
As part of porting, we fixed the code a little bit to get it working on 5X_STABLE.
=> Port upstream pg_hba.conf commits for hostname support

src/backend/parser/parse_func.c, src/test/regress/expected/filter.out, src/test/regress/sql/filter.sql
Fixes https://github.com/greenplum-db/gpdb/issues/5565
=> Add same STRICTness check in window functions, that we have in aggregates.

gpdb-doc/dita/admin_guide/intro/about_statistics.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_statistic.xml
update relevant using and catalog ref pages
=> docs - add pg_statistic stainherit column

src/bin/pg_dump/pg_dump.c
In pg_dump, we had a GPDB-specific hack to change the owners of the
handler and validator functions of the language, after dumping the CREATE
LANGUAGE command. This was added back in 2008, with commit message:
MPP-3774: Change pg_dump to emit ALTER FUNCTION ... OWNER statements
for functions underlying created languages for languages defined
using pg_pltemplate-specified languages.
I looked into MPP-3774, but I couldn't make much sense of it.
Title:
pg_dumpall doesn't dump Language function owners
Description:
pg_dumpall doesn't dump the permissions for the CREATE LANGUAGE. need to
modify the function owners. so ALTER FUNCTION ... OWNER TO ...
PostgreSQL never had that code. I don't think it is relevant anymore,
there's been a lot of change in the way languages are handled. Firstly,
they …
=> Don't emit extra ALTER FUNCTION OWNER TO commands after CREATE LANGUAGE.

gpAux/extensions/pxf/src/pxffilters.c, gpAux/extensions/pxf/test/pxffilters_test.c, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, src/backend/utils/misc/guc_gp.c
Co-authored-by: Shivram Mani <smani@pivotal.io>
Co-authored-by: Alex Denissov <adenissov@pivotal.io>
=> Default gp_external_enable_filter_pushdown GUC to true and fixes to handle both planner & orca qualifiers

gpdb-doc/book/master_middleman/source/subnavs/pxf-subnav.erb, gpdb-doc/markdown/pxf/instcfg_pxf.html.md.erb, gpdb-doc/markdown/pxf/pxf_kerbhdfs.html.md.erb, gpdb-doc/markdown/pxf/pxfuserimpers.html.md.erb
docs describing how to config PXF for a secure HDFS
- new topic added to PXF section
- a few misc related edits in other files
doc review site link to new page:
- http://docs-lisa-pxfkerb.cfapps.io/600/pxf/pxf_kerbhdfs.html
=> docs - pxf config for kerberized hdfs

src/backend/commands/analyze.c, src/backend/commands/analyzeutils.c, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/expected/incremental_analyze.out
This commit adds more log messages and updates existing log messages to
increase logging verbosity.
Signed-off-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>
=> Making incremental analyze more verbose

src/test/regress/expected/dpe_optimizer.out, src/test/regress/expected/gporca_optimizer.out
There are plan changes after the
commit:02af5c59043d907fe986d58506ce90f32d9c8258, so updating the output
files with the valid plans. It got missed in the earlier commit.
=> Updated test case related to commit: 02af5c59

src/test/regress/expected/gp_dqa.out, src/test/regress/expected/qp_misc_jiras.out
Fix test cases that are failing to pass, They are caused by a4cbf5860d1a8b86e948ad78d27a84d1bada9407 .
=> Fix test cases that are failing to pass

gpdb-doc/dita/admin_guide/external/pxf-overview.xml, gpdb-doc/markdown/pxf/hbase_pxf.html.md.erb, gpdb-doc/markdown/pxf/hive_pxf.html.md.erb, gpdb-doc/markdown/pxf/using_pxf.html.md.erb
filter pushdown is enabled by default.  most updates are in the pxf docs.
=> docs - updates for ext tbl filter pushdown default value on

src/backend/commands/portalcmds.c, src/backend/executor/spi.c, src/backend/tcop/pquery.c, src/backend/utils/mmgr/portalmem.c, src/backend/utils/resscheduler/README, src/backend/utils/resscheduler/resqueue.c, src/backend/utils/resscheduler/resscheduler.c, src/include/utils/portal.h, src/include/utils/resscheduler.h, src/test/regress/expected/resource_queue_with_rule.out, src/test/regress/greenplum_schedule, src/test/regress/sql/resource_queue_with_rule.sql
Backports https://github.com/greenplum-db/gpdb/pull/5704 to 5X_STABLE. Waiting for a green build to merge.
=> Backport "Avoid out of shared memory adding portal increments."

src/backend/optimizer/path/allpaths.c
This helps gpdb planner debugging.
Co-authored-by: Paul Guo <paulguo@gmail.com>
Co-authored-by: Shaoqi Bai <sbai@pivotal.io>
=> Show motion path and path locus type in print_path().

src/backend/utils/time/sharedsnapshot.c
Use StringInfo when logging distributed snapshot info
Under GCC 8, I get a warning (and rumor has it that you get this under
GCC 7 with `-Wrestrict`):
```
sharedsnapshot.c: In function ‘LogDistributedSnapshotInfo’:
sharedsnapshot.c:924:11: warning: passing argument 1 to
restrict-qualified parameter aliases with argument 4 [-Wrestrict]
snprintf(message, MESSAGE_LEN, "%s, In progress array: {",
^~~~~~~
message);
~~~~~~~
sharedsnapshot.c:930:13: warning: passing argument 1 to
restrict-qualified parameter aliases with argument 4 [-Wrestrict]
snprintf(message, MESSAGE_LEN, "%s, (dx%d)",
^~~~~~~
message, ds->inProgressXidArray[no]);
~~~~~~~
sharedsnapshot.c:933:13: warning: passing argument 1 to
restrict-qualified parameter aliases with argument 4 [-Wrestrict]
snprintf(message, MESSAGE_LEN, "%s …
```
=> Use StringInfo when logging distributed snapshot info (was: do not alias arguments to restrict-qualified parameters (`snprintf`))

src/backend/storage/ipc/procarray.c
procarray.c: In function ‘getAllDistributedXactStatus’:
procarray.c:1616:15: warning: passing argument 1 of ‘strlen’ discards
‘volatile’ qualifier from pointer target type
procarray.c: In function ‘getDtxCheckPointInfo’:
procarray.c:1693:36: warning: passing argument 1 of
‘includeInCheckpointIsNeeded’ discards ‘volatile’ qualifier from pointer
target type
=> Resolve compiler warnings caused by volatile variable.

gpdb-doc/dita/admin_guide/intro/mvcc_example.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_class.xml
=> docs - update when pg_class.relfrozenxid is 0 (zero)

contrib/pgbench/pgbench.c
=> Fix pgbench, and rename the -q option.

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/test/regress/expected/bfv_dd_optimizer.out, src/test/regress/expected/qp_targeted_dispatch_optimizer.out
This commit adds the tests corresponding to the below change introduced in PQO. Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/395
In case of Insert on Randomly distributed relations, a random / redistribute
motion must exists to ensure randomness of the data inserted, else there will
be skew on 1 segment.
Consider the below scenario:
Scenario 1:
```
CREATE TABLE t1_random (a int) DISTRIBUTED RANDOMLY;
INSERT INTO t1_random VALUES (1), (2);
SET optimizer_print_plan=on;
EXPLAIN INSERT INTO t1_random VALUES (1), (2);
Physical plan:
+--CPhysicalDML (Insert, "t1_random"), Source Columns: ["column1" (0)], Action: ("ColRef_0001" (1))   rows:2   width:4  rebinds:1   cost:0.020884   origin: [Grp:1, GrpExpr:2]
+--CPhysicalComputeScalar
|--CPhysicalMotionRandom  ==> Random …
```
=> Update optimizer output test files

gpdb-doc/dita/best_practices/ha.xml
=> docs - fix typo

src/test/regress/greenplum_schedule
The test was added in commit 3672f91274, but I forgot to add it to the
schedule. Oops.
=> Enable 'gp_types' test.

src/bin/gpfdist/gpfdist.c
gpfdist --sslclean option is a platform related patch for Solaris system.
gpfdist delays cleaning ssl buffer for some seconds which is configured
by sslclean option.
GPDB6 doesn't support Solaris now. We don't think that solution has
benefit for other platforms, so we remove --sslclean option.
Have Verified this patch manually and the default test cases cover this change.
=> Remove gpfdist --sslclean option

src/backend/replication/walsender.c
The reason we needed the FIXME pq_getmessage() marked with the FIXME
comment was that we were missing the pq_getmessage() call from
ProcessStandbyMessage(), that the corresponding upstream version, at
the point that we're caught up in the merge, had. I believe the reason
it was missing from ProcessStandbyMessage() was that we had earlier
backported upstream commit cd19848bd55. That commit removed the
pq_getmessage() call from ProcessStandbyMessage(), and added one in
ProcessRepliesIfAny(), instead.
Clarify this by changing the code to match upstream commit cd19848bd55
(except that we don't have pq_startmsgread() yet, that will arrive in
when we merge the rest of commit cd19848bd55)
=> Refactor code in ProcessRepliesIfAny() to match upstream.

src/backend/replication/walreceiver.c
Regular fault injection doesn't work for mirrors. Hence, using SIGUSR2 signal
and on-disk file coupled with it just for testing a fault injection mechanism
was coded. This seems very hacky and intrusive, hence plan is to get rid of the
same. Most of the tests using this framework are found not useful as majority of
code is upstream. Even if needs testing, better alternative would be explored.
=> Delete SIGUSR2 based fault injection logic in walreceiver.

gpcontrib/gp_internal_tools/gp_ao_co_diagnostics.c, src/backend/access/aocs/aocsam.c, src/backend/access/aocs/aocssegfiles.c, src/backend/access/appendonly/appendonlyam.c, src/backend/access/appendonly/appendonlywriter.c, src/backend/catalog/gp_toolkit.sql, src/include/access/appendonlywriter.h, src/include/utils/faultinjector_lists.h, src/test/isolation2/input/uao/insert_should_not_use_awaiting_drop.source, src/test/isolation2/isolation2_regress.c, src/test/isolation2/isolation2_schedule, src/test/isolation2/output/uao/insert_should_not_use_awaiting_drop.source
Please see individual commit messages for more details.
=> Fix a bug that caused new data to be inserted into segfiles in "awaiting drop" state

src/backend/access/transam/xlog.c
=> Fix two xlog.c fixmes

gpdb-doc/dita/admin_guide/managing/backup-boostfs.xml
-How to find the boostfs config. guide
-How to find the boostfs RPM
Link to HTML format on the GPDB Docs review site
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/managing/backup-boostfs.html
=> docs - update boostfs install instructions.

src/backend/cdb/motion/ic_tcp.c
When TCP connections cannot be setup for a long time, we check
if some segments are already failed out, the check is an high-cost
operation, so we set the interval to 2 seconds. We used to use a
counter to record the interval which is not reliable because
a loop cycle (500ms) may be interrupted earlier due to
EINT/EAGAIN of select().
To not affect the setup performance of TCP interconnect, we need
to make the interval mechanism more reliable.
=> Fix the interval issue when Seting up TCP interconnect

src/backend/optimizer/plan/planner.c
make_windowInputTargetList() seems like a better place for this code,
as suggested by the FIXME comment that was left here in the 9.3 merge.
=> Move code marked with FIXME to make_windowInputTargetList().

src/backend/utils/adt/ruleutils.c, src/test/regress/expected/olap_window_seq.out, src/test/regress/expected/olap_window_seq_optimizer.out, src/test/regress/sql/olap_window_seq.sql
Fixes https://github.com/greenplum-db/gpdb/issues/2996
=> Fix deparsing of DISTINCT-qualified window aggregates.

src/backend/catalog/oid_dispatch.c, src/backend/commands/alter.c, src/backend/commands/comment.c, src/backend/commands/event_trigger.c, src/backend/tcop/utility.c, src/include/catalog/pg_proc.h, src/test/regress/expected/event_trigger.out, src/test/regress/parallel_schedule, src/test/regress/sql/event_trigger.sql
=> Fix event triggers
