greenplum-db/gpdb

- src/backend/tcop/postgres.c
- src/backend/utils/resscheduler/resqueue.c
- src/test/isolation2/expected/resource_queue_multi_portal.out
- src/test/isolation2/sql/resource_queue_multi_portal.sql
A reported issue shows that queries belonging to a specific resource queue were blocked because the limit counter of the RQ was full. Actually, no query of the RQ were running. So we hit kind of limit counter "leak".
Investigation shows that `ResLockAcquire()` or `ResLockRelease()` was interrupted previously. Then, in `ResLockRelease()`, it found one or more locks (locallock, proclock and lock) were missing and returned early. It most likely missed updating resource queue limit counter and pg_locks info resulting that future queries were blocked due to the incorrect limit counter. However, we cannot determine the interruption point and lack more details. We need to dump more info for the case.
The PR includes three parts:
1. Use two static vars `ResLockAcquireStatus` and …
> Dump more info of releasing resource queue lock info

- src/backend/access/common/reloptions_gp.c
- src/backend/catalog/pg_attribute_encoding.c
- src/backend/commands/cluster.c
- src/backend/commands/matview.c
- src/backend/commands/tablecmds.c
- src/backend/parser/gram.y
- src/bin/psql/describe.c
- src/include/access/reloptions.h
- src/include/catalog/pg_attribute_encoding.h
- src/include/commands/cluster.h
- src/include/nodes/altertablenodes.h
- src/include/nodes/parsenodes.h
- src/test/regress/expected/alter_table_aocs.out
- src/test/regress/expected/alter_table_set.out
- src/test/regress/expected/column_compression.out
- src/test/regress/expected/gp_partition_template.out
- src/test/regress/expected/partition_storage.out
- src/test/regress/sql/alter_table_set.sql
- src/test/regress/sql/column_compression.sql
- src/test/regress/sql/partition_storage.sql
This PR includes two commits:
1. Add pg_attribute_encoding entries for partition roots.
During create statement, we add attribute encoding entries to catalog
If the table has a parent partition, and no options or encodings are
specified, we copy the parent partition's encoding entries
Also add encoding info to d+ description of root partitions
The storage encoding clause for a column is picked as follows:
* 1. An explicit encoding clause in the ColumnDef of self/parent
* 2. A column reference storage directive for this column
* 3. A default column encoding in the statement
* 4. Parent partition's column encoding values
* 5. A default for the type.
2. Alter column encoding for AOCO tables
This commit introduces a new command to alter a column's encoding for an AOCO table.
ALTER TABLE aoco …
> Alter column encoding for AOCO tables

- gpdb-doc/markdown/utility_guide/ref/plcontainer-configuration.html.md
Add `enable_network` reference docs for next pl/container release.
> Docs - add pl/container enable_network parameter reference

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLESPACE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLESPACE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_TABLESPACE.html.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. there was some greenplum-specific content on the v6 pages, see notes/questions for more info.
notes/questions:
- CREATE page has some greenplum-specifics related to content<N>, i retained this info.
- CREATE page was missing the tablespace_option = value (where tablespace_option = seq_page_cost or random_page_cost).  i added this to the synopsis and included the postgres option/value discussion.  was that the right thing to do?
- CREATE page - includes some text about max char length of the LOCATION directory - search for XXX.  is this still true for greenplum 7?
- CREATE page - removed some info from the Notes that was duplicated in the "using tablespaces" topic …
> docs - update sql ref pages for ALTER/CREATE/DROP TABLESPACE

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLESPACE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLESPACE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_TABLESPACE.html.md
per comment on https://github.com/greenplum-db/gpdb/pull/14435, add the tablespace_option to the CREATE TABLESPACE sql reference page.
note:  i also corrected some content, but did not include all of the wording edits from the main/7 PR.
> docs - misc updates to 6x TABLESPACE ref pages

- gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
the tables in this topic did not render correctly.  replaced the html with the markdown from https://github.com/greenplum-db/gpdb/blob/6X_STABLE/gpdb-doc/markdown/ref_guide/modules/gp_parallel_retrieve_cursor.html.md.
> docs - fix the tables in the parallel retrieve cursor topic

- gpMgmt/bin/gpactivatestandby
The pg_ctl promote wait logic checks for IN_PRODUCTION state in the promoted coordinator's control file to determine if the standby coordinator has successfully been promoted or not. Unfortunately, that IN_PRODUCTION state does not guarantee that the promoted coordinator is ready to accept database connections yet. Make gpactivatestandby do a retry loop on its forced CHECKPOINT logic to guarantee that the CHECKPOINT goes through and immediately reflects the new timeline id. With this patch, intermittent gpactivatestandby Behave test flakes seen frequently in the Concourse pipeline are resolved.
The logic in this patch is also actually somewhat of a revert to previous logic as we used to do the very same retry loop. The retry loop was removed because we wrongly assumed pg_ctl promote wait …
> Make gpactivatestandby do retry loop after standby promote

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
hash_search(,,HASH_REMOVE,) returns a dangling pointer that shouldn't be dereferenced.
> ao/co: don't dereference dangling pointers

- concourse/scripts/setup_gpadmin_user.bash
- gpMgmt/bin/gpinitsystem
- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Making sure that the gpinitsystem populates correct value in gp_segment_configuration table with the right value of segment host-name for primary and mirror segments. 
Currently when creating cluster using gpinitsystem and contains host with multiple interfaces/addresses, in the segment configuration host-name field is getting populated with host-address. After this change, host-address field and host-name field will have respective values. 
Code change contains to avoid overwriting host-name field with the address. 
**Testing Done**:
Ran manual tests on ByoL cluster with mirror and standby configuration. 
Concourse pipeline is almost green. 
**Prior to change**: 
If node has multiple NIC's, and if we specify address as part of segment host list, same getting populated as host name and …
> gpinitsystem: Making sure that host-name filed is populated with host-name

- src/backend/parser/gram.y
- src/backend/parser/parse_clause.c
- src/include/nodes/parsenodes.h
- src/test/regress/expected/olap_group.out
- src/test/regress/sql/olap_group.sql
Arbitrarily cap the size of CUBE, which has exponential grow is not a computationable SQL. 
Disallow elements more than 12 to keep align with upstream.
----------
* Master branch already have this kind of code when merging PG9.6. So this PR is only for 6X.
* I add a field in the parse tree's struct, append the filed at the end of the struct, so it should not break ABI
* In my local VM (very small machine), it runs 36 sec to generate a plan for the following SQL with 12 elements (NOTE the main part of explain cannot be interrupted still).
```
gpadmin@zlyu:~/workspace/gpdb$ psql
psql (9.4.26)
gpadmin=# \timing
Timing is on.
gpadmin=# set statement_mem = '2GB';
SET
Time: 28.256 ms
gpadmin=# explain select c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c25, c26, c27, …
```
> (6x only) CUBE is limited to at most have 12 elements.

- src/backend/catalog/oid_dispatch.c
- src/backend/commands/matview.c
- src/backend/optimizer/util/clauses.c
- src/include/catalog/oid_dispatch.h
- src/test/regress/expected/oid_consistency.out
- src/test/regress/sql/oid_consistency.sql
The two functions SaveOidAssignments and RestoreOidAssignments should come together, before some procedures that do not want to touch the global vars (dispatch_oids or preassigned_oids), we need to first save the oid assignments, and then do the job, finally restore oid assignments. A typical usage should be as below:
List *l = SaveOidAssignments();
do_the_job();
RestoreOidAssignments(l);
The global var dispatch_oids is only used on QD, and the global var preassigned_oids is only used on QEs. They are both Lists, in a specific memorycontext, normally the memorycontext will be reset at the end of transaction. Greenplum's MPP architecture need to make some OIDs consistent among coordinator and segments (like table OIDs). The oid assignments are generated on QD and then dispatched to QEs. A …
> Refactor SaveOidAssignments and RestoreOidAssignments logic.

- contrib/pgcrypto/expected/fips_2.out
- contrib/pgcrypto/openssl.c
- src/test/regress/init_file
old pgcrypto use FIPS_mode() == 0 to check if can enable FIPS or not. but FIPS_mode() return none zero means FIPS already initialized by the OS or env OPENSSL_FIPS=1
this PR removes the check, allow to enable FIPS on a none FIPS OS
7X: #13905
ci test case:
for 7X we have
- rhel8 with OpenSSL 1.1.1k  FIPS 25 Mar 2021:   FIPS_mode() support at application level, not certified
- centos7 with OpenSSL 1.0.2k-fips  26 Jan 2017: FIPS_mode() support at application level, not certified
- ubuntu 18.04 with OpenSSL 1.1.1  11 Sep 2018:  FIPS_mode not enabled
for 6X we have
- sles12 with OpenSSL 1.0.2p-fips  14 Aug 2018:   FIPS_mode() support at application level, not certified
- photon3 with OpenSSL 1.0.2zc-fips  22 Feb 2022: FIPS_mode() support at application level, not certified
- rhel8 with …
> 6X pgcrypto: allow enable FIPS in FIPS not enabled OS

- src/backend/executor/instrument.c
- src/include/executor/instrument.h
The extension metrics collector needs gp_gettmid to get the timestamp.
> Declare gp_gettmid as an extern function

- src/backend/cdb/dispatcher/cdbconn.c
- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/cdb/dispatcher/cdbgang.c
- src/backend/cdb/dispatcher/cdbgang_async.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbconn.h
- src/include/cdb/cdbgang.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/init_file
- src/test/regress/input/dispatch.source
- src/test/regress/output/dispatch.source
Add GUC gp_print_create_gang_time control whether to print information about creating gang time.
We print the create gang time for both DDL and DML.
If all the segDescs of a gang are from the cached pool, we regard the gang as reused.
We only display the shortest and longest establish conn time and their segindexs of a gang.
The info of the shortest establish conn time and the longest establish conn time is the same for 1-gang.
DDL:
```
create table t(tc1 int);
INFO: The shortest establish conn time: 4.48 ms, segindex: 2,
The longest  establish  conn time: 8.13 ms, segindex: 1
set optimizer=off;
INFO: (Gang) is reused
```
DML:
we can use DML or explain analyze to get create gang time.
```
select * from t_create_gang_time t1, t_create_gang_time t2 where t1.tc1=2;
INFO: (Slice1) is reused …
```
> 6X:Add a GUC to display create gang time while executing statements

- src/backend/commands/analyze.c
- src/backend/commands/analyzefuncs.c
- src/backend/tsearch/ts_typanalyze.c
- src/backend/utils/adt/rangetypes_typanalyze.c
- src/include/commands/vacuum.h
- src/test/regress/expected/analyze.out
- src/test/regress/expected/incremental_analyze.out
gp_bloat_diag use the given statistics(including stawidth) in pg_statistic to compute the expected number of pages for the given table.
To avoid consuming too much memory during analysis and/or too much space in the resulting pg_statistic rows, ANALYZE ignores varlena datums that are wider than WIDTH_THRESHOLD. So the average width of column values is far smaller than the real average width, especially for varlena datums which are larger than WIDTH_THRESHOLD but stored uncompressed.
The wrong stawidth value causes gp_bloat_diag view shows tables have bloat and require a "VACUUM" or "VACUUM FULL", although these tables don't have bloat in fact.
Include the total length and number of oversized rows when computing the stawidth.
> [6X]Consider oversized rows for stawidth computation

- src/backend/commands/analyze.c
- src/backend/commands/analyzefuncs.c
- src/backend/tsearch/ts_typanalyze.c
- src/backend/utils/adt/rangetypes_typanalyze.c
- src/include/commands/vacuum.h
- src/test/regress/expected/analyze.out
- src/test/regress/expected/incremental_analyze.out
- src/test/regress/expected/incremental_analyze_optimizer.out
gp_bloat_diag use the given statistics(including stawidth) in pg_statistic to compute the expected number of pages for the given table.
To avoid consuming too much memory during analysis and/or too much space in the resulting pg_statistic rows, ANALYZE ignores varlena datums that are wider than WIDTH_THRESHOLD. So the average width of column values is far smaller than the real average width, especially for varlena datums which are larger than WIDTH_THRESHOLD but stored uncompressed.
The wrong stawidth value causes gp_bloat_diag view shows tables have bloat and require a "VACUUM" or "VACUUM FULL", although these tables don't have bloat in fact.
Include the total length and number of oversized rows when computing the stawidth.
> Consider oversized rows for stawidth computation

- src/backend/postmaster/bgworker.c
- src/backend/postmaster/postmaster.c
- src/include/postmaster/bgworker_internals.h
Hi，
As diskquota uses dynamic bgworkers to monitor databases in the latest version (2.1), we have encountered some problems with it and found that those are all resolved on gpdb7, so we want to cherry-pick them into gpdb6.
There are total 3 commits in this pr: 
91118f1a59f2038f072552fdbb98e01363e30b59  this commit reduces log level for background worker events from LOG to DEBUG1,  as LOG is just too chatty for something that will happen as routinely as this.
aea5d298362e881b13d95a48c5ae116879237389 and 7f6fa29f18aa84743185ee7ada97f277459228a7, those 2 commits, fix failures of trying to launch new bgworkers before the worker slots used by the previous ones were freed. More details are in the commit message.
> [6X] Commits to fix some bgworker issues on gpdb6

- gpMgmt/bin/analyzedb
analyzedb keeps list of tables (partitions) to analyze as python list.
List lookups are slow, analyzedb may spend hours if `candidates` list has ~ 1M items.
Lookups in `set` are much faster.
> fix candidates lookup complexity

- src/backend/access/common/reloptions.c
- src/backend/access/common/reloptions_gp.c
- src/backend/commands/analyze.c
- src/include/access/reloptions.h
- src/include/utils/guc.h
- src/include/utils/rel.h
- src/test/regress/expected/incremental_analyze.out
- src/test/regress/sql/incremental_analyze.sql
Currently, tables do not collect HLL statistics unless they are part of a partitioned table. However, this means that a regular table that is exchanged or added to a partition table will also not have HLL statistics unless it is reanalyzed, and the root table will also therefore not have statistics for the exchanged/added partition.
This commit adds a reloption, "analyze_hll_non_part_table", that will also collect HLL stats if the table is created with this reloption. HLL stats will still always be collected if the table is created as part of a partitioned table, so this option only has an effect when tables are not part of the partition hierarchy.
Note: pg_dump/upgrade/gpbackup will automatically dump this since this is stored as a string in the reloption in pg_class.
New syntax:
`CREATE …
> [6X] Add reloption to force table to collect HLL stats

- src/backend/catalog/gp_toolkit.sql
- src/backend/catalog/gp_toolkit_test.sql
- src/test/isolation2/expected/resgroup/resgroup_views.out
- src/test/isolation2/sql/resgroup/resgroup_views.sql
Added a new view into the resource manager tool `gp_toolkit` to perform the function that are used frequently:
gp_toolkit.gp_resgroup_role: assigned resource group to roles.
> Added gp_resgroup_role view into gp_toolkit.

- src/backend/commands/copy.c
- src/test/regress/input/gpcopy.source
- src/test/regress/output/gpcopy.source
When the column order isn't consistent between the root table and its partitions, the data distribution check may fail due to it referencing the root table's distribution policy.
We have 2 optional choices to fix this issue:
1. We should use partition's distribution policy for computing the tuple's target segment.
2. As what we do in this PR, we move the distribution check logic before the reordering of the tuple's columns. Because before the reordering of the tuple's columns, the tuple's columns order is the same as the root table's column order. The benefit is that, we don't need to introduce another variable to store partition's distribution policy.
Fix #14353.
> [7X] Fix incorrect distkey when copy partitions on segment.

- src/backend/commands/analyze.c
- src/backend/commands/analyzeutils.c
- src/backend/statistics/dependencies.c
- src/backend/statistics/extended_stats.c
- src/backend/utils/adt/selfuncs.c
- src/include/commands/analyzeutils.h
- src/test/regress/expected/stats_ext.out
- src/test/regress/expected/stats_ext_optimizer.out
- src/test/regress/sql/stats_ext.sql
This pr contains the following modifications：
- fixed issue https://github.com/greenplum-db/gpdb/issues/13872.
We used to not acquire sample rows for root partition when the following conditions were held for all attributes.
```c
if (get_rel_relkind(attr->attrelid) == RELKIND_PARTITIONED_TABLE &&
!get_rel_relispartition(attr->attrelid) &&
leaf_parts_analyzed(stats->attr->attrelid, InvalidOid, va_cols, stats->elevel) &&
((!OidIsValid(eqopr)) || op_hashjoinable(eqopr, stats->attrtypid)))
```
It works fine when we just have per-column-statistics, we can merge the statistics of leaf partitions into statistics of the root partition. But it can't work with extended statistics. We must acquire sample rows for root partitions to build extended statistics. 
- cherry-picked …
> Acquire sample rows for root partition to build extend statistics

- src/test/fdw/extension/extended_protocol_commit_test_fdw.c
This extension fails with a later version of PostgreSQL, which we will merge.
commit 41c6a5bec25e720d98bd60d77dd5c2939189ed3c
Date:   Fri May 21 14:03:53 2021 -0400
Restore the portal-level snapshot after procedure COMMIT/ROLLBACK.
And quote the release note:
> Some extensions may attempt to execute SQL code outside of any Portal.
> They are responsible for ensuring that an outer snapshot exists before
> doing so. Previously, not providing a snapshot might work or it might
> not; now it will consistently fail with “cannot execute SQL without an
> outer snapshot or portal”.
> Fix the test extension to execute SQL code inside of a Portal

- src/backend/commands/cluster.c
- src/backend/commands/matview.c
- src/include/commands/cluster.h
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
Column names of matview are possible duplicate with the aliases used in those queries of refresh_by_match_merge(). Create transient table with specified colprefix to prevent column conflict issue happens.
Also, rather than trying to pick table aliases that won't conflict with any possible user-defined matview column name, adjust the queries' syntax so that the aliases are only used in places where they can't be mistaken for column names. Mostly this consists of writing "alias.*" not just "alias", which adds clarity for humans as well as machines.
In GPDB, use "SELECT alias.*" rather than "alias.*::compositetype" in upstream to support DISTRIBUTED BY clause.
> Fix column conflict issue in REFRESH MATERIALIZED VIEW CONCURRENTLY.

- src/backend/access/transam/xlog.c
- src/test/isolation2/expected/checkpoint_dtx_info.out
- src/test/isolation2/sql/checkpoint_dtx_info.sql
Proceed PR https://github.com/greenplum-db/gpdb/pull/12978.
Stop the cluster with immediate mode, the instance does not have
chance to write a SHUTDOWN_CHECKPOINT WAL. Hence, WAL replay is
trigger in startup process in next time cluster start. It will
collect a bunch of global txn which is not finished and write a
SHUTDOWN_CHECKPOINT to promise the cluster consistency.
Before we believe a RecordShort is enough for our extend checkpoint
wal due to global txn information. It is not always true, in data
bulk import into env, at least ten import session is working, so
RecordLong may used.
For every time the cluster instance start, it will valid the last
checkpoint wal size and replay. If the checkpoint wal was used
RecordLong the size validation believe it is an illegal xlog. The
issue is …
> [7X] Fix checkpoint wal replay failed when in long XLOG header.

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/ltree.html.md
- gpdb-doc/markdown/ref_guide/toc.md
add a topic for the ltree module that will now be included in the greenplum 7 and 6.23 distributions.
we are xref'ing out to the postgres docs for the bulk of the "using" content. this PR is for master, xrefs to the postgres v12 version of the docs.  i will create a new PR for 6X_STABLE that xrefs to the postgres v9.4 docs.
question:  are there any greenplum- or mpp-specific considerations to call out for this module?
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/ltree/greenplum-database/GUID-ref_guide-modules-ltree.html
> docs - add content for ltree module

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/uuid-ossp.html.md
- gpdb-doc/markdown/ref_guide/toc.md
add a topic for the uuid-ossp module that will now be included in the greenplum 7 and 6.23 distributions.
we are xref'ing out to the postgres docs for the bulk of the "using" content. this PR is for main, xrefs to the postgres v12 version of the docs. i will create a new PR for 6X_STABLE that xrefs to the postgres v9.4 docs.
question: are there any greenplum- or mpp-specific considerations to call out for this module?
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/uuid-ossp/greenplum-database/GUID-ref_guide-modules-uuid-ossp.html
> docs - add content for uuid-ossp module

- src/test/fdw/.gitignore
- src/test/fdw/extension/extended_protocol_commit_test_fdw.c
"795278996fc - Fix the test extension to execute SQL code inside of a Portal" (#14515) "fixed" it but also failed an assertion, this commit fixes it in another way as the pgsql-hackers suggests.
Ref: https://www.mail-archive.com/pgsql-hackers@lists.postgresql.org/msg95584.html
commit 41c6a5bec25e720d98bd60d77dd5c2939189ed3c
Date:   Fri May 21 14:03:53 2021 -0400
Restore the portal-level snapshot after procedure COMMIT/ROLLBACK.
And quote the release note:
> Some extensions may attempt to execute SQL code outside of any Portal.
> They are responsible for ensuring that an outer snapshot exists before
> doing so. Previously, not providing a snapshot might work or it might
> not; now it will consistently fail with “cannot execute SQL without an
> outer …
> Ensure that an active outer snapshot exists prior to executing SPI

- src/test/isolation2/input/parallel_retrieve_cursor/concurrency.source
- src/test/isolation2/output/parallel_retrieve_cursor/concurrency.source
Temporary dev pipeline is green: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-reset_guc_6x
> RESET newly added GUC to pass binary swap tests

- src/backend/cdb/cdbsubselect.c
- src/backend/optimizer/plan/subselect.c
- src/backend/optimizer/util/paramassign.c
- src/include/optimizer/subselect.h
- src/test/regress/expected/bfv_catalog.out
- src/test/regress/expected/gporca.out
- src/test/regress/expected/qp_subquery.out
Fix bug of multi-level correlated subplan with message in planner.
> ERROR:  correlated subquery with skip-level correlations is not supported
GPDB could support one-level correlated subquery by adding broadcast + result(param filter). 
like query below, add broadcast motion below param filter, and it's a easy way to support
correlated subplan in MPP-panner.
```
postgres=# explain(verbose on, costs off) select a, (select sum(b) from t2 where c = t1.c) from t1;
QUERY PLAN                                  
-----------------------------------------------------------------------------
Output: t1.a, ((SubPlan 1))
->  Seq Scan on public.t1
Output: t1.a, (SubPlan 1)
SubPlan 1
->  Aggregate
Output: sum(t2.b)
->  Result
Output: t2.b, t2.c
Filter: (t2.c = …
```
> FIX bug of multi-level correlated subquery

- src/backend/cdb/cdbsubselect.c
- src/backend/optimizer/plan/subselect.c
- src/include/optimizer/subselect.h
- src/test/regress/expected/bfv_catalog.out
- src/test/regress/expected/gporca.out
- src/test/regress/expected/qp_subquery.out
Fix bug of multi-level correlated subplan with message in planner.
> ERROR:  correlated subquery with skip-level correlations is not supported
GPDB could support one-level correlated subquery by adding broadcast + result(param filter). 
like query below, add broadcast motion below param filter, and it's a easy way to support
correlated subplan in MPP-panner.
```
postgres=# explain(verbose on, costs off) select a, (select sum(b) from t2 where c = t1.c) from t1;
QUERY PLAN                                  
-----------------------------------------------------------------------------
Output: t1.a, ((SubPlan 1))
->  Seq Scan on public.t1
Output: t1.a, (SubPlan 1)
SubPlan 1
->  Aggregate
Output: sum(t2.b)
->  Result
Output: t2.b, t2.c
Filter: (t2.c = …
```
> FIX multi-level correlated subquery bug 6X  backport

- src/backend/cdb/dispatcher/cdbdisp_async.c
- src/test/regress/input/dispatch.source
- src/test/regress/output/dispatch.source
In `checkDispatchResult()`, we flush out the buffer when something are not fully dispatched to QEs:
https://github.com/greenplum-db/gpdb/blob/f90428b433203893fa12dca78334ed4fd6b473b5/src/backend/cdb/dispatcher/cdbdisp_async.c#L519-L533
The `pqFlush()` set `sock = -1` when the connection is broken. And no `Assert()` in product code, so this fd (sock==-1) will be added in the poll array:
https://github.com/greenplum-db/gpdb/blob/f90428b433203893fa12dca78334ed4fd6b473b5/src/backend/cdb/dispatcher/cdbdisp_async.c#L538-L542
Then `poll()` it (fd==-1) later, it causes an infinite hang, and we already have user cases of it.
Fix it is easy: skip to add these fds to poll array. This issue also exists in main branch, ported: https://github.com/greenplum-db/gpdb/pull/14521
> [6X] Skip invalid socks in checkDispatchResult()

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/bin/lib/gpconfigurenewsegment
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Issue**: If the cluster never has mirrors, PgBasebackUp call will fail with create-slot option False.
To add the mirror as part of fall back we were making the PgBasebackUp call with create-slot option True.
Fixme was added to fix this code structure.
**Fix**: We did few spike to check if the slot is present and create-slot is true can it reuse the existing slot.
but there is no support for that. As a optimal solution we are now
droping the available existing slot and creating new if the create-slot
option is provided as True. Which will also help to clean up the orphaned slot.
**Implementation details:**
- Added class PgReplicationSlot which has utility functions to check if the slot exists and dropping the slot.
- Added unit test cases for the class PgReplicationSlot covering all …
> Fixme: basebackup slot creation

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
Before commit e8b4943178e2d7356149ce6791862737274d8de0, Orca falls back to planner with the error `Lookup of object 0.0.0.0 in cache failed` (only when assert is disabled) or `CTranslatorDXLToExpr.cpp:498: Failed assertion: pdxlcoldesc->MdidType()->IsValid()` (when assert is enabled),  which is actually a bug that we should fix. Commit e8b4943178e2d7356149ce6791862737274d8de0 assumes that when fetching the metadata the midid is always valid, causing Orca errors out (`type with OID 0 does not exist`) when it hits the bug. This patch doesn't try to fix the bug (we can do it in future), but reinstates the validity check of Oid.
We can't enable trace fallback flag, because fallback messages are different with assert disabled/enabled.
> Fix cache lookup failed for type 0

- gpMgmt/bin/gpexpand
- gpMgmt/bin/gpmovemirrors
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
gprecoverseg, gpmovemirrors should show warning and gpexpand should raise an exception if there is already a running instance of pg_basebackup for the segment that needs to be recovered/moved.
Fix:
Create a list segments_with_running_basebackup of segment dbids for which pg_basebackup is running and while creating the recovery triplets, check if the segment to be recovered/moved/added(expansion segments) is already present in the segments_with_running_basebackup list. If that's the case give warning or raise exception and terminate the utility execution.
* Behaviour of gprecoverseg - Warning message is logged containing list of segment contentIds with running basebackup and for the rest of the segments gprecoverseg will proceed with recovery
* Behaviour of gpmovemirrors - Warning message …
> [6X] Warn if any segment has a running basebackup

- src/backend/gporca/concourse/test_orca_pipeline.yml
These are similar changes to the PR pipeline. Currently this pipeline is failing when using the centos7 image.
> Update Orca test pipeline to use rhel8

- src/backend/optimizer/util/clauses.c
- src/backend/optimizer/util/predtest.c
- src/include/optimizer/clauses.h
- src/test/regress/expected/gporca.out
When checking relation exclusion by constraints, GPDB performs further
checks that if the predicate is of format expr=constant, try to evaluate
the clause by replacing every occurrence of expr with the constant. But,
this does not work for all cases.
the related issues are as follows:
https://github.com/greenplum-db/gpdb/issues/8582
https://github.com/greenplum-db/gpdb/issues/10287
remove simple_equality_predicate_refuted to fix wrong results caused by
over-eager constraint exclusion.
> fix wrong results caused by over-eager constraint exclusion

- src/backend/commands/resgroupcmds.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/resgroup.h
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/input/resgroup/resgroup_cpuset.source
- src/test/isolation2/output/resgroup/resgroup_cpuset.source
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
New SYNTAX of resource group cpuset for different master and segment
Using syntax like cpuset="1;3-4" could different cpuset of master and segment by semicolon.  For example,
if we define cpuset="1;3-4", then master will use the first  cpu core, segments will use third  and fourth core.
CREATE and ALTER resource group support this new syntax.
```
postgres=# CREATE RESOURCE GROUP rg1 WITH (cpuset='1;2-3');
CREATE RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset 
-----------+--------
rg1       | 1;2-3
(1 row)
postgres=# ALTER resource group rg1 SET cpuset '4;5-6';
ALTER RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset …
```
> NEW SYNTAX for resource group cpuset

- src/test/regress/input/aocs.source
- src/test/regress/output/aocs.source
Simply add one test case and adjust the test a little bit. This is originally for a 6X issue #14510. The issue only existed in 6X. But we'll follow the convention to address main branch first.
> Add test for pg_attribute_encoding entries with various AOCS table creation syntax

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
- src/include/gpopt/gpdbwrappers.h
- src/include/gpopt/translate/CTranslatorScalarToDXL.h
- src/test/regress/expected/domain.out
- src/test/regress/expected/domain_optimizer.out
- src/test/regress/sql/domain.sql
Prior to this PR, while translating constant values for text related
domains like char, bpchar and name ORCA was calling the incorrect
hashing function. This lead to `data corrupt` error while Query to DXL
translation in ORCA. This PR fixes that issue by checking for the
basetype of such domain types and calling the corresponding hashing
function.
Fixes issue: https://github.com/greenplum-db/gpdb/issues/14155
> ORCA: Fix data corruption error for text related domain types

- src/backend/access/transam/xlog.c
- src/bin/pg_basebackup/t/010_pg_basebackup.pl
In GPDB 6X, WAL segment files that are force switched (e.g. pg_switch_wal) will mostly zero out the rest of the WAL segment file (with some headers interleaved) while pg_basebackup’s WAL receiver simply just writes the records it receives in a pre-allocated zero’d file and just stops when the replication connection is closed abruptly. This causes the switched files on the primary and mirror to be different(even though they contain the same records).
This was [accidentally fixed in PG11](https://github.com/greenplum-db/gpdb/commit/4a33bb59dfc33566f04e18ab5e1f90b8e7461052) by simply completely zeroing out the end of switched WAL segment files. Original postgres thread that inspired the code change: also https://www.postgresql.org/message-id/flat/579297F8.7020107%40anastigmatix.net
This PR …
> Ensure that WAL pages skipped by a forced WAL switch are zero-filled. 

- src/backend/commands/analyze.c
- src/backend/commands/analyzefuncs.c
- src/backend/tsearch/ts_typanalyze.c
- src/backend/utils/adt/rangetypes_typanalyze.c
- src/include/commands/vacuum.h
- src/test/regress/expected/analyze.out
- src/test/regress/expected/incremental_analyze.out
This change impacted some other components unexpectedly and caused plan changes so it needs more work before being ready to release.
This reverts commit cbc9062a384e6827cfd3fb43818727dc01a41a1f.
> Revert "Consider oversized rows for stawidth computation"

- src/backend/parser/gram.y
- src/test/regress/input/aocs.source
- src/test/regress/output/aocs.source
Fix issue #14510. Always passing the implicit 'true' argument for 'appendonly' or 'appendoptimized' in case they are not handled properly anywhere in parse analysis.
Note that, we might also fix transofrmCreateStmt->is_aocs but we choose to not touch anywhere else in code. is_aocs() will be gone in 7X anyway.
The 7X PR: https://github.com/greenplum-db/gpdb/pull/14519 which just adds test coverage.
> [6X] Always add 'true' to 'appendonly'/'appendoptimized' reloptions

- src/backend/commands/explain.c
- src/backend/executor/nodeSort.c
- src/test/regress/expected/explain_analyze.out
- src/test/regress/expected/explain_analyze_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/explain_analyze.sql
The execution sequence of explain analyze is as follows:
ExecutorStart
ExecutorRun                                -->dispatch plan to QEs
cdbdisp_checkDispatchResult  -->wait all QEs finished
ExplainPrintXXX                          -->print explain infos
ExecutorEnd                                -->reThrow QE's error, etc.; 
When we execute explain analyze, we might not receive stats from QEs, If some QEs hit errors.
But, In ExplainPrintXXX we will use these stats and print explain info, if we forget to do null
judgment, this may hit a null pointer exception. Finally, in ExecutorEnd we reThrow the error from QE.
If some QE throws errors, we reThrow the error before executing ExplainPrintXXX.
> If QEs hit errors in explain analyze, rethrow the error before ExplainPrintPlan

- src/backend/commands/explain.c
- src/backend/executor/nodeSort.c
- src/test/regress/expected/gp_explain.out
- src/test/regress/expected/gp_explain_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/gp_explain.sql
The execution sequence of explain analyze is as follows:
ExecutorStart
ExecutorRun                              -->dispatch plan to QEs
cdbdisp_checkDispatchResult -->wait all QEs finished
ExplainPrintXXX                         -->print explain infos
ExecutorEnd                                -->reThrow QE's error, etc.;
When we execute explain analyze, we might not receive stats from QEs, If some QEs hit errors.
But, In ExplainPrintXXX we will use these stats and print explain info, if we forget to do null
judgment, this may hit a null pointer exception. Finally, in ExecutorEnd we reThrow the error from QE.
If some QE throws errors, we reThrow the error before executing ExplainPrintXXX.
backport from: fc885ec747bef7896ab115b5f3abb0de63daea89
> [6x backport] If QEs hit errors in explain analyze, rethrow the error before ExplainPrintPlan

- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/executor/execMain.c
- src/backend/utils/resgroup/cgroup.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/cgroup.h
My linker complains that there's multiple definition of cgroupOpsRoutine and cgroupSystemInfo.
We should declare the variable in header file with an extern tag and initialize it in one of the .c file.
Since cgroupSystemInfo and cgroupOpsRoutine are required on multiple platforms, I initialize them in resgroup.c which is compiled to object files on every platform while cgroup.c is only compiled on Linux platform.
> [7X] Fix multiple definition error when linking gpdb.

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/ltree.html.md
- gpdb-doc/markdown/ref_guide/toc.md
backport of https://github.com/greenplum-db/gpdb/pull/14494 for 6X_STABLE branch.  the only difference is we xref to postgres v9.4 version of the docs.
> docs - add content for ltree module (6x)

- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/data/dxl/minidump/CTAS_OrderedAgg_multiple_cols.mdp
- src/backend/gporca/data/dxl/minidump/HAWQ-TPCH-Stat-Derivation.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libgpopt/include/gpopt/cost/ICostModel.h
- src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
- src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
- src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
- src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/qp_skew.out
- src/test/regress/expected/qp_skew_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/qp_skew.sql
**Penalize hash join in case of skew**
**Issue:**
ORCA generates plan with hash redistribution when data is highly skewed,
making one segment the bottleneck in execution
**Root cause:**
Currently skew is only taken into account when the number of
distinct value is less than the segment count. This over simplifies the scenario
where skew may arise.
**Solution:**
We compute skew ratio using sampled statistics. The sampling rate of each bucket
is proportional to the bucket frequency, i.e, the higher the bucket frequency,
the more datum we sample from that bucket.
We employ deterministic sampling algorithm by always starting with the lower
bound, then the high bound, medium, quarter, three quarters, one eighth, three
eighths, etc. In normalized terms, 0, 1, 0.5, 0,25, 0.75, 0.125, 0.375, etc. …
> Penalize skewed hash join

- concourse/pipelines/templates/gpdb-tpl.yml
When run by `gen_pipeline.py -t prod --directed`, it will error out by missing image artifact source: gpdb7-rhel8-build
> [Releng] Fix missing image artifact source: gpdb7-rhel8-build

- src/backend/executor/execExpr.c
- src/backend/executor/nodeAgg.c
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
Fix aggnode crash in executor caused by ORCA plan
origin issue: https://github.com/greenplum-db/gpdb/issues/13994
when we force optimizer_force_multistage_agg to true, orca will
generate multistage agg plan for DQA, ex sql below.
explain (verbose, costs off) select count(distinct b), sum(c) from t1;
```
QUERY PLAN                                               
--------------------------------------------------------------------------------------------------------
Aggregate
Output: count(b), sum(c)
->  Gather Motion 3:1  (slice1; segments: 3)
Output: b, (PARTIAL sum(c))
->  Partial HashAggregate
Output: b, PARTIAL sum(c)
Group Key: t1.b
->  Redistribute Motion 3:3  (slice2; segments: 3)
Output: b, (PARTIAL sum(c))
Hash Key: b
->  Streaming Partial HashAggregate
Output: b, PARTIAL sum(c) …
```
> Fix crash of AggNode in executor casued by ORCA plan

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14067.
> docs - add reference info for new gp_print_create_gang_time guc

- gpdb-doc/markdown/install_guide/platform-requirements.html.md
python version upgrade for next greenplum 6.x release.
these were the only references to the complete (3 digit) version in the docs.  there are several references to 2.7.
> docs - greenplum bundled with python 2.7.18

- gpdb-doc/markdown/best_practices/tuning_queries.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/SELECT.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14149.  add a note identifying the max number of CUBE grouping columns in the two doc locations where CUBE is mentioned.
> docs - CUBE supports 12 elements max (6x)

- src/bin/pg_dump/pg_dumpall.c
Commit 99dc08f introduced a regression where dumpTablespaces will no
longer choose the correct SQL to dump tablespaces on 5X.
This conditional is removed in 7X. No 7X fix needed.
> [6X] Fix pg_dumpall to dump 5X tablespaces correctly

- src/backend/cdb/dispatcher/cdbdispatchresult.c
- src/backend/cdb/dispatcher/test/cdbdispatchresult_test.c
Use the correct hashing function oid_hash rather than the default string_hash when summing AO tuple counts for pg_aoseg entries.
This fixes an issue where multiple aorelid's can collide resulting in the same hash table entries. This lead to updating the wrong pg_aoseg entries on the coordinator segment.
This resulted in several issues:
1) Dangling pg_aoseg entries.
- This would result in pg_upgrade failing with: `could not open Append-Only segment file ""base/16410/20863.1665"": No such file or directory"`
2) Flakey tests
- These failing tests helped track down the root cause and fix the underlying issue.
- The ICW tests would intermittently fail on the pg_upgrade check for "AO/CO parent partitions with pg_aoseg entries".
Pipeline: …
> [6X] use correct hash function when summing AO tuple counts

- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
Commit 0f4af19b71f2f31acd28c39d0d0a865cbf1d3bab added this test, but the `analyze` statement exposed an unrelated issue and caused CI to fail. We should explicitly analyze tables to reduce runtime in tests anyway.
> Fix gp_dqa test to explicitly analyze tables

- contrib/formatter_fixedwidth/scripts/multi_fields_generator.sh
- contrib/formatter_fixedwidth/scripts/single_field_generator.sh
readable_query32 and readable_query33 take ~500 seconds without this commit and less than 1 second with it.
1, don't `echo | awk`, just use `printf` to generate the dataset.
2, reduce the dataset size to one-fifth.
> Speed up formatter_fixedwidth's test cases

- gpdb-doc/markdown/admin_guide/parallel_retrieve_cursor.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- src/backend/utils/misc/guc_gp.c
docs for https://github.com/greenplum-db/gpdb/pull/14051.
not sure if i got the set classifications correct.
(will backport to 6X_STABLE in a separate PR, as the parallel retrieve cursor functionality is a module in 6X.)
> docs - add content for new gp_max_parallel_cursors guc

- src/backend/executor/nodeDynamicBitmapHeapscan.c
- src/backend/executor/nodeDynamicSeqscan.c
- src/include/nodes/execnodes.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/expected/qp_dropped_cols.out
- src/test/regress/expected/qp_dropped_cols_optimizer.out
- src/test/regress/sql/gporca.sql
- src/test/regress/sql/qp_dropped_cols.sql
[PR to master](https://github.com/greenplum-db/gpdb/pull/14505)
The following scenario produces internal error:
```sql
CREATE TABLE ds_part ( a INT, b INT, c INT) PARTITION BY RANGE(c)( START(1) END (10) EVERY (2), DEFAULT PARTITION deflt);
CREATE TABLE non_part1 (c INT);
CREATE TABLE non_part2 (e INT, f INT);
INSERT INTO ds_part SELECT i, i, i FROM generate_series (1, 1000)i; 
INSERT INTO non_part1 SELECT i FROM generate_series(1, 100)i; 
INSERT INTO non_part2 SELECT i, i FROM generate_series(1, 100)i;
SET optimizer_enforce_subplans TO ON;
analyze ds_part;
analyze non_part1;
analyze non_part2;
EXPLAIN ANALYZE SELECT * FROM ds_part, non_part2 WHERE ds_part.c = non_part2.e AND non_part2.f = 10 AND a IN ( SELECT b + 1 FROM non_part1);
```
```
ERROR:  Unexpected internal error …
```
> Fix failure when DynamicSeqScan has a subPlan

- src/backend/access/transam/test/xlog_test.c
- src/backend/access/transam/xlog.c
- src/backend/replication/slot.c
- src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
- src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
- src/test/isolation2/sql_isolation_testcase.py
Previously, commit https://github.com/greenplum-db/gpdb/commit/185c7d796f9cfd431cea69c05dc06932faa0300b as part of PR 11989 added extra protection
for wal files for the following scenario:
- The common CHECKPOINT record of the source and the target segment
locates in an older wal file than the one that contains the
divergence record. AND
- More than one CHECKPOINT happened on the failed primary which
proceed the divergence LSN.
The previous fix was to have an in-memory variable that keeps track of
the last CHECKPOINT prior to the smallest replication slot's
restart_lsn. However, this fix only works if the segment has not gone
through shutdown and restart.
This commit prevents CHECKPOINT from removing wal files if the last
CHECKPOINT record pointer prior to the replication slot minimum lsn …
> Fix missing wal files for pg_rewind

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
minimal docs, just removes CUBE from the list of things GPORCA does not support.  TBD if other docs are required.
> docs - gporca supports CUBE

- src/backend/catalog/aclchk.c
- src/test/regress/expected/privileges.out
- src/test/regress/sql/privileges.sql
This one should be closing https://github.com/greenplum-db/gpdb/issues/14446
Seems to be an issue only for 6X as far as I`ve checked. There was a bug in objectNamesToOids which completely ignored(eliminated) not partitioned tables if partitioned tables are also present in the same statement.
> Fix GRANT/REVOKE when some tables are partitioned and some are not

- src/backend/parser/parse_cte.c
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/expected/with.out
- src/test/regress/sql/gp_recursive_cte.sql
> Remove handle RangeSubselect in checkWellFormedRecursionWalker.

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
This removes FIXMEs for the compute_xid_horizon_for_tuples() API, which
was introduced in 558a9165e08.
This API is used to compute what snapshots to conflict with when
replaying WAL records for page-level index vacuums. Page-level index
vacuums don't even arise for AO/CO tables today due to absence of HOT.
Thus it is perfectly fine to leave this unimplemented.
Details:
(1) The amgettuple() routine for index AMs can optionally kill off
tuples if they are found dead in the underlying table scan. This is done
with IndexScanDesc->kill_prior_tuple. For examples: see btgettuple(),
hashgettuple() and gistgettuple().
(2) The index AMs typically have a killitems function (like
_bt_killitems()), which among other things sets a garbage flag on the
index page (like BTP_HAS_GARBAGE)
(3) Afterwards, if …
> ao/co: Clarify compute_xid_horizon_for_tuples API

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
In d0f8614d1f1b18eb9101bb18b8e9192709bd670c, we removed an if statement that was previously catching and falling back to planner if a table AM was not recognized. Add this back, as there are cases of an unrecognized AM and otherwise we'll crash.
> Fix relcache lookup in Orca when selecting from sequence

- src/backend/commands/explain.c
- src/backend/commands/explain_gp.c
- src/include/commands/explain.h
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
Print summarized JIT instrumentation from all QEs. For example:
```
postgres=# explain analyze select * from test limit 10;
QUERY PLAN
----------------------------------------------------------------------------------------------------------------------------------------------
Limit  (cost=0.13..0.40 rows=10 width=4) (actual time=6.178..6.335 rows=10 loops=1)
->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.13..0.93 rows=30 width=4) (actual time=0.534..0.593 rows=10 loops=1)
->  Limit  (cost=0.13..0.53 rows=10 width=4) (actual time=1.076..1.325 rows=10 loops=1)
allstat: seg_firststart_total_ntuples/seg0_7.512 ms_1.325 ms_10/seg1_4.496 ms_4.292 ms_10/seg2_5.389 ms_2.369 ms_10//end
->  Seq Scan on test  (cost=0.00..1.33 rows=33 width=4) (actual time=0.035..0.104 rows=10 loops=1) …
```
> Collect distributed instruments of JIT to the client

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
This commit confirms that the tuple_lock API can be safely left
unimplemented for AO/CO tables. See below for details:
(1) UPSERT: ExecOnConflictUpdate() calls this, but clearly upsert is not
supported for AO/CO tables.
(2) DELETE and UPDATE triggers: GetTupleForTrigger() calls this, but
clearly these trigger types are not supported for AO/CO tables.
(3) Logical replication: RelationFindReplTupleByIndex() and
RelationFindReplTupleSeq() calls this, but clearly we don't support
logical replication yet for GPDB.
(4) For DELETEs/UPDATEs, when a state of TM_Updated is returned from
table_tuple_delete() and table_tuple_update() respectively, this API is
invoked.  However, that is impossible for AO/CO tables as an AO/CO tuple
cannot be deleted/updated while another transaction is updating it …
> ao/co: Clarify tuple_lock API

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
Some of the gpmovemirror and gprecoverseg tests seen failing when waiting for segment to come online or waiting for progress file (recovery_progress.file) to get created sometime which is taking longer. Enhancing timeout for such cases.
Ran 6X and 6x-without-asserts pipeline on prod instance and is green. 
Added a step in gprecoverseg and gpmovemirrors test cases to make sure that pg_basebackup is finished running.
Cherry-pick of : https://github.com/greenplum-db/gpdb/pull/14589
> Test fix failure by adding timeout and adding some checks 

- configure
- configure.in
clang-12 has introduced -Wcompound-token-split-by-macro, that is causing
a large amount of warnings when building PL/Perl because of its
interactions with upstream Perl.  This commit adds one -Wno to CFLAGS at
./configure time if the flag is supported by the compiler to silence all
those warnings.
Upstream perl has fixed this issue, but it is going to take some time
before this is spread across the buildfarm, and we have noticed that
some animals would be useful with an extra -Werror to help with the
detection of incorrect placeholders (see b0cf544), dangomushi being
one.
Reviewed-by: Tom Lane
Discussion: https://postgr.es/m/YYr3qYa/R3Gw+Sbg@paquier.xyz
Backpatch-through: 10
(cherry picked from commit 9ff47ea414c4e6ace347fc4e59866e38b9bbceaf)
> Clean up compilation warnings coming from PL/Perl with clang-12~

- src/backend/utils/misc/guc_gp.c
The value of guc gp_explain_jit should be set to ON by default. As mentioned in previous [PR 14354](https://github.com/greenplum-db/gpdb/pull/14354)
> fix default value of guc gp_explain_jit to ON

- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/data/dxl/minidump/HAWQ-TPCH-Stat-Derivation.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libgpopt/include/gpopt/cost/ICostModel.h
- src/backend/gporca/libgpopt/include/gpopt/engine/CHint.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
- src/backend/gporca/libgpopt/src/optimizer/COptimizerConfig.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerHint.cpp
- src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
- src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/qp_skew.out
- src/test/regress/expected/qp_skew_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/qp_skew.sql
**Penalize hash join in case of skew**
**Issue:**
ORCA generates plan with hash redistribution when data is highly skewed,
making one segment the bottleneck in execution
**Root cause:**
Currently skew is only taken into account when the number of
distinct value is less than the segment count. This over simplifies the scenario
where skew may arise.
**Solution:**
We compute skew ratio using sampled statistics. The sampling rate of each bucket
is proportional to the bucket frequency, i.e, the higher the bucket frequency,
the more datum we sample from that bucket.
We employ deterministic sampling algorithm by always starting with the lower
bound, then the high bound, medium, quarter, three quarters, one eighth, three
eighths, etc. In normalized terms, 0, 1, 0.5, 0,25, 0.75, 0.125, 0.375, etc. …
> Penalize redistributed hash join in case of skew

- src/backend/executor/execUtils.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
Executing a query that doesn't fetch all tuples from external scan that execute
program on coordinator leads to the next error:
ERROR:  external table table_master command ended with SHELL TERMINATED by
signal SIGPIPE (13)
DETAIL:  Command: execute:(echo foo; sleep 1; echo bar)
There are several cases when gpdb ends unfinished plan: extended protocol,
cursors. Greenplum communicate with shell command by pipe, it closes pipe while
shell command steel sends results. And SIGPIPE happens here. In such cases
if external web table is executed on segments, then it uses squelching
mechanics, that provides a separate way to handle unfinished yet plan nodes and
simply ignore SIGPIPE for externalScan. But the squelching doesn't execute
for master-only plans on coordinator. So the solution is …
> ADBDEV-2947: SIGPIPE during fechine external table data by extended protocol

- src/backend/commands/resgroupcmds.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/resgroup.h
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/input/resgroup/resgroup_cpuset.source
- src/test/isolation2/output/resgroup/resgroup_cpuset.source
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
New SYNTAX of resource group cpuset for different master and segment
Using syntax like cpuset="1;3-4" could different cpuset of master and segment by semicolon.  For example,
if we define cpuset="1;3-4", then master will use the first  cpu core, segments will use third  and fourth core.
CREATE and ALTER resource group support this new syntax.
```
postgres=# CREATE RESOURCE GROUP rg1 WITH (cpuset='1;2-3');
CREATE RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset 
-----------+--------
rg1       | 1;2-3
(1 row)
postgres=# ALTER resource group rg1 SET cpuset '4;5-6';
ALTER RESOURCE GROUP
postgres=# select groupname, cpuset from gp_toolkit.gp_resgroup_config where groupname = 'rg1';
groupname | cpuset …
```
> 【6X】NEW SYNTAX for resource group cpuset

- concourse/vars/without_asserts_common_prod.yml
Change GP7 `gpdb_main_without_asserts` pipeline compilation job (`compile_gpdb_rhel8`) to use `gpdb_src` (every commit) resource trigger instead of the once per day `reduced-frequency-trigger` trigger.
The pipeline impacted is:
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main_without_asserts
When this change is committed, the pipeline will need to be re-set.
> Perform GP7 `without_asserts` pipeline runs on `gpdb_src` trigger.

- src/backend/executor/execMain.c
**This PR is a following fix after #12694, as the `queryDesc->estate` may be NULL in the catch block, which may cause a PANIC.**
According to a reported error in PolicyEagerFreeAssignOperatorMemoryKB makes query end without calling GPDB hooks https://github.com/greenplum-db/gpdb/issues/12690 , the code path in standard_ExecutorStart didn't handle exception in PolicyAutoAssignOperatorMemoryKB and PolicyEagerFreeAssignOperatorMemoryKB calling, which may cause the OOM exception not handled in standard_ExecutorStart but throw to upper PortalStart methods, while there is also exception handling machanism in PortalStart but GPDB hooks will not be called because of portal->queryDesc will be NULL in certain transation states. This PR fixed this issue.
> Fix gpdb hooks calling in PortalStart in case of exceptions caught.

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
In explain_format test, The values of EXPLAIN's memory fields should be ignored.
The matchsub rules already exists but not ported to support JSON format.
Lacking of them, new test cases imported by PR #14360 would fail.
This commit set the matchsub rules for JSON format.
The failure fixed by this PR: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main_without_asserts/jobs/icw_planner_rhel8/builds/447
> fix regression test: ignore memory values in JSON-ed output of EXPLAIN

- src/backend/parser/gram.y
- src/test/regress/expected/role.out
- src/test/regress/sql/role.sql
Commit bc08de1cc5bb introduced ONLY keyword for GRANT/REVOKE. However there's an issue in the grammar where if the table list starts with a table with ONLY, it could not contain more tables with ONLY. Fixing it and adding test cases for all possible syntax.
Thanks to @lisakowen who found this in https://github.com/greenplum-db/gpdb/pull/14615
> Fixing ONLY keyword for multiple tables in GRANT/REVOKE

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- gpdb-doc/markdown/ref_guide/modules/gp_parallel_retrieve_cursor.html.md
- gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
- src/backend/utils/misc/guc_gp.c
docs for https://github.com/greenplum-db/gpdb/pull/14146.  this is basically a backport of https://github.com/greenplum-db/gpdb/pull/14548 for 6X_STABLE.  the guc reference info is the same.  same updates to guc_gp.c. changes:
- parallel cursor functionality is a module in 6X_STABLE.  
- also updated the greenplum_fdw module docs to use "local" and "remote", which involved changing some references of source -> local.
> docs - add content for new gp_max_parallel_cursors guc (6x)

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14192.  add reference info for new gporca guc optimizer_skew_factor.
this will be backported to 6X_STABLE.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/newguc/greenplum-database/GUID-ref_guide-config_params-guc-list.html#optimizer_skew_factor
> docs - add ref info for new optimizer_skew_factor guc

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/parser/analyze.c
- src/test/regress/input/uao_dml/uao_dml.source
- src/test/regress/output/uao_dml/uao_dml.source
We don't support speculative insert (INSERT ON CONFLICT) for AO/CO tables yet.
This commit does two things:
(1) Confirms that its okay to keep the speculative insert APIs unimplemented, by removing the FIXMEs and adding ereport().
(2) Instead of relying on the ERROR at the table AM layer, it introduces a check at the parse analysis stage to perform the ban. This is important as we can't rely on the table AM layer always. For instance, with DO NOTHING, if there is no conflict, the table AM routine is invoked. However, if there is a conflict, then the routine doesn't get invoked and the customer would see:
INSERT INTO spec_insert VALUES(1, 3) ON CONFLICT(i) DO NOTHING; INSERT 0 0
This would lead to a false impression that it is supported. So, we ban it at the parse analysis stage.
> ao/co: Ban speculative insert in parse analysis

- src/bin/pg_dump/pg_dump.c
Commit a452dbaef44059e83e5f5d3f5abb98ef754baccb introduced a regression
where pg_dump is now searching for materialized views and foreign tables
to dump. These objects do not exist on 5X and should not be considered
as dumpable objects. This is especially conflicting because relkind 'm'
is aovisimap table in 5X whereas in 6X it is materialized view.
This issue was caught by the gpupgrade tests where it was found that the
extra aovisimap entries due to the regression was changing the
dependency sorting expectations.
gpup: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpupgrade:dont-dump-mview-and-ftables
6x:   https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/dont-dump-mview-and-ftables
> [6X] Do not consider certain relkinds when dumping 5X cluster

- src/backend/cdb/cdbgroupingpaths.c
- src/backend/optimizer/plan/planner.c
- src/backend/optimizer/plan/setrefs.c
- src/include/nodes/nodes.h
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/expected/partition_aggregate.out
- src/test/regress/sql/gp_dqa.sql
Support intermediate aggregate in planner on GPDB7. 
**_What is DQA?_**
DQA(Distinct-Qualified Aggregates) is a complex optimization  in MPP planner, which used to stand for Count(Distinct xxx) in query. We cannot use hashagg for DQA in postgresql and Greenplum, which is a historic restriction from Executor. However, sortagg has a bad performance especially in MPP system because of too many duplicate tuple involved. So we need to implement double-hashagg strategy to solve this problem.   
SortAgg case
Duplication on t1 will result in base performance for whole plan.
```
postgres=# explain(costs off) select count(Distinct a) from t1 group by c;
QUERY PLAN                             …
```
> Support intermediate aggregate in planner

- src/test/regress/.gitignore
- src/test/regress/input/gpcopy.source
- src/test/regress/output/gpcopy.source
`\!rm` to test if they are located in the right directory.
> Remove the generated 'stdin' and 'stdout' files

- src/backend/cdb/cdbgroupingpaths.c
We used to have the same logic between `create_grouping_paths()` and `cdb_create_multistage_grouping_paths()` to determine if the input is hashable / sortable.
```
can_sort = grouping_is_sortable(parse->groupClause);
can_hash = (parse->groupClause != NIL &&
agg_costs->numPureOrderedAggs == 0 &&
grouping_is_hashable(parse->groupClause));
```
The logic in `create_grouping_paths()` has been changed by commit b5635948ab165b6070e7d05d111f966e07570d81 because if we have grouping sets, we might be able to sort / hash some but not all of them.
```
can_sort = (gd && gd->rollups != NIL)
|| grouping_is_sortable(parse->groupClause);
can_hash = (parse->groupClause != NIL &&
parse->groupingSets == NIL &&
agg_costs->numOrderedAggs == 0 &&
(gd ? gd->any_hashable : …
```
> Remove GPDB_12_MERGE_FIXME in cdb_create_multistage_grouping_paths()

- gpdb-doc/markdown/ref_guide/extensions/bgworker.html.md
- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
diskquota 2.1 includes some new gucs, among other features and changes.
questions:
1.  the new content i added references max_worker_processes server configuration parameter, but this guc is not documented.  should it be?
2. upgrade - not sure if i got the procedures correct.  are the 2.0.x diskquota libraries available with 2.1.0?
3. hard limit limitation - not sure what "that each table file doesn’t need to extend" means.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/dq210/greenplum-database/GUID-ref_guide-modules-diskquota.html
> docs - updates for diskquota version 2.1.0

- gpdb-doc/markdown/admin_guide/external/g-s3-protocol.html.md
untrusted protocols can be accessed only by superusers.  if create as TRUSTED, all users can access.
> docs - mention creating s3 protocol as TRUSTED

- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/gporca/data/dxl/minidump/DisableRedistributeHashJoin.mdp
- src/backend/gporca/data/dxl/minidump/DiscardRedistributeHashJoin.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
- src/backend/gporca/server/CMakeLists.txt
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
Add a GUC `optimizer_discard_redistribute_hashjoin` to control redistribute
hashjoin.
If any one of HashJoin's children operators is RedistributeMotion, this plan
alternative will be given MAX cost, hence it will not be picked by optimizer.
Default value is `OFF`.
> Add a GUC to discard redistribute hashjoin for Orca

- src/backend/executor/nodeModifyTable.c
- src/test/regress/expected/update.out
- src/test/regress/expected/update_gp.out
- src/test/regress/expected/update_gp_optimizer.out
- src/test/regress/expected/update_optimizer.out
- src/test/regress/sql/update.sql
- src/test/regress/sql/update_gp.sql
This PR fixes https://github.com/greenplum-db/gpdb/issues/14647. 
---
If the source and destination partitions don't have identical rowtypes (for example, one has dropped columns the other lacks), then the planSlot contents will be different because of that. If the query has a RETURNING list that tries to return resjunk columns out of the planSlot, that is columns from tables that were joined to the target table, we'd get errors or wrong answers. That's because we used the RETURNING list generated for the destination partition, which expects a planSlot matching that partition's subplan.
The most practical fix seems to be to convert the updated destination tuple back to the source partition's rowtype, and then apply the RETURNING list generated for the source partition.  This avoids making …
> Fix bugs in RETURNING in cross-partition UPDATE cases.

- src/backend/gporca/data/dxl/minidump/DeleteMismatchedDistribution.mdp
- src/backend/gporca/data/dxl/minidump/Insert-Parquet-Partitioned-SortDisabled.mdp
- src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution-2.mdp
- src/backend/gporca/data/dxl/minidump/InsertMismatchedDistrubution.mdp
- src/backend/gporca/data/dxl/minidump/LeftJoin-With-Pred-On-Inner2.mdp
- src/backend/gporca/data/dxl/minidump/UpdateDistKeyMismatchedDistribution.mdp
- src/backend/gporca/data/dxl/minidump/UpdateDroppedCols.mdp
- src/backend/gporca/data/dxl/minidump/UpdateNoDistKeyMismatchedDistribution.mdp
- src/backend/gporca/data/dxl/minidump/UpdatePartTable.mdp
- src/backend/gporca/libgpopt/src/xforms/CXformUpdate2DML.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/test/regress/expected/gp_unique_rowid_optimizer.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/expected/update_gp_optimizer.out
If we use Delete or Insert over a partitioned table, we will get a PartitionSelector right under these operators.
```
create table test (i int, j int)
distributed by (i)
partition by range (j) (start (0) end (2) every(1));
create table test1(i int);
explain (costs off)
delete from test
where not exists (
select 1 from test1 where test1.i = test.i
);
QUERY PLAN                                   
--------------------------------------------------------------------------------
Delete
->  Result
->  Partition Selector for test
->  Hash Anti Join
Hash Cond: (test.i = test1.i)
->  Sequence
->  Partition Selector for test (dynamic scan id: 1)
Partitions selected: 2 (out of 2)
->  Dynamic Seq Scan on test (dynamic scan id: 1)
->  Hash
->  Result
->  Seq Scan on test1
Optimizer: Pivotal Optimizer …
```
> Remove PartitionSelector insertion for DML operation

- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
i missed pushing a commit where i removed a step.   doh!
should be backported to 6X_STABLE.
> docs - didnt push a removed diskquota step

- src/backend/access/transam/distributedlog.c
- src/test/isolation2/input/distributed_snapshot.source
- src/test/isolation2/output/distributed_snapshot.source
- src/test/regress/regress_gp.c
Previous fix description
---------
~Previously, it is possible that DistributedLog_AdvanceOldestXmin() tries to advance to the next xid, when e.g. there's no concurrent running procs so that the "globalxmin" remains its initial value which is the next xid. When that happens, we could be truncating the current working DLOG segment, if the next xid happens to be the first one of the next segment.~
~Fixing it now by passing globalxmin-1 (the "latest completed xid") to DistributedLog_AdvanceOldestXmin() in that case. Add a test for the same. Had to move the test file to isolation/input in order to import the regress.so for the test_consume_xids() function we need.~
Updated fix description
----------
In DistributedLog_AdvanceOldestXmin() we advance DLOG's idea of the oldestXmin to the …
> Initialize DLOG's oldestXmin up to the latestCompletedXid+1

- src/backend/commands/indexcmds.c
- src/test/regress/expected/gp_index.out
- src/test/regress/sql/gp_index.sql
The following SQL hits the error "permission denied for schema s" on QE.
CREATE ROLE regress_minimal;
CREATE SCHEMA s;
create table s.t(tc1 int);
alter table s.t owner to regress_minimal;
create index idx on s.t(tc1);
The owner of s is login user, but the owner of s.t is regress_minimal,
when we create index for s.t, we will switch CurrentUserId to regress_minimal,
and we use regress_minimal to establish connection with QE,
regress_minimal does not have the permission of s. 
so check permission failed.
before dispatch stmt to QEs, switching user to login user,
so that the connection to QEs use the same user as the connection to QD.
pass the permission check of schema on QEs.
The above case is ok on main branch, however, failed on 6x_stable branch,
because this is introduced by the commit: …
> fix create index does not pass permission check for schema on QE, if the owner of s.t is not current user

- src/backend/access/transam/distributedlog.c
- src/test/isolation2/input/distributed_snapshot.source
- src/test/isolation2/output/distributed_snapshot.source
- src/test/regress/regress_gp.c
Backport from https://github.com/greenplum-db/gpdb/pull/14650 . No conflict.
PR description
==========
In DistributedLog_AdvanceOldestXmin() we advance DLOG's idea of the oldestXmin to the "globalxmin" value, and also truncate all DLOG segments that only hold xids older than the oldestXmin.
The oldestXmin can be xmax, i.e. the "latestCompletedXid" + 1, when e.g. there's no other concurrent running transactions. However, during postmaster restart we initialize the oldestXmin to be up to only latestCompletedXid. As a result, when we try to advance it again, we could try to access the segment that holds latestCompletedXid, which had been truncated before the restart.
Fixing it now by initializing oldestXmin properly. Add a test for the same. Had to move the test file to isolation/input in …
> [6X] Initialize DLOG's oldestXmin up to the latestCompletedXid+1

- src/backend/utils/time/snapmgr.c
- src/include/utils/snapmgr.h
GetCurrentDistributedSnapshotWithLocalMapping() has been dead since b3f300b9457.
> dsnap: Remove dead function

- src/backend/executor/execTuples.c
- src/backend/utils/cache/relcache.c
- src/test/regress/expected/update.out
- src/test/regress/expected/update_optimizer.out
- src/test/regress/sql/update.sql
Adopt a more consistent policy about what slot-type-specific
getsysattr functions should do when system attributes are not
available.  To wit, they should all throw the same user-oriented
error, rather than variously crashing or emitting developer-oriented
messages.
This closes a identifiable problem in commits https://github.com/greenplum-db/gpdb/commit/a71cfc56bf6013e3ea1d673acaf73fe7ebbd6bf3 and
https://github.com/greenplum-db/gpdb/commit/3fb93103a9fd5182f4f75d6da87dadcb3b36d7b1 (in v13 and v12), so back-patch into those branches,
along with a test case to try to ensure we don't break it again.
It is not known that any of the former crash cases are reachable
in HEAD, but this seems like a good safety improvement in any case.
Discussion: …
> Don't crash on reference to an un-available system column

- contrib/file_fdw/output/file_fdw_optimizer.source
- src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
Note that, commit d0f8614d1f1b18eb9101bb18b8e9192709bd670c enable ORCA to produce plan for foreign table query, but for locking clause on the foreign table, ORCA cann't produce correct remote SQL, which will lose locking clause.
For example, for the query "SELECT * FROM ft1 FOR UPDATE", the ORCA will produce the following plan:
postgres=# explain (verbose) SELECT * FROM ft1 where c1 in (select c1
from ft2 for share) for update;
QUERY PLAN
------------------------------------------------------------------------------------------
Hash Semi Join  (cost=0.00..862.33 rows=1 width=47)
Output: ft1.c1, ft1.c2, ft1.c3, ft1.c4, ft1.c5, ft1.c6, ft1.c7,
ft1.c8
Hash Cond: (ft1.c1 = ft2.c1)
->  Foreign Scan on public.ft1  (cost=0.00..431.04 rows=1000
width=47)
Output: ft1.c1, ft1.c2, ft1.c3, ft1.c4, …
> Fix locking clause on foreign table missing when ORCA is enabled

- src/backend/access/bitmap/bitmapsearch.c
Seems left over debug message by commit 22c1ec81c1ce. It floods the log files unnecessarily, when using bitmap index scans.
Reviewed-by: Bhuvnesh Chaudhary <bhuvnesh2703@gmail.com>
Reviewed-by: Jimmy Yih <jyih@vmware.com>
(cherry picked from commit 2ce4111e20e2404e12982bdf74146541cb1eccb3)
> [backport to 6X] Delete verbose logging of message "fetch bitmap page"

- src/backend/utils/adt/float.c
- src/include/port/solaris.h
- src/test/regress/expected/float8.out
- src/test/regress/expected/point.out
This is a follow-up to the PR https://github.com/greenplum-db/gpdb/pull/12485, and commit on-top to fully align float.c with upstream instead of having any GPDB-specific diff
Commentary from that PR
------
It seems that GPDB faced a glibc bug on RedHat 6 with denormalized numbers and fixed it using two-step conversion in float8in():
text to long double
long double to double after denormalized numbers validation
This differs from PG approach where we rely on libc and make the direct conversion to double. RedHat 6 seems to be an old system and there is no much sense to differ from upstream and have additional performance penalty converting long double to double in a two-step manner and making additional checks.
There is another problem with this code - long double can have problems on some …
> Convert float8 with double instead of long double

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SCHEMA.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_SCHEMA.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_SCHEMA.html.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content.  there didn't appear to be any greenplum-specific info in the gp6 pages.
doc review site  link for ALTER SCHEMA (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-schema/greenplum-database/GUID-ref_guide-sql_commands-ALTER_SCHEMA.html
> docs - update the sql ref pages for ALTER/CREATE/DROP SCHEMA

- gpdb-doc/markdown/install_guide/migrate.html.md
- gpdb-doc/markdown/install_guide/upgrade_intro.html.md
- gpdb-doc/markdown/install_guide/upgrading.html.md
the pxf upgrade topics that exist in the greenplum docs source are specific to greenplum 5 and greenplum 6.  remove references to these topics from main.
how we treat pxf within a greenplum 6->7 upgrade (when this is supported) is still tbd. i am retaining the actual source files for possible reuse/update.
> docs - remove refs to pxf upgrade topics

- gpdb-doc/markdown/pxf/migrate_5to6.html.md.erb
this PR is to fix a bad link.
the topic about migrating pxf when greenplum is migrated from version 5 to version 6.  the step that i changed deals with a user who has installed pxf version 5 in their new greenplum 6 installation.  the link in question directs the user to a non-existent pxf 6 topic, when it should be directing to a pxf v5 documentation topic (which are now all pdfs).  so i removed the link and just called out the steps.
(in practice, not sure how many customers would actually install pxf 5 in their new greenplum 6 cluster when pxf 6.x is now available, but that is a question for another time.)
> docs - fix a bad link in pxf migration docs (6x)

- concourse/pipelines/templates/gpdb-tpl.yml
The code changes is missing for:when run icw jobs, it will use generic tagged worker: icw-worker instead of icw-[os_type]
Also remove the work around for: task clang_tidy has failure: image check failed. Do not need to define the image resource since the core reason is the newly created worker has network issue, and now it is fixed, so no need for this code change
[GPR-1163]
> [Releng] Fixup for use generic icw worker name

- GNUmakefile.in
- contrib/postgres_fdw/.gitignore
- contrib/postgres_fdw/Makefile
- contrib/postgres_fdw/deparse.c
- contrib/postgres_fdw/expected/gp2pg_postgres_fdw.out
- contrib/postgres_fdw/postgres_clean.bash
- contrib/postgres_fdw/postgres_fdw.c
- contrib/postgres_fdw/postgres_setup.bash
- contrib/postgres_fdw/sql/gp2pg_postgres_fdw.sql
- contrib/postgres_fdw/sql/postgres_sql/gp2pg_postgres_init.sql
Now postgres_fdw test for gpdb7 is disabled in pipeline.
This pr is to enable postgres_fdw test for gpdb7.
File gp2pg_postgres_fdw.sql is changed from upstream postgres_fdw.sql file. The changes are as follows:
1. gp2pg_postgres_fdw.sql is used by gpdb7, and gpdb7 connects to a remote postgres server using postgres_fdw.
2. Because some features are not supported in gpdb7, we disable some related test cases.
- gpdb7 doesn't support that ModifyTable mixes distributed and entry-only tables now. So some test cases about partition table and inherited table (including postgres_fdw foreign table) are disabled.
- gpdb7 doesn't support triggers for statements now. So those related test cases are disabled.
- gpdb7 doesn't support REINDEX CONCURRENTLY now. So those related test cases are disabled. …
> Enable postgres_fdw test for gpdb7 in pipeline

- gpMgmt/bin/gpexpand
The table gpexpand.status_detail used by gpexpand should be distributed by "table_oid", to avoid the updating workload burden of tens thounsand tables in a segment, concentrated on only one single segment with the prior distribution policy (distributed by dbname).
Authored-by: Peng Han <phan@vmware.com>
------
main branch version of https://github.com/greenplum-db/gpdb/pull/14690
> (main branch) gpexpand.status_detail should be distributed by "table_oid".

- doc/src/sgml/ref/create_function.sgml
This ensures that create_help.pl can generate help output for CREATE
FUNCTION including the EXECUTE ON INITPLAN option.
Fixes https://github.com/greenplum-db/gpdb/issues/10269.
> psql: Ensure EXECUTE ON INITPLAN is in help text

- src/backend/cdb/cdbcat.c
- src/backend/cdb/cdbcopy.c
- src/backend/cdb/cdbpathlocus.c
- src/backend/cdb/cdbtm.c
- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/cdb/motion/ic_common.c
- src/backend/cdb/motion/ic_udpifc.c
- src/backend/optimizer/util/clauses.c
I'm running clang static analyzer against Greenplum source codes and found the following warnings:
1. (List *) freed by pfree().
2. Dead assinments (I only fixed those under cdb directory).
There're many warnings reported by CSA, I will continue to send small patches for easy reviewing.
> [7X] Fix warnings found by static analyzer.

- concourse/vars/common_prod.yml
For time concourse resource, stop should be later than start to make it work
[GPR-1081]
> [Releng] [7X] Resource reduced-frequency-trigger's stop should be later than start

- gpAux/client/scripts/greenplum_clients_path.sh
The greenplum_clients_path.sh could not be sourced in other directories before, copy greenplum_path.sh's codes to fix it.
```
$ cat /usr/local/greenplum-clients-devel/greenplum_clients_path.sh
GPHOME_CLIENTS=`pwd`
PATH=${GPHOME_CLIENTS}/bin:${GPHOME_CLIENTS}/ext/python/bin:${PATH}
...
$ set -x
$ . /usr/local/greenplum-clients-devel/greenplum_clients_path.sh
+ . /usr/local/greenplum-clients-devel/greenplum_clients_path.sh
+++ pwd
++ GPHOME_CLIENTS=/tmp/build/b251a50d
++ PATH=/tmp/build/b251a50d/bin:/tmp/build/b251a50d/ext/python/bin:...
...
```
> Set the GPHOME_CLIENTS correctly in the script

- src/test/regress/expected/truncate_gp.out
- src/test/regress/sql/truncate_gp.sql
The truncate_gp case lists the on-disk files to check the behavior of truncate, but it had two issues that made the case flaky.
1, the length of filenames may be long enough to have a different output title.
2, Python's `os.listdir()` doesn't guarantee the order.
This commit fixes it.
> Fix the flaky case truncate_gp

- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
Some of the gpmovemirror and gprecoverseg tests seen failing when waiting for segment to come online or waiting for progress file (recovery_progress.file)  to get created sometime which is taking longer. Enhancing timeout for such cases.
> [7x] Test fix failure by adding timeout

- src/backend/cdb/cdbpartition.c
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
Partition exchanging with different distribution policy may produce `SEGFAULT` at gpdb builded with `--enable-cassert`.
For ex., the next query, will produce SEGFAULT:
```
postgres=# CREATE TABLE ds_part ( a INT, b INT, c INT) PARTITION BY RANGE(c)( START(1) END (10) EVERY (2), DEFAULT PARTITION deflt);
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
NOTICE:  CREATE TABLE will create partition "ds_part_1_prt_deflt" for table "ds_part"
NOTICE:  CREATE TABLE will create partition "ds_part_1_prt_2" for table "ds_part"
NOTICE:  CREATE TABLE will …
```
> cdb: fix SEGFAULT for gpdb builded with cassert

- src/backend/cdb/cdbtm.c
- src/backend/storage/ipc/procarray.c
- src/backend/tcop/pquery.c
- src/include/cdb/cdbtm.h
- src/test/isolation2/input/distributed_snapshot.source
- src/test/isolation2/output/distributed_snapshot.source
Currently, we will create a distributed snapshot in the function `GetSnapshotData()` if 
we are QD, and we will iterate `procArray` again to get the global xmin/xmax/xip.
But if the current query could be dispatched to a single segment directly, which means 
it's a direct dispatch, there is no need to create a distributed snapshot, the local snapshot 
is enough.
> Not grab distributed snapshot if it's direct dispatch

- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Updating gprecoverseg tests case to make sure the cluster is rebalanced before bringing primaries down again.
> Fixed gprecoverseg and gpmovemirrors flaky testcases

- gpMgmt/bin/gppylib/heapchecksum.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Currently, when doing an incremental recovery in verbose mode with "gprecoverseg -v", we record the pg_controldata output of only source data directory. We can also record the pg_controldata output of the target data directory before running pg_rewind.
Context: Recently there have been multiple pg_rewind failures due to missing wal files with customers. Often times at the time of performing incremental recovery(pg_rewind), the target segments have been shutdown for quite sometime, and if the incremental recovery failed, users usually choose to perform a full recovery as a workaround to bring the target segments up. This sequence of operations would erase the clue of what had happened on the target segment before it went down in the first place. Recording the pg_controldata output of the …
> Record pg_controldata output of failed segment

- src/backend/utils/resgroup/cgroup.c
- src/include/utils/cgroup.h
When gpdb calls `InitResGroups` to init a postgres backend,  gpdb will first call function `getcpuset_v1` to get entire cpuset given to gpdb. And then call function `setcpuset_v1` to write cpuset to cgroup path.
However `getcpuset_v1` call function `readStr`(in src/backend/utils/resgroup/cgroup.c). Function `readStr` is implemmented as this:
```
void
readStr(Oid group, BaseDirType base, CGroupComponentType component,
const char *filename, char *str, int len)
{
char data[MAX_INT_STRING_LEN];
size_t data_size = sizeof(data);
char path[MAX_CGROUP_PATHLEN];
size_t path_size = sizeof(path);
buildPath(group, base, component, filename, path, path_size);
readData(path, data, data_size);
StrNCpy(str, data, len);
}
```
**Pay Attention to: char data[MAX_INT_STRING_LEN];**
As we see from the code, …
> Fix resgroup init error when there is a lot of cores in cpuset.cpus

- src/bin/pg_dump/pg_dump.c
Commit a452dbae introduced a regression that removed setting nchecks on tblinfo which are the number of check constraints. Since it was never set it defaulted to zero causing no table check constraints to be dumped.
This issue was discovered by the gpupgrade upgradeable pg_upgrade acceptance tests.
Test Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/dumpCheckConstraints
> [6X] pg_dump: set check constraints

- concourse/pipelines/pr_pipeline.yml
Should switch to rocky8 for pr_pipeline, the image need to be rocky8
> [Releng] [6X]Fix typo in pr pipeline

- contrib/pg_upgrade/version_old_8_3.c
Flush out the comment on upgrading sequences to make it obvious that pg_upgrade automatically applies the `adjust_sequences.sql` script. This comment can be very useful to future developers. This comment is not needed on main (7X) as the script is no longer used.
> [6X] flush out comment on upgrading sequences

- src/bin/scripts/reindexdb.c
We are testing PG server version, so we should remain consistent with upstream and report the PostgreSQL version to the user, otherwise we would be carrying significant diffs across the codebase with upstream forward.
> Remove FIXME in reindexdb.c

- src/backend/tcop/utility.c
- src/test/regress/expected/guc_gp.out
- src/test/regress/sql/guc_gp.sql
Fixed Resource management DDL report "WARNING: unrecognized node type" when log_statement='ddl'.
The `LogStmtLevel GetCommandLogLevel(Node *parsetree)` function lacks `NodeTag` handling for resource management commands.
Recurrence test case:
1. Modify GPDB's configurations:
```bash
gpconfig -c log_statement -v 'ddl'
gpstop -u
```
2. Execute query:
```
postgres=# show gp_resource_manager ;
gp_resource_manager
---------------------
queue
(1 row)
postgres=# alter resource group admin_group set concurrency 10;
WARNING:  unrecognized node type: 659
ALTER RESOURCE GROUP
postgres=# alter resource queue pg_default without (memory_limit);
WARNING:  unrecognized node type: 655
ALTER QUEUE
```
> Fixed Resource management DDL report "WARNING: unrecognized node type" when log_statement='ddl'.

- gpMgmt/doc/gpconfigs/gpinitsystem_singlenode
Removed the master reference from gpinitsystem single node template by changing the `COORDINATOR_DIRECTORY` value from `/gpmaster` to `/gpcoordinator`
> Docs: Change /gpmaster to /gpcoordinator

- concourse/pipelines/README.md
- concourse/pipelines/templates/gpdb-tpl.yml
Centos7 is a widely used by developer, so trigger it by gpdb commits instead of weekly trigger.
Except default platform: rocky8 and centos7, other platform are still weekly trigger.
Also update README of the how to create and update prod and dev pipelines
> [Releng] [6X] trigger 6X_STABLE_centos7 by commits

- doc/src/sgml/ref/create_function.sgml
This backports 7X commit: 87db41efcdf71b24319896de582847d2ed16038d
with a trivial conflict.
This ensures that create_help.pl can generate help output for CREATE
FUNCTION including the EXECUTE ON INITPLAN option.
Fixes https://github.com/greenplum-db/gpdb/issues/10269
> [6X] psql: Ensure EXECUTE ON INITPLAN is in help text

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
- src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
- src/test/regress/expected/bfv_dd_types_optimizer.out
- src/test/regress/expected/direct_dispatch.out
- src/test/regress/expected/direct_dispatch_optimizer.out
- src/test/regress/expected/inherit_optimizer.out
- src/test/regress/expected/qp_targeted_dispatch_optimizer.out
- src/test/regress/expected/window_optimizer.out
- src/test/regress/sql/direct_dispatch.sql
ORCA did not perform direct dispatch when the distribution column was of type 'varchar'
With this update this error is fixed.
For direct dispatch, in the code, for datum and distribution column OIds are compared. 
Direct dispatch is performed, if they are equal. 
Consider the following query which failed for a table (create table t1_varchar(col1_varchar varchar, col2_int int)):
explain select * from t1_varchar where col1_varchar = ‘c’;
In this case both the Old field in IMDid class, were different, thus direct dispatch was not performed. 
To fix this, it is checked if a cast exist between them and if that cast is binary coercible. Eg if datum oid id 25(Text) and DistCol oid is 1043(VarChar) then since a cast is possible and cast is binary coercible, we go ahead with direct dispatch. …
> Correct direct dispatch error in ORCA, if distribution column is of varchar type

- src/backend/executor/execProcnode.c
- src/test/regress/expected/bfv_subquery.out
- src/test/regress/expected/bfv_subquery_optimizer.out
- src/test/regress/sql/bfv_subquery.sql
**Issue:**
https://github.com/greenplum-db/gpdb/issues/10803
When ORCA generates a RESULT node with a LIMIT parent, the query returns a subset of the actual result.
**Root cause:**
When ORCA generates a RESULT node with a LIMIT parent, the parent node's tuple bound is pushed down to the RESULT node's child node. This is expected unless the RESULT node has a filter. The filter is supposed to be applied before the tuple bound, instead it's currently applied after the tuple bound. This leads to the query returning a subset of the actual result.
**Example:**
Consider this plan shape --
```
->  Limit
->  Result
Filter: (SubPlan 1)
->  Sort
...
SubPlan 1
...
```
The RESULT node has a LIMIT parent and a SORT child. The correct procedure should be: (1) sort the relation, (2) apply the filter to …
> Remove result tuple bound push down if qual

- gpdb-doc/markdown/install_guide/platform-requirements.html.md
Bumping RHEL8 version requirement to v8.7 due to XFS bug.
Similar wording will be added to latest 6.23 release notes as known issue/important note.
> Update RHEL 8 version requirement to v8.7

- gpdb-doc/markdown/ref_guide/sql_commands/GRANT.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/REVOKE.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14298.
i tried this out.  seems like the user can specify only a single table name with the ONLY clause, so updated the synopsis accordingly.
> docs - GRANT/REVOKE ONLY keyword

- gpMgmt/bin/gpcheckcat
The table `pg_db_role_setting` has no `oid` column, check `setdatabase` instead.
> gpcheckcat able to check pg_db_role_setting

- src/backend/cdb/motion/ic_common.c
Currently out-of-bounds targetRoute leads to SEGFAULT and crashes the segment anyway. After this commit the problem will result only in one failed query. Though root cause of invalid targetRoute is still unknown bug. It is a sanity check to avoid crash.
-----
pre-port PR https://github.com/greenplum-db/gpdb/pull/13964 to main branch.
Just a sanity check no need to add case.
> Convert targetRoute Assert()s in SendTupleChunkToAMS() into FATALs

- src/backend/commands/tablecmds.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
Greenplum doesn't allow this, creating readable external tables with a
distribution policy always fails, this commit disallows it via `ALTER`.
reference:
commit b610b10b27b3df4285b7cb677c8d665d92c4a6b1
Author: Huansong Fu <fuhuansong@gmail.com>
Date:   Thu Sep 29 08:12:30 2022 -0700
Support ALTER TABLE SET DISTRIBUTED BY for external tables
Fixes https://github.com/greenplum-db/gpdb/issues/14754
> Disallow setting the distribution policy of readable external tables

- src/bin/pg_dump/pg_backup_db.c
- src/tools/msvc/Solution.pm
1, the extra `libpq-int.h` involves `pthread-win32.h`, which doesn't
exist on our building machine.
2, The latest upstream Kerberos on Windows is installed under \lib\amd64,
but our building machine hasn't been updated yet.
> Fix building clients for Windows

- src/test/isolation2/expected/.gitignore
- src/test/isolation2/sql/.gitignore
https://github.com/greenplum-db/gpdb/pull/14650 moved the distributed_snapshot test to input/output folder but missed adding the .gitignore entries so the generated .sql and .out files would appear in untracked files. Adding now.
> Add .gitignore entries for distributed_snapshot test

- src/backend/statistics/dependencies.c
- src/backend/statistics/mvdistinct.c
- src/backend/statistics/statistics_gram.y
- src/backend/statistics/statistics_scanner.l
- src/test/regress/expected/minirepro.out
- src/test/regress/expected/stats_ext.out
- src/test/regress/expected/stats_ext_optimizer.out
- src/test/regress/sql/stats_ext.sql
Trying to remove compilation warnings from statistics grammar
```
statistics_gram.y: In function 'statistic_yyparse':
statistics_gram.y:163:75: warning: passing argument 2 of 'build_attnums_array' from incompatible pointer type [-Wincompatible-pointer-types]
163 |                 AttrNumber *ptr = build_attnums_array($2, &$$->nattributes);
|                                                                           ^~
|                                                                           |
|                                                                           AttrNumber * {aka short int *}
In file included from statistics_gram.y:4:
../../../src/include/statistics/extended_stats_internal.h:93:63: note: expected 'int *' but argument is of type 'AttrNumber *' {aka 'short int *'}
93 …
```
> Remove compilation warnings from statistic grammar file

- src/test/isolation2/expected/.gitignore
- src/test/isolation2/sql/.gitignore
https://github.com/greenplum-db/gpdb/pull/14707 moved the distributed_snapshot test to input/output folder but missed adding the .gitignore entries so the generated .sql and .out files would appear in untracked files. Adding now.
> [6X] Add .gitignore entries for distributed_snapshot test

- src/bin/scripts/reindexdb.c
Concurrent index builds/rebuilds are banned in GPDB, so also extend it
to reindexdb.
Finish the job that was started by e5b0e2531a2 and leave breadcrumb for
version check which will be applicable once we do support it.
> Ban reindexdb --concurrently

- src/backend/optimizer/plan/initsplan.c
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
When optimizer is off.
For qual (NOT(EXISTS_SUBLINK) and EXPR_SUBLINK)
or qual (NOT(ANY_SUBLINK) AND EXPR_SUBLINK)
In pull_up_sublinks_qual(), after NOT(EXISTS_SUBLINK) is converted to Anti-JOIN (or NOT(ANY_SUBLINK) => LASJ_NOTIN-JOIN), if EXPR_SUBLINK is also successfully converted to INNER-JOIN (see convert_EXPR_to_join) , we can encounter the scenario where qual is postponed past the anti or lasj_notin join. It will trigger assertion failure:
Assert(j->jointype == JOIN_INNER || j->jointype == JOIN_SEMI);
> FATAL:  Unexpected internal error (assert.c:48)
> DETAIL:  FailedAssertion("!(j->jointype == JOIN_INNER || j->jointype == JOIN_SEMI)", File: "initsplan.c", Line: 1018)
> server closed the connection unexpectedly
> ...
We can easily reproduce this issue in master and 6X branch:
``` …
```
> (6x backport) Possible qual postponing past ANTI-JOIN/LASJ_NOTIN-JOIN

- gpMgmt/bin/gpexpand
The table gpexpand.status_detail used by gpexpand should be distributed by "table_oid", 
to avoid the updating workload burden of tens thounsand tables in a segment, concentrated
on only one single segment with the prior distribution policy (distributed by dbname).
Authored-by: Peng Han <phan@vmware.com>
> (6x) gpexpand.status_detail should be distributed by "table_oid".

- gpMgmt/bin/gpexpand
It is distributed by table_oid column, put it the 1st column for better performance.
> Refine struct of gpexpand.status_detail table.

- src/backend/optimizer/plan/initsplan.c
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
When optimizer is off.
For qual (NOT(EXISTS_SUBLINK) and EXPR_SUBLINK)
or qual (NOT(ANY_SUBLINK) AND EXPR_SUBLINK)
In pull_up_sublinks_qual(), after NOT(EXISTS_SUBLINK) is converted to
Anti-JOIN (or NOT(ANY_SUBLINK) => LASJ_NOTIN-JOIN), if EXPR_SUBLINK is
also successfully converted to INNER-JOIN (see convert_EXPR_to_join)
, we can encounter the scenario where qual is postponed past the anti
or lasj_notin join. It will trigger assertion failure:
Assert(j->jointype == JOIN_INNER || j->jointype == JOIN_SEMI);
> FATAL:  Unexpected internal error (assert.c:48)
> DETAIL:  FailedAssertion("!(j->jointype == JOIN_INNER || j->jointype == JOIN_SEMI)", File: "initsplan.c", Line: 1018)
> server closed the connection unexpectedly
> ...
We can easily reproduce this issue in master and 6X branch:
```sql …
```
> Possible qual postponing past ANTI-JOIN/LASJ_NOTIN-JOIN

- src/backend/executor/nodeModifyTable.c
- src/test/regress/expected/returning_gp.out
- src/test/regress/sql/returning_gp.sql
- How to reproduce
1. create table and trigger
```
gpadmin=# create table loc1 (f1 serial, f2 text);
gpadmin=# CREATE FUNCTION trig_row_before_insupdate() RETURNS TRIGGER AS $$
BEGIN
NEW.f2 := NEW.f2 || ' triggered !';
RETURN NEW;
END
$$ language plpgsql;
gpadmin=# CREATE TRIGGER trig_local_before BEFORE INSERT OR UPDATE ON loc1
FOR EACH ROW EXECUTE PROCEDURE trig_row_before_insupdate();
```
2. insert a value, then assert pops
```
gpadmin=# INSERT INTO loc1(f2) VALUES ('test') RETURNING ctid;
ERROR:  Unexpected internal error (execTuples.c:1559)  (seg1 slice2 10.117.190.45:7001 pid=19255) (execTuples.c:1559)
DETAIL:  FailedAssertion("!(((bool) (((const void*)(&(htup->t_self)) != ((void *)0)) && ((&(htup->t_self))->ip_posid != 0))))", File: "execTuples.c", Line: 1559)
HINT:  Process 19255 …
```
> 6X: Fix assert when inserting/updating table with trigger and returning ctid

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- We recently changed the mdw hostname to cdw for inclusive terminology. This spot was missed.
> Update mdw to cdw in gpcheckperf hostfile test

- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
ALTER DEFAULT PRIVILEGES IN SCHEMA ... affects all future tables created in the same schema. Since the test 'partition' is running in parallel with other tests like 'partition1', when some table is created in 'partition1' test after the SELECT privilege on 'public' is granted to a role in 'partition' test, that role cannot be dropped later because that table still exists in another test, e.g.:
DROP ROLE user_prt_acl;
+DETAIL:  privileges for table start_exclusive_smallint
+ERROR:  role "user_prt_acl" cannot be dropped because some objects depend on it
+privileges for table start_exclusive_smallint_1_prt_p1
+privileges for table start_exclusive_smallint_1_prt_pmax
Fixing it by using a dedicated schema for the ALTER DEFAULT PRIVILEGES test in 'partition'.
> Fix flaky test 'partition'

- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
ORCA generated wrong result for a query on partitioned table, in a scenario where the query has different type of predicates at the same time like date and timestamp. Eg: select max(datedday) from table_rangePartition where datedday='2022-10-23' or datedday=('2022-10-23'::date -interval '1 day');
This bug existed only in 6X_STABLE, it was fixed. Through this PR, all the test cases generated for 6X_STABLE are forwarded to MAIN branch also.
PR ref for 6X_STABLE is 
https://github.com/greenplum-db/gpdb/pull/14535
> Adding Test cases for a bug (fixed now) which existed in ORCA 6X only

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
- src/backend/gpopt/translate/CPartPruneStepsBuilder.cpp
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/include/gpopt/gpdbwrappers.h
- src/include/gpopt/translate/CContextDXLToPlStmt.h
**Fixme:**
src/backend/gpopt/translate/CContextDXLToPlStmt.cpp: // GPDB_12_MERGE_FIXME: we haven't seen the scan id yet, this scan id is likely // for dynamic pruning.
**Action:**
Check removed
**Fixme:**
src/backend/gpopt/translate/CPartPruneStepsBuilder.cpp: // GPDB_12_MERGE_FIXME: This should be StrategyNumber, but IndexOpProperties // takes an INT
**Action:**
Explicit conversion from INT to StrategyNumber before value assigned to `PartitionPruneStepOp->opstrategy`
**Fixme:**
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp: // GPDB_12_MERGE_FIXME: this duplicates a check in ExecInitProjectSet
**Action:**
None. Function `SanityCheckProjectSetTargetList` share some code with `ExecInitProjectSet`. But refactoring isn't trivial and will involve changes to upstream .c files
> GPDB_12_MERGE_FIXME

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
Add fips support for 6X_STABLE
All the supported platform: centos6, centos7, rhel8, rocky8, oracle linux 8 will run fips test, except ubuntu18.04.
Due to need Ubuntu Pro subscription to enable fips, so ubuntu18.04 will not have fips test
> [Releng] [6X] Add fips test in pipeline

- src/backend/utils/resgroup/resgroup-ops-linux.c
- src/include/utils/resgroup.h
This backports 7X commit: https://github.com/greenplum-db/gpdb/commit/198ae8b857b4871076280db7144e101e85540213
When gpdb calls InitResGroups to init a postgres backend, 
readStr is called to read cpuset assigned to gpdb. However the size of data buffer in readStr is too small, cpuset string readed by gpdb is truncated.
This commit change the buffer size from MAX_INT_STRING_LEN(20) to MAX_CGROUP_CONTENTLEN(1024) to fix resgroup init error when there is a lot of cores in cpuset.cpus 
Fixes https://github.com/greenplum-db/gpdb/pull/14736
Please hava a look at this.
> [6X] backport: Fix resgroup init error when there is a lot of cores in cpuset.cpus 

- src/backend/executor/execMain.c
- src/backend/executor/functions.c
- src/backend/executor/spi.c
1. Create function written in sql language that optimizers can’t inline, e. g.: 
```
create function f(a int) returns int
immutable
security definer
language sql as $$
select case when $1 > 500 then 0 end;
$$;
```
2. Execute a query which executes this function multiple times 
```
explain analyze verbose
select f(i) from generate_series(1, 1000000) i;
```
3. The query uses much more memory when gp_enable_gpperfmon=true than in the opposite case.
The reason of high memory consumption is memory allocation for two structures in CreateQueryDesc() and release of memory for only one of these structures in FreeQueryDesc(). This pair of functions is run every time when subquery is executed. The more times the subquery is executed, the more memory leaks.
The patch adds …
> Fix high memory consumption for queries with SQL subqueries

- src/backend/replication/libpqwalreceiver/libpqwalreceiver.c
- src/backend/replication/walreceiver.c
- src/backend/replication/walreceiverfuncs.c
- src/include/replication/walreceiver.h
- src/test/regress/init_file
- src/test/walrep/Makefile
This is follow up PR https://github.com/greenplum-db/gpdb/pull/11343.
The current implementation of the synchronous walreceiver connection to the walsender has a flaw.
When the master host becomes unavailable, walreceiver is trying to open a connection with the master. After an unsuccessful attempt, it dies and reborns again. During the attempt, the system call `poll()` (or `select`) is called, where walreceiver is for a long time (~2 minutes).
When we call gpactivatestandby, the promote signal is sent. postmaster tries to stop the walreceiver and sends a `SIGTERM` to it. `SIGTERM` doesn't stop `poll()`. After the signals have arrived the `poll()` continues its work. You can check this by looking at the `pqSocketCheck` function in the `fe-misc.c` file.
Here's an stack trace for …
> [6X] Use asynchronous connection in libpqwalreceiver 

- src/backend/utils/adt/gp_dump_oids.c
- src/test/regress/expected/gp_dump_query_oids.out
- src/test/regress/sql/gp_dump_query_oids.sql
Previously, when using minirepro on a query with explain command that accessed materialized views/view , the object that the materialized view/view used/accessed were not dumped with the minirepro. This was because while rewriting queries in pg_rewrite_query, the utilities were not rewritten and were dumped into a result list. Due to this in the current implementation while getting the relids of queries containing explain command , we were getting the relids of the materialized view/view and not of the used/accessed objects. With this fix we are able to fetch the relids of both the materialized view/views and the used objects. So the minirepro will be able to collect the objects DDL used in the view.
Setup:
------
```
create table foo (a int);
create view foo_view as select a from foo; …
```
> Fix minirepro utility to create view dependencies for explain queries

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/gpfdist2_compress.source
- src/bin/gpfdist/regress/output/gpfdist2_compress.source
In the previous [https://github.com/greenplum-db/gpdb/pull/14144](PR), we finished the support of compression transmission for readable gpfdist external table. In this PR, I developed the code for zstd compression transmission for the writable gpfdist external table.
The pr involves three aspects of changes. The first part is adding decompression code for gpfdist. The second part is adding compression code for gpdb. Other modifications mainly involve the regression test for writable gpfdist external table.
Finally, to use the zstd compression to transfer data for a writable external table, we need to use the flag `--compress` to turn on the compression transmission for gpfdist.
> Add ZSTD compression support for gpfdist writable external table

- src/backend/access/aocs/aocsam_handler.c
- src/backend/commands/copy.c
- src/backend/executor/nodeSeqscan.c
- src/include/access/tableam.h
- src/test/regress/expected/aoco_projection.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/aoco_projection.sql
aocs_beginscan takes a projection array in the form of bool *proj. Previously, scan_begin_extractcolumns API only took a targetlist and qual that was converted to a projection array. This commit allows us to optionally pass a projection array directly to scan_begin_extractcolumns, which is pushed down to aocs_beginscan.
This change allows column projection for UTILITY statements such as COPY TO and adds test coverage for this use case.
Test on copy 1 column from 100 column wide table:
main:
```
postgres=# copy extra_wide_table (c2) to '/dev/null';
COPY 8192000
Time: 139364.596 ms (02:19.365)
```
```
-   98.07%     9.97%  postgres  postgres              [.] aocs_getnext                                                                                                  ▒
- 88.09% aocs_getnext …
```
> Pass column projection array to scan_begin_extractcolumns

- gpdb-doc/markdown/ref_guide/SQL2008_support.html.md
markdown table in sql compliance topic isn't rendering correctly in both greenplum 7 and greenplum 6 docs (https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/fix-tbl/greenplum-database/GUID-ref_guide-SQL2008_support.html).  found and fixed the bad row.
correctly-formatted table on doc review site (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/fix-tbl/greenplum-database/GUID-ref_guide-SQL2008_support.html
> docs - fix markdown table not rendering correctly

- src/backend/Makefile
- src/backend/statistics/.gitignore
- src/backend/statistics/Makefile
Due to ext_stats commit we are seeing untracked files after every gpdb build. So trying to ignore those files using .gitignore
Untracked files:
(use "git add <file>..." to include in what will be committed)
src/backend/statistics/statistics_gram.c
src/backend/statistics/statistics_scanner.c
> Cleaning untracked files

- src/test/regress/expected/aggregates.out
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/sql/aggregates.sql
`relname` of `pg_class` has an index, the stats and plan can be influenced by other tests running in parallel. Use `relnatts` instead.
```
{
'id' => 5,
'parent' => 2,
-          'short' => 'Seq Scan on pg_class'
+          'short' => 'Index Only Scan using pg_class_tblspc_relfilenode_index on pg_class'
}
],
'id' => 2,
```
> Fix a flaky test case querying pg_class

- src/backend/executor/nodeModifyTable.c
- src/test/regress/expected/returning_gp.out
- src/test/regress/input/uao_dml/uao_dml.source
- src/test/regress/output/uao_dml/uao_dml.source
- src/test/regress/sql/returning_gp.sql
Failed assertion if insert data into an AO table with returning ctid
Root cause:
miss `slot_set_ctid()` during inserting AO table
This PR is used to fix issue #14759
> 6X: set ctid on inserting AO table

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
This adds a guc optimizer_enable_foreign_table. If enabled, Orca will generate plans involving foreign tables. Otherwise, we will fall back to planner. By default this guc is enabled.
> Add GUC optimizer_enable_foreign_table

- src/backend/postmaster/postmaster.c
Currently, if archiver dies during the postmaster startup, it won't attempt to start again. Looks like that archiver restart code has been lost in the https://github.com/greenplum-db/gpdb/commit/a453004ea1946b5c141bd26ac871ac6edde64f37. I propose to move the lost fragment back.
> [6X_STABLE] Ressurect the lost code for archiver auto restart

- src/backend/catalog/namespace.c
- src/test/regress/expected/create_table_like_gp.out
- src/test/regress/sql/create_table_like_gp.sql
This PR is trying to fix the issue of #14649. 
When QD generates query tree and serializes it to string and sends it to QE, 
and QE will deserialize it to a plan tree. In this process, Greenplum seems not 
to consider the difference between NULL and an empty string, so if the original 
value is a NULL, QE may deserialize it to an empty string, which could lead error 
happened.
It's hard to modify the function of `deserializeNode()`, since Greenplum does not
have the mechanism to clarify NULL and empty string during serialization and
deserialization. 
So this PR is just fixing the special issue, not for general using.
> fix the issue of cannot create temporary table like existing table with comments

- src/backend/catalog/namespace.c
- src/test/regress/expected/create_table_like_gp.out
- src/test/regress/sql/create_table_like_gp.sql
This is the backport of #14742 
This PR is trying to fix the issue of #14649. 
When QD generates query tree and serializes it to string and sends it to QE, 
and QE will deserialize it to a plan tree. In this process, Greenplum seems not 
to consider the difference between NULL and an empty string, so if the original 
value is a NULL, QE may deserialize it to an empty string, which could lead error 
happened.
It's hard to modify the function of `deserializeNode()`, since Greenplum does not
have the mechanism to clarify NULL and empty string during serialization and
deserialization. 
So this PR is just fixing the special issue, not for general using.
> [6X] fix the issue of cannot create temporary table like existing table with comments

- src/backend/bootstrap/bootstrap.c
```
$ postgres --boot -D ~/greenplum-db-data/gpseg-1
LOG:  gp_role forced to 'utility' in single-user mode
free(): invalid pointer
Aborted (core dumped)
```
> pfree() the pstrdup()'d string userDoption

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_DOMAIN.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_DOMAIN.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_DOMAIN.html.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content.  i don't believe there was any greenplum-specific content in the original (v6) pages.  postgres ref page added Notes.
doc review site link for ALTER DOMAIN (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-domain/greenplum-database/GUID-ref_guide-sql_commands-ALTER_DOMAIN.html
> docs - update sql ref pages for ALTER/CREATE/DROP DOMAIN

- contrib/pg_upgrade/greenplum/frozenxids_gp.c
- contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h
- contrib/pg_upgrade/info.c
- contrib/pg_upgrade/pg_upgrade.c
The gp_fastsequence catalog table must be preserved when upgrading to a newer version. Not preserving this table will likely cause duplicate ctids in ao tables when normal cluster operations resume after an upgrade.
How duplicate ctids can occur:
1. gp_fastsequence is initialized to 0 for a new ao table.
2. gp_fastsequence only increases positively in increments of 100.
3. ctids are assigned based on gp_fastsequence values.
When a tuple is inserted it consumes a gp_fastsequence value to produce a ctid to index the data. If a fastsequence value is reused, a duplicate ctid will occur. This will result in indexes returning wrong results.
When an ao table's fastsequence value is lower than the it's tuple count, gpdb's default behavior in an attempt to fix the fastsequence value is to set it …
> [6X] Preserve gp_fastsequence during upgrade

- src/backend/access/aocs/aocssegfiles.c
- src/include/access/aocssegfiles.h
- src/test/regress/expected/alter_table_aocs.out
- src/test/regress/sql/alter_table_aocs.sql
When addcolumn + insert operation is aborted on an AOCO table, pg_aocsseg.vpinfo still has the entries for the aborted column.
Before this change aocsseg during reads we were copying over the whole vpinfo for segfile with RESERVED_SEGNO which includes entries for aborted column
This creates memory corruption as we are copying over more than what is needed/commited (aborted column's vpinfo)
This change edits the read of vpinfo to limit upto committed columns.
This solves the github issue: https://github.com/greenplum-db/gpdb/issues/14518
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fix_aoco_addcol_abort?group=ICW
> Fix memory corruption for AOCO add column + insert + abort

- contrib/postgres_fdw/deparse.c
- contrib/postgres_fdw/postgres_fdw.c
- src/backend/commands/vacuum.c
This pr is to solve issue https://github.com/greenplum-db/gpdb/issues/14579.
When ANALYZE foreign table, `num_pages == 0 && num_tuples > 0` may arise and is reasonable(like postgres_fdw and kafka_fdw).
For example, if ANALYZE kafka_fdw foreign table, `num_pages == 0 && num_tuples > 0` always arises.
Because kafka_fdw doesn't return `num_pages` , which is meaningless for kafka.
Since there are many possibilities causing `num_pages == 0 && num_tuples > 0`, it seems that these assertions are NOT reasonable.
```
if (num_pages < 1.0)
{
if (num_tuples >= 1.0)
{
Assert(Gp_role == GP_ROLE_UTILITY);
Assert(!IsSystemRelation(relation));
Assert(RelationIsAppendOptimized(relation));
num_tuples = 0;
}
Assert(num_tuples < 1.0);
num_pages = 1.0;
}
```
In this pr, if `num_pages == 0 && num_tuples > 0`, …
> Fix ANALYZE's wrong behavior for FDW

- src/backend/cdb/cdbsubselect.c
- src/test/regress/expected/notin.out
- src/test/regress/expected/notin_optimizer.out
- src/test/regress/sql/notin.sql
Per the comments of the field joinaliasvars of struct RangeTblEntry, it might be Var
or COALESCE expr or NULL pointer. For cases other than a simple Var, return NULL
is a safe choice.
For detailes please refer to Github Issue
https://github.com/greenplum-db/gpdb/issues/14858.
> Shortcut when joinaliasvars' element is not Var during NOT-IN pullup.

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_USER_MAPPING.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_USER_MAPPING.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_USER_MAPPING.html.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. i didn't notice any greenplum-specific content on the pages.
in this PR:   mostly editing changes and some narrative additions.
question:  the postgres ref pages do not identify SESSION_USER as a `user_name` option for the ALTER and DROP cl. a ds, i am wondering if this is a mistake?  i noticed that we have some (positive) tests for this in src/test/modules/unsafe_tests/expected/rolenames.out - do we run these?
(no review site, changes are pretty self-explanatory.)
> docs - update sql ref pages for ALTER/CREATE/DROP USER MAPPING

- gpdb-doc/markdown/ref_guide/sql_commands/DEALLOCATE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/EXECUTE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/PREPARE.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_prepared_statements.html.md
- gpdb-doc/markdown/ref_guide/toc.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. there didn't appear to be any greenplum-specific content.
i also added the pg_prepared_statements system view to the ref guide.
doc review site (behind vpn):
- DEALLOCATE (can get to the others from there):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-dealexprep/greenplum-database/GUID-ref_guide-sql_commands-DEALLOCATE.html
- pg_prepared_statements:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-dealexprep/greenplum-database/GUID-ref_guide-system_catalogs-pg_prepared_statements.html
> docs - sql ref page updates for DEALLOCATE/EXECUTE/PREPARE

- gpdb-doc/markdown/ref_guide/system_catalogs/pg_appendonly.html.md
Documenting the rest of the changes from PR https://github.com/greenplum-db/gpdb/pull/14713
The following columns have also been removed from pg_appendonly:
```
|`blocksize`|integer| |Block size used for compression of append-optimized tables. Valid values are 8K - 2M. Default is `32K`.|
|`compresslevel`|smallint| |The compression level, with compression ratio increasing from 1 to 19. When `quicklz`<sup>1</sup> is specified for compresstype, valid values are 1 or 3. With `zlib` specified, valid values are 1-9. When `zstd` is specified, valid values are 1-19.|
|`checksum`|boolean| |A checksum value that is stored to compare the state of a block of data at compression time and at scan time to ensure data integrity.|
|`compresstype`|text| |Type of compression used to compress …
```
> Docs pg appendonly changes

- gpdb-doc/markdown/admin_guide/query/topics/functions-operators.html.md
- gpdb-doc/markdown/analytics/pl_perl.html.md
- gpdb-doc/markdown/analytics/pl_python.html.md
- gpdb-doc/markdown/analytics/pl_sql.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_proc.html.md
doc updates for https://github.com/greenplum-db/gpdb/commit/e4128ee767df3c8c715eb08f8977647ae49dfb59#diff-076d0f40d3f8a1d5ad7153d572dd8ae05eb9f478b3587ff99b62b6c67359afab.
in this PR:
- add info from https://www.postgresql.org/docs/12/xproc.html, "user-defined procedures" to the "using functions and operators" topic - that is where a topic named "user-defined functions" lives
- update the pl/perl, pl/pgsql, and pl/python topics.  greenplum's content on these pages differs quite a bit from the postgres content.  NOT addressing that in this PR.  with respect to procedures, i scanned all of the postgres 12 topics for each of the mentioned procedural languages for procedure-related info, and placed it into an "About Developing PL/xxx Procedures" topic.  not sure if the info is too disjointed? …
> docs - misc updates/additions related to stored procedures

- src/backend/commands/tablecmds.c
- src/test/regress/expected/partition_storage.out
- src/test/regress/sql/partition_storage.sql
Just like what we do during 'ALTER ACCESS METHOD'. Do not inherit reloptions from the parent in this condition.
> Fix error out when partitioned children has different am with parent.

- src/backend/commands/typecmds.c
- src/test/regress/expected/AOCO_Compression.out
- src/test/regress/expected/column_compression.out
- src/test/regress/sql/AOCO_Compression.sql
Changing a type's default encoding using ALTER TYPE name SET DEFAULT
ENCODING should also set it's dependent array type to the same encoding.
This is the expected behavior if default compression encoding is
specified on CREATE TYPE. This also fixes pg_dump and pg_upgrade since
pg_dump relies on ALTER TYPE statements to set a type's default
encoding.
Without this change user defined types with their default encodings
specified on creation will set default encodings on the both type and
it's depedent array type. The ALTER TYPE SET DEFAULT ENCODING statement
from pg_dump would not restore the default encoding of the dependent
array type.
This change prohibits altering types without a dependent array type.
This was allowed under the following assumptions.
1. User defined types will always …
> [7X] Also set dependent array type encoding on ALTER TYPE ENCODING

- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/vars/common_prod.yml
Run 6X_STABLE_centos on every day on 4:00 am
Run non default platform, and non centos7 job every Monday
6X_STABLE_rhel8:  0:00 am
6X_STABLE_ubuntu18.04:  2:00 am
6X_STABLE_centos6:  6:00 am
Only run check_format on default platform, the job are exactly same across all the supported platform, 
so there is no need to run them on all platform
> [Releng] [6X] Run 6X_STABLE_centos7 pipeline every day

- src/backend/parser/gram.y
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_ao.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
- src/test/regress/sql/matview_ao.sql
Allow DISTRIBUTED BY when using the CREATE MATERIALIZED VIEW IF NOT EXISTS SYNTAX.
Resolves error:
```
CREATE MATERIALIZED VIEW IF NOT EXISTS mvtest AS SELECT * FROM mvtest_tvvmv DISTRIBUTED RANDOMLY; 
ERROR:  syntax error at or near "DISTRIBUTED"
```
> Fix syntax error with CREATE MATERIALIZED VIEW

- gpMgmt/bin/lib/gp_bash_functions.sh
There is a bug in `GET_PG_PID_ACTIVE()` function where the `ss` command is called remotely. The remote execution occurs through the following command - `REMOTE_EXECUTE_AND_GET_OUTPUT $HOST $SS -an 2>/dev/null`. When this is called, only the `$SS` part is passed as an argument to the `REMOTE_EXECUTE_AND_GET_OUTPUT()` function ignoring the rest. Due to this the `ss` command takes a long time to complete since there is no -n flag provided (without the -n flag, the command tries to resolve the service name of the IP addresses which can take a long time to complete).
This commit resolves this issue by simply enclosing the ss command under quotes - `REMOTE_EXECUTE_AND_GET_OUTPUT $HOST "$SS -an 2>/dev/null"`. This greatly reduces the time the `ss` command takes to execute and hence improves the …
> gpinitsystem: Fix bug when calling ss remotely

- src/backend/storage/ipc/shmem.c
The max size for shared memory hash table name is SHMEM_INDEX_KEYSIZE - 1 (shared hash table name is stored and indexed by ShmemIndex hash table, the key size of it is SHMEM_INDEX_KEYSIZE), but when caller using a longer hash table name, it doesn't report any error, instead it just uses the first SHMEM_INDEX_KEYSIZE chars as the hash table name.
When some hash tables' names have a same prefix which is longer than (SHMEM_INDEX_KEYSIZE - 1), issues will come: those hash tables actually are created as a same hash table whose name is the prefix. So add the assert to prevent it.
> Add assert to the length of shared hash table name

- src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
- src/test/regress/expected/qp_orca_fallback.out
- src/test/regress/expected/qp_orca_fallback_optimizer.out
- src/test/regress/sql/qp_orca_fallback.sql
Previously, Orca would crash if encountering this. For now, fall back similarly to what we do for RTE_TABLEFUNCTION.
Example query: explain SELECT * FROM xmltable('/root' passing '' COLUMNS element text);
This actually fell back correctly in retail build, but we were hitting a `__builtin_unreachable` call, which is undefined behavior, so we were likely just getting lucky.
Fixes issue reported in https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/4F8GUSs04L8
> Fall back in Orca for queries with RTE of type TableFunc

- src/backend/commands/copy.c
- src/backend/commands/createas.c
- src/backend/commands/tablecmds.c
- src/backend/executor/execMain.c
- src/include/executor/executor.h
- src/test/regress/expected/autostats.out
- src/test/regress/sql/autostats.sql
Greenplum introduces auto_stats for a long time, please refer to https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/bAyw2KBP6yE/m/hmoWikrPAgAJ for details and decision of auto_stats.
auto_stats() now is invoked at the following 7 places:
1. ProcessQuery()
2. _SPI_pquery()
3. postquel_end()
4. ATExecExpandTableCTAS()
5. ATExecSetDistributedBy()
6. DoCopy()
7. ExecCreateTableAs()
Previously, Place 2, 3 is hard-coded as inside function, Place 1, 4 ~ 7 is hard-coded as not-inside function. Place 4 ~ 7 does not cover the case that COPY or CTAS is called inside procedure language.
Since in future auto_stats will be removed, for now let's just to do some simple fix instead of big refactor.
To correctly pass the inFunction parameter for auto_stats() at Place 4 ~ 7 we introduce …
> (6X backport) Fix inFunction for auto_stats in CTAS, COPY and AlterTable.

- src/backend/cdb/cdbgroup.c
- src/test/regress/expected/functional_deps.out
- src/test/regress/sql/functional_deps.sql
The issue is caused by a GPDB_91_MERGE_FIXME(https://github.com/greenplum-db/gpdb-postgres-merge/commit/e94522ad93f2208eb8c56adc0dd333f00508f769),
which also manage to solve bug related pipeline failure after merging feature (https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=e49ae8d3bc588294d07ce1a1272b31718cfca5ef) from upstraem.
The key reason to this issue is that there is a assumption in GP6 and not in upstream, which is columns of final targetlist must in group by clause during generating multi hashagg plan, and PR above has tried to add functional-dependency-related columns  to group by clause.
Besides adding those columns into group by clause, we also need to fill GroupColIdx and GroupOperators in AggNode struct for executing Hashagg plan, and this is what we done in …
> (6X_STABLE)Fix bug about functional dependency on primary key of group by clause

- src/backend/cdb/cdbpartition.c
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
Problem:
ORCA generates incorrect results for a query on partition table with date and timestamp predicates.
Setup :
create tables
create table public.test
(datedday date)
WITH (
appendonly=false
)
PARTITION BY RANGE(datedday)
(
PARTITION pn_20221022 START ('2022-10-22'::date) END ('2022-10-23'::date),
PARTITION pn_20221023 START ('2022-10-23'::date) END ('2022-10-24'::date),
DEFAULT PARTITION pdefault
);
load data
insert into public.test(datedday)
select ('2022-10-22'::date)
union
select ('2022-10-23'::date);
query
select max(datedday) from public.test where datedday='2022-10-23' or datedday=('2022-10-23'::date -interval '1 day');
Sol:
ORCA retained the information of the functions used to access the predicate value and used it to access the other predicate also. For example, if the …
> Incorrect result for query on date and timestamp predicate in partition table scenario

- src/backend/commands/copy.c
- src/backend/commands/createas.c
- src/backend/commands/tablecmds.c
- src/backend/executor/execMain.c
- src/backend/tcop/utility.c
- src/include/executor/executor.h
- src/include/tcop/utility.h
- src/test/regress/expected/autostats.out
- src/test/regress/sql/autostats.sql
Greenplum introduces auto_stats for a long time, please refer to https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/bAyw2KBP6yE/m/hmoWikrPAgAJ for details and decision of auto_stats.
auto_stats() now is invoked at the following 7 places:
1. ProcessQuery()
2. _SPI_pquery()
3. postquel_end()
4. ATExecExpandTableCTAS()
5. ATExecSetDistributedBy()
6. DoCopy()
7. ExecCreateTableAs()
Previously, Place 2, 3 is hard-coded as inside function, Place 1, 4 ~ 7 is hard-coded as not-inside function. Place 4 ~ 7 does not cover the case that COPY or CTAS is called inside procedure language.
Since in future auto_stats will be removed, for now let's just to do some simple fix instead of big refactor.
To correctly pass the inFunction parameter for auto_stats() at Place 4 ~ 7 we introduce …
> Fix inFunction for auto_stats in CTAS, COPY and AlterTable.

- src/backend/storage/ipc/shm_mq.c
- src/test/isolation2/input/parallel_retrieve_cursor/status_wait.source
- src/test/isolation2/output/parallel_retrieve_cursor/status_wait.source
select * from foreign table with limit n in local cluster is much
slower than select * from foreign table without limit clause.
select a foreign table will declare a parallel retrieve cursor in remote cluster.
then establish retrieve conn with all the endpoints and retrieve data.
if with limit n clause we only retrieve n tuples in each retrieve connection.
But if foreign table has a log of data, Senders wait in waitLatch due to
MQ does not have extra space.
After local cluster get enough data, it will close the parallel cursor, however,
Sender receive SIGUSR1 does not call setLatch because set_latch_on_sigusr1 is false.
set set_latch_on_sigusr1 to true in shm_mq_send_bytes to allow setLatch
to be called after receiving SIGUSR1.
> fix select with limit is slower than without limit for a greenplum_fdw table

- contrib/pg_upgrade/greenplum/check_gp.c
- src/backend/commands/tablecmds.c
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/pg_dump.h
The individual commits that make upgrading external partitions work:
```
commit 1495eec10b5bc1485e7b1eaaf9f6c2a4897ce175
Author: Jimmy Yih <jyih@vmware.com>
Date:   Thu Jan 19 18:42:13 2023 -0800
Allow EXCHANGE PARTITION to run in utility mode during upgrade
We don't allow EXCHANGE PARTITION to run in utility mode because
primary segments do not have the pg_partition_rule catalog information
to be able to perform the EXCHANGE PARTITION. However, we should allow
it to run during upgrade because only the coordinator segment is
touched which does have the pg_partition_rule data (its catalog is
later copied over to the primary segments as a part of the gpupgrade
flow).
commit 0e853d6e20933d8d06c961a0181decf651f46e47
Author: Jimmy Yih <jyih@vmware.com>
Date:   Fri Jan 20 14:32:43 2023 -0800 …
```
> [6X] pg_dump and pg_upgrade: fix/change external partition handling

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/IndexOnLeaf-NonOverlappingHeterogenousIndex-ANDPredicate-AO.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnLeaf-OverlappingHeterogenousIndex-ANDPredicate-AO.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnLeaf-OverlappingHeterogenousIndex-ORPredicate-AO.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnLeaf-SingleColumnHeterogenousIndexOnRoot-2-AO.mdp
- src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
- src/backend/gporca/libnaucrates/include/naucrates/dxl/parser/CParseHandlerMDIndex.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIndexGPDB.h
- src/backend/gporca/libnaucrates/include/naucrates/md/IMDIndex.h
- src/backend/gporca/libnaucrates/src/md/CMDIndexGPDB.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDIndex.cpp
This was used in the previous partitioning architecture with partial indexes, but is now unused. Also resolves a FIXME.
> Remove unused mdpart_constraint from indexes in Orca

- src/backend/postmaster/autovacuum.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/misc/postgresql.conf.sample
- src/bin/psql/tab-complete.c
- src/include/postmaster/autovacuum.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/autovacuum-ao-aux.out
- src/test/regress/expected/autovacuum-catalog.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/autovacuum-ao-aux.sql
- src/test/regress/sql/autovacuum-catalog.sql
Add a guc to control which tables autovacuum will vacuum. Supported options are 'catalog' and 'catalog_ao_aux'.
Also add basic regression test coverage for autovacuum of catalog bloat and bloat in AO auxiliary tables.
> Add support for gp_autovacuum_scope guc

- contrib/file_fdw/input/gp_file_fdw.source
- contrib/file_fdw/output/gp_file_fdw_optimizer.source
- src/backend/commands/copy.c
Previously, when using a foreign table that was created with the file fdw under a redistribute and the execution was on the coordinator, the query would hang. This happens because we were using the COPY_EXECUTOR dispatch mode, which is for receiving pre-processed data from QD. Instead, we should be using COPY_DIRECT, which is used with COPY " ON SEGMENT running on a segment, or utility mode, or non-distributed table in QD."
This fixes plans such as:
```
test=# explain select * from f_table, bar where a=c;                                                                                                                                                                                                                                             QUERY PLAN …
```
> Fix COPY when executed via fdw on coordinator as executor

- src/backend/commands/resgroupcmds.c
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
**Disable drop resource group `system_group`.**
Test case:
```
[fairyfar@bogon gpdb]$ psql postgres
psql (12.12)
postgres=# select version();
version
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.1+dev.43.g8e2050682e build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit compiled on Feb  8 2023 11:40:02 Bhuvnesh C.
(1 row)
postgres=# select * from gp_toolkit.gp_resgroup_config;
groupid |   groupname   | concurrency | cpu_hard_quota_limit | cpu_soft_priority | cpuset …
```
> Disable drop resource group `system_group`.

- contrib/file_fdw/file_fdw.c
- contrib/postgres_fdw/postgres_fdw.c
- src/backend/optimizer/path/clausesel.c
- src/backend/optimizer/path/costsize.c
- src/backend/utils/adt/selfuncs.c
- src/include/optimizer/optimizer.h
- src/include/utils/hsearch.h
This pr includes two commits.
**Commit 1:**
Function `clauselist_selectivity` in gpdb7 has one more parameter `use_damping` than upstream postgres.
It causes many postgres's fdw compilation failures in gpdb7(like kafka_fdw, clickhouse_fdw and arrow_fdw).
Because function `clauselist_selectivity` is a general function called by most postgres's fdw,
it's better to keep function `clauselist_selectivity` having same format with upstream postgres.
In this commit, we rename function `clauselist_selectivity` to `clauselist_selectivity_extended`  for gpdb7 internal use.
Meanwhile, we keep function `clauselist_selectivity` having same format with upstream postgres for external fdw use.
**Commit 2:**
We add function `tag_hash` declaration in src/include/utils/hsearch.h.
For function `tag_hash` …
> Make function clauselist_selectivity have same format with upstream postgres

- src/test/isolation2/input/parallel_retrieve_cursor/status_wait.source
- src/test/isolation2/output/parallel_retrieve_cursor/status_wait.source
If foreign table has lots of data, and we only retrieve few tuples in retrieve conn,
Sender will be waiting in WaitLatch due to MQ has no space.
Add testcase to test sender can be notified when cursor is closed.
> Test parallel retrieve cursor can be closed if sender wait in WatLatch when MQ has no space

- gpMgmt/bin/gpcheckresgroupimpl
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckresgroupimpl.py
This is the negligence of PR #14733.
As the title said, this PR is just trying to fix the failed unit test of `test_unit_gpcheckresgroupimpl.py`
> Fix the failed unit test case

- src/backend/cdb/dispatcher/cdbdisp_async.c
- src/backend/cdb/dispatcher/cdbgang.c
- src/backend/cdb/dispatcher/cdbgang_async.c
- src/backend/cdb/motion/ic_udpifc.c
- src/backend/storage/ipc/latch.c
- src/include/cdb/cdbgang.h
- src/include/storage/latch.h
In commit https://github.com/greenplum-db/gpdb/commit/e30909fccfef42a99070f080b7c06439d6d79b29, I used the "WaitEventSet" to refactor the dispatch logic.
But in the following pgbench test, we found the performance downgrade 50% due to this commit. Did a perf on it, the bottleneck is `native_queued_spin_lock_slowpath`, means there is a lot of lock contention in it. 
After investigation, we found the culprit is a large number of concurrent creation and destruction of epoll objects. And the fix idea is simple: reuse the epoll object.
Opened this PR to fix it, and:
* no need to backport to 6x, because it doesn't use WaitEventSet.
* no special test for it, the existing tests cover the whole changes.
> Reuse the epoll object to fix the dispatcher performance downgrade

- gpMgmt/bin/gpactivatestandby
- gpMgmt/bin/gpdeletesystem
- gpMgmt/bin/gpmovemirrors
- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This commit replaces the remaining places where `master` term is being used to `coordinator` and adds an alternative flag `--coordinator-data-directory` in addition to the existing flag `--master-data-directory` in some places to maintain backward compatibility.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-master_coordinator_rename)
> Rename master instances to coordinator

- src/bin/pg_dump/pg_dump.c
The recent pg_dump fixes to handle external partitions introduced some compilation failures for Windows. Specifically, the errors were:
error C2057: expected constant expression
error C2466: cannot allocate an array of constant size 0
error C2133: 'lookupSubRootHierarchyIndex': unknown size
Fix the issue by creating the int array with pg_malloc. Also fix up a minor issue where a string was being instantiated in a weird way which was the result of improper commit splitting (the two commits referenced below were once a single commit but I split them up to make it more easier to understand).
GPDB commit references:
https://github.com/greenplum-db/gpdb/commit/8ecf11fa6eb936afa6875da76fd82332dfb793d2
https://github.com/greenplum-db/gpdb/commit/ca97e829b1403a0e72914a6aa5afc788f9de4ddc
> Fix pg_dump compilation for Windows client

- gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
make each options delimited by space.
currently only csv and text fmtopts output is delimited by space. we should make all formatters align
current output of custom formatter:
```
gpadmin=# CREATE READABLE EXTERNAL TABLE tbl_ext_fixedwidth (
s1 char(10), s2 text)
LOCATION ('file://localhost/test.tbl')
FORMAT 'CUSTOM' (formatter='fixedwidth_in', s1=10, s2=10);
gpadmin=# SELECT ext.fmtopts FROM pg_exttable AS ext, pg_class AS c WHERE ext.reloid = c.oid AND c.relname = 'tbl_ext_fixedwidth';
fmtopts
-------------------------------------------
formatter 'fixedwidth_in's1 '10's2 '10'
(1 row)
```
It should be
```
gpadmin=# SELECT ext.fmtopts FROM pg_exttable AS ext, pg_class AS c WHERE ext.reloid = c.oid AND c.relname = 'tbl_ext_fixedwidth';
fmtopts
------------------------------------------- …
```
> correct fmtopts column output format of pg_exttable

- src/test/regress/greenplum_schedule
Test "gp_fastsequence_column" was flaky in pipeline with error:
```
SELECT * from fastseq_details('INSERT INTO test_fastseq_insert%');
- logdatabase | logsegment | logseverity |             logdebug             |                                                   logmessage
--------------+------------+-------------+----------------------------------+-----------------------------------------------------------------------------------------------------------------
- regression  | seg0       | LOG         | INSERT INTO test_fastseq_insert% | Frozen insert to gp_fastsequence (rel, segno, last_sequence): (reloid, 1, 100)
- regression  | seg0       | LOG         | INSERT INTO test_fastseq_insert% | In-place update to gp_fastsequence (ctid, rel, segno, last_sequence): ((block, offset), …
```
> Run gp_fastsequence_row|column test sequentially

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Modified documentation to specify that Greenplum 6.x only supports cgroup v1.
This PR only is intended to merge to 6X_STABLE as GPDB 7 will support v2.
Review site:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-cgroup/greenplum-database/GUID-admin_guide-workload_mgmt_resgroups.html#topic71717999
> Docs cgroup version

- src/backend/commands/resgroupcmds.c
- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/backend/utils/resgroup/resgroup.c
- src/include/catalog/pg_resgroup.dat
- src/include/utils/cgroup.h
1. `pg_resgroup.dat` has defined reserved resource group oids. So, there is no need to redefine.
2. `DEFAULTAUXILIARY_OID` was renamed to `SYSTEMRESGROUP_OID`.
> Removed duplicate resource group Oid definitions

- src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
This patch reinstates the logic before commit 30e79d2, so that when there is
order by clause in the subquery, we can safely remove the order by clause. The
previous logic was not wrong, but will keep the outer reference as correlated
subquery, which is also worse plan but correct correlated plan. But in our
preprocessing step, 26th, it is doing wrong on decorrelating subquery, in which
case, we can't decorrelate actually.
The commit 30e79d2 added a fix that allows adding a project in the translator
that will echo the outer ref from within the subquery.
`select foo.c from foo where b in 
(select bar.q from bar where bar.r =10 order by foo.c);`
ORCA is currently unable to decorrelate sub-queries that contain project
nodes.For the above query the parser adds foo.c to the target list of the …
> Fix bug that Orca fails to decorrelate subqueries order by outer reference

- src/backend/Makefile
- src/backend/statistics/.gitignore
- src/backend/statistics/Makefile
- src/backend/statistics/dependencies.c
- src/backend/statistics/statistics_gram.y
- src/backend/statistics/statistics_scanner.l
Reformatting extended stats grammar, build files as per postgresql way.
> Reformat extended stats build files

- src/backend/tcop/postgres.c
Minor correction that we don't need to call pstrdup() when initializing the query string. exec_mpp_query() would fill in a dummy string if it is empty.
Noticed this when testing some specific workloads and seeing overheads in memory allocator caused by this. Didn't dig more into the impact but let's just fix it anyway.
> No need pstrdup to initialize the dispatched query string

- src/backend/utils/misc/faultinjector.c
Calls to FaultInjector_InjectFaultIfSet that provide tableName as an argument currently break early if the tableName does not match the hash entry (set by gp_inject_fault) for the fault. This is problematic because the fault must be set with a specific table name to be triggered at all.
This commit modifies the behavior to only check for matching tableName if the hash entry has a tableName set. This allows for more targeted testing.
Example:
Setting fault without a tableName will trigger for any table:
```
postgres=# SELECT gp_inject_fault('AppendOnlyStorageRead_ReadNextBlock_success', 'skip', '', '', '', 1, 100, 0, dbid)
FROM gp_segment_configuration WHERE content = 1 AND role = 'p';
gp_inject_fault
-----------------
Success:
(1 row)
postgres=# copy alter_attach_t1 to '/dev/null';
COPY …
```
> Update fault injector to better handle tableName argument.

- src/backend/cdb/cdbappendonlystorageread.c
- src/backend/commands/copy.c
- src/test/regress/expected/aoco_projection.out
- src/test/regress/sql/aoco_projection.sql
This commit implements the patch discussed in https://github.com/greenplum-db/gpdb/issues/6193#issuecomment-437487173 and backports the regression tests from d2623d889c18711b679626116d97ebf40e296ca6
In addition to improving performance by passing only the required columns for a table scan, this fixes the issue described in https://github.com/greenplum-db/gpdb/issues/6193 where COPY TO attempted to scan and decompress a dropped column without encoding information, resulting in the error
`ERROR:  decompression information missing (cdbappendonlystorageread.c:1417)`.
> Mark columns to be projected for COPY TO on AOCO table

- src/backend/executor/execUtils.c
- src/test/regress/expected/alter_table_ao.out
- src/test/regress/expected/alter_table_aocs.out
- src/test/regress/expected/table_statistics.out
- src/test/regress/sql/alter_table_ao.sql
- src/test/regress/sql/alter_table_aocs.sql
- src/test/regress/sql/table_statistics.sql
Ensure no seg entries are created for AO or AOCO tables when there are no tuples to add. That is, only create a seg entry when the tupcount is greater than 0. This ensures post-upgrade vacuum freeze succeeds. Entries can be created when there are no tuples to add when altering the distribution of an AOCO partition table which does CREATE and INSERT across, or when inserting an empty row to an AO table. For full coverage test both scenarios across AO and AOCO tables.
Specifically, pg_upgrade failures can occur when AO and AOCO parent partitions contain entries in pg_aoseg or pg_aocsseg respectively. These tables should not contain any entries as parent partitions don't carry any data.
Running into such entries can cause unexpected failures during pg_upgrade (and possibly during …
> [6X] Don't create a seg entry if there are no tuples to add

- concourse/scripts/compile_gpdb_remote_windows.bash
There is tag can be all letter, so use getversion script to get the correct version
For example, if the tag is: docs-archived-dita-source, then the script will fail by get an empty value for GIT_TAG
> [Releng][7X][Windows]Set GIT_TAG from getversion

- concourse/scripts/compile_gpdb_remote_windows.bash
There is tag can be all letter, so use getversion script to get the correct version
For example, if the tag is: `docs-archived-dita-source`, then the script will fail by get an empty value for GIT_TAG
> [Releng][6X][Windows]Set GIT_TAG from getversion

- src/include/catalog/catversion.h
- src/include/catalog/pg_proc.dat
- src/test/isolation2/expected/resgroup/resgroup_functions.out
- src/test/isolation2/sql/resgroup/resgroup_functions.sql
In the case of insert-select, the cpu_usage field contains information about master only. This leads to an error at the moment of analyzing the table, as the contents of the field do not correspond to json format. The error was fixed by setting the proexeclocation property of the function to i (PROEXECLOCATION_INITPLAN).
https://github.com/greenplum-db/gpdb/issues/14154
> Fix value in the cpu_usage column returned from the pg_resgroup_get_status() function

- src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable-Disjunction.mdp
- src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
- src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
- src/test/regress/expected/direct_dispatch.out
- src/test/regress/expected/direct_dispatch_optimizer.out
- src/test/regress/sql/direct_dispatch.sql
In ORCA direct dispatch was supported for Hash distributed table, with this update we are able to perform direct dispatch for a randomly distributed table with condition on gp_segment_id.
This update solves the problem described at the following link from ORCA perspective:
https://github.com/greenplum-db/gpdb/issues/13202
Consider the following example
create table foo_randDistr(col1 int, col2 int) distributed randomly;
insert into foo_randDistr select i,i*2 from generate_series(1, 10)I;
explain select gp_segment_id, * from foo_randDistr where gp_segment_id=0;
QUERY PLAN
-------------------------------------------------------------------------------
Gather Motion 1:1 (slice1; segments: 1) (cost=0.00..431.00 rows=1 width=12)
-> Seq Scan on foo_randdistr (cost=0.00..431.00 rows=1 width=12) …
> Support Direct Dispatch for a randomly distributed table, when filtered on gp_segment_id

- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/resgroup.c
- src/backend/utils/resgroup/test/resgroup_test.c
- src/include/utils/resgroup.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/expected/resgroup/resgroup_bypass_catalog.out
- src/test/isolation2/isolation2_resgroup_v2_schedule
- src/test/isolation2/sql/resgroup/resgroup_bypass_catalog.sql
Try to bypass query with only catalog tables.
We need to bypass the query with only `catalog` tables in resource groups in some situations, like the Database GUI client(DBeaver), which will run some catalog queries to fetch metadata.
The code just walk the parse tree and find `RangeVar` to compare it's schemaname with `pg_catalog`, it's just a few cases which be considered now. Because every query will be walked after enabling resource group, so the effort should be as small as as possible.
Following catalog query will be bypassed:
```sql
SELECT n.oid,n.*,d.description FROM pg_catalog.pg_namespace n  
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=n.oid AND d.objsubid=0 AND d.classoid='pg_namespace'::regclass
WHERE nspname='public' ORDER BY nspname;
```
But query without any …
> Try to bypass query with only catalog tables

- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_client.c
- src/backend/cdb/motion/ic_proxy_packet.c
- src/backend/cdb/motion/ic_proxy_packet.h
- src/backend/cdb/motion/ic_proxy_peer.c
- src/backend/cdb/motion/ic_proxy_router.c
icproxy processes communicate with each other with the public addr:port (see `gp_interconnect_proxy_addresses`), but no auth control here. So, any connection may connect in and send any byte, it may cause some unexpected exceptions (e.g. OOM). 
In the PR, introduces a magic number field in the `ICProxyPkt` and does a sanity check: drop the corresponding package if magic number doesn't match.
This method does not attempt to solve all problems, but only as a simple solution to avoid **internal misaccess**, looks it's good enough.
(no separated test needed, current icw_icproxy_xxx tests covered them)
(need to port to 6x later)
> Add magic number field in the ICProxyPkt

- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- src/bin/pg_rewind/pg_rewind.c
gprecoverseg should give warning and skip the recovery if there is already a running instance of pg_rewind for the segment that needs to be recovered.
Implementation:
pg_stat_activity contains entries for active pg_rewind processes. So to check for active pg_rewind processes for a failed segment, pg_stat_activity can be queried on it's source server.  Reasons to check for pg_stat_activity entry: 
- pg_rewind is invoked using --source-server connection string as it needs libpq connection with source server, which will be remote to the target server and --source-pgdata can not be used in that case. Thus pg_stat_activity will always contain entry for active pg_rewind.
- pg_rewind keeps a connection open throughout it's lifecycle, so pg_stat_activity will contain entries for active pg_rewind …
> Skip recovery of failed segment if it already has running pg_rewind

- src/backend/cdb/cdbappendonlystorageread.c
https://github.com/greenplum-db/gpdb/commit/bfe180def82d7ed14d3817feb0304d955c3a7ddf neglected to add an `#ifdef FAULT_INJECTOR` guard when change from `SIMPLE_FAULT_INJECTOR` macro to `FaultInjector_InjectFaultIfSet` function, causing non-assert enabled builds to fail to compile.
> Add ifdef for fault injector call in cdbappendonlystorageread.c

- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/resgroup-ops-linux.c
Currently, the max value of the GUC `gp_resource_group_cpu_priority` is 256,
it has a very bad effect on overall system performance, especially on 1-core or 
2-core low-end systems, since we will change the value of Cgroup `cpu.shares`
to 1024 * 256, but the other value is just 1024, which means the amount of CPU
between GPDB and other groups is 256:1.
So this PR changed the max allowed value of `gp_resource_group_cpu_priority`
to 50. 
No more test cases added, cause the `resgroup_cpu_rate_limit.source` has 
covered it.
> [6X] change the max allowed value of gp_resource_group_cpu_priority to 50

- src/backend/commands/schemacmds.c
- src/test/regress/expected/pg_stat_last_operation.out
- src/test/regress/sql/pg_stat_last_operation.sql
Updated
===========
The real issue see https://github.com/greenplum-db/gpdb/pull/14899#issuecomment-1435299158
Original PR description
===========
The test oid_wraparound consumes all remaining OIDs and wraps it around. Then, we would be reusing the OIDs we used before. That could lead to flakiness to subsequent tests such as the one we saw in `uao_dml_unique_index_update_column` (could happen to `uao_dml_unique_index_update_row` too):
```
create schema uao_dml_unique_index_update_ao_column;
+DETAIL:  Key (classid, objid, staactionname)=(2615, 27835, CREATE) already exists. 
+ERROR:  duplicate key value violates unique constraint "pg_statlastop_classid_objid_staactionname_index"
```
We are reusing the same OID of the schema we created in a previous test 'foreign_data':
```sql
regression=# …
```
> Move oid_wraparound to the bottom of the schedule

- src/backend/gporca/libgpopt/src/base/CConstraint.cpp
- src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
Issue:
The join of two columns, one varchar and one char, of matching values with trailing spaces, generates empty output.
Example:
create table foo (a varchar(3)) distributed by (a); create table bar (b char(3)) distributed by (b);
insert into foo values ('1 ');
insert into bar values ('1 ');
select a, b from foo join bar on a = b;
a | p
---+---
(0 rows)
Root cause:
According to Postgres documentation, "Values of type character are physically padded with spaces to the specified width n, and are stored and displayed that way. However, trailing spaces are treated as semantically insignificant and disregarded when comparing two values of type character."
This means, '1 ' of char(3) (1 trailing space) is stored as '1  ' (2 trailing spaces). However, when it's used for comparison, such as in …
> Fix incorrect result from hash join on char column

- src/backend/tcop/postgres.c
Remove the extra `InvalidateCatalogSnapshotConditionally` call as we are already calling this function a couple of lines above.
> Remove extra `InvalidateCatalogSnapshotConditionally` call

- src/backend/parser/parse_partition_gp.c
Currently, partition definition element can have mix of partition
definitions and also COLUMN ENCODING clauses within it.
For example:
```sql
CREATE TABLE foo (a1 int, a2 char(5)) using ao_row
partition by range (a1) (
start(1) end(5) every(1),  --> partition definition
COLUMN a1 ENCODING (compresstype=zstd) --> column encoding
);
```
Due to this when GpPartitionDefinition has single list of partDefElems
which contains partition definitions and also column encodings. Fixme
was to evaluate if current grammer can be optimized to generate
separate lists and eliminate the need for separating these later in
transformGpPartitionDefinition(). So, not essentially anything to fix,
just optimize.
After looking into the details - seems not straightforward without
modifing the grammer which will be …
> Remove merge fixme from transformGpPartitionDefinition()

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table_gp.out
- src/test/regress/sql/alter_table_gp.sql
Currently, Greenplum doesn't support foreign key constraint validation. However, we only emit a warning message saying Greenplum doesn't support it without skipping the validation process. I noticed this issue when I was running the following query:
```
CREATE TABLE fk_test_reference (col2 text unique not null); INSERT INTO fk_test_reference VALUES ('stuff');
CREATE UNLOGGED TABLE id_taptest_table (
col1 bigint,
col2 text not null default 'stuff',
col3 timestamptz DEFAULT now(),
col4 text,
FOREIGN KEY (col2) REFERENCES fk_test_reference(col2))
PARTITION BY RANGE (col1);
CREATE TABLE id_taptest_table_p3000000000 (
LIKE id_taptest_table
INCLUDING DEFAULTS
INCLUDING CONSTRAINTS
INCLUDING STORAGE
INCLUDING COMMENTS
INCLUDING GENERATED
INCLUDING INDEXES);
ALTER TABLE id_taptest_table ATTACH …
```
> [7X] Skip the foreign key constraint validation.

- src/backend/utils/time/sharedsnapshot.c
Note that when SharedSnapshotDump is called, the caller must held the SharedSnapshotLock in advance, so this commit fix the case that didn't satisfy this condition.
> Fix LWLockHeldByMe assert failure in SharedSnapshotDump

- src/backend/access/transam/xlog.c
The merge w/ PG 12.12 (https://github.com/greenplum-db/gpdb/pull/14790) backported an if branch in xlog.c which we cherrypicked before (commit 12e44a0eee8c). Removing it now.
Checked other parts of the original commit and this seems to be the only redundancy.
> Remove a redundant if(info == XLOG_OVERWRITE_CONTRECORD) in xlog.c

- src/backend/postmaster/autovacuum.c
It is making too much noise in the log. Let's make it DEBUG1, which is the same as upstream:
https://github.com/postgres/postgres/blob/master/src/backend/postmaster/autovacuum.c#L1707-L1708
> Make LOG "autovacuum: processing database..." to be DEBUG1

- src/bin/gpfdist/gpfdist.c
In an extreme case, two gpfdist occupy one port(ipv4/ipv6). The reason for this problem includes two aspects. The first one is that 'bind' is not mutually exclusive. And another is that when listening to a port fail, gpfdist will try the same port with a different protocol(ipv4 or ipv6). 
If you want to reproduce the condition by yourself, the following steps will help you.
1. Start two gpfdist by gdb. And do not forget to set a breakpoint on the line 'listen'.
2. At this time, you will find both gpfdist will stop on the line 'listen'.
3. You can choose the first gpfdist to continue execution before the second one, and the first one will listen on the port (ipv6) while another one will fail to listen. 
4. And two gpfdist will stop on the line 'listen' again. This time, you should continue …
> Double gpfdist listening to one port.

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/aosegfiles.c
- src/backend/access/appendonly/appendonly_blkdir_udf.c
- src/backend/access/appendonly/appendonly_compaction.c
- src/backend/access/appendonly/appendonly_visimap.c
- src/backend/access/appendonly/appendonly_visimap_udf.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/backend/access/appendonly/appendonlywriter.c
- src/backend/catalog/aocatalog.c
- src/backend/catalog/index.c
- src/backend/catalog/pg_appendonly.c
- src/backend/catalog/pg_attribute_encoding.c
- src/backend/commands/cluster.c
- src/backend/commands/indexcmds.c
- src/backend/commands/tablecmds.c
- src/backend/commands/vacuum.c
- src/backend/commands/vacuum_ao.c
- src/backend/utils/adt/dbsize.c
- src/backend/utils/cache/relcache.c
- src/include/catalog/pg_appendonly.h
- src/include/utils/rel.h
We used to have the pg_appendonly row for the AO/CO table stored in its relcache entry, but that somehow got lost during the PG12 merge (it is still in 6X). Now bringing it back, and utilize it wherever possible.
This commit basically does similar thing as ef92bcf151f99c9152a10c8750eee0d4dde39bc1. But due to a lot of changes in the code base and also we don't need other changes in that commit, we are not cherrypicking it directly.
Relation with https://github.com/greenplum-db/gpdb/pull/14970: both have similar purpose which is to speed up pg_appendonly lookup. For most of our current needs, relcache is probably better because we often already hold the Relation reference to the AO table, so we just need a pointer dereference instead of searching in syscache. But syscache would still be …
> Bring back pg_appendonly to relcache

- src/backend/catalog/pg_attribute_encoding.c
- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/sql/alter_table_set_am.sql
When we alter the table AM from non-AOCO to AOCO, we need to add pg_attribute_encoding entries for it. That includes checking types of the columns to decide the encoding options. But if a column is dropped, we would fail to find its type. A failure case like:
```sql
postgres=# create table ao(a int, b int) using ao_row;
CREATE TABLE
postgres=# alter table ao drop column b;
ALTER TABLE
postgres=# alter table ao set access method ao_column;
ERROR:  cache lookup failed for type 0 (format_type.c:126)
```
Now take that into consideration. Basically a dropped column will still have its entry in pg_attribute_encoding (if it's an AOCO table), until the table itself is dropped, just like pg_attribute.
> Fix error in ATSETAM to ao_column with dropped column

- src/backend/catalog/pg_type.c
- src/backend/commands/typecmds.c
- src/backend/utils/cache/lsyscache.c
- src/include/catalog/pg_type_fn.h
- src/include/utils/lsyscache.h
- src/test/regress/expected/AOCO_Compression.out
- src/test/regress/expected/column_compression.out
- src/test/regress/sql/AOCO_Compression.sql
This is a backport of main commit:
670ffac
An exception was added to the original commit to allow changing domain
type default encodings without needing a dependent array type because
dependent array types for domains are present on 7x but not 6x.
Changing a type's default encoding using ALTER TYPE name SET DEFAULT
ENCODING should also set it's dependent array type to the same encoding.
This is the expected behavior when default compression encoding is
specified on CREATE TYPE. This also fixes pg_dump and pg_upgrade since
pg_dump relies on ALTER TYPE statements to set a type's default
encoding.
Without this change user defined types with their default encodings
specified on CREATE TYPE will set default encodings on the both the type
and it's depedent array type. …
> [6X] Also set dependent array type encoding on ALTER TYPE ENCODING

- gpcontrib/gp_exttable_fdw/extaccess.c
We fixed encoding propagation to custom formatters for READABLE EXTERNAL TABLE use case in [pr-14702](https://github.com/greenplum-db/gpdb/pull/14702). However, there is still a problem for WRITABLE EXTERNAL TABLE use case where the table encoding is not propagated.
**Author:** Yongtao Huang @hyongtao-db 
**Co-author**: Jingwen Yang @jingwen-yang-yjw
> fix bug of foreign writable table encoding (7X)

- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/commands/tablecmds.c
These were causing:
tablecmds.c: In function ‘ao_aux_tables_safe_truncate’: tablecmds.c:1810:13: warning: unused variable ‘relid’ [-Wunused-variable]
1810 |         Oid relid = RelationGetRelid(rel);
|             ^~~~~
appendonlyam_handler.c: In function ‘appendonly_relation_nontransactional_truncate’:
appendonlyam_handler.c:1045:13: warning: unused variable ‘ao_base_relid’ [-Wunused-variable]
1045 |         Oid ao_base_relid = RelationGetRelid(rel);
|
These cropped up after the relcache changes for pg_appendonly in b8ed1004f09.
> Remove dead relid variables

- src/backend/access/appendonly/appendonlywriter.c
- src/backend/utils/cache/syscache.c
- src/include/utils/syscache.h
`pg_appendonly` is scanned in many occurrences but often all we need to do is just look up by table OID. Putting it in syscache avoid unnecessary table scans which is beneficial when pg_appendonly is large (i.e. there're a lot of AO tables), especially for short queries. 
Since it is already a catalog, just need to create the syscache entry for it. For now conservatively setting the bucket size to 32.
Also take the chance to use syscache lookup for pg_class in `ShouldUseReservedSegno()`.
Some performance numbers:
```sql
-- ./configure --prefix=/usr/local/gpdb7 --with-python --enable-depend CFLAGS=-O3 -fno-omit-frame-pointer CPPFLAGS=-O3 -fno-omit-frame-pointer --enable-ic-proxy
-- Targeted case: short INSERT for AO table (but run it many times to reduce variation)
create table t1(a int) …
```
> Syscache lookup for pg_appendonly

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/utils/cache/lsyscache.c
- src/include/gpopt/gpdbwrappers.h
- src/include/gpopt/translate/CContextDXLToPlStmt.h
- src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
- src/include/utils/lsyscache.h
Instead, we check the relation's partdec.
In the future I'd like to optimize getting the relation for use in Orca's relcache. For example, in many cases we don't need each attribute and statistics for each attribute, and this gets expensive.
Also removes some other unused functions
> Orca FIXME: Remove references to RelIsPartitioned

- src/backend/cdb/cdbpartition.c
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
Historically, we hardedcode searching path in Greenplum when retrieving operators for partitioned table.  When inserting data into gpdb, it looks up operators in the 'pg_catalog' schema.  That is to say, we cannot partition a table with user defined types unless we create the type and its associated operators inside the 'pg_catalog' schema.  This patch helps resolve the problem by looking up operators using the opclass that we use when defining the partitioned table.
Fix #14941
> [6X Only] Use opclass to retrieve operators for partitioned table.

- src/backend/cdb/cdbpartition.c
- src/backend/optimizer/plan/planpartition.c
- src/backend/optimizer/prep/prepunion.c
- src/include/cdb/cdbpartition.h
- src/include/nodes/relation.h
- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/sql/partition_pruning.sql
This patch partially fixes #14982 for planner. Greenplum generates PartitionSelector plan nodes when JOIN-ing partitioned tables without checking the partkey's opfamily and the equality operator's opfamily in the JOIN query's condition.
For example, we have two partitioned tables:
```
CREATE TABLE t1 (a int4, b int4) PARTITION BY LIST (b)
(PARTITION p1 VALUES (1), PARTITION p2 VALUES (-1));
CREATE TABLE t2 (a int8, b int8) PARTITION BY LIST (b)
(PARTITION p1 VALUES (1), PARTITION p2 VALUES (-1));
```
Then we define some customed operators for comparing absolute values. The complete definitions of these operators are available in my test case.
```
CREATE OPERATOR |=| (procedure = abseq4, leftarg = int4, rightarg = int4, commutator = |=|, merges);
...
CREATE OPERATOR |>=| (procedure = …
```
> [6X] Fix wrong partition pruning plan generated by planner.

- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/input/uao/bad_buffer_on_temp_ao.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/bad_buffer_on_temp_ao.source
This is attempted to _fix_ the issue https://github.com/greenplum-db/gpdb/issues/13809 (see also https://github.com/greenplum-db/gpdb/issues/6351). Actually it is more like a workaround than a complete fix and of course other proposals are welcomed to be discussed.
The problem is, when the writer aborts the transaction before any of readers, it drops the shared_buffer and unlinks corresponding temporary relfilenodes. But readers may be yet to receive the cancel signal from QD hence continue executing their part of the plan. This makes a reader has a chance to read previous unlinked relfilenode into shared_buffers and re-mark it to dirty in the case of hintbit is set, which could result to a permanent failure `could not open file` when other processes (such like bgworker or readers) …
> [6X] Tolerate failure of bad buffer flushing on a temporary table.

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/Hash-BitmapScan.mdp
- src/backend/gporca/data/dxl/minidump/Hash-IndexScan.mdp
- src/backend/gporca/libgpopt/src/operators/CLogical.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/md/IMDIndex.h
- src/backend/gporca/libnaucrates/src/md/CMDIndexGPDB.cpp
- src/backend/gporca/libnaucrates/src/md/IMDIndex.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/expected/create_index_optimizer.out
- src/test/regress/expected/hash_index.out
- src/test/regress/sql/bfv_index.sql
- src/test/regress/sql/hash_index.sql
Currently ORCA is not using hash indexes while generating plan. This PR 
allows to generate plan with hashindexes in ORCA. 
- Push down the hashindex type to dxl
- Use hash indexes at CXformSelect2BitmapBoolOp, ExfSelect2IndexGet, ExfSelect2DynamicIndexGet, 
ExfSelect2DynamicBitmapBoolOp to generate plane
- Generate a plan with indexscan by using hash indexes when bitmapscan was turned off as like planner.
setup:
create table foo(a int, b int);
create table bar(a int, b int);
insert into foo select i, i from generate_series(1, 1000000)i;
insert into bar select i, i from generate_series(1, 1000000)i;
analyze foo;
analyze bar;
create index idx on foo using hash(b);
Before Fix:
```
QUERY PLAN
----------------------------------------------------------------------------------------------------- …
```
> Support for HashIndexes in Orca

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/access/brin/README
- src/backend/access/brin/brin.c
- src/backend/access/brin/brin_revmap.c
- src/backend/access/heap/heapam_handler.c
- src/backend/access/table/tableamapi.c
- src/include/access/appendonlytid.h
- src/include/access/brin_revmap.h
- src/include/access/tableam.h
- src/include/catalog/aoseg.h
- src/include/catalog/gp_fastsequence.h
- src/test/isolation2/input/uao/brin.source
- src/test/isolation2/input/uao/limit_indexscan_inits.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/brin.source
- src/test/isolation2/output/uao/limit_indexscan_inits.source
- src/test/regress/expected/brin.out
- src/test/regress/expected/brin_ao.out
- src/test/regress/expected/brin_ao_optimizer.out
- src/test/regress/expected/brin_aocs.out
- src/test/regress/expected/brin_aocs_optimizer.out
- src/test/regress/expected/brin_optimizer.out
- src/test/regress/expected/privileges.out
- src/test/regress/sql/brin.sql
- src/test/regress/sql/brin_ao.sql
- src/test/regress/sql/brin_aocs.sql
This PR introduces a new table AM API for unifying code for block traversal used in BRIN indexes. To ensure that the changes don't break existing functionality, we had to bring back specific-range-summarization for heap tables. Also, we extended and improved the tests significantly. Please review commits individually.
This also fixes https://github.com/greenplum-db/gpdb/issues/14843.
> brin: table AM API for block traversal

- gpMgmt/bin/gppylib/heapchecksum.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
backported from bb3d18eba40025fc10c49a4ab982d4780ad3846f
Currently, when doing an incremental recovery in verbose mode with "gprecoverseg -v", we record the pg_controldata output of only source data directory. We can also record the pg_controldata output of the target data directory before running pg_rewind.
Context: Recently there have been multiple pg_rewind failures due to missing wal files. Often times at the time of performing incremental recovery(pg_rewind), the target segments have been shutdown for quite sometime, and if the incremental recovery failed, users usually choose to perform a full recovery as a workaround to bring the target segments up. This sequence of operations would erase the clue of what had happened on the target segment before it went down in the first place. …
> [6X backport] Record pg_controldata output of failed segment

- src/backend/executor/nodeAgg.c
- src/backend/gporca/data/dxl/minidump/AggregateWithSkew.mdp
- src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
- src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate2.mdp
- src/backend/gporca/data/dxl/minidump/DQA-InnerJoin-GroupBy-HashAggregate.mdp
- src/backend/gporca/data/dxl/minidump/DqaNoRedistribute.mdp
- src/backend/gporca/data/dxl/minidump/MultiColumnDQA-InnerJoin-GroupBy-HashAggregate.mdp
- src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbMultipleCol-DistinctOnDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
- src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp
- src/test/isolation2/expected/spilling_hashagg.out
- src/test/isolation2/expected/spilling_hashagg_optimizer.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/spilling_hashagg.sql
- src/test/regress/expected/gp_dqa_optimizer.out
In a two-stage hash aggregate plan, if the local stage aggregate hash table fills up then it has one of two options:
1) spill to disk
2) stream to next stage aggreegate.
Issue is if we stream a DQA to next stage and the next stage isn't prepared to handle duplicates, then we could encounter wrong results. That was observed in the following plan:
SELECT a, COUNT(DISTINCT b) FROM t GROUP BY a;
QUERY PLAN
--------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..3366.93 rows=7 width=12)
->  HashAggregate  (cost=0.00..3366.93 rows=3 width=12)
Group Key: a
->  HashAggregate  (cost=0.00..3212.44 rows=1273152 width=8)
Group Key: a, b
->  Seq Scan on test  (cost=0.00..640.00 rows=10000034 width=8)
Optimizer: Pivotal …
> Force two-stage local aggregate to remove duplicates

- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/input/uao/bad_buffer_on_temp_ao.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/bad_buffer_on_temp_ao.source
This is backporting https://github.com/greenplum-db/gpdb/pull/14949.
This is intended to fix the issue #13809 (see also #6351). The problem is, when the writer aborts the transaction before any of readers, it drops the shared_buffer and unlinks corresponding temporary relfilenodes. But readers may be yet to receive the cancel signal from QD hence continue executing their part of the plan. This makes a reader has a chance to read previous unlinked relfilenode into shared_buffers and re-mark it to dirty in the case of hintbit is set, which could result to a permanent failure could not open file when other processes (such like bgworker or readers) attempt to evict or flush this dirty buffer to disk.
The patch is trying to address a kinda like semantic contradiction that a temporary object …
> [7X BKPT] Tolerate failure of bad buffer flushing on a temporary table.

- src/backend/parser/parse_partition.c
- src/backend/utils/cache/lsyscache.c
- src/include/utils/lsyscache.h
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
When partitioning by list, the PARTITION BY transformation makes a partition rule where each partition key uses an equality operator "=" that is not schema-qualified. Later on in the CREATE TABLE logic during type coercion, it tries to look up the equality operator by going through OprCacheHash which requires a hash key that contains the search_path to look in. This works for general cases but not for when the partition key is a custom type and its equality operator is in a schema that is not in the session's search_path (nor default pg_catalog). Things are even worse when dealing with pg_restore (and in relation pg_upgrade) where the search_path is always set to blank at the beginning of the SQL restore so even custom operators created in the public schema would have issues.
To fix the …
> Use partition key opclass to get equality operator for PARTITION BY LIST

- src/backend/cdb/cdbcopy.c
- src/include/cdb/cdbcopy.h
- src/test/isolation2/expected/ao_unique_index.out
- src/test/isolation2/expected/aocs_unique_index.out
This pr fixes the the bug reported in [issue-14126](https://github.com/greenplum-db/gpdb/issues/14126).
**Bug Info:**
For replicated table, COPY reports incorrect number of inserted rows. The wrong result is showed as below:
```
postgres=# create table foox(i int) distributed replicated;
CREATE TABLE
postgres=# copy foox from program 'seq 1 10';  <-------- we only insert 10 data in fact.
COPY 30                                        <-------- count multiplied by number of segments (3).
``` 
**Diagnose:**
For replicated table, gpdb stores the same data on each segment. So, when we insert _M_ tuples, we actually insert _M_ tuples into _N_ segments, totally _N_ times _M_. But we're actually only inserting _M_ valid tuples. So in this case, gpdb just needs to return the number of tuples _M_ …
> COPY should report correct No. of inserted rows for replicated table (7X)

- gpMgmt/bin/gpcheckcat
After we removed blkdiridxid and visimapidxid from pg_appendonly (commti c16943a6e1e528acb6a8f360119a7f7ab3e3d860), we can no longer query them directly from pg_appendonly. The above commit missed addressing one in gpcheckcat. Address now.
This fix just makes the query identical as before. However, when I tested this it seems that the query (including the original) could not actually achieve what it wants to achieve (find out different owners) for block directory relation AND its index. I feel that it's a quite outdated query and we should update it. Will create issue to address it separately.
> Fix a gpcheckcat query after removing blkdiridxid

- src/test/regress/expected/aggregates.out
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/sql/aggregates.sql
This test case needs to be a on a coordinator-only table, but using pg_class is flaky as we'll sometimes choose an index-only scan and other times a seq scan.
> Fix flaky aggregates test

- src/backend/storage/smgr/smgr.c
This PR is trying to fix the issue of #14561, we should not invoke `mdinit()`
directly at the end of the function `smgr_init_standard()`.
No more tests are needed, cause current tests are enough to cover.
> remove reduant invocation of `mdinit()` at `smgr_init_standard()`

- gpMgmt/bin/gpinitsystem
in bash `[` and `]` is not a keyword, that thing is an executable file in `PATH`
add one space after `[` and before `]`
> gpinitsystem: fix bash syntex when remote locale is not correct

- src/backend/commands/analyze.c
- src/test/regress/expected/analyze.out
- src/test/regress/sql/analyze.sql
This pr can fix the bug reported in [issue 14644](https://github.com/greenplum-db/gpdb/issues/14644) for 6X_STABLE.
It is backport from [pr 14978](https://github.com/greenplum-db/gpdb/pull/14978).
**Bug Detail:**
After analyzing a table with a dropped subclass, the value on the coordinator may differ from the segments. See the SQL result with bug below:
```
gpadmin=# CREATE TYPE test_type2 AS (a int, b text);
CREATE TYPE
gpadmin=# CREATE TABLE test_tbl2 OF test_type2;
CREATE TABLE
gpadmin=# CREATE TABLE test_tbl2_subclass () INHERITS (test_tbl2);
CREATE TABLE
gpadmin=# DROP TABLE test_tbl2_subclass;
DROP TABLE
gpadmin=# analyze;
ANALYZE
gpadmin=# select gp_segment_id, relhassubclass from pg_class where relname = 'test_tbl2';        
gp_segment_id | relhassubclass …
```
> bug fix: catalog inconsistency of relhassubclass after analyze (6X)

- src/bin/pg_dump/pg_dump.c
I met this error when I tried to use pg_dump in the main branch to dump ao table from gpdb6.
The step to reproduce is:
```
[gpadmin@localhost gpcopy] $ pg_dump --version
pg_dump (PostgreSQL) 12.12
[gpadmin@localhost gpcopy] $ pg_dump --gp-syntax -h <host-of-gp6> -p 6000 -U gpadmin -s -t '"public"."my_ao"' 'gpadmin'
Segmentation fault (core dumped)
```
The ao table structure:
```
[gpadmin@mdw ~] $ psql
psql (9.4.26)
gpadmin=# \d+ public.my_ao
Append-Only Table "public.my_ao"
Column |  Type   | Modifiers | Storage | Stats target | Description
--------+---------+-----------+---------+--------------+-------------
c      | integer |           | plain   |              |
Compression Type: zlib
Compression Level: 5
Block Size: 32768
Checksum: t
Distributed by: (c)
Options: …
```
> Fix pg_dump small bug

- src/bin/pg_dump/pg_dump.c
The encoding clause is necessary to maintain catalog consistency for dropped columns in pg_attribute_encoding across major version upgrades. Without this, the column encoding will be set to the hardcoded server default in the new cluster. If the encoding was modified from the default in the old cluster, an error would occur if the column needed to be scanned for any reason.
Resolves the issue `ERROR:  decompression information missing` after a column is dropped from an AO/CO table and the table is run through pg_upgrade
> In binary upgrade, dump the encoding clause for dropped columns

- src/backend/catalog/gp_toolkit.sql
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v1.out
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/expected/resgroup/resgroup_views.out
since commit c25db0c support resgroup with memory_limit, adds it to gp_resgroup_config view.
> show memory_limit information in gp_toolkit.gp_resgroup_config view

- src/backend/executor/nodeTupleSplit.c
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
QE will hang in `ExecTupleSplit()` while executing the following query.
```
SELECT DQA_1(expr1) filter (subquery1), DQA_2(expr2) ...
```
If a tuple is filtered out by DQA_1's filter, `filter_out` will be set to true. Because dqa2 has no filters, `filter_out` will not be set to false on the next loop. Then it's an endless loop.
The solution is simple, if current Expr has no filter, set `filter_out` to false.
> Fix hang of multi-dqa with filter in planner

- src/backend/cdb/cdbgroupingpaths.c
- src/backend/optimizer/plan/planner.c
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
`fetch_multi_dqas_info()` will push the MultiDQA's filter to TupleSplit, then get rid of final and partial DQA aggref filter. If we use the same path target as single-stage aggregation, single-stage aggregation will lose the filter of MultiDQA.
For instance:
```
postgres=# set enable_hashagg = off;
SET
postgres=# explain (verbose, costs off) select count(distinct a) filter(where a>1), count(distinct b) from issue14728;
QUERY PLAN
-----------------------------------------------------
Aggregate
Output: count(DISTINCT a), count(DISTINCT b)
->  Gather Motion 3:1  (slice1; segments: 3)
Output: a, b
->  Seq Scan on public.issue14728
Output: a, b
Settings: enable_hashagg = 'off', optimizer = 'off'
(8 rows)
```
> Create a copy of the path target for multi-stage aggregation

- contrib/pg_upgrade/greenplum/check_gp.c
- src/bin/pg_dump/pg_dump.c
Dump ALTER statements for child tables with different schemas
ALTER TABLE name SET SCHEMA statements are dumped to support restore and
upgrade of child partitions whose schemas are different than their
parents. In binary upgrade mode, child partition oids are reserved using the
parent's schema because that is where they initially land on creation.
pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-cm-kyeap-vmware?group=all
> [6x] Dump ALTER statements for child tables with different schemas

- src/backend/cdb/motion/ic_udpifc.c
Finish the job started in 13902f8b335.
Improvements:
(1) We should print the error message from errno iff recv returned -1.
We were printing the errno message even if recv returned 0 (indicating
conn close).
(2) We should print a specific error message when 0 is returned from
recv(), or if the backend socket is invalid.
> Enhance logging for dispatch conn liveness checks

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/sql/alter_table_set_am.sql
When change AM to heap, the exisiting reloptions were not cleared. The root cause is that we would skip setting reloptions if there's no reloptions being passed in with the ATSETAM command. Note that we only skip such for heap table, but not AO table, which is why this issue only existed for heap.
The fix is to always replace the reloptions when AM changed.
Also add the missing test case and a lot more.
Resolve issue #15080.
> Fix ATSETAM to heap that doesn't clear reloptions for partitioned root

- src/backend/catalog/pg_attribute_encoding.c
Anum_pg_attribute_encoding_attnum is effectively an int16. We should use
F_INT2EQ and not F_OIDEQ, as oids are uint32.
> pg_attribute_encoding: Use correct scan regproc

- src/bin/pg_rewind/filemap.c
The log directory can often be symlinked in the same way the pg_wal
directory is. Today, even if BOTH the source and target servers have
their log directories symlinked, pg_rewind will run into the error:
"log" is of different type in source and target
This is because when we use the libpq query to fetch the filemap from
the source server, we consider the log directory as a directory, even if
it is a symlink. This is because pg_stat_file() is used in that query in
libpqProcessFileList() and pg_stat_file() returns isdir=t for symlinks
to directories.
This shortcoming is somewhat called out:
* XXX: There is no backend function to get a symbolic link's target in
* general, so if the admin has put any custom symbolic links in the data
* directory, they won't be copied correctly.
We could fix …
> Fix pg_rewind when log is a symlink

- gpMgmt/bin/gpcheckperf
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Currently, there is a bug in the `getMemory()` function in `gpcheckperf` because of the way we check the return code of the `run()` method which is called inside `getMemory()`. The `run()` method returns an integer value of `zero` in case of success and a `non-zero` value if it fails.
We are checking this value using the condition `if not ok` which is incorrect because when the `run()` method succeeds (`ok = 0`), the condition would result as `False` causing the `getMemory()` function to assume that the `run()` method failed but in reality, it did not.
A simple fix would be to change the condition from `if not ok` to `if ok != 0` to check for any possible failure from the `run()` method.
Further, the way `getMemory()` handles errors is also incorrect. It just returns `0` whenever there is …
> gpcheckperf: Fix memory calculation function

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
Fix broken `explain_format` regress test case: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs//builds/169
Co-Authored by : @Tao-T
> Fix icw_gporca_jit_rocky8 failure.

- src/backend/cdb/cdbvars.c
- src/test/regress/expected/guc_gp.out
- src/test/regress/sql/guc_gp.sql
The GPDB's document says that:
> `statement_mem`
> Sets the maximum memory limit for a query. Helps avoid out-of-memory errors on a segment host during query processing as a result of setting statement_mem too high.
However, there is no any ERROR when I set `statement_mem` to greater than `max_statement_mem`.
So, `max_statement_mem` loses protection for `statement_mem`.
```sql
postgres=# select version();
version
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PostgreSQL 12.12 (Greenplum Database 7.0.0-beta.1+dev.90.g7ac8734891 build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2), 64-bit …
```
> Throws ERROR when statement_mem is set to greater than max_statement_mem

- src/backend/parser/parse_partition_gp.c
- src/test/regress/expected/bfv_partition.out
- src/test/regress/expected/partition1.out
- src/test/regress/output/partition_ddl.source
- src/test/regress/sql/partition1.sql
Historically, Greenplum is hardcoding the schema when looking up the '+' operator for the range partitioned table creation DDL `(START (XXX) END (YYY) EVERY (ZZZ))`.
This patch simply removes the hardcoded schema name which is similar to the logic behind processing `BETWEEN XXX AND YYY` syntax. When evaluating the `BETWEEN XXX AND YYY` clause, PostgreSQL looks up the `'>='` and `'<='` operators in the current searching path.
e.g.,
```
CREATE TYPE myint;
CREATE FUNCTION myint_in(cstring) RETURNS myint AS 'int4in' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE FUNCTION myint_out(myint) RETURNS cstring AS 'int4out' LANGUAGE INTERNAL IMMUTABLE STRICT;
CREATE TYPE myint (INPUT=myint_in, OUTPUT=myint_out, passedbyvalue, internallength=4);
CREATE FUNCTION myint_lt(myint, myint) RETURNS boolean AS …
```
> [7X] Fix hardcoded schema in partition creation DDL.

- src/backend/commands/schemacmds.c
- src/test/regress/expected/pg_stat_last_operation.out
- src/test/regress/sql/pg_stat_last_operation.sql
Backport from https://github.com/greenplum-db/gpdb/pull/14899
Due to some test flakiness, we found that when we drop a schema, we were not dropping the meta tracking rows in pg_stat_last_operation associated with the schema. We used to do that in RemoveSchema: c83fb8108854. But it was lost in 4750e1b65518a5575e0cc75eb6716cc7d5594139 which got rid of RemoveSchema and only used RemoveSchemaById ever since.
Now add back MetaTrackDropObject in RemoveSchemaById. Add test case too.
> [6X] Drop metadata tracking info when dropping schemas

- src/backend/postmaster/autovacuum.c
It is making too much noise in the log. Let's make it DEBUG1, which is the same as upstream:
https://github.com/postgres/postgres/blob/master/src/backend/postmaster/autovacuum.c#L1707-L1708
The 7X PR: https://github.com/greenplum-db/gpdb/pull/15045
> [6X] Make LOG "autovacuum: processing database..." to be DEBUG1

- src/bin/pg_dump/pg_backup_db.c
Resolves an issue where `pg_dump` would segfault when called with `--binary-upgrade` flag and 5 or fewer total arguments. The bug was introduced during PG12_12 merge https://github.com/greenplum-db/gpdb/commit/fb93f784fc9c31f12361462653d325fdce01207d
> Fix segfault when calling pg_dump with --binary-upgrade

- src/bin/pg_rewind/filemap.c
Backported from 7X commit: b9adc4e with log turned into pg_log and
conflicts resolved by changing pg_wal to pg_xlog
The log directory can often be symlinked in the same way the pg_wal
directory is. Today, even if BOTH the source and target servers have
their log directories symlinked, pg_rewind will run into the error:
"log" is of different type in source and target
This is because when we use the libpq query to fetch the filemap from
the source server, we consider the log directory as a directory, even if
it is a symlink. This is because pg_stat_file() is used in that query in
libpqProcessFileList() and pg_stat_file() returns isdir=t for symlinks
to directories.
This shortcoming is somewhat called out:
* XXX: There is no backend function to get a symbolic …
> [6X] Fix pg_rewind when pg_log is a symlink

- src/bin/pg_dump/pg_dump.c
The encoding clause is necessary to maintain catalog consistency for dropped columns in pg_attribute_encoding across major version upgrades. Without this, the column encoding will be set to the hardcoded server default in the new cluster. If the encoding was modified from the default in the old cluster, an error would occur if the column needed to be scanned for any reason.
Resolves the issue `ERROR:  decompression information missing` after a column is dropped from an AO/CO table and the table is run through pg_upgrade.
Backported from https://github.com/greenplum-db/gpdb/pull/15106
Resolves issue https://github.com/greenplum-db/gpdb/issues/6193
> [6X]: In binary upgrade, dump the encoding clause for dropped columns

- src/backend/commands/tablecmds.c
- src/bin/gpfdist/regress/.gitignore
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
- src/bin/pg_dump/pg_dump.c
- src/test/regress/expected/pg_dump_binary_upgrade.out
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/sql/pg_dump_binary_upgrade.sql
1) Don’t dump dropped columns for external tables
Dropped columns are preserved to create binary-compatible files on-disk. That is pg_dump must ensure the same physical column order, including dropped columns, as in the original. However, since the external table DDL needs to map directly to the underlying data there is no need to preserve dropped columns. Simplify by removing this logic.
2) Support dumping external tables with serial column types
Serial column types are dumped in components and added together. The CREATE TABLE is dumped, followed by the CREATE SEQUENCE, and then attached to the table column with ALTER TABLE ONLY public.foobar ALTER COLUMN b SET DEFAULT nextval('public.foobar_b_seq'::regclass);
The restore fails with “unsupported ALTER command for external table” causing …
> [6X] support dumping external tables with serial column types

- src/backend/cdb/motion/ic_proxy_addr.h
When compiling proxy interconnect code on MacOS, it fails to compile with the following error:
```
In file included from ic_proxy_main.c:23:
./ic_proxy_addr.h:35:17: error: use of undeclared identifier 'HOST_NAME_MAX'
char            hostname[HOST_NAME_MAX];        /* hostname or IP */
^
ic_proxy_main.c:112:14: error: use of undeclared identifier 'HOST_NAME_MAX'
char            name[HOST_NAME_MAX];
^
ic_proxy_main.c:168:14: error: use of undeclared identifier 'HOST_NAME_MAX'
char            name[HOST_NAME_MAX] = "unknown";
```
Some systems like FreeBSD or MacOS do not define HOST_NAME_MAX so we need to define it ourselves. Using the POSIX value of 255 seems to be a safe fallback value so define it as such if HOST_NAME_MAX is unavailable.
Will need to backport this to 6X_STABLE as well.
> Fix ic_proxy compilation for when HOST_NAME_MAX is unavailable

- src/backend/cdb/motion/ic_udpifc.c
COMMERROR doesn't fail the query. ERROR does. This was an oversight in
fbde68090e7.
> Use ERROR for dispatcher liveness checks

- src/backend/gporca/libgpos/include/gpos/memory/CMemoryPool.h
In CI pipeline there were occassional test failures due to ORCA fallback with following stacktrace.
```
+INFO:  GPORCA failed to produce a plan, falling back to planner
+DETAIL:  CSyncHashtable.h:109: Failed assertion: IsValid(key) && "Invalid key is inaccessible"
+Stack trace:
+1    gpos::CException::Raise + 227
+2    <symbol not found> + 15235666
+3    gpos::CMemoryPoolManager::CreateMemoryPool + 653
+4    gpos::CAutoMemoryPool::CAutoMemoryPool + 34
+5    gpopt::CColumnFactory::CColumnFactory + 80
+6    gpopt::COptCtxt::PoctxtCreate + 77
+7    gpopt::CAutoOptCtxt::CAutoOptCtxt + 54
+8    gpopt::COptimizer::PdxlnOptimize + 411
+9    COptTasks::OptimizeTask + 850
+10   gpos::CTask::Execute + 52
+11   gpos::CWorker::Execute + 36
+12   gpos::CAutoTaskProxy::Execute + 97
+13   gpos_exec + …
```
> [ORCA] Fix flaky "Invalid key is inaccessible" fallback

- gpMgmt/bin/gpcheckresgroupv2impl
As the PR title said, just add permission check to file /sys/fs/cgroup/cgroup.procs.
Make sure `gpstart -rai` will definitely succeed if the customer uses `gpconfig` to set the
gp_resource_manager to group-v2.
> add permission check to file /sys/fs/cgroup/cgroup.procs

- src/backend/storage/smgr/smgr.c
This is the backport of  #15091
This PR is trying to fix the issue of #14561, we should not invoke `mdinit()` directly at 
the end of the function `smgr_init_standard()`.
No more tests are needed, cause current tests are enough to cover.
> [6X] remove reduant invocation of `mdinit()` at `smgr_init_standard()`

- contrib/auto_explain/Makefile
- contrib/auto_explain/auto_explain.c
- contrib/auto_explain/expected/memory_leaks.out
- contrib/auto_explain/sql/memory_leaks.sql
- src/backend/commands/explain.c
- src/backend/commands/explain_gp.c
- src/backend/tcop/pquery.c
- src/include/cdb/cdbexplain.h
Statistic context wasn't destroyed with query descriptor, so queries with multiple call of sql functions consumed a lot of memory.
```
LOAD 'auto_explain';
SET auto_explain.log_nested_statements=true;
SET auto_explain.log_min_duration = 0;
SET auto_explain.log_analyze = true;
explain analyze select information_schema._pg_truetypid(a, t) from (
select a as a, t as t from pg_type t
join pg_attribute a on a.atttypid = t.oid
where typtype = 'd' limit 1
) at join generate_series(1, 9000000) gc on true;
```
Changes:
1. Add cdbexplain_showStatCtxFree() function to release memory allocated for statistic context. The function is called from FreeQueryDesc() when the statistic context exists. To check whether the context exists the assigning NULL value to the showstatctx field of …
> Fix memory leaks in auto_explain

- gpcontrib/gp_exttable_fdw/extaccess.c
The function externalgettup_custom() is to handle custom formatter logic when loading data with external tables. But if custom protocol like PXF is used to loading data, the EOF is not reached when the last content of data is returned, the EOF is reached only when the last reading returns 0. So in the current logic of function externalgettup_custom(), it may lose the chance for custom formatter to handle the last line of data.
This commit removes the using of raw_buf_len, instead the formatter->fmt_databuf which provides the real data is used. So we check the length of this buffer to give custom formatter last chance to handle the last line of data. Even if the last line is not complete, it is the custom formatter's responsibility to report this.
The right way to return FMT_NEED_MORE_DATA …
> Fix custom formatter handling logic.

- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_client.c
- src/backend/cdb/motion/ic_proxy_iobuf.c
- src/backend/cdb/motion/ic_proxy_peer.c
- src/test/regress/expected/ic_proxy_socket.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/ic_proxy_socket.sql
My previous comment 57a314073a59c6ec8ab2b0dfc7ed7f578a4568d3 added magic number field in the ICProxyPkt. Some bugs are found in the process of porting it to 6x: they are related to the invalid value of ICProxyPkt field, current code doesn't handle them since they don't exist in the normal package.
All of them have been fixed in the 6x PR: https://github.com/greenplum-db/gpdb/pull/14998, so this PR backport the fix code and test cases into main branch.
> Fix IC bugs in ic_proxy_ibuf_push()

- src/backend/commands/analyze.c
- src/test/regress/expected/analyze.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/analyze.sql
For table AMs that support column projection (AOCO), we can
optimize the table scan when acquiring sample rows by projecting only
columns that have not been dropped to the table scan.
> 6X: Don't scan dropped columns during ANALYZE for AOCO tables.

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table.out
- src/test/regress/sql/alter_table.sql
Description
========
This PR attempts to resolve a FIXME in `ATExecAddColumn` regarding fast ADD COLUMN w/ non-NULL default values for ao_column tables:
We disabled both AO and AOCO tables from the upstream feature of _not_ rewriting table when there's non-NULL default (commit 16828d5c0273b4fe5f10f42588005f16b415b2d8). However, we should be able to support it at least for AOCO tables by just writing the new column, which we already have the facility. Then, fetching from the table should be able to see the new values which are already written.
Note that, pg_attribute.attmissingval will be populated in such cases for AOCO tables, but they won't be used yet. We would be leveraging that field later when we are going to optimize even the column rewrite away.
Also note that, this column rewrite …
> Resolve a FIXME for ADD COLUMN for AOCO table

- src/backend/utils/resgroup/resgroup_helper.c
- src/include/catalog/catversion.h
- src/include/catalog/pg_proc.dat
- src/test/isolation2/expected/resgroup/resgroup_dumpinfo.out
- src/test/isolation2/sql/resgroup/resgroup_dumpinfo.sql
In the case of insert-select, the value column contained information about coordinator only. The error was fixed by setting the proexeclocation property of the function to i (PROEXECLOCATION_INITPLAN).
https://github.com/greenplum-db/gpdb/issues/14154
Execution of the "SELECT * FROM pg_resgroup_get_status_kv(NULL);" query resulted in a segmentation fault. NULL check has been added.
The dumpResGroupInfo() function was called 2 times per query. Now it is called only once.
Simplification of the function code.
> Fix the pg_resgroup_get_status_kv() function

- gpMgmt/bin/Makefile
An error occurred when `make install` on Mac m1:
"PyYAML-5.3.1/build/lib*-3.*/*: No such file or directory"
Since the lib name format on Mac m1 is different from x86,
it is 'xx-cpython-**3.8**.so' on x86 and 'xx-cpython-**38**.so' on Mac m1.
This patch we removed the unnecessary '.', so both x86 and arm will be fine.
> fix format error of the lib name on Mac m1

- src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable-Disjunction.mdp
- src/backend/gporca/data/dxl/minidump/DirectDispatch-RandDistTable.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
- src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXLUtils.h
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXLUtils.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CDirectDispatchTest.cpp
- src/test/regress/expected/direct_dispatch.out
- src/test/regress/expected/direct_dispatch_optimizer.out
- src/test/regress/sql/direct_dispatch.sql
In ORCA direct dispatch was supported for Hash distributed tables, with this update we are able to perform direct dispatch for a randomly distributed table with condition on gp_segment_id.
CODE CHANGES
A patch was added in "CTranslatorExprToDXLUtils::SetDirectDispatchInfo(,,,,)" to check the condition if the table is a 'Random distrubuted table'. If yes, then a newly added function "CTranslatorExprToDXLUtils::GetDXLDirectDispatchInfoRandDist(,,,)" is called to check whether 'direct dispatch' is feasible or not.
This update solves the problem described at the following link from ORCA perspective:
https://github.com/greenplum-db/gpdb/issues/13202
PR LINK (main version)
https://github.com/greenplum-db/gpdb/pull/14725
> Support Direct Dispatch for a randomly distributed table(6X_STABLE)

- src/backend/executor/nodeTupleSplit.c
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
we cannot get corrent number of projecting targets for executing TupleSplit Node if wrong maxAttrNum in TupleSplitState, that cause wrong results in multi-dqa sql. like sql
```
select count(distinct a), count(distinct b) from dqa_f4 group by c;
For each splited tuple, we also need to project column `c` as group column besieds
distinct column `a` and `b`. As a result, toal maxAttrNum of TupleSplit is three instead of two, 
which also decided totals projection columns of Node Tuplesplit.
```
To figure maxAttrNum correctly, we need to calculate again after we initiated all elements in TupleSplitState.
> Fix wrong number of maxAttrNum in TupleSplitState

- src/backend/catalog/system_views.sql
- src/backend/storage/ipc/procsignal.c
- src/backend/tcop/postgres.c
- src/backend/utils/adt/Makefile
- src/backend/utils/adt/mcxtfuncs.c
- src/backend/utils/init/globals.c
- src/backend/utils/mmgr/aset.c
- src/backend/utils/mmgr/generation.c
- src/backend/utils/mmgr/mcxt.c
- src/backend/utils/mmgr/slab.c
- src/include/catalog/catversion.h
- src/include/catalog/pg_proc.dat
- src/include/catalog/pg_type.dat
- src/include/miscadmin.h
- src/include/nodes/memnodes.h
- src/include/storage/procsignal.h
- src/include/utils/memutils.h
- src/test/regress/expected/gp_log_mem_dispatch.out
- src/test/regress/expected/misc_functions.out
- src/test/regress/expected/misc_functions_optimizer.out
- src/test/regress/expected/opr_sanity.out
- src/test/regress/expected/rules.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/gp_log_mem_dispatch.sql
- src/test/regress/sql/misc_functions.sql
Backport multiple commits from upstream to add `pg_backend_memory_contexts` view and `pg_log_backend_memory_contexts` function.  
NOTE: this does not bring `pg_log_backend_memory_contexts` up to current state of upstream, as there was significant refactoring work done around interrupts that blocks the commits that add the ability to log memory contexts for auxiliary processes.  Per team conversation, that is out of scope at this time.
Implement a `gp_log_backend_memory_contexts` that dispatches calls to this function for a target session on target/all segments and responds with which segments report success.
> Backport log mem ctx

- src/backend/commands/vacuum_ao.c
- src/backend/gpopt/translate/CPartPruneStepsBuilder.cpp
This commit fixes the following compiler warnings:
vacuum_ao.c:738:1: warning: ‘init_vacrelstats’ was used with no prototype before its definition [-Wmissing-prototypes]
738 | init_vacrelstats()
| ^~~~~~~~~~~~~~~~
CPartPruneStepsBuilder.cpp: In member function ‘PartitionedRelPruneInfo* gpdxl::CPartPruneStepsBuilder::CreatePartPruneInfoForOneLevel(gpdxl::CDXLNode*)’: CPartPruneStepsBuilder.cpp:83:29: warning: comparison of integer expressions of different signedness: ‘gpos::ULONG’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare]
83 |         for (ULONG i = 0; i < pinfo->nparts; ++i)
|                           ~~^~~~~~~~~~~~~~~
> Fix 2 compiler warnings.

- gpMgmt/bin/gpcheckperf
In gpcheckperf, a remaining "python" reference exists. This commit renames it to "python3" and allows it to run when the symbolic link /usr/bin/python pointing to /usr/bin/python3 does not exist.
Tl;dr - An attempt was made to update all Greenplum utilities to reference 'python3'. A reference was left unchanged in gpcheckperf.
Python 3 installations by default do not create the symbolic link /usr/bin/python --> /usr/bin/python3. This has been observed in Python 3 installation3 on Rockylinux 8 & 9 and Ubuntu 20.04 & 22.04.
In the case of gpcheckperf, when invoked, the output below reveals the "Error" a user receives when /usr/bin/python does not exist:
```
gpadmin@cdw:~$ /usr/local/gp7/bin/gpcheckperf -h cdw -d /data -r d -S 1 -v
SETUP 2023-03-12T17:26:27.967030 …
```
> gpcheckperf - Update a Python 3 reference of "python" to "python3"

- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/vars/common_prod.yml
update var-name frequency trigger from centos7 to rhel7 , centos6 to rhel6
> Fix generate pipeline error for rhel8 and oel8

- gpdb-doc/markdown/ref_guide/extensions/madlib.md
equivalent doc changes as in 6x PR https://github.com/greenplum-db/gpdb/pull/15117 **PLUS** i removed some references to older v1.13. and 1.15 madlib versions.  let me know if that was not the right thing to do ...
> docs - madlib v1.21 available for greenplum 5 (5X_STABLE)

- src/backend/catalog/index.c
- src/test/regress/expected/pg_stat_last_operation.out
- src/test/regress/sql/pg_stat_last_operation.sql
Note that, most system catalog tables should be consistent between coordinator and segments. However, for now, meta tracking stuffs are done by coordinator only, so the changes to `pg_last_stat_operation` should only be made by coordinator. But for index DDL, changes are also made on QEs. This commit fix that.
> Fix index DDL operations are recorded in QEs' pg_last_stat_operation

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/vars/common_prod.yml
This PR includes two pipeline changes:
- Bring the centos6 and centos7 pipeline back
- Update the test_gpdb_clients_windows resource to use bin_gpdb_centos7_rc
> Bring the pipeline centos6 and centos7 back

- src/backend/nodes/outfast.c
- src/backend/nodes/readfast.c
- src/backend/nodes/readfuncs.c
- src/test/regress/expected/select_distinct.out
- src/test/regress/expected/select_distinct_optimizer.out
- src/test/regress/sql/select_distinct.sql
This pr can fix the bug reported in [issue 15033](https://github.com/greenplum-db/gpdb/issues/15033)
Add identification of `NOT DISTINCT` node as `DISTINCT` under `src/backend/nodes`.
**Signed-off-by**: Yongtao Huang <yongtaoh@vmware.com>
> bug fix: unable to understand 'IS NOT DISTINCT' (7X)

- src/bin/gpfdist/gpfdist.c
In an extreme case, two gpfdist occupy one port(ipv4/ipv6). The reason for this problem includes two aspects. The first one is that 'bind' is not mutually exclusive. And another is that when listening to a port fail, gpfdist will try the same port with a different protocol(ipv4 or ipv6).
If you want to reproduce the condition by yourself, the following steps will help you.
1. Start two gpfdist by gdb. And do not forget to set a breakpoint on the line 'listen'.
2. At this time, you will find both gpfdist will stop on the line 'listen'.
3. You can choose the first gpfdist to continue execution before the second one, and the first one will listen on the port (ipv6) while another one will fail to listen.
4. And two gpfdist will stop on the line 'listen' again. This time, you should continue …
> [6x] Double gpfdist occupy one port.

- concourse/pipelines/templates/gpdb-tpl.yml
error: invalid pipeline config:
invalid resources:
resource 'bin_gpdb_centos7_rc' is not used
> Fix set -dev pipeline error .

- src/backend/executor/functions.c
- src/test/regress/expected/qp_functions.out
- src/test/regress/sql/qp_functions.sql
Hello guys.
I came across a bug related to function execution in entrydb QE. Details provided below.
``` sql
create table invalid_name (name text) distributed replicated;
create table candidate (name text, parent_name text) distributed by (name);
create or replace function is_invalid_name (aname text) 
returns boolean 
language sql 
as $$ 
select aname in (select name from invalid_name)
$$;
create table tst_valid_name (a text) distributed randomly;
create table tst_invalid_name (a text) distributed randomly;
insert into invalid_name (name) values ('tst_invalid_name');
insert into candidate(name, parent_name) values ('tst_valid_name', 'tst_invalid_name');
```
Table "candidate" contains 1 row.
``` sql
select * from candidate;
name      |   parent_name …
```
> Protect function execution in entrydb QE

- gpMgmt/bin/gppylib/gpcatalog.py
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Issue:**
A customer reported an issue where they were unable to DROP time-based login constraints for users after running gpexpand. This was because, if there are time-based login constraints for users, there are entries in the `pg_auth_time_constraints` catalog table that are identical across all segments. However, when gpexpand was run, this table was not replicated to new segments. As a result, running the DROP command would give an error.
```
NOTICE:  dropping DENY rule for "user03" between Thursday 18:00:00 and Saturday 23:59:59
ERROR:  cannot find matching DENY rules for "user03"  (seg3 192.168.50.53:6000 pid=4429)
```
**RCA:**
The reason why the table was not getting replicated is because gpexpand creates a template of the coordinator segment and uses it to create new segments in …
> gpexpand: Fix tables not copied to new segments

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14854.  also documenting the autovacuum_naptime guc.
> docs - ref info for gp_autovacuum_scope, autovacuum_naptime gucs

- src/backend/catalog/gp_toolkit.sql
- src/backend/utils/adt/misc.c
- src/include/catalog/catversion.h
- src/include/catalog/pg_proc.dat
- src/test/regress/greenplum_schedule
- src/test/regress/input/alter_db_set_tablespace.source
- src/test/regress/input/gp_check_files.source
- src/test/regress/input/gp_tablespace.source
- src/test/regress/output/alter_db_set_tablespace.source
- src/test/regress/output/gp_check_files.source
- src/test/regress/output/gp_tablespace.source
- src/test/regress/regress_gp.c
Description
--------------
1. Add views to get _existing_ relation files in the database, including the default, global and user tablespaces. Note that these views won't expose files outside of the data directory. We only look into those under `base/`, `global/` and user-defined tablespace directories.
2. Add views to get _expected_ relation files in the database, using the knowledge from the catalog.
3. Using 1 and 2, construct views to get the **_missing_** files (i.e. files that are expected but not existed) and **_orphaned_** files (i.e. files that are there unexpectedly).
4. Create views to run the above views in MPP. Also, we support checking extended data files for AO/CO tables. 
5. Add regress tests.
To use:
```sql
-- checking non-extended files (no '.' sign)
select * from …
```
> Add views/functions to check missing and orphaned data files

- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/transam/xact.c
- src/test/isolation/specs/ao-insert-eof.spec
SnapshotNow has been deleted on 9.4.
Instead, using MVCC snapshot to scan tables,
so the related race condition issues are gone.
> Fix obsolete references to SnapshotNow in comment.

- src/backend/gporca/data/dxl/minidump/DisableBroadcastThreshold.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/backend/utils/misc/guc_gp.c
Currently, when optimizer_penalize_broadcast_threshold is set to 0, it will disable broadcasts when the estimated tuples to be broadcast is greater than 0. Because the value of this GUC is limited to INT_MAX, there is no way to disable this guc. This commit disables penalizing broadcast when this value is 0.
> Disable GUC optimizer_penalize_broadcast_threshold when set to 0

- src/backend/gporca/libgpopt/include/gpopt/base/CPartitionPropagationSpec.h
- src/backend/gporca/libgpopt/src/base/CPartitionPropagationSpec.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalMotion.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalPartitionSelector.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalSpool.cpp
This commit adds back some checks to ensure we're not creating an invalid plan that will fail during execution. While I don't believe that we'll generate these plans currently as we don't currently generate partition selectors under NLJs, I'd rather be defensive here and maintain the old logic. I wasn't able to find any cases where these disallow incorrect plans based on the current logic. If we feel that these are redundant/unnecessary, I'm also ok with leaving these checks out for now.
> Orca FIXME: Add checks to ensure plans with part selectors are valid

- src/backend/cdb/motion/ic_proxy.h
My previous PR https://github.com/greenplum-db/gpdb/pull/15139 introduced a warning: https://prod.ci.gpdb.pivotal.io/builds/1733638
```
ic_proxy_peer.c:159:17: warning: result of comparison of constant 65534 with expression of type 'int16' (aka 'short') is always false [-Wtautological-constant-out-of-range-compare]
peer->content == IC_PROXY_INVALID_CONTENT)
~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
This PR fix it: change `IC_PROXY_INVALID_CONTENT` to int16 (align its type to `ICProxyPeer.content` field).
> Fix compilation warning in ic_proxy_peer.c

- src/backend/cdb/motion/ic_proxy.h
Port https://github.com/greenplum-db/gpdb/pull/15219 to 6X.
Keep the code consistent though no such a compilation warning in 6x (may related to compiler/os version).
> Changing IC_PROXY_INVALID_CONTENT to int16

- src/test/isolation2/input/idle_gang_cleaner.source
- src/test/isolation2/output/idle_gang_cleaner.source
After calling `cleanupAllGangs()`, there is a chance of encountering the FATAL "writer segworker group shared snapshot collision" error when executing a query. The reason is that if the writer gang cannot exit before a new command starts, it will find the same session id in the shared snapshot and collision will happen. Additionally, since the session only have the writer gangs before executing the target query, there is no need to call `cleanupAllGangs()` before executing the query.
> [6X] Fix flaky idle_gang_cleaner case

- src/test/isolation2/input/idle_gang_cleaner.source
- src/test/isolation2/output/idle_gang_cleaner.source
After calling `cleanupAllGangs()`, there is a chance of encountering the FATAL "writer segworker group shared snapshot collision" error when executing a query. The reason is that if the writer gang cannot exit before a new command starts, it will find the same session id in the shared snapshot and collision will happen. Additionally, since the session only has the writer gangs before executing the target query, there is no need to call cleanupAllGangs() before executing the query.
> Fix flaky idle_gang_cleaner case

- gpMgmt/bin/gpcheckperf
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
This is a backport from 7X PR https://github.com/greenplum-db/gpdb/pull/14865
Currently, there is a bug in the `getMemory()` function in `gpcheckperf` because of the way we check the return code of the `run()` method which is called inside `getMemory()`. The `run()` method returns an integer value of `zero` in case of success and a `non-zero` value if it fails.
We are checking this value using the condition `if not ok` which is incorrect because when the `run()` method succeeds (`ok = 0`), the condition would result as `False` causing the `getMemory()` function to assume that the `run()` method failed but in reality, it did not.
A simple fix would be to change the condition from `if not ok` to `if ok != 0` to check for any possible failure from the `run()` method.
Further, the way …
> [6X_Backport] gpcheckperf: Fix memory calculation function

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-388-renamed-GUC/greenplum-database/GUID-ref_guide-config_params-guc-list.html#walkeepsize-309
> DOCS: Rename wal_keep_segments to wal_keep_size and pull in explanation from Postgres 13 docs

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
Staging here: https://docs-staging.vmware.com/en/Greenplum-Database-7/GPDOCS-141-max_slot_wal_keep_size/greenplum-database/GUID-ref_guide-config_params-guc-list.html#maxslotwalkeepsize-117
> DOCS: Add max_slot_wal_keep_size GUC to GP7 docs

- src/backend/catalog/pg_appendonly.c
Updated Description:
-------------
GetAppendOnlyEntryAuxOids / GetAppendOnlyEntry should only be called on a non-partitioned AO/CO table. Otherwise, there's no pg_appendonly entry and the relation's relcache also doesn't carry any pg_appendonly entry data. Putting a strong assert there.
Original Description:
-------------
It normally shouldn't happen, but if GetAppendOnlyEntryAuxOids or GetAppendOnlyEntry is called on a non-AO table or an AO table w/o storage (e.g. partitioned table), we wouldn't be able to get the pg_appendonly tuple from relcache. As a result of that, we would get segfault when we try to dereference rd_appendonly.
Now error out in such case. We probably don't want Assert either because although rare, the above scenario could still exist. And also it's good to report …
> ASSERT relation is AO in GetAppendOnlyEntryAuxOids/GetAppendOnlyEntry

- doc/src/sgml/ref/create_aggregate.sgml
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_AGGREGATE.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_aggregate.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14811.
in this PR:
- add aggrepsafeexec field/description to pg_aggregate ref page
- add the REPSAFE clause to CREATE AGGREGATE sql ref page
- update the sgml ref page so that the new REPSAFE clause is included in psql help text
question:  should i call this out as supported only by GPORCA, or do we plan to add or have planner support for this?
> docs - new pg_aggregate column for safe aggs

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
gporca supports multiple grouping sets.  docs for https://github.com/greenplum-db/gpdb/pull/14366, which identifies a specific fallback scenario and workaround.
> docs - note specific gporca multiple grouping set limitation

- src/bin/pg_rewind/pg_rewind.c
* Due to commit eb4db09544bcb8b6ea52f47effe8e30b0f736a97 string comparison was giving below warning, fixed the string comparison code
pg_rewind.c: In function ‘main’: pg_rewind.c:318:75: warning: comparison with string literal results in unspecified behavior [-Waddress] 318 |  while(getenv("SUSPEND_PG_REWIND") != NULL && getenv("SUSPEND_PG_REWIND") == "true") |
* Also placed the suspend pg_rewind code block under #ifdef FAULT_INJECTOR to avoid shipping this in production build as suggested in https://github.com/greenplum-db/gpdb/pull/14476#discussion_r1110459120
> Fixed the string comparison warning

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
Add compile_platform variable to use rocky8 for oel8,rhel8.rocky8 in compile related bins,images and names
[GPR-1212]
> Rename compile job name to 'rocky8' for oel8,rhel8.rocky8

- gpMgmt/bin/generate-greenplum-path.sh
fix for #14327
`'.*/[0-9][0-9]-*.\.conf$'`
example input:
```
etc/environment.d/
etc/environment.d/10-pljava.conf
etc/environment.d/10-add-python-path-gpdb.conf
```
`.*` will match until the last '/', `[0-9][0-9]-` is the file prefix `00-`. then the file name. and the name should ends with `.conf`.
> fix regex for etc/environment.d

- src/backend/cdb/cdbutil.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbutil.h
- src/include/utils/unsync_guc_name.h
Neither hosts and IP addr can make sure everything is correct.
Sometimes users do want to use IP to compute the N segments on
a host. This commit introduces a GUC gp_count_host_segments_using_address,
its default value is false:
* when it is false, nsegments on a host is computed using hostname
as key,
* when it is true, nsegments on a host is computed using ip addr as
key.
Test locally using as below using two hosts to build a 4-segment
cluster with no mirrros and no standby:
gpadmin=# select content, port, hostname, address from gp_segment_configuration ;
content | port |  hostname  |  address
---------+------+------------+------------
-1 | 5432 | zlv-ubuntu | zlv-ubuntu
0 | 6000 | test       | rr1
1 | 6001 | test       | rr1
2 | 6002 | test       | rr2
3 | 6003 | test       | rr2
(5 …
> 6X: Introduce GUC gp_count_host_segments_using_address.

- gpMgmt/bin/gpcheckperf
- gpMgmt/bin/gppylib/util/ssh_utils.py
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
This PR contains the following changes: 
1. Changes related to fixing gpssh to return a string instead of the mix of string+bytes. 
2. Changes related to gpcheckperf failured after gpssh changes due to string parsing. 
3. Backporting changes from 6X PR for gpcheckperf: https://github.com/greenplum-db/gpdb/pull/15192 
All changes are combined in this PR as they are related to each other. 
**Details:** 
**1.Issue-1: gpssh fix:** Before this change, gpssh was returning command output mix of string + bytes and had characters like b and \r. 
Sample command output before the fix: 
```
$ gpssh -h sdw1 hostname
[sdw1] b'sdw1\r'
```
**RCA:**
When gpssh reads output from pexpect.before, it is in byte format.
We need to convert this output into the string format. Also, carriage return characters …
> [7x]: Fixing gpcheckperf failure parity changes and gpssh fix

- doc/src/sgml/ref/pg_dump.sgml
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/t/002_pg_dump.pl
Backport of upstream commit: a563c24c9574b74f4883c004c89275bba03c3c26
Resolved merge conflicts in:
* 002_pg_dump.pl due to multiple tests present in upstream that are not yet present in gpdb codebase.
* minor merge conflicts in pg_dump.sgml, unclear their source, likely formatting-derived
backported by: Andrew Repp
This patch adds new pg_dump switches
--table-and-children=pattern
--exclude-table-and-children=pattern
--exclude-table-data-and-children=pattern
which act the same as the existing --table, --exclude-table, and --exclude-table-data switches, except that any partitions or inheritance child tables of the table(s) matching the pattern are also included or excluded.
Gilles Darold, reviewed by Stéphane Tachoires
Discussion: …
> Allow pg_dump to include/exclude child tables automatically.

- gpMgmt/bin/gppylib/gpcatalog.py
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a backport of #15025
**Issue:**
A customer reported an issue where they were unable to DROP time-based login constraints for users after running gpexpand. This was because, if there are time-based login constraints for users, there are entries in the `pg_auth_time_constraints` catalog table that are identical across all segments. However, when gpexpand was run, this table was not replicated to new segments. As a result, running the DROP command would give an error.
```
NOTICE:  dropping DENY rule for "user03" between Thursday 18:00:00 and Saturday 23:59:59
ERROR:  cannot find matching DENY rules for "user03"  (seg3 192.168.50.53:6000 pid=4429)
```
**RCA:**
The reason why the table was not getting replicated is because gpexpand creates a template of the master segment and uses it …
> [6X Backport] gpexpand: Fix tables not copied to new segments

- gpMgmt/bin/gpcheckperf
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpcheckperf utility can be run in verbose mode in 2 ways : "-v" and "-V" which is verbose mode and very verbose mode respectively. In very verbose mode, any commands called through gpcheckperf are also run in verbose mode. 
**Problem:**   
When gpcheckperf ran in very verbose mode (-V) option, it runs gpssh command with -v option which results in the extra lines of output (see example bellow for more details). Those extra lines were leading to run-time exception.
gpssh command when ran in regular mode output is as follows:
```
$ gpssh -h sdw2 hostname
[sdw2] sdw2
```
When ran gpssh in verbose mode, output is as follows:
```
gpssh -v -h sdw2 hostname
[WARN] Reference default values as $MASTER_DATA_DIRECTORY/gpssh.conf could not be found
Using delaybeforesend 0.05 and …
```
> [6X] Fixing gpcheckperf error when ran with -f and -V option

- src/backend/parser/parse_expr.c
- src/test/regress/expected/alter_table.out
- src/test/regress/sql/alter_table.sql
* This tiny merge request is used to fix this issue : https://github.com/greenplum-db/gpdb/issues/15034
* Added `T_OpExpr` case to transform expression(`src/backend`).
* Added some test cases in `regress/alter_table`
> bug fix: 'unrecognized node type: 145'

- src/backend/optimizer/path/allpaths.c
- src/test/isolation2/expected/misc.out
- src/test/isolation2/sql/misc.sql
Re-worked approach to https://github.com/greenplum-db/gpdb/pull/15252
-------------
Currently when we plan a subquery, we refer to the subquery RTE's forceDistRandom field in order to understand if it is a gp_dist_random. If so we will set its locus to CdbLocusType_Strewn. In utility mode, that could result in motion being created which it couldn't handle (see #15238).
Therefore, now we don't force the random distribution in utility mode and let the subquery decide its own locus (which might involve gp_dist_random again but we'll follow the same logic here again).
Fixed #15238
> Do not force gp_dist_random in set_subquery_pathlist in utility mode

- src/backend/gporca/data/dxl/minidump/LeftJoinPruning.mdp
- src/backend/gporca/data/dxl/minidump/LeftJoinPruningInOuterInnerQuery.mdp
- src/backend/gporca/data/dxl/minidump/LeftJoinPruningInnerQuery.mdp
- src/backend/gporca/data/dxl/minidump/LeftJoinPruningOuterQuery.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CLeftJoinPruningPreprocessor.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/operators/Makefile
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/join_gp.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/expected/join_optimizer.out
- src/test/regress/sql/join_gp.sql
This PR implements join pruning in ORCA. Following are the conditions which will determine if a left join will be pruned or not.
1. The output columns and the WHERE clause should only contain columns from the outer relation.
2. The unique keys of the inner relation should either be constant or equal to a column from the outer relation.
3. All the unique/primary keys from a particular key set collection of the inner relation should be present in the join condition.
Co-Author : @24nishant
> Implement Left Join Pruning

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gpstop
- gpMgmt/sbin/gpsegstop.py
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
There was an issue reported and fixed by #11378 where the `kill_9_segment_processes` function had a bug and could not get the postgres pids to kill (more details in the mentioned PR). Even though the fix was correct, it has some issues - 
- It is not reliable to use the grep command `ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'` to get a list of postgres processes since the pattern can be changed in the future and the output of the command also depends on the OS.
- The function never considered the case for executing on remote hosts. So the function would never work in case of standby shutdown when standby is on another host.
To address the above issues following changes are made - 
- Use the postmaster pid to get the list of all its child processes (implemented using …
> gpstop: Fix kill_9_segment_processes function

- src/backend/commands/vacuum_ao.c
- src/test/isolation2/expected/setup.out
- src/test/isolation2/expected/vacuum_progress_column.out
- src/test/isolation2/expected/vacuum_progress_row.out
- src/test/isolation2/sql/setup.sql
- src/test/isolation2/sql/vacuum_progress_column.sql
- src/test/isolation2/sql/vacuum_progress_row.sql
The following fields of pg_stat_all_tables view now have stats available for append-optimized tables:
n_live_tup
n_dead_tup
last_vacuum
vacuum_count
Note that n_dead_tup only accounts for dead tuples in non-awaiting-drop segment files.
> Collect vacuum stats for append-optimized tables

- src/backend/access/aocs/aocsam_handler.c
- src/backend/commands/copy.c
- src/test/regress/input/gpcopy.source
- src/test/regress/output/gpcopy.source
PostgreSQL does not support copying partitioned tables to files. Refer to: https://www.postgresql.org/docs/12/sql-copy.html
> COPY TO can only be used with plain tables, not views, and does not copy rows from child tables or child partitions.
> For example, COPY table TO copies the same rows as SELECT * FROM ONLY table. The syntax COPY (SELECT * FROM table)
> TO ... can be used to dump all of the rows in an inheritance hierarchy, partitioned table, or view.
```
postgres=# copy rank to '/tmp/test1';
ERROR:  cannot copy from partitioned table "rank"
HINT:  Try the COPY (SELECT ...) TO variant.
```
In GPDB 7, partitioning was replaced with an upstream implementation. To ensure forward compatibility, `COPY partitioned_table TO file` is converted to `COPY (SELECT * FROM partitioned_table) TO …
> Enable `COPY partitioned_table TO file` for better performence

- src/backend/cdb/cdbdistributedsnapshot.c
The code:
```c
if (target->inProgressXidArray == NULL)
{
target->inProgressXidArray =
(DistributedTransactionId*) malloc(GetMaxSnapshotDistributedXidCount() * sizeof(DistributedTransactionId));
if (target->inProgressXidArray == NULL)
ereport(ERROR,
(errcode(ERRCODE_OUT_OF_MEMORY),
errmsg("out of memory")));
}
```
in `DistributedSnapshot_Copy` is dead code, because we do the same thing in `DistributedSnapshot_Reset`.
It could be a history problem caused by code changes.
> Removed dead code in DistributedSnapshot_Copy

- src/backend/tcop/dest.c
- src/interfaces/libpq/fe-exec.c
- src/interfaces/libpq/libpq-fe.h
- src/interfaces/libpq/libpq-int.h
Before this commit, Greenplum didn't take `internalPQconninfoOption` and
`PQconninfoOption` differently on the backend side, that's why we had
`connofs` in `PQconninfoOption`, nowadays it's not needed and not
actually being used, just remove.
commit 510a20b6c2ea8f7c6f9319ff904aea83a00a1ffc
Author: Adam Lee <ali@pivotal.io>
Date:   Mon Oct 23 14:40:11 2017 +0800
Retire gp_libpq_fe part 1, libpq itself
Fix #14462
> Remove element connofs from PQconninfoOption

- src/test/regress/expected/autovacuum-ao-aux.out
- src/test/regress/sql/autovacuum-ao-aux.sql
Waiting for fault blocks stats updates sent from the same connection.  There was a race condition in the test where if we got to the wait before the stats were updated they'd never be received and so autovacuum would never run and the test would fail on timeout.
This was only visible in greenplum configurations that are faster, most debug builds never observed this.  The JIT pipeline reliably reproduced it, however.
> Update flakey av ao aux test.

- src/backend/jit/llvm/llvmjit_expr.c
Test latest master, it's a serious coredump problem.
Default compile and start a demo-cluster.
```shell
psql postgres
postgres=# create table T (a int, b int, g int);
postgres=# insert into T values (1, 3, 9),(2, 5, 8), (8,7,6),(10,3,2);
INSERT 0 4
postgres=# set jit=on;
postgres=# set jit_inline_above_cost = 0;
SET
postgres=# set jit_above_cost = 0;
SET
postgres=# select g, sum(distinct a), SUM(distinct b) from T group by g;
before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```
crash stack into llvm assert:
when we want to store a value into a pointer like `LLVMBuildStore(b, v_group_id, v_resvaluep);` , we need to make sure the …
> Fix coredump when use group by with jit enabled

- gpMgmt/bin/gpinitsystem
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- src/backend/postmaster/postmaster.c
- src/backend/tcop/postgres.c
- src/backend/utils/init/globals.c
- src/backend/utils/init/postinit.c
- src/backend/utils/misc/guc_gp.c
- src/bin/pg_dump/pg_backup_archiver.c
- src/bin/pg_dump/pg_backup_db.c
- src/bin/pg_upgrade/pg_upgrade.c
- src/include/miscadmin.h
- src/include/utils/unsync_guc_name.h
Greenplum 7 lost this restriction after this commit:
commit f6297b96eeb4937629bd796333f6118340613197
Author: Paul Guo <pguo@pivotal.io>
Date:   Mon Jun 8 11:00:32 2020 +0800
Retire guc gp_session_role (#9396)
To avoid users connecting to and damaging the coordinator-only clusters, get this restriction back.
Fixes https://github.com/greenplum-db/gpdb/issues/12217
> Only utility connections are allowed for coordinator-only clusters

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gpstop
- gpMgmt/sbin/gpsegstop.py
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a backport of https://github.com/greenplum-db/gpdb/pull/15148
There was an issue reported and fixed by #11378 where the `kill_9_segment_processes` function had a bug and could not get the postgres pids to kill (more details in the mentioned PR). Even though the fix was correct, it has some issues - 
- It is not reliable to use the grep command `ps ux | grep "[p]ostgres:\s*%s" | awk \'{print $2}\'` to get a list of postgres processes since the pattern can be changed in the future and the output of the command also depends on the OS.
- The function never considered the case for executing on remote hosts. So the function would never work in case of standby shutdown when standby is on another host.
To address the above issues following changes are made - 
- Use the postmaster pid to …
> [6X Backport] gpstop: Fix kill_9_segment_processes function

- src/backend/gporca/data/dxl/minidump/LASJ-Not-In-Force-Broadcast.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecReplicated.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalMotionBroadcast.h
- src/backend/gporca/libgpopt/src/base/CDistributionSpecReplicated.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalLeftAntiSemiHashJoinNotIn.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalMotionBroadcast.cpp
- src/backend/gporca/server/CMakeLists.txt
When we have a query like
`select * from foo where a not in (select a from bar);`
we can produce 2 valid plans:
```
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..896.64 rows=40000 width=4)
->  Hash Left Anti Semi (Not-In) Join  (cost=0.00..896.04 rows=13334 width=4)
Hash Cond: (foo.a = bar.a)
->  Seq Scan on foo  (cost=0.00..431.62 rows=33334 width=4)
->  Hash  (cost=439.03..439.03 rows=100000 width=4)
->  Broadcast Motion 3:3  (slice2; segments: 3)  (cost=0.00..439.03 rows=100000 width=4)
->  Seq Scan on bar  (cost=0.00..431.62 rows=33334 width=4)
Optimizer: Pivotal Optimizer (GPORCA)
```
or
```
Hash Left Anti Semi (Not-In) Join  (cost=0.00..903.99 rows=40000 width=4)
Hash Cond: (foo.a = bar.a)
->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..433.36 rows=100000 width=4) …
```
> 6X: Don't penalize broadcast under LASJ (not in) in Orca

- gpdb-doc/markdown/admin_guide/external/g-foreign.html.md
- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-changed.html.md
- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14287, https://github.com/greenplum-db/gpdb/pull/14844, https://github.com/greenplum-db/gpdb/pull/14890
in this PR:
- remove notes that gporca doesn't support foreign tables, misc edits on the page
- update the gporca limitations section to include DML and COPY ops on foreign tables
- remove some fallback to planner references for partitions that are external tables
- add ref info for new optimizer_enable_foreign_table guc
future task/PR:  review the existing gporca docs before release.  they are currently framed around new features/changes in gp6, and we should call out new gp7 features.  also, explain plans have changed, and the docs include a bit of EXPLAIN output.
> docs - gporca supports planning queries on foreign tables

- gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
After merging https://github.com/greenplum-db/gpdb/pull/15294, `test_PgPortIsActive_no_netstat_ss` gpstate unit test case started failing for rocky8 and centos7 platforms on prod pipeline with the error -
```
File "/tmp/build/9a968038/gpdb_src/gpMgmt/bin/gppylib/commands/unix.py", line 587, in __init__
logger.critical(
AttributeError: Mock object has no attribute 'critical'
```
The reason for this is that we have mocked the logger framework in the previous PR https://github.com/greenplum-db/gpdb/blob/dd223740668f8f84eed8b468e760704c94b73b76/gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py#L11 and this mock is not cleaned up for subsequent unit test runs on these platforms (not sure why). Since we have not mocked the `critical` attribute, we see the above error.
This commit fixes …
> Fix unit test failure in gpstate on rocky8/centos7

- gpdb-doc/markdown/analytics/greenplum_r_client.html.md
- gpdb-doc/markdown/analytics/pl_container.html.md
- gpdb-doc/markdown/utility_guide/ref/gpmapreduce.html.md
Added deprecation notice for Greenplum MapReduce, PL/Container 3 Beta and GreenplumR client (deprecated since 6.24.0).
> Added deprecation notices

- src/bin/pg_dump/pg_dump.c
The comment seems to have been incorrectly handled while dealing with backports and the Postgres 9.4 merge. Update it to what it is in Postgres REL9_4_STABLE as that should be the correct comment.
> Fix a comment in pg_dump

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-tables.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_attribute_encoding.html.md
This PR adds the column filenum to the table pg_attribute_encoding, based on https://github.com/greenplum-db/gpdb/pull/15074).
> Added column filenum to pg_attribute_encoding

- src/backend/access/transam/xact.c
- src/test/regress/expected/distributed_transactions.out
- src/test/regress/sql/distributed_transactions.sql
Fix some issues in mpp situation after merge feature COMMIT AND CHAIN from upstream.
Supported by upstream in https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=280a408b48d5ee42969f981bceb9e9426c3a344c
But for our MPP structure, there are few issues need to fix, especially transaction block Context/State.
As a result, In this PR, we tried to set up DtxContext again before start a "chain" transaction for
keeping correct distributed Context in a new transaction block state. And this setup method inherited
from what we did in StartTransactionCommand().
List some of block state that we need to setup DtxContext for chain transaction:
TBLOCK_END
TBLOCK_ABORT_END
TBLOCK_ABORT_PENDING
TBLOCK_SUBCOMMIT
> fix bug of upstream merge feature COMMIT AND CHAIN

- src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
- src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
- src/backend/gporca/data/dxl/minidump/VariadicFlagWithFormatQuery.mdp
- src/backend/gporca/data/dxl/minidump/VariadicFlagWithJson.mdp
- src/backend/gporca/data/dxl/minidump/VariadicFlagWithUnionAll.mdp
- src/backend/gporca/data/dxl/parse_tests/q14-FuncExpr-NoArg.xml
- src/backend/gporca/data/dxl/parse_tests/q15-FuncExpr-WithArgs.xml
- src/backend/gporca/data/dxl/parse_tests/q16-FuncExpr-WithNestedFuncExpr.xml
- src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
- src/backend/gporca/data/dxl/parse_tests/q31-LogicalLimit.xml
- src/backend/gporca/data/dxl/parse_tests/q69-ArrayRef2.xml
- src/backend/gporca/data/dxl/parse_tests/s02-NestedFuncExpr.xml
- src/backend/gporca/libgpopt/include/gpopt/operators/CScalarFunc.h
- src/backend/gporca/libgpopt/src/operators/COrderedAggPreprocessor.cpp
- src/backend/gporca/libgpopt/src/operators/CScalarFunc.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLScalarFuncExpr.h
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLScalarFuncExpr.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/text.out
- src/test/regress/expected/variadic_parameters.out
- src/test/regress/sql/text.sql
- src/test/regress/sql/variadic_parameters.sql
Through this PR, we have allowed processing of functional Expressions with 'funcvariadic' as true
This PR is a back-port of the original PR on 7X:  https://github.com/greenplum-db/gpdb/pull/15178
> Allow queries with valid function variadic flag (6X_STABLE)

- gpdb-doc/markdown/admin_guide/expand/expand-initialize.html.md
- gpdb-doc/markdown/admin_guide/expand/expand-overview.html.md
Adding a note on gpexpand initialization page and some clarification on landing page to make sure there is no confusion regarding DDL operations running during gpexpand initialization phase.
Review site:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-gpexpand/greenplum-database/GUID-admin_guide-expand-expand-initialize.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-gpexpand/greenplum-database/GUID-admin_guide-expand-expand-overview.html
> Note about initialization phase

- src/backend/cdb/motion/tupleremap.c
- src/test/isolation2/expected/free_remapper_fatal.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/free_remapper_fatal.sql
Usually, the `typmodmap` field is NULL. And it has a valid value if need the "record type cache", example:
```
create table t as select i as id from generate_series(1,8) i; 
create type myudt as (i int, c char);
-- the following query will generate "record type cache"
select row((1,'a')::myudt), row((2,'b')::myudt, 2) from t;
```
When the similar query raises a FATAL, it runs into the following routine:
```
FATAL->AbortTransaction()
AtAbort_Portals()
MemoryContextDeleteChildren()     // delete ExecutorState memory context
ResourceOwnerRelease()
cleanup_interconnect_handle()
TeardownUDPIFCInterconnect()
DestroyTupleRemapper()          // pfree remapper->typmodmap
```
But it may cause SIGSEGV, reason: 
`remapper->typmodmap` is alloced in `MotionLayerMemCtxt`, but the memory context has been …
> Fix double free remapper->typmodmap in TeardownUDPIFCInterconnect()

- src/backend/commands/explain.c
- src/backend/optimizer/plan/orca.c
- src/include/optimizer/orca.h
Previously, we didn't run some of the query preprocessing methods to fold constants and transform window functions during ExplainDXL. While this doesn't affect production code or creating minidumps, it did make the DXL explain plan different from what was produced in minidumps. This adds the same logic to unify the behavior.
The following query produced a different explain (dxl) and minidump output because constants were not folded in explain (dxl): `select format(‘|%20s|’, ‘ten’) union all select format(‘|%10s%10s|’, variadic array[‘first’, ‘second’]);`
> Run preprocessing methods in ExplainDXL

- src/backend/cdb/motion/tupleremap.c
- src/test/isolation2/expected/free_remapper_fatal.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/free_remapper_fatal.sql
This PR backports https://github.com/greenplum-db/gpdb/pull/15340 to 6X.
> Fix double free remapper->typmodmap in TeardownUDPIFCInterconnect() 

- gpdb-doc/markdown/ref_guide/sql_commands/DISCARD.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DO.html.md
bring DISCARD and DO sql ref pages up to postgres 12 content.  there appears to be some greenplum-specific info on these pages
DISCARD:
- SEQUENCES was missing from the synopisis, but it was described in the para
meters section.
- i tried "DISCARD ALL", it worked, so removed statements that indicated it wasn't support in greenplum.
DO:
- there are a few paragraphs of text in the DO command description that are not on the pg12 ref page. (look for text between XXX tags.)  not sure where that info came from, but looks like it could still be true.
- simplified some language.
- is this statement from the Notes still true:  Anonymous blocks do not support function volatility or `EXECUTE ON` attributes.
- removed an example (didn't work when i tried it on gp7)
> docs - sql ref page updates for DISCARD, DO

- gpdb-doc/markdown/admin_guide/managing/monitor.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/pg_backend_memory_contexts.html.md
- gpdb-doc/markdown/ref_guide/toc.md
docs for https://github.com/greenplum-db/gpdb/pull/15145.
in this PR:
- port the postgres v15 pg_backend_memory_contexts system view reference (https://www.postgresql.org/docs/15/view-pg-backend-memory-contexts.html)
- add topic "Viewing and Logging Per-Process Memory Usage Information" that discusses the view and the new sys admin functions to the admin guide monitoring page.  i choose this page because this new info seemed aligned with an existing topic there named "Viewing Session Memory Usage Information".
question:  how/does this new feature relate to the `session_level_memory_consumption` view mentioned in the "Viewing Session Memory Usage Information" topic?
- new catalog view: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/memctx …
> docs - memory context view and sys admin log functions

- src/test/isolation2/expected/fsync_ao.out
- src/test/isolation2/sql/fsync_ao.sql
The test was flaky w/ a diff like this:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/expected/fsync_ao.out	2023-04-10 11:51:22.694100534 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/results/fsync_ao.out	2023-04-10 11:51:22.706101385 +0000
@@ -107,7 +107,7 @@
gp_inject_fault
------------
- Success: fault name:'ao_fsync_counter' fault type:'skip' ddl statement:'' database name:'' table name:'' start occurrence:'1' end occurrence:'-1' extra arg:'0' fault injection state:'triggered'  num times hit:'3'
+ Success: fault name:'ao_fsync_counter' fault type:'skip' ddl statement:'' database name:'' table name:'' start occurrence:'1' end occurrence:'-1' extra arg:'0' fault injection state:'triggered'  num times hit:'2' (1 row)
```
The reason seems to be that there's one …
> Fix flaky test fsync_ao

- src/backend/gporca/data/dxl/minidump/CTAS-random-distr.mdp
- src/backend/gporca/libgpopt/src/base/CDistributionSpecNonSingleton.cpp
- src/backend/gporca/server/CMakeLists.txt
This builds on logic in d14e61d7117f822e71170d69951e36cdc153b25f, and I would recommend reading that commit message first.
When inserting into a randomly distributed table, Orca adds a random
distribution motion to ensure tuples are properly distributed across the
segments. However, when this motion is a duplicate sensitive motion, which we
define as being on top of a replicated table or a universal distributed (eg a
generate_series function), we don't actually perform a redistribute. Instead,
we filter each segment by the segment id, ensuring all tuples only exist on one
segment. This is done for correctness, and is the correct behavior.
In this case, the distribution spec was creating a strict random distribution,
and this will match the required strict random distribution required by …
> Fix missing redistribute for CTAS/insert into randomly distributed table using Orca

- src/test/regress/expected/pg_stat.out
- src/test/regress/sql/pg_stat.sql
Commit 580250229423c5475dcf6fed90a00ab89cf82072 added a few test cases in pg_stat which used outdated column name 'segment_id' in pg_stat_sys_tables. The original PR https://github.com/greenplum-db/gpdb/pull/15306 was not rebased before merge which resulted this error. Also added a missed comment to address in the original PR ("cluster-wise" to "cluster-wide").
> Fixing up pg_stat test: segment_id -> gp_segment_id

- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/aosegfiles.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/bitmap/bitmapattutil.c
- src/backend/access/heap/heapam.c
- src/backend/access/heap/rewriteheap.c
- src/backend/access/heap/tuptoaster.c
- src/backend/access/transam/xloginsert.c
- src/backend/catalog/indexing.c
- src/include/access/tuptoaster.h
- src/include/access/xloginsert.h
- src/include/catalog/indexing.h
- src/test/isolation2/expected/frozen_insert_crash.out
- src/test/isolation2/sql/frozen_insert_crash.sql
Similar to #15127, now apply the same approach for all the "frozen insert" logic in GPDB, for two purposes:
1. Solve the remaining inconsistency hazard. For example, the bitmap LOV could still see the same problem (a repro shown below).
2. Align core function interface with upstream, including things like `heap_prepare_insert` and `toast_save_datum`. With that we also removed GPDB-specific function such as `frozen_heap_insert` and `XLogInsert_OverrideXid`.
Please review each commit individually.
A repro for the inconsistency in bitmap LOV table:
```sql
-- on session 1, do
create extension pageinspect;
drop table if exists tab_fi;
create table tab_fi(a int, b int) with (appendoptimized=true) distributed replicated;
create index tab_fi_idx on tab_fi using bitmap(b);
insert into tab_fi …
```
> Replace "frozen insert" with "insert & freeze" across GPDB

- src/backend/executor/nodeAgg.c
- src/include/nodes/execnodes.h
- src/include/nodes/pathnodes.h
- src/test/isolation2/expected/spilling_hashagg.out
- src/test/isolation2/expected/spilling_hashagg_optimizer.out
- src/test/isolation2/sql/spilling_hashagg.sql
In multi-phase aggregate, this feature streams entries of the bottom
phase when out of memory instead of spilling to disk, it avoids the disk
I/O and roughly deduplicates to save the network I/O.
The planner always supports streaming aggregate and there are lots of
cases, but the executor part was lost while merging PostgreSQL 12, this
commit gets it back.
> Get streaming hash aggregate back

- README.macOS.arm.bash
- README.macOS.md
Co-authored-by: Anusha Shakarad <shakarada@vmware.com>
Co-authored-by: Mounika M <mmounika@vmware.com>
**Problem :**
With the existing README.macOS.bash script there were multiple dependencies missing while configuring gpdb on M1 based MacOS. The missing dependencies resulted in random errors and fixing these were time consuming.
**RCA :**
Missing dependencies were due to change in architecture from x86 to arm64 .
**Solution :**
Below are the dependencies needed for arm based macOS which are implemented in the README.macOS.arm.bash script
1. Change the brew installation method from ruby to bash and update the homebrew path.
2. library xerces-c installation method changed from brew installation to manual make installation.
3. Hardcoded the python installation to 3.9 version specific to …
> Adding README.macOS.arm.bash script for arm based macOS 

- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
- src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
In resource group mode, if user requests more than statement_mem, grant that, otherwise set the statement_mem to the query's memory limit.
> set resource group's minimum query memory limit to statement_mem

- src/backend/utils/init/globals.c
- src/backend/utils/misc/guc.c
- src/backend/utils/misc/postgresql.conf.sample
When commit f425b605 introduced cost based vacuum delays back in 2004, the defaults reflected then-current trends in hardware, as well as certain historical limitations in PostgreSQL.  There have been enormous improvements in both areas since that time.  The cost limit GUC defaults finally became much more representative of current trends following commit cbccac37, which decreased autovacuum_vacuum_cost_delay's default by 10x for PostgreSQL 12 (it went from 20ms to only 2ms).
The relative costs have shifted too.  This should also be accounted for by the defaults.  More specifically, the relative importance of avoiding dirtying pages within VACUUM has greatly increased, primarily due to main memory capacity scaling and trends in flash storage.  Within Postgres itself, improvements like …
> Reduce the default value of vacuum_cost_page_miss.

- src/backend/access/bitmap/bitmapinsert.c
- src/test/regress/expected/bitmap_index.out
- src/test/regress/expected/bitmap_index_optimizer.out
- src/test/regress/sql/bitmap_index.sql
This is the backport of #15271.
------
If we build bitmap index on a heap table, there could have HOT-chain, 
and it'll return the root tuple's tid, which could lead to the TIDs we 
scanned are not in order.
> [6X] fix tids are not in order when building bitmap index

- README.macOS.arm.bash
- README.macOS.md
Authored-by: Anusha Shakarad [shakarada@vmware.com](mailto:shakarada@vmware.com)
Co-authored-by: Mounika M [mmounika@vmware.com](mailto:mmounika@vmware.com)
Problem :
With the existing README.macOS.bash script there were multiple dependencies missing while configuring gpdb on M1 based MacOS. The missing dependencies resulted in random errors and fixing these were time consuming.
RCA :
Missing dependencies were due to change in architecture from x86 to arm64 .
Solution :
Below are the dependencies needed for arm based macOS which are implemented in the README.macOS.arm.bash script
Change the brew installation method from ruby to bash and update the homebrew path.
library xerces-c installation method changed from brew installation to manual make installation.
Hardcoded the python …
> Adding README.macOS.arm.bash for MAC arm based OS for 6X_stable

- contrib/btree_gin/expected/enum.out
- contrib/btree_gin/sql/enum.sql
- src/backend/commands/tablecmds.c
- src/backend/parser/parse_utilcmd.c
- src/test/regress/expected/enum.out
- src/test/regress/expected/enum_dist_part_ban.out
- src/test/regress/expected/gpdist_legacy_opclasses.out
- src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
- src/test/regress/expected/partition_prune.out
- src/test/regress/expected/partition_prune_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/enum.sql
- src/test/regress/sql/enum_dist_part_ban.sql
- src/test/regress/sql/gpdist_legacy_opclasses.sql
- src/test/regress/sql/partition_prune.sql
Enums cannot be safely used for hashed keys.
See: https://github.com/greenplum-db/gpdb/issues/14198
> Ban enums as distribution and partition keys

- src/backend/cdb/cdbcopy.c
- src/backend/cdb/cdbtm.c
- src/backend/cdb/dispatcher/cdbdisp.c
- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/cdb/endpoint/cdbendpointutils.c
- src/backend/commands/explain.c
- src/backend/executor/execUtils.c
- src/backend/executor/nodeSubplan.c
- src/backend/utils/error/elog.c
cases(#15278)
This commit addresses issue #15278, where the InterruptHoldoffCount value was not always resetting to zero in certain abnormal scenarios. This issue had the potential to impact the proper functioning of the ProcessInterrupts process. The fix ensures that the InterruptHoldoffCount value is properly reset to zero in all cases.
> Fix InterruptHoldoffCount value not being reset to zero in abnormal

- src/bin/pg_dump/pg_backup_archiver.c
We're checking the address instead of the bool value for the binary_upgrade value. This will result in us always trying to connect in binary_upgrade mode.
Resolves
```
pg_backup_archiver.c:4888:94: warning: address of 'clone->public.ropt->binary_upgrade' will always evaluate to 'true' [-Wpointer-bool-conversion]
ConnectDatabase((Archive *) clone, &clone->public.ropt->cparams, true, &clone->public.ropt->binary_upgrade);
```
> Fix bug in pg_backup_archiver

- contrib/postgres_fdw/postgres_fdw.h
- contrib/postgres_fdw/shippable.c
- src/backend/access/hash/hashvalidate.c
- src/backend/access/transam/parallel.c
- src/backend/access/transam/xlog.c
- src/backend/catalog/index.c
- src/backend/catalog/pg_enum.c
- src/backend/catalog/toasting.c
- src/backend/commands/vacuum.c
- src/backend/executor/nodeDynamicBitmapIndexscan.c
- src/backend/libpq/hba.c
- src/backend/libpq/pqcomm.c
- src/backend/optimizer/plan/planner.c
- src/backend/snowball/README
- src/backend/utils/adt/enum.c
- src/backend/utils/adt/lockfuncs.c
- src/backend/utils/time/snapmgr.c
- src/include/catalog/pg_enum.h
- src/include/nodes/execnodes.h
- src/include/utils/snapmgr.h
- src/pl/plpgsql/src/expected/plpgsql_trap.out
- src/pl/plpgsql/src/sql/plpgsql_trap.sql
- src/pl/tcl/pltcl.c
- src/test/isolation2/sql_isolation_testcase.py
- src/tools/pgindent/pgindent
Backport multiple commits removing uninclusive terms listed below.  Manually remove all additional uses of those terms.
This PR removes all remaining in-tree uses of the terms:
- slave
- blacklist
- whitelist
A follow-up PR will reduce uses of the term "master", to the extent practically possible.
Backports: 
* b0d184e99f047204a43a81be79f2f3d0c8f29867 -- removes some usages of "master" and "slave" from code/tests/comments
* 800714dab76275efefd2f55b0b64126e44d9269e -- removes some usages of "master" and "slave" from tests
* 845d9e66c9cae80eec290de914c819980968a9c2 -- removes some usages of "master" and "slave" from tests
* 845d9e66c9cae80eec290de914c819980968a9c2 -- removes usages of "whitelist" from comments
* 40710e085fd56e2f75c422efb6e500cff5afa4ec -- removes some usages of "whitelist" …
> Inclusive language

- src/backend/commands/analyze.c
- src/test/regress/expected/analyze.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/analyze.sql
This reverts commit 93acc3eaf3d6545ee7ba5f3b588b11ff22ce9d4e.
This commit introduced a regression when running ANALYZE on an AOCO table having dropped columns of a fixed length.
ExecCopySlotHeapTuple does conversion from virtual tuple to heap tuple and it's referencing the dropped columns, but the slot values have not been initialized for the dropped columns.
```
#0  0x00007f80581d54fb in raise () from /home/gpadmin/cases/ALL/345767/packcore-postgres.695501.181669.core/lib64/libpthread.so.0
#1  0x0000000000c03f90 in StandardHandlerForSigillSigsegvSigbus_OnMainThread (processName=<optimized out>, postgres_signal_arg=11) at elog.c:5581
#2  <signal handler called>
#3  heap_compute_data_size (tupleDesc=tupleDesc@entry=0x7f801c545df8, values=0x313fe78, isnull=isnull@entry=0x32e0ad8 "") at …
```
> revert 6X: Don't scan dropped columns during ANALYZE for AOCO tables.

- src/backend/gporca/data/dxl/minidump/CTEMisAlignedProducerConsumer.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-SPE-Boolean1.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-SPE-Boolean2.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CConstraintInterval.h
- src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
- src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
- src/backend/gporca/libgpopt/src/base/CDefaultComparator.cpp
- src/backend/gporca/libgpopt/src/base/CUtils.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/backend/gporca/server/src/unittest/gpopt/translate/CTranslatorExprToDXLTest.cpp
- src/test/regress/expected/partition_prune_optimizer.out
- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/expected/qp_targeted_dispatch_optimizer.out
- src/test/regress/sql/partition_pruning.sql
After Postgres 12 merge into GPDB, GPDB absorbed the underlying Postgres
partition implementation. In the process, ORCA lost static partition
pruning on boolean partitioned tables. In order to support that feature,
ORCA constraint framework needs to support boolean types as interval
constraints for contraint contradiction.
In SQL standard, boolean type includes NULL and UNKNOWN. Some special
care was needed to handle UNKNOWN type as it relates to an interval
constraint. Since it is unknown, it can be anywhere on the spectrum
(-inf, inf), hence that is the range we assign it.
> [ORCA] Support boolean static partition pruning 

- gpcontrib/gp_inject_fault/README
- gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
- src/backend/cdb/cdbdtxrecovery.c
- src/backend/utils/misc/faultinjector.c
- src/include/cdb/cdbtm.h
The test was flaky with a diff:
```
@@ -25,8 +25,10 @@
-- session1 will be fatal.
1: select count(*) > 0 from gp_dist_random('pg_class');
-FATAL:  could not allocate resources for segworker communication
-server closed the connection unexpectedly
+ ?column?
+----------
+ t
+(1 row)
```
The reason is that the DTX recovery process got ahead and detonate it first...
```
2023-04-20 17:03:26.380438 UTC,,,p119165,th1614203008,,,,0,con2,,seg-1,,,,sx1,"LOG","00000","DTM Started",,,,,,,0,,"cdbdtxrecovery.c”,155
...
2023-04-20 17:04:18.184150 UTC,,,p119165,th1614203008,,,,0,con2,,seg-1,,,,sx1,"LOG","XX009","fault triggered, fault name:'make_dispatch_result_error' fault type:'skip' ",,,,,,,0,,"faultinjector.c",475,
2023-04-20 17:04:18.292955 …
```
> Fix a flakiness in test gpdispatch

- src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
- src/backend/gporca/data/dxl/minidump/ArrayCoerceCast.mdp
- src/backend/gporca/data/dxl/minidump/ArrayCoerceExpr.mdp
- src/backend/gporca/data/dxl/minidump/ArrayCoerceImplicitCast.mdp
- src/backend/gporca/data/dxl/minidump/SimpleArrayCoerceCast.mdp
- src/backend/gporca/data/dxl/parse_tests/q26-Metadata.xml
- src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CScalarArrayCoerceExpr.h
- src/backend/gporca/libgpopt/src/base/CCastUtils.cpp
- src/backend/gporca/libgpopt/src/base/CUtils.cpp
- src/backend/gporca/libgpopt/src/operators/CScalarArrayCoerceExpr.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLScalarArrayCoerceExpr.h
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDArrayCoerceCastGPDB.h
- src/backend/gporca/libnaucrates/src/md/CMDArrayCoerceCastGPDB.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLScalarArrayCoerceExpr.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerMDArrayCoerceCast.cpp
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerScalarArrayCoerceExpr.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CCastTest.cpp
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
As part of GP6 and older versions, ArrayCoerceExpr struct held the
information of the cast function as function oid and a boolean
isExplicit for representing if its an explicit or implicit cast.
Starting PG11 this was changed to an Expr elemexpr.
This PR updates the representation of CDXLScalarArrayCoerceExpr in
ORCA so that we can correctly roundtrip the Expr *elemexpr.
Thus addressing the 2 FIXME's that are removed as part of this PR.
> Address Fixme related to ArrayCoerceExpr

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-html.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
- gpdb-doc/markdown/ref_guide/toc.md
The view gp_resgroup_status_per_segment is not included in GPDB 7, removing references to it.
> Removed all references of gp_resgroup_status_per_segment

- src/backend/catalog/storage_database.c
- src/backend/postmaster/checkpointer.c
- src/test/regress/input/alter_db_set_tablespace.source
- src/test/regress/output/alter_db_set_tablespace.source
1. Set the fsync GUC to on.
2. Make changes to a database and move it to another tablespace, for example:
```
psql -c "create tablespace ts1 location '/tmp/ts'" postgres
psql -c "create database test" postgres
psql -c "create table t (i int)  DISTRIBUTED randomly" test
psql -c "alter database test SET TABLESPACE ts1" postgres
```
If a mirror checkpointer doesn't create checkpoint between "create table" and "alter database", then attempt to create checkpoint the next time will result in the file synchronization error, because the file doesn't exist. At the moment of
checkpoint creating the database file has already been moved to a new tablespace, but fsync request to checkpointer was not changed.
The error doesn't manifest itself in PostgreSQL. PostgreSQL removes files …
> Fix mirror checkpointer error on the alter database query

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_DATABASE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_DATABASE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_DATABASE.html.md
this PR updates the listed sql command reference pages to align with the postgres v12 ref page content. i don't believe there was any greenplum-specific content in the original (v6) pages.
doc review site link for ALTER DATABASE (behind vpn), can navigate to others from there:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-db/greenplum-database/GUID-ref_guide-sql_commands-ALTER_DATABASE.html
> docs - update sql ref pages for ALTER/CREATE/DROP DATABASE

- gpdb-doc/markdown/ref_guide/sql_commands/RESET.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/SET.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/SHOW.html.md
bring SET/RESET/SHOW sql ref pages up to postgres 12 content. there appears to be some greenplum-specific info on the SET page, and some postgres info on pages that wasn't in the original/6x docs.
questions:
1. on the SET page, is the statement about the DECLARE command that is preceeded by XXX still true?
2. the postgres SET reference page (https://www.postgresql.org/docs/12/sql-set.html) identifies some config params with a special syntax (like SET SEED, SET NAMES, SET SCHEMA, SET TIME ZONE).  only SET TIMEZONE is currently documented.  i tried the others on a greenplum 7 install, SET SEED and SET NAMES did not work (i may have invoked them incorrectly).  SET SCHEMA did work so i added it to the docs. i am not sure why it wasn't previously documented.  LET ME KNOW IF THIS SHOULD NOT BE …
> docs - updates to SET/RESET/SHOW sql ref pages

- concourse/pipelines/pr_pipeline.yml
This will add the job compile_and_test_gpdb_without_assert, it is the same with compile_and_test_gpdb, except the configure has option --disable-cassert, and do not run check_format, clang_tidy, unit_tests_gporca_rocky8
task in the job, since it is already exist in the job compile_and_test_gpdb
[GPR-1309]
> [Releng]Add without-asserts testing job to gp7 pr pipeline

- concourse/pipelines/pr_pipeline.yml
This will add the job compile_and_test_gpdb_without_assert, it is almost the same with compile_and_test_gpdb, except the configure has option --disable-cassert, and do not run check_format, unit_tests_gporca_rocky8, since it is already exist in compile_and_test_gpdb
[GPR-1309]
> [Releng]Add without-asserts testing to gp6 pr pipeline

- gpdb-doc/markdown/install_guide/install_python_dsmod.html.md
- tensorflow-gpu is removed from DSB-py39 1.1.0. The tensorflow-gpu and
tensorflow are identical now.
- Add transformers.
> Doc - Update Data Science Package for Py39

- src/test/regress/expected/aggregates.out
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/sql/aggregates.sql
Sometimes these prepared statements would be replanned and log ORCA fallbacks, which are expected and ok. However, to make this more deterministic, reset the plan cache in the test.
This uses the same approach as dee8ee04909f03e0aaa1e3def7c6fea4ab11778a and 8fa789e0cde3d6a6c158d6420fdd9c95603b2fd4
> Fix another flaky aggregates ICW test

- gpdb-doc/markdown/ref_guide/sql_commands/RELEASE_SAVEPOINT.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ROLLBACK_TO_SAVEPOINT.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/SAVEPOINT.html.md
bring SAVEPOINT, RELEASE SAVEPOINT, and ROLLBACK TO SAVEPOINT sql ref pages up to postgres 12 content.  didnt notice any greenplum-specific content on the pages.
- SAVEPOINT (can navigate to others from here):  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/sqlref-savepoint/greenplum-database/GUID-ref_guide-sql_commands-SAVEPOINT.html
> docs - updates to RELEASE/ROLLBACK TO... SAVEPOINT sql ref pages

- src/backend/access/transam/xlog.c
- src/backend/access/transam/xloginsert.c
- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/expected/segwalrep/select_throttle.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/segwalrep/select_throttle.sql
- src/test/isolation2/sql/setup.sql
- src/tools/gdb/.gdbinit
Previously, commit https://github.com/greenplum-db/gpdb/commit/611b788d18d6f1ad5235267aee68dc9925eeee96 added throttling for SELECT and other read
operations that call MarkBufferDirtyHint(). Since these operations
generate a lot of Full Page Image (FPI) WALs, the throttling is needed
to avoid large replication lag. The throttling function
`wait_to_avoid_large_repl_lag()` calls `SyncRepWaitForLSN()` in which
the primary waits for mirror to catch up to given LSN.  However, the
throttling function (wait for replication) was added in a critical
section during which PGXACT->delayChkpt is set, and when this variable
is set, the checkpointer process will pause. This would cause a
deadlock situation if the mirror is stopped.
Previous deadlock scenario:
- Backend process of a SELECT query sets …
>  Primary should stop waiting for replication when mirror is stopped 

- src/bin/pg_dump/pg_dump.c
During upgrade, pg_dump will dump table names with sql syntax dollar
quoting to escape table names with special characters. However, using
just $$ as our tag means we do not handle the edge cases of tables
ending in $. This will cause upgrade to fail when pg_restore fails to
bring back such tables. Replace the `$$` tag with `$_GPDB_$`. Tag collision
will still happen on quoted table names containing `$_GPDB_$`, but since
it should be extremely unlikely with this 8 character sequence.
> Fix pg_dump binary-upgrade dollar quoting on table names ending with $

- src/backend/nodes/nodeFuncs.c
- src/backend/utils/misc/guc_gp.c
- src/test/isolation2/expected/resgroup/resgroup_bypass_catalog.out
- src/test/isolation2/input/resgroup/disable_resgroup.source
- src/test/isolation2/input/resgroup/enable_resgroup.source
- src/test/isolation2/sql/resgroup/resgroup_bypass_catalog.sql
Per the comments of raw_expression_tree_walker():
> Currently, the node type coverage extends to SelectStmt and everything
> that could appear under it, but not other statement types.
There are some node types introduced by Greenplum and do not put in raw_expression_tree_walker:
* T_GroupingFunc
* T_TableValueExpr
* T_GroupingClause
* T_CaseWhen
* T_GroupId
* T_Value
I get the above list using:
1. hack the code to log node tag value for SelectStmt during parsing
2. run the full test with the hack code
3. go to log to fetch all node tag value for SelectStmt
4. See what is missing in raw_expression_tree_walker()
No need to consider T_CaseWhen because it is substruct of T_Case which is already handled.
No need to consider T_Value because it will always be changed to other type.
See Github …
> (6x) Add missing nodes for function raw_expression_tree_walker().

- src/backend/access/transam/xlog.c
- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/expected/segwalrep/select_throttle.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/segwalrep/select_throttle.sql
- src/test/isolation2/sql/setup.sql
- src/tools/gdb/.gdbinit
This is the 6X_STABLE backport of https://github.com/greenplum-db/gpdb/pull/15426. 
cherry-picks went smoothly with one minor change: 7X moved `XLogSaveBufferForHint()` from xlog.c to xloginsert.c.
> [6X backport] Primary should stop waiting for replication when mirror is stopped

- concourse/scripts/build_gpdb.py
GPDB 7X uses python3. 7X explain pipeline broke for failing to locate python interpreter.
> Update python version in build script used by ORCA

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
As per https://github.com/greenplum-db/gpdb/pull/15383 changing the default value for guc `vacuum_cost_page_miss` to 2.
> changed default value for guc vacuum_cost_page_miss

- src/backend/storage/ipc/procarray.c
- src/backend/storage/lmgr/proc.c
- src/backend/utils/resgroup/resgroup.c
- src/include/storage/proc.h
Actually, this PR is part of #13481, cause I consider that PR is too complicated
to merge directly, I decided to divide them and keep the core fix.
This PR is quite simple, just added a SpinLock to protect the field of `movetoResSlot`
and `movetoGroupId`, nothing else to say.
----
Since the race condition is not easy to add a test case to trigger it every time. If we
add inject_fault every time we find a race condition, the codes will be bulky.
> [6X] add movetoMutex to protect moveto* fields in PGPROC

- src/backend/catalog/Makefile
- src/backend/catalog/system_views.sql
- src/backend/catalog/system_views_gp_summary.sql
- src/backend/commands/analyze.c
- src/backend/commands/copy.c
- src/backend/replication/basebackup.c
- src/bin/initdb/initdb.c
- src/include/catalog/catversion.h
- src/include/commands/progress.h
- src/test/isolation2/expected/analyze_progress.out
- src/test/isolation2/expected/ao_index_build_progress.out
- src/test/isolation2/expected/basebackup_progress.out
- src/test/isolation2/expected/copy_progress.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/expected/vacuum_progress_column.out
- src/test/isolation2/expected/vacuum_progress_row.out
- src/test/isolation2/input/uao/cluster_progress.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/cluster_progress.source
- src/test/isolation2/sql/analyze_progress.sql
- src/test/isolation2/sql/ao_index_build_progress.sql
- src/test/isolation2/sql/basebackup_progress.sql
- src/test/isolation2/sql/copy_progress.sql
- src/test/isolation2/sql/setup.sql
- src/test/isolation2/sql/vacuum_progress_column.sql
- src/test/isolation2/sql/vacuum_progress_row.sql
Created the following system views for greenplum specific progress reporting
- gp_stat_progress_vacuum_summary
- gp_stat_progress_analyze_summary
- gp_stat_progress_cluster_summary
- gp_stat_progress_create_index_summary
- gp_stat_progress_copy_summary
- gp_stat_progress_basebackup_summary
For reviewer:
- It is better to review commit-by-commit
- Things we are looking for feedback
1. Replicated table are handled differently in most cases
2. Do we calculate average among just primaries or also include the coordinator (mostly only applied to pg_basebackup)?
3. For COPY command, ON SEGMENT commands and replicated tables are handled differently
4. How to define the "pid" column? We report an arbitrary pid from a segment right now.
> Add gp_stat_progress_*_summary system views

- src/backend/gporca/data/dxl/minidump/LOJ-With-Single-Pred-On-Outer.mdp
- src/backend/gporca/data/dxl/minidump/LOJ_NULLTEST-On-SelfCheck-Pred.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
Issue:
Orca tries to eliminate self comparisons at preprocessing, but this early optimization
misleading the further expression preprocesing of LOJ. This PR tries to avoid self comparison
check's of WHERE clause predicate when SELECT's logical child is LOJ.
NOTE:
Postgres Executor’s standard, restriction placed in the ON clause is processed before the join, while a restriction placed in the WHERE clause is processed after the join. That does not matter with inner joins, but it matters a lot with outer joins.
Setup:
CREATE TABLE t2(c0 int, c1 int not null);
INSERT INTO t2 values(1, 2),(3,4),(5,6),(7,8);
CREATE TABLE t3(c0 int not null, c1 int, c2 int);
```
c1
----
(0 rows)
QUERY PLAN
--------------------------------------------------------------------------------------------------- 
Gather …
```
> Wrong results by ORCA when NULL TEST on LOJ

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
This PRs documents the new function and views to the gp.toolkit administrative schema added by https://github.com/greenplum-db/gpdb/pull/15186.
Review site: https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-gp.toolkit/greenplum-database/GUID-ref_guide-gp_toolkit.html#get_column_sizeoid
> Added views to gp.toolkit

- src/backend/utils/init/postinit.c
- src/test/regress/expected/dboptions.out
- src/test/regress/sql/dboptions.sql
It is difficult for users to anticipate how many connections will hit a
database on a segment (multi-slice plans and what not). So, only enforce
a database's connection limit on the coordinator (like for role
connection limits)
> Disallow dbconnlimit checking on segments

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/15441.  the default value of this guc is now false.
> docs - new gp_resource_group_bypass_catalog_query guc default (6X)

- concourse/tasks/diff_explain_results_with_baseline.yml
Change image configuration: centos7 -> rocky8
centos7 has been deleted for 7x
> Fix 7X explain pipeline diff failure

- src/test/recovery/t/002_archiving.pl
As part of https://github.com/greenplum-db/gpdb/pull/15187, we added partial wal file tests to gpdb6. Since partial wal file is already supported by gpdb7, we just need to port the tap tests from the aforementioned PR.
Partial wal scenario:
A few previous commits de7688442f and 7cbee7c introduced the concept of creating and archiving partial wal files when the mirror is promoted while the primary is still alive.  In this case, the last wal file on the old timeline in the mirror's pg_wal dir is renamed with the suffix ".partial".  This partial file also get archived. The original wal file only gets archived once the user runs pg_rewind.
Consider the following example: Let's assume that 0000100004 is the current wal file on the master
start with a master and standby pair
add data to master …
> Add tests for partial wal file generation

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
When explain queries, Greenplum prints non-default GUC parameters. However, when build Greenplum without ORCA, the default value for `'optimizer'` is `'off'`; when build Greenplum with ORCA, the default value is `'on'`. The explain_format test will fail in Greenplum w/o ORCA build. This patch helps fix it.
Failed test:
```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /home/v/workspace/gpdb7/src/test/regress/expected/explain_format.out /home/v/workspace/gpdb7/src/test/regress/results/explain_format.out
--- /home/v/workspace/gpdb7/src/test/regress/expected/explain_format.out        2023-04-19 14:09:17.475129547 +0800
+++ /home/v/workspace/gpdb7/src/test/regress/results/explain_format.out 2023-04-19 14:09:17.501796392 +0800
@@ -299,7 +299,6 @@
Optimizer: "Postgres query optimizer" …
```
> Ignore "optimizer = 'off'" in 'explain_format' test.

- src/pl/plpython/plpy_exec.c
Backport from https://github.com/postgres/postgres/commit/57d0051706b897048063acc14c2c3454200c488f
---- Original Commit Message ----
If we exit a PG_TRY block early via "continue", "break", "goto", or "return", we'll skip unwinding its exception stack.  This change moves a couple of such "return" statements in PL/Python out of PG_TRY blocks.  This was introduced in d0aa965c0a and affects all supported versions.
We might also be able to add compile-time checks to prevent recurrence, but that is left as a future exercise.
Reported-by: Mikhail Gribkov, Xing Guo
Author: Xing Guo
Reviewed-by: Michael Paquier, Andres Freund, Tom Lane
Discussion: https://postgr.es/m/CAMEv5_v5Y%2B-D%3DCO1%2Bqoe16sAmgC4sbbQjz%2BUtcHmB6zcgS%2B5Ew%40mail.gmail.com
Discussion: …
> [7X] Move return statements out of PG_TRY blocks.

- gpMgmt/bin/gppylib/commands/unix.py
Current `findCmdInPath` only search cmd in specific `CMDPATH`, if user has some commands in other locations(but add those locations to `PATH`) and not in the `CMDPATH`, gpdb will cannot find it.
For example, the paths in `CMDPATH` are not existed in `NixOS`, the `PATH` in `NixOS` is like this:
```
/nix/store/vr631vl97c7gfsy1zdwpj60zzxnnz8v6-openssh-9.2p1/bin:/nix/store/zbr5i1jzfaj29v62g9r9xlibhv8295r6-patchelf-0.15
.0/bin:/nix/store/0h7yqpk1gd6argxfv59x1vz0zklhjcnv-gcc-wrapper-12.2.0/bin
```
To solve this problem, the system `PATH` should be added into `CMDPATH`.
> Add system PATH to  findCmdInPath

- src/test/regress/expected/select_parallel_optimizer.out
Non-default collation fallbacks is a known issue that will be addressed in the future, but isn't specific to the PG12 merge. Remove this FIXME as it's not a blocker.
> Remove non-default collation fixme

- src/backend/commands/matview.c
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
In postgres, with option "WITH NO DATA", the materialized view will be truncated without run the query.
In GPDB, the refresh clause is dispatched to segments when execute the query plan. But for WITH NO DATA option, it should be like a TRUNCATE like in postgres, so it doesn't need to take long time to run the query.
By adding an constant-FALSE to the qual to generate a result plan with One-Time Filter. We have hold matview's distribution policy into the query->intoPolicy, planner will create a motion node on the top so that the refresh clause will still dispatch to segments with the query plan and the query can be execute quickly.
> Improve refresh materialized view with "no data" option

- src/backend/utils/resource_manager/memquota.c
`Mixed-Agg` may appear when rollup or cube used in aggregation. Assuming that MIXED must contains hash-agg, it should be memory intensive. Gp7 might forget to add this, but it may causes unnecessary spill if we do not pay attention to the scene i mentioned before.
> [7X] mem intensive agg should contains mixed type

- src/test/regress/sql/partition_join.sql
GPDB does not support the Lateral feature officially.
some of the lateral features do work well, such as:
```
create table t1(Tc1 int, tc2 int);
create table t2(Tc3 int, tc4 int);
explain SELECT * FROM t1 LEFT JOIN LATERAL
(SELECT a.tc3, least(t1.tc1,a.tc3) from t2 a) ss
ON t1.tc1=ss.tc3;
```
we specify the keyword LATERAL to indicate in subquery we can use the column of t1.
Above join do not need motion between t1 and ss. So it can work well.
However, some of the lateral features do not work well, such as the following sql:
```
create table t1(Tc1 int, tc2 int);
create table t2(Tc3 int, tc4 int);
explain SELECT * FROM t1 LEFT JOIN LATERAL
(SELECT a.tc3, a.tc4, least(t1.tc1, a.tc3) from t2 a) ss
ON t1.tc2=ss.tc4;
ERROR:  could not devise a query plan for the given query (pathnode.c:275) …
```
> resove fixme for lateral left join in partition_join.sql

- src/backend/utils/mmgr/aset.c
The PR is a manual merge of postgres commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=99e74cd235a5cb7d58eadfc627e4e1b1ebac1231
The discussion is here: https://postgr.es/m/CACiT8iaAET-fmzjjZLjaJC4zwSJmrFyL7LAdHwaYyjjQOQ4hcg@mail.gmail.com
It fixed some Valgrind markings in AllocSetRealloc which may cause false valgrind error reports.
> Fix some Valgrind markings in AllocSetRealloc

- src/backend/utils/resgroup/test/resgroup_test.c
Guc value `gp_resource_group_bypass_catalog_query` doesn't get default value in unittest environment, so i set the value in unittest.
> fix bypass catalog unittest

- src/backend/gporca/data/dxl/minidump/LOJ-With-Single-Pred-On-Outer.mdp
- src/backend/gporca/data/dxl/minidump/LOJ_NULLTEST-On-SelfCheck-Pred.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
cherry picked from commit (https://github.com/greenplum-db/gpdb/pull/15358)
Issue:
Orca tries to eliminate self comparisons at preprocessing, but this early optimization
misleading the further expression preprocesing of LOJ. This PR tries to avoid self comparison
check's of WHERE clause predicate when SELECT's logical child is LOJ.
NOTE:
Postgres Executor’s standard, restriction placed in the ON clause is processed before the join,
while a restriction placed in the WHERE clause is processed after the join.
That does not matter with inner joins, but it matters a lot with outer joins.
Setup:
```
CREATE TABLE t2(c0 int, c1 int not null);
INSERT INTO t2 values(1, 2),(3,4),(5,6),(7,8);
CREATE TABLE t3(c0 int not null, c1 int, c2 int);
SELECT t2.c1 FROM t2 LEFT OUTER JOIN t3 ON t3.c1 > t3.c2 …
```
> Fix wrong results by ORCA when NULL TEST on LOJ

- src/test/regress/expected/constraints_check.out
- src/test/regress/parallel_schedule
- src/test/regress/sql/constraints_check.sql
As the title said, add test case for over-eager constraint exclusion. Please refer to [issue 10287 comment](https://github.com/greenplum-db/gpdb/issues/10287#issuecomment-1333659985)
**Signed-off-by**: Yongtao Huang <yongtaoh@vmware.com>
> Add test case for over-eager constraint exclusion (7X)

- src/backend/utils/resgroup/test/resgroup_test.c
Fix bypass catalog unittest.
Guc value gp_resource_group_bypass_catalog_query doesn't get default value in unittest environment, so i set the value in unittest.
BTW, the unittest should return non-0 value when cases failed.
> (backport to 6X) Fix bypass catalog unittest

- src/backend/commands/analyze.c
- src/backend/commands/analyzefuncs.c
- src/test/regress/expected/analyze.out
- src/test/regress/expected/bfv_dd.out
- src/test/regress/expected/bfv_dd_multicolumn.out
- src/test/regress/expected/bfv_dd_multicolumn_optimizer.out
- src/test/regress/expected/bfv_dd_optimizer.out
- src/test/regress/sql/analyze.sql
Send results of select pg_catalog.gp_acquire_sample_rows query in binary mode.
That allows to avoid overflow for max double.
For example, if run the following prior to this fix:
set extra_float_digits to 0;
create table t (a double precision);
insert into t values (1.7976931348623157e+308);
analyze t;
the following message will be printed:
ERROR:  value out of range: overflow
For text mode (default) when analyze for table is performed the
master calls gp_acquire_sample_rows() helper function on each
segment. That eventually calls float8out function on segment to
converts float8 number to a string with snprintf:
int	ndig = DBL_DIG + extra_float_digits; 
snprintf(ascii, MAXDOUBLEWIDTH + 1, "%.*g", ndig, num); 
When ndig is 15 the maximum float8 value 1.7976931348623157e+308 is
rounded to …
> Send rows in binary mode for ANALYZE

- gpdb-doc/markdown/utility_guide/ref/pg_dump.html.md
See issue https://github.com/greenplum-db/gpdb/issues/15014
pg_dump does not include/exclude leaf partitions for GPDB 7.x. The following options have been ported:
--table-and-children=pattern
--exclude-table-and-children=pattern
--exclude-table-data-and-children=pattern
which act the same as the existing --table, --exclude-table, and --exclude-table-data switches, except that any partitions or
inheritance child tables of the table(s) matching the pattern are also included or excluded.
@AJR-VMware could we get an example on how to use the pattern? Thanks.
Sample site: https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-pg_dump/greenplum-database/GUID-utility_guide-ref-pg_dump.html
> added new pg_dump options

- gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
- gpdb-doc/markdown/utility_guide/ref/vacuumdb.html.md
Added Vacuum option ao_aux_only as per https://github.com/greenplum-db/gpdb/pull/14984
Also added reference to vacuumdb wraparound (let me know if this is correct).
Let me know if the syntax is correct, I added it as as completely different option, not sure if compatible with any of the other VACUUM options.
Review sites:
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-ref_guide-sql_commands-VACUUM.html
https://docs-staging.vmware.com/en/VMware-Tanzu-Greenplum/mireia-vacuum/greenplum-database/GUID-utility_guide-ref-vacuumdb.html
> Added ao_aux_only option

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
Documentation update after https://github.com/greenplum-db/gpdb/pull/15344
`ALTER COLUMN TYPE` does not require a table rewrite for AO/CO tables.
> Modified table entry for alter column type and aoco tables

- src/test/isolation2/input/resgroup/resgroup_memory_limit.source
- src/test/isolation2/output/resgroup/resgroup_memory_limit.source
The previous processes accept the query cancel command and returned before they exited compeletely. The following commands continuously require to alloc memory and previous processes haven't released the allocated memory, it finally cause the out of memory error.
Sleep a while to wait for the previous processes exit.
> fix resgroup_memory_limit test failure

- src/backend/optimizer/path/allpaths.c
- src/test/regress/expected/bfv_cte.out
- src/test/regress/sql/bfv_cte.sql
GPDB_96_MERGE_FIXME: Should we check forceDistRandom here, like set_subquery_pathlist() does? 
```
create table ttt(tc1 int,tc2 int) ;
insert into ttt values(1,1);
insert into ttt  values(2,2);
WITH cte AS (
SELECT oid, relname
FROM pg_class
WHERE oid <2000
)
SELECT *
FROM gp_dist_random('cte')
JOIN ttt ON cte.oid = ttt.tc2;
ERROR:  relation "cte1" does not exist
```
CET can not be the param of gp_dist_random.
So in set_cte_pathlist we do not need to check forceDistRandom.
Remove GPDB_96_MERGE_FIXME in allpaths.c
> resolve fixme, do not need to check forceDistRandom in set_cte_pathlist

- src/backend/utils/misc/guc_gp.c
After Postgres 12 merge the GUC to set default table type was moved to default_table_access_method as hinted by the error message.
```
SET gp_default_storage_options='appendonly=true';
ERROR:  invalid storage option "appendonly"
HINT:  For table access methods use "default_table_access_method" instead.
```
Instead seems one should run:
```
SET default_table_access_method='ao_row';
```
Remove the stale comment that suggested otherwise.
> Fix up stale gp_default_storage_options comment

- src/backend/catalog/gp_toolkit.sql
- src/include/catalog/catversion.h
- src/test/regress/expected/.gitignore
- src/test/regress/greenplum_schedule
- src/test/regress/input/gp_check_files.source
- src/test/regress/output/gp_check_files.source
- src/test/regress/sql/.gitignore
The existing orphaned/missing file checking views (`gp_toolkit.gp_check_orphaned_files`, `gp_toolkit.gp_check_missing_files` etc.) have many false alarm possibilities. A few examples:
1. Views created from tables via the `CREATE RULE ... ON SELECT...` syntax still have valid relfilenodes. However, its data file might have already been removed, causing false missing file report.
2. An entry in the aoseg/aocsseg does not necessarily mean there is data file associated with them. For example, an entry could be created just for recording modcount (we chose any non-reserved segment to do that). This could cause false missing file report as well. Note that, such entries would have `eof=0`.
3. An AO/CO table being created and then truncated in the same transaction will not have its extended data …
> Fix missing/orphaned file checking views

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
The default value of `gp_interconnect_address_type` is changed from `wildcard` to `unicast` in 7X. Fix it in the doc, and add explanation appropriately.
> DOCS: Fix the default value of gp_interconnect_address_type in 7X

- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
This PR marks the FIXME as unsupported for now because enabling the "PexprConvert2In" preprocessing step is leading to multiple issues like IN operator with Hash Indexed Table is falling back to planner,wrong filters are generated while converting a  "OR" between a date and timestamp to IN operator etc.
> Marking the "PexprConvert2In" preprocessing step as "unsupported for now"

- src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
GUC optimizer_enable_multiple_distinct_aggs is supposed to enable
multi-DQA in ORCA. However, after commit https://github.com/greenplum-db/gpdb/commit/0ccfee593d37ebac09fafad25b62e792832bd438 that stopped
working.
Issue is that the offending commit updated child arguments of
CScalarAggFunc to store additional aggregate info (e.g. order/distinct
args). ORCA detects whether a query has multi-DQA by parsing a project
list. When the list format changed, ORCA failed to detect multi-DQA and
failed to trigger xform CXformGbAggWithMDQA2Join.
Fix parses the new format. Also, since we now allow multiple distinct
arguments we cannot simply pass the first distinct argument. Hence the
need to pass the list of distinct argments.
> [ORCA] Fix option to enable multi-distinct agg 

- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
- src/test/regress/expected/gp_dqa_optimizer.out
Automatic merge did not resolve conflict correctly. Commits 94c62c2a026a and 4581ce9679 updated the same MDPs, but the space size conflicted.
> Fix ORCA build break

- src/backend/utils/misc/guc_gp.c
Currently, we don't show all relevant Orca gucs when running `show all`, which is useful when gathering system information and debugging user systems.
> Mark additional Orca gucs to be shown in guc list

- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/resgroup.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/expected/resgroup/resgroup_bypass.out
- src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
- src/test/isolation2/isolation2_resgroup_v1_schedule
- src/test/isolation2/isolation2_resgroup_v2_schedule
- src/test/isolation2/sql/resgroup/resgroup_bypass.sql
- src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
This commit introduces a new GUC gp_resource_group_bypass_direct_dispatch which is defaultly true. After getting the plan, we can unassign (bypass) from resgroup:
- for SelectStmt, direct dispatch means there are two slices and the 1st slice is QD and the 2nd is direct dispatch
- for (Update|Delete|Insert)Stmt, direct dispatch means there is only one slice and that slice is direct dispatch
Also we move some tests into bypass suite.
Co-authored-by: Wenru Yan <ywenru@vmware.com>
> Resgroup can unassign(bypass) for direct dispatch plans.

- src/test/recovery/t/002_archiving.pl
A previous commit 700cad0 added tap tests for the partial wal file feature. This test was a bit flaky on the ci pipeline.
Context:
Once we promote the standby(while the primary is running), a partial wal file gets generated on the standby. In order to test if this file gets generated with the correct name, we were previously querying the pg_stat_archiver view. We would compare the name of the last archived wal with the expected partial wal filename. It's possible that this comparison would return wrong results on some platforms because of the ">=" predicate(which could change based on the sorting order.)
Fix:
This commit removes the use of pg_stat_archiver view and instead relies on the pg_stat_file function to check for the existence of the partial wal file and other files in the tap …
> Fix flaky archiving tap test

- src/backend/catalog/catalog.c
- src/backend/commands/schemacmds.c
- src/backend/commands/tablespace.c
- src/backend/replication/logical/origin.c
- src/include/catalog/catalog.h
- src/test/regress/expected/role.out
- src/test/regress/sql/role.sql
The merge with upstream absorbed 293007898d3fa5a815c1c5814df53627553f114d which disallowed creating roles with reserved names because some default system roles started with 'pg_' were introduced since 9.6 so we don't want them to conflict: https://www.postgresql.org/docs/9.6/default-roles.html
However, in Greenplum reserved names include not only 'pg_' but also 'gp_'. But we do not have any system roles starting with 'gp_' so it is fine to allow users to still create those roles.
Now modifying IsReservedName() to pass a parameter to indicate whether we want to reserve 'gp_' or not. It would create more footprint in the codebase than e.g. don't change IsReservedName() but just check 'gp_' explicitly when doing role name checking. But modifying IsReservedName() would force the caller to …
> Allow role names started with 'gp_'

- src/backend/access/common/reloptions_gp.c
Resolves the warning
```
reloptions_gp.c: In function 'validate_and_adjust_options': reloptions_gp.c:927:48: warning: argument to 'sizeof' in 'strncpy' call is the same expression as the source; did you mean to use the size of the destination? [-Wsizeof-pointer-memaccess]
927 |    strncpy(result->compresstype, "zstd", sizeof("zstd"));
```
> Fix compiler warning in reloptions_gp.c

- src/backend/optimizer/util/relnode.c
The `width` is now in `joinrel->reltarget` and has been set in `build_joinrel_tlist()` and `add_placeholders_to_joinrel()`. After the merge of PostgreSQL 9.6, the concept of `PlaceHolderVar` was introduced, calculating in this way may cause us to ignore the width of `PlaceHolderVar` and thus underestimate the cost of joinrel.
> Remove GPDB_96_MERGE_FIXME in relnode.c:724

- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/sql/partition_pruning.sql
This FIXME was for planner's lack of partition pruning in certain cases. The logic in GP6 could generate wrong results, so it was decided to remove the over-eager optimization for GP7. Orca never did pruning in this case. See https://github.com/greenplum-db/gpdb/issues/10287 and https://github.com/greenplum-db/gpdb/pull/14553 for additional context.
> Remove FIXME in partition_pruning that was already addressed

- src/bin/pg_dump/pg_dump.c
This is a 6X backport of 7X commit:
8a12c8077afb784a519f247948c2b61de3ac26bd
original commit message:
During upgrade, pg_dump will dump table names with sql syntax dollar
quoting to escape table names with special characters. However, using
just $$ as our tag means we do not handle the edge cases of tables
ending in $. This will cause upgrade to fail when pg_restore fails to
bring back such tables. Replace the $$ tag with $_GPDB_$. Tag collision
will still happen on quoted table names containing $_GPDB_$, but since
it should be extremely unlikely with this 8 character sequence.
> [6x backport] Fix pg_dump's dollar quoting for table names ending with $

- src/backend/nodes/copyfuncs.c
- src/backend/nodes/outfuncs.c
- src/backend/nodes/readfuncs.c
- src/backend/optimizer/plan/planner.c
- src/include/nodes/plannodes.h
PlanRowMark.canOptSelectLockingClause field is removed as it has been replaced by RangeTblEntry.rellockmode field and never used again.
> solve GPDB_96_MERGE_FIXME in planner.c

- src/backend/access/aocs/aocs_compaction.c
- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/backend/commands/analyze.c
- src/backend/commands/analyzefuncs.c
- src/backend/utils/datumstream/datumstream.c
- src/backend/utils/misc/sampling.c
- src/include/access/tableam.h
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/include/cdb/cdbappendonlyblockdirectory.h
- src/include/commands/vacuum.h
- src/include/utils/datumstream.h
- src/include/utils/sampling.h
- src/test/isolation2/expected/ao_blkdir.out
- src/test/isolation2/input/uao/fast_analyze.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/fast_analyze.source
- src/test/isolation2/sql/ao_blkdir.sql
Prior to this patch, GPDB ANALYZE on large AO/CO tables is a time-consuming process.
This is because PostgreSQL's two-stage sampling method didn't work well on AO/CO tables.
GPDB had to unpack all varblocks till to the target tuples, which could easily result in
almost full table scanning if sampling tuples fall around the end of the table.
Denis Smirnov <sd@picodata.io> 's PR greenplum-db#11190 introduced
a `logical` block concept containing fixed number of tuples to support PG's two-stage sampling
mechanism, also it sped up fetching target tuples by skipping uncompression of varblock content.
Thanks for Denis Smirnov's great contribution!
Also, thanks for Ashwin Agrawal <aashwin@vmware.com> 's advice on leveraging AO Block Directory
to locate the target sample row without scanning …
> Implement Fast Analyze on AO/CO Tables

- src/backend/optimizer/plan/planner.c
- src/include/optimizer/orca.h
optimize_query is qualified by static and defined in orca.h. If build gpdb w/o ORCA and include orca.h without using optimize_query, there will be warnings.
```
In file included from explain.c:56:
../../../src/include/optimizer/orca.h:31:1: warning: 'optimize_query' defined but not used [-Wunused-function]
31 | optimize_query(Query *parse, int cursorOptions, ParamListInfo boundParams)
| ^~~~~~~~~~~~~~
```
> [7X] Suppress compiler warning.

- src/test/regress/expected/qp_misc_jiras.out
- src/test/regress/expected/qp_misc_jiras_optimizer.out
- src/test/regress/expected/qp_misc_rio.out
- src/test/regress/sql/qp_misc_jiras.sql
- src/test/regress/sql/qp_misc_rio.sql
Long log:
Don't need to cast the unknown typed literal to text, drop the cast and remove FIXME.
Related PR https://github.com/greenplum-db/gpdb/commit/1e7c4bb0049732ece651d993d03bb6772e5d281a
> Remove FIXME: cast the unknown typed literal to text (7X)

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/db/catalog.py
- gpMgmt/bin/gppylib/operations/Makefile
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/get_segments_in_recovery.py
- gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_get_segments_in_recovery.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
- gpMgmt/bin/gppylib/programs/clsAddMirrors.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/bin/gppylib/recoveryinfo.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegsetuprecovery.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/sbin/gpsegsetuprecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
**Context:**
Greenplum so far has 2 modes for mirror recovery: FULL and INCREMENTAL. Incremental happens in 2 flavors based on the situation purely WAL based or pg_rewind based. Existing mirror disconnecting and reconnecting back is purely WAL based incremental recovery. When for a segment, preferred roles is same as actual role on running gprecoverseg, incremental pg_rewind based recovery happens
**Challenge:**
In some situations, incremental recovery could fail like due to missing WAL logs (because of GUC max_slot_wal_keep_size or space constraints) or pg_rewind interrupted. Postgres does not recommend running pg_rewind again upon failure (https://www.postgresql.org/docs/current/app-pgrewind.html). FULL recovery is the only fallback option in these cases. GPDB's majority of use cases …
> gprecoverseg differential recovery(rsync based)

- concourse/README.md
- concourse/pipelines/gen_pipeline.py
`os.getlogin` will get the following error when creating pipeline:
```
File "./gen_pipeline.py", line 505, in <module>
main()
File "./gen_pipeline.py", line 413, in main
default=os.getlogin(),
OSError: [Errno 6] No such device or address
```
`getpass.getuser` is more recommended according to the [Python API manual](https://docs.python.org/3/library/os.html#os.getlogin).
Port #15296 to gpdb7
> Replace os.getlogin with getpass.getuser in gen_pipeline.py [7X]

- concourse/README.md
- concourse/pipelines/gen_pipeline.py
`os.getlogin` will get the following error when creating pipeline:
```
File "./gen_pipeline.py", line 505, in <module>
main()
File "./gen_pipeline.py", line 413, in main
default=os.getlogin(),
OSError: [Errno 6] No such device or address
```
`getpass.getuser` is more recommended according to the [Python API manual](https://docs.python.org/3/library/os.html#os.getlogin).
> Replace os.getlogin with getpass.getuser in gen_pipeline.py

- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/test/isolation2/expected/ao_blkdir.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/ao_blkdir.sql
This commit clarifies the hidden intent behind one of
AppendOnlyBlockDirectory_GetEntry()'s branches to exit early, when the
rowNum being looked up doesn't have a minipage entry it belongs to and
yet is lower than the highest minipage entry in the page.
This optimization is pretty crucial as it saves us from per-tuple
sysscans further down in AppendOnlyBlockDirectory_GetEntry() for any
rowNum falling in a hole between two blkdir entries. Such holes can
arise from aborted inserts.
Consider the following example (all data in seg1):
```
create table foo(i int, j int) with(appendonly=true);
create index on foo(i);
insert into foo select 1;
begin; insert into foo select 20, i from generate_series(1, 10000000)i; abort;
```
We have a hole at the end of the minipage.
```
select …
```
> aofetch: Clarify early exit for inter-entry hole

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
**Long log:**
This commit can fix bug reported in [issue 15104](https://github.com/greenplum-db/gpdb/issues/15104)
If we do` gpcheckcat -R owner postgres`, it can identify the 
- AO table/index; 
- aovisimap table/index;
In fact, we don't need to identify `aovisimap table/index`.
So we rewrite the SQL query in function `checkOwners()`.
Co-authored-by: Huansong Fu <fhuansong@vmware.com>
Co-authored-by: Xing Guo <guxing@vmware.com>
> FIX BUG: gpcheckcat owner with AO return wrong results (7X)

- src/backend/parser/parse_partition_gp.c
Long log:
In src/backend/parser/parse_partition_gp.c,
function transformGpPartDefElemWithRangeSpec()
has duplicated if condtions, `if (boundspec->partEvery)`
and `else if (boundspec->partEvery)`.
So delete redundant `else if (boundspec->partEvery)`. 
Related issue: [15041](https://github.com/greenplum-db/gpdb/issues/15041)
Signed-off-by:Yongtao Huang <yongtaoh@vmware.com>
> Remove duplicated if(boundspec->partEvery) (7X)

- src/backend/optimizer/util/pathnode.c
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/sql/gp_recursive_cte.sql
Prior to 9.6 merge, given the locus of the non-recursive path of a
recursive CTE as input, we used to set the locus of the recursive
path, aka WorkTaleScan, to Strewn in some cases.
This logic was first introduced by commit fd61a4ca26 which initially
brought recursive CTE into Greeanplum. However the logic was lost
during PostgreSQL 9.6 merge by commit
greenplum-db/gpdb-postgres-merge@799c7f90fc in iteration_REL9_6 merge
branch. A GPDB_96_MERGE_FIXME had been added by a merge commit
greenplum-db/gpdb-postgres-merge@c67c3ec4f8, along with this merge
commit, an additional add-on to the logic for OuterQuery by Greenplum
commit 00e25afe11 was also overlooked. Later on by commit b5bc9dfcf9,
even the merge FIXME was innocently removed.
This patch adds the missing logic back and adds test for …
> Correctly set locus for WorkTable Scan

- configure
- configure.in
- src/backend/jit/llvm/llvmjit.c
- src/backend/jit/llvm/llvmjit_inline.cpp
Per https://llvm.org/docs/OpaquePointers.html, support for non-opaque pointers still exists and we can request that on our context.  We have until LLVM 16 to move to opaque pointers, a much larger change.
Back-patch to 11, where LLVM support arrived.
Author: Thomas Munro <thomas.munro@gmail.com>
Author: Andres Freund <andres@anarazel.de>
Discussion: https://postgr.es/m/CAMHz58Sf_xncdyqsekoVsNeKcruKootLtVH6cYXVhhUR1oKPCg%40mail.gmail.com (cherry picked from commit aa34bc4e2bc8d13efb38b349f39b0f3b04883ffb)
> Track LLVM 15 changes.

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- src/backend/utils/misc/guc.c
This commit updates autovacuum GUC defaults based on the findings
presented in https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/5yRc-FBB9i8/m/Ju9p4oqXAAAJ
autovacuum_vacuum_threshold: Increase to 500 so not constantly vacuuming small catalog tables.
autovacuum_vacuum_scale_factor: Reduce to 5% to trigger AVs more frequently that each do less work, smoothing out I/O
autovacuum_work_mem: Allows more tuple identifiers to be stored in dead tuple array, may reduce number of index scans during vacuum.
> Update autovacuum GUC default values.

- src/backend/access/transam/xact.c
- src/backend/utils/cache/inval.c
- src/include/utils/inval.h
`malloc` uses locks internally to ensure thread-safety. When the signal handler is called, and `malloc` is already holding a lock, the subsequent signal delivery will be blocked until the `malloc` call completes. However, the `malloc` call will be waiting indefinitely for the lock to be released, resulting in a deadlock. 
This PR backports the upstream commit to avoid calling `malloc()` in `procsignal_sigusr1_handler()`. Call Stack: `procsignal_sigusr1_handler()` -> `HandleCatchupInterrupt()` -> `ProcessCatchupEvent()` -> `StartTransactionCommand()` -> `StartTransaction()` -> `AtStart_Inval()` -> `MemoryContextAllocZero()` -> ... -> `malloc()`.
---
Original commit message：
> Instead of initializing a new `TransInvalidationInfo` for every transaction or subtransaction, we can just do it …
> [6x][backport]Avoid setup work for invalidation messages at start-of-(sub)xact.

- src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
- src/backend/gporca/data/dxl/minidump/Union-On-HJNs.mdp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
GUC optimizer_enable_multiple_distinct_aggs is supposed to enable multi-DQA in ORCA. However, after commit 0ccfee593d3 that stopped working.
Issue is that the offending commit updated child arguments of CScalarAggFunc to store additional aggregate info (e.g. order/distinct args). ORCA detects whether a query has multi-DQA by parsing a project list. When the list format changed, ORCA failed to detect multi-DQA and failed to trigger xform CXformGbAggWithMDQA2Join.
Fix parses the new format. Also, since we now allow multiple distinct arguments we cannot simply pass the first distinct argument. Hence the need to pass the list of distinct arguments.
(cherry-picked from https://github.com/greenplum-db/gpdb/commit/94c62c2a026af8deb5268fcd6ef17e1e5ef60531)
> [ORCA] Fix option to enable multi-distinct agg  (#15445)

- src/test/regress/expected/autovacuum-ao-aux.out
- src/test/regress/sql/autovacuum-ao-aux.sql
7dbd59be34a2892143fe8911cc4a23e5324fbb10 increased the autovacuum_vacuum_threshold default from 50 to 500 and reduced the autovacuum_vacuum_scale_factor from 0.2 to 0.05. This resulted in the auto_vac_worker_after_report_activity not being triggered for autovacuum-ao-aux regress test.
Adjust autovacuum_vacuum_threshold for the test to ensure the fault is triggered.
> Reduce vac threshold for av-ao-aux test

- GNUmakefile.in
Add analyzedb to ICW for regression and isolation databases. We'll run this after gpcheckcat.
This is useful for ensuring all types and tables can be analyzed and provides a data point for analyze performance. Currently, analyzedb takes 83 seconds for the regression database in CI.
> Run analyzedb during ICW

- src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
- src/test/regress/expected/qp_orca_fallback.out
- src/test/regress/expected/qp_orca_fallback_optimizer.out
- src/test/regress/sql/qp_orca_fallback.sql
ORCA assumes that if a table is partitioned it's partition key column
isn't dropped.  This assumption holds true as GPDB doesn't allow
dropping partition key column via direct drop(`ALTER ... DROP COLUMN`). 
But, if a partition key column is a user type and is dropped using 
`DROP TYPE..CASCADE` the partition key column is also dropped.
This will break the underlying assumption in ORCA which may lead to
unknown crashes.
This PR fixes this issue by falling back to planner in such
scenarios.
Note: this issue does not exist on GP7 as if `DROP TYPE..CASCADE` is called on a type associated with partition key column, the table is dropped (similar to Postgres)
> [6X]: ORCA Fallback to planner if table contains dropped partition key column 

- src/backend/access/common/memtuple.c
- src/include/access/memtup.h
The main change is to remove the code that handles of the old nul_saves array which is no longer used. And use the name "null_saves" to indicate the new/existing format (which was "null_saves_aligned"). Some archaeology:
* The original code was added in 1a80ef70aa19 to support old format.
* Later, in 53210fb2a848962155c5d57b69e367fd7fa27ed5 the support was reduced to read-only. All new memtuples were new format since then.
* In f6c74df57e7e9dcb26f3c58b7d3871d0d2e7f717, even the upgrade support was removed. The old format-related code should be completely irrelevant to 7X now.
Also made two smaller changes:
1. memtuple_size_from_uint32 not used anywhere. Removed.
2. memtuple_get_nullp doesn’t need to pass pbind. Reduced.
> Remove some dead code in memtuple.c

- gpMgmt/bin/gppylib/commands/base.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_base.py
1. Updated code to use get_stderr() instead of get_result().stderr
2. Added test case for retry count.
parent pr: https://github.com/greenplum-db/gpdb/pull/15283
> Added test case for pr 15283

- src/backend/storage/lmgr/lock.c
remove redundant code in lock.c
> remove redundant code in lock.c

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- src/backend/access/aocs/aocsam.c
- src/backend/access/appendonly/appendonly_compaction.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/access/common/memtuple.c
- src/backend/catalog/gp_fastsequence.c
- src/backend/catalog/pg_appendonly.c
- src/backend/catalog/pg_attribute_encoding.c
- src/backend/commands/cluster.c
- src/backend/commands/tablecmds.c
- src/include/access/memtup.h
- src/include/catalog/catversion.h
- src/include/catalog/gp_fastsequence.h
- src/include/catalog/pg_attribute_encoding.h
- src/include/cdb/cdbappendonlyam.h
- src/test/isolation2/input/uao/alter_table.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/alter_table.source
- src/test/regress/expected/alter_table.out
- src/test/regress/expected/alter_table_ao.out
- src/test/regress/expected/alter_table_aocs2.out
- src/test/regress/expected/column_compression.out
- src/test/regress/input/appendonly.source
- src/test/regress/output/appendonly.source
- src/test/regress/sql/alter_table.sql
- src/test/regress/sql/alter_table_ao.sql
- src/test/regress/sql/column_compression.sql
Since 16828d5c0273b4fe5f10f42588005f16b415b2d8, heap table can avoid a whole table rewrite in case of ADD COLUMN with non-volatile, non-NULL default value. The way it achieves that is to store the evaluated default values in pg_attribute. To any existing tuples, such a new attribute will be regarded as "missing", and when we read the tuples, we will fill the missing attributes using the values stored in pg_attribute. And, any new tuples being inserted will store the value physically on file (i.e. those attributes are not missing in new tuples).
Now doing the same for ao_row tables. The key difficulty we faced was that unlike heap tuples, the memtuple used by ao_row tables does not store the number of attributes in its header. Therefore, we do not know how many attributes are missing.
The …
> Support fast ALTER TABLE ADD COLUMN for appendonly row-oriented tables

- src/backend/commands/cluster.c
- src/backend/commands/vacuum.c
- src/include/commands/vacuum.h
- src/test/regress/expected/cluster.out
- src/test/regress/expected/cluster_gp.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/cluster_gp.sql
Even though we were sending these stats from QE->QD, we weren't
combining them, nor were we updating QD's pg_class.
Highlights:
(1) Perhaps a bit ugly, but reusing vacuum_combine_stats() and
vac_update_relstats_from_list() on the QD side, just as we reuse
vac_send_relstats_to_qd() on the QE side.
(2) vacuum_combine_stats() now accepts a MemoryContext param for any
on-heap allocation. We pass a vacuum context during vacuum and a cluster
context during cluster.
(3) dispatchCluster() routine to dispatch and update stats thereafter.
Fixes: https://github.com/greenplum-db/gpdb/issues/10489
> cluster: Update relpages,reltuples on QD

- src/backend/cdb/cdbcopy.c
- src/backend/cdb/cdbtm.c
- src/backend/cdb/dispatcher/cdbdisp.c
- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/backend/cdb/endpoint/cdbendpointutils.c
- src/backend/commands/explain.c
- src/backend/executor/execUtils.c
- src/backend/executor/nodeSubplan.c
- src/backend/utils/error/elog.c
- src/include/utils/elog.h
- src/test/regress/expected/interrupt_holdoff_count.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/interrupt_holdoff_count.sql
cases(#15278)
This commit addresses issue #15278, where the InterruptHoldoffCount value was not always resetting to zero in certain abnormal scenarios. This issue had the potential to impact the proper functioning of the ProcessInterrupts process. The fix ensures that the InterruptHoldoffCount value is properly reset to zero in all cases.
this issue is found in #15203 , we will add test cases in pr #15203 
backport form https://github.com/greenplum-db/gpdb/pull/15279
> [6x backport] Fix InterruptHoldoffCount not being reset issue

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
As part of pr 15402 a behave test got added which was broken Fixed by using dbconn.query instead of dbconn.execSQL. only difference between both the api is that execSQL doesn't return any cursor object and it is mostly use for create and update. but the .query() returns cursor object after executing the query.
parent pr: <https://github.com/greenplum-db/gpdb/pull/15402>
> Fix gpexpand behave test fail

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
Previously, header_callback(), used to get and parse HTTP headers, took only first status header from all header blocks to show it to user. The problem is that we can have multiple messages with multiple header blocks. In case of error, only first (successful) status is shown to user, which is not informative. This patch fixes header_callback(), which now process all status headers.
___________________
Here is an example of case we faced during the testing of insertion to gpfdist.
We used a long row (more that 32K) to check how gpfdist handles it.
```
gpfdist -d /opt/gpfdist -p 8081 -l /opt/gpfdist/log8081.log
create writable external table table_ext_wr(s varchar)
location ('gpfdist://localhost:8081/out_00.csv')
format 'CSV';
insert into table_ext_wr
select string_agg(md5(random()::text), …
```
> [7x] Fix url_curl.c headers handling

- src/backend/jit/jit.c
- src/backend/optimizer/plan/planner.c
- src/backend/utils/misc/guc_gp.c
- src/include/jit/jit.h
- src/include/utils/guc.h
- src/include/utils/sync_guc_name.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
Through this PR, we shall enable JIT using ORCA costing model. 
CODE CHANGES 
1. Adding new GUCs for ORCA
We are adding following GUCs for ORCA specifically for JIT compilation:
```
1. optimizer_jit
2. optimizer_jit_above_cost
3. optimizer_jit_inline_above_cost
4. optimizer_jit_optimize_above_cost
```
2. Including the logic so that, JIT flags can be set using ORCA specific JIT GUCs or Planner specific JIT GUCs.
JIT compilation is triggered based on the cost of a plan. Earlier, the cost of plan generated by ORCA/planner was compared with the following JIT specific costing GUCs (defined for planner):
```
1.  jit_above_cost
2.  jit_optimize_above_cost
3.  jit_inline_above_cost
```
Based on the certain conditions, JIT flags were set in the planned statement. Thus, we did not have individual …
> Enabling JIT with Orca costing (7X)

- src/backend/cdb/cdbsetop.c
- src/backend/optimizer/prep/prepunion.c
If `optype` is equal to `PSETOP_PARALLEL_PARTITIONED`, `generate_nonunion_paths` will invoke `make_motion_hash_all_targets` twice for certain subpaths. This won't generate incorrect query plans now because the target locus and subpath locus are equal, the second invocation of `make_motion_hash_all_targets` won't add new motion on top of the existing motion. This commit removes the GPDB_96_MERGE_FIXME and performs some simple refactoring to make the code logic clearer.
> Remove fixme in prepunion.c:848

- configure
- configure.in
- contrib/pgcrypto/openssl.c
- gpcontrib/gpmapreduce/src/mapred.c
- src/backend/access/external/url_curl.c
This PR contains 2 commits
ea3e668dfcca  - Disable -Wdeprecated-non-prototype in the back branches (cherrypicked from upstream)
- It solved the warnings caused by the latest RHEL8/Rocky8/OEL8 updates from Clang14/LLVM14 to Clang15/LLVM15
3c5af863e18a - fixed some other warnings
- url_curl.c: strerr for CURLMcode is applied to avoid wrong error message
- mapred.c: fixed the code style to remove duplicated strlen calls and fit
warning rules for strncpy
- openssl.c: removed the check of FIPS_mode_set existence in running pgcrypto,
as it always exists in libopenssl 1.0.x and 1.1.x . And if linking
to openssl without FIPS, the loading of pgcrypto would just fail.
> Fix gp7 warnings

- src/backend/cdb/cdbpathlocus.c
The codes around FIXME tends to figure out bugs as merging from upstream.
```
if (pathtarget->sortgrouprefs[attno - 1] == 0 &&
contain_volatile_functions((Node *) expr))
{
/*
* GPDB_96_MERGE_FIXME: this modifies the subpath's targetlist in place.
* That's a bit ugly.
*/
pathtarget->sortgrouprefs[attno - 1] = ++maxRef;
}
```
If we don't have these codes, ERROR **"volatile EquivalenceClass has no sortref"** is raised.
That's caused by an assumption which has been added in upstream to slove issues.
related PR https://github.com/greenplum-db/gpdb/commit/d5a4b69c3a0d2668fa6098c73be7b6f0036bb642.
As a result, we could just modify pathtarget->sortgrouprefs[attno - 1] in place, which is safe and no more
regressions.
> Remove FIXME from function cdbpathlocus_for_insert()

- gpdb-doc/markdown/admin_guide/query/topics/just-in-time.html.md
Running `EXPLAIN ANALYZE VERBOSE` now displays further information about JIT compilation. Edited documentation to match these changes. Also a couple of more edits.
> Modifications to JIT documentation page

- src/test/regress/expected/async.out
- src/test/regress/expected/dboptions.out
- src/test/regress/expected/distributed_transactions.out
- src/test/regress/expected/gpsd.out
- src/test/regress/expected/minirepro.out
- src/test/regress/input/createdb.source
- src/test/regress/output/createdb.source
- src/test/regress/sql/async.sql
- src/test/regress/sql/dboptions.sql
- src/test/regress/sql/distributed_transactions.sql
- src/test/regress/sql/gpsd.sql
- src/test/regress/sql/minirepro.sql
Some regression tests rely on invoking psql, but by default the output will depend on what users configured in their local .psqlrc file.  To avoid that add an extra -X (--no-psqlrc) option to all psql invokation.
> Ignore any local .psqlrc when running tests.

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
reduced-frequency-trigger not needed for rocky9
> ICW CLI groups not needed for now on el9 platforms

- gpMgmt/bin/gppylib/operations/test/unit/test_unit_configurationImplGpdb.py
- gpMgmt/bin/gppylib/system/configurationImplGpdb.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
- gpdb-doc/markdown/ref_guide/system_catalogs/gp_configuration_history.html.md
- src/backend/fts/fts.c
- src/include/catalog/catversion.h
- src/include/catalog/gp_configuration_history.h
- src/test/regress/expected/misc_sanity.out
`desc` is a keyword, so rename the column to `description`
Resolves the following issue:
```
gpadmin=# select desc from pg_catalog.gp_configuration_history; psql: ERROR:  syntax error at or near "desc"
LINE 1: select desc from pg_catalog.gp_configuration_history;
```
Bumps catalog version
Resolves https://github.com/greenplum-db/gpdb/issues/12077
> Rename gp_configuration_history.desc column

- src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
ORCA makes extensive use of the GPOS_NEW to allocate memory,
not checking the result for NULL, but instead relying on throwing an exception.
The implementation of this macro depends on the memory pool.
Depending on the variable optimizer_use_gpdb_allocators can be used either
GreenPlum's memory pool manager CMemoryPoolPalloc (default), or
ORCA's memory pool manager CMemoryPoolTracker.
When there is not enough memory for the GreenPlum's memory pool manager
in the gpdb::GPDBMemoryContextAlloc function an exception is thrown using
the macro GP_WRAP_END and therefore the lines, testing for NULL are never
run and can be safely removed.
And if there is not enough memory for the ORCA's memory pool manager
in the CMemoryPoolTracker::NewImpl function an exception is thrown using
the macro …
> [7X] new operator shouldn't return NULL

- src/bin/pg_upgrade/parallel.c
- src/bin/pg_upgrade/relfilenode.c
Disable pg_upgrade's broken parallel tablespace transfer. By doing this,
we can utilize the remaining parallelism from the --jobs flag to achieve
a performance boost.
The --jobs flag in pgupgrade allows for parallelization in two ways:
1. It enables parallel schema upgrades by running multiple instances of
pg_dump/pg_restore to upgrade the database schema simultaneously.
2. It supports parallel data transfer of tablespaces when using link
mode.
However, there is currently a bug in the parallel tablespace transfer
functionality that causes pg_upgrade to fail with the following error:
```
error while creating link for relation [relation_name]
([old_relfilenode] to [new_relfilenode]): File exists
Failure, exiting
```
> Disable pg_upgrade's broken parallel tablespace transfer

- src/backend/commands/analyze.c
- src/backend/commands/vacuum.c
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/expected/vacuum_gp.out
- src/test/regress/sql/vacuum_gp.sql
After running VACUUM ANALYZE, the pg_class catalog does not contain
correct values for relallvisible. Underlying issue is that, unlike
standard Postgres nodes, GPDB coordinator nodes do not actually contain
data (e.g. visibility maps). Instead, relevant info is gathered through
dispatch requests.
In the case of VACUUM ANALYZE, the coordinator does dispatchVacuum()
from vacuum_rel() and aggregates the stats, but then checked an empty
visibility map and overwrote the result. This commit resolves the issue
by reading the info that was previously saved in the catalog.
> Update VACUUM ANALYZE to correctly store relallvisible

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
The paramter `cmd` of _get_remove_cmd failed to express its meaning, seems better renaming it to `removeFile`.
> [typo] polish parameter name of _get_remove_cmd

- concourse/pipelines/templates/gpdb-tpl.yml
This is a temporary change. We should revert this commit once we release the package for ubuntu20.04 on TanzuNet.
We don't release the package for ubuntu20.04 on TanzuNet yet, so cannot download the previous release from TanzuNet. Previously we tried to use ubuntu18.04 package as a substitute but the `icw_planner_ubuntu20.04` test will fail with error
```
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
hence try to use the ubuntu20.04 package produced by gpdb-package-testing pipeline
> Replace previous gpdb package for ubuntu20.04

- src/backend/cdb/dispatcher/cdbdisp_query.c
Postgres added `paramExecTypes` in struct `PlannedStmt` at commit [e64861c7](https://github.com/postgres/postgres/commit/e64861c7).
In gpdb 7X, we have queryDesc->plannedstmt->paramExecTypes,
so no need to pass var `paramExecTypes` as a param.
- [√] Pass `make installcheck`
> Remove FIXME: no longer to pass paramExecTypes as a param (7X)

- src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
- src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_aggregate.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
- src/test/regress/expected/direct_dispatch_optimizer.out
- src/test/regress/sql/bfv_aggregate.sql
Consider the following setup:
```
create table t(a int, b int, c int);
insert into t select 1, i, i from generate_series(1, 10)I;
insert into t select 1, i, i from generate_series(1, 10)I;
insert into t select 1, i, i from generate_series(1, 10)I;
insert into t select 1, i, i from generate_series(1, 10)I; 
```
On running the following query, erroneous plans were generated
`explain select count(distinct(b)), gp_segment_id from t group by gp_segment_id; `
Multiple plans were generated, if we traverse through those plans, following erroneous plan was found:
QUERY PLAN
```
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..431.00 rows=1 width=12)
->  GroupAggregate  (cost=0.00..431.00 rows=1 width=12)
Group Key: gp_segment_id
->  GroupAggregate  (cost=0.00..431.00 rows=1 width=8)
Group …
```
> Fix bug in ORCA of removing required redistribution motion when query uses GROUP BY over gp_segment_id

- src/backend/catalog/catalog.c
- src/backend/utils/cache/relcache.c
There used to be a restriction where the oid and relfilenode needed to match for pg_upgrade. This restriction was removed a long time back (see below commit reference). Also, relfilenode logic is actually separate from oids in Greenplum (relfilenode has its own counter). Because of the above, we do not need to check new relfilenode values against the preserved oid list during upgrade. In fact, it was actually hindering upgrade performance by a noticeable amount.
GPDB commit reference:
https://github.com/greenplum-db/gpdb/commit/20a95219123a52634dfa060771edb8888ef9b7e0
This will be backported to 6X_STABLE as well.
> Do not check new relfilenodes against the preserved oid list for upgrade

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_gp.py
- gpMgmt/bin/gppylib/programs/clsSystemState.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gpstate.feature
- gpMgmt/test/behave/mgmt_utils/steps/data/pid_background_script.py
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a backport of https://github.com/greenplum-db/gpdb/pull/15359
**Issue:**
Currently, `gpstate -e` may sometimes display incorrect or stalled progress for `gprecoverseg` when the main `gprecoverseg` process is terminated or interrupted (e.g. due to SSH disconnections).
**RCA:**
This happens because `gpstate -e` depends on `recovery_progress.file` to show progress to the user. However, when the main `gprecoverseg` process is terminated, this file is no longer updated and is not cleaned up, resulting in stalled or incorrect progress. A fix was attempted for a similar issue in https://github.com/greenplum-db/gpdb/pull/13412, but it required the user to manually remove the `gprecoverseg.lock` directory.
**Fix:**
This commit resolves the issue by checking whether the main `gprecoverseg` …
> [6X Backport] gpstate -e: Fix gprecoverseg progress reporting

- src/test/isolation2/input/autovacuum-analyze.source
- src/test/isolation2/output/autovacuum-analyze.source
- src/test/regress/expected/autovacuum-catalog.out
- src/test/regress/input/autovacuum.source
- src/test/regress/output/autovacuum.source
- src/test/regress/sql/autovacuum-catalog.sql
To speed up tests and reduce timeouts waiting for AV worker, reduce `autovacuum_vacuum_threshold` to 50 for all autovacuum tests.
> Reduce autovacuum threshold for remaining autovacuum tests

- src/backend/cdb/dispatcher/cdbconn.c
fix issues #15194 
We got an unexpected msg while idle. So, we construct a simple notice msg use pqInternalNotice
which do not specify the line no. Due to the line is NULL we got segfault in MPPnoticeReceiver while
copying it to QENotice using strlcpy(notice->line, line, sizeof(notice->line));
Solution: use the same way as file does. Use SIZE_VARLEN_FIELD and COPY_VARLEN_FIELD instead of strlcpy.
SIZE_VARLEN_FIELD and COPY_VARLEN_FIELD will process NULL value.
In MPPnoticeReceiver the initialize value of file and func is "".
```
char	   *file = "";
char	   *func = "";
```
If the notice we received does not contain file or func info, file or func will still be "".
In SIZE_VARLEN_FIELD and COPY_VARLEN_FIELD we only judge NULL value not
judge "" value, so the length will be calculated as 1 …
> Fix coordinator crash in MPPnoticeReceiver

- src/backend/executor/nodeHashjoin.c
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
This error is caused by the execution logic of Hash Join Node, when the outernode does not fetch a tuple, it calls the ExecSquelchNode method let the lowernodes not to produce tuples anymore, leaving the inner node "squalched" but "un-executed" state. If the hash join needs to be rescanned, then the inner nodes has to be rescanned too if Hash Node's lefttree does not have chgParam, and finally a node does not have chgParam but "squelched" will cause ERROR.
Let's explain with example given in issue #11673 
```
gpadmin=# set from_collapse_limit = 1; set join_collapse_limit = 1;
SET
gpadmin=# explain select * from pg_namespace  join lateral  (select * from aclexplode(nspacl) x join pg_authid  on x.grantee = pg_authid.oid) z on true;
QUERY PLAN …
```
> Fix "cannot execute squelched plan node of type" error (greenplum-db#11673)

- src/backend/parser/parse_utilcmd.c
- src/test/regress/expected/create_table_like_gp.out
- src/test/regress/sql/create_table_like_gp.sql
Previously, in a CREATE TABLE statement, the LIKE .. INCLUDING STORAGE clause would overwrite the USING or WITH (appendonly=true orientation=..) clause if the source table in the LIKE clause is an append-optimized table. This is because Greenplum overloaded the INCLUDING STORAGE option of CREATE TABLE LIKE in commit 951065c48cc, and implicitly copies the source append-optimized table's access method (AM). This is problematic if in the same CREATE TABLE statement, an access method is also explicitly specified.
This commit does the following:
- Disallow INCLUDING STORAGE of append-optimized tables if table AM is explicitly specified in the same CREATE TABLE statement
- Improve the error message when there are multiple INCLUDING STORAGE clauses of append-optimized tables.
- Add tests to …
> Disallow "LIKE <AO/AOCO> INCLUDING STORAGE" if table AM is already set

- src/bin/pg_upgrade/pg_upgrade.c
When creating new objects on the target cluster via pg_restore, objects that do not have a preassigned oid will try to get a new oid from the oid counter. This works in upstream Postgres but can be slow in GPDB because the new oid is checked against the preserved oid list. If the new oid is in the preserved oid list, a new oid is generated from the oid counter until a valid oid is found. In production scenarios, it would be very common to have a very, very large preserved oid list and starting the oid counter from FirstNormalObjectId (16384) would make object creation slower than usual near the beginning of pg_restore. To prevent pg_restore performance degradation from so many invalid new oids from the oid counter, bump the oid counter to what the source cluster has via pg_resetwal. If …
> Set next OID before restoring schema during pg_upgrade

- gpcontrib/gp_replica_check/Makefile
- gpcontrib/gp_replica_check/gp_replica_check.c
- gpcontrib/gp_replica_check/gp_replica_check.py
This has 2 commits:
1. Fixes gp_replica_check to run against all reltypes
2. Enables gp_replica_check -r=all on CI.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/replica_check
> gp_replica_check: Run for all reltypes

- src/backend/commands/vacuum.c
- src/backend/storage/lmgr/lmgr.c
- src/include/storage/lmgr.h
After merging Upstream commit https://github.com/postgres/postgres/commit/566372b3d6435639e4cc4476d79b8505a0297c87, pipeline uao VACUUM cases hung due to a distributed deadlock was observed. (See also https://github.com/greenplum-db/gpdb/issues/15458).
It is because compaction phase in the process of vacuuming an append-optimized table requires two-phase commit, which could introduce distributed deadlock when updating DatabaseFrozenIds.
The solution is updating pg_database.datfrozenxid only at the last phase of VACUUM, instead of updating it in every phase, to avoid acquiring DatabaseFrozenIds lock under the two-phase context in VACUUM compaction phase.
> Resolve GPDB_12_12_MERGE_FIXME: distributed deadlock on AO VACUUM.

- src/backend/cdb/cdbvars.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
- src/include/utils/sync_guc_name.h
Greenplum dropped the hybrid hash aggregation after 6X and switched to
the upstream hash agg implementation, these GUCs are not actually used
any more, remove them.
> Remove dead hash agg GUCs

- gpMgmt/doc/gpfdist_help
- src/backend/access/external/url_curl.c
- src/backend/utils/misc/fstream/gfile.c
- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/data/gpfdist2/one_column.txt
- src/bin/gpfdist/regress/input/gpfdist2_compress.source
- src/bin/gpfdist/regress/output/gpfdist2_compress.source
Compression is very useful for data transmission with low bandwidth and high efficiency. But compression is a computationally intensive task and may increase the cost of time in the compression stage. To improve the efficiency of data transmission with compression, multi-thread data compression and transmission are introduced in this PR.
The feature makes each segment served by a single thread. In the main thread, requests are read and further parsed into specific data structures. The data is read into a buffer, then a sub-thread is created to compress data and send the compressed data.
To avoid conflict between threads, each request can be only served by one sub-thread. What's more, all public resources are accessed by a main thread to avoid waiting caused by thread synchronization. To …
> Add multi-thread compression and transmission from gpfdist to gpdb7

- contrib/file_fdw/input/gp_file_fdw.source
- contrib/file_fdw/output/gp_file_fdw.source
- contrib/file_fdw/output/gp_file_fdw_optimizer.source
- contrib/postgres_fdw/Makefile
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/ForeignScanExecLocAnyJoin.mdp
- src/backend/gporca/data/dxl/minidump/ForeignScanExecLocAnySimpleScan.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicForeignGet.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalDynamicForeignScan.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformExpandDynamicGetWithForeignPartitions.h
- src/backend/gporca/libgpopt/src/operators/CLogicalDynamicForeignGet.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysical.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalDynamicForeignScan.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalForeignScan.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalMotionRandom.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformDynamicForeignGet2DynamicForeignScan.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformExpandDynamicGetWithForeignPartitions.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/md/IMDRelation.h
- src/backend/gporca/libnaucrates/src/md/IMDRelation.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
- src/test/regress/init_file
When the mpp_execute option "ANY" is specified, we now will either execute it on a segment or coordinator depending on the cost.
Previously, when a foreign table was created to be executed with the ANY location, Orca still only executed it on the coordinator. Now, we treat it similarly to executing a set-returning function such as generate_series, and allow it to be executed on either the coordinator or a segment depending on costing. We add a new table distribution, Universal, which derives a Universal distribution in Orca just like a generate_series. It's important to note that this has different behavior from `all segments`, which treats the data as distributed randomly and processed as separate data on each segment (for example, accessing a specific file on each segment).
As an …
> Support executing foreign tables from segments in Orca

- src/backend/access/aocs/aocsam.c
- src/backend/access/appendonly/aomd_filehandler.c
- src/backend/access/appendonly/test/aomd_filehandler_test.c
- src/backend/access/common/reloptions_gp.c
- src/backend/catalog/pg_attribute_encoding.c
- src/backend/commands/tablecmds.c
- src/backend/nodes/outfuncs.c
- src/backend/nodes/readfuncs.c
- src/include/access/reloptions.h
- src/include/catalog/pg_attribute_encoding.h
- src/include/nodes/altertablenodes.h
- src/test/isolation2/expected/aoco_column_rewrite.out
- src/test/isolation2/sql/aoco_column_rewrite.sql
- src/test/regress/expected/alter_table_set.out
Since we added the column rewrite functionality in #15344, we can now do the same for `ALTER TABLE ... ALTER COLUMN ... SET ENCODING` which used to require table rewrite. Now do that. Like `ALTER COLUMN TYPE`, we use a new command for `ALTER COLUMN SET ENCODING` so that we can properly decide if we should perform the column rewrite-only optimization.
The idea is simple but there are some notable things during implementation:
* In the same ALTER TABLE statement, ALTER COLUMN SET ENCODING is made to happen after ALTER COLUMN TYPE for the same column. This is because both use the same column rewrite facility and we need to make sure they do not step onto each other's toes, so make ALTER COLUMN TYPE go first (we can also do the other way around but it seems simpler current way because we …
> Avoid table rewrite in ALTER COLUMN SET ENCODING

- src/bin/pg_upgrade/check.c
- src/bin/pg_upgrade/greenplum/option_gp.c
- src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
- src/bin/pg_upgrade/pg_upgrade.c
Since pg_upgrade checks can take a long time add --skip-checks. This is useful for internal testing to reduce the feedback cycle.
The skip was implemented using a label to reduce the amount of diffs for upstream merges.
6X: https://github.com/greenplum-db/gpdb/pull/15604
Pipeline: https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/upgrade-skip-checks_7X
> add pg_upgrade --skip-checks flag

- src/backend/optimizer/prep/prepunion.c
Fixme in prepunion.c
GPDB_96_MERGE_FIXME: On coordinator, before the merge, more complicated logic was added in
commit ad6a6067d9 to make the loci on the WorkTableScan and the RecursiveUnion correct.
That was largely reverted as part of the merge, and things seem to be working with this much simpler thing,
but I'm not sure if the logic is 100% correct now.
On commit ad6a6067d9 we change locus of WorkTableScan from CdbLocusType_SegmentGeneral to
CdbLocusType_SingleQE in create_worktablescan_path.
then before create_recursiveunion_path adding gather motion to non_recursive_path, changing locus of
non_recursive_path from CdbLocusType_SegmentGeneral to CdbLocusType_SingleQE.
Current implement is:
Before create_worktablescan_path adding gather motion, changing locus of non_recursive_path from …
> resolve GPDB_96_MERGE_FIXME in prepunion about recursive cte

- src/backend/executor/nodeHashjoin.c
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
This error is caused by the execution logic of Hash Join Node, when the outernode does not fetch a tuple, it calls the ExecSquelchNode method let the lowernodes not to produce tuples anymore, leaving the inner node "squalched" but "un-executed" state. If the hash join needs to be rescanned, then the inner nodes has to be rescanned too if Hash Node's lefttree does not have chgParam, and finally a node does not have chgParam but "squelched" will cause ERROR.
Let's explain with example given in issue #11673 
```
gpadmin=# set from_collapse_limit = 1; set join_collapse_limit = 1;
SET
gpadmin=# explain select * from pg_namespace  join lateral  (select * from aclexplode(nspacl) x join pg_authid  on x.grantee = pg_authid.oid) z on true;
QUERY PLAN …
```
> Fix cannot execute squelched plan node of type error

- concourse/pipelines/gen_pipeline.py
If there are back-slash '/' in the branch name, gen_pipeline would have
the slash in the pipeline yaml path. And an error will be reported:
```
❯ ./gen_pipeline.py -t dev
File "\xxx\gpdb/concourse/pipelines/./gen_pipeline.py", line 376, in <module>
main()
File "\xxx\gpdb/concourse/pipelines/./gen_pipeline.py", line 367, in main
pipeline_created = create_pipeline(args, git_remote, git_branch)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "\xxx\gpdb/concourse/pipelines/./gen_pipeline.py", line 144, in create_pipeline
with open(args.output_filepath, 'w') as output:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\xxx\gpdb/concourse/pipelines/gpdb-dev-mc/slash_in_gen_pipeline-rocky8.yml'
```
Replace it with …
> Fix gen_pipeline with '/' in the branch name

- src/backend/catalog/oid_dispatch.c
pg_upgrade can potentially preassign quite a large number of Oids when upgrading, so the List would be a bottleneck during lookups of Oids allocated to non-preassigned objects. This replaces the list with a Red-Black tree to achieve O(log n) lookups at the cost of slower inserts.
Backported from GPDB main (7X):
https://github.com/greenplum-db/gpdb/commit/62e87534feafd5e6711e4bb5de6cb1d97c10f4df
> [6X backport] Replace List with RBTree for preassigned Oids

- src/backend/catalog/catalog.c
- src/backend/utils/cache/relcache.c
There used to be a restriction where the oid and relfilenode needed to match for pg_upgrade. This restriction was removed a long time back (see below commit reference). Also, relfilenode logic is actually separate from oids in Greenplum (relfilenode has its own counter). Because of the above, we do not need to check new relfilenode values against the preserved oid list during upgrade. In fact, it was actually hindering upgrade performance by a noticeable amount.
GPDB commit reference:
https://github.com/greenplum-db/gpdb/commit/20a95219123a52634dfa060771edb8888ef9b7e0
Backported from GPDB main:
https://github.com/greenplum-db/gpdb/commit/32adf0aaa7730251e24d8ce4cacefa3742d2413a
> [6X backport] Do not check new relfilenodes against the preserved oid list for upgrade

- contrib/pg_upgrade/pg_upgrade.c
When creating new objects on the target cluster via pg_restore, objects that do not have a preassigned oid will try to get a new oid from the oid counter. This works in upstream Postgres but can be slow in GPDB because the new oid is checked against the preserved oid list. If the new oid is in the preserved oid list, a new oid is generated from the oid counter until a valid oid is found. In production scenarios, it would be very common to have a very, very large preserved oid list and starting the oid counter from FirstNormalObjectId (16384) would make object creation slower than usual near the beginning of pg_restore. To prevent pg_restore performance degradation from so many invalid new oids from the oid counter, bump the oid counter to what the source cluster has via pg_resetxlog. If …
> [6X backport] Set next OID before restoring schema during pg_upgrade

- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
The commit https://github.com/greenplum-db/gpdb/commit/50239de1810692256fe2c9aaf6474f082668576f introduced the fixme, the explain output will print the same subplan twice.
But After the commit https://github.com/greenplum-db/gpdb/commit/38d88155520790b268b1a380caa9a2d9508edc66 merged, the fixme has been resolved, so remove the fixme directly.
> Remove GPDB_96_MERGE_FIXME in subselect_gp*.

- src/backend/nodes/readfuncs.c
```
readfuncs.c:130:20: warning: unused function 'extended_char' [-Wunused-function]
inline static char extended_char(char* token, size_t length)
1 warning generated.
```
The usage has been removed by 19cd1cf4b68 - pg12 merge commit
> Fix unused warning 'extended_char'

- src/test/regress/expected/groupingsets.out
- src/test/regress/expected/groupingsets_optimizer.out
- src/test/regress/sql/groupingsets.sql
When merging PG95 (commit 8ae22d15ebf), the query plan for the lateral query with grouping sets do not make right plans and the results are wrong.
The plan for merging 95 is
```
postgres=# explain select * from (values (1),(2)) v(a) left join lateral (select v.a, four, ten, count(*) from onek group by cube(four,ten)) s on true order by v.a,four,ten;
QUERY PLAN
---------------------------------------------------------------------------------------------------------
Sort  (cost=10000000143.08..10000000143.35 rows=110 width=24)
Sort Key: "*VALUES*".column1, onek.four, onek.ten
->  Nested Loop Left Join  (cost=10000000068.83..10000000139.35 rows=110 width=24)
->  Values Scan on "*VALUES*"  (cost=0.00..0.03 rows=1 width=4)
->  Materialize  (cost=68.83..138.08 rows=19 width=20)
-> …
```
> Remove GPDB_95_MERGE_FIXME in groupingset*.

- gpMgmt/bin/gpcheckcat_modules/foreign_key_check.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
The false positive case the FIXME talks about has been resolved by commit 7d289b5460a (later incorporated in 19cd1cf4b68faff2e29bc2fa884c480e4644cdb4), which removes the foreign key reference between pg_rewrite.ev_class and pg_attribute.attrelid. Therefore, we do not need to ignore pg_rewrite anymore.
In 6X, this issue has been fixed using a different approach in #11732. The PR discussion also mentioned the problem of foreign key reference between pg_rewrite.ev_class and pg_attribute.attrelid. But it was fixed in a different way because it's not easy to change catalog in 6X.
The above PR also added a behave test case for 6X. Adding the same for 7X.
> Resolve a FIXME for gpcheckcat

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/include/gpopt/gpdbwrappers.h
This fdw has special logic that populates fdw_private and performs parallel cursor setup on the coordinator in `BeginForeignScan`, which is called in `ExecInitForeignScanForPartition`. Within the Dynamic nodes, Orca calls this function during execution for each partition, as there is partition-specific logic that needs to be done to move to the next partition. Planner on the other hand does this during initialization for each individual partition, not during execution.
There may be a way to refactor this logic to be performed on the coordinator or expand dynamic scans into individual scans similar to planner, but for now let's fall back to planner to prevent a crash. Note that Orca still supports the greenplum_fdw if it is not a partition.
Note: There are no tests here, as the …
> Fall back to planner for queries with foreign partitions using greenplum_fdw

- src/test/isolation/isolation_schedule
After applying ` pg_isolation_test_session_is_blocked() ` to look if there were any waiting locks instead of
attaching pg_locks, we could remove fixme then recover upsert cases. But there was one left case insert-conflict-do-update-3 failing due to CTE bugs, that is not related to upsert and I also open a issue https://github.com/greenplum-db/gpdb/issues/15635 for it.
> remove upsert fixme from isolation_schedule

- src/backend/nodes/nodeFuncs.c
Fix GPDB_96_MERGE_FIXME: verify walker works on Sequence node (in nodeFuncs.c) #15716
Sequence is GPDB-special node generated by ORCA. It returns tuples from the
last child node only. The walkers passed into `planstate_tree_walker` are:
1. walkers in execParallel.c:
- no verification required as gp never touch them.
2. ExplainPreScanNode in explain.c:
- it works. no rels in Sequence so no switch-case entry.
3. ExecShutdownNode in execProcnode.c:
- it works, no special shutdown ops for Sequence
The above walkers get verified and the fixme is removed.
> Fix GPDB_96_MERGE_FIXME: verify walker works on Sequence node (in nodeFuncs.c)

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/backend/access/brin/brin.c
- src/backend/access/brin/brin_revmap.c
- src/backend/cdb/cdbappendonlystorageread.c
- src/include/access/appendonlytid.h
- src/include/access/tableam.h
- src/include/catalog/aoseg.h
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/include/cdb/cdbappendonlyblockdirectory.h
- src/include/cdb/cdbappendonlystorageread.h
- src/test/isolation2/expected/ao_partial_scan.out
- src/test/isolation2/input/uao/brin.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/brin.source
- src/test/isolation2/sql/ao_partial_scan.sql
This contains 3 patches:
1. Fixes specific range summarization for AO/CO tables
2. Fixes specific range desummarization for AO/CO tables (utility mode only for now .. MPP version later)
3. Introduces partial scans support for AO/CO tables (fixes  #14836)
Dev pipeline :https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/partial_scan
> brin ao/co: Summarization/desummarization improvements

- configure
- configure.in
- src/backend/utils/misc/guc.c
- src/backend/utils/misc/postgresql.conf.sample
- src/test/isolation2/expected/segwalrep/select_throttle.out
- src/test/isolation2/sql/segwalrep/select_throttle.sql
Based on recent findinds, `wal_compression` may give huge
benefits when workloads generates large amounts of FPIs (Full Page
Images). With `wal_compression`, the WAL generated can be reduced by
20-30% and even higher when loading high volumes of data causes
checkpoints to occur too frequently; checkpoints occuring too frequently
causes more FPIs to be written to WAL.
When the amount of WAL generated is reduced, this will inherently reduce
the amount of data being transferred via interconnect to the mirrors.
Furthermore, there will be a reduction in disk I/O as less data are generated.
In a multi-node with mirrored environment, the overall duration of load will be
reduced by 6-15%. `wal_compression` does not directly effect AO/CO,
however, as part of AO/CO is comprised of auxiliary heap …
> enable `wal_compression` by default

- src/bin/pg_rewind/parsexlog.c
There are three points in the two FIXMEs. Let's review them one by one:
1. Should we return for `RM_APPEND_ONLY_ID`: confirmed that `RM_APPEND_ONLY_ID` doesn't have any registered buffers in all cases. But I don't think we need to return there because the `for` loop will just be a no-op. There are other types of WALs that don't have registered buffers either, and we do not need to treat AO ones specially.
2. Should we take care of `RM_DISTRIBUTEDLOG_ID`: I don't think we need to because it should be treated in the same way as for other SLRU related WALs, which is not keeping anything from the target. There's no buffer registered for it either.
3. Make sure `RM_BITMAP_ID` works after we took the upstream WAL format revamp (commit 2c03216d8311): I think the current code looks fine and we do …
> Resolve two FIXMEs in extractPageInfo()

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/gporca/data/dxl/minidump/ForeignPartOneTimeFilterDPE.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecRandom.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalMotion.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalMotionRandom.h
- src/backend/gporca/libgpopt/src/base/CDistributionSpecNonSingleton.cpp
- src/backend/gporca/libgpopt/src/base/CDistributionSpecRandom.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalMotionRandom.cpp
- src/backend/gporca/server/CMakeLists.txt
In certain cases, Orca generates duplicate sensitive random motions, which in
the translator are translated to a result node with with a filter on gp_segment_id. This
effectively only outputs the rows for a single segment. Inside the
optimizer, we treat this as a motion, as it causes the distribution to
change.
However, this isn't actually a physical motion, but rather a filter that
doesn't create a separate slice. Therefore, we can pass partition
selectors through this, allowing Orca to generate more performant plans
For example, we can now generate plans such as
```
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1293.01 rows=33 width=16)
->  Hash Join  (cost=0.00..1293.01 rows=11 width=16)
Hash Cond: (part_mixed_dpe.b = non_part.b)
->  Append  (cost=0.00..862.00 rows=22 width=8) …
```
> Support DPE for duplicate sensitive random motions in Orca

- src/test/regress/expected/motion_socket.out
- src/test/regress/sql/motion_socket.sql
psutil is not a dependency of plpython, thus we cannot assume it exists
when running regress test. We are going to use different python versions
for management utilities and plpython in the future release, and psutil
won't exist anymore while running regress tests.
- Rewrite teh motion_socket tests with 'lsof', which is a explicit
dependency of greenplum.
Related with #15703
> Remove psutil usage from regress tests

- concourse/scripts/extract_package.bash
- concourse/tasks/extract_package.yml
To support the release pipeline of Postgis extract package task and the related script is needed. the scripts extracts the rpm into a tarball for further processing. The same might be required for Madlib as well.
> Forward port of extract_package yml and bash

- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_FUNCTION.html.md
the WITH (describe = <describe_function>) clause was inadvertently removed from the CREATE FUNCTION ref page.
notes/questions:
- didnt look like this should be added to the ALTER FUNCTION page
- should i add this info to CREATE PROCEDURE also (new in greenplum 7)?
> docs - CREATE FUNCTION missing WITH (describe = func)

- gpMgmt/doc/gpfdist_help
- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
The default value for session clean up timeout is 300s, but in heavy workload, this default value is not long enough to wait for segment next POST request to arrive. Then it will cause "400 invalid request due to wrong sequence number" failure.
So this commit add one option '-k' to set this value for gpfdist. The default is 300, the valid range would be (300..86400).
> Add session clean up timeout parameter for gpfdist with '-k' option.(7X)

- src/pl/plpython/Makefile
- src/pl/plpython/expected/plpython3_path_guc.out
- src/pl/plpython/init_file
- src/pl/plpython/plpy_main.c
- src/pl/plpython/sql/plpython3_path_guc.sql
GP7 is going to use different python3 version for management utilities
and plpython, the PYTHONPATH in greenplum_path.sh will be a problem for
plpython.
This cherry-pick only use the GUC part of the original commit.
---
grenplum_path.sh always set PYTHONPATH to its 'lib/python', which creates
trouble using plpython3 for GPDB6. GUC 'plpython3.python_path' is
added by this commit to solve the issue.
- If the python_path has not been set, while loading plpython3, the
'PYTHONPATH' and 'PYTHONHOME' will be unset.
- If the python_path has been set, the 'PYTHONHOME' will be unset and the
'PYTHONPATH' will be set to the given value.
Some regress tests have been modified for python3 support.
plpython2 and plpython3 can co-exist with this commit. But they cannot
be used in the same session, which …
> Add guc plpython3.python_path, fix plpython3 build (#13095)

- src/backend/parser/gram.y
- src/backend/utils/misc/guc.c
- src/backend/utils/misc/postgresql.conf.sample
- src/test/regress/expected/as_alias.out
- src/test/regress/sql/as_alias.sql
1. Add missing keywords to PartitionIdentKeyword
As the FIXME suggests, many keywords added during the PG12 merge are not
added to `PartitionIdentKeyword`. Add them now, so that we could use them
as column alias without a preceding `AS`, or as partition name. E.g.:
```sql
create table t1(a int, b int);
select a new, b old from t1;
create table part(a int, b int) partition by range(b) 
(partition old start (0) end(1), partition new start(1) end(2));
```
What's not covered in this PR: keywords that are in both 6X and 7X. Essentially, 
I didn't go over all of the keywords that are not in `PartitionIdentKeyword`.
P.S. it is actually a GPDB-specific feature that we allow keywords to be
used for column alias without `AS` (commit https://github.com/greenplum-db/gpdb/commit/a64af2d78ebcacc72c89183 …
> Resolve two FIXMEs in gram.y and postgresql.conf.sample

- src/backend/catalog/system_views_gp_summary.sql
- src/include/catalog/catversion.h
`gp_statio_user_tables_summary` was incorrectly filtering on `gp_stat_all_tables_summary`. 
Changed to filter on `gp_statio_all_tables_summary`
Bump catalog version
> Fix gp_statio_user_tables_summary view

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam.c
Update the comment to mention that the flags are currently not supported for AO/CO. There will need to be additional work to implement the synchronized sequential scans, buffer strategy, and page mode for AO/CO. Furthermore, TABLESAMPLE, which is not implemented, is the only use case in which the ScanOptions flags are changed after the initial scan.
> Update MERGE_FIXME comment for `appendonly_rescan`

- src/backend/cdb/cdbtargeteddispatch.c
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/include/nodes/plannodes.h
Postgres introduced recheckqual and Greenplum reuses it as the
"original" index qual for direct dispatching, this commit updates the
leftover comments.
> Comment about direct dispatch's indexqualorig changes

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/gpfdist.c
There are 3 commits about polishing gpfdist in this pr.
Please review them one by one. Thanks.
**First commit afccfb48fa8ad1f47991fe335edfcd96a7ef04b5**
Apply standard C format code and comment. Such as:
- change comment from `//` to `/* */`
- change `if {` to 
```
if 
{
```
et. al
**Second commit 46bf222b12ed300960340b159ecf10d5c83132a6**
Reomve 2 unnecessary assignments, take one as an example
From
```
int res = recycle_thread(r);
if (res < 0)
```
To
```
if (recycle_thread(r) < 0)
```
**Third commit b3d84ecf702036c0f3fbca49b8826808e4871cc7**
- add `#define ERROR_CODE_SUCCESS 0` and `#define ERROR_CODE_GENERIC 1`
- rewrite `session_end(r->session, 0);` as `session_end(r->session, ERROR_CODE_SUCCESS);`
- rewrite `request_end(r, 0, 0);` as `request_end(r, ERROR_CODE_SUCCESS, 0);` …
> Polish code and comment of gpfdist (7X)

- src/backend/cdb/motion/ic_proxy_addr.c
- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_client.c
- src/backend/cdb/motion/ic_proxy_main.c
- src/backend/cdb/motion/ic_proxy_peer.c
- src/backend/cdb/motion/ic_proxy_router.c
- src/backend/cdb/motion/ic_tcp.c
- src/backend/cdb/motion/ic_udpifc.c
IC proxy messages should have the `ic-proxy:` prefix.
The messages that are enabled by the TERSE settings should be written
with a severity level of LOG.
> Refine IC proxy log messages

- gpMgmt/doc/gpfdist_help
- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
The default value for session clean up timeout is 300s, but in heavy workload, this default value is not long enough to wait for segment next POST request to arrive. Then it will cause "400 invalid request due to wrong sequence number" failure.
So this commit add one option '-k' to set this value for gpfdist. The default is 300, the valid range would be (300..86400).
> Add session clean up timeout parameter for gpfdist with '-k' option.(6X_STABLE)

- src/backend/cdb/cdbtargeteddispatch.c
This PR backport https://github.com/greenplum-db/gpdb/pull/15659 to 6x to resolve the performance regression of pgbench.
> 6x backport: Hardcode the attributes of GpSegmentId in GetContentIdsFromPlanForSingleRelation()

- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
When insert into writable external tables, the gpfdist is the server, and segments are clients. The clients will send POST requests one by one in sequence order. There is retry mechanism on the gpdb segment side when it fails to send one POST request to gpfdist because of network failure. If the network failure happens after the connection has been made, then gpfdist will also get an error when reading data from the socket. 
However, the retry is not working because of gpfdist legacy code that will close fstream when failed to receive data from socket. Gpfdist will close the file stream and set an error, so when the retry POST request arrives to gpfdist, an "500 internal error" will be sent back to segment which will stop the whole insert procedure.
This commit will let gpfdist confirm …
> Fix "500 internal error" when gpfdist fails to receive data from network(6X_STABLE).

- src/backend/cdb/motion/ic_udpifc.c
Align this teardown event logging with interconnect TCP.
> CI fix: don't log too much interconnect events

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/test/isolation2/expected/aoco_analyze_progress.out
- src/test/isolation2/expected/appendonly_analyze_progress.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/aoco_analyze_progress.sql
- src/test/isolation2/sql/appendonly_analyze_progress.sql
Fast Analyze was introduced for AOCO tables in 2939f9ada5d.
This commit adds the progress reporting metrics on top of the analyze logic for reporting progress in gp_stat_progress_analyze_summary
Analyze for AOCO tables happens based on row based sampling unlike block based sampling for heap tables.
We report the progress in terms of blocks processed using ratio of rows scanned/ target rows on totalblocks in the table. For e.g: if we have 1000 blocks in the table & we are sampling 100 rows and if 10 rows are done, we can say that 100 blocks are done.
Added isolation tests in aoco_analyze_progress
> Add analyze progress reporting for AOCO tables

- src/pl/plpython/Makefile
- src/pl/plpython/expected/plpython3_path_guc.out
- src/pl/plpython/sql/plpython3_path_guc.sql
- src/pl/plpython/sql/setup.sql
- src/test/isolation2/sql/setup.sql
A new GUC `plpython3.python_path` is introduced in #15737, we use it to control the `PYTHONPATH` environment variable before starting the Python interpreter of PL/Python to control the package looking up path. The default value for this GUC is an empty string and some PL/Python functions in test cases are invoking gpMgmt tools. We need to set up this GUC to a proper value before running these tests.
> [7X] Fix failed tests caused by plpython3.python_path.

- src/backend/gpopt/utils/CMemoryPoolPalloc.cpp
- src/backend/gporca/libgpos/src/memory/CMemoryPoolTracker.cpp
ORCA makes extensive use of the GPOS_NEW to allocate memory,
not checking the result for NULL, but instead relying on throwing an exception.
The implementation of this macro depends on the memory pool.
Depending on the variable optimizer_use_gpdb_allocators can be used either
GreenPlum's memory pool manager CMemoryPoolPalloc (default), or
ORCA's memory pool manager CMemoryPoolTracker.
When there is not enough memory for the GreenPlum's memory pool manager
in the gpdb::GPDBMemoryContextAlloc function an exception is thrown using
the macro GP_WRAP_END and therefore the lines, testing for NULL are never
run and can be safely removed.
And if there is not enough memory for the ORCA's memory pool manager
in the CMemoryPoolTracker::NewImpl function an exception is thrown using
the macro …
> [6X] new operator shouldn't return NULL

- concourse/scripts/ic_gpdb_resgroup_v2.bash
In recent times, the dev pipeline always failed at the `resource_group_v2_rhel8`.
After some investigations, I found we must use the root role to config Cgroup directly,
otherwise the `echo "+cpu" >> $basedir/cgroup.subtree_control` will failed.
So when we config the Cgroup-v2, use `sudo su` to change the role.
> use root role to change the configuration of cgroup-v2

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
This is the backport of https://github.com/greenplum-db/gpdb/pull/15473
----
The parameter cmd of _get_remove_cmd failed to express its meaning, seems 
better renaming it to `remove_file`.
> [6X] polish parameter name of _get_remove_cmd

- src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h
- src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_aggregate.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
- src/test/regress/expected/direct_dispatch_optimizer.out
- src/test/regress/sql/bfv_aggregate.sql
REVERT <eb56553aabd3bb92d471cd5aa8b671d252b0f848>
This bug is  solved for 'MAIN' branch through PR https://github.com/greenplum-db/gpdb/pull/15537
1) REASON TO REVERT
In https://github.com/greenplum-db/gpdb/issues/15521 a wrong result was reported.
2) SETUP TO REPRODUCE ERROR
```
create table t(a int, b int, c int);
insert into t select 1, i, i from generate_series(1, 10)i; 
insert into t select 1, i, i from generate_series(1, 10)i; 
insert into t select 1, i, i from generate_series(1, 10)i; 
insert into t select 1, i, i from generate_series(1, 10)I;
analyze t;
set optimizer_force_multistage_agg to on;
```
On running the following query, erroneous plans were generated
explain select count(distinct(b)), gp_segment_id from t group by gp_segment_id;
Multiple plans were generated, if we …
> [6X Backport] Fix bug in ORCA of removing required redistribution motion when query uses GROUP BY over gp_segment_id

- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
As the PR title said, just fix the field name to correctness.
> fix the name of "cpu_hard_quota_limit" in resgroup_syntax.sql

- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
In Cgroup v1, we can not set `cpu_quota_us` larger than parent's, it'll throw an
error of "Invalid Argument":
```
smart@postgres:/sys/fs/cgroup/cpu/gpdb/6441$ echo 370000 > cpu.cfs_quota_us
bash: echo: write error: Invalid argument
```
But this could happen in Cgroup v2, so the interface between them is not exactly
the same, this PR is trying to fix it.
> fix cgroup v1 cpu_quota_us can not be larger than parent

- src/bin/gpfdist/gpfdist.c
fix a compile problem for gpfdist (--without-zstd).
To disable the function call `recycle_thread` and the function declaration `wait_for_thread_join` when compiling without the zstd flag, use the `--without-zstd` flag. However, using this flag will result in a compile failure for `recycle_thread` and a compile warning for `wait_for_thread_join`.
Please note that using the `WIN32` flag only disables the above cases in the Windows platform. It cannot handle the case of compiling with the `--without-zstd` flag in Linux. To handle compilation cases both in Linux without 'zstd' and in Windows, we include the function call and function declaration in the USE_ZSTD macro. This approach ensures that the code can be compiled successfully regardless of the platform being used.
> fix compile warning

- src/test/isolation2/isolation2_schedule
The following isolation2 tests needs to run prior to enabling autovacuum. Otherwise, the test will be polluted by the auto-analyze and auto-vacuum and cause intermittent failures.
test: analyze_progress
test: appendonly_analyze_progress
test: aoco_analyze_progress
test: ao_index_build_progress
> Fix intermittent test failure

- src/test/isolation2/expected/aoco_column_rewrite.out
- src/test/isolation2/sql/aoco_column_rewrite.sql
The expected behavior of this test case is that 'ALTER TABLE' and
'INSERT' commands will block each other. This patch helps fix it.
Co-Authored-By: Hao Zhang <hzhang2@vmware.com>
> Fix incorrect testcase aoco_column_rewrite.

- contrib/pg_upgrade/check.c
The GPDB upgrade checks can take a while to run and we found that they also run against every source primary segment during upgrade. The checks against the source primary segments are not needed since none of the checks are specific to primary segment issues and the target coordinator segment's catalog is used to initialize the target primary segments. Therefore, only run the GPDB upgrade checks against the source coordinator segment to prevent unnecessary work. The original Postgres upgrade checks are left alone since they run relatively quick and may also serve a second purpose in filling out some parts of the old_cluster object that may be needed for later.
Some extra PR notes:
* It is not known yet what type of GPDB checks will be required for 6-to-7 upgrade so this change is only for …
> [6X] Only run GPDB upgrade checks against the coordinator segment

- contrib/pg_upgrade/parallel.c
- contrib/pg_upgrade/relfilenode.c
backported from 7x commit:
https://github.com/greenplum-db/gpdb/commit/b286ac793dab9f0fa368a4d11cbc0eacda0db46d
original commit message:
Disable pg_upgrade's broken parallel tablespace transfer. By doing this, we can utilize the remaining parallelism from the --jobs flag to achieve a performance boost.
The --jobs flag in pgupgrade allows for parallelization in two ways:
1. It enables parallel schema upgrades by running multiple instances of pg_dump/pg_restore to upgrade the database schema simultaneously.
2. It supports parallel data transfer of tablespaces when using link mode.
However, there is currently a bug in the parallel tablespace transfer functionality that causes pg_upgrade to fail with the following error:
```
error while creating link for relation [relation_name] …
```
> [6X backport] Disable pg_upgrade parallel tablespace transfer

- src/backend/access/common/relation.c
Long log:
The error and errdetail are both valid. Please refer to 
[issue 15095](https://github.com/greenplum-db/gpdb/issues/15095).
The mini repo below will trigger this errdetail
```
create table t1(c1 int);
create temporary table t2(c1 int);
create index i0 on t1(c1);
create index i0 on t2(c1);
discard all;
drop index i0;
vacuum t1;
```
So revome this fixme.
> Remove fixme in relation_open()

- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/gporca/data/dxl/minidump/CTE-Preds2.mdp
- src/backend/gporca/data/dxl/minidump/CTE15HAReplicated.mdp
- src/backend/gporca/data/dxl/minidump/CTE15Replicated.mdp
- src/backend/gporca/data/dxl/minidump/CannotPullGrpColAboveAgg.mdp
- src/backend/gporca/data/dxl/minidump/ExpandFullOuterJoin.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnlyScan-CTE.mdp
- src/backend/gporca/data/dxl/minidump/Insert-With-HJ-CTE-Agg.mdp
- src/backend/gporca/data/dxl/minidump/LeftOuter2InnerUnionAllAntiSemiJoin-Tpcds.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_diffcol.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_multiple_samecol_difforderespec.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_single.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonOrderedAgg.mdp
- src/backend/gporca/data/dxl/minidump/OrderedAgg_with_nonconst_fraction.mdp
- src/backend/gporca/data/dxl/minidump/TVF-With-Deep-Subq-Args.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
- src/backend/gporca/libgpopt/include/gpopt/base/CColumnFactory.h
- src/backend/gporca/libgpopt/src/base/CColumnFactory.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp
- src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
- src/backend/gporca/server/CMakeLists.txt
- src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
- src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gp_covering_index.out
- src/test/regress/expected/gp_covering_index_optimizer.out
- src/test/regress/sql/gp_covering_index.sql
In ORCA, commit https://github.com/greenplum-db/gpdb/commit/801b7a920b6dc69a44390d26427433f7912b8936 introduced a column usage framework.  When
index-only scan was introduced in commit https://github.com/greenplum-db/gpdb/commit/3b72df1810411f4716137446f00b550378084835, it leveraged that
framework to determine whether a plan could be satisfied using an
index-only scan. If the index's columns are a superset of the query's
used columns then an index-only scan is allowed.
In the case of CTE, ORCA didn't correctly copy and set the column usage.
Instead, ORCA was overly aggressive in marking columns as used. As a
result, the optimizer rejected index-only scan alternatives because it
assumed additional columns were required when in fact they were not.
Following should produce an index-only scan …
> [ORCA] Enable Index-Only Scan on CTE

- gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14698.
questions:
1.  is this new feature supported for read only, or both read and write?
2. does gpfdist care or behave differently if the original file is compressed itself (say with gzip)?
> docs - gpfdist supports multi-threaded compression and data transfer

- src/backend/cdb/motion/cdbmotion.c
Function `setExpectedReceivers()` is replaced by `UpdateMotionExpectedReceivers()`
in this commit https://github.com/greenplum-db/gpdb/commit/b0353e0ad5
Update the comment.
> Update comment in createMotionLayerState()

- src/test/regress/expected/gp_covering_index.out
- src/test/regress/expected/gp_covering_index_optimizer.out
- src/test/regress/expected/instr_in_shmem.out
- src/test/regress/greenplum_schedule
- src/test/regress/input/uao_dml/ao_covering_index.source
- src/test/regress/output/uao_dml/ao_covering_index.source
- src/test/regress/output/uao_dml/ao_covering_index_optimizer.source
- src/test/regress/sql/gp_covering_index.sql
- src/test/regress/sql/instr_in_shmem.sql
This is adding equivalent cases to test covering index functionalities for AO/CO tables, which is same as gp_covering_index.sql for Heap.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/covering_index_ao
> Add covering index tests for Append-Optimized table

- gpMgmt/bin/gpinitsystem
- gpMgmt/bin/lib/gp_bash_functions.sh
Each time we use 'egrep' there's a warning message emitted: 'egrep: warning: egrep is obsolescent; using grep -E'. This patch replaces 'egrep' with 'grep -E'.
Reference:
- https://www.shellcheck.net/wiki/SC2196
> Replace 'egrep' with 'grep -E'.

- src/bin/psql/tab-complete.c
Extends the psql console utility. It's autocompletion capabilities with the "CREATE EXTERNAL TABLE" syntax. Now, when you type "CREATE EXT" and press Tab, both options will be offered: "CREATE EXTENSION" and "CREATE EXTERNAL TABLE".
>  Autocompletion for create EXTERNAL TABLE in psql

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Following up with https://github.com/greenplum-db/gpdb/pull/15543, some further changes to the resource group reference pages. 
Note that PR https://github.com/greenplum-db/gpdb/pull/15751 handles the narrative changes but they are not included here as they were modified in previous branch (not merged yet).
Test site:  https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-rg-ref/greenplum-database/ref_guide-config_params-guc-list.html
> Docs resgroups ref

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
Follow up from PR https://github.com/greenplum-db/gpdb/pull/15765 which renames the resource groups parameters   “cpu_hard_quota_limit” to “cpu_max_percent”, and “cpu_soft_priority”  to “cpu_weight”.
> Modifications to resource group parameter changes

- gpdb-doc/markdown/admin_guide/ddl/ddl-index.html.md
- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_INDEX.html.md
in this PR:
- port the postgres content for index-only scans and covering indexes from https://www.postgresql.org/docs/12/indexes-index-only-scans.html.  this topic referenced partial indexes and expression indexes, so i also ported those sections.
- update the gporca limitations topic to include unsupported index features.  i pulled these unsupported features from src/test/regress/expected/gp_covering_index.out.
not in this PR:
- review of existing index content
- review of non-index related info in the gporca limitations topic
questions:
1.  is greenplum 7 planner support for index-only scans and covering indexes equivalent to postgres 12?  or do we need to call out any limitations?
2.  would it be helpful to include example queries that gporca does not support?  if so, can i use the …
> docs - add info for index-only scan, covering index info; gporca limits

- src/bin/gpfdist/gpfdist.c
There is a code flaw in gpfdist. This PR is to fix it.  `r->zstd_dctx` should be set to `NULL` in  `r->zstd_dctx` branch.
> Fix a code flaw in gpfdist

- concourse/pipelines/gpdb_main-generated.yml
- concourse/pipelines/templates/gpdb-tpl.yml
- concourse/scripts/ic_resgroup.bash
- concourse/tasks/ic_resgroup.yml
- contrib/extprotocol/Makefile
- contrib/file_fdw/init_file
- gpMgmt/bin/gpload_test/gpload2/init_file
- gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
- gpcontrib/orafce/init_file
- src/test/isolation2/expected/checkpoint_dtx_info.out
- src/test/isolation2/sql/checkpoint_dtx_info.sql
- src/test/regress/expected/resource_group_cpuset_resgroup.out
- src/test/regress/expected/resource_group_resgroup.out
- src/test/regress/expected/strings_resgroup.out
generate ic_resgroup task to run icw test under resoure group mode.
resource queue test case in icw test under rg task will change the resource manager's configure, remove these test case from rg icw task, also explain_format need llvm package to test jit, it's meaningless, also remove the test case.
> create icw task under resource group mode

- src/backend/executor/execPartition.c
- src/test/isolation2/expected/gdd/concurrent_update.out
- src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
- src/test/isolation2/sql/gdd/concurrent_update.sql
Once GDD is enabled, heap tuples can be concurrently updated on segment. ORCA will generate
Dynamic Scan for Partition table instead of multi subplans in planner. For concurrent update, Executor 
nitialized EPQ state and table describer called resultRelInfo which always generated for each partitions.
But in Dynamic Scan, we only have one resultRelInfo for table not partitions here, and will fill Dynamic
Scan infos before IUD operations. So we need to adapt Dynamic Scan to EPQ which used to be based on planner.
Here There are two places needed to fix.
- As we ExecInitPartitionInfo for partition table, we assign 1 to ResultRelInfo->ri_RangeTableIndex instead of 0, and
we could make EPQ work in this way. But in FDW scenario, we choose to keep 0 for ri_RangeTableIndex
since FWD has its own …
> Fix concurrent update core of partiton table in Dynamic scan

- src/backend/cdb/motion/tupser.c
Addressed the following GPDB_12_MERGE_FIXME in tupser.c:
/*
* GPDB_12_MERGE_FIXME: This function does not use this context. This context
* is only used in SerializeRecordCacheIntoChunks(). We need to find a better
* place for resetting it, or eliminating the needs for this context. */ MemoryContextReset(s_tupSerMemCtxt);
As the FIXME stated, post 12 merge, the allocation of memory under this memory context is more temporary and localized, so remove it altogether and instead directly call pfree().
> Remove MemoryContext s_tupSerMemCtxt

- gpdb-doc/markdown/analytics/postgis-upgrade.html.md
- gpdb-doc/markdown/install_guide/prep_os.html.md
Reported by user via bugzilla. It probably needs to be cherry-picked to 6.x
> docs: fixed two typos on Greenplum name

- contrib/pg_upgrade/greenplum/check_gp.c
- contrib/pg_upgrade/pg_upgrade.h
- contrib/pg_upgrade/util.c
A handful of our GPDB-specific upgrade checks can take a long time to run (specifically all the view ones that traverse parse trees) on a large production GPDB cluster. To reduce the runtime, we can take the same parallelization logic that already exists in pg_upgrade and implement something similar for the GPDB upgrade checks. We do not include the upstream Postgres upgrade checks to keep things simple but may do so in the future if needed.
Note: There's not much upgrade checks in GPDB main (7X) yet to implement this logic so just do it in 6X_STABLE only for now.  Can always forward-port later when we actually start working on 6-to-7 upgrade.
> [6X] Allow pg_upgrade --jobs to also run GPDB upgrade checks in parallel

- src/backend/cdb/cdbpath.c
- src/backend/commands/tablecmds.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/expected/guc_gp.out
- src/test/regress/init_file
- src/test/regress/sql/alter_distribution_policy.sql
- src/test/regress/sql/guc_gp.sql
We made an optimization (1dc3e975b8a) in which we skip redistribution in an INSERT query if the target table is randomly-distributed. In normal cases that makes sense, but in case of ALTER TABLE SET (REORGANIZE=true), the expectation is that the table's data should be redistributed randomly again.
So now adding a GUC `gp_force_random_redistribution` to force the redistribution if wished (i.e. for REORGANIZE=true). The default is set to false to keep the aforementioned optimization unaffected.
Fix #15733.
> Fix REORGANIZE=true not redistributing randomly-distributed tables

- src/backend/access/aocs/aocs_compaction.c
- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/aomd.c
- src/backend/access/appendonly/aosegfiles.c
- src/backend/access/appendonly/appendonly_compaction.c
- src/backend/access/appendonly/appendonlywriter.c
- src/backend/catalog/gp_fastsequence.c
- src/backend/commands/tablecmds.c
- src/backend/commands/vacuum_ao.c
- src/backend/executor/nodeIndexonlyscan.c
- src/backend/optimizer/util/plancat.c
- src/include/utils/rel.h
- src/test/regress/expected/alter_table_set_am.out
Similar to RelationIsAppendOptimized vs RelationStorageIsAO (https://github.com/greenplum-db/gpdb/pull/15546), add `RelationStorageIsAoRows | RelationStorageIsAoCols` corresponding to the existing `RelationIsAoRows | RelationIsAoCols` but exclude tables that do not have has storage. Currently only partitioned table is excluded.
Replace the existing with the new macros for callsites that are meant for accessing table storage or AO/CO aux tables.
But no change if:
* The callsite allows partitioned table to be there, or already excludes partitioned tables through some ERROR or Assert previously.
* The callsites are used in the way like if (RelationIsAoRows) ... else (RelationIsAoCols) ..., in that case we just add an `Assert(RelationStorageIsAO)` before that.
Also remove RelationAMIsAO which …
> Add two macros RelationStorageIsAoRows|RelationStorageIsAoCols

- gpdb-doc/markdown/admin_guide/managing/startstop.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- gpdb-doc/markdown/utility_guide/ref/gpstart.html.md
Greenplum 6 documentation should still refer to gp_session_role and not gp_role. Modifying some documentation pages to address this.
> Docs: Replaced gp_role with gp_session_role for GPDB 6

- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
After recovery, the segment should start in execute mode. Currently, after the recovery using gprecoverseg starts the segment in utility mode. With these changes made sure the segment is started in execute mode. Also added tests to confirm segments are in execute mode after recovery.
Also, updated existing test cases to add a check for execute mode. 
Currently this PR checks for execute mode by connecting to segment using sql and parsing the error thrown.
Before recovery output of PS command: 
```
/usr/local/gpdb/bin/postgres -D /datadatadirs/dbfast2/demoDataDir1 -c gp_role=execute
```
After recovery without changes: 
```
/usr/local/gpdb/bin/postgres -D /datadatadirs/dbfast2/demoDataDir1 -c gp_role=utility
```
After recovery with current changes: 
```
/usr/local/gpdb/bin/postgres -D …
```
> [7x] starting segments in execute mode post recovery

- src/test/regress/expected/AOCO_Compression.out
- src/test/regress/sql/AOCO_Compression.sql
The test is flaky with a diff like:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/AOCO_Compression.out	2023-06-21 03:50:47.656165913 +0000 +++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/AOCO_Compression.out	2023-06-21 03:50:47.808177112 +0000 @@ -2871,7 +2871,7 @@
Select count(*) from ao_wt_sub_partzlib8192_5_2;
count
-------
-   232
+   231
(1 row)
```
It is flaky after 5c153a0f7f14ec7ad281ba4f30117a6b583481f6 where we increased the default cache size of implicitly-created sequence, including the SERIAL type. It is flaky because some times we might skip some SERIAL numbers during an INSERT, so that a subquery like this:
```
select id from co_cr_sub_partzlib8192_1_2 where id = 10
```
could return nothing because we skipped SERIAL number 10 when inserting into …
> Fix flaky test AOCO_Compression

- src/backend/gporca/data/dxl/minidump/CoveringIndex-1.mdp
- src/backend/gporca/data/dxl/minidump/CoveringIndex-2.mdp
- src/backend/gporca/data/dxl/minidump/CoveringIndex-Cost-1.mdp
- src/backend/gporca/data/dxl/minidump/CoveringIndex-Cost-2.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnlyScan-CTE.mdp
- src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelParamsGPDB.h
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libgpdbcost/src/CCostModelParamsGPDB.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/gp_covering_index.out
- src/test/regress/expected/gp_covering_index_optimizer.out
- src/test/regress/expected/join_optimizer.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/gp_covering_index.sql
After commit https://github.com/greenplum-db/gpdb/commit/b9f43b9349d724b989609f898c0d1729c4f6f0d6, ORCA supports cover INCLUDE index columns. But
the cost model does not yet account for those columns. An INCLUDE column
is extra payload embedded into the physical index file. That requires
extra I/O to read tuples from the index that is proportional to the
width of the INCLUDE columns. In short, ORCA should always perform
index-only-scan using the index with the narrowest width that satisfies
the query.
For example:
```sql
CREATE TABLE t1 (c1 int, c2 int, c3 int, c4 int, c5 int);
CREATE INDEX idx_large ON t1 USING btree(c1) INCLUDE (c2, c3, c4, c5);
CREATE INDEX idx_c1 ON t1 USING btree(c1);
EXPLAIN ANALYZE SELECT c1 FROM t1 WHERE c1= 4;
```
Given that both indexes completely cover the …
> [ORCA] Update index cost model to account for INCLUDE columns

- src/backend/access/brin/brin.c
- src/backend/catalog/system_views.sql
- src/include/catalog/catversion.h
- src/include/catalog/pg_proc.dat
- src/test/isolation2/expected/ao_partial_scan.out
- src/test/isolation2/input/uao/brin.source
- src/test/isolation2/output/uao/brin.source
- src/test/regress/expected/brin.out
- src/test/regress/expected/brin_interface.out
- src/test/regress/expected/brin_optimizer.out
- src/test/regress/expected/privileges.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/brin_interface.sql
Please review commits individually. Mainly consists of 2 changes:
1. Making brin_desummarize_range MPP aware.
2. Warning users when the autosummarize reloption is set for BRIN indexes.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/brin_interface
> BRIN changes to user interface

- src/backend/cdb/cdbpath.c
They should be JOIN_DEDUP_SEMI/JOIN_DEDUP_SEMI_REVERSE, in line with enum JoinType.
> Fix typo JOIN_SEMI_DEDUP/JOIN_SEMI_DEDUP_REVERSE in comments.

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Due to changes made in https://github.com/greenplum-db/gpdb/pull/15504 step 'the user asynchronously sets up to end {process_name} process with SIGHUP' was defined twice, so removed the ambiguity
> Removed ambiguous step

- src/backend/gporca/concourse/test_explain_pipeline.yml
Before adding the "latest" tag, we used an outdated image, where lib 'uuid' was missing. As a result, explain pipeline couldn't compile. Adding the "latest" tag allows us to access the required libraries.
> Add latest tag to gpdb6-centos7-build image

- src/bin/pg_dump/pg_dumpall.c
Long log:
This is a post commit of https://github.com/greenplum-db/gpdb/commit/7a4c80d7e3dbab86cebda28365cb62d11eb10fe9
Change var name for consistency
- `i_cpu_hard_quota_limit` to `i_cpu_max_percent` 
- `i_cpu_soft_priority` to `i_cpu_weight`
> Post fix: change resgroup name

- gpMgmt/bin/gpcheckperf
- gpMgmt/doc/gpcheckperf_help
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
Use '--buffer-size' flag with size in kilobytes to set buffer size,
which will be used at gpnetbenchClient.
It is optional parameter. Default value is 8 kilobytes.
> gpcheckperf: add buffer size parameter

- src/backend/gporca/concourse/test_orca_pipeline.yml
Before adding the "latest" tag, we used an outdated image, where lib 'uuid' was missing. As a result, orca pipeline couldn't compile. Adding the "latest" tag allows us to access the required libraries.
> Add latest tag to gpdb6-centos7-build image for orca pipeline

- src/backend/catalog/dependency.c
- src/backend/cdb/cdbpartition.c
- src/backend/commands/tablecmds.c
- src/include/catalog/dependency.h
- src/include/cdb/cdbpartition.h
- src/test/regress/expected/qp_orca_fallback.out
- src/test/regress/expected/qp_orca_fallback_optimizer.out
- src/test/regress/sql/qp_orca_fallback.sql
Prior to this PR, for GP6 and older versions if `DROP TYPE..CASCADE`
finds a partition key column dependent on the type being dropped it
would go ahead and drop the column which leads to catalog inconsistency
causing gpcheckcat to fail and erroring out for INSERT and UPDATE
queries on such tables. To avoid landing in this state, this PR
aligns the behavior of `DROP TYPE..CASCADE` with that of a direct drop
(`ALTER ... DROP COLUMN`) by erroring out when trying to drop a partition
key column.
The tests that were added as part of commit [c4c2732](https://github.com/greenplum-db/gpdb/commit/c4c2732e5d82d14824e8ae70d9ec73a921b0bf95) had a drop table at the end
which did not fail for gpcheckcat test later. This PR also updates the test
by removing DROP TABLE at the end to ensure we check for …
> Error out when DROP TYPE..CASCADE tries dropping partition key dependency

- contrib/pg_upgrade/check.c
When skipping checks with --skip-checks be sure to run checks that generate scripts when upgrading such as “old_8_3_create_sequence_script” and “old_8_3_rebuild_tsvector_tables”. Unfortunately, the check_and_dump_old_cluster() function is heavily overloaded where some of the checks output scripts when performing the upgrade.
Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/upgrade-skip-checks
RC Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/updateSkipChecks_6X_RC
> [6X] pg_upgrade: don’t skip generating scripts

- src/backend/cdb/cdbmutate.c
- src/backend/executor/nodeSplitUpdate.c
- src/backend/optimizer/plan/setrefs.c
- src/test/regress/expected/update_gp.out
- src/test/regress/expected/update_gp_optimizer.out
- src/test/regress/sql/update_gp.sql
This PR aim to support returning clause in SplitUpdate as we try to update distributed column, 7x master
branch has supported it after refactoring paths in planner. 
Currently in 6X, we create splitupdate plan targetlist in hard code, just assign OUTER_VAR to elements
in targetlist (why did that? just guess SplitUpdate Node is a Top Node so no one else should reference it).
As we know, Other nodes replace Var with OUTER_VAR in set_plan_refs for generating final plan.
There is no set_plan_refs function for node SplitUpdate, and that's also the root clause we cannot
support returning clause. Because as we assign OUTER_VAR for vars in returning clause, we could not
reference anything for them since subplan targetlist has already been replaced by OUTER_VAR.
- refactor function …
> 【6X】support returning clause in splitupdate

- src/test/regress/expected/misc_sanity.out
- src/test/regress/sql/misc_sanity.sql
This PR add assert case for https://github.com/greenplum-db/gpdb/pull/15659, to resolve https://github.com/greenplum-db/gpdb/pull/15659#discussion_r1227616967
(no need to backport to 6x since the catalog is stable)
> Add assert cases for the attributes of GpSegmentId

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
As discussed in the following link
(https://github.com/greenplum-db/gpdb/pull/15665#discussion_r1235942189), the presence of asserts in release builds may cause to performance slowdown. So it has been decided to remove asserts on release builds in CTranslatorDXLToPlStmt.cpp
> Fix to remove Asserts on release build

- src/test/isolation2/expected/resource_queue.out
In 52c7e0a, we fixed the status message for the isolation2 test driver. The test case should be updated accordingly.
> [7X] Fix isolation2 tests for PR15840.

- doc/src/sgml/sources.sgml
- src/backend/utils/error/elog.c
- src/backend/utils/mmgr/mcxt.c
- src/include/nodes/memnodes.h
- src/include/utils/elog.h
- src/include/utils/memutils.h
- src/include/utils/palloc.h
Cherry-pick a total of 5 commits from  gpdb7 to make pgaudit extension work on gpdb_6X.
The oldest pg version that the pgaudit extension can support is 9.5. So there are a couple
of compiling errors on gpdb_6X, as pgaudit depends on the following 2 new features from gpdb7:
1. Invent a memory context reset/delete callback mechanism 
2. Add capability to suppress CONTEXT: messages to elog machinery 
So cherry-pick those commits.
> Cherry pick some commits from gpdb7 to make pgaudit extension work

- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
- src/test/regress/expected/qp_correlated_query.out
- src/test/regress/expected/qp_correlated_query_optimizer.out
- src/test/regress/sql/qp_correlated_query.sql
Fixing crash in ORCA with skip-level correlated query
This PR fixes the crash in ORCA observed with skip-level correlated query
containing a subquery.
Setup:
-------
```
create table t1(a int, b int);
create table t2(a int, b int);
create table t3(a int, b int);
```
Query:
-------
```
explain select * from t1 where ( EXISTS ( select t2.a from t2 left join t3 on (
EXISTS ( select t1.b from t2))));
```
Detailed RCA:
-------------
In 7X the trace flag EopttraceEnableLOJInNAryJoin is enabled by default. Due to
this CLogicalLeftOuterJoin is converted to CLogicalNAryJoin in the
preprocessing stage. For the above query while deriving the join stats using
method CJoinStatsProcessor::DeriveJoinStats the subquery present in the join
condition is replaced by a CScalarConst by method …
> Fixing crash in ORCA with skip-level correlated query

- src/backend/commands/cluster.c
```
cluster.c: In function ‘rebuild_relation’:
cluster.c:673:11: warning: unused variable ‘is_ao’ [-Wunused-variable]
673 |     bool  is_ao = RelationStorageIsAO(OldHeap);
|           ^~~~~
```
Probably this was a conflict mismerge between 0c942b968d and 569de03c2c.
> Fix warning of unused variable

- src/backend/catalog/aclchk.c
- src/backend/catalog/heap.c
- src/test/regress/expected/storage_pg_attributes.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/storage_pg_attributes.sql
AO tables do not use system columns `cmin`, `cmax`, `xmin`, and `xmax`, so do not include them when adding the system attributes. Not including the listed system columns above makes it possible to error out during parse analysis instead of getting a run-time error.
This addresses https://github.com/greenplum-db/gpdb/issues/11844
> Do not include unused system attributes for AO

- src/backend/postmaster/autovacuum.c
Anti-wraparound autovacuums are meant primarily to update transaction
metadata and currently they are executed on user tables as well.
Executing them on AO tables is pointless from this perspective as they
don't carry any transaction metadata, and will lead to unintended cycles
spent on vacuuming their contents. Their aux tables carry it and will be
anti-wraparound autovacuumed anyway.
This is already enforced in the code, add an assert for the same.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/awav_ao
> Assert AO/CO exclusion for anti-wraparound vacuums

- src/backend/catalog/heap.c
- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/expected/alter_table.out
- src/test/regress/expected/bfv_partition.out
- src/test/regress/expected/column_compression.out
- src/test/regress/expected/generated.out
- src/test/regress/expected/generated_optimizer.out
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/expected/index_including_gist_optimizer.out
- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/expected/qp_dropped_cols.out
- src/test/regress/expected/qp_dropped_cols_optimizer.out
- src/test/regress/expected/rpt.out
- src/test/regress/expected/rpt_optimizer.out
- src/test/regress/expected/vacuum_gp.out
- src/test/regress/output/table_functions.source
- src/test/regress/output/table_functions_optimizer.source
- src/test/regress/output/uao_ddl/alter_drop_allcol.source
- src/test/regress/sql/alter_distribution_policy.sql
- src/test/regress/sql/qp_dropped_cols.sql
Prior to this PR, if DROP TYPE..CASCADE finds a distribution key
column dependent on the type being dropped it would go ahead and drop
the column without updating catalog for table's distribution policy
leading to invalid distribution policy in gp_distribution_policy and
when trying to describe the table it would reference dropped distribution
column that would lead to a crash and gpcheckcat failure. To avoid landing in this state, this
commit aligns the behavior of DROP TYPE..CASCADE with that of a direct
drop (ALTER ... DROP COLUMN) for a distribution key column and
update the distribution policy of the table to random.
This issue also exists on 6X. Will backport to 6X once approved
gpdb-dev discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/Yo2Tp18ENu8
>  Update distribution policy when DROP TYPE..CASCADE drops distribution key dependency

- concourse/pipelines/gen_pipeline.py
test_sections is a option for users to set what job groups to run, when it's prod concourse, it should set to all test sections: ICW, CLI, AA, Release, but when it's non prod concourse, user can specify which job groups to run.
The error is when it's prod, dev, cm concourse, the test_sections is always set to ICW, CLI, AA, Release, which is not expected.
> [Releng]Fix the test_sections option is always set to full pipeline

- contrib/sepgsql/expected/ddl.out
- src/backend/catalog/namespace.c
- src/backend/commands/schemacmds.c
- src/test/regress/expected/namespace.out
- src/test/regress/sql/namespace.sql
From the commit message:
Replace last PushOverrideSearchPath() call with set_config_option().
The two methods don't cooperate, so set_config_option("search_path",
...) has been ineffective under non-empty overrideStack.  This defect
enabled an attacker having database-level CREATE privilege to execute
arbitrary code as the bootstrap superuser.  While that particular attack
requires v13+ for the trusted extension attribute, other attacks are
feasible in all supported versions.
Standardize on the combination of NewGUCNestLevel() and
set_config_option("search_path", ...).  It is newer than
PushOverrideSearchPath(), more-prevalent, and has no known
disadvantages.  The "override" mechanism remains for now, for
compatibility with out-of-tree code.  Users should update such code,
which likely …
>  CREATE SCHEMA ... schema_element defeats protective search_path changes

- contrib/sepgsql/expected/ddl.out
- src/backend/catalog/namespace.c
- src/backend/commands/schemacmds.c
- src/test/regress/expected/namespace.out
- src/test/regress/sql/namespace.sql
The two methods don't cooperate, so set_config_option("search_path", ...) has been ineffective under non-empty overrideStack.  This defect enabled an attacker having database-level CREATE privilege to execute arbitrary code as the bootstrap superuser.  While that particular attack requires v13+ for the trusted extension attribute, other attacks are feasible in all supported versions.
Standardize on the combination of NewGUCNestLevel() and set_config_option("search_path", ...).  It is newer than PushOverrideSearchPath(), more-prevalent, and has no known disadvantages.  The "override" mechanism remains for now, for compatibility with out-of-tree code.  Users should update such code, which likely suffers from the same sort of vulnerability closed here. Back-patch to v11 (all supported …
> CREATE SCHEMA ... schema_element defeats protective search_path changes

- src/backend/storage/lmgr/lock.c
- src/backend/utils/resscheduler/resqueue.c
- src/include/storage/lock.h
- src/test/isolation2/expected/resource_queue.out
- src/test/isolation2/sql/resource_queue.sql
This is a backport of #15840 . There were some minor conflicts (described in the commit messages)
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_resq_holdable
> [6X] Fix statement leak for holdable cursors

- src/test/isolation2/expected/resource_queue.out
- src/test/isolation2/sql/resource_queue.sql
Quitting the session is non-blocking and can cause diffs like:
```diff
-- Sanity check: Ensure that all locks were released.
0:SELECT granted, locktype, mode FROM pg_locks where locktype = 'resource queue' and pid != pg_backend_pid();
- granted | locktype | mode
----------+----------+------
-(0 rows)
+ granted | locktype       | mode
+---------+----------------+---------------
+ t       | resource queue | ExclusiveLock
+(1 row)
-- Sanity check: Ensure that the resource queue is now empty.
0: SELECT rsqcountlimit, rsqcountvalue from pg_resqueue_status WHERE rsqname = 'rq_concurrency_test';
```
CLOSE the cursor instead, which will be a blocking operation, and will
exercise the same code path.
Co-authored-by: Jimmy Yih <jyih@vmware.com>
Dev-pipeline: …
> resqueue test: Close holdable cursor instead

- src/backend/catalog/heap.c
- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/expected/qp_dropped_cols.out
- src/test/regress/expected/qp_dropped_cols_optimizer.out
- src/test/regress/sql/alter_distribution_policy.sql
- src/test/regress/sql/qp_dropped_cols.sql
Prior to this commit, if DROP TYPE..CASCADE finds a distribution key column dependent on the type being dropped it would go ahead and drop the column without updating catalog for table's distribution policy leading to invalid distribution policy in gp_distribution_policy and when trying to describe the table it would reference dropped distribution column that would lead to a crash. To avoid landing in this state, this commit aligns the behavior of DROP TYPE..CASCADE with that of a direct drop (ALTER ... DROP COLUMN) for a distribution key column and update the distribution policy of the table to random.  This commit adds tests and distributions policy asserts for few existing tests.
Note: did not change the NOTICE message for 6X.
6X:  `NOTICE: dropping a column that is part of the …
> [6X] Update distribution policy for dropping distribution key dependency

- src/backend/commands/vacuum.c
- src/backend/utils/resgroup/resgroup.c
For the previous investigation, I neglected the fact that the AutoVacuum worker will be 
executed by PostermasterMain, it will invoke InitResmanager to init the resource group if
it is enabled. And it'll use StartTransactionCommand to create a transaction to finish its 
job, which could put the AutoVacuum worker process to the admin_group, not system_group,
so this PR is trying to fix it.
> force the auto vacuum worker controlled by the system_group

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/optimizer/util/plancat.c
- src/test/isolation2/expected/lockmodes_optimizer.out
- src/test/regress/expected/partition_locking.out
- src/test/regress/expected/partition_locking_optimizer.out
- src/test/regress/sql/partition_locking.sql
FIXME's:
* GPDB_12_MERGE_FIXME: Revisit this post merge and see if we have a
chance to unlock the pruned partitions
 
* GPDB_12_MERGE_FIXME: Revisit this post merge and see if we have a
chance to unlock the pruned partitions
RCA:
ORCA always require root partition statistics for accurate query
planning and cost estimation. While fetching total size of a
partition table we lock all the leaf partitions including pruned
parittions, but if we find the relation statistics in MD cache,
we only acquire lock on root partition table. Although acquire
lock on every leaf partition is unnecessary, we have to acquire
lock for necessary leaf partitions on master node, otherwise it
can lead to deadlock issues.
For example :
//Assuming relation stats are available at MD Cache, so ORCA
//acquires only …
> Fix unlock the pruned partitions of partition table

- src/backend/catalog/system_views.sql
- src/test/regress/expected/sysviews_gp.out
- src/test/regress/sql/sysviews_gp.sql
The `gp_stat_bgwriter` view which is supposed to show cluster-wide view of `pg_stat_bgwriter` only shows part of the segments, e.g.:
```sql
postgres=# select * from gp_stat_bgwriter;
segment_id | checkpoints_timed | checkpoints_req | checkpoint_write_time | checkpoint_sync_time | buffers_checkpoint | buffers_clean | maxwritten_clean | buffers_backend | buffers_backend_fsync | buffers_alloc |          stats_reset
------------+-------------------+-----------------+-----------------------+----------------------+--------------------+---------------+------------------+-----------------+-----------------------+---------------+-------------------------------
0 |              1097 |               0 |                 37946 |                   15 |                378 |             0 | …
```
> Fix gp_stat_bgwriter which shows incomplete/incorrect results

- src/test/regress/greenplum_schedule
The test is flaky with diff:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/sysviews_gp.out	2023-06-29 15:15:01.228910780 +0000 +++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/sysviews_gp.out	2023-06-29 15:15:01.236911545 +0000 @@ -137,7 +137,7 @@
select count(*) = 0 or count(distinct gp_segment_id) = :segcount from gp_stat_progress_analyze;
?column?
----------
- t
+ f (1 row)
```
Autoanalyze can be run nondeterministically on some segment. So we cannot assume that we can see progress report on none-or-all segments. Similar to the vacuum progress view too.
> Fix a flaky case in sysviews_gp

- gpdb-doc/markdown/admin_guide/external/g-external-tables.html.md
Fix a typo of external markdown
from `gpdists` to `gpfdists`
Signed-off-by: Yongtao Huang <yongtaoh@vmwrare.com>
> Fix a typo of external markdown

- src/backend/optimizer/util/clauses.c
- src/test/regress/expected/rowsecurity.out
- src/test/regress/sql/rowsecurity.sql
If an SRF in the FROM clause references a table having row-level security policies, and we inline that SRF into the calling query, we neglected to mark the plan as potentially dependent on which role is executing it.  This could lead to later executions in the same session returning or hiding rows that should have been hidden or returned instead.
Our thanks to Wolfgang Walther for reporting this problem.
Stephen Frost and Tom Lane
(cherry picked from commit ca73753b090c33bc69ce299b4d7fff891a77b8ad)
NB: Greenplum did not have the problem described in the above commit message because it always aggressively evaluate stable functions. Refer to the following Greenplum commits for details:
ccca0af2c6d3858b8a5a0659c40595d53bfe782c
ce32a0dba1cb1435e839cfd9d9f1644ed214a0ed …
> Handle RLS dependencies in inlined set-returning functions properly.

- src/test/regress/expected/function_extensions.out
- src/test/regress/expected/function_extensions_optimizer.out
- src/test/regress/sql/function_extensions.sql
The function_extensions test used to flake as follows:
```
-- Temp file number before running INITPLAN function
SELECT get_temp_file_num();
get_temp_file_num
------------
- 0 files and 0 directories
+ 0 files and 1 directories
(1 row)
```
It is possible that some temp directories are present sometimes before
the we execute the INITPLAN function, just like this old comment
suggests that temp dirs like pgsql_tmp3889679.0.sharedfileset may hang
around:
-- Temp file number after running INITPLAN function. All the files should've
-- been cleaned up, but it's normal that the temp directory to hold them is
-- still around.
So, in this commit, we don't even bother about the directories, we just
look at the files. That too, we also eliminate any other possibility of
flakes by doing a …
> function_extensions: Fix tmpdir ls flake

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam_handler.c
Long log:
We met these warnings
```
appendonlyam_handler.c: In function 'appendonly_index_build_range_scan':
appendonlyam_handler.c:1666:3: warning: missing braces around initializer [-Wmissing-braces]
AppendOnlyBlockDirectoryEntry  dirEntry = {0};
^
appendonlyam_handler.c:1666:3: warning: (near initialization for 'dirEntry.range') [-Wmissing-braces]
aocsam_handler.c: In function 'aoco_index_build_range_scan':
aocsam_handler.c:1905:3: warning: missing braces around initializer [-Wmissing-braces]
AppendOnlyBlockDirectoryEntry dirEntry = {0};
^
aocsam_handler.c:1905:3: warning: (near initialization for 'dirEntry.range') [-Wmissing-braces]
```
`AppendOnlyBlockDirectoryEntry` is a nested struct with `range` inside.
```
typedef struct AppendOnlyBlockDirectoryEntry
{
struct range
{
int64 …
```
> Fix warning: missing braces around initializer [-Wmissing-braces]

- concourse/scripts/ic_gpdb_resgroup.bash
- concourse/scripts/ic_gpdb_resgroup_v2.bash
Long log:
Fix warning about resgroup CI test, remove a useless configure paramater.
```
+ ./configure --prefix=/usr/local/greenplum-db-devel --without-zlib --without-rt --without-libcurl --without-libedit-preferred --without-docdir --without-readline --disable-gpcloud --disable-gpfdist --disable-orca --without-python PKG_CONFIG_PATH=/usr/local/greenplum-db-devel/lib/pkgconfig
configure: WARNING: unrecognized options: --without-docdir
```
> Fix warning configure: WARNING: unrecognized options: --without-docdir

- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/bin/gppylib/utils.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Problem: During gprecoverseg host-name and host-address fields are getting populated with the same value(host-address) in the gp_segment_configuration table after recovery. The reason being the recovery input configuration file can have only three parameters host-address, port, data-directory and host-name field is not there. In previous versions of gpdb hostname was resolved using the provided host-address but the functionality used to resolve the hostname was unstable and faulty. So, It was removed in https://github.com/greenplum-db/gpdb/commit/f61d35cdeacc2f97e234648e06788207fb9e53fc with the reason provided "The hostname resolution from address was incorrect and faulty in its logic - an IP address never requires a hostname associated with it. However, the hostname field in …
> [7x] Added host-name parameter in recovery configutation

- src/test/isolation2/isolation2_schedule
The test was flaky with a diff like:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/expected/segwalrep/die_commit_pending_replication.out	2023-06-30 20:21:28.988978262 +0000 +++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/results/segwalrep/die_commit_pending_replication.out	2023-06-30 20:21:28.996979056 +0000 @@ -60,8 +60,7 @@
0U: select pg_terminate_backend(pid) from pg_stat_activity where wait_event='SyncRep' and sess_id in (select sess_id from store_session_id);
pg_terminate_backend
------------
- t -(1 row)
+(0 rows)
-- We expect two more occurrence: one for backend quitting and another for retry.
select gp_wait_until_triggered_fault('sync_rep_query_die', 3, dbid) from gp_segment_configuration where role='p' and content = 0;
@@ -72,9 +71,10 @@
-- Verify that the sess_id …
```
> Fix a flaky test die_commit_pending_replication

- src/backend/commands/vacuum.c
- src/test/regress/expected/vacuum_gp.out
- src/test/regress/sql/vacuum_gp.sql
IN GPDB, VACUUM FREEZE of any table, like many other operations, will leave tracking info in pg_stat_last_operation/pg_stat_last_shoperation. Those rows in pg_stat_last_operation/pg_stat_last_shoperation are unfrozen until we freeze those two tables themselves. Therefore, a database-wide VACUUM FREEZE could leave a lot of unfrozen rows in those two tables.
That doesn't hurt until we try to import collations at gpinitsystem time and we want to freeze template0 before going into pg_upgrade (#15667). But the unfrozen rows generated during VACUUM FREEZE would defeat the purpose of VACUUM FREEZE.
So now we try to not leave unfrozen rows in those two catalogs. We do that by moving pg_stat_last_operation and pg_stat_last_shoperation to the end of the list of relations to be vacuumed during a …
> Make sure database-wide VACUUM FREEZE don't leave unfrozen rows in pg_stat_last_operation/pg_stat_last_shoperation

- gpdb-doc/markdown/ref_guide/gp_toolkit.html.md
Adds the view gp_resgroup_role to the gp_tooklit reference documentation. Somehow it was missed when documenting the new GPDB 7 resource groups.
> Docs: Added view gp_resgroup_role

- src/backend/optimizer/util/pathnode.c
- src/test/regress/greenplum_schedule
- src/test/regress/input/table_functions.source
- src/test/regress/output/table_functions.source
- src/test/regress/output/table_functions_optimizer.source
Greenplum has a special path to handle semjoin, the planner might add a
unique_row_id path to the first inner join and then de-duplicate.
Table function scan has no corresponding dedup workflow. Here we
introduce a switch to turn off it when there is a table function scan.
> 6X: Don't create unique rowid paths if there is a table function scan

- .editorconfig
- src/backend/optimizer/util/pathnode.c
- src/backend/utils/misc/faultinjector.c
- src/include/nodes/relation.h
- src/include/utils/faultinjector.h
- src/test/regress/input/table_functions.source
- src/test/regress/output/table_functions.source
- src/test/regress/output/table_functions_optimizer.source
Greenplum has a special path to handle semjoin, the planner might add a
unique_row_id path to the first inner join and then de-duplicate.
Table function scan has no corresponding dedup workflow. Here we
introduce a switch to turn off it when there is a table function scan.
> 5X: Don't create unique rowid paths if there is a table function scan

- src/backend/cdb/cdbtargeteddispatch.c
- src/include/cdb/cdbtargeteddispatch.h
Long log:
Funciton `FinalizeDirectDispatchDataForSlice()`  is applied to free 
and override direct dispatch data on the given node.
Before this commit [93abe74](https://github.com/greenplum-db/gpdb/commit/93abe741cd67f04958e2951edff02b45ab6e280f), 
the call chain of `FinalizeDirectDispatchDataForSlice()` is
`standard_planner() -> AssignContentIdsToPlanData() -> FinalizeDirectDispatchDataForSlice()`.
After this commit [93abe74](https://github.com/greenplum-db/gpdb/commit/93abe741cd67f04958e2951edff02b45ab6e280f), the logic of direct-dispatch was rewritten. 
Direct dispatch information is attached at `PlanSlice`, 
rather than struct `ContentIdAssignmentData`, function `AssignContentIdsToPlanData()` is  also deleted. 
Then `FinalizeDirectDispatchDataForSlice()` is never called now. So remove …
> Remove function FinalizeDirectDispatchDataForSlice()

- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
When insert into writable external tables, the gpfdist is the server, and segments are clients. The clients will send POST requests one by one in sequence order. There is a retry mechanism on the gpdb segment side when it fails to send one POST request to gpfdist because of network failure. If the network failure happens after the connection has been made, then gpfdist will also get an error when reading data from the socket.
However, the retry is not working because of gpfdist legacy code that will close fstream when failed to receive data from the socket. Gpfdist will close the file stream and set an error, so when the retry POST request arrives at gpfdist, an "500 internal error" will be sent back to the segment which will stop the whole insert procedure.
This commit will let gpfdist …
> Add resumable download logic for gpfdist in gpdb7

- src/test/isolation2/expected/pg_rewind_fail_missing_xlog.out
- src/test/isolation2/sql/pg_rewind_fail_missing_xlog.sql
When execute inject fault `checkpoint_after_redo_calculated` or 'checkpoint_control_file_updated' in a newly promoted mirror node, connection failed error occurs due to the fatal log 'mirror is being promoted'. It means when connection state is MIRROR_READY but the role change to primary during promoting, the connection will be declined to avoid confusion.
Sleep 5 seconds to wait until the mirror node promotion is finished and the role change to primary.
> Fix case pg_rewind_fail_missing_xlog

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
doc updates for https://github.com/greenplum-db/gpdb/pull/15468 and https://github.com/greenplum-db/gpdb/pull/15591.
greenplum no longer rewrites the table when adding a column (ao, aoco, and heap) or setting the encoding (ao).
updates are to the ALTER TABLE ref page, i didnt find any references in the rest of the docs.
> docs - alter table set encoding, add column no longer rewrite

- src/backend/gporca/data/dxl/minidump/CastedScalarIf-On-Index-Key.mdp
- src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-vc-vc.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-IDFWithCast.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CCastUtils.h
- src/backend/gporca/libgpopt/src/base/CCastUtils.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/sql/bfv_index.sql
https://github.com/greenplum-db/gpdb/issues/15624
**Motivation:**
Customer reports plan difference when the predicate is written in the form of `col op val` vs. `val op col`. Specifically, if the column is the on left side, ORCA is able to leverage the bitmap scan alternative given the indexed column. When the value is placed on the left side, ORCA chooses much inferior a plan with sequential scan.
**Root cause:**
The transform from select into bitmap scan expects predicates with columns on the left side and values on the right side. That is, in order for the bitmap scan alternative to be generated, the predicate has to be in the form of `col op val`. If the predicate is written in the form `val op col`, preprocessor converts it to `col op val`. This way, entering the exploration phase, a …
> Reorder scalar comparison expression in case of cast

- src/backend/cdb/cdbtargeteddispatch.c
#15925 removes dead function `FinalizeDirectDispatchDataForSlice()`.
Var `gp_test_options` becomes useless and causes this warning.
Delete the unused var.
> Fix warning: 'gp_test_options' defined but not used

- gpMgmt/bin/gpinitsystem
- gpMgmt/bin/gppylib/gpcatalog.py
- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
- src/bin/initdb/initdb.c
- src/test/regress/input/oid_wraparound.source
- src/test/regress/output/oid_wraparound.source
In upstream the function pg_import_system_collations() is run at initdb time to import all collations available on the platform. In GPDB we could not do that because we have to make sure all segments have imported the same collations and bear the same OIDs, so we disabled pg_import_system_collations in initdb and leave that task to DB admin (see PR #5016).
However, without breaking the consistency promise, this can still be done at gpinitsystem time for all initial databases (template0, template1 and postgres). If all segments could install the same collations (which is probably the majority of cases), then the call succeeds and the user does not need to do anything. Otherwise, the call fails w/ a warning and the behavior remains the same as currently where the user has to figure out what …
> Import collations at gpinitsystem time

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/test/regress/expected/bfv_dml.out
- src/test/regress/expected/bfv_dml_optimizer.out
- src/test/regress/sql/bfv_dml.sql
Currently, in constructing the target list for a DML statement, we require the target list to be not NULL. If the target list is NULL, we fall back in the debug build. This PR changes this behavior by removing the assertion that the target list has to be non-NULL. One example of an empty target list is inserting rows without columns into tables without columns.
> Allow ORCA plans with empty target list

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
Resource Groups are a core piece of functionality in Greenplum. Resource Groups requires certain OS packages to be installed. When users are installing the Greenplum Server, that is the appropriate time to require those packages.
Adding libcgroup-tools dependency to Platform Requirements page for GPDB 7.X.
> Docs: added libcgroup-tools to platform requirements page

- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
Resource Groups are a core piece of functionality in Greenplum. Resource Groups requires certain OS packages to be installed. When users are installing the Greenplum Server, that is the appropriate time to require those packages.
Adding libcgroup/libcgroup-tools dependency to Platform Requirements page for GPDB 6.x
> Added libcgroup dependency to Platform Requirements page

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/ExceptHashCompatibleRange.mdp
- src/backend/gporca/data/dxl/minidump/ExceptHashIncompatibleRange.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/include/gpopt/gpdbwrappers.h
- src/test/regress/expected/rangetypes.out
- src/test/regress/expected/rangetypes_optimizer.out
- src/test/regress/sql/rangetypes.sql
Previously, ORCA would set a datatype as hashable or not based on the
equality operator. As part of postgres 9.4 merge commit
(https://github.com/postgres/postgres/commit/36ea99c84d856177ec307307788a279cc600566e)
range's are treated as containers and whether a range type can support
hashing is decided based on hashing support of the range's subtype. This
check is done as part of fetching `HASH_PROC` in `lookup_typ_cache()`, which
is also later fetched when executing the query with a range type.
For a query where the range's subtype is not hashable, ORCA treats it as hashable
and generates a HASH plan which later fails during execution.  Below is an example:
```
create type cashrange as range (subtype = money);
select '(2,5)'::cashrange except select '(5,6)'::cashrange;
```
Here ORCA …
> [ORCA] update relcache logic for setting hashable for RANGETYPES 

- gpMgmt/sbin/gpconfig_helper.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Long log:
`BaseException.message` was deprecated since Python 2.6 and removed in Python 3.
Please refer to [stackoverflow link](https://stackoverflow.com/questions/13063212/deprecationwarning-baseexception-message-has-been-deprecated-as-of-python-2-6-e
)
This is a tiny example:
```
def test_func():
if 1 == 2:
allen_dic = {}  # trigger an exception
allen_dic['allen'] = 'handsome'
try:
test_func()
except Exception as e:
raise Exception("Error msg: %s" % e.message)
```
Run the example in _Python3_, error result is shown as below:
```
File "hello.py", line 9, in <module>
raise Exception("Error msg: %s" % e.message)
AttributeError: 'UnboundLocalError' object has no attribute 'message'
```
**Solution**: substitute `str(e)` for `e.message`
Signed-off-by: …
> Fix: BaseException.message deprecated since Python 2.6

- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
- gpMgmt/bin/gppylib/test/unit/test_unit_mainUtils.py
Long log:
Since `assertEquals()` has become a deprecated method in unittest,
`assertEquals()`  should be substituted by `assertEqual()`.
Take an example as below:
```
import unittest
class TestStringMethods(unittest.TestCase):
def test_negative(self):
firstValue = "abc"
secondValue = "abc"
self.assertEquals(firstValue, secondValue)
if __name__ == '__main__':
unittest.main()
```
run main.py, `DeprecationWarning `will happen.
```
python3 main.py 
main.py:7: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(firstValue, secondValue)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
```
>  Clean up the use of the deprecated unittest.TestCase.assertEquals()

- src/backend/cdb/endpoint/README
- src/backend/cdb/endpoint/cdbendpoint.c
- src/backend/cdb/endpoint/cdbendpointutils.c
- src/test/isolation2/input/parallel_retrieve_cursor/privilege.source
- src/test/isolation2/output/parallel_retrieve_cursor/privilege.source
- src/test/regress/.gitignore
It's a weird behavior that parallel retrieve cursors are opened on
behalf of the session user no matter who the current user is, and it
confuses the database users.
This commit changes the behavior to open parallel retrieve cursors on
behalf of the current user, just as how these parallel retrieve cursor
functions check permissions.
> Open parallel cursors on behalf of the current user

- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/test/regress/expected/qp_correlated_query.out
- src/test/regress/expected/qp_correlated_query_optimizer.out
- src/test/regress/sql/qp_correlated_query.sql
This PR is a backport of #15648
This PR fixes the crash in ORCA observed with skip-level correlated query containing a subquery with exhaustive2 join order.
Setup:
-------
```
create table t1(a int, b int);
create table t2(a int, b int);
create table t3(a int, b int);
```
Query:
-------
```
explain select * from t1 where ( EXISTS ( select t2.a from t2 left join t3 on (
EXISTS ( select t1.b from t2))));
```
Detailed RCA:
-------------
In 6X the optimizer_join_order is exhaustive by default. On setting the optimizer_join_order to exhaustive2 trace flag EopttraceEnableLOJInNAryJoin is enabled. Due to this CLogicalLeftOuterJoin is converted to CLogicalNAryJoin in the preprocessing stage. For the above query while deriving the join stats using method CJoinStatsProcessor::DeriveJoinStats the …
> Fixing crash in ORCA with skip-level correlated query with exhaustive2 join order

- src/backend/gporca/scripts/convert_minirepro_5_to_6.py
- src/backend/gporca/scripts/get_debug_event_counters.py
The "version" argument to ArgumentParser is deprecated. 
Please refer to https://bugs.launchpad.net/yade/+bug/1134422
Take a short example:
```
import argparse
parser = argparse.ArgumentParser(version='1.0')
```
the error result is shown as below:
```
$ python3 main.py 
File "main.py", line 2, in <module>
parser = argparse.ArgumentParser(version='1.0')
TypeError: __init__() got an unexpected keyword argument 'version'
```
**Solution**: use `parser.add_argument()` to fix it.
> Fix the version argument to ArgumentParser is deprecated

- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
gprecoverseg job has been failing recently on pipeline due to few testcase failures
Failure 1:
"HOOK-ERROR in after_scenario: OperationalError: ERROR:  tablespace "outerspace" is not empty" 
Testcase: differential recovery works with tablespaces -- @1.2 
Root cause: In after scenario during cleanup of tablespace, first database is dropped before dropping the tablespace. Looks like when we try to drop tablespace, database is not dropped yet as it is taking time to delete database. Hence the error
Solution:  while cleaning up the tablespace, after executing query to drop database added a check to verify that database has been dropped. If database has been dropped then only proceed to drop the tablespace.
Failure 2: 
Step "gpstate should print "Segments in recovery" to stdout" is failing …
> Fix intermittent pipeline failures

- gpdb-doc/markdown/admin_guide/external/g-s3-protocol.md
backport docs changes in https://github.com/greenplum-db/gpdb/pull/14572 to 5X_STABLE
> docs - create s3 protocol as trusted (5x)

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
Backport of #14976
____________
Previously, header_callback(), used to get and parse HTTP headers, took only first status header from all header blocks to show it to user. The problem is that we can have multiple messages with multiple header blocks. In case of error, only first (successful) status is shown to user, which is not informative. This patch fixes header_callback(), which now process all status headers.
> [6X] Fix url_curl.c headers handling

- doc/src/sgml/recovery-config.sgml
- src/backend/access/transam/recovery.conf.sample
- src/backend/access/transam/xlog.c
- src/backend/postmaster/postmaster.c
- src/include/access/xlog_internal.h
- src/test/recovery/t/104_recovery_target_action.pl
Currently, the `pause_at_recovery_target` recovery config option is effectively useless in GP 6X since it works only when `hot_standby` mode is enabled and GP 6X does not support it.
I propose to backport the following patches from Postgres 9.5 to replace the `pause_at_recovery_target` with the `recovery_target_action` recovery config setting for better control over the recovery process:
- https://github.com/postgres/postgres/commit/aedccb1f6fef988af1d1a25b78151f3773954b4c
- https://github.com/postgres/postgres/commit/b8e33a85d4e86a8391118c3d5cdb249b560dec4f
- https://github.com/postgres/postgres/commit/da71632fcfc4e642e9bafb2c0074cad109e59486
- https://github.com/postgres/postgres/commit/51c11a7025ecc10c2b922d60a056ad7c6cf147a5
- …
> [6X] Backport recovery_target_action from PostgreSQL 9.5

- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/setup.sql
When an error occurs in pg_basebackup(), its detail can not be printed properly. Instead, the following error will be raised:
```
+ERROR:  TypeError: can only concatenate str (not "bytes") to str
+CONTEXT:  Traceback (most recent call last):
+  PL/Python function "pg_basebackup", line 26, in <module>
+    results = str(e) + "\ncommand output: " + e.output
+PL/Python function "pg_basebackup"
```
This problem is caused by that `e.output` is a bytes array and cannot contact with str.
Change `e.output` to `e.output.decode()`
> Fix the bug for error report in pg_basebackup().

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/db/catalog.py
- gpMgmt/bin/gppylib/operations/Makefile
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/get_segments_in_recovery.py
- gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_get_segments_in_recovery.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
- gpMgmt/bin/gppylib/programs/clsAddMirrors.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/bin/gppylib/recoveryinfo.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegsetuprecovery.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/sbin/gpsegsetuprecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Backport of https://github.com/greenplum-db/gpdb/pull/15146
**Context:**
Greenplum so far has 2 modes for mirror recovery: FULL and INCREMENTAL. Incremental happens in 2 flavors based on the situation purely WAL based or pg_rewind based. Existing mirror disconnecting and reconnecting back is purely WAL based incremental recovery. When for a segment, preferred roles is same as actual role on running gprecoverseg, incremental pg_rewind based recovery happens
**Challenge:**
In some situations, incremental recovery could fail like due to missing WAL logs (because of GUC max_slot_wal_keep_size or space constraints) or pg_rewind interrupted. Postgres does not recommend running pg_rewind again upon failure (https://www.postgresql.org/docs/current/app-pgrewind.html). FULL recovery is the only …
> [6X] gprecoverseg differential recovery(rsync based)

- gpMgmt/bin/gppylib/gpcatalog.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Objects in these two catalogs do not have pg_depend nor pg_shdepend entries. We should ignore the dependency check for them like a few others.
Fix https://github.com/greenplum-db/gpdb/issues/12016
> gpcheckcat shouldn't throw dependency error for pg_subscription and pg_transform

- src/backend/gporca/data/dxl/minidump/CastedScalarIf-On-Index-Key.mdp
- src/backend/gporca/data/dxl/minidump/InferPredicatesBCC-vc-vc.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-IDFWithCast.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CCastUtils.h
- src/backend/gporca/libgpopt/src/base/CCastUtils.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/sql/bfv_index.sql
Motivation:
Customer reports plan difference when the predicate is written in the form of `col op val` vs. `val op col`. Specifically, if the column is the on left side, ORCA is able to leverage the bitmap scan alternative given the indexed column. When the value is placed on the left side, ORCA chooses much inferior a plan with sequential scan.
Root cause:
The transform from select into bitmap scan expects predicates with columns on the left side and values on the right side. That is, in order for the bitmap scan alternative to be generated, the predicate has to be in the form of `col op val`. If the predicate is written in the form `val op col`, preprocessor converts it to `col op val`. This way, entering the exploration phase, a scalar comparison expression is already reordered. …
> [Backport] Reorder scalar comparison expression in case of cast (#15880)

- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/bin/gppylib/utils.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
This is a cherry-pick of https://github.com/greenplum-db/gpdb/pull/15566
Problem: During gprecoverseg host-name and host-address fields are getting populated with the same value(host-address) in the gp_segment_configuration table after recovery. The reason being the recovery input configuration file can have only three parameters host-address, port, data-directory and host-name field is not there. In previous versions of gpdb, the hostname was resolved using the provided host-address but the functionality used to resolve the hostname was not stable and faulty. So, It was removed in https://github.com/greenplum-db/gpdb/commit/f61d35cdeacc2f97e234648e06788207fb9e53fc with the reason provided "The hostname resolution from address was incorrect and faulty in its logic - an IP address never …
> [6X]Added host-name parameter in recovery configuration

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_PROTOCOL.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_PROTOCOL.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_PROTOCOL.html.md
external protocols are greenplum-specific, so no postgres ref pages to align to.
in this PR:
- some misc edits
- can someone confirm that greenplum 7 continues to support external protocols as they existed in greenplum 6?
> docs - edits to ALTER/CREATE/DROP PROTOCOL

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
This PR adds the following sentences to the existing resource group documentation for Greenplum 7:
- You cannot manually assign roles to the system_group resource group.
- The value of `gp_resgroup_memory_query_fixed_mem` must be lower than `max_statement_mem`.
> Docs: few modifications to existing resource group documentation

- src/bin/pg_dump/common.c
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/pg_dump.h
- src/test/regress/expected/pg_dump_locking.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/pg_dump_locking.sql
Currently, getTables will hold a lock on all partition tables in the database by calling `pg_get_partition_def` and
`pg_get_partition_template_def` on each table, resulting in tables being locked that are not part of the backup set.
This commit extracts the `pg_get_partition_def` and `pg_get_partition_template_def` function calls out of getTables and into `getPartitionDefs`. Now, only partition tables in the backup set  will be included in calls to these functions.
Add a regression test to ensure pg_dump doesn't attempt to lock
partition tables outside the backup set.
> 6X: Add getPartitionDefs function to pg_dump
