greenplum-db/gpdb

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/option.c
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/commands/foreigncmds.c
The legacy code of foreign data wrapper forget to separate the option 'num_segments', so when creating foreign server with option 'num_segments', each FDW extensions have to add an option 'num_segments' which is supposed to be a public option for FDW.
The testing cases has been add in this commit:
https://github.com/greenplum-db/gpdb/commit/4eda660b305cc10743eee16227983ec0d79311cc with 'num_segments' option added.
> Separate out option 'num_segments' for foreign server validators

- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Problem:** After recovery, the segment should start in the default mode of dispatch for 6x. Currently, gprecoverseg starts the segment in utility mode after the recovery. Before recovery, all segments are in dispatch mode (gp_role_string). With this PR we are making sure that after the recovery, we are not changing the gp_role of the segment.
In the case of 6X, we do not pass any parameter/role value when starting the segment. Here's how the segment looks on a newly created cluster: 
`/usr/local/gpdb6/bin/postgres -D /data/dbfast1/demoDataDir0 -p 6002`
After the recovery, before this PR, gprecoverseg adds execute parameter in the command line. Here's how the command line looks: 
`/usr/local/gpdb6/bin/postgres -D /data/dbfast1/demoDataDir0 -p 6002-c gp_role=utility`
**Solution:**
With …
> [6X] starting segments in default mode post recovery 

- src/backend/parser/parse_partition_gp.c
- src/test/regress/input/partition_ddl.source
- src/test/regress/output/partition_ddl.source
This commit addresses an issue arising when creating a partitioned table with its child partitions using the classic partitioning syntax in one command. Semantically, if both the parent and the child table had specified reloptions (using the WITH clause), the child's reloptions would override the parent's.
However, in Greenplum 7, with the integration of the table AM API, the internal parsing of "appendonly" and "orientation" as reloptions has been phased out. Instead, the syntax "USING ao_{row,column}" has been standardized, effectively making "WITH (appendonly=true, orientation=xxx)" an alias.
Thus, if a child partition is created using the classic partitioning syntax, and it uses a different table access method than its parent but doesn't specify its own reloptions, it's better for the …
> Don't inherit parent's reloptions if child partition's AM differs

- gpMgmt/bin/gpsd
Long log:
The `distutils `module was deprecated in Python 3.10 and is scheduled for removal in Python 3.12.
At the same time, it is also dead code.
> Remove deprecated distutils

- gpMgmt/bin/gpload.py
- gpMgmt/bin/gpload_test/gpload2/init_file
- gpMgmt/bin/gpload_test/gpload2/query497.ans
- gpMgmt/bin/gpload_test/gpload2/query75.ans
Don't apply str(obj, errors='ignore') on a str object, otherwise an exception will be raised.
```
➜ python
Python 3.11.3 (main, Apr  5 2023, 15:52:25) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> str(str('a'))
'a'
>>> str(str('a'), errors='ignore')
File "<stdin>", line 1, in <module>
TypeError: decoding str is not supported
```
> Don't apply str(obj, errors='ignore') on a str object.

- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
For ubuntu20.04 gprecoverseg test case fail.
Problem : In test case we use  hostname -I command to get host address and it will gives all the address associated with hostname. so while creating the input config file it taking an extra space and the format of the file becomes incorrect thats throwing error.
Solution: Split hostname -I command output and return the first element so there will be no extra space and It will make input config file format correct.
> [7x]: Fix for gprecoverseg test case failure

- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
originally had two procedures, one for 1.x -> 2.0 upgrade and 2.n -> 2.newer.
questions:  are any steps required for diskquota 2.2.1 -> 2.2.2 upgrade?  or does the stopping and restarting of greenplum to apply its upgrade take care of things?
> docs - new diskquota module upgrade instructions

- gpdb-doc/markdown/admin_guide/highavail/topics/g-recovering-from-segment-failures.html.md
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
PR https://github.com/greenplum-db/gpdb/pull/15566 introduces a new column `failedHostfile` to the input file for gprecoverseg.  This PR modifies the documentation so the new column is introduced.
Note the PR is for main but will also be introduced for 6X_STABLE as the target release is 6.25.
The PR for main is https://github.com/greenplum-db/gpdb/pull/15908
> Docs: added failedHostname column to gprecoverseg input file

- src/backend/catalog/partition.c
- src/backend/commands/analyze.c
- src/backend/commands/analyzeutils.c
- src/backend/postmaster/autovacuum.c
- src/include/catalog/partition.h
- src/test/isolation2/input/autovacuum-analyze.source
- src/test/isolation2/output/autovacuum-analyze.source
Currently, autoanalyze will simply ignore intermediate/root partitions and only sample data from partition leaves. However, the Orca and Planner optimizers rely on root partition statistics in order to generate performent plans, and GPDB heavily uses partitioned tables. One of the main concerns in upstream Postgres is the sampling time to resample the entire partition hierarchy.
GPDB supports merging leaf partition statistics, and this PR utilizes this feature in order to significantly speed up populating root stats. When analyzing a leaf partition, if all other leaves are analyzed, the root partition stats will be populated by merging statistics. To prevent redundant merging of statistics (which can take non-insignificant time with many partitions and columns), we only merge stats at the …
> Collect statistics for root partitions during autoanalyze

- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Parity changes from 6X PR: https://github.com/greenplum-db/gpdb/pull/15915 
Mirror segments always give the same error message even if in utility mode or dispatch mode 
hence no way to detect the mode for mirrors. 
Changes done in this PR: 
- Updated step to check segment in execute mode to check only primary segments 
- Check the exact error message thrown by mirror when in execute mode 
Testing done:
Ran test case on demo cluster and concourse cluster.
> [7x-Test Changes] Parity changes for check if segment in execute mode

- src/test/isolation2/expected/crash_recovery_dtm.out
- src/test/isolation2/sql/crash_recovery_dtm.sql
We might be hitting a race condition where we are suspending `after_orphaned_check` on before suspending on `before_orphaned_check`, which may cause the `gp_inject_fault_infinite` of
`before_orphaned_check` to never get triggered.
Reorder the fault injection to fix the issue.
> Fix flaky test for crash_recovery_dtm

- gpMgmt/bin/gpload.py
Long log:
threading.Thread.getName() is deprecated since python 3.10.
Deprecated getter/setter API for [name](https://docs.python.org/3/library/threading.html#threading.Thread.name); use it directly as a property instead.
Take a simple example in python 3.10:
```
import threading
import time
def run(n):
print("task", n)
time.sleep(1)
print('1s')
time.sleep(1)
print('0s')
time.sleep(1)
if __name__ == '__main__':
t1 = threading.Thread(target=run, args=("t1",))
t1.start()
print(t1.getName())
print(t1.name)
```
The result is shown as below:
```
$ python main.py
task t1
/hoem/gpadmin/main.py:15: DeprecationWarning: getName() is deprecated, get the name attribute instead
print(t1.getName())
Thread-1 (run)
Thread-1 (run)
1s
0s
```
> Fix threading.Thread.getName() is deprecated

- src/backend/cdb/cdbpath.c
Since there already have PR #9183 to elide explicit motion, we can delete this
FIXME directly.
> remove FIXME in function `create_motion_path_for_updel()`

- src/backend/access/external/url_curl.c
- src/backend/utils/misc/guc_gp.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
This PR wants to adjust some default configurations of gpfdist and libcurl on segments.
1. Adjust `writable_external_table_bufsize` default value to 1M.
This will increate the throughput when writing into gpfdist writable external table.
2. Enable keepalive for libcurl socket for gpfdist readable external tables. 
In some particular scenarios like select from readable external tables that gpfdist server and 
segments are not in the same network region, some of the long connections between gpfdist
and segments will broken, in this case gpfdist will fail to send EOF to segment so that may be
one of the QEs will hung in waiting for data coming. As the legacy code of libcurl socket does
not enable keepalive probes, so it will hung forever and fails to detect the broken of the 
connection. …
> Optimize gpfdist external table logic

- src/backend/access/bitmap/bitmaputil.c
- src/backend/access/bitmap/bitmapxlog.c
- src/include/access/bitmap_xlog.h
- src/test/isolation2/expected/bitmap_index_crash.out
- src/test/isolation2/sql/bitmap_index_crash.sql
This PR is trying to fix the issue of #13517. The RCA could be found at [huansong's comments](https://github.com/greenplum-db/gpdb/issues/13517#issuecomment-1601716547).
The data registered by `XLogRegisterBufData()` could be replaced by Full Image, and the value 
of `bm_next_blkno` in special data is page data too, if we change that, we should record it in XLog, 
instead of predicting it in the replay process.
> fix bitmap index

- src/backend/gporca/data/dxl/minidump/Hash-BitmapScan-InArray.mdp
- src/backend/gporca/data/dxl/minidump/Hash-TableScan-AllArray.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformUtils.h
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/sql/bfv_index.sql
Previously, when we added support for Hash Indexes we only considered it for Equality comparator and not for ScalarArrayCmp. As part of commit 327592f, we added support to consider Bitmap scans for OR and IN predicates on btree indexes. Need to extend it to consider Bitmap scan alternatives for ArrayCmp predicates on hash indexes too. This commit also updates the var names to reflect that we consider Bitmap alternatives for other indexes(btree and hash) and not just for btree indexes.
> [ORCA] Support BitmapIndex plans for ArrayCmp on Hash indexes

- src/bin/pg_dump/common.c
- src/bin/pg_dump/pg_dump.c
- src/bin/pg_dump/pg_dump.h
Commit 1:
Currently, when backing up a GP5 or GP6 database, getTables will
hold a lock on all partition tables in the database by calling
`pg_get_partition_def` and `pg_get_partition_template_def` on each table,
resulting in tables being locked that are not part of the backup set.
This commit extracts the `pg_get_partition_def` and
`pg_get_partition_template_def` function calls out of getTables and
into getPartitionDefs. Now, only partition tables in the backup set  will be
included in calls to these functions.
Commit 2:
Postpone calls of unsafe server-side functions in pg_dump.
Backported from PG15 e3fcbbd
Conflicts resolved:
* OidOptions enum value zeroIsError does not exist, instead used the
existing zeroAsOpaque.
* Minor conflicts in dumpTableSchema resulting from foreign server …
> Refactor pg_dump queries to gather partition definitions

- src/backend/access/external/url_curl.c
- src/backend/utils/misc/guc_gp.c
- src/bin/gpfdist/regress/input/exttab1.source
- src/bin/gpfdist/regress/output/exttab1.source
This PR wants to adjust some default configurations of gpfdist and libcurl on segments.
1. Adjust `writable_external_table_bufsize` default value to 1M.
This will increate the throughput when writing into gpfdist writable external table.
2. Enable keepalive for libcurl socket for gpfdist readable external tables. 
In some particular scenarios like select from readable external tables that gpfdist server and 
segments are not in the same network region, some of the long connections between gpfdist
and segments will broken, in this case gpfdist will fail to send EOF to segment so that may be
one of the QEs will hung in waiting for data coming. As the legacy code of libcurl socket does
not enable keepalive probes, so it will hung forever and fails to detect the broken of the 
connection. …
> Optimize gpfdist external table logic 6x

- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
This is a cherry-pick of https://github.com/greenplum-db/gpdb/pull/15910
gprecoverseg job has been failing recently on pipeline due to few testcase failures
Failure 1:
"HOOK-ERROR in after_scenario: OperationalError: ERROR:  tablespace "outerspace" is not empty" 
Testcase: differential recovery works with tablespaces -- @1.2 
Root cause: In after scenario during cleanup of tablespace, first database is dropped before dropping the tablespace. Looks like when we try to drop tablespace, database is not dropped yet as it is taking time to delete database. Hence the error
Solution:  while cleaning up the tablespace, after executing query to drop database added a check to verify that database has been dropped. If database has been dropped then only proceed to drop the tablespace.
Failure 2: …
> [6x]: Fix intermittent pipeline failures (#15910)

- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
This is a cherry-pick of https://github.com/greenplum-db/gpdb/pull/15979
For ubuntu20.04 gprecoverseg test case fail.
Problem : hostname -I command gives the list of address associated with hostname. so while creating the input config file it taking an extra space and the format of the file becomes incorrect thats throwing error.
Solution: Split hostname -I command output and return the first element. It will make input config file format correct.
> [6x]: Fix for gprecoverseg tescase failure (#15979)

- src/backend/utils/resgroup/.gitignore
These files are generated by parser generator, let's ignore them.
> Don't track file changes in io_limit_gram[.h|.c]/io_limit_scanner.c

- src/backend/utils/misc/guc.c
Per conversation with team, there is no need for these restrictions to be in place, and users have requested that they be lifted.  This commit removes them.
> Remove block on changing checkpoint_timeout GUC

- src/backend/executor/execProcnode.c
- src/include/nodes/execnodes.h
Commit e0cca54551 add a new field at the end of struct PlanState, however PlanState is many other execute Nodes' base. So the previous commit breaks ABI of stable version. This commit fixes it by adding the field in SubPlanState, which is a leaf struct in GPDB 6 (no other struct include it as base).
> Fix ABI broken of 6X introduced by e0cca54551.

- src/backend/access/external/url_curl.c
> Fix compilation for libcurl with version lower than 7.19 (6X_STABLE)

- src/backend/commands/vacuum_ao.c
- src/test/isolation2/expected/vacuum_progress_column.out
- src/test/isolation2/expected/vacuum_progress_row.out
- src/test/isolation2/sql/vacuum_progress_column.sql
- src/test/isolation2/sql/vacuum_progress_row.sql
VACUUM Append-Optimized is a multi-phases process, coordinator performs disptching vacuum for doing each phase job respectively, progress reporting accumulates each phase data as long as running vacuum on the same backend of each segment.
However, multiple dispatches job could be handled on different backends when there is an update of cluster configuration such like mirror down or node expansion. If this event happens in between phases of VACUUM, the vacuum backend may be changed resulting in accumulated progressing data in former phases being reset in the new worker.
This patch allows vacuum reporting per-phase progress instead of failing assertion like issue https://github.com/greenplum-db/gpdb/issues/15916 when vacuum backend is changed in between phases.
Dev-pipeline: …
> [7X] Remove assertion to allow per-phase progress reporting on VACUUM AO/CO.

- src/backend/commands/copy.c
- src/backend/parser/gram.y
- src/include/nodes/parsenodes.h
This is the same pr as https://github.com/greenplum-db/gpdb/pull/14840 but cherry-picked to master branch 
This resolves GPDB_91_MERGE_FIXME in copy.c
Yacc parser rules modified so that SREH clause now return a list of options, which is later concatenated with other copy stmt options.
Removed plain C code from copy.c which does exatly the same.
Change sreh type to List in CopyStmt struct.
> [7x] Move single row expression handler list-concat logic to parser.

- src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorUtils.cpp
- src/backend/gporca/data/dxl/minidump/RTErequiredPerms.mdp
- src/backend/gporca/libgpopt/include/gpopt/metadata/CTableDescriptor.h
- src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorDXLToExpr.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLTableDescr.h
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLTableDescr.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/src/unittest/CTestUtils.cpp
- src/backend/gporca/server/src/unittest/dxl/statistics/CStatisticsTest.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CDMLTest.cpp
- src/backend/gporca/server/src/unittest/gpopt/translate/CTranslatorDXLToExprTest.cpp
- src/include/gpopt/translate/CContextDXLToPlStmt.h
- src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
- src/test/regress/expected/privileges.out
- src/test/regress/expected/privileges_optimizer.out
**Background:**
ICW test privileges was turned off on ORCA in 2014 after ORCA generated plans
requesting incorrect privilege, causing queries that should be executed denied.
To revive the test, we have a few issues to address --
1. Some tests in the suite failed the non-NULL target list assertion in DXL ->
planned statement translation. This issue was fixed by 
PR https://github.com/greenplum-db/gpdb/pull/15939, and the
assertion is no more considered necessary.
2. Duplicate rte's in planned statement. ORCA may generate plans with duplicate
range table entries, each annotated with a different required permission. This
issue was fixed by PR https://github.com/greenplum-db/gpdb/pull/14304. 
Now we reuse rte's in the range table entries list, and update the permission in 
the process.
3. …
> Pass requiredPerms from parse tree to plstmt

- concourse/scripts/gsutil_sync
- gpMgmt/requirements-dev.txt
After switched python3.9 to python3.6, `gsutil` command cannot work on RHEL8 image, it will have the following error:
```
File "/usr/lib/python3.6/site-packages/urllib3/exceptions.py", line 2, in <module>
from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'
```
By default the RHEL8 system has the package `urllib3` installed under `/usr/lib/python3.6`, when installing `gsutil`,the dependencies are installed under `/usr/local/lib/python3.6`, so `gsutil` cannot find dependencies when calling `urllib3`. In order to fix the above error, need to uninstall and reinstall urllib3.
> Fix gsutil command failed due to wrong dependency location

- src/backend/optimizer/plan/setrefs.c
- src/test/regress/expected/bfv_aggregate.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
- src/test/regress/sql/bfv_aggregate.sql
The root cause was that Aggref in targetlist of AggNode refer incorrect VAR in subplan targetlist.
```
postgres=# explain verbose SELECT MIN(tx.c1) FROM tx GROUP BY (tx.c1)::VARCHAR;
QUERY PLAN                                     
------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=298.00..314.67 rows=1000 width=64)
Output: (min(c1)), ((c1)::character varying)
->  HashAggregate  (cost=298.00..301.33 rows=333 width=64)
Output: min(c1), ((c1)::character varying)
Group Key: (tx.c1)::character varying
->  Seq Scan on public.tx  (cost=0.00..210.00 rows=17600 width=64)
Output: (c1)::character varying, c1
Settings: optimizer = 'off'
(9 rows)
```
as above plan, c1 in min(c1) should …
> Fix error of relabelType in group by clause

- gpcontrib/gp_toolkit/gp_toolkit--1.0.sql
- src/test/isolation2/expected/resgroup/resgroup_views.out
- src/test/isolation2/sql/resgroup/resgroup_views.sql
Add view gp_resgroup_status_per_segment to show memory usage calculated by vmem tracker.
The usage of gp_resgroup_status_per_segment is as follows:
create extension gp_toolkit;
postgres=# select * from gp_toolkit.gp_resgroup_status_per_segment ;
groupid |  groupname  | segment_id | vmem_usage 
---------+-------------+------------+------------
6438 | admin_group |         -1 |         13
6438 | admin_group |          0 |          9
6438 | admin_group |          1 |          9
6438 | admin_group |          2 |          9
(4 rows)
The view  gp_toolkit.resgroup_session_level_memory_consumption is similar to session_state.session_level_memory_consumption, But session_state.session_level_memory_consumption is in another extension, and we can not create extension nested. So in extension …
> add view gp_resgroup_status_per_segment to show vmem usage of resource group in each segment

- src/backend/commands/sequence.c
- src/backend/nodes/outfuncs.c
- src/backend/nodes/readfuncs.c
- src/test/regress/expected/truncate.out
- src/test/regress/sql/truncate.sql
After rollback a transaction which execute restart identity clause in, the insert result to sequence column is incorrect. It's due to the cache value stored in hash table in QE has been out of date but not be cleaned.
If the sequence has been transactionally replaced since we last saw it, should discard any cached-but-unissued values both in QD and QE. Dispatch TruncateStmt with restart_seqs to enable segment to reset a sequence when specify restart identity.
> Fix insert result error to sequence column

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/cdb/cdbcat.c
- src/backend/cdb/cdbutil.c
- src/backend/executor/execUtils.c
- src/backend/executor/nodeModifyTable.c
- src/backend/optimizer/plan/createplan.c
- src/backend/optimizer/util/pathnode.c
In some special FDW cases, Greenplum could have more or less backends than the number of actual segments in one gang, this commit sets the policy correctly.
> Fix the policy of foreign tables

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Problem : Running gpcheckcat FK check taking a lot of time to complete, One of the workarounds to fix this is to Pull the FK query and run it separately in psql using the GUC disable_cost='1e20' at session level. It help in making the query run faster but its not acceptable solution.So need to set the GUC at session level.
Solution : Added a new option [-x] in gpcheckcat that will provide support for PGOPTIONS to pass multiple session GUCs [such as disable_costs, gp_role] to set the parameter.
Implementation : Added a new option -x which is used to pass the multiple session GUCs to set the parameter. This is helpful when wanting to run certain tests in gpcheckcat with session level parameters. User can use the -x option multiple times to specify multiple GUC.
User can pass the GUC like : …
> gpcheckcat: Add new option -x to set session level GUCs

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Differential recovery left the replication slot in the inactive state, and because of that wal keeps accumulating on the primary. 
1. check if the database is up and running.
2. make any of the mirrors down, and wait for the configuration to update.
3. run differential recovery, this will make the down mirror up and start the segment.
4. check the pg_replication_slot table, where you will find the slot is in an inactive state, and active_pid column will be empty.
****Expectation**: post recovery the replication_slot should be active.**
Firstly checked the pg_replication_slots table post differential recovery.
```
slot_name           | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | confirmed_flush_lsn | wal_status | …
```
> [7X]Fix replication slot inactive  issue post differential recovery.

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
- gpMgmt/bin/gppylib/operations/update_pg_hba_on_segments.py
- gpMgmt/bin/gppylib/test/unit/test_unit_seg_update_pg_hba.py
- gpMgmt/sbin/seg_update_pg_hba.py
- gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
- src/backend/replication/libpqwalreceiver/libpqwalreceiver.c
- src/test/walrep/gplibpq.c
- src/test/walrep/input/setup.source
- src/test/walrep/output/setup.source
Fixes https://github.com/greenplum-db/gpdb/issues/13030
**Problem:** 
When moving mirrors from one host to another in a multi-host cluster setup, an inconsistency is observed in the gp_segment_configuration data. This occurs when mirrors are recovered on a new host due to the old host's unavailability. A situation arises where the current host becomes unreachable while the old host becomes reachable. As a result, gp_segment_configuration incorrectly shows mirrors as "up" even though their actual hosts are unavailable
**RCA:**
- We are using the GPDB internal protocol for streaming replication connections. The internal protocol is meant for special QD<->QE libpq interaction (fts, dispatch etc). For walsender<->walreceiver connections, this is not necessary.
- The issue arises when a mirror …
> [7x] walsender connecting to the wrong walreceiver

- src/backend/access/brin/README
- src/backend/access/brin/brin.c
- src/backend/access/common/reloptions.c
- src/backend/catalog/index.c
- src/backend/utils/adt/selfuncs.c
- src/backend/utils/cache/lsyscache.c
- src/include/access/brin.h
- src/include/access/reloptions.h
- src/include/catalog/catversion.h
- src/include/catalog/index.h
- src/include/utils/lsyscache.h
- src/test/regress/expected/brin_interface.out
- src/test/regress/sql/brin_interface.sql
For heap tables, we have decided to scale back the default to 32, since in GPDB
one heap block is 4x the default size in PG.
For AO/CO tables, since many more tuples fit in 1 logical heap block as
opposed to heap (for e.g. the tpch lineitem table will have at most 248
tuples/block, whereas an AO/CO table is bound to have 32768
tuples/block).
Having a default of 32 will thus be counter-productive - CPU processing
cost from unwanted tuples will far outweigh any IO cost savings and will
dominate the total cost of the query (as per planner cost estimation).
Thus, we use the lowest default possible: a default value of 1.
Implementation:
Without access to the base table type inside brinoptions(), we are left
with no choice but to introduce a thin layer over the default value. We
define …
> brin: Adjust the default value of pages_per_range

- src/test/regress/expected/select_parallel.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/expected/write_parallel.out
- src/test/regress/sql/select_parallel.sql
- src/test/regress/sql/write_parallel.sql
Since Greenplum doesn't support parallel scan, so change the FIXME to
FEATURE NOT SUPPORTED. But this is the feature of version 9.6, and we do
not want to create another new FLAG, so change it to the value of
`GPDB_12_MERGE_FEATURE_NOT_SUPPORTED`
>  change parallel test FIXME to FEATURE NOT SUPPORTED 

- gpAux/gpperfmon/src/gpmon/gpmmon.c
gpdb_get_master_data_dir should set master_data_dir variable with non-NULL pointer. However, there is codepath in this function that leads to NULL result. We need to check this case and finish gpmon process with error if any trouble.
This case is really reproduced in our production
```
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007f18fc1de9ce in __GI___strdup (s=0x0) at strdup.c:41
#2  0x000055ff3885813d in getconfig () at gpmmon.c:1679
#3  main (argc=<optimized out>, argv=<optimized out>) at gpmmon.c:1358
(gdb) Quit
```
> Check `gpdb_get_master_data_dir` result in getconfig

- src/backend/parser/parse_utilcmd.c
- src/test/regress/expected/gp_index.out
- src/test/regress/sql/gp_index.sql
Co-authored-by: Xing Guo <admin@higuoxing.com>
The unique index key order will affect the distribution key order of child partitions. For example we create a partitioned table with distribution key(a, b, c). After that, an unique index created on (a, c, b):
```
CREATE TABLE foo1 (a int, b int, c int)  DISTRIBUTED BY (a,b,c) PARTITION BY RANGE(a) 
(PARTITION p1 START (1) END (10000) INCLUSIVE,
PARTITION p2 START (10001) END (100000) INCLUSIVE,
PARTITION p3 START (100001) END (1000000) INCLUSIVE);
create unique index acb_idx on public.foo1 using btree(a,c,b);
```
When adding a new partition p4, we found the p4 distribution key has been changed to (a ,c ,b) which is different from other partitions:
```
alter table public.foo1 add partition p4 START (1000001) END (2000000) INCLUSIVE;
\d+ …
```
> Fix error of unique index key order

- src/backend/utils/misc/guc_gp.c
This PR backport https://github.com/greenplum-db/gpdb/pull/15632 to 6x.
> [6X] Changing the default value of dtx_phase2_retry_count to 60

- gpcontrib/gp_parallel_retrieve_cursor/gp_parallel_retrieve_cursor.c
- src/backend/cdb/endpoint/README
- src/backend/cdb/endpoint/cdbendpoint.c
- src/test/isolation2/input/parallel_retrieve_cursor/privilege.source
- src/test/isolation2/output/parallel_retrieve_cursor/privilege.source
It's a weird behavior that parallel retrieve cursors are opened on behalf of the session user no matter who the current user is, and it confuses the database users.
This commit changes the behavior to open parallel retrieve cursors on behalf of the current user, just as how these parallel retrieve cursor functions check permissions.
> 6X: Open parallel cursors on behalf of the current user

- gpMgmt/bin/gppylib/commands/base.py
- gpMgmt/bin/gppylib/commands/unix.py
Use findCMDInPath("bash") in Command for portability.
Use "/bin/bash" is not portable for some environments, like nix. And gpdb already has ‘findCMDInPath' to get path of command(find from system PATH and some custom paths), so use findCMDInPath("bash")  to get bash path is a convenient way. BTW, move findCMDInPath to base.py for solving cyclic import.
> Use findCMDInPath("bash") in Command

- contrib/postgres_fdw/Makefile
- contrib/postgres_fdw/connection.c
- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/option.c
- contrib/postgres_fdw/postgres_clean.bash
- contrib/postgres_fdw/postgres_fdw.c
- contrib/postgres_fdw/postgres_fdw.h
- contrib/postgres_fdw/postgres_setup.bash
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
- contrib/postgres_fdw/sql/postgres_sql/mpp_gp2pg_postgres_init_1.sql
- contrib/postgres_fdw/sql/postgres_sql/mpp_gp2pg_postgres_init_2.sql
This PR is separated from https://github.com/greenplum-db/gpdb/pull/15525.
This feature is designed for scenes that the foreign table is a distributed foreign table which data stored on multiple remote servers.
The main commits are as follows:
```
CREATE SERVER pgserver
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (multi_hosts 'localhost localhost', multi_ports '5432 5555', num_segments '2', mpp_execute 'all segments');
CREATE USER MAPPING FOR gpadmin SERVER pgserver;
CREATE FOREIGN TABLE f_tbl (c1 int) SERVER pg_server OPTIONS (table_name 'l_tbl');
```
SQLs above create a foreign table f_tbl, which consists of l_tbl in two different remote postgres servers.
This feature supports creating and accessing such postgres_fdw foreign tables.
Now we only support read data from remote servers when …
> Add multi_hosts and multi_ports option for postgres_fdw server

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorUtils.cpp
- src/backend/gporca/libgpopt/include/gpopt/metadata/CTableDescriptor.h
- src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/operators/CDXLTableDescr.h
- src/backend/gporca/libnaucrates/src/operators/CDXLOperatorFactory.cpp
- src/backend/gporca/libnaucrates/src/operators/CDXLTableDescr.cpp
Since it is a bitmap of uint32 in the parser (see parsenodes.h), it ought to be declared as a ULONG in ORCA (corresponds to uint32_t).
This also rids us of the compiler WARNING:
CTranslatorDXLToPlStmt.cpp:5215:42: warning: comparison of integer expressions of different signedness: ‘gpos::INT’ {aka ‘int’} and ‘unsigned int’ [-Wsign-compare]
5215 |                                 acl_mode <= std::numeric_limits<AclMode>::max());
|                                 ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/orca_fix_acl_mode
> Declare ACL mode as a ULONG

- contrib/postgres_fdw/postgres_clean.bash
Use "/usr/bin/env bash" is more portable than "/bin/bash".
> use "/usr/bin/env bash" in postgres_clean.bash

- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/sql/bfv_index.sql
This is a partial backport of PR: https://github.com/greenplum-db/gpdb/pull/15898
(changes for hash index not ported)
Partial cherry-pick of commit 8bbadb87007502365b244f46d654d6ec3684ced3
Updated test for ALL to have single element in array so that ORCA goes through the codepath that has been fixed as part of this commit. In GP6, ORCA optimizes ALL with multiple array elements to a one-time false filter.
Original commit messgae:
Commit 290166f introduced ScalarArrayOpExpr as an indexable qual for ANY operator only as it is translated into an OR combination of indexscan on the array elements.  Prior to this commit ORCA considered Bitmap alternatives for equality on ScalarArrayCmp (both ANY and ALL) whereas similar to planner, ORCA should also only consider it for equality on ANY op. This …
> [6X] Consider bitmap alternative only for ANY ScalarArray

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/ExceptHashCompatibleRange.mdp
- src/backend/gporca/data/dxl/minidump/ExceptHashIncompatibleRange.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/include/gpopt/gpdbwrappers.h
- src/test/regress/expected/rangetypes.out
- src/test/regress/sql/rangetypes.sql
Previously, ORCA would set if a datatype is hashable or not based on the equality operator. As part of postgres 9.4 merge commit (https://github.com/postgres/postgres/commit/36ea99c84d856177ec307307788a279cc600566e) range's are treated as containers and whether a range type can support hashing is decided based on hashing support of the range's subtype. This check is done as part of fetching HASH_PROC in lookup_typ_cache(), which is also later fetched when executing the query with a range type. For a query where the range's subtype is not hashable, based on just the operator's hashing support ORCA treats it as hashable and generates a HASH plan which later fails during execution.  Below is an example:
```
create type cashrange as range (subtype = money);
select '(2,5)'::cashrange except …
```
> [6X backport] ORCA: update relcache logic for setting hashable for RANGETYPES

- gpMgmt/bin/gppylib/commands/base.py
When inserting elements to Python's `set()`, it doesn't guarantee the elements' order. The commit f8dd733 is causing flaky failure in our CI. This patch helps fix it.
Failed job: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs/check_centos/builds/608
Minimal reproduction script:
```
➜  /tmp python a.py
-------
['/usr/sbin', '/opt/sfw/bin', '/usr/share/Modules/bin', '/usr/local/greenplum-db-devel/bin', '/opt/Navisphere/bin', '/usr/ucb', '/usr/sfw/bin', '/sbin', '/usr/kerberos/bin', '/usr/local/bin', '/sw/bin', '/root/bin', '/bin', '/usr/bin', '/usr/local/go/bin', '/usr/local/sbin']
-------
➜  /tmp python a.py
-------
['/opt/sfw/bin', '/usr/bin', '/usr/ucb', '/usr/local/bin', '/opt/Navisphere/bin', '/usr/share/Modules/bin', '/usr/local/sbin', '/bin', '/usr/local/go/bin', …
```
> [7X] Keep order while removing duplicated paths.

- src/backend/utils/adt/gp_dump_oids.c
- src/test/regress/expected/gp_dump_query_oids.out
- src/test/regress/expected/minirepro.out
- src/test/regress/sql/gp_dump_query_oids.sql
- src/test/regress/sql/minirepro.sql
When a table has an explicitly created sequence, the sequence will be ignored by pg_dump if it's not owned by the table.
In pg_dump, implicitly created sequence like SERIAL and GENERATED AS IDENTITY, the referenced sequence will be dumped if the owning table is dumped. But for explicitly created sequence, we should specify sequence's oid if we want to dump the sequence object when the sequence is not owned by table.
Collect oids of sequence which be referenced by table columns in gp_dump_query_oids.
Fix issue #15856
> minirepro: collect using sequence

- src/test/regress/expected/gp_index.out
- src/test/regress/sql/gp_index.sql
The fix is partially check-pick from
https://github.com/greenplum-db/gpdb/pull/16013. On GPDB7, code fix is not needed, but we still need a test case to cover the scenario of unique index key order of partition table. So I merged the test case with minor changes of regex to handle 7X env.
> Fix error of unique index key order (#16013) on 7X

- src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h
- src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
Issue:
Sample array used for skew stats collection caused stack overflow in address sanitizer environment.
Solution:
Allocate the array on heap memory. Also simplified the math in the sample rate populator for better readability.
Fix #16021
> Allocate histogram sample array on heap

- gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- src/backend/postmaster/postmaster.c
- src/backend/replication/walreceiver.c
- src/bin/pg_ctl/pg_ctl.c
- src/include/storage/pmsignal.h
- src/include/utils/pidfile.h
- src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql
- src/test/isolation2/sql/setup.sql
pg_ctl start -w waits until the postmaster state PM_STATUS_STANDBY
on the mirror for it to return. On postmaster startup, we begin starting
the walreceiver after we have already reached this state. We require the
walreceiver to be up to mark the mirror as up in
gp_segment_configuration. This results in utilities such as gprecoverseg
to complete before the walreceiver is up, while they are still starting.
This commit adds a new postmaster signal PMSIGNAL_WALRCV_STREAMING
which is sent by the walreceiver when it first starts streaming. We
also add a new postmaster state PM_STATUS_WALRECV_STARTED_STREAMING
which is set when the postmaster receives the signal from walreceiver
when it has started streaming.
For mirrors, pg_ctl start -w  will now
wait until this state is reached, to ensure the …
> Set postmaster status ready after walreceiver up

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/toc.md
the first commit adds the greenplum_fdw doc source file from the 6X_STABLE branch.  the second commit includes the changes i made for greenplum 7.
in this PR:
- support 7beta4+ to 7beta4+ for now, so removed the dependencies section (parallel retrieve cursor functionality is built-in in greenplum 7).
- add missing/new content from https://www.postgresql.org/docs/12/postgres-fdw.html. this includes importing a foreign schema and import options, remote execution options, remote query execution environment.
- update postgres links to v12
questions:
- i added a few known issues based on the test output, not sure if i captured them correctly.
- i've noticed some fdw-related PRs in the works, not sure if any of those are applicable to greenplum_fdw.  let me know if they are.
doc review site …
> docs - add content for greenplum_fdw for gp7

- src/test/regress/expected/privileges.out
- src/test/regress/expected/privileges_optimizer.out
- src/test/regress/sql/privileges.sql
Since privileges suite was restored on ORCA, we have been observing flakes associated with creations of multiple views. When we query these views, ORCA may fall back once or multiple times. The fallback info is flagged as plan diffs since we have the trace fallback GUC on. This PR adds "discard plans" to release all cached plans. Now that we force re-planning, we expect to log each ORCA fallback and have a consistent output.
> Reset plan cache to prevent flakes in ICW privileges

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/optimizer/util/pathnode.c
Only when `create_foreignscan_path()`, can we call `cdbpathlocus_from_baserel()` to get `path->locus` if option mpp_execute = 'all segments'.
When `create_foreign_upper_path()` and `create_foreign_join_path()`, `rel->cdbpolicy` is empty.
In this case, `cdbpathlocus_from_baserel()` will return locus with type `CdbLocusType_Entry` even if mpp_execute = 'all segments'.
This behavior is wrong.
In this commit, we modify the method to get `path->locus` for function `create_foreign_upper_path()` and `create_foreign_join_path()`.
> Modify path->locus for foreign table 

- src/backend/utils/resgroup/resgroup.c
It's not re-throw the ERROR in `PG_CATCH`, and according to the current codes,
wo do not need to use `PG_TRY()` to catch the dispatch error, so just remove them.
> remove the inappropriate usgae of PG_TRY

- src/test/recovery/t/003_recovery_targets.pl
changes introduced in 1d2b2288d9b made the test flaky as it doesn't explicitly mention the gp_role in the command.
Adding gp_role to the pg_ctl command fixes this issue
> fix gp_role for CI flaky test 003_recovery_targets

- src/backend/cdb/cdbvars.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
The GUC 'gp_session_role' and 'gp_role' use the same parameter 'gp_role_string' to store the value. It will lead to double free or corruption issue.
See discussion  https://github.com/greenplum-db/gpdb/issues/15370
You can check it with test case 'pg_dump_binary_upgrade'
```
./pg_regress --load-extension=gp_inject_fault --init-file=init_file pg_dump_binary_upgrade
```
> Fix pg_dump_binary_upgrade flaky fails. 

- contrib/postgres_fdw/Makefile
- contrib/postgres_fdw/deparse.c
- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/postgres_fdw.c
- contrib/postgres_fdw/postgres_fdw.h
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
- contrib/postgres_fdw/sql/postgres_sql/mpp_gp2pg_postgres_init_1.sql
- contrib/postgres_fdw/sql/postgres_sql/mpp_gp2pg_postgres_init_2.sql
- contrib/postgres_fdw/transcoding.c
- src/backend/cdb/cdbgroupingpaths.c
- src/backend/optimizer/path/joinpath.c
- src/backend/optimizer/plan/planner.c
- src/backend/utils/adt/numeric.c
- src/include/cdb/cdbgroupingpaths.h
- src/include/foreign/fdwapi.h
- src/include/utils/numeric.h
- src/tools/pgindent/typedefs.list
This PR is separated from https://github.com/greenplum-db/gpdb/pull/15525.
For the convenience of review, https://github.com/greenplum-db/gpdb/pull/15525 is split into multiple sub-PRs.
- sub-PR 1:    https://github.com/greenplum-db/gpdb/pull/15821 (**Merged**)
- sub-PR 2:   https://github.com/greenplum-db/gpdb/pull/15824 (**Merged**)
- sub-PR 3:   current PR
We consider such scenario -- foreign table demo_f_tbl is distributed randomly across multiple remote postgres server.
```
CREATE EXTENSION postgres_fdw;
CREATE SERVER multi_pg_servers
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'all segments', num_segments '2', multi_hosts '127.0.0.1 127.0.0.1', multi_ports '5432 5555', dbname 'postgres');
CREATE USER MAPPING FOR gpadmin 
SERVER multi_pg_servers OPTIONS (user 'postgres'); …
```
> Support partial aggregate functions pushdown to distributed postgres_fdw servers

- src/backend/utils/misc/guc_gp.c
- src/test/isolation2/expected/resgroup/resgroup_bypass.out
- src/test/isolation2/sql/resgroup/resgroup_bypass.sql
This reverts commit 85d943910c74b48e606515fc18a7d4a99e197dbc.
Bypass resgroup still will put proc into cgroup and use a small value of query memory so it will not impact system too much. Revert previous commit let other application like GPCC can work easily.
> Revert "Only super user can set the GUC gp_resource_group_bypass."

- src/test/isolation2/input/autovacuum-analyze.source
- src/test/isolation2/output/autovacuum-analyze.source
Previously, we were checking that the leaf partition was analyzed and immediately querying if the root stats had been populated. While the root stats are merged right after, there is a short time window and if the stats are queried in this window, the root stats would not yet be populated. Instead, wait for the analyze (merge) of the root partition to be completed.
> Fix autovacuum-analyze flake

- src/test/isolation2/expected/ao_partial_scan.out
- src/test/isolation2/expected/bitmap_index_inspect.out
- src/test/isolation2/expected/brin_heap.out
- src/test/isolation2/expected/frozen_insert_crash.out
- src/test/isolation2/input/uao/brin.source
- src/test/isolation2/input/uao/brin_chain.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/brin.source
- src/test/isolation2/output/uao/brin_chain.source
- src/test/isolation2/sql/ao_partial_scan.sql
- src/test/isolation2/sql/bitmap_index_inspect.sql
- src/test/isolation2/sql/brin_heap.sql
- src/test/isolation2/sql/frozen_insert_crash.sql
- src/test/regress/expected/alter_extension.out
- src/test/regress/expected/brin_interface.out
- src/test/regress/expected/vacuum_gp.out
- src/test/regress/pg_regress.c
- src/test/regress/sql/alter_extension.sql
- src/test/regress/sql/brin_interface.sql
- src/test/regress/sql/vacuum_gp.sql
pageinspect is necessary for many tests, so load it up front like we do
for gp_inject_fault and gp_toolkit. This means we can remain all CREATE
EXTENSION/DROP EXTENSION commands for pageinspect (barring the
alter_extension test).
This also enables us to parallelize the brin_chain tests, since we no
longer have to worry about concurrent drops of pageinspect. This shaves
off 4-5mins off of total ICW runtime.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/pageinspect_icw
> Load pageinspect implicitly for regress/isolation2

- gpMgmt/bin/gpexpand
- gpMgmt/bin/gpmemwatcher
- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/package.py
- gpMgmt/bin/gpssh-exkeys
Fixes https://github.com/greenplum-db/gpdb/issues/14744
Problem :
rsync skips file if it has identical sizes and modification times on the source and destination hosts, this makes gpsync behave different than gpscp. gpscp was replaced with gpsync (which uses rsync to copy files) but we don't want to change the behaviour.
Solution :
To make gpsync behave the same as gpscp, -I or --ignore-times and -W or --whole-file option can be used with rsync. It will copy the files that have identical size and modification time on the source and destination hosts. -I or --ignore-times is used to make sure files that match in size and mod-time are not skipped. -W or --whole-file flag used to copy files completely without using delta-transfer algorithm.
Implementation :
Added the -I or --ignore-times and …
> [7x]: Added --ignore-times and --whole-file option in rsync

- contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
- src/backend/gpopt/translate/CTranslatorUtils.cpp
- src/test/regress/expected/bfv_olap.out
- src/test/regress/expected/bfv_olap_optimizer.out
- src/test/regress/expected/groupingsets_optimizer.out
- src/test/regress/sql/bfv_olap.sql
Issue:
Performance drop observed with TPCDS-DS query-167
RCA:
When a query involves a ROLLUP, we observed that the order of
children under the append operator has changed. The first child of the append operator has a distribution of "SINGLETON," which results in all inner children inheriting the same distribution. As a consequence, Gather Motion operations are performed for all the aggregators under the Append operator, leading to increased execution time for the append operator in TPC-DS query 167.
FIX:
The PR addresses the issue by fixing the order of children while
creating grouping sets for the rollup during the query to DXL translation.
Setup:
create table foo (a int, b int, c int);
insert into foo select i, i, i from generate_series(1, 10)i; analyze foo;
select a, b, sum(c) from foo …
> Correct the child order when creating grouping sets for the rollup

- src/test/regress/greenplum_schedule
The results of `cluster_gp` are getting affected by autovacuum, which are causing failures.
Fix the flaky test by ensuring that the test runs while autovacuum is off.
> Fix flaky test `cluster_gp`

- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This PR documents the changes in `gppkg` utility introduced for GP 7 beta 5.
Test site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-gppkg/greenplum-database/utility_guide-ref-gppkg.html
> Docs gppkg

- src/backend/access/brin/README
- src/backend/access/brin/brin.c
- src/backend/access/brin/brin_tuple.c
- src/include/access/brin_tuple.h
- src/test/isolation2/input/uao/brin.source
- src/test/isolation2/output/uao/brin.source
For BRIN indexes on AO/CO tables, we can exploit a property of exhausted
logical block ranges (fast sequence numbers used up) belonging to a
segment that undergoes VACUUM (i.e. a segment awaiting drop). The
property is that these ranges will never be reused for future inserts.
This is because we don't reset gp_fastsequence when we VACUUM AO/CO
tables and gp_fastsequence is always increasing.
So, these ranges are effectively dead and can thus be marked as empty.
Doing so brings about a couple of benefits:
(1) These dead ranges will never result in false positives during scans
which match the ranges' summary info.
(2) Cycles will not be spent trying to summarize them, as empty ranges
are not summarized. This saves cycles for both the summarization call at
the end of VACUUM and for all …
> brin ao/co: Mark dead ranges as empty on VACUUM

- src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
These assertions were added to ensure that statistical operations on histograms in Orca are as expected. While they're valid assertions, fixing them simply isn't a super high priority at this time. Keeping them included ends up hiding more potentially serious bugs and makes debugging issues more cumbersome. Instead, comment these assertions out for now until we have some time to properly dig into the issue.
> Disable some Orca histogram asserts

- concourse/scripts/combine_cli_coverage.bash
in job: combine_cli_coverage job
Same with prevous commit: bd2c707df2e3fe40025beacd7dd7129a43effe30
[GPR-1433]
> [Pipeline] Fix gsutil command failed due to wrong dependency location

- gpdb-doc/markdown/utility_guide/ref/gpsupport-gp_log_collector.html.md
Also, here is the text of the GPDB 7 Beta.5 release note:
"`gpsupport gp_log_collector` can now filter logs based on timestamps at the level of hours and minutes (YYYY-MM-DD-HH:MM); previously, filter granularity was limited to days (YYYY-MM-DD)."
> DOCS: Add example for collecting logs with timestamps that specify hour and minute

- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
Currently, QD will not attach a resource group if QD is in bypass mode when it's already 
running in bypass mode, things will go wrong if we change role, just like:
```
CREATE RESOURCE GROUP rg_test_group WITH (cpu_max_percent=10, concurrency=5);
CREATE ROLE rg_test_role RESOURCE GROUP rg_test_group;
SET ROLE rg_test_role;
CREATE TABLE rg_test_group_table(a int);
-- Since rg_test_group_table is empty, the total cost of this SQL will be less than min_cost,
-- so it'll run in bypass mode
SELECT count(*) FROM rg_test_group_table;
SELECT is_session_in_group(pg_backend_pid(), 'rg_test_group');
RESET ROLE;
-- Still running in bypass mode, but the role is not rg_test_role
SELECT count(*) FROM rg_test_group_table;
SELECT is_session_in_group(pg_backend_pid(), 'admin_group');
DROP TABLE …
```
> Attach a resource group even QD is in bypass mode

- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Closes:#15952
Cherry-pick: #15981
Differential recovery left the replication slot in the inactive state, and because of that wal keeps accumulating on the primary. 
1. check if the database is up and running.
2. make any of the mirrors down, and wait for the configuration to update.
3. run differential recovery, this will make the down mirror up and start the segment.
4. check the pg_replication_slot table, where you will find the slot is in an inactive state, and active_pid column will be empty.
****Expectation**: post recovery the replication_slot should be active.**
Firstly check the pg_replication_slots table post differential recovery.
```
slot_name           | plugin | slot_type | datoid | database | temporary | active | active_pid | xmin | catalog_xmin | restart_lsn | …
```
> [6X] Fix replication slot inactive issue post differential recovery. (#15981)

- src/backend/optimizer/plan/createplan.c
- src/test/regress/input/aocs.source
- src/test/regress/output/aocs.source
See #15904, when generating scan plan in `create_scan_plan()`, the upstream code prefer to generate a tlist containing all Vars in order. For the row-based storage such as heap, it looks fine, but for column-based storage, it would result into unnecessary overhead and impact performance. 
This commit makes specific optimization for Greenplum, and let the tlist apply to the projection to avoid unnecessory column fetches from the appened-only column storage, to improve the performance.
Applying this patch gains much performance improvement on TPC-DS & TPC-H benchmarks. The reason is for column-based storage, it would avoid loading unnecessary columns into the disk during the Scan.
Upstream discussion: https://www.postgresql.org/message-id/flat/SN6PR05MB51999AC1D043689076188370C400A%40SN6PR05 …
> Disuse physical list for legacy planner Scans

- src/include/cdb/cdbaocsam.h
The FIXME reads quite confusing at first: it is placed between two things that are unrelated to bitmap. It is not clear what exactly is the "new method" that is supposed to have another MERGE_FIXME, and what exactly should we store in the "new struct".
When looking at the original commit that introduced it: fb7f49c1a20b61f079614dd44aad1153ff723e72, it becomes somewhat clearer that the original purpose of this FIXME might have been actually addressed by the same commit. The "new method" it talks about is the scan_begin_extractcolumns_bm() handler, which had a MERGE_FIXME at that time: https://github.com/greenplum-db/gpdb/commit/fb7f49c1a20b61f079614dd44aad1153ff723e72#diff-bfe700fba9b92e12fb7e0d77101d4bef63591973e55662f6fffdf66e2333d919R216-R219. And the "new struct" is the …
> Remove a FIXME in cdbaocsam.h

- gpMgmt/bin/gppylib/commands/base.py
- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/sbin/recovery_base.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Currently, gprecoverseg lacks the ability to handle interrupts. When the main gprecoverseg process is terminated, it leaves behind orphaned `gpsegrecovery, pg_rewind, or pg_basebackup` processes that the user would have to manually terminate.
This change aims to add signal handling capabilities to the gprecoverseg code so that we can gracefully terminate the gprecoverseg process by using appropriate signal handlers and performing necessary cleanup actions, instead of abruptly terminating only the main process.
A new option `start_new_session` is added to the `Command` class, which is used by the `gprecoverseg` to spawn `gpsegrecovery` in separate sessions. This is to make sure that sending a termination signal to `gprecoverseg` does not affect the `gpsegrecovery` process (refer to …
> gprecoverseg: Add ability to handle interrupts

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR adds the following undocumented autovacuum gucs:
autovacuum_max_workers
autovacuum_analyze_threshold
autovacuum_analyze_scale_factor
autovacuum_multixact_freeze_max_age
autovacuum_vacuum_cost_limit
> Docs: added more autovacuum gucs

- concourse/scripts/ic_gpdb_resgroup_v2.bash
Because some OS could not contain "io" in `cgroup.subtree_control` by
default, so add it to fix the broken CI
> Add "+io" to cgroup.subtree_control

- src/backend/cdb/cdbgroup.c
- src/test/regress/expected/functional_deps.out
- src/test/regress/sql/functional_deps.sql
Previously we just support only one column in the primary key groupby scenario by function `has_functional_dependency`. But for multiple primary keys, anything goes wrong.
```
create table t1(a int, b int, c int, d int, primary(a,b));
select a,b,sum(c),d from t1 group by a,b;
```
So we removed `has_functional_dependency` which was used to check the single column.
Instead of it, we apply the function  `check_functional_grouping` from upstream to check
multiple primary keys.
> [6X] Fix wrong result of multi-stage aggregate plan with multiple primary key

- src/backend/utils/adt/gp_dump_oids.c
- src/test/regress/expected/gp_dump_query_oids.out
- src/test/regress/expected/minirepro.out
- src/test/regress/sql/gp_dump_query_oids.sql
- src/test/regress/sql/minirepro.sql
When a table has an explicitly created sequence, the sequence will be ignored by pg_dump if it's not owned by the table.
In pg_dump, implicitly created sequence like SERIAL and GENERATED AS IDENTITY, the referenced sequence will be dumped if the owning table is dumped. But for explicitly created sequence, we should specify sequence's oid if we want to dump the sequence object when the sequence is not owned by table.
Collect oids of sequence which be referenced by table columns in gp_dump_query_oids.
> [6X] minirepro: collect using sequence

- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/test/isolation2/expected/resgroup/resgroup_cpu_max_percent.out
- src/test/isolation2/expected/resgroup/resgroup_cpuset.out
- src/test/isolation2/expected/resgroup/resgroup_syntax.out
- src/test/isolation2/sql/resgroup/resgroup_cpu_max_percent.sql
- src/test/isolation2/sql/resgroup/resgroup_cpuset.sql
- src/test/isolation2/sql/resgroup/resgroup_syntax.sql
The test cases in `resgroup_cpu_max_percent` is designed for the value of
`gp_resource_group_cpu_limit` equals 0.9, but I set it to 1 in #15699.
Because the test results allow for a 10% deviation, it is possible to pass the 
test incorrectly in most cases.
> change gp_resource_group_cpu_limit to the default value after test

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
This is a cherry pick of https://github.com/greenplum-db/gpdb/pull/15962
Problem : Running gpcheckcat FK check taking a lot of time to complete, One of the workarounds to fix this is to Pull the FK query and run it separately in psql using the GUC disable_cost='1e20' at session level. It help in making the query run faster but its not acceptable solution.So need to set the GUC at session level.
Solution : Added a new option [-x] in gpcheckcat that will provide support for PGOPTIONS to pass multiple session GUCs [such as disable_costs, gp_role] to set the parameter.
Implementation : Added a new option -x which is used to pass the multiple session GUCs to set the parameter. This is helpful when wanting to run certain tests in gpcheckcat with session level parameters. User can use the -x …
> [6x] gpcheckcat: Add new option -x to set session level GUCs

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/sql/alter_table_set_am.sql
When ALTERing the access method or reloptions of tables in a hybrid
partition hierarchy containing foreign tables, we used to ERROR out when
a foreign table was encountered (as these operations don't make sense
for foreign tables).
Based on feedback, we want to skip such tables during AT recursion and
apply the change to all other tables. Such tables are now skipped with a
NOTICE to the user. For consistency, attempting these operations on
standalone/leaf foreign tables will also result in the same NOTICE:
NOTICE:  skipping foreign table "%s" for ALTER operation
If there are multiple foreign tables in a partition hierarchy, the
NOTICE will get printed once for each such table. Although that may be
verbose, that feels better than a silent no-op.
Dev-pipeline: …
> AT-SET-AM/AT-SET-RELOPTIONS: Skip foreign tables

- gpdb-doc/markdown/utility_guide/ref/gpcheckcat.html.md
Documents https://github.com/greenplum-db/gpdb/pull/15962 which adds a new option `-x` to `gpcheckcat`.
> Docs: new option -x for gpcheckcat

- src/test/isolation2/expected/vacuum_progress_column.out
- src/test/isolation2/expected/vacuum_progress_row.out
- src/test/isolation2/sql/vacuum_progress_column.sql
- src/test/isolation2/sql/vacuum_progress_row.sql
If injecting a fault to all segments but waiting for only one segment
fault trigger, it could lead to flakiness because the moment of that
fault trigger is variable, resulting in different summary results of
segments in vacuum progress report.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/hw-7X-vac-prog-flaky
> Fix flakiness due to waiting for different number of fault triggers

- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This PR removes the gppkg upgrade option from the reference page.
> Docs: removed the gppkg upgrade subcommand

- src/backend/replication/slot.c
- src/include/replication/walsender_private.h
67d4843a149 introduced WalSndError as a means for having a persistent
error state, exposed through the sync_error field in
gp_stat_replication. This state was meant to signal
walsender<->walreceiver connection failures, even when the walsender
died (the traditional upstream mechanism depends on the walsender being
alive to report issues).
We should set this state when the replication slot is invalidated as
well. This was done correctly in 6X_STABLE commit: ea69506b407.
This would prevent flakes in the associated max_slot_wal_keep_size test
such as:
```diff
--- expected/segwalrep/max_slot_wal_keep_size.out
+++ results/segwalrep/max_slot_wal_keep_size.out
@@ -289,7 +450,7 @@
1: SELECT sync_error FROM gp_stat_replication WHERE gp_segment_id = 0;
sync_error
------------
- walread
+ none
(1 …
```
> Flag persistent WalSndError on repslot invalidation

- src/backend/utils/error/elog.c
> Remove duplicated function declarations in elog.c

- gpMgmt/bin/analyzedb
- gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Problem: analyzedb reports many errors saying that "schema XXX does not exist",
because by the time the process starts analyzing the temp table, the session
with the temp tables is already gone.
Solution: skip temp schemas for analyzedb.
> analyzedb should be skipped on Temp tables

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
**Issue:**
gpcheckcat is reporting error  while running ‘missing_extraneous’ test on pg_description catalogue table
```
[~/workspace/gpdb6/gpAux/gpdemo/datadirs: {6X_STABLE} ?]$ gpcheckcat postgres
Truncated batch size to number of primaries: 4Connected as user 'sshirisha' to database 'postgres', port '6000', gpdb version '6.24'
-------------------------------------------------------------------
Batch size: 4
Performing test 'unique_index_violation'
Total runtime for test 'unique_index_violation': 0:00:02.08
Performing test 'duplicate'
Total runtime for test 'duplicate': 0:00:03.11
Performing test 'missing_extraneous'
Execution error: ERROR:  column "oid" does not exist
LINE 4:                 SELECT oid FROM pg_description
^
SELECT oid
FROM (
SELECT oid FROM pg_description
WHERE …
```
> Fix gpcheckcat error against pg_description

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InList.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/expected/create_index_optimizer.out
- src/test/regress/sql/bfv_index.sql
For older versions of GPDB(and PG) the executor supported ScalarArrayCmp
with BitmapIndexScans only. As part of the PG_92 merge (commit: 9e8da0f)
support was added to IndexScans as well but wasn't updated in ORCA. This
PR adds support in ORCA to consider IndexScan plans for Btree
indexes with indexquals on ScalarArrayOp.  Similar to planner for
multikey indexes, a ScalarArrayOp qual will only be considered as an index qual if the
predicate column is the first index key else will be added as a filter on top. This ensures we do not assume
scan results are ordered. (ref commit: 807a40c)
This PR also renames a bool to reflect what it is used for now.
New tests added for partitioned tables in addition to existing tests for non-partition tables.
> Enable ORCA to generate IndexScan plans with ScalarArrayOp quals

- src/backend/access/appendonly/appendonlyam.c
- src/backend/catalog/pg_appendonly.c
- src/include/catalog/pg_appendonly.h
After moving pg_appendonly tuples into relcache, it seems that we no longer need to incur function calls just for some memory copy/dereference. Change them to macros now.
Per discussion in https://github.com/greenplum-db/gpdb/pull/15027#discussion_r1120460866
> Change GetAppendOnlyEntryAuxOids/GetAppendOnlyEntry to macros

- src/test/regress/expected/resource_queue_stat.out
- src/test/regress/sql/resource_queue_stat.sql
When getting the number of `n_queries_exec` of a resource queue, we must wait more than PGSTAT_STAT_INTERVAL in current query, or we might can't acquire fresh resource queue stats. This is because `n_queries_exec` is updated at the end of the query, original `select pg_sleep(1)` can't ensure subsequent query get correct results.
> Fix flaky case resource_queue_stat

- src/test/regress/expected/resource_queue_stat.out
- src/test/regress/sql/resource_queue_stat.sql
This is a backport of main PR: https://github.com/greenplum-db/gpdb/pull/15967
When getting the number of n_queries_exec of a resource queue, we must wait more than PGSTAT_STAT_INTERVAL in current query, or we might not be able to aquire fresh resource queue stats.
Without this fix, we would get flakes like:
```diff
--- expected/resource_queue_stat.out
+++ results/resource_queue_stat.out
@@ -77,7 +77,7 @@
select queuename, n_queries_exec from pg_stat_resqueues where queuename = 'q';
queuename | n_queries_exec
-----------+----------------
- q         |              4
+ q         |              3
(1 row)
```
(cherry picked from commit f3cf4ae096ceb1435b13784cfeaf7155b8af2b3a)
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_fix_resource_queue_stat_flake
> [6X] Fix flaky case resource_queue_stat

- contrib/auto_explain/sql/bfv_preload_auto_explain.sql
- contrib/pgcrypto/sql/setup_fips.sql
Previously in ICW tests, some extensions including auto_explain and pgcrypto set GUC `shared_preload_libraries` regardless of its original value. This will impact other extensions who also need to include themselves into `shared_preload_libraries`.
To fix this issue, this patch changes the `gpconfig` command to
- Before running the test, append new library names to the end, rather than replace the whole value.
- After running the test, instead of removing the GUC setting, only the newly appended library is removed.
As a result, extensions required to be in `shared_preload_libraries` can work nicely together throughout the whole ICW tests.
> Append to shared_preload_libraries instead of replace

- src/test/regress/expected/interrupt_holdoff_count.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/interrupt_holdoff_count.sql
This commit fixes test, which was added at [commit](https://github.com/greenplum-db/gpdb/commit/50e66c76acf19d09ac7f0fc05cca01e014bb0ab8)
This test checks that error, which generated at critical place (where `InterruptHoldoffCount` is more than zero) leads to resetting counter `InterruptHoldoffCount` at QD. Operation, which generates created commit, is used for the test.
This operation:
1. Dispatches to segments and can lead to error on segments (as already done at the test).
2. Does not process interruptions while dispatching to the segments.
At first version of this test there was declare cursor. QD does not wait result of declare cursor, but on segments there is work, which ends with error. This error is processed when abort is called. At some cases abort is called before error is …
> Rewrite test interrupt_holdoff_count

- src/backend/fts/test/ftsmessagehandler_test.c
Test case test_HandleFtsWalRepPromoteMirror had undefined behavior. On
CI using Rocky9 non-asserts build this triggered a segfault against an
unrelated commit.
In the test ReplicationSlotCtl is already a pointer. And so referencing
it passes a pointer to a pointer to will_be_called_with_sideeffect().
But that is not what the method set_replication_slot() expects. That
leads to undefined behavior.
> Fix test test_HandleFtsWalRepPromoteMirror variable reference

- src/backend/access/external/external.c
- src/backend/commands/tablecmds.c
- src/backend/parser/gram.y
- src/test/regress/expected/partindex_test.out
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition1.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/expected/qp_orca_fallback.out
- src/test/regress/expected/qp_orca_fallback_optimizer.out
- src/test/regress/input/external_table.source
- src/test/regress/input/part_external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
- src/test/regress/output/gpcopy.source
- src/test/regress/output/part_external_table.source
- src/test/regress/output/part_external_table_optimizer.source
In 7X, external tables are essentially just one kind of foreign tables. Also, because EXCHANGE PARTITION is now just DETACH+ATTACH PARTITION, exchanging partition with an external table has the same behavior as attaching a foreign table in upstream.
Because of that, there were certain restrictions that got lost for exchanging external tables: (1) we cannot exchange a writable external table in; (2) we cannot exchange a readable external table in w/o "WITHOUT VALIDATION" clause.
For (1): we should bring that restriction back, because otherwise there would always be an error when scanning that partition (unless the query is written in a way that avoids scanning that particular partition). To disallow having a write-only external partition makes more sense. And, keeping existing behavior is …
> Add error/warning when exchanging/attach an external table

- src/test/regress/expected/alter_table_set_am.out
Missed addressing this in 03afdc5b5d3f5caefa09aca9556303fce9ead9c3 after a recent test case. Fixing now.
> Add a missing NOTICE log message in test alter_table_set_am

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
This is a backport of [https://github.com/greenplum-db/gpdb/pull/16130](https://github.com/greenplum-db/gpdb/pull/16130)
**Issue:**
gpcheckcat is reporting error  while running ‘missing_extraneous’ test on pg_description catalogue table
```
[~/workspace/gpdb6/gpAux/gpdemo/datadirs: {6X_STABLE} ?]$ gpcheckcat postgres
Truncated batch size to number of primaries: 4Connected as user 'sshirisha' to database 'postgres', port '6000', gpdb version '6.24'
-------------------------------------------------------------------
Batch size: 4
Performing test 'unique_index_violation'
Total runtime for test 'unique_index_violation': 0:00:02.08
Performing test 'duplicate'
Total runtime for test 'duplicate': 0:00:03.11
Performing test 'missing_extraneous'
Execution error: ERROR:  column "oid" does not exist …
```
> [6x Backport] Fix gpcheckcat error against pg_description 

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
If run `analyze_db` for any database, than for this database folder "db_analyze" is created. It may contain large volume of data. This catalog is useless for segments. If after it create new segment using `gpexpand`, than folder "db_analyze" will be copied to new segment. This folder is useless for new segment. Because of this exclude "db_analyze" is added to `PgBaseBackup`.
Steps to reproduce the problem:
1) Create demo cluster.
2) Run `analyzedb -d postgres -a`.
3) Create config file "expand.conf" for `gpexpand`:
```
sdw1|sdw1|36101|<PATH_TO_GPDB_SRC>/gpAux/gpdemo/datadirs/dbfast4|9|3|p
sdw1|sdw1|36102|<PATH_TO_GPDB_SRC>/gpAux/gpdemo/datadirs/dbfast_mirror4|10|3|m
```
4) Run `gpexpand -i expand.conf`.
5) Done.
> Add exclude of directory "db_analyze" to generate template to gpexpand

- src/test/regress/expected/privileges.out
- src/test/regress/expected/privileges_optimizer.out
- src/test/regress/sql/privileges.sql
We tried a couple other times to fix these flaky privileges tests that displayed different numbers of Orca fallback messages, but unfortunately the approach of discarding plans doesn't work for all cases. I think this has to do with not being able to discard the plan cache during the query. Instead, disable tracing the fallback for these queries. These are explain plans, so any plan changes will still be caught.
> Fix flaky privileges tests

- gpMgmt/bin/analyzedb
- gpMgmt/test/behave/mgmt_utils/analyzedb.feature
Problem: analyzedb reports many errors saying that "schema XXX does not exist", because by the time the process starts analyzing the temp table, the session with the temp tables is already gone.
Solution: skip the temporary schemas from being analyzed.
> [6x Backport] analyzedb should be skipped on Temp tables (#16095)

- src/backend/optimizer/util/pathnode.c
- src/backend/utils/misc/guc_gp.c
- src/include/nodes/relation.h
- src/include/utils/guc.h
- src/test/isolation2/expected/vacuum_full_recently_dead_tuple_due_to_distributed_snapshot.out
- src/test/regress/input/table_functions.source
- src/test/regress/output/table_functions.source
- src/test/regress/output/table_functions_optimizer.source
Use a GUC to block the new behavior so it will be less likely to affect other customers.
commit 5ad4db29600308504f569021cea159c6a01409b1
Author: Adam Lee <adlee@vmware.com>
Date:   Thu Jul 6 10:19:04 2023 +0800
5X: Don't create unique rowid paths if there is a table function scan (#15771)
> 5X: Convert disallow_unique_rowid_path to a GUC

- gpcontrib/gp_internal_tools/gp_resource_group.c
- gpdb-doc/dita/ref_guide/config_params/guc-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
- gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- src/backend/access/transam/xact.c
- src/backend/storage/ipc/procarray.c
- src/backend/storage/lmgr/proc.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/resgroup.c
- src/include/storage/proc.h
- src/include/storage/procarray.h
- src/include/utils/resgroup.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/input/resgroup/resgroup_move_query.source
- src/test/isolation2/output/resgroup/resgroup_move_query.source
This is the copy of #13481 
-----
The pg_resgroup_move_query() function implemented in 51ee26b has several disadvantages:
1) Slot leaking. The slot acquired in initiator process doesn't free if target process isn't alive, didn't receive a signal, or even received, but at the time it was in idle state.
2) Race condition between UnassignResGroup() called at the end of transaction (or honestly any other code) and handler called immediately after USR1 signal.
3) Not working entrydb process moving. Previously, the USR1 signal was sent to only one process, target or entrydb. Entrydb moving was never tested properly.
Improvements added to solve the first problem:
1) Feedback from target process to initiator. Target process can set initiator's latch to quickly interrupt pg_resgroup_move_query() …
> pg_resgroup_move_query() improvements

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_EXTERNAL_TABLE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/DROP_EXTERNAL_TABLE.html.md
ASSUMPTION:  the syntax, etc of these commands is unchanged between greenplum 6 and 7.
a few minor edits for issues i noticed as i was reviewing these pages.
NOT IN THIS PR:   updates related to external tables really being foreign tables under the hood will be submitted in a separate PR, which may possibly modify these pages.
> docs - minor edits to EXTERNAL TABLE sql ref pages

- gpdb-doc/markdown/utility_guide/ref/gpcheckcat.html.md
This PR ports https://github.com/greenplum-db/gpdb/pull/16111 to 6X_STABLE.
> Docs: Added gprecoverseg -x option for 6X_STABLE

- src/backend/utils/adt/selfuncs.c
- src/include/access/appendonlytid.h
brin ao/co: Correctly derive numRanges for costing
For AO/CO tables, we can't use baserel->pages to figure out the number
of ranges present in the baserel. This is because relpages for AO/CO
tables is based on physical bytes, whereas ranges are based on the
logical heap block numbers present.
Consider the following example:
```sql
CREATE TABLE ao(i int) USING ao_row;
INSERT INTO ao select 1 from generate_series(1, 1000000);
ANALYZE ao;
-- See how far apart relpages and num_logical_heap_blks are.
SELECT relpages, reltuples from pg_class where relname = 'ao';
relpages | reltuples
----------+-----------
306 |     1e+06
(1 row)
SELECT count(distinct(right(split_part(ctid::text, ',', 1), -1)))
AS num_logical_heap_blks FROM ao;
num_logical_heap_blks
-----------------------
31
(1 row)
```
During …
> brin ao/co: Correctly derive numRanges for costing

- src/backend/access/external/url_curl.c
> Fix compilation for url_curl.c with libcurl version lower than 7.19

- src/bin/gpfdist/gpfdist.c
Current gpfdist will update the corresponding sequence number when it responses a HTTP request successfully. However, the network may be unstable when gpfdist processes a HTTP request. In rare conditions, a connection could be aborted when gpfdist finishes receiving and writing data, which would lead to a data-sending retry.
Since gpfdist wouldn't update the sequence number despite finishing data writing when the response failed, data will be written again when gpdb retries sending the same data.
The PR is to handle the rare case. Gpfdist updates the sequence number when data writing ends or the request is OPEN_SEQ. The adaptation will avoid data overwriting.
> Fix gpfdist7 data overwriting

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_table_gp.out
- src/test/regress/sql/alter_table_gp.sql
During ALTER COLUMN TYPE of an indexed column, we check if the index can be re-used. If so, we preserve the existing relfilenode instead of removing it. However, in GPDB the preservation is done on QD and the relfilenode is packaged in another ALTER TABLE subcommand to be handled later. So QE might make its index to have QD's relfilenode, which could cause data missing/corruption errors.
The fix is for QE to go through the generated index command, and replace QD's relfilenode with its own.
It's not an issue for 6X as we don't allow altering type of indexed column in 6X.
P.S. this should help resolve two flaky tests `vacuum_gp` and `gp_check_files` for diff like this:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/vacuum_gp.out	2023-08-07 17:31:36.674940540 +0000
+++ …
```
> Re-used index after ALTER COLUMN TYPE shouldn't change relfilenode

- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_wait_time.out
- src/test/isolation2/isolation2_resgroup_v1_schedule
- src/test/isolation2/isolation2_resgroup_v2_schedule
- src/test/isolation2/sql/resgroup/resgroup_wait_time.sql
DEV CI https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/zlv_test_rg_wait_time
> Fix bug: resgroup total wait during always 0.

- gpdb-doc/markdown/admin_guide/ddl/ddl-index.html.md
address https://github.com/greenplum-db/gpdb/pull/15763#issuecomment-1671962152.
this info should also end up in release notes and/or upgrade guide.
> docs - index-only scan avail only for tables created in gp7

- src/backend/parser/parse_coerce.c
- src/test/regress/expected/qp_dml_joins.out
- src/test/regress/expected/qp_dml_joins_optimizer.out
- src/test/regress/sql/qp_dml_joins.sql
An UNKNOWN var refered to the targetlist of a join's subquery in the insert statement can't coerce to a proper type lead to error. When coerce qury targetlist's tpe to the insert column's type, the fixed unknown var can be coerce to other type which isn't equal to target type. Do unknownout(Var) for a non-UNKNOWN is dangerous.
When transforms a Select Statement, Untyped Const or Param nodes in a subquery in the FROM clause might have been assigned proper types when we transformed the WHERE clause. So after that, when coerce UNKNOWN var in targetlist to the assigned type, don't need to specify target type. Now we simply pass UNKNOWNOID to the tartgettypeId, then if the var refs to a join, it will still keep unchanged.
If the unknown var is refered to a join, the joinvar must refs to a leaf …
> (6x) fix unknown var coerce

- gpMgmt/bin/gpload.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_preload.py
- gpMgmt/bin/gpload_test/gpload2/query205.ans
- gpMgmt/bin/gpload_test/gpload2/query233.ans
- gpMgmt/bin/gpload_test/gpload2/query259.ans
- gpMgmt/bin/gpload_test/gpload2/query260.ans
- gpMgmt/bin/gpload_test/gpload2/query261.ans
- gpMgmt/bin/gpload_test/gpload2/query609.ans
- gpMgmt/bin/gpload_test/gpload2/query665.ans
- gpMgmt/bin/gpload_test/gpload2/query76.ans
- gpMgmt/bin/gpload_test/gpload2/query77.ans
gpload usually starts a transaction for preload, before sql, gpload sql, and after sql. But in insert mode, no transaction is started. So if gpload insert fails, the sqls in preload, before and after will still be executed.
In this pr, we will start a transaction for insert mode to avoid this behavior.
* The behavior of the insert mode will change: when the insert fails and rollback, the [preload](https://docs.vmware.com/en/VMware-Greenplum/5/greenplum-database/utility_guide-admin_utilities-gpload.html#:~:text=and%20so%20on.-,PRELOAD,-Optional.%20Specifies%20operations) and [SQL](https://docs.vmware.com/en/VMware-Greenplum/5/greenplum-database/utility_guide-admin_utilities-gpload.html#:~:text=a%20warning%20message.-,SQL,-Optional.%20Defines%20SQL) In YAML file will also rollback.
> Fix gpload insert mode not included in transaction 

- gpMgmt/bin/gpload.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_base.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_preload.py
- gpMgmt/bin/gpload_test/gpload2/init_file
- gpMgmt/bin/gpload_test/gpload2/query609.ans
- gpMgmt/bin/gpload_test/gpload2/query665.ans
- gpMgmt/bin/gppylib/test/unit/test_unit_gpload.py
This pr backport [pr](https://github.com/greenplum-db/gpdb/pull/16146) in 6X_STABLE
Gpload usually starts a transaction for preload, before sql, gpload sql, and after sql. But in insert mode, no transaction is started. So if gpload insert fails, the sqls in preload, before and after will still be executed.
In this pr, we will start a transaction for insert mode to avoid this behavior.
* The behavior of the insert mode will change: when the insert fails and rollback, the [preload](https://docs.vmware.com/en/VMware-Greenplum/5/greenplum-database/utility_guide-admin_utilities-gpload.html#:~:text=and%20so%20on.-,PRELOAD,-Optional.%20Specifies%20operations) and [SQL](https://docs.vmware.com/en/VMware-Greenplum/5/greenplum-database/utility_guide-admin_utilities-gpload.html#:~:text=a%20warning%20 …
> fix gpload insert mode not included in transaction

- src/backend/gpopt/CGPOptimizer.cpp
- src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
- src/backend/gporca/libgpopt/include/gpopt/exception.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformFactory.h
- src/backend/gporca/libgpopt/src/exception.cpp
- src/backend/gporca/libgpopt/src/init.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
- src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
- src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
- src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
- src/backend/gporca/libgpos/include/gpos/task/CWorkerPoolManager.h
- src/backend/gporca/libgpos/src/_api.cpp
- src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
- src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
- src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
- src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
- src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
- src/backend/gporca/libnaucrates/include/naucrates/exception.h
- src/backend/gporca/libnaucrates/src/exception.cpp
- src/backend/gporca/libnaucrates/src/init.cpp
- src/backend/gporca/server/src/startup/main.cpp
- src/include/gpopt/utils/CMemoryPoolPallocManager.h
When initializing ORCA mixed a C approach (returning error codes and then checking them) and a C++ approach (throwing exceptions and then catching them). This mixing led to errors. For example, in case of low memory or any other exception, the CWorkerPoolManager::Init function did not return GPOS_OK, and then the gpos_init function called
the CMemoryPoolManager::GetMemoryPoolMgr()->Shutdown function, which reset CMemoryPoolManager::m_memory_pool_mgr. In this case, all the exceptions that arose were not rethrown, so the execution continued, and the following gpdxl_init function was called, in which the CAutoMemoryPool class was initialized. In the constructor of this class, the static method CMemoryPoolManager::GetMemoryPoolMgr returned NULL, because we nullified m_memory_pool_mgr up the …
> [7X] ORCA initialization refactoring

- contrib/postgres_fdw/expected/gp2pg_postgres_fdw.out
- src/backend/optimizer/path/costsize.c
- src/test/regress/expected/bfv_olap.out
- src/test/regress/expected/gp_covering_index.out
- src/test/regress/expected/join.out
- src/test/regress/expected/partition_join.out
- src/test/regress/expected/qp_join_union_all.out
- src/test/regress/expected/rpt.out
- src/test/regress/expected/select.out
- src/test/regress/expected/subselect_gp_indexes.out
- src/test/regress/output/uao_dml/ao_covering_index.source
Since c5f6dbbe84c, we have changed planner's cost model to operate on
rows/tuples/pages scaled down by the number of segments, when
considering base tables.
However, we didn't do the same thing for the index's tuples/pages during
index costing, which we should. That way, we won't overcharge for index
access.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/cost_index
> planner: Adjust index scan path by numsegments

- src/backend/access/index/amapi.c
- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/include/access/amapi.h
- src/include/gpopt/gpdbwrappers.h
When querying a relation with an `ivfflat` index from pgvector, Orca won't currently generate this index alternative. This will take a bit of work to support in Orca for a few reasons: generating index scans for this particular plan shape, creating the correct checks to ensure we generate a valid index plan, and proper costing for ivfflat indexes.
For now, fall back to planner to ensure users can still generate plans with index scans. Note that Orca will not fall back if no index is present--Orca can generate those plans without any issues.
No test is included since pgvector isn't part of this repo. Test case:
```
CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3)); 
INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]'); 
CREATE INDEX ON items USING ivfflat …
```
> Fall back to planner for queries on relations with pgvector index

- contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
- src/test/regress/expected/select_optimizer.out
With the planner cost model changes introduced in 167a67f7f82, two ORCA
answer files were missed. ORCA falls back to planner in these files, and
a similar plan diff needs to be incorporated.
> Update ORCA ans files for index costing change

- src/backend/utils/mmgr/generation.c
- src/backend/utils/mmgr/slab.c
We need to call gp_malloc|free() for the newly added MemoryContext types
instead of malloc|free(), so that we can get the VMEM reservation etc.
This was missed during the 12 merge.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/use_gp_malloc
> Make slabs and generations use gp_malloc|free

- gpMgmt/bin/gppylib/test/unit/test_unit_gpload.py
Gpload insert mode was included in one transaction in this [pr](https://github.com/greenplum-db/gpdb/pull/16146).
So in the unit test, insert mode will expect a begin and commit. 
Gpload unit test has passed in my local environment.
> Fix gpload unit test fail

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InList.mdp
- src/backend/gporca/libgpopt/include/gpopt/operators/CPredicateUtils.h
- src/backend/gporca/libgpopt/src/operators/CPredicateUtils.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/expected/create_index_optimizer.out
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/bfv_index.sql
- src/test/regress/sql/gporca.sql
For older versions of GPDB(and PG) the executor supported ScalarArrayCmp with BitmapIndexScans only. As part of the PG 92 merge (commit: 9e8da0f) support was added to IndexScans aswell but wasn't updated in ORCA. This commit adds support in ORCA to consider IndexScan plans for Btree indexes with indexquals on ScalarArrayOp.  Similar to planner for multikey indexes, a scalararrayop qual will only be considered as an index qual if the predicate column is the first index key else it will be added as a filter on top. This ensures we do not assume scan results are ordered. (ref commit: 807a40c) This commit also renames the boolean flag and pass it further down in the function call.
(backport of PR https://github.com/greenplum-db/gpdb/pull/16055)
Note: the test in gporca.sql for testing …
> [6X Backport]Enable ORCA to generate IndexScan plans with ScalarArrayOp quals

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/15535.  default value is off.
question:  will we add this guc to greenplum 6?
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gporcacfg1/greenplum-database/GUID-ref_guide-config_params-guc-list.html#optimizer_enable_push_join_below_union_all
> docs - add optimizer_enable_push_join_below_union_all to guc ref

- gpdb-doc/markdown/ref_guide/system_catalogs/gp_expansion_tables.html.md
docs for https://github.com/greenplum-db/gpdb/pull/14768 (main) and https://github.com/greenplum-db/gpdb/pull/14769 (6X_STABLE).
will backport to 6X docs.
> docs - table_oid is first col of gpexpand.status_detail tbl

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
the exhaustive2 option was missing.  and the default is exhaustive2.
i pulled the descriptions of exhaustive and exhaustive2 from the greenplum 6 docs.
> docs - correct the optimizer_join_order guc ref info

- concourse/scripts/compile_gpdb.bash
rsync is required dependency for gpdb6 server, also rsync used in multiple
gpManagement tools like gpcheckperf, rsync on rocky9/oel9/rhel9 happens 
to not work with our built zstd 1.3.7, error message:
/bin/rsync: undefined symbol: ZSTD_compressStream2
So we decided not to vendor our built zstd 1.3.7, but use system provided
zstd on  rocky9/oel9/rhel9 platform.
[GPR-1485]
> [Releng][6X] Unvendor libzstd for gpdb6 on rocky9/oel9/rhel9

- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/postgres_fdw.c
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
- src/backend/optimizer/plan/planner.c
We consider such scenario -- foreign table f_tbl is distributed randomly across multiple remote postgres server.
```
CREATE EXTENSION postgres_fdw;
CREATE SERVER multi_pg_servers
FOREIGN DATA WRAPPER postgres_fdw
OPTIONS (mpp_execute 'all segments', num_segments '4', multi_hosts '127.0.0.1 127.0.0.1 127.0.0.1 127.0.0.1', multi_ports '5432 5555 6666 7777', dbname 'postgres');
CREATE USER MAPPING FOR gpadmin 
SERVER multi_pg_servers OPTIONS (user 'postgres');
CREATE FOREIGN TABLE f_tbl(a int, b int) 
SERVER multi_pg_servers
OPTIONS(table_name 'demo_local_tbl');
```
- We set option `mpp_execute` to `all segments` for server `multi_pg_servers`. So when select something from postgres_fdw foreign table, the scan will be executed in a distributed way.
- The number of executors is controlled by …
> Consider LIMIT pushdown when there are multiple remote postgres servers for postgres_fdw.

- src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
- src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
- src/test/regress/expected/bfv_joins.out
- src/test/regress/expected/bfv_joins_optimizer.out
- src/test/regress/sql/bfv_joins.sql
When deriving stats in Orca for CTEs, we need to remap the statistics so that the CTE consumer uses the statistics of the CTE producer. This involves remapping the colrefs of associated statistics objects. While we did this for histograms and widths, we didn't do this for attnos, which then caused a crash in `ApplyCorrelatedStatsToScaleFactorFilterCalculation()` as it wasn't able to find the correct colref in the map.
Note that in the test case the error is expected (and Orca actually falls back), but it shouldn't cause a crash. The behavior should be the same both with and without extended statistics.
Fixes #15462
> Fix Orca crash due to improper colref mapping with CTEs

- src/test/fsync/expected/bgwriter_checkpoint.out
- src/test/fsync/sql/bgwriter_checkpoint.sql
- src/test/isolation2/expected/disable_autovacuum.out
- src/test/isolation2/expected/enable_autovacuum.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/sql/disable_autovacuum.sql
- src/test/isolation2/sql/enable_autovacuum.sql
- src/test/isolation2/sql/setup.sql
- src/test/regress/expected/disable_autovacuum.out
- src/test/regress/expected/enable_autovacuum.out
- src/test/regress/expected/vacuum_ao_aux_only.out
- src/test/regress/sql/disable_autovacuum.sql
- src/test/regress/sql/enable_autovacuum.sql
- src/test/regress/sql/vacuum_ao_aux_only.sql
We are encouraging the use of gpconfig/gpstop -u to toggle
autovacuum on/off. This is preferred over ALTER SYSTEM because the ALTER
doesn't make the changes on the mirrors. If there is a failover in the
test suite, some segments will have out of sync autovacuum settings.
Also, we want to ensure the autovacuum launchers are correctly
started/stopped after the gpstop -u, so busy wait for up to 2min in the
test.
Remove ALTER SYSTEM set autovacuum commands in vacuum_ao_aux_only test.
This test is run in the part of the schedule with autovacuum disabled.
> Confirm AV launcher state in {enable,disable}_autovacuum tests

- src/test/unit/mock/gpopt_mock.c
When running cmockery, I was hitting some compilation issues. This commit fixes those problems.
error: incompatible pointer to integer conversion returning 'void *'from
a function with result type 'Datum' (aka 'unsigned long') [-Wint-conversion]
return NULL;
error: parameter 'PG_FUNCTION_ARGS' was not declared, defaults to 'int';
ISO C99 and later do not support implicit int [-Wimplicit-int]
EnableXform(PG_FUNCTION_ARGS)
> Fix compilation error

- src/test/isolation2/input/resgroup/resgroup_views.source
- src/test/isolation2/output/resgroup/resgroup_views.source
Make test case 'resgroup_views' environmental independent.
> Fix test case resgroup_views

- src/backend/cdb/cdbvars.c
- src/backend/tcop/postgres.c
- src/backend/utils/misc/guc.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
map_old_guc_names facility exist to have alias for old GUC names to new ones. Hence best to use that facility instead of hand roll gp_session_role as alias to gp_role.
Doing this also eliminates having the problem fixed via commit 8d52dad.
> Make gp_session_role alias of gp_role using map_old_guc_names

- src/test/regress/expected/select.out
- src/test/regress/expected/select_optimizer.out
- src/test/regress/sql/select.sql
Since 167a67f and b43316b, the following query has been flaking in CI,
alternating between the following plans (showed w/ costs on):
```
explain
select unique1, unique2 from onek2
where (unique2 = 11 or unique1 = 0) and stringu1 < 'B';
QUERY PLAN
----------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=8.29..12.32 rows=1 width=8)
->  Bitmap Heap Scan on onek2  (cost=8.29..12.30 rows=1 width=8)
Recheck Cond: (((unique2 = 11) AND (stringu1 < 'B'::name)) OR (unique1 = 0))
Filter: (stringu1 < 'B'::name)
->  BitmapOr  (cost=8.29..8.29 rows=1 width=0)
->  Bitmap Index Scan on onek2_u2_prtl  (cost=0.00..4.14 rows=1 width=0)
Index Cond: (unique2 = 11)
->  Bitmap Index Scan on onek2_u1_prtl  (cost=0.00..4.14 rows=1 …
```
> Fix flaky plan diffs for select.sql

- src/backend/access/external/url_curl.c
- src/bin/gpfdist/gpfdist.c
- src/bin/gpfdist/regress/.gitignore
- src/bin/gpfdist/regress/Makefile
- src/bin/gpfdist/regress/change_cert.bash
- src/bin/gpfdist/regress/change_client_cert.bash
- src/bin/gpfdist/regress/init_file
- src/bin/gpfdist/regress/input/gpfdist_ssl.source
- src/bin/gpfdist/regress/input/gpfdists_multiCA.source
- src/bin/gpfdist/regress/output/gpfdist_ssl.source
To simplify the ssl authentication of `gpfdist`, we provide one more configuration option to `gpfdist` and changed the gpdb side SSL identity authentication behavior when verify_gpfdist_cert=off. 
The new command flag is `ssl_verify_peer`. If the flag is 'on', `gpfdist` will be forced to check the identity of clients, and  CA certification file (root.crt) is necessary to be laid in the SSL certification directory. 
If the flag is 'off', even the GUC `verify_gpfdists_cert=on`, `gpfdist` will not check the identity of clients, and it doesn't matter whether the CA certification file exists on the gpfdist side.  And SSL certificate files and SSL private key files on the gpdb segments' side are no longer necessary. This greatly simplifies the configuration burden when using the `gpfdists` …
> Add an command option for gpfdist to disable client ssl identity verification.

- src/backend/cdb/dispatcher/test/Makefile
- src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
- src/backend/cdb/dispatcher/test/gpsegconfig_dump
- src/interfaces/libpq/fe-connect.c
- src/interfaces/libpq/fe-misc.c
QD sends ready to execute plan to QE as an array of bytes named as queryText (see buildGpQueryString function for details). This message may be large enough in case of complex multi-node plan. This message is common for any process of any slice on QEs. To avoid duplicating this message for each of hundreds and thousands connection for the query, gpdb temporary replace malloc'ed output connections buffers with queryText, allocated with Postgres allocator (see PQsendGpQuery_shared). Normally, no messages are written to connection buffer until dispatching was done and buffer will be replaced back (see
cdbdisp_waitDispatchFinish_async->pqFlushNonBlocking->pqSendSome).
But this process may be interrupted by client. In case of receiving SIGTERM, gpdb aborts transaction, destroy dispatcher state …
> Fix segmentation fault during dispatch interrupt

- src/backend/optimizer/path/indxpath.c
Ivfflat and hsnw indexes both don't support 'amgetbitmap', after this pr they can be used on AO tables.
The main reason for us to enable those 2 indexes on AO tables is that they both only support `ORDER BY` queries and the typical query on embedding data is `ORDER BY embedding LIMIT `, as only limited rows fetched from the base tables, the cost on AO table random access won't be big.
The other reason is that the IVFFLAT index only fetches part of the index tuples when doing a query (the percent is probes/lists), so generally using the index can improve the performance.
No such indexes (amgetbitmap=NULL but amgettuple=non-NULL) exist in core or have ever been supported for GPDB customers, so no chance of regression with this change.
No test has been added to this pr because there isn't …
> Enable index scan on AO tables for indexes that don’t have amgetbitmap

- src/bin/gpfdist/gpfdist.c
Current gpfdist will update the corresponding sequence number when it responds a HTTP request successfully.  However, the network may be unstable when gpfdist processes a HTTP request. In rare conditions, a connection could be aborted when gpfdist finishes receiving and writing data, which would lead to a data-sending retry.  
Since gpfdist wouldn't update the sequence number despite finishing data writing when the response failed, gpdb will retry to send the same data which will be written again. 
The PR is to handle the rare case. Gpfdist updates the sequence number when data writing ends or the request is OPEN_SEQ. This will avoid the unexpected network abortion when gpfdist responds 'OK' to gpdb. After the sequence number is updated for the segment, even if the same data is sent to …
> Fix gpfdist data overwriting

- src/test/isolation2/expected/resgroup/resgroup_cpu_max_percent.out
- src/test/isolation2/sql/resgroup/resgroup_cpu_max_percent.sql
UDF busy in resgroup_cup_max_percent.sql is as follows:
```
CREATE OR REPLACE FUNCTION busy() RETURNS void AS $$
import os
import signal
n = 15
for i in range(n):
if os.fork() == 0:
signal.signal(signal.SIGINT,  lambda a, b: os._exit(0))
signal.signal(signal.SIGQUIT, lambda a, b: os._exit(0))       
signal.signal(signal.SIGTERM, lambda a, b: os._exit(0))
while True: 
pass
os.wait()
$$ LANGUAGE plpython3u;
``` 
SELECT * FROM gp_dist_random('gp_id') WHERE busy() IS NULL;
When we execute the above SQL, call busy in QEs and each QE will fork 15 processes.
The call stack and memory values of the 15 processes are the same as QE's.
In one segment now there are 16 QEs( one original QE and 15 QEs forked),
and they belong to one MPP session.
Some struct related to MPP session is shared between all …
> Modify UDF busy in resgroup_cpu_max_percent.sql to fix resource group flaky case

- src/backend/access/common/reloptions.c
- src/backend/catalog/pg_appendonly.c
I run into those codes occasionally and found something wrong.
The rd_options in appendonly table was not correct because fetching it with
RELOPT_KIND_HEAP.
Fix that by passing RELOPT_KIND_APPENDONLY to 'default_reloptions' and
add 'RELOPT_KIND_APPENDOPTIMIZED' to some options like 'boolRelOpts'
to make them avaliable to AO tables.
> Get reloptions of appendonly table from rd_options directly.

- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/sbin/gpsegrecovery.py
- gpcontrib/gp_toolkit/gp_toolkit--1.0.sql
- src/backend/access/external/url.c
- src/backend/access/external/url_curl.c
- src/backend/access/external/url_execute.c
- src/backend/gporca/scripts/get_debug_event_counters.py
- src/backend/postmaster/postmaster.c
- src/backend/postmaster/syslogger.c
- src/backend/replication/basebackup.c
- src/backend/utils/misc/guc.c
- src/bin/pg_basebackup/pg_basebackup.c
- src/bin/pg_rewind/filemap.c
- src/bin/pg_rewind/libpq_fetch.c
- src/bin/pg_rewind/pg_rewind.c
- src/bin/pg_rewind/pg_rewind.h
- src/bin/pg_rewind/t/003_extrafiles.pl
- src/bin/pg_rewind/t/RewindTest.pm
- src/include/access/url.h
- src/include/miscadmin.h
- src/test/isolation2/expected/log_directory.out
- src/test/isolation2/expected/prepared_xact_deadlock_pg_rewind.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/log_directory.sql
- src/test/isolation2/sql/prepared_xact_deadlock_pg_rewind.sql
- src/test/isolation2/sql/setup.sql
Enable GUC `log_directory` to be modifiable
This commit enables the flexibility of `log_directory`.
There are three scenarios to consider.
- Absolute path
- Relative path to the data directory
- Relative path but goes outside the data directory
When the GUC change is an absolute path (or outside the data directory),
we will append a unique identifier (DBID) to the `log_directory` GUC. If
we do not do this, the segment logs will overwrite one another and cause issues.
For example:
`log_directory: /tmp/foosball` will internally change to
coordinator: /tmp/foosball/1, seg0: /tmp/foosball/2, seg1:
/tmp/foosball/3, and so on.
The points above are all internal, so when a user queries the
`log_directory` GUC, it will not have the DBID.
For example:
$ gpconfig -s log_directory
Values on all …
> Enable GUC `log_directory` to be modifiable

- src/backend/commands/vacuum.c
With `optimizer_analyze_root_partition` enabled, `VACUUM` commands with a relation list would check leaf partition stats even when `VACUUM (ANALYZE)` was not specified.
Instead, check for `VACOPT_ANALYZE` before updating parent partition stats in `expand_vacuum_rel`. There is no reason to check `leaf_parts_analyzed` or add to the vacuum list if `ANALYZE` wasn't specified.
The existing comment explains the intended behavior:
```
* GPDB: If you explicitly ANALYZE a partition, also update the
* parent's stats after the partition has been ANALYZEd. (Thanks to
* the code to merge leaf statistics, it should be fast.)
```
The fix results in a large performance improvement when issuing `VACUUM` with a relation list and `optimizer_analyze_root_partition` enabled.
Authored-by: Brent Doil …
> Fix ANALYZE bug in expand_vacuum_rels

- src/backend/postmaster/postmaster.c
If gp_role value is not specified then internally "utility" is set as default. This is mainly for single node coordinator or segments. Changing that setting to use PGC_S_DYNAMIC_DEFAULT instead of PGC_S_OVERRIDE.
The problem with using PGC_S_OVERRIDE is GUC value can't be set later. Since commit 260710, we rely on assign_gp_role() hook to set should_reject_connection. If PGC_S_OVERRIDE is used to SetConfigOption() while setting the default in PostmasterMain(), then later setting gp_role via PGOPTIONS or any other mechanism will not call the assign hook and hence misses to set
should_reject_connection. The reason for change being safe is check_gp_role() only allows "utility" mode to set as value for this GUC and any other values like "execute" or "dispatch" are already banned from …
> Don't use PGC_S_OVERRIDE for setting gp_role GUC

- src/backend/cdb/motion/tupser.c
The benefit from this optimization idea is plausible (basically, avoiding one memcpy of the memtuple), but the changes incurred by this are just too backwards and invasive for the effort to be worthy:
1. There is no memtuple to directly serialize from. The `PRIVATE_tts_memtuple` field in `TupleTableSlot` is gone after the FIXME was added (d20e071e879). Basically we do not store the memtuple outside of the AM layer anymore (like in the executor memory). I think bringing `PRIVATE_tts_memtuple` back to `TupleTableSlot` and utilize it everywhere is a clear backward change.
2. Assuming we somehow pass the memtuple into `SerializeTuple` as a function argument. But on the deserialization side, we would still need to deserialize it back to minimal tuple because all the deserilization logic and …
> Remove a FIXME in tupser.c

- src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/expected/gporca_optimizer.out
Previously a fallback to planner for query parameters would be logged as an error instead of
a notice, which is misleading as this is an intentional fallback. Now,
it will display as a notice.
`THD000,ERROR,""GPDB Expression type: Query Parameter not supported in DXL"",`
will change to:
`THD000,NOTICE,""GPDB Expression type: Query Parameter not supported in DXL"",`
Backport of 83e3f510a9
> 6X: Change Query Parameter fallback message in Orca to notice type

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
This PR changes the order of the different subtopics in the Platform Requirements page, in order to make it easier for the user to identify them. 
It removes the "On premise hardware requirements" as OS, tools/extensions, hardware, storage and hadoop requirements are common for any kind of installation.
Bringing Cloud (and vSphere when available) to the bottom of the page.
Test site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-platformreq/greenplum-database/install_guide-platform-requirements-overview.html
> Docs: reorder of Platform Requirements page

- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
This PR changes the order of the different subtopics in the Platform Requirements page, in order to make it easier for the user to identify them.
It removes the "On premise hardware requirements" as OS, tools/extensions, hardware, storage and hadoop requirements are common for any kind of installation.
Bringing Cloud and vSphere to the bottom of the page.
Test site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-platformreq-6X/greenplum-database/install_guide-platform-requirements-overview.html
> Docs: reorder of platform requirements 6 x

- src/backend/gpopt/CGPOptimizer.cpp
- src/backend/gpopt/utils/CMemoryPoolPallocManager.cpp
- src/backend/gporca/libgpopt/include/gpopt/exception.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformFactory.h
- src/backend/gporca/libgpopt/src/exception.cpp
- src/backend/gporca/libgpopt/src/init.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
- src/backend/gporca/libgpos/include/gpos/error/CFSimulator.h
- src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
- src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
- src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
- src/backend/gporca/libgpos/include/gpos/task/CWorkerPoolManager.h
- src/backend/gporca/libgpos/src/_api.cpp
- src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
- src/backend/gporca/libgpos/src/error/CFSimulator.cpp
- src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
- src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
- src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
- src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
- src/backend/gporca/libnaucrates/include/naucrates/exception.h
- src/backend/gporca/libnaucrates/src/exception.cpp
- src/backend/gporca/libnaucrates/src/init.cpp
- src/backend/gporca/server/src/startup/main.cpp
- src/include/gpopt/utils/CMemoryPoolPallocManager.h
When initializing ORCA mixed a C approach (returning error codes and then checking them) and a C++ approach (throwing exceptions and then catching them). This mixing led to errors. For example, in case of low memory or any other exception, the CWorkerPoolManager::Init function did not return GPOS_OK, and then the gpos_init function called
the CMemoryPoolManager::GetMemoryPoolMgr()->Shutdown function, which reset CMemoryPoolManager::m_memory_pool_mgr. In this case, all the exceptions that arose were not rethrown, so the execution continued, and the following gpdxl_init function was called, in which the CAutoMemoryPool class was initialized. In the constructor of this class, the static method CMemoryPoolManager::GetMemoryPoolMgr returned NULL, because we nullified m_memory_pool_mgr up the …
> [6X] ORCA initialization refactoring

- src/backend/commands/explain.c
- src/backend/executor/nodeAgg.c
- src/include/executor/nodeAgg.h
- src/include/lib/simplehash.h
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
After upgrading to GPDB7, we lost the detailed cdb executor instruments of hashagg since the code base has been changed in a large size. The patch is to re-implement explain analyze related code of hashagg to provide more critical info for troubleshooting issues.
We use a script to create the hashagg scenario:
```
create table streaming_t1 (d int, i int, c int, dt date);
insert into streaming_t1 select i/10, i/10, i/100, '2009-06-10'::date + ( (i%34) || ' days')::interval from generate_series(0, 99999999) i;
analyze streaming_t1;
SET statement_mem='1000kB';
SET optimizer=off;
explain analyze select count(distinct i) from streaming_t1 group by c;
```
Result in GPDB6:
```
testdb=# explain analyze select count(distinct i) from streaming_t1 group by c;
QUERY PLAN …
```
> Add explain analyze detailed info of hash agg

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
The PR https://github.com/greenplum-db/gpdb/pull/15917/ imported a mistake about mismatch in test case explain_format, which dues to some output string of optimizer in latest code. The fix is simply to update the string.
> Fix test case explain_format

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/commands/explain_gp.c
This PR is try to fix the issue #14573
When the options of the foreign table include mpp_execute as 'all segments' (for example,
Greenplum FDW), and the number of segments in the remote cluster is greater than the
number of local segments, executing explain analyze will fail assert/insist.
To fix this problem, QE should uses qe_identifier instead of segindex to
identify its own workerid.
>  Fixed EXPLAIN ANALYZE bug when foreign scan's gang size larger than number of segments

- src/backend/commands/analyze.c
- src/backend/commands/vacuum.c
- src/test/regress/expected/analyze.out
- src/test/regress/sql/analyze.sql
Problem: Analyzing leaf partitions of multi-level partition table causes
resampling of intermediate partition.
Solution: Remove the intermediate partition from the list of table to be analyzed.
> Analyzing leaf partitions of multi-level partition table causes resampling of intermediate partition.

- src/backend/storage/buffer/bufmgr.c
- src/test/isolation2/expected/segwalrep/hintbit_throttle.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/segwalrep/hintbit_throttle.sql
Backport from c5abb1f3e6c20f5fa372c2c807dfd22b350985f2
The only difference between the 6X and 7X change is that in 6X we can directly use the "exclusive" field in the content lock. So we do not need to add a function like 7X which was mainly for the purpose of not exposing the buffer exclusive lock.
Commit description:
Similar to a previous deadlock issue (bd74bfc),
there's another deadlock possibility in hintbit WAL syncrep while mirror is down, due to it is holding an exclusive buffer lock:
1. Mirror is down.
2. Primary does something that sets hintbits with exclusive lock on buffers, such as VACUUM.
3. During setting hintbits, we would throttle WAL rep (wait_to_avoid_large_repl_lag). Because mirror is down, this is essentially blocking until syncrep is disabled.
4. FTS detects mirror …
> [6X] Hintbit WAL syncrep should not throttle when holding exclusive lock

- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
Following the merging of changes from pull request #15727, there was an intermittent test failure in gpstop. This situation occurred when testing how the gpstart process behaves in the presence of a lock directory created by a previous gpstop operation.
In this specific scenario, the expected behavior was that the lock directory from gpstop shouldn't disrupt the gpstart process. To examine this, a test was set up where a gpstop process was started and stopped before completion. This created a lock directory in COORDINATOR_DATA_DIRECTORY. Subsequently, an attempt was made to clean up any remaining parts of the postgres process on the coordinator using the `pkill postgres `command. This was essential to prevent issues where gpstart might fail with errors like ‘Greenplum instance already …
> Fix gpstop pipeline flakiness after #15727

- src/test/regress/expected/vacuum_stats.out
- src/test/regress/sql/vacuum_stats.sql
During the test, backgroup process like dtx recover and FTS will create gang, which will start transaction on segment. And concurrent transacion will affect the behavior of vacuum (OldestXmin), which will result in that relallvisible could be 0.
In this commit, we make sure that dtx recover and FTS are not working in the test.
> Fix flaky test case vacuum_stats

- contrib/extprotocol/expected/exttableext.out
- contrib/formatter_fixedwidth/output/readable_query02.source
- contrib/formatter_fixedwidth/output/readable_query03.source
- contrib/formatter_fixedwidth/output/readable_query04.source
- contrib/formatter_fixedwidth/output/readable_query10.source
- contrib/formatter_fixedwidth/output/readable_query14.source
- contrib/formatter_fixedwidth/output/readable_query17.source
- contrib/formatter_fixedwidth/output/readable_query20.source
- contrib/formatter_fixedwidth/output/readable_query32.source
- contrib/formatter_fixedwidth/output/readable_query33.source
- gpcontrib/gp_exttable_fdw/.gitignore
- gpcontrib/gp_exttable_fdw/input/gp_exttable_fdw.source
- gpcontrib/gp_exttable_fdw/option.c
- gpcontrib/gp_exttable_fdw/output/gp_exttable_fdw.source
- gpcontrib/gpcloud/regress/output/1_10_all_regions.source
- gpcontrib/gpcloud/regress/output/1_18_all_regions_version2.source
- src/backend/access/external/external.c
- src/backend/commands/exttablecmds.c
- src/bin/gpfdist/regress/output/exttab1.source
- src/bin/pg_dump/t/002_pg_dump.pl
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/expected/create_table_like_gp.out
- src/test/regress/expected/dsp.out
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
Greenplum had both `format` and `format_type` in the external table's
`ftoptions` because the `ExtTableEntry` had both (one is for the catalog,
the other is for COPY), which made the `ftoptions` confusing.
This PR refactor to remove the `format_type` option.
Before, the external table's ftoptions member stored values directly
from the `ExtTableEntry`, for instance, `log_errors` could be 'p',
`encoding` could be '6', which is kind of not human-friendly.
This commit changes:
1, the key `encoding`'s values to the real names, like 'UTF8'.
2, the key `log_errors`'s values to 'enable', 'disable', or 'persistently'.
'true', 'false', or 'persistent' also work to be tolerant.
3, the key `reject_limit_type`'s values to 'rows' or 'percentage'.
'row' or 'percent' also work because the external table …
> Refactor the external table's ftoptions

- src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
- src/backend/gporca/libgpos/src/string/CWStringBase.cpp
- src/backend/gporca/libgpos/src/string/CWStringConst.cpp
Previously, we would use GPOS_WSZ_LENGTH, which is just a wrapper around gpos::clib::Wcslen(x), which checks the length by iterating over the string. We already store the string length within the string, so we should use that instead. This shaves off ~8% of optimization time in my tests when the relcache is populated.
> Optimize string length checks in Orca

- src/backend/cdb/cdbgroup.c
- src/test/regress/expected/select_having.out
- src/test/regress/sql/select_having.sql
Replace PVC_REJECT_PLACEHOLDERS with PVC_INCLUDE_PLACEHOLDERS so we could accept placeholders as targtelists of lower plan, that's the behavior we expected.
> [6X] fix placeholder var ERROR of HavingQual in planner

- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
This is a backport of [#13323](https://github.com/greenplum-db/gpdb/pull/13323)
**Issue:**
gprecoverseg -i fails to recover any segment if the failed host is unreachable.
This is irrespective of full/incremental recovery, if the failed host is down then none of the down segments are recovered.
Ideally the recovery should depend on the failover host status.
**RCA:**
Currently while recovering the segments with input configuration file, we check the status of failed host for both the below scenarios,
1. when failed and failover host are same (in-place recovery)
2. When failed and failover host are different
If the failed host is unreachable, recovery fails.
**Fix:**
Checking the status of failed host is done only in case of in-place recovery, specifically, when the failover information is …
> [6x Backport] Fix gprecoverseg with unreachable failed host

- src/backend/libpq/hba.c
- src/test/regress/expected/hba_conf.out
- src/test/regress/greenplum_schedule
- src/test/regress/serial_schedule
- src/test/regress/sql/hba_conf.sql
When ldaptls is set to "1", and ldapscheme is not set, when `select from pg_hba_file_rules;`, postgres will crash because of dereference to a null pointer which is the value of ldapscheme.
> Fix ldap crash when ldaptls=1 and ldapscheme is not set.

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/include/gpopt/gpdbwrappers.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
In 6X while retrieving the column widths of a partitioned table, inherited stats i.e. stats that cover all the child tables are used. This is done by using method gpdb::GetAttStats. But in 7X the inherited stats are not used. In 7X the method gpdb::GetAttAvgWidth is getting used which generates stats for individual tables and not for inheritance trees. This PR makes the behaviour of 7X similar to 6X by using inherited stats for partitioned tables.
> Fixing column width of partitioned tables

- gpMgmt/bin/gppylib/commands/base.py
- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Added a behave test scenario which tests the data integrity property of differential recovery. In this scenario we assert that any data inserted in database during the execution of recovery can be seen even after the completion of recovery and no data loss happens.
Steps:
- Create a table test_recoverseg with 1000 rows
- Stop one primary segment and wait for it to marked down in gp_segment_configuration
- Create a rsync bash script which will (1st and 2nd steps will be performed only if pg_wal is being synced)
1. insert 1000 extra rows in test_recoverseg
2. execute a checkpoint (just to make sure the latest_checkpoint is updated in pg_control file)
3. executes actual (/usr/bin/rsync) rsync to sync the source and target provided
- Run differential recovery and make sure it uses new rsync …
> gprecoverseg differential: Data integrity scenario

- gpMgmt/bin/gppylib/operations/reload.py
This utility has been superseded by ALTER TABLE REPACK BY statements, and is now deprecated. Add a logged warning indicating so.
> Deprecate gpreload

- src/backend/commands/tablecmds.c
- src/test/isolation2/expected/aoco_column_rewrite.out
- src/test/isolation2/sql/aoco_column_rewrite.sql
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/sql/alter_distribution_policy.sql
If AT SET DISTRIBUTED BY, or AT SET WITH (reorganize=true|false) is run
today along with another subcommand, it will result in ERRORs such as:
ALTER TABLE foo ADD COLUMN c int, SET DISTRIBUTED BY(b);
ERROR: attribute number 3 exceeds number of columns 2
This kind of error results when the CTAS for the temp table is
dispatched as part of ATExecSetDistributedBy(). Since SET DISTRIBUTED BY
is run in the last pass, the ADD COLUMN takes effect on the QD and is
considered as part of the dispatched QueryDesc for the CTAS. However,
since the AT command has not been dispatched yet to the QEs (which only
happens after ATController()), the QE hasn't yet applied the results of
the ADD COLUMN operation.  Thus, the QEs cannot reconcile the reference
to the added column, and an ERROR results.
Other …
> Disallow non-standalone ALTER distribution

- src/bin/gpfdist/regress/Makefile
- src/bin/gpfdist/regress/input/gpfdist_old_ssl.source
- src/bin/gpfdist/regress/input/gpfdist_ssl.source
- src/bin/gpfdist/regress/output/gpfdist_old_ssl.source
- src/bin/gpfdist/regress/output/gpfdist_ssl.source
Gpdb is going to support rocky9/rhel9/oel9. In this operation system, the default openssl version is 3.*, which doesn't support tls 1.0 and tls 1.1. Thus, we have to do some adjustments for gpfdist regression tests.
>  Fix ssl test for gpfdist6

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
docs for https://github.com/greenplum-db/gpdb/pull/16087.
remove backwards index scan from list of unsupported gporca index features
> docs - gporca now supports backwards index scan

- gpdb-doc/markdown/admin_guide/ldap.html.md
This PR addresses the following corrections for the page Using LDAP Authentication with TLS/SSL:
1. all "ldaptls=1" should be replaced with "ldaptls=true"
2. "Specify a non-default port with the ldapport parameter. In this example, the authentication method includes the ldaptls parameter and the ldapport parameter to specify the port 550.
ldap ldapserver=[myldap.com](http://myldap.com/) ldaptls=1 ldapport=500 ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
"
The description the port550 and the ldapport=500 doesn't match. It should be both 550 or 500.
3. the last example is wrong,
"host all ldapsuser 0.0.0.0/0 ldap ldapserver=[ldaps://myldap.com] ldapprefix="uid=" ldapsuffix=",ou=People,dc=example,dc=com"
"
should be modified with
"host all ldapsuser 0.0.0.0/0 ldap …
> Docs: LDAP page corrections

- gpdb-doc/markdown/admin_guide/kerberos.html.md
The server configuration parameter `krb_srvname` was removed in Greenplum 6. From postgres documentation:
When connecting, the client must know the principal name of the server it intends to connect to. The servicename part of the principal is ordinarily postgres, but another value can be selected via libpq's krbsrvname connection parameter. The hostname part is the fully qualified host name that libpq is told to connect to. The realm name is the preferred realm specified in the Kerberos configuration file(s) accessible to the client.
Updating the topic "Using Kerberos Authentication" to reflect this change.
This probably needs to be ported to 6X_STABLE branch too.
> Docs: removed reference of removed configuration parameter krb_srvname

- gpdb-doc/markdown/install_guide/prep_os.html.md
This PR modifies the section "Synchronizing System Clocks" to include:
- Distinction about two different architectures: configure segments to rely on the coordinator for NTP or configure all hosts in the cluster to rely on an external NTP source.
- Include chronyd as another possible daemon to implement the NTP protocol.
Review site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-ntp/greenplum-database/install_guide-prep_os.html#topic_qst_s5t_wy
> Docs: modified Synchronizing System Clocks section 

- src/backend/storage/file/buffile.c
The issue was imported by https://github.com/greenplum-db/gpdb/pull/16243. Basically, the code in `makeBufFile()` fails to compile if GPDB is compiled without `USE_ZSTD`:
```
file->compressed_buffer_size = 0;
```
The fix is to include the code by `ifdef USE_ZSTD` macro.
> Fix compiling failure without USE_ZSTD

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
- gpMgmt/bin/lib/multidd
Support for 6x has been introduced for rocky9/oel9/rhel9, but there are some jobs experiencing failures.
**Failure 1:** gpcheckperf Failure
**Root Cause** - This failure is attributed to the absence of Python 2, as these operating systems exclusively
support Python 3. The code relied on Python 2-specific syntax, including the "print" statement.
**Solution** - To rectify this, we have diligently updated the affected code sections to be compatible with
Python 2 and Python 3 both. Instances of Python 2-specific syntax, such as the "print" statement, have
been replaced with Python 3-compatible alternatives like "print()".
**Failure 2:** gpinitsystem failure
**Root Cause** - The gpinitsystem failure was primarily caused by the presence of a banner in the command output,
making it challenging …
> [6x]: Fix failed jobs for rocky9/oel9/rhel9

- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Added a behave test scenario which tests the data integrity property of differential recovery. In this scenario we assert that any data inserted in database during the execution of recovery can be seen even after the completion of recovery and no data loss happens.
Steps:
- Create a table test_recoverseg with 1000 rows
- Stop one primary segment and wait for it to marked down in gp_segment_configuration
- Create a rsync bash script which will (1st and 2nd steps will be performed only if pg_wal is being synced)
- 1. insert 1000 extra rows in test_recoverseg
- 2. execute a checkpoint (just to make sure the latest_checkpoint is updated in pg_control file)
- 3. executes actual (/usr/bin/rsync) rsync to sync the source and target provided
- Run differential recovery and make sure it uses new …
> [6X] gprecoverseg differential: Data integrity scenario

- src/backend/executor/nodeHashjoin.c
- src/backend/storage/file/buffile.c
- src/include/storage/buffile.h
The PR https://github.com/greenplum-db/gpdb/pull/16243 caused ABI breaking in BufFilePledgeSequential():
```
buffile.h, postgres
[−] BufFilePledgeSequential ( BufFile* buffile )  1
⇣
BufFilePledgeSequential ( BufFile* buffile, workfile_set* work_set )
```
However, because `BufFile` has a pointer of `workfile_set`, we don't need to change the interface of `BufFilePledgeSequential()` at all. The fix is simply to use `buffile->work_set` and avoid the change of `BufFilePledgeSequential()` interface.
> Fix ABI breaking of BufFilePledgeSequential()

- src/include/access/tableam.h
- src/include/nodes/parsenodes.h
A recent commit caused ABI changes after the beta-5 ABI freeze. Reorganize those changes to fix that:
* move relation_copy_for_repack to end of the  TableAmRoutine struct
* move AT_RepackTable to end of AlterTableType enum
> Fix ABI breakage

- src/backend/cdb/cdbpath.c
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/sql/gp_recursive_cte.sql
For a recursive CTE, planner currently creates a mergejoin plan which moves the WorkTableScan results to a singleQE using CdbPathLocus_MakeSingleQE
That would introduce motion in between Union and WorkTableScan. The WorkTableScan results should be local to each segment and shouldn't be broadcasted/moved to other segments. We shouldn't be allowing any motion in between Union and WorkTableScan. This commit adds a check for the last resort case to avoid adding that motion. If there is a WTS on any side in the last resort case, we should just fail (no possible plan using mergejoin)
Added simplified test to force a mergejoin for such recursive CTE, the test shouldn't create a mergejoin plan.
> Fix recursive CTE mergejoin having motion on WTS

- src/include/access/url.h
e358573762ee35a40f95ba96630f176b0cd795cc introduced a new field in
extvar_t called GP_SEG_LOGDIR. It was done in the middle of the struct.
So we move it to the end of the struct as a mitigation.
Reviewed-by: Ashwin Agrawal <aashwin@vmware.com>
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/fix_extvar
> url.h: Fix ABI breakage in extvar_t

- src/backend/commands/resgroupcmds.c
- src/backend/utils/resgroup/cgroup-ops-dummy.c
- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/backend/utils/resgroup/cgroup_io_limit.c
- src/backend/utils/resgroup/io_limit_gram.y
- src/backend/utils/resgroup/io_limit_scanner.l
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/cgroup.h
- src/include/utils/cgroup_io_limit.h
- src/include/utils/resgroup.h
- src/test/isolation2/output/resgroup/resgroup_io_limit.source
Use tablespace name in catalog will cause some wrong exceptions, for example, the tablespace has been renamed.
Use oid in catalog like:
```
1663:rbps=5,wbps=5,riops=1000,wiops=1000
```
can eliminate errors caused by rename.
io limit also support write tablespace oid directly in this pr. Both
```
1663:rbps=5,wbps=5,riops=1000,wiops=1000
```
and 
```
pg_default:rbps=5,wbps=5,riops=1000,wiops=1000
```
is legal.
> io limit: save oid in catalog instead of tablespace name

- src/test/regress/expected/hba_conf.out
- src/test/regress/sql/hba_conf.sql
This previous commit https://github.com/greenplum-db/gpdb/commit/b7715f24d7f453c13b74f0a4f05bc4c84f0ebf99 introduced one bad pghba text line for pg_hba.conf and did not clear it after the test. Thus binary swap task to old version of gpdb without fix will cause the cluster crash.
This PR is to fix the binary swap task by adding recovery script when case "hba_conf" has finished.
> Fix failed pipeline for job icw_planner_jit_rocky8.

- src/backend/commands/explain_gp.c
- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
By https://github.com/greenplum-db/gpdb/pull/15917, some code was added to test case explain_format to check the EXPLAIN ANALYZE output for hash agg. However, it failed occasionally because there might be an additional line of "Extra Text" like this:
```
@@ -871,6 +871,8 @@
Group Key: share0_ref2.b
Extra Text: (seg0)   hash table(s): ###; ### groups total in ### batches, ### spill partitions; disk usage: ###KB; chain length ###.## avg, ### max; using ## of ### buckets; total ### expansions.
+                    Extra Text: (seg0)   hash table(s): ###; ### groups total in ### batches, ### spill partitions; disk usage: ###KB; chain length ###.## avg, ### max; using ## of ### buckets; total ### expansions.
+
->  Redistribute Motion 3:3  (slice2; segments: 3) (actual time=##.###..##.### …
```
> Fix test case explain_format about Extra Text

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
The most important changes of this commit are:
1. Notice the user that cgroup2 doesn't yet support control of real-time
processes, the possible "Invalid argument" error is expected when there are
real-time processes in non-root cgroups.
2. Greenplum has to have the write permission of `/sys/fs/cgroup/cgroup.procs`
to manipulate the cgroups since it currently not spawned by Systemd or other
managers that take over cgroups management.
Reference: https://docs.kernel.org/admin-guide/cgroup-v2.html#controlling-controllers
> Refine the document of resource groups

- src/backend/storage/file/fd.c
The comment maybe mislead the code readers because we never use ` t<digits>_<digits>_<forkname>` pattern for temporary relation in GPDB.
> Corrected comment mistake about `looks_like_temp_rel_name` function.

- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/resgroup-dummy.c
The Cgroups, which the resource group depends on, is a Linux kernel feature.
> Disable resource group helper functions on non-Linux systems

- src/backend/cdb/cdbhash.c
- src/backend/cdb/cdbvars.c
- src/backend/executor/nodeModifyTable.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbhash.h
- src/include/cdb/cdbvars.h
- src/include/utils/sync_guc_name.h
- src/test/isolation2/expected/guc_gp.out
- src/test/isolation2/sql/guc_gp.sql
During OS upgrades, such as an upgrade from CentOS 7 to CentOS 8, there could be some
locale changes happen that lead to the data distribution or data partition position change.
In order to detect it, we add a new GUC of `gp_detect_data_correctness`, if it sets to on,
we will not insert data actually, we just check whether the data belongs to this segment or
this partition table or not.
> add a new GUC of gp_detect_data_correctness to detect data correctness during OS upgrade

- src/bin/gpfdist/regress/input/gpfdist_old_ssl.source
- src/bin/gpfdist/regress/output/gpfdist_old_ssl.source
Gpfdsits old ssl test cases are used for testing TLS1.0 and TLS1.1.
We have extracted these test cases to a standalone file in previous PR #16311 , but missed to start gpfdist for these test cases.
So, Add the steps to start/stop gpfdist
> Fix gpfdsits old ssl test cases

- src/backend/access/transam/xlog.c
- src/test/recovery/t/138_archive_current_timeline_history.pl
Note: This PR replaces https://github.com/greenplum-db/gpdb/pull/16161.
Previously, the only time the timeline history file would be archived was when a standby already configured for WAL archiving was promoted. If WAL archiving was set up and started after the standby was promoted, its current timeline history file would not be found in the archive. This could cause issues when restoring backups that did not include the timeline history files (e.g. pg_basebackup -Xnone). Some example failures include failing to restore with recovery_target_timeline explicitly set to the control file's timeline id and failing to create cascade standbys after recovering with recovery_target_timeline set to 'current' or 'latest'. To prevent these restore issues, we now ensure that the current timeline …
> Archive current timeline history file after recovery finishes if needed

- gpMgmt/bin/gpload_test/Makefile
- gpMgmt/bin/gpload_test/pytest_requirement.txt
install pip2 and other site-packages needed by gpload test in Makefile
gpload_test needs pytest module to run with vendored python2.7.18. in the past, we use os provided python2 and os provided pip2 to install pytest inside the gpdb6-[OS]-test docker image, then during ICW, use vendored python2.7.18 to import pytest inside the gpdb6-[OS]-test docker image.
But this does not work for EL9 platform, because EL9 has dropped python2 and pip2, so there is no way to have pytest installed inside gpdb6-rocky9/rhel9/oel9-test image, so gpload_test will failed on EL9 like the following error
/usr/local/greenplum-db-devel/ext/python/bin/python: No module named pytest
To fix the issue on platform EL9. we use vendored python2.7.18 and its pip to install pytest during the test.
> support gpload test in rocky9

- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
**Post differential recovery more tablespace directory is created on the target segment.**
```
[gpadmin@cdw ~]$ gpssh -f segment_host_list -v
[WARN] Reference default values as $COORDINATOR_DATA_DIRECTORY/gpssh.conf could not be found Using delaybeforesend 0.05 and prompt_validation_timeout 1.0 [Reset ...]
[INFO] login sdw2
[INFO] login sdw1
=> ls /tmp/mytblespace/
ls /tmp/mytblespace/
[sdw2] 4 5 6 7
[sdw1] 2 3 8 9
=> exit
[gpadmin@cdw ~]$ gpssh -f segment_host_list -v
[WARN] Reference default values as $COORDINATOR_DATA_DIRECTORY/gpssh.conf could not be found Using delaybeforesend 0.05 and prompt_validation_timeout 1.0 [Reset ...]
[INFO] login sdw1
[INFO] login sdw2
=> ls /tmp/mytblespace/
ls /tmp/mytblespace/
[sdw1] 2 3 4 5 6 7 8 9
[sdw2] 4 5 6 7
=> exit
```
1. make sure that the …
> [7X] Fix Differential recovery tablespace issue

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/sql/alter_distribution_policy.sql
This is a 6X backport of 20f39c76f3dd03b0feb8b05011c1e0637df6c77e, with
trivial conflicts resolved (there was no test case for
gp_force_random_redistribution and the aoco_column_rewrite test file
doesn't exist in 6X).
Also, in 6X the ERROR message is slightly different from the one
described in the original commit message:
ERROR:  invalid attribute number 3 (heaptuple.c:1231)
If AT SET DISTRIBUTED BY, or AT SET WITH (reorganize=true|false) is run
today along with another subcommand, it will result in ERRORs such as:
ALTER TABLE foo ADD COLUMN c int, SET DISTRIBUTED BY(b);
ERROR: attribute number 3 exceeds number of columns 2
This kind of error results when the CTAS for the temp table is
dispatched as part of ATExecSetDistributedBy(). Since SET DISTRIBUTED …
> [6X] Disallow non-standalone ALTER distribution

- src/backend/cdb/cdbpath.c
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/sql/gp_recursive_cte.sql
For a recursive CTE, planner currently creates a mergejoin plan which moves the WorkTableScan results to a singleQE using CdbPathLocus_MakeSingleQE
That would introduce motion in between Union and WorkTableScan. The WorkTableScan results should be local to each segment and shouldn't be broadcasted/moved to other segments. We shouldn't be allowing any motion in between Union and WorkTableScan. This commit adds a check for the last resort case to avoid adding that motion. If there is a WTS on any side in the last resort case, we should just fail (no possible plan using mergejoin)
Added simplified test to force a mergejoin for such recursive CTE, the test shouldn't create a mergejoin plan.
Co-authored-by: Zhenghua Lyu <zlv@pivotal.io>
Co-authored-by: Alexandra Wang<lewang@pivotal.io>
(cherry …
> 6X: Fix recursive CTE mergejoin having motion on WTS

- gpdb-doc/markdown/ref_guide/modules/postgres_fdw.html.md
docs for https://github.com/greenplum-db/gpdb/pull/16177.  in this PR:
- add new "About Limit Pushdown Support" to postgres_fdw topic
- didn't look to me like any other docs required updates
> docs - postgres_fdw supports limit pushdown

- gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
can use greenplum_fdw to access 6x cluster also.
will backport to greenplum 6 docs.
> docs - greenplum_fdw works between versions 6 <=> 7

- gpdb-doc/markdown/install_guide/prep_os.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv-base.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv-config.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv-greenplum.html.md
- gpdb-doc/markdown/utility_guide/ref/gpv.html.md
- gpdb-doc/markdown/utility_guide/utility-programs.html.md
The Greenplum Virtual Appliance introduces the `gpv` utility. This PR adds the gpv commands to the Greenplum utility reference guide.
Review site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/gpv-gva/greenplum-database/utility_guide-ref-gpv.html
Few points:
- The section "Required Inputs" lists all the data user needs to know before starting with the configuration. We decided to bring the table to the reference pages and not the narrative pages in order to have it in one place only, and since the table items are mapped into the command options and sub-options, any future changes to the commands would only have to be reflected on this page.
- How to distribute the gpv reference pages? Currently they are split into three different subpages due to how extensive `gpv …
> Docs gpv reference

- src/backend/gporca/data/dxl/minidump/JoinOnReplicatedUniversal.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
"IF" block of CPhysicalJoin.cpp as part of commit#5c36a44ab03c43e82ef08006ad6021773c6176b6 was not clang-formatted and because of it check format failed in pipeline.
Pipeline status after fix: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fixing_check_format-rocky8
> Fix clang-formatting in CPhysicalJoin.cpp and MDP file

- src/backend/access/transam/xlog.c
- src/test/recovery/t/138_archive_current_timeline_history.pl
Previously, the only time the timeline history file would be archived was when a standby already configured for WAL archiving was promoted. If WAL archiving was set up and started after the standby was promoted, its current timeline history file would not be found in the archive. This could cause issues when restoring backups that did not include the timeline history files (e.g. pg_basebackup -Xnone). Some example failures include failing to restore with recovery_target_timeline explicitly set to the control file's timeline id and failing to create cascade standbys after recovering with recovery_target_timeline set to 'current' or 'latest'. To prevent these restore issues, we now ensure that the current timeline history file has been archived by marking it as ready for archiving after …
> [6X backport] Archive current timeline history file after recovery finishes if needed

- src/backend/commands/resgroupcmds.c
- src/backend/commands/tablespace.c
- src/backend/utils/resgroup/cgroup-ops-dummy.c
- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/backend/utils/resgroup/cgroup_io_limit.c
- src/backend/utils/resgroup/resgroup.c
- src/include/utils/cgroup.h
- src/include/utils/cgroup_io_limit.h
- src/include/utils/resgroup.h
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/input/resgroup/resgroup_io_limit.source
- src/test/isolation2/output/resgroup/resgroup_io_limit.source
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
This pr has several improvements for io limit:
1. Add a function to clear `io.max`. This function should be used when alter io_limit.
2. Check tablespace in io_limit when drop tablespaces. If the tablespace which will be dropped presents in some io_limit resource groups, the drop tablespace statement will be aborted.
3. When `InitResGroup` and `AlterResourceGroup`, if `parseio` raises an error, the error will be demote to `WARNING`. So the cluster can launch when some tablespace has been removed.
> Improve io_limit behaviors

- src/backend/cdb/dispatcher/test/Makefile
- src/backend/cdb/dispatcher/test/cdbdisp_query_test.c
- src/backend/cdb/dispatcher/test/gpsegconfig_dump
- src/interfaces/libpq/fe-connect.c
- src/interfaces/libpq/fe-misc.c
This PR ported https://github.com/greenplum-db/gpdb/pull/16141 to 6x
----
QD sends ready to execute plan to QE as an array of bytes named as queryText (see buildGpQueryString function for details). This message may be large enough in case of complex multi-node plan. This message is common for any process of any slice on QEs. To avoid duplicating this message for each of hundreds and thousands connection for the query, gpdb temporary replace malloc'ed output connections buffers with queryText, allocated with Postgres allocator (see PQsendGpQuery_shared). Normally, no messages are written to connection buffer until dispatching was done and buffer will be replaced back (see
cdbdisp_waitDispatchFinish_async->pqFlushNonBlocking->pqSendSome).
But this process should and may be interrupted by …
> [6X] Fix segmentation fault during dispatch interrupt

- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
The flaky case caused by running `mkdir` on multi segments at the same host.
Just catch `FileExistsError` and ignore it is ok, the `mkdir` function just need the dir exists.
> Fix resource group io limit flaky case

- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/sbin/recovery_base.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
After the merging of https://github.com/greenplum-db/gpdb/pull/15700, there were some intermittent `gprecoverseg` and `gprecoverseg_new_hosts` job failures. They were happening for a couple of reasons -
- The `signal_handler` in the `gpsegrecovery` process would be called multiple times and sometimes the logger would close the buffer for writing leading to a logging error. Fixed this by moving the logging outside the handler and ignoring the signal once inside the function so that it cannot be called multiple times.
- The timeout for waiting for the `pg_basebackup/pg_rewind` process was less (around 1 min) so increase it.
- Sometimes the mirror might take some time to come up, so changed it to wait instead of just checking once and erroring out.
> gprecoverseg: Fix CI flakiness after #15700

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
- src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
- src/backend/gporca/libgpos/src/string/CWStringBase.cpp
- src/backend/gporca/libgpos/src/string/CWStringConst.cpp
Extension of commit https://github.com/greenplum-db/gpdb/commit/26c3382759b3ec526fc715f4f78617f88b9f17e9 that falls back to planner for queries
using 'ivfflat' indexes from pgvector. However, there is another similar
index 'hnsw' added in pgvector 0.5.0. Add 'hnsw' to the list of indexes
ORCA will fall back when it encounters.
An alternative approach was considered to fallback for any unsupported
index. However, the downside of that is that it will lead to many more
fallbacks when a table has an unsupported index. That could severely
limit ORCA's ability to operate on that table.
NB: This is intended as a temporary hack to avoid ORCA from picking bad
plans until ORCA is able to support these indexes.
Following test falls back to PLANNER:
```sql
CREATE EXTENSION embedding;
CREATE TABLE …
```
> [ORCA] Add fallback on relations with 'hnsw' index type

- src/backend/utils/misc/guc_gp.c
- src/backend/utils/mmgr/memprot.c
- src/backend/utils/mmgr/test/memprot_test.c
- src/include/utils/gp_alloc.h
- src/include/utils/sync_guc_name.h
This commit formalizes the long existing 2GB upper bound for memory
allocations inside gp_malloc_internal(). Historically, this limit has
always been imposed only on debug builds - it doesn't apply to retail
builds. We make that slightly more apparent here in this commit.
Also, we turn the bound into a GUC for greater developer flexibility.
For instance, this GUC can be quite useful when running experiments with
high work_mem: a good rule of thumb would be to set this GUC to a value
higher than 2 * work_mem (internal routines often try to allocate 2 *
work_mem or more, such as tidbitmap growth. See:
tbm_get_pageentry->pagetable_insert()).
Eg: Q4 (at TPC-H scale 30, with work_mem='1GB', and with B-tree indexes
would BRIN indexes created overt the tables) would fail this assert.
Now, …
> Formalize assert build high mem alloc protection

- src/backend/utils/misc/guc.c
- src/pl/plpgsql/src/expected/plpgsql_transaction.out
- src/test/regress/expected/aggregates.out
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/expected/bitmapops.out
- src/test/regress/expected/bitmapops_optimizer.out
- src/test/regress/expected/groupingsets.out
- src/test/regress/expected/groupingsets_optimizer.out
- src/test/regress/expected/guc.out
- src/test/regress/expected/guc_gp.out
- src/test/regress/expected/join.out
- src/test/regress/expected/join_hash.out
- src/test/regress/expected/join_hash_optimizer.out
- src/test/regress/expected/join_optimizer.out
- src/test/regress/expected/rangefuncs.out
- src/test/regress/expected/rangefuncs_optimizer.out
- src/test/regress/expected/select_distinct.out
- src/test/regress/expected/select_distinct_optimizer.out
- src/test/regress/expected/select_parallel.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/output/aocs.source
- src/test/regress/output/appendonly.source
work_mem still enjoys abundant use in our codebase. Although, we would
like to replace it with operatorMemKB, that kind of change will require
significant investment and a careful strategy. So, bring it out of
deprecation for now.
Discussion: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/GgOxTgaMJsA/m/004-RkHDFAAJ
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/undep_work_mem
> Bring work_mem out of deprecation

- src/backend/utils/mmgr/test/memprot_test.c
The memprot_test couldn't resolve gp_max_alloc_size_mb when the unit test was run in a without_asserts build.
So, make a logical copy of the var for unit testing happiness.
> ci: Fix unit test failure in without_asserts build

- concourse/scripts/test_upgrade.bash
- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpstop.py
- gpMgmt/bin/gpstop
- gpMgmt/doc/gpstop_help
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/unreachable_hosts_mgmt_utils.py
This is a backport of https://github.com/greenplum-db/gpdb/pull/15727
Issue:
When a gpstop process with 'smart' option is interrupted, the subsequent gpstop command becomes stuck with an error message stating "the database system is shutting down". This error message also appears when attempting to connect to the database using psql and other utilities.
The problem is that the error message does not provide clear instructions on how to stop the database, leading to confusion and an inability to perform a graceful shutdown. Gpstop will not work at this point and the only way to stop the database is to manually kill the master processes.
RCA
The issue occurs due to the interruption of the gpstop process, which leaves the database system in an incomplete shutdown state with unfinished master …
> [Backport] gpstop does not work if previous gpstop was interrupted.

- src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
**Issue:**
Gporca failed to produce plan for casting int[] to text[].
Example query with plan result:
```
-- setup
create table foo(a int, b int[]);
-- query
explain select CAST(b as text[]) FROM foo;
INFO:  GPORCA failed to produce a plan, falling back to planner
DETAIL:  Feature not supported: ArrayCoerceExpr with elemexpr that is neither FuncExpr or RelabelType
QUERY PLAN
------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..1770.00 rows=49600 width=32)
->  Seq Scan on foo  (cost=0.00..1108.67 rows=16533 width=32)
(3 rows)
```
**RCA:**
In function `CTranslatorScalarToDXL::TranslateArrayCoerceExprToDXL`,
there is a condition restricting the plan dxl to be generated if …
> Remove check restricting some array casts by orca

- src/backend/parser/analyze.c
- src/test/isolation/expected/alter-table-2.out
- src/test/isolation/isolation_schedule
- src/test/isolation/specs/aborted-keyrevoke.spec
- src/test/isolation/specs/alter-table-2.spec
- src/test/isolation/specs/delete-abort-savept-2.spec
- src/test/isolation/specs/freeze-the-dead.spec
- src/test/isolation/specs/lock-committed-keyupdate.spec
- src/test/isolation/specs/lock-committed-update.spec
- src/test/isolation/specs/lock-update-delete.spec
- src/test/isolation/specs/lock-update-traversal.spec
- src/test/isolation/specs/multixact-no-deadlock.spec
- src/test/isolation/specs/multixact-no-forget.spec
- src/test/isolation/specs/nowait-2.spec
- src/test/isolation/specs/nowait-3.spec
- src/test/isolation/specs/nowait-4.spec
- src/test/isolation/specs/nowait-5.spec
- src/test/isolation/specs/nowait.spec
- src/test/isolation/specs/skip-locked-2.spec
- src/test/isolation/specs/skip-locked-3.spec
- src/test/isolation/specs/skip-locked-4.spec
- src/test/isolation/specs/skip-locked.spec
- src/test/isolation/specs/tuplelock-conflict.spec
- src/test/isolation/specs/tuplelock-upgrade-no-deadlock.spec
Currently the isolation_schedule is quite messy as it contains too many FIXMEs and has too many tests disabled w/o a reason. This PR tries to sort them out. It mainly includes two changes:
1. Fixed an issue with upgrading lock for SELECT under utility mode on coordinator. With that, enable tests that can be enabled now, and remove FIXMEs;
```
In https://github.com/greenplum-db/gpdb/commit/6ebce73331773d7cf71cfd109d1d7617453c738e 
we allow that when the right conditions meet, we do not upgrade
lock for a SELECT statement.
This commit fixes a corner case with utility mode: when we are connecting the
coordinator in utility mode, and when we do not enable global deadlock detector
(GDD) but all the other conditions meet, we should not need to upgrade lock as
well because we are not going to …
```
> Sort out isolation_schedule

- src/backend/cdb/dispatcher/test/Makefile
My previous https://github.com/greenplum-db/gpdb/commit/8ada6cbe4e3ca514981200acc53e0826dca03ac6 caused `cdbdisp_query_test.c` failed:
```
mocking /tmp/build/f8c7ee08/gpdb_src/src/backend/libpq/fe-misc.c
mocking /tmp/build/f8c7ee08/gpdb_src/src/backend/utils/misc/gpexpand.c
[          OK ] test__CdbDispatchPlan_may_be_interrupted
[=============] 1 tests ran
[ PASSED      ] 1 tests
make[3]: *** wait: No child processes.  Stop.
make[3]: *** Waiting for unfinished jobs....
make[3]: *** wait: No child processes.  Stop.
make[2]: *** [../../../src/backend/common.mk:49: unittest-check-dispatcher-recurse] Error 2
make[1]: *** [common.mk:49: unittest-check-cdb-recurse] Hangup
make[4]: *** [../../../../../src/Makefile.mock:25: cdbdisp_query-check] Hangup
make: *** [GNUmakefile:221: unittest-check] …
```
> Fix the failure of src/backend/cdb/dispatcher/test/cdbdisp_query_test.c

- gpdb-doc/markdown/ref_guide/modules/timestamp9.html.md
This PR documents two new gucs added to the `timestamp9` module.
> Docs: new two gucs for timestamp9 module

- src/bin/pg_dump/t/002_pg_dump.pl
External table's encoding keeps same with database server encoding when without specify data encoding, so change encoding 'utf8' with '\w+' to match different enncodings.
> replace 'utf8' with '\w+' to match different encoding

- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/minirepro.feature
- gpMgmt/test/behave/mgmt_utils/steps/minirepro_mgmt_utils.py
I'm not sure why minirepro behave tests are not run on our CI and those tests cannot pass. This patch fixes them.
We need to re-enable them on our CI.
Steps to run minirepro's tests locally:
```
cd gpMgmt
make behave flags='--tags=minirepro'
```
> Fix minirepro behave tests.

- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/backend/utils/resgroup/cgroup_io_limit.c
- src/backend/utils/resgroup/io_limit_gram.y
- src/backend/utils/resgroup/io_limit_scanner.l
- src/include/utils/cgroup_io_limit.h
- src/test/isolation2/input/resgroup/resgroup_io_limit.source
- src/test/isolation2/output/resgroup/resgroup_io_limit.source
When io_limit encountered syntax error, previous log is just "Error: Syntax error".
Now, the io_limit has comprehensive log for syntax error:
```
demo=# create resource group rg1 WITH (cpu_max_percent=10, io_limit='pg_defaultrbps=100, wbps=550,riops=1000,wiops=1000');
ERROR:  io limit: syntax error, unexpected '=', expecting ':'
HINT:   pg_defaultrbps=100, wbps=550,riops=1000,wiops=1000
^
demo=# create resource group rg1 WITH (cpu_max_percent=10, io_limit='pg_default:rbps=100wbps=550,riops=1000,wiops=1000');
ERROR:  io limit: syntax error, unexpected IO_KEY, expecting end of file or ';'
HINT:   pg_default:rbps=100wbps=550,riops=1000,wiops=1000
^
```
> Io limit improve error log

- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdCast.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdColStats.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdGPDB.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdRelStats.h
- src/backend/gporca/libnaucrates/include/naucrates/md/CMDIdScCmp.h
- src/backend/gporca/libnaucrates/src/md/CMDIdCast.cpp
- src/backend/gporca/libnaucrates/src/md/CMDIdColStats.cpp
- src/backend/gporca/libnaucrates/src/md/CMDIdGPDB.cpp
- src/backend/gporca/libnaucrates/src/md/CMDIdGPDBCtas.cpp
- src/backend/gporca/libnaucrates/src/md/CMDIdRelStats.cpp
- src/backend/gporca/libnaucrates/src/md/CMDIdScCmp.cpp
This is a follow up to commit https://github.com/greenplum-db/gpdb/commit/b90e0e5b84f6e539eaedd7da9fd2b71a2283507d,
which optimized many objects to do their serialization only when needed.
This commit modifies the rest of the objects. This serialization is
primarily used when there is an error, so there's no need to serialize
it in the vast majority of cases.
This improves optimization time when loading objects into the relcache
by 11%, and for queries when the relcache is already populated by 6% in
a complex sample query involving large and wide partition tables.
> Optimize serialization of IMDId objects in Orca to be lazy

- gpMgmt/bin/analyzedb
- gpMgmt/test/behave/mgmt_utils/analyzedb.feature
- gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
Problem:
analyzedb does not include materialized views when preparing the list of tables to be analyzed.
Some refreshed materialized views have poor performance until analyzed.
Solution:
Updated the SQL statements in analyzedb that collect the list of tables to also include relkind='m' from pg_class.
This will add materialized views to the list of hash tables to be analyzed for each run.
> [7x]: Analyzedb add materialized views to list of tables to be analyzed

- src/backend/access/appendonly/README.md
- src/backend/access/appendonly/appendonlyblockdirectory.c
We can use the last cached minipage in the AppendOnlyBlockDirectory
structure during successive index only checks.
Today, index only scans on AO/CO tables have enormous per-tuple overhead
borne from the cost of starting, executing and tearing down short-lived
block directory sysscans.
This patch can result in a dramatic reduction in the number of these
shortlived sysscans, by referring to the last cached minipage. The best
case would be for highly correlated data where the next lookup would be
satisfied from the last cached minipage, with very high probability.
Example (TPC-H AO table of on-disk size 26GB, scale=30):
explain analyze select count(*) from lineitem where l_shipdate >= date '1994-01-01'
and l_shipdate < date '1994-01-01' + interval '1' year;
and we have a clustered b-tree …
> ao/co IndexOnlyScan: Use the last cached minipage

- src/backend/optimizer/path/costsize.c
- src/test/isolation2/input/uao/index_only_scan.source
- src/test/isolation2/output/uao/index_only_scan.source
- src/test/isolation2/output/uao/snapshot_index_corruption.source
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/expected/qp_indexscan.out
- src/test/regress/expected/qp_indexscan_optimizer.out
- src/test/regress/input/uao_dml/ao_covering_index.source
- src/test/regress/output/uao_dml/ao_covering_index.source
- src/test/regress/output/uao_dml/ao_covering_index_optimizer.source
- src/test/regress/sql/bfv_index.sql
- src/test/regress/sql/qp_indexscan.sql
This resolves to an extent #15914.
In this commit, we take into account the heavy cost of performing
repeated sysscans (begin -> getnext -> end) for each index tuple in
Index Only Scans on AO/CO block directory and visimap tables.
This massive overhead is not felt when the index is highly correlated.
We take that into account as well and interpolate our costs accordingly.
Since the block directory and visimap relstats aren't available on the
QD, we estimate the block directory relstats from the parent rel's
relstats and consider the visimap to be empty. This is an area that can
be definitely improved upon.
Testing reveals that with this patch, we are no longer wrongfully
choosing an Index Only Scan on un-correlated indexes created on lineitem
for TPC-H Q4, Q17, Q18, Q20, Q21, which was …
> ao/co: Update cost model for Index Only Scans

- gpMgmt/bin/gppylib/db/dbconn.py
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
The current logic uses string comparison to check the file mode, which results in a false warning on Python 3 due to the mode format difference ("0600" vs. "0o600"). We will get mode "0o600" on Python3, which will mismatch with "0600" and make a false warning.
https://github.com/greenplum-db/gpdb/blob/14fe09cb97419fc0f1e832c6baf764bf30ba2713/gpMgmt/bin/gppylib/db/dbconn.py#L39-L45
```
[gpadmin@gpcc-main gpcc_src]$ gpstop -air
20230906:07:01:00:742207 gpstop:gpcc-main:gpadmin-[INFO]:-Starting gpstop with args: -air
...
...
WARNING: password file "/home/gpadmin/.pgpass" has group or world access; permissions should be u=rw (0600) or less
...
...
20230906:07:01:09:742207 gpstop:gpcc-main:gpadmin-[INFO]:-----------------------------------------------------
20230906:07:01:09:742207 …
```
> Fix the wrong permissions warning on the pgpass file

- src/backend/commands/vacuum.c
- src/include/commands/vacuum.h
https://github.com/greenplum-db/gpdb/commit/05b333dfdc03d0477fafe132b10c0cfa2a19d5ae Introduced a check to only update pg_class statistics on the QD when all QEs' data was collected to avoid partial updates.
https://github.com/greenplum-db/gpdb/commit/249581df95ef4c5bbfca2d27e3e64681f35d8ff2 Reused infrastructure for updating relstats that both VACUUM and CLUSTER use to update QD pg_class stats.
We usually expect to receive one stats entry per relid from each QE. However, if indexes are present, we might receive multiple stats entries for the same relid and QE pair (for parent relations only) when performing operations that reindex relations as a side effect, such as VACUUM, CLUSTER etc. This is because index_update_relstats is called for the parent relation from the reindex code.
For …
> Fix regression with QD relstats update on doing VACUUM/CLUSTER

- src/backend/gporca/libgpopt/src/base/CColumnFactory.cpp
- src/backend/gporca/libgpopt/src/init.cpp
- src/backend/gporca/libgpopt/src/search/CSchedulerContext.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp
- src/backend/gporca/libgpos/include/gpos/common/DbgPrintMixin.h
- src/backend/gporca/libgpos/include/gpos/error/CMessageRepository.h
- src/backend/gporca/libgpos/include/gpos/memory/CCache.h
- src/backend/gporca/libgpos/include/gpos/memory/CCacheAccessor.h
- src/backend/gporca/libgpos/include/gpos/memory/CCacheFactory.h
- src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h
- src/backend/gporca/libgpos/src/_api.cpp
- src/backend/gporca/libgpos/src/common/CDebugCounter.cpp
- src/backend/gporca/libgpos/src/error/CMessageRepository.cpp
- src/backend/gporca/libgpos/src/memory/CAutoMemoryPool.cpp
- src/backend/gporca/libgpos/src/memory/CCacheFactory.cpp
- src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
- src/backend/gporca/libgpos/src/task/CTask.cpp
- src/backend/gporca/libgpos/src/task/CWorkerPoolManager.cpp
- src/backend/gporca/libnaucrates/src/init.cpp
- src/backend/gporca/server/src/unittest/CTestUtils.cpp
Refactoring. Declare methods as static if they work with static member variables only
- I made the CMemoryPoolManager::Cleanup method static, which was previously called only on the static object m_memory_pool_mgr.
- I made the CMemoryPoolManager::CreateMemoryPool method static, which was previously called only on the static object m_memory_pool_mgr.
- I made the CMemoryPoolManager::Destroy method static, which was previously called only on the static object m_memory_pool_mgr.
- I made the CMemoryPoolManager::GetGlobalMemoryPool method static, which was previously called only on the static object m_memory_pool_mgr.
- I made the CMemoryPoolManager::Shutdown method static, which was previously called only on the static object m_memory_pool_mgr.
- I made the CMessageRepository::Shutdown …
> [7X] Refactoring. Declare methods as static if they work with static member variables only

- gpdb-doc/markdown/ref_guide/modules/pgvector/pgvector.html.md
docs for https://github.com/greenplum-db/gpdb/pull/16384.  gporca doesn't support hnsw pgvector index types.
> docs - queries on hnsw indexes fall back to planner

- gpdb-doc/markdown/admin_guide/roles_privs.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
The configuration parameter password_encryption has changed from GPDB 6 to 7. Instead of a boolean, now it works the same way as Postgres password_encryption, which sets the encryption method for a role (either md5 or scram-sha-256). 
This PR updates the configuration parameter reference page, as well as updates the page Managing Roles and Privileges, which was still referencing old syntax for role configuration.
> Docs: updated the content of Managing Roles and Privileges page

- src/backend/postmaster/pgstat.c
- src/backend/utils/adt/pgstatfuncs.c
- src/backend/utils/resgroup/resgroup.c
- src/backend/utils/resgroup/resgroup_helper.c
- src/include/pgstat.h
- src/include/utils/resgroup.h
- src/test/isolation2/expected/resgroup/resgroup_move_query.out
For unassigned and bypassed query, still show resgroup information as before, but append "*" to end of the group name to imply it's a bypass query.
Improve the output warning when execute pg_resgroup_move_query for process in IDLE state.
> fix pg_Stat_activity display and Improve output warning when pg_resgroup_move_query

- gpdb-doc/markdown/admin_guide/query/topics/query-piv-opt-limitations.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
docs for https://github.com/greenplum-db/gpdb/pull/16260.
remove an item from unsupported features, update the optimizer_enable_indexonlyscan guc description.  didn't seem to be other doc areas that discussed this.
> docs - gporca supports indexonlyscan on gist for some ops

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
This issue was introduced by #15706. When ORCA translates multi-level partition table Relcache to DXL, it searches for the storage type of the leaf table and checks if the foreign table is a greenplum_fdw table. However, the none-leaf table is also checked, and an ERROR is thrown because the none-leaf table is not a foreign table.
Fix this issue by checking if the table is a foreign table first to avoid elog ERROR.
> Fix "cache lookup failed for foreign table" ERROR when ORCA handles multi-level partition table with foreign tables.

- src/backend/commands/vacuum.c
- src/test/regress/expected/vacuum_gp.out
- src/test/regress/sql/vacuum_gp.sql
Cherry-pick https://github.com/postgres/postgres/commit/74388a1ac36d2f0206c5477eeddc636d7947a5a4 and add a regress test. 
Resolves https://github.com/greenplum-db/gpdb/issues/15652
Avoid VACUUM reltuples distortion.
Add a heuristic that avoids distortion in the pg_class.reltuples
estimates used by VACUUM.  Without the heuristic, successive manually
run VACUUM commands (run against a table that is never modified after
initial bulk loading) will scan the same page in each VACUUM operation.
Eventually pg_class.reltuples may reach the point where one single heap
page is accidentally considered highly representative of the entire
table.  This is likely to be completely wrong, since the last heap page
typically has fewer tuples than average for the table.
It's not …
> Avoid VACUUM reltuples distortion

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
This PR changes the default value of guc gp_autostats_mode from `on_no_stats` to `none`. This change is due to the fact that now autovacuum handles collecting statistics.
> Docs: modified the default value of guc gp_autostats_mode

- gpdb-doc/markdown/utility_guide/ref/gpreload.html.md
This PR introduces a deprecation notice for gpreload on GPDB 7 in favour of ALTER TABLE REPACK BY COLUMNS.
> Docs: add deprecation notice for gpreload

- gpMgmt/bin/analyzedb
- gpMgmt/test/behave/mgmt_utils/analyzedb.feature
- gpMgmt/test/behave/mgmt_utils/steps/analyzedb_mgmt_utils.py
cherry-pick: #16410
Problem:
analyzedb does not include materialized views when preparing the list of tables to be analyzed.
Some refreshed materialized views have poor performance until analyzed.
Solution:
Updated the SQL statements in analyzedb that collect the list of tables to also include relkind='m' from pg_class.
This will add materialized views to the list of hash tables to be analyzed for each run.
> [6X Backport] - Analyzedb add materialized views to list of tables to be analyzed

- src/backend/catalog/heap.c
- src/backend/catalog/partition.c
- src/backend/commands/copy.c
- src/backend/commands/indexcmds.c
- src/backend/commands/tablecmds.c
- src/backend/commands/tablecmds_gp.c
- src/backend/commands/trigger.c
- src/backend/executor/execPartition.c
- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CPartPruneStepsBuilder.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/optimizer/util/plancat.c
- src/backend/parser/parse_partition_gp.c
- src/backend/parser/parse_utilcmd.c
- src/backend/partitioning/partbounds.c
- src/backend/partitioning/partdesc.c
- src/backend/utils/cache/partcache.c
- src/backend/utils/cache/relcache.c
- src/include/gpopt/gpdbwrappers.h
- src/include/partitioning/partdesc.h
- src/include/utils/partcache.h
- src/include/utils/rel.h
- src/test/regress/expected/create_table.out
- src/test/regress/sql/create_table.sql
This commit is heavily taken from an upstream commit: 5b9312378e2f8fb35ef4584aea351c3319a10422
That commit could not be backported directly due to the current ABI freeze for GPDB7.  In addition, there were multiple GPDB-only changes needed to route all rd_partdesc and rd_partkey accesses through the new RelationRetrievePartition* functions to ensure that there are no null pointer accesses for those fields.
This commit fixes a regression in partition behavior that can be observed if the dependencies of a partitioned table are altered during a single connection.  GPDB6 and previous, with classic partitioning syntax, handled this correctly, but modern syntax requires late loading of the partition description to match it.
Note that we disable optimizer during partition bound generation. Orca …
> Lazy load relcache partition data

- gpdb-doc/markdown/ref_guide/modules/greenplum_fdw.html.md
in this PR:  add a topic named "About Using Resource Groups to Limit Concurrency" to the greenplum_fdw module docs.  also changed some master refs -> coordinator.
questions:  are the CREATE RESOURCE GROUP statements correct and reasonable for this scenario?  is there any other info that would be helpful to the user?
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gp2gp-resgroups/greenplum-database/GUID-ref_guide-modules-greenplum_fdw.html#about-using-resource-groups-to-limit-concurrency
> docs - use resource groups to limit greenplum_fdw concurrency

- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
greenplum 7 supports madlib version 2.0.0.  update the docs.  (note:  separate PR for greenplum 6 will be forthcoming, not a direct backport.)
in this PR:
- assumed that greenplum 7 doesn't support madlib v1.x - let me know if this is not the case.
- upgrade from 1.x is not supported.  removed the upgrade topic for now, will add back in when madlib 2.1.0 is available
- un-tar'ing the package results in a madlib-xxx.gppkg.tar.gz file.  assuming that this can be provided directly to gppkg command.
- other misc edits
- update the platform requirements for madlib to specify v2.0.0 only.
> docs - update madlib docs for version 2.0.0 for gp7

- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
greenplum 6 supports madlib version 2.0.0 in addition to 1.x. update the docs.
in this PR:
- add Rerequisites section for m4.  if user installing v2.0, they also need to register python3u, added that to the preq section also.
- upgrade from 1.x to 2.x is not supported.  user can still upgrade 1.n -> 1.biggern, so kept that section.  will need to add a section for upgrading 2.x next madlib release.
- unlike the madlib 2.0 pkg for greenplum 7, the unpacked gp6 package suffix was .gppkg (not a .gppkg.tar.gz).
- other misc edits
- update the platform requirements for madlib to add v2.0.
> docs - add install instructs for madlib 2.0.0 for 6x

- src/backend/cdb/motion/ic_udpifc.c
This commit is inspired by https://github.com/greenplum-db/gpdb/pull/16353
This is not a direct cherry-pick as there were conflicts, so I did most of the changes manually.
`SendDummyPacket` eventually calls `getaddrinfo` (which is a reentrant), however, `getaddrinfo` is not an async-signal-safe function. `getaddrinfo` internally calls `malloc`, which is strongly advised to not do within a signal handler as it may cause deadlocks. Cache the accepted socket information for the listener, so that it can be reused in `SendDummyPacket()`.
The purpose of `SendDummyPacket` is to exit more quickly; it circumvents the polling that happens, which eventually times out after 250ms.
Without `SendDummyPacket()`, there will be multiple test failures since some tests expects the backend connection to …
> Remove `getaddrinfo` in `SendDummyPacket()` to address malloc deadlock

- gpcontrib/gp_toolkit/Makefile
PORTNAME is defined in Makefile.global, we can only use it after the
definition. But for extensions we also need to define the OBJS before
all the PGXS stuff.
This commit checks the operating system via `uname -s` instead, other
systems like Windows are not covered since Greenplum server is not
supported on them anyway.
> Fix the use of PORTNAME in gp_toolkit makefile

- src/backend/commands/resgroupcmds.c
- src/test/isolation2/input/resgroup/resgroup_io_limit.source
- src/test/isolation2/output/resgroup/resgroup_io_limit.source
There is a such example:
```
CREATE RESOURCE GROUP test WITH (CPU_MAX_PERCENT=20, MEMORY_LIMIT=25, io_limit = 'pg_default:rbps=1024,wbps=1024');
```
and then
```
ALTER RESOURCE GROUP test SET concurrency 10;
```
GPDB will throw some errors now.
That's because following reasons:
In `AlterResourceGroup`:
```
GetResGroupCapabilities(pg_resgroupcapability_rel, groupid, &oldCaps);
caps = oldCaps;
```
now, `caps.io_limit = oldCaps.io_limit`.
And then, in `alterResgroupCallback`:
```
if (callbackCtx->caps.io_limit != NIL)
cgroupOpsRoutine->freeio(callbackCtx->caps.io_limit);
if (callbackCtx->oldCaps.io_limit != NIL)
cgroupOpsRoutine->freeio(callbackCtx->oldCaps.io_limit);
```
io_limit has been double freed.
> io limit: fix double free

- src/backend/cdb/cdbcopy.c
- src/test/regress/input/gpcopy.source
- src/test/regress/output/gpcopy.source
Long log:
This pr can fix bug reported in https://github.com/greenplum-db/gpdb/issues/16250
The bug is introduced by https://github.com/greenplum-db/gpdb/pull/14989, which forgets to check the corner test case.
Solution: 	
set the default value of `first_segment_rows_completed` and `first_segment_rows_rejected` as 0
> Fix bug: copy to a replicated table from an empty file (7X)

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/bin/gppylib/system/environment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
- gpMgmt/test/behave/mgmt_utils/gpstate.feature
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Issue**: following are the gpMgmt utilities does not honor -d flag, when COORDINATOR_DATA_DIRECTORY is not set.
1. gpstart
2. gpstop
3. gpstatus
4. gprecoverseg
5. gpaddmirror
**RCA**: to get the coordinator data directory gp.getcoordinator_datadir() function is called from the above-listed utilties. The function do not have any provision to return the coordinator data directory which is provided with -d flag. currently, it looks for COORDINATOR_DATA_DIRECTORY and MASTER_DATA_DIRECTORY env variable.
Also in some of the utilities, we were creating a lock file before parsing the provided options which looks like a design flow that was causing the utilities to crash when looking for the coordinator data directory.
**Fix**: added a global flag that holds the datadirectory provided with the …
> [7X]Fix utilities does not honor -d flag when COORDINATOR_DATA_DIRECTORY is not set.

- src/backend/postmaster/pgstat.c
- src/backend/utils/adt/pgstatfuncs.c
- src/backend/utils/resgroup/resgroup.c
- src/backend/utils/resgroup/resgroup_helper.c
- src/include/pgstat.h
- src/include/utils/resgroup.h
- src/test/isolation2/expected/resgroup/resgroup_move_query.out
The first commit add a field ‘st_bypass_rsg’ of exported struct PgBackendStatus, even if it append at the end, this struct is included as middle element of other struct LocalPgBackendStatus which is also export, and the other commit also used the field ‘st_bypass_rsg’, revert both of them.
> Revert "fix pg_stat_activity display and Improve output warning"

- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/sql/alter_distribution_policy.sql
The test was flaky with a diff like:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/alter_distribution_policy.out	2023-09-19 15:30:40.631966743 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/alter_distribution_policy.out	2023-09-19 15:30:40.699971949 +0000
@@ -1725,7 +1725,7 @@
select check_redistributed('alter table t_reorganize set with (reorganize=true) distributed randomly', 't_reorganize', 't_reorganize');
check_redistributed
------------
- t
+ f
(1 row)
```
The reason is that table redistribution from random-to-random can happen to not change the number of rows on each segments. This was kinda expected during the PR preparation (https://github.com/greenplum-db/gpdb/pull/15795) but the chance that it happens is still higher than I would've hoped. Now …
> Fix flaky test alter_distribution_policy

- gpcontrib/Makefile
- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/expected/gp_toolkit.out
- gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
- gpcontrib/gp_toolkit/expected/resource_manager_restore_to_none.out
- gpcontrib/gp_toolkit/expected/resource_manager_switch_to_queue.out
- gpcontrib/gp_toolkit/gp_toolkit--1.1--1.2.sql
- gpcontrib/gp_toolkit/gp_toolkit.control
- gpcontrib/gp_toolkit/sql/gp_toolkit.sql
- src/test/isolation2/expected/aoco_column_rewrite.out
- src/test/isolation2/expected/misc.out
- src/test/isolation2/sql/aoco_column_rewrite.sql
- src/test/isolation2/sql/misc.sql
- src/test/regress/input/gp_check_files.source
- src/test/regress/output/gp_check_files.source
This commit mainly improves the gp_check_orphaned_files view in the sense that, since ultimately its user is likely going to remove the reported orphaned files, we would not like that to cause any potential issues due to causes like:
* Main relation files that are associated with dropped tables are kept until the next CHECKPOINT in order to prevent potential issue with crash recovery (see comments for mdunlink()). So removing them would have issue.
* Relation files that are created during an ongoing transactions could be recognized as orphaned: another session will see an old pg_class.relfilenode so it would think the new relfilenode is orphaned. So if one removes that, we might have data loss.
So accordingly, the improvements are:
* We should force a CHECKPOINT prior to collecting the …
> Improve gp_toolkit.gp_check_orphaned_files for more reliable results

- concourse/scripts/perfsummary.py
1) To determine whether the plan is using Orca or the postgres-based planner, we now need to also look for the string "GPORCA"
2) Some syntax errors were returned due to the planning time not being an int, so cast this to an int
> Fix explain pipeline performance summary script bugs

- src/test/regress/input/gp_tablespace_with_faults.source
- src/test/regress/output/gp_tablespace_with_faults.source
The test was flaky with a diff like:
```
@@ -397,9 +397,9 @@
(8 rows)
select list_tablespace_dbid_dirs(:expected_number_of_tablespaces, :'tablespace_location');
-                                 list_tablespace_dbid_dirs
+                                                 list_tablespace_dbid_dirs
------------
- {Success,"expected 1 tablespaces","found 1 tablespaces",/tmp/my_tablespace_for_testing/2}
+ {Failed,"expected 1 tablespaces","found 2 tablespaces",/tmp/my_tablespace_for_testing/2,/tmp/my_tablespace_for_testing/5}
(1 row)
```
The reason is that there's a chance the mirror has already replayed the WAL to create tablespace, so we can have two orphaned tablespace directories instead of one. Now make it panic even before we write the WAL to create tablespace to make it not flaky.
> Fix flaky test gp_tablespace_with_faults

- src/test/regress/input/gp_check_files.source
- src/test/regress/output/gp_check_files.source
This should have be done with #16428, but we need to disable autovacuum when running the gp_check_files regress test. Otherwise we might see errors like:
```
@@ -53,12 +53,8 @@
-- check orphaned files, note that this forces a checkpoint internally.
set client_min_messages = ERROR;
select gp_segment_id, filename from run_orphaned_files_view();
- gp_segment_id | filename
----------------+----------
-             1 | 987654
-             1 | 987654.3
-(2 rows)
-
+ERROR:  failed to retrieve orphaned files after 10 minutes of retries.
+CONTEXT:  PL/pgSQL function run_orphaned_files_view() line 19 at RAISE
reset client_min_messages;
```
In the log we have:
```
2023-09-20 15:33:00.766420 UTC,"gpadmin","regression",p148081,th-589358976,"[local]",,2023-09-20 15:31:39 …
```
> Fix a flakiness with test gp_check_files

- src/backend/gpopt/translate/CQueryMutators.cpp
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/subselect.sql
The ORCA optimizer could fallback to the legacy optimizer due to incorrect processing of nested SubLinks (SubLink contains one more SubLink or rtable subquery inside) during query normalization.
The erroneous behaviour took place when a query had a nested SubLink in its targetList and this SubLink was in GROUP BY clause itself (see the test section).
During query normalization for queries like in the tests the RunGroupingColMutator function is called. This function processed nested SubLinks incorrectly. It has Query code branch, which is supposed to be executed for various subqueries of the original query. However, for the nested SubLink case, when mutating the subquery of the SubLink (at second query level), the m_current_query_level field was not increased respectively, because …
> Fix ORCA invalid processing of nested SubLinks referenced in GROUP BY clause

- src/bin/pg_basebackup/t/010_pg_basebackup.pl
**CONTEXT**:
A previous commit
https://github.com/greenplum-db/gpdb/commit/bef7e82d270f422c975e57e5f83fa517fe83e1e8 had added a basebackup tap test to ensure that the primary WAL file containing the wal switch record (created by pg_basebackup) exactly matched the WAL file on the standby.
**PROBLEM**:
In order to get the name of the WAL file to compare, we used to rely on `pg_current_wal_lsn()` to return the "last WAL file" copied over by pg_basebackup to the standby server. This wasn't always reliable because because it's possible for newer WAL files to get created after pg_basebackup is run.
More specifically on 7X, insertion of "Standby" records can create new WAL files quickly enough for `pg_current_wal_lsn()` to not return the WAL file where pg_basebackup had stopped.
Because of this, …
> Fix flaky basebackup tap test that relied on pg_current_wal_lsn

- src/backend/gpopt/translate/CQueryMutators.cpp
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/subselect.sql
The ORCA optimizer could produce an invalid query plan and fallback to the legacy optimizer due to incorrect processing of nested SubLinks (SubLink contains one more SubLink or rtable subquery inside) during query normalization.
The issue could arise when query had a AggRef inside a Sublink and that AggRef contained one more SubLink inside (see the example of the query in the tests section).
While mutating the SubLink inside RunExtractAggregatesMutator, the Aggref branch is executed for SubLink's query targetList, which mutates args of the AggRef. And if inside this AggRef arg some Var had varlevelsup value greater than the m_agg_levels_up, i.e the Var referenced a relation that is higher than the AggRef (it's important to notice, that Aggref referenced the same relation), the Var was not …
> Fix ORCA invalid processing of nested SubLinks under aggregates.

- src/backend/commands/matview.c
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
This PR is trying to fix the issue #16447, the RCA for 7X could be found at [RCA for 7X](https://github.com/greenplum-db/gpdb/issues/16447#issuecomment-1725276402)
-----
The resolution is quite simple and direct: if an AO materialized view has indexes, create the block directory
for it.
> fix REFRESH MATERIALIZED VIEW on AO table with index

- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
**Issue:**
Currently, gprecoverseg performs rebalance operation (-r option) which is an incremental operation. To recover segments to a new host (-p option) operation is always a full recovery operation. 
Providing the `-F `flag along with the` -r `or -p option makes no sense. 
**Solution:**
To raise the exception when the Full Recovery option (-F)  is specified along with:
1. Recovery to new host (-p option)
2. Rebalance Operation (-r option)
Changes in this PR: 
- Raise error when -F option is passed with -r or -p
- Moved gprecoverseg flags validation to a separate function. 
- Added tests to verify rebalance and new host options.
> [7x]gprecoverseg: Raise exception when -F option is used in rebalance and recovery to new host options

- gpdb-doc/markdown/admin_guide/about-resgroups-changes.html.md
This PR creates a new page "About Changes to Resource Groups in Greenplum 7" which compares resource groups implementation between GPDB 6 and 7.
I still need to confirm more details on guc `gp_resource_group_move_timeout`. Feel free to suggest any changes.
staging site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-rg-changes/greenplum-database/admin_guide-about-resgroups-changes.html
> Docs resgroups new

- src/test/regress/greenplum_schedule
After #16469 we are still having the issue which however seems to be associated with a few platforms. Now doing the original fix which is to disable autovacuum for the test to make sure it won't get in the way of gp_check_orphaned_files in any way. Meanwhile will look at the platform-specific issue separately.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/flake-gpcheckfiles
> Disable autovacuum for flaky test gp_check_files

- src/backend/access/transam/xlog.c
- src/test/perl/PostgresNode.pm
- src/test/recovery/t/003_recovery_targets.pl
Backported from upstream
Original commit 1:
https://github.com/postgres/postgres/commit/dc788668bb269b10a108e87d14fefd1b9301b793
Backported with the change in the test:
diff:
```
- run_log(['pg_ctl', '-D', $node_standby->data_dir,
-		 '-l', $node_standby->logfile, 'start']);
+ run_log(['pg_ctl', '-D', $node_standby->data_dir, '-l', $node_standby->logfile, '-o', "-c gp_role=utility --gp_dbid=$node_standby->{_dbid} --gp_contentid=0 -c maintenance_mode=on", 'start']);
```
Before, if a recovery target is configured, but the archive ended before the target was reached, recovery would end and the server would promote without further notice.  That was deemed to be pretty wrong. With this change, if the recovery target is not reached, it is a fatal error. …
> Fail if recovery target is not reached

- gpMgmt/bin/gpcheckperf
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
- gpMgmt/test/behave/mgmt_utils/gpcheckperf.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Fixes - https://github.com/greenplum-db/gpdb/issues/16356
**Problem** - gpcheckperf provides different results when executing a sequential network test with a specified hostfile between versions 6.23 and 6.25.
**RCA** - The problem arises from the getHostList function, which assigns GV.opt['-h'] with a list of hosts because of which the code interprets that the -h option is set with the host list. As GV.opt['-h'] is already assigned during network testing, the code incorrectly combines hosts from both the GV.opt['-f'] option and GV.opt['-h'], when it should exclusively retrieve hosts from either GV.opt['-f'] or GV.opt['-h']. It leads to redundant host list data, resulting in the observed issue
**Solution** - Omit the assignment of the global variable GV.opt['-h'] within the "getHostList" …
> [6x]: Fix gpcheckperf discrepancy in network test results (v6.23 vs v6.25)

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
- gpMgmt/test/behave/mgmt_utils/gpstate.feature
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
cherry-pick  (#16433)
Issue: Following are the gpMgmt utilities that do not honor the -d flag, when MASTER_DATA_DIRECTORY is not set.
1. gpstart
2. gpstop
3. gpstate
4. gprecoverseg
5. gpaddmirror
RCA: to get the master data directory gp.getmaster_datadir() function is called from the above-listed utilities. the function does not have any provision to return the master data directory which is provided with the -d flag. currently, it looks for MASTER_DATA_DIRECTORY and MASTER_DATA_DIRECTORY env variable.
also in some of the utilities, we were creating lock files before parsing the provided options which looks like the design flow that was causing the utilities to crash when looking for the master data directory.
Fix: Added a global flag that holds the data directory provided with the -d …
> [6X backport]Fix utilities do not honor -d flag when MASTER_DATA_DIRECTORY is not set (#16433)

- src/backend/commands/matview.c
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
This is the backport of  #16465, to fix the issue #16447.
---
The resolution is quite simple and direct: if an AO materialized view has indexes, create the block directory
for it.
> [6X] fix REFRESH MATERIALIZED VIEW on AO table with index

- src/backend/cdb/cdbhash.c
- src/backend/cdb/cdbvars.c
- src/backend/executor/nodeModifyTable.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbhash.h
- src/include/cdb/cdbvars.h
- src/include/utils/sync_guc_name.h
- src/test/isolation2/expected/guc_gp.out
- src/test/isolation2/sql/guc_gp.sql
This is the backport of #16333
----
During OS upgrades, such as an upgrade from CentOS 7 to CentOS 8, there could be some
locale changes happen that lead to the data distribution or data partition position change.
In order to detect it, we add a new GUC of gp_detect_data_correctness, if it sets to on,
we will not insert data actually, we just check whether the data belongs to this segment or
this partition table or not.
> [6X] add a new GUC of gp_detect_data_correctness to detect data correctness during OS upgrade

- gpMgmt/bin/gpexpand
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Issue:**
Currently `gpexpand` errors out whenever it is run using a user-created input file (not created using the `gpexpand` interview process) on a cluster that has `custom tablespaces` created with the following error -
```
$ cat gpexpand_inputfile_20230914_201220
jnihal3MD6M.vmware.com|jnihal3MD6M.vmware.com|7005|/tmp/demoDataDir3|5|3|p
$ gpexpand -i gpexpand_inputfile_20230914_201220
20230914:20:13:04:066896 gpexpand:jnihal3MD6M:jnihal-[ERROR]:-gpexpand failed: [Errno 2] No such file or directory: 'gpexpand_inputfile_20230914_201220.ts'
```
**RCA:**
This is happening due to the commit 9b70ba8698f656c40ee62e5519314f7db1e4655e. This commit introduced a change, where it requires `gpexpand` to have a separate tablespace input configuration file (`<input_file>.ts`) whenever there are …
> gpexpand: Fix error when database has tablespaces

- gpcontrib/Makefile
- gpcontrib/gp_check_functions/Makefile
- gpcontrib/gp_check_functions/gp_check_functions--1.0.0.sql
- gpcontrib/gp_check_functions/gp_check_functions.c
- gpcontrib/gp_check_functions/gp_check_functions.control
- src/test/isolation2/expected/misc.out
- src/test/isolation2/sql/misc.sql
- src/test/regress/expected/.gitignore
- src/test/regress/expected/truncate_gp.out
- src/test/regress/greenplum_schedule
- src/test/regress/input/alter_db_set_tablespace.source
- src/test/regress/input/gp_check_files.source
- src/test/regress/input/gp_tablespace.source
- src/test/regress/output/alter_db_set_tablespace.source
- src/test/regress/output/gp_check_files.source
- src/test/regress/output/gp_tablespace.source
- src/test/regress/regress_gp.c
- src/test/regress/sql/.gitignore
- src/test/regress/sql/truncate_gp.sql
Backport from 6bbafd96d698740e3b8706de8c292ec0daa3a295 (original view), #15480 and #16428 (improvements).
-----------------
For 6X, we create a new extension called `gp_check_functions` instead of burning the function/views into `gp_toolkit`. The main reason is to avoid requiring existing 6X users to reinstall gp_toolkit which might have many objects depending on. Correspondingly, the views will be created under the default namespace. To use:
```sql 
create extension if not exists gp_check_functions;
select * from gp_check_missing_files; -- only checks main relation files
select * from gp_check_missing_files_ext; -- checks extended relation files too
select * from gp_check_orphaned_files; -- checks both main and extended files
```
Other adjustments:
* In 6X, external, foreign and virtual …
> [6X] Add views/functions to check missing and orphaned data files

- src/backend/catalog/namespace.c
- src/backend/cdb/dispatcher/cdbgang.c
- src/backend/cdb/dispatcher/test/cdbgang_test.c
- src/include/catalog/namespace.h
- src/test/isolation2/expected/orphan_temp_table.out
- src/test/isolation2/sql/orphan_temp_table.sql
Note that, commit e88ceb8e399074189160a8a2a2eb906bdfebbb12 fixed orphaned temp table left on coordinator, but it did't handle orphaned namespace catalog entry left on coordinator. This commit fix that.
> Fix orphaned temp namespace catalog entry left on coordinator

- src/backend/gporca/data/dxl/minidump/AssertMaxOneRow.mdp
- src/backend/gporca/data/dxl/minidump/CoveringIndex-1.mdp
- src/backend/gporca/data/dxl/minidump/CoveringIndex-2.mdp
- src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-InnerJoin.mdp
- src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-LeftJoin.mdp
- src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScanCosting.mdp
- src/backend/gporca/data/dxl/minidump/IndexNLJ-IndexGet-OuterRef.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnLeaf-NonOverlappingHeterogenousIndex-ANDPredicate-HEAP.mdp
- src/backend/gporca/data/dxl/minidump/IndexOnlyScanCosting.mdp
- src/backend/gporca/data/dxl/minidump/LogicalIndexGetDroppedCols.mdp
- src/backend/gporca/data/dxl/minidump/OverlappingHomogenousIndexesOnRoot-HEAP.mdp
- src/backend/gporca/data/dxl/minidump/PartTbl-DPE-DynamicIndexOnlyScan-Range.mdp
- src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp
- src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/IStatistics.h
- src/backend/gporca/libnaucrates/src/statistics/CStatistics.cpp
- src/test/regress/expected/dpe.out
- src/test/regress/expected/dpe_optimizer.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/sql/dpe.sql
**MOTIVATION**
----------------------------------------------------------------------------------------------------------------------
While creating 'Physical Scan Opertors', the statistics of base table are computed in function CPhysicalScan::ComputeTableStats().But while computing these statistics, the histograms for the columns of table are not generated as the columns of the table are not sent to CMDAccessor::Pstats(,,,,).
While costing (Dynaic)Index(only) scans, NDV of columns of table is required. The NDV cannot be calculated as the histograms were not generated during creation of scan operator.
**SOLUTION**
----------------------------------------------------------------------------------------------------------------------
To overcome this, function 'CStatistics::ComputeColStats …
> Compute statistics for a column of table

- src/backend/gporca/data/dxl/minidump/AllowIndexOnlyScanOnAppendOnlyTable.mdp
- src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InListLarge.mdp
- src/backend/gporca/data/dxl/minidump/DoubleNDVCardinalityEquals.mdp
- src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
We never scan the underlying append-optimized table relfile for
performing visibility checks. It's as if all blocks are all-visible. See
cdb_estimate_rel_size(). So consider dPartialVisFrac as 0.
This will make Index Only Scans more favorable on AO and CO tables.
Co-authored-by: David Kimura <dkimura@vmware.com>
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/orca_ios
> ao/co: Consider all blocks as all-visible in ORCA

- src/backend/gporca/data/dxl/minidump/CTE-NestedWithPrunedProducer.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CCTEInfo.h
- src/backend/gporca/libgpopt/src/base/CCTEInfo.cpp
- src/backend/gporca/libgpopt/src/base/CQueryContext.cpp
- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CCTETest.cpp
- src/test/regress/expected/qp_with_clause.out
- src/test/regress/expected/qp_with_clause_optimizer.out
- src/test/regress/sql/qp_with_clause.sql
In the case of nested CTE, additional care needs to be taken to remove
unused anchors that have no corresponding CTE consumer. Consider the
following query:
```sql
EXPLAIN WITH q AS (
SELECT * FROM (WITH cte AS (SELECT 1) SELECT 1) t)
SELECT * FROM q;
```
Prior to this commit, it produced two common table expressions:
1.
+--CLogicalCTEProducer (1), Columns: ["?column?" (1)]
+--CLogicalProject
|--CLogicalConstTableGet Columns: [(0)] Values: [(1)]
+--CScalarProjectList
+--CScalarProjectElement "?column?" (1)
+--CScalarConst (1)
2.
+--CLogicalCTEProducer (0), Columns: ["?column?" (3)]
+--CLogicalCTEAnchor (1)
+--CLogicalProject
|--CLogicalConstTableGet Columns: [(2)] Values: [(1)]
+--CScalarProjectList
+--CScalarProjectElement "?column?" (3)
+--CScalarConst (1)
However, `CLogicalCTEAnchor …
> [ORCA] Fix unused nested CTE pruning 

- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
- src/backend/optimizer/plan/subselect.c
- src/include/gpopt/gpdbwrappers.h
- src/include/optimizer/subselect.h
- src/test/regress/expected/qp_subquery.out
- src/test/regress/expected/qp_subquery_optimizer.out
- src/test/regress/sql/qp_subquery.sql
Previously, all subplans in Orca had the `useHashTable` parameter set to false. However, in certain cases, when the subplan testexpr is hashable and there aren't any outer refs, we can hash the subplan, which can significantly reduce execution time. This logic was taken from build_subplan in the planner code.
For example, consider the case:
```
explain analyze select a1,case when a2 in (select a1::text from a1 where a1 is not null) then 'true' else 'false' end as checkcol from (
select a1,rj->>'a1'::text as a2
from a3
)t;
```
The execution time decreased by 75% by using a hashed subplan in this case. Orca now produces the plan:
```
QUERY PLAN
-------------------------------------------------------------------------------------------
Result  (cost=0.00..1427188.70 rows=500000 width=12) …
```
> Hash subplans in Orca plans when possible

- src/backend/access/transam/xlog.c
- src/test/perl/PostgresNode.pm
- src/test/recovery/t/003_recovery_targets.pl
Backported from GPDB7: 
https://github.com/greenplum-db/gpdb/commit/a93ab09e380a62240e8ea99d1c17f5385def8673
with the following changes:
- In the TAP test framework added the `standby` parameter for the enable_restoring function to distinguish between standby and recovery which in GPDB7 is done via .signal files.
- In the TAP test put recovery_target_name into recovery.conf file instead of postgresql.conf
- In the TAP test added variables declaration.
Original GPDB7 commit message:
Backported from upstream with change in the test:
diff:
```
- run_log(['pg_ctl', '-D', $node_standby->data_dir,
-		 '-l', $node_standby->logfile, 'start']);
+ run_log(['pg_ctl', '-D', $node_standby->data_dir, '-l', $node_standby->logfile, '-o', "-c gp_role=utility --gp_dbid=$node_standby->{_dbid} …
```
> [6X_BACKPORT] Fail if recovery target is not reached

- src/backend/utils/mmgr/memprot.c
When memory usage have reached Vmem limit or resource group limit, it will loop in gp_malloc and gp_failed_to_alloc if new allocation happens, and then errors out with "ERRORDATA_STACK_SIZE exceeded".
We are therefore printing the log message header using write_stderr.
> print log message with write_stderr when reach vmem or resgroup limit

- src/backend/utils/mmgr/memprot.c
When memory usage have reached Vmem limit or resource group limit, it will loop in gp_malloc and gp_failed_to_alloc if new allocation happens, and then errors out with "ERRORDATA_STACK_SIZE exceeded".
We are therefore printing the log message header using write_stderr.
(cherry picked from commit a7210a4be2068abfe7c5e2ee135016d5b8c77cd8)
> (6x backport) print log message with write_stderr when reach vmem or resgroup limit.

- gpcontrib/gpcloud/test/s3restful_service_test.cpp
When curl with empty header to https://www.bing.com/, the response size used to be more than 10000, but it's not the case anymore, it's 5594 now, so update test to be more than 1000 to match the change
> [gpcloud] Update respsonse size from https://www.bing.com/

- gpcontrib/gpcloud/test/s3restful_service_test.cpp
When curl with empty header to https://www.bing.com/, the response size used to be more than 10000, but it's not the case anymore, it's 5594 now, so update test to be more than 1000 to match the change
> [gpcloud] [6X] [backport] Update respsonse size from https://www.bing.com/ 

- gpAux/extensions/gpcloud/test/s3restful_service_test.cpp
When curl with empty header to https://www.bing.com/, the response size used to be more than 10000, but it's not the case anymore, it's 5594 now, so update test to be more than 1000 to match the change
> [5X][gpcloud] Backport: Update respsonse size from https://www.bing.com/

- gpMgmt/bin/gpexpand
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This is a backport of https://github.com/greenplum-db/gpdb/pull/16444
**Issue:**
Currently `gpexpand` errors out whenever it is run using a user-created input file (not created using the `gpexpand` interview process) on a cluster that has `custom tablespaces` created with the following error -
```
$ cat gpexpand_inputfile_20230914_201220
jnihal3MD6M.vmware.com|jnihal3MD6M.vmware.com|7005|/tmp/demoDataDir3|5|3|p
$ gpexpand -i gpexpand_inputfile_20230914_201220
20230914:20:13:04:066896 gpexpand:jnihal3MD6M:jnihal-[ERROR]:-gpexpand failed: [Errno 2] No such file or directory: 'gpexpand_inputfile_20230914_201220.ts'
```
**RCA:**
This is happening due to the commit 9b70ba8698f656c40ee62e5519314f7db1e4655e. This commit introduced a change, where it requires `gpexpand` to have a separate …
> [6X Backport] gpexpand: Fix error when database has tablespaces

- gpdb-doc/markdown/install_guide/install_modules.html.md
- gpdb-doc/markdown/ref_guide/modules/gp_check_functions.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/toc.md
documents https://github.com/greenplum-db/gpdb/pull/15343.
in this PR:
- ported content from main PR (https://github.com/greenplum-db/gpdb/pull/16076) that added this info to gp_toolkit docs.
- noticed a new filepath column in gp_check_orphaned_files, added it.  is this column in 7/main?  i looked but didn't find it.
doc review site link (behind vpn): https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gp_check_functions/greenplum-database/GUID-ref_guide-modules-gp_check_functions.html
> docs - add gp_check_functions module docs

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/operations/rebalanceSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Backport of https://github.com/greenplum-db/gpdb/pull/16220
**Issue:** If there is a big gap between flush_lsn and replay_lsn on mirror then trigerring rebalance will cause a panic.
**Fix:** Added a check to WAL Replay Location of mirror. gprecoverseg rebalance should throw an exception if replay lag (flush_lsn - replay_lsn) on mirror is more than the default allowed limit (10 GB).
The default value for ALLOWED_REPLAY_LAG has been decided based on the experiments performed with different amount of replay lags on mirror. Below are the findings:
Purpose of experiments: Get the rough estimate of time mirror takes to replay different amount of wals
```
Replay_lag in bytes(flush_lsn - replay_lsn) | time taken by mirror to make replay_lag 0 …
```
> [6X] Abort rebalance if replay lag is big on mirror

- gpdb-doc/markdown/analytics/madlib.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
minor edits to supported platforms and madlib 6x install topic.
in this PR:
- use current version 2.1.0 in example package names
- add a new topic "Upgrading a MADlib 2.x Package" (for 2.n -> 2.higher_n)
> docs - gp6 supports madlib 2.1.0

- src/fe_utils/Makefile
- src/fe_utils/print.c
- src/fe_utils/test/Makefile
- src/fe_utils/test/print_test.c
When user try to select a big number of rows via PSQL, they may encounter the following error:
`ERROR: "Cannot add cell to table content: total cell count of XXX exceeded`. 
The root cause is the overflow of int type in `printTableAddCell()`. 
And this issue also exists in upstream, I have reported it (with repro steps) at:
https://www.postgresql.org/message-id/flat/TYBP286MB0351B057B101C90D7C1239E6B4E2A%40TYBP286MB0351.JPNP286.PROD.OUTLOOK.COM
Let's fix it in GP first since it takes a bit long time on the upstream side.
(needs to port to 6X later)
> Fix int overflow in printTableAddCell()

- src/backend/cdb/cdbvars.c
- src/backend/cdb/motion/ic_udpifc.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
- src/include/utils/sync_guc_name.h
Previous PR https://github.com/greenplum-db/gpdb/pull/13355 fixed https://github.com/greenplum-db/gpdb/issues/10314.
But it introduced a new bug: IC-UDP may hang forever in some scenarios (lots of IC instances in single one UDF), please see the discussion: https://github.com/greenplum-db/gpdb/pull/13411#issuecomment-1707865320
I want to improve it in this PR:
* for the non-read-only transaction, keep the previous logic (before PR-13355) to prevent the new bug.
* for the read-only transaction, introduce `gp_interconnect_cursor_ic_table_size` to config the size of Cursor History Table as a workaround (didn't think about a total solution).
> Improve prune behavior for the read-only transaction

- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_backend.h
- src/backend/cdb/motion/ic_proxy_main.c
- src/backend/cdb/motion/ic_tcp.c
- src/test/isolation2/expected/ic_proxy_listen_failed.out
- src/test/isolation2/isolation2_ic_proxy_schedule
- src/test/isolation2/script/start_py_httpserver.sh
- src/test/isolation2/sql/ic_proxy_listen_failed.sql
In IC-PROXY mode, user doesn't get a notification when peer listener bind/listen failed. Because the related code is in IC-PROXY process, it only records warning logs:
https://github.com/greenplum-db/gpdb/blob/f6ac62d91757118735ceb42dfdcc92ce7152e63c/src/backend/cdb/motion/ic_proxy_main.c#L193-L208
So, the user's query just hangs here silently. This behavior may make the user very confused.
In the PR, I introduced a SHM variable to check the failure and give notification in time, the output example:
```
$ nc -l 2001
...
ubuntu@gpdb:~/workspace/interma-gpdb$ PGOPTIONS="-c gp_interconnect_type=proxy" psql demo
demo=# select count(*) from test;
ERROR:  SetupInterconnect: We are in IC_PROXY mode, but IC-Proxy Listener failed, please check. (ic_tcp.c:1296)  (seg1 slice1 127.0.1.1:6001 …
```
> Check peer listener failed in IC-PROXY mode

- gpdb-doc/markdown/admin_guide/ddl/ddl-partition.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TABLE.html.md
in this PR:
- note the acquired lock difference for classic/modern when adding/attaching a partition in the "choosing the syntax" topic
- update ALTER TABLE reference page with some lock info for ATTACH (modern), ADD (classic).  note that the Description states ACCESS EXCLUSIVE unless otherwise stated, i highlighted this sentence.
> docs - note some partitioning ddl lock-related behaviours

- src/backend/gpopt/translate/CQueryMutators.cpp
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/expected/bfv_olap.out
- src/test/regress/expected/bfv_olap_optimizer.out
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/bfv_olap.sql
- src/test/regress/sql/subselect.sql
- src/test/regress/sql/subselect_gp.sql
This PR is a backport of 
* 3 patches related to improving ORCA behaviour when it normalizes the Query structure with nested SubLinks.
* 1 commit adding testcase for a fixed issue of panic in ORCA which is fixed by one of the patches.
> [6X backport] Fix ORCA nested SubLink processing during query normalization

- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
**Issue:**
When gprecoverseg is run with too many arguments then it errors out with an exception stack trace.
> [~/workspace/gpdb: {gprecoverseg_throttle_network} ?]$ gprecoverseg -B 10 abc
20231004:09:42:43:029461 gprecoverseg:sshirishaXG4C7:sshirisha-[INFO]:-Starting gprecoverseg with args: -B 10 abc
File "/usr/local/gpdb/lib/python/gppylib/mainUtils.py", line 351, in simple_main_locked
commandObject = createCommandFn(parserOptions, parserArgs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/gpdb/lib/python/gppylib/programs/clsRecoverSegment.py", line 565, in createProgram
raise ProgramArgumentValidationException("too many arguments: only options may be specified", True)
gppylib.mainUtils.ProgramArgumentValidationException: too many …
> Fix validation of too many arguments in gprecoverseg

- src/backend/cdb/cdbpath.c
The comments for create_split_update_path:
```
GPDB_96_MERGE_FIXME: the below comment is obsolete. Nowadays, SplitUpdate
computes the new row's hash, and the corresponding. target segment. The
old segment comes from the gp_segment_id junk column. But ORCA still
does it the old way!
Third, to support deletion, and hash delete operation to correct segment,
we need to get attributes of OLD tuple. The old attributes must therefore
be present in the subplan's target list. That is handled earlier in the
planner, in expand_targetlist().
```
For planner we use Explicit Redistribute Motion instead of Redistribute Motion above the split node,
So old attributes is useless to compute target segment id for Redistribute Motion.
remove above comments.
> resolve GPDB_96_MERGE_FIXME for SplitUpdate

- gpdb-doc/markdown/ref_guide/modules/pgaudit.html.md
The reference readme file is linked to the wrong version of README.md. This PR fixed it.
> [DOC][GP7] Fix pgaudit document.

- src/backend/tcop/postgres.c
Add the duration time into "canceling statement due to user request" to help the user
debug when canceling the query.
The log message will be
```
2023-10-10 03:32:55.325528 UTC,"smart","postgres",p463714,th1746153216,"[local]",,2023-10-10 03:32:01 UTC,
0,con32,cmd9,seg-1,,,,sx1,"ERROR","57014","canceling statement due to user request, duration:4256.617",,,,,,
"select * from t, t as t1, t as t2;",0,,"postgres.c",4053,
```
Not change the log schema.
> add duration if the query is canceled when it needs to be logged

- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
**Issue** - Even if the database is dropped before the recovery process, differential recovery still leaves behind orphaned directory for the dropped database under base directory. This issue only exists in 6X, in 7x `pg_internal.init` file is not added to the excluded list of rsync.
**RCA** - When a database is created, a file named pg_internal.init is also generated in the database directory. During the rsync process of pg_data, we intentionally exclude this pg_internal.init file (--exclude=pg_internal.init). However, because this file remains in the database directory and is excluded from rsync, it results in an error message stating "cannot delete non-empty directory: base/db_oid". As a consequence, it becomes problematic to delete the directory of a dropped database.
**Fix** - …
> [6x]: Cleanup orphaned directory of dropped database after differential recovery

- gpdb-doc/markdown/ref_guide/function-summary.html.md
gp_array_agg functions are in an extension/module in greenplum 6.x.  they are built in in greenplum 7.  include relevant info in the docs.
in this PR:
- fix an unrelated formatting error
- add the two gp_array_agg() aggregate functions to the table in the "Advanced Aggregates" topic in the ref guide.  based on some postgres array_agg ref info, and used some test examples.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gp_array_agg/greenplum-database/ref_guide-function-summary.html#advanced-aggregate-functions
> docs - include built-in gp_array_agg functions in ref guide

- README.Ubuntu.bash
> Add missing dep pyscopg2 for ubuntu readme

- src/backend/commands/collationcmds.c
The coordinator and all segments are required to have same set of collations.
This function was tuned to support MPP structure via DispatchCollationCreate,
but only for importing collations from libc. Once ICU enabled, it would fail.
This commit updated DispatchCollationCreate to support dispatching ICU
collations. New argument `provider` is added while unused `encoding` removed.
> Fix the import of ICU collations in pg_import_system_collations()

- gpMgmt/bin/gpstop
- gpMgmt/doc/gpstop_help
In 6x, The gpdb_pitr job encountered an indefinite delay while attempting to establish a connection with the database. This issue was investigated and resolved by specifying the 'utility=True' parameter when invoking the 'dbconn.Connect()'
function (https://github.com/greenplum-db/gpdb/pull/16413). Incorporating those changes to 7x to keep both versions in sync.
Other changes include moving the doc update in #16239 to 7x.
> [7x] Use utility mode when connecting to DB with dbconn.Connect()

- src/backend/access/common/reloptions_gp.c
- src/test/regress/expected/quicklz_fallback.out
- src/test/regress/sql/quicklz_fallback.sql
We should not directly use the return value of pg_strcasecmp.
> Fix missing check return value of pg_strcasecmp.

- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_backend.h
- src/backend/cdb/motion/ic_proxy_bgworker.c
- src/backend/cdb/motion/ic_proxy_main.c
- src/backend/cdb/motion/ic_tcp.c
- src/backend/postmaster/postmaster.c
- src/backend/storage/ipc/ipci.c
- src/include/cdb/ic_proxy_bgworker.h
My previous commit 8915cd09333961e203baf0255ca1a0f2c4d8607e caused coredump in some pipeline jobs.
Example stack:
```
Core was generated by `postgres:  7000, ic proxy process                                             '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000b46ec3 in pg_atomic_read_u32_impl (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics/generic.h:48
(gdb) bt
#0  0x0000000000b46ec3 in pg_atomic_read_u32_impl (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics/generic.h:48
#1  pg_atomic_read_u32 (ptr=0x7f05a8c51104) at ../../../../src/include/port/atomics.h:247
#2  LWLockAttemptLock (mode=LW_EXCLUSIVE, lock=0x7f05a8c51100) at lwlock.c:751
#3  LWLockAcquire (lock=0x7f05a8c51100, mode=mode@entry=LW_EXCLUSIVE) at lwlock.c:1188
#4 …
```
> Init ICProxy's SHM variable in CreateSharedMemoryAndSemaphores()

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/test/regress/expected/gp_covering_index.out
- src/test/regress/expected/gp_covering_index_optimizer.out
- src/test/regress/sql/gp_covering_index.sql
ORCA uses index_can_return() to check whether an index can return a
given column's data. The result determines whether an index-only-scan
plan is allowed. The function uses attno, however ORCA erroneously
passed the column number instead. This caused ORCA to incorrectly allow
an index-only-scan plan.
See get_relation_info() usage of index_can_return() attno for PLANNER.
> [ORCA] Fix bug checking index_can_return()

- concourse/scripts/ic_gpdb_resgroup.bash
- concourse/scripts/ic_gpdb_resgroup_v2.bash
- concourse/scripts/ic_resgroup.bash
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
Systemd would try to remove unused controllers. Those controllers activated
by gpdb scripts are not realized by systemd and is likely to be cleaned.
We tell systemd all controllers are required via `Delegate=yes` option
in some service, so the controllers get survived during the maintenance:
1) For pipelines, a transient service is applied to get there.
2) For normal runtimes, the greenplum-cgroup-v2-config service is
recommended in gpdb-doc.
Other minor fixes in this commit:
1) reduntant command `sudo su` removed in `enable_cgroup_subtree_control()`,
which benifits tracing of following remote commands.
2) option `-t` removed for `ssh` with shell heredoc, so avoid the warning
"Pseudo-terminal will not be allocated because stdin is not a terminal."
3) option `-n` added for `sudo` so we can …
> fix missing cgroup v2 controllers caused by systemd management

- src/backend/utils/adt/ruleutils.c
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
Long log:
This commit can fix the bug reported in https://github.com/greenplum-db/gpdb/issues/16558
Solution is simple, use `quote_identifier` to add quotes if needed.
Co-authored-by: Hovhannes Tsakanyan <thovhannes@vmware.com>
> Fix missing " in subpartition template name

- src/backend/executor/nodeHash.c
- src/backend/executor/nodeHashjoin.c
- src/backend/utils/workfile_manager/workfile_mgr.c
- src/include/executor/hashjoin.h
- src/include/utils/workfile_mgr.h
- src/test/regress/expected/zlib.out
- src/test/regress/expected/zlib_optimizer.out
- src/test/regress/sql/zlib.sql
1. Remove the max/min file size in the statistic info of temporary files, and add the average file size.
2. Include the statistic info of temporary files of the hash table and the outer table.
> Update the statistic info of hash join temporary files

- concourse/scripts/verify_gpdb_versions.bash
we have found several times the concourse task failed with `no URLs in mirrorlist` on this task, in order to reduce error, install the package in the docker image.
[GPR-1562]
> Remove yum install from verify_gpdb_versions task

- src/backend/cdb/motion/ic_udpifc.c
- src/backend/cdb/motion/test/Makefile
- src/backend/cdb/motion/test/cdbsenddummypacket_test.c
Previously on commit 70306db18e2, we removed pg_getaddrinfo_all for signal handlers. However, in doing so, the capability of supporting both AF_INET6 and AF_INET was lost; this responsibility must now be handled by us. The commit mentioned above fixed the issue for AF_INET (IPv4), but not for AF_INET6 (IPv6).
This commit addresses the situation for both AF_INET and AF_INET6.
> Accommodate for AF_INET6 when doing a motion layer IPC teardown

- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**First Commit:** Validate options with -o
Issue: There is no requirement of following flag combinations:
-         -o with -r: No need of output config file when rebalancing
-         -o with -i: Can't think of any valid usecase for this combination
Fix: gprecoverseg should raise an exception when invalid flags are used with -o
**Second Commit:**
Current behaviour: gprecoverseg -o outputs a config file containing the rows for each failed segment. But skips to add row for segment if failed segment is unreachable as it can't be recovered during the recovery process.
Requested behaviour: gprecoverseg -o should generate config file which contains row for each failed segment from gp_segment_configuration even if the failed segment host is unreachable. As the genarted config file can be …
> [7X] gprecoverseg: Fix behaviour of -o flag 

- src/backend/parser/analyze.c
- src/test/regress/expected/strings.out
- src/test/regress/sql/strings.sql
unknown-type constants and params in the SELECT's targetlist
are copied up as-is rather than being referenced as subquery
outputs.  This is to ensure that when we try to coerce them to
the target column's datatype.
This issued has been fixed in 7X in PR https://github.com/greenplum-db/gpdb/pull/9686
> 6X: Fix Insert Error with unknown type

- src/backend/optimizer/plan/planner.c
- src/test/regress/expected/bfv_aggregate.out
- src/test/regress/expected/bfv_aggregate_optimizer.out
- src/test/regress/sql/bfv_aggregate.sql
Partial Agg emitted reductant columns in targetlist especially on multi-stage agg scenario(upstream didn't have this concern since they don't have mutlistage-agg path).
```
postgres=# explain verbose SELECT b/2, sum(b) * (b/2) FROM t1  GROUP BY b/2 ORDER BY b/2;
QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=506.05..520.22 rows=1000 width=12)
Output: ((b / 2)), ((sum(b) * ((b / 2))))
Merge Key: ((b / 2))
->  Sort  (cost=506.05..506.88 rows=333 width=12)
Output: ((b / 2)), ((sum(b) * ((b / 2))))
Sort Key: ((t1.b / 2))
->  Finalize HashAggregate  (cost=486.25..492.08 rows=333 width=12)
Output: ((b / 2)), (sum(b) * ((b / …
```
> Fix redundant columns of mutlistage-agg plan

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/operations/rebalanceSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_rebalance_segment.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Check for replay lag during rebalance was introduced in commit d5f26a703a91735b4798630d0894326e9961513d. The default value of replay lag is set to 10 GB which can be configured through --replay-lag flag. Reverting the default value of replay lag as the user can configure to any required value. --disable-replay-lag flag is not required now as there will be no replay lag check by default.
> [6X] gprecoverseg rebalance: revert 10 GB default value for replay lag

- concourse/tasks/verify_gpdb_versions.yml
change to gcr.io/data-gpdb-public-images/gpdb6-rocky8-build image which includes git.
[GPR-1562]
> Update the verify_gpdb_versions task image

- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/gp_toolkit--1.2--1.3.sql
- gpcontrib/gp_toolkit/gp_toolkit--1.3.sql
- gpcontrib/gp_toolkit/gp_toolkit.control
- src/bin/pg_dump/pg_dump.c
- src/test/binary_swap/expected/pg_dumpall_current.out
- src/test/binary_swap/expected/pg_dumpall_other.out
- src/test/binary_swap/sql/pg_dumpall_current.sql
- src/test/binary_swap/sql/pg_dumpall_other.sql
- src/test/regress/expected/gp_upgrade_cornercases.out
- src/test/regress/sql/gp_upgrade_cornercases.sql
We did that when we made gp_toolkit an extension. All objects in the extension are under 'gp_toolkit' schema, but the extension itself is created under 'public' schema (`pg_extension.extnamespace` reflects that, and there's a `pg_depend` linkage between the extension and the schema). However, conventionally 'public' schema should not contain anything other than user themselves created. And in many cases the user would actually opt to drop the 'public' schema - and they now have to drop gp_toolkit extension before doing that (despite that nothing in gp_toolkit actually belong to 'public'), which is not nice.
So now we do not create the schema within the extension, but do that via the control file which implicitly creates the schema and use it for the extension. This removes the dependency …
> Do not create schema gp_toolkit within extension gp_toolkit

- src/backend/access/aocs/aocsam.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyblockdirectory.c
- src/include/cdb/cdbappendonlyblockdirectory.h
- src/test/isolation2/input/uao/fast_analyze.source
- src/test/isolation2/output/uao/fast_analyze.source
Extend usage of cache_mpentry_num for optimizing minipage entries lookup.
Prior to this patch, blkdir->cache_mpentry_num is only used for caching
minipage entry for tuple locating in ao_row ANALYZE context. This patch
extended its usage to common tuple fetch for both ao_row and ao_column.
> Extend usage of cache_mpentry_num for optimizing minipage entries lookup.

- src/backend/Makefile
In Gawk 5.0, regexp routines are replaced by Gnulib implementation, which only allows escaping specific characters. This patch fix the warning introduced in b3ad725.
Upstream PostgreSQL seems having the same issue.
> Fix awk script for Gawk 5.0~.

- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TABLE.html.md
the ALTER TABLE page defers to CREATE TABLE storage parameters section, so only one update required.
> docs - clarify fillfactor valid for heap tables only (7x)

- src/backend/utils/misc/timeout.c
dec17da7c9c "Fix the TimeoutId ABI breakage" did a workaround to avoid
the ABI breakage, but also made a conflict with the USER_TIMTOUTs
allocation mechanism, this commit fixes it.
> Fix the USER_TIMTOUTs allocation

- src/backend/access/table/table.c
- src/test/isolation2/expected/gdd/concurrent_insert_on_conflict.out
- src/test/isolation2/expected/gdd/concurrent_insert_on_conflict_optimizer.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/gdd/concurrent_insert_on_conflict.sql
This bug is introduced by #[13440](https://github.com/greenplum-db/gpdb/pull/13440)
When performing an INSERT ON CONFLICT operation, the target table is parsed with a RowExclusiveLock, which will call CdbTryOpenTable() with the same lock. If another transaction deletes the same table concurrently, try_table_open() returns nullptr. When GDD(Global Deadlock Detector) is enabled, this nullptr is fetched by RelationIsAppendOptimized, resulting in a segmentation fault.
This commit fixes this bug by adding a check with RelationIsValid(rel) to prevent fetching nullptr.
> Fix segmentation fault caused by concurrent INSERT ON CONFLICT and DROP TABLE

- gpdb-doc/markdown/admin_guide/external/g-using-the-greenplum-parallel-file-server--gpfdist-.html.md
As the title said, fix `gpfist` to `gpfdist`.
> [Doc] Fix a typo in gpfdist doc

- src/backend/cdb/cdbvars.c
- src/backend/executor/nodeHash.c
- src/backend/executor/nodeHashjoin.c
- src/backend/storage/file/buffile.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/workfile_manager/workfile_mgr.c
- src/include/cdb/cdbvars.h
- src/include/executor/hashjoin.h
- src/include/utils/sync_guc_name.h
- src/include/utils/workfile_mgr.h
- src/test/regress/expected/zlib.out
- src/test/regress/sql/zlib.sql
It's a back port of https://github.com/greenplum-db/gpdb/pull/16243. However, besides the port there are still some essential changes:
1. Removed the statistic info of max/min file size, and used average file size instead;
2. Included the work file number of not only hash table (for inner table), but also outer table;
3. Updated the test case zlib to compare work file number and compressed work file number to avoid checking accurate file number on different envs (planner vs. orca, 6X vs. 7X)
The changes should be forward-ported to 7X again after the PR is merged to keep the behaviors consistent.
> [6X] Add GUC gp_workfile_compression_overhead_limit for ZSTD buffer

- src/backend/cdb/endpoint/cdbendpointutils.c
- src/backend/commands/portalcmds.c
- src/backend/utils/init/postinit.c
- src/backend/utils/misc/timeout.c
- src/backend/utils/mmgr/portalmem.c
- src/include/cdb/cdbendpoint.h
- src/include/utils/portal.h
- src/include/utils/timeout.h
- src/test/isolation2/input/parallel_retrieve_cursor/status_check.source
- src/test/isolation2/output/parallel_retrieve_cursor/status_check.source
After the Parallel Retrieve Cursor was declared the session enters "idle in transaction" state and waits for new commands. 
And we can retrieve data from the root QE using a retrieve connection. However, If other QE raises an error, it will abort and
send the error to QD. But, QD remains in an "idle in transaction" state and does not handle the QE error, causing the root QE
was not  aware of the mistake, and continue running.
```
create table t1(a int);
insert into t1 values (-1);
begin;
explain declare c1 parallel retrieve cursor for  select count(*) from t1 group by  sqrt(a);
QUERY PLAN
------------------------------------------------------------------------------------------------
Finalize HashAggregate  (cost=716.00..721.00 rows=333 width=16)
Group Key: (sqrt((a)::double precision)) …
```
> 6X: Handle parallel retrieve cursor errors via timeout mechanism

- src/backend/cdb/motion/ic_udpifc.c
- src/backend/cdb/motion/test/Makefile
- src/backend/cdb/motion/test/cdbsenddummypacket_test.c
`SendDummyPacket` eventually calls `getaddrinfo` (which is a reentrant), however, `getaddrinfo` is not an async-signal-safe function. `getaddrinfo` internally calls `malloc`, which is strongly advised to not do within a signal handler as it may cause deadlocks. Cache the accepted socket information for the listener, so that it can be reused in `SendDummyPacket()`.
The purpose of `SendDummyPacket` is to exit more quickly; it circumvents the polling that happens, which eventually times out after 250ms.
Without `SendDummyPacket()`, there will be multiple test failures since some tests expects the backend connection to terminate almost immediately.
To view all the async-signal-safe functions, please view the signal-safety(7) — Linux manual page.
====================
Accommodate for AF_INET6 …
> [6X] Remove `getaddrinfo` in `SendDummyPacket()` to address malloc deadlock

- src/backend/access/appendonly/appendonlywriter.c
The return statement at the end of void function is redundant
> Remove return at the end of void functions

- src/bin/pg_basebackup/t/010_pg_basebackup.pl
Backported from GPDB main: https://github.com/greenplum-db/gpdb/commit/5f7452103edd20ed93f948416f0d34d544f374f1 and https://github.com/greenplum-db/gpdb/commit/bd1a975dcd962c42efb15e9f7b444f787fb16587
Note that we haven't observed this test being flaky on gpdb6 but it was flaky
on gpdb7. So we fixed it for gpdb7 and are backporting this since this is a
better way to compare wal files. More details on the flaky test can be
found on the 7X PR https://github.com/greenplum-db/gpdb/pull/16445
**CONTEXT:**
A previous commit
https://github.com/greenplum-db/gpdb/commit/a62bba858bad3395d1ecea14fe1ac3828dbb66ff
had added a basebackup tap test to ensure that the primary XLOG file
containing the xlog switch record (created by pg_basebackup) exactly
matched the XLOG file on the standby.
**PROBLEM:** …
> [6X_BACKPORT] Fix flaky basebackup tap test that relied on pg_current_xlog_location

- src/backend/cdb/cdbtm.c
- src/test/isolation2/expected/orphan_temp_table.out
- src/test/isolation2/sql/orphan_temp_table.sql
When session exits within a transaction block, temp table created in this session will be left. This is because `ResetAllGangs` will reset `myTempNamespace`, normal temp table catalog clean up won't be called. More details could ref
https://github.com/greenplum-db/gpdb/issues/16506.
Noted that, when a session is going to exit on coordinator, there is no need to drop temp tables by calling GpDropTempTables, callback function will do that at the end.
> Fix orphaned temp table on coordinator

- src/backend/optimizer/util/pathnode.c
fixme in create_ctescan_path is as bellow:
```
// GPDB_96_MERGE_FIXME: Why do we set pathkeys in GPDB, but not in Postgres?
// pathnode->pathkeys = NIL;    /* XXX for now, result is always unordered */
pathnode->pathkeys = pathkeys;
```
By now we can not find the commit info of why we use pathkeys in GPDB, but not in Postgres.
The codes "pathnode->pathkeys = pathkeys;" are already introduced after commit: 6b0e52bead. 
And I can not find much more infos in historical repos too.
Sometimes we can reduce extra sort path when the pathkeys of cte node and the pathkeys of subpath node are the same.
So we should keep these codes. Just remove GPDB_96_MERGE_FIXME.
```
explain WITH EmployeeCTE AS (
SELECT
employee_id,
employee_name,
salary 
FROM employees order by employee_id  
) …
```
> fix GPDB_96_MERGE_FIXME in create_ctescan_path

- src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
When ORCA transforms a SEMI join to an INNER join, a LogicalGbAgg is introduced in the inner side of the INNER join to remove duplicate inner keys. Subsequently, this join is attempted to be transformed into a LogicalIndexApply. ORCA determines if this transformation can be done by checking if the inner side's grouping columns contain all distribution columns.
However, when the inner side's distribution columns come from a RANDOM table, the checking always evaluates to true and allows the transform to proceed. But RANDOM distribution cannot satisfy this transformation because the same 'distribution' key may appear in different segments.
This commit resolves the issue by adding a check for the size of RANDOM distribution columns and forbidding the illegal transform.
Fix #16611
> Fix ORCA producing incorrect plan when handling SEMI join with RANDOM distributed table

- .abi-check/6.25.3/postgres.symbols.ignore
- .github/workflows/greenplum-abi-tests.yml
- The symbol 'ConfigureNamesInt_gp' is changed due to 11d915a908117278a0c2edcc92a63f8826b5bb07 [^1]. It's Greenplum specific GUC and it will not be referenced by other programs. So, it's safe to ignore it.
- We should always print the HTML report to stdout, even if the job is failed.
- I also enabled running ABI checking for pull-requests.
[^1]: https://github.com/greenplum-db/gpdb/commit/11d915a908117278a0c2edcc92a63f8826b5bb07
> [6X] Post fix for ABI checking pipeline.

- src/backend/gporca/libgpopt/include/gpopt/base/CColRefSet.h
- src/backend/gporca/libgpopt/src/base/CColRefSet.cpp
- src/backend/gporca/libgpos/include/gpos/common/CBitSet.h
This re-allows debugging via `colrefset->DbgPrint()`. Previously trying to do this resulted in an error, as both CColRefSet and CBitSet inherited from DbgPrintMixin.
> Fix CColRefSet's DbgPrint

- contrib/file_fdw/output/gp_file_fdw_optimizer.source
- contrib/postgres_fdw/expected/gp2pg_postgres_fdw_optimizer.out
- src/backend/gpopt/translate/CTranslatorUtils.cpp
Access to alias name will be necessary when hints reference the same
relation multiple times in a query (e.g. self-join). It provides a way
to distinguish each reference to the relation.
> [ORCA] Allow alias name to represent table name

- gpAux/Makefile
> Only create the ext/python3.9 folder when vendoring python3.9

- doc/src/sgml/ref/alter_table.sgml
The FOR (RANK) syntax is no longer supported in GP7. Remove it so psql helper command prints correct information. Also add two new GP7 syntaxes.
The doc page: https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-sql_commands-ALTER_TABLE.html . There are still a few minor inconsistencies, but I'm leaving them out for now because it would be more proper to address them in an overall effort that synchronizes those two doc sources, instead of spending cycles to fix each one by hand.
> Remove FOR (RANK) and add two new syntaxes in the ALTER TABLE sgml file

- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
This PR fixes an error with a provided query, it was still pointing to the old columns for table `pg_stat_activity`.
> Docs: fixed an error with provided query

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR documents the new guc gp_interconnect_cursor_ic_table_size for Greenplum 6.26
> Docs: new guc gp_interconnect_cursor_ic_table_size

- gpMgmt/bin/gppylib/gpparseopts.py
This commit can fix the bug reported in #16665 
Since Python 3.6, `re.LOCALE` can be used only with bytes patterns and is not compatible with re.ASCII.
> Fix bug: cannot use LOCALE flag with a str pattern

- src/pl/plpython/expected/plpython_test.out
- src/pl/plpython/sql/plpython_test.sql
> Add test case for PR-11946

- src/backend/tcop/postgres.c
This is the backport of #16557
------
Add the duration time into "canceling statement due to user request" to help the user
debug when canceling the query.
The log message will be
```
2023-10-10 03:32:55.325528 UTC,"smart","postgres",p463714,th1746153216,"[local]",,2023-10-10 03:32:01 UTC,
0,con32,cmd9,seg-1,,,,sx1,"ERROR","57014","canceling statement due to user request, duration:4256.617",,,,,,
"select * from t, t as t1, t as t2;",0,,"postgres.c",4053,
```
Not change the log schema.
> [6X] add duration if the query is canceled when it needs to be logged 

- src/backend/storage/file/gp_compress.c
It doesn’t make sense to compare variable resultingUncompressedLen with uncompressedLen inside function gp_decompress because they are always equal. So I think the best way is that we move the logic of function gp_decompress_generic into function gp_decompress, then remove function gp_decompress_generic.
> Refactor function gp_decompress

- src/backend/gporca/libgpopt/src/xforms/CXformJoin2IndexApplyGeneric.cpp
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
This is a backport of #16615
When ORCA transforms a SEMI join to an INNER join, a LogicalGbAgg is introduced in the inner side of the INNER join to remove duplicate inner keys. Subsequently, this join is attempted to be transformed into a LogicalIndexApply. ORCA determines if this transformation can be done by checking if the inner side's grouping columns contain all distribution columns.
However, when the inner side's distribution columns come from a RANDOM table, the checking always evaluates to true and allows the transform to proceed. But RANDOM distribution cannot satisfy this transformation because the same 'distribution' key may appear in different segments.
This commit resolves the issue by adding a check for the size of RANDOM distribution columns and forbidding the illegal …
> Fix ORCA producing incorrect plan when handling SEMI join with randomly distributed table 

- gpcontrib/gp_check_functions/Makefile
- gpcontrib/gp_check_functions/gp_check_functions--1.0.0--1.1.sql
- gpcontrib/gp_check_functions/gp_check_functions--1.1.sql
- gpcontrib/gp_check_functions/gp_check_functions.control
- src/backend/utils/adt/genfile.c
- src/test/regress/input/gp_check_files.source
- src/test/regress/output/gp_check_files.source
Backport from #16584. Changes applied:
* Add a commit to allow specifying absolute path for `pg_file_rename`.
* There's no cluster-wide system views such as `gp_settings`. Use `gp_dist_random('pg_settings')` instead.
* Add a new extension script for `1.1` besides the upgrade script `1.0.0--1.1`, because 6X does not support automatically upgrade to newer version via `CREATE EXTENSION` (which was supported in https://github.com/greenplum-db/gpdb/commit/40b449ae84dc). Also removed the current `1.0.0` script.
* Note that the new version is a two-number version 1.1 instead of three-number like 1.0.1, since it does not seem to make sense to have a three-number version in the first place. We cannot change the existing so just make future versions correct (thanks to @soumyadeep2007 to catch …
> [6X] UDF to move orphaned files

- src/backend/commands/tablecmds.c
- src/test/regress/expected/toast.out
- src/test/regress/sql/toast.sql
Fix #16650 .Commit d38d978 change 'swap_toast_by_link' to 'swap_toast_by_content' in order to avoid exchanging toast table names during distributed key alteration. However, 'swap_toast_by_content' requires rewriting the toast table with rd_toastoid as old relid, which is not set during the alter distributed key operation. As a result, the toast table becomes corrupted. So revert d38d978 to fix this issue.
> Revert d38d978 to fix wrong oid in toast tuple after change distributed key

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
Warning fixed:
```
../../../../src/include/nodes/nodes.h:656:68: warning: ‘right_arg’ may be used uninitialized in this function [-Wmaybe-uninitialized]
CTranslatorDXLToPlStmt.cpp:1198:23: note: ‘right_arg’ was declared here
1198 |                 Node *right_arg;
|                       ^~~~~~~~~
```
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/translator_warning?group=all
> Fix uninitialized-use warning in CTranslatorDXLToPlStmt.cpp

- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
This is a backport of [#16543](https://github.com/greenplum-db/gpdb/pull/16543)
**Issue:**
CM utilities like gpstart, gpstop, gpstate, gprecoverseg, gpaddmirror error out with an exception stack trace, when
- Arguments are provided without any option
- or, too many arguments are provided for an option.
> [~/workspace/gpdb: {gprecoverseg_throttle_network} ?]$ gprecoverseg -B 10 abc
20231004:09:42:43:029461 gprecoverseg:sshirishaXG4C7:sshirisha-[INFO]:-Starting gprecoverseg with args: -B 10 abc
File "/usr/local/gpdb/lib/python/gppylib/mainUtils.py", line 351, in simple_main_locked
commandObject = createCommandFn(parserOptions, parserArgs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/gpdb/lib/python/gppylib/programs/clsRecoverSegment.py", …
> [6X Backport] Fix error seen in CM utilities when invalid argument is provided

- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
This PR adds two new gucs to diskquota documentation, `diskquota.max_quota_probes` and `diskquota.max_monitored_databases`.
Staging site: https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-diskquota/greenplum-database/ref_guide-modules-diskquota.html#configuring-the-diskquota-module
> Docs: added two new diskquota gucs

- gpMgmt/bin/gppylib/operations/startSegments.py
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
**Issue 1** - While running gpstart with 64 segment nodes with 384 primary and 384 mirror,
a warning message is displayed: "`[WARNING]:-Number of segments which failed to start: 384.`"
However, when checking with "gpstate," all segments appear to be in a normal state.
**RCA** - When the batch size (-B) is less than the number of segments host gpstart starts
the mirror segment before the primary segment. From segment logs, we found out `pg_ctl -w start` 
for mirror is timeout out with a nonzero exit status. This leads to a warning
in gpstart for mirror segments - `[WARNING]:-Number of segments which failed to start: 384`.
The PR(https://github.com/greenplum-db/gpdb/pull/15994) introduced the changed pg_ctl start
with -w flag for Mirrors now wait until walreceiver is started to be marked as …
> [7x]: Fix  gpstart issues for large  segment host

- src/bin/gpfdist/regress/input/gpfdist_old_ssl.source
- src/bin/gpfdist/regress/output/gpfdist_old_ssl.source
Gpfdsits old ssl test cases are used for testing TLS1.0 and TLS1.1.
We have extracted these test cases to a standalone file in previous PR #16277 , but missed to start gpfdist for these test cases.
So, Add the steps to start/stop gpfdist
> Fix gpfdsits old ssl test cases for gp7

- src/test/isolation2/input/parallel_retrieve_cursor/explain.source
- src/test/isolation2/output/parallel_retrieve_cursor/explain.source
- src/test/regress/atmsort.pm
I got some plan header diffs when running regression with different GUCs, like:
which is not expected, the root cause is we only match `costs off` in atmsort.pm and miss other valid boolean values.
SQL like: EXPLAIN (COSTS OFF) will ignore segment info, other valid boolean values should also be recognized. ex:
EXPLAIN (COSTS OFF/FALSE/0).
I wouldn't say it's a bug, but it seems reasonable to make up.
> Fix gpdiff.pl should ignore infomation when explain ignore costs.

- src/backend/commands/tablecmds.c
- src/test/regress/expected/alter_distribution_policy.out
- src/test/regress/sql/alter_distribution_policy.sql
Currently we are doing `swap_relation_files` and a few other steps in ALTER TABLE DISTRIBUTE BY. However, we are missing some necessary steps such as renaming toast tables or clearing missing-attribute related stuff (RelationClearMissing). The `finish_heap_swap()` function which is used by the other ALTER TABLE commands should be used to take care of these general table-rewriting tasks (apart from toast table renaming, also including things like reindex of the old table and deletion of the new table). There should be no reason that ALTER TABLE DISTRIBUTED BY could not use `finish_heap_swap`. It appears that it is just at the time when the related changes of ALTER TABLE DISTRIBUTED BY was introduced, we did not have finish_heap_swap yet (e.g. …
> Use finish_heap_swap to swap relation files and else in ALTER TABLE DISTRIBUTED BY

- gpdb-doc/markdown/ref_guide/modules/gp_check_functions.html.md
- gpdb-doc/markdown/ref_guide/modules/intro.html.md
docs for https://github.com/greenplum-db/gpdb/pull/16645.  gp_move_orphaned_files() UDF added to the gp_check_functions module (a new module in greenplum 6.26).
note:  similar content will be added to the greenplum 7 gp_toolkit docs via a separate PR.
doc review site link (behind vpn):  https://docs-staging.vmware.com/en/draft/VMware-Greenplum/gp_check_functions/greenplum-database/GUID-ref_guide-modules-gp_check_functions.html#moving-orphaned-data-files
> docs - gp_move_orphaned_files() UDF (6x)

- src/backend/gporca/data/dxl/minidump/NdvPreservingExprProjectionEquiJoin.mdp
- src/backend/gporca/data/dxl/minidump/NdvPreservingExprProjectionNonEquiJoin.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalUnary.h
- src/backend/gporca/libgpopt/src/operators/CLogicalProject.cpp
- src/backend/gporca/libgpopt/src/operators/CLogicalUnary.cpp
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CProjectStatsProcessor.h
- src/backend/gporca/libnaucrates/src/statistics/CProjectStatsProcessor.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/join_hash_optimizer.out
When calculating the join cardinality, we lookup the histogram that corresponds to the colrefs in the join condition. However, when projecting a column such as `int+5`, we previously created a new colref with the new histogram as a default histogram with no buckets. This means that we lost all of the information about the underlying colref. When calculating the join cardinality, we then checked if any of the histograms are empty (ie: no buckets). If so, we set the cardinality as the max rows of the 2 histograms.
This PR utilizes the work done in
https://github.com/greenplum-db/gpdb/pull/16660, and improves the estimates for ndv-preserving scalar ops such as addition and subtraction. Now, when projecting a column of a scalar op with a constant, we'll use the histogram of the underlying …
> Improve cardinality estimation for projection of ndv-preserving columns

- src/backend/utils/error/elog.c
- src/pl/plpython/expected/plpython_test.out
- src/pl/plpython/sql/plpython_test.sql
> Fix bug of very long UTF-8 encoded query string truncation  [6X]

- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/segment_tablespace_locations.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_tablespace_locations.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
cherry-pick: https://github.com/greenplum-db/gpdb/pull/16195
Issue:
1. Post differential recovery more tablespace directory is created on the target segment.
[gpadmin@cdw ~]$ gpssh -f segment_host_list -v
[WARN] Reference default values as $COORDINATOR_DATA_DIRECTORY/gpssh.conf could not be found Using delaybeforesend 0.05 and prompt_validation_timeout 1.0 [Reset ...]
[INFO] login sdw2
[INFO] login sdw1
=> ls /tmp/mytblespace/
ls /tmp/mytblespace/
[sdw2] 4 5 6 7
[sdw1] 2 3 8 9
=> exit
[gpadmin@cdw ~]$ gpssh -f segment_host_list -v
[WARN] Reference default values as $COORDINATOR_DATA_DIRECTORY/gpssh.conf could not be found Using delaybeforesend 0.05 and prompt_validation_timeout 1.0 [Reset ...]
[INFO] login sdw1
[INFO] login sdw2
=> ls /tmp/mytblespace/
ls /tmp/mytblespace/
[sdw1] 2 3 4 5 …
> [6X Backport] Fix Differential recovery tablespace issue (#16195)

- src/backend/utils/misc/guc.c
- src/include/utils/guc_tables.h
This PR cherry-picked two commits from upstream, about being more wary about NULL values for GUC string variables.
- Commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=0bc726d95a305ca923b1f284159f40f0d5cf5725
- Commit: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7704a1a72e879daaefa1742916e01505edd2ce47
- Background issue reported: https://github.com/greenplum-db/gpdb/issues/16502
- Related PR: https://github.com/greenplum-db/gpdb/pull/16504
- Upstream discussion: https://www.postgresql.org/message-id/flat/CACpMh%2BAyDx5YUpPaAgzVwC1d8zfOL4JoD-uyFDnNSa1z0EsDQQ%40mail.gmail.com
> Be more wary about NULL values for GUC string variables.

- src/backend/gpopt/translate/CDXLTranslateContext.cpp
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/libgpos/include/gpos/error/CException.h
- src/backend/gporca/libgpos/server/src/unittest/gpos/string/CWStringTest.cpp
- src/backend/gporca/libgpos/src/common/clibwrapper.cpp
- src/backend/gporca/libgpos/src/error/CMessage.cpp
- src/include/gpopt/translate/CDXLTranslateContext.h
- src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
- src/include/gpopt/utils/COptTasks.h
- src/test/regress/expected/gp_locale.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/gp_locale.sql
ORCA represents strings using wide characters. That requires converting
to wide format using `vswprintf()`. However, that API may fail if the
string to covert is incompatible with the set LC_CTYPE character set.
That can happen if the database defined LC_CTYPE character set doesn't
support the client character set.
For example, if the database has LC_CTYPE set to 'C', but the client has
'ko_KR.UTF-8'. In that case, ORCA currently falls back to PLANNER
because converting to wide format fails.
A few possible solutions were considered:
1) Remove wide characters from ORCA
2) Use a 'good' LC_CTYPE while calling `vswprintf()`
3) Return a generic wide character string on failure
Solution 1 is very invasive. Solution 2 is tricky to pick a 'good'
LC_CTYPE. Solution 3 seems the simplest and is the …
> [ORCA] Relax client/server CTYPE encoding requirement

- src/backend/commands/tablecmds.c
- src/test/regress/expected/expand_table.out
- src/test/regress/sql/expand_table.sql
Similar to AT SET DISTRIBUTE BY, AT EXPAND TABLE also misses a few steps in swapping the existing table and temp table during the table-rewriting process (in fact, it probably used the exact same code as AT DISTRIBUTE BY). Therefore, similar to 001a1415f02b1c01b60913b205135c3692fcacdc, we should use finish_heap_swap in AT EXPAND TABLE as well.  
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/at-expand-toast
> Use finish_heap_swap to swap relation files and else in ALTER TABLE EXPAND TABLE

- gpdb-doc/markdown/analytics/pl_python.html.md
- GP7 Only python3.9, plpython2 has been dropped.
- Fix broken examples.
- Fix 0xAO problem -- invisible blank char in the plpython UDF body.
- Remove out-of-date documents.
> [DOC] Various fixes for plpython doc

- gpMgmt/bin/gppylib/mainUtils.py
- gpMgmt/test/behave/mgmt_utils/gpstop.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
This commit fixes the issue, where the `gpstop` errors out when there is an empty PID file in the `gpstop.lock` directory.
```
20231013:03:18:29:033818 gpstart:mdw:gpadmin-[CRITICAL]:-Error occurred: non-zero rc: 1
Command was: '$GPHOME/bin/gpstop -a -m -M immediate -d /data1/master/gpseg-1 -v -B 64'
rc=1, stdout='', stderr='Traceback (most recent call last):
File "/usr/local/greenplum-db-6.25.3/bin/gpstop", line 1098, in <module>
simple_main(GpStop.createParser, GpStop.createProgram, GpStop.mainOptions())
File "/usr/local/greenplum-db-6.25.3/lib/python/gppylib/mainUtils.py", line 263, in simple_main
simple_main_internal(createOptionParserFn, createCommandFn, mainOptions)
File "/usr/local/greenplum-db-6.25.3/lib/python/gppylib/mainUtils.py", line 288, in simple_main_internal
otherpid = …
```
> Fix ValueError exception if there is an empty lock directory

- gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsSystemState.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gpstate.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
Backport of https://github.com/greenplum-db/gpdb/pull/16460/
Issue : The "gpstate -e" command allows us to track full and incremental recovery progress. However, this functionality is not available for differential recovery.
Approach :  Show the progress stage-wise with rsync version 3.1.0 or above. We are synchronizing data for several components of the segment data directory, including pg_data, tablespace, pg_wal, and pg_control. Multiple rsync sessions will run sequentially for these components, and we want to track the progress of each stage. In rsync version 3.1.0 and above, the --info=progress2 option is available, which allows us to display cumulative progress information for a running rsync session. As each rsync session progresses, the cumulative progress information will be …
> [6x]: Added support for gpstate tracking for differential recovery

- gpcontrib/gp_toolkit/expected/gp_toolkit.out
- gpcontrib/gp_toolkit/expected/gp_toolkit_resgroup.out
- gpcontrib/gp_toolkit/sql/gp_toolkit.sql
The test was flaky with a diff like:
```
--- /tmp/build/e18b2f02/gpdb_src/gpcontrib/gp_toolkit/expected/gp_toolkit.out	2023-11-07 20:06:36.276652825 +0000
+++ /tmp/build/e18b2f02/gpdb_src/gpcontrib/gp_toolkit/results/gp_toolkit.out	2023-11-07 20:06:36.304655494 +0000
@@ -399,9 +399,11 @@
-- However it will show there is a difference if segment guc is different
-- primary_conninfo can be different due to failovers in isolation2 tests
select * from gp_toolkit.gp_param_settings_seg_value_diffs where psdname != 'primary_conninfo';
- psdname | psdvalue | psdcount
----------+----------+----------
-(0 rows)
+      psdname      |           psdvalue            | psdcount
+-------------------+-------------------------------+----------
+ primary_slot_name |                               |        2
+ …
```
> Fix a flakiness in gpcontrib/gp_toolkit test

- src/backend/cdb/cdbgroupingpaths.c
- src/backend/executor/nodeTupleSplit.c
- src/backend/nodes/copyfuncs.c
- src/backend/nodes/equalfuncs.c
- src/backend/nodes/outfuncs.c
- src/backend/nodes/readfuncs.c
- src/backend/optimizer/plan/setrefs.c
- src/include/nodes/execnodes.h
- src/include/nodes/primnodes.h
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
Support multi-dqa with normal agg
Although we have supported multi-dqa with new strategy named AGG_TUP_SPLIT in GP7 compared with GP6, 
normal agg is  hard to supported in multi-dqa using AGG_TUP_SPLIT, such as sql
“select count(distinct a), count(distinct b) ,sum(c) from t1 group by d;”
which have to back GroupAgg plan instread of using AGG_TUP_SPLIT. So this PR is aimed to bring
AGG_TUP_SPLIT back in normal agg case like above case, But there are also some limitations, in another hand,
some special corner cases can’t be supported and also back to groupAgg, we’ll certainly list them.
**Multi-dqa case:**
```
Select count(distinct a), count(distinct b) from t1;
Before ExecTupleSplit:
a  b
1  1
2  2 
After  ExecTupleSplit:
a  b  id(Aggexprid, junk column identify distinct column id) 
1 …
```
> support multi-dqa with normal agg

- gpdb-doc/markdown/admin_guide/perf_intro.html.md
- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
- gpdb-doc/markdown/install_guide/prep_os.html.md
- gpdb-doc/markdown/security-guide/topics/preface.html.md
This PR rephrases the current statement on the GPDB docs about anti-virus software:
- We broaden the term to refer to endpoint security instead of anti-virus.
- We do not state it is not supported, but instead that user should reach out to your vendor if any issues occur.
- There is a separate section within the Security guide instead of a Caution note so support can link customers to this section.
- Any other references in the GPDB documentation point to this new section in the Security Guide.
- This content will also be ported to the 6X documentation when approved.
Staging site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-antivirus/greenplum-database/security-guide-topics-preface.html
Other pages linking to new content: …
> Docs: relax requirements for anti-virus

- gpdb-doc/markdown/install_guide/platform-requirements-overview.md.hbs
- gpdb-doc/markdown/install_guide/prep_os.html.md
This PR updates the GPDB 6.x documentation to include:
- Support for RHEL/Rocky 9
- Added required dependencies for RHEL/Rocky 9
- Updated some of the configuration steps to include EL 8 and 9 versions.
Question: are there any required depencendies for VMware Greenplum Database 6 client software?
Note: there is another PR https://github.com/greenplum-db/gpdb/pull/16580 (merged) that provides instructions on how to change the default cgroups version for EL 9 to use resource groups.
> Docs: updated 6.X documentation to include EL 9 requirements

- gpdb-doc/markdown/utility_guide/ref/gpfdist.html.md
- gpdb-doc/markdown/utility_guide/ref/gpload.html.md
This PR modifies the description for the option MAX_LINE_LENGHT of gpload to align with -m option of gpfdist. Let me know if this is correct.
> Docs: edit the description for gpload option MAX_LINE_LENGHT

- src/backend/executor/execMain.c
gp2gp might encounter the issue when remote gpdb cluster has more segments than local gpdb cluster.
For example, local gpdb cluster has 3 segments and remote gpdb cluster has 4 segments.
```
testdb=# insert into l_tbl select * from f_tbl limit 10;
FATAL:  unexpected content id 3, should be [-1, 2]
before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```
We can reproduce the issue by steps below.
**Note: remote gpdb cluster must have more segments than local gpdb cluster.**
```
create extension greenplum_fdw;
create server gpdb_server foreign data wrapper greenplum_fdw options (host '10.117.190.206', port '7000', mpp_execute 'all segments', …
```
> [6X backport] Fix issue that segment index might be wrong in slice->segments

- contrib/postgres_fdw/expected/gp_postgres_fdw.out
- contrib/postgres_fdw/expected/gp_postgres_fdw_optimizer.out
- contrib/postgres_fdw/sql/gp_postgres_fdw.sql
- src/backend/optimizer/plan/createplan.c
For foreign table, if its remote server specifies the option `num_segments` and the value of option `num_segments` is larger than the number of local gpdb actual segments,
accessing such foreign table might encounter an issue as follows.
```
testdb=# insert into l_tbl select * from f_tbl limit 5;
FATAL:  unexpected content id 3, should be [-1, 2]
before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```
We can reproduce the issue by steps below.
```
create extension postgres_fdw;
create server multi_pg_servers foreign data wrapper postgres_fdw options (mpp_execute 'all segments', num_segments '4', multi_hosts '10.117.190.206 10.117.190.206 …
```
> Fix issue that segment index might be wrong in slice->segments

- src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
- src/test/regress/expected/join_gp.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/sql/join_gp.sql
fix issue https://github.com/greenplum-db/gpdb/issues/16688
ORCA performs the left join pruning at the preprocessing stage. For performing
the pruning operation ORCA creates a set of columns which are output by the
child operators. In the current implementation to generate the output columns
for the child operators following steps are performed
1.) Derive output columns of the logical parent operator
2.) If scalar operator is present
2a.) Derive used columns of the scalar operator
2b.) Create a set combining columns from step 1 and 2a
But for some operators like UNION where no scalar child is present ORCA was
creating a empty set of output columns for the child operators which was
leading to wrong pruning of left joins. This PR fixes that issue by modifying
the logic for computing output …
> Fix LeftJoinPruning pruns essential left join

- src/backend/cdb/motion/ic_proxy_backend.c
- src/backend/cdb/motion/ic_proxy_backend.h
- src/backend/cdb/motion/ic_proxy_bgworker.c
- src/backend/cdb/motion/ic_proxy_main.c
- src/backend/cdb/motion/ic_tcp.c
- src/backend/postmaster/postmaster.c
- src/backend/storage/ipc/ipci.c
- src/include/cdb/ic_proxy_bgworker.h
- src/test/isolation2/expected/ic_proxy_listen_failed.out
- src/test/isolation2/isolation2_ic_proxy_schedule
- src/test/isolation2/script/start_py_httpserver.sh
- src/test/isolation2/sql/ic_proxy_listen_failed.sql
This PR backported https://github.com/greenplum-db/gpdb/pull/16438 to 6x
----
In IC-PROXY mode, user doesn't get a notification when peer listener bind/listen failed. Because the related code is in IC-PROXY process, it only records warning logs. So, the user's query just hangs here silently. This behavior may make the user very confused.
In the commit, introduced a SHM variable to check the failure and give notification in time. An output example:
```
$ nc -l 2001
...
$ PGOPTIONS="-c gp_interconnect_type=proxy" psql demo
demo=# select count(*) from test;
ERROR:  SetupInterconnect: We are in IC_PROXY mode, but IC-Proxy Listener failed, please check. (ic_tcp.c:1296)  (seg1 slice1 127.0.1.1:6001 pid=189355) (ic_tcp.c:1296)
```
> 6X: Check peer listener failed in IC-PROXY mode

- gpdb-doc/markdown/ref_guide/modules/diskquota.html.md
The formula of `diskquota.table_segments` is confusing. The customer may get the wrong result and set the wrong GUC value.
> [DOC][GP7] Update diskquota doc

- src/bin/pg_config/pg_config.c
- src/common/config_info.c
Some [extension development framework](https://github.com/tcdi/pgrx/issues/1179) need to read pg_config at compile time to determine the Postgresql version.
We have an ABI incompatibility with Postgresql, but the output of pg_config is identical.
Modify the output of pg_config to allow such tools to determine the version of gp before compiling.
```
~/GPDB/gpdb_7X sa/gp_config ❯ ../install_7x/bin/pg_config                                                                                                                                                      15s ⎈ default 18:38:39
BINDIR = /home/sa/GPDB/install_7x/bin
DOCDIR = /home/sa/GPDB/install_7x/share/doc/postgresql
HTMLDIR = /home/sa/GPDB/install_7x/share/doc/postgresql
INCLUDEDIR = /home/sa/GPDB/install_7x/include
PKGINCLUDEDIR = …
```
> add gp version to pg_config

- src/backend/catalog/namespace.c
- src/backend/postmaster/autovacuum.c
- src/backend/storage/ipc/procarray.c
- src/include/catalog/namespace.h
- src/include/storage/procarray.h
- src/test/isolation2/expected/autovacuum-temp-table.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/autovacuum-temp-table.sql
One of important autovacuum duties in PostgreSQL is to process and drop leftover (orphan) temp tables. Usually, PostgreSQL backend handle temp tables when on exit (session end). But in some rare cases, backend may fail this step. For example, in backend is killed with `kill -9 $pid`, its temp tables will persist.
In Greenplum, temp tables uses different naming than in PostgreSQL, except tables created by UTILITY roles. So, proposed changes is to fix isTempNamespaceInUse to check if given namespace may be used by either some backend  (utility mode case) or belong to some session (dispatch case).
> Fix autovacuum to drop leftover temporary tables

- src/backend/cdb/dispatcher/cdbgang.c
- src/backend/cdb/dispatcher/cdbgang_async.c
- src/include/cdb/cdbgang.h
- src/test/regress/output/dispatch.source
Before this commit, any error from a segment that is unrelated to
recovery, would result in an immediate termination with the following:
ereport(ERROR, (errcode(ERRCODE_GP_INTERCONNECTION_ERROR),
errmsg("failed to acquire resources on one or more segments"),
errdetail("%s (%s)", PQerrorMessage(segdbDesc->conn), segdbDesc->whoami)));
In other words, this termination did not respect
gp_gang_creation_retry_count. From now on, we exhaust the retries first,
before emitting this ERROR.
Reviewed-by: Xin Zhang <xinzweb@users.noreply.github.com>
Reviewed-by: Huansong Fu <fuhuansong@gmail.com>
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gang_retry
> Retry gang creation for non-recovery failures

- src/test/regress/greenplum_schedule
Helps avoid flakes like:
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_main/jobs/icw_planner_icproxy_rocky8/builds/878
> icw: Disable autovacuum for col_proj test

- src/backend/cdb/cdbsubplan.c
- src/backend/optimizer/plan/subselect.c
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
After path refactoring of the planner in 7x, the path is alive instead of plan once one query block is finished. upstream has
considered this in commit https://github.com/postgres/postgres/commit/68fa28f77146653f1fcaa530d2f2f161bf5de479. So  for Greenplum we also need to consider those changes because subplan/initplan also is important for us especially on MPP.
For this issue, we should set splan->extParam as all plan done rather than just one query block done, so we moved 
splan->extParam work to SS_finalize_plan() which stand for all plans done and we try to finish set param job in last step.
> Fix PANIC for EXISTS query in planner

- gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
docs for https://github.com/greenplum-db/pgbouncer/pull/27.   the user can now provide an encrypted ldap password for pgbouncer.   this PR is against 6X_STABLE because the pgbouncer docs are pending addition to the main branch.   this content will be applied to main when that is in place.
in this PR:
- add new topic "About Specifying an Encrypted LDAP Password" to the pgbouncer using page.   includes requirements and example configuration.
- add descriptions of auth_key_file and auth_cipher to the pgbouncer.ini reference page.
questions:
1. it wasn't clear to me if any updates were required to the pgbouncer ldap intro docs (https://docs.vmware.com/en/draft/VMware-Greenplum/pgb-encpasswd/greenplum-database/admin_guide-access_db-topics-pgbouncer.html#configuring-ldap-based-authentication-for …
> docs - pgbouncer supports encrypted ldap password

- gpdb-doc/markdown/utility_guide/ref/gpstate.html.md
This PR adds a note to indicate the minimum version of rsync in order to view the tracking information for segments undergoing a differential recovery.
> Added rsync version requirement for gpstate -e

- src/test/regress/expected/function_extensions.out
- src/test/regress/expected/function_extensions_optimizer.out
- src/test/regress/sql/function_extensions.sql
The failure diff:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/function_extensions_optimizer.out	2023-09-19 15:16:27.567037328 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/function_extensions.out	2023-09-19 15:16:27.591039792 +0000
@@ -525,7 +526,7 @@
SELECT :num_temp_files_before = :num_temp_files_after;
?column?
----------
- t
+ f
(1 row)
```
In the log we can see what are the numbers:
```
2023-09-19 15:16:24.455922 ......"statement: SELECT 1 = 0;",,,,,,,0,,"postgres.c",1729
```
So it seems that some existing file just happened to be cleaned up at the same time, so the number-before > the number-after. We should allow such a case.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/flake-function_extensions
> Fix flaky test function_extensions

- src/include/utils/builtins.h
There are some duplicated definitions, some exist
since commit Initial Greenplum code dump.
Remove that for clean codes.
> Remove duplicated function definitions in builtins.h

- gpcontrib/gp_toolkit/resgroup.c
As the title said, fix typo `timestap` to `timestamp`.
> Fix typo timestamp

- src/backend/commands/exttablecmds.c
- src/bin/gpfdist/regress/input/gpfdist2.source
- src/bin/gpfdist/regress/output/gpfdist2.source
Long log:
This commit can fix the bug reported in #16753 
Without this commit, the last column name `time` and its name in FDW options `"time"` are different, shown as below, which leads to this error `column ""time"" of relation "test_quote_ext" does not exist`. 
``` sql
gpadmin=# \d test_quote_ext
Foreign table "public.test_quote_ext"
Column  |           Type           | Collation | Nullable | Default | FDW options 
---------+--------------------------+-----------+----------+---------+-------------
id      | bigint                   |           |          |         | 
item    | text                     |           |          |         | 
price   | integer                  |           |          |         | 
segment | integer                  |           |          |         | 
time    | …
```
> Remove quote_identifier in function list_join()

- src/backend/cdb/dispatcher/cdbdisp_query.c
- src/test/regress/expected/distributed_transactions.out
- src/test/regress/sql/distributed_transactions.sql
Backport from #16675. Clean merge, no conflict.
If there is an explicit BEGIN, and if the transaction only has SET command, we will begin transaction and setup DTX context on QEs at the time of the first SET command. So we need to add dtxSegments in SET to make sure we end the transaction at the time of END/COMMIT. This is required since b43629b where we no longer start DTX at the time of BEGIN.
However, we should not do this when there's NO explicit BEGIN. Because in that case, QEs will not have DTX context setup with the SET command, so if we decide to send DTX protocol command later (e.g. we have some direct-dispatch command that requires DTX with part of the QEs), we will send DTX protocol command to ALL dtxSegments. As a result, some QE might fail to …
> [6X] Fix SET command that sends DTX protocol command when shouldn't

- src/test/regress/expected/distributed_transactions.out
The test was added in https://github.com/greenplum-db/gpdb/commit/b055a88584fcc503ce8f5a85e7e4b49f04edfd53. Some query CONTEXT output is missing the output. Added now. (I don't remember exactly why it's missed, but definitely should've flown a pipeline for that PR).
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6x-dtx-test-failure
> Fix a test failure in distributed_transactions

- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/gp_toolkit--1.3--1.4.sql
- gpcontrib/gp_toolkit/gp_toolkit.control
- src/test/regress/input/gp_check_files.source
- src/test/regress/output/gp_check_files.source
Provide a UDF `gp_toolkit.gp_move_orphaned_files` to move orphaned files found by `gp_toolkit.gp_check_orphaned_files` into a location specified by user, which can then be removed/backup by the user later.
```sql
gp_toolkit.gp_move_orphaned_files(target_directory text)
```
~Under the target directory, files that belong to each segment will be put into a subdirectory for that segment. Under that subdirectory, maintain the nested directory tree of the file to be the same as the original data directory, for easier tracking. Create the subdirectory tree if not existed. In addition, we also attach a special suffix `.orphaned` to the file name in order to avoid confusion with normal data files which might lead to data loss (e.g. in case the user specified some path that would somehow …
> UDF to move orphaned files

- src/backend/tcop/postgres.c
- src/backend/tcop/test/postgres_test.c
The commit https://github.com/greenplum-db/gpdb/commit/be97c73d7131d57abf0178f2cf981f1895af9d2f added calling of `ereport()` to `StatementCancelHandler()` to print out more info. However, we need to avoid calling `ereport()`/`elog()` in signal handler. See the discussion: https://www.postgresql.org/message-id/flat/7E3165DE-601D-4930-A85F-35BD6318E1C2%40arenadata.io
With the calling, it's possible to hit deadlock in a corner case. See the scenario:
1. QE was waiting for message from QD.
2. QE received signal SIGINT from cancellation, and `StatementCancelHandler()` was called.
3. In `errstart()`,  `backtrace()` was called.
4. At the time, another signal SIGTERM was received, and `die()` was called. 
5. In `die()`, `backtrace()` was called again and we hit a hung because of re-entry of …
> remove ereport()/elog() from signal handler

- gpMgmt/bin/gppylib/commands/base.py
- gpMgmt/bin/gppylib/operations/package.py
Gppkg for Greenplum 7 is closed source and we don't ship it for OSS users. This patch helps suppress the error message when gppkg is missing.
> Don't emit critical error message when gppkg is missing.

- .abi-check/6.26.0/postgres.symbols.ignore
- .github/workflows/greenplum-abi-tests.yml
Files for skipping dumping symbols and types may not exist. We should
allow the absence of these files.
Also, the length of the symbol `ConfigureNamesBool_gp` is changed in
https://github.com/greenplum-db/gpdb/commit/12423cd2264a89fff1aaaee6a815574ea4d3e3c8 and it's a safe abi breaking change. This patch helps add it to
the `.abi-check/6.26.0/postgres.symbols.ignore` list.
To fix failed job: https://github.com/greenplum-db/gpdb/actions/runs/6952453627/job/18916224008
After my fix, the job is green: https://github.com/higuoxing/gpdb/actions/runs/6953806844
> [CI] Post fix for ABI checking pipeline.

- src/backend/commands/cluster.c
- src/backend/commands/typecmds.c
- src/include/commands/typecmds.h
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/sql/alter_table_set_am.sql
Unlike heap tables, append-optimized tables do not have an array type of
their base type created in the catalog. This is done to avoid catalog
bloat.
When changing AM from heap -> ao_row|ao_column, we weren't removing
this array type. Also, when changing AM from ao_row|ao_column -> heap,
we weren't adding this type into the catalog. This commit fixes that.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/setam_heap_fix_typearray
> ao/co: Manage array type during AM changes

- contrib/file_fdw/file_fdw.c
- contrib/file_fdw/input/gp_file_fdw.source
- contrib/file_fdw/output/gp_file_fdw.source
- contrib/file_fdw/output/gp_file_fdw_optimizer.source
- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
- src/backend/commands/analyze.c
- src/include/commands/vacuum.h
For file_fdw, the analyze method `fileAnalyzeForeignTable()` is just forked from upstream. There are no adaptation modifications for this analyze callback. So when the file_fdw foreign table in greenplum point to multiple files with mpp_execute option is set to `all segments`, it can not do all the sampling work from QD process, because the remote files may be stored on each segment which may be different hosts.
So this PR adds some adaptation work for the analyze callback function to deal with this situation. Also this PR tries to fix this issue: https://github.com/greenplum-db/gpdb/issues/16700
Pipeline link:https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-zhaorui
> Add analyze functionality for mpp file fdw.

- src/backend/access/brin/brin.c
- src/backend/access/index/indexam.c
- src/backend/executor/execIndexing.c
- src/include/access/brin_internal.h
- src/include/access/genam.h
- src/test/regress/expected/brin.out
- src/test/regress/expected/brin_optimizer.out
- src/test/regress/sql/brin.sql
This is a backport of upstream commit c1ec02be1d7 with some notable
adjustments:
(1) We don't backport the aminsertcleanup() AM routine, as that will
break ABI. Left merge fixmes with instructions for when that becomes
available.
~(2) Since we don't have REL14 commit c5b7ba4e67a, ExecOpenIndices() can
be called, even if ExecInsert() is never called (e.g. on QD or IIS with
no insert set). This means that ii_AmCache can be NULL, which means we
have to early return from index_insert_cleanup() if that is the case.
Left merge fixme with instructions for when that commit is absorbed.~
~(3) initialize_brin_insertstate() takes an isAO argument, like many
other BRIN routines. This avoids having to open the base relation to
figure out if this index is on an AO table or not.~
Note: the benefits of …
> Reuse BrinDesc and BrinRevmap in brininsert

- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/expected/gp_partition_maint.out
- gpcontrib/gp_toolkit/gp_partition_maint.c
- gpcontrib/gp_toolkit/gp_toolkit--1.3--1.4.sql
- gpcontrib/gp_toolkit/sql/gp_partition_maint.sql
- src/backend/catalog/partition.c
- src/include/catalog/partition.h
- src/include/partitioning/partbounds.h
This commit introduces the following UDFs and view to help users tackle
various partition maintenance tasks.
```
Helper UDFs:
pg_partition_rank()
- Rank of a non-default range partition among siblings (position of
partition in a hypothetical sorted array of siblings)
pg_partition_range_from()
- Lower range bound of a range partition
pg_partition_range_to()
- Higher range bound of a range partition
pg_partition_bound_value()
- Textual representation of the range bounds of a partition
pg_partition_isdefault()
- Checks if given partition is a default partition
pg_partition_lowest_child()
- Finds the lowest ranked child of given partition
pg_partition_highest_child()
- Finds the highest ranked child of a given partition
```
```
View:
gp_partitions: Equivalent of legacy view pg_partitions from …
```
> gp_toolkit: partition maintenance UDFs and views

- gpMgmt/bin/gppylib/commands/test/unit/test_unit_unix.py
- gpMgmt/bin/gppylib/commands/unix.py
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsSystemState.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gpstate.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstate_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
**Issue :** The "gpstate -e" command allows us to track full and incremental recovery progress. However, this functionality is not available for differential recovery.
**Approach :**  Show the progress stage-wise with rsync version 3.1.0 or above. We are synchronizing data for several components of the segment data directory, including pg_data, tablespace, pg_wal, and pg_control. Multiple rsync sessions will run sequentially for these components, and we want to track the progress of each stage. In rsync version 3.1.0 and above, the --info=progress2 option is available, which allows us to display cumulative progress information for a running rsync session. As each rsync session progresses, the cumulative progress information will be displayed on the terminal. The --info=progress2 option …
> [7x]: Added support for gpstate tracking of differential recovery

- src/backend/commands/tablecmds.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
This PR is to fix the issue https://github.com/greenplum-db/gpdb/issues/16769.
Now `CREATE EXTERNAL TABLE ... DISTRIBUTED REPLICATED` will fail because gpdb don't support it.
But `ALTER EXTERNAL TABLE ... SET DISTRIBUTED REPLICATED` will succeed. This is unreasonable.
```
// Fail
testdb=# create writable external table tmp_ext_table_gpfdist_writable (id int, category text) location ('gpfdist://localhost.localdomain:8801/testWritable.tbl') format 'custom' (formatter="delimited_in", delimiter=";;;") distributed replicated;
ERROR:  external tables can't have DISTRIBUTED REPLICATED clause
// Succeed (NOT reasonable)
testdb=# create writable external table tmp_ext_table_gpfdist_writable (id int, category text) location ('gpfdist://localhost.localdomain:8801/testWritable.tbl') format 'custom' …
```
> Disable SET DISTRIBUTED REPLICATED for ALTER EXTERNAL TABLE

- gpMgmt/bin/gpexpand
- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
This commit is a cherry-pick of the community PR #15961. In summary `gpexpand redistribution` earlier used to error out when the table would have been already expanded manually by the user or the table would have been damaged. This commit changes this behaviour so that any expanded/broken tables are skipped without affecting the redistribution for other tables.
> gpexpand: skip expanded/broken tables when redistributing

- src/backend/optimizer/prep/prepunion.c
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/sql/gp_recursive_cte.sql
In a recursive CTE, We can use union or union all to connect non-recursive part and recursive part.
If we use union, we should deduplicate the tuples.
However, from the following plan, Recursive union is executed on 3 segments,
this only deduplicates the tuples on its segment. there are duplicated tuples between different segments.
```
postgres=# explain with recursive x(a) as ( select a from tmp union select a+1 from x where a<10) select * from x;
QUERY PLAN                                      
--------------------------------------------------------------------------------------
-
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..126409.67 rows=2956100 width=4)
->  Recursive Union  (cost=0.00..86995.00 rows=985367 width=4)
->  Seq Scan on tmp  (cost=0.00..321.00 rows=28700 width=4) …
```
> fix results wrong while using union for recursive_cte

- src/backend/gporca/data/dxl/minidump/Least-Greatest-Subselect.mdp
- src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRef.mdp
- src/backend/gporca/data/dxl/minidump/SubqueryInsideArrayRefIndexList.mdp
- src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CICGTest.cpp
- src/backend/gporca/server/src/unittest/gpopt/minidump/CSubqueryTest.cpp
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
Currently, Query fallsback to the planner when a subquery is present in a ScalarMinMax (LEAST, or GREATEST) expression. In This PR, I am addressing the situation by incorporating the ScalarMinMax operator when processing scalar operators with subqueries.
setup:
create table foo (a int, b int) distributed by(a);
Before Fix:
```
explain (costs off) select foo.a from foo where foo.a <= LEAST(foo.b, (SELECT 1), NULL);
INFO:  GPORCA failed to produce a plan, falling back to Postgres-based planner
DETAIL:  Unexpected Operator Subquery in unexpected context
QUERY PLAN
----------------------------------------------------
InitPlan 1 (returns $0)  (slice2)
->  Result
->  Seq Scan on foo
Filter: (a <= LEAST(b, $0, NULL::integer))
Optimizer: Postgres-based …
```
> Fix query fallback when subqury present within LEAST()/GREATEST()

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/bin/gppylib/commands/pg.py
- gpMgmt/bin/gppylib/commands/test/unit/test_unit_pg_base_backup.py
- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
- gpMgmt/bin/gppylib/test/unit/test_unit_gpsegrecovery.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recovery_base.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/sbin/gpsegrecovery.py
- gpMgmt/sbin/recovery_base.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
As part of this PR, an option is introduced to throttle network speed during full recovery of a segment.
`--max-rate` option is added in gprecoverseg utility to tune the speed at which recovery should happen.
Its value can range from `32KB/s to 1048576KB/s(1024MB/s).`
This is an optional argument and if not passed then it takes entire available network bandwidth for Full recovery of failed segments.
gprecoverseg uses pg_basebackup as an underlying utility for transfer of data-directories in case of Full recovery.
`pg_basebackup` has a existing 'max-rate' option provided as an option to the user to control the rate at which data-directory can be transferred. This utility is now introduced in gprecoverseg also, using which the user can tune the rate of full recovery and thereby preventing …
> Implementation of network throttling in gprecoverseg

- concourse/scripts/compile_gpdb.bash
because these platform support system libzstd 1.4.4
[GPR-1624]
> Rocky8/oel8/rhel8 needs zstd 1.4.4 to be vendored

- contrib/tsm_system_rows/tsm_system_rows.c
- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/include/utils/guc.h
- src/include/utils/sync_guc_name.h
- src/test/isolation2/Makefile
- src/test/isolation2/input/uao/tablesample.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/tablesample.source
This PR contains a couple of bug fixes for CO analyze infrastructure, a commit to update pg_statio.blks_read for sampling, and then the commit to support BERNOULLI/SYSTEM TABLESAMPLE for AO/CO tables. The main tablesample commit also adds implicit coverage for the 2 bug fixes.
Supporting commits for tsm_system_rows and tsm_system_time have also been added.
Finally, a dev GUC has been added for devs to toggle between blkdir and non-blkdir based analyze for ease of testing.
Please refer to individual commit messages for details.
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/tsamplev2?group=all
> ao/co: Support TABLESAMPLE

- src/backend/cdb/dispatcher/cdbdisp_async.c
- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/input/resgroup/enable_resgroup.source
- src/test/isolation2/output/resgroup/enable_resgroup.source
Current check order of reserve memory for resource group: 1. reserve memory from the resource group slot 2. if the slot quota exceeded, reserve memory from the group shared 3. then reserve memory from the global free chunk.
If group 2 over use the global freeChunks, even group 1 has enough group share free space to alloc, it will still check global freeChunks value and get MemoryFailure_ResourceGroupMemoryExhausted error.
Check global freeChunks only when group shared memory are over used.
> fix resource group reserve memory

- GNUmakefile.in
Migrate changes https://github.com/greenplum-db/gpdb/pull/14150 to gpdb7.
The test for tablefunc extension is enabled: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-lxy-rhel8/jobs/icw_planner_rhel8/builds/1#L647c1c1b:3915
> Enable tablefunc extension in gpdb7

- gpdb-doc/markdown/ref_guide/modules/tablefunc.html.md
https://github.com/greenplum-db/gpdb/pull/16641 adds tablefunc to the 7 greenplum distribution.  we already have docs for this module, same as in greenplum 6:  https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/ref_guide-modules-tablefunc.html.
this PR updates the postgres xref to point to v12 version of the docs.
question:  these docs have been in greenplum 6 for a while.  let me know if i should create docs based on the postgres docs rather than link off.
> docs - tablefunc to xref to pg v12 docs

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/LeftSemiJoinWithRepOuterTab.mdp
- src/backend/gporca/server/CMakeLists.txt
- src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
- src/test/regress/expected/join_gp.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/sql/join_gp.sql
**Problem**
---------------------------------------------------- 
ORCA generated incorrect plan while doing "Left Semi Join with replicated outer table" . Duplicated rows were observed in the output.
Note - This problem is also solved for 'Main' branch in PR -[16767](https://github.com/greenplum-db/gpdb/pull/16767)
**Wrong Output:**
----------------------------------------------------
SETUP
```
create table repli_t1 (a int) distributed replicated;
insert into repli_t1 values(1);
analyze repli_t1;
create table dist_t1 (a int , b int) distributed by (a);
insert into dist_t1 select i, 1 from generate_series(1, 100) i;
analyze dist_t1;
```
Query -
`select * from repli_t1 where exists ( select 1 from dist_t1 where repli_t1.a >= dist_t1.b);`
```
explain analyze select * from repli_t1 where …
```
> Fix incorrect ORCA plan for "Left Semi Join with replicated outer table"

- src/backend/utils/resgroup/cgroup-ops-linux-v1.c
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
- src/backend/utils/resgroup/cgroup.c
- src/include/utils/cgroup.h
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Add one more hierarchy for resource group when use cgroup v2.
Current leaf node in the gpdb cgroup hierarchy is: `/sys/fs/cgroup/gpdb/<oid>`, it's ok for gpdb workflow. But for some extensions which want to use gpdb cgroup hierarchy, it's not convenient.
Extensions like `plcontainer` want create sub-cgroup under `/sys/fs/cgroup/<oid>` as new leaf node, it's not possible in current hierarchy, because of `no internal processes` constraint of cgroup v2.
This commit use a new hierarchy to adopt extensions which want to use gpdb cgroup hierarchy, and the modification is tiny: move processes from `/sys/fs/cgroup/<oid>/cgroup.procs` to `/sys/fs/cgroup/gpdb/<oid>/queries/cgroup.procs`, and keep limitations in `/sys/fs/cgroup/<oid>`.
With this modification, extensions which want to use gpdb cgroup …
> Add one more hierarchy for resgroup cgroup root

- src/backend/executor/nodeAgg.c
- src/backend/executor/nodeAppend.c
- src/backend/executor/nodeBitmapHeapscan.c
- src/backend/executor/nodeGroup.c
- src/backend/executor/nodeHash.c
- src/backend/executor/nodeHashjoin.c
- src/backend/executor/nodeIndexonlyscan.c
- src/backend/executor/nodeIndexscan.c
- src/backend/executor/nodeLimit.c
- src/backend/executor/nodeLockRows.c
- src/backend/executor/nodeMaterial.c
- src/backend/executor/nodeMergeAppend.c
- src/backend/executor/nodeMergejoin.c
- src/backend/executor/nodeModifyTable.c
- src/backend/executor/nodeNestloop.c
- src/backend/executor/nodeRecursiveunion.c
- src/backend/executor/nodeResult.c
- src/backend/executor/nodeSubplan.c
- src/backend/executor/nodeTidscan.c
- src/backend/executor/nodeUnique.c
- src/backend/executor/nodeWindowAgg.c
Backport this commit to fix a hung case in cancellation of request.
commit d47cfef7116fb36349949f5c757aa2112c249804
Author: Andres Freund <andres@anarazel.de>
Date:   Tue Jul 25 17:37:17 2017 -0700
Move interrupt checking from ExecProcNode() to executor nodes.
In a followup commit ExecProcNode(), and especially the large switch
it contains, will largely be replaced by a function pointer directly
to the correct node. The node functions will then get invoked by a
thin inline function wrapper. To avoid having to include miscadmin.h
in headers - CHECK_FOR_INTERRUPTS() - move the interrupt checks into
the individual executor routines.
While looking through all executor nodes, I noticed a number of
arguably missing interrupt checks, add these too.
Author: Andres Freund, Tom Lane
Reviewed-By: …
> Checking interrupt more frequently in HashJoin

- src/backend/parser/gram.y
- src/test/regress/expected/partition.out
- src/test/regress/expected/partition_optimizer.out
- src/test/regress/sql/partition.sql
We should not allow subpartition by clause when creating empty partition hierarchy with modern syntax (`CREATE PARTITION BY` ... without creating any partitions and then later on adding partitions by `CREATE TABLE PARTITION OF`...).
Example:
`CREATE TABLE foo(i int, j int) PARTITION BY range(i) SUBPARTITION BY range(j);`
Here the info about subpart by j is lost.
This is because the info in the subpartition by clause is currently lost. Partitions attached henceforth don't obey the partition policy of the top level. So, ban it outright - it is a bad mixture of upstream and legacy syntax.
> Disallow SUBPARTITION BY clause when creating empty partition hierarchy

- src/backend/commands/trigger.c
- src/test/regress/expected/foreign_key_gp.out
- src/test/regress/expected/triggers_gp.out
- src/test/regress/greenplum_schedule
- src/test/regress/parallel_schedule
- src/test/regress/sql/foreign_key_gp.sql
- src/test/regress/sql/triggers_gp.sql
Foreign key constraint is not supported in GPDB. However, the expected behavior is that we should ignore the constraint and there shouldn't be errors.
But before this commit we would encounter an ERROR when performing INSERT on an AOCO table that has foreign key constraint:
```sql
CREATE TABLE a(id int primary key);
CREATE TABLE b(id int references a) WITH (appendonly=true, orientation=column); 
WARNING:  referential integrity (FOREIGN KEY) constraints are not supported in Greenplum Database, will not be enforced
INSERT INTO b VALUES (1);
ERROR:  Trigger is not supported on AOCS yet (trigger.c:2714)  (seg4 #######:16004 pid=3948271) (trigger.c:2714)
```
The error message, which was for the purpose of disabling row trigger for AO/CO tables, got in the way of ignoring foreign key …
> Do not throw error for INSERT into a table w/ foreign key constraint

- src/bin/pg_dump/pg_dumpall.c
In order to support 6 > 7 upgrade using pg_upgrade. 7x pg_dumpall needs to be able to dump 6x resource groups correctly. Supporting the dumping of 6x resource group resolves the following error with trying to upgrade from 6 > 7.
```
ALTER RESOURCE GROUP "default_group" SET cpu_weight 0;
psql:pg_upgrade_dump_globals.sql:27: ERROR:  cpu_weight range is [1, 500]
```
This happens because some of the attribute ordering in pg_resgroupcapability changed from 6x to 7x. To resolve this issue, the following mapping was done based on 6x and 7x resource group docs. New attribute cpu_weight is set to 7x default value of 100.
```
6x             |  7x
---------------+-----------------
concurrency    | concurrency
cpu_rate_limit | cpu_max_percent
100            | cpu_weight
cpuset         | cputset
``` …
> pg_dumpall: dump 6x resource groups correctly for 6 > 7 upgrade

- .abi-check/7.0.0/postgres.symbols.ignore
The signature of `CreateDir` has been changed in #16732  which is unlikely expected to be used by the outside world. Just add it to the ABI ignore list.
> ignore CreateDir in abi-check

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- gpdb-doc/markdown/ref_guide/guc-changes-6to7.html.md.erb
docs for https://github.com/greenplum-db/gpdb/pull/16491.
in this PR:
- add reference info for this guc.  i pulled the text from greenplum 6 guc description.  
- gp6 default is off, gp7 is on, so add to list of guc changes.
> docs - optimizer_enable_orderedagg guc added to gp7

- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This PR documents the option to specify a package name when migrating with `gppkg`.
Also introduces some formatting changes in order to correctly render the command options.
> Docs: add gppkg option to specify package to migrate

- src/backend/optimizer/prep/prepunion.c
- src/test/regress/expected/union.out
For union case, it will add motion atop Append node, and hash on all non-junk attributes, convert locus for SubqueryScanPath has no effect.
But for INTERSECT/EXCEPT, it will add motion(if needed) below the Append for hashed locus, and also hash on all non-junk attributes. When subquery's DistributionKey expr are same with the non-junk attributes, convert subpath's locus to use Vars pointing to the outputs of the subquery can eliminate redistribute motion.
Remove GPDB_96_MERGE_FIXME.
> Adjust subquery's locus for recurse_set_operations

- gpdb-doc/markdown/admin_guide/access_db/topics/pgbouncer.html.md
- gpdb-doc/markdown/security-guide/topics/ports_and_protocols.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer-admin.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer.html.md
- gpdb-doc/markdown/utility_guide/utility-programs.html.md
supercedes https://github.com/greenplum-db/gpdb/pull/16733.
pgbouncer docs were removed a while ago in commit 72e17f8f817ca6e252385e135e11b14c8cec1391.  add them back in (when source file exists) using current content from 6X_STABLE.
note: will apply updates from https://github.com/greenplum-db/gpdb/pull/16735 (6x, ldap encrypted password) after that PR is merged.
- using topic - https://docs-staging.vmware.com/en/draft/VMware-Greenplum/pgb7/greenplum-database/admin_guide-access_db-topics-pgbouncer.html
- ports and protocols (scroll to the bottom of the table) - https://docs-staging.vmware.com/en/draft/VMware-Greenplum/pgb7/greenplum-database/security-guide-topics-ports_and_protocols.html
- utility ref pages - …
> docs - add pgbouncer reference and using content

- src/backend/executor/nodeShareInputScan.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/sync_guc_name.h
- src/test/regress/expected/bfv_cte.out
- src/test/regress/expected/bfv_cte_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/bfv_cte.sql
Previously, a race condition between Share Input Scan (SISC) reader and
writer could cause the writer to hang if the reader node was squelched
before the writer node was initialized.
Here's an example plan:
```
-- Setup tables
CREATE TABLE sisc_t1(a int, b int) DISTRIBUTED BY (a);
INSERT INTO sisc_t1 VALUES (1, 1), (2, 2), (5, 5);
ANALYZE sisc_t1;
CREATE TABLE sisc_t2(c int, d int) DISTRIBUTED BY (c);
-- Ensure that sisc_t2 has 0 tuple on seg2
INSERT INTO sisc_t2 VALUES (1, 1), (2, 2);
ANALYZE sisc_t2;
-- Query
EXPLAIN (COSTS OFF)
WITH cte AS MATERIALIZED (SELECT * FROM sisc_t1)
SELECT y.a, z.a
FROM (SELECT cte1.a, cte1.b FROM cte cte1 JOIN sisc_t2 ON (cte1.a = sisc_t2.d)) y,
(SELECT cte2.a, cte2.b FROM cte cte2 JOIN sisc_t2 ON (cte2.a = sisc_t2.d)) z
WHERE y.b = z.b - 1;
```
QUERY PLAN …
> Fix race condition in CTE reader-writer communication

- src/backend/commands/indexcmds.c
- src/test/isolation2/expected/create_index_deadlock.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/create_index_deadlock.sql
Create index will dispatch query `select indcheckxmin from pg_catalog.pg_index where indexrelid = 'xxx'` to segments to sync `indcheckxmin` on coordinator. This query will acquire `AccessShareLock` on `pg_index` in segments, and wouldn't release until the end of the transaction, since coordinator won't acquire the lock for now, deadlock between coordinator and segment may be occurred in some scenarios, what's worse, this kind of deadlock couldn't be resolved by GDD.
To avoid that, before dispatching the query, coordinator should also grab the `AccessShareLock` on `pg_index`.
> Fix deadlock between coordinator and segments

- gpdb-doc/markdown/ref_guide/modules/ip4r.html.md
version 2.4.2 is bundled.
questions:  
1. the control file specifies version 2.4.  does this mean that the user will automatically get this new version of the ip4r library after they upgrade greenplum?  i.e. if the user is already using ip4r, it did not seem to me that an ALTER EXTENSION ... UPDATE TO ... was required here.  let me know if i am missing something.
2. will upcoming greenplum v6.26.0 include ip4r 2.4.2?
> docs - ip4r version 2.4.2

- src/test/isolation2/expected/autovacuum-temp-table.out
- src/test/isolation2/sql/autovacuum-temp-table.sql
Failure diff:
```
--- /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/expected/autovacuum-temp-table.out	2023-12-07 10:40:29.583957111 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/isolation2/results/autovacuum-temp-table.out	2023-12-07 10:40:29.591957823 +0000
@@ -29,7 +38,9 @@
Success:
(1 row)
1: select * from tt_av1;
-ERROR:  fault triggered, fault name:'exec_mpp_query_start' fault type:'panic'
+ a
+---
+(0 rows)
0Uq: ... <quitting>
1q: ... <quitting>
```
The fault was not hit by the expected "select * from tt_av1" query. From the log it's hit by a query dispatched by the autovacuum on QD:
```
2023-12-07 10:40:26.973550 UTC,"gpadmin","isolation2test",p206008,th-1346017152,"[local]",,2023-12-07 10:40:26 UTC,0,con147,cmd5,seg-1,,dx268381,,sx1,"LOG","00000","statement: create table …
```
> Fix flaky test autovacuum-temp-table

- gpdb-doc/markdown/utility_guide/ref/gppkg.html.md
This PR adds a note for the `-f` option for `gppkg` utility, based on the changes introduced by https://github.com/pivotal/gp-pkg/pull/150
> Docs: added note for gppkg remove force option

- src/backend/executor/execPartition.c
- src/backend/partitioning/partdesc.c
- src/include/partitioning/partdesc.h
This gives us a speedup for bulk loads, which is important more-so from a GPDB perspective.
Replicating the experiment [here](https://www.postgresql.org/message-id/CA%2BHiwqFbMSLDMinPRsGQVn_gfb-bMy0J2z_rZ0-b9kSfxXF%2BAg%40mail.gmail.com), we only see a 5% improvement on an optimized build, but might see more where we are bulk loading data **partition-by-partition**.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/find_partition_cache
Backported from 3592e0ff98b130c428c1d8091fc61767f7608732 with negligible conflicts. Original commit message follows:
Here we add code which detects when ExecFindPartition() continually finds the same partition and add a caching layer to improve partition lookup performance for such cases.
Both RANGE and LIST partitioned tables traditionally …
> Have ExecFindPartition cache the last found partition

- src/backend/partitioning/partbounds.c
Gives us minor speed improvements (among a wealth of memory related improvements) with respect to partition bound manipulation:
With these 2 patches, -O3 non-assert build, creating 3k partitions:
Classic:
```
CREATE TABLE p3(a int, b int, c int) with (appendonly=true)
partition by range (a)
( partition aa start (1) end (3000) inclusive every (1) );
Averaged over 3 runs:
Before patches: 24s
After patches: 21s
```
Modern (one transaction): See 
[script_one_tx.sql.txt](https://github.com/greenplum-db/gpdb/files/13592091/script_one_tx.sql.txt)
```
Averaged over 3 runs:
Before patches: 23s
After patches: 20s
```
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/backport_palloc_save
> Backport improvements to partition bound manipulation

- src/backend/optimizer/util/pathnode.c
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
* We decide whether to generate a new subplan for this CTE.
* We decide whether to enable plan sharing for this CTE.
* We decide whether to inline this CTE accroding to self references and if contains volatile functions.
* We decide whether to push down quals for this CTE.
* For CTEs shared, generate one Subquery plan as a singleton and store it in cteplaninfo. `sub_final_rel->pathlist` also only keeps the cheapest cost path, for sharing purpose.
* For CTEs not shared, generate different Subquery plans for each CTE. `sub_final_rel->pathlist` would have more than one cost paths, leaving upper callsite to decide the cheapest cost path.
* Add a `CtePath` by: https://github.com/greenplum-db/gpdb/blob/7ef0db993d850268bc8c365f8d8728345ce1f11a/src/backend/optimizer/path/allpaths.c#L3105
* For …
> Resolve FIXME in create_ctescan_path()  in pathnode.c.

- src/backend/utils/resgroup/cgroup.c
There is no leaf directory in gpdb cgroup when use cgroup v1, so the `rmdir(leaf_path)` will always return non-zero values, then the `rmdir(path)` will be ignored.
When drop some resource groups, when corresponding cgroup dir cannot be removed because the `rmdire(path)` is not executed, this behavior will cause the failure of CI.
This commit add some logic to check resource group version in `deleteDir`, when use `group-v1`, `rmdir(leaf_path)` will be ignored.
> delete cgroup leaf dir only when use group-v2

- src/backend/gporca/data/dxl/minidump/PartTbl-SPE-Boolean2.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CConstraintInterval.h
- src/backend/gporca/libgpopt/src/base/CConstraintInterval.cpp
- src/test/regress/expected/partition_prune_optimizer.out
- src/test/regress/expected/partition_pruning.out
- src/test/regress/expected/partition_pruning_optimizer.out
- src/test/regress/sql/partition_pruning.sql
After the commit "[ORCA] Support boolean static partition pruning (#15348)", we added support for boolean testing in partition pruning or other condition pruning. However, currently, we only treated it as a parent of ident. When its child is an expression, errors may occur.
For example 1, this query will lead to a "One-Time Filter: false" because we treated it as "b is true and (not b)".
create table test (a int, b boolean);
explain select * from test where (not b) is true and (not b);
For example 2, this query will have no results because partition pruning will prune the current part as we treated it as "col2 IS true".
CREATE TABLE pt_bool_tab (
col1 int,
col2 bool
)
distributed by (col1)
partition by list(col2)
(
partition part1 values(true),
partition part2 values(false)
);
INSERT INTO …
> [ORCA] Fix boolean testing when the child is not an ident but an expression

- src/backend/access/aocs/aocssegfiles.c
- src/backend/access/appendonly/aosegfiles.c
`connected` local variable used in PG_TRY/PG_CATCH block should be declared 'volatile'.
> Add volatile qualifier missed in ao segfiles

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/tablespace_mgmt_utils.py
**Issue:**
gpcheckcat reports `column "oid" does not exist` error while running ‘missing_extraneous’ test on pg_shdescription catalogue table
```
[~/workspace/gpdb6: {6x_error_gpcheckcat} ?]$ gpcheckcat postgres
Truncated batch size to number of primaries: 4
Connected as user 'sshirisha' to database 'postgres', port '6000', gpdb version '6.24'
-------------------------------------------------------------------
Batch size: 4
Performing test 'unique_index_violation'
Total runtime for test 'unique_index_violation': 0:00:02.50
Performing test 'duplicate'
Total runtime for test 'duplicate': 0:00:04.49
Performing test 'missing_extraneous'
  Execution error: ERROR:  column "oid" does not exist
LINE 4:                 SELECT oid FROM pg_shdescription
                               ^
          …
```
> Fix gpcheckcat 'oid does not exist' error for catalog tables

- src/backend/utils/adt/ruleutils.c
- src/test/regress/expected/create_view.out
- src/test/regress/expected/create_view_optimizer.out
- src/test/regress/sql/create_view.sql
Previous coding in get_const_expr() has handled with negative number, opexpr plus number is an exception. 
(ex. -1 could be a negative const and also could be a opexpr '-' plus number 1). So we needed to hacking up
in get_rule_sortgroupclause() for Opexpr cases and pre-calculate opexpr plus number to real const by expression_planner(). 
More Discussions: https://www.postgresql.org/message-id/KL1PR03MB728644D79999D6BBF65E4D6FA482A%40KL1PR03MB7286.apcprd03.prod.outlook.com
> [6X] Printing const-folder expression in ruleutils.c

- src/backend/utils/adt/ruleutils.c
- src/test/regress/expected/create_view.out
- src/test/regress/expected/create_view_optimizer.out
- src/test/regress/sql/create_view.sql
Previous coding in get_const_expr() has handled with negative number, opexpr plus number is an exception. 
(ex. -1 could be a negative const and also could be a opexpr '-' plus number 1). So we needed to hacking up
in get_rule_sortgroupclause() for Opexpr cases and pre-calculate opexpr plus number to real const by expression_planner(). 
More Discussions: https://www.postgresql.org/message-id/KL1PR03MB728644D79999D6BBF65E4D6FA482A%40KL1PR03MB7286.apcprd03.prod.outlook.com
> Printing const-folder expression in ruleutils.c 

- src/backend/executor/execDynamicIndexes.c
- src/backend/executor/nodeDynamicBitmapIndexscan.c
This fix addresses a memory leak that occurs during the execution of DynamicIndexScan, DynamicIndexOnlyScan, and DynamicBitmapIndexScan. Each partition of the DynamicIndexScan creates an IndexScanState for execution usage. Within each IndexScanState, an ExprContext is allocated but not freed in ExecFreeExprContext(). This ExprContext includes a MemoryContext, resulting in a memory leak of the initial context space during each iteration of the DynamicIndexScan partition loop. Which will lead to a significant accumulation of leaked memory if the partition loop is extensive.
The same issue is observed in the execution of DynamicIndexOnlyScan and DynamicBitmapIndexScan.
This fix ensures that the allocated MemoryContext within the ExprContext is properly freed during the execution of each …
> Fix memory leak in Dynamic Index/IndexOnly/BitmapIndex Scan during execution (#16797)

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
This commit borrows two test helper functions from PG13 https://github.com/postgres/postgres/commit/10013684970453a0ddc86050bba813c611114321 that replace changeable output details in the EXPLAIN output. 
As a result, remove the complex matchsubs in the explain_format.sql regression test. This results in stable test output across planner/orca and assert/non-assert builds.
> Produce stable explain_format test output

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
ecc8344 was slightly overzealous in removing all matchsubs from `explain_format.sql`. Add back the subs filtering out JIT guc settings.
> Ignore variable JIT gucs in explain_format output

- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_SERVER.html.md
see https://greenplum.slack.com/archives/C04JJQ5AHJ4/p1691999617535799.
greenplum behaves the same as postgresql.  the default action for an ALTER SERVER on an option is ADD.  if you specified an option when you created the server (or if you previously altered the server and specified that option), the option is considered to be already defined.  an ALTER SERVER command with no action for that option is attempting to add that option again.  to change/replace an option, the user should specify the SET action.
the error "provided more than once" is slightly misleading, as is noted in this message from the postgresql message board:  https://www.postgresql.org/message-id/10352.1374877685%40sss.pgh.pa.us.  (i don't think the postgresql community acted on the recommendation in that message.)
i …
> docs - clarify ALTER SERVER option actions

- gpMgmt/sbin/packcore
- src/test/isolation2/sql_isolation_testcase.py
For more reliability, use python `shutil.which` in Popen, it's also a recommended way in python document. 
Use `/bin/bash` in `src/test/isolation2/sql_isolation_testcase.py` will block the isolation2 on some environments, like `nix`.
reference:
https://docs.python.org/3/library/subprocess.html#popen-constructor
> use shutil.which to get cmd path in Popen

- gpcontrib/gp_toolkit/expected/gp_toolkit.out
- gpcontrib/gp_toolkit/gp_toolkit--1.3.sql
- gpcontrib/gp_toolkit/sql/gp_toolkit.sql
The view gp_toolkit.gp_stats_missing is used by users to show which tables/partitioned tables do not have stats--and therefore which tables should be analyzed. 
The current behavior has a few shortcomings:
1) it shows tables that have been analyzed but have no data 
2) it shows intermediate partitions (which can't be analyzed, but displaying them is noisy)
3) it never shows root partitioned tables
4) it never shows materialized views
Now, the above behavior is fixed. Note that it will still show root partitioned tables as having no stats if none of the leaves have data--we can't differentiate between a root table that has no stats and a root table that has no data but has been analyzed.
The goal with this is to show users which tables may not be being analyzed in their workflow or need to …
> Fix view gp_toolkit.gp_stats_missing to only show tables missing stats

- src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrder.h
- src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h
- src/backend/gporca/libgpopt/src/operators/CLogical.cpp
- src/backend/gporca/libgpopt/src/xforms/CJoinOrder.cpp
- src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
DPv2 produces a few different join order alternatives. One of these
alternatives, stored in m_top_k_part_expressions, attempts to produce a
plan while considering the effects of partition selection. This was
initially added in 9c44532. However, when considering a partition
selector's effect, we also need to consider the distribution spec.
Otherwise we may choose a particular join order that may appear to be a
valid join order with a partition selector, but it actually isn't due to
a mismatch of distribution specs. In many cases, the DPv2 algorithm's
partition selection logic wasn't producing a valid join order.
Consider the tables P1, P2, T1, T2 all inner joined together. We
currently produce the join order:
```
PS2
PT2
PT1
PS1
```
This occurs in the hope that PS1 is a partition selector …
> Improve DPv2 algorithm to include distribution spec information with partition selectors

- .abi-check/7.0.0/postgres.symbols.ignore
- gpMgmt/bin/gpconfig
- src/backend/cdb/cdbvars.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/resgroup/cgroup.c
- src/include/utils/guc.h
- src/include/utils/resgroup.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Add guc: gp_resource_group_cgroup_parent (only for cgroup v2).
Current gpdb doesn't support change root cgroup path of resource group. For some situations, it's better if gpdb can change the root cgroup path of resource group.
For example, on the OS with systemd, user maybe want to create a delegated  cgroup to gpdb via systemd, but the delegated cgroup must end with `.service` which typically is `/sys/fs/cgroup/gpdb.service`. And in other OS without systemd, user maybe want to use `/sys/fs/cgroup/gpdb` or other locations directly. So add the `gp_resource_group_cgroup_parent` can make the resource group more flexible.
> Add guc: gp_resource_group_cgroup_parent

- src/backend/executor/nodeDynamicBitmapIndexscan.c
- src/backend/executor/nodeDynamicIndexscan.c
This fix addresses a memory leak that occurs during the execution of DynamicIndexScan and DynamicBitmapIndexScan. Each partition of the DynamicIndexScan creates an IndexScanState for execution usage. Within each IndexScanState, an ExprContext is allocated but not freed in ExecFreeExprContext(). This ExprContext includes a MemoryContext, resulting in a memory leak of the initial context space during each iteration of the DynamicIndexScan partition loop. Which will lead to a significant accumulation of leaked memory if the partition loop is extensive. The same issue is observed in the execution of DynamicBitmapIndexScan.
This fix ensures that the allocated MemoryContext within the ExprContext is properly freed during the execution of each partition in Dynamic Index/BitmapIndex Scan.
Fix …
> Fix memory leak in Dynamic Index/BitmapIndex Scan during execution

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-views.html.md
This PR adds the view `gp_stat_progress_dtx_recovery` to the documentation reference pages for system views. 
Based on https://github.com/greenplum-db/gpdb/pull/15945
Let me know if the column types and descriptions are correct.
> Docs gp stat progress dtx recovery

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorUtils.cpp
- src/include/gpopt/translate/CIndexQualInfo.h
- src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
- src/include/gpopt/translate/CTranslatorUtils.h
Since the GPDB 5 merge, this logic is now done during execution and is no longer populated in the plan node. Thus Orca doesn't need to retrieve this information and we can simplify some code paths. 
Additionally, the previous code was wrong and wouldn't work: we were populating the index strategy information with the subtype oid:
```
*index_strategy_list = gpdb::LAppendInt(*index_strategy_list, index_qual_info->m_index_subtype_oid);
```
> Remove unused index strategy and subtype information from Orca

- concourse/pipelines/templates/gpdb-tpl.yml
> Fix resource ‘filedump_src’ is not used for genpipeline cli

- GNUmakefile.in
- contrib/pg_buffercache/.gitignore
- contrib/pg_buffercache/Makefile
- contrib/pg_buffercache/expected/pg_buffercache.out
- contrib/pg_buffercache/pg_buffercache--1.3--1.4.sql
- contrib/pg_buffercache/pg_buffercache--1.4--1.4.1.sql
- contrib/pg_buffercache/pg_buffercache.control
- contrib/pg_buffercache/pg_buffercache_pages.c
- contrib/pg_buffercache/sql/pg_buffercache.sql
- doc/src/sgml/pgbuffercache.sgml
Enable MPP support for pg_buffercache and build by default
This PR first backports the following upstream commits for `pg_buffercache`
https://github.com/postgres/postgres/commit/be39d88934331c47c43d8c51500305e928f06240
https://github.com/postgres/postgres/commit/2589434ae0fbfe08e46b6a4ffba400140b636074
https://github.com/postgres/postgres/commit/f3fa31327ecba75ee0e946abaa56dbf471ba704b
The final commit:
* Adds wrapper views around pg_buffercache_summary() and
pg_buffercache_usage_counts() for convenience.
* Adds three MPP views displaying results from the coordinator and all segments
- gp_buffercache
- gp_buffercache_summary
- gp_buffercache_usage_counts
* Adds two views displaying aggregated cluster-wide results
- gp_buffercache_summary_aggregated
- …
> Enable MPP support for pg_buffercache and build by default

- GNUmakefile.in
- contrib/pg_buffercache/.gitignore
- contrib/pg_buffercache/Makefile
- contrib/pg_buffercache/expected/pg_buffercache.out
- contrib/pg_buffercache/pg_buffercache--1.0--1.1.sql
- contrib/pg_buffercache/pg_buffercache--1.1.sql
- contrib/pg_buffercache/pg_buffercache.control
- contrib/pg_buffercache/pg_buffercache_pages.c
- contrib/pg_buffercache/sql/pg_buffercache.sql
- doc/src/sgml/pgbuffercache.sgml
This is a partial backport of https://github.com/greenplum-db/gpdb/pull/16819.
Changes from 7X:
- 1.2 updated the extension to be `PARALLEL` safe. 6X does not support the `PARALLEL` keyword, so 1.2 cannot be backported.
- Default monitoring roles were added to the catalog as a larger effort that bumped the version to 1.3. This cannot be backported to a stable branch.
- The `_summary` and `_usage_count` functions added in 1.4 rely on backend behavior introduced in 9.5/9.6 that cannot be backported to a stable branch.
Ref:
https://github.com/postgres/postgres/commit/ed127002d8c592610bc8e716759a1a70657483b6
https://github.com/postgres/postgres/commit/48354581a49c30f5757c203415aa8412d85b0f70
- The view `gp_buffercache` was added directly to `1.1` since this is the first version we're shipping …
> 6X Backport: Enable MPP support for pg_buffercache and build by default

- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformRightOuterJoin2HashJoin.h
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
In production systems, we encountered scenarios where poor cardinality
estimations led to plans with ROJ that yielded memory related workfile
limit errors. In those cases, the only way to turn off ROJ was to either
rewrite the query or turn off the xform. A query rewrite takes time to
come up with and turning off the xform doesn't work at the per-user
level. This commit introduces a GUC optimizer_enable_right_outer_join as
a convenient way to work around this problem.
> [ORCA] Add GUC to disable right outer join (ROJ)

- gpMgmt/bin/lib/gp_bash_functions.sh
- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
**Fixes:** https://github.com/greenplum-db/gpdb/issues/16848
**Issue:** gpinitsystem fails with an error when an invalid option is provided. But the exit code is 0 not 1. It should fail with exit code 1.
**Fix:** LOG_MSG fn is being used to print the error which sets EXIT_STATUS to 1 only when message is a FATAL message. Updated LOG_MSG to set the EXIT_STATUS to 1 in case of ERROR messages also.
Current behaviour:
```
[~/workspace/gpdb/gpMgmt: {gpinitsystem_invalid_options} ?]$ gpinitsystem -c ../gpAux/gpdemo/clusterConfigFile -h ../gpAux/gpdemo/hostfile --sdbds
20231215:11:01:58:098912 gpinitsystem:ashahaniKMD6M:ashahani-[ERROR]:-Unknown option --sdbds
gpinitsystem -c gp_config_file [OPTIONS]
Creates a new Greenplum Database instance on a Coordinator host and a number of
segment instance …
```
> gpinitsystem should return code 1 when invalid option is used

- src/backend/gporca/libgpopt/src/base/CDatumSortedSet.cpp
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
Previously, when constructing CDatumSortedSet from an array expression with all NULL elements, the aprngdatum was becoming an empty array. This caused unexpected errors that could lead to ORCA fallback to the planner, or even coredump.
The bug has been fixed by ensuring that no unnecessary operations are performed on the empty aprngdatum array.
> Fix CDatumSortedSet handling of empty arrays causing errors in ORCA

- src/backend/gporca/data/dxl/minidump/DQA-1-RegularAgg.mdp
- src/backend/gporca/data/dxl/minidump/DQA-2-RegularAgg.mdp
- src/backend/gporca/data/dxl/minidump/DQA-GroupBy-HashAggregate1.mdp
- src/backend/gporca/data/dxl/minidump/DQA-SplitScalar.mdp
- src/backend/gporca/data/dxl/minidump/DQA-SplitScalarOnDistCol.mdp
- src/backend/gporca/data/dxl/minidump/DQA-SplitScalarWithAggAndGuc.mdp
- src/backend/gporca/data/dxl/minidump/DQA-SplitScalarWithGuc.mdp
- src/backend/gporca/data/dxl/minidump/DistinctQueryWithMotions.mdp
- src/backend/gporca/data/dxl/minidump/LOJ_bb_mpph.mdp
- src/backend/gporca/data/dxl/minidump/MDQA-SameDQAColumn.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping-OrderBy.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Grouping.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs-Union.mdp
- src/backend/gporca/data/dxl/minidump/MDQAs1.mdp
- src/backend/gporca/data/dxl/minidump/ScalarDQAWithNonScalarAgg.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnComputedCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-DistinctOnSameNonDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-GbandDistinctOnDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctComputedCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg-ScalarAgg-DistinctNonDistrCol.mdp
- src/backend/gporca/data/dxl/minidump/ThreeStageAgg.mdp
- src/backend/gporca/data/dxl/minidump/UnionOfDQAQueries.mdp
- src/backend/gporca/data/dxl/minidump/WinFunc-Redistribute-Sort-CTE-Producer.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalAgg.cpp
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
As we set optimizer_force_multistage_agg=on to force orca choose multi-agg plan, there are redundant hash keys of motion as below `(Hash Key: c, b, b)`, obviously column `b` is redundant anyway.
```
postgres=# explain (costs off) select count(distinct b) from num_table group by c;
QUERY PLAN                                     
------------------------------------------------------------------------------------
->  GroupAggregate
Group Key: c
->  Sort
Sort Key: c
->  Redistribute Motion 3:3  (slice2; segments: 3)
Hash Key: c
->  GroupAggregate
Group Key: c, b
->  Sort
Sort Key: c, b
->  Redistribute Motion 3:3  (slice3; segments: 3)
Hash Key: c, b, b
->  Seq Scan on num_table
Optimizer: GPORCA
(15 rows)
```
The reason is that as the first stage agg …
> Remove redundant hash keys of motion

- src/backend/access/aocs/aocsam.c
- src/backend/commands/tablecmds.c
- src/test/isolation2/expected/aoco_column_rewrite.out
- src/test/isolation2/sql/aoco_column_rewrite.sql
This is intended to support generating column values based on
existing columns for AT add-column operation on an AOCO table.
For example,
```
create table aoco(a int) with (appendonly=true, orientation=column);
insert into aoco select * from generate_series(1, 5);
gpadmin=# select * from aoco;
a
---
5
2
3
4
1
(5 rows)
gpadmin=# alter table aoco add column b int generated always as (a*a) stored;
ALTER TABLE
gpadmin=# select * from aoco;
a | b
---+----
1 |  1
5 | 25
2 |  4
3 |  9
4 | 16
(5 rows)
```
Without this commit, values of the new column b will be null which is not expected.
> Support ADD COLUMN GENERATED by existing column on AOCO Tables.

- src/backend/storage/smgr/md.c
AO table has its own fsync function `aosyncfiletag`, but it didn't call `FileClose` at the end, which will cause mirror segment's checkpointer process memory leak.
> Fix AO table fsync memory leak

- gpMgmt/bin/gpcheckcat
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
This commit is a cherry-pick of community PR [#16809 ](https://github.com/greenplum-db/gpdb/pull/16809)
Changes are approved as part of that PR.
Error occurs when we issue command `gpcheckcat -C pg_class`. Reported error is "[ERROR] executing: Cross consistency check for pg_class\n  Execution error: name 'db' is not defined". This is because of use of an undefined variable 'db'. This commit fixes the issue by removing its usage.
> Fix for gpcheckcat when issue `gpcheckcat -C pg_class`

- src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-InnerJoin.mdp
- src/backend/gporca/data/dxl/minidump/DynamicIndexOnlyScan-LeftJoin.mdp
- src/backend/gporca/libgpopt/src/operators/CPhysicalScan.cpp
- src/test/regress/expected/bfv_index.out
- src/test/regress/expected/bfv_index_optimizer.out
- src/test/regress/expected/gp_covering_index_optimizer.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/expected/select_parallel_optimizer.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/bfv_index.sql
It's also a problem of IndexOnlyScan on AO/AOCS tables that can not generate IndexScan but can generate IndexOnlyScan. For example:
create table test (a int, b int)
with (appendonly='true') distributed by (a);
create index test_a_idx on test(a);
create index test_b_idx on test(b) include (a);
insert into test select i,i from generate_series(1, 10000)i;
analyze test;
explain (costs off) select t1.a from test t1, test t2 where t1.a = t2.a and t1.b < 10;
QUERY PLAN
-------------------------------------------------------------
->  Nested Loop
Join Filter: true
->  Broadcast Motion 3:3  (slice2; segments: 3)
->  Index Only Scan using test_b_idx on test
Index Cond: (b < 10)
->  Index Only Scan using test_a_idx on test test_1
Index Cond: (a = test.a) …
> [ORCA] Fix Missing pdshashedEquiv in IndexOnlyScan, Especially under InnerIndexNLJoin.

- gpMgmt/doc/gpexpand_help
Issue:  gpexpand --help was showing wrong for -n option 
```
-n <parallel_processes>
The number of tables to redistribute simultaneously. Valid values
are 1 - 16. Each table redistribution process requires two database
connections: one to alter the table, and another to update the table's
status in the expansion schema. Before increasing -n, check the current
value of the server configuration parameter max_connections and make
sure the maximum connection limit is not exceeded.
```
instead of 1 - 16 it should be 1 - 96 as per the code MAX_PARALLEL_EXPANDS = 96
Fix: updated max range value in help file.
> updated max range value in help file for gpexpand -n option

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
This PR added support for using the -i flag with differential recovery in the gprecoverseg command, enhancing its capabilities.
Implementation: 
**Simultaneous Use of -i and --differential:**
Added the functionality to allow the use of both the -i and --differential options simultaneously in the gprecoverseg command. This means that by providing a recovery configuration file with the -i flag and specifying the --differential flag, you will initiate a differential recovery process for all hosts listed in the recovery configuration file, similar to how the -i and -F options currently work together
**Recovery Type Specification in Recovery Configuration File:** 
Added the functionality to specify I/D/F as a recovery type for each line in recovery_config_file and based on that recovery type …
> [7x]: Added Support for -i flag with differential recovery

- gpdb-doc/markdown/admin_guide/ddl/ddl-sequence.html.md
- gpdb-doc/markdown/ref_guide/SQL2008_support.html.md
- gpdb-doc/markdown/utility_guide/ref/pg_dump.html.md
- gpdb-doc/markdown/utility_guide/ref/pg_dumpall.html.md
- gpdb-doc/markdown/utility_guide/ref/pg_restore.html.md
in this PR:
- finish up doc change for INSERT ... ON CONFLICT
- bring pg_dump, pg_dumpall, pg_restore utility ref pages up to postgres 12
- general:
- omitted new --no-publications and --no-subscriptions options
- kept trigger if as-is, there is work-in-progress on this topic
- there are references to large objects, which greenplum doesn't support.  i followed what the pages are doing currently - include the info from postgres page, then add a note that it is unsupported (not my preference).
- pg_dump questions:
- no --exclude-table-and-children and --exclude-table-data-and-children on postres 12 ref page, but i do see a ref in the pg_dump code.  is this supported in greenplum 7?
- no --table-and-children option on postgres 12 ref page, i do see a ref in the pg_dump code.  is this …
> docs - wrap up UPSERT doc changes, dump/dumpall/restore utility ref page updates

- gpMgmt/bin/gpssh
In current release of GPDBv7, if we run `gpssh -v` it will always report warning like below:
``` bash
$ gpssh -v -f ~/all_segment_hosts.txt  -e "uptime"
[WARN] Reference default values as $COORDINATOR_DATA_DIRECTORY/gpssh.conf could not be found
Using delaybeforesend 0.05 and prompt_validation_timeout 1.0
```
it does not matter if the file is exists or not
```
$ cat $COORDINATOR_DATA_DIRECTORY/gpssh.conf  | grep -v "^#" | grep -v "^$"
[gpssh]
delaybeforesend = 0.05
prompt_validation_timeout = 1.0
sync_retries = 3
```
the issue in under below line (line#112) of `$GPHOME/bin/gpssh`
```python
110     try:
111         config = configparser.RawConfigParser()
112         config.read(gp.get_coordinator_datadir() + '/gpssh.conf')
```
Noted that in GPv6 we do not have such issue, seems GPv6 using …
> gpssh with -v will not load gpssh.conf no matther if the file is exist or not

- src/backend/cdb/cdbmutate.c
- src/backend/optimizer/plan/createplan.c
- src/backend/optimizer/prep/prepunion.c
- src/backend/optimizer/util/pathnode.c
- src/backend/parser/parse_cte.c
- src/include/cdb/cdbmutate.h
- src/test/regress/expected/gp_recursive_cte.out
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/expected/with.out
- src/test/regress/expected/with_clause.out
- src/test/regress/expected/with_clause_optimizer.out
- src/test/regress/expected/with_optimizer.out
- src/test/regress/init_file
- src/test/regress/sql/gp_recursive_cte.sql
- src/test/regress/sql/with.sql
After pr #14656, following sql raises ERROR "GROUP BY in a recursive query is not implemented"
```
create table test_cte (a int, b int);
EXPLAIN
WITH RECURSIVE r(c1, c2) as 
(
select a as c1, b as c2 from test_cte
union all
select r.c1, r.c2 from r
join 
(
select a as c1 , max(b) as c2 from test_cte group by c1
) as tmp_table
on r.c1 = tmp_table.c1
)
select * from r join test_cte on r.c1 = a;
```
Analysis:
The slices of workTableScan and RecursiveUnion must be the same.
We add commit: https://github.com/greenplum-db/gpdb/commit/3f5cf5c730f in GPDB to process above problems, 
Currently Recursive CTE's do not support the following operations in the recursive term:
- Group By
- Window Functions
- Subqueries with a self-reference
- Distinct
Sometimes this is over-restricted. Although there is …
> Fix error is thrown even if group by clause does not reference a recursive CTE

- .abi-check/7.0.0/postgres.symbols.ignore
- .abi-check/7.0.0/postgres.types.ignore
- src/backend/catalog/heap.c
- src/backend/commands/createas.c
- src/backend/commands/exttablecmds.c
- src/backend/commands/sequence.c
- src/backend/commands/tablecmds.c
- src/backend/commands/tablecmds_gp.c
- src/backend/commands/typecmds.c
- src/backend/commands/view.c
- src/backend/nodes/copyfuncs.c
- src/backend/nodes/equalfuncs.c
- src/backend/nodes/outfuncs.c
- src/backend/nodes/readfast.c
- src/backend/parser/gram.y
- src/backend/parser/parse_partition_gp.c
- src/backend/partitioning/partbounds.c
- src/backend/partitioning/partdesc.c
- src/backend/tcop/utility.c
- src/include/catalog/heap.h
- src/include/nodes/parsenodes.h
- src/include/parser/parse_utilcmd.h
- src/include/partitioning/partbounds.h
- src/include/partitioning/partdesc.h
- src/test/regress/expected/bfv_partition.out
- src/test/regress/expected/partition1.out
- src/test/regress/input/partition_ddl.source
- src/test/regress/output/partition_ddl.source
Currently, in the classic CREATE workflow, we rebuild the partition
descriptor of parent relations once for each child. This
has significant overhead.
To eliminate that overhead, we have to avoid calls to
RelationRetrievePartitionDesc(). In this commit, we avoid the following:
* We avoid locking the default partition, for each child.
* We avoid calling check_new_partition_bound() for each child. Instead,
we defer all bounds checks to the end of the command.
* We avoid performing repeated relcache invalidations for default partitions.
This gives us close to a 3x improvement in performance.
Note: Currently, we perform this optimization only for range partitions
created with classic syntax. However, this can also be extended to ALTER
ADD and other types of partitions.
Dev-pipeline: …
> Optimize classic DDL syntax for partition creation

- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/minirepro.feature
- src/bin/pg_dump/pg_dump.c
pg_dump does not correctly dump functions when both greenplum specific internal flags `--function-oid` and `--relation-oid` are used at the same time. This is because functions are being marked dumpable or not twice. The first time is by selectDumpableFunction and then again by selectDumpableObject. When `--relation-oid` is used, all namespaces are marked not dumpable which is why selectDumpableObject will mark the function to not be dumped.
This must be a regression. The original commit that introduces greenplum specific selectDumpableFunction removes the usage of the more generic selectDumpableObject.
selectDumpableFunction reference commit:
https://github.com/greenplum-db/gpdb/commit/318b86afc3eb5745f07ddfb390970b1769c63a1b
> pg_dump: fix --function-oid when --relation-oid is also used

- gpMgmt/bin/gppylib/commands/gp.py
- gpMgmt/sbin/gpsegstart.py
- gpMgmt/test/behave/mgmt_utils/gpstart.feature
- gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave_utils/utils.py
- src/bin/pg_ctl/pg_ctl.c
There was a recent commit that made pg_ctl wait for mirrors to display 'wrecvstreaming' in its postmaster.pid instead of 'standby'. However, this caused a regression in gpstart where it would wait for the mirror to finish starting up before eventually failing due to timeout because its primary segment was not able to start up. In this scenario, the mirror would be in lock status 'standby' and is able to be promoted by FTS but FTS is unavailable during gpstart because the coordinator segment is not up when primary and mirror segments are brought up. To fix the issue, we add a new hidden flag to pg_ctl which will allow pg_ctl to complete its wait loop if the mirror is in lock status 'standby'. This should be okay for gpstart since it doesn't care too much if a mirror's wal receiver has …
> Add hidden flag --gp-mirror-fast-wait to pg_ctl

- gpdb-doc/markdown/ref_guide/sql_commands/COPY.html.md
bring the COPY sql ref page up to postgres 12 content. there is a bit of greenplum-specific content on this page, and also a bunch of new content pulled from the pg12 page.
notes/questions:
- ON SEGMENT, FILL MISSING FIELDS, LOG ERRORS, IGNORE EXTERNAL PARTITIONS - these are greenplum-specific clauses.  i am assuming that they have not changed in greenplum 7.  let me know if this is incorrect.
- Parameters section: column_name includes a statement about the max size of bytea columns - is this still true in greenplum 7?
- search for text between XXX (there is a large block in the Notes section and others in the File Formats sections) - still valid in greenplum 7?
- there are several greenplum-specific examples, i am assuming they are still valid (i called them out with XXX).
- in the …
> docs - update COPY sql ref page

- src/backend/access/transam/xact.c
- src/pl/plpython/expected/plpython_subtransaction.out
- src/pl/plpython/plpy_cursorobject.c
- src/pl/plpython/plpy_spi.c
- src/pl/plpython/plpy_spi.h
- src/pl/plpython/sql/plpython_subtransaction.sql
An error occurs in python lib when a plpython function is executed.
After our analysis, in the user's cluster, a plpython UDF 
was running with the unstable network, and got a timeout error:
`failed to acquire resources on one or more segments`.
Then a plpython UDF was run in the same session, and the UDF
failed with GC error.
Here is the core dump:
```
2023-11-24 10:15:18.945507 CST,,,p2705198,th2081832064,,,,0,,,seg-1,,,,,"LOG","00000","3rd party error log:
#0 0x7f7c68b6d55b in frame_dealloc /home/cc/repo/cpython/Objects/frameobject.c:509:5
#1 0x7f7c68b5109d in gen_send_ex /home/cc/repo/cpython/Objects/genobject.c:108:9
#2 0x7f7c68af9ddd in PyIter_Next /home/cc/repo/cpython/Objects/abstract.c:3118:14
#3 0x7f7c78caa5c0 in PLy_exec_function …
```
> Fix bug: PLPY function causes master process reset.

- contrib/pg_buffercache/expected/pg_buffercache.out
`AclObjectKind` has no enum for view, just change the output file.
> Update the output file of pg_buffercache

- src/bin/pg_upgrade/check.c
- src/bin/pg_upgrade/greenplum/check_gp.c
- src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
- src/bin/pg_upgrade/version.c
pg_upgrade has a few checks that look for specific data types. The SQL
used to look for data types does not run on GPDB6 because it is a
recursive CTE that contains a self-reference in a subquery. This
specific type of query works on GPDB7, but is broken on GPDB6 and
therefore doesn't work for GPDB6 > GPDB7 upgrade. To get type of query
working on GPDB6 would require a non trivial amount of backports. As a
workaround, the query was rewritten in plpgsql so it can run on GPDB6.
This fixes the following pg_upgrade checks:
- check_for_composite_data_type_usage
- check_for_reg_data_type_usage
- old_11_check_for_sql_identifier_data_type_usage
- old_9_6_check_for_unknown_data_type_usage
performance numbers using `\timing` against the icw regression db on a demo clusters.
plpgsql on 6X regression …
> pg_upgrade: rewrite data type check sql in plpgsql to run on GPDB6

- src/backend/executor/execUtils.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
This pull request introduces a new GUC, gp_max_system_slices, mirroring gp_max_slices, with the distinction that it is restricted to superusers (PGC_SUSET). Because there are many instances of users already using gp_max_slices, we will retain that guc and its behavior to ease the upgrade path.
After Fix on 7X:
```
CREATE ROLE
SET
=> select current_user;
current_user
--------------
user1
(1 row)
=> set gp_max_slices=100;
SET
=> set gp_max_system_slices=100;
ERROR:  permission denied to set parameter "gp_max_system_slices"
```
> Add GUC gp_max_system_slices with superuser(PGC_SUSET)  only

- gpdb-doc/markdown/admin_guide/about-resgroups-changes.html.md
- gpdb-doc/markdown/admin_guide/wlmgmt.html.md
- gpdb-doc/markdown/admin_guide/workload_mgmt_resgroups.html.md
- gpdb-doc/markdown/analytics/pl_container_using.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_RESOURCE_GROUP.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_RESOURCE_GROUP.html.md
This PR reintroduces PL/Container support with Resource Groups. 
It aligns most of the GPDB 7 documentation to what GPDB 6 supported, plus a few additions:
- New guc gp_resource_group_cgroup_parent
- Modification of the bash script for resource groups using cgroup v2 to automatically start during system startup.
Questions:
- Can you provide an example of creating a resource group for the `CREATE RESOURCE GROUP` reference page that uses PL/Container? The previous examples used memory auditor.
- Can you review  the page gpdb-doc/markdown/analytics/pl_container_using.html.md to help adapt concepts to the GPDB 7 resource group concepts? I only ported back the changes that were removed on https://github.com/greenplum-db/gpdb/pull/16490 so it needs some editing. Especially around memory …
> Docs: add PL/Container support with Resource Groups back

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-functions.html.md
- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref.html.md
This PR:
- Creates a new documentation reference page for System Catalog Functions.
- Creates a sub-menu for Statistics Functions.
- Adds the function `pg_stat_get_backend_subxact` to the list under Statistics Functions.
Question:
- Should we also add `gp_get_suboverflowed_backends` to the list? Is this a wrapper of `pg_stat_get_backend_subxact`? I can see that the system view `gp_suboverflowed_backend` exists. What is the relationship among them all?
Review site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-catfunct/greenplum-database/ref_guide-system_catalogs-catalog_ref-functions.html
> Docs: new reference page for system catalog functions

- gpdb-doc/markdown/ref_guide/system_catalogs/catalog_ref-functions.html.md
This is a follow up PR to https://github.com/greenplum-db/gpdb/pull/16854. I forgot to add the function `gp_get_suboverflowed_backends` to the initial page index. I just need a quick approval. Thanks.
> Docs: added gp_get_suboverflowed_backends to index

- concourse/pipelines/gen_pipeline.py
- concourse/pipelines/templates/gpdb-tpl.yml
- gpAux/Makefile
Change compile platform to rhel9 for el9 platforms  as llvm 15 is not supported in rocky9 system apps
Tested Pipelines : https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-GPR-1509-rhel9 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-GPR-1509-oel9 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-GPR-1509-rocky9 
> Change compile platform to rhel9 for el9 platforms 

- gpdb-doc/markdown/ref_guide/modules/postgresml.html.md
This PR adds the function `pgml.train` to the existing PostgresML reference page. 
@radarwave @yihong0618 could you help with an example for the last section, can anything be added to the existing example that uses the `pgml.train` function? Thanks.
Edit: it now also includes `pgml.predict` and an example at the end of the page.
Review site: 
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-pgml/greenplum-database/ref_guide-modules-postgresml.html
> Docs postgresml train

- src/bin/pg_dump/pg_dump.c
`pg_dump -t` an inherits child table will dump its parent table's index.
``` SQL
$ pg_dump --gp-syntax -h cdw -p 5432 -U gpadmin -s -t '"public"."capitals"' 'testdb_gpcopy_ginkgo1'
-- .....skip sth.......
CREATE TABLE public.capitals (
state character(2)
)
INHERITS (public.cities)
;
-- .....skip sth.......
CREATE INDEX cities_id_idx ON public.cities USING btree (id); -- pay attention, should not to be dumped
-- .....skip sth.......
```
Only 6X has this bug.
Related issue https://github.com/greenplum-db/gpdb/issues/16926
The behavior of func `getIndexes()` changes at this https://github.com/greenplum-db/gpdb/commit/4428ef34782ec9dc4bc96e07d3d7dd102adb42f7 
When we refactored it, miss these code
```
/* Ignore indexes of tables not to be dumped */
if (!tbinfo->dobj.dump)
continue;
```
Keep …
> [6X] pg_dump: Ignore indexes of tables not to be dumped

- src/bin/pg_dump/pg_dump.c
`pg_dump -t` an inherits child table will miss `distributed by`.
```SQL
$ pg_dump -h 127.0.0.1 -p 15432 -U gpadmin -s -t '"public"."capitalsxxxxx"' 'gpadmin' 
-- ,,,,,,,,,skip sth,,,,,,,,
CREATE TABLE public.capitalsxxxxx (
state character(2) NOT NULL
)
INHERITS (public.cities) -- pay attention, `distributed by` disappeared
;
-- ,,,,,,,,,skip sth,,,,,,,,
```
Only 6X has this bug.
Related issue https://github.com/greenplum-db/gpdb/issues/16933
The behavior changes at this commit https://github.com/greenplum-db/gpdb/commit/cef5b96ea89f532929ee92b994d283d7ef3817d1#diff-36e3806266f5e832b422f878e1d7fef4ebeea2143b1733ea3fa2f90a99bad5c5L14472-L14479
miss these code `&& !tbinfo->parents` when pg_dump judges whether it should `Dump distributed by clause` or not.
Keep the same behavior to 5X and …
> [6X] pg_dump should addDistributedBy if it is a child table

- .abi-check/6.26.1/postgres.symbols.ignore
ABI problems with the symbol `ConfigureNamesBool_gp`:
> Size of this global data has been changed from 38304 bytes to 38456 bytes.
The reason is that an additional GUC is added in this commit: https://github.com/greenplum-db/gpdb/pull/16887/files#diff-3d03368dae4bd5ea009d6cdc0ce2ddc4620e2b776429532d32fde1c3ba63c515R3292 since 6.26.1
Currently, we can ignore this symbol in the ABI check.
Related PR: #16887
> Ignore symbol ConfigureNamesBool_gp in base 6.26.1

- gpMgmt/test/behave/mgmt_utils/environment.py
- gpMgmt/test/behave/mgmt_utils/minirepro.feature
- src/bin/pg_dump/pg_dump.c
This is a backport of 7X commits 992b4dd and 9a36a39 with minor modifications to account for differences in pg_dump code between 6X and 7X.
pg_dump does not correctly dump functions when both greenplum specific
internal flags `--function-oid` and `--relation-oid` are used at the
same time. This is because functions are being marked dumpable or not
twice. The first time is by selectDumpableFunction and then again by
selectDumpableObject. When `--relation-oid` is used, all namespaces are
marked not dumpable which is why selectDumpableObject will mark the
function to not be dumped.
This must be a regression. The original commit that introduces greenplum
specific selectDumpableFunction removes the usage of the more generic
selectDumpableObject. …
> [6X] pg_dump: fix --function-oid when --relation-oid is also used

- src/backend/commands/schemacmds.c
- src/test/regress/expected/privileges.out
- src/test/regress/expected/privileges_optimizer.out
- src/test/regress/sql/privileges.sql
We lost this code change and its test in an upstream merge, get it back.
commit c5d6078de405cfeb66a35192efd16c4298220d82
Author: Pengzhou Tang <ptang@pivotal.io>
Date:   Thu Apr 25 19:52:42 2019 -0400
Fix a permission denied issue
Assume user1 has the privilege to database db1 and user2 has not, when
user1 try to create a schema in db1 and authorize it to user2, a
permission denied error is reported in QE. The RCA is QD set current
user to user2 before dispatching the query to QEs, so QE will also
set current user to user2, however, user2 has no provilege to create
schema in database db1.
To fix this, we delay setting the current user to user2 until the query
is dispatched to QEs.
Fix #16988
> Delay setting the current user until the CREATE SCHEMA is dispatched

- src/test/regress/expected/quicklz_fallback.out
- src/test/regress/sql/quicklz_fallback.sql
a spelling mistake which cause error message like
```
test quicklz_fallback             ... Having no space between pattern and following word is deprecated at (eval 74) line 3, <$infh> line 15.
Bareword found where operator expected at (eval 74) line 3, near "m/none) { 
$ini =~  s/none"
(Might be a runaway multi-line // string starting on line 2)
Having no space between pattern and following word is deprecated at (eval 77) line 3, <$infh> line 15.
Bareword found where operator expected at (eval 77) line 3, near "m/none) { 
$ini =~  s/none"
(Might be a runaway multi-line // string starting on line 2)
ok          549 ms (diff   72 ms)
``
> Fix regex mistake on regress test case

- gpdb-doc/markdown/ref_guide/sql_commands/VACUUM.html.md
This PR adds the options SKIP_DATABASE_STATS and ONLY_DATABASE_STATS to VACUUM to vacuum. 
Based on the PR https://github.com/greenplum-db/gpdb/pull/16191
> Docs: add SKIP_DATABASE_STATS and ONLY_DATABASE_STATS to VACUUM

- src/backend/executor/execUtils.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/sync_guc_name.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
This pull request introduces a new GUC, gp_max_system_slices, mirroring gp_max_slices, with the distinction that it is restricted to superusers (PGC_SUSET). Because there are many instances of users already using gp_max_slices, we will retain that guc and its behavior to ease the upgrade path
```
CREATE ROLE
SET
=> select current_user;
current_user
--------------
user1
(1 row)
=> set gp_max_slices=100;
SET
=> set gp_max_system_slices=100;
ERROR:  permission denied to set parameter "gp_max_system_slices"
```
(cherry picked from commit https://github.com/greenplum-db/gpdb/commit/2a5338d223e0ca2f3a3d35614dd26c6bbe3a1d58)
pipeline: https://qpa.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-6X/jobs/compile_and_test_gpdb/builds/602
> [6X] Add GUC gp_max_system_slices with superuser(PGC_SUSET) only

- src/test/regress/expected/explain_format.out
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/sql/explain_format.sql
Test case explain_format failed recently:
```
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/explain_format_optimizer.out /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/explain_format.out
--- /tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/explain_format_optimizer.out	2024-01-15 15:50:02.765529591 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/explain_format.out	2024-01-15 15:50:02.813534472 +0000
@@ -708,6 +708,8 @@
Group Key: share0_ref2.b
Extra Text: (segN)   hash table(s): N; N groups total in N batches, N spill partitions; disk usage: NKB; chain length N.N avg, N max; using N of N buckets; total N expansions.
+                    Extra Text: (segN)   hash table(s): N; N groups total in N batches, N …
```
> Fix test case explain_format about hashagg output

- src/backend/access/transam/xact.c
- src/pl/plpython/expected/plpython_subtransaction.out
- src/pl/plpython/plpy_cursorobject.c
- src/pl/plpython/plpy_spi.c
- src/pl/plpython/plpy_spi.h
- src/pl/plpython/sql/plpython_subtransaction.sql
An error occurs in python lib when a plpython function is executed.
After our analysis, in the user's cluster, a plpython UDF 
was running with the unstable network, and got a timeout error:
`failed to acquire resources on one or more segments`.
Then a plpython UDF was run in the same session, and the UDF
failed with GC error.
Here is the core dump:
```
2023-11-24 10:15:18.945507 CST,,,p2705198,th2081832064,,,,0,,,seg-1,,,,,"LOG","00000","3rd party error log:
#0 0x7f7c68b6d55b in frame_dealloc /home/cc/repo/cpython/Objects/frameobject.c:509:5
#1 0x7f7c68b5109d in gen_send_ex /home/cc/repo/cpython/Objects/genobject.c:108:9
#2 0x7f7c68af9ddd in PyIter_Next /home/cc/repo/cpython/Objects/abstract.c:3118:14
#3 0x7f7c78caa5c0 in PLy_exec_function …
```
> [6X_STABLE] Fix bug: PLPY function causes master process reset.

- src/backend/utils/adt/network_selfuncs.c
- src/test/regress/expected/join_gp.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/sql/join_gp.sql
During the GP7 merge, separate join selectivity functions were added for network types. However, GPDB has a separate join, JOIN_LASJ_NOTIN, that does not exist in Postgres and thus was not added as a possible case.
I followed the same pattern in selfuncs.c, treating it as a semi/anti join for calculating the selectivity.
Fixes https://github.com/greenplum-db/gpdb/issues/16997
> Fix "unrecognized join type" error with LASJ Not-In and network types

- src/backend/gporca/data/dxl/minidump/EagerAggEmptyInput.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggExpression.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggGroupColumnInJoin.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggMax.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggMaxWithNestedLoop.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggMinMax.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggSubquery.mdp
- src/backend/gporca/data/dxl/minidump/EagerAggUnsupportedAgg.mdp
- src/backend/gporca/libgpopt/include/gpopt/xforms/CXformEagerAgg.h
- src/backend/gporca/libgpopt/src/xforms/CXformEagerAgg.cpp
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
To Fix issue https://github.com/greenplum-db/gpdb/issues/16978, In CXformEagerAgg rule, we chould fill argtypes of CLogicalAgg, which used for filling Aggref in finla Plan.
> [ORCA] Fill Agg argtypes as optimizer_enable_eageragg is on

- src/backend/gporca/libgpopt/include/gpopt/metadata/CColumnDescriptor.h
- src/backend/gporca/libgpopt/include/gpopt/search/CGroup.h
- src/backend/gporca/libgpopt/src/search/CGroupExpression.cpp
- src/backend/gporca/libgpos/include/gpos/common/CDynamicPtrArray.h
- src/backend/gporca/libgpos/include/gpos/string/CWStringBase.h
- src/backend/gporca/libgpos/server/include/unittest/gpos/common/CDynamicPtrArrayTest.h
- src/backend/gporca/libgpos/server/src/unittest/gpos/common/CDynamicPtrArrayTest.cpp
- src/backend/gporca/libgpos/server/src/unittest/gpos/common/CHashMapIterTest.cpp
- src/backend/gporca/libgpos/server/src/unittest/gpos/common/CHashSetIterTest.cpp
- src/backend/gporca/libnaucrates/include/naucrates/base/IDatum.h
- src/backend/gporca/libnaucrates/include/naucrates/md/IMDId.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/IStatistics.h
- src/backend/gporca/libnaucrates/src/statistics/CJoinStatsProcessor.cpp
CDynamicPtrArray has methods to sort itself and compare equality against
another array. However, the implementation of these methods makes strong
assumptions about the size of the stored data type. If the data type has
significant bits beyond 8 bytes (sizeof ULONG_PTR), then the effects of
these functions may yield unexpected behavior.
This commit targets StringPtrArray, but there are other bad types, too.
That can be seen by a static_assert sizeof(T) <= sizeof(ULONG_PTR). It
is surprising that we hadn't noticed this earlier. It may be the case
that equal elements generally share the same allocated memory. And so,
the first 8 bytes of the object behind the pointer could correctly match
on equality.
As a blanket fix for other types larger than 8 bytes, a memcmp is done
for sizeof(T). If …
> [ORCA] Fix CDynamicPtrArray sort/compare that contains large objects

- src/bin/pg_dump/pg_dump.c
As of GPDB7, gp_toolkit is an extension. During gpinitsystem gp_toolkit extension is automatically created in template1. During 6 > 7 upgrade, we should assume that this extension will always be there. In future upgrades, gp_toolkit will be treated like any other extension.
> pg_dump: exclude gp_toolkit from being dumped when upgrading from GPDB6

- src/Makefile.global.in
- src/test/recovery/Makefile
Backpatch the commit from gpdb7 to gpdb6:
https://github.com/greenplum-db/gpdb/commit/a40f8ea0f5550930eb743e76cb23a742f5e7befa
Discussion: https://postgr.es/m/f2401388-936b-f4ef-a07c-a0bcc49b3300@dunslane.net
The commit above is in PR #14790
I want to run TAP tests in extensions for gpdb6 and find this issue about prove_installcheck
> Backpatch fix for prove_installcheck with PGXS

- .abi-check/6.26.1/postgres.symbols.ignore
ABI problems with the symbol ConfigureNamesInt_gp:
> Size of this global data has been changed from 18880 bytes to 19040 bytes.
The reason is that an additional GUC is added in this PR #16957 [file](https://github.com/greenplum-db/gpdb/pull/16957/files#diff-3d03368dae4bd5ea009d6cdc0ce2ddc4620e2b776429532d32fde1c3ba63c515R4677) since 6.26.1
Currently, we can ignore this symbol in the ABI check-ignore list.
Similar PR: #16992
> Ignore symbol ConfigureNamesInt_gp in base 6.26.1

- src/bin/pg_upgrade/check.c
Commit bb4f0754efbc8661033110ce44c9b94922e5d632 was a bit overzealous in removing checks. The AO matview check is required for a 6X source cluster.
> pg_upgrade: Re-add AO matview check call

- gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature
- src/backend/libpq/pqcomm.c
- src/backend/utils/misc/guc_gp.c
- src/include/utils/unsync_guc_name.h
For instance, the default `listen_addresses` is set to `*` (all), it
should not break right after the first good address.
> Fix regression: listen all listen_addresses with the specified family

- gpdb-doc/markdown/utility_guide/ref/pgbouncer-admin.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer-ini.html.md
- gpdb-doc/markdown/utility_guide/ref/pgbouncer.html.md
This PR brings the PgBouncer documentation pages up to date with the latest PgBouncer version 1.21.
This PR is against main, it also needs to be cherry-picked to 6X_STABLE.
Review sites:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-pgbouncer/greenplum-database/utility_guide-ref-pgbouncer.html
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-pgbouncer/greenplum-database/utility_guide-ref-pgbouncer-ini.html#synopsis
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-pgbouncer/greenplum-database/utility_guide-ref-pgbouncer-admin.html
> Docs: updated PgBouncer documentation pages to match latest version 1.21

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
This PR removes the Data Domain Boost section from the Platform Requirements page for VMware Greenplum 7.
> Docs: removed DDboost section from Platform requirements page

- gpcontrib/Makefile
- gpcontrib/pg_hint_plan/Makefile
- gpcontrib/pg_hint_plan/make_join_rel.c
- gpcontrib/pg_hint_plan/pg_hint_plan--1.3.0.sql
- gpcontrib/pg_hint_plan/pg_hint_plan.c
- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
- src/test/regress/expected/planhints.out
- src/test/regress/expected/planhints_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/planhints.sql
Now that pg_hint_plan is in gpcontrib and ORCA optimizer has the framework to
support hints, we are nearly ready to turn on the feature. This is the final
batch of commits to enable scan hints. It's a combination of cleanups and fixes.
1) Fix up code to compile successfully
2) Initialize plan_hint_hook so that ORCA can leverage the parser
3) Setup to run planhints test in CI and miscellaneous cleanups
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-gpdb-support-pg_hint_plan-rocky8
> Enable pg_hint_plan for GPDB

- src/bin/pg_upgrade/greenplum/check_gp.c
If a check errors out early and `--continue-check-on-fatal` isn't specified, subsequent pg_upgrade runs will hit a `schema __gpupgrade_tmp already exists` error during setup because `teardown_GPDB6_data_type_checks` never executed.
> Drop __gpupgrade_tmp if exists during pg_upgrade setup

- src/bin/pg_upgrade/function.c
- src/bin/pg_upgrade/greenplum/check_gp.c
GP7 does not  support plpython2, so any functions using it on GP6 will fail to upgrade. 
Provide a check to output the offending functions.
> pg_upgrade: Add check for functions dependent on plpython2

- doc/src/sgml/ref/pgupgrade.sgml
- src/bin/pg_upgrade/check.c
- src/bin/pg_upgrade/greenplum/check_gp.c
- src/bin/pg_upgrade/greenplum/option_gp.c
- src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
- src/bin/pg_upgrade/greenplum/version_gp.c
- src/bin/pg_upgrade/pg_upgrade.c
- src/bin/pg_upgrade/pg_upgrade.h
- src/bin/pg_upgrade/util.c
- src/bin/pg_upgrade/version.c
This PR backports some QOL improvements for `pg_upgrade` output, then adds a new pg_upgrade flag, `--output-dir`.
Currently, `pg_upgrade` output (checks, logs, schema dump) is sent to the target cluster's data directory in `pg_upgrade.d` by default. The new flag allows the user to redirect the output. For example, during `pg_upgrade` checks, users may want to send the check output files to `gpAdminLogs` instead of the target data directory. This will be a likely use-case for gpupgrade.
As a note, output files are always removed unless the `-r, --retain` flag is set, which seems to me an odd choice when `pg_upgrade` fails. Since this is the case in upstream and gpupgrade always sets `--retain` flag, leave this as is.
Example:
GP6 -> GP7 check run
```
pg_upgrade -c --continue-check-on-fatal …
```
> pg_upgrade: Add flag for relocateable output

- src/backend/access/aocs/aocsam.c
- src/test/isolation2/expected/ao_partial_scan.out
- src/test/isolation2/sql/ao_partial_scan.sql
In AO/CO partial scan, we reposition to read block from a desired file offset. There is an edge case bug where if we intend to read from start of the file of a CO table, we might end up reading the first block of the file twice. The reason is that, when opening file segments for CO tables (open_scan_seg()), we would read ahead the first blocks of the files. So, if we re-position to the start of the file, after we scanned all the rows of the read-ahead blocks, we would read in the first blocks again, and end up scanning the same blocks twice. This was found when looking at some incoherent numbers in ao_partial_scan regress test. Fixing the issue now, and correcting the test output.
Co-authored-by: Soumyadeep Chakraborty <soumyadeepc@vmware.com>
Dev pipeline: …
> Fix an edge case bug of repositioning in AOCO partition scan

- src/backend/executor/nodeBitmapAnd.c
- src/backend/executor/nodeBitmapHeapscan.c
- src/backend/executor/nodeBitmapIndexscan.c
- src/backend/executor/nodeBitmapOr.c
- src/backend/nodes/tidbitmap.c
- src/test/regress/expected/query_finish_pending.out
- src/test/regress/sql/query_finish_pending.sql
Previously, BitmapIndexScan create and free the bitmap memory. When BitmapHeapScan retrieves all tuples, it will free the bitmapstate's memory(tbmiterator, don't free bitmap), and the next relation's (of the same dynamic scan) BitmapHeapScan will first rescan the child node BitmapIndexScan which will free the bitmap memory.
But if QueryFinishPending is true when iteration over the bitmap, it will return null without free the bitmapstate, and next bitmapheap scan still need to do the rescan and free the bitmap memory. Finally when ExecEndBitmapHeapScan free bitmap iterator will access to a freed bitmap.
We don't have need to let BitmapIndexScan free bitmap memory, free bitmap iterator and bitmap memory together.
> [6X] Fix query with DynamicBitmap scan crash when QueryFinishPending is true

- src/interfaces/libpq/fe-connect.c
Note that f86af5ecf12d522568a1a1fa255ec714e4affe51 introduces `gpconntype` in `pg_conn`, but this field won't be freed in `freePGconn`.
> Fix FTS PROBE process memory leak

- .abi-check/7.0.0/postgres.symbols.ignore
- .abi-check/7.0.0/postgres.types.ignore
- src/backend/access/transam/xlogarchive.c
- src/backend/bootstrap/bootstrap.c
- src/backend/postmaster/pgarch.c
- src/backend/postmaster/pgstat.c
- src/backend/postmaster/postmaster.c
- src/backend/storage/ipc/ipci.c
- src/include/miscadmin.h
- src/include/pgstat.h
- src/include/postmaster/pgarch.h
- src/include/storage/pmsignal.h
- src/include/storage/proc.h
- src/tools/pgindent/typedefs.list
> [!IMPORTANT]
>  Backporting Upstream Postgres Commit to GPDB main
>         - https://github.com/postgres/postgres/commit/d75288fb27b8fe0a926aaab7d75816f091ecdc27 (Make archiver process an auxiliary process.) (PG14)
>         - https://github.com/postgres/postgres/commit/beb4e9ba1652a04f66ff20261444d06f678c0b2d (Improve performance of pgarch_readyXlog() with many status files.) (PG15)
>        - https://github.com/postgres/postgres/commit/1fb17b1903414676bd371068739549cd2966fe87 (Fix issues in pgarch's new directory-scanning logic.) (PG15)
Original Commit Message:
[Archiver Process as an Auxiliary Process](https://github.com/postgres/postgres/commit/d75288fb27b8fe0a926aaab7d75816f091ecdc27)
```
Make archiver process an auxiliary process.
This commit changes …
```
> Make archiver process as auxiliary process and Improve performance of pgarch_readyXlog() with many failed status file 

- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
**Context:**
PR https://github.com/greenplum-db/gpdb/pull/16529 changed the behviour of gprecoverseg -o to also add entry for a failed segment that is not reachable. If the generated file is used as input for recovery, gprecoverseg will skip the recovery of unreachable failed segments. If the user wants to recover that segment to somewhere else (any other reachable host) they should modify the entry of such segments (unreachable) and add failover details in output config file. But there is no way for the user to identify those entries from config file which require attention.
**Solution:**
To inform the user about failed segment entry with unreachable hosts, the entry will be commented in the output config file. gprecoverseg skips the recovery of a segment if the host is unreachable so if …
> [7X] gprecoverseg -o behaviour change

- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Backport of f03f27e8ebadf2cb3859aff7b63ea2e9bc6277fa
**Current behaviour:** gprecoverseg -o outputs a config file containing the rows for each failed segment. But skips to add row for segment if failed segment is unreachable as it can't be recovered during the recovery process.
**Requested behaviour:** gprecoverseg -o should generate config file which contains row for each failed segment from gp_segment_configuration even if the failed segment host is unreachable. As the genarted config file can be modified according to usecase and need.
**Fix:** While creating the list of triplets (which will considered for recovery) a triplet is not added to list if failed host is unreachable. This triplet should not skipped if we just want to generate an output config file. So added check for -o option …
> [6X] gprecoverseg: Fix behaviour of -o flag

- src/backend/gporca/scripts/fix_mdps.py
Update fix_mdps.py script to work on systems that do not have python version 2
in absolute path /usr/local/bin/python.
- Ran: "2to3 -w -n fix_mdps.py"
- Fixed hash-bang arguments
> Update fix_mdps.py script to python3 syntax

- concourse/scripts/builds/GpBuild.py
This is required for us to locate the Postgres configuration in workload pipelines and append necessary environment settings, such as number of segments and optional GUC's.
> Source gpdemo-env.sh in case of DB exists

- src/bin/pg_dump/pg_dumpall.c
`cpu_set` causes a syntax error
> pg_dumpall: Fix syntax error when dumping RGs

- src/bin/pg_dump/pg_dump.c
It's required to provide some value for every column name that calls `PQfnumber`. tgisinternal snuck in during the 12_12 merge but the query that 6X runs wasn't updated.
> Fix 7X pg_dump crash when dumping triggers from 6X

- src/backend/executor/nodeBitmapHeapscan.c
- src/test/regress/expected/query_finish_pending.out
- src/test/regress/sql/query_finish_pending.sql
Backport test case of commit 2795ae2f2763d008309b2ecbb3ea4e3056c4276e and remove out-of-date comment message.
> backport test case of DynamicBitmap scan when QueryFinishPending is true

- src/interfaces/libpq/fe-connect.c
Note that f86af5e introduces `gpconntype` in `pg_conn`, but this field won't be freed in `freePGconn`.
> [6X][backport] Fix FTS PROBE process memory leak

- src/backend/commands/resgroupcmds.c
- src/test/isolation2/expected/resgroup/resgroup_memory_limit.out
- src/test/isolation2/sql/resgroup/resgroup_memory_limit.sql
Resgroup doesn't check memory_limit value when create a resource group, but when execute a query, and set query's memory limit, it will assert memory_limit=-1 if memory_limit < 0.
Set memory_limit range to [0, INT_MAX] or set to default value -1.
> Fix query crash with minus memory_limit value in resgroup

- .abi-check/7.1.0/postgres.symbols.ignore
- .abi-check/7.1.0/postgres.types.ignore
- src/backend/gporca/libgpopt/src/operators/CLeftJoinPruningPreprocessor.cpp
- src/test/regress/expected/join_gp.out
- src/test/regress/expected/join_gp_optimizer.out
- src/test/regress/sql/join_gp.sql
Fix issue  #16932
`Derived Output columns:` Output columns defined by each operator
`Output Columns:` The intersection of the operator's derived output columns and
the operator's parent's combined output pred columns. If the operator is the
root operator, its output columns would be the intersection of the operator's
derived output columns and the query's output columns.
`Combined Output Pred Columns:` A set containing operator's output columns and
its predicate's (if present) derived output columns
-------------------------
Consider the below tree
```
+--A(Logical)
|--B (Logical)
|  |----C (Logical)
|  |----D (Logical)
|  +----E (Scalar)
|
+--F (Scalar)
```
In order to perform left join pruning in ORCA, one of the step is that each
operator(Logical) determines two sets. One set …
> Fix for finding child output columns when parent is union while join pruning

- .abi-check/7.1.0/postgres.types.ignore
Adding ignore symbols/types that were added as part of https://github.com/greenplum-db/gpdb/commit/128d497843152196a4414349c6a5f5bbd5e3c069 as it did not make it to the 7.1.0 release.
> Remove AuxProcType from the abi ignore files for 7.1.0

- gpMgmt/bin/gpload.py
- gpMgmt/bin/gpload_test/gpload2/TEST_local_data_format.py
- gpMgmt/bin/gpload_test/gpload2/query264.ans
- gpMgmt/bin/gpload_test/gpload2/setup.ans
- gpMgmt/bin/gpload_test/gpload2/setup.sql
This PR fixes issue https://github.com/greenplum-db/gpdb/issues/16959
gpload needs to create a staging table for update and merge.
The staging table's distribution key should be the same as the target table.
When the target table doesn't have distribution key (distributed random or replicated), the distribution key of staging table should be the same as `MATCH_COLUMNS` in the gpload config file.
In the before code, when the target table has distribution key with special order like:`distributed by (col2, col1, col3)`
Gpload will create staging table `distributed by ( col1, col2, col3)`, which is the wrong order.
In this PR, we fix this wrong distribution key order.
We don't use the function `pg_get_table_distributedby` because gpload6 needs to support gpdb5, and gpdb5 doesn't have this …
> fix gpload create staging table with wrong distribution key order

- .abi-check/6.26.2/postgres.symbols.ignore
- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/gpopt/translate/CContextDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/libnaucrates/include/naucrates/traceflags/traceflags.h
- src/backend/optimizer/prep/prepunion.c
- src/backend/tcop/pquery.c
- src/backend/utils/misc/guc_gp.c
- src/include/gpopt/gpdbwrappers.h
- src/include/gpopt/translate/CContextDXLToPlStmt.h
- src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/isolation2/expected/concurrent_select_vacuum_ao_partitioned_table.out
- src/test/isolation2/expected/concurrent_select_vacuum_ao_partitioned_table_optimizer.out
- src/test/isolation2/input/uao/select_while_vacuum.source
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/output/uao/select_while_vacuum.source
- src/test/isolation2/sql/concurrent_select_vacuum_ao_partitioned_table.sql
Introduce a new GUC gp_keep_partition_children_locks that preserves
relation locks on AO partition leaves, that are taken during planning.
This fixes concurrency issues such as #16545, where a SELECT pre-dating
a concurrent lazy vacuum can read past eof of a segfile, since the
vacuum would "drop" the segment. Adequate locking during planning is one
way to ensure that vacuumStatement_Relation() can't acquire the
AccessExclusiveLock on the coordinator. This would cause it to give up
on the drop, and the concurrent SELECT isn't compromised.
Unfortunately, we can't quite mark this GUC on by default, as it has
consequences on the amount of locks consumed:
Setting this GUC on means that we keep the acquired locks in
expand_inherited_rtentry() around longer now, up until the end of the …
> Keep partition child lock until end of select

- src/backend/storage/lmgr/proc.c
- src/backend/utils/mmgr/portalmem.c
- src/backend/utils/resscheduler/resqueue.c
- src/backend/utils/resscheduler/resscheduler.c
- src/include/utils/portal.h
- src/include/utils/resscheduler.h
- src/test/isolation2/expected/resource_queue_alter.out
- src/test/isolation2/expected/resource_queue_multi_portal.out
- src/test/isolation2/expected/resource_queue_role.out
- src/test/isolation2/expected/resource_queue_self_deadlock.out
- src/test/isolation2/expected/resource_queue_terminate.out
- src/test/isolation2/isolation2_resqueue_schedule
- src/test/isolation2/sql/resource_queue_alter.sql
- src/test/isolation2/sql/resource_queue_multi_portal.sql
- src/test/isolation2/sql/resource_queue_role.sql
- src/test/isolation2/sql/resource_queue_self_deadlock.sql
- src/test/isolation2/sql/resource_queue_terminate.sql
- src/test/regress/expected/resource_queue.out
- src/test/regress/init_file
- src/test/regress/output/resource_queue_function.source
This PR consists of:
1) Tests adding coverage and documentation for resource queue behavior
2) The fix for the statement leak involving self-deadlocks
3) The fix for the statement leak involving termination
4) Logging improvements
Please review commits individually
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/resq_self
> Fix resource queue slot leaks involving self-deadlocks and termination

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR adds the guc `debug_shareinput_xslice` to the documentation reference pages.
> Docs: document guc debug_shareinput_xslice

- src/backend/cdb/cdbutil.c
- src/backend/cdb/dispatcher/test/gpsegconfig_dump
fts process dumps gpsegconfig_dump file in coordinator datadir. in the current dump it does not include datadir from gp_segment_configuration. 
In this commit added support to include datadir in segment configuration dump.
following functions updated
writeGpSegConfigToFTSFiles()
readGpSegConfigFromFTSFiles()
Location:  $COORDINATOR_DATA_DIRECTORY/gpsegconfig_dump
sample output of gpsegconfig_dump file (before change) 
```
1 -1 p p n u 7000 shrakeshSMD6M.vmware.com shrakeshSMD6M.vmware.com 
2 0 p p s u 7002 shrakeshSMD6M.vmware.com shrakeshSMD6M.vmware.com 
5 0 m m s u 7005 shrakeshSMD6M.vmware.com shrakeshSMD6M.vmware.com 
3 1 p p s u 7003 shrakeshSMD6M.vmware.com shrakeshSMD6M.vmware.com 
6 1 m m s u 7006 shrakeshSMD6M.vmware.com shrakeshSMD6M.vmware.com 
4 2 p p s u 7004 …
```
> Added support to include datadir in gpsegconf_dump file

- src/backend/gpopt/utils/COptTasks.cpp
- src/backend/gporca/data/dxl/minidump/Hint-AbsoluteRows-Over-Join.mdp
- src/backend/gporca/data/dxl/minidump/Hint-AddRows-Over-Join.mdp
- src/backend/gporca/data/dxl/minidump/Hint-MultiplyRows-Over-Join.mdp
- src/backend/gporca/data/dxl/minidump/Hint-SubtractRows-Over-Join.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropRelational.h
- src/backend/gporca/libgpopt/include/gpopt/hints/CPlanHint.h
- src/backend/gporca/libgpopt/include/gpopt/hints/CRowHint.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalJoin.h
- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalNAryJoin.h
- src/backend/gporca/libgpopt/src/hints/CPlanHint.cpp
- src/backend/gporca/libgpopt/src/hints/CRowHint.cpp
- src/backend/gporca/libgpopt/src/hints/Makefile
- src/backend/gporca/libgpopt/src/operators/CLogicalJoin.cpp
- src/backend/gporca/libgpopt/src/operators/CLogicalNAryJoin.cpp
- src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/dxltokens.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h
- src/backend/gporca/libnaucrates/include/naucrates/statistics/IStatistics.h
- src/backend/gporca/libnaucrates/src/parser/CParseHandlerPlanHint.cpp
- src/backend/gporca/libnaucrates/src/xml/dxltokens.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/include/optimizer/hints.h
- src/test/regress/expected/rowhints.out
- src/test/regress/expected/rowhints_optimizer.out
- src/test/regress/greenplum_schedule
- src/test/regress/sql/maskout.sh
- src/test/regress/sql/rowhints.sql
This work is a continuation of plan hints in commit https://github.com/greenplum-db/gpdb/commit/e781fe0db4e3cb24b38be0b8497fc2ebafdd2b7a.
This change allows the user to specify row hints that tweak join result
cardinality estimates based on statistics. The updated estimates can
coerce the optimizer to generate different join types or orders that may
yield faster execution times.
The syntax mirrors pg_hint_plan [1]. Row hints can only be used for
joins, even though it could theoretically be useful on single relations,
too. In order to lift that constraint we must resolve upstream issue
[2]. Until then, row hints are only applied during stats derivation of
logical joins.
Example usage:
A user can specify that joining t1 and t2 produces 123 rows:
```sql
/*+
Rows(t1 t2 #123)
*/
EXPLAIN SELECT …
```
> [ORCA] Implement plan hints for row hints 

- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpmovemirror demo cluster was flaky and failing at below test "gpmovemirrors gives warning if pg_basebackup is already running for all mirrors to be moved ".
In the above test the gprecoverseg is triggered for inplace mirror recovery in asynchronous mode and then parallely gpmovemirror is triggered for the same set of mirror's. Since gprecoverseg is running in background the mirror data directory is not consistent and gomovemirror will calculates the size of the mirror data directory before invoking gprecoverseg, which was falking out sometimes in gpdb without-assert build.
Hence the changes are done so that the original intention of the test is met to fix this flakynes.
> fix flakyness in gpmovemirror demo cluster without-assert build

- gpdb-doc/markdown/install_guide/install_guide.html.md
This PR fixes a typo where GPDB 7 documentation was incorrectly referring to GPDB 6.
> Docs: Fixed typo where it was still referring to GPDB 6

- src/backend/storage/lmgr/proc.c
- src/backend/utils/mmgr/portalmem.c
- src/backend/utils/resscheduler/resqueue.c
- src/backend/utils/resscheduler/resscheduler.c
- src/include/utils/portal.h
- src/include/utils/resscheduler.h
- src/test/isolation2/expected/resource_queue_alter.out
- src/test/isolation2/expected/resource_queue_multi_portal.out
- src/test/isolation2/expected/resource_queue_role.out
- src/test/isolation2/expected/resource_queue_self_deadlock.out
- src/test/isolation2/expected/resource_queue_terminate.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/sql/resource_queue_alter.sql
- src/test/isolation2/sql/resource_queue_multi_portal.sql
- src/test/isolation2/sql/resource_queue_role.sql
- src/test/isolation2/sql/resource_queue_self_deadlock.sql
- src/test/isolation2/sql/resource_queue_terminate.sql
- src/test/regress/expected/resource_queue.out
- src/test/regress/init_file
- src/test/regress/output/resource_queue_function.source
This is a backport of #17022 with clean cherry-picks with very minor conflicts in test output, schedule files etc.
Notable absentee is https://github.com/greenplum-db/gpdb/pull/17022/commits/9d0450d479b48e064271861df82cab900d3e3c4b which already exists in 6X_STABLE.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_resq_self
> [6X] Fix resource queue slot leaks involving self-deadlocks and termination

- src/backend/port/unix_latch.c
- src/backend/storage/lmgr/s_lock.c
- src/include/storage/s_lock.h
From a field report, we have seen a race condition between an exiting backend (Y) and another backend (X) undergoing init. If the act of returning the PGPROC to the freelist for Y gets reordered before the store for procLatch->pid = 0, then there is a chance that X can grab the same PGPROC object from the freelist and can still see that procLatch->pid = Y. This can lead to the sanity check blowing up inside OwnLatch(). This can only happen if X's OwnLatch() is scheduled before Y's store for pid = 0.
1. We now PANIC in OwnLatch(), instead of ERRORing out. The effect is the same. See commit message for details
2. Spinlock primitives now act as compiler barriers on top of being CPU barriers for reordering.
* Follow-ups to that patch that contain minor upstream fixes
3. Adding an explicit …
> [6X] Fixes to latch and spinlock infrastructure

- gpMgmt/doc/gpexpand_help
Issue: gpexpand --help was showing wrong for -n option
-n <parallel_processes>
The number of tables to redistribute simultaneously. Valid values
are 1 - 16. Each table redistribution process requires two database
connections: one to alter the table, and another to update the table's
status in the expansion schema. Before increasing -n, check the current
value of the server configuration parameter max_connections and make
sure the maximum connection limit is not exceeded.
instead of 1 - 16 it should be 1 - 96 as per the code MAX_PARALLEL_EXPANDS = 96
Fix: updated max range value in help file.
> [6X][backport] updated max range value in help file for gpexpand -n option

- src/backend/access/transam/xact.c
For distributed transactions, we write the transaction commit WAL record in these three cases:
1. For 1PC, QE writes it at the end of the commit;
2. For 2PC, QD writes it after PREPARE phase is done on all segments;
3. For 2PC, QE writes it at the end of COMMIT phase.
For 1 and 2, we include distributed xid in the records. But not 3. Therefore, a segment replaying such a record won't initialize distributed log for that xid. Essentially, the commit will be equivalent to a local commit from the view of that segment.
This has not been an issue because when a QE needs to replay a 2PC (that is, only during recovery), it does not need to conduct dtx visibility check for the 2PC, since no query is allowed during recovery.
However, this has become an issue when we want to support hot standby or …
> Include distributed xid in transaction commit WAL in all dtx cases

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/test/regress/expected/qp_subquery.out
- src/test/regress/expected/qp_subquery_optimizer.out
- src/test/regress/sql/qp_subquery.sql
In Query to DXL translation, one of the tasks in RetrieveRel() is to get the
relation keyset. That keyset defines the table descriptor used in the query.
In the case of materialized views, ORCA did not build the keyset. As a
result, the column was never marked used and was subsequently optimized
out. That led a SIGSEGV in release mode (or fallback in debug mode) when
the optimized out column is later referenced.
See FRemoveExistentialSubquery()
Following example demonstrated this issue:
```sql
CREATE TABLE t (a int) DISTRIBUTED BY (a);
CREATE MATERIALIZED VIEW v AS SELECT a FROM t DISTRIBUTED RANDOMLY;
SELECT * FROM v WHERE EXISTS (select a FROM v);
```
This commit fixes the problem by allowing materialized views to build a keyset.
Notes:
- Commit 801b7a920b6dc69a44390d26427433f7912b8936 …
> [ORCA] Fix invalid colref using subquery exists 

- gpMgmt/bin/minirepro
- src/test/regress/expected/minirepro.out
- src/test/regress/sql/minirepro.sql
This commit adds minor improvement to the minirepro tool. Minirepro now also captures and stores any Non-default planner related gucs set in the environment. This includes three categories of postgres settings: Query Tuning / Planner Cost Constants, Query Tuning / Planner Method Configuration and Query Tuning / Other Planner Options. If all the settings related to this category are set to the default values, minirepro reports appropriate message indicating the same. This improvement aids developers to reproduce the plan if customers aren't aware of guc settings done at cluster/database/user level.
> Capture Non default planner gucs in minirepro

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
The funccolcount value wasn't being set by Orca when populating the plan to execute, which caused running explain <qry> for such queries to fail with "invalid attnum <X> for relation".  Interestingly, the queries I tested would execute fine--only explain would fail. Nonetheless, this should be populated.
> Properly set function column count for table value functions in Orca

- .abi-check/6.26.3/postgres.symbols.ignore
We have a new release tag for
[6.26.3](https://github.com/greenplum-db/gpdb/releases/tag/6.26.3) that doesn't have the commit [4ac7227](
https://github.com/greenplum-db/gpdb/commit/4ac7227e93dc294b3527557ae7cb5185a734bdd4)
Adding the symbol added as part of the above mentioned commit to be ignored for 6.26.3 release to avoid abi check failures for new PR's on 6X.
> Ignore symbol ConfigureNamesBool_gp for base 6.26.3

- gpdb-doc/markdown/install_guide/install_gpdb.html.md
Greenplum.org does not have a downloads section anymore, pointing to main page instead.
> Fix broken link

- gpdb-doc/markdown/analytics/pl_container_using.html.md
`enable_network` and `roles` are required due to security reason
No code change, just doc.
I forgot to mention this.
> Docs: add enable_network and roles to remote plc example

- src/backend/fts/fts.c
- src/backend/fts/ftsprobe.c
- src/backend/fts/test/ftsprobe_test.c
- src/include/postmaster/fts.h
- src/include/postmaster/ftsprobe.h
- src/test/isolation2/expected/fts_doublefault.out
- src/test/isolation2/expected/fts_errors.out
- src/test/isolation2/expected/fts_errors_1.out
- src/test/isolation2/expected/fts_mirrorless.out
- src/test/isolation2/expected/setup.out
- src/test/isolation2/isolation2_schedule
- src/test/isolation2/mirrorless_schedule
- src/test/isolation2/sql/fts_doublefault.sql
- src/test/isolation2/sql/fts_errors.sql
- src/test/isolation2/sql/fts_mirrorless.sql
- src/test/isolation2/sql/setup.sql
Update ftsprobe process to log each double fault occurence into
gp_configuration_history with the message
Also keep track of contents that are currently under doublefault.
Whenever any content comes out of double fault, update that status into
gp_configuration_history
gp_configuration_history log message:
```
2023-12-13 09:57:54.000504-05 |    5 | FTS: double fault detected for content id 0
2023-12-13 09:59:10.074589-05 |    5 | FTS: segment started for content id 0
```
Enable fts for mirrorless cluster, and also log segments going down/up into gp_configuration_history
```
2023-12-13 09:57:54.000504-05 | 2    | FTS: content id 0 dbid 2 is down.  
2023-12-13 09:59:10.074589-05 | 2    | FTS: content id 0 dbid 2 is now up 
```
> Enable fts for mirrorless and log doublefault in gp_configuration_history

- gpdb-doc/markdown/utility_guide/ref/pg_config.html.md
With commit 8a33784, we are able to retrieve the version of Greenplum via 'pg_config --gp_version'. This patch adds doc about it with little correction.
> [6X][Doc] Add an description entry for pg_config --gp_version.

- gpdb-doc/markdown/utility_guide/ref/pg_config.html.md
With commit a427242, we are able to retrieve the version of Greenplum via 'pg_config --gp_version'. This patch adds doc about it with little correction.
> [Doc] Add an description entry for pg_config --gp_version.

- src/backend/postmaster/pgarch.c
- src/include/access/xlog_internal.h
> [!NOTE]
> This PR is the Partial Backport of GPDB PR https://github.com/greenplum-db/gpdb/pull/16984
1. https://github.com/postgres/postgres/commit/b981df4cc09aca978c5ce55e437a74913d09cccc
2. https://github.com/postgres/postgres/commit/beb4e9ba1652a04f66ff20261444d06f678c0b2d
3. https://github.com/postgres/postgres/commit/1fb17b1903414676bd371068739549cd2966fe87
*<sub>_For more information on actual changes please refer to the relevant commit message._</sub>
<details> 
<summary> 
</summary>
[Prioritize history files when archiving](https://github.com/postgres/postgres/commit/b981df4cc09aca978c5ce55e437a74913d09cccc)
```
Prioritize history files when archiving
At the end of recovery for the post-promotion process, a new history
file is created followed by the last partial segment of the …
```
> [6X backport] Improve performance of pgarch_readyXlog() with many failed status file and history file prioritization

- src/backend/cdb/cdbsubselect.c
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/subselect.sql
As we pull up the sublink to join, the raw join condition is lost in such case:
```
postgres=# explain (costs off, verbose on) WITH cte1(a, b, c, d) AS
(
select * from tl1
) 
select * from cte1 
where 
cte1.b = (
select 
max(tl2.a) 
from 
tl2 join tl3 on tl3.c = tl2.c 
join tl4 on tl4.d = tl2.d 
where 
tl2.b = cte1.c
);
QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice5; segments: 3)
Output: tl1.a, tl1.b, tl1.c, tl1.d
->  Hash Join
Output: tl1.a, tl1.b, tl1.c, tl1.d
Hash Cond: ((tl1.b = "Expr_SUBQUERY".csq_c1) AND (tl1.c = "Expr_SUBQUERY".csq_c0))
->  Seq Scan on public.tl1
Output: tl1.a, tl1.b, tl1.c, tl1.d
->  Hash
Output: "Expr_SUBQUERY".csq_c1, …
```
> Fix join condition lost after pull up sublink to join

- gpMgmt/bin/el8_migrate_locale/README.md
- gpMgmt/bin/el8_migrate_locale/el8_migrate_locale.py
This PR mainly does two things.
1. Add a `verbose` option, it will print more info, like the number of range partitioning tables and partition key collation info.
2. If the GUC `gp_detect_data_correctness` is missing, the script will print an error stack before, improving the error display.
> [6X]Add verbose option and improve the GUC check error display

- src/backend/executor/nodeModifyTable.c
- src/test/regress/expected/update_gp.out
- src/test/regress/expected/update_gp_optimizer.out
- src/test/regress/sql/update_gp.sql
Before this PR, when merging 9.6, this part of the code was commented by the commit https://github.com/greenplum-db/gpdb-postgres-merge/commit/2a864ff1421a631be1ebd2fb68f93cdfb8df09a4.
The test case will report an error because the `tle->expr` is var, not const.
```
test=# create table base_tbl (a int4, b int4) distributed by (a);
CREATE TABLE
test=# insert into base_tbl select g, g from generate_series(1, 5) g;
INSERT 0 5
test=# explain (costs off) update base_tbl set a=a+1;
QUERY PLAN
---------------------------------------------------------------
Update on base_tbl
->  Explicit Redistribute Motion 3:3  (slice1; segments: 3)
->  Split
->  Seq Scan on base_tbl
(5 rows)
test=# alter table base_tbl drop column b;
ALTER TABLE
test=# explain (costs off) …
```
> Remove fixme in nodeModifyTable.c.

- src/backend/commands/resgroupcmds.c
- src/backend/utils/resgroup/resgroup.c
- src/test/isolation2/expected/resgroup/resgroup_auxiliary_tools_v2.out
- src/test/isolation2/input/resgroup/resgroup_io_limit.source
- src/test/isolation2/output/resgroup/resgroup_io_limit.source
- src/test/isolation2/sql/resgroup/resgroup_auxiliary_tools_v2.sql
Fix no response when alter io_limit of resource group to '-1'.
There is no action when `ALTER RESOURCE GROUP xxx SET IO_LIMIT '-1'` before.
Now the action is that clear the content of `io.max` and update relation `pg_resgroupcapability`.
CI: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-fix_io_limit-rocky8
> Fix no response when alter io_limit of resource group to '-1'

- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/test/regress/expected/explain_format_optimizer.out
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/gporca.sql
Previously, Orca would generate unused extra slices when the plan contained Subplans. This was due to a bug in the logic that set the number of InitPlans (which do require an extra slice) to the number of Subplans. This is incorrect--Orca doesn't generate InitPlans, so this value can safely be set to 0. The dispatcher would create the slice table and number of slices as "n = 1 + nMotions + nSubplans;" (where nSubplans is actually the number of InitPlans).
For the query:
```
create table foo (a int, b int);
create table  bar (a int, b int);
test=# explain analyze select (select b from foo where b=bar.a) from bar;
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice2; segments: 3) …
```
> Fix Orca to not generate unnecessary slices for plans with Subplans

- src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp
- src/test/regress/expected/bfv_cte.out
- src/test/regress/expected/bfv_cte_optimizer.out
- src/test/regress/sql/bfv_cte.sql
In preprocessing, ORCA may choose to add select filters in order to help
trigger predicate push down during query normalization. In preprocessing
step PexprReplaceColWithConst(), a duplicate filter is created with
idents replaced by const values. The transformation looks like:
Input:
```
Select
|-- NaryJoin/LeftOuterJoin
|   |-- ...
|   +-- Join Pred (has idents)
+-- Filter
```
Output:
```
Select
|-- Select
|  |-- NaryJoin/LeftOuterJoin
|  |  |-- ...
|  |  +-- Join Pred (has idents)
|  +-- Join Pred (has consts)
+-- Filter
```
However, an issue occurs if the Join Pred contains a CTEAnchor. In that
case the CTEAnchor is "duplicated" and leads to an invalid plan. In
retail build that manifests as a crash during DXL to PlStmt translation.
This commit fixes the issue by choosing to not add …
> [ORCA] Fix ident to const predicate push down optimization

- src/backend/cdb/cdbsubselect.c
- src/test/regress/expected/subselect.out
- src/test/regress/expected/subselect_optimizer.out
- src/test/regress/sql/subselect.sql
from main branch https://github.com/greenplum-db/gpdb/pull/17115
As we pull up the sublink to join, the raw join condition is lost in such case:
```
postgres=# explain (costs off, verbose on) WITH cte1(a, b, c, d) AS
(
select * from tl1
) 
select * from cte1 
where 
cte1.b = (
select 
max(tl2.a) 
from 
tl2 join tl3 on tl3.c = tl2.c 
join tl4 on tl4.d = tl2.d 
where 
tl2.b = cte1.c
);
QUERY PLAN                                                
---------------------------------------------------------------------------------------------------------
Gather Motion 3:1  (slice5; segments: 3)
Output: tl1.a, tl1.b, tl1.c, tl1.d
->  Hash Join
Output: tl1.a, tl1.b, tl1.c, tl1.d
Hash Cond: ((tl1.b = "Expr_SUBQUERY".csq_c1) AND (tl1.c = "Expr_SUBQUERY".csq_c0))
->  Seq Scan on public.tl1
Output: …
```
> [6X] Fix join condition lost after pull up sublink to join

- src/backend/cdb/cdbgroup.c
- src/backend/utils/misc/guc_gp.c
- src/include/cdb/cdbvars.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gp_aggregates.out
- src/test/regress/sql/gp_aggregates.sql
Introduce GUC `gp_enable_mdqa_shared_scan ` for queries with multi-DQA
In some scenarios, using a shared scan during three-stage aggregation
can lead to significant disk I/O and generate large spill files. To
address this issue, a new GUC, `gp_enable_mdqa_shared_scan`, has been
introduced. This configuration option controls whether to use shared
scan in three-stage aggregations.
By default, `gp_enable_mdqa_shared_scan` is set to `true`, enabling
shared scans during three-stage aggregation. This default setting aims
to optimize performance in general use cases. However, for specific
scenarios where disk I/O and spill file size are concerns, users can now
disable shared scans by setting this GUC to `false`.
This change allows for more flexible performance tuning.
This change is 6x only. …
> [6x only]Introduce GUC `gp_enable_mdqa_shared_scan` for queries with multi-DQA

- gpcontrib/gp_toolkit/.gitignore
- gpcontrib/gp_toolkit/expected/gp_toolkit_ao_funcs.out
- gpcontrib/gp_toolkit/sql/gp_toolkit_ao_funcs.sql
- src/backend/access/aocs/aocssegfiles.c
Fix #17142 
We try to use macro to fetch relation'name after closing the relation in error message, which causes a crash.
We do have heap_close in later lines, don't need to close here.
Only for aocs function, ao function is correct, doesn't have this issue.
> Fix gp_toolkit.__gp_aocsseg_history crash on non-aocs tables.

- src/include/postgres.h
DatumPtr is unused in gp7 and is defined in pg_vector. 
When we compile pg_vector v0.6.0 with gp7, it throws the [double-definition error](https://github.com/pgvector/pgvector/blob/master/src/hnsw.h#L130). 
So we want to remove it. BTW, we removed GET_x_BYTE and SET_x_BYTES 
since they are unused.
> Remove unused macro definition.

- src/backend/gpopt/config/CConfigParamMapping.cpp
- src/backend/utils/misc/guc_gp.c
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/regress/expected/gporca.out
- src/test/regress/expected/gporca_optimizer.out
- src/test/regress/sql/bfv_partition_plans.sql
- src/test/regress/sql/gporca.sql
optimizer_enable_dynamicindexscan
optimizer_enable_dynamicbitmapscan
Fix #16885
I meant for the GUC tests to be as sutble as possible. I did verify locally that if those GUC's are turned off, plans not involving dynamic bitmap/index scan are returned in the gporca suite. Specifically, dynamic bitmap/index scan was replaced by dynamic sequential scan.
(cherry picked from commit f82f956350cd4603985227affb8bdd9b7d367689)
> Add ORCA GUC's for dynamic index/bitmap scan

- src/backend/cdb/motion/ic_tcp.c
Fixme:
GPDB_12_MERGE_FIXME: should use WaitEventSetWait() instead of select() following the routine in ic_udpifc.c
This fixme was added in PR #13394 by @interma.
After discussing with @interma offline, initially, he intended to use WaitEventSetWait()
instead of poll in ic_udpifc.c. However, due to the modification of cdbdisp_getWaitSocketFd(CdbDispatcherState *ds)
to cdbdisp_getWaitSocketFds(CdbDispatcherState *ds, int *nsocks), cdbdisp_getWaitSocketFd is also called in ic_tcp.c.
As a result, a fixme was left in ic_tcp.c.
The advantage of using WaitEventSetWait instead of select is that we can monitor the specific
waitevent in the pg_stat_activity view. However, we believe the potential benefits may not be significant.
Therefore, we have decided to simply remove this fixme.
> Remove GPDB_12_MERGE_FIXME in ic_tcp.c

- src/backend/executor/nodeShareInputScan.c
```
/* GPDB_12_MERGE_FIXME: would be nicer to store this hash in the DSM segment or DSA */
info.keysize = sizeof(shareinput_tag);
info.entrysize = sizeof(shareinput_Xslice_state);
shareinput_Xslice_hash = ShmemInitHash("ShareInputScan notifications",
N_SHAREINPUT_SLOTS(),
N_SHAREINPUT_SLOTS(),
&info,
HASH_ELEM | HASH_BLOBS);
```
Shmem is static shared memory which is pre-allocated and initialized during the startup of the postmaster.
It stores frequently accessed data pages and it is suitable for fixed-size data.
The address of static shared memory is the same between different backends. Using static shared memory is much simpler.
DSM and DSA is dynamic shared memory is allocated and managed dynamically during the runtime of the postgres.
It is suitable for temporary data storage, and …
> Fix GPDB_12_MERGE_FIXME in nodeShareInputScan

- src/backend/storage/smgr/md.c
backport https://github.com/greenplum-db/gpdb/pull/17123
This change has no impact to existing behavior but could avoid intermediate unnecessary memory allocation.
It was forgotten to delete by https://github.com/greenplum-db/gpdb-postgres-merge/commit/92a49f49ea1d7015b702e8e9c636a096a9bf71f6#diff-30ebbb2a1d78f03e00b9464c3234529da0eeb1828ce3877750ed7969383bd8a9
> Remove unused buf[MAXPGPATH] variable in mdcreate_ao()

- config/c-compiler.m4
- configure
- configure.in
- src/backend/utils/adt/arrayfuncs.c
- src/backend/utils/adt/arrayutils.c
- src/include/common/int.h
- src/include/pg_config.h.in
- src/include/pg_config.h.win32
- src/include/utils/array.h
- src/test/regress/expected/arrays.out
- src/test/regress/sql/arrays.sql
array_set_element() and related functions allow an array to be
enlarged by assigning to subscripts outside the current array bounds.
While these places were careful to check that the new bounds are
allowable, they neglected to consider the risk of integer overflow
in computing the new bounds.  In edge cases, we could compute new
bounds that are invalid but get past the subsequent checks,
allowing bad things to happen.  Memory stomps that are potentially
exploitable for arbitrary code execution are possible, and so is
disclosure of server memory.
To fix, perform the hazardous computations using overflow-detecting
arithmetic routines, which fortunately exist in all still-supported
branches.
The test cases added for this generate (after patching) errors that
mention the value of …
> Detect integer overflow while computing new array dimensions.

- src/backend/access/transam/xlogfuncs.c
It is definitely supported and used by differential recovery in-tree.
The NOTICE was added when WAL replication was introduced into GPDB in
737e216e9e5f. We have come a long way since then.
Reviewed-by: Huansong Fu <fuhuansong@gmail.com>
> Lift NOT_SUPPORTED notice for pg_start|stop_backup

- src/bin/pg_upgrade/greenplum/check_gp.c
Views that use deprecated operators will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using types or operators that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a deprecated operator causes pg_upgrade to fail. This check calls a support function on the source cluster to check if views using deprecated operators exist.
Due to the limitations of the query walker being a function that only returns a bool, we can only tell if a deprecated operator exists in a view. We do not have an easy way to tell users how many or which deprecated operators are present in the view.
> pg_upgrade: check for views using removed operators

- contrib/pg_upgrade_support/pg_upgrade_support.c
Views that use removed functions will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using functions that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a removed function causes pg_upgrade to fail. In order to detect views with removed functions. A query_tree_walker is used to walk the nodes of all views. Each node is then checked to see if it is a function. If it is, we then check if the oid of the function matches one that is not present in GPDB7.
Currently we only notify end users of views that contain a removed function. We do not log what specific part of the view triggered the check for a removed function.
The following functions were excluded …
> [6x] pg_upgrade: add support func to check if view contains removed functions

- gpcontrib/gp_toolkit/Makefile
- gpcontrib/gp_toolkit/gp_toolkit--1.4--1.5.sql
- gpcontrib/gp_toolkit/gp_toolkit.control
In function `gp_toolkit.gp_move_orphaned_files`, the following SQL will call `pg_file_rename` to move orphaned files:
```
WITH OrphanedFiles AS (
xxxxx
xxxxx
)
SELECT
OrphanedFiles.gp_segment_id,
OrphanedFiles.oldpath,
OrphanedFiles.newpath,
pg_file_rename(OrphanedFiles.oldpath, OrphanedFiles.newpath,
NULL) AS move_success
FROM OrphanedFiles
```
However, `pg_file_rename` will only be called by coordinator, which means, in a distributed environment, segments' files can't be moved as expected.
> Fix incorrect behavior of gp_toolkit.gp_move_orphaned_files

- src/backend/access/common/reloptions_gp.c
- src/backend/utils/datumstream/datumstream.c
- src/include/storage/gp_compress.h
- src/test/binary_swap/test_binary_swap_pre.sql
- src/test/regress/expected/dsp.out
- src/test/regress/expected/rle.out
- src/test/regress/sql/rle.sql
This is a backport of 7X PR: #17147, with conflicts resolved:
(1) USE_ZSTD is replaced with HAVE_ZSTD
(2) Test changes:
using ao_column -> with (appendonly=true, orientation=column)
ALTER TABLE ALTER COLUMN ENCODING is not supported on 6X, so the
test is taken out.
This addresses #12721.
Zstandard is superior to Zlib in terms of both compression speed and
disk footprint. So offer users the ability to rely on it. To enjoy the
benefits of Zstandard compression in column-oriented tables users can
create tables with compresslevel=5|6.
Example:
create table co_rle_zstd(i int encoding(compresstype=rle_type,
compresslevel=5)) using ao_column;
convert existing tables to the new compress levels as well.
Compresslevels 5 and 6 invoke zstd compression with zstd …
> [6X] CO: Support RLE with Zstandard

- gpdb-doc/markdown/install_guide/platform-requirements-overview.html.md
It should have the same level as the head "java". Otherwise it cannot be
accessed through link:
https://docs.vmware.com/en/VMware-Greenplum/7/greenplum-database/install_guide-platform-requirements-overview.html#python
> [Doc] Fix Python requirements head level

- src/backend/cdb/cdbmutate.c
- src/backend/optimizer/plan/subselect.c
- src/include/cdb/cdbmutate.h
- src/test/regress/expected/join.out
- src/test/regress/expected/join_optimizer.out
- src/test/regress/expected/tablesample.out
- src/test/regress/sql/join.sql
- src/test/regress/sql/tablesample.sql
1、In gpdb7 there are a few testcases will still cause panic.
Backport "check whether motion contains nestloop params" from 6X_STABLE to gpdb7.
If we pass params by a motion, throw an error instead of panic.
```
SELECT * FROM
(VALUES (0.0),(10.3),(100.5)) v(nrows),
LATERAL (SELECT count(*) FROM test_tablesample
TABLESAMPLE system_rows (nrows::float8)) ss;
```  
2、Remove start_ignore and end_ignore of lateral testcases.
Some can execute correctly and some will throw an error.
Those which throw an error will try to be supported later.
> Fix crashes of lateral join

- .abi-check/6.26.4/postgres.symbols.ignore
- src/bin/pg_basebackup/pg_basebackup.c
This was found while running gpaddmirrors. The word "direcotory" should obviously have been "directory". Fix it accordingly.
> Fix pg_basebackup verbose message

- src/backend/optimizer/plan/planner.c
When we create a preliminary limit path (to be executed on the QEs), we
were not passing 0 as the estimate for OFFSET (like in 6X), and we were
passing -1 instead. Consequently, in adjust_limit_rows_costs() we were
triggering the 10% estimate calculation when offset isn't provided,
which led to 10% of the subpath's total cost getting added to the
startup cost of the prelim Limit path. I believe that this change was
inadvertently introduced as part of 9.6 merge commit:
98c86ecd2287896e017361ea10e0b08b9d378e8e
This bug led to incorrect costing for:
(*) Queries with no OFFSET clause. Here offset_est = 0 for
adjust_limit_rows_costs() and we incorrectly did the 10% estimation.
This issue was discovered when it was found that regular IndexScans
weren't getting picked as ordering operators for …
> Correctly pass down offset estimate in prelim limit

- src/bin/pg_upgrade/greenplum/check_gp.c
As part of 6 > 7 upgrade we check for views using objects that have been removed in GPDB7. To prevent our 7 > 7 CI tests from failing, version guard the upgrade checks using pg_upgrade support functions that only exist on 6X.
pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/kyeap-version_guard_removed_operators
> pg_upgrade: version guard checks that use 6X support functions

- gpdb-doc/markdown/ref_guide/modules/intro.html.md
- gpdb-doc/markdown/ref_guide/modules/pg_cron.html.md
This PR creates a reference page for `pg_cron` module for the 6.x Greenplum documentation.
> Docs: add pg_cron reference page for GP 6

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/aocs/aocssegfiles.c
- src/backend/commands/copy.c
- src/test/regress/input/uao_ddl/alter_drop_allcol.source
- src/test/regress/input/uao_ddl/create_ao_tables.source
- src/test/regress/output/uao_ddl/alter_drop_allcol.source
- src/test/regress/output/uao_ddl/create_ao_tables.source
The issue is that if the CO table once had column (and data), but later all columns are dropped, then COPY this table would hang:
```sql
create table co(a int) using ao_column;
insert into co select * from generate_series(1,10);
alter table co drop column a;
copy co to stdout; -- this hangs forever
```
The is because `aocs_getnext` is not handling this case well: it would open the segment files but skip the actually scanning (because no projected columns), write no tupleslot values, and finally return TRUE which doesn't make any sense as it did not read any tuple. So a loop to get next tuple would loop forever. If we return FALSE here, we would stop the loop early.
Note that, however, this does not make COPY's behavior for CO to be the same as heap or AO, where we would still copy out the …
> ao/co: fix an issue with COPY zero-column CO table

- src/bin/pg_upgrade/greenplum/check_gp.c
Views that use removed types will cause upgrade to fail. This happens during metadata restore on the target cluster because pg_restore will error trying to create a view using types that do not exist anymore. This is not ideal as we could be many hours into upgrade before a view using a removed type causes pg_upgrade to fail. This check calls a support function on the source cluster to check if views using removed types exist.
pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/kyeap-check_views_removed_types
https://github.com/greenplum-db/gpupgrade/pull/903
https://github.com/greenplum-db/gpdb/pull/17187
https://github.com/greenplum-db/gpdb/pull/17188
> pg_upgrade: check for views using removed types

- gpMgmt/bin/gpcheckperf
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckperf.py
This is to fix gpcheckperf fails with an exception when sometime `time` commmand output has a comma separator instead of a dot. This issue happens in case of certain locale due to decimal number format change. 
Steps to reproduce issue:
```
$export LC_ALL=de_DE_utf8
$time sleep 1
real	0m1,021s
user	0m0,001s
sys	0m0,005s
```
**Fix**: added check if comma present in the time output, replace it with a dot and continue parsing.
**Testing**: Added unit tests to check the output of `parseMultiDDResult()` in case of comma and dot.
> gpcheckperf: Fix for error when the time command has comma in the output

- gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
This PR is to fix issue https://github.com/greenplum-db/gpdb/issues/17180.
We provide more detailed information about logerrors in pg_exttable view in GP7. This is to keep consistent with older GP version.
**DDL**
```
DROP EXTERNAL TABLE if exists public.test_ext;
CREATE READABLE EXTERNAL TABLE public.test_ext
(
id int
)
LOCATION(
'file://gp6/test.txt'
)
FORMAT 'TEXT' ( delimiter 'off')
LOG ERRORS PERSISTENTLY SEGMENT REJECT LIMIT 10 PERCENT;
```
**Before this PR:**
```
SELECT logerrors, options FROM pg_exttable WHERE reloid = 'public.test_ext'::regclass;
logerrors | options
-----------+---------
t         |
(1 row)
```
**After this PR:**
```
testdb=# SELECT logerrors, options FROM pg_exttable WHERE reloid = 'public.test_ext'::regclass;
logerrors |           options …
```
> Fix issue: missing some information about logerrors in pg_exttable view.

- src/backend/access/aocs/aocsam.c
- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/test/isolation2/input/uao/fast_analyze.source
- src/test/isolation2/output/uao/fast_analyze.source
to satisfy sampling rows when the sample size is greater than the
total row number of the table.
RowSampler returned samplerows that could be less than the requesting
sample size. Considering the following example:
```SQL
create table aorow(i int, j int, k int) using ao_row;
insert into aorow select 1, j, j from generate_series(1, 10) j;
delete from aorow where j % 2 = 0;
select * from aorow;
i | j | k
---+---+---
1 | 1 | 1
1 | 3 | 3
1 | 5 | 5
1 | 7 | 7
1 | 9 | 9
(5 rows)
select * from gp_acquire_sample_rows('aorow'::regclass, 10000, 'f') as
(totalrows pg_catalog.float8, totaldeadrows pg_catalog.float8,
oversized_cols_length pg_catalog._float8, i int, j int, k int);
totalrows | totaldeadrows | oversized_cols_length | i | j | k
-----------+---------------+-----------------------+---+---+--- …
```
> [7X] Initialize RowSampler.N to totaltupcount including dead tuples

- src/backend/cdb/cdbpath.c
- src/test/regress/expected/aggregates.out
- src/test/regress/expected/aggregates_optimizer.out
- src/test/regress/expected/gp_create_table.out
- src/test/regress/sql/aggregates.sql
- src/test/regress/sql/gp_create_table.sql
The following sql failed in main branch after we bring in CdbLocusType_OuterQuery.
And it is ok in 6X_stable.
```
create table ttt1(tc1 int,tc2 int);
create table ttt2(tc1 int,tc2 int);
explain create table xt as
select a.tc1,ss.tc2 from ttt1 a join lateral (
select * from ttt2 b where b.tc2 = a.tc2 limit 1) ss on true;
-- In 6X_stable
explain(costs off) create table xt as
select a.tc1,ss.tc2 from ttt1 a join lateral (
select * from ttt2 b where b.tc2 = a.tc2 limit 1) ss on true;
QUERY PLAN                                     
------------------------------------------------------------------------------------
Redistribute Motion 1:3  (slice3; segments: 1)
Hash Key: a.tc1
->  Nested Loop
->  Gather Motion 3:1  (slice1; segments: 3)
->  Seq Scan on ttt1 a
->  Materialize
->  Subquery Scan …
```
> fix create table as lateral join failed

- src/backend/access/external/external.c
- src/backend/commands/exttablecmds.c
- src/test/regress/input/external_table.source
- src/test/regress/output/external_table.source
- src/test/regress/output/external_table_optimizer.source
This PR is to fix issue https://github.com/greenplum-db/gpdb/issues/17179.
In pg_foreign_table.ftoptions location is stored as connected string with delimiter '|', so when uri contain '|' should be escaped, and when read it should be reverse escaped. 
DDL:
```
bash-4.2$ echo "1" > /tmp/\|.txt
bash-4.2$ psql testdb
psql (12.12)
testdb=# CREATE READABLE EXTERNAL TABLE public.test_ext
(
id int
)
LOCATION(
'file://localhost.localdomain/tmp/|.txt'
)
FORMAT 'TEXT' ( delimiter 'off')
ENCODING 'UTF8';
CREATE EXTERNAL TABLE
```
Before this PR:
```
SELECT * FROM public.test_ext;
ERROR:  invalid URI '.txt' : undefined structure
SELECT urilocation from pg_exttable WHERE reloid = 'public.test_ext'::regclass;
urilocation
------------------------ …
```
> Fix external table location escape for delimiter '|'

- src/bin/pg_upgrade/Makefile
installcheck was always a no-op for pg_upgrade until PostgreSQL 15
switched tests to TAP.
Remove the fixme.
> Remove a fixme of pg_upgrade makefile

- contrib/postgres_fdw/deparse.c
- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/postgres_clean.bash
- contrib/postgres_fdw/postgres_fdw.c
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
Before this PR, GPDB won't push OFFSET/LIMIT in the remote servers for MPP FDW when both offset and limit clause are specified.
Because it's **unsafe** if we don't adjust `Remote SQL`.
In this PR, we consider MPP FDW OFFSET/LIMIT pushdown when both OFFSET and LIMIT clause are specified.
We will adjust `Remote SQL` when `mpp_execute = 'all segments'` for query including OFFSET/LIMIT clause.
There are 3 cases for query including OFFSET/LIMIT clause.
**Case 1: only LIMIT is specified**
Two-phase LIMIT plan is enough and there is NO need to adjust `Remote SQL`.
This case had been supported. (Look at PR https://github.com/greenplum-db/gpdb/pull/16177 for more information.)
**Case 2: both LIMIT and OFFSET are specified**
We also need to adjust `Remote SQL` to let GPDB fetch tuples from 0 to …
> Consider MPP FDW LIMIT pushdown when both offset and limit clause are specified

- gpcontrib/gp_check_functions/Makefile
- gpcontrib/gp_check_functions/gp_check_functions--1.1--1.2.sql
- gpcontrib/gp_check_functions/gp_check_functions--1.2.sql
- gpcontrib/gp_check_functions/gp_check_functions.control
In function `gp_move_orphaned_files`, the following SQL will call `pg_file_rename` to move orphaned files:
```
WITH OrphanedFiles AS (
xxxxx
xxxxx
)
SELECT
OrphanedFiles.gp_segment_id,
OrphanedFiles.oldpath,
OrphanedFiles.newpath,
pg_file_rename(OrphanedFiles.oldpath, OrphanedFiles.newpath,
NULL) AS move_success
FROM OrphanedFiles
```
However, `pg_file_rename` will only be called by coordinator, which means, in a distributed environment, segments' files can't be moved as expected.
> [6X] Fix incorrect behavior of gp_move_orphaned_files

- src/test/regress/input/guc_env_var.source
- src/test/regress/output/guc_env_var.source
- src/test/regress/regress_gp.c
Commit d7cdf6ee36a introduced a similar function to this one with regress_putenv(), switch to it.
> Remove udf_setenv() for tests

- src/backend/cdb/cdbutil.c
fts process dumps gpsegconfig_dump file in coordinator datadir. in the current dump it does include datadir from gp_segment_configuration. In this commit added support to include datadir in segment configuration dump.
following functions updated
writeGpSegConfigToFTSFiles()
readGpSegConfigFromFTSFiles()
> [6X backport]Added support to include datadir in gpsegconf_dump file (#16922)

- README.Rhel-Rocky.bash
There are some errors when compiling gpdb7 on rocky. These errors are caused by the leaking of packages.
Co-authored-by: yihong0618 <zouzou0208@gmail.com>
> Fix README.Rhel-Rocky.bash

- gpdb-doc/markdown/ref_guide/config_params/guc-list.html.md
- gpdb-doc/markdown/ref_guide/config_params/guc_category-list.html.md
This PR documents the guc gp_keep_partition_children_locks introduced in https://github.com/greenplum-db/gpdb/pull/16790
> Docs: add guc gp_keep_partition_children_locks

- gpdb-doc/markdown/admin_guide/ddl/ddl-storage.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/ALTER_TYPE.html.md
- gpdb-doc/markdown/ref_guide/sql_commands/CREATE_TYPE.html.md
This PR documents the newly introduced support for RLE with zstd.
Staging site:
https://docs-staging.vmware.com/en/draft/VMware-Tanzu-Greenplum/mireia-linux/greenplum-database/admin_guide-ddl-ddl-storage.html
Note that this PR is against 6X_STABLE and needs to be cherry-picked to main when approved.
> Docs: document RLE with Zstd

- src/backend/utils/adt/numeric.c
- src/test/regress/expected/numeric.out
- src/test/regress/sql/numeric.sql
For numeric type fucntion `add_abs`, if the result's `ndigits` > 34, it will allocate heap memory to store the digits. And if`numeric_sum` is called in the subsequent execution, it will invoke `make_result` to get a finalized agg result, and will free the digits buffer allocated before at the end of `make_result`. However, this var is still in used in the following computation, which will further caused wrong results.
A typical reproduce case is:
```
CREATE TABLE test_win_sum_agg_numeric (c1 numeric, c2 text, c3
date);
INSERT INTO test_win_sum_agg_numeric VALUES
('100014942160023011133842548958242367825725430241610707803699732053545063989664069666352137812280875129584842270112562758099895079.16',
'test', '20200112');
INSERT INTO test_win_sum_agg_numeric VALUES ('21.91', 'test', …
```
> [6X] Fix wrong result of numeric window sum agg

- src/backend/access/aocs/aocsam_handler.c
- src/backend/access/appendonly/appendonly_visimap.c
- src/backend/access/appendonly/appendonlyam_handler.c
- src/include/access/appendonly_visimap.h
- src/include/cdb/cdbaocsam.h
- src/include/cdb/cdbappendonlyam.h
- src/test/regress/input/uao_dml/uao_dml_unique_index_update.source
- src/test/regress/output/uao_dml/uao_dml_unique_index_update.source
This fixes https://github.com/greenplum-db/gpdb/issues/17183.
When consulting the visimap during an UPDATE for the purposes of
uniqueness checks, we used to refer to the visimap from the delete half
of the update.
This is the wrong structure to look at as this structure is not meant to
be consulted while deletes are in flight (we haven't reached
end-of-delete where visibility info from the visimapDelete structure
flows into the catalog).
Instead, we should be consulting the visimapDelete structure attached to
the deleteDesc. This structure can handle visimap queries for tuples
that have visimap changes that haven't yet been persisted to the catalog
table.
The effect of not using this structure meant running into issues such
as: "attempted to update invisible tuple" when we would attempt …
> Fix visimap consults for unique checks during UPDATEs

- gpMgmt/bin/gpcheckcat
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
Issue:
gpcheckcat missing_extraneous test reported errors when gpdb was upgraded from older version to a newer version after performing gpexpand.
RCA:
This is a false alarm and the catalog tables can be skipped during gpcheckcat missing_extraneous test
Solution:
gpcheckcat is modified to skip the tables during missing/extra tests.
> [6X_STABLE] skip pg_description and pg_shdescription tables with gpcheckcat missing/extra tests

- src/bin/pg_upgrade/Makefile
- src/bin/pg_upgrade/greenplum/pg_upgrade_greenplum.h
- src/bin/pg_upgrade/greenplum/util.c
- src/bin/pg_upgrade/pg_upgrade.c
Previously when specifying `--output-dir`, pg_upgrade creates `<output-dir-option>/pg_upgrade_output.d/<timestamp>/[files and logs]`.
This made it very hard to manage the directories when wrapped with gpupgrade. The timestamps are created on the fly, which made each pg_upgrade have unique folder. Unfortunately, this made it hard to track down the pg_upgrades that ran with gpupgrade. Ideally, all pg_upgrade that are run on the segments have the same timestamps.
Modify `--output-dir` such that we only need to give the directory we want to put the files and logs. The user of pg_ugprade will be the one responsible for creating unique log directories.
With this change, pg_upgrade will create
`<output-dir-option>/[files and logs]`.
The data directory already has a log directory which conflicts …
> pg_upgrade: modify `--output-dir` to not create certain sub-directories

- src/backend/access/common/tupconvert.c
- src/backend/executor/execPartition.c
- src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/Delete-Check-AssignedQueryIdForTargetRel.mdp
- src/backend/gporca/data/dxl/minidump/DeleteMismatchedDistribution.mdp
- src/backend/gporca/data/dxl/minidump/DeleteRandomDistr.mdp
- src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTable.mdp
- src/backend/gporca/data/dxl/minidump/DeleteRandomlyDistributedTableJoin.mdp
- src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h
- src/backend/gporca/libgpopt/include/gpopt/base/CColRefComputed.h
- src/backend/gporca/libgpopt/include/gpopt/base/CColRefTable.h
- src/backend/gporca/libgpopt/include/gpopt/metadata/CColumnDescriptor.h
- src/backend/gporca/libgpopt/src/base/CColRefTable.cpp
- src/backend/gporca/libgpopt/src/metadata/CColumnDescriptor.cpp
- src/backend/gporca/libgpopt/src/metadata/CTableDescriptor.cpp
- src/backend/gporca/libgpopt/src/operators/CPhysicalDML.cpp
- src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp
- src/include/access/tupconvert.h
- src/test/regress/expected/DML_over_joins_optimizer.out
- src/test/regress/expected/bfv_dml.out
- src/test/regress/expected/bfv_dml_optimizer.out
- src/test/regress/sql/bfv_dml.sql
Currently, ORCA projects all columns for DML operations, which means that deleting a row requires populating all of the columns in the targetlist. For deletes, the only necessary columns are the ctid and gp_segment_id in the executor. This performance difference is especially evident for CO tables
Things are more complicated due to how Orca handles partitioned tables. Orca produces DynamicScan nodes, which scan the necessary partitions and pass those tuples to the DML operator. While planner uses separate scan and each partition corresponds to a delete operator, for Orca the DML operator needs to figure out which partition to delete from for each tuple. It does this through tuple routing logic in the executor. Because of this, Orca needs to project the partition key and include additional …
> Optimize DELETEs in Orca to only project necessary columns

- src/backend/access/common/reloptions_gp.c
- src/backend/utils/datumstream/datumstream.c
- src/include/storage/gp_compress.h
- src/test/binary_swap/test_binary_swap.sh
- src/test/binary_swap/test_binary_swap_pre.sql
- src/test/regress/expected/dsp.out
- src/test/regress/expected/rle.out
- src/test/regress/sql/rle.sql
This addresses #12721.
Zstandard is superior to Zlib in terms of both compression speed and
disk footprint. So offer users the ability to rely on it. To enjoy the
benefits of Zstandard compression in column-oriented tables users can
create tables with compresslevel=5|6.
Example:
create table co_rle_zstd(i int encoding(compresstype=rle_type,
compresslevel=5)) using ao_column;
Alternatively, users can use ALTER TABLE ALTER COLUMN ENCODING to
convert existing tables to the new compress levels as well.
Compresslevels 5 and 6 invoke zstd compression with zstd levels 1 and 3
respectively. Since zstd level 3 is the default and the recommended
level, compresslevel = 6 should cover most cases and is highly
encouraged.
Notes:
(1) Since zstd level = 1 can readily beat zlib level = 9 in terms of …
> CO: Support RLE with Zstandard

- src/backend/utils/mmgr/freepage.c
- src/include/utils/freepage.h
- src/include/utils/relptr.h
Backport from upstream 
https://github.com/postgres/postgres/commit/7201cd18627afc64850537806da7f22150d1a83b
Previously, we encoded both NULL and the first byte at the base address as 0.  That confusion led to the assertion in commit e07d4ddc, which failed when min_dynamic_shared_memory was used.  Give them distinct encodings, by switching to 1-based offsets for non-NULL pointers.  Also improve macro hygiene in passing (missing/misplaced parentheses), and remove open-coded access to the raw offset value from freepage.c/h.
> Fix relptr's encoding of the base address.

- gpMgmt/bin/gpcheckcat
- gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
- gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
- gpMgmt/test/behave/mgmt_utils/steps/data/gpcheckcat/create_legacy_hash_ops_tables.sql
- gpMgmt/test/behave/mgmt_utils/steps/data/gpcheckcat/create_non_legacy_hashops_tables.sql
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Gpcheckcat is enhanced to report if there are tables created using legacy and non legacy hashops in distribution policy. This check is essential as ORCA fails back to planner if there is mix distribution policy found.
Option Added 
`gpcheckcat -R mix_distribution_policy
`
High level design of "gpcheckcat -R mix_distribution_policy" Check if there are tables created with both legacy and non legacy hashops in distribution policy.
1.      If there is Mix Distribution Policy
-       Report error that there is mix distribution policy.
-       Create an sql file containing the sql query using which the user can
obtain the table names created with legacy and non legacy hashops
2.     In case there is no Mixed Policy
-      Check if gp_use_legacy_hashops is on and there are no tables created with …
> [6X_STABLE] gpcheckcat enhancement to report if there are tables created using mix distribution policy 

- .abi-check/7.1.0/postgres.symbols.ignore
- src/backend/cdb/cdbpath.c
- src/backend/gpopt/gpdbwrappers.cpp
- src/backend/utils/cache/lsyscache.c
- src/include/utils/lsyscache.h
- src/test/regress/expected/triggers_gp.out
- src/test/regress/sql/triggers_gp.sql
Check `make_splitupdate_path()`, it is supposed to fail, but Greenplum
skipped the check on the table's children while merging PostgreSQL 12.
This commit gets the check back.
> Fail the SplitUpdate if table's any child has update triggers

- src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalGet.h
- src/backend/gporca/libgpopt/src/operators/CLogicalForeignGet.cpp
- src/backend/gporca/libgpopt/src/operators/CLogicalGet.cpp
- src/backend/gporca/server/src/unittest/CTestUtils.cpp
Let's prefer to not use default parameters for a couple reasons:
1) It makes code reading harder because it essentially adds a new
function signature. When there are multiple signatures with default
parameters it takes longer to find out which one is actually used.
2) It makes it painful to add new parameters and can lead to subtle
bugs. For example, if signature changes from: C(a, c=1) to C(a, b,
c=1), then all the callers must be carefully updated. Otherwise, an
old caller C(1, 2) may now pass unexpected arguments.
Also, refactor to use delegating constructor to remove code duplication.
---
Dev Pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-orca-delegating-constructor-refactor-rocky8
> [ORCA] Remove default parameter argument

- src/backend/gporca/data/dxl/minidump/ParallelUnionAllWithJson.mdp
- src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp
- src/backend/gporca/server/CMakeLists.txt
- src/test/regress/expected/union.out
- src/test/regress/expected/union_optimizer.out
- src/test/regress/sql/union.sql
It was observed that while populating default opfamilies in PopulateDefaultOpfamilies(), for some of the operator the retrieved opfamily can be 'InvalidOid'. Eg - For 'json', the distribution opfamily is 'InvalidOid'. 
Using this invalid value for further processing leads to crash in ORCA. To prevent this condition, a check is added before using the mdid of opfamily.
This is a back port of [PR 17165 ](https://github.com/greenplum-db/gpdb/pull/17165)
> Handle Invalid Return Value For Opfamily Mdid.

- src/bin/pg_upgrade/check.c
Running pg_upgrade -c and checking for roles starting with "pg_" prefix doesn't say "fatal" when there is an error, instead it says "ok"
These changes corrects the output to show "fatal" on failure and also gets the user a list of all roles that failed the check
Sample output:
```
Checking for tables WITH OIDS                               ok
Checking for invalid "sql_identifier" user columns          ok
Checking for invalid "unknown" user columns                 ok
Checking for hash indexes                                   ok
Checking for roles starting with "pg_"                      fatal
| Your installation contains roles starting with "pg_".
| "pg_" is a reserved prefix for system roles, the cluster
| cannot be upgraded until these roles are renamed.
| A list of roles starting with …
```
> Backport upstream upgrade check improvements for roles starting with "pg_"

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment_triples.py
- gpMgmt/bin/gppylib/programs/test/unit/test_cluster_clsrecoversegment_triples.py
- gpMgmt/doc/gprecoverseg_help
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
- gpdb-doc/markdown/utility_guide/ref/gprecoverseg.html.md
Backport of https://github.com/greenplum-db/gpdb/pull/16719
This PR added support for using the -i flag with differential recovery in the gprecoverseg command, enhancing its capabilities.
**Implementation:** 
Simultaneous Use of -i and --differential:
Added the functionality to allow the use of both the -i and --differential options simultaneously in the gprecoverseg command. This means that by providing a recovery configuration file with the -i flag and specifying the --differential flag, you will initiate a differential recovery process for all hosts listed in the recovery configuration file, similar to how the -i and -F options currently work together
**Recovery Type Specification in Recovery Configuration File:**
Added the functionality to specify I/D/F as a recovery type for each …
> [6X Backport] Added Support for -i flag with differential recovery

- src/backend/access/transam/xlog.c
> [!IMPORTANT]
> Backporting  __`postgres 12`__ commit https://github.com/postgres/postgres/commit/683e0ef5530 to __`GPDB 6X_STABLE`__ branch.
Original Commit Message:
Previously when there were multiple timelines listed in the history file of the recovery target timeline, archive recovery searched all of them, starting from the newest timeline to the oldest one, to find the segment to read. That is, archive recovery had to continuously fail scanning the segment until it reached the timeline that the segment belonged to. These scans for non-existent segment could be harmful on the recovery performance especially when archival area was located on the remote storage and each scan could take a long time.
To address the issue, this commit changes archive recovery so …
> [6X backport] Prevent archive recovery from scanning non-existent WAL files.

- src/backend/cdb/cdbllize.c
- src/backend/optimizer/plan/createplan.c
- src/include/optimizer/planmain.h
- src/test/regress/expected/subselect_gp.out
- src/test/regress/expected/subselect_gp_optimizer.out
- src/test/regress/sql/subselect_gp.sql
Fix issue: #14682
The following codes in cdbpathtoplan_create_motion_plan will ignore path->path.pathkeys,
Which lead to incorrect results.
``` 
else if (CdbPathLocus_IsOuterQuery(path->path.locus))
{
motion = make_union_motion(subplan);
motion->motionType = MOTIONTYPE_OUTER_QUERY;
}
```
So use make_sorted_union_motion instead of make_union_motion if path has pathkeys.
> Fix result is wrong when outer query has order by after LATERAL subquery

- src/backend/optimizer/util/plancat.c
- src/test/regress/expected/hash_part.out
- src/test/regress/sql/hash_part.sql
In a rare scenario: 
A (Postgres-style) partition AO table with index on it, but haven't created any child table for it yet. QD will panic when accessing it.
Root cause is in the `get_relation_info()`:
```
* no child table mean no corresponding entry in pg_inherits => `inhparent` is false
* then go into the `hasindex` condition and will check the AO version soon
* but `relation->rd_appendonly` is NULL (since it's a parent table)
* then panic happened in `AORelationVersion_Validate()`
```
Fix:
Using `RelationStorageIsAO()` (rather than `RelationIsAppendOptimized()`) as the prerequisites check: it checks the "true" storage, so skip the parent partition table. (We did a similar check in `DefineIndex()`)
No need to port to 6x (since no related logic in it).
> Do RelationStorageIsAO() check before call AORelationVersion_Validate()

- src/backend/utils/mmgr/portalmem.c
commit c5454f9 add deteled comment and commit 41baee7 remove the comment.
Currently, every MarkPortalActive() caller ensures it updates the portal status again before relinquishing control. When using an upper-level portal in a subtransaction, change to PORTAL_READY or when error happens change to PORTAL_FAILED, so ACTIVE can't happen here.
> Remove GPDB_96_MERGE_FIXME in portalmem.c

- src/backend/utils/misc/faultinjector.c
- src/test/isolation2/expected/cancel_query.out
- src/test/isolation2/sql/cancel_query.sql
we should CHECK_FOR_INTERRUPTS() as FaultInjectorTypeSuspend is sleep in while().
> Fix Inject_fault suspend cannot be canceled

- gpMgmt/bin/gpcheckresgroupv2impl
- src/backend/utils/resgroup/cgroup-ops-linux-v2.c
`cpu.pressure` is one of API for PSI.
PSI(Pressure Stall Information) is an optional feature of the Linux kernel.
PSI is not enabled by default on some Linux distributions. For example, on UOS 20 SP1:
```bash
gpdb@yz-PC:/sys/fs/cgroup/gpdb$ pwd
/sys/fs/cgroup/gpdb
gpdb@yz-PC:/sys/fs/cgroup/gpdb$ ll cpu.*
-rw-r--r-- 1 gpdb gpdb 0 Apr   8 19:19 cpu.max
-r--r--r-- 1 gpdb gpdb 0 Apr   8 19:19 cpu.stat
-rw-r--r-- 1 gpdb gpdb 0 Apr   8 19:19 cpu.weight
-rw-r--r-- 1 gpdb gpdb 0 Apr   8 19:19 cpu.weight.nice
```
This causes GPDB to FAIL to start if `gp_resource_manager='group-v2'`.
On the other hand, `cpu.pressure` is not used in GPDB resource management, so it can be removed.
> Removed the permission check for `cpu.pressure` item when resource manager sets to 'group-v2'.

- src/backend/cdb/endpoint/cdbendpoint.c
During SetupEndpointExecState, hold the LWLOCK to ensure that allocating the endpoint and setup_endpoint_token_entry are atomic operations.
> Fix token for user id xxx doesn't exist (#17325)

- src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
- src/backend/gporca/data/dxl/minidump/LeftSemiJoinCE.mdp
- src/backend/gporca/data/dxl/minidump/SystemColCtidStats.mdp
- src/backend/gporca/data/dxl/minidump/SystemColSegIdStats.mdp
- src/backend/gporca/server/CMakeLists.txt
- src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
- src/test/regress/expected/tidscan_optimizer.out
fix issue [17249](https://github.com/greenplum-db/gpdb/issues/17249)
> Orca: reinstate the retrieval of system column statistics

- gpMgmt/bin/gppylib/recoveryinfo.py
- gpMgmt/bin/gppylib/test/unit/test_unit_recoveryinfo.py
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
Currently when gprecoverseg fails, it records the error in a log file. This log file can be pg_basebackup/pg_rewind file depending on the type of recovery the failed segments were undergoing.
So in case of gprecoverseg failure, the user has to navigate through the log file to get the reason for failure.
With these changes it will enable the user to get a primal understanding on the reason for failure by displaying a snippet of error on console. Gprecoverseg will obtain last occurring error/panic/fatal message from the log file and display it. For more details the user can dive into the reported logfile.
`20231106:15:28:00:087928 gprecoverseg:sshirishaXG4C7:sshirisha-[INFO]:-------------------------------
20231106:15:28:00:087928 gprecoverseg:sshirishaXG4C7:sshirisha-[INFO]:-Failed to …
> Project pg_basebackup, pg_rewind or pg_ctl start errors to gprecoverseg output

- src/backend/cdb/motion/ic_udpifc.c
- src/include/cdb/cdbicudpfaultinjection.h
- src/test/regress/expected/icudp/icudp_full.out
- src/test/regress/sql/icudp/icudp_full.sql
Backport from 7X commit https://github.com/greenplum-db/gpdb/commit/b8411c0ba394d5df44056c07993038e59820a1de
When the user encounters the IC error `interconnect may encountered a network error, please check your network`, one possible reason is MTU settings.
As the error message is very generic, this PR gives a hint message about MTU settings when the error no is `EMSGSIZE` for `sendto()`
> [6X]Add hint message for MTU settings when IC reports ERROR Failed to send packet

- src/backend/access/bitmap/bitmapxlog.c
- src/backend/commands/dbcommands.c
- src/backend/utils/init/postinit.c
An obvious memory leak in `_bitmap_xlog_insert_bitmapwords()`, it caused the memory usage of startup process to continue to grow. We already have a user to report it and it can be reproduced locally.
* Fix it in the first commit.
* In the process of checking this issue, we found another memory leak related commit of upstream (https://github.com/postgres/postgres/commit/0bd56172b2871e94c0d7115ffbf430308317ac49), also ported it in the second commit.
(need to backport to 6x)
> Fix the memory leak in _bitmap_xlog_insert_bitmapwords()

- src/backend/postmaster/pgstat.c
- src/backend/replication/walreceiver.c
- src/backend/replication/walsender.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/misc/postgresql.conf.sample
- src/bin/pg_basebackup/receivelog.c
- src/include/access/xlog.h
- src/include/pgstat.h
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/perl/PostgreSQL/Test/Utils.pm
- src/test/recovery/t/121_streaming_and_archiving.pl
This commit introduces a GUC `wal_sender_archiving_status_interval`
that will specify the interval at which primaries will send an
archival status messages to their mirrors (including coordinator and
standby coordinator). Any value greater than zero will enable this
feature and set the interval.
Currently, if a primary loses connectivity to its archive repository
while the streaming replication between the primary and its mirror is
intact, it is likely that there will be WAL files that the mirror has
but the archive repository does not. If primary goes down at this
stage, those WAL files will be lost forever as they are marked as
.done on the mirror as part of regular streaming replication
logic. When the mirror is promoted, it will start archiving from the
last WAL file that was streamed …
> Stream WAL archiving status from primaries to mirrors

- gpMgmt/test/behave/mgmt_utils/gpexpand.feature
- src/backend/access/transam/xact.c
- src/backend/access/transam/xlog.c
`gpexpand` will create new segment by doing pg_basebackup from coordinator, and DTX can be started in coordinator during that phase. So the newly added segment's checkpoint XLOG may contain DTX info, which will result in the start of the segment failed.
> Avoid replay dtx info in checkpoint for newly expanded segments

- contrib/postgres_fdw/Makefile
- contrib/postgres_fdw/deparse.c
- contrib/postgres_fdw/expected/mpp_gp2pg_postgres_fdw.out
- contrib/postgres_fdw/sql/mpp_gp2pg_postgres_fdw.sql
While play MPP FDW with LIMIT, found several cases could be improved:
When there were NULL or zero values in OFFSET/LIMIT, we may don't need to fetch more rows, and expression
has NULL plus others is pointless.
example before this fix:
```sql
EXPLAIN (VERBOSE, COSTS OFF)
SELECT c1, c2 FROM mpp_ft2 order by c1 limit 0 offset 998;
QUERY PLAN
--------------
Limit
Output: c1, c2
->  Gather Motion 2:1  (slice1; segments: 2)
Output: c1, c2
Merge Key: c1
->  Foreign Scan on public.mpp_ft2
Output: c1, c2
Remote SQL: SELECT c1, c2 FROM "MPP_S 1"."T 2" ORDER BY
c1 ASC NULLS LAST LIMIT (998::bigint + 0::bigint)
```
We will have to fetch 998 rows from remote, but as we have limit 0, that's pointless.
With this fix:
```sql
EXPLAIN (VERBOSE, COSTS OFF)
SELECT c1, c2 FROM mpp_ft2 order by c1 limit 0 …
```
> Optimize MPP FDW LIMIT/OFFSET push down when there is NULL/0.

- src/backend/commands/trigger.c
- src/test/isolation2/expected/gdd/concurrent_update.out
- src/test/isolation2/expected/gdd/concurrent_update_optimizer.out
- src/test/isolation2/sql/gdd/concurrent_update.sql
Panic occurs when we meet the following three conditions at the same time:
1. set gp_enable_global_deadlock_detector=true;
2. The table should have a before row update trigger.  
3. There is a concurrence when executing update statement.
In ExecBRUpdateTriggers
```
if (newSlot != NULL)
{
slot = ExecFilterJunk(estate->es_junkFilter, newSlot);
slottuple = ExecFetchSlotHeapTuple(slot);
newtuple = slottuple;
}
```
We use estate->es_junkFilter, But it is null, so it is panic.
estate->es_junkFilter is used for select and resultRelInfo->ri_junkFilter
used for DML.We should use resultRelInfo->ri_junkFilter instead of
estate->es_junkFilter here.
GPDB7 uses resultRelInfo->ri_junkFilter from the beginning, So it is ok.
GPDB6 uses estate->es_junkFilter from the beginning.
I think there is something …
> fix panic when concurrent update with before row update trigger

- gpMgmt/bin/go-tools/.gitignore
- gpMgmt/bin/go-tools/internal/config/config.go
- gpMgmt/bin/go-tools/internal/config/config_test.go
- gpMgmt/bin/go-tools/internal/config/database.go
- gpMgmt/bin/go-tools/internal/config/infra.go
- gpMgmt/bin/go-tools/internal/enums/auth_type.go
- gpMgmt/bin/go-tools/internal/enums/deployment_type.go
- gpMgmt/bin/go-tools/test/data/gpdeploy.testconf
- gpMgmt/bin/go-tools/test/data/gpdeploy_override.testconf
- gpMgmt/bin/go-tools/testutils/testutils.go
We are extending go-tools to manage OS configuration in a greenplum cluster.
This commit has following changes in go-tools :
* added package internal/pkg/config, with configuration details for remote hosts to be used for OS configirations
* added package internal/pkg/enums, with enums for authentication type and greenplum deployment type
> Add new fields to gp.conf for infra requirements

- gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
- gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
- gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
- gpMgmt/test/behave/mgmt_utils/gprecoverseg_newhost.feature
- gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
- gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
**Fix1:**
- The logging format has been changed to display date and time along with hostname and dbid when showing progress of pg_rewind/pg_basebackup/rsync process.
Previous format:
<hostname> (dbid 22): 701679/1421743313 kB (0%), 0/1 tablespace (...test2/gpseg20/pg_log/xxx)
New format:
2024-03-19 16:05:38.202000: <hostname> (dbid 22): 701679/1421743313 kB (0%), 0/1 tablespace (...test2/gpseg20/pg_log/xxx)
**Fix2:**
- Do not remove progress files of pg_basebackup/pg_rewind/rsync process from logdir even if the recovery was successful. The current behaviour is to remove these progess logs if gprecoverseg completes successfully. Having these progress files will help troubleshoot  slow running instances of pg_rewind/pg_basebackup/rsync. But the problem here is, these files can consume the …
> [7X] gprecoverseg: progress logging improvement

- .abi-check/6.27.0/postgres.symbols.ignore
- src/backend/postmaster/pgstat.c
- src/backend/replication/walreceiver.c
- src/backend/replication/walsender.c
- src/backend/utils/misc/guc_gp.c
- src/backend/utils/misc/postgresql.conf.sample
- src/bin/pg_basebackup/receivelog.c
- src/include/access/xlog.h
- src/include/pgstat.h
- src/include/utils/guc.h
- src/include/utils/unsync_guc_name.h
- src/test/recovery/t/121_streaming_and_archiving.pl
Backported from 7x commit: c42ee49db3dcbcb42f5e82f958dae8664ada74f5 with some conflicts.
This commit introduces a GUC `wal_sender_archiving_status_interval` that will specify the interval at which primaries will send an archival status messages to their mirrors (including coordinator and standby coordinator). Any value greater than zero will enable this feature and set the interval.
Currently, if a primary loses connectivity to its archive repository while the streaming replication between the primary and its mirror is intact, it is likely that there will be WAL files that the mirror has but the archive repository does not. If primary goes down at this stage, those WAL files will be lost forever as they are marked as .done on the mirror as part of regular streaming replication logic. When …
> [6X Backport] Stream WAL archiving status from primaries to mirrors

- gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_configurationImplGpdb.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_reconfigurer.py
- gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_on_segments.py
- tests from gpMgmt/bin/gppylib/operations dir  were not being executed with 'make check' as __init__.py file was missing from gppylib/operations/test directory, added the file.
- Fixed few of the failing tests
> Fix gppylib/operations unit tests 

- src/backend/access/aocs/aocsam.c
- src/backend/access/appendonly/appendonlyam.c
- src/backend/utils/datumstream/datumstream.c
- src/test/isolation2/input/uao/fast_analyze.source
- src/test/isolation2/output/uao/fast_analyze.source
Sampling on CO tables requires all columns sub-segfiles
have the same total `tupcount` presented physically,
ADD COLUMN operation didn't populate physical rows which have
default values for better performance. This would break the
assumption as the new added column may have less phyical rows
than the anchor column, result in sampling scan may exceed
EOF on new added columns.
The solution of above issue is, after getting the target rowNum
of the anchor column (aka `phyrow`), fetch the same rowNum as
`phyrow` for the rest non-anchor columns instead of re-caculating
the target rowNum for each column.
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/hw-7X-debug-ao-sampling
> Fix CO sampling crashed on added column

- gpMgmt/bin/gpexpand
- gpMgmt/doc/gpexpand_help
Because the 'icproxy' is a configurable function. So, if we have not config it, give us a chance to bypass it.
> Add a new option for gpexpand to bypass checking the icproxy address

- gpMgmt/bin/gppylib/util/ssh_utils.py
- gpMgmt/bin/gppylib/util/test/unit/test_cluster_ssh_utils.py
Currently `gpssh` always clears out the `TERM` env variable before performing SSH connections. This will cause problems when users want only to use a specific terminal (like tmux) when performing SSH connections since the empty `TERM` will cause some terminals to fail.
To fix this issue, a retry operation is added when trying to login to a host. The first login attempt is made in the current manner where it clears out the `TERM` env variable. If it fails, then the operation is retried by restoring the `TERM` env variable.
`gpssh` will now also print the exception in case of errors so that we get to know the actual reason for SSH failures aiding us in debugging.
**Output During Failure**
Before:
```
[gpadmin@cdw ~]$ gpssh -h cdw
[ERROR] unable to login to cdw
Could not acquire connection. …
```
> gpssh: Retry with TERM env variable set during failures

- gpMgmt/bin/gppylib/util/ssh_utils.py
- gpMgmt/bin/gppylib/util/test/unit/test_cluster_ssh_utils.py
This is a backport of https://github.com/greenplum-db/gpdb/pull/17345
Currently gpssh always clears out the TERM env variable before performing SSH connections. This will cause problems when users want only to use a specific terminal (like tmux) when performing SSH connections since the empty TERM will cause some terminals to fail.
To fix this issue, a retry operation is added when trying to login to a host. The first login attempt is made in the current manner where it clears out the `TERM` env variable. If it fails, then the operation is retried by restoring the `TERM` env variable.
`gpssh` will now also print the exception in case of errors so that we get to know the actual reason for SSH failures aiding us in debugging.
**Output During Failure**
Before:
```
[gpadmin@cdw ~]$ gpssh -h …
```
> [6X Backport] gpssh: Retry with TERM env variable set during failures

- src/backend/cdb/cdbgroup.c
- src/backend/optimizer/plan/plangroupext.c
- src/test/regress/expected/bfv_dd.out
- src/test/regress/expected/bfv_dd_multicolumn.out
- src/test/regress/expected/gp_dqa.out
- src/test/regress/expected/gp_dqa_optimizer.out
- src/test/regress/sql/gp_dqa.sql
In the 6x side, if the subpath's locus collocates tuples with group keys, the planner favors
local sortgroupagg over MDQ join rewrite. We also choose sortgroupagg when the group
key becomes constant, as constants should also be collocated.
In this PR, we need to differentiate between an empty groupClause and a constant
groupClause, as they are obviously distinct. In the function `cdb_grouping_planner`, 
`root->group_pathkeys == NULL` and `root->parse->groupClause` collocates with
subpath's locus indicate constant groupClause in the query. Otherwise, the groupClause
should be empty.
Fix Github Issue https://github.com/greenplum-db/gpdb/issues/17434
> [6X] fix wrong result of MDQA in planner

- gpMgmt/bin/go-tools/utils/sys_utils.go
When `netcat` listens on a port without mentioning the IP address, the current validation of the port in use fails. 
Added a check to confirm the port is not in use by dialing the connection. 
Verified by manually running validation when `netcat` is with host and also without host.
> Gpinitsystem2.0 - Bug-Fix Validate port in use by dialing connection

- src/backend/commands/indexcmds.c
- src/test/isolation2/sql/concurrent_index_creation_should_not_deadlock.sql
AlterTableCreateAoBlkdirTable() is being called unconditionally, it upgrades ShareLock to ShareRowExclusiveLock hence may result in deadlock for concurrent index creation even if block directory is present on the append-optimized table. This is regression in 7X compared to 6X. As a fix avoiding call to
AlterTableCreateAoBlkdirTable() if block directory is present which is checked already in DefineIndex() with ShareLock held.
Just note: the deadlock case for concurrent index creations in absence of block directory (which is initial index) still exists, as in absence of block directory, lock upgrade from ShareLock to ShareRowExclusiveLock in DefineIndex() still exists and is hard to resolve. Existing test 
concurrent_index_creation_should_not_deadlock wasn't testing the case correctly. …
> Resolve Deadlock: Allow Concurrent Creation of Non-First Index on AO

- src/backend/commands/vacuum.c
- src/test/regress/expected/vacuum_ao_aux_only.out
- src/test/regress/sql/vacuum_ao_aux_only.sql
Appendonly partitioned table do not have any auxiliary table, so partitioned table itself should not participate in VACUUM AO_AUX_ONLY
Dev-pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/hw-fix_vacuum_aux_only
> Fix crash caused by vacuum ao_aux_only on AO partitioned table.

- src/backend/commands/matview.c
- src/test/regress/expected/matview.out
- src/test/regress/expected/matview_optimizer.out
- src/test/regress/sql/matview.sql
In postgres, with option "WITH NO DATA", the materialized view will be truncated without run the query.
In GPDB, the refresh clause is dispatched to segments when execute the query plan. But for WITH NO DATA option, it should be like a TRUNCATE like in postgres, so it doesn't need to take long time to run the query.
By adding an constant-FALSE to the qual to generate a result plan with One-Time Filter. We have hold matview's distribution policy into the query->intoPolicy, planner will create a motion node on the top so that the refresh clause will still dispatch to segments with the query plan and the query can be execute quickly.
> [6X] Improve refresh materialized view with "no data" option

- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_db_validation_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_env_validation_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_test.go
- gpMgmt/bin/go-tools/test/integration/testutils/db_utils.go
- gpMgmt/bin/go-tools/test/integration/testutils/locale_utils.go
- gpMgmt/bin/go-tools/test/integration/testutils/test_utils.go
This commit adds functional tests for the changes committed in the gpinitsystem support for mirror PR https://github.com/greenplum-db/gpdb/pull/17294.
init_cluster_config_validation_test.go - This contains tests related to the input init config provided with support for mirrors and functions to form default config with primary and mirror support
init_cluster_db_validation_test.go - This contains tests related to the database configuration checks after the cluster is successfully initialized with mirror support, gprecoverseg validation, gpstat replication validation
init_cluster_env_validation_test - cluster initialisation Validation related to mirror directory is not empty and mirror port is in use
> gp init cluster: support for mirror functional tests

- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_config_validation_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_db_validation_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_suite_test.go
- gpMgmt/bin/go-tools/test/integration/init_cluster/init_cluster_test.go
This commit adds functional tests for expansion support changes pushed in the PR
https://github.com/greenplum-db/gpdb/pull/17335
Below changes are included:
init_cluster_config_validation_test.go - This contains tests related to the input expansion config validations, new functions GetDefaultExpansionConfig is added to create default config with expansion support along with config validaiton related tests
init_cluster_db_validation_test.go - This contains tests related to the database configuration checks after the cluster is successfully initialized with expansion support, it also included validation for spread and group mirroring
init_cluster_test.go: This includes expansion validation by passing config file with different file formats
init_cluster_suite_test.go: In this file check has …
> [gpinitsystem2.0] Functional tests for expansion support

- gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
Following gprecoverseg scenarios are not valid-
* SIGINT on gprecoverseg should delete the progress file
* SIGINT on gprecoverseg differential recovery should delete the progress file
Reason: if user selects yes when prompted for input at the time of interrupt, gprecoverseg will be terminated and segments will still be down. If user selects no, then recovery will continue marking the segments up but progress file will exist. Hence above scenarios are invalid.
Assertion of progress file deletion has been covered already in following scenario: 
- gprecoverseg should terminate on SIGINT when user selects Yes in the prompt
Similar scenario for differential recovery should also be added in future, when we find any solution for suspending the ongoing differential recovery of segments.
> [7X] Removed redundant tests

- gpMgmt/bin/gpexpand
When user uses a distribution **without ENABLE_IC_PROXY**, gpexpand complains an error `unrecognized configuration parameter gp_interconnect_proxy_addresses` when checking the ICProxy addresses.
We cannot assume all GP distribution have this Guc (e.g. compile by source code), so add a simple try ... catch logic to prevent the error.
(As the follow up of https://github.com/greenplum-db/gpdb/pull/17316#issuecomment-2060232989)
> Bypass the ICProxy addresses check of gpexpand when disable ENABLE_IC_PROXY

- doc/src/sgml/ref/pg_waldump.sgml
- src/bin/pg_waldump/pg_waldump.c
- src/bin/pg_waldump/t/001_basic.pl
**Context:**
As suggested [here](https://github.com/greenplum-db/gpdb/pull/17126#issuecomment-2014060576) we need to fetch the last valid wal segment to calculate the remaining bytes of startup recovery. So added option --last-valid-walname to pg_waldump to emit the last valid wal segment for the timeline provided with -t.  
**New option:**
` --last-valid-walname     output last valid wal segment for given timeline`
**Usage:**
`pg_waldump -p <pg_wal_path> -t <timeline> --last-valid-walname`
**Example:**
```
pg_waldump -p ./gpAux/gpdemo/datadirs/dbfast3/demoDataDir2/pg_wal/ -t 15 --last-valid-walname 
000000010000000000000003
```
Testing: Added TAP tests for pg_waldump
Code changes borrowed from: https://www.postgresql.org/message-id/attachment/129055/v5-0001-Introduce-feature-to-start-WAL- …
> pg_waldump: Added option --last-valid-walname

- src/bin/pg_waldump/pg_waldump.c
- src/bin/pg_waldump/t/001_basic.pl
Removed strerror(errno) from error messages as it is not required for argument checks.
> Fix compiler warnings

- gpMgmt/bin/gppylib/programs/clsAddMirrors.py
- gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
- gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py
Issue: gpaddmirrors with -p option produces ports outside of the valid rangeMirror error
RCA: gpaddmirrors with -p option was considering the coordinator port number while calculating the mirror port, because of that it lands up error case if the coordinator port is 5432 and calulcated mirror port will come 5432 + 500 = 5932 which is less than allowed minPort for mirror (6432).
Fix: with this fix now the mirror port will be calulated from min segment port available.
for example :
Coordinator port : 5432
Primary base port : 8000
Mirror base port will be 8000 + offset.
Added behave test case to validate the same.
> Fix Addmirror valid range port error

- src/backend/catalog/pg_attribute_encoding.c
- src/test/regress/expected/alter_table_set_am.out
- src/test/regress/sql/alter_table_set_am.sql
Changing access method of heap/ao_row tables to ao_column tables fail when
the attribute of heap/ao_row is bigger than 10. The error message is
could not find tuple for attnum 10 for relid, which roots from a
misinitialization of the attnum_entry_present flag. This commit fixes the issue.
> Fix AT SETAM for heap/ao_row to ao_column when attnum >= 10
