greenplum-db/gpdb

gpcontrib/gp_replica_check/gp_replica_check.c

If primary and mirror are not connected or not in STREAMING state, fail fast and
not retry. Retry only in-case they are connected but checkpoint is not streamed
across and yet to be replayed. Also, here reduce the waiting time from 1 sec
from checking to 1/5 of a sec so speed up.
Many times in CI replica check appeared to be hung because if primary and mirror
pair are not in sync, it still tries to compare each file. Most of the times
this comparison will fail, it goes for retry where will wait for checkpoint to
get streamed for 1 minute. This will happen for every file which differs causing
extremely long delay in reporting the failure.

Fail fast in replica check if primary and mirror disconnected.

---

gpdb-doc/dita/admin_guide/highavail/highavail.ditamap
gpdb-doc/dita/admin_guide/highavail/topics/g-overview-of-high-availability-in-greenplum-database.xml
gpdb-doc/dita/admin_guide/highavail/topics/g-overview-of-master-mirroring.xml
gpdb-doc/dita/admin_guide/highavail/topics/g-overview-of-segment-mirroring.xml
gpdb-doc/dita/admin_guide/intro/about_ha.xml
gpdb-doc/dita/ref_guide/ref_guide.ditamap
gpdb-doc/dita/ref_guide/system_catalogs/catalog_ref-tables.xml
gpdb-doc/dita/ref_guide/system_catalogs/gp_segment_configuration.xml
gpdb-doc/dita/ref_guide/system_catalogs/gp_stat_replication.xml

Overview of changes:
--replace filerep information with WALrep information in overview topics
--edit overview topics
--update gp_segment_configuration catalog table
--add gp_stat_replication catalog table
NOTE: This PR is only for the overview topics. Other PRs will be opened for the
procedural topics in the Admin Guide.
Link to HTML format of updated topics on the GPDB Docs Review site.
Admin Guide GPDB Overview topic
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/intro/about_ha.html
Admin Guide HA Topics
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/highavail/topics/g-overview-of-high-availability-in-greenplum-database.html
http://docs-gpdb-review-staging.cfapps.io/review/admin_guide/highavail/topics/g-overview-of-master-mirroring.html …

docs - update to HA overview topics for WAL rep

---

gpMgmt/bin/gppylib/operations/unix.py

The `CleanSharedMem.execute()` routine throws an exception if it cannot cleanup
shared memory.  However, there is a race condition between stopping the segments
and explicitly cleaning the shared memory.
This can happen when `CleanSharedMem.execute()` is able to read the
postmaster.pid file and find the shared memory to free, but the shared memory
has already been freed from previously stopping the segments with
`GpMirrorListToBuild.__ensurestopped()`.
Therefore, we are not throwing an exception in `CleanSharedMem.execute()` when 
there is an error in cleaning up the shared memory when the shared memory does 
not exist as it is most likely already freed from stopping the segments.
Co-authored-by: Shoaib Lari <slari@pivotal.io>
Co-authored-by: Kalen Krempely <kkrempely@pivotal.io>

gprecoverseg: Do not throw exception in  `CleanSharedMem.execute()`.

---

concourse/pipelines/README.md
concourse/pipelines/gen_pipeline.py

There is a new concourse yaml file for setting dev pipelines for
gpdb_master and gpdb_master_without_asserts.

ci: Update gen_pipeline output for setting dev pipeline

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/indexjoin_optimizer.out

Corresponding ORCA PR : https://github.com/greenplum-db/gporca/pull/409

Update plans for ORCA change "Remove Broadcast for Inner Nested Loop Join"

---

src/backend/cdb/dispatcher/cdbdisp_query.c

Query string is dispatched with each sub command, when the query string
and the count of sub commands are both large it is a huge effort to
dispatch it repeatedly.  One simple example is as below:
create table t (c1 int, c2 int)
/* comment */
/* ... */
/* comment */
partition by range(c2) (start(0) end(1000) every(1));
This SQL contains 2001 sub commands, if we put 10MB comments into it
then it is 10MB*2001 = 20GB data to dispatch, that will impact the
performance a log.  There can also be real world example:
create table t (c1 int, c2 int, ..., c100 int)
with (appendonly=true, compresslevel=5, orientation=column, compresstype=zlib)
partition by range(c2) (
start(0) end(1) every(1) with (tablename='p1', appendonly=true, compresslevel=5, orientation=column, compresstype=zlib)
column c1 …

5X: Dispatch truncated query strings

---

src/backend/optimizer/plan/createplan.c
src/test/isolation2/expected/update_hash_col_utilitymode.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/update_hash_col_utilitymode.sql

This commit fix Github Issue https://github.com/greenplum-db/gpdb/issues/5976.
Co-authored-by: Zhenghua Lyu <zlv@pivotal.io>
Co-authored-by: Shujie Zhang <shzhang@pivotal.io>

Throw an error when updating hash columns on utility mode.

---

src/backend/parser/parse_relation.c

Fix github issue: https://github.com/greenplum-db/gpdb/issues/5915

Fix bad error message for FOR UPDATE on non-existent table

---

src/bin/pg_dump/pg_dump.c

We were doing a linear search through the list of tables to find the correct OID. That's what `findTableByOid()` is for -- it does a binary search on the sorted list of tables -- so use it instead.
I don't expect this to speed things up much, but it seemed like a good improvement over what we had, and it has the nice side effect of loudly complaining if the parent doesn't actually exist.

pg_dump: improve big-O of partition dependency generation

---

src/backend/access/transam/distributedlog.c
src/backend/access/transam/test/distributedlog_test.c

During binary upgrade for segments, the distributed transaction log that we're using at startup has just been copied as-is from the master data directory. This distributed log isn't actually maintained by the master, so it may not have all the pages that we need. This leads to a stacktrace on startup:
Could not read from file "pg_distributedlog/[file]" at offset [num]
Since no distributed transactions exist during upgrade (there's no cluster to distribute to), and the distributed log is going to be blown away and replaced with the old segment's copy later during the upgrade, let's just make sure it is initialized to all zeroes for the pages between `oldestActiveXid` and `nextXid`.
The unit tests here just verify that we're calling `SimpleLruZeroPage` for the right pages, including XID …

Zero out distributed xlogs during segment upgrade

---

contrib/pg_upgrade/relfilenode.c

Segment files for AO relations aren't necessarily contiguous. Utilize the same logic as aomd.c to find and copy each AO segment individually. Pull the body of the `transfer_relfile()` main loop into a helper function, `transfer_relfile_segment()`, to minimize duplication.
There are several potential optimizations that could be made here -- we don't need to search through all 127 options for concurrency level, and we don't need to look for "columns" greater than zero on a row-oriented table.

pg_upgrade: correctly copy AO[CO] relfile segments

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_joins.out
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/sql/bfv_joins.sql

Any other suggests for tests are very welcome.
Related ORCA PR: https://github.com/greenplum-db/gporca/pull/414

Add tests for ORCA commmit "Remove broadcasts for Inner NLJ with INDF join predicates"

---

src/bin/pg_dump/pg_dump.c

The query on the `pg_partitions` view to find external partitions is expensive and currently runs for every partitioned table. Optimization of the view itself has proven tricky -- many corner cases need to be evaluated -- but it seems pointless to run the query if we know we don't have any external partitions to begin with. This is especially true for pg_upgrade, which currently disallows external partitions entirely.
Add a (much faster) preliminary query on `pg_partition[_rule]` to see if the current table has any external partitions, and if not, skip the expensive query entirely.
An unscientific performance comparison: before, it took roughly four minutes to dump the ICW cluster schema on CI hardware; now it takes less than a minute and a half.

pg_dump: try to omit expensive external partition queries

---

gpAux/Makefile
gpAux/releng/set_bld_arch.sh

- BLD_ARCH for ubuntu is ubuntu1604_amd64

Makefile: Add `ubuntu` to supported BLD_ARCH

---

src/backend/executor/execQual.c

Fix compiler warnings which be introduced by f4f4bdcc8b7327faccbda8e12721b2c6b943aed7.

Fix compiler warnings

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-fallback.xml
src/test/regress/expected/aggregates_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/qp_orca_fallback_optimizer.out
src/test/regress/output/qp_gist_indexes2_optimizer.source

Corresponding to PR: https://github.com/greenplum-db/gporca/pull/415

Update message logged for not supported features by ORCA

---

gpdb-doc/dita/admin_guide/ddl/ddl-partition.xml
gpdb-doc/dita/admin_guide/ddl/ddl-storage.xml
gpdb-doc/dita/admin_guide/ddl/ddl-table.xml

Changes in Admin guide for the addition of the replicated table distribution policy.

Update Admin Guide ddl sections for replicated tables

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/sql/arrays.sql

Corresponding to ORCA https://github.com/greenplum-db/gporca/pull/420.
Refer to the ORCA PR for details  if required.

Bump Orca to v3.5.0 and Remove fix-me

---

contrib/pg_upgrade/test_gpdb_pre.sql

We will await the push of https://github.com/greenplum-db/gpdb/pull/6047 before submitting this PR.

pg_upgrade: enable isolation2test inclusion

---

src/backend/cdb/motion/ic_tcp.c

When registering TCP interconnect, it always assume sendSlice has a full size
of primary processes, but Commit 576690f2ae break this rule, now a send slice
may only consist of 2 out of 3 segments, so using list_nth(xxx, src_contentid)
to get primary process is not correct now. This commit fixes this defect.

Fix TCP interconnect registering issue

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/pg_lsn_optimizer.out

Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/421
This PR Bumps the Orca version and updates test cases.

Fix greedy bestjoin

---

contrib/pg_upgrade/.gitignore

This doesn't need to be checked in.

pg_upgrade: .gitignore symlinked source file

---

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
gpdb-doc/dita/ref_guide/gp_toolkit.xml

docs - add information about nested cgroups

---

gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

include missing refpages, update name

docs - update refs to kafka connector; add missing ref page

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/join_optimizer.out
src/test/regress/sql/gporca.sql

Corresponding to ORCA PR: greenplum-db/gporca#422
Co-authored-by: Sambitesh Dash <sdash@pivotal.io>

Bump ORCA v3.9.0 and update test cases

---

src/backend/optimizer/path/indxpath.c

As far as I can tell, GPDB works the same as PostgreSQL with regards to
path keys used for append rels, so I don't see why we'd need to do any
transformation here. I tried commenting out that call, and the regression
tests passed on my laptop.
This code has been moved around as part of the 9.2 merge, and some other
cleanup, but goes all the way back to 2007 in the old pre-open sourcing
repository. The commit that introduced was a massive commit with message
"Merge of Release-3_1_0_0-alpha1-branch branch down to HEAD", so I lost the
trace of its origin there. I guess it was needed back then, but seems
unnecessary now.

Remove unnecessary GPDB code to transform PathKeys of index paths.

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE.xml

Related to code change in [PR 5902](https://github.com/greenplum-db/gpdb/pull/5902).

Update gp_create_table_random_default_distribution to describe 6.x rules

---

gpdb-doc/book/master_middleman/source/subnavs/pxf-subnav.erb
gpdb-doc/markdown/pxf/client_instcfg.html.md.erb
gpdb-doc/markdown/pxf/pxf_kerbhdfs.html.md.erb
gpdb-doc/markdown/pxf/sdk/deploy_conn.html.md.erb

no technical changes in this PR:
- fix incorrect references to pxf topic
- fix subnav
- add Optional to topic title

docs - misc pxf content and book edits

---

doc/src/sgml/ref/alter_table.sgml
doc/src/sgml/ref/create_table.sgml

This affects the syntax summary printed by psql \h command.

Fix a few places in docs where DISTRIBUTED REPLICATED was missing.

---

src/backend/access/transam/xlog.c

When recovery_target_timeline setting is set in recovery.conf, we expect the
recoveryTargetTLI variable to change (e.g. when set to 'latest', it will read
the primary's history file to get latest TLI). This logic seems to have been
removed from the bottom of readRecoveryCommandFile() when WAL replication was
backported for master/standby replication.
Co-authored-by: Paul Guo <pguo@pivotal.io>
This is mainly just restoring upstream Postgres code that was removed.

Fix support of recovery_target_timeline recovery.conf setting

---

src/backend/cdb/cdbvars.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/include/cdb/cdbvars.h
src/include/nodes/plannerconfig.h

Commit 6dd2759a does a nice clean on SingleQE's segid but
forgot to remove this global variable. Remove it here.

Remove unused variable: gp_singleton_segindex

---

gpdb-doc/dita/ref_guide/sql_commands/COPY.xml

docs - fix SEGEMENT typo on COPY ref page

---

gpdb-doc/dita/install_guide/init_gpdb.xml

docs - update GPDB port information to recommended ports.

---

src/backend/utils/adt/dbsize.c
src/test/regress/expected/db_size_functions.out
src/test/regress/greenplum_schedule
src/test/regress/sql/db_size_functions.sql

And related fixes, see commit messages.

Fix pg_relation_size() for non-main forks.

---

gpdb-doc/dita/ref_guide/extensions/pl_sql.xml

in this PR:
- no technical changes
- updated postgresql links from 8.3 to 9.4
- not sure how we decided what content from postgres pl/pgsql docs to include on this greenplum page.  in any case, compared existing greenplum content with postgres 9.4 content - resulted in some doc updates
- misc edits

docs - pl/pgsql doc updates

---

gpdb-doc/dita/admin_guide/external/g-external-tables.xml
gpdb-doc/dita/admin_guide/external/g-file-protocol.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_PROTOCOL.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_ROLE.xml
gpdb-doc/dita/ref_guide/sql_commands/GRANT.xml

"protocols". How to set permissions on each type.
This is counterpart to PR 6114 in master branch.

docs - note differences between file/gpfdist and gphdfs/s3/pxf

---

contrib/pg_upgrade/test_gpdb.sh

This should make refactoring into functions easier and help readability.

Wraps main work for pg_upgrade test_gpdb.sh inside of a main function.

---

gpdb-doc/dita/utility_guide/admin_utilities/gprecoverseg.xml

Information from support.
This will be backported to 5X_STABLE.

docs - add information about gprecoverseg full recovery.

---

concourse/pipelines/pr_pipeline.yml

Replace deprecated Concourse PR resource

---

src/backend/commands/vacuum.c
src/backend/commands/vacuumlazy.c

Commit cc2e211f42 attempted silencing the assertion in
vac_update_relstats(), but at the place where the check for zero pages and
non-zero tuples combination, is also reached in QD mode. I put an
assertion there, that we only get there in utility mode, but we do
actually run vacuum_appendonly_fill_stats() in QD mode, too. I'm not sure
why we look at the totals in QD mode - AFAICS we just throw away them away
- but I'm reluctant to start restructuring this code right now. So move
the code to zap reltuples to 0, into vac_update_relstats().

Another attempt at fixing Assertion on empty AO tables.

---

gpcontrib/gpcloud/src/gpcloud.cpp
src/backend/cdb/cdbmutate.c
src/backend/gpopt/gpdbwrappers.cpp
src/backend/optimizer/plan/planshare.c
src/include/cdb/cdbmutate.h
src/include/gpopt/gpdbwrappers.h

Collection of misc cleanups I've accumulated over the last few weeks, that would be nice to fix, but have felt too small to bother with individually.

Remove unused functions and includes

---

gpcontrib/gpcloud/include/s3log.h
gpcontrib/gpcloud/src/decompress_reader.cpp
gpcontrib/gpcloud/src/gpreader.cpp
gpcontrib/gpcloud/src/s3key_writer.cpp
gpcontrib/gpcloud/src/s3log.cpp

Silence a few gpcloud compiler warnings.

---

src/backend/access/transam/xlog.c

Code fails to compile if WAL_DEBUG is enabled, as rm_desc is called with 3
arguments (as upstream) instead of 2 arguments in gpdb. Fixing the same by
copying header and then rmgr specific data and then passing the same to
`rm_desc()`. This logging is very helpful debugging tool for xlog related
issues.
I wished to make `rm_desc()` function take 3 arguments as upstream but functions
like btree and checkpoint desc routines depend on data from record header
currently and hence can't get away from passing just rmgr data to desc
routines. This can be revisited anyways with 9.5 merge.
Also, modified xlog INSERT message to match REDO message style. It's very
confusing to read INSERT @ where it actually displays end location and not
really start @.

Fix compilation with WAL_DEBUG.

---

gpdb-doc/dita/utility_guide/admin_utilities/gpcopy.xml

docs - gpcopy add  --parallelize-leaf-partitions option

---

gpdb-doc/dita/ref_guide/extensions/madlib.xml

docs - remove MADlib 1.11 note

---

src/backend/postmaster/postmaster.c

Backport of commit 47fec424cbc9ea281d5bc4649ccedcba3e1116cf from upstream. We'll get there anyway as part of the `REL9_4_STABLE` merge, but this race has been injecting random 10-second delays into cluster startup for a while now. Let's fix it.
On my machine, the timeline is roughly as follows:
- `gpstart` launches the cluster and waits for a `COMMIT` (which requires sync'd replication)
- the primary and mirror begin to come up
- mirror's startup process asks the WAL receiver to start, and eventually ends up waiting in `WaitForWALToBecomeAvailable()` on the `XLogCtl->recoveryWakeupLatch`
- postmaster sees the request and forks off a new WAL receiver, setting `WalReceiverPID`
- the new WAL receiver tries to connect to the primary, but it's told `FATAL:  the database system is starting up` …

Fix random 10-second delay during cluster startup

---

src/backend/cdb/cdbmutate.c
src/backend/executor/nodeResult.c
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/optimizer/plan/createplan.c
src/include/cdb/cdbmutate.h
src/include/gpopt/gpdbwrappers.h
src/include/nodes/execnodes.h
src/include/nodes/plannodes.h
src/test/regress/expected/rangefuncs_cdb.out
src/test/regress/sql/rangefuncs_cdb.sql

See commit messages.
I had made some of these changes as part of PR #6327, but that PR is large enough anyway, so it seems better to handle these separately.

Refactoring Result node's hash filter code.

---

gpdb-doc/dita/admin_guide/managing/configure.xml

in this PR:
- remove a reference to remove gp_enable_sequential_window_plans guc
- for some reason, several of the gucs had a space in their names.  removed the space.

docs - remove gp_enable_sequential_window_plans ref, edits

---

gpdb-doc/dita/admin_guide/ddl/ddl-index.xml
gpdb-doc/dita/admin_guide/query/topics/json-data.xml
gpdb-doc/dita/ref_guide/data_types.xml
gpdb-doc/dita/ref_guide/function-summary.xml
gpdb-doc/dita/ref_guide/ref_guide.ditamap
gpdb-doc/dita/ref_guide/system_catalogs/pg_amop.xml
gpdb-doc/dita/ref_guide/system_catalogs/pg_opfamily.xml

Summary of updates
update Admin. Guide JSON topic
Add jsonb data type to GPDB data types -- NEED INFO ON jsonb data type
update index -- add index on expressions
update/add catalog tables
pg_amop
pg_opfamily
Link to HTML docs on temp. GPDB6 review site 
**Updates for JSON**
https://docs-msk-gpdb6-dev.cfapps.io/600/admin_guide/query/topics/json-data.html
**Updates to list of functions and data types - need info on jsonb data type**
https://docs-msk-gpdb6-dev.cfapps.io/600/ref_guide/function-summary.html
https://docs-msk-gpdb6-dev.cfapps.io/600/ref_guide/data_types.html
**Update to index - index on expressions**
https://docs-msk-gpdb6-dev.cfapps.io/600/admin_guide/ddl/ddl-index.html#topic96
**Updates to catalog tables**
https://docs-msk-gpdb6-dev.cfapps.io/600/ref_guide/system_catalogs/pg_am …

docs - updates for jsonb type

---

src/backend/commands/tablecmds.c
src/test/regress/input/query_info_hook_test.source
src/test/regress/output/query_info_hook_test.source

Add hook point for `alter table set distributed by`

---

gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap
gpdb-doc/markdown/pxf/about_pxf_dir.html.md.erb
gpdb-doc/markdown/pxf/cfginitstart_pxf.html.md.erb
gpdb-doc/markdown/pxf/client_instcfg.html.md.erb
gpdb-doc/markdown/pxf/hbase_pxf.html.md.erb
gpdb-doc/markdown/pxf/hdfs_read_pxf.html.md.erb
gpdb-doc/markdown/pxf/hdfs_write_pxf.html.md.erb
gpdb-doc/markdown/pxf/hive_pxf.html.md.erb
gpdb-doc/markdown/pxf/install_java.html.md.erb
gpdb-doc/markdown/pxf/instcfg_pxf.html.md.erb
gpdb-doc/markdown/pxf/jdbc_pxf.html.md.erb
gpdb-doc/markdown/pxf/overview_pxf.html.md.erb
gpdb-doc/markdown/pxf/pxf_kerbhdfs.html.md.erb
gpdb-doc/markdown/pxf/pxfuserimpers.html.md.erb
gpdb-doc/markdown/pxf/ref/pxf-cluster.html.md.erb
gpdb-doc/markdown/pxf/ref/pxf-ref.html.md.erb
gpdb-doc/markdown/pxf/ref/pxf.html.md.erb
gpdb-doc/markdown/pxf/sdk/build_conn.html.md.erb
gpdb-doc/markdown/pxf/sdk/deploy_conn.html.md.erb
gpdb-doc/markdown/pxf/sdk/deploy_profile.html.md.erb
gpdb-doc/markdown/pxf/sdk/dev_concepts.html.md.erb
gpdb-doc/markdown/pxf/troubleshooting_pxf.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb
gpdb-doc/markdown/pxf/using_pxf.html.md.erb

backport PXF config and command line interface changes to 5X_STABLE.

docs - backport pxf config and cli changes to 5X_STABLE

---

src/backend/access/external/fileam.c
src/backend/cdb/cdbcopy.c
src/backend/cdb/cdbsreh.c
src/backend/cdb/dispatcher/cdbdispatchresult.c
src/backend/commands/copy.c
src/backend/executor/execUtils.c
src/include/cdb/cdbcopy.h
src/include/cdb/cdbdispatchresult.h
src/include/cdb/cdbsreh.h
src/include/commands/copy.h

COPY code cleanup

---

src/backend/cdb/cdbpartition.c
src/backend/nodes/readfuncs.c
src/backend/tcop/postgres.c
src/include/cdb/cdbdisp_dtx.h

Collection of little things I've spotted while working on other stuff. See commit messages.

Misc code cleanup

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave_utils/cluster_expand.py

- Add a fault inject to test rollback process
- Remove pg_hba.conf updating during online expand, for only master
will connect to segment via libpq, master's ip has already been
in pg_hba.conf

Add gpexpand rollback test case

---

src/backend/commands/copy.c

This code is performance-critical, as the QD will quickly become the
bottleneck when loading data with COPY FROM. Optimizing it is therefore
warranted.
I did some quick testing on my laptop, loading a table with 50 boolean
columns. This commit improved the performance of that by about 10%.
In GPDB 5, we used to postpone calling the input functions for columns
that were not needed to determine which segment to send the row to. We
lost that optimization during the 9.1 merge, when the COPY code was
heavily refactored. We now call the input functions for every column in
the QD, which added a lot of overhead to the QD. On the other hand, some
other things got faster. Before this commit, the test case with 50
booleans was about 10% slower in GPDB 6, compared to GPDB 5, so this buys
back the …

Optimize the code to send data rows from QD to QEs in COPY FROM.

---

src/backend/cdb/motion/ic_common.c
src/backend/cdb/motion/ic_tcp.c
src/backend/cdb/motion/ic_udpifc.c

I'm not sure if anyone cares about it, but this at least makes it compile
again.

Fix compilation with AMS_VERBOSE_LOGGING.

---

src/backend/access/transam/xact.c
src/backend/executor/nodeIndexscan.c
src/backend/optimizer/plan/transform.c
src/backend/utils/gdd/gddfuncs.c
src/test/regress/expected/insert.out
src/test/regress/expected/rowtypes.out
src/test/regress/sql/insert.sql
src/test/regress/sql/rowtypes.sql

Resolve a few misc merge FIXMEs.

---

gpdb-doc/dita/admin_guide/managing/plugin_api/plugin_api_version.xml

docs - change gpbackup API version to current version 0.3.0

---

src/test/regress/input/tablespace.source
src/test/regress/output/tablespace.source

Add analyze in test tablespace to avoid orca notice

---

gpdb-doc/dita/ref_guide/sql_commands/ALTER_DATABASE.xml
gpdb-doc/dita/ref_guide/sql_commands/ALTER_SERVER.xml
gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
gpdb-doc/dita/ref_guide/sql_commands/ALTER_USER_MAPPING.xml
gpdb-doc/dita/ref_guide/sql_commands/CLUSTER.xml
gpdb-doc/dita/ref_guide/sql_commands/COPY.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_DATABASE.xml
gpdb-doc/dita/utility_guide/client_utilities/clusterdb.xml

Covers changes to:
ALTER DATABASE
ALTER SERVER
ALTER TABLE
ALTER USER MAPPING
CLUSTER
CLUSTERDB
COPY
CREATE DATABASE

Docs: 8.4 merge updates for Reference Pages

---

src/backend/commands/analyze.c

The previous algorithm to merge the HLL counters for leaf partitions had a time
complexity of O(n^2) where n is the number of leaf partitions. In case where
the number of partitions was high, resulting in poor performance of analyze on
partitioned tables.  This patch fixes the performance issue by using a new
algorithm to merge the leaf HLL counters in O(n) time.
Co-authored-by: Omer Arap <oarap@pivotal.io>
Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>

Improve performance of `merge_leaf_stats()`

---

src/backend/optimizer/util/predtest.c
src/backend/optimizer/util/predtest_valueset.c
src/include/optimizer/predtest.h
src/test/regress/expected/bfv_dd.out
src/test/regress/expected/bfv_dd_multicolumn.out
src/test/regress/expected/direct_dispatch.out
src/test/regress/expected/direct_dispatch_optimizer.out
src/test/regress/sql/direct_dispatch.sql

Perhaps not super interesting, but it's straightforward to implement, and
ORCA was already doing it.

Implement direct dispatch for IS NULL.

---

src/backend/catalog/heap.c
src/backend/commands/resgroupcmds.c
src/backend/utils/resgroup/resgroup-ops-linux.c
src/include/access/url.h

Silence compiler warnings.

---

gpdb-doc/dita/admin_guide/load/topics/g-using-a-custom-protocol.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_PROTOCOL.xml
gpdb-doc/dita/ref_guide/sql_commands/DROP_PROTOCOL.xml

online doc changes for https://github.com/greenplum-db/gpdb/pull/6507

docs - must be a superuser to create a protocol

---

src/backend/access/transam/xact.c
src/test/regress/expected/gpdtm_plpgsql.out
src/test/regress/sql/gpdtm_plpgsql.sql

Fix quoting when dispatching SAVEPOINT commands.

---

gpMgmt/bin/README.gpexpand.md

Update a detailed README for online expand.
- ~[] Add tests for the change~ (No need)
- ~[] Document changes~(Doc changes will be done by other PR and jobs)
- ~[] Communicate in the mailing list if needed~
- ~[] Pass `make installcheck`~

Update gpexpand readme.

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to 3.18.0

---

src/backend/optimizer/plan/createplan.c

If best_path->materialize_inner, best_path->jpath.outerjoinpath->motionHazard and best_path->jpath.innerjoinpath->motionHazard are all true this can happen.
See the plan example below (without this patch).
```
regression=# explain
select a.idv, b.idv from tidv a, tidv b where a.idv = b.idv;
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------
Merge Join  (cost=10000000000.33..10000085645.93 rows=2787840 width=64)
Merge Cond: (a.idv = b.idv)
->  Gather Motion 3:1  (slice1; segments: 3)  (cost=0.17..21848.17 rows=52800 width=32)
Merge Key: a.idv
->  Index Only Scan using tidv_idv_idx on tidv a  (cost=0.17..20792.17 rows=17600 width=32)
->  Materialize  (cost=0.00..0.00 rows=0 width=0)
->  Materialize  (cost=0.00..0.00 …
```

Avoid possible duplicated materialize node in merge join plan

---

src/backend/cdb/cdbgroup.c

The only place where it was read was in setting the number of segments,
when marking the resulting plan as "strewn". We can use the 'input_locus'
directly for that, because that's where the numsegments value for the
'output_locus' came from in every case.
(This is extracted from PR #6327. Might as well commit this separately, to make that big PR a little bit smaller.)

Remove unused 'output_locus' fields in cdbgroup.c.

---

src/backend/cdb/cdbhash.c
src/backend/cdb/cdbpath.c
src/backend/optimizer/plan/createplan.c
src/backend/optimizer/plan/initsplan.c
src/backend/postmaster/pgarch.c
src/backend/storage/buffer/bufmgr.c
src/backend/utils/sort/tuplesort.c
src/include/nodes/relation.h
src/include/utils/tuplesort.h

Remove some code that is no longer used, or that got slightly messed up in the upstream merges. See commit messages for details.

Remove misc unused or unnecessary code

---

src/backend/executor/execTuples.c

This change brings back an optimization to reuse buffer when slot's
`PRIVATE_tts_memtuple` is `NULL` and `PRIVATE_tts_mtup_buf` is not. Here we
pass `inline_toast=false` into `memtuple_form_to()`. Thus previous refactor to
detoast either `MemTuple` or `HeapTuple` in `SendTuple()` is maintained.
Feedback was originally posted here https://github.com/greenplum-db/gpdb/pull/6527#discussion_r243173510.

Revive lost optimization from detoast memtuple refactor

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

see PR https://github.com/greenplum-db/gpdb/pull/6482

docs - new GUC optimizer_enable_agg_skew_avoidance

---

src/backend/optimizer/plan/initsplan.c

Remove unused variable 'maybe_local_equijoin'.

---

src/backend/executor/execDynamicIndexScan.c

Co-authored-by: Hao Wang <haowang@pivotal.io>
Co-authored-by: Wenlin Zhang <wzhang@pivotal.io>

Fix misuse pointer of pointer in IndexScan_OpenIndexRelation

---

src/backend/utils/cache/syncrefhashtable.c

see commit message for details.

Fixes a potential LWLOCK bug

---

src/backend/executor/nodeHashjoin.c
src/include/nodes/nodes.h

fix typo and indent

---

README.docker.md

- Include how to make Greenplum within docker accessible to SQL editors
running on the local machine (outside of docker).
- Update the pip install command so that psutil and lockfile are
accessible when the make cluster command is executed.

Update instructions in README.docker.md

---

src/backend/cdb/motion/ic_tcp.c

In the TCP interconnect, we used to bind outgoing TCP connections to the
same source IP address that the libpq connection came from. That can lead
to running out of ephemeral TCP ports. I was seeing errors, when running
the regression tests with the TCP interconnect:
ERROR:  interconnect error setting up outgoing connection
DETAIL:  Could not bind to local addr 2.0.0.0: Address already in use
This was easily reproducible, by running the parallel group of tests that
includes the qp_misc_jiras test. Apparantly that parallel group opens
especially many connections.
When a socket is bound to a particular IP address with bind(), it is also
allocated an ephemeral TCP port. On Linux, the range of ports available
can be seen in /proc/sys/net/ipv4/ip_local_port_range. It defaults to
32768-60999, …

Don't bind outgoing TCP connections to a particular IP address.

---

.travis.yml
concourse/pipelines/templates/gpdb-tpl.yml
concourse/scripts/builds/GpBuild.py
concourse/scripts/common.bash
concourse/scripts/compile_gpdb.bash
concourse/scripts/compile_gpdb_open_source_centos.bash
concourse/scripts/compile_gpdb_open_source_ubuntu.bash
concourse/scripts/deb_create_package.bash
concourse/scripts/gpMgmt_check_gpdb.bash
concourse/scripts/gpcheckcloud_tests_gpcloud.bash
concourse/scripts/ic_gpdb.bash
concourse/scripts/ic_gpdb_resgroup.bash
concourse/scripts/ic_gpdb_sles12.bash
concourse/scripts/ic_gpdb_ubuntu.bash
concourse/scripts/regression_tests_gphdfs.bash
concourse/scripts/test_gpdb.py
configure
configure.in
gpAux/Makefile
gpcontrib/zstd/expected/compression_zstd.out
gpcontrib/zstd/sql/compression_zstd.sql
src/backend/access/common/reloptions_gp.c
src/include/pg_config.h.in

Enable zstd by default

---

src/backend/access/appendonly/appendonlyam.c
src/backend/access/appendonly/appendonlywriter.c
src/backend/cdb/cdbappendonlystorageformat.c
src/backend/cdb/cdbappendonlystorageread.c
src/backend/cdb/cdbappendonlystoragewrite.c
src/backend/cdb/cdbbufferedread.c
src/backend/commands/vacuum.c
src/backend/storage/smgr/smgr.c
src/backend/utils/datumstream/datumstream.c
src/include/access/appendonlywriter.h
src/include/cdb/cdbappendonlystorageformat.h
src/include/cdb/cdbappendonlystoragewrite.h
src/include/cdb/cdbbufferedread.h
src/include/storage/smgr.h

Remove unused variable and unused functions when see code related to appendonly table

Remove unused variable and unused functions

---

gpMgmt/bin/gpcheckcat
gpMgmt/bin/gpconfig
gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py

Minor fix. Cases are already there.

Add a mock for gpexpandcheck to fix unittest of gpconfig.

---

src/backend/executor/nodeHash.c

Fix incorrect comments and remove unused code

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_activity.xml

Docs updated from PostgreSQL docs to match \d output.

Docs: Update pg_stat_activity view to match current gpdb 6 build

---

gpMgmt/bin/gpcheckcat
gpMgmt/bin/gppylib/utils.py
src/test/regress/expected/run_utility_gpexpand_phase1.out

Fix output of utility while gpexpand.

---

src/backend/commands/explain_gp.c

The 'nloop' counts showed one too much. Here's how it happened:
1. In the QE processes, cdbexplain_sendExecStats() was called, and
a node's 'running' flag was true. It called InstrEndLoop() on the
node, which bumped up 'nloops' by one, and reset 'running' to false.
2. In the stats that were collected and sent to the QD, 'running'
was recorded as 'true', and for 'nloops', the incremented value.
3. In the QD, the stats were received from the QE, and installed to the
local Instrumentation structs.
4. QD called ExplainNode(), which saw that running=true, because that's the
value that was received from the QE, and it called InstrEndLoop() again.
Fix, by not including the 'running' flag in the Instrumentation information
that is sent from QE to QD. The stats sent reflect the situation after …

Fix off-by-one in EXPLAIN ANALYZE 'nloops' counts.

---

src/bin/pg_basebackup/pg_basebackup.c

This commit addresses a race condition where it was possible that during
xlogstream the pg_xlog directory went missing. The race exists only with
--foceoverwrite and --xlog stream. In stream mode pg_basebackup forks a
process to populate pg_xlog directory with new transaction files and
another process to receive and untar base directory contents. Force
overwrite removes an existing pg_xlog directory before copying contents
from tar file. It is problematic if untar process deletes xlog directory
while stream process tries to write to it.
In order to avoid this situation in forceoverwrite mode, the deletion
of pg_xlog now happens before starting stream and untar processes. This
enables untar process to skip deletion of pg_xlog.
Co-authored-by: Ashwin Agrawal <aagrawal@pivotal.io>

Fix race-condition of pg_xlog delete during pg_basebackup

---

src/tools/docker/centos6/Dockerfile
src/tools/docker/centos7/Dockerfile

Add libzstd-devel to centos docker images

---

src/test/regress/pg_regress.c

Porting the use-existing flag related code from master to 5X_STABLE. It was introduced as part of efc16ea520679d713d98a2c7bf1453c4ff7b91ec, so extracted only the relevant part for pg_regress.
It is a useful flag, and can save time recreating the database objects required for testing queries.

use-existing flag for pg_regress

---

gpdb-doc/dita/ref_guide/feature_summary.xml
gpdb-doc/dita/ref_guide/sql_commands/COMMENT.xml
gpdb-doc/dita/ref_guide/system_catalogs/pg_largeobject.xml
gpdb-doc/dita/utility_guide/client_utilities/pg_dump.xml
gpdb-doc/dita/utility_guide/client_utilities/pg_restore.xml
gpdb-doc/dita/utility_guide/client_utilities/psql.xml

Adding note around current documentation that suggests large object support akin to postgresql.

Add notes to qualify lack of Large Object support.

---

src/backend/optimizer/plan/planner.c

For LockRows node, if its outer plan is dummy then there will be no
row for locking and thus it could be dummy path.
No new test is needed since there have been tests cover that (e.g. updatable_views and with, etc).

Fix FIXME in is_dummy_plan_walker() and also refactor the code a bit.

---

src/backend/storage/file/fd.c

Before this, you would get warnings like this in the log at crash
recovery, for every temporary file that's deleted:
2019-01-28 20:20:45.702848 EET,,,p7513,th-1570674304,,,,0,,,seg1,,,,,"WARNING","01000","could not open directory ""base/pgsql_tmp/pgsql_tmpslice1_tuplestore5876.0"": No such file or directory",,,,,,,,"pgfnames","pgfnames.c",43,
To fix, backport changes PostgreSQL v11, which added the support for
removing temporary directories in upstream. That is, commit dc6c4c9dc2,
and the follow up commits 561885db0 and eeb3c2df42.

Don't print WARNING for every temporary file being deleted at recovery.

---

gpdb-doc/dita/admin_guide/managing/gptransfer.xml
gpdb-doc/dita/admin_guide/managing/migrating-data.xml
gpdb-doc/dita/best_practices/summary.xml
gpdb-doc/dita/security-guide/topics/ports_and_protocols.xml
gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml
gpdb-doc/dita/utility_guide/dblink.xml

PR for removing gptransfer from docs https://github.com/greenplum-db/gpdb/pull/6821

docs - deprecate gptransfer. Removed in GPDB 6

---

configure
configure.in

Improving this error message was suggested in Issue https://github.com/greenplum-db/gpdb/issues/6700

Update missing zstd error message in configure

---

gpdb-doc/dita/admin_guide/external/pxf-overview.xml
gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/markdown/pxf/access_objstore.html.md.erb
gpdb-doc/markdown/pxf/install_java.html.md.erb
gpdb-doc/markdown/pxf/intro_pxf.html.md.erb
gpdb-doc/markdown/pxf/objstore_cfg.html.md.erb

docs - misc pxf edits

---

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature

When a primary segment crashes, there is a possibility of the
postmaster.pid being left behind. If another process starts actively
using that pid, pg_rewind will failed when it tries to start the
failed segment in single-user mode (crash recovery to ensure clean
shutdown). It should be safe to remove the file before pg_rewind
during gprecoverseg since gprecoverseg ensures all failed segments are
shut down (pg_ctl stop or via forceful termination).
Also, revert some gprecoverseg full calls in gprecoverseg.feature
Behave test to be back to gprecoverseg incremental. They were marked
with WALREP_FIXME last year waiting for pg_rewind which we now have.
Co-authored-by: Jimmy Yih <jyih@pivotal.io>

Remove postmaster.pid before running pg_rewind in gprecoverseg

---

concourse/pipelines/pipeline_coverity.yml
concourse/scripts/scan_with_coverity.bash
concourse/tasks/scan_with_coverity.yml

concourse: Install QuickLZ

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_database.xml

software change made in this PR.
https://github.com/greenplum-db/gpdb/pull/6811

docs - remove hashmethod from pg_database

---

src/tools/docker/centos6/Dockerfile
src/tools/docker/centos7/Dockerfile

This is to customize the output format when running time utility on a bash command.

Add GNU Time to centos images

---

src/backend/access/common/reloptions_gp.c

Commit 46b21685f7 added a similar check for Zstandard. This makes QuickLZ
behave the same.
Fixes https://github.com/greenplum-db/gpdb/issues/5107

Don't allow CREATE TABLE with quicklz, if server is built without quicklz.

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/join_gp.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/sql/join_gp.sql

ORCA PR: https://github.com/greenplum-db/gporca/pull/444
More testing ideas welcome!

Tests for ORCA commit 'Fix wrong results from LOJ reordering'

---

gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py

Grab the backend_start value of pg_basebackup (executed from
gprecoverseg) from pg_stat_replication and display it for the user
during gpstate -s. It's not a time estimation but it's good to see.
Screenshot example:

Display backup start time in gpstate -s

---

gpMgmt/bin/gppylib/programs/clsAddMirrors.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/addmirrors_mgmt_utils.py

We added a test to the gpaddmirrors behave file.
Also we made gpaddmirrors start respecting the non-interactive flag for non-standard clusters.

Add gpaddmirrors test

---

gpdb-doc/dita/admin_guide/admin_guide.ditamap
gpdb-doc/dita/admin_guide/managing/compression.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

-Add a topic that lists features that support configuring compression.
-update gp_workfile_compression GUC. Remove requirement to install zstd.

docs - update compression information

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpstate.py

This commit checks whether there are any active pg_rewind connections when the mirror is down and displays an appropriate status message if so.  To facilitate this, the pg_rewind call in gprecoverseg has been modified to specify its application_name when connecting to the database.

gpstate: add "Rewinding" status for primary during incremental recovery

---

src/backend/cdb/cdbgroup.c
src/backend/optimizer/path/pathkeys.c

Set correct nullable_relids for  get_eclass_for_sort_expr.

---

src/backend/optimizer/util/pathnode.c
src/test/regress/expected/rangefuncs.out
src/test/regress/expected/rangefuncs_optimizer.out
src/test/regress/sql/rangefuncs.sql

Also refactor subquery_motionHazard_walker() to make it simpler.

Fix subquery_motionHazard_walker() to accomodate more plan node types.

---

contrib/pg_upgrade/test_gpdb.sh

We tweak the existing 6-6 upgrade test test_gpdb.sh to work
on a 5-6 upgrade.  This allows anyone to upgrade a 5 demo
cluster, with various user data, to a 6 demo cluster.
Co-authored-by: Jesse Zhang <jzhang@pivotal.io>

5-6 upgrade: change local test test_gpdb.sh to work for 5-6

---

PULL_REQUEST_TEMPLATE.md

Add a reminder for mutual review offset obligations. Ideally we are
expected to review at least one other PR when submitting our own PR.

Review a PR when create a PR

---

contrib/pg_upgrade/check_gp.c

We improve the check in pg_upgrade for gphdfs in the following ways.
All of these checks are done only when the old cluster version has
support for gphdfs.
1). skip checking for gphdfs tables for cluster versions where gphdfs
support is absent.
2). fail upon a successful check for gphdfs roles
NOTE: we do not special case the existence of the gphdfs.so library,
even in absense of gphdfs tables or roles.  In other words, the existing
library checks force the user to drop all gphdfs-dependent functions
before upgrade.
Co-authored-by: Francisco Guerrero <aguerrero@pivotal.io>
NOTE: in a cluster containing gphdfs, here is what the check looks like; only the only line showing "gphdfs role" has changed.
```
Performing Consistency Checks
-----------------------------
Checking cluster versions …
```

improve pg_upgrade checks for gphdfs in pre-6 clusters

---

src/backend/catalog/oid_dispatch.c

When binary-upgrading the QD node, we must preserve the OIDs of types,
relations from the old cluster, so we should have pre-assigned OIDs for
them.
When binary-upgrading a QE node, we should have pre-assigned OIDs for
all objects, to ensure that the same OIDs are used for all objects
between the QD and the QEs.
That said, in general the new cluster might have a need to create
any type of object.  As we have no effective way of tracking which
objects are newly created in the new cluster (versus binary-upgraded
from the old cluster), we allow the new cluster to create any object
it wants.
This is a companion PR to the Master PR #6990; it enables a GPDB-6 based pg_upgrade to upgrade a 5 cluster. 
Co-authored-by: Jesse Zhang <jzhang@pivotal.io>

allow binary_upgrade mode to create new tuples/relations of any type

---

src/backend/storage/ipc/procarray.c

We should ensure obtaining or releasing an LWLock fast. But the
FillInDistributedSnapshot() is so weight that leading to serious
lock contentions. We move it after releasing the ProcArrayLock
to reduce the lock contentions.
- [  ] Add tests for the change
- [  ] Pass `make installcheck`

5X: Construct distributed snapshot after releasing LWLock

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/include/gpopt/gpdbwrappers.h
src/include/gpopt/translate/CTranslatorUtils.h
src/include/utils/builtins.h

Mcv text cardinality

---

gpMgmt/bin/gpcheckcat
gpMgmt/bin/gpconfig
gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/programs/clsSystemState.py
gpMgmt/bin/gppylib/programs/gppkg.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpcheckcat.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpexpand_status.py
gpMgmt/doc/gpexpand_help
gpMgmt/doc/gpstate_help
gpMgmt/test/behave/mgmt_utils/gpstate.feature
gpMgmt/test/behave_utils/utils.py
src/test/regress/expected/run_utility_gpexpand_phase1.out
src/test/regress/greenplum_schedule
src/test/regress/sql/run_utility_gpexpand_phase1.sql

This is a replacement for https://github.com/greenplum-db/gpdb/pull/6985, per discussions in that PR we decided to provide a python api instead of a C one to check gpexpand status.  This api is currently used by gpstate, gpcheckcat, gppkg and gpconfig.
Also retired the `-D` option in gpexpand to simplify the detection of schema dbname.
The PR is split into several commits by function, hope that could makes the review easier.

python api to check gpexpand status

---

src/backend/access/appendonly/aosegfiles.c

Issue is that we're not guaranteed that SharedSnapshotSlot is not NULL
here. We also need to lock the SharedSnapshotSlot->slotLock before
accessing its variables.

Fix 5X storage test failure

---

gpMgmt/bin/gppylib/operations/package.py
gpMgmt/bin/gppylib/programs/gppkg.py

1. Use fakeroot to install/uninstall deb package in gppkg
2. Throw an exception when installing an existing gppkg/deb package
3. Throw an exception when update a non-existing gppkg/deb package
Co-authored-by: Haozhou Wang <hawang@pivotal.io>

Fixed gppkg/deb package install for ubuntu

---

gpdb-doc/dita/admin_guide/external/g-s3-protocol.xml

doc changes for https://github.com/greenplum-db/gpdb/pull/6867

docs - remove SOCKS proxy support from s3 protocol

---

gpdb-doc/dita/admin_guide/roles_privs.xml
gpdb-doc/dita/best_practices/encryption.xml
gpdb-doc/dita/security-guide/topics/Encryption.xml

in this PR:
- register pgcrypto with "CREATE EXTENSION", not the pgcrypto.sql file
- update xrefs to postgres pgcrypto page to 9.4

docs - register pgcrypto extension, use 9.4 pg xrefs

---

gpdb-doc/dita/admin_guide/dml.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

Updated Admin Guide and and GUC in Ref Guice.

docs - GDD - add information about specific type of deadlocks.

---

gpMgmt/bin/gpexpand
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
src/backend/cdb/cdbcat.c
src/backend/commands/tablecmds.c
src/test/regress/expected/expand_table.out
src/test/regress/expected/expand_table_ao.out
src/test/regress/expected/expand_table_aoco.out
src/test/regress/expected/expand_table_regression.out
src/test/regress/expected/partial_table.out
src/test/regress/greenplum_schedule
src/test/regress/sql/expand_table.sql
src/test/regress/sql/expand_table_ao.sql
src/test/regress/sql/expand_table_aoco.sql
src/test/regress/sql/expand_table_regression.sql
src/test/regress/sql/partial_table.sql

These fixes are cherry picked from the feature branch https://github.com/greenplum-db/gpdb/tree/feature_gpdb6_expand, please refer to each commit for details.

Misc fixes on gpexpand and data redistribution

---

gpdb-doc/dita/admin_guide/managing/backup-plugin-api.xml
gpdb-doc/dita/admin_guide/managing/backup-plugins.xml
gpdb-doc/dita/admin_guide/query/topics/CTE-query.xml
gpdb-doc/dita/admin_guide/wlmgmt.xml
gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/sql_commands/SELECT.xml
gpdb-doc/dita/ref_guide/sql_commands/SELECT_INTO.xml
gpdb-doc/markdown/pxf/hdfs_parquet.html.md.erb
gpdb-doc/markdown/pxf/objstore_parquet.html.md.erb

Experimental->Beta terminology change for 5X_STABLE.

Docs: Experimental->Beta for 5X_STABLE docs

---

src/test/isolation2/expected/oom_mixed_1.out
src/test/isolation2/expected/oom_mixed_1_optimizer.out
src/test/isolation2/expected/oom_mixed_2.out
src/test/isolation2/expected/oom_mixed_2_optimizer.out
src/test/isolation2/init_file_isolation2
src/test/isolation2/sql/oom_mixed_1.sql
src/test/isolation2/sql/oom_mixed_2.sql

ignore some test case to have queck fix on memory accouting test

---

gpdb-doc/dita/admin_guide/ddl/ddl-tablespace.xml

Updating description of temp table / temp file location for different types of query.

Docs: Update location of different temp/spill files

---

gpdb-doc/dita/utility_guide/admin_utilities/gpcheckcat.xml

- Refer to specific gpcheckcat output to fix catalog

docs gpcheckcat toast catalog doc

---

gpdb-doc/dita/admin_guide/load/topics/g-loading-data-with-gpload.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpload.xml

This will be backported to 5X_STABLE as well.

Adding gpload limitation notice for MPP-29682

---

src/backend/cdb/cdbpath.c
src/backend/cdb/cdbsetop.c
src/backend/optimizer/util/pathnode.c

Most of these FIXME were put in the code as reminders for us to revisit
the decision policy on numsegments, during the development we have
verified the policies or fixed the incorrect ones, now we just need to
remove these FIXME or convert them to comments.

Cleanup some numsegments related FIXME

---

src/backend/cdb/motion/ic_udpifc.c
src/backend/executor/execMain.c
src/backend/utils/adt/dbsize.c

Adding WIP since this depends on the related gp6 PR https://github.com/greenplum-db/gpdb/pull/7120 since most of the code change is exactly same as those on gp6.

[5X] Fix the issues which were reported by coverity.

---

concourse/tasks/build_with_orca.yml

Add enable-debug-extensions flag to ORCA pipeline

---

gpMgmt/test/behave_utils/utils.py

Reverts greenplum-db/gpdb#7232
This PR has not fixed the flaky case, we revert it and push another one later.

Revert "Fix gpexpand flaky case"

---

src/backend/postmaster/syslogger.c

Backport of https://github.com/greenplum-db/gpdb/pull/7127 to 5X_STABLE.
The first issue(committed as 14a794e82c878c1f64436069ac5b6c62db99bf30) does not exist on 5X_STABLE, so we did not backport that.

5X_STABLE Backport: logfile_rotate(): correct multiple calls to set_next_rotation_time()

---

gpdb-doc/markdown/pxf/hdfs_parquet.html.md.erb
gpdb-doc/markdown/pxf/objstore_parquet.html.md.erb
gpdb-doc/markdown/pxf/objstore_text.html.md.erb

describe the new parquet write options.  have not yet included them in an example.  also a few misc edits.
question:  do we want to provide any guidance on setting these options?

docs - new pxf parquet write options

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Backport of commit 0ddd60eb05 from master.

Bump ORCA to v3.31.0

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

For ORCA commit "Fix crash when merging group containing CTE consumer"
Authored-by: Chris Hajas <chajas@pivotal.io>

Bump ORCA version to 3.32.0

---

gpMgmt/doc/gprecoverseg_help

fix grammar in message from the mistaken `Do no show` to `Do not show`.

gprecoverseg: improve help message for --no-progress

---

src/bin/gpfdist/regress/input/custom_format.source
src/bin/gpfdist/regress/input/exttab1.source
src/bin/gpfdist/regress/input/gpfdist2.source
src/bin/gpfdist/regress/input/gpfdist_ssl.source
src/bin/gpfdist/regress/output/custom_format.source
src/bin/gpfdist/regress/output/exttab1.source
src/bin/gpfdist/regress/output/gpfdist2.source
src/bin/gpfdist/regress/output/gpfdist_ssl.source
src/test/regress/input/sreh.source
src/test/regress/output/sreh.source

It tried to make sure gpfdist is ready by sleep 3 seconds before
queries, but that could not guarantee. This commit changes the sleep to
a retry until gpfdist is ready.

Make sure gpfdist is ready in test cases

---

gpMgmt/bin/gppylib/test/unit/test_unit_workerpool.py

Despite my best efforts to avoid races on overloaded test containers, `test_join_and_indicate_progress_prints_dots_until_pool_is_done()` has been failing fairly often ([recent example](https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master/jobs/icw_gporca_conan_ubuntu16/builds/29)). Replace the simple-but-flaky time-based test with an implementation that serializes the components of the race.
This is more complex, but it (if I've implemented it correctly) won't fail due to timing changes. Suggestions for making the implementation more readable are very welcome, since there are many more moving parts now.

gppylib: remove race in WorkerPool progress test

---

gpdb-doc/dita/utility_guide/admin_utilities/gprecoverseg.xml

Update synopsis and describe how progress report behaviors

Add -s and --no-progress options to gprecoverseg utility ref

---

gpdb-doc/dita/utility_guide/admin_utilities/util_ref.xml

and remove gpsyncmaster. 
This should be picked to 5X_STABLE and 6X_STABLE.

docs - utility reference - add pg_basebackup

---

gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/mainUtils.py
gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py
gpMgmt/bin/lib/gpconfigurenewsegment
gpMgmt/doc/gprecoverseg_help
gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
src/test/isolation2/expected/fts_dns_error.out
src/test/isolation2/expected/fts_errors.out
src/test/isolation2/expected/segwalrep/mirror_promotion.out
src/test/isolation2/expected/segwalrep/twophase_tolerance_with_mirror_promotion.out
src/test/isolation2/sql/fts_dns_error.sql
src/test/isolation2/sql/fts_errors.sql
src/test/isolation2/sql/segwalrep/mirror_promotion.sql
src/test/isolation2/sql/segwalrep/twophase_tolerance_with_mirror_promotion.sql
src/test/regress/sql/fts_recovery_in_progress.sql
src/test/regress/sql/mirror_replay.sql

This is a backport of PR #7207.
The relevant commits from that PR have been cherry-picked without modification.   Merging this PR is awaiting backport approval.

6_Backport: show gprecoverseg progress

---

gpdb-doc/dita/admin_guide/load/topics/g-loading-data-with-gpload.xml
gpdb-doc/dita/admin_guide/load/topics/transforming-xml-data.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpfdist.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpload.xml

This will be backported to 6X_STABLE, 5X_STABLE

Add warning about gpfdist/gpload major version compatibility

---

gpdb-doc/dita/ref_guide/sql_commands/ALTER_FUNCTION.xml
gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
gpdb-doc/dita/ref_guide/sql_commands/COMMENT.xml
gpdb-doc/dita/ref_guide/sql_commands/COPY.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_AGGREGATE.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FUNCTION.xml
gpdb-doc/dita/ref_guide/sql_commands/DROP_ROLE.xml
gpdb-doc/dita/ref_guide/sql_commands/DROP_USER.xml
gpdb-doc/dita/ref_guide/sql_commands/PREPARE.xml
gpdb-doc/dita/ref_guide/sql_commands/REASSIGN_OWNED.xml
gpdb-doc/dita/ref_guide/sql_commands/REINDEX.xml
gpdb-doc/dita/utility_guide/client_utilities/pg_dump.xml

Updates GPDB 6 DITA docs with changes to sgml files in Postgres 9.4 merge. This is part 2.

Docs postgresql 9.4 merge ga

---

src/backend/executor/execProcnode.c
src/test/regress/input/query_info_hook_test.source
src/test/regress/output/query_info_hook_test.source
src/test/regress/query_info_hook_test/query_info_hook_test.c

master PR is #7188, already merged.

add hook in MultiExecProcNode

---

gpMgmt/bin/gppylib/test/unit/test_unit_workerpool.py

_This is a `6X_STABLE` backport of #7285._
Despite my best efforts to avoid races on overloaded test containers, `test_join_and_indicate_progress_prints_dots_until_pool_is_done()` has been failing fairly often. Replace the simple-but-flaky time-based test with an implementation that serializes the components of the race.
(cherry picked from commit 9f5384bc59aa339c624b6308bd70ca25aba3b6fc)

6X: gppylib: remove race in WorkerPool progress test

---

concourse/scripts/build_gpdb.py
concourse/scripts/builds/GpBuild.py
concourse/scripts/diff_explain_results_with_baseline.bash
concourse/scripts/setup_gpadmin_user.bash
concourse/tasks/diff_explain_results_with_baseline.yml

Add an option in script to allow use of existing database and existing gpadmin user.

ORCA explain test suite pipeline changes

---

gpdb-doc/dita/security-guide/topics/ports_and_protocols.xml

Cherry-pick just the updated example from ea2eecc827

Update gpstate -p example to use gpdb 5.17

---

concourse/pipelines/gen_pipeline.py

Mostly making lines and variable names shorter and more consistent.
Co-authored-by: Oliver Albertini <oalbertini@pivotal.io>
Co-authored-by: Bradford Boyle <bboyle@pivotal.io>

Obey py-linter

---

src/backend/executor/execProcnode.c
src/test/regress/input/query_info_hook_test.source
src/test/regress/output/query_info_hook_test.source
src/test/regress/query_info_hook_test/query_info_hook_test.c

master PR is #7188, already merged.

Add node hook in MultiExecProcNode

---

concourse/scripts/build_gpdb.py
concourse/scripts/builds/GpBuild.py

Fix Path of the gpdb repo from where the script is invoked.

Fix Path of the gpdb repo for ORCA pipeline

---

gpdb-doc/dita/admin_guide/expand/expand-planning.xml
gpdb-doc/dita/admin_guide/highavail/topics/g-enabling-segment-mirroring.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpinitsystem.xml

Doc updates for changes in PR #7296

Docs gpinitstandby flags 2

---

src/backend/fts/fts.c

Quick fixup I noticed while working on the FTS hang.
Modified from camel to snake case.

Conform variable style to surrounding fts code.

---

gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/parseutils.py
gpMgmt/test/behave/mgmt_utils/gpmovemirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave/mgmt_utils/steps/mirrors_mgmt_utils.py

6X BACKPORT Prevent gpmovemirrors from deleting mirror directory

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/olap_window_seq.out
src/test/regress/expected/olap_window_seq_optimizer.out
src/test/regress/sql/olap_window_seq.sql

These are the corresponding ICG changes to https://github.com/greenplum-db/gporca/pull/463

ICG changes for "Predicate pushdown in part tables with window func"

---

gpdb-doc/dita/ref_guide/extensions/pl_java.xml
gpdb-doc/dita/ref_guide/extensions/pl_perl.xml
gpdb-doc/dita/ref_guide/extensions/pl_python.xml
gpdb-doc/dita/ref_guide/extensions/pl_r.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_LANGUAGE.xml
gpdb-doc/dita/utility_guide/client_utilities/createlang.xml

Move to documenting CREATE/DROP EXTENSION for pl/r, pl/perl, pl/python. Also update deprecation notices.

Update PL's to use CREATE/DROP EXTENSION

---

concourse/scripts/compile_gpdb.bash
concourse/scripts/sync_tools.bash
concourse/tasks/compile_gpdb.yml
concourse/tasks/sync_tools.yml
gpAux/releng/releng.mk

Co-authored-by: Bhuvnesh Chaudhary <bchaudhary@pivotal.io>

Compile ORCA and Xerces using the same toolchain as GPDB on CentOS.

---

src/backend/executor/execMain.c
src/backend/executor/functions.c
src/backend/executor/spi.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/include/nodes/plannodes.h
src/include/utils/metrics_utils.h
src/test/regress/input/query_info_hook_test.source
src/test/regress/output/query_info_hook_test.source
src/test/regress/query_info_hook_test/query_info_hook_test.c

master PR is #7362 already merged.

5X: Improve monitability of query_info_hook to SPI queries

---

src/backend/executor/execMain.c
src/backend/executor/functions.c
src/backend/executor/spi.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/include/nodes/plannodes.h
src/include/utils/metrics_utils.h
src/test/regress/input/query_info_hook_test.source
src/test/regress/output/query_info_hook_test.source
src/test/regress/query_info_hook_test/query_info_hook_test.c

master PR is #7362 and #7458, #7362 is already merged.

6X: Improve monitability of query_info_hook to SPI queries

---

gpdb-doc/dita/ref_guide/sql_commands/CREATE_FUNCTION.xml

Docs - fix type in create function ref

---

src/bin/gpfdist/gpfdist.c

Fix gpfdist build error on USE_SSL off

fix gpfdist build error on USE_SSL off

---

gpdb-doc/markdown/pxf/jdbc_pxf.html.md.erb

formatting change.  backport to 6X_STABLE and 5X_STABLE.

docs - replace < in CREATE EXTERNAL TABLE syntax

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_class.xml
gpdb-doc/dita/ref_guide/system_catalogs/pg_index.xml

Reconciles gp_class and pg_index catalog references with the GPDB 6 Beta catalog tables

Docs - update pg_class and pg_index catalog table references

---

gpdb-doc/markdown/pxf/jdbc_cfg.html.md.erb

update jdbc server configuration topic to include info about this new property.
doc review site link - MAY NEED TO REFRESH - http://docs-lisa-pxf.cfapps.io/6-0/pxf/jdbc_cfg.html#conntransiso

docs - add pxf jdbc.connection.transactionIsolation server cfg property

---

src/test/isolation2/expected/segwalrep/dtm_recovery_on_standby.out
src/test/isolation2/helpers/server_helpers.sql
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/segwalrep/dtm_recovery_on_standby.sql
src/test/isolation2/sql_isolation_testcase.py

This is a backport of #7532 from master to 6X_STABLE.

6X backport: Re-implement master/standby tests for DTM recovery 

---

gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml

a few misc edits, and correction of gpbackup/restore email example YAML file.
will be back-ported to 6X_STABLE and 5X_STABLE

docs - fixes/edits to gpbackup/restore email example

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/union_gp.out
src/test/regress/sql/union_gp.sql

Also add a few more tests for unions to ICG.

Bump ORCA version to 3.37 (from 3.35)

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Includes ICG changes for ORCA commit:
'Convert FULL OUTER JOIN to LEFT JOIN when possible'
ICG pases.
ORCA PR: https://github.com/greenplum-db/gporca/pull/468

ICG changes for 'Convert FULL OUTER JOIN to LEFT JOIN when possible'

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/union_gp.out
src/test/regress/sql/union_gp.sql

Also add a few more tests for unions to ICG.

5X: Bump ORCA version to 3.37 (from 3.35)

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Includes ICG changes for ORCA commit:
'Convert FULL OUTER JOIN to LEFT JOIN when possible'
ORCA PR: greenplum-db/gporca#468

Port to 5X ICG changes for 'Convert FULL OUTER JOIN to LEFT JOIN when possible' 

---

GNUmakefile.in
contrib/auto_explain/Makefile
contrib/auto_explain/expected/auto_explain.out
contrib/auto_explain/init_file
contrib/auto_explain/sql/auto_explain.sql

1. Add test cases for auto_explain
* Add init_file to filter out random numbers
* set CLIENT_MIN_MESSAGES to show `LOG` message to result file
2. Add auto_explain item in gpdb/GNUmakefile.in
- [*] Add tests for the change
- [*] Pass `make installcheck`

Add test cases for auto_explain and enable it in GNUmakefile.in

---

contrib/auto_explain/expected/auto_explain.out
contrib/auto_explain/expected/auto_explain_optimizer.out
contrib/auto_explain/init_file
contrib/auto_explain/sql/auto_explain.sql

This PR is used to fix a pipeline failure caused by a bad init_file(in #7195 ) for auto_explain.

Fix auto explain init file

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/473
Fix the spec if the union child has external scan.

Bump ORCA version to v3.39.0

---

concourse/pipelines/pr_pipeline.yml

Authored-by: David Sharp <dsharp@pivotal.io>
A test pipeline (with the pr 'put' steps removed) is up here: https://k8s.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_pr/

concourse pr_pipeline: Switch to building centos7; Only master PRs

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_dml_optimizer.out
src/test/regress/expected/qp_orca_fallback_optimizer.out
src/test/regress/expected/updatable_views_optimizer.out
src/test/regress/expected/update_gp.out
src/test/regress/expected/update_gp_optimizer.out
src/test/regress/expected/update_optimizer.out
src/test/regress/sql/update_gp.sql

Corresponding ORCA PR:
https://github.com/greenplum-db/gporca/pull/474

Bump ORCA version to v3.40.0

---

gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb

backport to 6X_STABLE and 5X_STABLE

docs - fix link xml->html

---

src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/test/regress/expected/qp_orca_fallback.out
src/test/regress/expected/qp_orca_fallback_optimizer.out
src/test/regress/sql/qp_orca_fallback.sql

Allow user to enable and disable hash/group aggregates with GPORCA

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/expected/update_gp_optimizer.out

Bump ORCA version to 3.41.0 and update test cases.
Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/471

Master spec dist

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/expected/notin_optimizer.out
src/test/regress/expected/update_gp_optimizer.out

Bump ORCA version to 3.41.0 and update test cases.
Corresponding ORCA PR: greenplum-db/gporca#471

Bump ORCA to v3.41.0 and update test cases

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_statistic_optimizer.out
src/test/regress/expected/update_gp_optimizer.out

Bump ORCA to v3.42.0 and update test cases
Corresponding ORCA PR: greenplum-db/gporca#456

Bump ORCA to v3.42.0 and update test cases

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/bfv_statistic_optimizer.out
src/test/regress/expected/gpdist_legacy_opclasses_optimizer.out
src/test/regress/expected/update_gp_optimizer.out

Bump ORCA to 3.42.0 and update test cases
Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/456

Bump ORCA to 3.42.0 and update test cases

---

gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

In gpexpand behave test there is a flaky failed test in "verify that the
cluster has 8 new segments".
We suspect some segments may be down after expansion.  So we dump the
gp_segment_configuration on that exception to confirm.

Dump gp_segment_configuration in gpexpand behave test

---

gpdb-doc/book/master_middleman/source/subnavs/pxf-subnav.erb

about server configuration, read file as row topics

add recent pxf topic additions to subnav

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gp_dqa_optimizer.out

Bump ORCA version to 3.43.1

---

src/backend/access/transam/xact.c
src/backend/cdb/cdbtm.c
src/backend/storage/ipc/procarray.c
src/include/cdb/cdbtm.h
src/include/storage/procarray.h

Minor refactor around ProcArrayEndTransaction

---

.travis.yml
README.amazon_linux
README.ubuntu.bash
gpMgmt/Makefile
gpMgmt/bin/Makefile
gpMgmt/bin/ext/.gitignore
gpMgmt/bin/ext/Crypto/.gitignore
gpMgmt/bin/lib/.gitignore
python-dependencies.txt
src/tools/docker/centos6/Dockerfile
src/tools/docker/centos7/Dockerfile
src/tools/docker/ubuntu16/Dockerfile
src/tools/vagrant/centos/vagrant-setup.sh
src/tools/vagrant/debian/vagrant-setup.sh

6X BACKPORT: remove paramiko

---

contrib/pxf_fdw/Makefile
contrib/pxf_fdw/expected/pxf_fdw.out
contrib/pxf_fdw/pxf_fdw--1.0.sql
contrib/pxf_fdw/pxf_fdw.c
contrib/pxf_fdw/pxf_option.c
contrib/pxf_fdw/sql/pxf_fdw.sql

PXF: Validation for wrapper options

---

src/tools/msvc/Solution.pm

Commit 42b915a introduced GP_MAJORVERSION dependency in catalog.h.
Add GP_MAJORVERSION to windows configure script.

Fix Windows client build

---

gpcontrib/gp_inject_fault/Makefile
gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.c
src/backend/fts/ftsmessagehandler.c
src/backend/postmaster/postmaster.c
src/backend/replication/walreceiver.c
src/backend/replication/walsender.c
src/backend/storage/lmgr/proc.c
src/backend/tcop/postgres.c
src/backend/utils/init/miscinit.c
src/backend/utils/init/postinit.c
src/backend/utils/misc/faultinjector.c
src/backend/utils/resource_manager/resource_manager.c
src/include/libpq/pqcomm.h
src/include/utils/faultinjector.h
src/include/utils/faultinjector_lists.h
src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql
src/test/regress/expected/psql_gp_commands.out

This is back port of PR #7577 to 6X_STABLE

6X backport: Allow faults to be injected on mirror and use them for master/standby replication tests

---

src/tools/docker/ubuntu16-debian/debian/control

The debian package only exists in 5X

Fix debian description to adhere to standards

---

concourse/scripts/build_gpdb.py
concourse/scripts/builds/GpBuild.py

Minor change to use the correct path for modules testing orca and adding a default guc to test orca pipeline.

Update diff path and add guc to run orca pipelines

---

concourse/scripts/builds/GpBuild.py
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h

Rename optimizer_enable_full_join to optimizer_expand_fulljoin

---

gpMgmt/bin/gppylib/operations/segment_reconfigurer.py
gpMgmt/test/behave_utils/utils.py
src/backend/access/transam/xact.c
src/backend/cdb/cdbtm.c
src/backend/cdb/cdbtmutils.c
src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/cdb/dispatcher/cdbdisp_query.c
src/backend/tcop/dest.c
src/backend/utils/misc/guc_gp.c
src/include/access/xact.h
src/include/cdb/cdbtm.h
src/interfaces/libpq/fe-protocol3.c
src/interfaces/libpq/libpq-int.h
src/test/isolation2/expected/fts_errors.out
src/test/isolation2/expected/segwalrep/commit_blocking.out
src/test/isolation2/expected/segwalrep/failover_with_many_records.out
src/test/isolation2/expected/segwalrep/fts_unblock_primary.out
src/test/isolation2/sql/fts_errors.sql
src/test/isolation2/sql/segwalrep/commit_blocking.sql
src/test/isolation2/sql/segwalrep/failover_with_many_records.sql
src/test/isolation2/sql/segwalrep/fts_unblock_primary.sql
src/test/regress/expected/direct_dispatch.out
src/test/regress/expected/direct_dispatch_optimizer.out
src/test/regress/expected/distributed_transactions.out
src/test/regress/expected/gangsize.out
src/test/regress/expected/gangsize_optimizer.out
src/test/regress/expected/qp_targeted_dispatch.out
src/test/regress/expected/qp_targeted_dispatch_optimizer.out
src/test/regress/twophase_pqexecparams.c

This is based on the reverted PR #7529 plus fixes the failed behave tests.

Optimize explicit transactions

---

gpMgmt/bin/gpconfig
gpMgmt/bin/gpconfig_modules/compare_segment_guc.py
gpMgmt/bin/gppylib/test/unit/test_unit_compare_segment_guc.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpconfig.py
gpMgmt/sbin/gpconfig_helper.py
gpMgmt/test/behave/mgmt_utils/gpconfig.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpMgmt/test/behave_utils/utils.py
gpdb-doc/dita/utility_guide/admin_utilities/gpconfig.xml

This is a 6X backport of PR #7749.

6X backport: gpconfig quoting

---

concourse/scripts/compile_gpdb.bash

Do not include zstd or quicklz for SLES

---

concourse/scripts/compile_gpdb.bash

Co-authored-by: Bradford D. Boyle <bboyle@pivotal.io>
Co-authored-by: Shaoqi Bai <sbai@pivotal.io>

Fix pipeline failure in compile_gpdb_sles11

---

gpMgmt/bin/lib/gp_bash_functions.sh

Previously, PING_HOST swallowed any log messages from ping, and now we
display those messages in the error message.

gp_bash_functions: Improve PING_HOST logging

---

gpdb-doc/markdown/pxf/troubleshooting_pxf.html.md.erb

can config certain OOM behaviours for pxf jvm.  document them on the pxf troubleshooting page.
doc review site link:  http://docs-lisa-pxf2.cfapps.io/6-0/pxf/troubleshooting_pxf.html#pxf-cfgoom

docs - add info about config'ing pxf OOM actions

---

gpdb-doc/dita/utility_guide/admin_utilities/gpconfig.xml

update gpconfig reference with info about setting GUC value 

---

src/tools/msvc/Mkvcbuild.pm

AddResourceFile function adds a project and use the 3rd parameter as icon.

Add icon to client script tools

---

concourse/pipelines/gen_pipeline.py
concourse/pipelines/templates/gpdb-tpl.yml
concourse/scripts/compile_gpdb_remote_windows.bash
concourse/scripts/compile_gpdb_remote_windows.bat
concourse/tasks/compile_gpdb_remote_windows.yml

Co-authored-by: Peifeng Qiu <pqiu@pivotal.io>
Co-authored-by: Bob Bao <bbao@pivotal.io>

Add windows gpdb clients compile task to pipeline

---

src/include/commands/copy.h

Remove the duplicate definition of CopyState

---

concourse/scripts/sync_tools.bash

Update orca to new version v3.47.0

---

src/test/isolation2/expected/create_memory_accounting_tables.out
src/test/isolation2/expected/oom_mixed_1.out
src/test/isolation2/expected/oom_mixed_1_optimizer.out
src/test/isolation2/expected/oom_mixed_2.out
src/test/isolation2/expected/oom_mixed_2_optimizer.out
src/test/isolation2/expected/oom_simple.out
src/test/isolation2/expected/segwalrep/master_xlog_switch.out
src/test/isolation2/helpers/gp_management_utils_helpers.sql
src/test/isolation2/input/pg_basebackup.source
src/test/isolation2/input/pg_basebackup_with_tablespaces.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/pg_basebackup.source
src/test/isolation2/output/pg_basebackup_with_tablespaces.source
src/test/isolation2/sql/segwalrep/master_xlog_switch.sql
src/test/isolation2/sql_isolation_testcase.py

This is back port of #7716 to 6X_STABLE.

 6X backport: Test to perform backup when master goes through XLOG switch

---

GNUmakefile.in
contrib/auto_explain/Makefile
contrib/auto_explain/expected/auto_explain.out
contrib/auto_explain/expected/auto_explain_optimizer.out
contrib/auto_explain/init_file
contrib/auto_explain/sql/auto_explain.sql

This is a backport of #7195 and #7608 for 6X_STABLE

Backport: Add test cases for auto_explain and enable it

---

concourse/scripts/git_info.bash

Inlcude the output of getversion in git-info.json

---

gpdb-doc/dita/ref_guide/sql_commands/COPY.xml

This change will also go into 6X_STABLE, and into 5X_STABLE after the code backport is complete.

Remove COPY (query) limitation for ON SEGMENT clause

---

concourse/scripts/sync_tools.bash
config/orca.m4
configure
depends/conanfile_orca.txt

Bump ORCA version to 3.48.0

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to 3.48

---

concourse/pipelines/gen_pipeline.py

- convert print statements to function calls
- remove unused import
- fix a few minor PEP8 spacing lints

Update gen_pipeline to work with python3

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/test/regress/expected/qp_gist_indexes3_optimizer.out
src/test/regress/expected/qp_gist_indexes4_optimizer.out
src/test/regress/expected/qp_targeted_dispatch_optimizer.out

Bump ORCA version to 3.50.0, ICG result file changes

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/qp_gist_indexes3_optimizer.out
src/test/regress/expected/qp_gist_indexes4_optimizer.out
src/test/regress/expected/qp_targeted_dispatch_optimizer.out

5X: Bump ORCA version to 3.50, ICG expected file changes

---

gpdb-doc/dita/ref_guide/system_catalogs/gp_segment_configuration.xml

Docs: clarify values for master/standby in gp_segment_configuration

---

src/test/regress/.gitignore
src/test/regress/GNUmakefile
src/test/regress/expected/.gitignore
src/test/regress/greenplum_schedule
src/test/regress/input/temp_tablespaces.source
src/test/regress/output/temp_tablespaces.source
src/test/regress/sql/.gitignore

Test does not include tablespace drop.

Temporary tables should be created in the tablespace specified by temp_tablespaces guc

---

concourse/pipelines/gen_pipeline.py
concourse/pipelines/templates/gpdb-tpl.yml
concourse/scripts/compile_gpdb_remote_windows.bash
concourse/scripts/compile_gpdb_remote_windows.bat
concourse/scripts/ic_gpdb_remote_windows.bash
concourse/scripts/ic_gpdb_remote_windows.bat
concourse/scripts/windows_remote_test.ps1
concourse/tasks/compile_gpdb_remote_windows.yml
concourse/tasks/rename_rc_artifacts.yml
concourse/tasks/windows_remote_test.yml
gpAux/client/install/src/windows/CreatePackage.bat
gpAux/client/install/src/windows/greenplum-clients.wxs
gpMgmt/bin/gpload_test/gpload2/TEST_REMOTE.py
src/bin/gpfdist/wintest/pipe_win10.cpp
src/test/regress/gpdiff.pl

1) Run TEST_REMOTE.py of gpload
2) Run psql SSL, gpfdist Windows pipe testing
Pipeline: https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master-bob-add-windows-test
After the PR merged, we will delete the pipeline ASAP.
Co-authored-by: Tingfang Bao <bbao@pivotal.io>
Co-authored-by: Xiaoran Wang <xiwang@pivotal.io>
Co-authored-by: Xiaodong Huo <xhuo@pivotal.io>

Add gpdb clients test cases on windows server

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt

ORCA commit: Skip group expression containing circular references
Authored-by: Chris Hajas <chajas@pivotal.io>

Bump ORCA version to 3.52.0

---

concourse/scripts/common.bash
src/bin/gpfdist/regress/input/gpfdist_ssl.source

Configure gpdb with openssl to enable gpfdist_ssl test cases

---

gpdb-doc/dita/admin_guide/ddl/ddl-tablespace.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
gpdb-doc/dita/ref_guide/sql_commands/CREATE_INDEX.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE_AS.xml
gpdb-doc/dita/ref_guide/sql_commands/DROP_TABLESPACE.xml

Adding reference topic and additional docs around temp_tablespaces

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/test/regress/expected/qp_subquery.out
src/test/regress/expected/qp_subquery_optimizer.out
src/test/regress/sql/qp_subquery.sql

Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/500

ICG changes for Create LAS Correlated Apply on in filter context

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/qp_subquery.out
src/test/regress/expected/qp_subquery_optimizer.out
src/test/regress/sql/qp_subquery.sql

ICG changes for Create LAS Correlated Apply on in filter context

5X: Bump ORCA version to 3.53.0

---

concourse/scripts/remove_non_production_files.bats
concourse/scripts/remove_non_production_files.sh

To match how bin_gpdb tar.gz is created.
Co-authored-by: Mark Sliva <msliva@pivotal.io>
Co-authored-by: Amil Khanzada @amilkh

Update remove_non_production_files.sh to tar with ./ paths

---

concourse/scripts/common.bash
src/bin/gpfdist/regress/input/gpfdist_ssl.source
src/bin/gpfdist/regress/output/gpfdist_ssl.source

Configure gpdb with openssl to enable gpfdist_ssl test cases

Run gpfdist_ssl test cases on windows and linux

---

src/test/regress/expected/olap_window_seq.out
src/test/regress/expected/olap_window_seq_optimizer.out
src/test/regress/sql/olap_window_seq.sql
src/test/regress/sql/rangefuncs_cdb.sql

Co-authored-by: Asim R P <apraveen@pivotal.io>
Co-authored-by: Taylor Vesely <tvesely@pivotal.io>
(cherry picked from commit 95a33fb41dd525c95a1bdfac097aec72984495cc)

Use distinct schema in tests having table name collisions

---

gpdb-doc/markdown/pxf/jdbc_cfg.html.md.erb

minor doc content update for https://github.com/greenplum-db/pxf/pull/182.

docs - jdbc named query ending semicolon is optional

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt

Bump ORCA version to v3.54.0

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt

Corresponding GPORCA PR: https://github.com/greenplum-db/gporca/pull/507

Bump ORCA version to v3.55.0

---

src/backend/cdb/dispatcher/cdbgang.c

For example:
In the same session,
query 1 has 3 slices and it creates gang 1, gang 2 and gang 3.
query 2 has 2 slices, we hope it reuses gang 1 and gang 2 instead of other
cases like gang 3 and gang 2.
In this way, the two queries can have the same send-receive port pair. It's
useful in platform like Azure. Because Azure limits the number of different
send-receive port pairs (AKA flow) in a certain time period.
Co-authored-by: Hubert Zhang <hzhang@pivotal.io>

Keep the order of reusing idle gangs

---

src/test/regress/output/external_table.source

Fix the output of test 'external_table'

---

concourse/scripts/windows_remote_test.ps1

fix win curl tool link failure problem

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/include/gpopt/utils/COptServer.h

The associated GPORCA PRs are:
- greenplum-db/gporca#503 (add project node on top of groupby)
- greenplum-db/gporca#510 (remove multi-threading code)

Bump ORCA version from 3.55 to 3.57

---

contrib/file_fdw/file_fdw.c
contrib/pg_upgrade/gpdb4_heap_convert.c
src/backend/access/external/fileam.c
src/backend/cdb/cdbsreh.c
src/backend/commands/copy.c
src/backend/optimizer/util/pathnode.c
src/include/access/relscan.h
src/include/c.h
src/include/cdb/cdbsreh.h
src/interfaces/libpq/fe-protocol3.c
src/interfaces/libpq/libpq-int.h

Remove some MERGE_FIXMEs

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/utils/misc/guc_gp.c
src/include/gpopt/gpdbwrappers.h
src/include/utils/guc.h
src/test/regress/expected/gpdist_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/join_optimizer.out

Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/484

Support Equi- Full Merge Joins

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/include/gpopt/gpdbwrappers.h

Corresponding ORCA PR: https://github.com/greenplum-db/gporca/pull/484/

Disable Full Merge Join in 5X

---

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml

Will backport to 6X_STABLE and 5X_STABLE

Add centos7 command to start config.service

---

src/backend/executor/execTuples.c

ExecMaterializeSlot() transformed any tuple to a virtual tuple via
slot_getallattrs(), then form a heaptuple from it, ctid was lost here
since virtual tuples have no system columns.
This commit copies the entire htup directly if we have a regular
physical tuple but not locally palloc'd.
Fix #8143

Save the complete slot data in ExecMaterializeSlot()

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Also, bump ORCA version to 2.61.0

Changes for ORCA commit: "IndexNLJ should not broadcast co-located tables"

---

src/backend/executor/execTuples.c

ExecMaterializeSlot() transformed any tuple to a virtual tuple via
slot_getallattrs(), then formed a heaptuple from it, ctid was lost here
since virtual tuples have no system columns.
This commit copies the entire htup directly if we have a regular
physical tuple but not locally palloc'd.
(cherry picked from commit 1eeae2e97e47bda1d840468eb42aea238e77f3c2)

6X: Save the complete slot data in ExecMaterializeSlot()

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to v3.62.0

---

gpdb-doc/dita/admin_guide/dml.xml
gpdb-doc/dita/ref_guide/sql_commands/SELECT.xml

Add information about GDD managing SELECT...FOR <locking strength> queries
Currently, this feature is in MASTER only.
HTML format of updated files
SELECT command
http://docs-msk-gpdb-gdd-dev.cfapps.io/6-0/ref_guide/sql_commands/SELECT.html
Inserting, Updating, and Deleting Data
http://docs-msk-gpdb-gdd-dev.cfapps.io/6-0/admin_guide/dml.html#topic_gdd

docs - GDD SELECT...FOR locking

---

src/backend/cdb/cdbfts.c
src/backend/fts/README
src/backend/fts/fts.c
src/backend/fts/ftsprobe.c
src/include/cdb/cdbfts.h
src/test/isolation2/helpers/server_helpers.sql
src/test/isolation2/input/fts_manual_probe.source
src/test/isolation2/isolation2_schedule
src/test/isolation2/output/fts_manual_probe.source
src/test/regress/regress_gp.c

6X_BACKPORT of #8228 .
This was done via a manual cherry-pick from
a674b6b3025b9dc56c4cb34b3330f8b7bc1bf757.
The only conflict was with the README, which was new in master and was added to 6X.

FTS: Ensure fresh results from a probe (6X_BACKPORT)

---

gpdb-doc/markdown/pxf/hive_pxf.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb

doc changes for pxf-related 5X_STABLE PR https://github.com/greenplum-db/gpdb/pull/8213

docs - pxf updates due to changes in passing format options

---

src/backend/access/transam/xact.c

commit 4be677c7feb05a3dfcea9420b4ebeab4c0de6d4e removed that accidently.
This patch adds it back.

Add back global xaction info in one phase commit.

---

src/backend/commands/dbcommands.c

The movedb_failure_callback existed to ensure that if copydir fails
inside movedb, it would clean up the destination directory. We
introduced the pending deletes mechanism to ensure cleanup throughout
2PC in b0208894eb.
These are two conflicting mechanisms, especially evident in the
following scenario:
1. An error occurs after the ScheduleDbDirDelete on the target
tablespace directory and inside the ENSURE block.
2. movedb_failure_callback() is invoked first which calls rmtree() on the
target tablespace directory.
3. DoPendingDbDeletes() is called from within the subsequent
AbortTransaction(). Since there was a pending db delete,
dropDatabaseDirectory() is called and it eventually calls rmtree().
Since the directory was already deleted at this point this rmtree
produces the following …

Tear out movedb_failure_callback

---

gpMgmt/doc/gpinitsystem_help

synchronize the help file with the documentation
and add missing options

synchronize gpinitsystem help file with the documentation

---

src/backend/cdb/motion/ic_udpifc.c

For a query like:
SELECT ... ORDER BY key LIMIT n;
When the query running time is longer than UNACK_QUEUE_RING_LENGTH * TIMER_SPAN
(By default is 10 seconds), and the first tuple send from OrderBy node to QD is
not acknowledged, function putIntoUnackQueueRing will calculate an
inappropriate retransmission period, which is UNACK_QUEUE_RING_LENGTH *
TIMER_SPAN.

Fix interconnect retransmission period

---

src/backend/access/transam/xact.c

commit 39f09c8586c8ff9bc7cbd78398b1c tends to add that but the code is not right.
Reviewed-by: Ning Yu
Reviewed-by: Asim R P
Reviewed-by: Ashwin Agrawal
Cherry-pick from 237ba5cca110bbc897c4c3c9f62f6eeee049f5cb

[6X Backport] Add global transaction info in one phase commit xlog. (#8346)

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/test/regress/expected/dpe_optimizer.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/expected/indexjoin_optimizer.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/expected/join_optimizer.out
src/test/regress/expected/subselect_gp_optimizer.out

Bump ORCA version to v3.64, add GUC optimizer_penalize_skewed_hashjoin

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h

Add GUC optimizer_penalize_skewed_hashjoin and bump ORCA version

---

src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h

Rename optimizer_penalize_skewed_hashjoin to optimizer_penalize_skew

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h
src/include/utils/unsync_guc_name.h

Co-Authored-By: Hans Zeller <hzeller@pivotal.io>

Add GUC for pruning unused columns in ORCA

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h

Co-Authored-By: Hans Zeller <hzeller@pivotal.io>

5X: Add GUC for pruning unused columns in ORCA

---

gpMgmt/bin/gppylib/Makefile

Fix revision replacement in mainUtils.py

---

src/backend/storage/lmgr/lock.c

When acquire a lock, there is a case where locallock doesn't hold
the lock but global lock treats we already held the lock. This
inconsistent state may be caused by broken of locallock or
global lock. We dump their details in the log here to help analysis.

Error out when locallock and proclock are not consistent. 

---

src/backend/storage/lmgr/lock.c

When acquire a lock, there is a case where locallock doesn't hold
the lock but global lock treats we already held the lock. This
inconsistent state may be caused by broken of locallock or
global lock.
Upstream elog error for this case from the begining. If we already
know locallock or global lock is broken, there is no reason to
continue the queries.

6X BackPort Error out when locallock and proclock are not consistent.

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/optimizer/util/walkers.c
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

5X version of https://github.com/greenplum-db/gpdb/pull/8381

Set Plan::allParam correctly in CTranslatorDXLToPlStmt

---

gpAux/Makefile

Authored-by: Tingfang Bao <bbao@pivotal.io>

Remove the LICENSE and NOTICE files from clients installer

---

src/backend/utils/time/sharedsnapshot.c
src/backend/utils/time/test/sharedsnapshot_test.c

(cherry picked from commit d38c7ecebdc6a6e1fd111108de91e678817ac07a)

Fix unit test sharedsnapshot_test.c

---

gpAux/client/install/src/windows/CreatePackage.bat
gpAux/client/install/src/windows/greenplum-clients.wxs
gpMgmt/bin/gpload.py

- Get gpdb version and supports gpdb5 and gpdb6 SQL
- Add gpversion.py into windows client package
Test can be covered by existing cases.

GPload supports GPDB5 and GPDB6 with the same gpload.py file

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gppylib/test/unit/test_unit_gpload.py

Initialize gpdb_version in gpload init function to fix gpload UT cases

Fix gpload unit test case

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

This corresponds to ORCA commit "Fix stats calculation for Dynamic scans
with partition elimination"
Authored-by: Chris Hajas <chajas@pivotal.io>

Bump ORCA version to v3.66.0

---

gpdb-doc/dita/ref_guide/extensions/pl_r.xml

HTML of updated doc.
http://docs-msk-gpdb6-dev.cfapps.io/6-0/ref_guide/extensions/pl_r.html

docs - Add Ubuntu install/uninstall R information

---

gpdb-doc/dita/ref_guide/extensions/pl_java.xml

Link to HTML format of draft changes
http://docs-msk-gpdb6-pljava-dev.cfapps.io/6-0/ref_guide/extensions/pl_java.html#topic_qx1_xcp_w3b

docs - Add OpenJDK install information

---

gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

- changed title for extension parameters
- added a left nav menu for XML parameters

docs - update to reference parameters

---

gpdb-doc/dita/admin_guide/query/topics/query-piv-opt-notes.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

PR #8456 changes optimizer_force_multistage_agg default to off.

docs - changes default value of optimizer_force_multistage_agg GUC to off

---

gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_activity.xml

backport of doc PR https://github.com/greenplum-db/gpdb/pull/8581

docs - 5X pg_stat_activity - add note about resource group values.

---

src/test/regress/input/gp_tablespace.source
src/test/regress/input/gptokencheck.source
src/test/regress/output/external_table.source
src/test/regress/output/gp_tablespace.source
src/test/regress/output/gptokencheck.source
src/test/regress/pg_regress.c

Thanks to @danielgustafsson for reviewing PR #8559. I pushed the PR before receiving them. Hence, incorporating the feedback separately now here.

Incorporate review comments for PR #8559

---

gpdb-doc/dita/ref_guide/extensions/postGIS.xml

correct the postgis package name.  (not sure why there is a "remove package" reference, but no install package reference ...)

docs - update postgis package name

---

concourse/pipelines/pr_pipeline.yml

Set base_branch for pr_pipeline.yml on 6X_STABLE.

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/translate/CTranslatorDXLToScalar.cpp
src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp

Bump ORCA version to v3.70.0

---

gpdb-doc/dita/admin_guide/external/g-gpfdist-protocol.xml
gpdb-doc/dita/admin_guide/external/g-gpfdists-protocol.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpfdist.xml

Also added links to the gpfdist utility in other topics.

docs - add gpfdist support for writing gzip compressed files.

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

ORCA side PR: https://github.com/greenplum-db/gporca/pull/527
Planner issue: https://github.com/greenplum-db/gpdb/issues/8582

ICG tests for ORCA change: "Wrong preprocessed query for nullable contraints"

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Bump ORCA version to 3.71, Add ICG tests for ORCA PR527

---

src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out

Fix test case subselect_gp.

---

src/backend/storage/lmgr/proc.c

Allocate and zero out the memory of MyTmGxactLocal

---

concourse/tasks/compile_gpdb.yml
config/orca.m4
configure
depends/conanfile_orca.txt
src/backend/gpopt/utils/COptTasks.cpp
src/backend/optimizer/plan/orca.c
src/backend/utils/misc/guc_gp.c
src/include/gpopt/utils/COptTasks.h
src/test/regress/expected/gporca_optimizer.out

- The corresponding ORCA PR is : https://github.com/greenplum-db/gporca/pull/533
- Change GUC value OPTIMIZER_UNEXPECTED_FAIL so that we log only unexpected failures.
Co-authored-by: Sambitesh Dash <sdash@pivotal.io>

Reduce Error logging for ORCA

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/utils/COptTasks.cpp
src/backend/optimizer/plan/orca.c
src/backend/utils/misc/guc_gp.c
src/include/gpopt/utils/COptTasks.h
src/test/regress/expected/gporca_optimizer.out

- The corresponding ORCA PR is : https://github.com/greenplum-db/gporca/pull/533
- Change GUC value OPTIMIZER_UNEXPECTED_FAIL so that we log only unexpected failures.
Co-authored-by: Sambitesh Dash <sdash@pivotal.io>

Bump ORCA v3.72.0 and reduce Error logging for ORCA

---

src/bin/pg_dump/dumputils.c

Backporting #7533 to 6X_STABLE
strncat unfortunately takes a misleading size argument which means
at most size from src. It is a bit of an antipattern in the string
family of functions and for that compilers will emit a warning if
it happens that the size argument matches the size of src, since that
is not what usually users of strncat want to do.
The usage of the function in the code was correct. However instead
of silencing the compiler, strncat was replaced with a front end
dynamic buffer and family of functions that postgres is providing.
Also protect against an invalid read in case that the size of the
result is zero.

Backport #7533 Silece stringop-overflow warning and protect against invalid read to 6X

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

Will be backported to 6X_STABLE, 5X_STABLE

docs -clarify  GUC default_transaction_deferrable has no effect.

---

src/backend/cdb/cdbplan.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

Fixes github issue https://github.com/greenplum-db/gpdb/issues/8621

Handle VALUES expressions in plan_tree_mutator()

---

src/backend/cdb/cdbmutate.c

The function did completely different things for different callers, so
seems better to move the logic to the callers instead.

Refactor away add_slice_to_motion() function.

---

gpdb-doc/dita/ref_guide/sql_commands/CREATE_AGGREGATE.xml

Made some small changes, sfunc -> statefunc where I saw variable name in the xml. 
Also, removed stype reference in the text. 
But I'm not 100% certain that's what you're looking for David.

edits to AGGREGATE function variables

---

src/test/tinc/tincrepo/dml/triggers/expected/child_part_fallback.ans
src/test/tinc/tincrepo/dml/triggers/expected/delete_fallback.ans
src/test/tinc/tincrepo/dml/triggers/expected/insert_fallback.ans
src/test/tinc/tincrepo/dml/triggers/expected/update_fallback.ans
src/test/tinc/tincrepo/dml/triggers/sql/child_part_fallback.sql
src/test/tinc/tincrepo/dml/triggers/sql/delete_fallback.sql
src/test/tinc/tincrepo/dml/triggers/sql/insert_fallback.sql
src/test/tinc/tincrepo/dml/triggers/sql/update_fallback.sql

This will make the pipeline green

Fix orca fallback tinc tests

---

contrib/pg_upgrade/test/integration/Makefile
contrib/pg_upgrade/test/integration/bdd-library/bdd.h
contrib/pg_upgrade/test/integration/bdd-library/upgrade-bdd.c
contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test.c
contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
contrib/pg_upgrade/test/integration/scenarios/ao_table.c
contrib/pg_upgrade/test/integration/scenarios/ao_table.h
contrib/pg_upgrade/test/integration/scenarios/heap_table.c
contrib/pg_upgrade/test/integration/scenarios/heap_table.h
contrib/pg_upgrade/test/integration/scripts/gpdb5-cluster.c
contrib/pg_upgrade/test/integration/scripts/gpdb6-cluster.c
contrib/pg_upgrade/test/integration/utilities/gpdb5-cluster.c
contrib/pg_upgrade/test/integration/utilities/gpdb5-cluster.h
contrib/pg_upgrade/test/integration/utilities/gpdb6-cluster.c
contrib/pg_upgrade/test/integration/utilities/query-helpers.c
contrib/pg_upgrade/test/integration/utilities/query-helpers.h
contrib/pg_upgrade/test/integration/utilities/test-helpers.c
contrib/pg_upgrade/test/integration/utilities/test-helpers.h
contrib/pg_upgrade/test/integration/utilities/upgrade-helpers.c

This change includes some refactoring to make it easier to add more tests without conflicting with other developers also writing tests in pg_upgrade.
Reusable bits between tests should be extracted from test files into reusable components.

Test an administrator can upgrade an AO table with data.

---

gpMgmt/bin/gpload.py

gpload.py catches importError for gpversion. 
It will fallback to GPDB5 compatible if fails to import gpversion.

gpload: catch importError for gpversion

---

gpdb-doc/dita/install_guide/migrate.xml

github issue https://github.com/greenplum-db/gpdb/issues/8676

docs - add string_agg function as a GPDB 6 migration issue

---

gpdb-doc/dita/utility_guide/admin_utilities/gpfdist.xml
gpdb-doc/dita/utility_guide/admin_utilities/gpload.xml

This will be backporrted to 6X_STABLE, 5X_STABLE, and 4.3.x

docs - Add note for gpfdist/gpload wrong line number in error messages

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

See dev PR 5X_STABLE https://github.com/greenplum-db/gpdb/pull/8704

docs - add GUC optimizer_enable_dml

---

src/test/isolation2/isolation2_schedule

- as an experiment. We want to see if it becomes less flakey.

Remove vacuum_drop_phase_ao from parallel group

---

gpdb-doc/markdown/pxf/gphdfs-pxf-migrate.html.md.erb
gpdb-doc/markdown/pxf/hdfs_parquet.html.md.erb
gpdb-doc/markdown/pxf/objstore_parquet.html.md.erb

docs - remove beta designation of pxf parquet write

---

gpdb-doc/dita/install_guide/migrate.xml

This PR restores text about using gpcopy to copy data to the migration topic

docs - add gpcopy as an option to migrate data to GPDB 6

---

gpdb-doc/markdown/pxf/hdfs_text.html.md.erb
gpdb-doc/markdown/pxf/read_s3_s3select.html.md.erb

doc review site link:  http://docs-lisa-s3selfhead.cfapps.io/6-0/pxf/read_s3_s3select.html#s3_select_csv

docs - provide more detail about pxf s3 select FILE_HEADER option

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Corresponding ORCA commit: "Support on-demand property derivation for scalar properties"
Authored-by: Chris Hajas <chajas@pivotal.io>

5X: Bump ORCA version to 3.77.0

---

src/backend/cdb/motion/ic_tcp.c

In SetupTCPInterconnect() we initialize both incoming and outgoing
connections, a state pointer sendingChunkTransportState is created to
track the status of outgoing connections, it is an entry of the states
array, we expect the pointer to be valid during the function.
However, after we get this pointer we will initialize the incoming
connections, they will resize the states array with repalloc(), so
sendingChunkTransportState will point to invalid memory and crash at
runtime.
To fix that we should initialize the incoming connections before the
outgoing ones, so the sendingChunkTransportState pointer stays valid
during its lifecycle.
Tests are not added as it has chances to be triggered by existing tests.
(cherry picked from commit 296dba824b2934d2cf13c74bb567a561b31f58b9)
This is the 5X …

5X: ic: tcp: init incoming conns before outgoing conns

---

gpdb-doc/dita/utility_guide/ref/gprecoverseg.xml

--full segment recovery does not recover custom files.
to be backported

docs - add info about gprecoverseg -F

---

src/backend/catalog/gp_toolkit.sql
src/test/regress/expected/gp_toolkit.out
src/test/regress/sql/gp_toolkit.sql

Add materialized view support in gp_toolkit

---

src/backend/commands/matview.c
src/backend/tcop/dest.c
src/include/commands/matview.h
src/test/regress/expected/matview_ao.out
src/test/regress/sql/matview_ao.sql

Support 'refresh materialized view with no data'

---

gpdb-doc/dita/admin_guide/partV.xml
gpdb-doc/dita/admin_guide/perf_issues.xml
gpdb-doc/dita/install_guide/capacity_planning.xml

--Add information about using tablespace for temp files
--Also update performance overview topic (not related to this PR)
This will be backported to 5.x and 4.3.x

docs - update disk usage planning info.

---

gpdb-doc/dita/utility_guide/admin_utilities/gpcheck.xml

--clarify how to run gpcheck with root privileges
--add example to run gpcheck with root privileges

docs - update gpcheck information

---

src/backend/access/transam/xlog.c

Initdb outputs:
```
creating template1 database in data-master/base/1 ... 2019-10-15 17:32:43.566646 CST,,,p73904,th345056704,,,,0,,,seg-10000,,,,,"LOG","00000","end of transaction log location is 0/4000098",,,,,,,,"StartupXLOG","xlog.c",7417,
2019-10-15 17:32:43.567223 CST,,,p73904,th345056704,,,,0,,,seg-10000,,,,,"LOG","00000","latest completed transaction id is 4294967295 and next transaction id is 3",,,,,,,,"StartupXLOG","xlog.c",7705,
2019-10-15 17:32:43.567528 CST,,,p73904,th345056704,,,,0,,,seg-10000,,,,,"LOG","00000","database system is ready",,,,,,,,"StartupXLOG","xlog.c",7729,
ok
initializing pg_authid ... 2019-10-15 17:32:45.008956 CST,,,p73906,th83031488,,,,0,,,seg-10000,,,,,"LOG","00000","end of transaction log location is 0/40101D8",,,,,,,,"StartupXLOG","xlog.c",7417, …
```

Avoid recovery log messages during initdb

---

src/test/regress/expected/join_gp_optimizer.out

Co-authored-by: Hans Zeller <hzeller@pivotal.io>

Bump ORCA version to 3.79, update ICG answer file

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/join_gp_optimizer.out

5X: Bump ORCA version to 3.79, update ICG answer file

---

contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table_with_a_dropped_column.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table_with_a_dropped_column.h

Add upgrade happy-path test of partition tables with dropped columns

---

gpdb-doc/dita/admin_guide/access_db/topics/g-greenplum-database-client-applications.xml
gpdb-doc/dita/ref_guide/extensions/pl_java.xml
gpdb-doc/dita/ref_guide/extensions/pl_perl.xml
gpdb-doc/dita/ref_guide/extensions/pl_python.xml
gpdb-doc/dita/ref_guide/extensions/pl_r.xml
gpdb-doc/dita/utility_guide/ref/createlang.xml
gpdb-doc/dita/utility_guide/ref/droplang.xml

PR 1 of 2 for this story
Expanded the note in createlang and created the note in droplang.
Added notes about createlang/droplang in java/perl/python/R

docs - createlang and droplang additional text in note 

---

gpdb-doc/dita/ref_guide/sql_commands/CREATE_ROLE.xml

it occurred on all the versions.

update a tiny mistake for create role doc

---

contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_ao_table.h
contrib/pg_upgrade/test/integration/utilities/query-helpers.c
contrib/pg_upgrade/test/integration/utilities/query-helpers.h

Co-authored-by: Bhuvnesh Chaudhary <bhuvnesh2703@gmail.com>

Add upgrade test for subpartitioned ao tables with multiple ao segments

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/qp_misc_jiras.out
src/test/regress/expected/qp_misc_jiras_optimizer.out
src/test/regress/sql/qp_misc_jiras.sql

Bump ORCA version to v3.80.0

---

src/bin/pg_rewind/filemap.c

A simple panic case so no test is needed.  I saw this during testing.

Fix potential panic in process_aofile_change().

---

src/backend/commands/extension.c

The operation for ALTER EXTENSION ADD/DROP doesn't be dispatched to
segments, so there is no effect on segments.
Now we do it like ExecAlterObjectSchemaStmt() in this commit.
Before the fix, This ADD/DROP action only takes effect on the master:
```sql
postgres=# \dx+ dva
Objects in extension "dva"
Object Description 
table a
table d
table v
(3 rows)
postgres=# alter extension dva drop table d;
ALTER EXTENSION
Time: 5.766 ms
```
```sql
postgres=# select objid::regclass from pg_depend where refobjid = (select oid from pg_extension where extname = 'dva') and refclassid = 'pg_extension'::regclass and deptype = 'e';
objid 
-------
v
a
(2 rows)
Time: 16.005 ms
```
And  there is no effect on segments:
```sql
$PGOPTIONS='-c gp_session_role=utility' psql -p 25432
Timing is on. …
```

Fix ALTER EXTENSION ADD/DROP don't be executed on QE

---

gpcontrib/gp_inject_fault/gp_inject_fault--1.0.sql
gpcontrib/gp_inject_fault/gp_inject_fault.c
src/test/regress/expected/psql_gp_commands.out
src/test/regress/input/alter_db_set_tablespace.source
src/test/regress/input/createdb.source
src/test/regress/input/gp_tablespace.source
src/test/regress/input/gp_tablespace_with_faults.source
src/test/regress/output/alter_db_set_tablespace.source
src/test/regress/output/createdb.source
src/test/regress/output/gp_tablespace.source
src/test/regress/output/gp_tablespace_with_faults.source
src/test/regress/regress_gp.c

This backports 5feccaae (#8908 ).

6X Backport: Elevate force_mirrors_to_catch_up() to gp_inject_fault

---

src/backend/commands/extension.c

This backports PR: #8935 and fixes #8862

6X Backport: Fix ALTER EXTENSION ADD/DROP don't be executed on QE

---

gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml

6.x only.
dev PR https://github.com/greenplum-db/gpdb/pull/8847

docs - add gpinitsystem option --ignore-warnings

---

contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
contrib/pg_upgrade/test/integration/scenarios/pl_function.c
contrib/pg_upgrade/test/integration/scenarios/pl_function.h
contrib/pg_upgrade/test/integration/scenarios/plpgsql_function.h

A plpython version of commit f871cbe515e8.

Add a plpython test case for upgrade from 5X to 6X

---

gpdb-doc/dita/install_guide/prep_os.xml
gpdb-doc/dita/utility_guide/ref/gpbackup.xml
gpdb-doc/dita/utility_guide/ref/gpexpand.xml
gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
gpdb-doc/dita/utility_guide/ref/gprestore.xml

To be bacported to 6X_STABLE and 5X_STABLE

docs - add MaxSessions to SSH connections note.

---

gpdb-doc/dita/install_guide/migrate.xml

Adding another batch of 4.3 to 6 migration considerations.

Additional migration considerations from IRL testing.

---

src/backend/commands/extension.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/equalfuncs.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/include/nodes/parsenodes.h

This backports commit: 841d8fa6946, PR: #8951

6X backport: Add support for update extension

---

contrib/pg_upgrade/test/integration/greenplum_five_to_greenplum_six_upgrade_test_suite.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table.c
contrib/pg_upgrade/test/integration/scenarios/partitioned_heap_table.h

Add new partition to list and range partitioned table and test upgrading the table.

Add new partitions and test upgrade

---

configure
configure.in
src/backend/cdb/cdbutil.c
src/backend/cdb/dispatcher/cdbconn.c
src/include/pg_config.h.in

Configure.in cleanup

---

src/backend/utils/resgroup/resgroup.c
src/backend/utils/resgroup/test/resgroup_test.c

In shouldBypassQuery() we used to parse the query_string with the memory
context MessageContext, however when it is NULL we would crash at
runtime, this is possible by extensions or bgworkers when executing like
below:
debug_query_string = "select 1";
StartTransactionCommand();
This is not the recommended order to set debug_query_string, however we
should not put a constraint on the order by resource group anyway.
To fix this we create and switch to a temporary memory context when
MessageContext is NULL.

resgroup: use proper memory context when checking bypass mode

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/gporca_optimizer.out

The corresponding ORCA PR is greenplum-db/gporca#553

Bump ORCA version to 3.82, update ICG result files

---

concourse/scripts/test_upgrade.bash

The previous PR introduced new required flags for pg_upgrade. We'd missed one spot because this job is not a part of the PR pipeline.

Adds gp dbid flags to pg_upgrade while running in concourse.

---

contrib/pg_upgrade/test/integration/output/exchange_partition_heap_table.source
contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_dropped_columns.source
contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_varlen_dropped_columns.source
contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_sized_dropped_columns.source
contrib/pg_upgrade/test/integration/output/unsupported_dist_coltypes.source

Commit 04031f54399 changed output of upgrade for live cluster
Commit d528e71c3db accidentally forgot to add tokens to output file

Fixup some miscellaneous answer files

---

gpdb-doc/dita/admin_guide/managing/gptransfer.xml

reworded one of the prerequisites bullets to clarify distinction between segment hosts vs segment instances

docs - clarifying hosts vs instances in prerequisites

---

gpdb-doc/dita/ref_guide/system_catalogs/gp_expansion_tables.xml

minor correction to status value; FINISHED -> COMPLETED

docs - correct a gpexpand status value

---

src/backend/cdb/cdbsubselect.c
src/test/regress/expected/subselect_gp.out
src/test/regress/expected/subselect_gp_optimizer.out
src/test/regress/sql/subselect_gp.sql

Same as PR #9096 on master. I opened this PR just to run the concourse pipeline on it.

Don't pull up aggregate subquery with LIMIT. (5X_STABLE)

---

src/backend/executor/execMain.c

Fix a bug of assign relation oid to relfilenode

---

src/backend/cdb/cdbpath.c
src/backend/cdb/cdbpathlocus.c
src/backend/cdb/cdbpullup.c
src/backend/optimizer/path/pathkeys.c
src/include/cdb/cdbpullup.h
src/test/regress/expected/bfv_joins.out
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/sql/bfv_joins.sql

This is a fix for github issue 8918. It's not complete, need to add tests, and there are a few things I'd like to check with this before it's ready

Fix for issue 8918

---

src/backend/cdb/cdbpath.c
src/backend/cdb/cdbpathlocus.c
src/backend/cdb/cdbpullup.c
src/backend/optimizer/path/pathkeys.c
src/include/cdb/cdbpullup.h
src/test/regress/expected/bfv_joins.out
src/test/regress/expected/bfv_joins_optimizer.out
src/test/regress/sql/bfv_joins.sql

Backported from master commit b852c2b68c1775b8a4ffe47582dd722eb48f5eea.

Fix bugs in choosing compatible hash distributions in join. (6X_STABLE)

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Also make minor interface changes needed for ORCA version 3.84.

Bump ORCA version to 3.85, add ICG tests for ORCA with gpexpand

---

gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml
gpdb-doc/dita/utility_guide/ref/gpbackup_manager.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

Add gpbackup_manager reference.
All of this content is conditionalized because it is unavailble in opensource GPDB.

Add password encryption parameters to ddboost config file.

---

gpdb-doc/dita/admin_guide/intro/about_statistics.xml
gpdb-doc/dita/utility_guide/ref/analyzedb.xml

Updates to deprecate the option.
dev commit - https://github.com/greenplum-db/gpdb/commit/1ac37fef32d0ab7bec70a

docs - deprecate analyzedb option --skip_root_stats - 6X

---

gpcontrib/pxf/src/pxffragment.c
gpcontrib/pxf/test/pxffragment_test.c

PXF relies on getDistributedTransactionId() to distribute load among
segments. This is important when the fragmentation call returns a small
list of fragments. Recently, the behavior of
getDistributedTransactionId() changed, and it no longer returns a value
for SELECT queries. As an alternative, we will use a combination of the
session id and the command count to balance the load on PXF.

PXF: Do not rely on getDistributedTransactionId()

---

gpdb-doc/dita/admin_guide/managing/backup-plugin-api.xml
gpdb-doc/dita/admin_guide/managing/backup.ditamap
gpdb-doc/dita/admin_guide/managing/plugin_api/delete_backup.xml
gpdb-doc/dita/admin_guide/managing/plugin_api/plugin_api_version.xml
gpdb-doc/dita/utility_guide/ref/gpbackup_manager.xml

Add delete_backup reference topic to the gpbackup/restore plugin API docs
Update API version to 0.4.0

Add delete backup to gpbackup plugin api

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to v3.86.0

---

gpdb-doc/dita/utility_guide/ref/gpfdist.xml

docs - gpfdist uncompreses data on the fly.

---

contrib/pg_upgrade/info.c
contrib/pg_upgrade/info_gp.c
contrib/pg_upgrade/info_gp.h
contrib/pg_upgrade/test/integration/scripts/upgrade-cluster.c
contrib/pg_upgrade/test/unit/info_gp_test.c

This was causing build failures, so I'm going to merge quickly.

Return default value for tablespace path when no tablespace file given.

---

gpdb-doc/dita/admin_guide/intro/about_statistics.xml
gpdb-doc/dita/ref_guide/sql_commands/ANALYZE.xml
gpdb-doc/dita/utility_guide/ref/analyzedb.xml

dev PR https://github.com/greenplum-db/gpdb/pull/8985

docs - remove analyzedb option --skip_root_stats - 7.x

---

src/backend/access/transam/xlog.c
src/backend/cdb/cdbappendonlystoragewrite.c
src/backend/cdb/cdbappendonlyxlog.c
src/backend/postmaster/checkpointer.c
src/backend/postmaster/test/checkpointer_test.c
src/backend/storage/smgr/md.c
src/include/access/aomd.h
src/include/postmaster/bgwriter.h
src/include/storage/smgr.h
src/test/isolation2/expected/fsync_ao.out
src/test/isolation2/isolation2_schedule
src/test/isolation2/sql/fsync_ao.sql

This is a back port of PR #9201.  It is a cherry-pick with some trivial conflicts in md.c.  Once the PR pipeline is green, I will merge it.

6X back port: Delay fsync on mirror 

---

src/backend/utils/adt/selfuncs.c

The code to fetch the largest partition's statistics was broken in the
9.6 merge. Fix it.
There are no regression tests for
gp_statistics_pullup_from_child_partition=on, but the codepath where the
parent has no statistics is exercised by existing tests. I guess that's
enough for now. (I still feel that we should probably get rid of this
altogether, as I mentioned in the old comment, but that's a different
story.)

Fix gp_statistics_pullup_from_child_partition.

---

src/bin/gpfdist/gpfdist.c

Print errno and message if local_send() fails.
Print detail information on session end

Enhance gpfdist error log

---

src/test/regress/expected/DML_over_joins.out
src/test/regress/expected/gp_explain_optimizer.out

This pr is to repair the broken pipeline by commit d525474047757865f88a2f0d6d8e43837e15f70d

fix the plan on answer file in tests dml_over_joins and gp_explain

---

src/include/cdb/cdbtm.h

Remove duplicate declaration, already declared at line 268

Remove duplicate declaration, already declared at line 268

---

src/backend/access/common/tupconvert.c
src/backend/cdb/cdbpartindex.c
src/backend/cdb/cdbpartition.c
src/backend/commands/analyze.c
src/backend/commands/copy.c
src/backend/commands/indexcmds.c
src/backend/commands/tablecmds.c
src/backend/executor/execDML.c
src/backend/executor/execMain.c
src/backend/executor/execQual.c
src/backend/executor/nodeModifyTable.c
src/include/access/tupconvert.h
src/include/commands/tablecmds.h
src/include/executor/execDML.h
src/include/executor/executor.h
src/include/nodes/execnodes.h
src/pl/plpgsql/src/pl_exec.c
src/test/regress/expected/partition.out
src/test/regress/expected/partition_optimizer.out

To reduce the diff vs upstream a tiny bit. See commit messages for details.

Minor refactoring to partition-related code.

---

src/backend/commands/matview.c

019-12-04 23:16:23.075209 CST,"gpadmin","regression",p30552,th-790954624,"[local]",,2019-12-04 23:16:03 CST,8192,con143,cmd54,seg-1,,,x8192,sx1,"ERROR","XX000","unrecognized node type: 0 (copyfuncs.c:6424)",,,,,,"REFRESH MATERIALIZED VIEW m_aocs WITH NO DATA;",0,,"copyfuncs.c",6273,"Stack trace:
1    0xaf1f9c postgres errstart (elog.c:561)
2    0xaf4b83 postgres elog_finish (elog.c:1734)
3    0x7b15f7 postgres copyObject (copyfuncs.c:6424)
4    0x6c6ad1 postgres ExecRefreshMatView (matview.c:409)
5    0x997841 postgres <symbol not found> (utility.c:1743)
6    0x9969f4 postgres standard_ProcessUtility (utility.c:1071)
7    0x993bc5 postgres <symbol not found> (palloc.h:176)
8    0x9945c5 postgres <symbol not found> (pquery.c:1552)
9    0x995a21 postgres PortalRun (pquery.c:1022)
10 …

Fix dangling pointer issue when refreshing a matview relation(#9273)

---

src/backend/storage/buffer/bufmgr.c

It even can not compile now. This is a useful debugging feature I think.

memory protection via mprotect() is broken.

---

src/test/isolation2/expected/modify_table_data_corrupt.out
src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
src/test/isolation2/sql/modify_table_data_corrupt.sql

When @paul-guo- review the pr https://github.com/greenplum-db/gpdb/pull/9332 (for 6x),
he points out this typo.
Then I check master, also find this. Open this pr to fix.

Fix typo in the test cases.

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to 3.87.0

---

src/backend/utils/mmgr/redzone_handler.c

Quick fix to pass the compile.

Fix typo of InvalidOid

---

src/backend/storage/smgr/md.c

Backport below commit from postgres to gpdb 5X:
commit 049469e7e7cfe0c69d30385952e2576b63230283
Author: Robert Haas <rhaas@postgresql.org>
Date:   Tue Dec 15 13:57:45 2015 -0500
Teach mdnblocks() not to create zero-length files.
It's entirely surprising that mdnblocks() has the side effect of
creating new files on disk, so let's make it not do that.  One
consequence of the old behavior is that, if running on a damaged
cluster that is missing a file, mdnblocks() can recreate the file
and allow a subsequent _mdfd_getseg() for a higher segment to succeed.
This happens because, while mdnblocks() stops when it finds a segment
that is shorter than 1GB, _mdfd_getseg() has no such check, and thus
the empty file created by mdnblocks() can allow it to continue its
traversal and find higher-numbered …

Teach mdnblocks() not to create zero-length files.

---

src/backend/access/transam/distributedlog.c

DistributedLog_AdvanceOldestXmin is a hot function which hold DistributedLogControlLock
in LW_EXCLUSIVE mode during the whole lifecycle.
This lock is used to protected:
1. DistributedLogShared->oldestXmin
2. DistributedLogCtl->shared->page_buffer
The first one could be optimized using atomic operation.
The second one could be optmized using LW_SHARED mode.

Backport 6X: Optimize DistributedLogControlLock in DistributedLog_AdvanceOldestXmin

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA version to v3.88.0

---

contrib/pg_upgrade/greenplum/check_gp.c

Update comment grammar

---

gpdb-doc/dita/ref_guide/extensions/pl_container.xml

Also some other minor updates and fixed

docs - add python3 information PL/Container configuration example

---

gpdb-doc/dita/admin_guide/managing/backup-ddboost-plugin.xml
gpdb-doc/dita/admin_guide/managing/backup.ditamap
gpdb-doc/dita/admin_guide/managing/replication-ddb.xml

--move replication info. into separate topic.
--update toc
Link to new topic in temporary review doc site.
http://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/managing/replication-ddb.html

reorganize ddboost replication information.

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp
src/backend/gpopt/translate/CTranslatorUtils.cpp
src/include/gpopt/gpdbwrappers.h
src/include/gpopt/translate/CTranslatorScalarToDXL.h
src/include/utils/builtins.h

Better cardinality estimation for citext in ORCA

---

gpdb-doc/dita/analytics/madlib.xml
gpdb-doc/dita/analytics/overview.xml
gpdb-doc/dita/analytics/text.xml

Various small fixes to reorganized analytics topics.

Docs analytics fixes

---

src/backend/commands/copy.c
src/backend/utils/misc/guc_gp.c
src/include/commands/copy.h
src/include/utils/sync_guc_name.h
src/test/regress/expected/gpcopy_dispatch.out
src/test/regress/greenplum_schedule
src/test/regress/output/sreh.source
src/test/regress/sql/gpcopy_dispatch.sql

This is 6X_STABLE backport of fixes done in PR https://github.com/greenplum-db/gpdb/pull/9241 for master. Only additional commit here is to revert the revert done before for commit "Only parse enough of each COPY row, to compute which segment to send it to." This PR is purely for running PR pipeline purpose and then will be merged to 6X_STABLE branch.

[6X] Assorted Fixes Following PR #9085

---

src/backend/access/transam/xloginsert.c
src/backend/access/transam/xlogreader.c

With postgres 9.5 merge GPDB got the capability to compress the full
page images or backup blocks in wal. But given pg_lz is not great and
zstd is better compression algorithm, use zstd instead of pg_lz to
compress the FPI in GPDB.
Just to give a data point, 6000MB of total wal is created on each
segment for ICG. With wal compression enabled, approximately by 700MB
wal size gets reduced for each segment.

Use zstd for wal_compression

---

gpMgmt/bin/gppylib/operations/package.py

1. When two gppkg packages have the same dependencies, gppkg utility
will refuse to install the second gppkg package and throw an error.
This patch fixes this issue and the second gppkg package can install
successfully.
2. Fix install/uninstall issue if the master and standby master use the
same node address.
This PR has first proposed in https://github.com/greenplum-db/gpdb/pull/9494 for 6X_STABLE branch. As discussed in that PR, we propose this patch in the master branch first. This patch is a quick solution to solve two gppkg dependencies conflict (two packages contains the same dependency with the same version). If a conflict happened, this patch will overwrite the previous gppkg dependencies. Only the rpm (centos/Redhat) has this issue due to the historical problem, and deb (ubuntu) …

Fix dependencies issue in GPPKG utility

---

gpMgmt/bin/gppylib/operations/package.py

1. When two gppkg packages have the same dependencies, gppkg utility
will refuse to install the second gppkg package and throw an error.
This patch fixes this issue and the second gppkg package can install
successfully.
2. Fix install/uninstall issue if the master and standby master use the
same node address.
PS: This patch is different from the fix in 5X_STABLE branch

Fix dependencies issue in GPPKG utility (6X_STABLE)

---

gpdb-doc/dita/admin_guide/managing/backup-gpbackup-incremental.xml
gpdb-doc/dita/admin_guide/managing/backup-gpbackup.xml
gpdb-doc/dita/utility_guide/ref/gpbackup.xml
gpdb-doc/dita/utility_guide/ref/gprestore.xml

Synch. docs with backup/restore 1.17

docs - update backup/restore docs

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/config/CConfigParamMapping.cpp
src/backend/utils/misc/guc_gp.c
src/include/utils/guc.h

Ths commit also ports DPv2 to 5X

Bump ORCA version to v3.93.0

---

gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/dita/analytics/overview.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

misc edits and conditionalization of some docs cross-references

docs - fix some xrefs and conditionalize

---

gpMgmt/bin/gpload.py

Add max_retries flag for gpload. It indicates the max times on connecting to GPDB timed out. 
max_retries default value is 0 which means no retry.
If max_retries is -1 or other negative value, it means retry forever. 
Test has been done manually.

Add max_retries flag for gpload

---

src/backend/replication/basebackup.c
src/bin/pg_basebackup/pg_basebackup.c
src/bin/pg_basebackup/t/010_pg_basebackup.pl

This PR contains below two optimizations:
The pg_basebackup command supports the --exclude option to exclude a
path name, it can be provided multiple times to exclude multiple path
names.  However it can be provided at most 255 times, the limit is
hard-coded in the source code because it is internall a fix-sized string
array.
To support excluding more path names, we could enlarge this number,
however there is still limits on the cmdline size or the argument count.
So we now provide a new option, --exclude-from=FILE, to get the path
names to exclude from a file.
The replication basebackup command supports excluding path names with
the EXCLUDE clause, the excluding list used to be stored internally as a
string list and be matched one by one, this can be very inefficient when
the excluding …

basebackup: optimize for large exclude list

---

src/test/regress/expected/join_gp.out
src/test/regress/expected/join_gp_optimizer.out
src/test/regress/sql/join_gp.sql

Fix expect file for test 'join_gp'

---

src/backend/nodes/copyfuncs.c

Fix multi-dqa query failed in cursor

---

src/backend/cdb/cdbpathlocus.c

Function `cdbpathlocus_for_insert` is only invoked by
`create_motion_path_for_insert` and `create_split_update_path`.
Besides, the invokation of `cdbpathlocus_for_insert` is
always under a condition branch with policy type partitioned.
So this commit refactors `cdbpathlocus_for_insert` to add
Assert in it.
-------------------------------
Do not add test cases because current test suites should cover it.

Minor refactor of cdbpathlocus_for_insert.

---

gpdb-doc/dita/admin_guide/query/topics/functions-operators.xml
gpdb-doc/dita/ref_guide/sql_commands/ALTER_FUNCTION.xml
gpdb-doc/dita/ref_guide/sql_commands/CREATE_FUNCTION.xml

Updated
CREATE FUNCTION
ALTER FUNCTION
Using Functions and Operators
HTML output on temporary GPDB doc review site
https://docs-msk-gpdb6-dev.cfapps.io/7-0/ref_guide/sql_commands/CREATE_FUNCTION.html
https://docs-msk-gpdb6-dev.cfapps.io/7-0/ref_guide/sql_commands/ALTER_FUNCTION.html
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/query/topics/functions-operators.html

docs - CREATE FUNCTION - new attribute EXECUTE ON INITPLAN

---

gpdb-doc/dita/admin_guide/external/g-s3-protocol.xml

Will be backported to 6X_STABLE

docs - add deflate support for s3 protocol

---

src/backend/storage/lmgr/proc.c

[6x backport]Allocate and zero out the memory of MyTmGxactLocal

---

src/backend/storage/ipc/procarray.c
src/test/isolation2/expected/concurrent_update.out
src/test/isolation2/sql/concurrent_update.sql

Fix a bug in LocalXidGetDistributedXid

---

src/bin/gpfdist/regress/.gitignore
src/bin/gpfdist/regress/Makefile
src/bin/gpfdist/regress/change_client_cert.bash
src/bin/gpfdist/regress/gen_multiCA_certs.bash
src/bin/gpfdist/regress/input/gpfdists_multiCA.source
src/bin/gpfdist/regress/output/gpfdists_multiCA.source

* Add 2 level multiple CA test cases for gpfdist SSL
* Fix output file due to foreign table modification

Enable and enhance gpfdist SSL test cases

---

gpMgmt/bin/Makefile
gpMgmt/bin/gpinitsystem
gpMgmt/bin/lib/gp_bash_functions.sh
gpMgmt/bin/test/gpinitsystem_test.bash
gpMgmt/bin/test/suite.bash

See commit message for details.

Backport to 5x: Fix gpinitsystem when setting password for numeric username

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/test/regress/expected/direct_dispatch_optimizer.out
src/test/regress/expected/qp_targeted_dispatch.out
src/test/regress/expected/qp_targeted_dispatch_optimizer.out
src/test/regress/sql/direct_dispatch.sql
src/test/regress/sql/qp_targeted_dispatch.sql

Bump ORCA version to v3.95.0

---

src/backend/access/transam/xlog.c

Fix memory leak in checkpointer process.

---

src/backend/cdb/cdbgroupingpaths.c
src/test/regress/expected/bfv_olap.out
src/test/regress/sql/bfv_olap.sql

Fixes github issue https://github.com/greenplum-db/gpdb/issues/9760

Fix assertion failure with two-stage agg, ROLLUP and HAVING.

---

gpdb-doc/markdown/pxf/intro_pxf.html.md.erb

docs - update pxf supported platforms for v5.11

---

gpcontrib/gp_replica_check/gp_replica_check.c

Skip comparison for bulk-extended pages in gp_replica_check.
This fixes a flaky gp_replica_check test. PG supports block bulk-extend. In
such case some pages are extended, initialized but not xlogged. On mirror those
pages are just zero filled so we'd skip comparison for these pages in
gp_replica_check.
Note the related upstream patch is:
commit 719c84c1be51f3d3fe6049b77ddbaa0c4b58a9a9
Author: Robert Haas <rhaas@postgresql.org>
Date:   Fri Apr 8 02:04:46 2016 -0400
Extend relations multiple blocks at a time to improve scalability.
Co-authored-by: Hao Wu <gfphoenix78@gmail.com>

Skip comparison for bulk-extended pages in gp_replica_check.

---

contrib/pg_upgrade/greenplum/frozenxids_gp.c

Escape database name to be used in where clause

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA to v3.97.0

---

gpdb-doc/dita/admin_guide/client_auth.xml

clarified/enhanced SSL configuration information.
This will be backported to 6X_STABLE and 5X_STABLE
Link to the HTML output on a temporary GPDB doc review site.
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/client_auth.html#topic5

docs - updates to Encrypting Client/Server Connections

---

src/backend/utils/resgroup/resgroup.c

Set ps status when transaction is queuing on resource group

---

src/backend/utils/misc/guc_gp.c

Use gpconfig set gp_resource_group_queuing_timeout

---

src/backend/utils/resgroup/resgroup.c

[6X backport] Set ps status when transaction is queuing on resource group

---

src/backend/access/transam/distributedlog.c

The shared oldestXmin (DistributedLogShared->oldestXmin) may be updated
concurrently. It should be set to a higher value, because a higher xmin
can belong to another distributed log segment, its older segments might
already be truncated.
For Example: txA and txB call DistributedLog_AdvanceOldestXmin concurrently.
```
txA and txB: both hold shared DistributedLogTruncateLock.
txA: set the DistributedLogShared->oldestXmin to XminA. TransactionIdToSegment(XminA) = 0009
txB: set the DistributedLogShared->oldestXmin to XminB. TransactionIdToSegment(XminB) = 0008
txA: truncate segment 0008, 0007...
After that, DistributedLogShared->oldestXmin == XminB, it is on removed segment 0008.
```
Subsequent GetSnapshotData() calls will be failed because SimpleLruReadPage will error out.

Fix a bug when setting DistributedLogShared->oldestXmin

---

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap

in this PR:
- add reference for new guc gp_resource_group_queuing_timeout; add to appropriate guc category and subnavs
- update the main "using resource groups" topic to mention this new guc
- misc edit to a subtopic title on the using page

docs - add content for new gp_resource_group_queuing_timeout guc

---

src/backend/access/transam/distributedlog.c

The shared oldestXmin (DistributedLogShared->oldestXmin) may be updated
concurrently. It should be set to a higher value, because a higher xmin
can belong to another distributed log segment, its older segments might
already be truncated.
For Example: txA and txB call DistributedLog_AdvanceOldestXmin concurrently.
```
txA and txB: both hold shared DistributedLogTruncateLock.
txA: set the DistributedLogShared->oldestXmin to XminA. TransactionIdToSegment(XminA) = 0009
txB: set the DistributedLogShared->oldestXmin to XminB. TransactionIdToSegment(XminB) = 0008
txA: truncate segment 0008, 0007...
```
After that, DistributedLogShared->oldestXmin == XminB, it is on removed
segment 0008. Subsequent GetSnapshotData() calls will be failed because SimpleLruReadPage will error out.

[6X backport]Fix a bug when setting DistributedLogShared->oldestXmin

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Bump ORCA to v3.101.0

---

src/tools/docker/centos6/Dockerfile
src/tools/docker/centos7/Dockerfile

since former is no longer available in the upstream repo

Dockerfile: Update centos devtoolset-6 to devtoolset-7

---

gpdb-doc/dita/admin_guide/ddl/ddl-view-best-practices.xml
gpdb-doc/dita/admin_guide/ddl/ddl-view-find-depend.xml
gpdb-doc/dita/admin_guide/ddl/ddl-view-storage.xml
gpdb-doc/dita/admin_guide/ddl/ddl-view.dita
gpdb-doc/dita/admin_guide/ddl/ddl.ditamap

-example queries to find dependency information
-catalog table information
-best practices
This will be backported to 6X_STABLE and 5X_STABLE
Link to HTML output on a temporary GPDB draft doc website
Creating and Managing Views
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/ddl/ddl-view.html
Working with View Dependencies - Example Queries
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/ddl/ddl-view-find-depend.html
Best Practices
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/ddl/ddl-view-best-practices.html
About View Storage in Greenplum Database
https://docs-msk-gpdb6-dev.cfapps.io/7-0/admin_guide/ddl/ddl-view-storage.html

docs - add information about view dependency

---

src/test/isolation2/helpers/server_helpers.sql

Currently this UDF might report a false positive if the node is still starting
up after timeout since currently pg_ctl returns 0 for this case. This behavior
is changed in upstream with the below patch:
commit f13ea95f9e473a43ee4e1baeb94daaf83535d37c
Date:   Wed Jun 28 17:31:24 2017 -0400
Change pg_ctl to detect server-ready by watching status in postmaster.pid.
We've seen some test flakiness due to this issue since pg_ctl restart needs
more time sometimes on pipeline (by default pg_ctl timeout is 60 seconds).
Yesterday I found on a hang job that a primary needs ~ 4 minutes to get the
recovery finished during 'pg_ctl restart' (It's test
ao_same_trans_truncate_crash which enables fsync. Even it launches a checkpoint
before pg_ctl restart, pg_ctl …

Enlarge timeout in isolation2:pg_ctl UDF

---

src/backend/cdb/motion/ic_tcp.c

flushBuffer() is used to send packets through TCP interconnect, before
sending, it first check whether receiver stopped or teared down the
interconnect, however, there is window between checking and sending, the
receiver may tear down the interconnect and close the peer, so send()
will report an error, to resolve this, we recheck whether the receiver
stopped or teared down the interconnect in this window and don't error
out in that case.

Fix a race condition in flushBuffer

---

src/backend/utils/resscheduler/resqueue.c

When ResLockAcquire errors out after proclock is allocated and before the lock
is granted, the 'holdMask' and 'nLocks' of proclock are 0, it should be removed
properly in ResLockRelease.

Fix a resource queue lock issue

---

src/backend/utils/misc/faultinjector.c

Fix a spinlock leak for fault injector

---

src/backend/utils/gp/segadmin.c

This problem partially fixed in #8012
However, these changes do not take into account the lock mode of nested functions
for gp_add_segment_mirror (add_segment_config, add_segment_config_entry,
get_availableDbId). This functions still require AccessExclusiveLock mode.
Catalog changes are proccess in single transaction for ALL segments so this mode
will be held until transaction commit. So we may get deadlock if we will be restore
multiple segments for cluster with large persistent tables, which will require updating
the catalog more than 30 * 2 (DISPATCH_WAIT_TIMEOUT_MSEC) seconds.
In general, any update catalog operations requiring dispatch may cause deadlock with FTS.
So fixed gp_add_master_standby too.
gp_add_segment does not dispatch, but is performed in one transaction with the update …

fix possible deadlocks between catalog update and FTS

---

src/backend/access/transam/xact.c
src/backend/storage/ipc/procarray.c
src/backend/storage/ipc/procsignal.c
src/backend/storage/lmgr/proc.c
src/backend/utils/resgroup/resgroup.c
src/backend/utils/resgroup/resgroup_helper.c
src/include/catalog/pg_proc_gp.h
src/include/storage/proc.h
src/include/storage/procarray.h
src/include/storage/procsignal.h
src/include/utils/builtins.h
src/include/utils/resgroup.h
src/test/isolation2/isolation2_resgroup_schedule

select pg_resgroup_move_query(pid, groupid);

 Move a query to a resource group

---

concourse/scripts/compile_gpdb.bash
gpAux/Makefile

172362931 set correct runpath for plpython

---

src/backend/executor/nodeAgg.c

Account for transvalue in combine function in the mpool
We found that two-stage hashagg wasn't spilling early enough in the
final aggregate. This was because the transvalue wasn't being accounted
for in nodeAgg. This sometimes results in 200x under-counting. Since we
base our spilling decisions on the mpool's accounting, this commit is
necessary. This seems to be an oversight in commit 38d88155520 (9.6
merge commit). What happend in the merge is:
advance_combine_function() was never used in 6X, instead
invoke_agg_trans_func() was used and which used datumCopyWithMemManager().
When we started calling advance_combine_function() in the 9_6 merge
instead, we didn't adapt it to use datumCopyWithMemManager().
Since we also intend to backport upstream's disk-based hashagg
implementation into …

Account for transvalue in combine function in the mpool

---

gpdb-doc/dita/utility_guide/ref/gpstart.xml

This will be backported to 6X_STABLE and 5X_STABLE

docs - update for gpstart when standby master is not available

---

gpAux/Makefile

Authored-by: Shaoqi Bai <sbai@pivotal.io>

[backported to 5X]Recompile plpython subdir to set the right RUNPATH

---

src/backend/utils/misc/faultinjector.c

[6X backport] Fix a fault injector spinlock leak problem

---

src/test/isolation2/input/resgroup/resgroup_move_query.source
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/output/resgroup/resgroup_move_query.source

Add test for resource group move query

---

src/backend/utils/resgroup/resgroup_helper.c
src/test/isolation2/input/resgroup/resgroup_move_query.source
src/test/isolation2/output/resgroup/resgroup_move_query.source

Minor fix in resource gorup move query

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

docs - update max value for max_connections - 6.x

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml

docs - fix max value for max_connections 5.x

---

gpMgmt/bin/gpexpand
gpMgmt/bin/gppylib/commands/gp.py
gpMgmt/bin/gppylib/commands/pg.py
gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

Retire #9551 to fix the broken gpexpand master pipeline.

gpexpand: retire the optimization of #9551

---

gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

update the version in some links

docs - update some xrefs

---

gpdb-doc/dita/utility_guide/ref/gpsys.xml
gpdb-doc/dita/utility_guide/utility-programs.xml

Also uncommented gpmovemirrors from table of uitlities.
Doc update for gpsys1 removal on master - Dev PR https://github.com/greenplum-db/gpdb/pull/10099

docs - deprecate gpsys1

---

concourse/pipelines/gen_pipeline.py
concourse/pipelines/templates/gpdb-tpl.yml
concourse/scripts/drop_functions_with_dependencies_not_shipped_to_customers.sql
concourse/scripts/dumpdb.bash
concourse/scripts/ic_gpdb.bash
concourse/tasks/ic_gpdb_binary_swap.yml

Dump 5X ICW in the icw_planner_centos6 job
Dump into a gcp bucket since downstream consumers have mostly migrated to gcp.

Add 5X ICW dump

---

src/backend/cdb/motion/ic_tcp.c

This is mainly to resolve slow response to sequence requests under
TCP interconnect, sequence requests are sent through libpqs from
QEs to QD (we call them dispatcher connections). In the past, under
TCP interconnect, QD checked the events on dispatcher connections
every 2 seconds, obviously it's inefficient.
Under UDPIFC mode, QD also monitors the dispatcher connections when
receving tuples from QEs so QD can process sequence requests in
time, this commit applies the same logic to the TCP interconnect.
Reviewed-by: Hao Wu <gfphoenix78@gmail.com>

[ 6X backport]Monitor dispatcher connection when receiving from TCP interconnect

---

src/backend/gpopt/utils/COptTasks.cpp
src/backend/gporca/libgpos/include/gpos/_api.h
src/backend/gporca/libgpos/src/_api.cpp
src/backend/optimizer/plan/orca.c

This is a continuation of commit 456b2b3 in GPORCA. Adding more errors to the list that
doesn't get logged in log file.

Log fewer errors

---

src/backend/cdb/motion/cdbmotion.c

processIncomingChunks() receives a list of chunks from a one sender, and
then calls addChunkToSorter() on each chunk. addChunkToSorter() looks up
some things based on the sender. But since all the chunks came from the
same sender, we can move the lookups to outside of the loop and save some
overhead.

Optimize some code in the receiving side of a Motion.

---

src/backend/commands/matview.c

In REFRESH MATERIALIZED VIEW command, CONCURRENTLY option is only
allowed if there is at least one unique index with no WHERE clause on
one or more columns of the matview. Previously, concurrent refresh
checked the existence of a unique index on the matview after filling
the data to new snapshot, i.e., after calling refresh_matview_datafill().
So, when there was no unique index, we could need to wait a long time
before we detected that and got the error. It was a waste of time.
To eliminate such wasting time, this commit changes concurrent refresh
so that it checks the existence of a unique index at the beginning of
the refresh operation, i.e., before starting any time-consuming jobs.
If CONCURRENTLY option is not allowed due to lack of a unique index,
concurrent refresh can immediately …

Make concurrent refresh check early on matview

---

.gitmodules

Upgrade pgbouncer to 1.13

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query39.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

Add "FILL_MISSING_FIELDS" option for gpload.

---

src/backend/cdb/motion/ic_tcp.c

Previously, the result of select() system call and errno set by it was checked after performing several function calls, including checking for interrupts and checkForCancelFromQD.  That made it very likely for errno to change, losing the original value that was set by the
select().
This patch fixes it so that the errno is checked immediately after the system call.  This should address intermittent failures in CI with error message like this:
```
ERROR","58M01","interconnect error: select: Success"
```

Check errno as early as possible

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

The corresponding Orca PRs are
- https://github.com/greenplum-db/gporca/pull/590
- https://github.com/greenplum-db/gporca/pull/588

Bump Orca version to 3.105

---

src/backend/utils/adt/lockfuncs.c

The logic with 'whichrow' and 'whichresultset' introduced in commit
991273b2b3 was slightly wrong. The last row (or first? not sure) of each
result set was returned twice, and the corresponding number of rows at the
end of the last result set were omitted.
For example:
```
postgres=# select gp_segment_id, * from pg_locks;
gp_segment_id |  locktype  | database | relation | page | tuple | virtualxid | transactionid | classid | objid | objsubid | virtualtransaction |  pid  |      mode       | granted | fastpath | mppsessionid | mppiswriter | gp_segment_id
---------------+------------+----------+----------+------+-------+------------+---------------+---------+-------+----------+--------------------+-------+-----------------+---------+----------+--------------+-------------+---------------
-1 …
```

Fix the logic in pg_lock_status() to keep track of which row to return.

---

src/test/regress/expected/matview_ao.out
src/test/regress/sql/matview_ao.sql

This patch will create a test role to exec the test.
Related-Issues: https://github.com/greenplum-db/gpdb/issues/10198

Fix user specify in matview_ao test

---

gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/dita/analytics/overview.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/install_guide/upgrading.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

update some links and upgrade info

docs - update some xrefs and upgrade info

---

src/test/regress/expected/gporca_optimizer.out

Updating an expected output file that we missed.

Fix expected output from 4847e31

---

gpdb-doc/dita/admin_guide/highavail/topics/g-enabling-high-availability-features.xml
gpdb-doc/dita/admin_guide/intro/about_ha.xml
gpdb-doc/dita/install_guide/prep_os.xml

Tone down mirroring support statement; add k8s info.

Update statement about mirroring recommendations & support

---

src/test/isolation2/expected/segwalrep/recoverseg_from_file.out
src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql

Need to wait until the cluster is synchronized after gprecoverseg before
running subsequent tests.

Fix flaky test recoverseg_from_file

---

gpdb-doc/dita/install_guide/init_gpdb.xml

Add a new line feed and fix a bad file name

---

src/backend/commands/tablespace.c
src/test/regress/input/gp_tablespace.source
src/test/regress/output/gp_tablespace.source

If the directory of tablespace does not exist, we should got a
error on commit transaction. But error on commit transaction will
cause a panic. So the directory of tablespace should be checked
so that we can avoid panic.

Check whether the directory exists when deleting the tablespace

---

NOTICE
README.amazon_linux
README.docker.md
README.ubuntu.bash
concourse/scripts/combine_cli_coverage.bash
gpMgmt/Makefile
gpMgmt/bin/Makefile
gpMgmt/bin/gpmovemirrors
gpMgmt/bin/gppylib/mainUtils.py
gpMgmt/bin/gppylib/programs/clsRecoverSegment.py
gpMgmt/bin/gppylib/test/unit/test_unit_mainUtils.py
python-dependencies.txt
src/tools/docker/centos6/Dockerfile
src/tools/docker/centos7/Dockerfile
src/tools/docker/ubuntu/Dockerfile

[Lockfile](https://pypi.org/project/lockfile/) has not been maintained
since around 2015. Further, the functionality it provided seems poor - a
review of the code indicated that it used the presence of the PID file
itself as the lock - in Unix, using a file's existence followed by a
creation is not atomic, so a lock could be prone to race conditions.
The lockfile package also did not clean up after itself - a process
which was destroyed unexpectedly would not clear the created locks, so
some faulty logic was added to mainUtils.py, which checked to see if a
process with the same PID as the lockfile's creator was running. This
is obviously failure prone, as a new process might be assigned the same
PID as the old lockfile's owner, without actually being the same process.
(Of note, the …

Remove lockfile from mainUtils

---

gpAux/Makefile
gpMgmt/bin/Makefile
gpMgmt/bin/generate-greenplum-path.sh
gpcontrib/quicklz/Makefile

This PR is a _forward-port_ of the changes in PR #10336. See PR comment there and commit messages for more details.

173410713 uprade packaging master

---

gpdb-doc/dita/admin_guide/load/load.ditamap
gpdb-doc/dita/admin_guide/load/topics/g-loading-and-unloading-data.xml
gpdb-doc/dita/analytics/overview.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/install_guide/upgrading.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap

docs - update misc xrefs to new version

---

gpdb-doc/dita/ref_guide/config_params/guc-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
gpdb-doc/dita/utility_guide/ref/gpfdist.xml

Add GUC and add link to GUC in gpfdist reference
Related dev PR #10214
Will be backported to 4.3.x

docs - add GUC -write_to_gpfdist_timeout

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp

This PR is the GPDB side changes related to https://github.com/greenplum-db/gporca/pull/595
It contains only the GPDB side changes which updates function names in the CTranslatorRelCacheToDXL.cpp.

[5X Backport] Improve statistics calculation for exprs like "var = ANY (ARRAY[...])"

---

gpdb-doc/dita/utility_guide/ref/gpload.xml

--Also, add some links to other topics.
related dev PR #10220

docs - add gpload config file parameter fill_missing_fields

---

README.windows.md
concourse/scripts/compile_gpdb_remote_windows.bash
concourse/scripts/compile_gpdb_remote_windows.bat
gpAux/client/install/src/windows/greenplum-clients.wxs
gpMgmt/bin/pythonSrc/PyGreSQL/CMakeLists.txt

- CMakeLists.txt moved to gpMgmt/bin/pythonSrc/PyGreSQL
- Unpack source code from gpMgmt/bin/pythonSrc/ext/PyGreSQL-*.tar.gz
- Add declaration to force dllexport on init_pg
- Remove the pygresql level folder. All files are moved up.

Fix pygresql windows build

---

README.linux.md

Issue #10069 noted some problems with the linux documentation.
Updating this documentation to be more accurate and direct configuration
steps to the appropriate documentation.
Co-authored-by: Tyler Ramer <tramer@vmware.com>
Co-authored-by: Jamie McAtamney <jmcatamney@vmware.com>

Update linux installation guide

---

src/backend/access/transam/xact.c
src/backend/storage/ipc/latch.c
src/backend/storage/ipc/procarray.c
src/backend/utils/time/sharedsnapshot.c

This include two patches. We add the debugging code since we saw such cases in real scenarios and the error message was not helpful.

Add debugging code in latch code & shared snapshot code.

---

src/test/regress/expected/subselect_gp_optimizer.out

Fix subselect_gp_optimizer.out

---

gpdb-doc/dita/analytics/greenplum_r_client.xml

greenplumR functions db.gpapply() and db.gptapply() now take an input.signature argument.  document this and add an example.
doc review site link - scroll to **Example 2**:  http://docs-lisa-greenplumr-inputsig.cfapps.io/7-0/analytics/greenplum_r_client.html#use

docs - greenplumr input.signature

---

src/test/regress/greenplum_schedule

This was missed in commit 96b332c0.

Add mirror_replay test to greenplum_schedule

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Corresponding Orca commit: "Add knowledge of partition selectors to
Orca's DPv2 algorithm"
Also includes commit "Do not allocate MemoryPoolManager from a memory pool "

[5X] Bump Orca version to v3.108.0

---

src/backend/catalog/heap.c
src/backend/commands/analyze.c

Clean identical code in heap.c and analyze.c
No test case needed.

Coverity: Identical code for different branches

---

src/backend/cdb/motion/ic_proxy_client.c

In a query that contains multiple init/sub plans, the packets of the
second subplan might be received while the first is still being
processed in the ic-proxy mode, this is because in ic-proxy mode a local
host handshake is used instead of the global one.
To distinguish the packets of different subplans, especially for the
early coming ones, we must stop handling on the BYE immediately, and
pass any unhandled early coming pkts to the successor or the
placeholder.
This fixes the random hanging during the ICW parallel group of
qp_functions_in_from.  No new test is added.
Co-authored-by: Hubert Zhang <hzhang@pivotal.io>

ic-proxy: handle early coming BYE correctly

---

gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py

conn = dbconn.connect() should be aligned with if statement, or it
will never be executed.

Coverity: Behave test misformat

---

src/backend/cdb/motion/ic_proxy_client.c

In a query that contains multiple init/sub plans, the packets of the
second subplan might be received while the first is still being
processed in the ic-proxy mode, this is because in ic-proxy mode a local
host handshake is used instead of the global one.
To distinguish the packets of different subplans, especially for the
early coming ones, we must stop handling on the BYE immediately, and
pass any unhandled early coming pkts to the successor or the
placeholder.
This fixes the random hanging during the ICW parallel group of
qp_functions_in_from.  No new test is added.
Co-authored-by: Hubert Zhang <hzhang@pivotal.io>
(cherry picked from commit 79ff4e62a8cc34ed0a4996ad6d1b0dbaed3bee4b)
----
This is the 6X backport of #10566.

6X: ic-proxy: handle early coming BYE correctly

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/query39.ans
gpMgmt/bin/gpload_test/gpload2/setup.ans
gpMgmt/bin/gpload_test/gpload2/setup.sql

Add "FILL_MISSING_FIELDS" was reverted due to release plan, now it can be added back for the new release.  
This reverts commit 7118e8aca825b743dd9477d19406fcc06fa53852.

Add "FILL_MISSING_FIELDS" option for gpload."

---

gpdb-doc/dita/admin_guide/external/pxf-overview.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/security-guide/topics/SecuringGPDB.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap
gpdb-doc/markdown/pxf/gphdfs-pxf-migrate.html.md.erb
gpdb-doc/markdown/pxf/migrate_5to6.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb

docs - update pxf xrefs to v5.14

---

gpMgmt/bin/lib/pexpect/__init__.py
gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
src/backend/catalog/heap.c
src/backend/cdb/cdbcopy.c
src/backend/commands/analyze.c
src/backend/commands/exttablecmds.c
src/bin/pg_dump/pg_backup_archiver.c
src/bin/pg_dump/pg_dump.c
src/include/utils/tuplesort.h

See each commit message for which master commit is backported.

[BACKPORT 6X] backport the fix to coverity issues

---

contrib/pgcrypto/internal.c
src/backend/cdb/dispatcher/cdbdisp_async.c
src/backend/cdb/motion/ic_udpifc.c
src/backend/commands/analyze.c
src/backend/commands/analyzeutils.c
src/backend/executor/nodeSplitUpdate.c
src/backend/utils/adt/matrix.c
src/backend/utils/resscheduler/resqueue.c
src/interfaces/libpq/fe-exec.c
src/interfaces/libpq/fe-protocol3.c

Reviewed-by: Heikki Linnakangas <hlinnakangas@pivotal.io>
Reviewed-by: Hao Wu <gfphoenix78@gmail.com>
(cherry picked from commit af0fac1835c67e1bfc4033f3dbf12780f205e6bb)

[6X Backport] coverity: Fix 'unchecked return value' issues. (#10545)

---

src/backend/commands/tablecmds.c

SET DISTRIBUTED BY and EXTEND TABLE subcommands worked differently from
all other ALTER TABLE subcommands in who's responsible for closing the
relcache reference. In all other subcommands, ATRewriteCatalogs opens and
closes the 'rel', but for these two commands, the ATExec*() function
closed it. I don't see any good reason for that. There were very old
comments about forcing the relcache entry to be forgotten, but that
explanation doesn't make sense to me, and everything seems to work without
the early closing. Maybe it was needed a long time ago, but the code has
changed a lot since it was written. Simplify, by closing the relation in
ATRewriteCatalogs(), like with all other ALTER TABLE subcommands.

Simplify responsibility for 'rel' in SET DISTRIBUTED BY and EXTEND TABLE.

---

gpdb-doc/dita/admin_guide/access_db/topics/pgbouncer.xml
gpdb-doc/dita/install_guide/install_gpdb.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/utility_guide/ref/pgbouncer-admin.xml
gpdb-doc/dita/utility_guide/ref/pgbouncer-ini.xml

Merging to 6X_STABLE only per feedback in https://github.com/greenplum-db/gpdb/pull/10595

Docs pgbouncer update 6x

---

gpdb-doc/dita/utility_guide/ref/gpcheckcat.xml

docs for new gpcheckcat test - update gpcheckat ref page

docs - add gpcheckcat aoseg_table test

---

src/backend/storage/lmgr/proc.c
src/backend/utils/resscheduler/resqueue.c

Cleanup idle gangs after releasing lock table's partition lock

---

src/backend/access/external/url_curl.c
src/backend/bootstrap/bootstrap.c
src/backend/commands/functioncmds.c
src/backend/fts/ftsmessagehandler.c

Mainly fixed the file handler issues.
(cherry picked from commit cdc41e2b3ad02cf3fd0de1d7df7e49946cda4544)

6X: Coverity: fix some coverity issues

---

src/bin/initdb/initdb.c
src/bin/pg_basebackup/streamutil.c
src/bin/pg_dump/pg_dump.c

Coverity: Cleanup minor memory leak issue

---

src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out

Correct modify_table_data_corrupt test output for orca.

---

src/backend/commands/copy.c

Fix performance issue, use local variable to replace struct's field access.

---

src/bin/pg_dump/pg_backup_tar.c

```
warning: the use of `tempnam' is dangerous, better use `mkstemp'
```
It is annoying, and could not be suppressed since it's a linker warning.
`-Wno-deprecated-declarations` has no effect, and overriding the
`.gnu.warning.foobar` binary section doesn't work with other compilers.

Get rid of tempnam()

---

src/backend/gporca/README.md
src/backend/gporca/libgpopt/src/mdcache/CMDAccessorUtils.cpp
src/backend/gporca/libgpopt/src/mdcache/CMDCache.cpp
src/backend/gporca/libgpopt/src/minidump/CMinidumperUtils.cpp
src/backend/gporca/libgpos/include/gpos/error/CException.h
src/backend/gporca/libgpos/include/gpos/error/CFSimulator.h
src/backend/gporca/libgpos/include/gpos/io/ioutils.h
src/backend/gporca/libgpos/include/gpos/task/traceflags.h
src/backend/gporca/libgpos/include/gpos/test/CFSimulatorTestExt.h
src/backend/gporca/libgpos/server/CMakeLists.txt
src/backend/gporca/libgpos/src/error/CErrorContext.cpp
src/backend/gporca/libgpos/src/error/CErrorHandlerStandard.cpp
src/backend/gporca/libgpos/src/error/CMessage.cpp
src/backend/gporca/libgpos/src/io/ioutils.cpp
src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
src/backend/gporca/libgpos/src/test/CFSimulatorTestExt.cpp
src/backend/gporca/libgpos/src/test/CUnittest.cpp
src/backend/gporca/libnaucrates/src/traceflags.cpp
src/backend/gporca/server/CMakeLists.txt

Misc GPORCA cleanup

---

gpdb-doc/dita/admin_guide/managing/gpcopy-migrate.xml
gpdb-doc/dita/install_guide/migrate.xml

docs - clarify gpcopy supported greenplum versions

---

src/backend/postmaster/backoff.c

Previous commit ab74e1c, c7befb1 did not completely solve its race
condition, it did not test for last iteration of the while/for loop.
This could result in failed assertion in the following loop. The patch
moves the judgement to the ending of the for loop, it is safe, because
the first iteration will never trigger: Assert(activeWeight > 0.0).
Also, the other one race condition can trigger this assertion
Assert(gl->numFollowersActive > 0). Consider this situation:
Backend A, B belong to the same statement.
Timestamp1: backend A's leader is A, backend B's leader is B.
Timestamp2: backend A's numFollowersActive remains zero due to timeout.
Timestamp3: Sweeper calculates leader B's numFollowersActive to 1.
Timestamp4: backend B changes it's leader to A even if A is inactive.
We stop sweeping …

Fix assertion failures in BackoffSweeper

---

src/backend/cdb/cdbpath.c
src/test/regress/expected/triggers_gp.out
src/test/regress/greenplum_schedule
src/test/regress/sql/triggers_gp.sql

Greenplum doesn't officially support triggers, period. But the behavior
of row-level triggers is actually somewhat sane. Let's add a test file
for those cases, to act as internal documentation on what works and what
doesn't.

Add some tests for row-level triggers.

---

src/backend/cdb/cdbpersistentfilesysobj.c

With a segment whose primary is down and its mirror is promoted to
primary, we run gp_remove_segment_mirror to remove the mirror of
the segment, we see the mirror related fields are cleaned up in
gp_persistent_filespace_node. But when we run gp_remove_segment_mirror
for the same segment again, the primary related fields are also
cleaned up, this is wrong and not expected.

[5X] Fix unexpected corrupt of persistent filespace table

---

gpcontrib/gp_error_handling/Makefile

Fix gp_error_handling makefile

---

src/backend/postmaster/backoff.c

Previous commit ab74e1c6, c7befb1d did not completely solve its race
condition, it did not test for last iteration of the while/for loop.
This could result in failed assertion in the following loop. The patch
moves the judgement to the ending of the for loop, it is safe, because
the first iteration will never trigger: Assert(activeWeight > 0.0).
Also, the other one race condition can trigger this assertion
Assert(gl->numFollowersActive > 0). Consider this situation:
Backend A, B belong to the same statement.
Timestamp1: backend A's leader is A, backend B's leader is B.
Timestamp2: backend A's numFollowersActive remains zero due to timeout.
Timestamp3: Sweeper calculates leader B's numFollowersActive to 1.
Timestamp4: backend B changes it's leader to A even if A is inactive.
We stop …

[Backport 6X]Fix assertion failures in BackoffSweeper

---

src/backend/executor/execHHashagg.c

This backports the fixes to two associated assertion related issues discovered as a part of #9946

5X Backport PR#9946

---

src/backend/cdb/motion/ic_proxy_main.c

Fix compile error for missing brackets

---

src/backend/utils/resgroup/resgroup.c

Correct reset condition in sessionResetSlot

---

src/backend/utils/mmgr/redzone_handler.c
src/backend/utils/resgroup/resgroup.c

Resource group used to access resGroupSlot in SessionState without
lock. This is correct when session only access resGroupSlot by itself.
But as we introduced runaway feature, we need to traverse the current
session array to find the top consumer session when redzone is reached.
This requires:
1. runaway detector should hold shared resgroup lock to avoid resGroupSlot
is detached from a session concurrently when redzone is reached.
2. normal session should hold exclusive lock when modifying resGroupSlot
in SessionState.
Also fix a compile warning.
(cherry picked from commit a4cb06b4005b9a397361d6f678e1db6989972350)

[Backport 6X] Using lwlock to protect resgroup slot in session state

---

src/backend/storage/ipc/procsignal.c
src/test/regress/expected/async.out
src/test/regress/sql/async.sql

This will make LISTEN and NOTIFY work on the QD node.

Handle the PROCSIG_NOTIFY_INTERRUPT signal

---

src/test/isolation2/output/resgroup/resgroup_memory_runaway.source

Fix formatting issue in answer file

---

gpdb-doc/dita/admin_guide/external/pxf-overview.xml
gpdb-doc/dita/install_guide/platform-requirements.xml
gpdb-doc/dita/security-guide/topics/SecuringGPDB.xml
gpdb-doc/dita/utility_guide/utility-programs.xml
gpdb-doc/dita/utility_guide/utility_guide.ditamap
gpdb-doc/markdown/pxf/gphdfs-pxf-migrate.html.md.erb
gpdb-doc/markdown/pxf/migrate_5to6.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb
gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb

update the xrefs to the pxf docset

docs - update pxf xrefs to v5.15

---

concourse/scripts/common.bash
src/backend/cdb/motion/README.ic-proxy.md
src/backend/cdb/motion/ic_proxy_addr.c
src/backend/cdb/motion/ic_proxy_addr.h
src/backend/cdb/motion/ic_proxy_main.c
src/backend/cdb/motion/ic_proxy_peer.c

Reverts greenplum-db/gpdb#10802
It was merged outside the feature merge window, my mad.  I'll resubmit it on the next window.

Revert "6X: ic-proxy: support hostname as proxy addresses"

---

gpMgmt/bin/gpload.py
gpMgmt/bin/gpload_test/gpload2/TEST.py
gpMgmt/bin/gpload_test/gpload2/data/external_file_16.txt
gpMgmt/bin/gpload_test/gpload2/query41.ans

* add double quotations to column names and omit distribution keys when creating staging tables
* add gpload test case

Fix gpload fail when capital letters in column in merge mode 

---

src/backend/catalog/storage_tablespace.c
src/backend/catalog/storage_tablespace_twophase.c
src/backend/catalog/storage_tablespace_xact.c
src/backend/catalog/test/storage_tablespace_test.c
src/backend/cdb/cdbcat.c
src/backend/cdb/cdbgroup.c
src/backend/cdb/cdbpathlocus.c
src/backend/optimizer/util/relnode.c
src/backend/utils/misc/guc_gp.c
src/include/catalog/storage_database.h
src/include/catalog/storage_tablespace.h
src/include/cdb/cdbvars.h
src/include/cdb/ic_proxy_bgworker.h
src/include/gpopt/translate/CTranslatorRelcacheToDXL.h
src/include/nodes/execnodes.h
src/include/optimizer/pathnode.h
src/include/utils/unsync_guc_name.h

Misc little things I've spotted in the last couple of weeks. See commit messages for details.

Misc cleanup

---

src/test/regress/greenplum_schedule
src/test/regress/parallel_schedule

Move truncate_gp test from parallel_schedule to greenplum_schedule

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gporca/data/dxl/minidump/ConstTblGetUnderSubqUnderProjectWithOuterRef.mdp
src/backend/gporca/data/dxl/minidump/ConstTblGetUnderSubqWithOuterRef.mdp
src/backend/gporca/data/dxl/minidump/DQA-KeepOuterReference.mdp
src/backend/gporca/data/dxl/minidump/ExprOnScSubqueryWithOuterRef.mdp
src/backend/gporca/data/dxl/minidump/PartTbl-DPE-Correlated-NLOuter.mdp
src/backend/gporca/data/dxl/minidump/ScSubqueryWithOuterRef.mdp
src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

Port to master of https://github.com/greenplum-db/gpdb/pull/10863.

[master] Project outrrefs in the targetlist of subqueries in ORCA

---

gpcontrib/gp_replica_check/gp_replica_check.py
src/test/unit/mock/mocker.py

As we are decoupling dependency on python2, these dev tools should
also use Python3.

Unit test mock and gp_replica_check script use Python3

---

src/backend/utils/resgroup/resgroup_helper.c
src/include/catalog/pg_proc.dat
src/test/isolation2/expected/resgroup/resgroup_functions.out
src/test/isolation2/isolation2_resgroup_schedule
src/test/isolation2/sql/resgroup/resgroup_functions.sql

Some stats could only be collected on master, update the catalog.

Execute pg_resgroup_get_status() on master

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/test/regress/expected/gporca.out
src/test/regress/expected/gporca_optimizer.out
src/test/regress/sql/gporca.sql

The corresponding ORCA PR is https://github.com/greenplum-db/gporca/pull/605

Bump ORCA version to 3.111.0, add test cases

---

src/backend/parser/parse_partition_gp.c
src/test/regress/expected/partition1.out
src/test/regress/sql/partition1.sql

Use ereport() with proper error code for a couple of user-facing errors.

---

src/backend/gporca/README.md

Update GPORCA README for how to run tests

---

concourse/scripts/separate_qautils_files_for_rc.bash
concourse/tasks/separate_qautils_files_for_rc.yml

The task is being used in the 5X_release pipeline.

Revert deletion of separate_qautils_files_for_rc

---

src/backend/cdb/cdbdtxrecovery.c
src/backend/cdb/cdbvars.c
src/backend/postmaster/bgworker.c
src/backend/storage/ipc/procarray.c
src/backend/tcop/postgres.c
src/backend/utils/misc/guc_gp.c
src/backend/utils/misc/ps_status.c
src/include/cdb/cdbvars.h
src/include/storage/procarray.h
src/include/utils/unsync_guc_name.h
src/test/isolation2/expected/crash_recovery_dtm.out
src/test/isolation2/expected/terminate_in_gang_creation.out
src/test/isolation2/sql/crash_recovery_dtm.sql
src/test/isolation2/sql/terminate_in_gang_creation.sql

Will push it once the pr pipeline is green.

[6x backport] Periodically check and abort orphaned transactions post dtx recovery

---

config/orca.m4
configure
depends/conanfile_orca.txt
gpAux/releng/releng.mk

Corresponding ORCA commit: "Disallow physical index scans in Orca to have predicate condition with subquery"

Bump ORCA version to 3.112.0

---

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/include/gpopt/translate/CTranslatorDXLToPlStmt.h

Port of https://github.com/greenplum-db/gpdb/pull/10971 to 5X.

Increment ExternalScan::scancounter across queries in ORCA

---

gpAux/gpdemo/demo_cluster.sh

demo_cluster.sh: remove GPSEARCH

---

src/backend/access/transam/xlog.c

To allow experimentation of various Postgres recovery features, we
must handle distributed commit WAL records similarly to commit and
commit prepared WAL records. This will allow the standby master
segment to utilize the recovery features. The mirror segments already
get handled since they use the regular commit and commit prepared WAL
records.
With this change, the standby master segment will be able to properly
output a value for a pg_last_xact_replay_timestamp() call (while in
hot standby), have delayed WAL replay, and use PITR/archive recovery
settings such as recovery_target_time and recovery_target_xid.

Handle distributed commit WAL records for various recovery features

---

src/backend/gporca/README.memo.md

While learning basics how to read Orca memos, I did not find any readily
available documentation. This is an attempt to leave something behind for the
next person.
https://github.com/dgkimura/gpdb/blob/memo-readme/src/backend/gporca/README.memo.md

Add README on basics for how to read Orca memos

---

src/backend/commands/createas.c

GPCC want to hook query like
- create table ... as select ...
- create materialized view ... as select ...

Add query info hook for CTAS query type.

---

concourse/tasks/run_explain_suite.yml
src/backend/gporca/concourse/test_explain_pipeline.yml

6X add orca pipeline workload3

---

gpdb-doc/dita/best_practices/bloat.xml

doc edit requested by greenplum oss slack user Mark in https://greenplum.slack.com/archives/C6TQ7D43E/p1600291971022400.

docs - add -a (no prompt) option to analyzedb call in script

---

gpdb-doc/dita/admin_guide/perf_troubleshoot.xml

update a troubleshooting topic

docs - update some troubleshooting info

---

gpdb-doc/dita/admin_guide/managing/proxy-ic.xml
gpdb-doc/dita/ref_guide/config_params/guc-list.xml

To be backported to 6X_STABLE.

Docs - update interconnect proxy discussion to cover hostname support

---

src/backend/commands/createas.c

GPCC want to hook query like
- create table ... as select ...
- create materialized view ... as select ...
This is backport from commit: 7ae210a1bf7e569a18cda32dcec3b55665a42ee7

[6X backport]Add query info hook for CTAS query type

---

gpMgmt/test/behave/mgmt_utils/gpexpand.feature
src/backend/commands/tablecmds.c

Allow gpexpand to expand materialized view

---

src/backend/gpopt/utils/COptTasks.cpp
src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InListLarge.mdp
src/backend/gporca/data/dxl/minidump/BitmapIndexScanChooseIndex.mdp
src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp
src/backend/gporca/libgpdbcost/src/CCostModelParamsGPDB.cpp
src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp
src/backend/gporca/scripts/cal_bitmap_test.py
src/backend/gporca/server/CMakeLists.txt

Port of https://github.com/greenplum-db/gpdb/pull/11083 plus conversion of the calibration program to Python 3.
For details see the individual commit messages.

Experimental cost model update (port from 6X)

---

gpMgmt/bin/gpinitsystem

Earlier the error was sent to /dev/null and the information was lost
displaying the cause of the error. Redirect the error to log file.

Redirect the error to log message
