greenplum-db/gpdb

src/backend/access/heap/heapam.c, src/backend/executor/execMain.c, src/backend/parser/parse_clause.c, src/backend/parser/parse_relation.c, src/backend/rewrite/rewriteHandler.c, src/backend/storage/lmgr/lmgr.c, src/backend/utils/cache/plancache.c, src/include/access/heapam.h, src/include/parser/parse_relation.h, src/include/storage/lmgr.h, src/test/isolation2/expected/select_for_update.out, src/test/isolation2/sql/select_for_update.sql
This is a backport of PR(https://github.com/greenplum-db/gpdb/pull/9726)
for 5X_STABLE. NOWAIT only affects how SELCT locks rows as they are
obtained from the table. They are used by the execution. So, the SELECT
statement with locking clause will wait for the table lock if it
can't hold the table lock.
=> 6X: Fix the nowait issue(#8539)

src/backend/optimizer/path/allpaths.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
Previously, in function bring_to_outer_query and bring_to_singleQE
it depends on the path->param_info field to determine if the path
can be taken into consideration since we cannot pass params across
motion node. But this is not enough, for example, an index path's
param_info field might be null, but its orderbyclauses refs some
outer params. This commit fixes the issue by adding more check
for indexpath.
See Github Issue: https://github.com/greenplum-db/gpdb/issues/9733
for details.
----------------------
I have gone through the code to verify if we are missing other fields that may contain outerparams.
I do not find anything yet.
I will go through it twice today.
=> Add check for indexpath when bring_to_outer_query and bring_to_singleQE.

src/backend/access/heap/heapam.c, src/backend/executor/execMain.c, src/backend/parser/parse_clause.c, src/backend/parser/parse_relation.c, src/backend/rewrite/rewriteHandler.c, src/include/access/heapam.h, src/test/isolation2/expected/select_for_update.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/select_for_update.sql
This is a backport of PR(https://github.com/greenplum-db/gpdb/pull/9726)
for 5X_STABLE. NOWAIT only affects how SELCT locks rows as they are
obtained from the table. They are used by the execution. So, the SELECT
statement with locking clause will wait for the table lock if it
can't hold the table lock.
=> 5X: Fix the nowait issue(#8539)

src/backend/access/appendonly/aomd.c, src/backend/catalog/heap.c, src/include/access/aomd.h, src/test/regress/expected/sirv_functions.out, src/test/regress/expected/truncate_gp.out, src/test/regress/parallel_schedule, src/test/regress/sql/sirv_functions.sql, src/test/regress/sql/truncate_gp.sql
In past, when create table and truncate table are in the same
transaction, Greenplum will call heap_truncate_one_rel() to truncate
the relation. But for AO tables, it has different segmenting logic,
which leads to some of segment files cannot be truncated to zero.
Using ao_truncate_one_rel to replace heap_truncate_one_rel() and
handle the segmenting by ao_foreach_extent_file().
Reviewed-by: Ashwin Agrawal <aagrawal@pivotal.io>
Reviewed-by: Soumyadeep Chakraborty <sochakraborty@pivotal.io>
(cherry picked from commit bb8d0305e17d79db7747688c783d7c13bb2939ae)
=> [Backport 6X] Truncate AO relation correctly (#9806)

src/backend/optimizer/path/allpaths.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
Previously, in function  bring_to_singleQE
it depends on the path->param_info field to determine if the path
can be taken into consideration since we cannot pass params across
motion node. But this is not enough, for example, an index path's
param_info field might be null, but its orderbyclauses refs some
outer params. This commit fixes the issue by adding more check
for indexpath.
See Github Issue: https://github.com/greenplum-db/gpdb/issues/9733
for details.
This pr is backporting the pr https://github.com/greenplum-db/gpdb/pull/9814 (already merged in master) to 6X to fix the above issue. 
Will merge this once pipeline is green.
=> (6x backport)Add check for indexpath when bring_to_singleQE.

concourse/scripts/compile_gpdb.bash, gpAux/Makefile
For gpdb release, gp-releng team wants to consolidate all configurations in one location: `gpAux/Makefile`
see this comment on PR: https://github.com/greenplum-db/gpdb/pull/9785#discussion_r397253979
Authored-by: Tingfang Bao <bbao@pivotal.io>
=> Move --disable-pxf from compile_gpdb.bash to gpAux/Makefile

src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h, src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp
This bug is particularly evident with queries containing a large array
IN clause, e.g "a IN (1, 3, 5, ...)".
As a first step to improve optimization times for such queries, this
commit reduces unnecessary re-allocation of histogram buckets during the
merging of statistics of disjunctive predicates.
It improves the performance of the target query with 7000 elements in
the array comparison by around 50%.
Co-authored-by: Shreedhar Hardikar <shardikar@pivotal.io>
Co-authored-by: Ashuka Xue <axue@pivotal.io>
=> Speed up stats derivation for large number of disjunction in ORCA

configure, configure.in, gpcontrib/gpmapreduce/Makefile, src/Makefile.global.in, src/bin/gpfdist/Makefile
Before this the top level configure only sets the have_yaml, but doesn't
add -lyaml to LIBS for gpfdist or gpmapreduce.
Let Autoconf resolve all the relevant libraries here and place them in
$XXX_LIBS variables.
=> Set the libraries of gpfdist and gpmapreduce at the top level

src/backend/commands/matview.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfuncs.c, src/test/regress/expected/matview_ao.out, src/test/regress/sql/matview_ao.sql
Co-authored-by: Jinbao Chen <jinchen@pivotal.io>
Just add the missing field in serialization, so no test is needed.
=> Add missing field skipData in RefreshClause serialization.

src/backend/commands/createas.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/outfast.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/nodes/readfuncs.c, src/backend/tcop/utility.c, src/include/nodes/parsenodes.h, src/test/regress/expected/gpctas.out, src/test/regress/sql/gpctas.sql
As reported in issue #9790, 'CTAS with no data' statement doesn't handle WITH
clause, the options in WITH clause should be added in 'pg_attribute_encoding'.
=> Fix CTAS 'with no data' bug

gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_last_operation.xml
enhance the docs for pg_stat_last_operation table to describe the preferred mechanism for querying (objid, not stasubtype); also added an example with sample output.
added this info to the reference page, below the table of fields, as this table isn't referenced elsewhere in the docs.
=> docs - add info about querying the pg_stat_last_operation tbl

gpdb-doc/dita/ref_guide/modules/dblink.xml, gpdb-doc/dita/security-guide/topics/Authenticate.xml
in this PR:
- add an dblink connection string example with sslmode. 
- a few misc edits to related client authentication topic
=> docs - add dblink connection string example with sslmode

src/backend/access/transam/twophase.c, src/backend/access/transam/xlog.c, src/backend/access/transam/xlog_mm.c, src/backend/cdb/cdbtm.c, src/include/access/twophase.h, src/include/access/xlogmm.h, src/include/cdb/cdbtm.h
Checkpointer process is a long-live and the current memory context for
the FOR loop is its own memory context. So any memory leak will lead to
the checkpointer process hold more and more memory until the memory
context is reset.
The `rdata` to build xlog record has 5 pointers that allocated by
palloc/palloc0 and only one pointer frees the memory. It's better to
free memory here rather than resetting the memory context in the for loop
of the checkpointer process.
=> Fix memory leak in checkpointer process.

src/backend/cdb/cdbpath.c, src/test/regress/expected/qp_union_intersect.out, src/test/regress/expected/qp_union_intersect_optimizer.out, src/test/regress/sql/qp_union_intersect.sql
Previously, planner cannot generate plan when a replicated
table union all a general locus scan. A typical case is:
select a from t_replicate_table
union all
select * from generate_series(1, 10);
The root cause is in the function `set_append_path_locus`
it deduces the whole append path's locus to be segmentgeneral.
This is reasonable. However, in the function `cdbpath_create_motion_path`
it fails to handle two issues in the case:
* segmentgeneral locus to segmentgeneral locus
* general locus to segmentgeneral locus
And the both above locus change does not need motion in fact.
This commit fixes this by:
1. add a check at the very begining of `cdbpath_create_motion_path`
that if the subpath's locus is the same as target locus, just return
2. add logic to handle general locus to …
=> Fix plan when segmentgeneral union all general locus.

src/backend/cdb/cdbpath.c, src/test/regress/expected/qp_union_intersect.out, src/test/regress/expected/qp_union_intersect_optimizer.out, src/test/regress/sql/qp_union_intersect.sql
Previously, planner cannot generate plan when a replicated
table union all a general locus scan. A typical case is:
select a from t_replicate_table
union all
select * from generate_series(1, 10);
The root cause is in the function `set_append_path_locus`
it deduces the whole append path's locus to be segmentgeneral.
This is reasonable. However, in the function `cdbpath_create_motion_path`
it fails to handle two issues in the case:
* segmentgeneral locus to segmentgeneral locus
* general locus to segmentgeneral locus
And the both above locus change does not need motion in fact.
This commit fixes this by:
1. add a check at the very begining of `cdbpath_create_motion_path`
that if the subpath's locus is the same as target locus, just return
2. add logic to handle general locus to …
=> (6x backport) Fix plan when segmentgeneral union all general locus.

src/backend/commands/createas.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/outfast.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/nodes/readfuncs.c, src/backend/tcop/utility.c, src/include/nodes/parsenodes.h, src/test/regress/expected/gpctas.out, src/test/regress/sql/gpctas.sql
As reported in issue #9790, 'CTAS with no data' statement doesn't handle WITH
clause, the options in WITH clause should be added in 'pg_attribute_encoding'.
=> [6X backport]Fix CTAS 'with no data' bug

src/backend/commands/vacuum.c, src/test/isolation2/expected/uao_crash_compaction_row.out, src/test/isolation2/sql/uao_crash_compaction_row.sql
This test creates an AO table and inserts data on all segments, then
it deletes some data on seg0 and seg1 and do a vacuum on the AO
table. When doing vacuum, it suspends the QE in seg0 at starting
doing the post vacuum cleanup, then crash the seg0 and finally do
the post crash validation checks using gp_toolkit.__gp_aoseg(), this
function will check all aoseg info on all segments.
The VACUUM process on seg1 is in an uncertain state, it might have
finished the post cleanup which is expected or hasn't started yet,
so the aoseg info in seg1 is uncertain too.
To resolve this, this commit added a new injector on the point all
post vacuum cleanup are committed and validate the aoseg info after
the vacuum process on seg1 reached this point.
=> Fix flaky uao_crash_compaction_row test

src/backend/access/transam/twophase.c, src/backend/access/transam/xlog.c, src/include/access/twophase.h, src/test/isolation2/expected/crash_recovery_dtm.out, src/test/isolation2/sql/crash_recovery_dtm.sql
The CurrentMemoryContext in CreateCheckPoint is long-live
memory context owned by the checkpointer process. The memory context
is reset only if the error occurs. So memory leak will lead to
huge memory leak in the OS.
=> Fix memory leak in checkpointer process

src/backend/cdb/dispatcher/cdbgang.c, src/backend/cdb/dispatcher/cdbgang_async.c, src/backend/storage/lmgr/lock.c, src/include/cdb/cdbgang.h, src/include/cdb/cdbvars.h, src/test/isolation2/expected/terminate_in_gang_creation.out, src/test/isolation2/sql/terminate_in_gang_creation.sql
The reason is that new created reader gang would fail on QE due to missing
writer gang process in locking code, and retry would fail again with the same
reason, since the cached writer gang is still used because QD does not know &
check the real libpq network status. See below for the repro case.
Fixing this by checking the error message and then reset all gangs if seeing
the error message, similar to the code logic that checks the startup/recovery
message in gang create function. We could have other fixes, e.g. checking the
writer gang network status, etc but those fixes seem to be ugly after trying.
create table t1(f1 int, f2 text);
<kill -9 one idle QE>
insert into t1 values(2),(1),(5);
ERROR:  failed to acquire resources on one or more segments
DETAIL:  FATAL:  reader could not find …
=> Fix a bug that reader gang always fail due to missing writer gang.

src/backend/cdb/cdbutil.c, src/backend/cdb/dispatcher/cdbgang.c, src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/postmaster/postmaster.c, src/include/cdb/ml_ipc.h, src/include/postmaster/postmaster.h
Currently, interconnect/UDP always binds the wildcard address to
the socket, which makes all QEs on the same node share the same
port space(up to 64k). For dense deployment, the UDP port could run
out, even if there are multiple IP address.
To increase the total number of available ports for QEs on a node,
we bind a single/unicast IP address to the socket for interconnect/UDP,
instead of the wildcard address. So segments with different IP address
have different port space.
To fully utilize this patch to alleviate running out of port, it's
better to assign different ADDRESS(gp_segment_configuration.address) to
different segment, although it's not mandatory.
With this patch, for interconnect/UDP, the source and the destnation
network address is the same as the ADDRESS of its corresponding …
=> Use a unicast IP address for interconnection

src/backend/gporca/data/dxl/minidump/AggWithVolatileFunc.mdp, src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp, src/backend/gporca/server/src/unittest/gpopt/minidump/CAggTest.cpp, src/test/regress/expected/subselect_optimizer.out
Consider the scenario below
```
create table tenk1 (c1 int, ten int);
create temp sequence ts1;
explain select * from (select distinct ten from tenk1) ss where ten < 10 + nextval('ts1') order by 1;
```
The filter outside the subquery is a candidate to be pushed below the
'distinct' in the sub-query.  But since 'nextval' is a volatile function, we
should not push it.
=> Do not push Volatile funcs below aggs

src/backend/utils/adt/lockfuncs.c
Allocate memory of CdbPgResults.pg_results with palloc0() instead
of calloc(), and free the memory afer use.
The CdbPgResults.pg_results array that is returned from various dispatch
functions is allocated by cdbdisp_returnResults() via calloc(), but in
most cases the memory is not free()-ed after use.
To avoid memory leak, the array is now allocated with palloc0() and
recycled with pfree().
Track which row and which result set is being processed in function context in pg_lock_status(), 
so that an ineffient inner loop can be eliminated.
-------------
cherry-pick the pr https://github.com/greenplum-db/gpdb/pull/9683 from master to 6X.
The pr https://github.com/greenplum-db/gpdb/pull/9683 has been reviewed and merged into master already.
This is a performance improvement and customer can …
=> 6x backport: Improve efficiency in pg_lock_status()

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
According to `plannode.h` `plan_node_id` should be unique across entire final plan tree. But `ORCA DXL` to `PlanStatement` translator returns uninitialized zero values for `BitmapOr` and `BitmapAnd` nodes. This behaviour differs from Postgres planner and from all other node translations in this class. It was fixed.
There are no regression tests in this PR as GP doesn't seem to have a SQL infrastructure to retrieve `plan_node_id` from a generated plan. I made some experiments with
```sql
create table t(a int);
insert into t select generate_series(1, 10000);
create index t_idx on t(a);
set debug_print_plan = on;
set client_min_messages = log;
set optimizer_enable_bitmapscan = on;
explain select * from t where (a < 10 or a > 9999) and (a > 0 or a < 10000);
```
but the result contained too …
=> Fix zero plan_node_id for BitmapOr/And in ORCA

contrib/auto_explain/expected/auto_explain.out, contrib/auto_explain/expected/auto_explain_optimizer.out, src/backend/commands/analyze.c, src/backend/utils/misc/postgresql.conf.sample, src/include/optimizer/cost.h, src/test/regress/expected/bitmapops.out, src/test/regress/expected/bitmapops_optimizer.out, src/test/regress/expected/create_index.out, src/test/regress/expected/create_index_optimizer.out, src/test/regress/expected/equivclass.out, src/test/regress/expected/join.out, src/test/regress/expected/join_optimizer.out, src/test/regress/expected/limit.out, src/test/regress/expected/partition_pruning.out, src/test/regress/expected/plancache.out, src/test/regress/expected/plancache_optimizer.out, src/test/regress/expected/portals.out, src/test/regress/expected/privileges.out, src/test/regress/expected/rowtypes.out, src/test/regress/expected/select.out, src/test/regress/expected/select_optimizer.out, src/test/regress/sql/bitmapops.sql, src/test/regress/sql/create_index.sql, src/test/regress/sql/join.sql, src/test/regress/sql/plancache.sql, src/test/regress/sql/regex.sql, src/test/regress/sql/rowtypes.sql, src/test/regress/sql/select.sql
In upstream,  `random_page_access` default value is always 4. For some unknown reason, we bump up to 100, which impacts bitmap index, index, and index-only scan cost different. After some performance tests in ao and aoco table, diminishment of the value also can leverage these table scans plan.
=> Change random_page_access default value to 4

src/backend/storage/ipc/procarray.c
Half committed transactions in shmCommittedGxactArray are omitted.
The bug could cause data loss/inconsistency. If transaction T1
failed to commit prepared for some reasons, and the transaction T1
has been committed on the master and other segments, but the transaction
T1 isn't appended in the checkpoint record. So the DTX recovery
can't retrieve the transaction and run recovery-commit-prepared,
and the prepared transactions on the segment are aborted.
Co-authored-by: Gang Xiong <gxiong@pivotal.io>
=> Fix getDtxCheckPointInfo to contain all committed transactions

src/backend/storage/lmgr/lock.c
At several places we just invoke the function add_size
but does not assign its return value to any variable.
The result is just discarded. This commit fixes this.
--------------------------------
This PR does not contain test cases. The issue is quite straightforward and it is not easy to add
cases for this.
The PR copies some changes from the PR https://github.com/greenplum-db/gpdb/pull/9396/
=> Fix some potential bugs that not update size results.

gpdb-doc/dita/install_guide/install_guide.ditamap, gpdb-doc/dita/install_guide/install_modules.xml, gpdb-doc/dita/install_guide/migrate.xml, gpdb-doc/dita/install_guide/upgrade_intro.xml, gpdb-doc/dita/install_guide/upgrading.xml
attempt to make finding upgrade and migration info a bit easier by relating the two topics.
in this PR:
- add a landing page for upgrade (6->6 upgrade, 4/5->6 migration), then link off to the existing upgrade and migration pages
- nest upgrade and migration in the left subnav
the PR also includes a misc unrelated edit to include diskquota in the list of additional supplied modules that use CREATE EXTENSION for registering.
=> docs - make finding upgrade & migration info easier

gpMgmt/bin/analyzedb
This commit partially reverts commit 2ba1627ed43720ddbb81dc814ce71168ce1abbd5,
specifically the changes in `get_oid_str`, which attempted to be
resilient to tables be dropped during analyzedb. While this query worked
fine for a relatively small number of tables, when the number of
tables/partitions in the analyze set was very large (tens of thousands+),
the query would run out of stack space and fail during planning.
Additionally, in databases with many entries in pg_class, some of the
queries would require a high statement_mem or fail by going out of
memory. Overall, this form of query was not scalable.
This partial revert does not apply to 6X/master, as those use `to_regclass()`
which can return NULL instead of throwing an exception and does not hit
the above issues..
This does …
=> 5X: Fix poor performing query in analyzedb

src/backend/utils/sort/tuplesort_mk.c
Memory pointed to by tuple was not released in time. The process of creating index will crash if the count of table's rows is big enough.
This pull request is to solve the issue #9676.
=> fix memory leak when creating index

contrib/auto_explain/auto_explain.c, src/backend/commands/explain.c, src/backend/executor/execMain.c, src/bin/gpfdist/regress/output/exttab1.source, src/bin/gpfdist/regress/output/gpfdist2.source, src/include/executor/executor.h, src/test/regress/expected/deadlock2.out, src/test/regress/expected/partition_locking.out
GPDB support to eliminate alien nodes for QEs, but master still
needs to run ExecInitNode for all the plan nodes. This will
introduce unneccessary CPU cost on master.
Ideally master only needs to ExecInitNode for all node on top of the first
gather motion. Note that there are some exceptions we skip the
optimization: explain query, explain analzye query, cursor case and
initplan case.
=> Eliminating alien nodes on master.

src/backend/storage/lmgr/lock.c
At several places we just invoke the function add_size
but does not assign its return value to any variable.
The result is just discarded. This commit fixes this.
------------------
Cherry-pick pr (https://github.com/greenplum-db/gpdb/pull/9972) to 6X.
Pr https://github.com/greenplum-db/gpdb/pull/9972 has been reviewed and merged into master.
Will merge this when pipeline is green.
=> (6x backport) Fix some potential bugs that not update size results.

src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/executor/execUtils.c, src/backend/executor/nodeSubplan.c, src/include/cdb/ml_ipc.h, src/test/regress/expected/ic.out, src/test/regress/sql/ic.sql
In TCP interconnect, the sender used to force an EOS messages to the
receiver in two cases:
1. cancelUnfinished is true in mppExecutorFinishup.
2. an error occurs.
For case1, the comment says: to finish a cursor, the QD used to send
a cancel to the QEs, QEs then set the cancelUnfinished flag and did
a normal executor finish up. We now use QueryFinishPending mechanism
to stop a cursor, so case1 logic is invalid for a long time.
For case2, the purpose is: when an error occurs, we force an EOS to
the receiver so the receiver didn't report an interconnect error and
QD then will check the dispatch results and report the errors in the
QEs. From the view of interconnect, we have selectedd to the end of
the query and no error in the interconnect, this logic has two
problems:
1. it doesn't work …
=> Remove forceEos mechanism for TCP interconnect

contrib/postgres_fdw/Makefile, contrib/postgres_fdw/expected/gp_postgres_fdw.out, contrib/postgres_fdw/sql/gp_postgres_fdw.sql, src/backend/cdb/cdbcat.c
This commit enables parallel writes for Foreign Data Wrapper. This
feature is currently missing from the FDW framework, whilst parallel
scans are supported, parallel writes are missing. FDW parallel writes
are analogous to writing to writable external tables that run on all
segments.
One caveat is that in the external table framework, writable tables
support a distribution policy:
CREATE WRITABLE EXTERNAL TABLE foo (id int)
LOCATION ('....')
FORMAT 'CSV'
DISTRIBUTED BY (id);
In foreign tables, the distribution policy cannot be defined during
table definition, so we assume random distribution for all foreign
tables.
Parallel writes are enabled when the foreign table's exec_location is
set to FTEXECLOCATION_ALL_SEGMENTS only. For foreign tables that run on
master or any segment, the current …
=> Enable parallel writes for Foreign Data Wrappers

src/backend/commands/explain.c, src/test/regress/expected/explain_format.out, src/test/regress/expected/explain_format_optimizer.out, src/test/regress/sql/explain_format.sql
Similar to 3bdece19da and 512578487b, an Append node doesn't always have
a Flow attached to it. Teach EXPLAIN code to dig into its children.
This seems to be a recurring issue, but since it's been refactored away in
'master', I guess we'll just whack these on 6X_STABLE as they're reported.
Downgrade it to a WARNING, though; an assertion failure seems too harsh
for this. Now you get the warning even on non-assertion builds, but I
think that's fine.
Fixes https://github.com/greenplum-db/gpdb/issues/9819
=> Fix another missing-flow bug in JSON-format EXPLAIN.

src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/cdb/motion/tupser.c, src/include/cdb/cdbvars.h
It was set to 1 on all supported platforms, and I'm almost certain it
would be broken if you tried to set it to anything else, because it hasn't
been tested for a long time.
As far as I can see, the alignment was only needed because in the
receiving side, we cast the buffer into a TupSerHeader pointer, and there
was otherwise no guarantee that the buffer was suitable aligned for
TupSerHeader. That's easy to fix by memcpy()ing the TupSerHeader into a
local variable that's properly aligned.
=> Remove TUPLE_CHUNK_ALIGN.

concourse/pipelines/gen_pipeline.py, concourse/pipelines/templates/gpdb-tpl.yml, concourse/scripts/common.bash, concourse/scripts/gpcheckcloud_tests_gpcloud.bash, concourse/scripts/ic_gpdb_resgroup.bash, concourse/scripts/setup_gpadmin_user.bash, concourse/tasks/gpcheckcloud_tests_gpcloud.yml, concourse/tasks/regression_tests_gpcloud.yml, concourse/tasks/rename-server-build.yml, concourse/tasks/rename_rc_artifacts.yml, concourse/tasks/test_upgrade.yml, concourse/tasks/unit_tests_gpcloud.yml, concourse/tasks/verify_gpdb_versions.yml
This patch uses new images built for gpdb7 and deprecates Centos 6. The pipeline is using a subset of operating systems supported by gpdb6, but more may be added in the future.
As of this commit, there are no changes to any underlying infrastructure apart from the renaming. However, the creation of new gpdb7 testing images allows us to make changes to this underlying infrastructure, which will not be backportable to gpdb6.
All pipeline tests previously running on a Centos 6 base container or VM are updated to use Centos 7 instead.
While we have specified a PLATFORM=centos7 default variable, we would like to begin specifying any infrastructure explicitly, so we have not removed any "PLATFORM" specification that defines Centos 7 in favor of a "default" variable.
Some small amount of tech …
=> Update testing images to use gpdb7 infrastructure instead of gpdb6

gpdb-doc/dita/analytics/postGIS.xml
-Updated version 2.1.5 -> 2.5.4
-Updated references to PostGIS topics
-Removed geometry and geography limitation
-Added enhancement for postgis_manager.sh script - support installing PostGIS in a non-default schema
-Added examples of updating postgis.enable_outdb_rasters and postgis.gdal_enabled_drivers for a GPDB session
-Remove ANALYZE limitation for user-defined data types
-Added  _postgis_index_extent function is not supported
-Added note: <-> operator returns centroid/centroid distance
-changed name of PostGIS aggregate function ST_MemCollect to ST_Collect
Link to HTML output on a temporary GPDB doc review site.
https://docs-msk-gpdb6-gis.cfapps.io/7-0/analytics/postGIS.html
=> docs - updates for PostGIS 2.5.4

src/backend/catalog/pg_db_role_setting.c, src/test/regress/input/dispatch.source, src/test/regress/output/dispatch.source
ALTER DATABASE SET ... FROM CURRENT dispatches incorrect statement to the
segments. Reported in https://github.com/greenplum-db/gpdb/issues/9823
=> Fix ALTER DATABASE SET ... FROM CURRENT

src/backend/optimizer/path/pathkeys.c
make_pathkey_from_sortinfo passes the incorrect sort ref 0 to the equivalance
class and it will error out when the equivalance class has volatile function.
=> Fix "volatile EquivalenceClass has no sortref"

src/backend/cdb/cdbsubselect.c, src/backend/optimizer/plan/planner.c, src/backend/optimizer/plan/transform.c, src/backend/optimizer/prep/prepjointree.c
Some of the GPDB-added subquery pull-up operations relied on the join
tree having specific form. But it's straightforward to teach those
operations to deal with arbitarary FromExprs and JoinExprs in the join
tree. Do that, and remove the join tree normalization step.
The reason I'm hacking on this right now is that on the 'merge' branch,
where we're working on merging with PostgreSQL v12, the normalization was
messing with the new SRF-in-targetlist processing. It probably would've
been easy to fix, but if we can get rid of the normalization step
altogether, that's even better.
=> Stop "normalizing" the join tree of every query.

src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/executor/execUtils.c, src/backend/executor/nodeSubplan.c, src/include/cdb/ml_ipc.h, src/test/regress/expected/ic.out, src/test/regress/sql/ic.sql
This is a backport of the bug fix of interconnect from master to 6X_STABLE, it mainly resolved the hung interconnect issue and simply the handling of EOS.
related PR in master is:
https://github.com/greenplum-db/gpdb/pull/9808
https://github.com/greenplum-db/gpdb/pull/9968
https://github.com/greenplum-db/gpdb/pull/9993
=> [6X_STABLE] Backport Interconnect bug fix 

src/backend/fts/ftsprobe.c, src/backend/postmaster/postmaster.c
commit d453a4aabaa7a9084db04d92906101c2a8b88e29 implemented that for the crash
recovery case (not marking the node down and then not promoting the mirror).  It
seems that we should do that for the usual "starting up" case also(i.e.
CAC_STARTUP), besides for the existing "in recovery mode" case (i.e.
CAC_RECOVERY).
We've seen that fts promotes the "starting up" primary during isolation2
testing due to 'pg_ctl restart'.  In this patch we check recovery progress for
both CAC_STARTUP an CAC_RECOVERY during fts probe and thus can avoid this.
=> Let Fts tolerate the in-progress 'starting up' case on primary nodes.

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/backend/gporca/data/dxl/minidump/ArrayCmp-IN-ManyElements.mdp, src/backend/gporca/data/dxl/minidump/FilterScalarCast.mdp, src/backend/gporca/data/dxl/minidump/IN-Nulls-ArrayCmpAny.mdp, src/backend/gporca/data/dxl/minidump/IN.mdp, src/backend/gporca/data/dxl/statistics/ArrayCmpAny-Input-1.xml, src/backend/gporca/data/dxl/statistics/ArrayCmpAny-Output-1.xml, src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CFilterStatsProcessor.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CPoint.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPred.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredArrayCmp.h, src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp, src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp, src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatsPredArrayCmp.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/Makefile, src/backend/gporca/server/CMakeLists.txt, src/backend/gporca/server/include/unittest/dxl/statistics/CFilterCardinalityTest.h, src/backend/gporca/server/src/unittest/dxl/statistics/CFilterCardinalityTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CHistogramTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
Implements an algorithm in MakeHistArrayCmpFilter() using CStatsPredArrayCmp:
1. Construct a histogram with the same bucket boundaries as present in the
base_histogram.
This is better than using a singleton bucket per point, because it that
case, the frequency of each bucket is so small, it is often less than
CStatistics::Epsilon, and may be considered as 0, leading to
cardinality misestimation. Using the same buckets as base_histogram
also aids in joining histogram later.
2. Compute the frequency for each bucket based on the number of points (NDV)
present within each bucket boundary. NB: the points must be de-duplicated
beforehand to prevent double counting.
3. Join this "dummy_histogram" with the base_histogram to determine the buckets
from base_histogram that should be selected (using …
=> Improve statistics calculation for exprs like "var = ANY (ARRAY[...])"

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/backend/gporca/data/dxl/minidump/ArrayCmp-IN-ManyElements.mdp, src/backend/gporca/data/dxl/minidump/FilterScalarCast.mdp, src/backend/gporca/data/dxl/minidump/IN-Nulls-ArrayCmpAny.mdp, src/backend/gporca/data/dxl/minidump/IN.mdp, src/backend/gporca/data/dxl/statistics/ArrayCmpAny-Input-1.xml, src/backend/gporca/data/dxl/statistics/ArrayCmpAny-Output-1.xml, src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libnaucrates/include/naucrates/statistics/CBucket.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CFilterStatsProcessor.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CHistogram.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CPoint.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatistics.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPred.h, src/backend/gporca/libnaucrates/include/naucrates/statistics/CStatsPredArrayCmp.h, src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp, src/backend/gporca/libnaucrates/src/statistics/CFilterStatsProcessor.cpp, src/backend/gporca/libnaucrates/src/statistics/CHistogram.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatsPredArrayCmp.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatsPredUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/Makefile, src/backend/gporca/server/CMakeLists.txt, src/backend/gporca/server/include/unittest/dxl/statistics/CFilterCardinalityTest.h, src/backend/gporca/server/src/unittest/dxl/statistics/CFilterCardinalityTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CHistogramTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CJoinCardinalityTest.cpp
Improve statistics calculation for exprs like "var = ANY (ARRAY[...])"
Implements an algorithm in MakeHistArrayCmpAnyFilter() using CStatsPredArrayCmp:
1. Construct a histogram with the same bucket boundaries as present in the
base_histogram.
This is better than using a singleton bucket per point, because it that
case, the frequency of each bucket is so small, it is often less than
CStatistics::Epsilon, and may be considered as 0, leading to
cardinality misestimation. Using the same buckets as base_histogram
also aids in joining histogram later.
2. Compute the frequency for each bucket based on the number of points (NDV)
present within each bucket boundary. NB: the points must be de-duplicated
beforehand to prevent double counting.
3. Join this "dummy_histogram" with the base_histogram to …
=> [Backport] Improve statistics calculation for exprs like "var = ANY (ARRAY[...])"

src/backend/catalog/pg_db_role_setting.c, src/test/regress/input/dispatch.source, src/test/regress/output/dispatch.source
ALTER DATABASE SET ... FROM CURRENT dispatches incorrect statement to the
segments. Reported in https://github.com/greenplum-db/gpdb/issues/9823
=> [6X backport]Fix ALTER DATABASE SET ... FROM CURRENT

gpMgmt/test/behave/mgmt_utils/gpexpand.feature
The gpinitsystem will fail if the gpinitsystem logs contain errors or
warnings from previous tests.
=> 6X only: gpexpand: clear gpinitsystem logs before every behave test

src/backend/storage/ipc/procarray.c, src/test/isolation2/expected/gdd/concurrent_update.out, src/test/isolation2/sql/gdd/concurrent_update.sql
the test case injects a 'suspend' fault in function 'ProcArrayEndTransaction'
and it could be triggered by some other process like 'global deadlock detector'
or FTS, to fix this we specify the database name in the fault.
=> Fix flaky test concurrent_update

gpcontrib/orafce/expected/dbms_pipe_session_B.out, gpcontrib/orafce/sql/dbms_pipe_session_B.sql
The dbms_pipe_session_{A,B} tests are flaky in CI as it can so happen
that session B calls receiveFrom() before session A can even call
createImplicitPipe(). This leads to flaky test failures such as:
```patch
--- /tmp/build/e18b2f02/gpdb_src/gpcontrib/orafce/expected/dbms_pipe_session_B.out	2020-04-20 17:02:27.270832458 +0000
+++ /tmp/build/e18b2f02/gpdb_src/gpcontrib/orafce/results/dbms_pipe_session_B.out	2020-04-20 17:02:27.278832994 +0000
@@ -7,14 +7,6 @@
-- Receives messages sent via an implicit pipe
SELECT receiveFrom('named_pipe');
-NOTICE:  RECEIVE 11: Message From Session A
-NOTICE:  RECEIVE 12: 01-01-2013
-NOTICE:  RECEIVE 13: Tue Jan 01 09:00:00 2013 PST
-NOTICE:  RECEIVE 23: \201
-NOTICE:  RECEIVE 24: (2,rob)
-NOTICE:  RECEIVE 9: 12345
-NOTICE:  RECEIVE 9: 12345.6789
-NOTICE: …
```
=> Reduce flakiness of orafce dbms_pipe test

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
This is a backport of PR: #9918.
According to plannode.h "plan_node_id" should be unique across
entire final plan tree. But ORCA DXL to PlanStatement translator
returns uninitialized zero values for BitmapOr and BitmapAnd nodes.
This behaviour differs from Postgres planner and from all other
node translations in this class. It was fixed.
(cherry picked from commit 53a0b78187735aa3efb7ce099f2cc7bd0a475740)
Co-authored-by: Denis Smirnov <sd@arenadata.io>
=> 6X Backport: Fix zero plan_node_id for BitmapOr/And in ORCA

src/backend/utils/adt/ruleutils.c, src/test/regress/expected/rules.out, src/test/regress/sql/rules.sql
This is a backport of two commits from master:
```
commit ecbc64ad31ac3993eeab0c4e61392a4cb6477b5d
Author: Robert Haas <rhaas@postgresql.org>
Date:   Fri Jul 29 12:06:18 2016 -0400
Eliminate a few more user-visible "cache lookup failed" errors.
Michael Paquier
Original Postgres commit:
https://github.com/postgres/postgres/commit/3153b1a52f8f2d1efe67306257aec15aaaf9e94c
commit 3b56fdf82169b642128996d5b2a38f21e22b948b
Author: Robert Haas <rhaas@postgresql.org>
Date:   Tue Jul 26 16:07:02 2016 -0400
Change various deparsing functions to return NULL for invalid input.
Previously, some functions returned various fixed strings and others
failed with a cache lookup error.  Per discussion, standardize on
returning NULL.  Although user-exposed "cache lookup failed" error
messages might normally …
```
=> Backport fixes for syscache lookup error

src/test/isolation2/isolation2_resgroup_schedule
0816e4e35843122 added a new test resgroup_move_query but forgot to add
the sql src/test/isolation2/sql/resgroup/resgroup_move_query.sql or an
input file to generate it. Disable this for now so that resource group
tests will go green on master.
=> Temporarily disable resgroup_move_query test

gpdb-doc/dita/ref_guide/gp_toolkit.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_resgroup_status.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_resgroup_status_per_host.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_resgroup_status_per_segment.xml
Will be backported to 6X_STABLE
=> docs - clarify text for resource group CPU core usage in catalog tables.

concourse/pipelines/README.md, concourse/scripts/verify_gpdb_versions.bash
Missed a hard coded check for centos 6 in release job. This should resolve failures in release job caused by this check.
=> Fix release job centos6

concourse/pipelines/pr_pipeline.yml, concourse/pipelines/templates/gpdb-tpl.yml, concourse/scripts/behave_gpdb.bash, concourse/scripts/common.bash, concourse/scripts/compile_gpdb.bash, concourse/scripts/dumpdb.bash, concourse/scripts/gpMgmt_check_gpdb.bash, concourse/scripts/gpcheckcloud_tests_gpcloud.bash, concourse/scripts/ic_gpdb.bash, concourse/scripts/regression_tests_gpcloud.bash, concourse/scripts/run_behave_test.sh, concourse/scripts/scan_with_coverity.bash, concourse/scripts/unit_tests_gpcloud.bash, concourse/tasks/compile_gpdb.yml, concourse/tasks/run_behave_on_ccp_cluster.yml, gpAux/Makefile, gpAux/Makefile.global, gpMgmt/bin/Makefile, gpMgmt/bin/README.md, gpMgmt/bin/generate-greenplum-path.sh
Currently, Greenplum is built with a vendored python in $GPHOME/lib/python, which is then set to be the PYTHONHOME environment value after sourcing `greenplum_path.sh` 
This PR removes the requirement to vendor python in this directory, and by extension, unsets the PYTHONHOME environment variable.
This has several implications to the build and installation process.
With regards to building:
- previously, our vendored python provided the python headers necessary to compile pl/python. Now, these headers must be provided by python-devel (in RHEL or Suse environments) or python-dev (in Debian-based systems) to compile Greenplum.
- The python libraries that we ship, which include pygresql and psutil, should be compiled with system gcc - the same gcc version which compiled python that they are …
=> Unvendor python runtime from Greenplum installation directory

gpdb-doc/markdown/pxf/hdfs_avro.html.md.erb, gpdb-doc/markdown/pxf/hdfs_fileasrow.html.md.erb, gpdb-doc/markdown/pxf/hdfs_json.html.md.erb, gpdb-doc/markdown/pxf/hdfs_parquet.html.md.erb, gpdb-doc/markdown/pxf/hdfs_seqfile.html.md.erb, gpdb-doc/markdown/pxf/hdfs_text.html.md.erb, gpdb-doc/markdown/pxf/objstore_fileasrow.html.md.erb, gpdb-doc/markdown/pxf/objstore_parquet.html.md.erb, gpdb-doc/markdown/pxf/objstore_text.html.md.erb, gpdb-doc/markdown/pxf/read_s3_s3select.html.md.erb, gpdb-doc/markdown/pxf/troubleshooting_pxf.html.md.erb
pxf introduces the IGNORE_MISSING_PATH option.  in this PR:
- add new section "About PXF External Table Child Partitions" to the troubleshooting page.  i added it here because it seems to me that this isn't that common of a scenario.  i could be convinced to add it elsewhere.
- this new option is available for many, but not all, of the profiles.  i added an entry for the option on the hdfs:text page, in the external table parameters table.  i can also add this option/description to the external table parameters tables of all applicable profiles.   but just wondering if we want to do this?  if the option won't typically be used, the description could introduce confusion.  interested in your thoughts.
doc review site link:  http://docs-lisa-newpxfopt.cfapps.io/7-0/pxf/troubleshooting_pxf.htm …
=> docs - new pxf IGNORE_MISSING_PATH option

contrib/postgres_fdw/Makefile, contrib/postgres_fdw/expected/gp_postgres_fdw.out, contrib/postgres_fdw/sql/gp_postgres_fdw.sql, src/backend/cdb/cdbcat.c
This commit enables parallel writes for Foreign Data Wrapper. This
feature is currently missing from the FDW framework, whilst parallel
scans are supported, parallel writes are missing. FDW parallel writes
are analogous to writing to writable external tables that run on all
segments.
One caveat is that in the external table framework, writable tables
support a distribution policy:
CREATE WRITABLE EXTERNAL TABLE foo (id int)
LOCATION ('....')
FORMAT 'CSV'
DISTRIBUTED BY (id);
In foreign tables, the distribution policy cannot be defined during the
table definition, so we assume random distribution for all foreign
tables.
Parallel writes are enabled when the foreign table's exec_location is
set to FTEXECLOCATION_ALL_SEGMENTS only. For foreign tables that run on
master or any segment, the …
=> 6X Backport: Enable parallel writes for Foreign Data Wrappers

src/backend/gporca/gporca.mk, src/backend/gporca/libgpopt/src/engine/Makefile, src/backend/gporca/libgpopt/src/eval/Makefile, src/backend/gporca/libgpopt/src/mdcache/Makefile, src/backend/gporca/libgpopt/src/search/Makefile, src/backend/gporca/libgpopt/src/translate/Makefile, src/backend/gporca/libgpopt/src/xforms/Makefile, src/backend/gporca/libgpos/src/common/Makefile, src/backend/gporca/libnaucrates/src/base/Makefile, src/backend/gporca/libnaucrates/src/md/Makefile, src/test/fsync/Makefile, src/test/heap_checksum/Makefile, src/test/walrep/Makefile
The one change I need to get in the most is "Use CXXFLAGS instead of CPPFLAGS for -std and -W* ."
- extract most `CXXFLAGS` into configure
- separate `-Wpedantic` so translator is not busted if it includes `gporca.mk`
=> Orca clean up post-merge

configure, configure.in, src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
This patch set knocks out the last "unused variable" compiler warning, and removes it from our CFLAGS in `configure`. See each commit for details.
=> Don't suppress unused-but-set variable warning

configure, configure.in
As it turns out, Wmissing-format-attribute is a no-op in Clang. And GCC correctly errors out on a couple of printf-like functions in ORCA for not having the "format" annotation. To get past compilation, temporarily suppress the warning just for C++. When a forthcoming patch brings in the attribute we can revert this fix.
=> Suppress missing format attribute warning for C++

src/backend/catalog/system_views.sql, src/test/regress/expected/pg_stat.out, src/test/regress/sql/pg_stat.sql
The column n_mod_since_analyze was always 0 in the past. The root cause
is that n_mod_since_analyze is generated on segments but we read it from
master. Fix the sql and read the value from segments.
=> Support 'n_mod_since_analyze' in system view pg_stat_all_tables

src/backend/optimizer/plan/planner.c, src/test/regress/expected/limit_gp.out, src/test/regress/expected/limit_gp_optimizer.out, src/test/regress/sql/limit_gp.sql
If there is ORDER BY or DISTINCT in the query, we need to bring all the
data to a single node by setting must_gather to be true. An exception is
when there's a LIMIT or OFFSET clause, which would be handled later when
inserting Limit node. Here to tell if there is any LIMIT or OFFSET
clause, we should use limit_needed, instead of checking limitCount or
limitOffset directly.
Fixes issue #9746.
=> Fix how must_gather is determined with LIMIT ALL.

src/backend/utils/gdd/gddfuncs.c
for is commit ID:13a1f66ffcc16a5369f02273addfb4b0a7bba033
LockTagTypeNames array in file src/backend/utils/gdd/gddfuncs.c is No synchronous modification.
=> global deadlock detector process  will terminated with signal 11

src/backend/commands/copy.c, src/test/regress/expected/gpcopy_dispatch.out, src/test/regress/sql/gpcopy_dispatch.sql
Target partitions need new ResultRelInfos and override previous
estate->es_result_relation_info in NextCopyFromExecute(). The
new ResultRelInfo may leave its resultSlot as NULL. If sreh is
on, the parsing errors will be caught and loop back to parse
another row; however, the estate->es_result_relation_info was
already changed. This can cause crash.
Reproduce:
```sql
CREATE TABLE partdisttest(id INT, t TIMESTAMP, d VARCHAR(4))
DISTRIBUTED BY (id)
PARTITION BY RANGE (t)
(
PARTITION p2020 START ('2020-01-01'::TIMESTAMP) END ('2021-01-01'::TIMESTAMP),
DEFAULT PARTITION extra
);
COPY partdisttest FROM STDIN LOG ERRORS SEGMENT REJECT LIMIT 2;
1	'2020-04-15'	abcde
1	'2020-04-15'	abc
\.
```
=> Fix possible crash in COPY FORM on QEs

configure, configure.in
On HEAD (commit 5cc2ea505f9b7) we're seeing a flurry of 78 warnings of
unused-but-set-variable warnings using GCC 9. We were clearly not ready
for this change. I was blindsided by my local choice of tools (Clang 10)
when I thought we were warning-free.
This reverts commit ec1f5f089ae13096f6bfa8ecd6b06e8efdbb91fa.
=> Revert "Don't suppress unused-but-set variable warning."

gpcontrib/orafce/expected/dbms_pipe_session_B.out, gpcontrib/orafce/sql/dbms_pipe_session_B.sql
This is a backport of PR: #9964 
The dbms_pipe_session_{A,B} tests are flaky in CI as it can so happen
that session B calls receiveFrom() before session A can even call
createImplicitPipe(). This leads to flaky test failures such as:
```patch
--- /tmp/build/e18b2f02/gpdb_src/gpcontrib/orafce/expected/dbms_pipe_session_B.out	2020-04-20 17:02:27.270832458 +0000
+++ /tmp/build/e18b2f02/gpdb_src/gpcontrib/orafce/results/dbms_pipe_session_B.out	2020-04-20 17:02:27.278832994 +0000
@@ -7,14 +7,6 @@
-- Receives messages sent via an implicit pipe
SELECT receiveFrom('named_pipe');
-NOTICE:  RECEIVE 11: Message From Session A
-NOTICE:  RECEIVE 12: 01-01-2013
-NOTICE:  RECEIVE 13: Tue Jan 01 09:00:00 2013 PST
-NOTICE:  RECEIVE 23: \201
-NOTICE:  RECEIVE 24: (2,rob)
-NOTICE:  RECEIVE 9: 12345
-NOTICE: …
```
=> [6X backport] Reduce flakiness of orafce dbms_pipe test

src/backend/commands/vacuum.c, src/test/isolation2/expected/uao_crash_compaction_column.out, src/test/isolation2/expected/uao_crash_compaction_row.out, src/test/isolation2/sql/uao_crash_compaction_column.sql, src/test/isolation2/sql/uao_crash_compaction_row.sql
In commit b00916e699c1fa3d95132bdb596e077d87c79cb0, we added a new
fault injector to wait segment 1 to finish the post cleanup and drop
the dead ao segment files, however, the test is still flaky because
segment 1 might delay the dropping of awaiting-drop segment files, this
is caused by commit 5778f31124d which changed the vacuum behavor:
"if there are concurrent transactions running, even in READ COMMITTED
mode, and even if they don't access the table at all, VACUUM will no
longer be able to recycle compacted segfiles. Next VACUUM will clean
them up, after the old concurrent transactions."
in test uao_crash_compaction_row, VACUUM has concurrent transactions.
1&:VACUUM crash_before_cleanup_phase;
3:SELECT gp_wait_until_triggered_fault('compaction_before....
it makes the status of …
=> Fix flaky uao_crash_compaction_row test: part two

src/backend/commands/copy.c, src/test/regress/expected/gpcopy_dispatch.out, src/test/regress/sql/gpcopy_dispatch.sql
Target partitions need new ResultRelInfos and override previous
estate->es_result_relation_info in NextCopyFromExecute(). The
new ResultRelInfo may leave its resultSlot as NULL. If sreh is
on, the parsing errors will be caught and loop back to parse
another row; however, the estate->es_result_relation_info was
already changed. This can cause crash.
Reproduce:
```sql
CREATE TABLE partdisttest(id INT, t TIMESTAMP, d VARCHAR(4))
DISTRIBUTED BY (id)
PARTITION BY RANGE (t)
(
PARTITION p2020 START ('2020-01-01'::TIMESTAMP) END ('2021-01-01'::TIMESTAMP),
DEFAULT PARTITION extra
);
COPY partdisttest FROM STDIN LOG ERRORS SEGMENT REJECT LIMIT 2;
1	'2020-04-15'	abcde
1	'2020-04-15'	abc
\.
```
-----------
This pr is cherry-picking the pr https://github.com/greenplum-db/gpdb/pull/9932 (already …
=> (6x backport)Fix possible crash in COPY FORM on QEs

gpdb-doc/markdown/pxf/col_project.html.md.erb, gpdb-doc/markdown/pxf/hive_pxf.html.md.erb, gpdb-doc/markdown/pxf/upgrade_pxf.html.md.erb
pxf supports column name-based mapping for Hive* profiles and column projection for the Hive and HiveRC profiles.  (didn't have the opportunity to try this feature out yet ...)  in this PR:
- update "about column projection" topic to include Hive and HiveRC profiles
- update the "accessing hive data" page:
- note column projection support
- note column name mapping requirements
- update all examples that were not previously using the same pxf/hive column names
- add a section to the upgrade topic that describes when/what upgrade actions may be required (drop/re-create external tables)
doc review site links:
- hive page:  http://docs-lisa-pxf-hivecolmap.cfapps.io/5270/pxf/hive_pxf.html#hive_queryextdata
- upgrade page (step 8):  http://docs-lisa-pxf-hivecolmap.cfapps.io/5270/pxf/upgrade_pxf …
=> docs - column projection for pxf hive and hiverc profiles

.travis.yml, configure, configure.in, src/backend/gporca/libgpos/include/gpos/attributes.h, src/backend/gporca/libgpos/include/gpos/common/clibwrapper.h, src/backend/gporca/libgpos/include/gpos/string/CStringStatic.h, src/backend/gporca/libgpos/server/src/unittest/gpos/io/CFileTest.cpp
Add `__format__` decorations for printf format checking to all ORCA functions that were missing them (uncovered by reverting commit 942448b).
When we build the ORCA test suite with CMake, we don't get to use Greenplum's configure infrastructure that determines the best format archetype (gnu_printf if available). ~For simplicity, just hardcode "printf", it's virtually universally supported.~ Add some CMake smarts to mimic what `configure` would do.
As part of this patch set, we also fix a problem the newly added attribute reveals. See each commit message for detail.
=> Add missing format attributes in Orca

src/backend/utils/workfile_manager/workfile_mgr.c
`workfile_shared->num_active` may not the actual size of the list workfile_shared->activeList in production. The best way is to find and fix the inconsistency. However, we failed to find where the problem code is. The above two variables are both in shared memory. It's commonly to reset the share-memory when part of the shared memory is corrupted.
=> PANIC if the workfile list in shared-memory is inconsistent

src/backend/cdb/cdbvars.c, src/backend/utils/misc/guc_gp.c, src/include/cdb/cdbvars.h
Looks like we were missing an "extern" in two places. While I was at it,
also tidy up guc_gp.c by moving the definition of Debug_resource_group
into cdbvars.c, and add declaration of
gp_encoding_check_locale_compatibility to cdbvars.h.
This is uncovered by building with GCC 10 and Clang 11, where
-fno-common is the new default [1][2] (vis a vis -fcommon). I could also
reproduce this by turning on "-fno-common" in older releases of GCC and
Clang.
We were relying on a myth (or legacy compiler behavior, rather) that C
tentative definitions act _just like_ declarations -- in plain English:
missing an "extern" in a global variable declaration-wannabe wouldn't
harm you, as long as you don't put an initial value after it.
This resolves #10072.
[1] "3.17 Options for Code Generation Conventions: …
=> Fix multiple definition linker error

src/backend/gporca/data/dxl/minidump/DPE-with-unsupported-pred.mdp, src/backend/gporca/data/dxl/minidump/Join-Varchar-Equality.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-AvoidRangePred-DPE.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverGbAgg-2.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-JoinOverUnion-1.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE-2.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-MultiWayJoinWithDPE.mdp, src/backend/gporca/libgpopt/src/base/CCostContext.cpp, src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp, src/backend/gporca/libgpopt/src/operators/CPhysicalJoin.cpp
DPE stats are computed when we have a dynamic partition selector that's
applied on another child of a join. The current code continues to use
DPE stats even for the common ancestor join and nodes above it, but
those nodes aren't affected by the partition selector.
Regular Memo groups pick the best expression among several to compute
stats, which makes row count estimates more reliable. We don't have
that luxury with DPE stats, therefore they are often less reliable.
By minimizing the places where we use DPE stats, we should overall get
more reliable row count estimates with DPE stats enabled.
The fix also ignores DPE stats with row counts greater than the group
stats. Partition selectors eliminate certain partitions, therefore
it is impossible for them to increase the row count.
=> Limit DPE stats to groups with unresolved partition selectors

gpdb-doc/markdown/pxf/col_project.html.md.erb, gpdb-doc/markdown/pxf/hive_pxf.html.md.erb, gpdb-doc/markdown/pxf/upgrade_pxf_6x.html.md.erb
port doc changes for this pxf v5.12.0 feature from 5X_STABLE (https://github.com/greenplum-db/gpdb/pull/10058) to master.  this will be backported to 6X_STABLE when pxf v5.12.0 is distributed with a greenplum 6.x  
the only difference between pxf in greenplum 5x/6x is the upgrade topic.
=> docs - pxf hive column mapping round 2

gpMgmt/bin/gpload.py
gpload in the latest windows client package requires VS redistributable
package. Output more meaningful message if pg.py fails to load.
=> [skip-ci] gpload: improve error message

gpMgmt/bin/gpload.py
gpload in the latest windows client package requires VS redistributable
package. Output more meaningful message if pg.py fails to load.
=> [skip-ci][6X_STABLE] gpload: improve error message

src/backend/utils/workfile_manager/workfile_mgr.c
This fixes an accidental trailing semicolon that "liberated" some
logging from the condition. This was introduced in 4c7854ee5545a and it
generates a compiler warning for me:
> workfile_mgr.c:603:54: warning: if statement has empty body [-Wempty-body]
>                 if (node->next == NULL || node->next->prev != node);
>                                                                    ^
> workfile_mgr.c:603:54: note: put the semicolon on a separate line to silence this warning
> 1 warning generated.
=> Remove trailing semicolon typo

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
In the scenario "inject a fail and test if rollback is ok" the expansion
is canceled after the new segment is launched, it must be shutdown in
time to prevent port conflicts in followings scenarios.
This is to fix a flaky gpexpand behave test, no new test is added.  It is also needed on 6X branch.  It has been verified on a devel 6X pipeline.
=> gpexpand: behave: cleanup leaked segs after rollback

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
In the scenario "inject a fail and test if rollback is ok" the expansion
is canceled after the new segment is launched, it must be shutdown in
time to prevent port conflicts in the following scenarios.
(cherry picked from commit a5e325308237266e2700e5e3805c05a4c6386b08)
This is to fix a flaky gpexpand behave test, no new test is added. It has been verified on a devel 6X pipeline.
This is the 6X version of https://github.com/greenplum-db/gpdb/pull/10101.
=> 6X: gpexpand: behave: cleanup leaked segs after rollback

gpMgmt/test/behave/mgmt_utils/gpexpand.feature
We use "pkill postgres" to cleanup leaked segments in the behave tests,
if the postgress processes already exited the pkill command would fail
with code 1, "No processes matched or none of them could be signalled".
Fixed by ignoring the return code of pkill.
This is a follow-up of https://github.com/greenplum-db/gpdb/pull/10101
=> gpexpand: behave: allow pkill to fail

gpMgmt/test/behave/mgmt_utils/gpexpand.feature
We use "pkill postgres" to cleanup leaked segments in the behave tests,
if the postgress processes already exited the pkill command would fail
with code 1, "No processes matched or none of them could be signalled".
Fixed by ignoring the return code of pkill.
(cherry picked from commit a92e0a33ec240be9ef8dc47d49dbd949cf44845d)
=> 6X: gpexpand: behave: allow pkill to fail

src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeMaterial.c, src/backend/executor/nodeShareInputScan.c, src/backend/executor/nodeSort.c, src/backend/executor/nodeSubplan.c, src/include/nodes/execnodes.h
Everywhere except ShareInputScanState, we're always dealing with either
a tuplestore or a tuplesort, so we don't need to use GenericTupStore.
=> Don't use GenericTupStore where the genericity is not needed.

contrib/file_fdw/output/file_fdw.source, contrib/postgres_fdw/connection.c, contrib/postgres_fdw/postgres_fdw.c, src/backend/cdb/dispatcher/cdbconn.c, src/backend/nodes/outfast.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/nodes/readfuncs.c, src/backend/optimizer/plan/createplan.c, src/backend/optimizer/plan/planner.c, src/backend/optimizer/util/pathnode.c, src/backend/replication/libpqwalreceiver/libpqwalreceiver.c, src/include/libpq/pqcomm.h, src/interfaces/libpq/fe-connect.c, src/interfaces/libpq/fe-protocol3.c, src/test/regress/expected/join.out, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/expected/join_optimizer.out, src/test/walrep/expected/walreceiver.out
Please check the commit messages.
This PR is to make the postgres_fdw work, the major things I have done are:
1, complete the missing parts of the kernel, "Get the missing T_MergeAppend back in pathnode_walk_kids()" and "Add binary (de)serialize functions for RestrictInfo node"
2, hack the connection option GPCONN_TYPE with a new available value "pg_compatible", which makes the libpq connection to use PostgreSQL version number. (GPDB uses the high bits of the major version to indicate special internal communications at the backend, bypass the authentication, and FDW is happening at the backend), which fixed #7935
3, disable UPDATE/DELETE on foreign Greenplum servers, because UPDATE/DELETE requires
the hidden column gp_segment_id and the other "ModifyTable mixes distributed and entry-only …
=> Make the postgres_fdw extension work

src/backend/utils/mmgr/aset.c
This showed up as bogus "Executor memory" lines in EXPLAIN ANALYZE
output.
Reviewed-by: Jesse Zhang <jzhang@pivotal.io>
=> Fix memory accounting.

src/test/isolation2/expected/segwalrep/dtm_recovery_on_standby.out, src/test/isolation2/sql/segwalrep/dtm_recovery_on_standby.sql
It takes time to start walsender after gpinitstandby, add a wait loop to reduce
the flaky. It also fix the next test commit_blocking_on_standby.
=> Fix flaky test dtm_recovery_on_standby

gpMgmt/bin/gpexpand, gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gppylib/commands/pg.py, gpMgmt/bin/gppylib/gpcatalog.py, gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Gpexpand creates new primary segments by first creating a template from
the master datadir and then copying it to the new segments. Some
catalog tables are only meaningful on master, such as
gp_segment_configuration, their content are then cleared on each new
segment with the "delete from ..." commands.
This works but is slow because we have to include the content of the
master-only tables in the archive, distribute them via network, and
clear them via the slow "delete from ..." commands -- the "truncate"
command is fast but it is disallowed on catalog tables as filenode must
not be changed for catalog tables.
To make it faster we now exclude these tables from the template
directly, so less data are transferred and there is no need to "delete
from" them explicitly.
---
This is the V2 of …
=> V2: gpexpand: exclude master-only tables from the template

src/backend/cdb/cdbpath.c, src/backend/optimizer/path/allpaths.c, src/backend/optimizer/plan/planmain.c, src/backend/optimizer/plan/subselect.c, src/include/nodes/plannerconfig.h, src/test/regress/expected/join.out, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/expected/join_optimizer.out
When handling join, if the inner path's locus is CdbLocusType_OuterQuery,
it also set the outer path's locus to CdbLocusType_OuterQuery in the
function cdbpath_motion_for_join. And later in cdbpath_create_motion_path,
it will add a materialize path over the motion path if the original path's
locus is CdbLocusType_OuterQuery. If the whole subquery can never be rescanned,
this materialize path is useless and will lead to performance lose. A typical
plan before this patch (from the case regress/expected/join.out) is:
```
explain (verbose, costs off)
select * from int4_tbl a,
lateral (
select * from int4_tbl b left join int8_tbl c on (b.f1 = q1 and a.f1 = q2)
) ss;
QUERY PLAN
------------------------------------------------------------------------
Nested Loop
Output: a.f1, b.f1, c.q1, c.q2
-> …
```
=> Remove useless materialize plannode in left tree of join.

gpMgmt/bin/gpexpand
The pg_partition_oid_index of template0 is used as a template of empty
indices, its path, however, is not fixed, we need to determine it at
runtime.
=> gpexpand: fix the template creation

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query38.ans
while gpload loads data if the configure file contains "error_table" and doesn't contain "preload".
=> Fix the gpload error that have no attribute "staging_table" or "fast_path".

gpdb-doc/dita/admin_guide/monitoring/monitoring.dita, gpdb-doc/dita/best_practices/bloat.xml
information from dev.
--Remove copying or redistributing table data as alternatives to VACUUM FULL
--Mention that VACUUM (without FULL) maintenance is for both heap and AO tables.
Also
Reorganized information.
Clarified ACCESS EXCLUSIVE lock is reason users cannot access table during VACUUM FULL
This will be backported to 6X_STABLE only.
Link to HTML output in a temporary GPDB draft doc web site
https://docs-msk-gpdb6-dev.cfapps.io/7-0/best_practices/bloat.html
=> docs - update bloat best practices

gpdb-doc/dita/ref_guide/sql_commands/CREATE_TABLE.xml
Also add more partitioned table examples.
Will be backported to 6X_STABLE
Link to HTML output on a temporary GPDB draft doc site.
https://docs-msk-gpdb6-part-tbl-dev.cfapps.io/7-0/ref_guide/sql_commands/CREATE_TABLE.html
=> docs - clarify/fix CREATE TABLE syntax for partitioned tables

gpdb-doc/dita/ref_guide/gp_toolkit.xml
most functions have been updated to use regclass (oid or table name)
@hlinnaka I created some ao tables, added some rows and deleted some rows
and these functions came back with 0 rows. Is that OK?
__gp_aovisimap()
__gp_aovisimap_entry()
dev PR on master https://github.com/greenplum-db/gpdb/pull/5928
=> docs - update gp_toolkit AO AOCO functions

src/backend/commands/tablecmds.c, src/test/regress/expected/alter_distribution_policy.out, src/test/regress/sql/alter_distribution_policy.sql
We are not allowed to modify the distribution of partition leaf table
after gpdb6. Because the distibution of root table and leaf table must
be same. But if only reorg on the partition leaf table, it will not
cause this problem. So we enable reorg when the distibution was not be
changed.
=> Enable reognization on partition leaf node

GNUmakefile.in, contrib/Makefile, contrib/amcheck/.gitignore, contrib/amcheck/Makefile, contrib/amcheck/amcheck--1.0.sql, contrib/amcheck/amcheck.control, contrib/amcheck/expected/check.out, contrib/amcheck/expected/check_btree.out, contrib/amcheck/sql/check.sql, contrib/amcheck/sql/check_btree.sql, contrib/amcheck/verify_nbtree.c, doc/src/sgml/amcheck.sgml, doc/src/sgml/contrib.sgml, src/tools/pgindent/typedefs.list
Backport the following commit from upstream
```
commit e2c3465a9d974be17345ed1929f02f75c098dc2b
Author: Andres Freund <andres@anarazel.de>
Date:   Thu Mar 9 15:50:40 2017 -0800
Add amcheck extension to contrib.
This is the beginning of a collection of SQL-callable functions to
verify the integrity of data files.  For now it only contains code to
verify B-Tree indexes.
This adds two SQL-callable functions, validating B-Tree consistency to
a varying degree.  Check the, extensive, docs for details.
The goal is to later extend the coverage of the module to further
access methods, possibly including the heap.  Once checks for
additional access methods exist, we'll likely add some "dispatch"
functions that cover multiple access methods.
Author: Peter Geoghegan, editorialized by Andres Freund …
```
=> Backport amcheck to 6X

src/backend/optimizer/plan/planner.c, src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/expected/dpe.out, src/test/regress/sql/bfv_aggregate.sql
The codes of multi phase aggregate add subqueryscan below the final
aggregate plan node. But we do not create a new root. So when we
create new path keys on sort node, wrong equivalent classes were
find out from the wrong list.
Now we just make a new root with empty equivalent class list when
the path keys were created. It is a little hack. But in gpdb5 we can only
make smallest changes.
=> Fix wrong result on aggregate with distinct

.travis.yml, src/backend/gporca/CMakeLists.txt, src/backend/gporca/gporca.mk, src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h, src/backend/gporca/libgpos/include/gpos/common/CAutoP.h, src/backend/gporca/libgpos/include/gpos/common/CAutoRg.h, src/backend/gporca/libgpos/include/gpos/common/CDouble.h, src/backend/gporca/libgpos/include/gpos/common/CLink.h, src/backend/gporca/libgpos/include/gpos/common/CRefCount.h, src/backend/gporca/libgpos/include/gpos/memory/CAutoMemoryPool.h, src/backend/gporca/libgpos/server/include/unittest/gpos/common/CSyncHashtableTest.h, src/backend/gporca/libgpos/src/memory/CAutoMemoryPool.cpp, src/backend/gporca/server/src/unittest/dxl/CParseHandlerCostModelTest.cpp
This patch makes the minimal changes to build ORCA with C++14. This
should address the grievance that ORCA cannot build with the default
Xerces C++ (3.2 or newer, which is built with GCC 8.3 in the default C++14
mode) headers from Debian. I've kept the CMake build system in sync with
the main Makefile. I've also made sure that all ORCA tests pass.
This patch set is the fleshed-out version of #9937 .
1. I've split up the steps into granular commits. See each commit for details
1. I plan to squash into one commit when we finally merge. Will post a draft message when we're close to merging.
1. Should we turn on ORCA in Travis CI? I've included changes that compile Greenplum with ORCA enabled in Travis CI, which adds to the compile time and run time. I've kept those changes in separate …
=> Build ORCA with C++14: Take Two

src/backend/commands/tablecmds.c, src/test/regress/expected/alter_distribution_policy.out, src/test/regress/expected/gp_explain.out, src/test/regress/expected/gp_explain_optimizer.out, src/test/regress/sql/alter_distribution_policy.sql, src/test/regress/sql/gp_explain.sql
We are not allowed to modify the distribution of partition leaf table
after gpdb6. Because the distibution of root table and leaf table must
be same. But if only reorg on the partition leaf table, it will not
cause this problem. So we enable reorg when the distibution was not be
changed.
backport from master cbcfafe6257a40e04a0c521704476654fbf050f6
=> Enable reognization on partition leaf node (#9975)

concourse/tasks/run_behave_on_ccp_cluster.yml
Commit 42930ed126d set the sysctl settings in a ccp cluster of VMs to be
identical to that in the docs. This has caused problems in the past, for
example see f765a0ef914 which resolve port overlap conflicts.
Recently, I've seen errors in gpconfig where python fails with "unable
to allocate memory" errors. Usually, on small memory systems like GCP
runs, this is due to the vm.overcommit=2 setting, because python
requests memory very greedily.
As an overarching statement, however, it's worth noting that GCP is
nothing like most customer systems in size or memory/cpu footprint, and
it's also nothing alike because it's on a vm, in the cloud, where some
sysctl settings are set prior to our access to the system on generic
vms.
I've taken the liberty of setting, or mostly unsetting, the OS …
=> Update CCP cluster sysctl to be inline with docs

gpdb-doc/markdown/pxf/intro_pxf.html.md.erb
in this PR:
- add subsections for os/java/hadoop
- add os info and note about centos6 curl issue
- add java info
=> docs - enhance the pxf supported platforms section

gpcontrib/pxf/src/pxffragment.c
When querying a PXF external table with some glob matching paths in the
LOCATION URI, Tomcat is rejecting the paths. In this commit, we remove
the `path` query string parameter as it has been deprecated and is no
longer used in the server, and it's causing issues with Tomcat because
the query string parameter is not URL-encoded.
=> PXF: fix glob matching in PXF paths for Hadoop-compatible filesystems

src/backend/utils/resscheduler/resqueue.c
When ResLockAcquire errors out after proclock is allocated and before the lock
is granted, the 'holdMask' and 'nLocks' of proclock are 0, it should be removed
properly in ResLockRelease.
=> [6X backport] Fix a resource queue lock issue

src/bin/gpfdist/gpfdist.c, src/bin/gpfdist/regress/test_watchdog.sh
Just like `man strtol` says:
>   the calling program should set errno to 0 before the call, and then determine if
>   an error occurred by checking whether errno has a nonzero value after the call.
=> Fix the bug that GPFDIST_WATCHDOG_TIMER doesn't work.

src/backend/utils/resscheduler/resqueue.c
When ResLockAcquire errors out after proclock is allocated and before the lock
is granted, the 'holdMask' and 'nLocks' of proclock are 0, it should be removed
properly in ResLockRelease.
=> [5X backport] Fix a resource queue lock issue

contrib/auto_explain/init_file
Commit 73ca7e7731917 (greenplum-db/gpdb#7195) introduced a simple suite
that exercises auto_explain. However, it went beyond a simple "EXPLAIN",
and instead it ran a muted version of EXPLAIN ANALYZE.
Comparing the output of "EXPLAIN ANALYZE" in a regress test is always
error-prone and flaky. To wit, commit 1348afc0054e3 (#7608) had to be
done shortly after 73ca7e7731917, because the feature was time
sensitive. More recently commit 2e4d99fa3f50e (#10032) was forced to
memorize the work_mem, likely compiled with --enable-cassert, and missed
the case when we were configured without asserts, failing the test with
a smaller-than-expected work_mem.
This commit puts a band aid on it by masking the numeric values of
work_mem in auto_explain output.
=> Mask out work_mem in auto_explain tests

src/backend/commands/analyze.c, src/backend/commands/analyzefuncs.c, src/backend/commands/vacuum.c, src/include/commands/vacuum.h, src/test/regress/expected/bfv_statistic.out, src/test/regress/expected/bfv_statistic_optimizer.out, src/test/regress/expected/gp_aggregates_costs.out, src/test/regress/sql/bfv_statistic.sql
Now the system table pg_statisitics only has data in master. But the
hash join skew hash need the some information in pg_statisitics. So
we need to dispatch the analyze command to segment. So that the system
table pg_statistics could have data in segments.
=> Dispatch analyze to segments

gpAux/extensions/pxf/src/pxffragment.c
When querying a PXF external table with some glob matching paths in the
LOCATION URI, Tomcat is rejecting the paths. In this commit, we remove
the `path` query string parameter as it has been deprecated and is no
longer used in the server, and it's causing issues with Tomcat because
the query string parameter is not URL-encoded.
=> 5X Backport: PXF: fix glob matching in PXF paths for Hadoop-compatible filesystems

contrib/pg_upgrade/check.c, contrib/pg_upgrade/test/integration/utilities/pg-upgrade-copy.c
During --check there is no need to pass the tablespaces information. No checks are performed regarding to tablespaces.
=> Dont generate tablespaces information during --check

src/backend/cdb/cdbsubplan.c, src/backend/executor/execMain.c, src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeShareInputScan.c, src/backend/executor/nodeSubplan.c, src/backend/utils/sort/tuplestorenew.c, src/include/cdb/cdbsubplan.h, src/include/utils/tuplestorenew.h, src/test/regress/expected/function_extensions.out, src/test/regress/expected/function_extensions_optimizer.out, src/test/regress/sql/function_extensions.sql
We introduce function which runs on INITPLAN in commit a21ff2
INITPLAN function is designed to support "CTAS select * from udf();"
Since udf() is run on EntryDB, but EntryDB is always read gang which
cannot do dispatch work, the query would fail if function contains DDL
statement etc.
The idea of INITPLAN function is to run the function on INITPLAN, which
is QD in fact and store the result into a tuplestore. Later the FunctionScan
on EntryDB just read tuple from tuplestore instead of running the real function.
But the life cycle management is a little tricky. In the original commit, we
hack to close the tuplestore in INITPLAN without deleting the file, and let
EntryDB reader to delete the file after finishing the tuple fetch. This will
introduce file leak if the transaction abort before …
=> Refactor the resource management in INITPLAN function

src/backend/commands/matview.c, src/backend/executor/execMain.c
We have a refresh matview with unique index check test case
CREATE TABLE mvtest_foo(a, b) AS VALUES(1, 10);
CREATE MATERIALIZED VIEW mvtest_mv AS SELECT * FROM mvtest_foo distributed by(a);
CREATE UNIQUE INDEX ON mvtest_mv(a);
INSERT INTO mvtest_foo SELECT * FROM mvtest_foo;
REFRESH MATERIALIZED VIEW mvtest_mv;
Only one segment contains tuples and will failed the unique index
check. Without 2pc, other segemnts will just commit transaction
successfully. Since one segment errors out, QD will send cancel
signal to all the segments, and if these segments have not finished
the commit process, it will report the warning:
DETAIL: The transaction has already changed locally,
it has to be replicated to standby.
Also it's risky to not use 2pc when qe write xlog.
=> Fix flaky test: refresh matview should use 2pc commit.

src/backend/cdb/motion/ic_tcp.c
This is mainly to resolve slow response to sequence requests under
TCP interconnect, sequence requests are sent through libpqs from
QEs to QD (we call them dispatcher connections). In the past, under
TCP interconnect, QD checked the events on dispatcher connections
every 2 seconds, obviously it's inefficient.
Under UDPIFC mode, QD also monitors the dispatcher connections when
receving tuples from QEs so QD can process sequence requests in
time, this commit applies the same logic to the TCP interconnect.
=> Monitor dispatcher connection when receiving from TCP interconnect

src/backend/cdb/cdbpath.c, src/test/regress/expected/union_gp.out, src/test/regress/sql/union_gp.sql
`select c.c1, c.c2 from d1 c union all select a.c1, a.c2 from d2 a;`
Both d1 and d2 are replicated tables, but the `numsegments` of them
in gp_distribution_policy are different. This could happen during
gpexpanding. The bug exists in function cdbpath_create_motion_path.
Both subpath->locus and locus are SegmentGeneral, but the locuses
are not equal
Co-authored-by: Pengzhou Tang <ptang@pivotal.io>
=> Fix bug when union all replicated tables with different numsegments

src/test/regress/input/sreh.source, src/test/regress/output/sreh.source
pkill is not in /bin/ folder on Ubuntu, so gpfdist can't be killed
in sreh test. That would make gpfdist regression test fail
=> Fix pkill path in sreh test

contrib/pg_upgrade/test/integration/utilities/pg-upgrade-copy.c
The 2 include statements were incorrectly removed in commit: 63702dc. Add them back.
=> Add headers removed during 63702dc26483e3e98223e376a54b12834c349024

src/backend/cdb/cdbsubplan.c, src/backend/cdb/dispatcher/cdbdisp_query.c, src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/executor/execUtils.c, src/include/cdb/cdbicudpfaultinjection.h
This issue is exposed when doing an experiment to remove the
special "eval_stable_functions" handling in evaluate_function(),
qp_functions_in_* test cases will get stuck sometimes and it turns
out to be a gp_interconnect_id disorder issue.
Under UDPIFC interconnect, gp_interconnect_id is used to
distinguish the executions of MPP-fied plan in the same session
and in the receiver side, packets with smaller gp_interconnect_id
is treated as 'past' packets, receiver will stop the sender to send
the packets.
The RCA of the hung is:
1. QD call InitSliceTable() to advance the gp_interconnect_id and
store it in slice table.
2. In CdbDispatchPlan->exec_make_plan_constant(), QD find some
stable function need to be simplified to const, then it executes
this function first.
3. The function contains …
=> Fix a hung issue caused by gp_interconnect_id disorder

src/bin/psql/describe.c, src/test/regress/expected/matview_ao.out, src/test/regress/sql/matview_ao.sql
The psql client ignored rel storage when he create the \dm command.
So the output of \dm was empty. Add the correct rel storage check in command.
=> Fixed the \dm empty output error

src/test/regress/input/sreh.source, src/test/regress/output/sreh.source
pkill is not in /bin/ folder on Ubuntu, so gpfdist can't be killed
in sreh test. That would make gpfdist regression test fail
=> Fix pkill path in sreh test (#10171)

src/backend/access/transam/distributedlog.c, src/backend/storage/ipc/procarray.c
the distributed xid is just a plain counter, there is no WRAPAROUND in it.
=> Always use the <,<=,>,>= for the comparison of gxid

src/backend/cdb/cdbsubplan.c, src/backend/cdb/dispatcher/cdbdisp_query.c, src/backend/cdb/motion/ic_common.c, src/backend/cdb/motion/ic_tcp.c, src/backend/cdb/motion/ic_udpifc.c, src/backend/executor/execUtils.c, src/include/cdb/cdbicudpfaultinjection.h
This issue is exposed when doing an experiment to remove the
special "eval_stable_functions" handling in evaluate_function(),
qp_functions_in_* test cases will get stuck sometimes and it turns
out to be a gp_interconnect_id disorder issue.
Under UDPIFC interconnect, gp_interconnect_id is used to
distinguish the executions of MPP-fied plan in the same session
and in the receiver side, packets with smaller gp_interconnect_id
is treated as 'past' packets, receiver will stop the sender to send
the packets.
The RCA of the hung is:
1. QD call InitSliceTable() to advance the gp_interconnect_id and
store it in slice table.
2. In CdbDispatchPlan->exec_make_plan_constant(), QD find some
stable function need to be simplified to const, then it executes
this function first.
3. The function contains …
=> [6x backport] Fix a hung issue caused by gp_interconnect_id disorder

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Duplicate sensitive HashDistribute Motions generated by ORCA get
translated to Result nodes with hashFilter cols set. However, if the
Motion needs to distribute based on a complex expression (rather than
just a Var), the expression must be added into the targetlist of the
Result node and then referenced in hashFilterColIdx.
However, this can affect other operators above the Result node. For
example, a Hash operator expects the targetlist of its child node to
contain only elements that are to be hashed. Additional expressions here
can cause issues with memtuple bindings that can lead to errors.
(E.g The attached test case, when run without our fix, will give an
error: "invalid input syntax for integer:")
This PR fixes the issue by adding an additional Result node on top of
the duplicate …
=> Remove unnecessary projections from duplicate sensitive Distribute(s) in ORCA

src/test/isolation2/input/resgroup/resgroup_move_query.source, src/test/isolation2/output/resgroup/resgroup_move_query.source
pg_resgroup_move_query is an asychronous operation, pg_resgroup_move_query
complete doesn't mean the query has already move to the destination group.
=> Fix flaky resgroup test

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/backend/gpopt/utils/COptTasks.cpp, src/backend/optimizer/plan/orca.c
This is a continuation of commit 456b2b3 in GPORCA. Adding more errors to the list that
doesn't get logged in log file. We are also removing the code that writes to std::cerr,
generating a not very nice looking log message. Instead, add the info whether the error was
unexpected to another log message that we also generate.
This is a cherry-pick of GPDB master PR greenplum-db/gpdb#10100.
The corresponding Orca PR is https://github.com/greenplum-db/gporca/pull/586.
=> Log fewer errors

gpMgmt/bin/gppylib/system/configurationImplGpdb.py, src/test/isolation2/expected/segwalrep/recoverseg_from_file.out, src/test/isolation2/helpers/server_helpers.sql, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql
When introducing a new mirror, we need two steps:
1. start mirror segment
2. update gp_segment_configuration catalog
Previously gp_add_segment_mirror will be called to update
the catalog, but dbid is chosen by get_availableDbId() which
cannot ensure to be the same dbid in internal.auto.conf.
Refer to issue-9837 for the bad case.
=> Using gp_add_segment to register mirror in catalog.

src/test/regress/expected/gp_toolkit.out, src/test/regress/sql/gp_toolkit.sql
Commit 152783e128 added a test along with the fix, but I broke it soon
after in commit c91e320c34. I changed the name of the test table from
'test' to 'wide_width_test', but forgot to adjust UPDATE command
accordingly, so the UPDATE did nothing.
Fix that, and also change the test to not rely on pg_attribute to create
the test table. I noticed this as I was working on the PostgreSQL v12
merge: the test was throwing an error because a new 'anyarray' column
(attmissingval) was added to pg_attribute in upstream. That caused the
CTAS to fail. Listing the table columns explicitly avoids that problem.
I verified this by reverting commit 152783e128 locally, and running the
test. It now throws an integer overflow error as intended.
=> Fix broken test for old gp_bloat_diag issue.

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
In some cases where Orca generates a plan where the material node is
not directly above a motion. The executor doesn't recognize this as a special case
to set EXEC_FLAG_REWIND, even though the Materialize serves to prevent a rescan of
the underlying Motion node.
This causes the execution to fail with:
`Illegal rescan of motion node: invalid plan (nodeMotion.c:1623)` as it
would attempt to rescan a motion.
Since Orca only produces Materialize only when necessary, either for performance reasons
or to prevent rescan of an underlying Motion, EXEC_FLAG_REWIND should be set for any Materialize
generated by Orca.
Below is a valid plan generated by Orca:
```
Result  (cost=0.00..3448.01 rows=1 width=4)
->  Nested Loop  (cost=0.00..3448.01 rows=1 width=1)
Join Filter: true
->  Gather Motion 3:1 …
```
=> Ensure Material nodes generated by Orca always materialize

src/backend/gporca/data/dxl/minidump/Join-Varchar-Equality.mdp, src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h, src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp
Previously in the DPv2 transform (`exhaustive2`) while we penalized 
cross joins for the remaining joins in greedy, we did
not for the first join, which in some cases selected a cross join.
This ended up selecting a poor join order in many cases and went against
the intent of the alternative being generated, which is to minimize
cross joins. 
We also increase the cost of the default penalty from 5 to 1024, which is the value we use in the cost model during the optimization stage.
The greedy alternative also wasn't kept in the heap, so we include that now too.
These changes improved tpcds performance using dpv2 overall by ~6% compared to the existing DPv2 transform (`exhaustive`) and improved many of the regressions we saw.
=> Penalize cross products in Orca's DPv2 algorithm more accurately

gpAux/gpperfmon/src/gpmon/gpsmon.c, gpcontrib/gp_internal_tools/gp_instrument_shmem.c, src/include/gpmon/gpmon.h, src/test/isolation2/expected/instr_in_shmem_terminate.out, src/test/isolation2/sql/instr_in_shmem_terminate.sql, src/test/regress/expected/instr_in_shmem.out, src/test/regress/expected/instr_in_shmem_verify.out, src/test/regress/sql/instr_in_shmem.sql, src/test/regress/sql/instr_in_shmem_verify.sql
The original PR at https://github.com/greenplum-db/gpdb/pull/9919.
It was below 6X_STABLE for 100+ commits so that I rebased it on my fork and open it again for CI testing.
For some reason, gpmon_qexeckey_t structure used int16 for ccnt while all other GP code operates int32. This problem can cause ccnt overflow in gpperfmon packets.
This problem doesn't affect master branch as gpperfmon code has been removed from it.
But it seems to affect 6X_STABLE and 5X_STABLE branches.
Authored-by: Denis Smirnov <darthunix@gmail.com>
Reviewed-by: Hao Wang <haowang@pivotal.io>
=> Fix ccnt overflow in gpperfmon

gpcontrib/zstd/expected/compression_zstd.out, src/backend/catalog/pg_attribute_encoding.c, src/backend/commands/createas.c, src/backend/commands/tablecmds.c, src/backend/executor/execMain.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/parser/parse_utilcmd.c, src/backend/tcop/utility.c, src/bin/pg_dump/pg_dump.c, src/include/catalog/pg_attribute_encoding.h, src/include/executor/execdesc.h, src/include/parser/analyze.h, src/include/parser/parse_utilcmd.h, src/test/regress/expected/column_compression.out, src/test/regress/input/aocs.source, src/test/regress/output/aocs.source, src/test/regress/output/appendonly.source, src/test/regress/sql/column_compression.sql
Because why not? This was forbidden back in 2012, with an old JIRA ticket that said:
MPP-15735 - Inheritance is not supported with column oriented table
This shouldn't be possible:
Create table parent_tb2 (a1 int, a2 char(5), a3 text, a4 timestamp,
a5 date, column a1 ENCODING (compresstype=zlib,compresslevel=9,blocksize=32768))
with (appendonly=true,orientation=column)
distributed by (a1);
Create table child_tb4 (c1 int, c2 char) inherits(parent_tb2)
with (appendonly = true, orientation = column);
The reason is, dealing with column compression and inheritance is tricky
and inheritance shouldn't even be supported.
That explanation didn't go into any details, but I can see the trickiness.
There are many places you can specify column compression options even
without inheritance: in …
=> Allow AOCO tables to be inherited

src/backend/cdb/cdbsubplan.c, src/backend/executor/execMain.c, src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeMaterial.c, src/backend/executor/nodeShareInputScan.c, src/backend/executor/nodeSubplan.c, src/backend/utils/sort/tuplestorenew.c, src/include/cdb/cdbsubplan.h, src/include/utils/tuplestorenew.h, src/test/regress/expected/function_extensions.out, src/test/regress/expected/function_extensions_optimizer.out, src/test/regress/sql/function_extensions.sql
We introduce function which runs on INITPLAN in commit a21ff2
INITPLAN function is designed to support "CTAS select * from udf();"
Since udf() is run on EntryDB, but EntryDB is always read gang which
cannot do dispatch work, the query would fail if function contains DDL
statement etc.
The idea of INITPLAN function is to run the function on INITPLAN, which
is QD in fact and store the result into a tuplestore. Later the FunctionScan
on EntryDB just read tuple from tuplestore instead of running the real function.
But the life cycle management is a little tricky. In the original commit, we
hack to close the tuplestore in INITPLAN without deleting the file, and let
EntryDB reader to delete the file after finishing the tuple fetch. This will
introduce file leak if the transaction abort before …
=> [BACKPORT] Refactor the resource management in INITPLAN function

src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeSubplan.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfuncs.c, src/backend/optimizer/plan/createplan.c, src/include/nodes/execnodes.h, src/include/nodes/plannodes.h, src/test/regress/expected/function_extensions.out, src/test/regress/expected/function_extensions_optimizer.out, src/test/regress/sql/function_extensions.sql
We now use initplan id to differentiate the tuplestore used by
different INITPLAN functions. INITPLAN will also write the function
result into different tuplestores.
Also fix the bug which appends initplan in the wrong place. It may
generate wrong result in UNION ALL case.
=> Support multiple INITPLAN functions in one query.

src/backend/optimizer/util/pathnode.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
In PostgreSQL, semi-joins are implemented with JOIN_SEMI join types, or
by first eliminating duplicates from the inner side, and then performing
normal inner join (that's JOIN_UNIQUE_OUTER and JOIN_UNIQUE_INNER).
GPDB has a third way to implement them: Perform an inner join first, and
then eliminate duplicates from the result. This is performed by a
UniquePath above the join. And there are two ways to implement the
UniquePath: sorting and hashing. But if hashing is not enabled, we
should not consider it.
This patch fixes github issue #8437.
=> Fix up enable_hashagg when creating a UniquePath.

src/backend/cdb/cdbpartition.c, src/backend/commands/tablecmds.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/equalfuncs.c, src/backend/nodes/outfast.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/nodes/readfuncs.c, src/backend/parser/analyze.c, src/backend/parser/gram.y, src/backend/parser/parse_utilcmd.c, src/include/nodes/nodes.h, src/include/nodes/parsenodes.h, src/test/regress/expected/gp_create_table.out, src/test/regress/sql/gp_create_table.sql
Introduce a new DistributionKeyElem to hold each element in the list of
columns (and optionally their opclasses) in DISTRIBUTED BY (<col> [opclass],
...) syntax. Previously, we have used IndexElem, which conveniently also
holds a column name and its opclass, but it was not a very good fit because
IndexElem also contains many other fields that are not needed. Using a
new node type specifically for DISTRIBUTED BY makes the code dealing with
distribution key lists more clear. To compare, PostgreSQL v10 uses a struct
called PartitionElem for similar purposes in PARTITION BY clause. (But that
is not to be confused with the PartitionElem struct in GPDB 6 and below,
which is also related to partitioning sytnax but is quite different!)
Unlike IndexElem, the new node type includes a 'location' …
=> Clarify code that parses DISTRIBUTED BY, with new DistributionKeyElem node.

.gitmodules
This reverts commit 412493b0f1fbba7d27be7dd06c9f3554f6afd5db.
Failed to compile pgbouncer on centos6: can't find libevent.
pgbouncer 1.13 uses pkg-config to look libevent up instead of
using --with-libevent.
Another issue is: pgbouncer does not support libevent version 1.x
in 1.13 version, but we use libevent 1.4 on centos6.
=> Revert "Upgrade pgbouncer to 1.13"

src/bin/psql/describe.c, src/test/regress/expected/matview_ao.out, src/test/regress/sql/matview_ao.sql
The psql client ignored rel storage when he create the \dm command.
So the output of \dm was empty. Add the correct rel storage check in command.
This pr backport from master 999f187e8ec8e9b883989035e9738d92ebf0b8ea
=> Fixed the \dm empty output error (#10163)

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Porting #10194 to master. Note that the test query was changed w.r.t 6X
to generate a similar effect in ORCA.
Duplicate sensitive HashDistribute Motions generated by ORCA get
translated to Result nodes with hashFilter cols set. However, if the
Motion needs to distribute based on a complex expression (rather than
just a Var), the expression must be added into the targetlist of the
Result node and then referenced in hashFilterColIdx.
However, this can affect other operators above the Result node. For
example, a Hash operator expects the targetlist of its child node to
contain only elements that are to be hashed. Additional expressions here
can cause issues with memtuple bindings that can lead to errors.
(E.g The attached test case, when run without our fix, will give an
error: "invalid …
=> Remove unnecessary projections from duplicate sensitive Distribute in ORCA

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Porting #10194 to 6X_STABLE
Duplicate sensitive HashDistribute Motions generated by ORCA get
translated to Result nodes with hashFilter cols set. However, if the
Motion needs to distribute based on a complex expression (rather than
just a Var), the expression must be added into the targetlist of the
Result node and then referenced in hashFilterColIdx.
However, this can affect other operators above the Result node. For
example, a Hash operator expects the targetlist of its child node to
contain only elements that are to be hashed. Additional expressions here
can cause issues with memtuple bindings that can lead to errors.
(E.g The attached test case, when run without our fix, will give an
error: "invalid input syntax for integer:")
This PR fixes the issue by adding an additional Result …
=> [6x] Remove unnecessary projections from duplicate sensitive Distribute(s) in ORCA

gpAux/Makefile
Currently, GPDB5 is built with --enable-rpath (default configure
option). For plperl, it's Makefile specifies an absolute path to the
location of "$(perl -MConfig -e 'print $Config{archlibexp}')/CORE"
(e.g., /usr/lib64/perl5/CORE on RHEL7). This directory is not on the
default search path for the runtime linker. Without the proper RUNPATH
entry, libperl.so cannot be found when postgres tries to load the plperl
extension.
Without setting correct RUNPATH for plperl.so, will see a error like
followin:
ERROR:  could not load library
"/usr/local/greenplum-db-devel/lib/postgresql/plperl.so": libperl.so:
cannot open shared object file: No such file or directory
dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-173050625-fix-plp …
=> [GP RELEASE]Recompile plperl to set the right RUNPATH

gpdb-doc/markdown/pxf/intro_pxf.html.md.erb
update supported platforms for pxf version 5.12.0.  
the docs for v5.12.0 pxf features (hive* column projection, IGNORE_MISSING_PATH) were already merged to master in https://github.com/greenplum-db/gpdb/pull/10086 and https://github.com/greenplum-db/gpdb/pull/10010 and will be backported to 6X_STABLE.
=> docs - add pxf v5.12 to supported platforms

src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeSubplan.c, src/backend/nodes/copyfuncs.c, src/backend/nodes/outfuncs.c, src/backend/nodes/readfast.c, src/backend/optimizer/plan/createplan.c, src/include/nodes/execnodes.h, src/include/nodes/plannodes.h, src/test/regress/expected/function_extensions.out, src/test/regress/expected/function_extensions_optimizer.out, src/test/regress/sql/function_extensions.sql
We now use initplan id to differentiate the tuplestore used by
different INITPLAN functions. INITPLAN will also write the function
result into different tuplestores.
Also fix the bug which appends initplan in the wrong place. It may
generate wrong result in UNION ALL case.
cherry-pick from: 2589a3
=> [BACKPORT] Support multiple INITPLAN functions in one query.

src/test/isolation2/expected/segwalrep/recoverseg_from_file.out, src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql
1. after stop primary with content=1, we should check promotion
status with 1U:
2. after manually update dbid, we should trigger a fts probe and
wait for the mirror promotion as well.
=> Fix flaky test in recoverseg_from_file

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
document the "move query to a different resource group" feature implemented in https://github.com/greenplum-db/gpdb/pull/10095.
in this PR:
- add new topic "Moving a Query to a Different Resource Group" that discusses the new pg_resgroup_move_query() function.
- seems like the pg_resgroup_move_query() function is granted to public per gp_toolkit SQL?
- added upgrade/downgrade information in a note at the end of the topic.  not sure if this is the best place for it.
doc review site link (scroll up a bit to get to the start):  http://docs-lisa-movequery-rg.cfapps.io/7-0/admin_guide/workload_mgmt_resgroups.html#moverg
=> docs - add info about moving a query to a different resource group

gpdb-doc/dita/admin_guide/workload_mgmt_resgroups.xml
"using" info from https://github.com/greenplum-db/gpdb/pull/10238 plus upgrade/downgrade info that was originally in that PR.
=> docs - using info for moving a query to a diff resgroup (6x)

gpMgmt/bin/gppylib/system/configurationImplGpdb.py, src/test/isolation2/expected/segwalrep/recoverseg_from_file.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/segwalrep/recoverseg_from_file.sql
When introducing a new mirror, we need two steps:
1. start mirror segment
2. update gp_segment_configuration catalog
Previously gp_add_segment_mirror will be called to update
the catalog, but dbid is chosen by get_availableDbId() which
cannot ensure to be the same dbid in internal.auto.conf.
Reported by issue9837
Reviewed-by: Paul Guo <pguo@pivotal.io>
cherry-pick from commit: f7965d48
=> [Backport 6X] Using gp_add_segment to register mirror in catalog. (#9974)

src/backend/optimizer/path/allpaths.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
Previous commit 625797280 fixes a lateral panic issue but does
not handle all the bad cases because it only check if the query
tree contains limit clause. Bad cases for example: if the subquery
is like `q1 union all (q2 limit 1)` then the whole query tree
does not contain limit clause.
Another bad case is the lateral subquery may contain groupby.
like:
select * from t1_lateral_limit t1 cross join lateral
(select (c).x+t2.a, sum(t2.a+t2.b) from t2_lateral_limit t2
group by (c).x+t2.a)x;
When planning the lateraled subquery we do not know where is
the param in the subquery's query tree. Thus it is a bit complicated
to precisely and efficiently resolve this issue.
This commit adopts a simple method to fix panic issue: it justs
check the subquery's query tree to see if there is any group-by …
=> Fix lateral PANIC issue when subquery contain limit or groupby.

GNUmakefile.in, contrib/Makefile, contrib/amcheck/.gitignore, contrib/amcheck/Makefile, contrib/amcheck/amcheck--1.0.sql, contrib/amcheck/amcheck.control, contrib/amcheck/expected/check.out, contrib/amcheck/expected/check_btree.out, contrib/amcheck/sql/check.sql, contrib/amcheck/sql/check_btree.sql, contrib/amcheck/verify_nbtree.c, doc/src/sgml/amcheck.sgml, src/tools/pgindent/typedefs.list
Backport the following commit from upstream and add test cases for AO and AOCS tables.
```
Author: Andres Freund <andres@anarazel.de>
Date:   Thu Mar 9 15:50:40 2017 -0800
Add amcheck extension to contrib.
This is the beginning of a collection of SQL-callable functions to
verify the integrity of data files.  For now it only contains code to
verify B-Tree indexes.
This adds two SQL-callable functions, validating B-Tree consistency to
a varying degree.  Check the, extensive, docs for details.
The goal is to later extend the coverage of the module to further
access methods, possibly including the heap.  Once checks for
additional access methods exist, we'll likely add some "dispatch"
functions that cover multiple access methods.
Author: Peter Geoghegan, editorialized by Andres Freund …
```
=> Backport amcheck to 5X

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CQueryMutators.cpp, src/include/gpopt/gpdbwrappers.h, src/include/gpopt/translate/CQueryMutators.h, src/test/regress/expected/gporca_optimizer.out
We found that when we have window functions and also correlated subqueries in the
same target list, the CQueryMutators::NormalizeWindowProjList method would leave
the varattno attributes of outer references in the subquery unchanged. That needs
to be changed, since we are producing a different RTE for the query.
We will eventually create a fix. For now, this PR just searches for the
problem and triggers a fallback when we see it, to avoid incorrect results.
Co-authored-by: Hans Zeller <hzeller@vmware.com>
=> Fall back with window function plus corr subquery in target list

src/backend/gporca/concourse/test_orca_pipeline.yml
The python changes required new images, so we now need a separate
pipeline for slack commands from 6X. We also no longer need libsigar.
=> Fix test_gpdb slack command pipeline to work with new master changes

src/backend/access/external/url.c, src/backend/access/external/url_curl.c, src/backend/utils/misc/guc_gp.c, src/bin/gpfdist/regress/input/exttab1.source, src/bin/gpfdist/regress/output/exttab1.source, src/include/access/url.h, src/include/utils/unsync_guc_name.h
write_to_gpfdist_timeout controls timeout value (in seconds) for writing data to gpfdist server.
Default value is 300, valid scope is [1, 7200]
- CURLOPT_TIMEOUT is hard code 300s
- For CURLE_OPERATION_TIMEDOUT error, retry twice. total time 300s *2
- For other errors retry 7 times with double interval time, total time is about 127s
- set CURLOPT_TIMEOUT as write_to_gpfdist_timeout, default value is 300
- For any error, retry with double interval time, returns SQL ERROR if write_to_gpfdist_timeout is reached
=> Add GUC write_to_gpfdist_timeout

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
gpcheckcat persistent check is consist of a series of extra/missing
check, one is to detect the extra relation files in the file system
after a table is dropped, the main idea is:
1. using gp_persistent_relation_node_check() to list all relation
files in the filesystem
2. say whether catalog pg_class contains the entries referring to
those relfilenodes.
3. say whether catalog pg_persistent_relation_node contains the
entries referring to those relfilenodes.
Another background is:
heap tables only ever store segment_file_num 0 in the persistent
tables, while ao/co tables will store every segment_file_num that
they use, so we need to handle the difference in the SQL file,
otherwise, segment_file_num > 0 will be treated as extra files.
With the old filter in the SQL file, extra segment files …
=> Enhance gpcheckcat persistent check

src/backend/commands/copy.c
The flaky case happens when select an external table with option
"fill missing fields". By gdb the qe, this value is not false
on QE sometimes. When ProcessCopyOptions, we use intVal(defel->arg)
to parse the boolean value, which is not correct. Using defGetBoolean
to replace it.
=> Fix flaky test exttab1

src/test/isolation2/expected/terminate_in_gang_creation.out, src/test/isolation2/sql/terminate_in_gang_creation.sql
The test case restarts all primaries and expects the old session
would fail for the next query since gangs are cached.
But the restart may last more than 18s which is the max idle
time QEs could exist. In this case, the new query in the old
session will just fetch a new gang without expected errors.
Just set gp_vmem_idle_resource_timeout to 0 to fix this flaky test.
=> Fix flaky test terminate_in_gang_creation

gpdb-doc/dita/utility_guide/ref/psql.xml
Adapted from postgres 9.4 psql page.
=> Docs - Add materialized view info to psql \d reference content

gpcontrib/pxf_fdw/expected/pxf_fdw_foreign_table.out, gpcontrib/pxf_fdw/sql/pxf_fdw_foreign_table.sql, src/backend/commands/copy.c
The flaky case happens when select an external table with option
"fill missing fields". By gdb the qe, this value is not false
on QE sometimes. When ProcessCopyOptions, we use intVal(defel->arg)
to parse the boolean value, which is not correct. Using defGetBoolean
to replace it.
Also fix a pxf_fdw test case, which should set fill_missing_fields to true
explicitly.
=> Fix flaky test exttab1 and pxf_fdw

src/backend/access/transam/xact.c, src/backend/cdb/cdblocaldistribxact.c, src/backend/storage/ipc/procarray.c, src/test/isolation2/expected/distributed_transactions.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/distributed_transactions.sql
When the error happens after ProcArrayEndTransaction, it will recurse back to
AbortTransaction, we need to make sure it will not generate extra WAL record
and not fail the assertions.
=> Fix a recursive AbortTransaction issue

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/input/resgroup/resgroup_move_query.source, src/test/isolation2/output/resgroup/resgroup_move_query.source
When move a query to a resource group whose memory_limit is 0, the available
memory is the current available global shared memory.
=> Move query to a resource group with memory_limit 0

src/test/isolation2/expected/terminate_in_gang_creation.out, src/test/isolation2/sql/terminate_in_gang_creation.sql
The test case restarts all primaries and expects the old session
would fail for the next query since gangs are cached.
But the restart may last more than 18s which is the max idle
time QEs could exist. In this case, the new query in the old
session will just fetch a new gang without expected errors.
Just set gp_vmem_idle_resource_timeout to 0 to fix this flaky test.
Reviewed-by: Paul Guo <pguo@pivotal.io>
=> BACKPORT 6X: Fix flaky test terminate_in_gang_creation

gpAux/releng/make/dependencies/ivy.sh, gpAux/releng/make/dependencies/ivy.xml
since the newly createdmit/krb5/1.6.2+vmware.1 is available in Jfrog, and newly created version of third-party/ext/gpdb5_ext-3.5 no longer contains the unmodified krb5 1.6.2 and  newly created mit/krb5/1.6.2+vmware.1, so those two new artifacts will be downloaded and integrated.
=> Greenplum 5 vendors krb5 1.6.2+vmware.1 

src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
We need to ignore the below output when enabling/disabling an Orca xform, otherwise there will be a diff if GPDB is not compiled with Orca:
```
select disable_xform('CXformInnerJoin2HashJoin');
disable_xform
--------------------------------------
CXformInnerJoin2HashJoin is disabled
(1 row)
```
Additionally, depending on how many GUCs are set, the number of dashes
in the explain plan can vary, which can cause additional false
negatives. Instead, we mask these out.
e.g.:
```
QUERY PLAN
------------------------------------------------------------------------
```
This should fix https://github.com/greenplum-db/gpdb/issues/10258
=> Fix ICW issues when GPDB compiled without ORCA

src/bin/pg_rewind/sql/config_test.sh
Increase the retry count to prevent test failed. Most of the time, the
failure is because of slow processing.
=> Increase retry count for pg_rewind tests' replication promotion and streaming.

src/backend/commands/copy.c
The flaky case happens when select an external table with option
"fill missing fields". By gdb the qe, this value is not false
on QE sometimes. When ProcessCopyOptions, we use intVal(defel->arg)
to parse the boolean value, which is not correct. Using defGetBoolean
to replace it.
Also fix a pxf_fdw test case, which should set fill_missing_fields to
true explicitly.
cherry pick from: f154e5
=> [Backport 6X]Fix flaky test exttab1 and pxf_fdw

src/backend/optimizer/path/allpaths.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
Previous commit 625797280 fixes a lateral panic issue but does
not handle all the bad cases because it only check if the query
tree contains limit clause. Bad cases for example: if the subquery
is like `q1 union all (q2 limit 1)` then the whole query tree
does not contain limit clause.
Another bad case is the lateral subquery may contain groupby.
like:
select * from t1_lateral_limit t1 cross join lateral
(select (c).x+t2.a, sum(t2.a+t2.b) from t2_lateral_limit t2
group by (c).x+t2.a)x;
When planning the lateraled subquery we do not know where is
the param in the subquery's query tree. Thus it is a bit complicated
to precisely and efficiently resolve this issue.
This commit adopts a simple method to fix panic issue: it justs
check the subquery's query tree to see if there is any group-by …
=> (6x backport)Fix lateral PANIC issue when subquery contain limit or groupby.

src/backend/executor/execHHashagg.c, src/backend/utils/adt/numeric.c, src/test/regress/expected/gp_hashagg.out, src/test/regress/sql/gp_hashagg.sql
Highlights:
1) We had a bug in a few of the combine functions where if the combine
function returned a NULL, it didn't set fcinfo->isnull = true. This led
to a segfault when we would spill in the final hashagg of a two-stage
agg inside the serial function. So, properly mark NULL outputs from the
combine functions. **-- Needs backport to 6X_STABLE.**
2) While writing a repro for 1), we ran into two assertion failures, which we have fixed in two separate commits in this PR.
i)  "Fix assert condition in spill_hash_table()" - addresses issue #9902 -- **Needs backport all the way to 4x.**
ii) "Fix double deduction of FREEABLE_BATCHFILE_METADATA" - addresses a memory accounting issue which caused:
```
FailedAssertion("!(hashtable->mem_for_metadata > 0)", File: "execHHashagg.c", Line: 2141)
``` …
=> Properly mark null return from combine functions

src/bin/pg_rewind/sql/config_test.sh
Increase the retry count to prevent test failed. Most of the time, the
failure is because of slow processing.
=> [Backport 6X]Increase retry count for pg_rewind tests' replication promotion and streaming.

src/backend/utils/time/snapmgr.c, src/test/isolation2/expected/distributed_snapshot.out, src/test/isolation2/sql/distributed_snapshot.sql
Greenplum tests the visibility of heap tuples firstly using
distributed snapshot. Distributed snapshot is generated on
QD and then dispatched to QEs. Some utility statement needs
to work under latest snapshot when executing, so that they
invoke the function `GetLatestSnapshot` in QEs. But remember
we cannot get the latest distributed snapshot.
Subtle cases are: Alter Table or Alter Domain statements on QD
get snapshot in Portal Run and then try to hold locks on the
target table in ProcessUtilitySlow. Here is the key point:
1. try to hold lock ==> it might be blocked by other transcations
2. then it will be waked up to continue
3. when it can continue, the world has changed because other transcations
then blocks it have been over
Previously, on QD we do not getsnapshot before we dispatch …
=> GetLatestSnapshot on QEs always return without distributed snapshot.

src/backend/utils/time/snapmgr.c, src/test/isolation2/expected/distributed_snapshot.out, src/test/isolation2/sql/distributed_snapshot.sql
Greenplum tests the visibility of heap tuples firstly using
distributed snapshot. Distributed snapshot is generated on
QD and then dispatched to QEs. Some utility statement needs
to work under the latest snapshot when executing, so that they
invoke the function `GetLatestSnapshot` in QEs. But remember
we cannot get the latest distributed snapshot.
Subtle cases are: Alter Table or Alter Domain statements on QD
get snapshot in Portal Run and then try to hold locks on the
target table in ProcessUtilitySlow. Here is the key point:
1. try to hold lock ==> it might be blocked by other transactions
2. then it will be waked up to continue
3. when it can continue, the world has changed because other transactions
then blocks it has been over
Previously, on QD we do not getsnapshot before we …
=> (6x backport) GetLatestSnapshot on QEs always return without distributed snapshot.

src/backend/commands/tablecmds.c, src/test/regress/expected/rpt.out, src/test/regress/sql/rpt.sql
This patch fixes the issue: https://github.com/greenplum-db/gpdb/issues/10224
Replicated table is not allowed to be a partition table.
So the distribution policy of an existing partition table
must not be altered to REPLICATED.
Reported-by: Heikki Linnakangas <hlinnakangas@pivotal.io>
=> Disallow to change the distribution policy to REPLICATED for partition table

.travis.yml, README.CentOS.bash, README.ubuntu.bash, gpMgmt/bin/Makefile
PyGreSQL may now be installed via pip or via Ubuntu apt.
Authored-by: Tyler Ramer <tramer@pivotal.io>
=> Document steps for installing pygresql for OSS database build

gpdb-doc/dita/analytics/postGIS.xml, gpdb-doc/dita/install_guide/platform-requirements.xml
Updates for Greenplum PostGIS 2.5.4 v2
--Add list of PostGIS extensions
--Add support for PostGIS TIGER geocoder, address standardizer and address rules files.
--Update install/uninstall instructions to use CREATE EXTENSION command
--Remove postgis_manager.sh script
--Remove PostGIS Raster limitation.
Link to updated HTML doc on a temporary GPDB draft doc site. 
https://docs-msk-gpdb7-pgis53-dev.cfapps.io/7-0/analytics/postGIS.html
=> docs - update postGIS 2.5.4 docs

src/backend/catalog/gp_toolkit.sql
Resource group we does not distinguish the per segment cpu usage, the
cpu usage reported by a segment is actually the total cpu usage of all
the segments on the host.  This is by design, not a bug.  However, in
the gp_toolkit.gp_resgroup_status_per_host view it reports the cpu usage
as the sum of all the segments on the same host, so the reported per
host cpu usage is actually N times of the actual usage, where N is the
count of the segments on that host.
Fixed by reporting the avg() instead of the sum().
Tests are not provided as the resgroup/resgroup_views did not verify cpu
usages since the beginning, because the cpu usage is unstable on
pipelines.  However, I have verified manually.
=> resgroup: fix the cpu value of the per host status view

src/test/isolation2/expected/gdd/dist-deadlock-upsert.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/gdd/dist-deadlock-upsert.sql
When to run GDD probe is undermined, but it is import for the test
gdd/dist-deadlock-upsert. If the GDD probe runs immediately after
the 2 inter-dead-locked transactions, one of the transactions will
be killed. The isolation2 framework consider the transaction being
blocked if the transaction doesn't finished in 0.5 second. So, if
the killed transaction is too early to be aborted, the test framework
sees no dead lock.
Analyzed-by: Gang Xiong <gxiong@pivotal.io>
=> Fix a flaky test for gdd/dist-deadlock-upsert

src/backend/executor/nodeBitmapIndexscan.c, src/backend/executor/nodeDynamicBitmapHeapscan.c, src/backend/executor/nodeDynamicBitmapIndexscan.c, src/backend/executor/nodeDynamicIndexscan.c, src/backend/executor/nodeDynamicSeqscan.c
Dynamic scans use scan states to initialize and keep sidecar nodes. It is done bypassing `ExecInitNode` that normally does `gpmon` packet initialization. As a result `gpmon` is not initialized for all dynamic sidecar nodes that causes `bad magic 0` warnings. Here is an example to reproduce a problem (`gp_enable_gpperfmon` should be `on`):
```sql
create table t(a int, b date, c int) distributed by (a)
partition by range (b) subpartition by list (c)
subpartition template
(subpartition s1 values (1), subpartition s2 values(2))
(start ('2020-04-01') end('2020-05-01') every(interval '1 day'));
create index t_idx on t using bitmap (b);
select count(*) from t where b = '2020-04-02';
WARNING:  gpmon - bad magic 0  (seg1 slice1 10.92.6.98:6006 pid=7727)
WARNING:  gpmon - bad magic 0  (seg1 slice1 …
```
=> Init gpmon packet for dynamic scan states

src/backend/utils/adt/ruleutils.c, src/test/regress/expected/case_gp.out, src/test/regress/sql/case_gp.sql
The clause 'CASE WHEN (arg1) IS NOT DISTINCT FROM (arg2)' dump will miss
the arg1. For example:
```
CREATE OR REPLACE VIEW xxxtest AS
SELECT
CASE
WHEN 'I will disappear' IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
The dump will lose 'I will disappear'.
```
SELECT
CASE
WHEN IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
=> Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/ref_guide/ref_guide.ditamap, gpdb-doc/dita/ref_guide/system_catalogs/catalog_ref-views.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_indexes.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_tables.xml
The views currently display access statistics only from master.
Add 6.x specific DDL for views that display access statistics from master and segments.
Also add some statistics GUCs.
--track_activities
--track_counts
Please check the GUCs set classifications are correct.
Link to HTML output on a temporary GDPB draft doc web site.
https://docs-msk-gpdb6-dev.cfapps.io/6-7/ref_guide/system_catalogs/pg_stat_indexes.html
https://docs-msk-gpdb6-dev.cfapps.io/6-7/ref_guide/system_catalogs/pg_stat_tables.html
https://docs-msk-gpdb6-dev.cfapps.io/6-7/ref_guide/config_params/guc-list.html#track_activities
https://docs-msk-gpdb6-dev.cfapps.io6-7/ref_guide/config_params/guc-list.html#track_counts
=> docs - add views pg_stat_all_tables and indexes - 6X

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/ref_guide/ref_guide.ditamap, gpdb-doc/dita/ref_guide/system_catalogs/catalog_ref-views.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_indexes.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_tables.xml
The views currently display access statistics only from master.
Add 6.x specific DDL for views that display access statistics from master and segments.
Also add some statistics GUCs.
--track_activities
--track_counts
This is a backport of a 6X_STABLE doc PR https://github.com/greenplum-db/gpdb/pull/10227
Link to HTML docs on temporary GPDB draft doc site
https://docs-msk-gpdb5-dev.cfapps.io/5270/ref_guide/system_catalogs/pg_stat_indexes.html
https://docs-msk-gpdb5-dev.cfapps.io/5270/ref_guide/system_catalogs/pg_stat_tables.html
https://docs-msk-gpdb5-dev.cfapps.io/5270/ref_guide/config_params/guc-list.html#track_activities
https://docs-msk-gpdb5-dev.cfapps.io/5270/ref_guide/config_params/guc-list.html#track_counts
=> docs - add views pg_stat_all_tables and indexes - 5X

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/ref_guide/ref_guide.ditamap, gpdb-doc/dita/ref_guide/system_catalogs/catalog_ref-views.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_indexes.xml, gpdb-doc/dita/ref_guide/system_catalogs/pg_stat_tables.xml
add catalog views
pg_stat_all_indexes
pg_stat_all_tables
Also add some statistics GUCs.
--track_activities
--track_counts
This is a port of a 6X_STABLE doc PR #10227
Link to HTML docs on temporary GPDB draft doc site
https://docs-msk-gpdb7-dev.cfapps.io/7-0/ref_guide/system_catalogs/pg_stat_indexes.html
https://docs-msk-gpdb7-dev.cfapps.io/7-0/ref_guide/system_catalogs/pg_stat_tables.html
https://docs-msk-gpdb7-dev.cfapps.io/7-0/ref_guide/config_params/guc-list.html#track_activities
https://docs-msk-gpdb7-dev.cfapps.io/7-0/ref_guide/config_params/guc-list.html#track_counts
=> docs - add views pg_stat_all_tables and indexes

src/backend/cdb/cdbutil.c, src/backend/fts/ftsmessagehandler.c, src/backend/tcop/postgres.c, src/backend/utils/misc/faultinjector.c, src/include/cdb/cdbutil.h
We had some negative tests that need to panic and thus generating core files
finally if the system is configured with corefile dump. Long ago we did
optimization to avoid generating core files in some cases. Now we found other
new scenarios that could be further optimized.
1. avoid core file generation with setrlimit() in the FATAL fault inject cod.
Some times FATAL is upgraded to PANIC (e.g.  critical section, fail when doing
QD prepare related work). So we could avoid generating core file for this
scenario also. Note even if the FATAL is not upgraded, it's fine mostly to
avoid core file generation since the process will quit soon.  With the code
change, We avoid two core files from test isolation2:crash_recovery_dtm.
2. We previously had sanity check dbid/segidx in …
=> Avoid generating core files during testing.

src/test/isolation2/expected/segwalrep/dtx_recovery_wait_lsn.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/segwalrep/dtx_recovery_wait_lsn.sql
It was disabled in 791f3b01ddc29ef002735307c485b8f08105444c.  Because there is
concern about the change of the line number in sql_isolation_testcase.py in the
test answer file. Using init file to mask the line change in
sql_isolation_testcase.py to ease the concern.
=> Re-enable test segwalrep/dtx_recovery_wait_lsn

src/backend/access/transam/xact.c, src/backend/cdb/cdbtm.c, src/backend/storage/ipc/procarray.c, src/backend/utils/time/sharedsnapshot.c, src/include/utils/sharedsnapshot.h
For cursor snapshot dump, we need to record both distributed and local
xid. So far, we only record distributed xid in the dump, as well as,
incorrectly assign distributed xid to local xid by dump read function.
Fix it.
=> Fix cursor snapshot dump xid issue

concourse/scripts/combine_cli_coverage.bash, concourse/scripts/common.bash, concourse/scripts/gsutil_sync, concourse/tasks/behave_gpdb.yml, concourse/tasks/gpMgmt_check_gpdb.yml, concourse/tasks/run_behave_on_ccp_cluster.yml
For the Python testing artifacts used by the CLI tools, utilize the
Concourse cached directories feature to create and use a pip cache dir
shared between task runs.
**Be aware**, the cache is scoped to the worker the task is run on. We do
not get a cache hit when subsequent builds run on different workers.
**Notes**
* The environment variable PIP_CACHE_DIR is used to store the cache
directory.
* Add "--retries 10" to Behave test dependency pip install commands.
=> For Python testing artifacts, introduce combination of Concourse cache and pip --cache-dir.

src/backend/cdb/cdbpath.c, src/backend/optimizer/path/allpaths.c, src/backend/optimizer/util/pathnode.c, src/include/optimizer/pathnode.h, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
This patch fixes two issues related to parameterized path logic on
master.
1. When generating unique row ID on the outer/inner side for join
JOIN_DEDUP_SEMI/JOIN_DEDUP_SEMI_REVERSE, we need to pass the param info
of outerpath/innerpath to the projection path. Otherwise we would have
problems when deciding whether a joinclause is movable to this join rel.
2. We should not pick up the parameterized path when its required outer
is beyond a Motion, since we cannot pass a param through Motion.
Fixes issue #10012
=> Fix parameterized paths

gpMgmt/bin/Makefile, python-dependencies.txt
psutil 4.0.0 is quite old, and only lists support for python 3.4. We'll
need support for python 3.6 and 3.8 as we update to python3.
Authored-by: Tyler Ramer <tramer@pivotal.io>
Pipeline: 
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-update_psutil
=> Update psutil from 4.0.0 to 5.7.0

contrib/pg_upgrade/ci/run-test-as-gpadmin.sh, contrib/pg_upgrade/test/unit/Makefile
- Add --disable-gpcloud configure flag as its not required for testing
pg_upgrade
- Remove -fsanitize=address
=> Fix pgupgrade unit tests

src/backend/cdb/cdbpullup.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
When planner adds a redistribute motion above this subplan, planner
will invoke `cdbpullup_findEclassInTargetList` to make sure the
distkey can be computed based on subplan's targetlist. When the distkey
is an expression based on some PlaceholderVar elements in targetlist,
the function `cdbpullup_missingVarWalker` does not handle it correctly.
For example, when distkey is:
```sql
CoalesceExpr [coalescetype=23 coalescecollid=0 location=586]
[args]
PlaceHolderVar [phrels=0x00000040 phid=1 phlevelsup=0]
[phexpr]
CoalesceExpr [coalescetype=23 coalescecollid=0 location=49]
[args] Var [varno=6 varattno=1 vartype=23 varnoold=6 varoattno=1]
```
and targetlist is:
```
TargetEntry [resno=1]
Var [varno=2 varattno=1 vartype=23 varnoold=2 varoattno=1]
TargetEntry [resno=2]
Var [varno=2 varattno=2 …
```
=> Make cdbpullup_missingVarWalker also consider PlaceHolderVar.

src/backend/cdb/cdbpullup.c, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/join_gp.sql
When planner adds a redistribute motion above this subplan, planner
will invoke `cdbpullup_findEclassInTargetList` to make sure the
distkey can be computed based on subplan's targetlist. When the distkey
is an expression based on some PlaceholderVar elements in targetlist,
the function `cdbpullup_missingVarWalker` does not handle it correctly.
For example, when distkey is:
```sql
CoalesceExpr [coalescetype=23 coalescecollid=0 location=586]
[args]
PlaceHolderVar [phrels=0x00000040 phid=1 phlevelsup=0]
[phexpr]
CoalesceExpr [coalescetype=23 coalescecollid=0 location=49]
[args] Var [varno=6 varattno=1 vartype=23 varnoold=6 varoattno=1]
```
and targetlist is:
```
TargetEntry [resno=1]
Var [varno=2 varattno=1 vartype=23 varnoold=2 varoattno=1]
TargetEntry [resno=2]
Var [varno=2 varattno=2 …
```
=> (6x backport) Make cdbpullup_missingVarWalker also consider PlaceHolderVar.

src/test/regress/input/appendonly.source, src/test/regress/output/appendonly.source
This fix the error:
```
---
/tmp/build/e18b2f02/gpdb_src/src/test/regress/expected/appendonly.out
2020-06-16 08:30:46.484398384 +0000
+++ /tmp/build/e18b2f02/gpdb_src/src/test/regress/results/appendonly.out
2020-06-16 08:30:46.556404454 +0000
@@ -709,8 +709,8 @@
SELECT oid FROM pg_class WHERE relname='tenk_ao2'));
case    | objmod | last_sequence | gp_segment_id
-----------+--------+---------------+---------------
+ NormalXid |      0 | 1-2900        |             1
NormalXid |      0 | >= 3300       |             0
- NormalXid |      0 | >= 3300       |             1
NormalXid |      0 | >= 3300       |             2
NormalXid |      1 | zero          |             0
NormalXid |      1 | zero          |             1
```
The flaky is because of the orca `CREATE TABLE` statement without …
=> [6X backport]Fix flaky appendonly test.

src/backend/executor/execHHashagg.c, src/test/regress/expected/partition.out, src/test/regress/expected/partition_optimizer.out, src/test/regress/sql/partition.sql
This problem manifests itself with HashAgg node on the top of Dynamic Index node and causes a segmentation fault.
Previously dynamic index scan tuples had a tuple descriptor with a partition index scan context. It caused dangling pointer segfaults in hash aggregates on the top of dynamic index scan. Hash aggregate used tuple descriptor from the first tuple it received and expected
that this descriptor would live until the aggregate node end. But as tuples returned descriptor from partition index scan context, this descriptor was valid only until the end of a first partition scan. Next partition returned a new tuple with a new descriptor (it is ok), but a hash aggregate still tried to use a tuple descriptor of the first partition causing a segfault.
The fix is to use dynamic index scan …
=> Fix desc context for dynamic index scan tuples

src/bin/pgbench/pgbench.c
The CREATE TABLE commands constructed in pgbench had the DISTRIBUTED BY
and TABLESPACE options the wrong way 'round, so that you got a syntax
error. For example:
```
$ pgbench postgres -i --tablespace "pg_default"
creating tables...
ERROR:  syntax error at or near "tablespace"
LINE 1: ...22)) with (appendonly=false) DISTRIBUTED BY (bid) tablespace...
^
```
Put the clauses in right order.
We have no test coverage for this at the moment, but PostgreSQL v11 adds
a test for this (commit ed8a7c6fcf). I noticed this while looking at test
failures with the PostgreSQL v12 merge.
=> Fix pgbench --tablespace option.

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CQueryMutators.cpp, src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/backend/gpopt/translate/CTranslatorUtils.cpp, src/include/gpopt/gpdbwrappers.h, src/include/gpopt/translate/CQueryMutators.h, src/include/gpopt/translate/CTranslatorUtils.h, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Fixing two bugs related to handling queries with window functions and refactoring the related code.
ORCA can't handle expressions on window functions like `rank() over() - 1` in a target list. To avoid these, we split `Query` blocks that contain them into two. The new lower `Query` computes the window functions, the new upper `Query` computes the expressions.
We use three mutators and walkers to help with this process:
1. Increase the `varlevelsup` of outer references in the new lower `Query`, since we now inserted a new scope above it.
2. Split expressions on window functions into the window functions (for the lower scope) and expressions with a `Var` substituted for the `WindowFunc` (for the upper scope). Also adjust the `varattno` for `Var`s that now appear in the upper scope.
3. …
=> Improve handling of target lists of window queries

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/input/resgroup/resgroup_move_query.source, src/test/isolation2/output/resgroup/resgroup_move_query.source
When move a query to a resource group whose memory_limit is 0, the available
memory is the current available global shared memory.
=> [6X backport]Move to a resource group with memory_limit 0

src/backend/access/transam/xact.c, src/backend/cdb/cdblocaldistribxact.c, src/backend/storage/ipc/procarray.c, src/test/isolation2/expected/distributed_transactions.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/distributed_transactions.sql
When the error happens after ProcArrayEndTransaction, it will recurse back to
AbortTransaction, we need to make sure it will not generate extra WAL record
and not fail the assertions.
=> [6X backport]Fix a recursive AbortTransaction issue

gpMgmt/bin/gppylib/programs/clsInjectFault.py, src/backend/access/transam/xact.c, src/backend/cdb/cdblocaldistribxact.c, src/backend/storage/ipc/procarray.c, src/backend/utils/misc/faultinjector.c, src/include/utils/faultinjector.h, src/test/isolation2/expected/distributed_transactions.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/distributed_transactions.sql
When the error happens after ProcArrayEndTransaction, it will recurse back to
AbortTransaction, we need to make sure it will not generate extra WAL record
and not fail the assertions.
=> [5X backport]Fix a recursive AbortTransaction issue

src/backend/optimizer/plan/planner.c, src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/sql/bfv_aggregate.sql
In the multiphase aggregation logic, cdb_grouping_planner would change
the parsetree, especially the range table list and targetlist. But for
EquivalenceClasses, their expressions are not changed accordingly, and
they are still based on the original range table list. As a result, when
we apply ORDER BY above the multiphase aggregation, in high possibility
we would be using the wrong EC for pathkey.
This PR clones a new root and resets its EC list when re-writing
sort_pathkeys, which is very hacky but works for this case.
Fixes issue #10231
=> Fix wrong results on multiphase aggregation with ORDER BY

src/backend/cdb/cdbutil.c
* Problem:
getDnsCachedAddress() always returns empty string if the hostname only
has IPv6 addresses
* Root cause:
Array hostinfo[] is redeclared in code section for IPv6, so the real
lookup result never returns.
* How to reproduce:
You can reproduce this issue even you don't have pure IPv6 environment
1. Assign a IPv6 address for your default net device
sudo ip -6 addr add 2401::1234/128 dev ${netdev}
2. Add the address to /etc/hosts with a dummy hostname, for example
2401::1234/128	ipv6host
3. Create external table using the dummy hostname
create external table test_ext_ipv6(a int) location('gpfdist://ipv6host:8080/data_file') format 'csv';
4. Launch gpfdist
5. Run test SQL
select * from test_ext_ipv6
Then an error will be reported with an empty address in url:
ERROR:  connection with …
=> Fix DNS lookup issue for pure IPv6 addresses in URLs

src/backend/cdb/cdbpartition.c, src/backend/commands/analyze.c, src/backend/commands/analyzeutils.c, src/include/cdb/cdbpartition.h, src/include/commands/analyzeutils.h
aggregate_leaf_partition_MCVs() and aggregate_leaf_partition_histograms()
functions did catalog lookups to count how many leaf partitions a root
table has. Why? Because the caller passes two arrays as inputs, with an
entry for each partition, and the functions need to know how large the
input arrays are. That's overly complicated, of course: the caller can
simply pass the size of the arrays as an argument. That's much more robust
too, I think the current code would crash and burn if the partition
hierarchy was modified concurrently. I'm not sure if that's a live bug, or
if we're holding locks that prevent that, but let's keep things simple in
any case.
This removes the last callers of rel_get_leaf_children_relids() function,
so remove that altogether.
=> Clean up the internal functions to merge partition stats a bit.

contrib/pg_upgrade/greenplum/check_gp.c, contrib/pg_upgrade/test/integration/expected/upgraded_foreign_key_constraint.out, contrib/pg_upgrade/test/integration/gpdb5_schedule, contrib/pg_upgrade/test/integration/gpdb6_schedule, contrib/pg_upgrade/test/integration/input/foreign_key_constraint.source, contrib/pg_upgrade/test/integration/output/foreign_key_constraint.source, contrib/pg_upgrade/test/integration/sql/upgraded_foreign_key_constraint.sql
partitions
If a root partition contains a foreign key constraint, pg_dump will
create the DDL in the below format:
```
CREATE TABLE public.pt (
a integer
)
DISTRIBUTED BY (a) PARTITION BY RANGE(a)
( START (1) END (3) EVERY (2) WITH (tablename='pt_1_prt_1', appendonly=false ) );
ALTER TABLE ONLY public.pt
ADD CONSTRAINT pt_fkey FOREIGN KEY (a) REFERENCES public.mfk(a);
```
When the ALTER statement is executed, the below error is observed:
```
ERROR:  can't add a constraint to "pt"; it is a partitioned table or part thereof
```
Foreign key constraint on root partitions must be dropped before
upgrading the cluster.
=> pg_upgrade: Add check to identify foreign key constraint on root

src/backend/parser/analyze.c, src/test/regress/expected/bfv_olap.out, src/test/regress/expected/bfv_olap_optimizer.out
This is a port of part of PR https://github.com/greenplum-db/gpdb/pull/10306.
This fixes https://github.com/greenplum-db/gpdb/issues/10143.
According to asubramanya, porting the entire
https://github.com/greenplum-db/gpdb/pull/10306 would have led to lots
of failures.
The fix places subqueries in the target list into the lower scope when separating groupby from window queries. We know that the subquery won't contain any window functions, because SQL does not allow that, so it is safe to do. Placing the subquery into the lower scope means that any outer references in the subquery that refer to the original scope Q are still valid, because the new lower scope Q'' will have the same target list. That was the bug in the pre-existing code: When we put the subquery in the upper scope Q', outer …
=> Fix issue 10143, correlated subquery with agg and windowfunc

gpMgmt/bin/gpinitsystem, gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature
Mirror registration passes through several steps at the moment:
1. CREATE_QE_ARRAY (QE_MIRROR_ARRAY is ordered by content)
2. ARRAY_REORDER (QE_MIRROR_ARRAY is ordered by port)
3. CREATE_ARRAY_SORTED_ON_CONTENT_ID (form QE_MIRROR_ARRAY_SORTED_ON_CONTENT_ID
on a base of QE_MIRROR_ARRAY)
4. REGISTER_MIRRORS (walk through QE_MIRROR_ARRAY, register mirrors with
pg_catalog.gp_add_segment_mirror on master's gp_segment_configuration
and update QE_MIRROR_ARRAY with returned dbids)
5. CREATE_SEGMENT (walk through QE_MIRROR_ARRAY_SORTED_ON_CONTENT_ID with old
dbids and create mirrors on segment hosts with pg_basebackup)
The problem is in a step 4 - we update the wrong array (QE_MIRROR_ARRAY instead
of QE_MIRROR_ARRAY_SORTED_ON_CONTENT_ID). Because of that we get inconsistency
between mirror dbids …
=> Fix dbid inconsistency on spread mirroring

gpdb-doc/book/config.yml, gpdb-doc/dita/admin_guide/external/pxf-overview.xml, gpdb-doc/dita/analytics/overview.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_EXTERNAL_TABLE.xml, gpdb-doc/dita/ref_guide/sql_commands/CREATE_PROTOCOL.xml, gpdb-doc/dita/security-guide/topics/SecuringGPDB.xml, gpdb-doc/dita/utility_guide/utility-programs.xml, gpdb-doc/dita/utility_guide/utility_guide.ditamap
in this PR:
- change some pxf links to xref to the dita landing page
- use relative external links when possible to refer to pxf docs, as they are moving to a new docset located at _greenplumdocsurl_/pxf
- xref to pxf docset version 5-13
- add some link exclusions for open source book
- misc formatting edits
=> docs - update some pxf xrefs, add excludes

gpMgmt/bin/gpcheckcat
These NOTICEs:
Connected as user 'heikki' to database 'postgres', port '5432', gpdb version '7.0'
-------------------------------------------------------------------
Batch size: 4
Performing test 'duplicate'
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'segid' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column(s) named 'segid' as the Greenplum Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key …
=> Silence useless NOTICEs emitted by gpcheckcat.

concourse/scripts/common.bash, concourse/tasks/behave_gpdb.yml, concourse/tasks/gpMgmt_check_gpdb.yml, concourse/tasks/run_behave_on_ccp_cluster.yml
For the Python testing artifacts used by the CLI tools, utilize the
Concourse cached directories feature to create and use a pip cache dir
shared between task runs.
Be aware, the cache is scoped to the worker the task is run on. We do
not get a cache hit when subsequent builds run on different workers.
**Notes**
* The environment variable PIP_CACHE_DIR is used to store the cache directory.
* Add "--retries 10" to Behave test dependency pip install commands.
The PR for the master branch: https://github.com/greenplum-db/gpdb/pull/10296
=> 6X_Stable back port: For Python testing artifacts, introduce combination of Concourse cache and PIP_CACHE_DIR

src/backend/gpopt/gpdbwrappers.cpp, src/include/gpopt/gpdbwrappers.h
Most of the code that uses fault injector is in the preprocess block.
But the function gpdb::InjectFaultInOptTasks() isn't guarded by
the macro FAULT_INJECTOR.
See issue: https://github.com/greenplum-db/gpdb/issues/10341
=> Enable to disable fault injector manually

gpMgmt/bin/gpexpand
When cleaning up the master-only files on the new segments we used to do
the job one by one, when there are tens or hundreds of segments it can
be very slow.
Now we cleanup in parallel.
(cherry picked from commit 857763ae076b70943714ebc2b8d261c2ce4e1be0)
=> 6X: gpexpand: cleanup new segments in parallel

src/backend/executor/execHHashagg.c, src/test/regress/expected/partition.out, src/test/regress/expected/partition_optimizer.out, src/test/regress/sql/partition.sql
This problem manifests itself with HashAgg on the top of
DynamicIndexScan node and can cause a segmentation fault.
1. A HashAgg node initializes a tuple descriptor for its hash
slot using a reference from input tuples (coming from
DynamicIndexScan through a Sequence node).
2. At the end of every partition index scan in DynamicIndexScan
we unlink and free unused memory chunks and reset partition's
memory context. It causes a total destruction of all objects in
the context including partition index tuple descriptor used in a
HashAgg node.
As a result we get a dangling pointer in HashAgg on switching to
a new index partition during DynamicIndexScan that can cause a
segfault.
Backport commit: 41ce55bf796d76f121ef942ebb3592f8fc0fa907 to 6X.
=> [6X Backport]Fix tupdesc dangling pointer segfault in HashAgg

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, src/backend/commands/tablecmds.c
For non partition table, we will skip gpexpand foreign tables,
but for partition table, when one of its child parition is a
foreign table, we error out when gpexpand. This is not a correct
behavior.
Since data of foreign table is located outside gpdb, skip these
tables when gpexpand is enough.
Co-Authored-by: Ning Yu <nyu@pivotal.io>
=> Skip foreign table when gpexpand

src/backend/commands/analyze.c, src/test/regress/expected/partition.out, src/test/regress/expected/partition_optimizer.out, src/test/regress/sql/partition.sql
Analyze error'd with "ERROR: unsupported table type" if external table
is part of partition hierarchy. Also, that blocks analyzing database
wide as can't analyze such partitions. This commit adds check to skip
external tables during acquire_inherited_sample_rows().
Fixes #9506 github issue.
Co-authored-by: Alexandra Wang <lewang@pivotal.io>
This works on master (well there are relcache reference leak warnings which needs investigation) but fails on 6X_STABLE hence opening PR against GPDB6 only.
=> Skip external tables during analyze

src/backend/commands/tablespace.c, src/test/regress/input/gp_tablespace.source, src/test/regress/output/gp_tablespace.source
If the directory of tablespace does not exist, we should got a
error on commit transaction. But error on commit transaction will
cause a panic. So the directory of tablespace should be checked
so that we can avoid panic.
=> Check whether the directory exists when deleting the tablespace

src/backend/cdb/cdbutil.c
It could be called in utility mode, however we should avoid calling into
FtsNotifyProber() for such case. Ideally we could do that if we access the
master node and postgres is not in single mode, but it seems that we do not that
need.
Here is the stack of the issue I encountered.
0  0x0000003397e32625 in raise () from /lib64/libc.so.6
1  0x0000003397e33e05 in abort () from /lib64/libc.so.6
2  0x0000000000b39844 in ExceptionalCondition (conditionName=0xeebac0 "!(Gp_role == GP_ROLE_DISPATCH)", errorType=0xeebaaf "FailedAssertion",
fileName=0xeeba67 "cdbfts.c", lineNumber=101) at assert.c:66
3  0x0000000000bffb1e in FtsNotifyProber () at cdbfts.c:101
4  0x0000000000c389a4 in cdbcomponent_getCdbComponents () at cdbutil.c:714
5  0x0000000000c26e3a in gp_pgdatabase__ (fcinfo=0x7ffd7b009c10) at …
=> Fix assert failure in cdbcomponent_getCdbComponents()

src/backend/catalog/gp_toolkit.sql
Resource group we does not distinguish the per segment cpu usage, the
cpu usage reported by a segment is actually the total cpu usage of all
the segments on the host.  This is by design, not a bug.  However, in
the gp_toolkit.gp_resgroup_status_per_host view it reports the cpu usage
as the sum of all the segments on the same host, so the reported per
host cpu usage is actually N times of the actual usage, where N is the
count of the segments on that host.
Fixed by reporting the avg() instead of the sum().
Tests are not provided as the resgroup/resgroup_views did not verify cpu
usages since the beginning, because the cpu usage is unstable on
pipelines.  However, I have verified manually.
(cherry picked from commit …
=> 6X: resgroup: fix the cpu value of the per host status view

src/backend/utils/adt/ruleutils.c, src/test/regress/expected/case_gp.out, src/test/regress/sql/case_gp.sql
For below example:
```
CREATE TABLE mytable2 (
key character varying(20) NOT NULL,
key_value character varying(50)
) DISTRIBUTED BY (key);
CREATE VIEW aaa AS
SELECT
CASE mytable2.key_value
WHEN IS NOT DISTINCT FROM 'NULL'::text THEN 'now'::text::date
ELSE to_date(mytable2.key_value::text, 'YYYYMM'::text)
END AS t
FROM mytable2;
```
mytable2.key_value will cast to type date. For clause `(ARG1) IS NOT
DISTINCT FROM (ARG2)`, this leads ARG1 to become a RelabelType node and
contains CaseTestExpr node in RelabelType->arg.
So when dumping the view, it'll dump extra `CASE_TEST_EXPR` as below
```
select pg_get_viewdef('notdisview3',false);
pg_get_viewdef
-----------------------------------------------------------------------------
SELECT …
```
=> Fix a cornor case which dump CaseTestExpr for IS NOT DISTINCT FROM.

src/backend/utils/adt/ruleutils.c, src/test/regress/expected/case_gp.out, src/test/regress/sql/case_gp.sql
The clause 'CASE WHEN (arg1) IS NOT DISTINCT FROM (arg2)' dump will miss
the arg1. For example:
```
CREATE OR REPLACE VIEW xxxtest AS
SELECT
CASE
WHEN 'I will disappear' IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
The dump will lose 'I will disappear'.
```
SELECT
CASE
WHEN IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
I dig into commit a453004, if left-hand argument for `IS NOT DISTINCT
FROM` contains any `CaseTestExpr` node, the left-hand arg should be
omit. `CaseTestExpr` is a placeholder for CASE expression.
=> [6X Backport]Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.

src/backend/utils/adt/ruleutils.c, src/test/binary_swap/test_binary_swap_pre.sql, src/test/regress/expected/case_gp.out, src/test/regress/sql/case_gp.sql
The clause 'CASE WHEN (arg1) IS NOT DISTINCT FROM (arg2)' dump will miss
the arg1. For example:
```
CREATE OR REPLACE VIEW xxxtest AS
SELECT
CASE
WHEN 'I will disappear' IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
The dump will lose 'I will disappear'.
```
SELECT
CASE
WHEN IS NOT DISTINCT FROM ''::text
THEN 'A'::text
ELSE 'B'::text
END AS t;
```
I dig into commit a453004, if left-hand argument for `IS NOT DISTINCT
FROM` contains any `CaseTestExpr` node, the left-hand arg should be
omit. `CaseTestExpr` is a placeholder for CASE expression.
=> [5X Backport]Fix CASE WHEN IS NOT DISTINCT FROM clause incorrect dump.

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, src/backend/commands/tablecmds.c
For non partition table, we will skip gpexpand external tables,
but for partition table, when one of its child parition is a
external table, we error out when gpexpand. This is not a correct
behavior.
Since data of foreign table is located outside gpdb, skip these
tables when gpexpand is enough.
Co-Authored-by: Ning Yu nyu@pivotal.io
(cherry picked from commit b9691eba051c37005ba9f038171cd8849b15cea3)
=> [BACKPORT] Skip foreign table when gpexpand

concourse/pipelines/5X_STABLE-generated.yml, concourse/pipelines/gen_pipeline.py
This change has already been made on 6X_STABLE and master, but now that python2 is end-of-life and distributions are dropping support for it setting 5X_STABLE pipelines has gotten a little more difficult.
This removes some of that friction.
=> Update gen_pipeline to work with python3

README.md, README.ubuntu.bash
While installing ORCA in Ubuntu 18.04 I ran into some issues while
trying to install gp-xerces. During the build, Greenplum was trying to
link against the installed xerces `libxerces-c-dev`, which is installed
by running the `./README.ubuntu.bash` script. By default, Ubuntu 18.04
will install xerces 3.2, which is incompatible with the version used by
Greenplum 6.
=> README: Fix documentation to install Greenplum with ORCA in Ubuntu

src/backend/utils/mmgr/aset.c, src/backend/utils/mmgr/mcxt.c, src/include/nodes/memnodes.h, src/include/utils/memutils.h
`localAllocated` is not set to 0 when resetting the memory context, which
makes the statistics data incorrect. `localAllocated` is used to account
the local usage of the memory context alone. It's better to expose this
value to track how much memory allocated from the memory context, which
is helpful to determine whether the memory leaks or not in a specific
memory context.
Size is an unsigned integer, and `MEMORY_ACCOUNT_UPDATE_ALLOCATED` uses
the opposite value for subtraction. Since they have the same bit width
and the same bit results. We'd avoid using it this way.
=> Fix memory accounting

src/backend/gporca/libgpopt/src/engine/CEngine.cpp, src/backend/gporca/libgpopt/src/search/CSearchStage.cpp
Previously, CTimerUser didn't initialize timer, so the elapsed time provided by
Orca was not meaningful, sometimes confusing.
When traceflag T101012 is turned on, we can see the following trace message:
```
[OPT]: Memo (stage 0): [20 groups, 0 duplicate groups, 44 group expressions, 4 activated xforms]
[OPT]: stage 0 completed in 860087 msec,  plan with cost 1028.470667 was found
[OPT]: <Begin Xforms - stage 0>
......
[OPT]: <End Xforms - stage 0>
[OPT]: Search terminated at stage 1/1
[OPT]: Total Optimization Time: 67ms
```
As shown above, the stage 0 elapsed timer is much greater than the total
optimization time, which is obviously incorrect.
=> Fix Orca optimizer search stage couldn't measure elapsed time correctly

src/backend/cdb/cdbvars.c, src/backend/replication/gp_replication.c, src/backend/replication/test/gp_replication_test.c, src/backend/replication/walsender.c, src/backend/storage/ipc/ipci.c, src/backend/utils/misc/guc_gp.c, src/include/cdb/cdbvars.h, src/include/replication/gp_replication.h, src/include/replication/walsender_private.h, src/include/storage/lwlock.h, src/include/utils/unsync_guc_name.h, src/test/isolation2/expected/segwalrep/replication_keeps_crash.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/segwalrep/replication_keeps_crash.sql
For GPDB FTS, if the primary, mirror replication keeps crash
continuously and attempt to crate replication connection too many times,
FTS should mark the mirror down. Otherwise, it may block other
processes.
If the WAL starts streaming, clear the attempt count to 0. This is because the blocked
transaction can only be released once the WAL in streaming state.
The solution for this is:
1. Use ` FTSReplicationStatus` which under `gp_replication.c`  to track current primary-mirror
replication status. This includes:
- A continuous failure counter. The counter gets reset once the replication
starts streaming, or replication restarted.
- A record of the last disconnect timestamp which is refactored from
`WalSnd` slot.
The reason for moving this is: When FTS probe happens, the `WalSnd`
slot may …
=> [6X Backport]Let FTS mark mirror down if replication keeps crash.

gpAux/Makefile, gpMgmt/bin/Makefile, gpMgmt/bin/generate-greenplum-path.sh, gpMgmt/bin/test-generate-greenplum-path.bash
- generate-greenplum-path.sh use second parameter yes to generate
PYTHONHOME
- ONLY gpAux need to run this script with second parameter yes, since
in GPDB5 we always vendor python.
- developer build on their box won't be impacted by this change, since
regular build doesn't have second parameter, hence PYTHONHOME will be
skipped.
- We added test-generate-greeplum-path.bash to verify the correctness of
the script.
Note: This PR is related to PR https://github.com/greenplum-db/gpdb/pull/10409
[#173567726]
Authored-by: Tingfang Bao <baotingfang@gmail.com>
=> Conditionally set the PYTHONHOME in greenplum-path.sh

src/backend/access/aocs/aocs_compaction.c, src/backend/access/appendonly/aomd.c, src/backend/access/appendonly/appendonly_compaction.c, src/include/access/aomd.h, src/test/regress/input/aocs.source, src/test/regress/input/appendonly.source, src/test/regress/output/aocs.source, src/test/regress/output/appendonly.source
The path constructed in `OpenAOSegmentFile()` didn't take into account
"t_" semantic of filename. Ideally, the correct filename is passed to
function, so no need to construct the same.
Would be better if can move `MakeAOSegmentFileName()` inside
`OpenAOSegmentFile()`, as all callers call it except
`truncate_ao_perFile()`, which doesn't fit that model.
This needs to be back-ported to 6X_STABLE as issue exists there too.
=> Fix vacuum on temporary AO table

src/backend/gporca/concourse/test_orca_pipeline.yml
We've moved the repo that holds trigger commits to a private repo since
there wasn't anything interesting there.
=> Move slack command trigger repo

gpAux/Makefile
=> Fix enterprise builds for Ubuntu16.04 to not set PYTHONHOME

src/backend/commands/tablecmds.c, src/test/regress/expected/inherit.out, src/test/regress/expected/inherit_optimizer.out, src/test/regress/sql/inherit.sql
Currently, replicated tables are not allowed to inherit a parent
table. But ALTER TABLE .. INHERIT can pass around the restriction.
See: https://github.com/greenplum-db/gpdb/issues/10141
On the other hand, a replicated table is allowed to be inherited
by a hash distributed table. It makes things much complicated.
When the parent table is declared as a replicated table inherited by
a hash distributed table, its data on the parent is replicated
but the data on the child is hash distributed. When running
`select * from parent;`, the generated plan is:
```
gpadmin=# explain select * from parent;
QUERY PLAN
-----------------------------------------------------------------------------
Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..4.42 rows=14 width=6)
->  Append  (cost=0.00..4.14 rows=5 …
```
=> Disallow the replicated table inherit or to be inherited

gpcontrib/gp_replica_check/gp_replica_check.c
When there is a big lag between primary and mirror replay, gp_replica_check
will fail if the checkpoint is not replayed in about 60 seconds.
=> Fix flaky test gp_replica_check

gpdb-doc/markdown/pxf/gphdfs-pxf-migrate.html.md.erb
gphdfs to pxf migration topic remains in greenplum docs.  the upcoming pxf v5.14 supports avro compression, so:
- remove the limitation
- note parallel CODEC_LEVEL option
=> docs - gphdfs2pxf migration pxf supports avro compression

gpMgmt/bin/gpcheckcat, gpMgmt/bin/gpsd, gpMgmt/bin/minirepro
Make some utilities search path safe, so it'll not calling any external
functions that has same name with our built-in functions.
This fix does not guarantee to fix CVE-2018-1058.
Co-authored-by: Jamie McAtamney <jmcatamney@pivotal.io>
Co-authored-by: Jacob Champion <pchampion@pivotal.io>
Co-authored-by: Shoaib Lari <slari@pivotal.io>
(cherry picked from commit 070d6221c0c4439db9489ac78e01c14fd784e987)
=> [5X Backport] gpMgmt: make additional utilities search_path-safe

gpMgmt/bin/gpcheckcat, gpMgmt/bin/gppylib/operations/segment_reconfigurer.py, gpMgmt/bin/gpsd, gpMgmt/bin/minirepro
Make some utilities search path safe, so it'll not calling any external
functions that has same name with our built-in functions.
This fix does not guarantee to fix CVE-2018-1058.
Backport from 070d6221c0c4439db9489ac78e01c14fd784e987.
Co-authored-by: Jamie McAtamney <jmcatamney@pivotal.io>
Co-authored-by: Jacob Champion <pchampion@pivotal.io>
Co-authored-by: Shoaib Lari <slari@pivotal.io>
=> [6X Backport] gpMgmt: make additional utilities search_path-safe

src/backend/executor/nodeBitmapHeapscan.c, src/test/regress/expected/co_nestloop_idxscan.out, src/test/regress/expected/co_nestloop_idxscan_optimizer.out, src/test/regress/sql/co_nestloop_idxscan.sql
When ExecReScanBitmapHeapScan get executed, bitmap state (tbmiterator
and tbmres) gets freed in freeBitmapState. So the tbmres is NULL, and we
need to reinit bitmap state to start scan from the beginning and reset AO/AOCS
bitmap pages' flags(baos_gotpage, baos_lossy, baos_cindex and baos_ntuples).
Especially when ExecReScan happens on the bitmap append only scan and
not all the matched tuples in bitmap are consumed, for example, Bitmap
Heap Scan as inner plan of the Nest Loop Semi Join. If tbmres not get init,
and not read all tuples in last bitmap, BitmapAppendOnlyNext will assume the
current bitmap page still has data to return. but bitmap state already freed.
From the code, for Nest Loop Semi Join, when a match find, a new outer slot is
requested, and then `ExecReScanBitmapHeapScan` …
=> [6X Backport] Fix bitmap scan crash issue for AO/AOCS table.

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
column 'vpinfo' in pg_aoseg.pg_aocsseg_xxx record the 'eof' of each attribute
in the AOCS table, the number of attributes in 'vpinfo' should be the same as
the number of attributes in 'pg_attribute'
=> gpcheckcat: add the check of vpinfo consistency

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
column 'vpinfo' in pg_aoseg.pg_aocsseg_xxx record the 'eof' of each attribute
in the AOCS table, the number of attributes in 'vpinfo' should be the same as
the number of attributes in 'pg_attribute'
=> [5X backport] gpcheckcat: add the check of vpinfo consistency

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
column 'vpinfo' in pg_aoseg.pg_aocsseg_xxx record the 'eof' of each attribute
in the AOCS table, the number of attributes in 'vpinfo' should be the same as
the number of attributes in 'pg_attribute'
=> [6X backport] gpcheckcat: add the check of vpinfo consistency

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
The entry in aocsseg table might be compacted and waiting for drop, so we
should use 'state' to filter the unused entry.
=> gpcheckcat: fix gpcheckcat vpinfo issue

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
The entry in aocsseg table might be compacted and waiting for drop, so we
should use 'state' to filter the unused entry.
=> [5X backport] gpcheckcat: fix gpcheckcat vpinfo issue

gpMgmt/bin/gpcheckcat, gpMgmt/test/behave/mgmt_utils/gpcheckcat.feature
The entry in aocsseg table might be compacted and waiting for drop, so we
should use 'state' to filter the unused entry.
=> [6X backport] gpcheckcat: fix gpcheckcat vpinfo issue

src/backend/gporca/data/dxl/minidump/UnionWithCTE.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/server/CMakeLists.txt
Previously, the PdrgpcrsAddEquivClass function would modify the input
colref set. This does not appear intentional, as this same reference may
be accessed in other places. This caused Orca to fall back to planner in
some cases during translation with "Attribute number 0 not found in
project list".
Co-authored-by: mubo.fy <mubo.fy@alibaba-inc.com>
Co-authored-by: Chris Hajas <chajas@pivotal.io>
Co-authored-by: Hans Zeller <hzeller@vmware.com>
Original PR: https://github.com/greenplum-db/gporca/pull/594
=> Fix colrefs getting mangled when merging equivalent classes in Orca

src/backend/gporca/data/dxl/minidump/UnionWithCTE.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CUtils.h, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/server/CMakeLists.txt
Previously, the PdrgpcrsAddEquivClass function would modify the input
colref set. This does not appear intentional, as this same reference may
be accessed in other places. This caused Orca to fall back to planner in
some cases during translation with "Attribute number 0 not found in
project list".
Co-authored-by: mubo.fy <mubo.fy@alibaba-inc.com>
Co-authored-by: Chris Hajas <chajas@pivotal.io>
Co-authored-by: Hans Zeller <hzeller@vmware.com>
(cherry picked from commit 84c027afdff13f1d91447a5a88809f6e85399a1b)
=> [6X] Fix colrefs getting mangled when merging equivalent classes in Orca

gpMgmt/bin/gppylib/operations/package.py
Commit 21a2cb27b38117cce90c4ff06d8d447842c5acf1, added in PR #10361,
updated yaml and changed yaml.load to yaml.safe_load in gpload.
gppkg uses yaml as well, but references were not updated - this commit
resolves that discrepancy.
Co-authored-by: Tyler Ramer <tramer@vmware.com>
Co-authored-by: Jamie McAtamney <jmcatamney@vmware.com>
=> Use yaml safe_load in gppkg

NOTICE, README.amazon_linux, README.docker.md, README.ubuntu.bash, gpMgmt/Makefile, gpMgmt/bin/Makefile, gpMgmt/bin/gpmovemirrors, gpMgmt/bin/gppylib/mainUtils.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gppylib/test/unit/test_unit_mainUtils.py, python-dependencies.txt, src/tools/docker/centos6/Dockerfile, src/tools/docker/centos7/Dockerfile, src/tools/docker/ubuntu/Dockerfile
[Lockfile](https://pypi.org/project/lockfile/) has not been maintained
since around 2015. Further, the functionality it provided seems poor - a
review of the code indicated that it used the presence of the PID file
itself as the lock - in Unix, using a file's existence followed by a
creation is not atomic, so a lock could be prone to race conditions.
The lockfile package also did not clean up after itself - a process
which was destroyed unexpectedly would not clear the created locks, so
some faulty logic was added to mainUtils.py, which checked to see if a
process with the same PID as the lockfile's creator was running. This
is obviously failure prone, as a new process might be assigned the same
PID as the old lockfile's owner, without actually being the same process.
(Of note, the …
=> [6X backport] Remove lockfile from mainUtils

gpcontrib/gp_replica_check/gp_replica_check.c
When there is a big lag between primary and mirror replay, gp_replica_check
will fail if the checkpoint is not replayed in about 60 seconds. Extend the
timeout to 600 seconds to reduce the chance of flaky.
=> [6X backport] Fix flaky test gp_replica_check

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk
Corresponding Orca commit: "Fix colrefs getting mangled when merging equivalent classes in Orca"
=> Bump Orca version to v3.107.0

gpAux/client/install/src/windows/CreatePackage.bat
Local fork at gpMgmt/bin/ext/yaml was removed by 8d6c305998. Unpack
it from gpMgmt/bin/pythonSrc/ext just like pygresql when making windows
client package.
=> Fix windows client build missing pyyaml issue

src/backend/replication/gp_replication.c, src/test/isolation2/expected/segwalrep/replication_keeps_crash.out, src/test/isolation2/sql/segwalrep/replication_keeps_crash.sql
Find an assertion that may not match when mark mirror down happens before
walsender exit, which will free the replication status before walsender
exit and try to record disconnect info. Which lead the segment crash
and starts to recover.
Also, remove the set `gp_fts_probe_retries to 1` which may cause FTS probe failed
under some extremes environment.
This was first added to reduce the test time. Since reduce the `gp_fts_replication_attempt_count` also
save the test time, so skip alter `gp_fts_probe_retries`.
=> Fix flaky test for replication_keeps_crash.

src/backend/replication/gp_replication.c, src/test/isolation2/expected/segwalrep/replication_keeps_crash.out, src/test/isolation2/sql/segwalrep/replication_keeps_crash.sql
Find an assertion that may not match when mark mirror down happens before
walsender exit, which will free the replication status before walsender
exit and try to record disconnect info. Which lead the segment crash
and starts to recover.
Also, remove the set `gp_fts_probe_retries to 1` which may cause FTS probe failed
under some extremes environment.
This was first added to reduce the test time. Since reduce the `gp_fts_replication_attempt_count` also
save the test time, so skip alter `gp_fts_probe_retries`.
=> [6X Backport] Fix flaky test for replication_keeps_crash.

src/backend/cdb/cdbgroup.c, src/test/regress/expected/qp_functions_idf.out, src/test/regress/sql/qp_functions_idf.sql
Flow in AggNode has wrong TargetList. AggNode has a different
TargetList from its child nodes, so copying flow directly from the
child node to AggNode is completely wrong. We need to use pullupflow to
generate this TargetList in creating the within group plan with single
QE.
=> Fix the assert failure on pullup flow in within group

gpMgmt/bin/minirepro
The approach of using a connection string is fragile in the event of an
update to pygresql or missing values, as demonstrated by errors after
update of pygresql in f5758021be347aea069c3ef930bae6354a2dd8db
Instead, we'll use a named value as arguments to pgdb.connect(),
following the example of dbconn.py
Addresses https://github.com/greenplum-db/gpdb/issues/10435 
Authored-by: Tyler Ramer <tramer@vmware.com>
=> Used dictionary to form connection string in minirepro

contrib/pgrowlocks/pgrowlocks.c
I encounter the following When I build master branch on Ubuntu 16.04 with gcc 6.3.0.
```
pgrowlocks.c: In function ‘pgrowlocks’:
pgrowlocks.c:132:8: error: ‘rel’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
htsu = HeapTupleSatisfiesUpdate(rel, tuple,
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
GetCurrentCommandId(false),
~~~~~~~~~~~~~~~~~~~~~~~~~~~
scan->rs_cbuf);
~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
<builtin>: recipe for target 'pgrowlocks.o' failed
make[1]: *** [pgrowlocks.o] Error 1
make[1]: Leaving directory '/home/japin/greenplum-db/gpdb/contrib/pgrowlocks'
Makefile:102: recipe for target 'all-pgrowlocks-recurse' failed
make: *** [all-pgrowlocks-recurse] Error 2
```
This commit fix this bug.
=> Fix uninitialized variable in pgrowlocks

src/backend/cdb/cdbsubselect.c, src/test/regress/expected/subselect_gp.out, src/test/regress/expected/subselect_gp_optimizer.out, src/test/regress/sql/subselect_gp.sql
Currently GPDB tries to pull up EXPR sublinks to inner joins. For query
select * from foo where foo.a >
(select avg(bar.a) from bar where foo.b = bar.b);
GPDB would transform it to:
select * from foo inner join
(select bar.b, avg(bar.a) as avg from bar group by bar.b) sub
on foo.b = sub.b and foo.a > sub.avg;
To do that, GPDB needs to recurse through the quals in sub-select and
extract quals of form 'outervar = innervar' and then build new
SortGroupClause items and TargetEntry items based on these quals for
sub-select.
But for quals of form 'function(outervar, innervar1) = innvervar2', GPDB
handles them incorrectly and will cause wrong results issues as
described in issue #9615.
This patch fixes this issue by treating these kinds of quals as not
compatible correlated and thus the …
=> Fix pulling up EXPR sublinks

src/backend/cdb/cdbpath.c, src/backend/cdb/cdbpathlocus.c, src/backend/optimizer/path/allpaths.c, src/backend/optimizer/plan/createplan.c, src/backend/optimizer/plan/subselect.c, src/backend/optimizer/util/clauses.c, src/backend/optimizer/util/pathnode.c, src/backend/parser/analyze.c, src/include/cdb/cdbpath.h, src/include/nodes/relation.h, src/include/optimizer/pathnode.h, src/test/regress/expected/bfv_planner_optimizer.out, src/test/regress/expected/insert_conflict.out, src/test/regress/expected/qp_functions_in_subquery.out, src/test/regress/expected/rpt_optimizer.out, src/test/regress/sql/bfv_planner.sql, src/test/regress/sql/insert_conflict.sql, src/test/regress/sql/rpt.sql
General and segmentGeneral locus imply that if the corresponding slice
is executed in many different segments should provide the same result
data set. Thus, in some cases, General and segmentGeneral can be
treated like broadcast.
But what if the segmentGeneral and general locus path contain volatile
functions? volatile functions, by definition, do not guarantee results
of different invokes. So for such cases, they lose the property and
cannot be treated as *general. Previously, Greenplum planner
does not handle these cases correctly. Limit general or segmentgeneral
path also has such issue.
The fix idea of this commit is: when we find the pattern (a general or
segmentGeneral locus paths contain volatile functions), we create a
motion path above it to turn its locus to singleQE and then …
=> Correct plan of general & segmentGeneral path with volatiole functions.

src/backend/cdb/dispatcher/cdbdisp.c, src/backend/cdb/dispatcher/cdbdisp_query.c, src/include/cdb/cdbdisp.h, src/test/regress/expected/guc_gp.out, src/test/regress/sql/guc_gp.sql
Reader gangs use local snapshot to access catalog, as a result, it will
not synchronize with the global snapshot from write gang which will lead
to inconsistent visibilty of catalog table. Considering the case:
select * from t, t t1; -- create a reader gang.
begin;
create role r1;
set role r1;  -- set command will also dispatched to idle reader gang
When set role command dispatched to reader gang, reader gang cannot see
the new tuple t1 in catalog table pg_auth.
To fix this issue, we should drop the idle reader gangs after each
utility statement which may modify the catalog table.
=> Cleanup idle reader gang after utility statements

src/test/regress/input/gpcopy.source, src/test/regress/output/gpcopy.source
The failed test case is to test the command "copy lineitem to '/tmp/abort.csv'"
can be cancelled after COPY is dispatched to QEs. To verify this, it checks that
/tmp/abort.csv has fewer rows than lineitem.
The cancel logical in codes is:
QD dispatched the COPY command to QEs, then if QD get a cancel interrupt, it
sends a cancel request to QEs, however, the QD will keep receiving data from
QEs even QD already get a cancel interrupt. QD relies on QEs to receive the
cancel request and explicitly stop copying data to QD.
Obviously, QEs may already have copied out all data to QDs before they
get cancel requests, so the test case cannot guarantee /tmp/aborted.csv
has fewer rows than lineitem.
To fix this, we just verify the COPY command can be aborted with message
'ERROR:  canceling statement …
=> Fix flaky test case 'gpcopy'

src/backend/optimizer/util/var.c, src/include/optimizer/var.h
It was used to implement dedup plan which has been
refactored by the commit 9628a332.
So in this commit we remove these unused functions.
=> Remove deadcode contain_ctid_var_reference.

src/backend/catalog/dependency.c, src/backend/catalog/heap.c, src/backend/catalog/index.c, src/backend/catalog/pg_constraint.c, src/backend/commands/cluster.c, src/backend/commands/indexcmds.c, src/backend/commands/tablecmds.c, src/backend/optimizer/prep/prepunion.c, src/backend/optimizer/util/plancat.c, src/backend/parser/parse_utilcmd.c, src/include/commands/tablecmds.h, src/test/isolation2/expected/gdd/dml_locks_only_targeted_table_in_query_optimizer.out, src/test/isolation2/sql/gdd/dml_locks_only_targeted_table_in_query.sql, src/test/regress/expected/partition_locking.out, src/test/regress/expected/partition_locking_optimizer.out, src/test/regress/sql/partition_locking.sql
That's how the locking works for all other tables, including inherited
tables, and for partitions in PostgreSQL v10 partitioning. But in GPDB,
we were intentionally releasing the lock too early, to save memory when
working on huge partition hierarchies I believe. But that's a lousy
tradeoff, we shouldn't skimp on safety just to save some memory. If
you run out of lock memory as a result, you need to bump up
max_locks_per_tranactions. Memory is cheap, and if you're working with
tens of thousands of partitions, you can afford reserving some memory for
the lock manager.
Fixes https://github.com/greenplum-db/gpdb/issues/5919
=> When dropping a partition, keep the lock until end of transaction.

gpdb-doc/dita/admin_guide/client_auth.xml, gpdb-doc/dita/security-guide/topics/Authenticate.xml
--SSL file should not be in $MASTER_DATA_DIRECTORY is standby master
is enabled (in both Admin Guide and Security Config Guide.)
Also in the Security Config. Guide
--Add not about not using NULL ciphers
--Correct default directory for SSL files to $MASTER_DATA_DIRECTORY
Link to HTML docs in a temporary GPDB draft doc web site.
Admin. Guide
https://docs-msk-gpdb7-ssl-dev.cfapps.io/7-0/admin_guide/client_auth.html#topic5
Security Config. Guide
https://docs-msk-gpdb7-ssl-dev.cfapps.io/7-0/security-guide/topics/Authenticate.html#topic_fzv_wb2_jr
=> docs - add information for SSL with standby master

src/backend/commands/copy.c, src/include/commands/copy.h, src/test/isolation2/input/external_table.source, src/test/isolation2/output/external_table.source
Fix a delimiter bug if external table has delimiter 'OFF', and the value of the column is 'O'.
Add a bool flag 'delim_off' for CopyStateData to indicate if delimiter is set to OFF or not.
This PR is to fix: https://github.com/greenplum-db/gpdb/issues/10009
=> Fix a delimiter bug if external table has delimiter 'OFF'.

gpdb-doc/dita/utility_guide/ref/gpaddmirrors.xml, gpdb-doc/dita/utility_guide/ref/gpexpand.xml, gpdb-doc/dita/utility_guide/ref/gpinitsystem.xml
Add information to gpinitsystem, gpaddmirrors, and gpexpand ref. docs
--Information about using hostnames vs. IP addresses
--Information about configuring hosts that are configured with mulitple NICs
Also updated some examples in gpinitsystem
Links to HTML output on a temporary GPDB draft doc web site.
[gpinitsystem](https://docs-msk-gpdb7-dev.cfapps.io/7-0/utility_guide/ref/gpinitsystem.html)
[gpaddmirrors](https://docs-msk-gpdb7-dev.cfapps.io/7-0/utility_guide/ref/gpaddmirrors.html)
[gpexpand](https://docs-msk-gpdb7-dev.cfapps.io/7-0/utility_guide/ref/gpexpand.html)
=> docs - update utility docs with IP/hostname information.

src/backend/gporca/libgpos/include/gpos/memory/CMemoryPoolManager.h, src/backend/gporca/libgpos/src/memory/CMemoryPoolManager.cpp
Our implementations of memory pools have a hidden dependency on _the_
global memory pool manager: typically GPOS_NEW and GPOS_DELETE will
reach for the memory pool manager singleton. This makes GPOS_DELETE on a
memory pool manager undefined behavior because we call member functions
on an object after its destructor finishes.
On the Postgres 12 merge branch, this manifests itself in a crash during
initdb. More concerning is that it only crashed when we set max
connections and shared buffers to a specific number.
=> Do not allocate MemoryPoolManager from a memory pool

src/test/isolation2/isolation2_schedule
Commit 362c48b665f4af9be3dad166089c28e9976837ba added test
concurrent_drop_truncate_tablespace but it never made it to the
schedule.
=> Add test concurrent_drop_truncate_tablespace to isolation2_schedule

src/backend/access/transam/xact.c, src/backend/port/unix_latch.c, src/backend/storage/ipc/procarray.c, src/backend/utils/time/sharedsnapshot.c
Will push the code once pr pipeline passes.
```
commit 139ac5af87a1ea6e85019c987218a0b74a119321 (HEAD -> 6x_debug, origin/6x_debug)
Author: Paul Guo <guopa@vmware.com>
Date:   Wed Jul 8 13:04:46 2020 +0800
Add debugging code in shared snapshot code and tweak the shared snapshot code a bit.
Notably we want the shared snapshot dumping information when encountering the
"snapshot collision" error, which was seen on real scenario and it is hard to
debug.
(cherry picked from commit ee2d4641bc14d23ab91d051064f4dfbca3aa088b)
commit 16404701368f839fe22c6540f9c78cda51565841
Author: Paul Guo <guopa@vmware.com>
Date:   Thu Jul 16 13:34:55 2020 +0800
Add debugging code for the "latch already owned" error.
We've seen such a case on a stable release but it is hard to debug via the
message only, so let's …
```
=> [6X Backport] Add debug code in shared snap shot and latch code.

src/backend/access/transam/xact.c, src/backend/port/unix_latch.c, src/backend/storage/ipc/procarray.c, src/backend/utils/time/sharedsnapshot.c
Will push the code once the pr pipeline passes.
```
commit 752239e4ae79f351a15bb1f50728a031e2121fdd (HEAD -> 5x_debug, origin/5x_debug)
Author: Paul Guo <guopa@vmware.com>
Date:   Wed Jul 8 13:04:46 2020 +0800
Add debugging code in shared snapshot code and tweak the shared snapshot code a bit.
Notably we want the shared snapshot dumping information when encountering the
"snapshot collision" error, which was seen on real scenario and it is hard to
debug.
(cherry picked from commit ee2d4641bc14d23ab91d051064f4dfbca3aa088b)
commit 40c1feee65d4b6c66f0a286f092cbd553b756bb2
Author: Paul Guo <guopa@vmware.com>
Date:   Thu Jul 16 13:34:55 2020 +0800
Add debugging code for the "latch already owned" error.
We've seen such a case on a stable release but it is hard to debug via the
message only, so …
```
=> [5X Backport] Add debug code in shared snap shot and latch code. 

src/backend/executor/nodeHash.c
ExecChooseHashTableSize() is a hot function which is not only called by executor,
but also by planner. Planner will call this function when calcualting cost for
each join path. The number of join path grow exponentially with the number of
table. As a result, do not using elog(LOG) to avoid generating too many logs.
Just change the log level to DEBUG1, so no test case is added.
=> Change log level in ExecChooseHashTableSize

src/backend/cdb/cdbdtxrecovery.c, src/backend/cdb/cdbtm.c, src/backend/utils/time/sharedsnapshot.c, src/backend/utils/time/test/sharedsnapshot_test.c, src/include/utils/sharedsnapshot.h, src/test/isolation2/expected/prepare_limit.out, src/test/isolation2/expected/uao_crash_compaction_column.out, src/test/isolation2/helpers/server_helpers.sql, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/prepare_limit.sql, src/test/isolation2/sql/uao_crash_compaction_column.sql
Previously we assign it as max_prepared_xacts. It is used to initialize some
2pc related shared memory. For example the array shmCommittedGxactArray is
created with this length and that array is used to collect not-yet "forgotten"
distributed transactions during master/standby recovery, but the array length
might be problematic since:
1. master max_prepared_xacts might be different than segment max_prepared_xacts
(although the document does not suggest it there is no code to enforce that),
so the array on master might not be able to accommodate the distributed
transactions.
2. Even master max_prepared_xacts is equal to segment max_prepared_xacts as
usual.  It is possible some distributed transactions use just partial gang so
the total distributed transactions might be larger (and even …
=> Limit gxact number on master with MaxBackends.

src/test/isolation2/expected/instr_in_shmem_terminate.out, src/test/isolation2/sql/instr_in_shmem_terminate.sql
Enlarge the sleep time for a query which will be canceled later
to avoid slow execution fails the test.
Normally the test's running time should not get affected since the
sleep query will get terminate immediately.
=> Fix flaky for test instr_in_shmem_terminate.

src/test/isolation2/expected/instr_in_shmem_terminate.out, src/test/isolation2/sql/instr_in_shmem_terminate.sql
Enlarge the sleep time for a query which will be canceled later
to avoid slow execution fails the test.
Normally the test's running time should not get affected since the
sleep query will get terminate immediately.
(cherry picked from commit bbccf20c12bcff76388e6b4df986494b28a2f6fe)
=> [6X Backport]Fix flaky for test instr_in_shmem_terminate.

gpcontrib/pxf_fdw/pxf_option.c
On an ARM64 machine, CREATE EXTENSION pxf_fdw fails with :
ERROR:  the log_errors option cannot be set without reject_limit
In pxf_fdw_validator(), the variable log_errors is declared bool, but
it is initialized with -1. Since bool seems to be now a built-in type,
it's definition is implementation dependent, and it's possible that on
ARM, it is defined as unsigned char. Because, through debugger it
could be seen that log_errors's value is 255 when it was assigned -1.
And because (log_errors != -1) condition returns true, we get the
error "log_errors option cannot be set without reject_limit" even when
log_errors option was not specified while creating the extension.
Due to this, all pxf_fdw tests were failing on ARM64.
If log_errors is specified, set log_errors to true rather than to …
=> Fix log_errors related issue while creating pxf_fdw extension

src/backend/optimizer/util/pathnode.c, src/backend/utils/adt/selfuncs.c, src/test/regress/expected/bfv_joins.out, src/test/regress/expected/bfv_joins_optimizer.out, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out, src/test/regress/sql/bfv_joins.sql
Greenplum use unique row id path as a candidate to implement semijoin.
It is introduced long before. But GPDB6 has upgraded the kernel
version to Postgres 9.4 and introduced many new path types and
new plan nodes, thus cdbpath_dedup_fixup failed to consider them.
Some typical issues are: https://github.com/greenplum-db/gpdb/issues/9427
On Master branch, Heikki's commit 9628a33 refactored this part of code
so that it is OK on master. And for 4X and 5X, we do not have many new
kinds of plannode and pathnode, it is also OK.
It is very hard to backport commit 9628a33 to 6X, there is no concept of
a Path's target list in 9.4. And to totally remove this kind of path
is too overkilling. So the policy is to fix them one bye one if reported.
------------------------------------
Fix github issue …
=> (6X only) Fix cdbpath_dedup_fixup does not consider merge append path.

src/backend/storage/ipc/procarray.c
Now that we do not have to use full gang for distributed transaction, that
makes in-progress distributed transaction on master might be greater than
max_prepared_xacts if max_prepared_xacts is configured with a small value.
max_prepared_xacts is used to as the inProgressXidArray length for distributed
snapshot. This might lead to distributed snapshot creation failure due to "Too
many distributed transactions for snapshot" if the system is in heavy 2pc load.
Fixing this by using GetMaxSnapshotXidCount() for the length of array
inProgressXidArray, following the setting on master.
This fixes github issue https://github.com/greenplum-db/gpdb/issues/10057
No test for this since test isolation2:prepare_limit already covered this.  (I
encoutered this issue when backporting a PR that introduces …
=> [6X BugFix] Fix "Too many distributed transactions for snapshot"

src/backend/cdb/cdbpath.c, src/backend/optimizer/path/allpaths.c, src/backend/optimizer/plan/createplan.c, src/backend/optimizer/plan/planner.c, src/backend/optimizer/plan/subselect.c, src/backend/optimizer/util/clauses.c, src/backend/optimizer/util/pathnode.c, src/include/cdb/cdbpath.h, src/include/nodes/relation.h, src/include/optimizer/pathnode.h, src/test/regress/expected/bfv_planner.out, src/test/regress/expected/qp_functions_in_subquery.out, src/test/regress/expected/qp_functions_in_subquery_optimizer.out, src/test/regress/expected/rpt.out, src/test/regress/sql/bfv_planner.sql, src/test/regress/sql/rpt.sql
General and segmentGeneral locus imply that if the corresponding slice
is executed in many different segments should provide the same result
data set. Thus, in some cases, General and segmentGeneral can be
treated like broadcast.
But what if the segmentGeneral and general locus path contain volatile
functions? volatile functions, by definition, do not guarantee results
of different invokes. So for such cases, they lose the property and
cannot be treated as *general. Previously, Greenplum planner
does not handle these cases correctly. Limit general or segmentgeneral
path also has such issue.
The fix idea of this commit is: when we find the pattern (a general or
segmentGeneral locus paths contain volatile functions), we create a
motion path above it to turn its locus to singleQE and then …
=> (6x backport) Correct plan of general & segmentGeneral path with volatiole functions.

src/backend/executor/nodeHash.c
ExecChooseHashTableSize() is a hot function which is not only called by executor,
but also by planner. Planner will call this function when calcualting cost for
each join path. The number of join path grow exponentially with the number of
table. As a result, do not using elog(LOG) to avoid generating too many logs.
(cherry picked from commit 6b4d93c58ae2c5dd32020b14bfd11118b506e6a2)
=> [Backport 6X] Change log level in ExecChooseHashTableSize

src/backend/commands/explain_gp.c, src/backend/executor/execMain.c, src/test/regress/input/dispatch.source, src/test/regress/output/dispatch.source
Error handling for explain analyze differed from a regular query. When we executed a plan slice and got an error in a case on a simple query we just cleanup and rethrew an exception out of `PG_TRY` block. But for explain analyze we tried to return stats to QD though it is possibly incorrect or even broken. It can cause different errors with stats packets during:
- serialization on QE (`InstrEndLoop called on running node`)
-  deserialization on QD (`Invalid execution statistics received stats node-count mismatch`)
Also in a case of a double fault an original error was overridden by a new one. It hid an original error from a user and this behavior differed from a simple query plan processing.
There is another possible solution: remove `PG_CATCH` block of code (to show the original error) …
=> Fix explain analyze error handling

concourse/pipelines/pr_pipeline.yml
We must install libuv on the PR pipeline to compile with ic-proxy
enabled.  ICW tests are still run in ic-udpifc mode.
=> ic-proxy: get libuv on pr pipeline

src/backend/commands/analyze.c, src/backend/commands/analyzeutils.c, src/include/commands/analyzeutils.h
In some cases, merge stats logic for root partition table may consume
very high memory usage in CacheMemoryContext.
This may lead to `Canceling query because of high VMEM usage` when
concurrently ANALYZE partition tables.
For example, there are several root partition tables and they both have
thousands of leaf tables. And these tables are all wide tables that may
contain hundreds of columns.
So when analyze()/auto_stats() leaf tables concurrently,
`leaf_parts_analyzed` will consume lots of memory(catalog catch for
pg_statistic and pg_attribute) under
CacheMemoryContext for each backend, which may hit the protect VMEM
limit.
In `leaf_parts_analyzed`, a single backend's leaf table analysis for a
root partition table, it may add cache entries up to
number_of_leaf_tables * number_of_columns …
=> Resolve high `CacheMemoryContext` usage for `ANALYZE` on large partition table.

src/bin/pg_dump/Makefile, src/bin/pg_dump/t/002_pg_dump.pl
We skipped these during the PostgreSQL 9.6 merge. Time to pay down this
little technical debt.
We had copied the latest version of the t/002_pg_dump.pl test file from
upstream REL9_6_STABLE branch. That included the test change from upstream
commit e961341cc, but we didn't have the corresponding code changes yet.
Revert the test change, so that it passes. We'll get the bug fix, along
with the test change again, when we continue with the upstream merge, but
until then let's just keep the test in sync with the code.
=> Fix and enable upstream pg_dump regression tests.

src/backend/mock.mk
None of the mock tests in the backend call into GPORCA functions, so
no need to generate mock objects for them. Saves some time and space when
running mock tests.
=> Don't mock GPORCA functions unnecessarily.

src/test/isolation2/input/pg_basebackup_with_tablespaces.source, src/test/isolation2/output/pg_basebackup_with_tablespaces.source
Here is the diff output of the test result.
drop database some_database_without_tablespace;
-DROP
+ERROR:  database "some_database_without_tablespace" is being accessed by other users
+DETAIL:  There is 1 other session using the database.
drop tablespace some_basebackup_tablespace;
-DROP
+ERROR:  tablespace "some_basebackup_tablespace" is not empty
The reason is that after client connection to the database exits, the server
needs some time (the process might be scheduled out soon, and the operation
needs to content for the ProcArrayLock lock) to release the PGPROC in
proc_exit()->ProcArrayRemove(). During dropdb() (for database drop), postgres
will call CountOtherDBBackends() to see if there are still sessions that are
using the database by checking proc->databaseId, and it will try at …
=> Fix flaky test isolation2:pg_basebackup_with_tablespaces

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
-Add GUC
-Also, updated ADD COLUMN clause of  ALTER TABLE command with GUC information
This is for 6X_STABLE only.
DEV PR https://github.com/greenplum-db/gpdb/pull/10432
Link to HTML docs in a temporary GPDB doc review site.
GUC reference
https://docs-msk-gpdb6-dev.cfapps.io/6-9/ref_guide/config_params/guc-list.html#gp_add_column_inherits_table_setting
ALTER TABLE... ADD COLUMN
https://docs-msk-gpdb6-dev.cfapps.io/6-9/ref_guide/sql_commands/ALTER_TABLE.html#topic1__section3
=> docs - add GUC gp_add_column_inherits_table_setting 6.x only

gpdb-doc/dita/ref_guide/sql_commands/ALTER_TABLE.xml
Add information about the compression parameters used when
a column is added to an AOCO table.
master only. doc PR for 6X_STABLE https://github.com/greenplum-db/gpdb/pull/10517
dev PR https://github.com/greenplum-db/gpdb/pull/10354
=> docs - update ALTER TABLE ... ADD COLUMN for AOCO tables

src/backend/gpopt/config/CConfigParamMapping.cpp, src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp, src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h, src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp, src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h, src/backend/gporca/libgpopt/include/gpopt/metadata/CIndexDescriptor.h, src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h, src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalIndexOnlyScan.h, src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CXformIndexGet2IndexOnlyScan.h, src/backend/gporca/libgpopt/include/gpopt/xforms/xforms.h, src/backend/gporca/libgpopt/src/metadata/CIndexDescriptor.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalIndexGet.cpp, src/backend/gporca/libgpopt/src/operators/CPhysicalIndexOnlyScan.cpp, src/backend/gporca/libgpopt/src/operators/Makefile, src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp, src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp, src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp, src/backend/gporca/libgpopt/src/xforms/Makefile, src/backend/utils/misc/guc_gp.c, src/include/gpopt/translate/CTranslatorDXLToPlStmt.h, src/include/utils/guc.h, src/include/utils/unsync_guc_name.h, src/test/regress/expected/bfv_index.out, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/sql/bfv_index.sql
This commit allows Orca to select plans that leverage IndexOnlyScan
node. A new GUC 'optimizer_enable_indexonlyscan' is used to enable or
disable this feature and is currently disabled by default until the
following issues are addressed:
1) Implement cost comparison model for index only scans. Currently,
cost is hard coded for testing purposes.
2) Support index only scan using GiST and SP-GiST as allowed.
Currently, code only supports index only scans on b-tree index.
CI run to show plan diffs:
https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-index-only-scan/jobs/icw_gporca_centos7/builds/30
=> Add Orca support for index only scan

.gitmodules
Make pgbouncer 1.13 to work on centos6
=> Upgrade pgbouncer to 1.13

src/backend/cdb/motion/ic_proxy.h
We used to store them under /tmp/, we include the postmaster port number
in the file name in the hope that two clusters will not conflict with
each other on this file.
However the conflict still happen in the test src/bin/pg_basebackup.
And it can also happen if a second cluster is missed configured by
accident.  So to make things safe we also include the postmaster pid in
the domain socket path, there is no chance for two postmasters to share
the same pids.
=> ic-proxy: include postmaster pid in the domain socket path

concourse/pipelines/pr_pipeline.yml
This reverts commit 7f44bfa83ce03955f4f4ba987f044a18ea5cf798.
----
According to #10522 we no longer need to get the libuv installer. The master pipelines are already handled by it, this one handles the 6X PR pipeline.
=> 6X: Revert "ic-proxy: get libuv on pr pipeline"

src/backend/gpopt/config/CConfigParamMapping.cpp, src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/backend/gporca/data/dxl/minidump/UnnestSQJoins.mdp, src/backend/gporca/libgpdbcost/include/gpdbcost/CCostModelGPDB.h, src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp, src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h, src/backend/gporca/libgpopt/include/gpopt/metadata/CIndexDescriptor.h, src/backend/gporca/libgpopt/include/gpopt/operators/COperator.h, src/backend/gporca/libgpopt/include/gpopt/operators/CPhysicalIndexOnlyScan.h, src/backend/gporca/libgpopt/include/gpopt/translate/CTranslatorExprToDXL.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CXform.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CXformIndexGet2IndexOnlyScan.h, src/backend/gporca/libgpopt/include/gpopt/xforms/xforms.h, src/backend/gporca/libgpopt/src/metadata/CIndexDescriptor.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalIndexGet.cpp, src/backend/gporca/libgpopt/src/operators/CPhysicalIndexOnlyScan.cpp, src/backend/gporca/libgpopt/src/operators/Makefile, src/backend/gporca/libgpopt/src/translate/CTranslatorExprToDXL.cpp, src/backend/gporca/libgpopt/src/xforms/CXformFactory.cpp, src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp, src/backend/gporca/libgpopt/src/xforms/Makefile, src/backend/utils/misc/guc_gp.c, src/include/gpopt/translate/CTranslatorDXLToPlStmt.h, src/include/utils/guc.h, src/include/utils/unsync_guc_name.h, src/test/regress/expected/bfv_index.out, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/sql/bfv_index.sql
Add Orca support for index only scan
This commit allows Orca to select plans that leverage IndexOnlyScan
node. A new GUC 'optimizer_enable_indexonlyscan' is used to enable or
disable this feature. Index only scan is disabled by default, until the
following issues are addressed:
1) Implement cost comparison model for index only scans. Currently,
cost is hard coded for testing purposes.
2) Support index only scan using GiST and SP-GiST as allowed.
Currently, code only supports index only scans on b-tree index.
(cherry picked from commit 3b72df1810411f4716137446f00b550378084835)
=> 6X backport: Add Orca support for index only scan

concourse/pipelines/pr_pipeline.yml
This reverts commit ef887cfe457dbefcdb477b9ec838ee999ec04c59.
----
According to https://github.com/greenplum-db/gpdb/pull/10522 we no longer need to get the libuv installer.  The master pipelines are already handled by it, this one handles the master PR pipeline.
=> Revert "ic-proxy: get libuv on pr pipeline"

src/backend/utils/error/debugutils.c
=> Coverity: (Resource leak)dump_mt_bind should free FILE pointer.

src/backend/gporca/data/dxl/minidump/Join-Varchar-Equality.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropRelational.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalBitmapTableGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEConsumer.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEProducer.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSelect.h, src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h, src/backend/gporca/libgpopt/src/base/CDrvdPropRelational.cpp, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libgpopt/src/operators/CExpression.cpp, src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp, src/backend/gporca/libgpopt/src/operators/CLogical.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalCTEConsumer.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalCTEProducer.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp, src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp, src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinDPv2.cpp, src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
Orca's DP algorithms currently generate logical alternatives based only on cardinality; they do not take into account motions/partition selectors as these are physical properties handled later in the optimization process. Since DPv2 doesn't generate all possible alternatives for the optimization stage, we end up generating alternatives that do not support partition selection or can only place poor partition selectors.
This PR introduces partition knowledge into the DPv2 algorithm. If there is a possible partition selector, it will generate an alternative that considers it, in addition to the previous alternatives.
We introduce new properties, m_contain_PS  to indicate whether a SExpressionInfo contains a PS for a particular expression. We consider an expression to have a possible …
=> Add knowledge of partition selectors to Orca's DPv2 algorithm

src/backend/gporca/libgpopt/include/gpopt/base/CDrvdPropRelational.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpression.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionHandle.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogical.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalBitmapTableGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEConsumer.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalCTEProducer.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalDynamicGetBase.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalGet.h, src/backend/gporca/libgpopt/include/gpopt/operators/CLogicalSelect.h, src/backend/gporca/libgpopt/include/gpopt/operators/CPhysical.h, src/backend/gporca/libgpopt/include/gpopt/xforms/CJoinOrderDPv2.h, src/backend/gporca/libgpopt/src/base/CDrvdPropRelational.cpp, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libgpopt/src/operators/CExpression.cpp, src/backend/gporca/libgpopt/src/operators/CExpressionHandle.cpp, src/backend/gporca/libgpopt/src/operators/CLogical.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalCTEConsumer.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalCTEProducer.cpp, src/backend/gporca/libgpopt/src/operators/CLogicalSelect.cpp, src/backend/gporca/libgpopt/src/xforms/CJoinOrderDPv2.cpp, src/backend/gporca/libgpopt/src/xforms/CXformExpandNAryJoinDPv2.cpp, src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp, src/backend/gporca/libnaucrates/src/statistics/CStatisticsUtils.cpp
This is a direct backport of 9c4453211e627887990599773ab1ffa5ee310bb0
Orca's DP algorithms currently generate logical alternatives based only on cardinality; they do not take into account motions/partition selectors as these are physical properties handled later in the optimization process. Since DPv2 doesn't generate all possible alternatives for the optimization stage, we end up generating alternatives that do not support partition selection or can only place poor partition selectors.
This PR introduces partition knowledge into the DPv2 algorithm. If there is a possible partition selector, it will generate an alternative that considers it, in addition to the previous alternatives.
We introduce new properties, m_contain_PS  to indicate whether a SExpressionInfo contains a PS for a …
=> [6X Backport] Add knowledge of partition selectors to Orca's DPv2 algorithm (#10263)

src/test/isolation2/expected/reader_waits_for_lock.out, src/test/isolation2/expected/segwalrep/commit_blocking_on_standby.out, src/test/isolation2/expected/segwalrep/dtm_recovery_on_standby.out, src/test/isolation2/expected/segwalrep/dtx_recovery_wait_lsn.out, src/test/isolation2/helpers/server_helpers.sql, src/test/isolation2/sql/reader_waits_for_lock.sql, src/test/isolation2/sql/segwalrep/commit_blocking_on_standby.sql, src/test/isolation2/sql/segwalrep/dtm_recovery_on_standby.sql, src/test/isolation2/sql/segwalrep/dtx_recovery_wait_lsn.sql, src/test/regress/expected/mirror_replay.out, src/test/regress/sql/mirror_replay.sql
Adding pg_stat_clear_snapshot() in functions looping over
gp_stat_replication / pg_stat_replication to refresh result everytime
the query is run as part of same transaction. Without
pg_stat_clear_snapshot() query result is not refreshed for
pg_stat_activity neither for xx_stat_replication functions on multiple
invocations inside a transaction. So, in absence of it the tests
become flaky.
Also, tests commit_blocking_on_standby and dtx_recovery_wait_lsn were
initially committed with wrong expectations, hence were missing to
test the intended behavior. Now reflect the correct expectation.
=> Correct and stabilize some replication tests

src/backend/cdb/cdbcopy.c, src/bin/pg_dump/pg_dump.c
Should not call gzdopen(dup(fileno(stdout)) directly, since return
value of dup() could be negative.
Also fix some resource leak.
=> Coverity: Resource leak

gpcontrib/gp_replica_check/gp_replica_check.c, src/test/regress/expected/create_table.out, src/test/regress/sql/create_table.sql
Unlogged tables do not propagate to replica servers, skip the check.
=> gp_replica_check: skip checking unlogged tables

src/backend/cdb/cdbappendonlystorageread.c, src/backend/utils/hyperloglog/gp_hyperloglog.c
Should check the len parameter of memcpy is not negative in
gp_hyperloglog.c
Should use errno instead of seekResult in cdbappendonlystorageread.c
No test case needed.
=> Coverity: Argument cannot be negative

gpMgmt/bin/gpinitsystem, gpMgmt/bin/lib/gp_bash_functions.sh, gpMgmt/bin/test/gpinitsystem_test.bash, gpMgmt/test/behave/mgmt_utils/gpinitsystem.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave_utils/utils.py
This fixes a big using `gpinitsystem -I gpinitsystem_config` in 6X.  
In 6X, we allow either a 5-field or 6-field format for the PRIMARY_ARRAY and the MIRROR_ARRAY.  The 6-field format adds an explicit host address(`host:address:1025:/data/primary/gpseg0:2:0:1089` vs `host:1025:/data/primary/gpseg0:2:0:1089`).    
The bug is that an internal routine assumes that we have the 6-field format always.  The net result is that we end up sorting the MIRROR_ARRAY numerically.  This can cause the sort to work on the hostnames or the ports.  This can cause all sorts of issues, the current manifestation being a mismatch between the contentIDs of the primary with its corresponding mirror.
Co-authored-by: David Krieger <dkrieger@vmware.com>
=> gpinitsystem: accept legacy format gpinitsystem_config files

src/backend/access/external/external.c, src/backend/commands/exttablecmds.c, src/include/utils/tuplesort.h
Remove unused varaible.
For tuplesort.h, we doesn't support mksort based cluster,
so we should just set is_mk_tuplesortstate to false
=> Coverity: Variable unused

gpMgmt/bin/lib/pexpect/__init__.py, src/backend/commands/vacuum_ao.c
Remove dead code.
insertDesc is alwasy NULL in ao_vacuum_rel_compact()
=> Coverity: Logically dead code

src/backend/commands/analyze.c
sizeof(HeapTuple *) should be sizeof(HeapTuple)
=> Coverity: Sizeof not portable

src/backend/commands/analyze.c, src/backend/commands/analyzeutils.c, src/include/commands/analyzeutils.h, src/test/regress/expected/incremental_analyze.out
In some cases, merge stats logic for root partition table may consume
very high memory usage in CacheMemoryContext.
This may lead to `Canceling query because of high VMEM usage` when
concurrently ANALYZE partition tables.
For example, there are several root partition tables and they both have
thousands of leaf tables. And these tables are all wide tables that may
contain hundreds of columns.
So when analyze()/auto_stats() leaf tables concurrently,
`leaf_parts_analyzed` will consume lots of memory(catalog catch for
pg_statistic and pg_attribute) under
CacheMemoryContext for each backend, which may hit the protect VMEM
limit.
In `leaf_parts_analyzed`, a single backend's leaf table analysis for a
root partition table, it may add cache entries up to
number_of_leaf_tables * number_of_columns …
=> [5X Backport]Resolve high `CacheMemoryContext` usage for `ANALYZE` on large partition table.

src/bin/pg_dump/pg_backup_archiver.c
return value of strcmp is not checked in some branches.
=> Coverity: Check return value of strcmp

src/backend/commands/analyze.c, src/backend/commands/analyzeutils.c, src/include/commands/analyzeutils.h
In some cases, merge stats logic for root partition table may consume
very high memory usage in CacheMemoryContext.
This may lead to `Canceling query because of high VMEM usage` when
concurrently ANALYZE partition tables.
For example, there are several root partition tables and they both have
thousands of leaf tables. And these tables are all wide tables that may
contain hundreds of columns.
So when analyze()/auto_stats() leaf tables concurrently,
`leaf_parts_analyzed` will consume lots of memory(catalog catch for
pg_statistic and pg_attribute) under
CacheMemoryContext for each backend, which may hit the protect VMEM
limit.
In `leaf_parts_analyzed`, a single backend's leaf table analysis for a
root partition table, it may add cache entries up to
number_of_leaf_tables * number_of_columns …
=> [6X Backport]Resolve high `CacheMemoryContext` usage for `ANALYZE` on large partition table.

gpMgmt/bin/gpcheckcat
Note that since PyGreSQL 5.0 this method will return the values of array
type columns as Python lists.
ref: https://pygresql.org/contents/pg/query.html
=> gpcheckcat: fix inconsistent issues reporting

src/backend/cdb/motion/ic_proxy_main.c
Fixed the bug that the SIGHUP handler was installed for SIGINT by
mistake, so the ic-proxy bgworkers would die on SIGHUP.
By correcting the signal name, now we could let the ic-proxy bgworkers
reload the postgresql.conf by executing "gpstop -u".
=> ic-proxy: correct SIGHUP handler

src/backend/cdb/motion/ic_proxy_main.c
Fixed the bug that the SIGHUP handler was installed for SIGINT by
mistake, so the ic-proxy bgworkers would die on SIGHUP.
By correcting the signal name, now we could let the ic-proxy bgworkers
reload the postgresql.conf by executing "gpstop -u".
(cherry picked from commit a181655b731120b3bcc05472b6cf93a150a9f3ba)
----
This is to backport https://github.com/greenplum-db/gpdb/pull/10572 to 6X.
=> 6X: ic-proxy: correct SIGHUP handler

src/test/isolation2/expected/segwalrep/max_slot_wal_keep_size.out, src/test/isolation2/sql/segwalrep/max_slot_wal_keep_size.sql
In the test, check 'sync_state' in pg_stat_replication is unnecessary and it
makes the test flaky, so remove it.
=> [6X only] Fix flaky test max_slot_wal_keep_size

gpdb-doc/markdown/common/gpdb-features.html.md.erb
add a blurb on the open source greenplum docs landing page that open source users need to build and install gpbackup, and xref to the README file in the gpbackup repo.
i added this gpbackup info to new section for greenplum components (i added a new section because most of the info on the page is related to pivotal / opensource differences), and moved the pxf info there as well.
=> docs - note how oss users get gpbackup

src/backend/access/external/url_curl.c, src/backend/bootstrap/bootstrap.c, src/backend/commands/functioncmds.c, src/backend/fts/ftsmessagehandler.c
This PR is mostly relevant to release memory when the memory pointer is no longer held.
=> Coverity: release memory when the memory pointer is no longer held.

src/test/isolation2/expected/segwalrep/dtx_recovery_wait_lsn.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/segwalrep/dtx_recovery_wait_lsn.sql
When the mirror is down and the master is reset, the 'dtx recovery' process
will hang because the primary can't sync the WAL to the mirror. The FTS
should be able to probe and 'sync off' the mirror.
=> [6X backport] Add a test for replication lag

src/backend/utils/misc/guc.c, src/include/utils/guc.h
In commit 3ef5e26, we changed the value of some macro in guc.h, that would
introduce ABI change if 3rd-party libaraies are using the macros.
=> [6X only] Avoid ABI change

src/backend/executor/nodeModifyTable.c, src/test/isolation2/expected/modify_table_data_corrupt.out, src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
When update or delete statement errors out because of the CTID is
not belong to the local segment, we should also print out the CTID
of the tuple so that it will be much easier to locate the wrong-
distributed data via:
`select * from t where gp_segment_id = xxx and ctid='(aaa,bbb)'`.
=> Print CTID when we detect data distribution wrong for UPDATE|DELETE.

src/backend/parser/parse_utilcmd.c, src/test/isolation2/expected/misc.out, src/test/isolation2/sql/misc.sql
When transforming DISTRIBUTED BY clause in utility mode, NULL would be returned
as only QD can have policies. As a result, the child table in a partitioned
table would have NULL distributedBy, which would trigger assertion failure or
cause crash with current codes.
This patch fixes that by emitting an error message in that case to avoid the
crash.
=> Fix crash when creating partitioned table in utility mode

src/backend/utils/error/debugutils.c
(cherry picked from commit 9d801056b29744a0d58a2459a192a8e64142d336)
=> [6X Backport]Coverity: dump_mt_bind should free FILE pointer.

src/backend/access/index/genam.c, src/backend/utils/time/tqual.c
We've seen a panic case on gpdb 6 with stack as below,
3  markDirty (isXmin=0 '\000', tuple=0x7effe221b3c0, relation=0x0, buffer=16058) at tqual.c:105
4  SetHintBits (xid=<optimized out>, infomask=1024, rel=0x0, buffer=16058, tuple=0x7effe221b3c0) at tqual.c:199
5  HeapTupleSatisfiesMVCC (relation=0x0, htup=<optimized out>, snapshot=0x15f0dc0 <CatalogSnapshotData>, buffer=16058) at tqual.c:1200
6  0x00000000007080a8 in systable_recheck_tuple (sysscan=sysscan@entry=0x2e85940, tup=tup@entry=0x2e859e0) at genam.c:462
7  0x000000000078753b in findDependentObjects (object=0x2e856e0, flags=<optimized out>, stack=0x0, targetObjects=0x2e85b40, pendingObjects=0x2e856b0,
depRel=0x7fff2608adc8) at dependency.c:793
8  0x00000000007883c7 in performMultipleDeletions (objects=objects@entry=0x2e856b0, …
=> Fix potential panic in visibility check code.

gpMgmt/bin/gpsd
gpsd was failing because the connectionString that we passed to pgdb.connect
had the parameters in the wrong order. It started failing after upgrading to a
higher version of PyGreSQL. So use a dictionary instead in order to avoid
sending in the parameters incorrectly.
=> Fix connection string for gpsd

src/test/walrep/expected/walreceiver.out, src/test/walrep/gplibpq.c, src/test/walrep/input/setup.source, src/test/walrep/output/setup.source, src/test/walrep/sql/walreceiver.sql
walreceiver is quite sensitive to any WAL write. After create a table
and insert some tuples, it doesn't run a vacuum. There may be other
cases that cause some WAL traffic. One of the WAL records is
relevant to the hot-standby to record `RUNNING_XACTS`
The last `test_receive()` only tests there should be no WAL traffic
after receiving the WAL records to the current xlog location. It still
has a gap that a new WAL record transmitted to the walreceiver.
It's not meaningful to run `test_receive()`, since the function
`test_receive_and_verify()` has verified that all the WAL traffic
to the latest xlog location is received. So, removed test_receive().
=> Fix the flaky test of walreceiver

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
add reference docs for new guc gp_fts_replication_attempt_count.  didn't reference or document the gp_fts_mark_mirror_down_grace_period guc, because the user wouldn't need to tune that.
wasn't clear to me if/where this info might fit in our existing admin guide docs.
=> docs - gp_fts_replication_attempt_count guc info

gpdb-doc/dita/ref_guide/gp_toolkit.xml
clarify that the max cpu used is 1.00.
=> docs - clarify resgroup status cpu max value

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml
GUC to control WAL log disk size. Per segment instance.
This is 6X_STABLE only
Dev PR https://github.com/greenplum-db/gpdb/pull/10234
=> docs - new GUC max_slot_wal_keep_size

gpdb-doc/dita/admin_guide/admin_guide.ditamap, gpdb-doc/dita/admin_guide/expand/expand-planning.xml, gpdb-doc/dita/admin_guide/managing/proxy-ic.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap, gpdb-doc/dita/utility_guide/ref/gpexpand.xml
-New topic in Admin. Guide.
-New GUC gp_interconnect_proxy_addresses
-Updated GUC gp_interconnect_type - new value PROXY
Also added note to gpexpand documents - do no use proxy during expand.
Link to HTML docs on temporary docs draft review site.
Will be backported to 6X_STABLE
Interconnect Proxy
https://docs-msk-gpdb7-dev-ic-proxy.cfapps.io/7-0/admin_guide/managing/proxy-ic.html
https://docs-msk-gpdb7-dev-ic-proxy.cfapps.io/7-0/ref_guide/config_params/guc-list.html#gp_interconnect_proxy_addresses
https://docs-msk-gpdb7-dev-ic-proxy.cfapps.io/7-0/ref_guide/config_params/guc-list.html#gp_interconnect_type
gpexpand
https://docs-msk-gpdb7-dev-ic-proxy.cfapps.io/7-0/admin_guide/expand/expand-planning.html
https://docs-msk-gpdb7-dev-ic-proxy.cfapps.io/7-0/utility
=> docs - support proxies for GPDB interconnect

src/backend/cdb/motion/ic_proxy.h
A typical mistake on allocating typed memory is as below:
int64 *ptr = malloc(sizeof(int32));
To prevent this, now we make ic_proxy_new() a typed allocator, it always
return a pointer of the specified type, for example:
int64 *p1 = ic_proxy_new(int64); /* good */
int64 *p2 = ic_proxy_new(int32); /* bad, gcc will raise a warning */
=> ic-proxy: type checking in ic_proxy_new()

src/backend/commands/copy.c, src/include/commands/copy.h, src/test/isolation2/input/external_table.source, src/test/isolation2/output/external_table.source
Add a bool flag 'delim_off' for CopyStateData to indicate if delimiter is set to OFF or not.
This PR is to fix: https://github.com/greenplum-db/gpdb/issues/10009
=> Fix a delimiter bug if external table has delimiter 'OFF', and the value of the column is 'O'.

src/backend/executor/nodeModifyTable.c, src/test/isolation2/expected/modify_table_data_corrupt.out, src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
When update or delete statement errors out because of the CTID is
not belong to the local segment, we should also print out the CTID
of the tuple so that it will be much easier to locate the wrong-
distributed data via:
`select * from t where gp_segment_id = xxx and ctid='(aaa,bbb)'`.
-------
Master branch pr is: https://github.com/greenplum-db/gpdb/pull/10582 is merged.
Wait for next week's shipping decision.
=> (6x backport) Print CTID when we detect data distribution wrong for UPDATE|DELETE.

src/backend/executor/execMain.c, src/backend/executor/nodeDML.c, src/test/isolation2/expected/modify_table_data_corrupt_optimizer.out
When update or delete statement errors out because of the CTID is
not belong to the local segment, we should also print out the CTID
of the tuple so that it will be much easier to locate the wrong-
distributed data via:
`select * from t where gp_segment_id = xxx and ctid='(aaa,bbb)'`.
Master branch PR: https://github.com/greenplum-db/gpdb/pull/10582 is merged.
Wait for next week's shipping decision.
=> (5x backport) Print CTID when we detect data distribution wrong for UPDATE|DELETE.

src/backend/access/index/genam.c, src/backend/utils/time/tqual.c
We've seen a panic case on gpdb 6 with stack as below,
3  markDirty (isXmin=0 '\000', tuple=0x7effe221b3c0, relation=0x0, buffer=16058) at tqual.c:105
4  SetHintBits (xid=<optimized out>, infomask=1024, rel=0x0, buffer=16058, tuple=0x7effe221b3c0) at tqual.c:199
5  HeapTupleSatisfiesMVCC (relation=0x0, htup=<optimized out>, snapshot=0x15f0dc0 <CatalogSnapshotData>, buffer=16058) at tqual.c:1200
6  0x00000000007080a8 in systable_recheck_tuple (sysscan=sysscan@entry=0x2e85940, tup=tup@entry=0x2e859e0) at genam.c:462
7  0x000000000078753b in findDependentObjects (object=0x2e856e0, flags=<optimized out>, stack=0x0, targetObjects=0x2e85b40, pendingObjects=0x2e856b0,
depRel=0x7fff2608adc8) at dependency.c:793
8  0x00000000007883c7 in performMultipleDeletions (objects=objects@entry=0x2e856b0, …
=> [6X Backport] Fix potential panic in visibility check code. (#10589)

src/backend/cdb/motion/ic_proxy_backend.c, src/backend/cdb/motion/ic_proxy_backend.h, src/backend/cdb/motion/ic_proxy_client.c, src/backend/cdb/motion/ic_proxy_packet.c, src/backend/cdb/motion/ic_proxy_packet.h, src/backend/cdb/motion/ic_proxy_peer.c, src/backend/cdb/motion/ic_tcp.c, src/include/cdb/cdbinterconnect.h
Previously, when backends connect to a proxy, we need to setup
domain socket pipe and send HELLO message(recv ack message) in
a blocking and non-parallel way. This makes ICPROXY hard to introduce
check_for_interrupt during backend registeration.
By utilizing libuv loop, we could register backend in paralle. Note
that this is one of the step to replace all the ic_tcp backend logic
reused by ic_proxy currently. In future, we should use libuv to replace
all the backend logic, from registeration to send/recv data.
=> ic-proxy: support parallel backend registeration to proxy

src/backend/cdb/dispatcher/cdbdisp_query.c, src/test/regress/expected/dispatch_encoding.out, src/test/regress/sql/dispatch_encoding.sql
Execution of a long enough query containing multi-byte characters can cause incorrect truncation of the query string. Incorrect truncation implies an occasional cut of a multi-byte character and (with log_min_duration_statement set to 0) subsequent write of an invalid symbol to segment logs. Such broken character present in logs produces problems when trying to fetch logs info from gp_toolkit.__gp_log_segment_ext  table - queries fail with the following error: «ERROR: invalid byte sequence for encoding…». 
This is caused by buildGpQueryString function in `cdbdisp_query.c`, which prepares query text for dispatch to QE. It does not take into account character length when truncation is necessary (text is longer than QUERY_STRING_TRUNCATE_SIZE). 
1. set log_min_duration_statement to 0;
2. …
=> Fix query string truncation while dispatching to QE

src/backend/access/transam/test/xlog_test.c, src/backend/utils/misc/faultinjector.c, src/backend/utils/mmgr/test/runaway_cleaner_test.c, src/backend/utils/time/test/sharedsnapshot_test.c, src/include/utils/faultinjector.h
Backport of https://github.com/greenplum-db/gpdb/pull/10616 to 6X_STABLE. Applied cleanly, but let's verify that the pipeline is happy before pushing..
=> Make Fault Injection sites cheaper, when no faults have been activated. (6X_STABLE)

src/backend/access/transam/test/xlog_test.c, src/backend/utils/misc/faultinjector.c, src/backend/utils/mmgr/test/runaway_cleaner_test.c, src/include/utils/faultinjector.h
Fault injection is expected to be *very* cheap, we even enable it on
production builds. That's why I was very surprised when I saw 'perf'
report that FaultInjector_InjectFaultIfSet() was consuming about 10% of
CPU time in a performance test I was running on my laptop. I tracked it
to the FaultInjector_InjectFaultIfSet() call in standard_ExecutorRun().
It gets called for every tuple between 10000 and 1000000, on every
segment.
Why is FaultInjector_InjectFaultIfSet() so expenseive? It has a
quick exit in it, when no faults have been activated, but before reaching
the quick exit it calls strlen() on the arguments. That's not cheap.
And the function call isn't completely negligible on hot code paths,
either.
To fix, turn FaultInjector_InjectFaultIfSet() into a macro that's only
few …
=> Make Fault Injection sites cheaper, when no faults have been activated.

gpAux/Makefile
The Greenplumn release builds are configured without any extra configure
flags, it only use the ones specified in gpAux/Makefile, so we have to
enable ic-proxy in this file to include the ic-proxy feature in relase
builds.
=> ic-proxy: enable in release builds

src/backend/optimizer/plan/plangroupext.c, src/test/regress/expected/olap_group.out, src/test/regress/sql/olap_group.sql
For grouping set query, we need to replace our private subplan into
a plan tree. But for subplan's RelOptInfo will not create if the
sub-plan does not have any relation in its fromlist.
Check pointer in simple_rte_array and simple_rel_array to promise
which is not null before replacement.
Fix #10491
=> 6X:Check if RelOptInfo exits before replace subplan for grouping set query

gpAux/Makefile
The Greenplumn release builds are configured without any extra configure
flags, it only use the ones specified in gpAux/Makefile, so we have to
enable ic-proxy in this file to include the ic-proxy feature in relase
builds.
Reviewed-by: Shaoqi Bai <bshaoqi@vmware.com>
(cherry picked from commit 489787569e3d2bd0a57ac262a1e4551e578d2ab8)
----
This is to backport https://github.com/greenplum-db/gpdb/pull/10629 to 6X_STABLE.
=> 6X: ic-proxy: enable in release builds

src/backend/cdb/motion/ic_proxy_backend.c, src/backend/cdb/motion/ic_proxy_router.c, src/backend/cdb/motion/ic_proxy_server.h
ic-proxy is developed with libuv, the minimal supported libuv version is
1.18.0. But in commit 608514, we introduce new API in libuv 1.19, which
break compatibility on os like Ubuntu 18.04 whose default libuv version
is 1.18.
We should keep our code base align with libuv 1.18, and replace the new
API in libuv 1.19. The API change is mainly about how to access data field
in uv handle and uv loop. The new API uses function interface like
`uv_handle_set_data` and `uv_handle_get_data` to access data filed, while
the old API in 1.18 access the data filed directly. Note that in the latest
libuv version 1.38.2, the old API and new API are both supported. And libuv
is stable enough to support the old API for a long time.
=> Using libuv 1.18 API in ic-proxy

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/gporca_optimizer.out, src/test/regress/expected/with_clause_optimizer.out
We currently translate the last child of a sequence node before all
other children. This stands out as highly unusual because DXL node
translations normally have no order dependencies, and so they typically
are translated in order ("the normal for-loop"). There was a comment
rationalizing this, which only furthers confusion. We dug deep, and
found that there was no apparent reason we did that.
This patch removes the special handling of the last child, and rolls it
back into "the normal for-loop". This both results in clearer code, and
it removes a hurdle for the Postgres 12 merge where we needed a dynamic
table scan to be translated _after_ its corresponding static partition
selector. That is not great either, but we have a path forward to
eliminate the implicit order dependency there …
=> [gpopt] Translate children of DXL Sequence in order.

gpcontrib/orafce/sql/dbms_pipe_session_B.sql
There is a race condition between receiveFrom() and
dbms_pipe_session_A::createImplicitPipe(). Sleep an extra seconds
is not reliable. So wait until the data is available.
This PR changes the semantics of receiveFrom(), i.e. wait until
the data is available, no timeout happens.
=> Fix flaky test: dbms_pipe_session_B

gpAux/gpperfmon/src/gpmon/gpsmon.c
After losing tcp connection between gpmmon and gpsmon and subsequent its reestablishment the gpsmon enters to infinite loop inside libevent routine of timeout event processing. The reason was in calling `event_set` function (that internally calls `event_assign` one) under new connection establishment on currently working (not released) `tcp_event` object that [rewrites](https://github.com/libevent/libevent/blob/7e6c5fb/event.c#L2172) internal flags of that event and puts it into inconsistent state.
The current fix releases `tcp_event` from participating in event loop (takes to unpending state) under connection closing from gpsmon by timeout so that the next new connection have to set `tpc_event` in event loop again.
In more detail, we have to delete `tcp_event` from all the queues on …
=> [BUGFIX] Release tcp_event after socket closing in gpsmon to remove it from event loop

gpcontrib/gp_internal_tools/expected/gp_session_state_memory.out, gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql, gpcontrib/gp_internal_tools/uninstall_gp_session_state.sql
1. SQL script in /gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql and /gpcontrib/uninstall_gp_session_state.sql changes current search_path, this commit set search to default at the end of the above two SQL scripts
2.fix typos in /gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql
3.fix the expect caused by this fix.
=> fix CREATE EXTENSION gp_internal_tools changes search_path

src/bin/gpfdist/regress/Makefile, src/bin/gpfdist/regress/input/gpfdist_ssl.source, src/bin/gpfdist/regress/output/gpfdist_ssl.source
* do curl 127.0.0.1:7070 can not work for gpfdists, we just sleep for 5s
* cp -rf $(MASTER_DATA_DIRECTORY)/gpfdists/* will copy all files in
in gpfdists instead of gpfdists folder into dest folder.
=> Output gpfdist log in regress test

gpcontrib/gpcloud/src/s3key_reader.cpp
Latest version of GCC detects string truncation and gives warnings.
However here is by design, use memcpy instead to avoid the warning.
=> gpcloud: use memcpy to avoid -Wstringop-truncation

contrib/pg_upgrade/greenplum/option_gp.c, contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h, contrib/pg_upgrade/option.c
optarg is a global and is not required to be passed to
process_greenplum_option. Also, for bool parameters pg_strdup must not
be called else it will fail with cannot duplicate null pointer (internal error)
=> upgrade: pg_strdup should not be run on the bool params

gpMgmt/bin/gpcheckcat
`j[i]`, could be the query result of array_agg(), which is a unhashable
list, convert it to a string first.
```
>>> row_of_ids = [[0,1],[1,2]]
>>> colset = set(j for j in row_of_ids)
File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```
```
>>> row_of_ids = [[0,1],[1,2]]
>>> colset = set(str(j) for j in row_of_ids)
>>>
```
Note that since PyGreSQL 5.0 this method will return the values of array
type columns as Python lists.
ref: https://pygresql.org/contents/pg/query.html
=> gpcheckcat: list is unhashable, convert it to a string

gpcontrib/gp_replica_check/gp_replica_check.c, src/test/regress/expected/create_table.out, src/test/regress/sql/create_table.sql
Unlogged tables do not propagate to replica servers, skip them and their
initialization forks.
=> 6X: gp_replica_check: skip checking unlogged tables

gpcontrib/gp_internal_tools/expected/gp_session_state_memory.out, gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql, gpcontrib/gp_internal_tools/uninstall_gp_session_state.sql
1. SQL script in /gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql
and /gpcontrib/uninstall_gp_session_state.sql changes current search_path,
this commit set search_path to default at the end of the above two SQL scripts
2.fix typos in /gpcontrib/gp_internal_tools/gp_internal_tools--1.0.0.sql
3.fix the expect caused by this fix.
This fixes the issue: https://github.com/greenplum-db/gpdb/issues/10575.
(cherry picked from commit 9d9662f0bf217ed40b25f6e6cba01f1308a56126)
=> [6X Backport]Fix CREATE EXTENSION gp_internal_tools changes search_path

concourse/scripts/builds/GpBuild.py, concourse/scripts/regression_tests_gpcloud.bash
This is a fix to https://github.com/greenplum-db/gpdb/commit/94d23e64721217833abdd65674b78bf32959a457 as the gpcloud tests assume a different installation directory on concourse.
=> Use correct installation directory for regression_tests_gpcloud_centos concourse task

src/backend/commands/tablecmds.c, src/test/regress/expected/alter_table.out, src/test/regress/expected/alter_table_gp.out, src/test/regress/sql/alter_table_gp.sql
Raise meaningfull error message for thsi case.
GPDB doesn't support alter type on primary key and unique
constraint column. Because it requires drop - recreate logic.
The drop currently only performs on master which lead error when
recreating index (since recreate index will dispatch to segments and
there still old constraint index exists).
This fix the issue https://github.com/greenplum-db/gpdb/issues/10561.
=> Error out when changing datatype of column with constraint.

gpcontrib/orafce/sql/dbms_pipe_session_B.sql
There is a race condition between receiveFrom() and
dbms_pipe_session_A::createImplicitPipe(). Sleep an extra seconds
is not reliable. So wait until the data is available.
This PR changes the semantics of receiveFrom(), i.e. wait until
the data is available, no timeout happens.
(cherry picked from commit 2f170b36639361153345a48132316d13ae436d3e)
=> 6X: Fix flaky test: dbms_pipe_session_B

src/backend/commands/tablecmds.c, src/test/regress/expected/alter_table.out, src/test/regress/expected/alter_table_gp.out, src/test/regress/sql/alter_table_gp.sql
Raise a meaningful error message for this case.
GPDB doesn't support alter type on primary key and unique
constraint column. Because it requires to drop - recreate logic.
The drop currently only performs on master which lead error when
recreating index (since recreate index will dispatch to segments and
there still an old constraint index exists).
This fixes the issue https://github.com/greenplum-db/gpdb/issues/10561.
(cherry picked from commit 32446a321d492226d3f26d91f3b0deeabce90fd4)
=> [6X Backport]Error out when changing datatype of column with constraint.

contrib/postgres_fdw/Makefile, contrib/postgres_fdw/postgres_fdw.h, src/interfaces/libpq/libpq-fe.h
When using posgres_fdw, it reports the following error:
unsupported frontend protocol 28675.0: server supports 2.0 to 3.0
root casue: Even if postgres_fdw.so is dynamic linked to libpq.so
which is compiled with the option -DFRONTEND, but when it's loaded
in gpdb and run, it will use the backend libpq which is compiled together
with postgres program and reports the error.
We statically link libpq into postgres_fdw and hide all the symbols
of libpq.a with --exclude-libs=libpq.a to make it uses the frontend
libpq.
As postgres_fdw is compiled as a backend without -DFRONTEND, and linked
to libpq which is a frontend, but _PQconninfoOption's length is
different between backend and frontend as there is a macro in it.
The backend's _PQconninfoOption has field connofs, but the frontend
doesn't. …
=> Fix postgres_fdw's libpq issue

src/test/isolation2/expected/uao_crash_compaction_column.out, src/test/isolation2/expected/uao_crash_compaction_row.out, src/test/isolation2/sql/uao_crash_compaction_column.sql, src/test/isolation2/sql/uao_crash_compaction_row.sql
In a normal vacuum, for each column, the vacuum will
1) create a new segment file and record it in the gp_aocsseg_xxxxx
table with a new entry with frozen xmin.
2) compact the tuples in the old segment file and move it to the new
segment file.
3) drop/truncate the old segment file and mark it as dropped in the
gp_aocsseg_xxxxx table.
In the uao_crash_compaction_column test, a PANIC is injected between
step 1 and step2 on seg0, so the whole transaction is aborted.
For seg1 and seg2, because step1 is using a frozen xmin, the new segment
file is visible even the vacuum is aborted.
For seg0, things are different. Because the PANIC occurs right behind
the new segment file is created in a very short time, so the buffer cache
for the new record in the gp_aocsseg_xxxx and the buffer cache for the …
=> Fix flaky uao_crash_compaction_column test

gpMgmt/bin/analyzedb
Commit 445fc7c hardened some parts of analyzedb. However, it missed a
couple of cases.
1) When the statement to get the modcount from the pg_aoseg table failed
due to a dropped table, the transaction was also terminated. This caused
further modcount queries to fail and while those tables were analyzed,
it would error and not properly record the mod count. Therefore, we now
restart the transaction when it errors.
2) If the table is dropped and then recreated while analyzedb is running
(or some other mechanism that results in the table being successfully
analyzed, but the pg_aoseg table did not exist during the initial
check), the logic to update the modcount may fail. Now, we skip the
update for the table if this occurs. In this case, the modcount would
not be recorded and the next …
=> Harden analyzedb further against dropped/recreated tables

gpMgmt/bin/analyzedb
This is a direct backport, except the second commit removes the connection close
due to differences in how dbconns are handled in gpdb master vs 6X.
Commit 445fc7c hardened some parts of analyzedb. However, it missed a
couple of cases.
1) When the statement to get the modcount from the pg_aoseg table failed
due to a dropped table, the transaction was also terminated. This caused
further modcount queries to fail and while those tables were analyzed,
it would error and not properly record the mod count. Therefore, we now
restart the transaction when it errors.
2) If the table is dropped and then recreated while analyzedb is running
(or some other mechanism that results in the table being successfully
analyzed, but the pg_aoseg table did not exist during the initial
check), the logic to …
=> [6X] Harden analyzedb further against dropped/recreated tables

gpdb-doc/dita/analytics/analytics.ditamap, gpdb-doc/dita/analytics/postGIS.xml, gpdb-doc/dita/analytics/postgis-upgrade.xml
Upgrade instructions 2.1.5 to different versions of 2.5.4
Includes upgrade to PostGIS 2.5.4.pivotal.3 package.
Will be backported to 6X_STABLE only.
Link to HTML output on a temporary GPDB doc site.
https://docs-msk-gpdb7-dev.cfapps.io/7-0/analytics/postgis-upgrade.html
=> docs - add information on upgrading to PostGIS 2.5.4

src/backend/gpopt/translate/CTranslatorScalarToDXL.cpp, src/backend/utils/cache/plancache.c
If you have plan_cache_mode=auto, which is the default, never try to
generate "generic" plans. GPORCA doesn't support Param nodes, so it will
always fall back to the Postgres planner. What happened without this patch
was that the backend code would compare the cost of the custom plan
generated with GPORCA with the cost of a generic plan generated with the
Postgres planner, and that doesn't make much sense because the GPORCA has
a very different cost model from the Postgres planner.
No test, because it would be quite tedious and fragile to write one, and
the code change seems simple enough.
I bumped into this while hacking on PR #10676, which changes the Postgres
planner's cost model. There's a test in 'direct_dispatch' for the generic
plan generation, and it started to fail because with …
=> Don't try to generate generic plans with GPORCA.

gpMgmt/bin/analyzedb, gpMgmt/bin/gppylib/operations/dump.py
Commit 2ba1627 hardened some parts of analyzedb. However, it missed a
couple of cases.
1) When the statement to get the modcount from the pg_aoseg table failed
due to a dropped table, the transaction was also terminated. This caused
further modcount queries to fail and while those tables were analyzed,
it would error and not properly record the mod count. Therefore, we now
restart the transaction when it errors.
2) If the table is dropped and then recreated while analyzedb is running
(or some other mechanism that results in the table being successfully
analyzed, but the pg_aoseg table did not exist during the initial
check), the logic to update the modcount may fail. Now, we skip the
update for the table if this occurs. In this case, the modcount would
not be recorded and the next …
=> [5X] Harden analyzedb further against dropped/recreated tables

src/backend/access/external/url_curl.c
Fix libcurl can not read data from gpfdist
on MacOS
But gpfdist with a pipe can not work on macos as
flock(2) which is used in gfile.c is not supported
on MacOS.
Fix the issue: https://github.com/greenplum-db/gpdb/issues/4105
=> Fix url_curl on MacOS

GNUmakefile.in, contrib/dblink/Makefile, contrib/dblink/dblink.c
When using dblink to connect to a postgres database, it reports the
following error:
unsupported frontend protocol 28675.0: server supports 2.0 to 3.0
Even if dblink.so is dynamic linked to libpq.so which is compiled
with the option -DFRONTEND, but when it's loaded in gpdb and run,
it will use the backend libpq which is compiled together with
postgres program and reports the error. So we define FRONTEND
before defining libpq-fe.h.
=> Fix dblink's libpq issue on gpdb 5X

contrib/postgres_fdw/Makefile, contrib/postgres_fdw/postgres_fdw.h
When using posgres_fdw, it reports the following error:
unsupported frontend protocol 28675.0: server supports 2.0 to 3.0
root cause: Even if postgres_fdw.so is dynamic linked to libpq.so
which is compiled with the option -DFRONTEND, but when it's loaded
in gpdb and run, it will use the backend libpq which is compiled together
with postgres program and reports the error.
We statically link libpq into postgres_fdw and hide all the symbols
of libpq.a with --exclude-libs=libpq.a to make it uses the frontend
libpq.
As postgres_fdw is compiled as a backend without -DFRONTEND, and linked
to libpq which is a frontend, but _PQconninfoOption's length is
different between backend and frontend as there is a macro in it.
The backend's _PQconninfoOption has field connofs, but the frontend
doesn't. …
=> Fix postgres fdw on gpdb 6X

GNUmakefile.in, contrib/dblink/Makefile, contrib/dblink/dblink.c
When using dblink to connect to a postgres database, it reports the
following error:
unsupported frontend protocol 28675.0: server supports 2.0 to 3.0
Even if dblink.so is dynamic linked to libpq.so which is compiled
with the option -DFRONTEND, but when it's loaded in gpdb and run,
it will use the backend libpq which is compiled together with
postgres program and reports the error. So we define FRONTEND
before defining libpq-fe.h.
This pr is almost the same as the pr:
https://github.com/greenplum-db/gpdb/pull/10617
which is used to fix postgres_fdw issue
=> Fix dblink's libpq issue on gpdb 6X

src/backend/cdb/cdbgroupingpaths.c, src/backend/optimizer/plan/planner.c, src/include/cdb/cdbgroupingpaths.h, src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/expected/gp_aggregates.out, src/test/regress/sql/bfv_aggregate.sql
This introduces two new functions cdb_prepare_path_for_sorted_agg() and
cdb_prepare_path_for_hashed_agg(), to sort and/or redistribute the input
to an Agg node, in single-phase aggregation. Previously, the logic was
in the callers in planner.c. This is in preparation for the PostgreSQL v12
merge, which will introduce more codepaths that create Agg nodes;
encapsulating the logic in functions reduces the duplication.
Parallel grouping is currently disabled alogether, but if it wasn't, we
should be using these functions when creating parallel grouping paths,
too.
There's one almost user-visible change here, which explains the change
in 'gp_aggregates' expected output. If a sorted Gather Motion is created,
we now use the path keys needed for the grouping (root->grouped_pathkeys),
rather than …
=> Refactor code to sort/redistribute input to Agg nodes.

src/backend/cdb/cdbtm.c, src/include/cdb/cdbtm.h
shmNumGxacts and shmGxactArray are accessed under the protection of
shmControlLock, this commit add some defensive code and PANIC at the earliest
when the shared memory is corrupted.
=> PANIC when the shared memory is corrupted

src/backend/postmaster/backoff.c
Previous commit ab74e1c, c7befb1 did not completely solve its race
condition, it did not test for last iteration of the while/for loop.
This could result in failed assertion in the following loop. The patch
moves the judgement to the ending of the for loop, it is safe, because
the first iteration will never trigger: Assert(activeWeight > 0.0).
Also, the other one race condition can trigger this assertion
Assert(gl->numFollowersActive > 0). Consider this situation:
Backend A, B belong to the same statement.
Timestamp1: backend A's leader is A, backend B's leader is B.
Timestamp2: backend A's numFollowersActive remains zero due to timeout.
Timestamp3: Sweeper calculates leader B's numFollowersActive to 1.
Timestamp4: backend B changes it's leader to A even if A is inactive.
We stop sweeping …
=> [Backport 5X] Fix assertion failures in BackoffSweeper

src/backend/commands/tablecmds.c, src/test/regress/expected/alter_table_gp.out, src/test/regress/sql/alter_table_gp.sql
Raise a meaningful error message for this case.
GPDB doesn't support alter type on primary key and unique
constraint column. Because it requires to drop - recreate logic.
The drop currently only performs on master which lead error when
recreating index (since recreate index will dispatch to segments and
there still an old constraint index exists).
This fixes the issue https://github.com/greenplum-db/gpdb/issues/10561.
(cherry picked from commit 32446a321d492226d3f26d91f3b0deeabce90fd4)
=> [5X Backport]Error out when changing datatype of column with constraint.

src/backend/utils/misc/guc_gp.c
This is used to avoid "writer segworker group shared snapshot collision on id
153871" kind of error.  Pengzhou and I saw this in a real product environment
on gpdb 5. Pengzhou suspected that writer gang exits due to
gp_vmem_idle_resource_timeout but it exits slowly because of ProcArrayLock
contention so the collision happens when a new gang is created. The theory was
roughly verified with process core dump when that issue happens - ProcArrayLock
contention was found in those core files.
Increasing the default gp_snapshotadd_timeout value to tolerate more with the
case. We have been optimizing the ProcArrayLock but we can not 100% avoid the
contention.
=> Increase default value of guc gp_snapshotadd_timeout

contrib/Makefile, contrib/postgres_fdw/Makefile
postgres_fdw can't built on Mac
=> Fix postgres_fdw makefile

src/backend/commands/analyze.c, src/backend/commands/analyzefuncs.c, src/include/commands/vacuum.h, src/test/regress/expected/bfv_statistic.out, src/test/regress/expected/bfv_statistic_optimizer.out, src/test/regress/expected/gp_aggregates_costs.out, src/test/regress/sql/bfv_statistic.sql
Commit 0c27e42adb changed the way that the gp_acquire_sample_rows()
function, called by ANALYZE, collects the sample rows. With the commit,
the sample size was not chosen correctly. The sample size is passed to
gp_acquire_sample_rows() as an argument, 'targrows', but the function did
not pass it down to the do_analyze_rel() function that actually collects
the sample. As a result, do_analyze_rel() collected a larger sample, but
gp_acquire_sample_rows() only returned the first 'targrows' rows of it
to the caller.
For example, if you have three segments and the total desired sample size
is 3000 rows, gp_acquire_sample_rows() is called with targrows=1000. But
do_analyze_rel() nevertheless collected a sample with 3000 rows, but
only the first 1000 rows of it were returned to the QD. The end …
=> Fix gathering statistics sample from segments.

src/backend/commands/analyze.c, src/backend/commands/analyzefuncs.c, src/include/commands/vacuum.h, src/test/regress/expected/analyze.out, src/test/regress/sql/analyze.sql
When QD acquiring sample rows on QE, the QE should only collects required
on parent or all inherited tables. Otherwise, the QD may get wrong results
for parent table since the inherited tables will overwrite the expected
values. And we'll have incorrect results in pg_class and pg_statistic.
In `gp_acquire_sample_rows`, the function has three inputs, but somehow,
the code loses the last `inherited` argument usage. This is important to
distinguish whether the QD need samples for parent only or all inherited
tables.
=> Fix bug for ANALYZE inherited tables.

src/backend/optimizer/plan/planner.c
If you have a pre-sorted input, like Index Scan, and a DISTINCT clause,
the planner would create an invalid plan. A Redistribute Motion node is
breaks the ordering of its input, so such a plan cannot be used as
input to a Unique node.
This is possibly unreachable at the moment, because parse analysis
transforms simple DISTINCT queries to GROUP BY (see call to
transformDistinctToGroupBy() in transformSelectStmt()). I have not been
able to come up with a query that would exercise this codepath; any
simple query is transformed to a GROUP BY, and anything more complicated,
with window functions or aggregates, don't yield sorted input to the
DISTINCT stage. But if you disable the DISTINCT -> GROUP BY transformation
in parse analysis, this query caused an assertion before this commit: …
=> Fix DISTINCT plans created on top of pre-sorted inputs.

src/backend/access/bitmap/bitmap.c, src/backend/access/bitmap/bitmapsearch.c, src/test/regress/expected/bitmap_index.out, src/test/regress/expected/bitmap_index_optimizer.out, src/test/regress/sql/bitmap_index.sql
Index Only Scans have not been implemented on Bitmap Indexes, but in
certain circumstances, when the query doesn't need any of the attributes
from the index, like in "SELECT count(*) from table", the planner may
still choose an Index Only Scan. It's debatable if that's actually a
planner bug, but we can easily support that limited case.
=> Fix crash when planner chose an Index Only Scan on a bitmap index.

src/backend/executor/nodeFunctionscan.c, src/backend/executor/nodeValuesscan.c, src/test/regress/expected/bfv_subquery.out, src/test/regress/expected/bfv_subquery_optimizer.out, src/test/regress/sql/bfv_subquery.sql
When converting semi-join to inner-join, one distinct agg on ctid is added
above the hash-join node. But tuples from VALUE scan may have invalid ctids;
so the assert check failed. 
This patch is based on commit d8886cf9.
Query:
```
SELECT * FROM tmp A WHERE (a=any(values (0),(1), (5), (99))) and (b >= '2019-09-20 00:00:00' AND b < '2019-09-21 00:00:00')
AND (c = ANY(VALUES ('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),
('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),
('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),
('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307'),('3307' …
```
=> value scan use ctid crash

src/backend/commands/cluster.c, src/backend/commands/vacuum.c, src/include/commands/vacuum.h, src/test/isolation2/expected/vacuum_full_interrupt.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/vacuum_full_interrupt.sql
When doing 'VACUUM FULL', 'swap_relation_files' updates the pg_class entry but
not increase the command counter, so the later 'vac_update_datfrozenxid' will
inplace update the 'relfrozenxid' and 'relhasindex' of old tuple, when the
transaction is interrupted and aborted on the QE after this, the old entry is
corrupted.
=> Fix a 'VACUUM FULL' bug

contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h, contrib/pg_upgrade/greenplum/reporting.c, contrib/pg_upgrade/pg_upgrade.c, contrib/pg_upgrade/relfilenode.c, contrib/pg_upgrade/test/integration/init_file, contrib/pg_upgrade/test/integration/output/different_name_index_backed_constraint.source, contrib/pg_upgrade/test/integration/output/exchange_partition_heap_table.source, contrib/pg_upgrade/test/integration/output/foreign_key_constraint.source, contrib/pg_upgrade/test/integration/output/gphdfs.source, contrib/pg_upgrade/test/integration/output/indexes.source, contrib/pg_upgrade/test/integration/output/large_objects.source, contrib/pg_upgrade/test/integration/output/mismatched_aopartition_indexes.source, contrib/pg_upgrade/test/integration/output/mismatched_partition_schemas.source, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_dropped_columns.source, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_varlen_dropped_columns.source, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_sized_dropped_columns.source, contrib/pg_upgrade/test/integration/output/unsupported_dist_coltypes.source, contrib/pg_upgrade/test/integration/output/unsupported_name_col.source, contrib/pg_upgrade/test/integration/output/unsupported_tsquery_col.source, contrib/pg_upgrade/test/unit/Makefile, contrib/pg_upgrade/test/unit/reporting_test.c, contrib/pg_upgrade/util.c
This commit add a new flag which allows printing the time taken by the steps during pg_upgrade. It uses the fact that prep_status and check_ok are run in conjunction (except where prep_status is used to print a new line), and starts a timer during prep_status and logs the timing during check_ok if timing is requested.
=> pg_upgrade: Add setup to log timing for check and upgrade steps

src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
With this patch, the whole translator compiles warning free.
null_ndv was orphaned in commit 25479cf1500b ("Fix num_distinct
calculation in relcache translator").
coercePathType was dead on arrival in commit cc799db46933 ("Fix Relcache
Translator to send CoercePath info (#2842)").
=> [gpopt] Remove dead variables from translator

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/input/resgroup/resgroup_memory_runaway.source, src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
When calculating safeChunksThreshold of runaway in resource group,
we used to divide by 100 to get the number of safe chunks. This may
lead to small chunk numbers to be rounded to zero. Fix it by storing
safeChunksThreshold100(100 times bigger than the real safe chunk) and
do the computation on the fly.
=> Fix resource group runaway rounding issue

src/backend/cdb/motion/ic_proxy_main.c, src/backend/postmaster/postmaster.c
Proxy bgworker will become orphan process after postmaster is dead
due to the lack of checking WL_POSTMASTER_DEATH in WaitLatch.
Since proxy bgworker uses libuv timer to replace the WaitLatch sleep,
the WaitLatch timeout should be set to zero.
=> ic-proxy: Quit proxy bgworker when postmaster is dead

src/backend/cdb/motion/ic_proxy_main.c, src/backend/utils/mmgr/redzone_handler.c, src/backend/utils/resgroup/resgroup.c
Resource group used to access resGroupSlot in SessionState without
lock. This is correct when session only access resGroupSlot by itself.
But as we introduced runaway feature, we need to traverse the current
session array to find the top consumer session when redzone is reached.
This requires:
1. runaway detector should hold shared resgroup lock to avoid resGroupSlot
is detached from a session concurrently when redzone is reached.
2. normal session should hold exclusive lock when modifying resGroupSlot
in SessionState.
=> Using lwlock to protect resgroup slot in session state

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/input/resgroup/resgroup_memory_runaway.source, src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
When calculating safeChunksThreshold of runaway in resource group,
we used to divide by 100 to get the number of safe chunks. This may
lead to small chunk numbers to be rounded to zero. Fix it by storing
safeChunksThreshold100(100 times bigger than the real safe chunk) and
do the computation on the fly.
(cherry picked from commit 757184f92e7ae6c0fbfc8a228fa3fe18340f8072)
=> [Backport 6X] Fix resource group runaway rounding issue

src/backend/utils/resgroup/resgroup.c, src/test/isolation2/input/resgroup/resgroup_memory_runaway.source, src/test/isolation2/output/resgroup/resgroup_memory_runaway.source
When calculating safeChunksThreshold of runaway in resource group,
we used to divide by 100 to get the number of safe chunks. This may
lead to small chunk numbers to be rounded to zero. Fix it by storing
safeChunksThreshold100(100 times bigger than the real safe chunk) and
do the computation on the fly.
(cherry picked from commit 757184f92e7ae6c0fbfc8a228fa3fe18340f8072)
=> [Backport 5X] Fix resource group runaway rounding issue

src/backend/cdb/motion/ic_proxy_main.c
Proxy bgworker will become orphan process after postmaster is dead
due to the lack of checking pipe postmaster_alive_fds[POSTMASTER_FD_WATCH].
Epoll this pipe inside proxy bgworker main loop as well.
(cherry picked from commit 9ce59d1a6f07ee7476f77ab6bd851f923ba09bc8)
=> [Backport 6X] ic-proxy: Quit proxy bgworker when postmaster is dead

src/backend/utils/mmgr/redzone_handler.c, src/backend/utils/resgroup/resgroup.c
Resource group used to access resGroupSlot in SessionState without
lock. This is correct when session only access resGroupSlot by itself.
But as we introduced runaway feature, we need to traverse the current
session array to find the top consumer session when redzone is reached.
This requires:
1. runaway detector should hold shared resgroup lock to avoid resGroupSlot
is detached from a session concurrently when redzone is reached.
2. normal session should hold exclusive lock when modifying resGroupSlot
in SessionState.
(cherry picked from commit a4cb06b4005b9a397361d6f678e1db6989972350)
=> [Backport 5X] Using lwlock to protect resgroup slot in session state

src/backend/storage/ipc/procsignal.c, src/test/regress/expected/async.out, src/test/regress/sql/async.sql
This will make LISTEN and NOTIFY work on the QD node.
It was tested by async.sql, but not working on different sessions.
=> Handle the PROCSIG_NOTIFY_INTERRUPT signal

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
We found several problems with outer references in outer joins and
related areas, especially when using optimizer_join_order = exhaustive2.
Adding some tests. Please note that due to some remaining problems in
both ORCA and planner, the tests contain some FIXMEs.
The corresponding ORCA PR is https://github.com/greenplum-db/gporca/pull/599.
Issue https://github.com/greenplum-db/gpdb/issues/10452 was filed for the wrong results with planner.
=> Add test cases for correlated subqueries with outer joins

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/backend/gpopt/translate/CTranslatorUtils.cpp, src/backend/gpopt/utils/Makefile, src/backend/gpopt/utils/RelationWrapper.cpp, src/include/gpopt/gpdbwrappers.h, src/include/gpopt/utils/RelationWrapper.h
Over at #10728, it has been suggested that:
1. Don't use `nullptr` until we've ridden the entire ORCA code base of `NULL`
1. `auto` is unreadable. Spell out the new type `RelationWrapper`
1. Don't overload `operator ->` or `operator ==` or `operator !=`
1. Don't overload `operator bool`.
1. Don't allow implicit cast from `RelationWrapper` to `Relation`.
Here's a patch set that follows those suggestions.
1. I'm glad that stylistic preferences came up in code review rather than felt later in the team that a change has been "snuck in".
1. I opened #10728 because I cannot stomach the manual clean up in code like this:
```c++
Relation rel = GetRelation(...);
if (!RelIsSupported(rel)) {
CloseRelation(rel);
return -1;
}
GPOS_TRY {
do_stuff(rel);
int i = calculate_stuff(rel->rd_att->natts); …
```
=> [RFC] Safer relation cleanup (alt ver)

config/c-compiler.m4, config/c-library.m4, configure
GPDB was failing to configure on macOS Catalina 10.15 with clang version 12.0.0 (clang-1200.0.31.1) with the following error: `configure: error: Cannot find a working 64-bit integer type.`
This is a cherry-pick commit from upstream that fixes the above issue. See upstream mailing list discussion:
https://www.postgresql.org/message-id/flat/09A4B554-82B1-4536-B191-2461342EE0BB%40icloud.com
Thanks to @d  for his help in this!
[Test pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/7X_configure_fix_int64)
=> Use return instead of exit() in configure

src/backend/cdb/test/cdbtm_test.c
commit 4f5a2c2 breaks the unittest cdbtm_test
=> [5X Only]Fix unit test failure

src/backend/commands/cluster.c, src/backend/commands/vacuum.c, src/include/commands/vacuum.h, src/test/isolation2/expected/vacuum_full_interrupt.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/vacuum_full_interrupt.sql
When doing 'VACUUM FULL', 'swap_relation_files' updates the pg_class entry but
not increase the command counter, so the later 'vac_update_relstats' will
inplace update the 'relfrozenxid' and 'relhasindex' of old tuple, when the
transaction is interrupted and aborted on the QE after this, the old entry is
corrupted.
=> [6X backport] Fix a 'VACUUM FULL' bug

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/.gitignore, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/data/external_file_16.txt, gpMgmt/bin/gpload_test/gpload2/query41.ans
Reverts greenplum-db/gpdb#10763
That commit caused gpload tests in test_gpdb_clients_windows job to fail.
A sample of the diffs looks like the following
--- C:\Users\buildbot\gpload2\query9.ans	2020-09-07 11:54:36.936844300 +0000
+++ C:\Users\buildbot\gpload2\query9.out	2020-09-07 11:54:36.936844300 +0000
@@ -1,4 +1,6 @@
GP_IGNORE: formatted by atmsort.pm
+HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
+NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 's1' as the Greenplum Database data distribution key for this table.
TODAYS_DATE1|INFO|gpload session started TODAYS_DATE2
TODAYS_DATE1|INFO|setting schema 'public' for table 'texttable'
TODAYS_DATE1|INFO|ports …
=> Revert "fix gpload upper letters in column in merge mode  "

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/.gitignore, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/data/external_file_16.txt, gpMgmt/bin/gpload_test/gpload2/query41.ans
Reverts greenplum-db/gpdb#10751
This commit change is the same as the commit #10763 in the master branch. As #10763 caused the gpload tests in test_gpdb_clients_windows job to fail, it's better to revert this PR to avoid possible failure in 6X_STABLE.
=> Revert "fix gpload fail when capital letters in column name in merge mode"

gpMgmt/bin/gppylib/operations/filespace.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py, gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/environment.py, gpMgmt/test/behave/mgmt_utils/gpstart.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
When the standby is unreachable and the user proceeds with startup, gpstart fails to start when temporary or transaction files have been moved to a non-default filespace.
To determine when the standby is unreachable fetch_tli was reworked to raise a StandbyUnreachable exception. And the standby is not started if it is unreachable.
This fix is is only needed for 5X since filespaces are only in 5X.
[Test Pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/5X_gpstart-without-standby-host)
**Note:** @lenapivotal and @mkiyama this change probably needs a documentation release note for 5X.
=> [5X] gpstart: skip filespace checks for standby when unreachable

gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py, gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/gpstart.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Much of similar code taken from this 5X bug fix https://github.com/greenplum-db/gpdb/pull/10742
When the standby is unreachable and the user proceeds with startup, the standby would attempt to be started resulting in a stack trace. Detect when the standby is unreachable and set start_standby to False to prevent starting it later in the startup process.
Test Pipeline - [dev](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/7X_gpstart-without-standby-host) and [cm](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/7X_gpstart-without-standby-host)
=> gpstart: when standby is unreachable don't start it

src/backend/utils/workfile_manager/workfile_mgr.c
We used to have `Assert` to check `RegisterFileWithSet` never register
file to a non-active workfile_set. But in porduction, there could be
some coner cases that caller register file to a non-active workfile_set.
It'll cause inconsistent `workfile_shared->num_active` with the real
active workfile_sets numbers under some situations.
For example,
1. `RegisterFileWithSet` a file to a created work_set. (current
`work_set->num_files` is 1)
2. `FileClose` closes the file and causes `WorkFileDeleted` to detele
the work_set since current `work_set->num_files` is 0 after detele file.
Which also decrease `workfile_shared->num_active`.
3.  `RegisterFileWithSet` another file to the created work_set(which
actually is not active now, but we dont't prevent that, only uses
`Assert` to check).
4. …
=> PANIC when register file to a non-active workfile set.

src/bin/gpfdist/regress/gen_multiCA_certs.bash, src/bin/gpfdist/regress/input/gpfdists_multiCA.source, src/bin/gpfdist/regress/output/gpfdists_multiCA.source
On centos7, the system libcurl uses NSS instead of OpenSSL as backend
for TLS/SSL connections. Previously it will fail if hostname is used
in external table location, probably due to initialization issues.
This is fixed by commit 89a1211c. Modify original test case to use
hostname.
curl is used for connection testing in gpfdist_ssl_start. But it will
always fail since we are now using SSL. Change the condition to not
equal to 7. This code can be found at curl documentation:
https://curl.haxx.se/libcurl/c/libcurl-errors.html
=> Test gpfdists external table with hostname

gpMgmt/Makefile, gpMgmt/bin/generate-greenplum-path.sh, gpMgmt/bin/gpload
Update greenplum_path.sh to use BASH_SOURCE for determining GPHOME
Update gpload test script to use bash instead of sh
discussion mail list: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/AgEGOsoAAlQ/m/a2VIBZgMCQAJ
dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-173785163-gphome-gp7
=> GPHOME is determined dynamically when sourcing greenplum_path

src/backend/access/external/url_curl.c, src/bin/gpfdist/regress/.gitignore, src/bin/gpfdist/regress/Makefile, src/bin/gpfdist/regress/change_client_cert.bash, src/bin/gpfdist/regress/gen_multiCA_certs.bash, src/bin/gpfdist/regress/input/gpfdists_multiCA.source, src/bin/gpfdist/regress/output/gpfdists_multiCA.source
On centos7, the system libcurl uses NSS instead of OpenSSL as backend
for TLS/SSL connections. Previously it will fail if hostname is used in external
table location, probably due to initialization issues.
This is fixed by commit 89a1211c on master. 
Backport d7e86dda, 89a1211c, 2f4aa7eb to fix gpfdists external table
issue on centos7.
=> Fix gpfdists hostname issue on centos7

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk, src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/test/regress/expected/direct_dispatch.out, src/test/regress/expected/direct_dispatch_optimizer.out, src/test/regress/sql/direct_dispatch.sql
Mostly clean backport, however can't direct dispatch to multiple segments as that was not implemented until GPDB 6X commit 576690f.  Straightforward diff 39fe59cb085e
---
This approach special cases gp_segment_id enough to include the column
as a distributed column constraint. It also updates direct dispatch info
to be aware of gp_segment_id which represents the raw value of the
segment where the data resides. This is different than other columns
which hash the datum value to decide where the data resides.
After this change the following DDL shows Gather Motion from 2 segments
on a 3 segment demo cluster.
```
CREATE TABLE t(a int, b int) DISTRIBUTED BY (a);
EXPLAIN SELECT gp_segment_id, * FROM t WHERE gp_segment_id=1 or gp_segment_id=2;
QUERY PLAN …
```
=> [5X backport] Allow setting direct dispatch info if predicate on column gp_segment_id

gpMgmt/bin/gppylib/test/unit/test_unit_gpstart.py, gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/gpstart.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Backport of https://github.com/greenplum-db/gpdb/pull/10770 which is much of similar code taken from this 5X bug fix https://github.com/greenplum-db/gpdb/pull/10742
When the standby is unreachable and the user proceeds with startup, the standby would attempt to be started resulting in a stack trace. Detect when the standby is unreachable and set start_standby to False to prevent starting it later in the startup process.
Test Pipeline - [dev](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_gpstart-without-standby-host) and [cm](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6X_gpstart-without-standby-host)
=> [6X Backport] gpstart: when standby is unreachable don't start it

src/backend/utils/workfile_manager/workfile_mgr.c
We used to have `Assert` to check `RegisterFileWithSet` never register
file to a non-active workfile_set. But in production, there could be
some corner cases that caller register file to a non-active workfile_set.
It'll cause inconsistent `workfile_shared->num_active` with the real
active workfile_sets numbers under some situations.
For example,
1. `RegisterFileWithSet` a file to a created work_set. (current
`work_set->num_files` is 1)
2. `FileClose` closes the file and causes `WorkFileDeleted` to detele
the work_set since current `work_set->num_files` is 0 after detele file.
Which also decrease `workfile_shared->num_active`.
3.  `RegisterFileWithSet` another file to the created work_set(which
actually is not active now, but we dont't prevent that, only uses
`Assert` to check).
4. …
=> [6X Backport]PANIC when register file to a non-active workfile set.

concourse/scripts/common.bash, src/backend/cdb/motion/README.ic-proxy.md, src/backend/cdb/motion/ic_proxy_addr.c, src/backend/cdb/motion/ic_proxy_addr.h, src/backend/cdb/motion/ic_proxy_main.c, src/backend/cdb/motion/ic_proxy_peer.c
The GUC gp_interconnect_proxy_addresses is used to set the listener
addresses and ports of all the proxy bgworkers, only IP addresses were
supported previously, which is inconvenient to use.
Now we add the support for hostnames too, the IP addresses are also
supported.
Note that if a hostname is bound to a different IP at runtime, we must
reload the setting with the "gpstop -u" command.
=> ic-proxy: support hostname as proxy addresses

src/backend/cdb/motion/ic_proxy.h
A typical mistake on allocating typed memory is as below:
int64 *ptr = malloc(sizeof(int32));
To prevent this, now we make ic_proxy_new() a typed allocator, it always
return a pointer of the specified type, for example:
int64 *p1 = ic_proxy_new(int64); /* good */
int64 *p2 = ic_proxy_new(int32); /* bad, gcc will raise a warning */
(cherry picked from commit a3ef623d49824ba2ab90ede71ca2551fb8c57d70)
----
This is to backport 10576 to 6X.
=> 6X: ic-proxy: type checking in ic_proxy_new()

concourse/scripts/common.bash, src/backend/cdb/motion/README.ic-proxy.md, src/backend/cdb/motion/ic_proxy_addr.c, src/backend/cdb/motion/ic_proxy_addr.h, src/backend/cdb/motion/ic_proxy_main.c, src/backend/cdb/motion/ic_proxy_peer.c
The GUC gp_interconnect_proxy_addresses is used to set the listener
addresses and ports of all the proxy bgworkers, only IP addresses were
supported previously, which is inconvenient to use.
Now we add the support for hostnames too, the IP addresses are also
supported.
Note that if a hostname is bound to a different IP at runtime, we must
reload the setting with the "gpstop -u" command.
(cherry picked from commit 2a1794bc47e58ea033e68ee1d8ef3ab2f999706f)
=> 6X: ic-proxy: support hostname as proxy addresses

config/c-compiler.m4, config/c-library.m4, configure
Master and 6X Backport of https://github.com/greenplum-db/gpdb/pull/10762 and https://github.com/greenplum-db/gpdb/pull/10768
GPDB was failing to configure on macOS Catalina 10.15 with clang version 12.0.0 (clang-1200.0.31.1) with the following error: `configure: error: Cannot find a working 64-bit integer type.`
This is a cherry-pick commit from upstream that fixes the above issue. See upstream mailing list discussion:
https://www.postgresql.org/message-id/flat/09A4B554-82B1-4536-B191-2461342EE0BB%40icloud.com
Thanks to @d  for his help in this!
[Test pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/5X_configure_fix_int64)
=> [5X Backport] Use return instead of exit() in configure

config/c-compiler.m4, config/c-library.m4, configure
6X Backport of https://github.com/greenplum-db/gpdb/pull/10762
GPDB was failing to configure on macOS Catalina 10.15 with clang version 12.0.0 (clang-1200.0.31.1) with the following error: `configure: error: Cannot find a working 64-bit integer type.`
This is a cherry-pick commit from upstream that fixes the above issue. See upstream mailing list discussion:
https://www.postgresql.org/message-id/flat/09A4B554-82B1-4536-B191-2461342EE0BB%40icloud.com
Thanks to @d  for his help in this!
[Test pipeline](https://cm.ci.gpdb.pivotal.io/teams/main/pipelines/6X_configure_fix_int64)
=> [6X Backport] Use return instead of exit() in configure

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/bin/pg_upgrade/test_gpdb_pre.sql, src/test/regress/expected/bfv_index.out, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/sql/bfv_index.sql
Function `RelationGetIndexList()` does not filter out invalid indexes.
That responsiblity is left to the caller (e.g. `get_relation_info()`).
Issue is that Orca was not checking index validity.
This commit also introduces an optimization to Orca that is already used
in Planner whereby we first check relhasindex before checking pg_index.
=> Align Orca relhasindex behavior with Planner

gpAux/gpperfmon/src/gpmon/gpmmon.c, gpAux/gpperfmon/src/gpmon/gpsmon.c
The `terminate_timeout` and `recv_timeout` parameters are defined based on incoming quantum value before its [invalidation/normalization](https://github.com/greenplum-db/gpdb/blob/6.10.1/gpAux/gpperfmon/src/gpmon/gpmmon.c#L1276-L1289) phase. As a consequence those parameters can take on values that lead to unstable interaction between gpmmon and gpsmon.
Current fix moves assignment of `terminate_timeout` and `recv_timeout` behind invalidation/normalization block. Furthermore, as `terminate_timeout` is passed to gpsmon as startup option, the guard that disallow zero timeout value forr `tcp_event` is added.
1. Set `quantum` parameter in gpperfmon.conf to zero or one.
2. Reload gpperfmon.conf via SIGHUP to gpmmon daemon.
3. Kill `gpsmon` so `gpmmon` can restart it with new …
=> gpperfmon: fix timeout characteristics that directly depends on raw quantum value

src/test/isolation2/expected/prepared_xact_deadlock_pg_rewind.out, src/test/isolation2/sql/prepared_xact_deadlock_pg_rewind.sql
@@ -14,11 +14,11 @@
role | preferred_role | content | mode | status
------+----------------+---------+------+--------
m    | m              | -1      | s    | u
- m    | m              | 0       | s    | u
+ m    | m              | 0       | n    | u
The root cause has nothing to do with this test case.  It's because test
prepared_xact_deadlock_pg_rewind finally calls gprecoverseg to recover the
cluster but does not wait until the cluster state restores.
=> Fix flaky test uao_crash_compaction_column

src/backend/cdb/cdbdtxrecovery.c, src/backend/cdb/cdbtm.c, src/backend/postmaster/postmaster.c, src/backend/utils/misc/ps_status.c, src/include/cdb/cdbtm.h, src/include/storage/pmsignal.h, src/test/isolation2/expected/crash_recovery_dtm.out, src/test/isolation2/sql/crash_recovery_dtm.sql
Previously QD panicks when Abort Prepared retry fails but this is not friendly
due to master reset (all sessions are gone). The panic is not that needed since
even Abort Prepared fails the cluster is consistent, but we still need to try
to finish the Abort since the orphaned prepared transaction still holds
resources.  Now that we do periodical handling of orphaned prepared transaction
in the dtx recovery process, QD could simply ignore and then proceed if Abort
Prepared retry fails.
=> Avoid panic after Abort Prepared retry fails.

src/backend/cdb/cdbdtxrecovery.c, src/test/isolation2/expected/terminate_in_gang_creation.out, src/test/isolation2/sql/terminate_in_gang_creation.sql
The test depends on fault create_gang_in_progress. Previously the fault might
be hit by dtx recovery when creating a new gang. Let's skip
checking in dtx recovery to avoid the test flakiness.
The test flakiness looks like this:
10&: SELECT * FROM foo a JOIN foo b USING (c2);  <waiting ...>
+FAILED:  Forked command is not blocking; got output: c2 | c1 | c1
+----+----+----
+(0 rows)
We could easily reproduce this by adding some sleep before the query.
=> Fix flaky test isolation2:terminate_in_gang_creation

src/backend/optimizer/util/pathnode.c, src/test/regress/expected/with_clause.out, src/test/regress/expected/with_clause_optimizer.out, src/test/regress/sql/with_clause.sql
A CteScan's pathkeys were incorrectly taken from the subpath. That's wrong
because a CteScan's subpath belongs to the subquery, which has its own
equivalence classes, range table and everything. The subpath's pathkeys
are nonsensical in the outer query. The caller of create_ctescan_path()
correctly converted the subpath's pathkeys to the outer query's context,
but create_ctescan_path() didn't use the passed-in pathkeys correctly.
As a result, queries involving CTEs would sometimes sort, even though the
input was already sorted. For example:
postgres=# explain (costs off) with my_order as
(select * from with_test1 order by i)
select i, count(*)
from my_order
group by i order by i;
QUERY PLAN
------------------------------------------------------ …
=> Fix pulling up pathkeys from a CTE plan.

src/backend/optimizer/prep/prepjointree.c, src/backend/utils/adt/selfuncs.c, src/test/regress/expected/dpe.out, src/test/regress/expected/equivclass.out, src/test/regress/expected/inherit.out, src/test/regress/expected/inherit_optimizer.out, src/test/regress/expected/join_gp.out, src/test/regress/expected/olap_window_seq.out, src/test/regress/expected/union.out, src/test/regress/expected/union_optimizer.out, src/test/regress/sql/equivclass.sql, src/test/regress/sql/inherit.sql, src/test/regress/sql/union.sql
There's no good reason to not do it anymore. It was disabled back in 2008,
when this test query was failing:
postgres=# create table tab as select generate_series(1,10) as a;
SELECT 10
postgres=# select * from tab where a in (select a from tab where a = 2 union all values (4));
ERROR:  Cannot append paths with incompatible distribution
But that's been fixed a long time ago, there's now code that adds Motions
as needed to the branches of an append relation, and there are test cases
for that in the 'union_gp' test. That query works fine now with the
optimization.
Some changes were required in examine_simple_variable(), because the code
that was added there for the 'gp_statistics_pullup_from_child_partition'
GUC assumed that all range table entries with 'inh==true' must be of
kind …
=> Re-enable upstream optimization to pull up simple UNION ALL subqueries.

.travis.yml
Historically we've lowered the cache size to 500M (from the default of
5GB) because we thought that saves us time fetching and storing the
cache. But with GCC 8 on Linux the total object file size is a little
south of 3G. That means we lose more time in compilation cache misses
than the transfer time on the cache itself. This change alone speeds up
the GCC 8 on Ubuntu bionic job by more than 50%: from 32 minutes to 14
minutes.
=> [Travis CI] Bump cache size to 4G

src/backend/gporca/libgpopt/include/gpopt/xforms/CSubqueryHandler.h, src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
When we have an outer ref in a subquery, like this
```
select * from foo where foo.a = (select foo.b from bar)
```
then we can't simply use the outer reference for the condition when
we unnest the subquery into an apply. This is because if the subquery
returns no rows, then we must be using a NULL instead of the outer
reference.
We have code to handle this for quantified subqueries, but not for
scalar subqueries.
When we translate the generated DXL to a plan, we assert when we find
an outer reference in the project list of a subquery. In rare cases,
we might also crash, when the subquery contained a project with multiple
values below the outer reference (see added test in gporca.sql).
The "fix" (more a workaround) is to force a fallback when we detect
this situation during unnesting of a …
=> Fall back for selects of outer refs in scalar subquery in ORCA

src/test/regress/expected/subselect.out, src/test/regress/expected/subselect_optimizer.out, src/test/regress/sql/subselect.sql
Previously after the 9.2 merge, we had a hack that short-circuits the
execution of the join when ORCA is on. This hack stops working with the
Postgres 12 merge because the FIXME subquery gets executed on the QEs as
well rather than just on the QD. This patch simply turns ORCA off for
the query.
Co-authored-by: Alexandra Wang <lewang@pivotal.io>
=> Use planner for one test in "subselect"

src/backend/gporca/libgpopt/include/gpopt/xforms/CSubqueryHandler.h, src/backend/gporca/libgpopt/src/xforms/CSubqueryHandler.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
This is a backport of the changes in #10799 to 6X_STABLE.
When we have an outer ref in a subquery, like this
select * from foo where foo.a is null or foo.a = (select foo.b from bar)
then we can't simply use the outer reference for the condition when
we unnest the subquery into an apply. This is because if the subquery
returns no rows, then we must be using a NULL instead of the outer
reference.
We have code to handle this for quantified subqueries, but not for
scalar subqueries.
When we translate the generated DXL to a plan, we assert when we find
an outer reference in the project list of a subquery. In rare cases,
we might also crash, when the subquery contained a project with multiple
values below the outer reference (see added test in gporca.sql).
The "fix" (more a workaround) is to …
=> 6X: Fall back for selects of outer refs in scalar subquery in ORCA

src/backend/catalog/heap.c, src/backend/commands/tablecmds.c, src/test/regress/expected/temp.out, src/test/regress/expected/truncate.out
GPDB does not support FK, but keep FK grammar in DDL, since it
reduce DB migration manual workload from others.
Hence, we do not need FK to check for truncate command, rid of it.
=> Skip FK check when do relation truncate

src/backend/utils/misc/guc_gp.c, src/backend/utils/resgroup/resgroup.c, src/include/utils/resgroup.h, src/include/utils/sync_guc_name.h
We had several issues on 5x and 6x that shows the resource group wait queue is
somehow corrupted, this commit add some checks and PANIC at the earliest to
help debugging.
=> Add consistency check on resource group wait queue

src/backend/catalog/heap.c, src/backend/commands/tablecmds.c, src/test/regress/expected/temp.out, src/test/regress/expected/truncate.out
GPDB does not support FK, but keep FK grammar in DDL, since it
reduce DB migration manual workload from others.
Hence, we do not need FK check for truncate command, rid of it.
=> [5X backport]Skip FK check when do relation truncate

src/backend/cdb/cdbpersistentfilesysobj.c
This bug was found in a production environment where vacuum on gp_persistent_relation was concurrently running with a backend performing end-of-xact filesystem operations.  And the GUC debug_persistent_print was enabled.
The *_ReadTuple() function was called on a persistent TID after the corresponding tuple was deleted with frozen transaction ID.  The concurrent vacuum recycled the tuple and it led to a SIGSEGV when the backend tried to access values from the tuple.
Fix it by avoiding the debug log message in case when the persistent tuple is freed (transitioning to FREE state).  All other state transitions are logged.
In absence of concurrent vacuum, things worked just fine because the *_ReadTuple() interface reads tuples from persistent tables directly using TID.
This change was tested …
=> [5X-only] Do not read a persistent tuple after it is freed

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/test/regress/expected/bfv_index.out, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/sql/bfv_index.sql
Clean cherry-pick
Passed ICW: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-6X-backport-orca-verify-indisvalid
---
Function `RelationGetIndexList()` does not filter out invalid indexes.
That responsiblity is left to the caller (e.g. `get_relation_info()`).
Issue is that Orca was not checking index validity.
This commit also introduces an optimization to Orca that is already used
in Planner whereby we first check relhasindex before checking pg_index.
(cherry picked from commit b011c3518bb068a4c886d2898b50664f640eec5e)
=> [6X Backport] Align Orca relhasindex behavior with Planner (#10788)

src/backend/gpopt/gpdbwrappers.cpp, src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp, src/test/regress/expected/bfv_index.out, src/test/regress/expected/bfv_index_optimizer.out, src/test/regress/sql/bfv_index.sql
Trivial conflict in `IsIndexSupported()` due to eae823f4d7d0
Passed ICW: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-dkimura
---
Function `RelationGetIndexList()` does not filter out invalid indexes.
That responsiblity is left to the caller (e.g. `get_relation_info()`).
Issue is that Orca was not checking index validity.
This commit also introduces an optimization to Orca that is already used
in Planner whereby we first check relhasindex before checking pg_index.
(cherry picked from commit b011c3518bb068a4c886d2898b50664f640eec5e)
=> [5X Backport] Align Orca relhasindex behavior with Planner (#10788)

src/backend/utils/misc/guc.c, src/test/regress/expected/dispatch_encoding.out, src/test/regress/greenplum_schedule, src/test/regress/sql/dispatch_encoding.sql
When client_encoding is dispatch to QE, error messages generated in QEs were
converted to client_encoding, but QD assumed that they were in server encoding,
it will leads to corruption.
This is fixed in 6X in a6c9b4, but this skips the gpcopy changes since 5X
doesn't support syntax 'COPY...ENCODING'.
Fix issue: https://github.com/greenplum-db/gpdb/issues/10815
=> [5X only] Don't dispatch client_encoding to QE

contrib/pg_upgrade/greenplum/pg_upgrade_greenplum.h, contrib/pg_upgrade/util.c
The `static step_timer timer` is only used in contrib/pg_upgrade/util.c.
So move it here.
=> [6X Only]Eliminate warnings during compile in pg_upgrade.

src/backend/cdb/cdbgroupingpaths.c, src/test/regress/expected/bfv_aggregate.out, src/test/regress/expected/bfv_aggregate_optimizer.out, src/test/regress/sql/bfv_aggregate.sql
Bumped into this while merging 'master' to the PostgreSQL v12 merge
branch. An upstream test query similar to that added to the
'bfv_aggregate' test in this commit failed on the merge branch, in the
'partition_aggregate' test.
=> Fix assertion failure with GROUP BY on FULL JOIN.

gpdb-doc/dita/admin_guide/query/topics/query-profiling.xml
add a best practice to query profiling page that addresses joins of multiple tables, long planning time, and join_collapse_limit and from_collapse_limit gucs.
=> docs - when to set *_collapse_limit gucs to a smaller value

src/test/isolation2/helpers/server_helpers.sql
The removed comment in the patch explains the details.  Now we've been able to
handle the  dtx recovery case in pg_ctl also we could safely revert the
previous change.
=> Fix a GPDB_12_MERGE_FIXME in test isolation2 udf pg_ctl()

NOTICE, python-dependencies.txt
It was vendored under src/test/tinc/ext/unittest2, but not anymore.
Fixes #4028
=> Remove unittest2 dependency

src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Planner was choosing a different join order and ORCA was choosing
different groupby strategies.
Spreading out the values of the smaller table, so that for a hash
join, the two tables will be of different size. That should make
choosing a hash join order more clear. Disabling sort groupby.
=> Try to fix flaky explain plans in gporca test

src/bin/pg_upgrade/greenplum/check_gp.c
Earlier the output filename for the test check_orphaned_toastrels
was partitioned_tables.txt, so updated that to represent toast tables
=> Update the filename for the test check_orphaned_toastrels

gpMgmt/bin/ifaddrs/main.c, gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature, gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
Customers can configure private address range on their loopback and use
it for communication on the greenplum cluster. If those addresses are
excluded from the replciation entries utilities like gpinitstandby or
gpaddmirrors can fail.
This commit updates the ifaddrs utility to include such addresses.
=> Include private ip address range on loopback interfaces

src/tools/msvc/Solution.pm
After pg12 merge, genbki.pl need to be run to gererate catalog
header files like pg_tablespace_d.h to build client tools.
Remove previously added switch that controls genbki.pl.
=> fix windows build

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/backend/gporca/data/dxl/minidump/ConstTblGetUnderSubqUnderProjectWithOuterRef.mdp, src/backend/gporca/data/dxl/minidump/ConstTblGetUnderSubqWithOuterRef.mdp, src/backend/gporca/data/dxl/minidump/DQA-KeepOuterReference.mdp, src/backend/gporca/data/dxl/minidump/ExprOnScSubqueryWithOuterRef.mdp, src/backend/gporca/data/dxl/minidump/PartTbl-DPE-Correlated-NLOuter.mdp, src/backend/gporca/data/dxl/minidump/ScSubqueryWithOuterRef.mdp, src/backend/gporca/libgpopt/src/operators/CNormalizer.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
In a previous commit (df5f06d), we added code to fall back gracefully
when a subquery select list contains a single outer ref that is not part
of an expression, such as in
`select * from foo where a is null or a = (select foo.b from bar)`
This commit adds a fix that allows us to handle such queries in ORCA
by adding a project in the translator that will echo the outer ref
from within the subquery, and using that projected value in the
select list of the subquery. This ensures that we use a NULL value
for the outer ref when the subquery returns no rows.
Also note that this is still skipped for grouping cols in the target
list. This was done to avoid regression for certain queries, such as:
```
select *
from A
where not exists (select sum(C.i)
from C
where C.i = A.i
group by a.i);
```
ORCA …
=> [6x] Project outrrefs in the targetlist of subqueries in ORCA

src/backend/utils/misc/guc_gp.c, src/backend/utils/resgroup/resgroup.c, src/include/utils/resgroup.h, src/include/utils/sync_guc_name.h
We had several issues on 5x and 6x that shows the resource group wait queue is
somehow corrupted, this commit add some checks and PANIC at the earliest to
help debugging.
=> [6X backport] Add consistency check on resource group wait queue

src/backend/utils/misc/guc_gp.c, src/backend/utils/resgroup/resgroup.c, src/include/utils/resgroup.h
We had several issues on 5x and 6x that shows the resource group wait queue is
somehow corrupted, this commit add some checks and PANIC at the earliest to
help debugging.
=> [5X backport] Add consistency check on resource group wait queue

src/backend/gporca/data/dxl/minidump/DQA-SplitScalarWithAggAndGuc.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h, src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp, src/backend/gporca/libgpopt/src/xforms/CXformSplitDQA.cpp, src/test/regress/expected/direct_dispatch.out, src/test/regress/expected/direct_dispatch_optimizer.out, src/test/regress/sql/direct_dispatch.sql
This allows Orca to perform a GROUP BY over gp_segment_id without
requiring a redistribute motion.
```
EXPLAIN (COSTS OFF) SELECT count(*), gp_segment_id FROM motiondata
ROUP BY gp_segment_id;
QUERY PLAN
------------------------------------------
->  GroupAggregate
Group Key: gp_segment_id
->  Sort
Sort Key: gp_segment_id
->  Seq Scan on motiondata
Optimizer: Pivotal Optimizer (GPORCA)
(7 rows)
```
=> Allow distribution spec match when hash spec uses gp_segment_id

src/include/pg_config_manual.h
It was modified to 16M (that's upstream default setting) during PG12 merge when
resolving code merge conflict without explanation. It looks like the change was
not intentional. Why the value was 64M on Greenplum is not clear just from
commit history (e.g. merge repo commit 8b1be90e989268a), but I assume we had
done some perf testing with the value, also the below related upstream patch
explains this a bit, especially the second reason, assuming it means calling
issue_xlog_fsync() less, is quite reasonable. Note with the below upstream
patch there isn't configure option so directly modifying the definition, else I
have to modify all code/scripts which calls initdb - that is bug prone and hard
to maintain.
commit fc49e24fa69a15efacd5b8958115ed9c43c48f9a
Author: Andres Freund …
=> Revert the default wal segment file size to 64M on Greenplum

concourse/pipelines/pr_pipeline.yml
In the same vein as commit 868fd2d78e34b46a, this adds a very quick
clang-format job that checks for conformance, similar to the Travis CI
job did in commit 54273fdd729a1958 (greenplum-db/gpdb#10357).
=> Add format checking in PR pipeline

gpMgmt/bin/ifaddrs/main.c, gpMgmt/test/behave/mgmt_utils/gpaddmirrors.feature, gpMgmt/test/behave/mgmt_utils/gpinitstandby.feature
With the ifaddrs utility, we excluded ip addresses on the loopback
interface which caused regression causing replication entries to be not
populated for such interfaces causing gpaddmirrors and gpinitstandby to
fail. Routable IP addresses can be assigned to the loopback interface,
and this case was not considered earlier.
This commit fixes the issues by allowing all loopback addresses
except 127.0.0.1 and ::1 address
6X PR: https://github.com/greenplum-db/gpdb/pull/10861
=> Exclude only 127.0.0.x and ::1 address.

gpMgmt/bin/gppylib/operations/filespace.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_filespace.py
If any segment host was down and the temporary or transaction filespace were
moved to a different filespace (i.e other than default), it used to do a
SSH to update the filespace content in a file on the down host and
will fail as the host is down. This will cause utilities by gprecoverseg
to fail even though if the segments on the down host are excluded from
the gprecoverseg input file.
=> Skip Segments which are down for updating filespaces files on the host

src/backend/parser/parse_clause.c, src/test/regress/expected/olap_group.out, src/test/regress/sql/olap_group.sql
When transforming RowExprs inside of a GroupingClause such as ROLLUP
or GROUPING SETS, we intend to only consider a RowExpr as a separate
grouping set if it is immediately inside of the GroupingClause. A
RowExpr that is nested inside of another RowExpr will be flattened.
For example, the following queries should all be equivalent:
SELECT a, b, c, d, SUM(v) FROM gstest GROUP BY ROLLUP(a, (b, (c, d)));
SELECT a, b, c, d, SUM(v) FROM gstest GROUP BY ROLLUP(a, (b, c, d));
SELECT a, b, c, d, SUM(v) FROM gstest GROUP BY GROUPING SETS ((a, b, c, d), (a), ());
SELECT a, b, c, d, SUM(v) FROM gstest GROUP BY GROUPING SETS ((a, (b, c), d), (a), ());
SELECT a, b, c, d, SUM(v) FROM gstest GROUP BY (a, b, c, d)
UNION ALL
SELECT a, NULL, NULL, NULL, SUM(v) FROM gstest GROUP BY (a)
UNION ALL
SELECT NULL, …
=> Fix parsing bug for ROLLUP/GROUPING SETS with nested RowExpr

contrib/pg_upgrade/greenplum/check_gp.c, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_dropped_columns.source, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_aligned_varlen_dropped_columns.source, contrib/pg_upgrade/test/integration/output/partitioned_heap_table_with_differently_sized_dropped_columns.source
The suggestion in the existing error text is incorrect, as CREATE TABLE AS on
a partition table will end up creating a non-partitioned table.  This commit
updates the message to be more precise in addressing the error.
Co-authored-by: Jamie McAtamney <jmcatamney@vmware.com>
=> pg_upgrade: fix check_heterogeneous_partition message

src/test/regress/expected/brin_aocs.out, src/test/regress/sql/brin_aocs.sql
In the brin_ao regress test we create a table brintest_ao with a brin
index, then performs brin indexscan on different columns to verify the
correctness.  After that we also perform some vacuum tests, first vacuum
that table, then copy all the data to itself, and finally vacuum again.
There is also a similar brin_aocs regress test, the only difference is
that its table is brintest_aocs.
However there is a typo in brin_aocs, it vacuums brintest_ao instead of
brintest_aocs, as well as the data doubling.  So in brin_ao we can
randomly see below message:
+WARNING:  unexpected number of results 106 for (int4rangecol,>,int4range,empty,53)
The actual number of results is double size of the expected one, that's
simply because that the data does is doubled concurrently.
Corrected the typo, both …
=> Fix flaky brin_ao regress test

src/backend/gporca/libgpopt/include/gpopt/base/CDistributionSpecHashed.h, src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp, src/test/regress/expected/direct_dispatch.out, src/test/regress/expected/direct_dispatch_optimizer.out, src/test/regress/sql/direct_dispatch.sql
Clean cherry-pick except answer files: https://github.com/greenplum-db/gpdb/commit/399d7d0157c7ce86a590d415243d234bcad99c3d (will before commit)
ICW passed: [CI Link](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-6X-avoid-redistribute-on-group-by-gp-segment-id/resources/gpdb_src)
---
This allows Orca to perform a GROUP BY over gp_segment_id without
requiring a redistribute motion.
```
EXPLAIN (COSTS OFF) SELECT count(*), gp_segment_id FROM motiondata
ROUP BY gp_segment_id;
QUERY PLAN
------------------------------------------
->  GroupAggregate
Group Key: gp_segment_id
->  Sort
Sort Key: gp_segment_id
->  Seq Scan on motiondata
Optimizer: Pivotal Optimizer (GPORCA)
(7 rows)
```
(cherry picked from commit 9ea2a96)
=> [6X Backport] Allow distribution spec match when hash spec uses gp_segment_id

gpMgmt/bin/analyzedb
After testing `analyzedb` on a huge database with 170k tables we have found a bottleneck while printing candidate list to `analyze`. It took about 45 minutes to print all tables. The bottleneck was in `O(n^2)` complexity when we validated candidates in a loop with a `list()` instead of `set()`. The same `O(n^2)` validation is made while running `analyze` commands on executor pool.
This commit change candidate type from list() to set() to reduce complexity from `O(n^2)` to `O(n)`.
The problem can be explained with a benchmark below. For 50k items with a `list()` validation we spend 29.4 sec while with a `set()` one - only 0.2 sec.
```python
import time
if __name__ == "__main__":
size = 50000
source_list = [("schema" + str(i), "table" + str(i)) for i in range(0, size)]
target_list = [] …
```
=> Replace list() with set() validation in analyzedb

src/include/executor/tuptable.h
Unlike PostgreSQL 9/10/11, Greenplum has no API ExecStoreTuple,
thus some external libraries such as redis_fdw will not compile
against Greenplum 6. Greenplum 7 has no such issue, as PostgreSQL 12
changed ExecStoreTuple to ExecStoreHeapTuple like Greenplum.
Greenplum 6 only.
=> Add function ExecStoreTuple for compatibility with 3rd party libraries

src/backend/utils/resgroup/resgroup_helper.c, src/test/isolation2/expected/resgroup/resgroup_functions.out, src/test/isolation2/isolation2_resgroup_schedule, src/test/isolation2/sql/resgroup/resgroup_functions.sql
This is the 6X version of
https://github.com/greenplum-db/gpdb/pull/10856.
The query `INSERT INTO .. SELECT .. FROM pg_resgroup_get_status()` will
execute the UDF on a QE started on the master node, it's not right to
check `if (Gp_role == GP_ROLE_DISPATCH)`.
It's not a complete fix since 6X could not have a catalog change, a more
complex query might start the QE on a segment which has no such stats.
Better than nothing.
Fixes #10794
=> Partially fix CTAS pg_resgroup_get_status()

src/backend/catalog/heap.c, src/backend/commands/tablecmds.c, src/test/regress/expected/temp.out, src/test/regress/expected/truncate.out
GPDB does not support FK, but keep FK grammar in DDL, since it
reduce DB migration manual workload from others.
Hence, we do not need FK to check for truncate command, rid of it.
=> [6X backport] Skip FK check when do relation truncate

concourse/scripts/common.bash, src/backend/cdb/motion/README.ic-proxy.md, src/backend/cdb/motion/ic_proxy_addr.c, src/backend/cdb/motion/ic_proxy_addr.h, src/backend/cdb/motion/ic_proxy_main.c, src/backend/cdb/motion/ic_proxy_peer.c
( The previous PR #10802 was merged outside the 6X feature merge window, so it was reverted with #10821, now we reopen the PR )
The GUC gp_interconnect_proxy_addresses is used to set the listener
addresses and ports of all the proxy bgworkers, only IP addresses were
supported previously, which is inconvenient to use.
Now we add the support for hostnames too, the IP addresses are also
supported.
Note that if a hostname is bound to a different IP at runtime, we must
reload the setting with the "gpstop -u" command.
(cherry picked from commit 2a1794bc47e58ea033e68ee1d8ef3ab2f999706f)
=> 6X again: ic-proxy: support hostname as proxy addresses

src/backend/cdb/cdbdtxrecovery.c, src/backend/cdb/cdbtm.c, src/backend/postmaster/postmaster.c, src/include/cdb/cdbtm.h, src/include/storage/pmsignal.h, src/test/isolation2/expected/crash_recovery_dtm.out, src/test/isolation2/sql/crash_recovery_dtm.sql
Previously QD panicks when Abort Prepared retry fails but this is not friendly
due to master reset (all sessions are gone). The panic is not that needed since
even Abort Prepared fails the cluster is consistent, but we still need to try
to finish the Abort since the orphaned prepared transaction still holds
resources.  Now that we do periodical handling of orphaned prepared transaction
in the dtx recovery process, QD could simply ignore and then proceed if Abort
Prepared retry fails.
Reviewed-by: Gang Xiong <gangx@vmware.com>
(cherry picked from commit ea3514afdd1b04fbfd544a7851b88afadbd9843c)
=> [6X Backport] Avoid panic after Abort Prepared retry fails. (#10795)

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query42.ans
* fix 6x gpload fail when capital letters in column names without data type
quote column names before comparing
* add test case
=> Fix 6x gpload fail when column types are not specified

src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp, src/include/gpopt/translate/CTranslatorDXLToPlStmt.h
gpfdist uses the global xid & timestamp to distinguish whether each
connection belongs to the same external scan or not.
ORCA generates a unique scan number for each ExternalScan within the
same plan, but not accross plans. So, within a transaction, we may issue
multiple external scans that do not get differentiated properly,
producing different results.
This commit patches that by using a different scan number accross plans,
just like what planner does. Ideally gpfdist should also take into
account the command-id of the query to prevent this problem for other
cases such as prepared statements.
=> Increment ExternalScan::scancounter across queries in ORCA

src/test/regress/expected/partition.out, src/test/regress/expected/partition_optimizer.out, src/test/regress/sql/partition.sql
Test partition1 creates table hhh_r1 also and that test runs with test
partition in parallel with schedule file greenplum_schedule, and this
could cause below test failure. Fixing this by renaming the table name.
@@ -523,9 +523,7 @@
partition aa start (date '2007-01-01') end (date '2008-01-01')
every (interval '0 days')
);
-ERROR:  EVERY parameter too small
-LINE 5:       every (interval '0 days')
-                     ^
+ERROR:  relation "hhh_r1" already exists
create table foo_p (i int) distributed by(i)
partition by range(i)
(start (1) end (20) every(0));
=> Fix flaky test regress/partition

src/backend/cdb/dispatcher/cdbdisp_query.c
The buildGpQueryString() function should use palloc() instead of palloc0() to allocate the buffer for holding the serialized query string, thus avoiding the unnecessary cost of setting all bytes in buffer to zero.
The related issue is here: https://github.com/greenplum-db/gpdb/issues/10874.
=> The buildGpQueryString() function should use palloc() instead of palloc0()

src/backend/cdb/cdbsubselect.c, src/backend/optimizer/path/joinpath.c, src/test/regress/expected/notin.out, src/test/regress/expected/notin_optimizer.out, src/test/regress/expected/qp_correlated_query.out, src/test/regress/expected/qp_subquery.out, src/test/regress/expected/qp_subquery_optimizer.out, src/test/regress/sql/notin.sql
The result of NULL not in an unempty set is false. The result of
NULL not in an empty set is true. But if an unempty set has
partitioned locus. This set will be divided into several subsets.
Some subsets may be empty. Because NULL not in empty set equals
true. There will be some tuples that shouldn't exist in the result
set.
The patch disable the partitioned locus of inner table by removing
the join clause from the redistribution_clauses.
Co-authored-by: Hubert Zhang <hubertzhang@apache.org>
Co-authored-by: Richard Guo <riguo@pivotal.io>
=> The inner relation of LASJ_NOTIN should not have partition locaus

concourse/tasks/rename_rc_artifacts.yml
Client package test on windows and the related binary was removed
by commit c2574cc4 and 8bb057ac, but there's still one usage in
rename_rc_artifacts task. Remove it also to fix release candidate
job.
=> Fix release candidate on master pipeline

src/backend/cdb/dispatcher/cdbdisp_query.c
The buildGpQueryString() function should use palloc() instead of palloc0()
to allocate the buffer for holding the serialized query string, thus
avoiding the unnecessary cost of setting all bytes in buffer to zero.
Reviewed-by: Heikki Linnakangas <hlinnaka@iki.fi>
Reviewed-by: Ashwin Agrawal <aashwin@vmware.com>
(cherry picked from commit 073be714a1be0f3ecba8d98dd4e0433499e03bcf)
=> Use palloc() instead of palloc0() in buildGpQueryString()

gpAux/gpdemo/demo_cluster.sh
Enable demo_cluster.sh to handle symlinks which is useful when GPDB is installed using RPMs and a demo cluster is desired.
_Note:_ If this is merged, backports to 6X and 5X are needed.
[Test pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/kalen_demo_cluster_symlinks_Master)
=> enable demo_cluster.sh to handle symlinks

src/backend/optimizer/plan/plangroupext.c, src/test/regress/expected/aggregate_with_groupingsets.out, src/test/regress/sql/aggregate_with_groupingsets.sql
When constructing plans for a list of rollups, the rollup_subplan may be
retrieved from root->simple_rel_array[i]->subplan, which is not always type of
SubqueryScan. So later in function rebuild_append_simple_rel_and_rte(), we need
to verify if the subplan is a SubqueryScan node before assigning a scanrelid to
it.
Fixes issue #10813 and issue #10841
=> Fix crash when planning for sub-queries that have grouping sets

src/backend/commands/resgroupcmds.c, src/backend/utils/resgroup/resgroup.c
In function DropResourceGroup(), group->lockedForDrop is set
to true by calling ResGroupCheckForDrop, however, it can only
be set to false inside dropResgroupCallback. This callback is
registered at the ending of function DropResourceGroup. If an
error occured between them, group->lockedForDrop would be true
forever.
Fix it by putting the register process ahead of the lock call.
To prevent Assert(group->nRunning* > 0) if ResGroupCheckForDrop
throws an error, return directly if group->lockedForDrop did
not change.
See:
```
gpconfig -c gp_resource_manager -v group
gpstop -r -a
psql
CPU_RATE_LIMIT=20,
MEMORY_LIMIT=20,
CONCURRENCY=50,
MEMORY_SHARED_QUOTA=80,
MEMORY_SPILL_RATIO=20,
MEMORY_AUDITOR=vmtracker
);
psql -U user_test
> \d -- hang
```
=> Fix resgroup unusable if its dropping failed

gpAux/gpdemo/demo_cluster.sh
master fix https://github.com/greenplum-db/gpdb/pull/10330  and 5X backport https://github.com/greenplum-db/gpdb/pull/11016
Use GPHOME directly. There is no need for GPSEARCH.
This enables demo_cluster.sh to handle symlinks which is useful when GPDB is installed using RPMs and a demo cluster is desired.
(cherry picked from commit 6932195ab2faa7fa5835e2c231314dabd3daf7bf)
[Test pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/demo_cluster_symlinks_5X)
=> [5X backport] demo_cluster.sh: remove GPSEARCH

gpMgmt/bin/gppylib/operations/segment_reconfigurer.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_segment_reconfigurer.py
The parameters were incorrectly passed while gprecoverseg was invoked
causing gprecoverseg to fail.
Co-authored-by: Aleksey Kashin <kashinav@yandex-team.ru>
=> fix gprecoverseg -r when password authentification enabled for gpadmin

src/backend/replication/syncrep.c, src/backend/storage/ipc/procsignal.c, src/backend/utils/resgroup/resgroup.c, src/include/storage/procsignal.h
Commit 4f85fde refactored the infrastructure for interrupt processing,
simplified signal handlers and it had no more need to perform
StartTransactionCommand()...CommitTransactionCommand() call inside any
signal handler.
So the AmIInSIGUSR1Handler() should not happen at all, remove it.
=> Remove the InSIGUSR1Handler mechanism

gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/gpstart.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Currently, if a host is unreachable when gpstart is run, it will not report this and will instead fail with an error that is both inaccurate and unhelpful to the user, such as claiming that checksums are invalid for segments on a given host when it simply can't reach that host to verify the checksums.
This commit adds a check to verify that all hosts are reachable before beginning the startup process and, if one or more hosts are not reachable, marks segments on those hosts down (in gparray, not in the cluster) so gpstart won't try to run any checks against unreachable hosts and so that the cluster can still be started in this state so long as there are otherwise enough valid segments to start it.
=> gpstart: improve handling of down segment hosts

src/backend/cdb/dispatcher/cdbdispatchresult.c, src/test/regress/expected/gp_constraints.out, src/test/regress/sql/gp_constraints.sql
This is essentially refresher of PR #8220 based on latest code.
Postgres 991f3e5ab3f8196d18d5b313c81a5f744f3baaea introduce new error
message fields, but cdbdisp_get_PQerror() did not extract these newly
added message field. These fields client cannot see from libpq.
This fixes https://github.com/greenplum-db/gpdb/issues/7934.
Also enable gp_constraints test, it hasn't been run for unknown
reason.
=> Extract new error message fields in cdbdisp_get_PQerror()

concourse/scripts/builds/GpBuild.py, concourse/scripts/common.bash, configure, configure.in, gpAux/Makefile, src/backend/utils/mmgr/aset.c
With this can do `configure && make install && make installcheck`
---
Enable building with python by default in configure
Many tests in GPDB depend on plpython, hence enabling it by default is
helpful, instead of required to specify everytime. Given python is
needed on developer system for GPDB Management Scripts so its not
adding any new dependency.
---
Disable gpcloud by default in configure
gpcloud has dependency on libxml. gpcloud enabled by default and
libxml disabled by default in configure, creates a weird pattern where
at least one option needs to be specified for configure to pass, just
./configure never passes for Greenplum.
ICG and isolation2 tests just pass without it so seems a better route
to disable gpcloud. Alternatively, can enable libxml by default but
seems conflicts …
=> Configure: disable gpcloud, enable python by default

src/backend/replication/slot.c
When SaveSlotToPath() is called with elevel=LOG, the early exits didn't
release the slot's io_in_progress_lock.
This could result in a walsender being stuck on the lock forever.  A
possible way to get into this situation is if the offending code paths
are triggered in a low disk space situation.
Author: Pavan Deolasee <pavan.deolasee@2ndquadrant.com>
Reported-by: Craig Ringer <craig@2ndquadrant.com>
Discussion: https://www.postgresql.org/message-id/flat/56a138c5-de61-f553-7e8f-6789296de785%402ndquadrant.com
=> 6X - Drop slot's LWLock before returning from SaveSlotToPath()

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py
It didn't log the error message before if pg_rewind fails, fix that to make
DBA/field/developer's life eaisier.
Before this:
```
20201022:15:19:10:011118 gprecoverseg:earth:adam-[INFO]:-Running pg_rewind on required mirrors
20201022:15:19:12:011118 gprecoverseg:earth:adam-[WARNING]:-Incremental recovery failed for dbid 2. You must use gprecoverseg -F to recover the segment.
20201022:15:19:12:011118 gprecoverseg:earth:adam-[INFO]:-Starting mirrors
20201022:15:19:12:011118 gprecoverseg:earth:adam-[INFO]:-era is 0406b847bf226356_201022151031
```
After this:
```
20201022:15:33:31:019577 gprecoverseg:earth:adam-[INFO]:-Running pg_rewind on required mirrors
20201022:15:33:31:019577 gprecoverseg:earth:adam-[WARNING]:-pg_rewind: fatal: could not find common ancestor of the source and target …
```
=> gprecoverseg: log the error if pg_rewind fails

gpMgmt/test/behave/mgmt_utils/steps/gpstart.py
The tests in commit be5d11e2286 contained a typo that caused the changes
in the Scenario "gpstart starts even if the standby host is unreachable"
to not properly cleanup after itself.  Though the test feature still
passes, this leaves a bug to be found later when more tests are added.
=> gpstart: testing of improve handling of down segment hosts

src/backend/access/nbtree/nbtinsert.c
If the system crashes when splitting a btree page and the WAL of downlink to
the parent is not flushed, crash recovery will complete this step in
'btree_xlog_cleanup' and it may led to split the parent, which will write a new
WAL record in '_bt_split'. We skip populating the PT information during
recovery in function 'RelationNeedToFetchGpRelationNodeForXLog' and it will
cause PANIC in this case. This is fixed in 6X and later version by commit
'40dae7ec'. This commit only set invalid PT information in the new WAL record.
=> [5X only] Skip setting PT information in WAL during recovery

src/backend/cdb/dispatcher/cdbgang.c
In buildGangDefinition, newGangDefinition->db_descriptors are
initialized one by one, but newGangDefinition->size was already
set to its final value. If an error was caught, its size should
be reset to the right number.
=> Fix: might recycle wrong gang size

concourse/scripts/ic_gpdb.bash, contrib/postgres_fdw/Makefile
postgres_fdw test is disabled by default, and it's
enabled in gpdb pipelines.
=> Enable postgres_fdw test in icw test of gpdb pipeline

src/backend/cdb/cdbplan.c, src/backend/nodes/nodeFuncs.c
It was handled in expression_tree_mutator(), which is why everything
worked, but that's not the right place. expression_tree_mutator() is
supposed to handle nodes that can appear in expressions, and
plan_tree_mutator() is supposed to handle Plan nodes.
=> Handle PartitionSelector in plan_tree_mutator().

gpMgmt/bin/gppylib/test/unit/test_unit_buildmirrorsegments.py
Otherwise, it will raise an exception "command not run yet".
=> Mock cmd.get_stdout() to fix test regression

src/backend/gporca/libnaucrates/src/base/IDatum.cpp, src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp, src/backend/gporca/server/include/unittest/dxl/base/CDatumTest.h, src/backend/gporca/server/include/unittest/dxl/statistics/CBucketTest.h, src/backend/gporca/server/include/unittest/dxl/statistics/CCardinalityTestUtils.h, src/backend/gporca/server/include/unittest/dxl/statistics/CHistogramTest.h, src/backend/gporca/server/include/unittest/gpopt/CTestUtils.h, src/backend/gporca/server/src/unittest/CTestUtils.cpp, src/backend/gporca/server/src/unittest/dxl/base/CDatumTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CBucketTest.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CCardinalityTestUtils.cpp, src/backend/gporca/server/src/unittest/dxl/statistics/CHistogramTest.cpp
When merging statistics buckets for UNION and UNION ALL queries
involving a column that maps to Double (eg: floats, numeric, time
related types), we could end up in an infinite loop. This occurred if
the bucket boundaries that we compared were within a very small value,
defined in Orca as Epsilon. While we considered that two values were
equal if they were within Epsilon, we didn't when computing whether
datum1 < datum2. Therefore we'd get into a situation where a datum
could be both equal to and less than another datum, which the logic
wasn't able to handle.
The fix is to make sure we have a hard boundary of when we check if a
datum is less than another datum by including the epsilon logic in all
datum comparisons. Now, 2 datums are equal if they are within epsilon,
but datum1 is less …
=> Fix stats bucket logic for Double values in UNION queries in Orca

gpMgmt/bin/Makefile
If the $(UBUNTU_PLATFORM) is an empty string, the test command will fail,
double quotes it to fix.
```
--- mock for platform
/bin/sh: line 0: [: =: unary operator expected
```
=> Fix a shell issue of empty string

src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h, src/include/utils/unsync_guc_name.h, src/test/regress/expected/olap_window.out, src/test/regress/expected/olap_window_optimizer.out, src/test/regress/sql/olap_window.sql
Previously, GPDB did not support the SQL "EXCLUDE [CURRENT ROW | GROU |
TIES]" syntax in window functions. We got support for that from upstream
with the PostgreSQL v12 merge. That left the GUC obsolete and unused.
Update the 'olap_window' test accordingly. NOTE: 'olap_window' test isn't
currently run as part of the regression suite! I don't know why it's been
neglected like that, but that's not this patch's fault. The upstream
'window' test has queries with the EXCLUDE clause, so it's covered.
=> EXCLUDE in window functions works now, remove 'gp_ignore_window_exclude'.

contrib/postgres_fdw/postgres_fdw.c
postgres_fdw: disable UPDATE/DELETE on foreign Greenplum servers
Greenplum only supports INSERT, because UPDATE/DELETE requires the
hidden column gp_segment_id and the other "ModifyTable mixes distributed
and entry-only tables" issue.
Co-authored-by: Xiaoran Wang <xiwang@pivotal.io>
=> postgres_fdw: cherry-pick c577eb5e from gpdb7

concourse/pipelines/pr_pipeline.yml
We started hitting this on Thursday, and there's been ongoing report
from the community about this as well. While upstream is figuring out a
long term solution [1], we've been advised [2] to pin to the previous
release (v0.21.0) to avoid being blocked for hours at once.
[1]: https://github.com/telia-oss/github-pr-resource/pull/238
[2]: https://github.com/telia-oss/github-pr-resource/pull/238#issuecomment-714830491
=> Pin PR resource to v0.21 to avoid Github abuse rate limit

gpdb-doc/dita/analytics/analytics.ditamap
remove duplicate entry in the left navigation pane.
should be backported to 6X_STABLE
=> docs - remove duplicate left nav entry

config/programs.m4, config/python.m4, configure
Some platforms do not have unversioned "python" available but do have
versioned "python2". Configure should look for either "python" or
"python2" when run with the option "--with-python".
These changes were manually copied from the Postgres build system but
omitted searching for "python3" since Greenplum does not have support
for Python 3 yet.
=> Update python configure macros

src/backend/utils/misc/guc_gp.c, src/include/utils/guc.h
Compiling with gcc 10 on Debian testing fails with the following error:
```
/usr/bin/ld: utils/misc/guc_gp.o:(.bss+0x308): multiple definition of
`data_directory'; utils/misc/guc.o:(.bss+0x70): first defined here
```
=> Remove duplicate definition of data_directory

concourse/pipelines/pr_pipeline.yml
Backport of https://github.com/greenplum-db/gpdb/pull/11045
We started hitting this on Thursday, and there's been ongoing report from the community about this as well. While upstream is figuring out a long term solution [1], we've been advised [2] to pin to the previous release (v0.21.0) to avoid being blocked for hours at once.
[1]: https://github.com/telia-oss/github-pr-resource/pull/238
[2]: https://github.com/telia-oss/github-pr-resource/pull/238#issuecomment-714830491
(cherry picked from commit f4bf9be689bbcb7b703af527f1520fb5b2d26803)
=> [6X backport]: Pin PR resource to v0.21 to avoid Github abuse rate limit

concourse/pipelines/pr_pipeline.yml
6X backport: https://github.com/greenplum-db/gpdb/pull/11065 master backport: https://github.com/greenplum-db/gpdb/pull/11045
We started hitting this on Thursday, and there's been ongoing report from the community about this as well. While upstream is figuring out a long term solution [1], we've been advised [2] to pin to the previous release (v0.21.0) to avoid being blocked for hours at once.
[1]: telia-oss/github-pr-resource#238
[2]: telia-oss/github-pr-resource#238 (comment)
=> [5X backport]: Pin PR resource to v0.21 to avoid Github abuse rate limit

src/backend/cdb/cdblegacyhash.c
Currently, when inserting into a table distributed by a bpchar using
the legacy bpchar hash operator, the row goes through jump consistent
hashing instead of lazy modular hashing. This is because the
cdblegacyhash_bpchar funcid is missing from the
isLegacyCdbHashFunction check function which determines if an
attribute is using a legacy hash function or not. The funcids
currently in that check function come from the auto-generated
fmgroids.h header file which only creates a DEFINE for the
pg_proc.prosrc field. Unfortunately, cdblegacyhash_bpchar is left out
because its prosrc is cdblegacyhash_text.
A proper fix would require a catalog change. To fix this issue in
6X_STABLE, we need to hardcode cdblegacyhash_bpchar funcid 6148 into
the isLegacyCdbHashFunction check function. This should be …
=> Hardcode missing cdblegacyhash_bpchar in isLegacyCdbHashFunction check

src/backend/cdb/motion/ic_udpifc.c
In some cases, some signals (like SIGQUIT) that should only be processed by the main thread of the postmaster may be dispatched to rxThread. So we should and it is safe to block all signals in the udp pthreads.
Fix #11006
=> mask all signal in the udp pthreads

gpMgmt/bin/gppylib/operations/buildMirrorSegments.py, gpMgmt/bin/gppylib/test/unit/test_unit_buildmirrorsegments.py
It didn't log the error message before if pg_rewind fails, fix that to make
DBA/field/developer's life eaisier.
Before this:
```
20201022:15:19:10:011118 gprecoverseg:earth:adam-[INFO]:-Running pg_rewind on required mirrors
20201022:15:19:12:011118 gprecoverseg:earth:adam-[WARNING]:-Incremental recovery failed for dbid 2. You must use gprecoverseg -F to recover the segment.
20201022:15:19:12:011118 gprecoverseg:earth:adam-[INFO]:-Starting mirrors
20201022:15:19:12:011118 gprecoverseg:earth:adam-[INFO]:-era is 0406b847bf226356_201022151031
```
After this:
```
20201022:15:33:31:019577 gprecoverseg:earth:adam-[INFO]:-Running pg_rewind on required mirrors
20201022:15:33:31:019577 gprecoverseg:earth:adam-[WARNING]:-pg_rewind: fatal: could not find common ancestor of the source and target …
```
=> 6X: gprecoverseg: log the error if pg_rewind fails

src/backend/cdb/cdbfts.c
If cdbcomponent_getCdbComponents() caught an error threw by
function getCdbComponents, FtsNotifyProber would be called.
But if it happened inside fts process, ftp process would hang.
Skip fts probe for fts process, after that, under the same
situation, fts process would exit and then be restarted by
postmaster.
=> Skip fts probe for fts process

gpdb-doc/dita/admin_guide/external/g-devel-fdw.xml, gpdb-doc/dita/admin_guide/external/g-foreign.xml, gpdb-doc/dita/install_guide/install_modules.xml, gpdb-doc/dita/ref_guide/modules/intro.xml, gpdb-doc/dita/ref_guide/modules/modules.ditamap, gpdb-doc/dita/ref_guide/modules/postgres_fdw.xml
add some docs for the postgres_fdw module; explicitly calling out greenplum limitations and xref'ing to postgres docs for the core info.
doc review site link:  http://docs-lisa-postgres_fdw.cfapps.io/7-0/ref_guide/modules/postgres_fdw.html
=> docs - add info about postgres_fdw module

gpMgmt/bin/generate-greenplum-path.sh
zsh doesn't have BASH_SOURCE. "${(%):-%x}" is the similar replacement
for zsh.
Also try to support other shells with some command combinations.
Tested with bash/zsh/dash.
=> Make greenplum-path.sh compatible with more shells

src/backend/cdb/dispatcher/cdbdisp_async.c
On QD, it tracks whether QE wrote_xlog in the libpq connection.
The logic is, if QE writes xlog, it'll send a libpq msg to QD. But the
msg is sent in ReadyForQuery. So, before QE execute this function, the
QE may already send back results to QD. Then when QD process this
message, it does not read the new wrote_xlog value. This makes the
connection still contains the previous dispatch wrote_xlog value,
which will affect whether choosing one-phase commit.
The issue only happens when the QE flush the libpq msg before the
ReadyForQuery function, hard to find a case to cover it.
=> Reset wrote_xlog in pg_conn to avoid keeping old value.

gpMgmt/bin/generate-greenplum-path.sh
The error was introduced by dc96f66789.
If `set -u` was called before sourcing greenplum_path.sh with bash, an
error `ZSH_VERSION: unbound variable` would be reported.
To solve the issue, use shell syntax `{:-}` which will output an empty
value if the variable doesn't exist.
Tested with zsh, bash and dash.
See example of CI failure at:
https://prod.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb_master/jobs/icw_planner_centos7/builds/1609
=> Fix source greenplum_path.sh error with set -u

src/backend/cdb/dispatcher/cdbdisp_async.c
On QD, it tracks whether QE wrote_xlog in the libpq connection.
The logic is, if QE writes xlog, it'll send a libpq msg to QD. But the
msg is sent in ReadyForQuery. So, before QE execute this function, the
QE may already send back results to QD. Then when QD process this
message, it does not read the new wrote_xlog value. This makes the
connection still contains the previous dispatch wrote_xlog value,
which will affect whether choosing one phase commit.
The issue only happens when the QE flush the libpq msg before the
ReadyForQuery function, hard to find a case to cover it.
I found the issue when I playing the code to send some information from
QE to QD. And it breaks the gangsize test which shows the commit info.
(cherry picked from commit 777b51cde0cc64f064378a4b11eeae7a821b85f0)
=> [6X Backport]Reset wrote_xlog in pg_conn to avoid keeping old value. (#11077)

src/backend/commands/resgroupcmds.c, src/backend/utils/resgroup/resgroup.c
In function DropResourceGroup(), group->lockedForDrop is set
to true by calling ResGroupCheckForDrop, however, it can only
be set to false inside dropResgroupCallback. This callback is
registered at the ending of function DropResourceGroup. If an
error occured between them, group->lockedForDrop would be true
forever.
Fix it by putting the register process ahead of the lock call.
To prevent Assert(group->nRunning* > 0) if ResGroupCheckForDrop
throws an error, return directly if group->lockedForDrop did
not change.
See:
```
gpconfig -c gp_resource_manager -v group
gpstop -r -a
psql
CPU_RATE_LIMIT=20,
MEMORY_LIMIT=20,
CONCURRENCY=50,
MEMORY_SHARED_QUOTA=80,
MEMORY_SPILL_RATIO=20,
MEMORY_AUDITOR=vmtracker
);
psql -U user_test
> \d -- hang
```
Conflicts:
src/backend/utils/resgroup/resgroup.c
=> [6X backport] Fix resgroup unusable if its dropping failed

src/backend/commands/resgroupcmds.c, src/backend/utils/resgroup/resgroup.c
In function DropResourceGroup(), group->lockedForDrop is set
to true by calling ResGroupCheckForDrop, however, it can only
be set to false inside dropResgroupCallback. This callback is
registered at the ending of function DropResourceGroup. If an
error occured between them, group->lockedForDrop would be true
forever.
Fix it by putting the register process ahead of the lock call.
To prevent Assert(group->nRunning* > 0) if ResGroupCheckForDrop
throws an error, return directly if group->lockedForDrop did
not change.
See:
```
gpconfig -c gp_resource_manager -v group
gpstop -r -a
psql
CPU_RATE_LIMIT=20,
MEMORY_LIMIT=20,
CONCURRENCY=50,
MEMORY_SHARED_QUOTA=80,
MEMORY_SPILL_RATIO=20,
MEMORY_AUDITOR=vmtracker
);
psql -U user_test
> \d -- hang
```
Conflicts:
src/backend/utils/resgroup/resgroup.c
=> [5X backport] Fix resgroup unusable if its dropping failed

src/backend/gpopt/utils/COptTasks.cpp, src/backend/gporca/data/dxl/minidump/BTreeIndex-Against-InListLarge.mdp, src/backend/gporca/data/dxl/minidump/BitmapIndexScanChooseIndex.mdp, src/backend/gporca/libgpdbcost/src/CCostModelGPDB.cpp, src/backend/gporca/libgpdbcost/src/CCostModelParamsGPDB.cpp, src/backend/gporca/libgpopt/src/xforms/CXformUtils.cpp, src/backend/gporca/scripts/cal_bitmap_test.py, src/backend/gporca/server/CMakeLists.txt
- In the default cost model, use the multi-range code to cost IN queries.
This makes the cost more similar with what we used to do in the past,
before we used an array comparison operator to cost it.
- Update the 'experimental' cost model (optimizer_cost_model=experimental)
to make it work a bit better for index scans. Using a simpler formula
and updated constants.
- Changes to the calibration program, made while measuring the new
cost model.
See the individual commits for more info.
=> Experimental cost model update

src/backend/cdb/motion/ic_udpifc.c
In some cases, some signals (like SIGQUIT) that should only be
processed by the main thread of the postmaster may be dispatched to rxThread.
So we should and it is safe to block all signals in the udp pthreads.
Fix #11006
(cherry picked from commit 54451fc061af2e2d1ba592ed962f58f73a5058ea)
=> [6X backport] mask all signal in the udp pthreads

src/backend/postmaster/autovacuum.c, src/backend/utils/init/postinit.c, src/test/regress/greenplum_schedule, src/test/regress/input/autovacuum-template0-segment.source, src/test/regress/output/autovacuum-template0-segment.source
the autovacuum worker for template0 will fail because `Gp_session_role` is still Dispatcher, as follow:
```
2020-09-29 21:20:02.686827 CST,,,p19902,th-881792832,,,,0,,,seg2,,,,sx1,"FATAL","57P03","connections to primary segments are not allowed","This database instance is running as a primary segment in a Greenplum cluster and does not permit direct connections.","To force a connection anyway (dangerous!), use utility mode.",,,,,0,,"postinit.c",1151,
```
```c
/*
* MPP:  If we were started in utility mode then we only want to allow
* incoming sessions that specify gp_session_role=utility as well.  This
* lets the bash scripts start the QD in utility mode and connect in but
* protect ourselves from normal clients who might be trying to connect to
* the system while we startup.
*/
if …
```
=> Fix the FATAL error of autovacuum on template0

src/backend/commands/matview.c
019-12-04 23:16:23.075209 CST,"gpadmin","regression",p30552,th-790954624,"[local]",,2019-12-04 23:16:03 CST,8192,con143,cmd54,seg-1,,,x8192,sx1,"ERROR","XX000","unrecognized node type: 0 (copyfuncs.c:6424)",,,,,,"REFRESH MATERIALIZED VIEW m_aocs WITH NO DATA;",0,,"copyfuncs.c",6273,"Stack trace:
1    0xaf1f9c postgres errstart (elog.c:561)
2    0xaf4b83 postgres elog_finish (elog.c:1734)
3    0x7b15f7 postgres copyObject (copyfuncs.c:6424)
4    0x6c6ad1 postgres ExecRefreshMatView (matview.c:409)
5    0x997841 postgres <symbol not found> (utility.c:1743)
6    0x9969f4 postgres standard_ProcessUtility (utility.c:1071)
7    0x993bc5 postgres <symbol not found> (palloc.h:176)
8    0x9945c5 postgres <symbol not found> (pquery.c:1552)
9    0x995a21 postgres PortalRun (pquery.c:1022)
10 …
=> [6X backport] Fix dangling pointer issue when refreshing a matview relation

gpMgmt/bin/gppylib/operations/Makefile, gpMgmt/bin/gppylib/operations/buildMirrorSegments.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_conf.py, gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py, gpMgmt/bin/gppylib/programs/clsAddMirrors.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py, gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py, gpMgmt/bin/gppylib/utils.py, gpMgmt/doc/gprecoverseg_help, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
When a down mirror segment is moved to a new host using gprecoverseg Full, the replication/connections entries for the new mirror are not appended to the primary pg_hba.conf due to which gprecoverseg fails. This commits updates the code to add the entries of the new mirror to the primary pg_hba.conf
=> Fix gprecoverseg hba

gpMgmt/bin/gpinitsystem
Earlier the error was sent to /dev/null and the information was lost
displaying the cause of the error. Redirect the error to log file.
=> Redirect the error to log message

gpMgmt/bin/analyzedb
Commit 4bbbb3810eb043af521dd60e738aaa2538cf30d4 introduced some hardening
around concurrent drop and recreate of tables while analyzedb is running but it
failed to take into account the code around updating the last operation
performed. This commit fixes it.
(cherry picked from commit 6949ecfb1a90c92db63c7c26463f3a9110d3fa12)
=> [6X backport] Harden analyzedb

gpMgmt/bin/analyzedb
Commit 4bbbb3810eb043af521dd60e738aaa2538cf30d4 introduced some hardening
around concurrent drop and recreate of tables while analyzedb is running but it
failed to take into account the code around updating the last operation
performed. This commit fixes it.
(cherry picked from commit 6949ecfb1a90c92db63c7c26463f3a9110d3fa12)
=> [5X] Harden analyzedb against concurrently dropped and recreated tables

gpMgmt/bin/gppylib/operations/Makefile, gpMgmt/bin/gppylib/operations/test/unit/test_unit_buildMirrorSegments.py, gpMgmt/bin/gppylib/operations/test/unit/test_unit_update_pg_hba_conf.py, gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py, gpMgmt/bin/gppylib/programs/clsAddMirrors.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gppylib/test/unit/test_unit_gpaddmirrors.py, gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py, gpMgmt/bin/gppylib/utils.py, gpMgmt/doc/gprecoverseg_help, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature
When a down mirror segment is moved to a new host using gprecoverseg Full, the replication/connections entries for the new mirror are not appended to the primary pg_hba.conf due to which gprecoverseg fails. This commits updates the code to add the entries of the new mirror to the primary pg_hba.conf
=> fix gprecoverseg

contrib/file_fdw/file_fdw.c, gpcontrib/gp_exttable_fdw/extaccess.c, gpcontrib/pxf_fdw/pxf_option.c, src/backend/commands/copy.c, src/backend/commands/exttablecmds.c, src/include/commands/copy.h
ProcessCopyOptions checks the option list of COPY command. It's also
called by external table when text/csv format is used. It's better
not to mix external table specific options here and check them
separately.
Checking custom protocol here is not necessary because it's checked
when parsing location urls in GenerateExtTableEntryOptions anyway.
=> Separate external table options out of copy option check

src/backend/cdb/motion/ic_proxy.h, src/backend/cdb/motion/ic_proxy_addr.c, src/backend/cdb/motion/ic_proxy_addr.h, src/backend/cdb/motion/ic_proxy_main.c, src/backend/cdb/motion/ic_proxy_peer.c, src/backend/cdb/motion/ic_proxy_server.h
The peer addresses are specified with the GUC
gp_interconnect_proxy_addresses, it can be reloaded on SIGHUP, we used
to only care about the newly added ones, however it is also possible for
the user to modify them, or even remove some of them.
So now we add the logic to classify the addresses after parsing the GUC,
we can tell whether an address is added, removed, or modified.
The peer connections and / or the listeners are refreshed accordingly.
----
Tests are not included, it's not easy to automate the verification.
But we can verify the effect manually, simply update the GUC `gp_interconnect_proxy_addresses` and reload with `gpstop -u`, then monitor the `netstat -nlt` output.
Also note that, ic-proxy header files are all private, they are not under `src/include` and are not included in …
=> ic-proxy: refresh peer connections and listeners on address/port changes

src/backend/storage/file/execute_pipe.c
```
execute_pipe.c:197:6: error: implicit declaration of function 'kill' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
if (kill(pid, 0) == 0) /* process exists */
^
1 error generated.
```
This actually showed up in Travis CI on PR #11121 (https://travis-ci.org/github/greenplum-db/gpdb/builds/742342058) before it got merged into master.
Co-authored-by: Jesse Zhang
=> Include <signal.h> to fix compiler error on MacOS

gpcontrib/gp_exttable_fdw/gp_exttable_fdw.c, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
With reject limit, if reject limit is not reached,
there should be some messages that how many rows
are rejected as `execute on segments` does.
Co-authored-by Mingli Zhang <zmingli@vmware.com>
Co-authored-by Adam Lee <adlee@vmware.com>
=> [master]Notice reject messages of external tables executed on master

src/backend/gporca/data/dxl/minidump/IndexOnlyScan-NoDistKeyInIndex.mdp, src/backend/gporca/libgpdbcost/src/CCostModelGPDBLegacy.cpp, src/backend/gporca/libgpopt/include/gpopt/base/CColRef.h, src/backend/gporca/libgpopt/src/operators/CLogical.cpp, src/backend/gporca/libgpopt/src/xforms/CXformIndexGet2IndexOnlyScan.cpp, src/backend/gporca/server/CMakeLists.txt
In order to produce an index only scan plan, all columns referenced in
the query must be covered by an index. This check is made in the
`CXformIndexGet2IndexOnlyScan::Transform`.
Issue is that distribution columns were being marked as used even when
they were not directly referenced. This is because they are implicitly
used to add motions. However, this meant that Orca would never consider
an index only scan if the distribution column was not covered by the
index.
The changes in CCostModelGPDBLegacy are only to make Orca unittests happy. Goal
is to eventually remove legacy cost model altogether. But for now the a path of
least resistance is to piggy-back on index legacy costing.
=> Allow Orca to choose index only scan on non-distribution columns

gpAux/Makefile, gpMgmt/Makefile, gpMgmt/bin/Makefile, gpMgmt/bin/generate-greenplum-path.sh, gpMgmt/bin/gpload, gpMgmt/bin/test-generate-greenplum-path.bash
Update greenplum_path.sh to use BASH_SOURCE for determining GPHOME
Update gpload test script to use bash instead of sh
Update Makefile target for pygresql to not source greenplum_path.sh, since BASH_SOURCE is only defined in bash, in ubuntu platform, it only has dash, which will make source greenplum_path.sh failed, build pygresql only need pg_config, so set PATH in order to find pg_config.
discussion mail list: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/AgEGOsoAAlQ/m/a2VIBZgMCQAJ
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-sbai
=> [backport 5X]GPHOME is determined dynamically when sourcing greenplum_path

gpAux/Makefile, gpMgmt/Makefile, gpMgmt/bin/Makefile, gpMgmt/bin/generate-greenplum-path.sh, gpMgmt/bin/gpload, gpMgmt/bin/test-generate-greenplum-path.bash
Update greenplum_path.sh to use BASH_SOURCE for determining GPHOME
Update gpload test script to use bash instead of sh
Update Makefile target for pygresql to not source greenplum_path.sh, since BASH_SOURCE is only defined in bash, in ubuntu platform, it only has dash, which will make source greenplum_path.sh failed, build pygresql only need pg_config, so set PATH in order to find pg_config.
discussion mail list: https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/AgEGOsoAAlQ/m/a2VIBZgMCQAJ
Dev pipeline: https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/gpdb-dev-173785163-gphome-gp6
=> [backport 6X]GPHOME is determined dynamically when sourcing greenplum_path

src/backend/gporca/data/dxl/minidump/ArrayCmpAllEmpty.mdp, src/backend/gporca/data/dxl/minidump/ArrayCmpAnyEmpty.mdp, src/backend/gporca/data/dxl/minidump/ArrayCmpAnyEmptyLessThan.mdp, src/backend/gporca/libgpopt/src/base/CConstraint.cpp, src/backend/gporca/libgpopt/src/base/CConstraintConjunction.cpp, src/backend/gporca/libgpopt/src/base/CConstraintDisjunction.cpp, src/backend/gporca/libnaucrates/src/parser/CParseHandlerArray.cpp, src/backend/gporca/server/CMakeLists.txt
During preprocessing, Orca simplifies the query by merging/deduplicating
constraints. However, Orca did not consider the case where the passed in
constraint was a column compared with an empty array. This assumption
caused Orca to crash.
Instead, we should skip merging a constraint with an empty array.
This occured with predicates such as `a = ANY('{}')`.
There were also some assertions about the length of the constraint arrays that
were hit in debug build. These assertions are removed as an empty
constraint array is allowed.
=> Fix handling of empty constraint array in Orca

src/backend/gporca/data/dxl/minidump/ArrayCmpAllEmpty.mdp, src/backend/gporca/data/dxl/minidump/ArrayCmpAnyEmpty.mdp, src/backend/gporca/data/dxl/minidump/ArrayCmpAnyEmptyLessThan.mdp, src/backend/gporca/libgpopt/src/base/CConstraint.cpp, src/backend/gporca/libgpopt/src/base/CConstraintConjunction.cpp, src/backend/gporca/libnaucrates/src/parser/CParseHandlerArray.cpp, src/backend/gporca/server/CMakeLists.txt
This is a trivial backport of https://github.com/greenplum-db/gpdb/pull/11139.
During preprocessing, Orca simplifies the query by merging/deduplicating
constraints. However, Orca did not consider the case where the passed in
constraint was a column compared with an empty array. This assumption
caused Orca to crash when dealing with predicates such as `a = ANY('{}')`.
Instead, we now explicitly return an empty constraint when dealing with an ANY('{}')
clause. For ALL('{}'), we won't process the constraint as there's no
simplification to do.
(cherry picked from commit f97a3e23899e58a91b3228b1686561440fc22a12)
=> [6X] Fix handling of empty constraint array in Orca (#11139)

config/orca.m4, configure, depends/conanfile_orca.txt, gpAux/releng/releng.mk
Corresponding ORCA PR: "Fix handling of empty constraint array in Orca" (https://github.com/greenplum-db/gporca/pull/608)
During preprocessing, Orca simplifies the query by
merging/deduplicating constraints. However, Orca did not consider
the case where the passed in constraint was a column compared with
an empty array. This assumption caused Orca to crash when dealing
with predicates such as a = ANY('{}').
Instead, we now explicitly return an empty constraint when dealing
with an ANY( '{}') clause. For ALL('{}'), we won't process the
constraint as there's no simplification to do.
=> Bump ORCA version to 3.114

src/backend/access/transam/xlog.c, src/backend/cdb/cdbdtxrecovery.c, src/backend/cdb/cdbtm.c, src/include/cdb/cdbtm.h
Those functionality is handled in checkpoint during recovery in utility
mode also.  The code is not needed anymore.
=> Remove gpdb specific dtx recovery code for utility mode.

src/backend/access/transam/xlog.c, src/backend/cdb/cdbdtxrecovery.c, src/test/isolation2/expected/standby_replay_dtx_info.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/standby_replay_dtx_info.sql
This PR fixes issue #9207.
When replaying checkpoint XLOG record on standby, it will add gids contained in it to
`shmCommittedGxactArray`. If the `DISTRIBUTED_FORGET`  XLOG record of the DTXs 
written before the checkpoint XLOG record. Those gids will be added twice, which finally
cause the overflow of `shmCommittedGxactArray`.
As is known, DTX info contained in checkpoint XLOG record is used for the situation 
DTX crash recovery, so on standby, only the first checkpoint XLOG record needs to be
replayed when start up, and the following can be skipped.
=> Fix overflow of shmCommittedGxactArray on standby

gpMgmt/bin/gppylib/operations/startSegments.py
I have seen too many "[CRITICAL]:-gpstart failed. (Reason='')
exiting..." errors, and there was nothing in the log. The reason could
be "SSH PATH", "Python modules" or some other issues.
Log the stderr to save debugging efforts.
=> gpstart logs commands' stderr

src/backend/tcop/test/postgres_test.c
In the same spirit as ee7eb0e8ec77d1b6, this removes the extra
definition in postgres_test.c.
This is uncovered by building with GCC 10, where -fno-common is the new
default [1][2] (vis a vis -fcommon). I could also reproduce this by
turning on "-fno-common" in older releases of GCC and Clang.
Backpatch to 6X_STABLE.
=> Fix multiple definition linker error in unit tests

src/backend/access/transam/xlog.c, src/backend/cdb/cdbdtxrecovery.c, src/test/isolation2/expected/standby_replay_dtx_info.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/standby_replay_dtx_info.sql
Previously, standby will replay checkpoint XLOG record's DTX info
in function XLogProcessCheckpointRecord. However, is some certain cases,
it will cause anomaly: When a DTX has flushed FORGET COMMITTED XLOG into
disk, but didn't change its own state to DTX_STATE_INSERTED_FORGET_COMMITTED.
If at this very moment, checkpoint process is calculating DTX info, it
will include the DTX into its XLOG record. So when standby replaying this
checkpoint XLOG record from master, it will add an already forgotten GID to
shmCommittedGxactArray again, which may cause the overflow of shmCommittedGxactArray.
Since DTX info stored in checkpoint XLOG record has been populated earlier in
ReadCheckpointRecord(), there is no need to call XLogProcessCheckpointRecord()
again during recovery.
Co-authored-by: …
=> [6X backport] Fix overflow of shmCommittedGxactArray on standby (#11071)

src/backend/access/external/fileam.c, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
With reject limit, if reject limit is not reached,
there should be some messages that how many rows
are rejected as `execute on segments` does.
Co-authored-by Mingli Zhang <zmingli@vmware.com>
Co-authored-by Adam Lee <adlee@vmware.com>
=> [6x_stable]Notice reject messages of external tables executed on master

src/backend/access/external/fileam.c, src/test/regress/input/external_table.source, src/test/regress/output/external_table.source
With reject limit, if reject limit is not reached,
there should be some messages that how many rows
are rejected as `execute on segments` does.
Co-authored-by Mingli Zhang <zmingli@vmware.com>
Co-authored-by Adam Lee <adlee@vmware.com>
=> [5x_stable]Notice reject messages of external tables executed on master

src/backend/cdb/cdbgroup.c, src/backend/optimizer/plan/planner.c, src/include/optimizer/planmain.h, src/test/regress/expected/aggregate_with_groupingsets.out, src/test/regress/expected/gporca.out, src/test/regress/sql/aggregate_with_groupingsets.sql
Currently if GROUPING SETS are empty sets, we will clean up
parse->groupClause and treat it as having no groups. If meanwhile there
are no aggregates in tlist or havingQual, the query would be planned as
if there are no GROUPING SETS, which is not correct.
This patch is just a workaround by petending the query has aggregates
when it finds the GROUPING SETS are empty sets.
Fix issue #11003
=> Fix GROUPING SETS of multiple empty sets

src/backend/cdb/cdbdistributedsnapshot.c, src/backend/utils/time/tqual.c, src/test/isolation2/expected/distributed_transactions.out, src/test/isolation2/sql/distributed_transactions.sql
This is partial cherry-pick from commit
b3f300b945735d46325f93449c0dea9f4f9c025c.  In the QD, the distributed
transactions become visible at the same time as the corresponding
local ones, so we can rely on the local XIDs. This is true because the
modification of local procarray and globalXactArray are protected by
lock and hence a atomic operation during transaction commit.
We have seen many situations where catalog queries run very slow on QD
and potential reason is checking distributed logs. Process local
distributed log cache fall short for this usecase as most of XIDs are
unique and hence get frequent cache misses. Shared memory cache falls
short as only caches 8 pages and many times need many more pages to be
cached to be effective.
Co-authored-by: Hubert Zhang <hzhang@pivotal.io> …
=> Avoid checking distributed snapshot for visibility checks on QD

src/backend/commands/vacuum.c, src/test/regress/expected/vacuum_gp.out, src/test/regress/sql/vacuum_gp.sql
In vac_update_datfrozenxid.(), the pg_database tuple for current
database should be fetched from disk heap table instead of system cache.
Since the cache already flatten toast tuple, so if the tuple in
pg_database contains toast attribute, heap_inplace_update() will fail
with "wrong tuple length".
Postgres upstream also has this issue. But since the issue is hot,
let's fix in GPDB first.
=> Get pg_database tuple from disk in vac_update_datfrozenxid.

src/backend/commands/vacuum.c, src/test/regress/expected/vacuum_gp.out, src/test/regress/sql/vacuum_gp.sql
In vac_update_datfrozenxid.(), the pg_database tuple for current
database should be fetched from disk heap table instead of system cache.
Since the cache already flatten toast tuple, so if the tuple in
pg_database contains toast attribute, heap_inplace_update() will fail
with "wrong tuple length".
Postgres upstream also has this issue. But since the issue is hot,
let's fix in GPDB first.
(cherry picked from commit 373e676de819fc0cdadfb59d35d9279abe3d11d9)
=> [5X Backport]Get pg_database tuple from disk in vac_update_datfrozenxid.

src/backend/access/aocs/aocssegfiles.c, src/backend/access/appendonly/aosegfiles.c
Seems dangerous to access tables without holding a lock. This PR is backport for PR https://github.com/greenplum-db/gpdb/pull/9657 against master branch.
=> Acquire proper locks in gp_aoseg() and similar debugging functions.

src/backend/commands/vacuum.c, src/test/regress/expected/vacuum_gp.out, src/test/regress/sql/vacuum_gp.sql
In vac_update_datfrozenxid.(), the pg_database tuple for current
database should be fetched from disk heap table instead of system cache.
Since the cache already flatten toast tuple, so if the tuple in
pg_database contains toast attribute, heap_inplace_update() will fail
with "wrong tuple length".
Postgres upstream also has this issue. But since the issue is hot,
let's fix in GPDB first.
(cherry picked from commit 373e676de819fc0cdadfb59d35d9279abe3d11d9)
=> [6X Backport]Get pg_database tuple from disk in vac_update_datfrozenxid.

src/backend/utils/resgroup/resgroup.c
groupIncMemUsage/groupDecMemUsage are not protected by locks, it
may occur concurrency problem, e.g.
```
Assume:
slot->memQuota = 500
slot->memUsage = 500
group->memSharedGranted = 100
group->memSharedUsage = 0
Now:
A groupIncMemUsage chunks=2:
atomic add slot->memUsage = 500+2 = 502
atomic fetch slotMemUsage = 502
B groupDecMemUsage chunks=2:
atomic fetch slotMemUsage = 502
atomic sub slot->memUsage = 502-2 = 500
slotMemUsage 502 > memQuota 500, so:
deltaSharedMemUsage = Min(502-500, 2) = 2
atomic fetch oldSharedUsage = 0
atomic sub group->memSharedUsage = 0-2 = -2
Assert(0 >= 2); // FAILED if --enable-cassert
A groupIncMemUsage chunks=2: -- continue
slotMemUsage 502 > memQuota 500, so:
deltaSharedMemUsage = Min(2, 2) = 2
atomic fetch oldSharedUsage = -2
atomic add group->memSharedUsage …
```
=> Fix potential assertion failure when resgroup inc/sub memusage

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
Compare the variance of row count can be flaky, fix it by comparing the
distribution of matview and base table.
=> Fix flaky test expand matview

gpMgmt/test/behave/mgmt_utils/gpexpand.feature
gpexpand test set 'optimizer=on' by default and CTAS without 'DISTRIBUTED BY'
clause will create random distributed table, that will cause the test flaky.
=> Fix flaky test

src/backend/gporca/data/dxl/minidump/AddPredsInSubqueries.mdp, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp, src/backend/gporca/libnaucrates/include/naucrates/base/CDatumGenericGPDB.h, src/backend/gporca/libnaucrates/include/naucrates/md/CMDTypeGenericGPDB.h, src/backend/gporca/libnaucrates/include/naucrates/md/IMDTypeGeneric.h, src/backend/gporca/libnaucrates/src/base/CDatumGenericGPDB.cpp, src/backend/gporca/libnaucrates/src/md/CMDTypeGenericGPDB.cpp, src/backend/gporca/scripts/convert_minirepro_6_to_7.py, src/backend/gporca/server/src/unittest/dxl/base/CDatumTest.cpp
Methods CDatumGenericGPDB::IsDatumMappableToLINT() and
CDatumGenericGPDB::IsDatumMappableToDouble() were relatively
expensive and they can be called many times when we process
large, complicated queries. The calls mostly happen during
derivation of join stats, but also during generation of
partition predicates.
Adding two boolean flags that indicate whether a datum is
mappable to LINT or CDouble makes these methods much faster
and can speed up optimization significantly. In the example I
looked at, the improvement was 30% for 'exhaustive' and 55%
for 'exhaustive2'. (164 sec -> 114 sec and 87 sec --> 39 sec).
This was a UNION of two 15-way joins, containing several left
outer joins and subqueries on partitioned tables with many
text columns.
For most queries the gains will be much smaller. …
=> Store lint/double mappable info in CDatumGenericGPDB

src/backend/cdb/cdbgroup.c, src/test/regress/expected/gp_aggregates.out, src/test/regress/sql/gp_aggregates.sql
When the group key is an expression, i.e. not a column name, and
there are some other ungrouped targets that reference the group key,
the planner may crash or produce incorrect result.
Normally, the function check_ungrouped_columns() will scan the
expression trees for ungrouped variables on the target list.
Later, subquery_planner() may transafer the target list to a
new equivalent list, for example,
SELECT dttm >= 0, NOT dttm >= 0 FROM foo GROUP BY 1;
`NOT dttm >= 0` will be converted to `dttm < 0`. In multi-agg,
deconstruct_agg_info() calls deconstruct_expr() to generate
the final target list. Since `dttm < 0` is not an Aggref, it
should reference the group key as the original expression.
The idea to fix this issue is to add the column names to the
output in the first aggregate, so …
=> Fix the planner crash when the group key is an expression in multi-agg

src/backend/gporca/data/dxl/minidump/AddPredsInSubqueries.mdp, src/backend/gporca/libgpopt/src/base/CUtils.cpp, src/backend/gporca/libgpopt/src/operators/CPhysicalHashJoin.cpp, src/backend/gporca/libnaucrates/include/naucrates/base/CDatumGenericGPDB.h, src/backend/gporca/libnaucrates/include/naucrates/md/CMDTypeGenericGPDB.h, src/backend/gporca/libnaucrates/include/naucrates/md/IMDTypeGeneric.h, src/backend/gporca/libnaucrates/src/base/CDatumGenericGPDB.cpp, src/backend/gporca/libnaucrates/src/md/CMDTypeGenericGPDB.cpp
Method CDatumGenericGPDB::IsDatumMappableToLINT()
can be called many times when we process large,
complicated queries. The calls mostly happen during
derivation of join stats, but also during generation of
partition predicates.
We can speed these calls up by caching a pointer to an
IMDType object, to avoid the repeated metadata lookups.
In the example I looked at, I saw improvements of up to 70%
(for 'exhaustive2'). This was a UNION of two 15-way joins,
containing several left outer joins and subqueries on
partitioned tables with many text columns. For most queries
the gains will be much smaller. For TPC-DS I saw basically
no gains.
(cherry picked from commit 5d44a43e17d44713fff128902aeaa1400f7f4a9c)
=> Cache a type pointer in CDatumGenericGPDB

src/backend/commands/indexcmds.c, src/test/isolation2/expected/reindex/createidx_while_reindex_ao_gist.out, src/test/isolation2/expected/reindex/createidx_while_reindex_ao_partition.out, src/test/isolation2/expected/reindex/createidx_while_reindex_aoco_gist.out, src/test/isolation2/expected/reindex/createidx_while_reindex_idx_ao_bitmap.out, src/test/isolation2/expected/reindex/createidx_while_reindex_idx_ao_btree.out, src/test/isolation2/expected/reindex/createidx_while_reindex_idx_aoco_bitmap.out, src/test/isolation2/expected/reindex/createidx_while_reindex_idx_aoco_btree.out, src/test/isolation2/sql/reindex/createidx_while_reindex_ao_gist.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_ao_partition.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_aoco_gist.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_idx_ao_bitmap.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_idx_ao_btree.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_idx_aoco_bitmap.sql, src/test/isolation2/sql/reindex/createidx_while_reindex_idx_aoco_btree.sql
Appendoptimized tables need block directory relation for index access. Creating
and maintaining block directory is expensive. We delay the block directory
creation until it is really needed - the first index creation. Once created,
all indexes share the same block directory. We need a stronger lock
(ShareRowExclusiveLock) if the block directory needs to be created. If the
block directory already exists, we can use the same lock as heap tables.
(backported from commit 514bcfe990773f4854d9994da936abd25b371b28)
=> 6X: Level down the lock of creating indexes on AO tables if blkdir exists

src/backend/utils/resgroup/resgroup.c
groupIncMemUsage/groupDecMemUsage are not protected by locks, it
may occur concurrency problem, e.g.
```
Assume:
slot->memQuota = 500
slot->memUsage = 500
group->memSharedGranted = 100
group->memSharedUsage = 0
Now:
A groupIncMemUsage chunks=2:
atomic add slot->memUsage = 500+2 = 502
atomic fetch slotMemUsage = 502
B groupDecMemUsage chunks=2:
atomic fetch slotMemUsage = 502
atomic sub slot->memUsage = 502-2 = 500
slotMemUsage 502 > memQuota 500, so:
deltaSharedMemUsage = Min(502-500, 2) = 2
atomic fetch oldSharedUsage = 0
atomic sub group->memSharedUsage = 0-2 = -2
Assert(0 >= 2); // FAILED if --enable-cassert
A groupIncMemUsage chunks=2: -- continue
slotMemUsage 502 > memQuota 500, so:
deltaSharedMemUsage = Min(2, 2) = 2
atomic fetch oldSharedUsage = -2
atomic add group->memSharedUsage …
```
=> [6X backport] Fix potential assertion failure when resgroup inc/sub memusage

gpMgmt/test/behave/mgmt_utils/gpexpand.feature, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
gpexpand test set 'optimizer=on' by default and CTAS without 'DISTRIBUTED BY'
clause will create randomly distributed table, that will cause the test flaky.
=> [6X backport] Fix flaky test expand matview

src/backend/utils/cache/lsyscache.c, src/test/regress/expected/rowsecurity.out, src/test/regress/expected/triggers.out
pg_trigger.tgenabled was changed in upstream Postgres 8.3 commit
postgres/postgres@0fe16500d3ae68b8 to support finer-grained control of
trigger firing mechanism. We merged that in during Greenplum 5
development cycle but ORCA didn't quite get the memo. This can lead to
extremely obscure bugs, like greenplum-db/gpdb#7410: assigning an 8-bit
integer to a boolean is an undefined behavior, and the compiler is
permitted to only look at the least significant bit of the value.
Fixes greenplum-db/gpdb#7410
=> Accurately report to ORCA whether a trigger will fire

src/backend/gporca/libgpos/src/memory/CMemoryPoolTracker.cpp
Issue is that when Malloc returns NULL due to OOM, we no longer raise
through GPOS_OOM_CHECK, which was the previous behavior (commit
644d3131826). The fallout of this is that callers of NewImpl() can
SIGSEGV, for example in NewArrayImpl().
Co-authored-by: Soumyadeep Chakraborty <sochakraborty@pivotal.io>
This needs backport to 6X and 5X
=> Reinstate GPOS_OOM_CHECK in CMemoryPoolTracker::NewImpl

src/backend/cdb/cdbappendonlyxlog.c
The value returned by GetDatabasePath is palloc'd, and
CurrentMemoryContext is TopMemoryContext when we enter
ao_truncate_replay(), so we should do a pfree.
Fix #11202
=> Fix memory leak in ao_truncate_replay

src/backend/executor/execUtils.c, src/test/regress/expected/insert.out, src/test/regress/sql/insert.sql
For the gang allocation, we assert the first allocated gang always be the
writer gang. And when recycle, the writer QE aliways be putted at the
top of free list.
Normally, the writer slice will be assign writer gang first when iterate the
slice table. But this is not true for writable CTE (with only one writer gang).
For below statement:
```
explain (slicetable) WITH updated AS (update tbl set rank = 6 where id = 5 returning
rank) select * from tbl where rank in (select rank from updated);
QUERY PLAN
--------------------------------------------------------------
->  Seq Scan on tbl
Filter: (hashed SubPlan 1)
SubPlan 1
->  Broadcast Motion 1:3  (slice2; segments: 1)
->  Update on tbl
->  Seq Scan on tbl
Filter: (id = 5)
Slice 0: Dispatcher; root 0; …
```
=> Fix writeable CTE assign reader gang to writer slice.

src/backend/storage/file/buffile.c, src/backend/storage/file/fd.c, src/backend/utils/sort/logtape.c, src/backend/utils/sort/sharedtuplestore.c, src/backend/utils/sort/tuplestore.c, src/include/storage/buffile.h
Track temporary files that can be shared by multiple backends, so the
gp_toolkit views and gp_* limits apply to these.
Update the signature of BufFileCreateShared() to not expose BufFile and
merge in the future won't miss the work_set.
=> Track shared file set by workfile

src/backend/access/bitmap/bitmappages.c, src/test/regress/expected/bitmap_index.out, src/test/regress/expected/bitmap_index_optimizer.out, src/test/regress/sql/bitmap_index.sql
Pass the index attribute collation for build_hash_key and
build_match_key from the index relation.
=> Resolve bitmap index pages GPDB_12_MERGE_FIXMEs.

gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query44.ans, src/bin/gpfdist/gpfdist.c
fix gpfdist in master header attribute not compatible in gpdb4
We cannot test if this gpfdist(for gp7) can work fine in gpdb4 in pipeline. But I have test this patch and can avoid header not recognizing issue in gp4 in my docker.
make gpfdist header attribute compat with gpdb4
add gpload test case 44 to test header
=> fix gpfdist header not work in gpdb4

gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query39.ans, src/bin/gpfdist/gpfdist.c
fix gpfdist for gpdb5 header not compatible in gpdb4
We cannot test if this gpfdist(for gp5) can work fine in gpdb4 in pipeline. But I have test this patch and can avoid header not recognizing issue in gp4 in my docker.
1. make gpfdist header attribute compat with gpdb4
2. add gpload test case 39 to test header attribute
=> fix gpfdist for gpdb5 header not compatible in gpdb4

src/bin/pg_rewind/copy_fetch.c, src/bin/pg_rewind/file_ops.c, src/bin/pg_rewind/filemap.c, src/bin/pg_rewind/filemap.h, src/bin/pg_rewind/libpq_fetch.c, src/bin/pg_rewind/parsexlog.c, src/bin/pg_rewind/pg_rewind.c
Customers usually have clusters with > 1 Million files, this would mean an incremental recovery will be a time consuming one. It will be good to have incremental work faster.
`lstat()` is slow, we did three times for every file before this PR, and only once after.
=> Refactor pg_rewind `lstat()`

src/bin/pg_rewind/copy_fetch.c, src/bin/pg_rewind/file_ops.c, src/bin/pg_rewind/filemap.c, src/bin/pg_rewind/filemap.h, src/bin/pg_rewind/libpq_fetch.c, src/bin/pg_rewind/parsexlog.c, src/bin/pg_rewind/pg_rewind.c
Customers usually have clusters with > 1 Million files, this would mean an incremental recovery will be a time consuming one. It will be good to have incremental work faster.
lstat() is slow, we did three times for every file before this PR, and only once after.
=> 6X: Refactor pg_rewind `lstat()`

src/backend/cdb/dispatcher/cdbgang.c
In buildGangDefinition, newGangDefinition->db_descriptors are
initialized one by one, but newGangDefinition->size was already
set to its final value. If an error was caught, its size should
be reset to the right number.
It seems that it is not good to remove Assert(segdbDesc != NULL)
in RecycleGang(), otherwise it cannot hold possible case:
gang->size is 3
gang->db_descriptors[0] is NULL
gang->db_descriptors[1] is NOT NULL
gang->db_descriptors[2] is NOT NULL
(cherry picked from commit 269c3b734685834ee3de4d2f41cf80d239c33990)
=> [6X backport] Fix: might recycle wrong gang size.

src/backend/cdb/cdblegacyhash.c, src/include/catalog/catversion.h, src/include/catalog/pg_proc.dat
Currently, when inserting into a table distributed by a bpchar using
the legacy bpchar hash operator, the row goes through jump consistent
hashing instead of lazy modular hashing. This is because the
cdblegacyhash_bpchar funcid is missing from the
isLegacyCdbHashFunction check function which determines if an
attribute is using a legacy hash function or not. The funcids
currently in that check function come from the auto-generated
fmgroids.h header file which only creates a DEFINE for the
pg_proc.prosrc field. Unfortunately, cdblegacyhash_bpchar is left out
because its prosrc is cdblegacyhash_text.
To fix this issue, we should simply give the cdblegacy_bpchar proc its
own prosrc instead of reusing cdblegacyhash_text and add the new
autogenerated funcid DEFINE to the isLegacyCdbHashFunction …
=> Give cdblegacyhash_bpchar proc its own prosrc

src/backend/executor/execHHashagg.c, src/backend/utils/adt/numeric.c, src/test/regress/expected/gp_hashagg.out, src/test/regress/sql/gp_hashagg.sql
This is a backport of PR: #9946
=> 6X Backport: Properly mark null return from combine functions

src/backend/utils/adt/dbsize.c, src/test/regress/expected/db_size_functions.out, src/test/regress/sql/db_size_functions.sql
Error out if this kind of functions execute on entry db, so
user will not confuse with the generated wrong results.
=> Some DB size functions should not execute on entry db.

gpMgmt/bin/gpconfig, gpMgmt/test/behave/mgmt_utils/gpconfig.feature
gpconfig invokes dbconn.Connect with verbose=False due to which
client_min_messages is set to error for that connection and gpconfig -s
client_min_messages always shows error instead of the actual value.
So, instead pass verbose=True for connect with gpconfig. Ran gpconfig -s
for all the parameters and there is no case where it was printing any
warning with libpq.
=> gpconfig always shows client_min_messages value as error

src/include/catalog/catversion.h, src/include/catalog/pg_proc.dat, src/test/isolation2/expected/gp_terminate_mpp_backends.out, src/test/isolation2/expected/segwalrep/dtm_recovery_on_standby.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/gp_terminate_mpp_backends.sql, src/test/isolation2/sql/segwalrep/dtm_recovery_on_standby.sql
This led to "No function matches the given name and argument types.".
Possible mismerge when rebasing master into iteration_REL_12 branch
during postgres 12 merge.
This function was originally introduced by GPDB commit b04175666ae and
merged into iteration_REL_12 in commit 19cfbeb5f0.
Co-authored-by: Soumyadeep Chakraborty <sochakraborty@pivotal.io>
=> Fix catalog definition of gp_terminate_mpp_backends()

gpMgmt/bin/gppylib/programs/clsAddMirrors.py, gpMgmt/test/behave/mgmt_utils/gpconfig.feature
If the configuration to add mirrors is passed by -i parameters, don't
perform mirror offset calculation as the entries in the files are
manually edited based on the preference of the customer.
=> Don't do port validation if passed explicity by configuration file

gpMgmt/test/behave/mgmt_utils/gpstart.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
We add a down mirror case.  This was tricky as Greenplum only detects
a down mirror after a timeout period.  We also needed to make sure this
test works on a multihost cluster.
We also refactored the tests.  This improves the testing of the merged https://github.com/greenplum-db/gpdb/pull/11002.
Co-authored-by: David Krieger <dkrieger@vmware.com>
=> gpstart: improve testing of handling down hosts

src/backend/utils/adt/dbsize.c, src/test/regress/expected/db_size_functions.out, src/test/regress/sql/db_size_functions.sql
Error out if this kind of functions runs on entry DB, so
user will not confuse with the generated wrong results.
(cherry picked from commit ca90fb093c0e4c9f968427a4512f8e33882df5ec)
=> [6X Backport]Some functions do dispatch so they should not execute on entry db.

src/backend/commands/vacuum.c
Index cleanup error message should include params->index_cleanup
=> Coverity: Copy paste error in vacuum param check

src/interfaces/libpq/fe-connect.c
Reported by coverity check.
addr_cur is already checked above and will `goto keep_going;` when addr_cur is NULL
=> Coverity: Remove logically dead code

src/backend/access/aocs/aocsam.c
should replace sizeof(AttrNumber*) with sizeof(AttrNumber).
=> Coverity: Wrong sizeof argument

gpMgmt/bin/gpcheckresgroupimpl, src/backend/utils/resgroup/resgroup-ops-linux.c
For version 6X or higher, 'cpuset' is a necessary subsystem for resource group.
However, if 'cpu' and 'cpuset' are mounted on the same hierarchy, the cpu usage
will be out of control. So we need a validation on this before we using resource
group.
Details in #10990
=> Add a validation on the mount hierarchy of 'cpu' and 'cpuset' subsystem

src/backend/gpopt/translate/CQueryMutators.cpp, src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp, src/backend/gpopt/translate/CTranslatorUtils.cpp, src/backend/gpopt/translate/README, src/backend/gporca/libgpopt/src/base/CDistributionSpecHashed.cpp, src/backend/optimizer/plan/orca.c, src/include/gpopt/translate/CTranslatorQueryToDXL.h, src/include/gpopt/translate/CTranslatorUtils.h, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/expected/groupingsets_optimizer.out, src/test/regress/expected/olap_plans_optimizer.out, src/test/regress/expected/orca_groupingsets_fallbacks.out, src/test/regress/expected/orca_groupingsets_fallbacks_optimizer.out, src/test/regress/expected/qp_olap_group2_optimizer.out, src/test/regress/greenplum_schedule, src/test/regress/sql/gporca.sql, src/test/regress/sql/orca_groupingsets_fallbacks.sql
This PR mostly contains two parts:
1. Re-enable GROUPING SETS and ROLLUP support in ORCA (a746b5bd4e52aaf7b4e633ec64b5cf2d577a3087)
2. Re-enable GroupingFunc support in ORCA (9582c89158cf2ca66da1bfba41c486dca5766806)
Both features were disabled in ORCA during the Postgres 9.5 merge by commit https://github.com/greenplum-db/gpdb-postgres-merge/commit/3d0e2f2e5c91ba90ee44189a10f9af4561525f27. 
The rest of the commits are house keeping: bug fix, adding FIXME and README, for exiting features in previously released GPDB versions.
Please review individual commits for details.
=> Re-enable GROUP BY GROUPTING SETS/ROLLUP and GroupingFunc support in GPORCA

gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
update the guc reference to include info about the dtx_phase2_retry count guc.
question:  guc_gp.c identifies the min/max as 0/INT_MAX.  per this comment and statement in src/test/isolation2/expected/crash_recovery_dtm.out:
```
-- Set to maximum number of 2PC retries to avoid any failures. Alter
-- system is required to set the GUC and can't be set on session level
-- as session reset happens for every abort retry.
11: alter system set dtx_phase2_retry_count to 1500;
```
does this mean that the max is actually 1500?
=> docs - for the dtx_phase2_retry_count guc

src/backend/utils/adt/ruleutils.c, src/include/catalog/pg_proc.dat
Locks were introduced by #7478 to prevent flaky tests using pg_partitions. But this view currently does not exist, so it's safe
to return to REL_12_STABLE implementation of pg_get_expr().
cc @d
=> Remove locks in pg_get_expr()

src/backend/access/transam/xlog.c, src/backend/utils/misc/guc_gp.c, src/include/access/xlog.h, src/include/utils/unsync_guc_name.h
On master the code for the guc is buggy since PG9.5 merge, and we could
actually use guc wal_keep_segments to complete the similar functionality. This
guc is one of the "DEVELOPER_OPTIONS" so there is no need to document it.
=> Remove guc gp_keep_all_xlog

src/backend/optimizer/plan/createplan.c, src/test/regress/expected/partition_pruning.out, src/test/regress/expected/partition_pruning_optimizer.out, src/test/regress/sql/partition_pruning.sql
This is how it is on master branch.  Without this patch, it is possible to generate a plan such as the following:
```
->  Merge Join
Merge Cond: ((t_left.a = (func(t_right.a))) AND ((t_left.b)::text = (t_right.b)))
->  Sort  t_left
->  Sort  t_right
Sort Key: (func(t_right.a)), t_right.b
->  Partition Selector for t_left
Filter: (func(t_right.a))
->  Broadcast Motion
->  Append
->  Seq Scan on t_right
```
The problem with such a plan is the Sort node needs to generate a new junk attribute representing func(t_rigth.a) by appending an entry to the target list of its child - Partition Selector.  However, the Append node's target list does not contain this junk attribute.  This results in the motion sender sending a tuple with two columns but the receiver thinking that it received a tuple …
=> [6X only] PartitionSelector is not projection capable

src/backend/cdb/cdblegacyhash.c
Following up on 3df1dcbc56cc65a0, we don't have to duplicate the legacy
hash function for text, simply calling it suffices.
No catver bump.
=> Replace copy-paste with a function call

src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
We have a few asserts in the code for bucket merges that are
well-intentioned, but currently trigger for some queries with boundary
conditions that we don't consider a bug. Commenting these out for now
until we have a better solution.
=> Comment out asserts in stats code

gpMgmt/bin/gpcheckresgroupimpl, src/backend/utils/resgroup/resgroup-ops-linux.c
For version 6X or higher, 'cpuset' is a necessary subsystem for resource group.
However, if 'cpu' and 'cpuset' are mounted on the same hierarchy, the cpu usage
will be out of control. So we need a validation on this before we using resource
group.
Co-authored-by: wuchengwen <wcw190496@alibaba-inc.com>
=> [6X backport] Add a validation on the mount hierarchy of 'cpu' and 'cpuset' subsystem

src/backend/gporca/data/dxl/minidump/InferPredicatesForPartSQ.mdp, src/backend/gporca/data/dxl/minidump/InferPredicatesForQuantifiedSQ.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CPropConstraint.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h, src/backend/gporca/libgpopt/src/base/CPropConstraint.cpp, src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp, src/backend/gporca/server/CMakeLists.txt, src/test/regress/expected/subselect_gp_indexes_optimizer.out
To generate inferred predicates for outer refs, we need to pass the
constraints for outer refs to several methods.
Initially NULL, the new argument is set to the constraints of the
current expression when we enter a subquery through a call to
CExpressionPreprocessor::PexprFromConstraintsScalar().
When generating inferred predicates, combine the local equivalence class
for the colref with that of the outer ref at the outer scope. With this
combined equivalence class, search both the current expression's constraints
and those of the outer refs for predicates to infer.
This will help queries such as
select *
from   foo
where  foo.a in (select max(bar.a) from bar where foo.b=bar.b)
and foo.b < 2;
We can now infer a predicate bar.b < 2 inside the subquery. The outer scope
contributes the …
=> Infer predicates from constraints on outer refs

src/backend/gporca/libnaucrates/src/statistics/CBucket.cpp
We have a few asserts in the code for bucket merges that are
well-intentioned, but currently trigger for some queries with boundary
conditions that we don't consider a bug. Commenting these out for now
until we have a better solution.
(cherry picked from commit 361cf02ab0b9a689cfefc49b1a0ed7182797e5e5)
=> Comment out asserts in stats code (#11259)

src/backend/gporca/data/dxl/minidump/InferPredicatesForPartSQ.mdp, src/backend/gporca/data/dxl/minidump/InferPredicatesForQuantifiedSQ.mdp, src/backend/gporca/libgpopt/include/gpopt/base/CPropConstraint.h, src/backend/gporca/libgpopt/include/gpopt/operators/CExpressionPreprocessor.h, src/backend/gporca/libgpopt/src/base/CPropConstraint.cpp, src/backend/gporca/libgpopt/src/operators/CExpressionPreprocessor.cpp, src/backend/gporca/server/CMakeLists.txt
* Pass outer ref constraints to several methods
To generate inferred predicates for outer refs, we need to pass the
constraints for outer refs to methods
and CExpressionPreprocessor::PexprFromConstraints(),
CExpressionPreprocessor::PexprFromConstraintsScalar(), and
CExpressionPreprocessor::PexprScalarPredicates().
Initially NULL, the new argument is set to the constraints of the
current expression when we enter a subquery through a call to
CExpressionPreprocessor::PexprFromConstraintsScalar(). Please
note that this commit has a limitation, it does not handle skip-level
outer refs.
* Infer predicates from constraints on outer refs
When generating inferred predicates, combine the local equivalence class
for the colref with that of the outer ref at the outer scope. With this
combined …
=> Infer predicates from constraints on outer refs (#11175)

src/backend/utils/adt/selfuncs.c, src/test/regress/expected/bitmap_index.out, src/test/regress/expected/bitmap_index_optimizer.out, src/test/regress/expected/gporca.out, src/test/regress/sql/bitmap_index.sql
We create a LOV for each distinct key in bitmap index. And the LOV point
to the bitmap vector pages. Since each bitmap vector has the same length,
although we do compress for the bits, we can assume each distinct
key has the approximately same number of bitmap vector pages(although there
must be some counterexamples). So the indexPages should be:
selectedDistinctValues / numDistinctValues * index->pages.
But the issue is we can't estimate both of the distinct values from stats
through estimate_num_groups since it produces larger estimates. Especially
for selectedDistinctValues.
Image below cases:
1. indexSelectivity also correspond to how may distinct values get selected.
Then the result of genericcostestimate's indexPages will be accurate.
2. indexSelectivity is high but only match a …
=> [6X Backport]Correct cost estimate for bmcostestimate()

src/backend/optimizer/plan/planmain.c, src/backend/optimizer/util/pathnode.c, src/test/isolation2/expected/execute_on_utilitymode.out, src/test/isolation2/isolation2_schedule, src/test/isolation2/sql/execute_on_utilitymode.sql, src/test/regress/expected/join_gp.out, src/test/regress/expected/join_gp_optimizer.out
It's not entirely clear what the behavior should be in utility mode.
With this commit, the EXECUTE ON options are effectively ignored in
utility mode, so the function is executed locally on the node you're
connected to. To achieve that, force Entry locus for the FunctionScan
path in the planner, when in utility mode. This is how other kinds
of scans are planned in utility mode, too.
Without this fix, the join queries added in the test case, with
EXECUTE ON SEGMENTS function, generated a plan with a Motion, even in
utility mode, which failed an assertion in the executor. EXECUTE ON
INITPLAN had similar issues, causing an error in the executor, when it
tried to open a non-existent tuplestore file.
(cherry picked from commit 83178d191e47b8f4f34f5c5e2e46d9d915ff44d7)
=> [6X Backport]Fix execution of functions with EXECUTE ON options in utility mode.

src/backend/storage/file/buffile.c
should check the return value of BufFileSeek
=> Coverity: Unchecked return value

COPYRIGHT, NOTICE, src/test/unit/cmockery/LICENSE.txt, src/test/unit/cmockery/README.md, src/test/unit/cmockery/README.txt
This PR includes a number of changes to open source licensing attribution and copyright topics.
1. ~~Update top-level copyright notices for VMware . Similar to this PR, https://github.com/greenplum-db/gpdb/pull/11209 , the Pivotal copyright statements are being replaced with "VMware, Inc. or its affiliates.".~~ Rebased on commit making the same changes
2. ~~Remove misplaced template at end of LICENSE. The Apache2.0 LICENSE file still contained a template at the bottom of it that does not need to be included.~~ Change after review
3. Provide more details about cmockery . The cmockery library is included in the code base but was lacking more thorough attribution about what it is, where it came from, and it's license.
4. ~~Remove reference to python-subprocess32 . This specific python …
=> Update various top level copyright statements and notices

src/backend/commands/analyze.c, src/test/regress/expected/incremental_analyze.out, src/test/regress/expected/incremental_analyze_optimizer.out, src/test/regress/sql/incremental_analyze.sql
HLL store was happening for all relations that were
RELKIND_RELATION. It should only happen for leaf partition
relations. Fix this by adding a check for relispartition.
=> Fix leaf partition HLL store during ANALYZE

src/backend/executor/execUtils.c, src/test/regress/expected/with.out, src/test/regress/sql/with.sql
For the gang allocation, our current implementation required the first
allocated gang must be the writer gang.
This has several reasons:
- For lock holding, Because of our MPP structure, we assign a LockHolder
for each segment when executing a query. lockHolder is the gang member that
should hold and manage locks for this transaction. On the QEs, it should
normally be the Writer gang member. More details please refer to
lockHolderProcPtr in lock.c.
- For SharedSnapshot among session's gang processes on a particular segment.
During initPostgres(), reader QE will try to lookup the shared slot written
by writer QE. For more details please refer to sharedsnapshot.c.
Normally, the writer slice will be assign writer gang first when iterating the
slice table. But this is not true for writable …
=> [6X Backport]Fix writeable CTE assign reader gang to writer slice.

src/backend/cdb/cdbtm.c
Related issue is here: https://github.com/greenplum-db/gpdb/issues/11309
=> Destruct MyTmGxactLocal->waitGxids with list_free() instead of pfree().

src/backend/access/transam/distributedlog.c, src/include/access/distributedlog.h
Distributed log buffers were hard-coded to 8. Mostly in HTAP
work-load, it is possible to have many distributed log page requests
in flight at one time which could lead to disk access for distributed
log page if the required page is not found in memory. Testing revealed
that we can get the best performance by having 128 distributed log
buffers, more than that it doesn't improve performance.
Hence, seeking inspiration from CLOG buffers, number of distributed
log buffers are also selected based on shared_buffers.
Discussion:
https://groups.google.com/a/greenplum.org/g/gpdb-dev/c/l_iNnfwTF7s/m/Fk-6UVlbAwAJ
=> Pick number of distributed log buffers based on shared_buffers

gpdb-doc/dita/admin_guide/load/topics/g-defining-a-command-based-writable-external-web-table.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_configuration_history.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_distributed_log.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_pgdatabase.xml, gpdb-doc/dita/ref_guide/system_catalogs/gp_transaction_log.xml
command-based writable web external table discussion states that $GP_SEGMENT_ID references the gp_segment_id dbid, when in fact it represents the content id.  update the docs accordingly.
this PR also includes a few edits for some related docs.
=> docs - GP_SEGMENT_ID references content, not dbid

src/backend/storage/file/buffile.c
Function 'ZSTD_initCStream' may fail due to out of memory, ignore the return
value could lead to an error later 'Context should be init first'.
=> Check the return value of 'ZSTD_initCStream'

src/test/regress/expected/.gitignore, src/test/regress/greenplum_schedule, src/test/regress/input/autovacuum-template0-segment.source, src/test/regress/output/autovacuum-template0-segment.source, src/test/regress/sql/.gitignore
This is forward port of test from GPDB6 which was committed as part of
commit e0f598b1d81df45f53c9fca2ebda1adab5188df2.
=> Add test for autovacuum of template0 on segments

gpMgmt/bin/gppylib/commands/base.py
PR #9540 introduces `Incremental recovery/rebalance in parallel`, it
uses WorkerPool to start worker threads. But if error occured inside
run_pg_rewind()'s for loop, cleanup() would be called and all running
workers in the pool would be requested to halt. Unluckily, non-blocking
gpsubprocess.communicate2 would return but leave its returncode None:
> The None value indicates that the process hasn't terminated yet.
After this, inside Worker::run(), logger.debug(self.cmd) would throw
an exception:
> TypeError: %d format: a number is required, not NoneType
Then, logger.debug(self.cmd) again inside its catch, so `addFinishedWorkItem`
would be skipped. Consequently, pool.join() would wait forever in the main
thread.
It is just one use case, WorkerPool may also be used elsewhere.
Fix it by using …
=> Fix possible gprecoverseg stuck

gpMgmt/bin/gppylib/commands/base.py
This is a clean backport of https://github.com/greenplum-db/gpdb/pull/11211
[Test pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_patch_gprecoverseg_stuck)
--- 
PR #9540 introduces `Incremental recovery/rebalance in parallel`, it
uses WorkerPool to start worker threads. But if error occured inside
run_pg_rewind()'s for loop, cleanup() would be called and all running
workers in the pool would be requested to halt. Unluckily, non-blocking
gpsubprocess.communicate2 would return but leave its returncode None:
> The None value indicates that the process hasn't terminated yet.
After this, inside Worker::run(), logger.debug(self.cmd) would throw
an exception:
> TypeError: %d format: a number is required, not NoneType
Then, logger.debug(self.cmd) again inside its catch, so …
=> [6X Backport] Fix possible gprecoverseg stuck

concourse/scripts/common.bash, concourse/scripts/ic_gpdb_resgroup.bash, configure, configure.in, src/Makefile.global.in, src/backend/access/common/reloptions_gp.c, src/backend/access/transam/xloginsert.c, src/backend/access/transam/xlogreader.c, src/backend/catalog/pg_compression.c, src/backend/cdb/cdbsrlz.c, src/backend/mock.mk, src/backend/storage/file/buffile.c, src/backend/storage/file/gp_compress.c, src/backend/utils/misc/guc_gp.c, src/include/pg_config.h.in, src/include/pg_config.h.win32, src/include/storage/gp_compress.h
Use `pkg-config` for detecting and enabling ZSTD
- Replaced `HAVE_LIBZSTD` (artifact of `AC_CHECK_LIB`) with a dedicated macro `USE_ZSTD`
- Use `pkg-config` version requirement, instead of a a manual and error-prone `AC_CHECK_HEADER`
- On system where the headers and library objects are not located in the default search path, simply specify `PKG_CONFIG_PATH` while invoking `configure` or override both `ZSTD_LIBS` and `ZSTD_CFLAGS` -- not that I encourage it, but if you feel compelled to avoid `pkg-config,` this option is available 
Discussion on https://groups.google.com/a/greenplum.org/forum/#!topic/gpdb-dev/Vs5omcqRvZQ
[resolves greenplum-db/gpdb#7381]
FIXME:
=> Use pkg-config for detecting and enabling ZSTD

src/backend/utils/cache/relcache.c
when the table is an external table.
Fix #11244
=> Fix memory leak in GpPolicyFetch() called in RelationBuildDesc()

src/backend/cdb/cdbtm.c
MyTmGxactLocal->waitGxids is a List of gxids, but it's currently destructed with pfree().
This commit changes it to list_free().
(cherry picked from commit 69da6add7d2966f2a107d47da9e963dc9140a44e)
=> [6X Backport] Destruct MyTmGxactLocal->waitGxids with list_free() instead of pfree().

gpMgmt/bin/gpload.py, gpMgmt/bin/gpload_test/gpload2/TEST.py, gpMgmt/bin/gpload_test/gpload2/query44.ans, gpMgmt/bin/gpload_test/gpload2/query45.ans, gpMgmt/bin/gpload_test/gpload2/setup.ans, gpMgmt/bin/gpload_test/gpload2/setup.sql
Fix gpload ' and " in config file input column. Make `'"col"',  "\"col\"", '"col"', "col" `and col in YAML input columns work fine
We just transmit what in the quotations or double quotations into gpdb.
add test case 44
=> fix gpload config file ' and " issue in 6x

gpMgmt/bin/analyzedb
pg_magic_oid.h:
> #define FirstNormalObjectId	16384
16384 is the first normal oid, analyzedb should not skip it.
When running pivotalguru/TPC-H on a fresh Greenplum cluster
inside containers, we met:
```
$ psql
postgres=# select oid,* from pg_namespace;
oid  |      nspname    | nspowner |  nspacl
-------+-----------------+----------+-----------
16384 | tpch            |       10 |
$ analyzedb -d postgres -s tpch --full -a -v
[WARNING]:-There are no tables or partitions to be analyzed. Exiting...
```
Fix: replace `relnamespace > 16384` with `relnamespace >= 16384`
=> analyzedb - include FirstNormalObjectId

gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gppylib/operations/buildMirrorSegments.py, gpMgmt/bin/gppylib/test/unit/test_unit_buildmirrorsegments.py, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Full recovery currently updates the display with progress updates provided by pg_basebackup; this commit does the same for incremental updates which uses pg_rewind.
The same design and implementation is done for both: the recovery command(pg_basebackup or pg_rewind) writes its progress to a log file, and gprecoverseg tails that file over the network to obtain updates.
There is a corresponding 6X PR: https://github.com/greenplum-db/gpdb/pull/11338
=> gprecoverseg incremental status

src/bin/pg_rewind/pg_rewind.c
Master pg_rewind does not use 'initdb -S' to fsync the target data directory
anymore.
This is a master only PR.
=> No need of initdb sanity check in pg_rewind

src/test/isolation2/expected/setup.out, src/test/isolation2/sql/setup.sql
This reduces the isolation2 testing time by ~10+ seconds (total time is 15min+)
in my dev vm.
=> Skip fsync in isolation2 tests that uses pg_basebackup.

src/backend/storage/file/buffile.c
'49116f6d' fix the problem for 'ZSTD_initCStream', should check the value of
'ZSTD_initDStream' as well.
=> Check the return value of 'ZSTD_initDStream'

src/backend/gporca/data/dxl/statistics/Basic-Statistics-Output.xml, src/backend/gporca/data/dxl/statistics/Merge-Output-Numeric.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-E-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-E-MinBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GT-MinBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GTE-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-GTE-MinBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LT-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LTE-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-2-LTE-MinBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-E-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-E-MinBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-GTE-MaxBoundary.xml, src/backend/gporca/data/dxl/statistics/Numeric-Output-LTE-MinBoundary.xml, src/backend/gporca/libgpos/include/gpos/io/IOstream.h, src/backend/gporca/libgpos/src/io/COstream.cpp, src/backend/gporca/libnaucrates/include/naucrates/dxl/xml/CXMLSerializer.h, src/backend/gporca/libnaucrates/src/md/CDXLBucket.cpp, src/test/regress/expected/gporca.out, src/test/regress/expected/gporca_optimizer.out, src/test/regress/sql/gporca.sql
Issue is that string formatter in COstream used plain "%f" which may
lead to truncation of significant digits. By default it keeps 6 digits
after the decimal. This caused Orca to mistakenly identify two
inequivalent statistics with a small precision diff as being identical.
That mistake occasionally led to assertion errors when merging histogram
statistics.
Fix is to preserve the significant bits for double values. The scope of
the change is limited to bucket upper/lower bounds.
=> Fix Orca stream operator<< precision

gpMgmt/bin/gppylib/commands/gp.py, gpMgmt/bin/gppylib/operations/buildMirrorSegments.py, gpMgmt/bin/gppylib/test/unit/test_unit_buildmirrorsegments.py, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/test/behave/mgmt_utils/steps/recoverseg_mgmt_utils.py
Full recovery currently updates the display with progress updates provided by pg_basebackup; this commit does the same for incremental updates which uses pg_rewind.
The same design and implementation is done for both: the recovery command(pg_basebackup or pg_rewind) writes its progress to a log file, and gprecoverseg tails that file over the network to obtain updates.
This is not needed for 5X: 5X uses gpstate to show recovery progress. This is because the 5X database provides direct progress updates using filerep statistics.  6X uses walrep and does not provide the same mechanism.
There is a corresponding 7X PR: https://github.com/greenplum-db/gpdb/pull/11339.
=> 6X: display gprecoverseg incremental status

src/backend/utils/adt/ruleutils.c
Oversight in commit 976b24fb4.
Andreas Seltenreich
Report: <87y448l3ag.fsf@credativ.de>
(cherry picked from commit 8a8c6b53810026641a1e12f60f873a7bd3cea5e3)
=> Fix crash when pg_get_viewdef_name_ext() is passed a non-view relation.

README.macOS.bash
For 7X, add zstd and pkg-config to README.macOS.bash.
=> README.macOS.bash: add zstd and pkg-config

src/backend/optimizer/plan/createplan.c, src/backend/optimizer/plan/planshare.c
The extParam and allParam sets for every Plan node are recursively computed in
SS_finalize_plan(). We do not need to copy them from children when creating
plan nodes.
This removes the GPDB_12_MERGE_FIXME in make_agg().
=> Do not copy extParam/allParam when creating plan nodes

gpMgmt/doc/gpinitstandby_help
Add hba hostname 6x to gpinitstandby help text
=> Add hba hostname 6x to gpinitstandby help text

gpMgmt/doc/gpinitstandby_help
Add --hba-hostnames to the help text of gpinitstandby
=> Add --hba-hostnames to the help text of gpinitstandby

gpAux/gpdemo/demo_cluster.sh
Don't set locals when it's not phton
The issue comes when make a demo cluster on mac os platform which reported by gp-management team. The code before this PR is that it hardcode locale to en_US.utf8 in all platform except photon 3 platform, which cause issues in mac os platform when gpinitsystem, the error is `Unable to locate locale value en_US.utf8 on this host`
have tested on mac os to make a demo cluster, the issue has gone.
Co-authored-by: Brent Doil <bdoil@vmware.com>
Co-authored-by: Shaoqi Bai <bshaoqi@vmware.com>
=> Only update locals on photon3

src/backend/utils/adt/selfuncs.c
=> Mark rte variable assert only in bmcostestimate() to fix warning

src/bin/pg_upgrade/controldata.c
There is no next gxid value in pg_control data in pre-7 version.  We need to
initialize it in those versions. Ideally during upgrade, those distributed logs
should be all zero-paged so there is no worry about distributed log format
change also due to the 64bit gxid work. (I saw a TODO in
DistributedLog_Startup() but that should be thought separately).
=> Fix broken pre7->7 pg_upgrade related to the 64bit gxid work.

src/backend/gpopt/translate/CTranslatorUtils.cpp
Jesse found this memory leak that was introduced in my previous commit
df3ce784285f7d9ceccfa761fd790ece65b65cde.
Adding some notes for how to detect ORCA memory leaks:
Just run ORCA MDP tests should detect memory leaks inside of gporca.
However, the translator code under gpopt is not tested by the MDP tests,
and we by default use GPDB memory contexts in the translator.
One way to detect memory leaks in the ORCA translator code is to set
"optimizer_use_gpdb_allocators=0" in the gpconfig files and run the
relevant queries. By doing that we instead use ORCA memory contexts and
ORCA will be able to detect the memory leaks.
Reported-by: Jesse Zhang <sbjesse@gmail.com>
=> Fix memory leak in ORCA translator CreateGroupingSetsForRollup()

gpMgmt/bin/lib/gp_bash_functions.sh
Rather than hard coding DEFAULT_LOCALE_SETTING to en_US.utf8 on linux, which is not available on all platforms, use locale -a output.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/7X_gpinitsystem_default_locale)
=> gpinitsystem: DEFAULT_LOCALE_SETTING determined by output of locale -a

src/backend/postmaster/pgstat.c, src/test/regress/input/pgstat_qd_tabstat.source, src/test/regress/output/pgstat_qd_tabstat.source
I think we can introduce a template engine to generate regress tests based on the regress test template. The content of regress test template as follow(based on Liquid):
```liquid
select n_tup_ins, n_tup_upd, n_tup_del, n_tup_hot_upd, n_live_tup, n_dead_tup, n_mod_since_analyze from pg_stat_all_tables where relid = 'table_for_truncate_abort'::regclass;
{% if 'replicated' in amit_conf_distby %}
{% comment %}
ORCA can't be used in the replicated table, the update of table_for_iud will not be implemented by delete + insert
{% endcomment %}
1600|301|777|0|777|1124|777
{% else %}
1901|0|1078|0|777|1124|777
{% endif %}
{% if 'replicated' not in amit_conf_distby %}
{% comment %}
ERROR:  PARTITION BY clause cannot be used with DISTRIBUTED REPLICATED clause
So don't do the following test in …
```
=> Fix that pgstat_send_qd_tabstats will report statistics redundantly for Replicated Table.

gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/doc/gprecoverseg_help, src/backend/access/transam/xlog.c
1. For unclean shutdown, need to fsync the whole pg data directory which is time-consuming. Log it in case users want to check the recovery time when recovery is slow.
2. gprecoverseg help page is out of date. Now that it supports progress report for incremental recovery.
=> Small recovery related fixes.

gpAux/gpdemo/demo_cluster.sh
Don't set locale when it's not Photon
- Fix bug in demo_cluster.sh ` [: too many arguments` on Centos
Co-authored-by: Brent Doil <bdoil@vmware.com>
Co-authored-by: Shaoqi Bai <bshaoqi@vmware.com>
=> gpdemo: Only pass locale to gpinitsystem on Photon

src/test/regress/init_file
The following NOTICE is generated by ORCA when it plans a partitioned table
that does not have stats. Although it is a useful messages for the end user, it
causes noise & flaky failures in ICW. This commit ignores these NOTICEs.
HINT:  For non-partitioned tables, run analyze <table_name>(<column_list>). For partitioned tables, run analyze rootpartition <table_name>(<column_list>). See log for columns missing statistics.
NOTICE:  One or more columns in the following table(s) do not have statistics: dml_union_s
=> Disable ORCA's statistics missing NOTICE

gpMgmt/bin/gppylib/gparray.py, gpMgmt/bin/gppylib/operations/Makefile, gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py, gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py, gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py, gpMgmt/test/behave_utils/utils.py
Add a check to gprecoverseg to skip attempting recovery of segments that are down and whose hosts are unreachable.
Also extract previous unreachable host logic from gpstart to avoid redundancy.
Pipeline is [here](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/7X_gprecoverseg_down_host).
=> gprecoverseg: don't recover unreachable segments

gpdb-doc/dita/admin_guide/managing/configure.xml, gpdb-doc/dita/ref_guide/config_params/guc-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_category-list.xml, gpdb-doc/dita/ref_guide/config_params/guc_config.ditamap
add content for guc gp_interconnect_transmit_timeout to the reference guide.
while investigating, i noticed that our docs for gp_interconnect_setup_timeout appeared to be incorrect.  this PR includes a doc changes for that guc as well.
=> docs - add ref info for gp_interconnect_transmit_timeout guc

src/backend/access/external/url_curl.c, src/bin/gpfdist/regress/output/exttab1.source
Reading from gpfdist external table can generate lots of HTTP traffic
in very short time window. This may cause intermittent network issues
resulting in "No route to host" error. Backdown and retry in such
scenario.
Reuse the backdown and retry logic for writable external table as
gp_perform_backoff_and_check_response. Pass read/write specific
part as function pointer(multi_perform_work/easy_perform_work).
It's difficult to reproduce such scenario in an automatic way so
we only manually tested this by setting IP_TTL option of socket to 1.
This will immediately result in TTL exceeded packet that cause the
"No route to host" error.
=> Backdown and retry for "No route to host" in gpfdist ext table

gpMgmt/bin/gppylib/gparray.py, gpMgmt/bin/gppylib/operations/Makefile, gpMgmt/bin/gppylib/operations/detect_unreachable_hosts.py, gpMgmt/bin/gppylib/operations/update_pg_hba_conf.py, gpMgmt/bin/gppylib/programs/clsRecoverSegment.py, gpMgmt/bin/gppylib/test/unit/test_unit_gprecoverseg.py, gpMgmt/bin/gpstart, gpMgmt/test/behave/mgmt_utils/gprecoverseg.feature, gpMgmt/test/behave/mgmt_utils/steps/gpstart.py, gpMgmt/test/behave/mgmt_utils/steps/mgmt_utils.py
A clean 6X backport of https://github.com/greenplum-db/gpdb/pull/11395 
Add a check to gprecoverseg to skip attempting recovery of segments that are down and whose hosts are unreachable.
Also extract previous unreachable host logic from gpstart to avoid redundancy.
[Pipeline](https://dev.ci.gpdb.pivotal.io/teams/main/pipelines/6X_gprecoverseg_down_host)
=> [6X backport] gprecoverseg: don't recover unreachable segments

src/backend/access/aocs/aocsam_handler.c, src/backend/executor/nodeBitmapHeapscan.c, src/include/access/tableam.h
These AOCS specific AMs extract column information from targetList
and the quals that used in the scan. This is an optimization for AOCO
relations to avoid fetch extra columns.
Just remove the FIXMEs.
Also, remove a fixme in aoco_beginscan_extractcolumns. If the query
is `count(*)`, targetlist and qual are null. So no columns are specified.
=> Remove the FIXME label for AOCS specific AM.
